### ISSUE TITLE
conversations don't send or receive messages over a unreliable network connection sometimes (wlan)

### ISSUE THREAD

**Issue by monarc99** [siacs/Conversations#1004]
If i send a message (over jabber server ccc.de), it is normally delivered in seconds. 
But sometimes the message needs 1-2 days to be received. conversations give as status "waiting"
Then i have to stop conversation and restart it to send the message.

Maybe my wlan or dsl connection is not reliable. Or a bug.

greetings

**Comment by iNPUTmice** [comment]
Do you still have the problem with 1.4.3?

If so please post an adb logcat output and specify if you are tolking about encrypted messages.

**Comment by dicer** [comment]
I also have this with OTR encrypted messages. They are stuck in waiting. What works for me, is to end that specific conversation (not the app), select that contact from the list again and open a new conversation. Then sending a new message will also make the old and waiting messages send.
I'll try and get a logcat next time this happens.

**Comment by iNPUTmice** [comment]
too generic. not a real bug report.

what ever problems OP had those are probably be solved by using stream management and OMEMO
