### ISSUE TITLE
Last seen info in contact details -> XEP-0012?

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1008]
Following on the issue #392 the last seen info is really confusing. I've just gotten a message from a contact written in a MUC, the contact's last seen info shows: last seen: 18 hours ago...
What is about implementing XEP-0012: Last Activity?

**Comment by iNPUTmice** [comment]
> I've just gotten a message from a contact written in a MUC, the contact's last seen info shows: last seen: 18 hours ago...

this has been fixed just now.

> What is about implementing XEP-0012: Last Activity?

I'd still rather hide the display.
