### ISSUE TITLE
Cannot connect using different XMPP-Domain from Server-Host

### ISSUE THREAD

**Issue by Black-Fry** [siacs/Conversations#1009]
Hi, i am serving a private ejabberd-instance whose jabber-domain-name differs from the host-name of the server. unfortunately - during installation of the conversations-app - i cannot set any option that lets me set my <nick@my-xmpp.com> but initiate  a server connection towards <sub.dyndns-account.com>.
All i am receiving is a connection error when my conversations-app tries to set up a connection to either <nick@my-xmpp.com> or <sub.dyndns-account.com>. Which is no surprise as <my-xmpp.com> is not routed into the internet - it is accessible via some portforwarding rules within a router.

My Provider does not allow changing SRV-Records. So how am I able to use the Conversations-App with my private ejabberd-Server?

Best Regards!

**Comment by iNPUTmice** [comment]
please read #962 especially the comments about how to set up bind.
