### ISSUE TITLE
Led color...

### ISSUE THREAD

**Issue by QuentinC** [siacs/Conversations#1014]
Hi,

I've built your last commit.
The led color however doesn't apperas as green as wanted.
The color is like a mix between a green and white...

If I set the color to the full-green (00FF00) it's many more next to the conversation color...

I've tried to take pictures of this, but my camera don't represents colors correctly...

I've tried this on two xperia devices (Z3 compact and ZR) and the result was the same...

I don't know if this is the same for other devices, but I believe that the "full-green" would be better !

Thanks ! (I can make a commit for that if you want)

**Comment by iNPUTmice** [comment]
I merged your PR. thanks
