### ISSUE TITLE
App Not working in Eclipse

### ISSUE THREAD

**Issue by romaasnani1986** [siacs/Conversations#1016]
Hello There,

I am new to android and trying to create a chat application. That's I use this app but its not running. Initially it gives error of two types. Can Anyone please help me. Thank you

03-05 03:44:19.256: E/AndroidRuntime(2347): FATAL EXCEPTION: main
03-05 03:44:19.256: E/AndroidRuntime(2347): Process: eu.siacs.conversations, PID: 2347
03-05 03:44:19.256: E/AndroidRuntime(2347): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{eu.siacs.conversations/eu.siacs.conversations.ui.ConversationActivity}: java.lang.ClassNotFoundException: Didn't find class "eu.siacs.conversations.ui.ConversationActivity" on path: DexPathList[[zip file "/data/app/eu.siacs.conversations-1.apk"],nativeLibraryDirectories=[/data/app-lib/eu.siacs.conversations-1, /system/lib]]
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2121)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at android.os.Looper.loop(Looper.java:136)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at dalvik.system.NativeStart.main(Native Method)
03-05 03:44:19.256: E/AndroidRuntime(2347): Caused by: java.lang.ClassNotFoundException: Didn't find class "eu.siacs.conversations.ui.ConversationActivity" on path: DexPathList[[zip file "/data/app/eu.siacs.conversations-1.apk"],nativeLibraryDirectories=[/data/app-lib/eu.siacs.conversations-1, /system/lib]]
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2112)
03-05 03:44:19.256: E/AndroidRuntime(2347): 	... 11 more

**Comment by iNPUTmice** [comment]
Conversations removed support for the ant build system a few releases ago and is using gradle now. Use Android Studio is you want a now afford solution or re-add ant support yourself if you want to stick with eclipse.
For further questions please use our conference since this is a bug tracker and not a forum for general questions.

**Comment by romaasnani1986** [comment]
Thank you Sir, I will use conference for further queries.
