### ISSUE TITLE
Trouble connecting to jabberd2 server

### ISSUE THREAD

**Issue by rsenger2** [siacs/Conversations#1017]
I am having trouble connecting to a jabberd2 (2.2.17) server running on Debian / LMDE. Conversations fails to connect several times until it finally (not really...) succeeds, and the c2s.log shows these messages:

Fri Mar  6 00:00:16 2015 [notice] [11] [2001:000:0000:303:f164:65b9:e8f7:f6d6, port=54101] connect
Fri Mar  6 00:00:18 2015 [notice] [11] PLAIN authentication succeeded: rsenger@abc-def.net 2001:000:0000:303:f164:65b9:e8f7:f6d6:54101 TLS
Fri Mar  6 00:00:18 2015 [notice] [11] bound: jid=rsenger@abc-def.net/gt-i8190
Fri Mar  6 00:00:18 2015 [notice] [11] packet sent before session start, closing stream
Fri Mar  6 00:00:18 2015 [notice] [11] [2001:000:0000:303:f164:65b9:e8f7:f6d6, port=54101] disconnect jid=rsenger@abc-def.net/gt-i8190, packets: 2
Fri Mar  6 00:00:18 2015 [notice] session 11 does not exist; telling sm to close

(ip address and domain name altered for security reasons)

This repeats several times, until the connection succeeds. After a short time, the connection is lost again, and the above behaviour shows up again until the connection is reestablished. After this happens, the peer client (Pidgin on Linux) complains that there are multiple sessions for the Conversations user. Every time Conversations reconnects, a new session appears, after 15 minutes or so up to eight. Most messages sent from Pidgin to Conversations get lost.

I googled "packet sent before session start, closing stream" error message, and found some older threads saying that this is caused by a client side protocol violation, which in at least one case was fixed in newer client version.

I do not have any problems connecting to this server with Pidgin/Linux, Pidgin/Windows, OS X and Xabber clients.

I can offer help for debugging is desired,

**Comment by iNPUTmice** [comment]
For later reference the pidgin issue that explains in detail what is happening: https://developer.pidgin.im/ticket/178

will fix this. but not today.

**Comment by iNPUTmice** [comment]
Is there any chance I could get a test account on that server? It's a bit difficult to find any jabberd2 servers these days.

**Comment by rsenger2** [comment]
Sure, I've enabled registration, and set up a simple webpage for you to view server logs.

Just send me an email to rsvfrdrst@microscopium.de, so that I can provide you with the server address and the http login credentials.
