### ISSUE TITLE
Featue request: Android notification on undeliverable messages

### ISSUE THREAD

**Issue by interruptor** [siacs/Conversations#1019]
It would be nice if conversations generates an android notification when the server states a message could not be delivered after timeout. Then you would notice a undeliverable message without checking if all of your dialog partners received all messages.

**Comment by dejIO** [comment]
Can this feature be easily implemented? For some reason many of my messages aren't sent lately, and it's quite annoying when you have to wonder why it's taking so long for someone to reply when it's only that they didn't receive the message.

**Comment by dicer** [comment]
I agree. I also have this problem with some contacts. Other communication apps like the standard sms app and k9mail will notify you, when a message could not be delivered. So this would be really helpful.
