### ISSUE TITLE
file transfer desktop compatibility

### ISSUE THREAD

**Issue by BigButt** [siacs/Conversations#102]
Was wondering about the new feature if there are any desktop clients (preferably Linux) I can use for file exchange?

**Comment by simontretter** [comment]
Any luck with prosody and mod_proxy65?

**Comment by JKingweb** [comment]
Prosody works fine.  I sent files back and forth between Conversations and Gajim (and Gajim and Adium, not that that is relevant) today.  The prosody documentation mentions that the host must (bold, bold, bold) have an A record in DNS; this appears to be very important.

**Comment by iNPUTmice** [comment]
Since 1.4 Conversations can send and receive files with gajim

**Comment by singpolyma** [comment]
Gajim 0.16.1 on Ubuntu sending to Conversations 1.4.3 it seems to work all the way through, and Gajim even reports success, but then Gajim reports that the other side cancelled the transfer (right after it reports success) and the recipient gets the "deleted" message.

**Comment by shtrom** [comment]
> Gajim does not send a proxy activation which conversations is waiting for.
> And no success tag.
> I another case were no proxy was involved gajim simply did not sent any date over the successfully established connection ...
> Gajim also does not send a success info on completion

For reference, this bug has been reported on the Gajim side [0]. I can confirm that Conversations 1.6.0 -> Gajim 0.16.3 works, but not the other way round.

[0] https://trac.gajim.org/ticket/7824

**Comment by seyedhosseinfakhr** [comment]
Hi
 how to change android client conversation to start use?

**Comment by marmistrz** [comment]
Confirming, sending files Gajim -> Conversations doesn't work. Gajim reports that the other party has cancelled the transfer, which is not the case.

**Comment by licaon-kter** [comment]
What Gajim version? Conversations version? App source? Server?

**Comment by marmistrz** [comment]
Gajim 0.16.7 from Arch Linux repos, Conversations 1.17.1 from F-Droid. Server: wiuwiu.de -> neko.im.

I will test it using 1.18.x today in the evening.

**Comment by ccaapton** [comment]
I failed to send jingle file from Gajim/windows 1.0.0 to Conversations 2.2.3

@iNPUTmice `Gajim does not send a proxy activation which conversations is waiting for`
I checked the logs of gajim and conversations, and conversation is waiting something for a long time before checking the candidates from gajim, maybe it is waiting for the "proxy activation" as you mentioned. But I went through the XEP-0234, and there is no mention of compulsory "proxy activation" in the standard.

**Comment by iNPUTmice** [comment]
@ccaapton I haven’t looked into this issue in years since HTTP Upload is the prefered technology these days so I don’t know if that bug still exists or if this is something else causing this.
However proxy activation is desrcibed in [XEP-0260](https://xmpp.org/extensions/xep-0260.html#complete)

**Comment by ccaapton** [comment]
@iNPUTmice Even in XEP-0260, the "proxy activation" is still optional.

**Comment by marmistrz** [comment]
@iNPUTmice while HTTP Upload is preferred, it can't be used for sending bigger files, e.g. a 40MB video.

**Comment by iNPUTmice** [comment]
@ccaapton there is a lot of stuff in Jingle Filetransfer that is *optional* on paper but absolutetly required for the protocol to work properly. That’s why the protocol hasn’t been advanced yet. See my postings on the standards mailinglist if you want to argue the technical details of the protocol.

Also you are wrong the standard says

> If the nominated candidate is of the "proxy" type, then the peer has no way to know when it can send data. Therefore the party that offered the nominated candidate MUST do two things...

@marmistrz sure. I’m just saying that this is the reason that I haven’t looked at the jingle stack in years. I’m not preventing anyone from fixing Gajim or Conversations.

**Comment by ccaapton** [comment]
@iNPUTmice I'm using Gajim and Conversations in the same LAN, so server-proxy is not a good idea.

About what the standard says,
> If the nominated candidate is of the "proxy" type, 

"Nominated" means that the initiator happened to offered the choice, and the receiver make the choice when "proxy" is available. The offer itself could still be valid even there is no proxy option, and the "nominated candidate" would just be another direct p2p candidate.

With proper implementation, jingle file transfer is much more attractive than HTTP upload especially when ipv6 is gradually going mainstream. HTTP-upload cost server space, and double the time required(upload and download can not go concurrently)

**Comment by iNPUTmice** [comment]
Conversations obviously only awaits proxy activation if a proxy is used.
Not on direct connections. 🙄
If it doesn't work on direct connections there might be something else.
Feel free to debug and fix.
