### ISSUE TITLE
OTR keys

### ISSUE THREAD

**Issue by davidgfnet** [siacs/Conversations#1020]
Hello,
Is it possible to import/export OTR keys to/from Conversations?
Is it possible to encrypt the keys using a PIN/password? It would be really nice, just in case you lose your phone.
Thanks!!

**Comment by LogicalDash** [comment]
I think this is an important feature. Without being able to import my desktop OTR key, I can't use carbons together with OTR -- or rather, messages encrypted for my desktop key are gibberish on mobile, though they still generate gibberish notifications.

**Comment by strb** [comment]
> messages encrypted for my desktop key are gibberish on mobile

This will still be the case if you have the same key on both devices, due to PFS. The only advantage of having the same key on both devices is that your contacts don't have to verify a second key. (for more discussion, see #78)

**Comment by davidgfnet** [comment]
Interesting. Thanks for the heads up!
Anyway the second question wasn't answered, was it? I'd like to have my OTR key encrypted in flash.
