### ISSUE TITLE
Duplicate MUC message on writing first message 

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1024]
I've noticed that the first message after creating a new MUC is a duplicate one. You can reproduce it. Just create a new conference, invite somebody and write a massage, it will look like that. 
![2015-03-08_10-35-44_vv2bj6r5uohz](https://cloud.githubusercontent.com/assets/3350754/6551327/f34cbeb4-c636-11e4-9f1e-27a87a4914d8.jpg)

**Comment by kriztan** [comment]
it seems working correctly now.
closing this

**Comment by kriztan** [comment]
It doesn't work. It's has something to do with mam. Yesterday mam wasn't working on prosody trunk build 564 because of an error in the code. So this issue seems to be solved. After updating to trunk 565 the duplicate on the first message arrives again.

**Comment by iNPUTmice** [comment]
This should be fixed in 1.4.4-beta2

**Comment by kriztan** [comment]
fixed
