### ISSUE TITLE
Share information about a Contact

### ISSUE THREAD

**Issue by kruks23** [siacs/Conversations#1025]
Hello,

Is very common to share a phone or email from a third person when you are chatting with one of your contacts.
It would be nice if you can share this information like other im's do selecting a contact from your android Contact application.

Thank you.

**Comment by iNPUTmice** [comment]
you can share the contact the other way round by opening the address book and selecting share with. conversions will listen to those intents. at some point it just doesn't make sense any more to clutter that menu with each and every file type some user might like to share at some point.
(come to think of it maybe I should remove the attach file option...)
