### ISSUE TITLE
axolotl support

### ISSUE THREAD

**Issue by geohuhn23** [siacs/Conversations#1026]
Hi guys, great work is going on here. 
I read about the announcement to support axolotl encryption protocol at the summer of code 2015 and wanted to know if it's coming soon

**Comment by simontretter** [comment]
Do you mean this? 
https://github.com/trevp/axolotl/wiki

**Comment by iNPUTmice** [comment]
op is referencing this http://wiki.xmpp.org/web/Summer_of_Code_2015#axolotl_support_for_Conversations


and well... gsoc has not happened yet...

if you are interested in implementing this or know someone speak up

otherwise it's pretty pointless to spam an issue tracker with eta questions.

**Comment by geohuhn23** [comment]
Thanks for the information, sorry if I bothered you.  
Unfortunately I cannot contribute
