### ISSUE TITLE
Distinguish between domain and server, like Pidgin does

### ISSUE THREAD

**Issue by tommyd3mdi** [siacs/Conversations#1028]
Because of https://code.google.com/p/android/issues/detail?id=79504, I currently cannot specify my private DNS name of my OpenFire server on Android L (5.0.1), which means I enter "[name]@[ip-address]" in the login field when adding a new account.

This works all fine, except that the list of available chats isn't populated by default, because "conference.[ip-address]" is of course invalid.

Pidgin does distinguish between domain and connecting server (and even allows me to specify a non-standard port), so it would be great if Conversations could get some "advanced" part in the login screen as well where I could enter these information.

**Comment by andersruneson** [comment]
This
https://github.com/siacs/Conversations/#where-can-i-set-up-a-custom-hostname--port
This https://github.com/siacs/Conversations/issues/962

?

**Comment by tommyd3mdi** [comment]
I see there is a lengthy discussion about this topic. While I generally agree on the use of SRV records, the above stated Android problem cannot be solved with this.

Background is that the DNS that is send by the DHCP response isn't properly propagated to the system on Lollipop (5.0, 5.0.1, 5.0.2, etc.) and as thus the DNS setup in our company Wifi is all fine, just Android 5 cannot resolve the hostname because it only ever queries its own DNS servers (8.8.8.8 and 8.8.4.4).

My 5 ct to the discussion above: If there are many people who demand this feature over and over again, for various reasons, just implement the darn little UI for that, instead of wasting resources any further by discussing the topic to death...

**Comment by iNPUTmice** [comment]
why doesn't your Android query your private DNS server? this seems like the real problem here...

**Comment by tommyd3mdi** [comment]
Yep, this is the real problem, but as I said, as a "customer" I'd still appreciate if the account dialog would get some "advanced" configuration options.
