### ISSUE TITLE
Re-send Image audio or any file option button

### ISSUE THREAD

**Issue by modmonkey** [siacs/Conversations#1029]
There is no option for resend Attachment when files are not receive

**Comment by iNPUTmice** [comment]
Have you tried long pressing a failed message? Not sure if this is what you are talking about.

**Comment by modmonkey** [comment]
but these options are hidden for new user please add some visual button and also add feature forward message

**Comment by Lesik** [comment]
Messengers like WhatsApp and Telegram (last time I used them) worked exactly the same way. Not very difficult to figure out to long press it in my opinion.

**Comment by felipedau** [comment]
I believe @modmonkey wants something like Facebook Messenger does:

![messenger](https://cloud.githubusercontent.com/assets/4574368/6690189/bbdc53be-cc9d-11e4-98a2-72eb54f8de50.jpg)

Tapping on the exclamation mark will ask if you want to resend it.

However, Conversations displays a green tick when the message is received (if supported), which in my opinion is enough:

![conversations](https://cloud.githubusercontent.com/assets/4574368/6690069/d8a8c33e-cc9c-11e4-983a-79945beb90bd.jpg)

If it does not have the tick, then it might have not been delivered. *This option is under the 'Expert options' though.* It could be enabled by default.

It is really close to what WhatsApp does, which works nicely.

**Comment by kriztan** [comment]
With this green tick you are right @felipedau, but if your contact has disabled "Confirm Messages" the tick isn't displayed. So you don't know if the message was received or not.

**Comment by felipedau** [comment]
You are right @kriztan.

Actually Facebook's notification is displayed when the message was not sent to the server. Not the person.

Then I guess something could be displayed (exactly where the green tick is) to tell the user something went wrong and intuitively he/she will tap on the message to resend. It would do what @modmonkey wants and would not be as exaggerated as Facebook's (in my opinion).

*Ps: What I meant by enabling the confirmation by default is only the one that requests the confirmation, not the one that confirms, as @kriztan mentioned. By the way, how does the request work?*
