### ISSUE TITLE
receives messages from another session

### ISSUE THREAD

**Issue by sedrubal** [siacs/Conversations#1030]
I'm not sure, if you mentioned this already in #951.

Since Version `1.0.3 (F-Droid)` I think Conversations receives every message sent to me, even if it is sent to another client. Not sure if this only happenes when OTR is enabled. When OTR is enabled, the mobile also wakes up and Conversations displays a notification on each "OTR backgound message".

**Comment by iNPUTmice** [comment]
This is called carbon messages and is a feature. And this has been in Conversations since forever and not just since 1.0.3 - Maybe this got enabled on your server recently.
For OTR messages the sending client should disable carbon copies on a per message basis.

**Comment by sedrubal** [comment]
ah ok, thank you.
