### ISSUE TITLE
2 things about /me

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#1031]
1. I'd like to change the name showed. In clients like Telepathy, I can change my username and it show «Alberto» instead of «aru» like does Conversations. It can be done including /nick, as pidgin did.
2. Why not to add another command like /you (to show the other username in the conversation) or /all (to call everyone in a room)? I don't know if this is possible, but, if Pidgin has added /nick, I think Conversations could add these commands easily.

**Comment by TameOfGroans** [comment]
1
Why not register an additional JID? 

2
What shows atop the UI amid conversation?

**Comment by moshpirit** [comment]
1. I don't want to create and add a lot of different accounts to every MUC conversation
2. Sorry I didn't understand you. What's the atop?

**Comment by iNPUTmice** [comment]
merged into #1779
