### ISSUE TITLE
Feature request: Background update frequency

### ISSUE THREAD

**Issue by Greezael** [siacs/Conversations#1032]
I don't use XMPP that much, so lowering the frequency of background syncs would be nice a nice way to spare some battery and leave the app running always.

I don't know if much more explanation is needed. I'm speaking about the typical "check for updates every x minutes".

Oh, and thank you for your work guys. You are breathing new life into the XMPP protocol with this app :)

**Comment by iNPUTmice** [comment]
There is already a thread talking about something like this (might actually be a bit harder to find so I don't blame you for now searching for this before (I think it was part of the MAM issue))
I said it in there and I will say this again in here. Conversations with stream managment and CSI already has a very low impact on battery life. There won't be any further optimizations especial not in the direction of connecting every x minutes unless someone comes up with a test tool that quantifies any optimizations.
It's kinda the point of instant messaging to be instant. If you want something you only check in regular intervals you are probably better of with email.

**Comment by Greezael** [comment]
Well, I was using WakeLock Detector and Conversation was keeping my phone awake about 4 times more than Whatsapp (yeah, some friends refuse to migrate). But I'm looking at the statistics again and it's true, it's not a significant drain. Both of them are behaving light on the battery, even if the wake count seems a little bit high compared to the rest of the system.

In my defense I'll say that I'm running a very low end smartphone, stripped down of everything unnecessary, so any little activity will go quickly to the top of the consumption lists xD


Ok, thank you for the fast response.
