### ISSUE TITLE
Avatar Published But Not Shown In user's chat history

### ISSUE THREAD

**Issue by modmonkey** [siacs/Conversations#1034]
I am try to publish avatar Conversations
toast says "your avatar has been published!"
But avatar not shown in chat history only Alphabetic avatar display I am using ejabberd XMPP Server

**Comment by Lykos153** [comment]
Same here with prosody 0.9

**Comment by iNPUTmice** [comment]
can not reproduce. probably a server bug. try the latest version of ejabberd
