### ISSUE TITLE
add ability to delete messages

### ISSUE THREAD

**Issue by kas70** [siacs/Conversations#1037]

**Comment by Lesik** [comment]
I believe XMPP doesn't supports this. Once the message is delivered to the recipient, it's there. Only local deletion would be possible.

**Comment by jkufner** [comment]
Also deletion from server-side message archive could be possible. But
nothing of this will ever affect recipient's client.

**Comment by kas70** [comment]
i'd recommend client-side deletion from the conversation history. this was principially what i thought of.

Am 17. März 2015 15:33:06 MEZ, schrieb Josef Kufner <notifications@github.com>:

**Comment by jkufner** [comment]
In that case there must be warning, that it is local deletion only and
once sent message will be delivered anyway.

**Comment by iNPUTmice** [comment]
You can clear out all messages in a Conversations by choosing 'Clear history' (which has a clear warning message)
I don't really see the point in being able to delete single messages. (This has been discussed before by the way)
