### ISSUE TITLE
Messages sent to offline contacts are not sent when contact comes online

### ISSUE THREAD

**Issue by Natanji** [siacs/Conversations#1038]
I am not sure why this happens, but I have experienced it multiple times now. I understand that the intended behaviour is for messages sent via the "grey sent button" to be cached and then sent by Conversations once my contact comes online. But they never reach my contact - and no error message indicating that the message wasn't sent is displayed to me. That's a very bad UX, especially in times of WhatsApp where I can be sure that no matter whether my contact is online or not, my message will be sent as soon as possible.

**Comment by SamWhited** [comment]
> I understand that the intended behaviour is for messages sent via the "grey sent button" to be cached and then sent by Conversations once my contact comes online.

This is not correct. Messages sent while your contact are offline are just sent normally. It's up to your server to hold them and deliver them when the contact is available.

**Comment by Natanji** [comment]
Well, seems like my server does not support this. Can we query whether the corresponding XEP is supported by the server, and disable the "sending" button (or display an error message), or something in this case? Users probably do not know which features their server supports, so for the sake of UX we should handle this ourselves.

**Comment by iNPUTmice** [comment]
Are we talking about unencrypted messages? Do the messages get marked as send? Or do they get stuck at waiting.
If you are sending messages to a server that doesn't support offline storage the messages should get you an error.

**Comment by Natanji** [comment]
Yes, this happens with unencrypted messages. I'm not sure what you mean by "stuck and waiting" - the messages appear exactly the same way as always when I am writing to someone who doesn't support XMPP Receipts. Of course when I know a certain contact always has Receipts enabled, then I can see that the message was not received because of a missing receipt as indicated by the green tick.

I am not getting any error message at all.

**Comment by iNPUTmice** [comment]
The recipients server should either store the messages into offline storage or return them to the sender and have Conversations mark the message as *delivery failed*.
Last time I checked this it worked. But currently I'm not having contacts which servers do not support this. Do you know what server your contact is using?

**Comment by amo13** [comment]
Same problem here. Both me and my friend are using the dukgo.com server. Unencrypted, no error message.
Maybe there is a way for the app to check the availability of this feature on the server and inform the user? If possible, this could be done together with other server-feature-checks with the results showing in the account details below JID&PW.

**Comment by BrianBlade** [comment]
I just tested the dukgo.com server and it **does support** offline messages. That is, when a `client@dukgo.com` is logged out any message will be stored and delivered after the next login of that client. The dukgo.com server **does not support** stream management however, so I assume thats perhaps the issue @amo13 is facing?

Personally, I dont see how a server could be of any use without returning an error for messages to offline clients but In theory it should be possible to query a server's offline capabilities by means of the `<feature var=’msgoffline’/>` disco item ([XEP-160](http://xmpp.org/extensions/xep-0160.pdf)).

**Comment by hussamT** [comment]
Same issue here on facebook/gmail. Messages sent to me while I was offline don't show when I connect to the internet.

**Comment by iNPUTmice** [comment]
closing because this is a server problem. Please report the bug to your server ops or devs.
