### ISSUE TITLE
Conversations started new sessions...

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1046]
Some of my contacts has really bad internet connections so that the connection between Conversations and prosody where lost very often. For that facts Conversations does not always resume an existing session and opens a new one like this nick@server.de/mobile.randomstring
Sometimes there where 6 open sessions at the same time and the user gets almost all messages (own and received messages) multiple times.
All are using Conversations 1.1.0 and are connected to the same server running prosody-trunk with inter alia mod_mam, mod_offline, mod_smacks.

**Comment by iNPUTmice** [comment]
This has hopefully been addressed by f25a82461007f43c23960720d6d94d2db5c8c7f7
Please wait for 1.2.0 and report back if the problem still exists.

**Comment by kriztan** [comment]
It seems to be solved with 1.2.0
Thanks
