### ISSUE TITLE
Add option to view received and sent media

### ISSUE THREAD

**Issue by Lykos153** [siacs/Conversations#1047]
It would be great if one could easily access media that was sent within a conversation. An alternative would be to create per-user subfolders for received and sent media.

**Comment by TameOfGroans** [comment]
does your native gallery app not have a partition for conversation (images or videos)?

**Comment by Lykos153** [comment]
Yes, it does, but not per-user. I'd like to be able to view all media that
has been sent to or received from a specific user - and not all media that
has been sent via Conversations in general.

For example, often I remember somebody sent me a picture some weeks ago.
Then, it wouldn't be hard to find it by scrolling through this user's
pictures, but if you have a lot of contacts, it can be a pain to scroll
through everything that has been shared in this time. And no - I could not
have saved it earlier. Sometimes you don't expect a file to be needed later.

Or - sometimes it happens that you are sitting next to a friend and somehow
you come to talk about a picture you recently shared. And while scrolling
through the recent media you don't necessarily want him to see all the
stuff you shared with other persons.

does your native gallery app not have a partition for conversation (images
or videos)?

—
Reply to this email directly or view it on GitHub
<https://github.com/siacs/Conversations/issues/1047#issuecomment-84520417>.

**Comment by tigre-bleu** [comment]
I agree that saving the picture in a seperate folder would be the minimum. You do not want your grand-mother to see your girlfriend in the hot tub while you show her the pictures of your holiday :-)

The way whatsapp does is imho very good as it is possible to "scroll" pictures from a contact/group from within the conversation.

**Comment by Lykos153** [comment]
#1540 would be a big step in the right direction

**Comment by therob84** [comment]
Are there any work going on in this matter (also same question for in #1540 and #2285)?
I find it is way more an important feature than nice new emojis...
Anywhere I can help in beta testing?

**Comment by unicorntaco** [comment]
And an option to be not-indexed by the system
https://github.com/siacs/Conversations/issues/3169

**Comment by licaon-kter** [comment]
:+1: Work In Progress: https://github.com/siacs/Conversations/commit/7a0c53aa71c7f405d5bd9b838a90f69ead9a021a

**Comment by iNPUTmice** [comment]
Done in Conversations 2.3.0
