### ISSUE TITLE
Move menu options to contact/conference details page

### ISSUE THREAD

**Issue by plsng** [siacs/Conversations#1049]
Several menu options for conversations seem to me like they aren't used enough to warrant being accessible from (and thereby taking up space in) the menu. I'm talking about:
- Invite contact
- Clear history
- End this conversation
- Disable notifications

Inviting contacts to a conversation is only done once. Clearing history is a bit strange to have as a main menu option and is also only done once. Ending a conversation is only done once and really doesn't need to be a main menu option. I suppose disabling notifications can be done more than once, but I still don't think it belongs in that menu.

Another reason contra these four is that they are all 'switches', whereas the other two/three menu options (Contact details, Manage accounts and Settings) take you to different pages in the application, and a menu with two different kinds of options is weird.

**Comment by iNPUTmice** [comment]
While the menu is definitely too crowded your solution doesn't work either because all the actions you are trying to move away are actions specific to a conversation and not to a contact and should belong to the conversation and not to the contact details.

**Comment by plsng** [comment]
You can't have multiple conversations with the same contact (on the same account), can you? If so I don't really see why it wouldn't work.

**Comment by andersruneson** [comment]
Where do you place "end conversation" for a muc?

**Comment by plsng** [comment]
Somewhere on the page that lists all participants, I suppose. It even makes more sense, at least to me: you see everyone in the MUC, including yourself, and you no longer want to participate in the MUC, so you remove yourself from the list.
