### ISSUE TITLE
(re) force verification, challenge response

### ISSUE THREAD

**Issue by TameOfGroans** [siacs/Conversations#1053]
both using 1.2.0-beta 

both clients identically configured, including: force end2end encryption,  do not save encrypted. 

conversations only initiated verification between Conversations and ChatSecure.

**Comment by iNPUTmice** [comment]
please provide detailed steps to reproduce, result and expected result since I don't really know what you mean

**Comment by iNPUTmice** [comment]
no reaction from op. closing
