### ISSUE TITLE
avatar publish, offer to resize before upload

### ISSUE THREAD

**Issue by TameOfGroans** [siacs/Conversations#1054]
would it be prudent to facilitate avatar downsizing? either a ui suggestion or invoking am editor.

**Comment by iNPUTmice** [comment]
the resolution has been chosen for a reason (not be pixilated on devices with high dpi)

**Comment by TameOfGroans** [comment]
should a user select a > 3 mega pixel image from her respective gallery does conversation attempt to publish avatar as is?
