### ISSUE TITLE
Syncronize roster with contacts

### ISSUE THREAD

**Issue by sim6** [siacs/Conversations#1057]
Firstly, thanks for your work.

Please could you add support to syncronize the roster (contacts of Conversations) with the phone (android) contacts?

Thanks again.

**Comment by iNPUTmice** [comment]
duplicate.

**Comment by sim6** [comment]
I'm sorry. I cannot found the first issue.

**Comment by iNPUTmice** [comment]
#46

**Comment by sim6** [comment]
Oh! Thanks.
