### ISSUE TITLE
Send pictures from Android5.0 to 4.4 not working

### ISSUE THREAD

**Issue by hschraep** [siacs/Conversations#1058]
If i send pictures from Android 5.0.2 to Android 4.4 the 4.4 user get the messages: picture deleted, and the 5.0.2 user: could not be deliverd. But the 4.4 user could send pictures to 5.0 users. Also a 5.0 user to a 5.0 user. I have this tesed with the last version of conversations 1.2.0-beta on both devices. Could you please have a look? Rgds

**Comment by iNPUTmice** [comment]
works fine for me. please provide detailed steps to reproduce. (are you using the share with button in your gallery or are you using take picture or choose picture) and name the involved devices.

**Comment by hschraep** [comment]
Hello, I used the internal conversations button to choose the picture. My device is the nexus4 with CyanogenMod installed 5.0.2. The other side was a Samsung galaxy plus also with cyanogenmod installed and a Samsung galaxy s4 with original rom from the vendor both with android 4.4.
Am 22.03.2015 19:31 schrieb Daniel Gultsch <notifications@github.com>:works fine for me. please provide detailed steps to reproduce. (are you using the share with button in your gallery or are you using take picture or choose picture) and name the involved devices.

**Comment by hschraep** [comment]
Also both devices counts until 100% but then comes the messages "could not deliver" on the 5.0 side and "picture deleted" on 4.4 side. Hope this helps to find the problem.

**Comment by hschraep** [comment]
Hello figured out thats it only happend if i use otr encryption. Without there is no problem. Have also try to deleted the keys on both sides and verified it new on both sides. But the problem stays. But it is only the way from android 5.0 to 4.4 the other way is working with otr encryption.

**Comment by kahlb** [comment]
Had this issue too, enabling mod_proxy65 in my ejabberd solved this issue for me.

**Comment by hschraep** [comment]
Proxy65 is is enabled within prosody config.  But why is picture sending via otr possible from android 4.4 to 5.0 but not vice verse?

**Comment by hschraep** [comment]
The proxy was enabled but not right configured. :-!  So now with the right config it works perfect. Here the config from the prosody server I used:
Component "proxy.jabber.myserver.de" "proxy65"
        proxy65_address = "proxyjabber.myserver.de"
        proxy65_interfaces = { "192.168.1.45" }

The issue could be closed. Thanks
