### ISSUE TITLE
Voice over IP (Jingle / Opus Codec)

### ISSUE THREAD

**Issue by DoM1niC** [siacs/Conversations#1059]
Hey, 

A Call encryption with SRTP and ZRTP for XMPP would be nice to use the Jingle Protocoll 4 Voip Calls.

The Opus Codes is open source and the Implantation should be possible. Currently a lot of my friends use Conversation and a simple Call function would like a dream... :)

**Comment by iNPUTmice** [comment]
not in the scope of Conversations right now

**Comment by genofire** [comment]
It would be very nice, if you would open it again and put it in a milestone for later.
I would really like a jingle implementation.
