### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by DenichSV** [siacs/Conversations#1064]
I drew some icons for Conversations, here they are:

[Con1.svg](https://github.com/DenichSV/icons-for-conversations/blob/master/Con1.svg)

[Con2.svg](https://github.com/DenichSV/icons-for-conversations/blob/master/Con2.svg)

[Con3.svg](https://github.com/DenichSV/icons-for-conversations/blob/master/Con3.svg)

You can use them if you want. I can draw something else if you need another icons.

**Comment by iNPUTmice** [comment]
We are currently not really looking for a new logo.
But thank you for your affords.
