### ISSUE TITLE
Feature request: Status update on screen lock

### ISSUE THREAD

**Issue by ivucica** [siacs/Conversations#1065]
When I'm not using the phone, I'd like that to be visible to other users by changing my `<presence>`'s `show` into `away`. Perhaps it could also change that into `xa` after a certain amount of minutes.

Xabber lets me do exactly this.

**Comment by sezuan** [comment]
This faq entry might be interesting: https://github.com/siacs/Conversations#where-can-i-see-the-status-of-my-contacts-how-can-i-set-a-status-or-priority

**Comment by ivucica** [comment]
Disappointing, but understandable. Thanks.
