### ISSUE TITLE
Feature request: Automatically changing priority (and obeying it)

### ISSUE THREAD

**Issue by ivucica** [siacs/Conversations#1066]
When I'm available, XMPP clients of choice generally set `priority` attribute of the `<presence>` to 15. (This is my arbitrary choice.)

When I'm busy, I set it to 2. (Again, purely arbitrary.)

When I'm away, it goes down to 0.

In this manner, I'd like to use `priority` to make other clients not buzz me when I happen to be using the phone, and not using the other clients. Vice versa, I'd like Conversations to buzz me only when its priority is the same as the maximum priority (the default behavior in XMPP when sending to pure JID). 

I understand that this may not be the 'mobile-first' behavior expected by most users these days, which is why I'd be perfectly happy seeing it shoved under expert options.

(Unless Conversations wants to expose manually setting `show` attribute, I assume this depends on issue #1065.)

**Comment by iNPUTmice** [comment]
this high level of productivity / scriptability is currently not in the scope of the project. We want a simple client that caters to the needs of regular consumers. There are other XMPP clients out there which might be better suited for your needs.

**Comment by jkufner** [comment]
Conversations makes use of Message Carbons, so priority attribute is
effective any more. If I understad you correctly, your issue is with
buzzing phone while other client is active, right?

**Comment by ivucica** [comment]
@iNPUTmice Just to comment on your statement about picking other clients: I have indeed tried most of them, and I find Conversations compelling due to beautiful UI and mostly sane handling of Carbons and MAM. Thank you for your work on it. So this is disappointing, but understandable. I hope the time comes when you can consider adding this type of functionality.

@jkufner That depends on the definition of 'active'. :-) For purposes of whether I want my phones to buzz, I consider the client on my work machine to be 'active' not just when it has focus, but when the status is not set to away. Which is why my first thought was to link this to `<presence>`'s `priority` attribute. Lowering `priority` would, according to my understanding of base XMPP RFCs, be the correct way of having the server not deliver the message at all if it's delivered to a bare jid. At least in a pre-carbons/pre-MAM world.

**Comment by Natureshadow** [comment]
All that is irrelevant with carbons.

Maybe a good option would be a configuration item to disable notifications on messages received as carbons vs. messages received directly.

**Comment by ivucica** [comment]
@Natureshadow Carbons get sent only if the message would ordinarily not be received by the client, right?

That would mean that being logged in with other clients that have `priority` > 0 would cause no notifications to ever be sent, right? (While I don't use Conversations with Google Talk, it seems that the Gmail's old-style web client, for example, hardcodes `priority` to 24.) 

Still, yes, this would be better than being ringed on three devices with Conversations for messages that I can handle on desktop...
