### ISSUE TITLE
LED notification not working after updating to 1.2.0

### ISSUE THREAD

**Issue by beriain** [siacs/Conversations#1067]
Hi! The LED notification has stopped working after updating to 1.2.0.

It used to work perfectly, after the first color modifications (I think after 1.1.0) the brightness lowered but still worked, but now does not show any color at all. The funniest thing is that this changes were made to "allow the led to work correctly on xperia devices", and my device is an xperia (but an xperia tipo, a low end one, not Z3 or ZR like mentioned in #1006 ).

Please, could the LED setting be reverted, or at least an option to choose between the previous setting and the new one added?

Thank you very much.

**Comment by QuentinC** [comment]
Hello, 

Could this be linked to this: http://www.phonandroid.com/forum/couleur-notification-par-led-t51993.html

Can you try apps to test that a green led is possible on your phone? 

Thanks!

**Comment by iNPUTmice** [comment]
can I get an TFDR (too French, didn't read) of the linked thread?
If it's just the one HEX value that causes problems and the old hex value was fine I'm happy to revert that.

**Comment by beriain** [comment]
Hi! I have tried a LED tester app, and it seems my device is not able to display green when the LED is blinking (notifications), only when is static (battery charged). So this seems to be an issue with my device and not with Conversations.

As far as this does not affect anyone else, I don't mind changing the HEX value in the source just for myself.

Thanks!

**Comment by andersruneson** [comment]
Why not go back to white? Default that seems to work for everyone.

/Anders

**Comment by hlad** [comment]
I created pull request #1062 for LED color settings
