### ISSUE TITLE
Feature request: Built in audio recorder

### ISSUE THREAD

**Issue by wiseoldman95** [siacs/Conversations#1070]
Currently, sending an audio messages requires opening an external app, this makes audio conversations impractical.

A Whatsapp/Telegram-style built in audio recorder would make "audio chats" (Not to be confused with Voip) practical in Conversations.

This was previously discussed here: #723

**Comment by TameOfGroans** [comment]
I prefer invoking external apps. Not all audio capture apps are great;  unless siacs is also an audio engineer diverting dev effort might be counterproductive. More vexatiously some phone audio subsystem employs dark arts, or drifts from audio APIs.

**Comment by TameOfGroans** [comment]
Thought for food

https://waze.uservoice.com/forums/59223-client-how-can-we-improve-waze-on-your-phone/suggestions/2997613-use-jingle-to-send-short-audio-blurbs-to-others

**Comment by wiseoldman95** [comment]
I don't understand the enthusiasm around invoking an external recorder, we want to long-hold a button, talk, release, done. This walkie-talkie style can never be achieved with an external voice recorder and therefore convenient voice conversations are not practical in Conversations.

By "voice conversations", I mean that both parties exchange short voice messages rapidly (Usually less than 10 seconds long), this is one of the awesome features in Whatsapp.

**Comment by wiseoldman95** [comment]
In the world of countless ready-to-use libraries, being an audio engineer has nothing to do with this. Game developers don't have to know a thing about GPU's nowadays.

I don't know how practical is this, but the code can theoretically be borrowed from [Telegram](https://github.com/DrKLO/Telegram/), Telegram is GPL2 licensed, and since Conversations is GPL3 [this is worth checking](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility). Telegram uses [Opus](https://www.opus-codec.org/).

**Comment by iNPUTmice** [comment]
this goes against the design principle of requiring as little permissions as possible

**Comment by wiseoldman95** [comment]
Fair enough.
