### ISSUE TITLE
FeatureRequest: Split preference option for delivery and displayed receipts into two

### ISSUE THREAD

**Issue by horas13** [siacs/Conversations#1071]
It might be interesting to split the option to send delivery and display receipts into two options - while delivery receipts just ensure that the message was delivered without technical issues, the display receipts are a bit more invasive from a privacy point of of view.

**Comment by iNPUTmice** [comment]
the concept of delivery receipts is considered deprecated. Introducing a new config option for this is not within the scope of this project.

**Comment by horas13** [comment]
Fair enough, but how come deliver receipts are deprecated? I find them quite useful.

**Comment by wiseoldman95** [comment]
I believe he means that they have been superseded by the "x has read up to this point" message.

**Comment by wiseoldman95** [comment]
> might be interesting to split the option to send delivery and display receipts into two options

Isn't that the current situation? You've got Settings > Confirm messages, and you've got `Settings > Exper Options > Request message receipts`.
