### ISSUE TITLE
Multi-client encrypted chat

### ISSUE THREAD

**Issue by TurkeyMan** [siacs/Conversations#1073]
I have phone, tablet, and PC client (at multiple locations). It's frustrating that I can't switch between devices using OTR.
I'm lead to believe this is a limitation of OTR (although the latest OTR revision has apparently addressed this?), but there are other attempts to solve this problem, for instance the axolotl protocol used by TextSecure somehow supports multiple clients.

I'm not sure about particular solution, but I think it's safe to say that the app that manages to solve this problem will gain ubiquitous support. Everyone among my social circle finds the single-client restriction of OTR too restrictive, and are patiently waiting for an app that cracks this problem.

**Comment by TameOfGroans** [comment]
does each client have a distinct resource?

**Comment by TurkeyMan** [comment]
I'm not sure what 'resource' means in this context.

I assume each device has created its own keys when it first runs?
Trouble is that OTR conversation on one device is unknown to other devices, so the history doesn't exist, and I can never refer to past conversations.

Does this work for others? User error?

**Comment by knoy** [comment]
The mpOTR (multi-party) protocol has been described but not implemented. It has been under development/discussion for a long time and it seems unlikely at this point it will ever see the light of day.

**Comment by TurkeyMan** [comment]
I see. Well that's a shame. But apparently axolotl can fill this void then?
It seems entirely unlikely to me that an encrypted chat technology will become ubiquitous unless it meets all the feature expectations compared to modern services.

**Comment by TameOfGroans** [comment]
"Sms texting" is not modern

**Comment by TameOfGroans** [comment]
Skype had been "encrypted" with RC4 albeit with a less than awesome key. RC4 is still employed in a fashion. 

Sip/xmpp encrypted audio or video will be ubiquitous even unwillingly in some sectors via Microsoft Lync.

**Comment by TameOfGroans** [comment]
Telegram is stymieingly popular. There are others

https://eff.org/secure-messaging-scorecard

**Comment by TurkeyMan** [comment]
I wasn't talking about sms texting... there's nothing modern about that. It's not possible to use sms on many devices, or swap devices as you like, so it's clearly not what I was talking about.

**Comment by timosl** [comment]
@iNPUTmice is working on axolotl support in this years [Google Summer of Code](http://wiki.xmpp.org/web/Summer_of_Code_2015#axolotl_support_for_Conversations), so maybe we will see some improvements as a result of that.

**Comment by iNPUTmice** [comment]
fixed in HEAD. beta will be pushed to the beta channel within this week

**Comment by TurkeyMan** [comment]
What is the fix?

**Comment by iNPUTmice** [comment]
Conversations 1.6 will come with multi-end-to-multi-end encryption (including offline messages / history)
See http://conversationsgsoc2015.blogspot.com/ for protocol description.

**Comment by TurkeyMan** [comment]
Interesting thanks.
I think I understood it correctly, but just to be clear, this is not compatible with TextSecure right? I think TextSecure uses some other transmission protocol than XMPP yeah?
It would be nice to be able to communicate with TextSecure clients from Conversations (most people I know use TextSecure).

**Comment by iNPUTmice** [comment]
> I think I understood it correctly, but just to be clear, this is not compatible with TextSecure right? I think TextSecure uses some other transmission protocol than XMPP yeah?

yes this is correct. TextSecure and Conversations just share the encryption primitives. Not the wire format. To my knowledge TextSecure doesn't even do multi-end-to-multi-end encryption. (Only in groups but not with multiple connected clients of the same account)

> It would be nice to be able to communicate with TextSecure clients from Conversations (most people I know use TextSecure).

Get TextSecure to use open, established and standardized protocols like XMPP instead of making up their own.

**Comment by TurkeyMan** [comment]
That's a reasonable criticism, but at the same time, I think Moxie Marlinspike has earned a level of respect for doing crypto really well.
I was going to ask if it might be possible to ask he reviews the axolotl implementation personally? If he feels the implementation is solid, perhaps that will give him a nudge to consider mirroring support in TextSecure.

**Comment by d9h02f** [comment]
>I think Moxie Marlinspike has earned a level of respect for doing crypto really well.
I'd say all respect is lost when you consistently refuse to put any effort into making your shit work without needing Google services, but this is going off-topic.
