### ISSUE TITLE
Sync OTR keys between apps/devices

### ISSUE THREAD

**Issue by TurkeyMan** [siacs/Conversations#1074]
How to sync OTR keys between apps and/or devices?
It's a problem to have different keys on every device; it seems to lead to the requirement to re-verify all my contacts every time I switch device. I presume this would be mitigated if my OTR instances shared keys?

**Comment by SamWhited** [comment]
Please do a search (including closed issues), this same issue has been raised many times.

Personally, I think this is a desirable circumstance (then when a key is compromised you can revoke that single device, not all of them and still have redundant verified keys which can be used to have a secure channel which can be used to re-verify the new key; if they all use the same key and it's compromised, you just lose all ability to have a secure conversation until you verify a new key).

**Comment by TurkeyMan** [comment]
Okay, is there an alternative solution to syncing the chat history between multiple OTR devices that you can suggest?
I think it's safe to say, people care about their chat history working as they expect more than they care about maximum security. OTR provides very good transmission security, and endpoint attacks can break it anyway, so I want my history to work like gtalk/facebook/etc.

**Comment by iNPUTmice** [comment]
You actually proposed the solution (axolotl) in your other issue. And we are planning on doing this. (This is way I haven't closed that issue)

**Comment by TurkeyMan** [comment]
Sorry, I'm not very familiar with the details of the protocols.

How does axolotl address the multiple client issue out of curiosity? (I just read that it does)
Are there other axolotl clients? Or will using axolotl effectively restrict communication to other Conversations users for the time being?

I read that OTRv3 did something too to address this problem?

I really look forward to this development, I'll gladly buy a bunch more copies when it appears :)
