### ISSUE TITLE
German Translation: Anwesenheitsbenachrichtigungen

### ISSUE THREAD

**Issue by tehabe** [siacs/Conversations#1077]
I think the word "Anwesenheitsbenachrichtigungen" for "presence update" is way too long also in some instances it is translated as "Online-Status", I think "Status" would be enough but anyway, I want to submit some alternative translation for the strings I could find at Transifex:

String 126
*English:* Send presence updates
*Current:* Anwesenheitsbenachrichtigungen senden
*My idea:* Online-Status senden

String 127
*English:* Receive presence updates
*Current:* Empfange Anwesenheitsbenachrichtigungen
*My idea:* Online-Status empfangen

String 128
*English:* Ask for presence updates
*Current:* Frage um Erlaubnis, Anwesenheitsbenachrichtigungen sehen zu dürfen
*My idea:* Online-Status anfragen

String 256
*English:* Please request presence updates from your contact first.\n\n<small>This will be used to determine what client(s) your contact is using.</small>
*Current:* Bitte erst Anwesenheitsbenachrichtigungen vom Kontakt anfordern.\n\n
*My idea:* Bitte erst Online-Status vom Kontakt anfragen.\n\n<small>Dies wird verwendet, um festzustellen, welche Client(s) der Kontakt benutzt.</small>

String 261
*English:* <b>Warning:</b> Sending this without mutual presence updates could cause unexpected problems.\n\n<small>Go to contact details to verify your presence subscriptions.</small>
*Current:* <b>Achtung:</b> Es kann zu unerwarteten Problemen führen, dies ohne gegenseitige Anwesenheitsbenachrichtigungen abzusenden.\n\n<small>Bitte die Online-Status-Abonnements in den Kontaktdetails prüfen.</small>
*My idea:* <b>Achtung:</b> Ohne die gegenseitig den Online-Status zu kennen, kann es zu unerwarteten Problemen führen.\n\n<small>Bitte prüfen Sie die Einstellungen in den Kontaktdetails.</small>

There are even strings where it is just "Status".

**Comment by iNPUTmice** [comment]
Translations are being managed on Transifex. Feel free to change them there. But I agree with you that 'Anwesenheitsbenachrichtigungen' might be a bit 'sperrig' and quite possible amusing to the English speaking people on our issue tracker. Yes we can form very long words in German. And yes I had to read the word twice after typing to check whether I typed it correctly.

**Comment by tehabe** [comment]
I requested to be part of the German translation group.

**Comment by kriztan** [comment]
I've just changed 'Anwesenheitsbenachrichtigung(en)' to 'Online-Status' in Transifex.
