### ISSUE TITLE
Conversation asked too many times to which resource it should sent

### ISSUE THREAD

**Issue by tehabe** [siacs/Conversations#1078]
I just want to send a message, Conversations should send it to the best option available. But instead it asked me to which resource and doesn't even give me hints which could be the best option (presence status). This makes it a very poor user experience.

This is especially annoying if I started an OTR conversation and I don't even know which devices also support it and if my message will be received correctly.

**Comment by iNPUTmice** [comment]
The best option available (which imho is the last active presence) is the preselected presence. So if you don't know what presence to choose you are most like good with the default.
Thats by the way the reasons Conversations uses 'sane defaults' on it's own resource offerings. So people don't use random strings as resource.
There is also no real way of knowing what resources support OTR (there is no disco for that)

And yes OTR sucks but these problems can only be overcome by not using OTR.
