### ISSUE TITLE
[Request] Option to never group messages

### ISSUE THREAD

**Issue by Hund** [siacs/Conversations#1079]
If you send messages in a rapid order, the messages groups together in the same chatbubble. Making it look like it is one and the message.

Having a option to never group messages would make it a lot easier to see every message when they are sent in a rapid order.

**Comment by iNPUTmice** [comment]
In general this feature is desirable to save space in the 'rapid fire' desktop style IM context where the sender basically hits enter after every sentence.
Offering a setting for this is against the design principles of Conversations (sane defaults)
However we can think about adjusting that sane default. Currently the 'attack window' is 20s which admittedly is a lot. Feel free to experiment with this value (https://github.com/siacs/Conversations/blob/development/src/main/java/eu/siacs/conversations/Config.java#L21) and report back if you find that maybe 15s or so give you better results.

**Comment by Hund** [comment]
I respect your design principles. But what I'm talking about is just a option, not changing the default behavior. 


But if you don't want to add a option, you should at least have a sane design. As of know the text blends together and it's impossible to see if it's one or several messages merged together. 

Changing the source myself? I can do that. If you personally learn me to code Java first.

**Comment by iNPUTmice** [comment]
> Changing the source myself? I can do that. If you personally learn me to code Java first. 

you can also set the value in the Config.java file I linked you to 0 to disable the behavior entirely. No need to learn Java over this.

**Comment by Hund** [comment]
I was somewhat sarcastic. :P I was hoping you'd be somewhat compliant.

**Comment by ElectronicWar** [comment]
Do you gain anything by not grouping the message? I mean you can still read the message but is it of some importance to be able to see the single messages?

**Comment by Hund** [comment]
It's more easy to read the messages. This is also the default behavior in every pretty much every IM client I've used over the years. Weechat, Irssi, Pidgin, Miranda IM, Facebook Messenger, Whatsapp, Skype, Adium, aMSN, emesene, Gajim, PSI, Telegram, Trillian and Viber. I think WLM had the same behavior to, but I haven't used that client in over 10 years now.

So It's not like I'm asking for something crazy weird things. :)

**Comment by Hund** [comment]
Pretty much every*

**Comment by timosl** [comment]
Maybe an alternative solution would be to keep each message in it's own box, but only display the avatar on the first message of the group, since the Avatar is the item that takes up the most space.

**Comment by Hund** [comment]
That's a great idea. :)

**Comment by TurkeyMan** [comment]
I like the grouping. Other apps just leave a slightly larger than usual gap (still within the one box) to denote where the message separation is.

**Comment by TameOfGroans** [comment]
Could you not yourself enable the expert setting to show Enter Key [bottom right] to add your preferred number of line breaks?

**Comment by TameOfGroans** [comment]
[I like the grouping as is]

Proper use of punctuation and caps might also benefit op conversations. 
Each line ought have bigger letter first on new line. 
See?

Else if not line breaks per se:
.
One could send one's own spacing character. 
.
It need not be a period!
□
Pick your preferred unicode symbol. 

🙅

**Comment by Hund** [comment]
Trolling is not appreciated.

**Comment by wiseoldman95** [comment]
>This is also the default behavior in every pretty much every IM client I've used over the years. Weechat, Irssi, Pidgin, Miranda IM, Facebook Messenger, Whatsapp...
Whatsapp does group messages in group chats, though it adds a tiny separator.

**Comment by Steltie** [comment]
This was a small thing that was bugging me too... A small seperator or, even better I think, just some space would be good. You could treat it like paragraphs this way.

**Comment by iNPUTmice** [comment]
> A small seperator or, even better I think, just some space would be good.

this has been implemented in 53e43daa0d8143d9a5abcd1391153b88a4702914

**Comment by QuentinC** [comment]
Hi,
I've tried this on 1.4.0alpha3.
It works prety grood, but a little grey square appears at the end of merged messages... Like if the separator were visible... 

I think that Android sees that as an unknown character that it tries to display !

Thanks !

**Comment by vijai1996** [comment]
I can confirm this. I only see a small box with "x" inside it. I think the unicode is not parsed as it should. I just disabled the whole grouping by adding `conversation.getMode() == Conversation.MODE_MULTI &&` to `mergeable()` in Message.java and merging is done only for groups now. I'm thinking of how to make the merge like in whatsapp now. Whatsapp merges message in a single view group where each message can be selected as an individual textview.
