### ISSUE TITLE
Conversations App pulled from Google Play Store

### ISSUE THREAD

**Issue by ElectronicWar** [siacs/Conversations#1080]
The app seems to be pulled from the Google Play Store.
Old links only show "not available":

https://play.google.com/store/apps/details?id=eu.siacs.conversations

Intentional?

**Comment by iNPUTmice** [comment]
Google has removed Conversations from the play store about three hours ago.
They claim Conversations or the app description or the screen shots violate someones intellectual property.
They were not specific about it and did not mention what it was exactly that caused the removal.

> This is a notification that your application, Conversations (Jabber / XMPP), for package ID eu.siacs.conversations, has been removed from Google Play.

> Please address the issue described below and submit a compliant update. Once approved, your application will again be available with all installs, ratings and reviews intact.

> REASON FOR REMOVAL:Violation of the intellectual property and impersonation or deceptive behavior provisions of the Content Policy. Please refer to the IP infringement and impersonation policy help article for more information.

>    Your app and/or elements of its listing on Google Play, including title, description, logo(s), or promotional screenshots must not include unauthorized usage of protected works belonging to a third party.
>    Your app icon and promotional screenshots must not contain images that appear confusingly similar to existing products.

> Protected work could typically include product names, brands, images, logos, music, and similar works.

> Please make modifications to your app and/or its listing to bring it into compliance. To do so, remove any content that may be a protected work in your app and/or app listing.

> If you are authorized to utilize this content, please contact us via the Google Play Help Center and attach verifiable and accepted proof of permission.

> All removals are tracked. Repeated removals will result in app suspension, at which point this app will count as a strike against the good standing of your developer account and no longer be available on Google Play.

> This notification also serves as notice for other apps in your catalog. You can avoid future removals and/or app suspensions by immediately ensuring that no other apps in your catalog are in violation of (but not limited to) the above policy. Before publishing applications, please ensure your apps’ compliance with the Developer Distribution Agreement and Content Policy.

> If you feel we have made this determination in error, you can visit this Google Play Help Center article.

> The Google Play Team

**Comment by ElectronicWar** [comment]
Oh well, that's nice :/
Good luck disputing that.

**Comment by iNPUTmice** [comment]
and we are back. I hope
