### ISSUE TITLE
Show padlock overlay on send-message button when encryption is enabled

### ISSUE THREAD

**Issue by TurkeyMan** [siacs/Conversations#1082]
I'd really like to see the '>' send-message button with the padlock overlay when OTR is enabled, as with other clients (TextSecure, ChatSecure).
I want to know at a glance that I'm sending messages securely or not without having to enter drop-down menus, and I think the padlock overlay on the send button is an excellent mechanism.

I think there's room for a colour distinction too. TextSecure uses green for plaintext, and blue for encrypted. It is also possible to distinguish whether messages in the chat history were sent plaintext or encrypted by the colour. Reaching consensus on these sorts of visual-language would be a good move across the board moving forward.

**Comment by bonsaithis** [comment]
how about stroking the button in a color [an outline]?

better, change the color of the closed padlock at the top... as it can be difficult for me to see the difference from the open icon. :/ Perhaps invert color and background

**Comment by TurkeyMan** [comment]
For my money, TextSecure already got this visual language perfect.

**Comment by aeuii** [comment]
Hi, I really like that idea and it would be very useful. It already happened a few times that I unintentionally sent unencrypted messages.

I know, that there's a padlock icon on the top (used to select: clear text, otr, and pgp), but it seem to be too far away to look at to confirm the encryption. (it also indicates false status at times)

There's also the gray text in the input area, but it's not visible right before sending.

Thank you!

**Comment by iNPUTmice** [comment]
fixed in 558d065d48b43c190cac706870cf8d97c70ecbfd

**Comment by aeuii** [comment]
Hi, I would like to ask to re-open this issue, because 558d065 fixed only the correct indication of encryption at the top of the screen.

@TurkeyMan asked to place a small padlock icon close to the send button, where eyes are usually fixed when sending a new message. Are there any disadvantages of this?

Cheers!
