### ISSUE TITLE
Facebook messages received while phone is offline don't appear in Conversations

### ISSUE THREAD

**Issue by something3** [siacs/Conversations#1083]
0. I'm using Conversations with facebook messages.

1. If the phone is not online at the moment the message is received, it doesn't appear in Conversations at all. (facebook doesn't sync the history or?)

2. Messages sent by user through facebook web interface also don't appear in Conversations (so i can only see replies from other people, but not my messages).

I have no idea if it's just facebook api being broken or something. People mentioned elsewhere that they are shutting their xmpp gateway soon anyway? Is it final? Any other solutions than stop using facebook?

**Comment by wiseoldman95** [comment]
This is not Conversations' fault.
Facebook does not sync history /:
Any other XMPP client would behave the same.

**Comment by BrianBlade** [comment]
Yes, Facebook's XMPP API is going to be deprecated soon: https://developers.facebook.com/docs/chat
There certainly will be tons of apps supporting the new FB Chat API. Conversations will most probably not be one of them, given the mission statement:
>- Be as beautiful and easy to use as possible without sacrificing security or privacy
