### ISSUE TITLE
Certificate pinning

### ISSUE THREAD

**Issue by wiseoldman95** [siacs/Conversations#1084]
When first connecting to a server with a self-signed certificate, Conversations warns about this and presents the user with three options: Accepting once, accepting always, aborting.

Does Conversations pin the self-signed certificate when selecting "always"?
If not, consider this post a feature request.

[Short background about key pinning here](http://security.stackexchange.com/a/29990)

Edit: According to @BrianBlade, no pinning occurs in Conversations.

**Comment by wiseoldman95** [comment]
Skimming through the source code reveals that Conversation uses [MemorizingTrustManager](https://github.com/ge0rg/MemorizingTrustManager). Is pinning s responsibility and not Conversations or MemorizingTrustManager's?

**Comment by knoy** [comment]
Yes, after clicking 'always' the certificate will be pinned

**Comment by BrianBlade** [comment]
Are you sure about that @knoy? 
I don't have the time to check it right now but from my understanding any new certificate that successfuly validates against the system's CA store will be accepted, even if an invalid or self-signed cert was memorized before.

**Comment by BrianBlade** [comment]
Just to confirm: There is **no** public-key pinning involved.
The MemorizingTrustManager will ask the user what to do with an invalid certificate (i.e., a certificate that is self-signed or signed by an unknown CA) and memorize that decision. If a different certificate is encountered later on and this new certificate can be successfully validated, the user will **not** be informed about the changed certificate. However, another user interaction is required if the new certificate's validity can not be verified.

**Comment by wiseoldman95** [comment]
This is what I suspected.
The whole point of self-signed certs is not relying on CA's, this defeats the whole purpose and is a security risk.
