### ISSUE TITLE
First message after longer pause in running conversation is not delivered

### ISSUE THREAD

**Issue by peter-greskovic** [siacs/Conversations#1087]
We are two people who have the same version of Conversations 1.2.0 on their phone (via F-droid).
We both have "force encryption" setting enabled in the expert options and the encryption set to OTR (we are both mutually verified).
We both have account on the same Prosody server.
We use the same conversation to send messages between us (i.e. we don't tear the conversation down and start a new one when we stop chatting for some time).

When we don't send any messages in the conversation for some time (hours) and then we resume chatting, the first message sent by whoever wants to continue the chat is undelivered (the other person doesn't get it and it is not marked as delivered). Second and next message continue the chat normally. This behaviour is easily reproducible for us.

**Comment by andersruneson** [comment]
I seem to have something similar, but I'm not using encryption. I've seen
this in mucs, but I've only tested in mucs so far.

/Anders

**Comment by iNPUTmice** [comment]
@peter-greskovic problem probably is an OTR problem which is probably fixed by #1021 

I'm closing here. If you @andersruneson can reproduce your bug please open another issue.
