### ISSUE TITLE
understanding the codes

### ISSUE THREAD

**Issue by hamedhamed** [siacs/Conversations#1088]
hi,
I started to read conversations codes, I understand some part and not understand some part of codes.
for example when user wnat to change password an IqPacket create and use xmppConnection.sendIqPacket() method and then use tagWriter.writeStanzaAsync(packet) to add packet to writeQueue . my question is how conversations  send the request throutgh socket ?which codes exactlly send the requests?
Is there any documentation for understanding better codes?

thanks

**Comment by andersruneson** [comment]
This is an issuetracker, not a support forum.
Please read the FAQ: https://github.com/siacs/Conversations#faq

Thanks

**Comment by SamWhited** [comment]
Your best bet is to try the MUC: `conversations@conference.siacs.eu`
