### ISSUE TITLE
Handling unreceived messages when offline?

### ISSUE THREAD

**Issue by kr428** [siacs/Conversations#1089]
Test scenario which I wanted to try after partially being offline today: Had Conversations running on the phone, pidgin on the desktop. Saw the Conversations account "online". Disconnected cell data on the phone. Conversations account obviously still online in pidgin. Tried to send a message from within pidgin, which worked (but obviously didn't arrive). Switched cell data on again, saw somethine like a "reconnecting" message in pidgin, but that one message sent while the user was offline seems lost.

Is there anything that can be done about this? Should XEP-0313 / MAM help here? Or is this merely just a server issue - the openfire has support for XEP-0136 but I am unsure about XEP-0313?

TIA,
Kristian

**Comment by BrianBlade** [comment]
Sounds like your server does not support XEP-198 Stream-Management and did not notice that the phone disconnected.

**Comment by kr428** [comment]
As far as I can tell, openfire does not support XEP-198, but it supports both a notion of detecting "offline" clients (using XMPP ping and a connection timeout) and "offline messages" but I am unsure how this is actually implemented; so far I failed to figure out which XEP they use for that. This seems to work, however, with most of the other XMPP clients we use internally (pidgin, psi, empathy on Linux, pidgin and psi on Windows, Xabber and yaxim on Android) that's why I am unsure where exactly the problem is, in this case.

I found the list of XEPs they support (http://www.igniterealtime.org/builds/openfire/docs/latest/documentation/protocol-support.html), but I am unsure which of these are required for working with offline clients.

**Comment by BrianBlade** [comment]
When you tear down the data connection it boils down to the question how long it takes the server to notice the disconnection. Its hardly a client issue and I dont see how this could be different for Xabber or Yaxim? Does your server support XEP-352 CSI in a strange way perhaps? 

So either just connect with a mobile when you've got a stable connection and make sure to cleanly logout once done or look for a server that supports XEP-198.
You could also try to increase the server's ping frequency to detect a disconnect as soon as possible but I'd strongly recommend against it as that comes at the cost of traffic and likely battery drain on the phone while messages can still get lost.
If you really need mobile clients the way to go is XEP-198 imho.

**Comment by kr428** [comment]
Thanks for your explanations. I suppose it definitely _is_ a server thing of some sort. Playing with the frequency of the server checking clients actually had massive effects in terms of battery consumption (as you pointed out) so I am back to more sensible settings here. 

Then again, that's not really a problem if messages would not get "lost" all along the way which happens here. The only difference between Xabber and Conversations about this seems the fact that Xabber does honour the server-sided message archive which our server keeps (and which seems XEP-0136) - I always see _all_ messages in a Xabber chat history, no matter on which client I received them. Maybe they use this approach to provide the user with messages unseen - in terms of messages new in the server history but not available in the client side cache?

**Comment by iNPUTmice** [comment]
Please migrate to a server that support Stream Management and message archive management.

**Comment by kr428** [comment]
Just out of curiosity: Which servers are recommended then? Especially talking Message Archive Management, I see this to be considered experimental and reliably implemented in obviously just a small handful of servers...?

**Comment by kriztan** [comment]
@kr428 I'm using my own prosody server pix-art.de with all features conversations supports. Feel free to create an account and use this features.

**Comment by kr428** [comment]
@kriztan Thanks for your offer - greatly appreciated but actually not working in our context. ;) Basically we use a semi-private XMPP server mostly as a hub for internal team communication. This installation is connected to the rest of the XMPP network with the restriction that no user accounts can be registered and that we do have pre-defined rosters that represent our current teams. Currently, we run openfire for these purposes which did well in most cases and with most clients so far, so I am left with giving up on either openfire or Conversations for this purpose. :(

**Comment by iNPUTmice** [comment]
@kr428 a recent ejabberd can handle most of the extensions required by Conversations out of the box except MAM. but there is a MAM module in the contrib repository.

**Comment by andersruneson** [comment]
We switched from openfire to prosody at work to get modern features
supported by Conversations working, such as pep avatars and stream
management.

/Anders

**Comment by kr428** [comment]
Thanks all then. I'm so far carefully looking into prodosy and ejabberd. @andersruneson Did you use some way of transferring data (users, rosters, history) from openfire to prodosy?

**Comment by andersruneson** [comment]
We have all users and MUCs (groups) in AD/LDAP so we imported nothing.

**Comment by kr428** [comment]
@andersruneson Thanks. I already have been looking at this but was unsure whether this would be a good approach, but it seems legit then.
