### ISSUE TITLE
Select several pictures to transfer 

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#1090]
For now, we only can send just one by one. If we want to send several images (just like we do using for example Gajim) we have to view the photo → share → Conversations → contact with every photo and that's really annoying.

**Comment by TameOfGroans** [comment]
is this a Conversations limit, or the gallery app?

**Comment by moshpirit** [comment]
A conversations limit, I can send them using another apps like KDE connect or Owncloud.
