### ISSUE TITLE
If an account is logged in with Conversations and pidgin at the same time

### ISSUE THREAD

**Issue by naixia** [siacs/Conversations#1091]
Messages sent by pidgin can be seen in conversations, but
those sent by conversations cannot be seen in pidgin.
Is this an error?

**Comment by andersruneson** [comment]
Pidgin does not support Message carbons (at least not without patches).
Use Gajim (enable carbons in Advanced config editor) on desktop.

**Comment by naixia** [comment]
Got it. Thanks.
