### ISSUE TITLE
File transfer is not working.

### ISSUE THREAD

**Issue by naixia** [siacs/Conversations#1093]
While I can happily use the "send file" function of other desktop jabber clients, it doesn't work for Conversations. There were no error messages, just waiting for file transfer to begin.

**Comment by iNPUTmice** [comment]
Maybe your contact is offline or you don't have presence subscription?
Also this is an issue tracker and not a support forum. If you want to report a bug please provide detailed steps to reproduce. For general help please see our conference.

**Comment by naixia** [comment]
I have 2 test accounts on a ejabber server.
If they are logged in with pidgin/jitsi, they can send files mutually.
If one account is logged in with conversations, they cannot.
It must be a bug of conversations.

**Comment by naixia** [comment]
Easy to reproduce ---  1 logged in with pidgin/jitsi,  2 logged in with conversations.
