### ISSUE TITLE
muc notifications improvement suggestion

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1095]
I think it would be better, if all muc notifications were allowed as standard. The settings option to `only notify, if my nick is mentioned` should be moved to the `disabled notifications` menu.
I'm a member of a lot of privat mucs, where I want to get notified on all messages and I'm also a member of public mucs, where I want to get notified, if my nick was mentioned. Currently I muted all the public mucs, what is not the best soloution.
Isn't it better do add the option to the `disable notifications` menu? So you can disable for a specified time or if own nick isn't mentioned.

**Comment by iNPUTmice** [comment]
Current HEAD changes the behavior to always notify in private / non-anonymous mucs (treat them like 1-on-1 chats). The 'Notify only when highlighted now acts on public mucs only)
