### ISSUE TITLE
Maintain private chat on MUC

### ISSUE THREAD

**Issue by margori** [siacs/Conversations#1097]
When I'm in a Multi User Chat room I can press and hold over a user avatar, then private message is allowed. In text area a "Send private private message to John" is shown. I start writing, then send.

Next message **is public**. I expected it **to be private to last person I sent.**

To support this request, I describe my behavior:

- I send a private message.
- I read messages chain.
- I see a private reply, so I need to reply, due to it has preference over public, I focus to keyboard 'cause I want to reply.
- I start typing ("private/public" message is hidden)
- Then press enter key expecting my reply going private since a private message I read.

**Comment by Natureshadow** [comment]
I second UI flaws / unexpected behaviour is security relevant.

**Comment by margori** [comment]
Thanks!
