### ISSUE TITLE
Move "hide_offline" checkbox to settings

### ISSUE THREAD

**Issue by Sohalt** [siacs/Conversations#1102]
I would suggest moving the "hide_offline" checkbox from the menu in the contacts screen into the main settings menu, as it adds unnecessary clutter imho and scatters the settings, making them harder to find and to keep track of.
Also filtering the contacts list to online accounts can simply be done by typing "online" into the search field (although that is not exactly the same behaviour, as other non-offline statuses get ignored. To fully support hiding offline contacts via filtering/search the search capabilities would need to be expanded to include a negate option -- maybe worth thinking about?).

**Comment by iNPUTmice** [comment]
I'm not seeing this as a general setting but as something that just toggles the view.

> Also filtering the contacts list to online accounts can simply be done by typing "online" into the search field

yes but this wasn't enough for people.

> To fully support hiding offline contacts via filtering/search the search capabilities would need to be expanded to include a negate option -- maybe worth thinking about?

I'm afraid that this is way too complex. (Not to implement but to actually use)

Lets not forget that the filter online contacts is just a tiny acknowledgment towards the 5% of user that use Conversations as a classic xmpp client. The general idea of Conversations is to hide presence information because everyone is online all the time anyway.

**Comment by Sohalt** [comment]
> I'm not seeing this as a general setting but as something that just toggles the view.

I totally understand the reasoning behind putting the option in the contacts screen. But it immediately jumped out at me, because I don't think it fits with the other items in the drop down (qr-code,account settings & general settings), which lead to different screens and don't directly affect the contact list shown. Maybe put it as an icon in the bar together with the search & add contact icons? After all it's also a way to filter/narrow down the contact list and having it there would also mean that you can more easily access it (both seeing the current setting and changing it).

> I'm afraid that this is way too complex. (Not to implement but to actually use)

I get your concern and also think it would be a feature that is overkill for the average user, but then it is something, that doesn't remove and only adds functionality.
By that I mean, that the complexity of using it is completely hidden from the average user, because they will probably never use it and it doesn't change the behaviour of the search bar if you don't use it (only problem would be accidentally triggering a negative search, but you could always make the extended functionality an option in the expert settings that has to explicitly be turned on).

**Comment by kr428** [comment]
Just €0.02 from one who actually uses both the current "toggle" switch and, even more (in other clients, such as Xabber) the group / roster feature: There are two use cases. The first one is wanting to send a message directly to one particular user. For this approach indeed I do not care whether this user is offline or online - I just want the message to be sent.

Use case 2, however: We use XMPP for our team communication. In this situation, in example while out of office, I am not really interested to write a message to a particular person - instead, in this situation I want to quickly see / find a member of a particular team (= roster / XMPP groups in our setup) who is in the office or at least "online" and want to message her/him. The current dynamic tags feature in Conversation is usable to figure out who is part of which group, so this works for me. For quickly finding "online" users, the "hide_offline" checkbox is the most convenient way I have seen so far; most XMPP clients are more complicated here.
