### ISSUE TITLE
File transfer is not working.

### ISSUE THREAD

**Issue by naixia** [siacs/Conversations#1103]
I have 2 test accounts on a ejabber server. 
If they are logged in with pidgin/jitsi, they can send files mutually.
If one account is logged in with conversations, they cannot.
It must be a bug of conversations.

**Comment by iNPUTmice** [comment]
Thats a weird behavior in the jitsi client. (Something with the way they handle caps). Jitsi and pidgin should not get influenced by Conversations even if Conversations where to do something wrong (which i don't believe it is)

**Comment by naixia** [comment]
Easy to reproduce --- one logged in with pidgin/jitsi, the other logged in with conversations.

**Comment by SamWhited** [comment]
Isn't this just a repost of #1093?

**Comment by naixia** [comment]
Yes, just a repost, since one closed the old one.

**Comment by naixia** [comment]
I assume jitsi has full support for XEP-0166 right?

**Comment by iNPUTmice** [comment]
> I assume jitsi has full support for XEP-0166 right? 

Afaik jitsi uses jingle only for voice/video and sadly not for file transfer.

Like I said before this is a strange behavior in the CAPS implementation of jitsi.  I don't think this is a bug in Conversations. (I will happily adjust my own caps settings though if there is any thing reasonable I can do to fix it and if someone figures out what.)
