### ISSUE TITLE
add an option to remove public key of a contact

### ISSUE THREAD

**Issue by pravi** [siacs/Conversations#1105]
Or even better offer to renogotiate keys if local key fingerprint does not match with the encrypted message. This happens when the contact reinstalls an app or switch to a different app. In both cases contact will have a new key pair and conversations won't be able to decrypt messages with old public key. Currently I can't use OTR because of this. My contact had to reinstall their app Loqui IM on Firefox OS because I switched to conversations from ChatSecure and they were messaging me with ChatSecure key.

**Comment by iNPUTmice** [comment]
You can delete your contacts OTR fingerprint by clicking the delete icon next to it.
There should be no need to renew your own key pair ever. (At least not in the scenarios you are describing)
