### ISSUE TITLE
Feature Request: Default XMPP server that supports the extensions.

### ISSUE THREAD

**Issue by harpereaves** [siacs/Conversations#1106]
A lot of potential users (myself included) are overwhelmed by the choice of XMPP services, some of which don't support the extensions necessary for all Conversations' features.

If Conversations recommended an XMPP server and made it really easy to create an account with that server from within the app, I might not have such a hard time convincing people to switch to it from "easier" proprietory alternatives like WhatsApp.

**Comment by rototom** [comment]
I would love to see that happen, but also there will be problems with that.
I use xmpp for years and had trouble with many free and open servers over the time. This ended two years ago with hosting my own one.
So we need to find someone who is really reliable. I would donate a domain and some skills with ejabberd/debian.

**Comment by harpereaves** [comment]
Does it have to be free and open? I would happily pay a small yearly fee (say, $1) for an account on a server specifically designed to work with Conversations.
Apart from a domain and some skills with ejabberd/debian, what else is needed?

**Comment by rototom** [comment]
Perhaps we should simply try this, before making it public?
Lets have some fun on my Server!
Any ideas for a domain?

Am 05.04.2015 13:14 schrieb harpereaves <notifications@github.com>:Does it have to be free and open? I would happily pay a small yearly fee (say, $1) for an account on a server specifically designed to work with Conversations.
Apart from a domain and some skills with ejabberd/debian, what else is needed?

**Comment by rototom** [comment]
So, I enabled my server for testing purposes. Temporary domain is immermusik.de.
The SSL cert is invalid, because its made for my main domain, but security features are ok as you may see at xmpp.net.
What xeps should we enable?

**Comment by harpereaves** [comment]
That's a great start!

For starters, enable all xeps listed on https://github.com/siacs/Conversations.

I've never tried to run an XMPP server before. Is it that easy? just select xeps from a list?

**Comment by rototom** [comment]
Unfortunatly its not that easy. Depending on which server you choose is more or less complicated.
I have a few hours time today and will see if can rule this list...
:-)

**Comment by kriztan** [comment]
You can also try my free XMPP server pix-art.de. I've prosody running on centos with all XEPs supported by Conversations enabled.

**Comment by harpereaves** [comment]
Thank you!

**Comment by rototom** [comment]
I`m done, also.
immermusik.de is up and running.

**Comment by timosl** [comment]
Related: #968

**Comment by iNPUTmice** [comment]
> Related: #968

I even dare to say duplicate.

**Comment by harpereaves** [comment]
Oh, yes. Same issue; slightly different proposal.
