### ISSUE TITLE
Send multimedia files in MUC

### ISSUE THREAD

**Issue by Nekmo** [siacs/Conversations#1108]
Today it's possible to send files to contacts in the roster, but not groupchats. An option is to use "inband images" http://wiki.xmpp.org/web/XHTML_Inband_Images . The problem are the clients that don't support this feature. I don't know if exists another XEP to solve this problem.

A workaround could be to upload the image via HTTP to a trusted server. This option could be parametrable, and even give the option to choose the server. The HTTP link can be previewed automatically.

**Comment by andersruneson** [comment]
There should already be an issue for this.

**Comment by andersruneson** [comment]
#175
