### ISSUE TITLE
Can't connect to any servers with recent version (not servers problem)

### ISSUE THREAD

**Issue by ache** [siacs/Conversations#1109]
It says "Server not found" for jabber.ru server and tries to connect
forever for gmail.com server.
The same two accounts works nice few versions back (or few google
services updates back, I don't know who broke it).
Xabber/IM+/Bluejabb etc. works with the same two accounts without any problems in the same time, so it is not the servers problem. I try to recreate accs, but nothing is changed. Passwords does not matter, I got the same results with wrong passwords too.
Android 5.0.1 Nexus 5 all things updated

**Comment by iNPUTmice** [comment]
I can connect to jabber.ru using my n4 with Android 5.0 just fine. I can't test gmail because I don't have an account with them.
are you using an IPv6 network?

**Comment by ache** [comment]
Yes, IPv6 network. Both talk.google.com and jabber.ru have IPv6 addresses in addition to IPv4 ones (dual-stack) and Android choose IPv6 when available, it can't be tuned.

**Comment by iNPUTmice** [comment]
can you ping the ipv6 addresses of those servers?
and would it be possible to provide the adb logcat output of the connection attempt?

**Comment by ache** [comment]
It seems it was temporary problem with my IPv6 tunnel few hours ago. It works now in Conversations, so I close the issue, sorry for the noise. 
Usually the tunnel works 24/7 so I don't ever think about possible IPv6-related problems, and other jabbers use IPv4 only so can't be compared.
