### ISSUE TITLE
XEP-0313 - All messages are restored after clearing

### ISSUE THREAD

**Issue by mase76** [siacs/Conversations#1110]
Hi!
I am using Conversations with Prosody 0.10 and mod_mam for XEP-0313.
After clearing a conversation, even when closing it afterwards, all messages are
restored when reopening. I think, only the new messages after clearing should
be restored from the server.

BTW: The basic XEP-0313 functionality works pretty fine in Conversations.

**Comment by kriztan** [comment]
I like this behaviour. Perhaps it would be better to ask the user after opening a cleared chat to load older messages. So you can decide it yourself.

**Comment by TameOfGroans** [comment]
I would prefer cleared xmpp texts to stay cleared. Undead messaging is spilt. 

I untick options to save history. I would greatly prefer a xep to indicate which contacts have opted to retain history -- and reject messages from them.

**Comment by TameOfGroans** [comment]
is split == is spooky 

[no edit from mobile]

**Comment by deoren** [comment]
I also like the option of restoring history from the server after clearing it on the client. 

In my particular use case this allows me to:

1. edit something out of the chat logs on the server
2. clear the chat history on the client
3. refresh on the client to pull in the updated conversation

This gives me the history without something which wasn't intended to be saved to begin with. That said, perhaps ask the user as @kriztan says or add a configurable option to not restore history from the server?

**Comment by mase76** [comment]
That would also be ok. I suggest 3 options:
- restore the whole history
- restore only from last clearance (conversations could remember the timestamp of clearance)
- don't restore anything

Also a button to trigger restoring in the options of a chat would be welcome.

**Comment by iNPUTmice** [comment]
@mase76 to provide a good solution here can I ask what your reasons for clearing messages from a conversation are?

**Comment by mase76** [comment]
One reason is to make this function in conversations clear. When selecting "clear" does not really clear, it does not make any sense. Without mam it stays clear, but with mam it is reconstructed from the server.
Another reason is, when the whole history is getting very large, and isn't needed any more.
A problem is, that when a client clears the history, the server does not get a notice of it, and does not also clear the history. Afaik XEP-0313 does not contain any deleting options. Maybe a future version.
-- 
gpg: 383107c4
https://www.setho.org/people

**Comment by iNPUTmice** [comment]
Oh sorry I wasn't asking about what's wrong with the current clear behavior but for the reason your are clearing in the first place.

**Comment by mase76** [comment]
Then take the second point.
The thing is not, what reasons the users could have, it is what they can do.
-- 
gpg: 383107c4
https://www.setho.org/people

**Comment by iNPUTmice** [comment]
So your problem here is with the inconsistency between servers that offer MAM and servers that don't? If thats the case then removing the 'Clear history' menu item would be a suitable solution for you?

**Comment by mase76** [comment]
Not really. Maybe only if the server supports mam.
I think the best solution is, that conversation remembers the timestamp of clearence, and either restores only from this timestamp, or maybe ask the user (dialog or option in the app settings).
-- 
gpg: 383107c4
https://www.setho.org/people

**Comment by TameOfGroans** [comment]
Can the client not opt out of mam from server?

**Comment by github-k8n** [comment]
@TameOfGroans, @iNPUTmice , the reason for clearing the message log might be as simple as not having enough space on the device.

I have another old device (HTC Legend) where the memory is pretty tight. Thus if you have to lug around a year's worth of logs only to keep the last few conversations in sync that would be a bit of overkill.

Disabling MAM is not really a solution, the chat history sync feature is nice and one of the reasons why people love something like hangouts etc...

I like the timestap suggestion (only sync back to when it was last cleared), maybe another possibility would be to have a setting to specify a maximum log size, then only sync up to that limit (backwards of course, not that we end up with only the oldest messages :-)
