### ISSUE TITLE
Fix proposal: Sending files when peer is practically offline, but not yet timed out

### ISSUE THREAD

**Issue by SafwatHalaby** [siacs/Conversations#1111]
When one sends a file to a contact who appears online, but is in fact offline and is yet to timeout, the following scenario always follows:

- Conversations is -rightfully- unable to tell that the contact is not really online, so it offers them the file, an "offering" message appears below the file on the sender's device.
- Since the contact is not really there, the "offering" message remains as long as the contact is marked online by the server.
- Once the server decides to timeout the contact, Conversations realizes that the file offer was in vain and the "offering" message turns into "delivery failed".
- Since the contact is now officially offline and the delivery failed, the file will never arrive, unless the sender long-touches the file and selects "resend", in that case, the "delivery failed" message is transformed into "waiting".
- When the contact is back online, "waiting" becomes "offering", now this is a genuine file transfer, and the file is transfered successfully. (Unless the contact gets online only very briefly, in that case, the scenario repeats itself).

Since Conversations works on mobile, and mobile is unreliable, this scenario happens quite often, when a contact's connection is really bad, "delivery failed" can appear several times in a row and the user must click re-send numerous times. The average user is expecting a Whatsapp-like "send-and-forget", something which Conversations has impressively achieved with text messages. But due to this issue, the user has no guarantee of delivery when it comes to files.

There are two things that can be improved here:
- When the receiver disconnects while the sender's Conversations is in the "offering" state, the new state should automatically become "waiting", it makes no sense to change the state into "delivery failed" and force the user to manually re-send the file.
- The "Offering" state should be internal. From the user's perspective, the difference between "waiting" and "offering" is vague and confusing, this is especially true considering the fact that Conversations' design departs away from the Presence feature. Whether Conversations is internally "waiting" or "offering", the user should only see "waiting".

Note that I am not suggesting that Conversations should always automatically re-send the file when delivery fails, there are numerous cases where it makes sense to not re-send. I am suggesting that Conversations should automatically re-send *only* in the scenario mentioned above (Receiver disconnects while sender is in the "offering" state).

**Comment by TameOfGroans** [comment]
"resend" might open the door to other interesting functionality not the least of which is pounce [send message upon Jid availability]

**Comment by iNPUTmice** [comment]
Feel free to send in a pull request

**Comment by wiseoldman95** [comment]
Alright, I will probably do that

**Comment by wiseoldman95** [comment]
Are you fine with both proposals? (The resend, and only showing "waiting..." to the user)

**Comment by iNPUTmice** [comment]
Yes. Beware that if you turn offering into an internal state the automatic 'send when user comes online' code will have to check if the file isn't already in an offer state. otherwise the file might get send twice.

**Comment by wiseoldman95** [comment]
Any pointers on where to start and which parts of the code are responsible for this?

**Comment by iNPUTmice** [comment]
current HEAD should fix this

**Comment by SafwatHalaby** [comment]
Thanks, I'll test it and report back if there are issues.

**Comment by SafwatHalaby** [comment]
Is this in 1.3.1 or just the dev head?

**Comment by iNPUTmice** [comment]
4151b72a6e68faff45e3d166823459eaa07c63a3 which is included in 1.4.0-beta

2015-05-17 12:46 GMT+02:00 Safwat Halaby <notifications@github.com>:

**Comment by SafwatHalaby** [comment]
Oh, ok. I saw that one but didn't realize the commit is related. The title is a bit misleading. "Message status" as in "File transfer status"?
