### ISSUE TITLE
Bug in automatic download of image links

### ISSUE THREAD

**Issue by lookshe** [siacs/Conversations#1121]
When sending two links in one message separated only by a space, only the first picture is downloaded. This happens also, if the message ends with e.g. "/xyz.png".
Messages for reproducing:
`http://upload.mitsu-freunde-bw.de/uploads/2015/01/i15bgalni.jpg http://upload.mitsu-freunde-bw.de/uploads/2015/03/i27b1zd0m.png`
and
`http://upload.mitsu-freunde-bw.de/uploads/2015/03/i27b1zd0m.png here a some text which will not be shown, cause the image will be downloaded instead /abc.png`

The bug is caused by Message.bodyContainsDownloadable()

I've made a patch which first checks for blanks in the message (normally this should be %20 in an url) and also should speed up the check for an url.

Here the a Link to the patch: http://www.thehappy.de/~lookshe/pub/0001-better-and-perhaps-faster-way-for-checking-if-a-mess.patch

**Comment by Natureshadow** [comment]
Huh? Conversations automatically downloads these URLs?

I hope this is opt-in and disabled by default‽

**Comment by lookshe** [comment]
Yes it does, if you have enabled "Accept files" and the file behind the link is smaller than the defined value. But it only works for files ending with webp, jpeg, jpg, png, jpe.

**Comment by iNPUTmice** [comment]
@lookshe thank you for you work. Can you create a PR for this?

**Comment by lookshe** [comment]
Done: https://github.com/siacs/Conversations/pull/1123
