### ISSUE TITLE
Get rid of notifications are disabled snackbar in favor of smaller icon

### ISSUE THREAD

**Issue by gsusrb** [siacs/Conversations#1124]
I think the message of "Notifications are disabled" is very big and annoying when you are writing in a a muc.
Can you place this message, with a simple icon, beside the name of the muc?.

Suggest: http://i.imgur.com/bVDiMPF.png

Thank you.
Regards.

gsusrb.

**Comment by iNPUTmice** [comment]
fixed in 0bb3ae37f0762ad264a4b98b3ebc4753017441af
