### ISSUE TITLE
Feature Request: Delete/Copy/Forward multiple messages By long press on the messages

### ISSUE THREAD

**Issue by vijai1996** [siacs/Conversations#1125]
It would be great if multiple messages could be selected for either delete/Copy or forward to other contacts. At present, I can only copy single message at a time and cannot delete individual messages or multiple messages at all. All I can do is clear the entire conversation. Also, an encrypted backup of database on storage option would be great to restore the messages back after the app is reinstalled.

**Comment by iNPUTmice** [comment]
out of scope
