### ISSUE TITLE
Doesn't seem to work with jabberd2 server

### ISSUE THREAD

**Issue by medikoo** [siacs/Conversations#1127]
I have setup a jabberd2 server on Ubuntu. Without issues I connect using e.g. Messages on OSX, but when I try this app, all I get is _Incompatible server_ message.

Server just indicates that with following log:
```
Tue Apr 14 20:27:25 2015 [notice] [8] [84.10.55.6, port=35125] connect
Tue Apr 14 20:27:25 2015 [notice] [8] [84.10.55.6, port=35125] disconnect jid=unbound, packets: 0
```

**Comment by Natureshadow** [comment]
What configuration are you using for the connection?

I assume something concerning TLS cipher suites might be incompatible here. Some more verbose logs sure would help.

**Comment by medikoo** [comment]
I didn't spot any possibility to tweak any settings in app. All it took was username and password

**Comment by iNPUTmice** [comment]
Please make sure your server supports STARTTLS.

also if you are just setting up you might want to go for ejabberd or prosody to get the best user experience out of Conversations.

**Comment by medikoo** [comment]
> Please make sure your server supports STARTTLS.

I think it doesn't, so I take that's the issue. It would be great then if application error message says specifically that _server doesn't support STARTTLS, which is mandatory_

**Comment by iNPUTmice** [comment]
> It would be great then if application error message says specifically that server doesn't support STARTTLS, which is mandatory

incompatible isn't just triggered by that. But we will publish a server how-to within the next couple of weeks which will mention STARTTLS as a requirement.

**Comment by unconed** [comment]
I ran into a similar issue today, app says "incompatible server" and nothing in the adb log but "error connecting account". Did that server how-to ever get published? Either way, this really should have more useful error logging, both debug and in-app.
