### ISSUE TITLE
HUGE weird icons instead of the pretty Android ones in the Action Bar

### ISSUE THREAD

**Issue by incognico** [siacs/Conversations#1131]
All icons in the action bar are huge and not esthetically pleasing. When I compare them to the beautiful Android icons seen in the screenshots on the Play Store page I almost have to cry because it feels like I am using a Seniorenhandy :'(

The device is a LG G3, the resolution of the display is 1440x2560.

Happens on the OnePlus One too.

I am participating in the beta test (Play Store), so I can provide early feedback if desired.

For example the attach and security button (all others are weird and huge too):
![screenshot_2015-04-17-10-18-14](https://cloud.githubusercontent.com/assets/2098066/7198310/53b470a8-e4eb-11e4-9ace-4e1173c6c547.png)

**Comment by QuentinC** [comment]
I have the same problem here after the upgrade to lollipop...
How to have the small icons ? 

Thanks !!!

**Comment by Natureshadow** [comment]
Confirmed.

**Comment by iNPUTmice** [comment]
I'm on to it. will push a 'fix' next time my notebook has Internet. this will probably make it to 1.3.0

**Comment by iNPUTmice** [comment]
fixed in 93e942f96d856b4ea2ac2595dd8f76ffa0832db3

**Comment by SamWhited** [comment]
These looked normal to me before, and now look tiny. Maybe there's a DPI difference we need to be accounting for?

I'm on an HTC m7.

**Comment by SamWhited** [comment]
Actually, ignore that last comment. I looked at some of the Google Apps and they all look that way (which to me seems tiny). Must just be me.

**Comment by iNPUTmice** [comment]
I - personally - was fine with the old size as well. This is very much a matter of taste I guess.

What made me change the icon size in the end was this: http://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-touch-target-size part of the material documentation that specificies an icon size of 24dp. (Previous size was 48dp but I'm not sure if Android scalled that done to some extend)

Now the icons are roughly the same size as the overflow menu dots which - if you compare that to other material apps like gmail for example seems about right...

**Comment by Natureshadow** [comment]
I wasn't too uncomfortable with the bigger icons either, but design integration with other apps seems imoortant as even tiny differences can feel disrupting at times.
