### ISSUE TITLE
Join the EFF list?

### ISSUE THREAD

**Issue by SafwatHalaby** [siacs/Conversations#1132]
Conversations could gain some popularity if it's added to the EFF secure messaging scoreboard:
https://www.eff.org/secure-messaging-scorecard

**Comment by iNPUTmice** [comment]
@wiseoldman95 Can you get in touch with the EFF and ask them to add Conversations to the list? If they have further questions either cc me in your email `inputmice (at) siacs.eu` or use this issue to ask me.

**Comment by wiseoldman95** [comment]
Will do. Has there been an independent code audit for Conversations?

**Comment by iNPUTmice** [comment]
> Has there been an independent code audit for Conversations?

No

**Comment by iNPUTmice** [comment]
request has been sent
