### ISSUE TITLE
[REQUEST] Hide conference tab

### ISSUE THREAD

**Issue by chrisvella** [siacs/Conversations#1133]
I would like the ability to hide the conferences tab as I never use conferences. This would mean both the contacts and conferences tab could disappear, giving the contact list even more room. A simple checkbox in the settings would be enough.

This is a fairly trivial request so I understand if you reject it.

Thank you for the fantastic client.

**Comment by iNPUTmice** [comment]
Since most users won't be opening the contact list on a daily basis (Conversations follows the concept of just leaving conversations open) it is not worth trading the space for a more cluttered app settings.
