### ISSUE TITLE
Adding people to MUC from private chat marks group "persistent"

### ISSUE THREAD

**Issue by vijai1996** [siacs/Conversations#1137]
Hello, 
        I configured MUC to be non-persistent by default in my server config. When I create MUC through the Conversation tab in "create new chat" screen, the group is created correctly with MUC being marked as non-persistent. But when I create group from the optionsmenu while in a private chat with a user, the group is still created successfully but thr MUC is marked "Persistent". I would like the persistence to be controlled by the server. Also can anybody say, how can I delete a MUC which is persistent? I have 4 unused MUC's with 0 users. And why is conversations@conference.siacs.eu down?

**Comment by iNPUTmice** [comment]
this is working as intended. please use the Join conference dialog if you don't want this to happen
