### ISSUE TITLE
Without avatars

### ISSUE THREAD

**Issue by sim6** [siacs/Conversations#1138]
I am using Conversations with ejabberd from Debian wheezy and avatars doesn't work.

**Comment by andersruneson** [comment]
Make sure your server supports PEP avatars, Conversations does not support
vcard avatars.
If you have more questions, please join the chat room.

**Comment by sim6** [comment]
PEP is enabled by default :(

**Comment by iNPUTmice** [comment]
you will need a fairly recent version of ejabberd. have a look at the repository provided by jabber.at

**Comment by sim6** [comment]
Firstly thanks dor your fast answers!
Maybe I we can use Debian jessie (testing) packages too.
Do you recomend to switch to another server like prosody?

**Comment by iNPUTmice** [comment]
No ejabberd is perfectly fine. You just need a recent version. I don't know if 14.07 (or what ever testing has right now) is recent enough. If I remember correclty you will need at least 14.12.
Just go with the jabber.at ones

**Comment by sim6** [comment]
OK, thanks for your support!
