### ISSUE TITLE
Feature request: Audio/Video chat (Jingle* XEPs)

### ISSUE THREAD

**Issue by BrokenVentilator** [siacs/Conversations#1139]
In XMPP, it exist some XEPs to support video and audio chat. Even multi-users chat with audio and video.
It would be great if Conversations can support it. Maybe by a plugin.

**Comment by iNPUTmice** [comment]
Adding voip capabilities to Conversations is currently not within the scope of the project.
There are other apps out there (jitsi comes to mind) that already do this.

**Comment by jkufner** [comment]
How complicated it would be to allow plugin for this?

If you don't want to implement it (which is fine -- it is a lot of work), it could be practical to let third party plugin to cooperate with Conversations. It would allow parallel development without complicated merging.

**Comment by iNPUTmice** [comment]
> How complicated it would be to allow plugin for this?

Very much. You will need to break through the carrier NAT first to create a real P2P connection instead of a proxied on.
Thats the first step. After that; nice bitrate adjustment isn't easy either. Not talking about all the UX stuff like turning of the screen while holding the phone to your ear.

**Comment by iNPUTmice** [comment]
Oh sorry I missunderstood your question. I don't know if a plugin is the right solution. You better base this of something like Jitsi and then just add a call button that invokes jitsi or something like this.

**Comment by Natureshadow** [comment]
> Oh sorry I missunderstood your question. I don't know if a plugin is the
> right solution. You better base this of something like Jitsi and then
> just add a call button that invokes jitsi or something like this.

Umm… can't I simply use Jitsi then?

**Comment by iNPUTmice** [comment]
> Umm… can't I simply use Jitsi then?

thats pretty much my point.

**Comment by jkufner** [comment]
Hmm... Jitsi is under LGPL and it has some [libjitsi](https://github.com/jitsi/libjitsi). I explored it only briefly, but Jingle videocalls may be easier to implement than it looks.

**Comment by Natureshadow** [comment]
> Hmm... Jitsi is under LGPL and it has some libjitsi
> <https://github.com/jitsi/libjitsi>. I explored it only briefly, but
> Jingle videocalls may be easier to implement than it looks.

Actually yes.

In fact, you can take just anything that speaks RTP. Fork any VoIP app
you like. The only Jabber-specific thing is the signalling part. Ones
peers are found and the session can be established (maybe using ICE and
the like), you get an RTP session just like with SIP, there is no
difference anymore.

There are plenty of SIP VoIP apps for Android out there, so the largest
part of the task should be extracting UI and RTP code from a pretty and
compatible VoIP app.

-nik

**Comment by chathudan** [comment]
webrtc-jingle for android https://github.com/lukeweber/webrtc-jingle-client is the best solution for audio. and you might use this STUN/TURN server https://code.google.com/p/rfc5766-turn-server

**Comment by joice33** [comment]
For social chat I have heard about chatwing you can try for that. It's totally free and no monthly/yearly charges. The chatwing features is available for all kinds of website like wordpress, joomla, magento and so on. Also you might get a better idea from here. http://www.blog.chatwing.com
