### ISSUE TITLE
Feature request: News Stream (PubSub)

### ISSUE THREAD

**Issue by BrokenVentilator** [siacs/Conversations#1141]
With PubSub, users can have a personal news stream. User can write some messages (with images, videos, etc…) and publish them to contact list or publicly. You can see examples with Movim web app: https://movim.eu/

It would be great if Conversations can support it.

**Comment by iNPUTmice** [comment]
This is currenlty not within the scope of this project. Conversation is an instant messenger and not a social network. If you want a social network there a plenty of other options (like movim for example)

**Comment by Postroutine** [comment]
But instant messenger is a network for social interactions. And a news feed is messages, sent instantly.

**Comment by labdsf** [comment]
Telegram is an instant messenger with a Publish-Subscribe service, called "channels".

**Comment by Postroutine** [comment]
@labdsf Exactly.

**Comment by myluckyapps** [comment]
I had similar idea earlier,  users always can send messages( or tweets) to his interested contacts. 

Can anyone provide sample demo or references sothat I will try implement in another fork. I will check movim to too for more info.

**Comment by uchchishta** [comment]
@myluckyapps [smack](https://github.com/igniterealtime/Smack/tree/master/smack-extensions/src/main/java/org/jivesoftware/smackx/pubsub) and https://github.com/esl/mangosta-android demo
