### ISSUE TITLE
Send Position: wait until GPS deviation is small enough to send an acceptable position

### ISSUE THREAD

**Issue by karlkarpfen** [siacs/Conversations#1143]
Function for sending a users position has one big problem: it seems to use the first position it gets when there is a GPS fix. Often this position has quite a huge deviation of several 100 meters and therefore is very inaccurate. It would be better to wait until GPS position accuracy is better than e.g. 25 m instead of using the first one that was found.

**Comment by TameOfGroans** [comment]
Should this not be up to offering user? 

"How much battery am I will to consume to send a fix?"

**Comment by TameOfGroans** [comment]
https://f-droid.org/repository/browse/?fdfilter=nlp 

[local] fixing alternatives

**Comment by vijai1996** [comment]
Created a pull request for this here: Also, it doesnt require map api I guess but I havent tested it. https://github.com/siacs/ShareLocationPlugin/pull/8

**Comment by iNPUTmice** [comment]
> it seems to use the first position it gets when there is a GPS fix.

it doesn't. If you wait longer the results will become better. The blue circle is indicating the current accuracy.
