### ISSUE TITLE
Import/Export/Convert OTR keys

### ISSUE THREAD

**Issue by mikecardwell** [siacs/Conversations#1145]
Please consider adding support to import/export OTR keys. I'd like to be able to use the same OTR key in Pidgin and Conversations.

FYI, the "keysync" program here https://github.com/guardianproject/keysync has support for converting between various OTR key file formats e.g, ChatSecure, Pidgin, Adium, and Jitsi.

**Comment by plsng** [comment]
Dupe of several issues, like this: https://github.com/siacs/Conversations/issues/78
