### ISSUE TITLE
Retry image send after failure

### ISSUE THREAD

**Issue by singpolyma** [siacs/Conversations#1147]
Usually image transmission fails just because of a hiccup in the internet on one side of the conversation. After a brief pause (or after next presence online from the target?) at least one retry seems like it would improve reliability

**Comment by TameOfGroans** [comment]
Should auto retry expire after offer not accepted a period? Perhaps detecting other not using auto accept [under x]?

or could auto accept be a PEP/PubSub ?

**Comment by dicer** [comment]
I also sometimes have this with normal messages. So maybe a general retry mechanism would be even better? Maybe one where time between retries keeps getting bigger.

**Comment by singpolyma** [comment]
the difference between images and normal messages is that we can *know* when an image/file transfer has failed for sure

**Comment by SafwatHalaby** [comment]
I already reported this. And @siacs says it was fixed in beta 1.4
This is a duplicate of #1111

**Comment by SafwatHalaby** [comment]
After a second thought, this isn't entirely identical.

**Comment by singpolyma** [comment]
Any comment on why this is invalid? Would help my use case a lot, as image transfer seems to fail with about 50/50 chance, even when both phones are on same wifi. Sometimes even gets to 100% and then fails... second try pretty much always works, so it seems like a simple retry would be great still.
