### ISSUE TITLE
feature: privacy lists

### ISSUE THREAD

**Issue by TameOfGroans** [siacs/Conversations#1148]
Would XEP-0016 fall within design principles?

**Comment by SamWhited** [comment]
What part of XEP-0016 do you think you need that's not already covered by XEP-0191 (Blocking Command) which is already supported?

**Comment by TameOfGroans** [comment]
Does not 16 allow for multiple lists loading [scenarios]?

At work I load list 01, at home list 02, evenings list 03.  This allows for one JID without relying on [training] contacts one's actual availability for various peer groups.

**Comment by iNPUTmice** [comment]
> Would XEP-0016 fall within design principles? 
nope. sorry
