### ISSUE TITLE
Resource leak -- file not closed -- found by Facebook's static analyzer

### ISSUE THREAD

**Issue by dulmarod** [siacs/Conversations#1150]
Hello,
This resource leak report, included with comments below, were found by running

Facebook's Infer static analyzer on Conversations.

Regards,
Dulma Rodriguez
Facebook Static Analysis Tools Team

File: libs/MemorizingTrustManager/src/de/duenndns/ssl/MemorizingTrustManager.java

Report: Resource Leak: resource acquired by call to FileInputStream(...) at line 329 is not released after line 329.

Remarks: The file should be closed.

---

File: src/main/java/eu/siacs/conversations/persistance/FileBackend.java

Report: Resource Leak: resource acquired by call to FileOutputStream(...) at line 159 is not released after line 171

Remarks:  The calls to os.flush and os.write can throw exceptions, in which case the streams won't get closed.

**Comment by Flowdalic** [comment]
It's hard to tell which version of MTM Converstations uses since it appears to be simply added by copying the files over, instead of using e.g. git submodules. :(

But this is likely fixed in https://github.com/ge0rg/MemorizingTrustManager/pull/41

**Comment by SamWhited** [comment]
@Flowdalic It's a git subtree merge; you can update by adding MTM as a new remote and doing a merge -S subtree (see the Readme or GitHub or Bitbucket's great help articles on the topic)

**Comment by dulmarod** [comment]
Hi, 
Facebook's Infer static analyzer, the tool that we used to find these issues, is open source now! Check it out! (http://fbinfer.com/).
