### ISSUE TITLE
can't share to a MUC 

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#1152]
I was reading Reddit and I wanted to share a link, so I pushed the "share" button of RedReader and I selected "Conversations", then I see a list of all my contacts, but that's it, only contacts, no rooms. 

If it was a picture, I would understand it since we can't share files in a room, but it's a link (a piece of text).

**Comment by iNPUTmice** [comment]
I cant reproduce this with current HEAD. but I'm pretty sure this has been working before as well. But I can't test this since I don't have a 1.2.0 installed right now.
