### ISSUE TITLE
Unknown error with OpenKeychain

### ISSUE THREAD

**Issue by seppi42** [siacs/Conversations#1153]
When trying to add my OpenPGP key, an unknown error is displayed (German: "Fehler mit OpenKeychain).  Perhaps related to the fact that my OpenPGP key has more than one identity? Can anyone reproduce? 

Latest version on both Conversations and OpenKeychain

**Comment by iNPUTmice** [comment]
Can you check the adb logcat output? The error message should be more detailed there.

**Comment by QuentinC** [comment]
Well I have the same problem, I will see the logcat this evening !

**Comment by seppi42** [comment]
Sorry for not answering all the long time, I had to study for two highly important tests. 
The new versions of both Conversations and OpenKeychain fixed the problem for me.

**Comment by iNPUTmice** [comment]
> The new versions of both Conversations and OpenKeychain fixed the problem for me.

ok. closing
