### ISSUE TITLE
server not found [only by conversations]: chatme.im

### ISSUE THREAD

**Issue by TameOfGroans** [siacs/Conversations#1154]
Occasionally I am left unable to connect my Chatme.im JID with error "server not found". Xabber Dev consequently started makes connection swiftly.

**Comment by iNPUTmice** [comment]
please provide an adb logcat output of your failed connection attempts. 
and if you are in an ipv6 network check your ipv6 settings.

**Comment by TheHellstorm** [comment]
I had the same problem in my ejabberd configuration.

The server was available with IPv6, but I did not had the "inet6" configuration option in my ejabberd.cfg (See here: https://www.ejabberd.im/node/1138). After changing this it worked.

In my opinion, a fallback to IPv4 would be nice, if IPv6 connection does not work. Or maybe a slightly more verbose error message. "Server not found" is not really helpful :(

**Comment by iNPUTmice** [comment]
Conversations is already trying to fall back to IPv4 if either the DNS server reports IPv4 addresses in their additional sections or the native resolver resolves to a IPv4 address.

**Comment by TheHellstorm** [comment]
Hm, well, ok. Maybe just a problem in my server configuration.

The DNS of my domain (lets say example.com) has A and AAAA records and _xmp-client._tcp.example.com which point again to example.com with the port number. 

The ejabberd config did not offer IPv6, so even though the DNS provided a IPv6 address to connect to, ejabberd did not listen on IPv6. Well, now it works, but weird that it did not. Xabber and Pidgin always worked, only Conversations did not :D

**Comment by iNPUTmice** [comment]
> please provide an adb logcat output of your failed connection attempts. 

without that there is literally nothing I can do

**Comment by TheHellstorm** [comment]
Ok, I will read into it and try. Working with the adb is not so easy without prior experience. Will take some time...

**Comment by iNPUTmice** [comment]
I'm closing this for now. Will reopen if op can provide a logcat output
