### ISSUE TITLE
Rouded avatars ?

### ISSUE THREAD

**Issue by Rupersia** [siacs/Conversations#1156]
Hi guys.

I'm making my own copy of this wonderful app but I'm making a few changes. Among them is the fact that I want rounded avatars for everyone. So, how is this possible ? what classes should I change ? Where to begin ? I'm a noob and I'm sorry if this ins't the right place for this kind of questions, I'm not used to Github. Please forgive me.

Thanks.

**Comment by jkufner** [comment]
I think I've seen feature request or maybe pull request for this some
time ago. Also there has been effort to add stripes next to avatar to
show status of each contact, which ended with unfortunately rejected
merge request. So, start with some searching, the code is already
somewhere around :)
