### ISSUE TITLE
Failed receiving files

### ISSUE THREAD

**Issue by vijai1996** [siacs/Conversations#1157]
Hello,
        I'm running a modified conversation. When I try to send a file to a user, it is sent fine upto 99% and then it says failed on the sender's side and "file deleted" on the receiver's side. The log doesnt say much. All I could find in log is:
```
could not find suitable candidate
sending fallback to ibb
received candidate error
opening encrypted input stream
```

May I know where or how the receive is failed? I know this is not a bug but still if you could answer, it would be great.

**Comment by Natureshadow** [comment]
I see file transfers failing reproducibly when using OTR. Disabling OTR, then sending a file, then re-enabling OTR works.

**Comment by vijai1996** [comment]
I guess invalid ssl is causing file transfer failure because I have 2 vhosts among one has a valid ssl while the other one uses the 1st vhost's ssl which means, its invalid. When I connect to valid ssl vhost, file transfer is successful. But connecting to 2nd host, it fails. I dont want to debug it further because the developer only closes the issues just like that. @Natureshadow
