### ISSUE TITLE
XEP-0313 working only intermittently

### ISSUE THREAD

**Issue by harpereaves** [siacs/Conversations#1158]
Running version 1.2.0 of Conversations on Android 4.4.4

XEPs available (according to Conversations) on the server:
0163
0191
0198
0237
0280
0313
0352

**Comment by iNPUTmice** [comment]
Is mam enabled for your account?

**Comment by harpereaves** [comment]
I don't know what that means and I've no idea how to do that or to find out whether it's been done. I'm new to XMPP. I haven't found anything in conversations that says anything about enabling XEPs for accounts.

**Comment by SamWhited** [comment]
MAM == Message Archive management == XEP-0313

**Comment by kriztan** [comment]
@harpereaves is using my server, where mam and mam_muc are activated. I think the problem is how to force Conversations to fetch the data, isn't it?

**Comment by harpereaves** [comment]
@kriztan but is mam being actiated the same thing as mam being enabled for my account?
mam is working fine with Gajim with the same account, if that's any help.

**Comment by iNPUTmice** [comment]
@harpereaves what are your symptoms? What have you tried to test MAM? Are your client and server time in sync?
Conversations will usually log (adb logcat) the MAM queries it is doing. This should give you a hint on what is happening.

**Comment by harpereaves** [comment]
@iNPUTmice With further testing, this problem seems to be intermittent. I tested again (deactivating my account in Conversations, then continuing to exchange some messages using Gajim, then reactivating my account in Conversations) and all but the last two messages appeared in Conversations. Then I tried the same experiment again and *none* of the messages sent/received by Gajim while account deactivated in Conversations appeared when account reactivated in Conversations. So apparently it was working for a bit, and then stopped. I don't know what I did that made it stop working (maybe I didn't do anything). Now that I know it's intermittent I may be able to narrow it down with further testing.

I don't know if server and client time are in sync and I dont know how to find out.
I also don't know how to find/read those logs.

**Comment by iNPUTmice** [comment]
> I also don't know how to find/read those logs.

The readme has a short part on this. You will either have to download the android dev tools (probably available in your repository) or use an android app that gives you access to it

**Comment by harpereaves** [comment]
Unfortunately I've not had any more time to look at this, and I don't expect to, and I've also stopped using XMPP with my friends in favour of Telegram which doesn't have XMPP's (potential) privacy features but does sync everything across all clients (across platforms) very nicely.
