### ISSUE TITLE
conversations@conference.siacs.eu doesn't exist

### ISSUE THREAD

**Issue by Natureshadow** [siacs/Conversations#1159]
The website says:

> Start out by searching our issue tracker for open tickets or
> get to know us in our group chat on conversations@conference.siacs.eu

Gajim says this room does not exist.

**Comment by iNPUTmice** [comment]
> Gajim says this room does not exist.

you should report that to the gajim bug tracker then probably.

**Comment by pramodwadkar** [comment]
I am not able register it shows the message server does not support registration

**Comment by SafwatHalaby** [comment]
You cannot register to a conference room. You should register somewhere else ([jabber.at](https://jabber.at), [Dukgo](https://duck.co/blog/post/2/using-pidgin-with-xmpp-jabber), etc.), and then join the conference using that account.

**Comment by sunil0688** [comment]
i also not able to login with my local ejabber. Jabber id is like this sunil@mum-at-w4-de013
