### ISSUE TITLE
Feature request: indicator when messages are delivered to server and indicator for every message separately

### ISSUE THREAD

**Issue by peter-greskovic** [siacs/Conversations#1160]
1.) I noticed that FB messenger has two stage "tick" indicator. I only speculate about its meaning, but it brought me to idea about this useful feature: let's show another indicator (e.g. smaller or inverted color tick) when the message is successfully delivered from my client to the server and then another indicator when the other client confirms reception like it is done now.

This would make debugging problems with undelivered messages much easier.

Undelivered messages can be fault of either client or server and most of the time it is a nightmare to determine which one is responsible. Readouts of the "delivered to server indicator" would make problem reports from normal users much easier to interpret.

2.) The message delivery can be very unreliable under certain conditions (some XMPP server software or configuration in conjunction with clients that are constantly on and off the network, such as smartphones in moving car or metro).

Right now the user can see that some of the messages were not delivered most of the time, but even that is not very clear in some situations: when two messages sent shortly after each other, they are merged into one block. In this case only one tick is displayed for both messages. This is a problem, because it can obscure the fact that the first message was missed and create confusion in the conversation.

Delivery indicators should be displayed for every message separately.

**Comment by Natureshadow** [comment]
Hi,

> 1.) I noticed that FB messenger has two stage "tick" indicator. I only
> speculate about its meaning, but it brought me to idea about this useful
> feature: let's show another indicator (e.g. smaller or inverted color
> tick) when the message is successfully delivered from my client to the
> server and then another indicator when the other client confirms
> reception like it is done now.

In my understanding, once the message gets a timestamp, it was
acknowledged by the server. Before that, it says "Sending…". So the
"first tick" is the display of the timestamp.

> 2.) The message delivery can be very unreliable under certain conditions
> (some XMPP server software or configuration in conjunction with clients
> that are constantly on and off the network, such as smartphones in
> moving car or metro).
> 
> Right now the user can see that some of the messages were not delivered
> most of the time, but even that is not very clear in some situations:
> when two messages sent shortly after each other, they are merged into
> one block. In this case only one tick is displayed for both messages.
> This is a problem, because it can obscure the fact that the first
> message was missed and create confusion in the conversation.

Which is another good reason to remove this odd bubble-merging-thing.

**Comment by iNPUTmice** [comment]
>  Before that, it says "Sending…". So the "first tick" is the display of the timestamp.

this is correct.

The merging is actually more or less 'intelligent'. It won't merge failed and received messages together. It also only merges 'upwards' in status. It won't show you a 'tick' for messages that are not received yet.

> Delivery indicators should be displayed for every message separately.

Delivery indicators should not be displayed at all because they are completly unecessary in the year 2015. Upgrade your servers (and clients)

**Comment by peter-greskovic** [comment]
> In my understanding, once the message gets a timestamp, it was acknowledged by the server. Before that, it says "Sending…". So the "first tick" is the display of the timestamp.

I completely missed that, thank you!

**Comment by peter-greskovic** [comment]
> The merging is actually more or less 'intelligent'. It won't merge failed and received messages together.

This is not my experience. I had many confused conversations and frustration due to this.

**Comment by iNPUTmice** [comment]
Ok I took a quick look at the code and turns out I was wrong on the upward part. But it certainly wont merge failed and non-failed messages together.

**Comment by peter-greskovic** [comment]
OK, here are screenshots of two clients - my client (ptr) was on a stable wifi network all the time. The other client (Sara) was on moving train and might or might not have unreliable connection at times. Both XMPP accounts were on the very same server, which is up to date and (to my knowledge) supports delayed message delivery (i.e. it should have delivered messages as soon as unreachable client would be online). Also, note that my client was online all the time, so when the moving client displays timestamp (deliveres message to server, as you say), there is absolutely no reason for it not to reach me.

https://drive.google.com/folderview?id=0BzgZvaB-tDu1bW1IMS1vV2N0dFE&usp=sharing

**Comment by peter-greskovic** [comment]
Also, perhaps the logs of the Prosody server may be of some use:
```
Apr 29 15:55:48 c2sb9bb20       info    Client connected
Apr 29 15:55:51 c2sb9bb20       info    Authenticated as sara@aoiy.eu
Apr 29 15:55:51 c2sa509a0       info    Disconnecting client, <stream:error> is: <stream:error><conflict xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Replaced by new connection</text></stream:error>
Apr 29 15:55:51 c2sa509a0       info    Client disconnected: Replaced by new connection
Apr 29 15:55:51 c2sa509a0       info    Destroying session for sara@aoiy.eu/phone (sara@aoiy.eu)
Apr 29 16:00:33 c2sce5b90       info    Client connected
Apr 29 16:01:13 c2sce5b90       info    Authenticated as sara@aoiy.eu
Apr 29 16:01:14 c2sb9bb20       info    Disconnecting client, <stream:error> is: <stream:error><conflict xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Replaced by new connection</text></stream:error>
Apr 29 16:01:14 c2sb9bb20       info    Client disconnected: Replaced by new connection
Apr 29 16:01:14 c2sb9bb20       info    Destroying session for sara@aoiy.eu/phone (sara@aoiy.eu)
Apr 29 16:09:20 c2sbe67d0       info    Client connected
Apr 29 16:09:21 c2sbe67d0       info    Authenticated as sara@aoiy.eu
Apr 29 16:09:22 c2sce5b90       info    Disconnecting client, <stream:error> is: <stream:error><conflict xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Replaced by new connection</text></stream:error>
Apr 29 16:09:22 c2sce5b90       info    Client disconnected: Replaced by new connection
Apr 29 16:09:22 c2sce5b90       info    Destroying session for sara@aoiy.eu/phone (sara@aoiy.eu)
Apr 29 16:11:04 c2sbe67d0       info    Client disconnected: closed
Apr 29 16:11:04 c2sbe67d0       info    Destroying session for sara@aoiy.eu/phone (sara@aoiy.eu)
Apr 29 16:11:04 c2scb61c0       info    Client connected
Apr 29 16:11:06 c2scb61c0       info    Authenticated as sara@aoiy.eu
Apr 29 16:21:55 s2sind9ab20     info    Incoming s2s connection
Apr 29 16:21:55 s2soutd5c310    info    Beginning new connection attempt to jabber.ccc.de (146.255.57.229:5269)
Apr 29 16:21:55 s2soutd5c310    info    sent dialback key on outgoing s2s stream
Apr 29 16:21:55 s2sind40120     info    Incoming s2s connection
Apr 29 16:21:56 s2soutd5c310    info    outgoing s2s connection aoiy.eu->jabber.ccc.de complete
Apr 29 16:21:56 s2sind9ab20     info    incoming s2s connection jabber.ccc.de->aoiy.eu complete
Apr 29 16:22:55 s2sind40120     info    Disconnecting (unknown host)[s2sin_unauthed], <stream:error> is: connection-timeout
Apr 29 16:22:55 s2sind40120     info    s2s disconnected: jabber.ccc.de->aoiy.eu (connection-timeout)
Apr 29 16:26:47 c2sc4bb20       info    Client connected
Apr 29 16:26:48 c2sc4bb20       info    Authenticated as sara@aoiy.eu
Apr 29 16:26:49 c2scb61c0       info    Disconnecting client, <stream:error> is: <stream:error><conflict xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Replaced by new connection</text></stream:error>
Apr 29 16:26:49 c2scb61c0       info    Client disconnected: Replaced by new connection
Apr 29 16:26:49 c2scb61c0       info    Destroying session for sara@aoiy.eu/phone (sara@aoiy.eu)
Apr 29 16:31:56 s2soutd5c310    info    s2s disconnected: aoiy.eu->jabber.ccc.de (closed)
Apr 29 16:32:24 s2sind9ab20     info    s2s disconnected: jabber.ccc.de->aoiy.eu (closed)
Apr 29 16:38:41 c2sa74450       info    Client connected
Apr 29 16:38:42 c2sa74450       info    Authenticated as sara@aoiy.eu
Apr 29 16:38:42 c2sc4bb20       info    Disconnecting client, <stream:error> is: <stream:error><conflict xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Replaced by new connection</text></stream:error>
Apr 29 16:38:42 c2sc4bb20       info    Client disconnected: Replaced by new connection
Apr 29 16:38:42 c2sc4bb20       info    Destroying session for sara@aoiy.eu/phone (sara@aoiy.eu)
```

**Comment by peter-greskovic** [comment]
well... i just noticed that the debugging was probably a waste of time since the issue was closed an hour ago. never mind.

**Comment by iNPUTmice** [comment]
I'm happy to help you with fixing the cause of your problems but that's different from introducing new ui elements.
does your server support stream management? from looking at the log it doesn't seem like it. or maybe conversations has trouble resuming the session.

**Comment by peter-greskovic** [comment]
if by "helping me to fix the cause of my problems" you mean that you want to work together on how to make your client and my server to deliver messages, then i'm happy to continue this conversation. if, however, you just want to explain me what it is that my server does wrong, then i'll be probably better off installing a client that happens to work with my server...

**Comment by iNPUTmice** [comment]
I'm more than willing to improve the reliability of Conversations. I'm however not willing to introduce UI elements to work around problems of unreliability that can easily be avoided by using a 2015 xmpp server.
Conversions is designed to work with state of the art xmpp technology like SM and MAM. if you don't want that you can use xabber or any other xmpp client.

**Comment by iNPUTmice** [comment]
I just realized from looking at the screenshots that we are talking about OTR encrypted messages here. We are shipping some OTR reliablity improvments with Version 1.3.0
OTR makes this stuff even more complicated. (Search for my various rants on OTR in this issue tracker)

Please make sure that you are using Stream Managment on your server this helps a lot with OTR. And stay tuned for version 1.3.0 (already available for beta testers)

Also note that I closed this issue because the feature request you are talking is in parts already implemented and in other parts considered to be not within the design goals. (I want to make Conversations reliable enough to not need delivery receipts any more)
I didn't not close this issue because I don't want to improve the reliabilty of Conversations where possible.

**Comment by peter-greskovic** [comment]
I am currently configuring my server to support session management (XEP-0198) and MAM (XEP-313) and I will see what that does.

And I was not proposing to add arbitrary UI features, just trying to make the real life easier. I don't want to rant any more... in ideal world you would be right - everybody would use the good technology and we would all agree on what it is. But the problem is that even though I am able and willing to run and configure my own "state of the art" jabber server, many people with whom I talk to will not do that. And even if they all did, the current state of the art for XMPP reliability is still somewhat shitty. Defining a sane standard for managing a chat of multiple users on multiple servers, each having multiple clients on unstable connections is simply a hard thing. So we can either all use WhatsApp, Messenger, whatever, or find some ways to make it easier to live with what we have - such as displaying stupid ticks to be sure that the message was delivered. And possibly something else.
