### ISSUE TITLE
connect server

### ISSUE THREAD

**Issue by norayr** [siacs/Conversations#1161]
Many XMPP clients like Pidgin or Xabber are able to use "connect server" option. I was not able to find similar option in Conversation's account settings which makes it impossible to connect to one of my jabber accounts which needs to specify custom connect server, which is not equal to server part of jid, right after '@' letter.

**Comment by SamWhited** [comment]
See [the readme](https://github.com/siacs/Conversations/#where-can-i-set-up-a-custom-hostname--port), and issues #1028, #962, #960, #952,  #942, #935, etc.
