### ISSUE TITLE
Crash when trying to attach a file in the locked mode

### ISSUE THREAD

**Issue by hearbeathorror** [siacs/Conversations#1162]
Hi,
Thanks for this project, its just been recent i have been looking into it, and there are some couple of issues that i have faced if you please help.

1. I don't seem to be able to send files even though it shows in the chatlist. As the other recipient using chat secure or even conversations does not seem to be receiving it. Is there a code change i need to make to make it work?
2. When i click on the lock button,  and then i send a file (an image for example) , the app crashes with the following error

    05-01 10:32:38.472: E/AndroidRuntime(19303): java.lang.NoSuchMethodError: No virtual method getPublic()Lorg/bouncycastle/crypto/params/AsymmetricKeyParameter; in class Lorg/bouncycastle/crypto/AsymmetricCipherKeyPair; or its super classes (declaration of 'org.bouncycastle.crypto.AsymmetricCipherKeyPair' appears in /data/app/eu.siacs.conversations-1/base.apk)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at net.java.otr4j.crypto.OtrCryptoEngineImpl.generateDHKeyPair(OtrCryptoEngineImpl.java:70)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at net.java.otr4j.session.AuthContextImpl.getLocalDHKeyPair(AuthContextImpl.java:266)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at net.java.otr4j.session.AuthContextImpl$MessageFactoryImpl.getDHKeyMessage(AuthContextImpl.java:92)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at net.java.otr4j.session.AuthContextImpl.handleDHCommitMessage(AuthContextImpl.java:710)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at net.java.otr4j.session.AuthContextImpl.handleReceivingMessage(AuthContextImpl.java:425)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at net.java.otr4j.session.SessionImpl.transformReceiving(SessionImpl.java:476)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at eu.siacs.conversations.parser.MessageParser.parseOtrChat(MessageParser.java:125)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at eu.siacs.conversations.parser.MessageParser.onMessagePacketReceived(MessageParser.java:546)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at eu.siacs.conversations.xmpp.XmppConnection.processMessage(XmppConnection.java:477)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:366)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:279)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:543)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:265)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:218)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:252)
05-01 10:32:38.472: E/AndroidRuntime(19303): 	at java.lang.Thread.run(Thread.java:818)
05-01 10:32:39.447: E/Vold(245): Failed to find mounted volume for /storage/sdcard1/Android/data/com.cleanmaster.mguard/files/
05-01 10:32:39.464: E/Vold(245): Failed to find mounted volume for /storage/sdcard1/Android/data/com.cleanmaster.mguard/files/
05-01 10:32:39.519: E/com.sprovider(20413): android.content.ReceiverCallNotAllowedException: BroadcastReceiver components are not allowed to register to receive intents
05-01 10:32:39.519: E/com.sprovider(20413): 	at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:195)
05-01 10:32:39.519: E/com.sprovider(20413): 	at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:184)
05-01 10:32:39.519: E/com.sprovider(20413): 	at com.sprovider.service.HandeService.initReceiver(Unknown Source)
05-01 10:32:39.519: E/com.sprovider(20413): 	at com.sprovider.service.HandeService.init(Unknown Source)
05-01 10:32:39.519: E/com.sprovider(20413): 	at com.sprovider.service.HandeService.<init>(Unknown Source)
05-01 10:32:39.519: E/com.sprovider(20413): 	at com.sprovider.service.HandeService.getInstance(Unknown Source)
05-01 10:32:39.519: E/com.sprovider(20413): 	at com.sprovider.utils.Tools.startHandleService(Unknown Source)
05-01 10:32:39.519: E/com.sprovider(20413): 	at com.sprovider.interfaces.SdkInterface.startServer(Unknown Source)
05-01 10:32:39.519: E/com.sprovider(20413): 	at com.sprovider.Sprovider$10.getDexInterface(Unknown Source)
05-01 10:32:39.519: E/com.sprovider(20413): 	at com.sprovider.a.b(Unknown Source)
05-01 10:32:39.519: E/com.sprovider(20413): 	at com.sprovider.a.b(Unknown Source)
05-01 10:32:39.519: E/com.sprovider(20413): 	at com.sprovider.b.handleMessage(Unknown Source)
05-01 10:32:39.519: E/com.sprovider(20413): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-01 10:32:39.519: E/com.sprovider(20413): 	at android.os.Looper.loop(Looper.java:135)
05-01 10:32:39.519: E/com.sprovider(20413): 	at android.app.ActivityThread.main(ActivityThread.java:5312)
05-01 10:32:39.519: E/com.sprovider(20413): 	at java.lang.reflect.Method.invoke(Native Method)
05-01 10:32:39.519: E/com.sprovider(20413): 	at java.lang.reflect.Method.invoke(Method.java:372)
05-01 10:32:39.519: E/com.sprovider(20413): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)

Could you please guide.
Thanks

**Comment by iNPUTmice** [comment]
The second one looks like a build error.

For the first one: Conversations method of file transfer is incompatible with ChatSecure. You should either teach ChatSecure Jingle File Transfer or Conversations ChatSecures method of FT (what ever they are using)

**Comment by hearbeathorror** [comment]
Hi, 

Thanks for the reply. i was wondering , for the first case, conversations to conversations file transfer also doesnt seem to show me a file transfer taking place :S..  i am doubting i am missing some things or some dependencies :( .. 

for point two, if its a build error, would files without the lock get transferred ? When i dont press the lock it does not crash. 

thanks

**Comment by iNPUTmice** [comment]
to debug conversations to conversations file transfer we would need much more information. Like an adb logcat output and a much more detailed explanation on what it is happening than just 'not working'

**Comment by hearbeathorror** [comment]
@iNPUTmice  - ya sir, true.. i was actually testing it device to device without attaching it to the system . il grab two devices and then send in the logs.

**Comment by iNPUTmice** [comment]
no reaction in 20 days. closing
