### ISSUE TITLE
Enforcing STARTTLS

### ISSUE THREAD

**Issue by robert-scheck** [siacs/Conversations#1163]
As far as I can see, STARTTLS is used if advertised by the server. But I can not see any option to enforce STARTTLS (so either connect via STARTTLS or do not connect at all). Or am I overlooking something?

**Comment by SamWhited** [comment]
This is the default. Plain connections are not allowed.

**Comment by robert-scheck** [comment]
If so, shouldn't this be explicitly mentioned at http://conversations.im/ as security feature?

**Comment by SamWhited** [comment]
I don't think that's so much a "security feature" as just "how things are done in 2015", and I suspect that's what Daniel was going for (though I don't want to put words in his mouth).

**Comment by iNPUTmice** [comment]
from the website:

> The communication between Conversations and the XMPP server as well as the communication between the individual servers is TLS encrypted.

**Comment by robert-scheck** [comment]
How could Conversations ensure that the communication between the individual servers is TLS encrypted (except using end-to-end encryption)? From XMPP perspective, TLS is a thing of s2s configuration, not of c2s.

A sentence like "Conversations does not support plaintext connections to the XMPP server, TLS encryption is mandatory" would have been what I was looking for. Maybe this addition can be made to the website through?

**Comment by SafwatHalaby** [comment]
>How could Conversations ensure that the communication between the individual servers is TLS encrypted

I'd be interested to know how that is done too. My guess is that the client can ask the server and the server will just say "Yes, I do encrypt s2s". Of course, servers can lie, theoretically.

**Comment by kriztan** [comment]
you can test the servers on https://xmpp.net 
If TLS is available on both servers the servers use it.
If you are still unsure use end-to-end encryption or allways chat with contacts on the same server.

**Comment by iNPUTmice** [comment]
> How could Conversations ensure that the communication between the individual servers is TLS encrypted

It can not ensure that directly but any decent server forces s2s encryption nowdays. You can either use the link @kriztan provided to check if your server requires STARTTLS on s2s links or ask your operator directly.
