### ISSUE TITLE
Certificate pinning and/or DANE support

### ISSUE THREAD

**Issue by robert-scheck** [siacs/Conversations#1164]
If the XMPP server uses a SSL certificate signed by a trusted CA (thus in the root CA bundle), there does not seem to be any option for manual certificate pinning. Alternatively DANE support would be great.

**Comment by Natureshadow** [comment]
+1 for DANE!

**Comment by iNPUTmice** [comment]
DANE support is now tracked here #2247

**Comment by robert-scheck** [comment]
Since when are older issues marked as duplicates of newer ones? It should have been the other way round…

**Comment by iNPUTmice** [comment]
@robert-scheck this issue here is an either/or that can't be tracked very well.
