### ISSUE TITLE
Last action crashes Conversations if no intent is installed

### ISSUE THREAD

**Issue by SamWhited** [siacs/Conversations#1168]
The last action button (formerly just the send button) causes Conversations to crash if it's displaying the location action and no location sharing app is installed.

To reproduce, send a location to someone, then uninstall the location app, then go back to that conversation and click the "share location" button in the send bar.

A bit contrived, and not likely to occur in the wild.

**Comment by iNPUTmice** [comment]
Isn't this fixed by 2582ece2105f98a7a20d72d8c8dc70772a48286f?

This can happen in the wild if you hard code the quick action to 'Send location' in the settings. But that’s intentional to guide users to the share location plugin.

**Comment by SamWhited** [comment]
On May 4, 2015 2:18:34 AM CDT, Daniel Gultsch <notifications@github.com> wrote:
>Isn't this fixed by 2582ece2105f98a7a20d72d8c8dc70772a48286f?
>
>This can happen in the wild if you hard code the quick action to 'Send
>location' in the settings. But that’s intentional to guide users to the
>share location plugin.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/siacs/Conversations/issues/1168#issuecomment-98605816

It just crashed for me (with that commit). I'll try it again tomorrow when I'm at a computer and can get a stack trace; I just wanted to file the issue so I wouldn't forget.

—Sam

-- 
Sam Whited
pub 4096R/54083AE104EA7AD3
