### ISSUE TITLE
[REQUEST] Configurable Action on double tap

### ISSUE THREAD

**Issue by thigg** [siacs/Conversations#1169]
I love this feature in hike. If you are double tapping the screen, it notifies the chat partner.
It would be nice to have a similar feature here.

If the screen is double-tapped in a chat a user defined message is sent. (For example: "<-" or "hey")

**Comment by Natureshadow** [comment]
Sounds like a job for a UI automation tool, not a chat client.

**Comment by thigg** [comment]
Could be, but thats much more effort.

Its just a nice feature if you want to write to a friend  and you assume that he didn't hear the notification

**Comment by iNPUTmice** [comment]
I actually kinda like this as an opt-in feature. Can be merged with #979

**Comment by iNPUTmice** [comment]
I looked into this. The problem with this is that double tab isn't a common pattern in Android.
