### ISSUE TITLE
XEP-0357 (Push Messages) support

### ISSUE THREAD

**Issue by devurandom** [siacs/Conversations#1171]
[XEP-0357](http://www.xmpp.org/extensions/xep-0357.html) defines semantics for a XMPP server to inform its users of new messages, so their XMPP clients can connect and receive the data.

This seems very useful to allow Conversations to reconnect automatically. (Currently it often gets stuck, and displays a disconnected notification with a "try again" button, that I have to tap manually. I assume there is some OS inherent issue that prevents Conversations from automatically reconnecting? Maybe receiving a GSM message would "unstuck" it, and allow it to revive its background service to reconnect.)

**Comment by SafwatHalaby** [comment]
Note that No GCM dependencies is part of Conversation's philosophy.

**Comment by devurandom** [comment]
Maybe it could be implemented as a plugin?

**Comment by iNPUTmice** [comment]
> Note that No GCM dependencies is part of Conversation's philosophy.

This. And reason to close.

> Currently it often gets stuck, and displays a disconnected notification with a "try again" button, that I have to tap manually. 

I'd rather much find other solutions to the problems you are describing maybe #1170 

Wild speculation by the way. Samsung phone and IPv6 network stack?

**Comment by devurandom** [comment]
Phone is a Samsung S4 Mini LTE, running CM 12.1 for serranoltexx.

The problem indeed occurs most often (but not exclusively - I'll pay closer attention) at a place connected by the German Unitymedia ISP, which uses [Dual-Stack-Lite](http://en.wikipedia.org/wiki/IPv6_transition_mechanism#Dual-Stack_Lite_.28DS-Lite.29). So my phone would get an private, NATed IPv4 address, but only the IPv6 address is routed globally.

**Comment by iNPUTmice** [comment]
@devurandom does your phone get an IPv6 address as well? Is your server available via IPv6? You can check that with adb.
Samsung phones have [massive problems with IPv6](http://developer.samsung.com/forum/board/thread/view.do?boardName=General&messageId=239890) and Samsungs reply seems to be to tell users to turn of IPv6. This even affects GCM

**Comment by devurandom** [comment]
I will check later whether my phone gets an IPv6 address. The server is available via IPv6 (confirmed that it works, both locally and via xmpp.net).

**Comment by iNPUTmice** [comment]
fwiw Conversations has now optional push support.
