### ISSUE TITLE
Sending/Receiving files fails. Deleted imediately upon arrival

### ISSUE THREAD

**Issue by DerFlob** [siacs/Conversations#1172]
Hello,
since a few weeks, I can't send or receive pictures or files any more. I am not exactly sure, since when, but it might coincide with the switch to Android 5.0. 
At first the transfer seems to start normal and progress is made (although rather slow). When the transfer reaches 100%, it fails. On the receiving side, the picture/file message says "The file has been deleted", on the receiving side, it just says "delivery failed".

I'm using a Samsung Galaxy S4, with the Resurrection Remix Rom, Android 5.0.2., the lastest (at the time 1.3.0) version of Conversations from F-Droid, but the previous (1.2.0) versions had the same problem. Before that I can't remember.
I know from two other users, who have both the HTC One M8 and are more or less recent nightlies of CM12, with Android 5.0. Both up to date Conversations.

Here is a logcat log of one transfer. Can I do something to increase the verbosity?
```
<message sent>
D/conversations(13572): derflob@domain.domain otr session established with jabber@domain.domain/mobile
W/Resources(13572): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f0d0066}
W/Resources(13572): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f0d0041}
I/wpa_supplicant( 9784): wlan0: CTRL-EVENT-SCAN-STARTED 
<message received>
D/conversations(13572): derflob@domain.domain: sending read marker to jabber@domain.domain/mobile
I/wpa_supplicant( 9784): wlan0: CTRL-EVENT-SCAN-STARTED 
<file transfer received>
D/conversations(13572): auto accepting file from jabber@domain.domain/mobile
D/conversations(13572): did not find a primary candidate for ourself
D/conversations(13572): received candidate error
D/conversations(13572): could not find suitable candidate
D/conversations(13572): receiving fallack to ibb
D/conversations(13572): opening encrypted output stream
<message received>
D/conversations(13572): derflob@domain.domain: sending read marker to jabber@domain.domain/mobile
<transfer completed and failed>
```

**Comment by vijai1996** [comment]
I have the same issue. I reported it (just slightly in a different way) and it got closed without stating any reason. Are you using a self signed ssl certificate or a commercial one?

**Comment by DerFlob** [comment]
I am using certificates issued by my private CA, the root cert of this CA is imported into the Android Certificate Store. It has been working before, with the private CA.

**Comment by DerFlob** [comment]
I haven't seen your report, because the last time I searched for this issue is a few days back.
I just tried sending a file with OTR disabled and it worked. It also was quick and not so slow as before. So it seems to be a problem combined with OTR encryption.

The SSL certificates shouldn't affect this. OTR isn't using them in any way.

**Comment by vijai1996** [comment]
It doesnt work for me in 2 case:
1. If I use a untrusted certificate (self signed or certificate with domain mismatch)
2. If I have OTR enabled on both sides. 
When I make sure the above 2 doesnt happen, It works for me

**Comment by vijai1996** [comment]
It is on issue #1157

**Comment by iNPUTmice** [comment]
I can reproduce this only when at least on of this devices is 5.0+
will see what I can do about this...

in the mean time quick workaround would be to enable proxy65 (file transfer proxy) on your server. this is generally a good recommendation anyway because this will vastly speed up your file transfers

**Comment by vijai1996** [comment]
I now enabled mod_proxy65 on my server and restarted ejabberd. Still, when I send files, it goes to 99% and fails.

**Comment by iNPUTmice** [comment]
please verify with adb that Conversations is actually using the proxy. you
might have to restart Conversations

**Comment by vijai1996** [comment]
Thank you. it says `connection to our own primary candidete failed` and I see its being logged while trying to establish a Jingle Socket5 connection (which directly translates to Proxy65?) I have enabled it on my server though with mod_proxy65: {} added in ejabberd config and restarting the server and reinstalling conversations multiple times

**Comment by iNPUTmice** [comment]
> I have enabled it on my server though with mod_proxy65: {}

I think the configuration has to go further than that. (assuming you literally just added this line)

> Jingle Socket5 connection (which directly translates to Proxy65?) 

Yes

**Comment by SamWhited** [comment]
> I think the configuration has to go further than that. (assuming you literally just added this line)

I'm pretty sure the defaults should be fine.

@vijai1996 did you open the correct ports in your firewall?

**Comment by SamWhited** [comment]
From the [guide](https://www.process-one.net/docs/ejabberd/guide_en.html#htoc57)

> *host: HostName*
> This option defines the Jabber ID of the service. If the host option is not specified, the Jabber ID will be the hostname of the virtual host with the prefix ‘proxy.’. The keyword "@HOST@" is replaced at start time with the real virtual host name.

**Comment by vijai1996** [comment]
I completely disabled firewall on server so every port was open. Reinstalled Conversation, enabled OTR --> failed transfer at 100%. WIll set up hostnames in proxy65 config later and check.
