### ISSUE TITLE
Invisibilty/low-priority?

### ISSUE THREAD

**Issue by jprjr** [siacs/Conversations#1173]
Hi there -

I've been using Conversations as my XMPP client, and I really like it.

I have ejabberd deployed at work, and I'll be logged in on my workstation (via Adium) along with Conversations.

Nearly all my coworkers strictly use XMPP from their workstations (never from home, a phone, etc), and they wind up treating an "available" status as "in the office" - but oftentimes I'm running around and not at my desk.

My workstation is setup to idle after a few minutes, and set my status to away - but I'll still show as available. I'll also forget to temporarily disable my account when leaving for the day and get messages from people.

I still want the client on my phone, since it's really handy to be able to message other sysadmins while I'm running around fixing this or that, but I'd prefer to let the workstation's status "win", or just not show as available at all if my phone is the only connected resource.

Is there anyway to accomplish that?

**Comment by timosl** [comment]
The FAQ in the [readme](https://github.com/siacs/Conversations#where-can-i-see-the-status-of-my-contacts-how-can-i-set-a-status-or-priority) explains this.
