### ISSUE TITLE
Datei Transfer extram Langsam

### ISSUE THREAD

**Issue by PhynixP** [siacs/Conversations#1174]
Hallo erst einmal ist das der beste XMPP Client der zurzeit für Android verfügbar ist. Leider ist der Dateiversand extrem langsam. Als Server benutzen wir Prosody 10 auf Debian 7. Server hat eine GBit-Anleitung und die Handy sind mit LDE oder Wlan mit max 4 MBit im Upstream möglich.
Doch eine kleine Datei oder Bild von 158kb braucht tatsächlich 3 Minuten.
Was Kann das sein ?

**Comment by andersruneson** [comment]
Use a file transfer proxy in prosody.

2015-05-07 11:09 GMT+02:00 PhynixP <notifications@github.com>:

**Comment by PhynixP** [comment]
Ok thanks i will test it thanks
Am 07.05.2015 11:11 schrieb "Anders Sandblad" <notifications@github.com>:
