### ISSUE TITLE
Add a possibility to exit Conversations

### ISSUE THREAD

**Issue by v2e** [siacs/Conversations#1176]
Yesterday I tried the Conversations program and found it very convenient. Particularly, its PGP-encryption ability is a huge advantage over another Jabber clients. 
However, it turned out to be impossible to turn this application off. It always sits in the background and connects the network each time I turn the Wi-Fi on. While this may be a desired behaviour for many users, it is not for me. So I suggest adding a simple action: "Exit" which would turn the process off instead of putting it to background.

Thanks!

**Comment by strb** [comment]
This has been discussed many times in the past. Please look for old closed issues on this topic.

**Comment by sereforg** [comment]
Indeed there are about half a dozen separate issues where this is mentioned, which tells me that:

 * This is something that at least a number of users expect to have.
 * The broken expectation causes uncertainty in the user.
 * The Android model, while having a number of good points, does not cover every use scenario. More to the point, it tries to emulate the "online world" on the device; for example I cannot shutdown Github--I can only log out. That's fine, but it does not take care of the other aspect: physical. Once I've logged out of Github, I *can* shutdown my browser and know that, as far as I am concerned, no more resources of mine are being consumed by my former activity. And that's where the Android model falls short in some cases.

**Comment by SafwatHalaby** [comment]
The Android model is not about "Annoy me with messages whenever I have 3g or wifi on".
If the devs don't want an exit button, how about making a button called "disable allow accounts temporarily"? A similar already exists in the menu, but it doesn't have an opposite "re-enable".

**Comment by SafwatHalaby** [comment]
Elaboration: It doesn't have to shutdown the app and free it from memory, It's only about going off the grid. This respects the Android model, and simultaneously fills a need the users are constantly begging for.

The features is already partially in place, just make the "disable all accounts" a global switch, **overrides** and not **overwrites** the online/offline preference of each account.
