### ISSUE TITLE
Conversations broadcasts all messages to any interested app though Pebble Message Intents

### ISSUE THREAD

**Issue by ashimokawa** [siacs/Conversations#1179]
Any installed app can just listen for  com.getpebble.action.SEND_NOTIFICATION read all incoming chat messages without requesting any permissions.

You could restrict the Intent with setPackage() to com.getpebble.android and maybe resend it to nodomain.freeyourgadget.gadgetbridge (a WIP FOSS replacement for the official app)

**Comment by iNPUTmice** [comment]
This should definitely be fixed. Care to send in a pull request?

**Comment by ashimokawa** [comment]
see PR #1180
