### ISSUE TITLE
Sometimes last MUC message is double received

### ISSUE THREAD

**Issue by pythonimus** [siacs/Conversations#1181]
![screenshot_2015-05-08-23-24-49](https://cloud.githubusercontent.com/assets/1097383/7545977/07b382de-f5da-11e4-97d0-962ce14b677e.jpg)

I'm on last HEAD with a prosody server installed only carbon copy as extra module.
Sometimes Conversations receives the last MUC message again a few hours later.
Double MUC message is not in the history backlog.
Smartphone was connected to stable WLAN.

**Comment by iNPUTmice** [comment]
duplicate detection should be much better in current HEAD
