### ISSUE TITLE
vcard avatars not working for foreign servers

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1183]
I'm using latest 1.4.0 alpha from PlayStore and noticed, that the r/o support for vcard avatars is not working for foreign servers. There are no vcard avatars shown in Conversations, although gajim or xabber are able to show them. The vcard avatars from users on my server are shown in Conversations.

**Comment by cloudjanak** [comment]
on hosted.im server also not working.

**Comment by iNPUTmice** [comment]
Do your contacts announce the avatar hash in their presence?

**Comment by kriztan** [comment]
How can I check this? I cant' find any information about presence or vcard or avatar in the ADB logs.

**Comment by iNPUTmice** [comment]
probably best with a desktop client that has an xml console

**Comment by kriztan** [comment]
I've checked this via gajims xml console and there were no  <photo> tags inside the <presence> parts of this users. But Gajim fetches the avatars on loading the whole vcard.

**Comment by iNPUTmice** [comment]
I see. this is a won't fix then. we can't get into polling random people's
vcards at arbitrary intervals
