### ISSUE TITLE
OpenPGP Messages not encrypted to self after OpenKeychain update

### ISSUE THREAD

**Issue by github-k8n** [siacs/Conversations#1184]
With old OpenKeychain, messages were always encrypted to self, thus you could read your own messages on another device when using carbon copy.
With OpenKeychain 3.2 , that does not work anymore as it looks as if the sender is not automatically added to the encryption recipients.

Please ensure that the message is also encrypted to the sender's key.

**Comment by Draghtnod** [comment]
Same problem here.
https://github.com/siacs/Conversations/blob/development/src/main/java/eu/siacs/conversations/crypto/PgpEngine.java
Line 136 adds only the remote key id, not the own one.

**Comment by iNPUTmice** [comment]
@Draghtnod care to send in a pull request?

**Comment by Draghtnod** [comment]
Sorry i don't have a development/test environment for Conversations. :/

**Comment by github-k8n** [comment]
OpenKeychain 3.2.1 readded encrypt to self, so this should no longer be an issue.

**Comment by Draghtnod** [comment]
Confirmed. Just got the OpenKeychain 3.2.1 update and i can read my own messages again. \o/

**Comment by github-k8n** [comment]
As long as OpenKeychain keeps the current behaviour I think we can close the issue, closing.
