### ISSUE TITLE
Thumbnails for shared files

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#1186]
Conversations create a thumbnail for shared pictures but it doesn't with videos, audios and any other file. It would be cool to have them too.

**Comment by tigre-bleu** [comment]
I agree that the "Open Video" button is the UI blackspot in the otherwise very clean design.

**Comment by iNPUTmice** [comment]
There are thumbnails for videos. Having thumbnails for other type of files is not on our todo list.
