### ISSUE TITLE
Request: Add option to restrict file transfers to SOCKS5 Bytestream (mod_proxy65) proxy

### ISSUE THREAD

**Issue by deoren** [siacs/Conversations#1187]
Hi,

Thanks in advance for reading this. Please let me know if I can supply additional information and I'll be happy to do so.

## Setup

* Client: Conversations 1.3.1
* Server: Prosody 0.10 nightly (latest)

## Background

Last September one of the developers for Prosody (Kim "Zash" Alvefur ) released a small module called "mod_proxy65_whitelist". This module successfully forced Conversations to use the file transfer proxy which Prosody provides instead of trying to use direct transfers (which fail due to firewalls). 

File transfer speeds went from very slow (what they are now) to near instantaneous. It was amazing. Sometime in recent months file transfers fell back to old speeds. At best they take a full minute (which is mostly acceptable, but still slow), but 3-10 minutes for a sub 30 KB file is not uncommon now.

I assumed the problem was the module itself, so I reported the issue to the Prosody Users list to see if others were affected. Kim was the only one to reply.

Kim suggested:

* Fixing firewalls
* Asking the Conversation developers about improving proxy selection code

The box hosting the Prosody server has the port open to world, so that end should be fine. I of course can't account for networks between clients, which is why I'd like to force them to use the server for all file transfers so they're more reliable. 

## Goal

I'd like to restrict Conversations to using only the file transfer proxy that Prosody provides. 

It appears that we have to wait for client-to-client transfers to time out and fall back to client-to-server transfers to begin, so I'd rather cut out the wait time and just have the clients go directly to the server to start with.

Accomplishing this server-side would be preferable because all clients would be affected (we run a private XMPP server with all clients aware of the particulars of the setup), but a client-side setting would be helpful.

## References

* [Is the proxy65_whitelist module compatible with recent 0.10 nightly builds?](https://groups.google.com/forum/#!topic/prosody-users/XYSiYiZdnp0)
* [Help with mod_proxy65](https://groups.google.com/forum/#!searchin/prosody-users/mod_proxy65_whitelist/prosody-users/Mzib2u2FOfw/3pEBVuwBhiEJ)
* [BIND zonefile with proxy65 record](http://www.wensley.org.uk/xmpp/zonefile)
  * I can't find other examples, so I assume the specific zone entry isn't valid

**Comment by iNPUTmice** [comment]
Are we talking Conversations to Conversations ft here? Because in that setup Conversations will not try to establish a p2p connection. (Given that mobile connections are almost always NATted there is no point)
it will only fall back to ibb if there is no proxy being offered on either side.

**Comment by deoren** [comment]
@iNPUTmice Yes. Both clients are running Conversations. My Nexus 4 (Android 4.4.4) is running the copy of Conversations from the Google Play store. The other client is a Galaxy S5 using Conversations from F-Droid.

Most of the time both of our devices are connected to local WiFi networks, but occasionally one or both of them are on cellular networks.

**Comment by deoren** [comment]
@iNPUTmice I notice that you closed my request. 

Is that because you don't consider this something worth fixing or a non-issue because the clients don't try to deliver directly to each other? In what scenarios would the clients try to deliver directly?

Do you have any suggestions for troubleshooting the delays?

**Comment by iNPUTmice** [comment]
if I understand you correctly this issue was about preferring proxied connection over direct connections. Conversions is already doing this. this is way I closed your issue.

**Comment by deoren** [comment]
@iNPUTmice Thanks for the response. This request _was_ about preferring a proxied connection over direct connections, but it was specifically about limiting transfers to only the file transfer proxy provided by the server that both clients are using.

* Is this the way Conversations is already setup?
* If I wanted to troubleshoot our server setup to confirm that it is properly offering a proxy to the clients, what should I look for?

Thank you for your help.

**Comment by iNPUTmice** [comment]
> Is this the way Conversations is already setup?

Yes

> If I wanted to troubleshoot our server setup to confirm that it is properly offering a proxy to the clients, what should I look for?

[README.md](https://github.com/siacs/Conversations/blob/development/README.md#how-do-i-debug-conversations)
