### ISSUE TITLE
Validate Subject Alternative Names in Certificates

### ISSUE THREAD

**Issue by jas4711** [siacs/Conversations#1189]
When I connect to my chat server I get a warning:  "Accept Mismatching Server Name? Server could not authenticate as "josefsson.org".  The certificate is only valid for: [2] chat.sjd.se".  My JID is simon@josefsson.org and through SRV records my chat server is chat.sjd.se.

However, the certificate presented by my server contains the PKIX SRV-ID identifier type as described in RFC 6120 section 13.7.1.2.1: https://tools.ietf.org/html/rfc6120#section-13.7.1.2.1 Thus I believe it should be able to read out from the certificate the 1.3.6.1.5.5.7.8.7 extension which says "_xmpp-client.josefsson.org" and use that to validate the use for "josefsson.org".

Let me know if I'm missing something.  Some more info about my PKIX certificate setup is available here: http://blog.josefsson.org/2015/05/12/certificates-for-xmpp-jabber/

**Comment by iNPUTmice** [comment]
Do other xmpp clients work with this setup?
Not saying this shouldn't be fixed. But I don't understand why you are
trying to make things complicated.

**Comment by jas4711** [comment]
I'm using GNOME's empathy and it hasn't complained.  (To be honest, that doesn't prove anything -- maybe it just accepts anything.)

What's complicated about it? I'm trying to follow the RFC...

**Comment by iNPUTmice** [comment]
I'm just wondering why you are not simply putting the domain in the CN (josefsson.org in your case) like most people [citation needed] do it.

Again. I'm not saying you are doing something wrong I'm just wondering about the upsides to your approach.

**Comment by jkolo** [comment]
Hi. I have same problem. I have own domain. I'm using Google Apps for XMPP, so certificate is for google domain and i cannot add to certificate my domain.

**Comment by iNPUTmice** [comment]
@jkolo I actually don't think this is the same problem. You could simply add a certificate to your Google Apps.

**Comment by iNPUTmice** [comment]
@jas4711 are you still running your server with that kind of certificate? I might need some server to test this with if I'm going to fix this.

**Comment by jas4711** [comment]
Yep, XMPP listening on chat.sjd.se with that cert.  Feel free to use it for testing!
