### ISSUE TITLE
Issue: My own Avatar is not getting reflected to my own application after publishing .

### ISSUE THREAD

**Issue by VedantaBabaria** [siacs/Conversations#1190]
After Publishing my Avatar, it is getting reflected to my contact list but no reflection is seen on my own client application. It shows the default Avatar(with initial's letter) or last reflected Avatar.

Observation: It is been observed that after I exit the app or kill my app from recent app list from home , and then again relaunching the application reflect my avatar on my application(before getting logged in again). First I thought this might be an issue of presence, so I tried to handle the presence also but no useful results.

Using Conversation ver: 1.4.0 alpha.

**Comment by iNPUTmice** [comment]
please provide steps to reproduce

**Comment by VedantaBabaria** [comment]
Steps to reproduce:

> Open Manage Accounts.
> Select  an account.
> Click on Avatar.
> Choose an Avatar to upload.
> Click on Publish button.

Toast appears: "Avatar has been Published".


Expectation: Selected Avatar should get reflected at my side and at all the instances(ex. Account Details, chat window with contacts, Publish Avatar activity).

Reality: The Published Avatar is successfully received by the subscribers (ie: friend's), but neither it reflects on my own ImageView of Avatar nor anywhere throughout the application.

Additional information:

Device: Sony Xperia s(lt26i), Moto-g, Moto-E, etc.
OS: CyanogenMod 12 (for Xperia), Official Android 5.0.2 (for rest of the devices)
XMPP Server: OpenFire(3.10.0)

**Comment by iNPUTmice** [comment]
Does 6489ddac6c6d3d6eced35ab4640963eb15667bb5 fix this for you?

>

**Comment by VedantaBabaria** [comment]
@iNPUTmice  : thanks a lot dude, for this fix! It's working now. (y)
