### ISSUE TITLE
While Switching Account Previous Account message is displaying

### ISSUE THREAD

**Issue by manivendhan** [siacs/Conversations#1192]
While switching from one account to another account. The conversations history is displaying in another account too. Need to close all conversations while switching account.

**Comment by iNPUTmice** [comment]
what do you mean by switching account?

please provide steps to reproduce

**Comment by manivendhan** [comment]
While we configure another account by manage account ->add new account.
Then starting new conversation with recently added account... The
Conversation held on old account displays too. If the account is switched
the corresponding account messages can be displayed.
what do you mean by switching account?

please provide steps to reproduce

—
Reply to this email directly or view it on GitHub
<https://github.com/siacs/Conversations/issues/1192#issuecomment-101707426>.

**Comment by iNPUTmice** [comment]
You mean you see the 'old' conversation in the Conversation overview as well? Or do the messages get mixed into each other?

**Comment by manivendhan** [comment]
Old account conversation mixed with new account in conversation view

**Comment by iNPUTmice** [comment]
Thats whats supposed to happend. You are not switching accounts you are
adding one. You can delete the old account though. This will also get rid
of the associated conversations.

**Comment by manivendhan** [comment]
If Possible can you say me how to display the corresponding account messages at conversation view while any of the account is temporarily disabled

**Comment by iNPUTmice** [comment]
for general questions please step by our conference (see README.md for the
address)

**Comment by manivendhan** [comment]
Thanks for your kind reply sir.
