### ISSUE TITLE
Enable Heads-up Notifications

### ISSUE THREAD

**Issue by pythonimus** [siacs/Conversations#1194]
Why are heads-up notifications not enabled on Conversations?
I'm in a fullscreen activity and the phone just vibrates on new message.
Whatsapp is displaying a heads-up notification.

**Comment by iNPUTmice** [comment]
to my knowledge this is nothing the app can decide. The system will decide this based on *criteria*

**Comment by SamWhited** [comment]
If I'm not mistaken (and disclaimer, I very well may be as I didn't research this at all) this requires marking your notifications as being high priority, which is probably not something we want to do.

There may be other ways though — I set notifications to be of type chat in a previous commit, so maybe you can just turn up the priority of chat messages at the system level (I have no idea if it exposes this anywhere, but I know that was the idea at one point)?

**Comment by iNPUTmice** [comment]
> this requires marking your notifications as being high priority,

I would assume so too. But the official documentation is full of sentences like *this might increase your chance of getting displayed as a heads up notification*

> which is probably not something we want to do.

heads up notifications are by their own definition something that requires immediate attention. Like a telephone call. An instant message definitely is not something that does.

**Comment by pythonimus** [comment]
Even Google's Messenger app uses heads-up notifications for incoming SMS.
Would be nice if Conversations had a per contact or global setting to set these notifications to high priority.

**Comment by hermann-san** [comment]
on my SlimRom 4.4.4 I can enable heads-up for specific apps. So it's disabled be default be can be enabled for Conversations. 
In the notification bar long press on the new Conversations message and select "enable heads up"

**Comment by iNPUTmice** [comment]
Fixed in 1.19.0
