### ISSUE TITLE
Receiving pictures fails

### ISSUE THREAD

**Issue by mistersixt** [siacs/Conversations#1195]
Hi,

on my Moto G (2013) running Cyanogenmod-12.1 I am having issues with receiving pics, adb logcat is showing:

D/conversations(22220): auto accepting file from mistersixt@jabber-germany.de/nexus 4
D/conversations(22220): did not find a primary candidate for ourself
D/conversations(22220): established connection with socks.jabber-germany.de:7777
D/conversations(22220): received candidate error
D/conversations(22220): candidate d3o79ac2nn was a proxy. waiting for other party to activate
D/conversations(22220): we were responding. receiving file

And both Conversation clients (pic was sent with Conversations 1.3 on Nexus-4) report "File transfer failed".

It is with the latest version 1.3 on this Moto-G, any help is welcome.

Kind regards, mistersixt.

**Comment by iNPUTmice** [comment]
If you update to latest HEAD Conversations will be a bit more verbose on why the file transfer failed

**Comment by mistersixt** [comment]
How do I checkout this "HEAD" version, and I do I need to compile it? Any help is welome,

regards, Joerg,

**Comment by iNPUTmice** [comment]
>  and I do I need to compile it?

either that or you wait a couple of hours until it is available in the [beta channel](http://conversations.im/#beta) - I'm gonna push 1.4.0 beta soon.

**Comment by iNPUTmice** [comment]
1.4.0 is out

**Comment by mistersixt** [comment]
With Conversations 1.4 (on both sides) logcat on my Moto G is showing this:

D/conversations(10172): xyz@jabber-germany.de: acknowledging stanza #31
D/conversations(10172): auto accepting file from mistersixt@jabber-germany.de/nexus 4
D/conversations(10172): did not find a primary candidate for ourself
D/conversations(10172): xyz@jabber-germany.de: acknowledging stanza #32
D/conversations(10172): established connection with socks.jabber-germany.de:7777
D/conversations(10172): received candidate error
D/conversations(10172): candidate aek6173q30 was a proxy. waiting for other party to activate
D/conversations(10172): xyz@jabber-germany.de: acknowledging stanza #33
D/conversations(10172): xyz@jabber-germany.de: acknowledging stanza #34
D/conversations(10172): we were responding. receiving file
D/conversations(10172): xyz@jabber-germany.de: acknowledging stanza #36
D/conversations(10172): xyz@jabber-germany.de: open failed: EACCES (Permission denied)
D/conversations(10172): xyz@jabber-germany.de: acknowledging stanza #37

Regards, mistersixt

**Comment by iNPUTmice** [comment]
have a look at this second to last line. permission denied. this looks like
privacy guard or what ever is preventing access to the SD card.

**Comment by mistersixt** [comment]
What path/folder is Conversations trying to store the data into? Maybe this leads to a direction I can look into.

Receiving data with TextSecure or Threema is working fine, and there is no privacy guard running or something.

As Conversations is running fine on all other devices from me and my friends I assume something is wrong with my Moto G to be honest, I don't think it is a bug in the software, I would like to know the root cause of the issue though ;-) .

Thanks, mistersixt.

**Comment by iNPUTmice** [comment]
Conversations stores images to the sdcard. A quick google for the EACCES (Permission denied) tells you to make sure your PC has not mounted the sd card as a USB device.

**Comment by mistersixt** [comment]
Ok, found it: when trying to write into /sdcard/Pictures/Conversations/ I got "Permission denied" even with "adb shell". After deleting and recreating that folder everything is working as expected again. Looks like it was a f2fs filesytem issue (for sure not a Conversations issue).

So issue ticket can be closed, thanks for the help and hints!
