### ISSUE TITLE
No support forum

### ISSUE THREAD

**Issue by sereforg** [siacs/Conversations#1196]
I've been through this project's bugtracker and I've seen a few comments along the lines of "this is a bugtracker not a support forum".

So **where** is the support forum then?

**Comment by andersruneson** [comment]
Welcome to the chat:

https://github.com/siacs/Conversations/blob/development/README.md#conversations-doesnt-work-for-me-where-can-i-get-help

**Comment by sereforg** [comment]
I was about to add an edit concerning that. So if I install your application but it doesn't work, in order to get support I need to install another XMPP client? And if that client does work, why would I want to move back to yours? Seems a bit of a self-defeating approach. :-P

**Comment by SafwatHalaby** [comment]
>I was about to add an edit concerning that. So if I install your application but it doesn't work, in order to get support I need to install another XMPP client? And if that client does work, why would I want to move back to yours? Seems a bit of a self-defeating approach. :-P

Haha.
