### ISSUE TITLE
Make "Disable all accounts" a global switch

### ISSUE THREAD

**Issue by SafwatHalaby** [siacs/Conversations#1199]
Currently, "disable all accounts" is a "global overwriter", it simply sets all the accounts to the "temporarily disable" state. Consequently, it cannot be reversed. You cannot re-enable only the accounts that were enabled before clicking that button.

I propose a simple change: "disable all accounts" should be a global switch, which does not modify the individual accounts' state. Instead, in overrides those states and makes all accounts log off. When it's clicked again, the individual accounts' online/offline states are respected again and only the accounts that were previously online re-connect.

**Comment by SafwatHalaby** [comment]
I'm willing to make a PR if the devs are interested in this.

**Comment by jkufner** [comment]
This was discussed many times and without satisfying results. I believe
it have a good chance to be accepted.

**Comment by SafwatHalaby** [comment]
I should note that the the feature is already but it behaves in a non-optimal way. What's wrong with fixing it?

**Comment by SamWhited** [comment]
There's never anything wrong with fixing it :) if you can submit a PR, please do!

**Comment by iNPUTmice** [comment]
will I have no problem with that app I wonder how many accounts you people have that this actually becomes a problem.  I mean with the quick switches in place now it's really not much work to enable two or three accounts in a list.

**Comment by SafwatHalaby** [comment]
Personally, I have 1 account. But fixing this has a real utility nevertheless: It would rid you of those people shouting "you don't have a logoff" button.

**Comment by iNPUTmice** [comment]
> Personally, I have 1 account. But fixing this has a real utility nevertheless: It would rid you of those people shouting "you don't have a logoff button".

I don't give a f* about two or three people shouting.

I mean lets face it. 75% of Conversations users have one or two account which both are enabled 100% of the time. (Imagine one of the accounts being a legacy account on an old server or something) Another 20% use Conversations with their work account. At 9 am the go into manage accounts, touch the switch next to their work account and are online. At 5 pm they do the reverse.

I would really like to know what the other 5% are doing that they can not be bothered to selectively touch all the accounts they would like to activate or deactivate. 

Implementing features just to shut up a couple of people on the internet is definitely not a good idea.

**Comment by SafwatHalaby** [comment]
Fair enough.
