### ISSUE TITLE
[Request] Add icons for the attach options

### ISSUE THREAD

**Issue by logos88** [siacs/Conversations#1200]
Hello. Is just a very simple idea but I think it would be nice to have little icons next to the send options, like a camera next to Take a photo or a map next to send ubication. I think it would be more intuitive. Maybe little flat black and white icons would be enough.

**Comment by jkufner** [comment]
Yes it is. It makes user interface look more friendly. For example [FontAwesome](http://fontawesome.io/icons/) is nice collection of icons (not sure if format is good for Android app).

**Comment by conrad-heimbold** [comment]
see issue #2252 , do those icons look good?

**Comment by vikiCoder** [comment]
Hello, I would like to work on this issue.

## Is this the wanted feature?

![design](https://cloud.githubusercontent.com/assets/16588032/23474226/0b81f9d6-fed9-11e6-94d2-2e41511010a6.png)

**Comment by iNPUTmice** [comment]
@vikiCoder yes.

**Comment by vikiCoder** [comment]
Can I start working on it?
