### ISSUE TITLE
Private message reset/Overwrite Avatars

### ISSUE THREAD

**Issue by dinklebob** [siacs/Conversations#1203]
When I accidentally click on someone's name, it targets them for private messaging and I don't know how to reset it other than punting to the settings page. Could a button or option toggle be set for private/normal messaging? 

Also, I am in a large group where no one has custom images. I'd like to set everyone's avatar to their in-game character's image, which could be overwritten if they choose their own avatar. Could this functionality be added? A client-side overwrite of the default?

**Comment by iNPUTmice** [comment]
> When I accidentally click on someone's name, it targets them for private messaging and I don't know how to reset it other than punting to the settings page. Could a button or option toggle be set for private/normal messaging? 

You can click the send button with an empty message to reset. However this has been made clearer in 1.4.0 where the send button turns into an X in that case.

> Also, I am in a large group where no one has custom images. I'd like to set everyone's avatar to their in-game character's image, which could be overwritten if they choose their own avatar. Could this functionality be added? A client-side overwrite of the default? 

it is very difficult to identify users in a anonymous muc. However if you use non-anonymous it already shows avatars of people you have in your roster.
