### ISSUE TITLE
Message delivered multiple times

### ISSUE THREAD

**Issue by allo-** [siacs/Conversations#1206]
When i am sending an unencryted message to an offline account, the message gets delivered many times, when the account comes back online (at the moment for example 5 times), while Conversations still states "sending ...". After some days, Conversation changes to "failed to deliver".

Sending account at jabber.org, receiving account is a prosody server used with pidgin. pidgin further tells me:

    (19:27:59) The following message from SENDER was not encryted: [MESSAGE]

And marks the conversation as OTR-unverified, while Conversations clearly states "plaintext" (not sure, if this matters for the bug).

**Comment by iNPUTmice** [comment]
Please upgrade to version 1.4.0 and provide an adb logcat output of your sending client while sending messages. Messages should not get stuck at sending for this long. (Sending should only be there for a few seconds till the server acknowledges the message.)

**Comment by iNPUTmice** [comment]
1.4.0 is out by the way

**Comment by allo-** [comment]
Do i need to enable debug mode somewhere? I do not get many messages from Conversations at all.

**Comment by iNPUTmice** [comment]
No there is no special debug mode. Just filter for the conversation tag (if
in doubt see README.md)

**Comment by allo-** [comment]
Hmm, i did not had many messages on a logcat without filters.
But i will have another look at it.
Can there be a problem with stream management and accounts, which time out instead of clean disconnection? I often put my pc into suspend and the jabber connection (which receives the multiple messages) gets a timeout instead of a disconnection.

**Comment by allo-** [comment]
05-22 23:17:06.094 D/conversations(30936): user@host send ping
    05-22 23:17:07.194 D/conversations(30936): user@host2 send ping
    05-22 23:17:07.334 D/conversations(30936): user@host2: server acknowledged stanza #21
    05-22 23:17:07.644 D/conversations(30936): app switched into foreground

Sending a message: no log at all

A bit later:

    05-22 23:17:46.494 D/conversations(30936): app switched into background
    05-22 23:18:16.215 D/conversations(30936): user@host: acknowledging stanza #96
    05-22 23:18:16.235 D/conversations(30936): user@host: server acknowledged stanza #23

If i go off and on again with pidgin:

    05-22 23:20:57.184 D/conversations(30936): user@host: acknowledging stanza #115
    ...
    05-22 23:21:08.144 D/conversations(30936): user@host: acknowledging stanza #133

This could be the number of "sending ..." messages. 
But no messages are sent to pidgin directly after going online, so it does not seem to retry just after the user came online.

**Comment by iNPUTmice** [comment]
are there log messages like `requesting ack for message stanza ...`
Could you publish the entire log. (Filtered for Conversations of course)

also is this for OTR or for unencrypted messages.

**Comment by allo-** [comment]
This WAS the complete log during some online time and sending a message.

That's why i asked for debug options. This is very little logging going on there ...

**Comment by iNPUTmice** [comment]
OK. there seems to be a bug in Conversations that happens only on mlink
servers. I think I have a fix but I'm only on my cell phone and I don't
have write access to the phone. However if you take a look into
XmppConnection.java line 924 in sendPacket()  a part of the condition is
this.streamId! =null if you change that part to getFeatures().sm() this bug
should be fixed.

**Comment by allo-** [comment]
Very cool, how you found this with that little log :-).
I never build Conversations, but i could test a debug build, if you provide one.
Or try some more steps how to reproduce it, if you now know what exactly is causing it. At the Moment i still have 11 Messages popping up, for example when i went online today.

**Comment by iNPUTmice** [comment]
fixed in 36034815ee34c9a48c5236329914439bd5885179

**Comment by allo-** [comment]
Seems to work with the current release from google play. Thanks.

**Comment by allo-** [comment]
Version 1.6.3 has the problem again.

**Comment by iNPUTmice** [comment]
allo- please describe in more detail the effects you are seeing. Do messages get stuck at sending... even though they have arrived at the recipient?

**Comment by allo-** [comment]
I upgraded today and messages sent to an offline jabber account in plaintext are stuck at "sending ...".
I thought this problem may be related or the same.

**Comment by iNPUTmice** [comment]
Sorry I just introduced the same bug again. I fixed version should be available very soon on the beta channel.

**Comment by allo-** [comment]
Thank you for the fast fix.

**Comment by iNPUTmice** [comment]
you should join the beta channel though: http://conversations.im/#beta

**Comment by allo-** [comment]
I do not have / do not want Google+ and it seems the channel only works if you have it.
