### ISSUE TITLE
Fails to send image when DCIM/Camera don't exist

### ISSUE THREAD

**Issue by QuentinC** [siacs/Conversations#1210]
Hi, I have this problem since I deleted the Camera folder under DCIM.

I think that a little fix should be to check thar the folder exists, and create it if not !

Thanks !

**Comment by iNPUTmice** [comment]
I'm assuming we are talking about the 'take picture' method?
What error messages are you getting where?

Because I just tried to replicate this by renaming the Camera Folder to
Camera2 and it worked as expected and Conversations recreated the Camera
folder.

**Comment by QuentinC** [comment]
May be me so, Is your app creating the Camera folder or the Camera app ?
I'm using the Xperia camera, there may be differences ?

**Comment by jkufner** [comment]
Conversations should not create any folder when taking photo. It should
receive filename of taken picture from camera app. Creating such folder
is out of Conversation's scope.

**Comment by QuentinC** [comment]
Great ! This is what I was thinking about !
But, in the sources, we can see that Conversations gives the filename to Camera app. So, Camera has to ensure that the filename is created !
What about if it don't create directories ? 

Shouldn't it be better to get from Camera the filename created ?

This is just suggestion of course !

**Comment by TameOfGroans** [comment]
OT

Is there a virtual camera app to deliver pictures to other apps expecting/allowing-only a camera? [(meta)sanitizing files]

**Comment by iNPUTmice** [comment]
Turns out Conversations didn't actually create the folder due to a typo. This has been fixed in latest HEAD.
