### ISSUE TITLE
Options to disable OTR

### ISSUE THREAD

**Issue by Natureshadow** [siacs/Conversations#1214]
I would like to be able to disable OTR completely as it causes trouble with other clients. I like using OpenPGP for message encryption sometimes, but OTR is automatically used if the other party enables it opportunistically.

Can an option be added to disable and not advertise OTR support?

**Comment by iNPUTmice** [comment]
Conversations does not 'advertise' OTR support. It also does not react to magic white spaces exactly to avoid these accidental activations.
If other clients still activate OTR without your consent it is time to fix those clients instead of introducing more configuration options into Conversations.
