### ISSUE TITLE
[Feature] Show who has joined/Left MUC as status message

### ISSUE THREAD

**Issue by vijai1996** [siacs/Conversations#1219]
Hello,
I think it would we worth showing a status message for the contacts who has joined or left the MUC chat room. Currently, there is no way to know who was added by whom and you could only know the person was added when you constantly keep an eye on the muc members from group settings.

**Comment by timosl** [comment]
This would probably spam the chat with info messages if people have to reconnect on their mobile connection or if the background service is getting restarted by Android. Maybe displaying this information if a user joins for the first time would suffice?

**Comment by vijai1996** [comment]
Yes. That is what I mean. Show only when the user is added for the first
time or when the user leaves MUC. Not always.

**Comment by moshpirit** [comment]
Or maybe developing some kind of "detector" to check if someone is all the time coming and exiting and discard this activity. Like: if in 10 seconds, this person is still here, then, It'll show the message.

**Comment by fortinj1354** [comment]
Something similar to pidgin's join part hiding plugin could work, only users that have been active within a certain amount of time trigger notifications. Personally I'd rather see all joins/parts but that's just me.

**Comment by fisle** [comment]
This is somewhat annoying currently - you're trying to ask something from your buddy in a MUC only to realize he has already left the room an hour ago. (Though you never realize he has left if you don't manually check the participants). Perhaps some people don't need this feature, but me and my friends certainly do. Maybe a configurable option to show room joins/leaves?

**Comment by iNPUTmice** [comment]
@fisle you can touch an avatar to highlight them. If that participant has left the MUC you will receive a toast. Maybe that helps.

In any case implementing join/leave messages is not on our todo list right now.

**Comment by paskalito** [comment]
@iNPUTmice Is it maybe possible to get "implementing join/leave messages" on your todolist around now?

We Just had the case that we tried to communicate with someone in a muc, just to find out some weeks later, that he had purposely left it.
That caused quiet some .. discomfort. :)


to me it should be
xyz has joinged the chat - on first join of the muc
xyz has left the chat  - when he leaves 

(blindly assuming this two events are detectable (serverd by server and protocol))

**Comment by bqv** [comment]
#2946
