### ISSUE TITLE
Hyperlink of internalionalised TLDs does not work

### ISSUE THREAD

**Issue by TheHellstorm** [siacs/Conversations#1223]
One example:

I send/receive the link to the internationalized domain [はじめよう.みんな](http://はじめよう.みんな) (Punycode: [xn--p8j9a0d9c9a.xn--q9jyb4c](http://xn--p8j9a0d9c9a.xn--q9jyb4c)) in a message.

The hyperlink will result in the following:

1. For はじめよう.みんな: No clickable hyperlink.
2. For xn--p8j9a0d9c9a.xn--q9jyb4c: [``xn--p8j9a0d9c9a.xn``](http://xn--p8j9a0d9c9a.xn)``--q9jyb4c``

resulting in the issue that the link cannot be clicked at all. The only possibility is to copy the entire message, strip the surrounding text and paste it into the web browser. Naturally, this is extremely cumbersome on smartphones.

An implementation solution would be to:

1. Recognize the Punycode pattern in Domains. Everything like foo.xn--bar should be recognized as a valid URL. Also keep in mind that URLs like xn--p8j9a0d9c9a.xn--q9jyb4c/%E3%83%96... are possible.
2. For URLs in Unicode (and to recognize other TLDs), the Public Suffix List can be used: https://publicsuffix.org/list/.

Well, this would certainly be a nice feature :)

**Comment by SamWhited** [comment]
I'm reasonably sure this is handled by Android and there's nothing we can do about it w/o ridiculous hacks.

**Comment by TheHellstorm** [comment]
OK, I understand. Thanks :)

**Comment by iNPUTmice** [comment]
It's like @SamWhited said. I'm sorry.
However if you are not using 5.0 there is a chance this is getting better for you with 5.0

**Comment by herbsmn** [comment]
I'm using Replicant 4.2 and .onion addresses aren't hyperlinked in Conversations. Does this change with android 5.0 or 6.0? Would it also be a large hack to make .onion addresses into hyperlinks in Conversations? Sorry if it is bad form to ask this question on a closed issue, but it seemed like a similar situation.

**Comment by iNPUTmice** [comment]
> .onion addresses aren't hyperlinked in Conversations. Does this change with android 5.0 or 6.0? 

Yes. Everything foo.bar is hyperlinked. For better or worse.
