### ISSUE TITLE
?server settings: store server if supported, local only, etc

### ISSUE THREAD

**Issue by TameOfGroans** [siacs/Conversations#1225]
server If supported
locally unsent unread
locally
none 

I would like options to opt out of various sent caching schemes client side. Always using otr fyi.

server if supported & user elected clear? is such possible?

**Comment by iNPUTmice** [comment]
> Always using otr fyi.

OTR messages are being marked as no-permanent-storage an should not be stored by your server anyway. (Even if they were no one would be able to read them). You can opt-out of client side storage in the expert option "don't write encrypted messages to disk" or what ever that's called again.
