### ISSUE TITLE
Feature: Swipe across open conversations

### ISSUE THREAD

**Issue by sesceu** [siacs/Conversations#1226]
I had my father in law change from Xabber to Conversation. He really likes it, but he misses one feature. In Xabber it is supposedly possible to swipe between open conversations. He'd like to have such a feature to. It is really much like you can already swipe from the list of all open conversations to the last active one. I created a mock of the feature, hoping that it makes it easier to understand:
![swipe_across_conversations_mockup](https://cloud.githubusercontent.com/assets/1614558/7796003/f8dd5790-02da-11e5-80ea-290272ef5d1a.png)

So the idea is, that out of an active conversation you'd swipe from right to left over the conversation history, to move on the the last active conversation and so on. Once you are on the end you cannot swipe anymore. You can also swipe from left to right, to get back to the more recent conversation. Once you are at the most recent one and swipe from left to right, you will swipe in the conversation list (same as it is implemented right now). Once you type into one of the conversations or receive a message, this conversation fragment is always put first in the list.

This way you'd always know to swipe left to right, in order to get to the more recent conversation or chat events, and the other way around. We might think about an indicator, giving you some topological view of the conversation fragments, especially when they move around in the background due to received messages.

What do you guys think? Too complicated or a missing feature?

**Comment by jkufner** [comment]
Swipe from right looks like good way to swap between last two chats, but
I would not browse all of them. Just current and previous. If you want
more, list of active conversations sounds like a better way.

**Comment by Lucki** [comment]
Maybe you can differentiate between a swipe on the screen and a swipe from the edge of the screen for the menu.

**Comment by sesceu** [comment]
Actually, I'm not a big fan off the edge swiping thing. And I think it would be hard to grasp for the user, that swiping from left to right, or left-edge to right are two different things.

**Comment by iNPUTmice** [comment]
I think the swipe to the right to open the Conversations overview and the swipe to left and right to switch between 'neighbouring' conversations are two conflicting patterns that don't match at all. You can either have the one or the other.
When initially starting Conversations I choose the overview pattern instead of the left-and-right neighbouring pattern (like gtalk and chatsecure did for example)  because to me there was never a clear structure on what the 'neighbouring conversations' are supposed to be.
