### ISSUE TITLE
Feature: Share scaled image

### ISSUE THREAD

**Issue by rigid** [siacs/Conversations#1230]
For the sake of "bandwith related user experience" it would be awesome if there was an option to share an image, that is scaled down on the fly (to a configurable pre-defined size).

If the UI shouldn't be cluttered, it might be acceptable, when "auto-downsize" happened by default upon "Select image". For transfering an unaltered image file, "Select file" could be chosen.

**Comment by kriztan** [comment]
This is already implemented and working as expected.

**Comment by iNPUTmice** [comment]
this is pretty much how it is done already. only that you can't choose the
size yourself. but it uses a sane default of full HD resolution as this is
what most smartphones can display these days.

**Comment by rigid** [comment]
oh, i didn't notice that. I always scaled images down manually when transfer speeds were awfully slow.

@iNPUTmice The default is full HD resolution? So images will be scaled down to 1920x... if they are bigger?
