### ISSUE TITLE
Logging in requires a restart of the app

### ISSUE THREAD

**Issue by Crasha** [siacs/Conversations#1233]
Logging in gets stuck on "connecting" and thus requires you to force close the app and re-open it, only for it to log you in and work perfectly fine afterwards. 

I was using the OpenFire 3.8.2 server on the raspberry pi.

Conversations was compiled on Ubuntu 12.04LTS and installed on my Google Nexus 5 via the debug .apk.

**Comment by andersruneson** [comment]
Can you create an account on another server (like e.g. jabber.de ) and see
if that works?
Can you connect adb debug and see if you can get any debug output from
Conversations?
Can you take a look at the OpenFire logs?
Can you test the official (non self-built) Conversations?

**Comment by iNPUTmice** [comment]
no reaction from op
