### ISSUE TITLE
adjust image after camera capture & prior to convey

### ISSUE THREAD

**Issue by TameOfGroans** [siacs/Conversations#1235]
Please allow some user configuration of image parameters after camera capture prior to Xmpp Texting conveyance.

I would greatly prefer to send PNG (24bit), or occasionally PNG 8bit after downsampling.  Less jpeg DCT is better for integrity. 

Also allow some downscaling/downsampling Connell

**Comment by iNPUTmice** [comment]
Use 'choose file' to send unmodified files (and images)

Re-encoding a JPEG file (most camera apps will just give you that) as PNG doesn't make too much sense and will just blow up the file size by the way.
