### ISSUE TITLE
Conversations sends repeated messages with let's chat

### ISSUE THREAD

**Issue by bufke** [siacs/Conversations#1237]
When I send a message it will often say "sending" forever and send the message several times - about once an hour. The repeats are visible from both Conversations and let's chat's web interface. 

Screenshot from let's chat.
![screenshot from 2015-05-30 18 30 35](https://cloud.githubusercontent.com/assets/739307/7899648/03d4935c-06fa-11e5-9c21-d8b342786afc.png)
 
If I can send any useful debug information please let me know.

**Comment by iNPUTmice** [comment]
What server are you using. A similar bug for mlink has just been fixed in
1.4.3 and a bug with prosody is already handled in another issue.

**Comment by bufke** [comment]
[Let's chat](https://github.com/sdelements/lets-chat/) is it's own server. Do you think the issue is with them? I'd be happy to donate beer money to anyone who can help. Here's a screenshot from Conversations.
![screenshot_2015-05-31-09-54-27](https://cloud.githubusercontent.com/assets/739307/7902145/66c28c7c-077b-11e5-81bf-44a34424b337.png)

**Comment by iNPUTmice** [comment]
is this specially for group messages?

if so this issue might be related to the server stripping message ids.
you can check out latest HEAD which uses a slightly improved message parser
which might not break if a server behaves like this.

**Comment by bufke** [comment]
It is MUC. Working on building from master (I've been using the store version). If you have an apk built I could test it out - could email it to david at burkesoftware.com

**Comment by bufke** [comment]
Think I got it installed from source. Still says "sending..." forever. No duplicates yet. Will monitor it for a bit and see.

**Comment by bufke** [comment]
No same behavior, thanks though. Let me know if I can test anything.

**Comment by iNPUTmice** [comment]
Is there a way I could get a test account on that server? You can send me credentials privately to inputmice at siacs.eu

**Comment by iNPUTmice** [comment]
fixed in df86b0fc47cb7af8e97826f97d0e202405cff414

**Comment by bufke** [comment]
Hello - I'm afraid there is a regression and it's doing the same behavior again. I haven't updated let's chat (until just now to see if it would fix it) which would suggest the issue is a change in Conversations. You are welcome to play around with my Let's Chat server again if you'd like.

**Comment by iNPUTmice** [comment]
yes. I was under the impression the bug was fixed in letschat about the
same time I initially fixed the bug in Conversations. I explicitly reverted
that change because it was causing problems.

let me know if I was wrong about the bug in let's chat being fixed.

**Comment by bufke** [comment]
It's happening on 0.4.2. Do you know if it was fixed in git master but not released? I can try it out.
