### ISSUE TITLE
blocked, still can send me messages, I receive them

### ISSUE THREAD

**Issue by bonsaithis** [siacs/Conversations#1238]
v 1.4.3 

in roster view, long click contact
select block

in options I have show tags so I see BLOCKED in white on black field.

**Comment by iNPUTmice** [comment]
this looks a lot like a server issue to me. The dynamic BLOCKED tag will
only show once the entry is in the servers block list.

**Comment by bonsaithis** [comment]
upon which XEP does this functionality rely?

**Comment by iNPUTmice** [comment]
http://conversations.im/#xmpp
