### ISSUE TITLE
Unhandled exception on SRV DNS using weights.

### ISSUE THREAD

**Issue by PMaynard** [siacs/Conversations#1244]
[Throwing Exception](https://github.com/siacs/Conversations/blob/a577ec7c318d734de3ed8c2dc5ab1dd4b773b78a/src/main/java/eu/siacs/conversations/xmpp/XmppConnection.java#L204) when a SRV DNS record has same priority but alternative weights.

Conversations Version: 1.4.3 - From F-Droid.

*adb -d logcat -C -v time -s conversations*
```
06-03 10:29:00.410 D/conversations( 4965): osaka@matrix.ac: connecting
06-03 10:29:00.413 D/conversations( 4965): using dns server: *.*.14.13 to look up matrix.ac
06-03 10:29:00.433 D/conversations( 4965): using dns server: *.*.6.66 to look up matrix.ac
06-03 10:29:00.450 D/conversations( 4965): using dns server: 8.8.8.8 to look up matrix.ac
06-03 10:29:05.449 D/conversations( 4965): osaka@matrix.ac: unhandled exception in DNS resolver
```

*DNS Zone*
```
matrix.ac. 1800 IN A 178.62.58.156
xmpp.matrix.ac. 1800 IN A 178.62.58.156
_xmpp-client._tcp.matrix.ac. 1800 IN SRV 0 5 5222 xmpp.matrix.ac.
_xmpp-client._tcp.matrix.ac. 1800 IN SRV 0 10 443 xmpp.matrix.ac.
_xmpp-server._tcp.matrix.ac. 1800 IN SRV 0 5 5269 xmpp.matrix.ac.
_xmpp-server._tcp.conference.matrix.ac. 1800 IN SRV 0 5 5269 xmpp.matrix.ac.
```

*Note*: We know this is not the correct setup, and have configured the DNS to use priorities instead of weights for finding an alternative connection.

**Comment by iNPUTmice** [comment]
Should be fixed in 1.4.4-beta2
