### ISSUE TITLE
ChromeOS Port?

### ISSUE THREAD

**Issue by jprjr** [siacs/Conversations#1246]
Hi there -

I've recently picked up a Chromebook and tried to find an XMPP app - there really aren't any, all the apps in the Chrome store are glorified bookmarks to web services.

I used the ARC Welder to turn Conversations into a Chrome app, and it works really well! I had to go into the export options and click the "enter is send" option and I was off and cruising!

Just wanted to toss that out there, XMPP/Jabber Chromebook users are a really under-served group right now.

**Comment by jkufner** [comment]
Can you provide pull request with modifications and build files, so they
can be merged into upstream version?

Of course, these modifications should not interfere with Android users.

**Comment by SafwatHalaby** [comment]
I think he implied he made no modifications at all.

**Comment by jprjr** [comment]
@jkufner - @SafwatHalaby is correct, I didn't make any modifications. I'm not sure what the process is for submitting an app to the Chrome Web Store

**Comment by jkufner** [comment]
I expected that ARC Welder recompiles the app or something and according
to their tutorial it is just runtime that operates on APK. This way it
is really about adding it to the store.

**Comment by jprjr** [comment]
@jkufner it looks like it. You'd probably want some method of enabling "Enter sends message" by default when packaged as a Chrome app, otherwise it seems very usable!

**Comment by Dragnucs** [comment]
@jkufner What you are looking for is movim. There is a pod at pod.movim.eu. Movim is a self-hosted web based XMPP client. You can use any pod you want with any XMPP you have.

**Comment by jkufner** [comment]
@Dragnucs Thanks for the tip, however I may have completely different use for it :)

**Comment by magicvodi** [comment]
@jprjr are you still using Conversations with ARC? Have you tried OMEMO encryption with it? I'm getting the strange issue that I and my contacts always get the "Trust OMEMO fingerprints" screen when sending a message, but there are no fingerprints displayed and the message is sent after pressing "done". But it comes at every single message.

**Comment by iNPUTmice** [comment]
@magicvodi yes I can confirm that. Somehow the OMEMO keys generated by ARC are not readable by other instances. (If you look at the adb logcat output of the phone it says verification failed or something)

**Comment by iNPUTmice** [comment]
Oh by the way: https://chrome.google.com/webstore/detail/conversations/hkadkgjkhifahjhgbbeancdbemdoiekd so I guess I can close here.
