### ISSUE TITLE
cant connect to server using android vm

### ISSUE THREAD

**Issue by austae** [siacs/Conversations#1250]
i don't why but i cant connect to openfire server using conversation running it in android vm , 

so i have Linux vm running openfire , i have tried 3 different  xmpp client and all of then can connect expect     conversation  running in android vm  , the logs show it trying to connect but there is no respond form the server

**Comment by RoadXY** [comment]
At work I also have OpenFire running on a VM and is working flawless.

**Comment by austae** [comment]
its confusion  ,in the log its try to use dns  it like it cant see the server , so i added shell app in the android vm and i can ping the server i dont know what is the issue  ?


log capture :
->﹕ using dns server: X.X.X.X to look up 192.168.197.132
->﹕ nayef@192.168.197.132: error connecting account. try again in 37s for the 2 time
->﹕ eglSurfaceAttrib not implemented
->﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa49cb800, error=EGL_SUCCESS

**Comment by lookshe** [comment]
Are you really running it in the VM or are you trying to debug Conversations with attached debugger? I ask, because I had a similar issue when trying to debug Conversations. Attaching the debugger after connecting to the server worked fine in this situation.

**Comment by iNPUTmice** [comment]
the current HEAD is unable to connect with JIDs that use an IP address as
domain name

**Comment by iNPUTmice** [comment]
fixed
