### ISSUE TITLE
automatically logout from server when going offline

### ISSUE THREAD

**Issue by codemonkeyforever** [siacs/Conversations#1251]
Hello there,
I really like Conversations, its the best jabber app I ever found and I am using it since it version 0.2 :-)))
There are 2 little improvements, I would be happy to see in some release sooner or later:
1.) I dont want to be online with my smartphone all the time, so I deactivate the Wifi or mobile data many times a day. If I only hit the "Wifi off" button in the android settings however, the xmpp server seems to hope that I will return soon, and thus only after 10-20 minutes it will then return an error message to my friends, that the message could not be delivered. This is of course annoying to my friends, and partly this is of course also a server problem. To circumvent this problem I go to the accounts settings in conversations, and "temporarily deactivate" my xmpp connection before I hit the "WIFI off" button. Then the xmpp server shows me as offline to my friend and stores their messages for offline storage, and doesnt return an error. 

Unfortunately it is much too tiresome do so so every time, multiple times a day, so if I dont have time, I just quickly deactivate the WIFI without logging out of the server. Thus, it would be really great if conversations could hook in any connection change event handler and log out of the xmpp server automatically before switching of the wifi device, when I hit the "wifi off" button. 

Maybe this can be achieved by registering some "android account" for conversations, like xabber did.

**Comment by jkufner** [comment]
You need to disable accounts in Conversations before going offline.

Conversations supports Stream Management to quickly reestabilish session
when connection is back. When you disable WiFi, it is already too late
for logout in Conversations. But when you travel by metro where signal
is only in stations, not in tunnels, nobody will notice you are offline
for short intervals.



codemonkeyforever wrote, on 16.6.2015 13:06:
