### ISSUE TITLE
make copy of conversations history file db on sdcard (improvement)

### ISSUE THREAD

**Issue by codemonkeyforever** [siacs/Conversations#1252]
2.) the second improvement, is a way to backup the conversations history without root permissions and even though there is no mam support. On the one hand, I rooted my phone and can easily backup the sqlite database of conversations to backup my history, and transfer it in the future to another new phone. On the other hand, I also have a tablet, which I found so far no way to root. So I have no way to backup my conversations on the tablet. If it is stolen or breaks, all my history from there is lost. :-(

I would like to see some button which allows to store a copy of the conversations db to sd card or sth. like that. A simple copy of this file, that would be so great :-)

Hope you found some suggestions helpful. Thanks for your attention and your great work!

Joe

**Comment by SamWhited** [comment]
This isn't exactly an answer to your issue, but you might look into enabling Message Archive Management on your server. This will allow your server to store your message history, and allow Conversations to re-download it if you clear your account and need it back.

**Comment by QuentinC** [comment]
If MAM is enabled on the server, you can download the full history using Gajim 0.16.1 !
Then everything will be on Gajim history !

**Comment by aeuii** [comment]
Hi, it would be a really welcomed feature!

Very useful would be a function to dump the history to an external storage in a readable JSON file. It is a good format and easy to parse both for machine and human eyes.

PS. MAM does not seem to be a very useful solution, because it's in direct conflict with end-to-end encryption, which is easy to use with Conversations.

**Comment by iNPUTmice** [comment]
this was implemented in 16.11
