### ISSUE TITLE
Vibration on Notification even when Vibrate unchecked

### ISSUE THREAD

**Issue by charlie-o** [siacs/Conversations#1255]
Would like to receive notifications without a vibration, while the phone is in vibrate mode (LED will still indicate). Currently, the Vibrate check box doesn't affect anything - the phone vibrates no matter what.

Is the issue in /services/NotificationService.java ?

**Comment by iNPUTmice** [comment]
> Is the issue in /services/NotificationService.java ?

maybe. I'm not entirely sure this is a Conversations issue.
Is the vibrate setting working for you when **not** in vibrate mode? Maybe Android transforms the rington into a vibration?

**Comment by bagage** [comment]
I am having this issue as well. I can confirm that it is only when sound notification is set to `vibrate`, otherwise sound notification is played.. so that's something in Android (lolipop?).

**Comment by bagage** [comment]
According to [this article](https://gigaom.com/2014/11/17/silent-vibrate-do-not-disturb-android-priority-notifications/), if you do not want Conversations to vibrate on new messages, you have to set sound to "Priority" mode.

**Comment by kriztan** [comment]
I'm having this issue, too. 
I've Conversations on my business phone and disabled ringtone and virbration within Conversations. The notification sound is not played, but the vibration is still enabled. I've tested it in *vibrate mode* and *ringtone mode*.
The phone is an Samsung Galaxy S5 mini with Android 4.4.2

**Comment by devdan** [comment]
I have the same issue. Even although it is an Android issue, is it still possible to fix it? My other messengers (Signal and Threema) obey their own vibrate setting.
