### ISSUE TITLE
The padlock icon doesn't properly indicate the encrytpion status

### ISSUE THREAD

**Issue by aeuii** [siacs/Conversations#1256]
Hello,

I noticed, that the padlock icon at the top of an open conversation doesn't properly indicate, whether a message is going to be sent encrypted or not.

1. It does not get updated, when I switch between “clear text” and “OTR” (the grayed text in the input area changes correctly)

2. If the conversation was encrypted, but the other party ended the OTR session, then the padlock does not open indicating that the session is unencrypted.

I happened a few times, that I sent unencrypted messages, because of that. Perhaps even stronger visual indication of the current encryption status would be useful, e.g., #1082.

Thanks!

PS I'm using Conversations v 1.4.3

**Comment by iNPUTmice** [comment]
fixed in 558d065d48b43c190cac706870cf8d97c70ecbfd
