### ISSUE TITLE
error: retrieving parent for item while importing project 

### ISSUE THREAD

**Issue by wonderer007** [siacs/Conversations#1257]
I just cloned and and import Conversations in eclipse and got themes.xml /res/values-v21/themes.xml line # 4     <style name="ConversationsTheme" parent="@android:style/Theme.Material.Light.DarkActionBar"> Error is "error: retrieving parent for item: No resource found that matches the given name "

**Comment by iNPUTmice** [comment]
Not sure if this is the root of your problems but you should be using android studio for gradle based projects.

**Comment by wonderer007** [comment]
OK let me try 
Thanks
