### ISSUE TITLE
Connection issues with ejabberd server

### ISSUE THREAD

**Issue by languitar** [siacs/Conversations#1258]
Conversations doesn't establish connections with my privately hosted ejabberd server. In the server logs I can find the following:

````
2015-06-22 00:25:42.353 [info] <0.542.0>@ejabberd_listener:accept:313 (#Port<0.28468>) Accepted connection 2A02:908:B40:D4C0:55:64A6:D4BE:227C:58310 -> 2A01:4F8:D16:5340::100:5222
2015-06-22 00:25:42.798 [info] <0.16461.1>@ejabberd_c2s:wait_for_sasl_response:898 ({socket_state,p1_tls,{tlssock,#Port<0.28468>,#Port<0.28470>},<0.16460.1>}) Accepted authentication for languitar by undefined
2015-06-22 00:25:42.981 [info] <0.16461.1>@ejabberd_c2s:wait_for_session:1079 ({socket_state,p1_tls,{tlssock,#Port<0.28468>,#Port<0.28470>},<0.16460.1>}) Opened session for languitar@semipol.de/mobile
2015-06-22 00:25:43.005 [info] <0.16461.1>@ejabberd_c2s:handle_enable:2659 Stream management with resumption enabled for languitar@semipol.de/mobile
2015-06-22 00:25:43.776 [warning] <0.16461.1>@ejabberd_c2s:check_queue_length:2807 ACK queue too long, terminating session for languitar@semipol.de/tablet
2015-06-22 00:25:43.776 [warning] <0.16461.1>@ejabberd_c2s:check_queue_length:2807 ACK queue too long, terminating session for languitar@semipol.de/tablet
2015-06-22 00:25:43.776 [warning] <0.16461.1>@ejabberd_c2s:check_queue_length:2807 ACK queue too long, terminating session for languitar@semipol.de/tablet
2015-06-22 00:25:43.777 [warning] <0.16461.1>@ejabberd_c2s:check_queue_length:2807 ACK queue too long, terminating session for languitar@semipol.de/tablet
2015-06-22 00:25:43.777 [warning] <0.16461.1>@ejabberd_c2s:check_queue_length:2807 ACK queue too long, terminating session for languitar@semipol.de/tablet
2015-06-22 00:25:43.777 [warning] <0.16461.1>@ejabberd_c2s:check_queue_length:2807 ACK queue too long, terminating session for languitar@semipol.de/tablet
2015-06-22 00:25:43.777 [info] <0.16461.1>@ejabberd_c2s:terminate:1754 ({socket_state,p1_tls,{tlssock,#Port<0.28468>,#Port<0.28470>},<0.16460.1>}) Close session for languitar@semipol.de/mobile
2015-06-22 00:25:43.799 [info] <0.16461.1>@ejabberd_c2s:handle_unacked_stanzas:2825 506 stanzas were not acknowledged by languitar@semipol.de/mobile
```

A logcat sessions starting from a fresh installation of conversations can be found here:
https://gist.github.com/languitar/3782edec62525b03e3c2

Conversations is the first client I know that fails to interact with the server.

**Comment by iNPUTmice** [comment]
@weiss any idea on this?
ejabberd complains about missing acks but Conversations log states that it sending those.
Is there a chance that the input queue on ejabberd is filled with (yet unhandled) IQ requests or something?

**Comment by weiss** [comment]
> Is there a chance that the input queue on ejabberd is filled with (yet unhandled) IQ requests or something?

My guess is that the account is flooded with offline messages.  ejabberd would delivers those right after logging in, probably too fast for Conversations to be able to acknowledge them in time.  By default, ejabberd will kill the session with that error message if the outgoing Stream Management queue exceeds 500 unacknowledged messages.  Those 500 messages would not be re-delivered on the next login, though.

@languitar, what ejabberd version are you using exactly?  My guess from that log output is that you're using 14.07, which doesn't support setting the `mod_offline` option `store_empty_body: false`, which I would otherwise recommend.  Either way, you can check the contents of your offline message queue in ejabberd's web interface.  If you want, you could also set the `ejabberd_c2s` listener option `max_ack_queue` to a value larger than 500, or even to `infinity` (though this opens your server to DoS attacks if you have untrusted users).

**Comment by iNPUTmice** [comment]
> My guess is that the account is flooded with offline messages. 

my money would have been on large roster. Could this lead to a similar behaviour?

@weiss I don't understand the 'in time' here. Are we talking about the server sends >500 stanzas almost at once and then ends the connection and doesn't wait for at least the round trip time? Because when looking at the log Conversations is acknowledging the stanzas...

**Comment by languitar** [comment]
The roster is definitely large, since I am using a transport to connect to Facebook, which is >300 contacts only from there.

**Comment by languitar** [comment]
@weiss I am running 14.07-5 from debian testing. Offline message queue is empty I can connect without problems from any other client.

**Comment by weiss** [comment]
> my money would have been on large roster. Could this lead to a similar behaviour?

Isn't the actual roster returned within a single stanza?  But ...

> The roster is definitely large, since I am using a transport to connect to Facebook, which is >300 contacts only from there. [...] Offline message queue [...].

... sounds like you're right, so I'm glad I didn't bet any money on my theory :-)  Maybe the presence stanzas are the culprit.

> Are we talking about the server sends >500 stanzas almost at once and then ends the connection and doesn't wait for at least the round trip time?

Exactly.  How long should the server wait?  What's a "round trip time"?

**Comment by weiss** [comment]
@languitar, did you try increasing `max_ack_queue` in the `ejabberd_c2s` listener section to, say, `5000`?

**Comment by languitar** [comment]
@weiss Yes, just tried that. 1000 wasn't enough, but with 5000 it works.

**Comment by languitar** [comment]
Isn't it still strange, that only conversations triggers this behavior? Usually I would think that one should be able to use the messenger without having to touch the server config.

**Comment by weiss** [comment]
> Isn't it still strange that only conversations triggers this behavior?

This behavior is only triggered when [Stream Management][1] is enabled.  Maybe the other clients don't support this?

> Usually I would think that one should be able to use the messenger without having to touch the server config.

Absolutely, and it _does_ work, "usually" (I haven't seen this issue reported before).  Maybe we should increase the default `max_ack_queue` value in ejabberd.

[1]: http://xmpp.org/extensions/xep-0198.html

**Comment by languitar** [comment]
> This behavior is only triggered when Stream Management is enabled. Maybe the other clients don't support this?

This might be true. I don't know any other usable client so far that supports this.

> Absolutely, and it does work, "usually" (I haven't seen this issue reported before). Maybe we should increase the default max_ack_queue value in ejabberd.

Probably a good idea. I don't think my setup is that extreme. So this shouldn't be triggered in default settings.

**Comment by SamWhited** [comment]
> Absolutely, and it does work, "usually" (I haven't seen this issue reported before). Maybe we should increase the default max_ack_queue value in ejabberd.

In general I find that ejabberd has fairly conservative thresholds for things; eg. my server complains about using too much memory every time a room gets a little busy (or did, until I turned up the threshold) and I'm having it do pretty much the bare minimum a server can be doing (only a handful of users with small rosters).

**Comment by jkufner** [comment]
Holger Weiß wrote, on 22.6.2015 15:37:
> @languitar <https://github.com/languitar>, did you try increasing
> |max_ack_queue| in the |ejabberd_c2s| listener section to, say, |5000|?

I also had to increase this limit on my server to make Conversations
work. I believe there is bug in sending some requests when loading
roster and not reading responses until all requests are sent.  So the
socket buffers get filled and then ack queue on server overflows.

**Comment by weiss** [comment]
> I also had to increase this limit on my server to make Conversations work.

Do any of you have a dump of the stream that triggers this behavior?  On the ejabberd side, you could log the payload with [mod_logxml][1], for example.  I would be really interested to see what kind of stanzas you're receiving before blindly increasing the limit.

[1]: https://github.com/processone/ejabberd-contrib/tree/master/mod_logxml

**Comment by languitar** [comment]
I'd like to provide a log, but I can't find out how to compile the mod_logxml module. I am stuck at:
```
root@cannonball ~ # ejabberdctl module_install mod_logxml
/usr/lib/x86_64-linux-gnu/ejabberd/include/jlib.hrl:23: can't find include file "xml.hrl"
/usr/lib/x86_64-linux-gnu/ejabberd/include/jlib.hrl:430: record xmlel undefined
/usr/lib/x86_64-linux-gnu/ejabberd/include/jlib.hrl:470: type xmlel() undefined
src/mod_logxml.erl:263: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
src/mod_logxml.erl:264: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
Error: {compilation_failed,"src/mod_logxml.erl"}
```

**Comment by weiss** [comment]
Current revisions of the ejabberd-contrib modules won't work with older ejabberd versions, sorry.  This should do the trick for you:

    git clone https://github.com/processone/ejabberd-contrib.git
    cd ejabberd-contrib/mod_logxml
    git checkout e5d24089d22
    ./build.sh
    cp ebin/mod_logxml.beam /usr/lib/x86_64-linux-gnu/ejabberd/ebin/

Then configure the module as per [the README file][1] and restart ejabberd.

[1]: https://github.com/processone/ejabberd-contrib/tree/master/mod_logxml

**Comment by languitar** [comment]
Ok, module compiled. Are the default settings of the module ok to provide the required data that you need?

**Comment by weiss** [comment]
> Are the default settings of the module ok to provide the required data that you need?

Yes, and I already received your log, thanks a lot.

So the problem is indeed that you receive a huge number of presence stanzas during login, all in one go from a single transport.  This happens due to (1) your large roster, and (2) the server behavior of explicitly sending unavailable presence for offline contacts (the standard allows this, but e.g. ejabberd wouldn't do it), and (3) the weird server behavior of sending every presence stanza twice (including those unavailable stanzas).

I don't know.  I think this situation _is_ quite unusual, but I do agree it would be nice if this would work out of the box.  I'll think about it a little more.

Thanks again!

**Comment by languitar** [comment]
Is this still related to conversations? Somehow this doesn't happen with other messengers, but maybe this has become more of an ejabberd issue?

**Comment by iNPUTmice** [comment]
> Somehow this doesn't happen with other messengers

>>> Isn't it still strange that only conversations triggers this behavior?

>> This behavior is only triggered when Stream Management is enabled. Maybe the other clients don't support this?

**Comment by languitar** [comment]
Right, so probably this discussion should then be transferred to an ejabberd issue?
