### ISSUE TITLE
SRV lookup via Android VPN client

### ISSUE THREAD

**Issue by monokhrome** [siacs/Conversations#1259]
Conversations is unable to lookup SRV records for a domain that is reachable via (say, IKEv1) VPN. So, despite the fact there are valid SRV records, it just don't see them. I believe that it's due to the fact Android doesn't store VPN's DNS servers in net.dns* properties.

**Comment by knoy** [comment]
Are you sure this isn't caused by the DNS server being incorrectly configured after connected to the VPN?

**Comment by monokhrome** [comment]
On 24.06.2015 00:16, knoy wrote:
> Are you sure this isn't caused by the DNS server being incorrectly
> configured after connected to the VPN?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/siacs/Conversations/issues/1259#issuecomment-114643822>.
>

Yep, I am. Just setprop net.dns1 <VPN's DNS> and everything's fine.

**Comment by monokhrome** [comment]
On 24.06.2015 00:16, knoy wrote:
> Are you sure this isn't caused by the DNS server being incorrectly
> configured after connected to the VPN?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/siacs/Conversations/issues/1259#issuecomment-114643822>.
>

Ah, and yes - everything using A records (browser, sip/email/ssh 
clients, etc) are just happy without that setprop magic. I mean, they do 
resolve inside-only hostnames.

**Comment by iNPUTmice** [comment]
Do you happen to know where Android stores the dns servers for VPN connections?

Also 1.4.6 has more fallback mechanisms. You might want to check if this helps your issue.

**Comment by iNPUTmice** [comment]
should be fixed by 3db70876588ca43687b69a3305a2547270aa0850
