### ISSUE TITLE
issue to build new release ( 1.4.4 ) for f-droid

### ISSUE THREAD

**Issue by call5** [siacs/Conversations#1261]
build log here https://f-droid.org/wiki/page/eu.siacs.conversations/lastbuild_72

**Comment by SamWhited** [comment]
Looks like fdroid is missing the build tools 22.0.1

**Comment by iNPUTmice** [comment]
should probably be reported to fdroid not us

**Comment by amo13** [comment]
https://gitlab.com/fdroid/fdroiddata/issues/256

**Comment by amo13** [comment]
fixed and solved by updating repos
