### ISSUE TITLE
What acknowledgement does Conversations expect for sent messages?

### ISSUE THREAD

**Issue by sibartlett** [siacs/Conversations#1265]
I've been working on a basic XMPP server implementation, and some of my users have encountered a problem with Conversations.

When a user sends a message via Conversations, a "Sending..." message is displayed and the app keeps trying to resend the message.

I realize this is most likely a problem with my XMPP implementation....

My question is: what exactly does Conversations expect from the XMPP server to acknowledge that the message was received? (I've tried looking through the source for Conversations myself, but haven't got very far yet).

Thanks for your time, I really appreciate it.

**Comment by iNPUTmice** [comment]
Hi,

I had to do some digging into your github account to figure out you were a) talking about [lets-chat](http://sdelements.github.io/lets-chat/) and b) talking about group messages. Specifying either or both of this in your issue would have saved me some time.
Anyway. Conversations 1.4.4 already had a fix for this df86b0fc47cb7af8e97826f97d0e202405cff414 which might have been the reason that only some of your users experienced this problem.
Emitting  or even worse changing the id of messages in a MUC is really bad practice though and I'm glad to see your latest commits seem to change this.

**Comment by sibartlett** [comment]
@iNPUTmice thanks for the response, and I'm really sorry for you having to dig through my GitHub account.

Yeah, I recognize that changing the IDs were a bad idea; especially responding with our database ID. That has now been fixed.

Again, thanks for taking the time to investigate and respond! I don't personally have an Android device, but Conversations looks like a great project!
