### ISSUE TITLE
Add an option to reduce files before send them

### ISSUE THREAD

**Issue by sim6** [siacs/Conversations#1266]
Firstly thanks for your work.

Please, could you add an option to reduce files, like images or videos, before send them?

**Comment by iNPUTmice** [comment]
If you use 'Choose picture' instead of 'choose file' the image will be compressed.

**Comment by sim6** [comment]
Thanks, I don't know it, but I think it's not compressed enough for spanish data connections.

And what about video?

**Comment by SamWhited** [comment]
> I think it's not compressed enough for spanish data connections.

I'm not sure that you're going to get much better w/o seriously degrading image quality.

> And what about video?

Unless you have an extremely powerful phone, with a magical battery, you probably don't want to be compressing video on your phone.

**Comment by moshpirit** [comment]
>Unless you have an extremely powerful phone, with a magical battery, you probably don't want to be compressing video on your phone.

Why? on others IMs like Telegram a 130Mb can be shared sizing 3 Mb even on old phones with 512Mb RAM, something extremely good.
