### ISSUE TITLE
Contacts from roster removed or wrongly detected as not being on the roster

### ISSUE THREAD

**Issue by languitar** [siacs/Conversations#1267]
I have observed several cases where conversations indicated that a contact, which always had been on my roster and with which I was communicating successfully, suddenly got detected as not being on my roster anymore. When sending a message, conversations refused to do so and asked whether the contact should be added to the roster. In one case, the contact actually wasn't on the roster anymore at that point in time and conversations is the only likely source which might have deleted the contact.

The logging level on my server is unfortunately not high enough to find anything useful.

**Comment by iNPUTmice** [comment]
Ok to narrow this down a bit. Are you using roster versioning? You can check in your account details (Overflow menu, server info)

**Comment by languitar** [comment]
versioning is unavailable

**Comment by sec-git** [comment]
the server I am on (jabber.de) has roster versioning XEP-237 enabled. Checked with another client, the deleted contact was shown as not in the roster neither.

**Comment by iNPUTmice** [comment]
This has been fixed in 1.22 or something like that
