### ISSUE TITLE
[Feature] Being able to password lock the application

### ISSUE THREAD

**Issue by arebokert** [siacs/Conversations#1268]
For people who value privacy, having a function that makes you able to set a password that has to be typed in when the application is brought up from idle would be good.
To be more precise, this would be separate from the server login itself. It would make you able to secure your application and its contents while still being logged in and receiving messages which you wouldn't be able to view without logging in to the app.

An example would be the application suresport for android which supports this function.

**Comment by d9h02f** [comment]
Application-specific passwords provide only a false sense of security if you don't have your device encrypted or at least have a PIN code set up. If you do have either or both of those, they serve no additional purpose.
