### ISSUE TITLE
Conversations shows an "unread" messages mark when there's no one

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#1270]
With the last release, Conversations shows a number on the launcher icon telling us how much unread messages we have, but sometimes it shows me that I have some messages to read when I really don't. I opened all the chats and is still there.

**Comment by iNPUTmice** [comment]
Can you try to provide steps to reproduce this? Otherwise there is very little I can do about this. Thank you

**Comment by moshpirit** [comment]
When Conversations starts, for example, my smartphone has a Gib of RAM and I sometimes have to reboot it. The thing is that it shows the mark for a while, but it's like 10 - 20 minutes. I tried to open all the chats and connect all the accounts.
