### ISSUE TITLE
Http Upload 

### ISSUE THREAD

**Issue by TadbirPaydar** [siacs/Conversations#1272]
Hello
in version 1.4.7 you have added http upload .
i wanna see how can i config my server for availability of this feature.
i have prosody .

**Comment by iNPUTmice** [comment]
> in version 1.4.7 you have added http upload.

not true. where did you get this information from?

**Comment by TadbirPaydar** [comment]
you merged feature/http_upload to development branch.
and in your code getFeature().HttpUload();

**Comment by strb** [comment]
HttpUpload is in the development branch because it is being tested at the moment. Releases are made from the master branch. As you can tell from the tagged release, those HttpUpload commits are not part of 1.4.7.
