### ISSUE TITLE
OpenPGP Key change not possible

### ISSUE THREAD

**Issue by MiskyWhixer** [siacs/Conversations#1276]
I try to change my OpenPGP Key.
The new key is registered in OpenKeychain.
Conversations is permitted to use the key:
http://miskywhixer.de/Bilder/Screenshot_OpenKeychain.png

When I try to publish the new key in Conversations for an account I get this error message:
http://miskywhixer.de/Bilder/Screenshot_Conversations.png
(An unknown error has occurred - Error with OpenKeychain)

Conversations Version: 1.4.7
OpenKeychain Version: 3.3

**Comment by iNPUTmice** [comment]
can you attach an adb logcat output for that?

**Comment by MiskyWhixer** [comment]
With OpenKeychain 3.4.1 it works again.
