### ISSUE TITLE
High bandwidth usage

### ISSUE THREAD

**Issue by aracnus** [siacs/Conversations#1286]
Hi,

I'm using Conversations 1.4.7 (downloaded from F-Droid) and noticed an increase on bandwidth usage recently, about 13Mb in less than 10 days (and I practically didn't used Conversations these days). My Android is 5.1 on a Moto X (Brazilian 1st generation) machine, updated recently.

Is there any problem with the recent versions of Conversations or between it and Android 5.1? And this is a general problem or just with me?

Regards.

**Comment by iNPUTmice** [comment]
> Is there any problem with the recent versions of Conversations or between it and Android 5.1? 

there are no known problems.

Also 1.3MiB / day doesn't sound that much... Even though I don't have any comparison. Do you have comparison values of how much data it would consume prior?

**Comment by aracnus** [comment]
Thank you for your answer, iNPUTmice.  :-)

The problem is that I don't have a comparison too, but thought that was odd a messenger consums more data than a mail client. But maybe it's just my lack of knowledge.  :-)

**Comment by iNPUTmice** [comment]
@aracnus read the [paragraph regarding mobile optimizations on our website](http://conversations.im/#xmpp) and make sure your server supports these extensions.
