### ISSUE TITLE
Python Script server.py on Open fire

### ISSUE THREAD

**Issue by VedantaBabaria** [siacs/Conversations#1288]
As mentioned in new feature of conversation, for uploading file on server, one needs to invoke HTTP upload component on server. 
My server is based on Open Fire(Windows), I have no clue about python on it. Please someone guide me through to invoke the component.

**Comment by danielreuther** [comment]
Not sure what you're asking exactly, but it should be relatively straight forward to get the component running. It at least was on Linux.

If Python and the required dependencies (at least YAML and SleekXMPP) are installed, you'll just need to make sure that a) the component can talk to the server and b) it is reachable to the outside world.

For a), you'll most likely need to adjust the port on either the OpenFire side or within the script (OF is defaulting to 5275 AFAIK and the component is hardcoded to use 5347.

As for b), you'll probably want to front the HTTP server part with an Apache or the like. Especially for handling SSL termination.

Oh, and you'll most likely also want to make the component start up automatically, of course :)

HTH

**Comment by strb** [comment]
This is a bug tracker, not a support forum. If there are bugs preventing you from using the component, please open an issue with [siacs/HttpUploadComponent](https://github.com/siacs/HttpUploadComponent).
