### ISSUE TITLE
Add BOSH (XEP-0124 & 0206) for Public Wifis/Guest-Networks

### ISSUE THREAD

**Issue by drdownload** [siacs/Conversations#129]
The Issue with most open Wifis are port / packet restrictions, it would be nice to add Support for BOSH and BOSH extensions to allow a fallback if the normal XMPP Connection fails.

http://xmpp.org/extensions/xep-0124.html
http://xmpp.org/extensions/xep-0206.html

**Comment by robert-scheck** [comment]
+1 for BOSH support

**Comment by iNPUTmice** [comment]
Closing this because #1170 is basically duplicate. Different but arguable better standard.

**Comment by robert-scheck** [comment]
Even if I agree that WebSocket makes sense future-wise, I wonder if it is really a good idea to defer BOSH support, because e.g. Prosody 0.9.8 (which I treat as a common XMPP server) doesn't ship WebSocket support out of the box AFAIK.

**Comment by SamWhited** [comment]
BOSH has an extremely high transport overhead compared to websockets and will most likely be considered an EOL technology in the near future (thanks to websockets). Conversations is a forward looking client; there's no reason to spend time implementing something now, just to throw it out and replace it in a few months.

**Comment by PeterEdens** [comment]
A library for reducing the BOSH overhead [library](https://github.com/matthewmgamble/xmppprebind)
