### ISSUE TITLE
[Feature]Adding support to automatically delete contact from other end if it's deleted from one end

### ISSUE THREAD

**Issue by Ankew2011** [siacs/Conversations#1291]
Hello sir first of all congratulations for the wonderful work,its a treat to use Conversations for its the best xmpp client.I have a feature request that the only problem iam facing is that if someone delete a contact from his roster it gets deleted from his end but not from other end and this creates confusion for the other person continues to message me.It would be a treat if you can add this feature in Conversations for its a pleasure to use it so far.

**Comment by iNPUTmice** [comment]
The roster is just a 'telephone book'. It doesn't make sense to remove it from the other end. A user could theoretically still message you even if your JID isn't in his or hers roster. Meaning the roster has nothing to do with who can and can not send you messages. If you want to prevent a user from sending you messages you can block the user. (This might require a supporting server)
