### ISSUE TITLE
Chat history showing only ciphered text

### ISSUE THREAD

**Issue by viric** [siacs/Conversations#1292]
With some contacts, using OTR, the chat history works fine as long as the conversation runs, but after some hours of having Conversations in background, or rebooting the Android system, when I go back to the chat history panel, it only shows the OTR encoded messages: ?OTRv3?sadhfqwiefhqlwiefhasdbasblablablablabbla= (and alike)

Instead of seeing the words we interchanged, only OTR garbage appears in the conversation.

I think that I started seeing this since some 1.4.0 version, and I still see it in 1.5.0.

This happens to me only with some contacts, despite I have contacts which use Conversations where we see this problem, and others where we do not.

**Comment by iNPUTmice** [comment]
Thats your MAM ignoring the no-permanent-store hint.

**Comment by viric** [comment]
Sorry, I don't know MAM. If it is an Android setting, shouldn't that mean that all chats should suffer that problem, of seeing only ciphered text in the chat history?

Thank you.

**Comment by viric** [comment]
Ah I guess it's an XMPP thing. http://xmpp.org/extensions/xep-0334.html#no-permanent-store

I'm using jabber.at, because it had good support of the DNS services and :443 working. Do you mean it is a bug from the server? At the end, a hint is a request that does not necessarily have to be fulfilled. Do I understand it right?

**Comment by iNPUTmice** [comment]
Yes you are correct with the hint and the MAM thing. jabber.at is a perfectly fine server. I will ask around what MAM version they are using these days (unfortunately there are two at the moment)

> ?OTRv3?

this doesn't sound like conversations though... Are these received messages you are talking about? Or do these messages appear as sent? And if received what client is your contact using?

**Comment by viric** [comment]
Sorry, it was not ?OTRv3?... I typed that by head, not seeing the screen. The messages are: ?OTR:AAMRD0IsNAhn......=.

**Comment by viric** [comment]
My chat colleague is also at jabber.at with Conversations. I see the ?OTR:blablablabla messages in the whole history, both from me and from my colleague. There are also some ?OTRv23?... start of OTR messages.

Not ALL messages appear like ?OTR:blablabla, but most of them do. In the one I look at now, there are some 'keylock icon' messages properly shown as first two messages (one from me, the other from the colleague), but the 3rd message is already ?OTR:blablabla, until the 10th message interchanged (last).

I have cleared the history several times the last weeks, but this problem keeps on appearing regularly.

**Comment by viric** [comment]
Please note that while chatting, I never see the ?OTR:blabla garbage. All recently received messages look fine. But after some days of not looking at the chat (maybe with some Android reboot in the middle), when I go back to that chat I see the garbage instead of the messages.

**Comment by iNPUTmice** [comment]
This has been 'fixed' in a5027104fdc3e64bf40a5764a2cf2bbd27a4ba99
