### ISSUE TITLE
Very bad performance in GUI

### ISSUE THREAD

**Issue by mzsergiu** [siacs/Conversations#1296]
With the latest release 1.5.2 just compiled from SVN, with the new green marking in chat, i have a very bad performance on scrolling on blackberry 10.3.2. Blackberry has library for 4.3 and with version 1.5.0 is working perfectly. 

Can you help me on this? 1.5.2 is not usable.

**Comment by iNPUTmice** [comment]
What branch? I'm assuming dev. Please go back to _before_ 74e05023b4f884b31876357c013513c51aff5369 and report if thats any better. before means b7ff2c34614a92f3893732338f75cb0f7fe77d32 for example.

**Comment by mzsergiu** [comment]
b7ff2c3 -> compiled in 1.5.0 and has same behavior. It has same green marking in chat, and when i scroll, gui simply freezes, also when I slide out to select another person for conversation.

**Comment by mzsergiu** [comment]
012f036 - Optimize imports ------->  I get when scroll the conversation or slide to see contacts small blocking, is not fluid. (this version is after 9c91b90 in repository), compile size 4.6 mb
9c91b90 - don`t show "show contacts" context menu item when contact isn not in roster -------->  works perfectly, fluid on scroll of conversation or contacts. compile size 3.7 mb

**Comment by iNPUTmice** [comment]
012f036840ade8f46462eafcc96d1f223f8ba845 simply can not be the cause of this. This commit doesn't do anything.

Candidates for commits with impact on performance are: 504ef0b72ebd951e3f3f493435fb96713a2b4efe e6cb12dfe414497b4317820497985c110cb81864 and 74e05023b4f884b31876357c013513c51aff5369

**Comment by mzsergiu** [comment]
then why when I compile 9c91b90 I get. apk of 3.7 mb and if I compile the next one that does nothing 012f036 I get 4.6 mb the. apk, 1 mb o data??!!!??! I d the compile with Android Studio. what is the size of. apk you get from compile latest version?

**Comment by iNPUTmice** [comment]
> then why when I compile 9c91b90 I get. apk of 3.7 mb and if I compile the next one that does nothing 012f036 I get 4.6 mb the

I don't know. Maybe you didn't clear before building or checked out something else. Just look at the commit. It doesn't change any code. It's just a reformat.

**Comment by mzsergiu** [comment]
I confirm that if I compile the master branch everything works smooth :) and the size is 2.9 mb, so is not my compiler the problem.

**Comment by iNPUTmice** [comment]
Nobody was trying to blame your compiler. If you could help us now to figure out which of the above mentioned commits is to blame for this we might be able to do something about it. Otherwise the problem will just come back after the 1.6 release.

**Comment by mzsergiu** [comment]
I explain again, 

I compile: 9c91b90 everything works perfectly and the output size is: 3.7mb
I compile: 012f036 (next comit) and everything is slugish, outpute size: 4.6mb
All the other compiles after the 012f036 are slugish! I tested them one by one.

This is in branch Development.

If I change for branch Master and compile, the version shows 1.5.2 also the size of apk is 2.9 mb abd everything works perfectly.

Now, I dont have any explanation, can you please compile in Development branch the last code and sned it to me to test it?

Thanks!

**Comment by iNPUTmice** [comment]
Is this still a problem? What kind of blackberry do you use?

**Comment by mzsergiu** [comment]
I have master branch compiled 1.6.9 and works perfect now, 

I have Blackberry Passport with OS 10.3.2.2639  - I know that he has Android 4.3 as runtime

**Comment by iNPUTmice** [comment]
Ok thanks.
