### ISSUE TITLE
Cannot save received files of unknown type

### ISSUE THREAD

**Issue by viric** [siacs/Conversations#1297]
I received a file of a type unknown to Android, but there is only an "Open" button. Clicking it, it says "No application can open it". With long-click, I can only "Share" the file.

It'd be nice if there were a "Save to file" button.

**Comment by iNPUTmice** [comment]
it is already saved. You can find the file in storage/Conversations

**Comment by jkufner** [comment]
Then it should inform user about where the file is stored.
