### ISSUE TITLE
since 1.5.0 conversations needs more battery power

### ISSUE THREAD

**Issue by hschraep** [siacs/Conversations#1300]
I think since the update to 1.5.0 conversations needs more power. In the past it needed 6% after the update it needs now 21% can you have a look . And have other also seen this?

**Comment by slammming** [comment]
Check for excessive network activity?

**Comment by hschraep** [comment]
Looks like it was a one day Problem.

**Comment by languitar** [comment]
I am also constantly experiencing high battery usage. How can I provide debug information?

**Comment by iNPUTmice** [comment]
@languitar make sure you are using all the mobile optimization XEPs mention in our README and our website. Especially stream management and CSI (you might have to turn on presence throttling)
Also make sure your session time (in Account Details) is relatively high. (Several hours to days)

**Comment by languitar** [comment]
All XEPs listed in the server information are available on my server and sessions keeps alive for at least a few hours. Still, Conversations is the most prominent battery consumer.

**Comment by iNPUTmice** [comment]
@languitar the question is have you configured presence throtteling. Since the default is off afair.

**Comment by languitar** [comment]
@iNPUTmice Any idea how to do that for ejabberd?

**Comment by languitar** [comment]
@weiss do you know how to enable presence throtteling in ejabberd?

**Comment by weiss** [comment]
> do you know how to enable presence throtteling in ejabberd?

    modules:
      # [...]
      mod_client_state:
        queue_presence: true

While at it, I would also set `drop_chat_states: true`.  See [the Guide][1] for details.

[1]: http://docs.ejabberd.im/admin/guide/configuration/#modclientstate

**Comment by languitar** [comment]
@weiss thank you. I always have a hard time finding the appropriate documentation for ejabberd.

**Comment by languitar** [comment]
Ok, presence throttling drastically decreased the battery consumption. Maybe it would be good to add this feature to the server information?

**Comment by iNPUTmice** [comment]
> Maybe it would be good to add this feature to the server information?

CSI is part of the server information. Conversations can not detect if you have configured your server correctly though.

**Comment by danielegobbetti** [comment]
Just adding some info for prosody. The modules to enable are:
[csi](https://code.google.com/p/prosody-modules/wiki/mod_csi)
[throttle_presence](https://code.google.com/p/prosody-modules/wiki/mod_throttle_presence)
[filter_chatstates](https://code.google.com/p/prosody-modules/wiki/mod_filter_chatstates)

HTH
