### ISSUE TITLE
MUC delay subject spam on reconnect

### ISSUE THREAD

**Issue by zeeZ** [siacs/Conversations#1301]
On every reconnect I get a notification that the subject was changed.
![screenshot_2015-07-23-12-11-55](https://cloud.githubusercontent.com/assets/715896/8858533/3ced1ee0-3178-11e5-8d77-9511f4631be7.png)

In pidgin I get two different related messages depending on if the subject change was recent during delay spam
```xml
<message from='s...@....uk/zeeZ' to='zeez@....uk/Pidgin' type='groupchat'>
	<subject>There is no topic</subject>
	<delay xmlns='urn:xmpp:delay' from='s...@....uk' stamp='2015-07-14T10:53:09Z'/>
	<x xmlns='jabber:x:delay' stamp='20150714T10:53:09'/>
</message>
```
or past history immediately after delay spam
```xml
<message from='s...@....uk' to='zeez@....uk/Pidgin' type='groupchat'>
	<subject>There is no topic</subject>
	<body>zeeZ has set the subject to: There is no topic</body>
</message>
```

If it's super recent I don't get the repeat message in Conversations, but it'll eventually start doing that again. Not sure if that's a bug, a feature request or a really weird server I'm dealing with.

**Comment by iNPUTmice** [comment]
duplicate. Search this issue tracker for subject

**Comment by zeeZ** [comment]
Oh right, closed ones exist. Whoops, I apologize.
