### ISSUE TITLE
stop hammering 8.8.8.8

### ISSUE THREAD

**Issue by slammming** [siacs/Conversations#1302]
30 some requests per second endlessly seems a little excessive?  That address is blacklisted here. Names resolve fine without google NS.

v147,v150

**Comment by slammming** [comment]
http://i.imgur.com/XspUF8y.jpg

**Comment by jkufner** [comment]
Why it calls Google's DNS in the first place?

**Comment by iNPUTmice** [comment]
Can you provide the adb logcat output for this?

**Comment by slammming** [comment]
@iNPUTmice, is there a suggested article on how to do this?  I shall happily comply. Kk444

**Comment by iNPUTmice** [comment]
OK.

adb ist the Android debug bridge. it can usually be found in your distributions repository under the name android-tools or something (search for android). after you installed it you connect your phone with the computer (might have to enable developer mode on your phone) and invoke
adb logcat -s conversations
and do what ever causes the 'hammering'

there are also apps that let you watch the logcat output on your phone (you can search the playstore for logcat) but I don't have personal experience with any of them.
