### ISSUE TITLE
Best server configuration 

### ISSUE THREAD

**Issue by TadbirPaydar** [siacs/Conversations#1304]
What are necessary modules to setup in prosody for having best performance with Conversations.
I suggest @iNPUTmice to post http://siacs.eu configuration file as a best practice plz.

**Comment by andersruneson** [comment]
If you check server info under your account detail you'll find a list of
XEPs that is needed for good performance. I also believe that those are
listed on conversations.im and in the github readme.

Please join the conversations muc for further questions.
