### ISSUE TITLE
Duplicate messages when send to myself

### ISSUE THREAD

**Issue by jwbargsten** [siacs/Conversations#1305]
If I send messages to myself, I get the same message two times. I don't know if this is bad behaviour of the jabber server (I use jabber.ccc.de), XMPP protocol or indeed a bug. Some details:

I'm logged in on my home PC with gajim
1. I send from my home PC to myself a message -> double message arrives at Conversations
2. I send a message in conversations to myself -> double message shows at conversations

for 2. it does not matter if I'm logged in on the PC or not.

Version: 1.5.2

**Comment by iNPUTmice** [comment]
yeah that's the sent message and the arriving message. this is pretty much standard behavior across all xmpp servers. I don't know what you are expecting? the server to just not deliver the message?

**Comment by jwbargsten** [comment]
I see, clear. However, if I send from my PC to my phone, I would not expect that the message pops up two times on my phone. My phone is not the sender, so why should I get it twice on my phone?

**Comment by iNPUTmice** [comment]
If you send a message from your PC to a third party that sent message will also show up on your phone. Why should that be different if you send a message to yourself?

**Comment by jwbargsten** [comment]
Hehe, you are right. Somehow I never noticed that all my PC messages show up in Conversations (I just have it for some days and did not chat much). Thanks for clarification and sorry for wasting your time. Great application by the way!
