### ISSUE TITLE
"Delivery failed" but I get all messages from the chat group (Other XMPP clients works ok)

### ISSUE THREAD

**Issue by atari130xe** [siacs/Conversations#1308]
For some reasons I can't send any message to a chat group (XMPP server suchat.org) but I can receive and read all messages from the group. What could be the issue? any clue? Thanks in advance
PS: I am using Xabber client and messages can be send to the same chat group without problems.
Jose

**Comment by iNPUTmice** [comment]
Can you update to latest HEAD and check with adb logcat? Conversations should be printing the failure reason now.

**Comment by atari130xe** [comment]
Already solved, thanks!

**Comment by andersruneson** [comment]
What was the problem?
I'm having the same symptoms.

**Comment by atari130xe** [comment]
I am not sure but I reinstalled the app and the issue is gone.

**Comment by andersruneson** [comment]
This is the adb debug message I get:

"sending message to conversations@conference.siacs.eu failed -
Server-to-server connection failed: DNS resolution failed"

/Anders

**Comment by philipflohr** [comment]
I had the same problem. 
Acually this is not a problem of Conversations but of your XMPP servers DNS settings
Try to add a reliable DNS server to your server (eg 8.8.8.8) if you run your own server or tell the server admin to do so.

**Comment by andersruneson** [comment]
This was on jabber.de, they did not respond to my email about this so I
switched to jabber.at.

You can close this issue even if I rather have Conversations handle this
somehow.

**Comment by iNPUTmice** [comment]
Ok. I'm closing here because:

> Acually this is not a problem of Conversations but of your XMPP servers DNS settings

this is what I thought as well.

> I rather have Conversations handle this somehow.

I just don't think this is possible.
