### ISSUE TITLE
Suggestion for a better file transfer handling

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1309]
I think the file transfer handling should be improved a bit, as we can share files via httpUploadComponent. For this case a file which had been shared and shall be shared again, Conversations should only send the file link instead of sharing the file again. Maybe you could rethink your statement from #654 for all file types listed under ´WELL_KNOWN_EXTENSIONS` and images, too.

Maybe the httpUploadComponent could check, if the same file is already existing on the server and should answer with a link, before uploading the file again. 

What do you think about that?

**Comment by jruere** [comment]
If this is implemented, please check the URL is still working before re-using.
