### ISSUE TITLE
Suggestion: Build poll-feature for conferences

### ISSUE THREAD

**Issue by MaRies25** [siacs/Conversations#1312]
A poll-feature that let's users ask a poll in a conference, e.g. to find a suitable date for a meeting or choose something so you don't have to do it via doodle. would be extremely useful!

![poll-feature](https://cloud.githubusercontent.com/assets/13640411/9059624/dea9762a-3aab-11e5-9aca-da8aaa25d7fc.png)

Each user get's notified and can fill it in once (or even change the answers depending on setting by poll-author if that's not too complicated). The result is visible to all (with the names who ticked what). 

Poll-Author should have the following settings:
Adjustable number of slots (show 1 more than is currently filled in)
Changeable or finite when someone ticks answers
End-Date and time (no changes/entries afterwards)
Possible answers: YES/NO  OR YES/NO/MAYBE
Users can add possible answers YES/NO
Click on 'finish poll' anytime to freeze the result

The result should show the absolute number (or percentage) for Yes/no/maybe for each answer and present the current 'best choice' as well as the number of participants + the 'number of missing replys' (=conference members-number of people who filled it in). If the poll has reached the end-date or the author finishes the poll (or everyone has answered), the poll freezes and posts it's results in the conference.

Possible addons: do a picture-poll (e.g. to let conference members vote for designs/pictures)

**Comment by SamWhited** [comment]
This is way outside the scope of a simple chat client, and a bot is probably the better answer here anyways.

**Comment by iNPUTmice** [comment]
Out of scope
