### ISSUE TITLE
Feature request: Message search

### ISSUE THREAD

**Issue by weiss** [siacs/Conversations#1315]
It would be nice if you could search for messages within conversations, similar to the search feature for the contact list.

I posted a [Bounty for this feature](https://www.bountysource.com/issues/25371199-feature-request-message-search).

**Comment by kbailey4444** [comment]
Would this be searching for a message within a specific conversation or searching through all conversations?

**Comment by weiss** [comment]
I would like to be able to search within a specific conversation.  When looking for some message(s), I usually remember who I talked to.

**Comment by rigid** [comment]
:+1:

**Comment by derlaft** [comment]
Wow, that's a lot of code in ConversationsActivity :) I will have a look, but not promise to implement

**Comment by derlaft** [comment]
Hmm.

As I understand, the problem is with XEP-0313.
  * Ejabberd mod_mam supports fetching messages with specific text (withText), but I have no idea how to check if current server supports it 
  * Prosody does not suppport it
What should Conversations do if ``withtext`` is unavailable?
  * Download every single message from a server (lots of time traffic) and then search
  * Search local messages only

What do you think?

**Comment by weiss** [comment]
> Ejabberd mod_mam supports fetching messages with specific text (`withtext`), but I have no idea how to check if current server supports it

The available form fields can be [queried][1], but unfortunately, ejabberd doesn't support such form requests and won't support them in the upcoming 16.01 release.  They will most probably be [supported][2] in the following release, though.

However, the real problem is that the `withtext` name is not standardized, and I'm not quite sure what to do about that.

> What should Conversations do if `withtext` is unavailable?

I'd say it should fall back to just searching local messages.

[1]: http://xmpp.org/extensions/xep-0313.html#query-form
[2]: https://github.com/weiss/ejabberd/commit/558f8243d4eaec80ed7a76b7fe725f3499d6a0fb

**Comment by rigid** [comment]
@derlaft the account settings -> account -> "server info" displays whether XEP-0313 is available, maybe you could use that?

I'm for "search local messages" as a fallback. (Also if there's no network connection)

**Comment by weiss** [comment]
So one idea would be: Perform a local search.  If that doesn't yield enough results, [check][1] whether the server offers a `withtext` search, and use that to get more results.  The `withtext` name could be replaced once another name is standardized (this has been suggested in the past).  I could provide an account to test the `withtext` feature if that helps.

However, I'm not sure this is really worth the hassle.  Server-side search won't work for OMEMO-encrypted messages, for example.  So personally, I'd actually be fine with having only local search implemented.

[1]: http://xmpp.org/extensions/xep-0313.html#query-form

**Comment by mlangguth** [comment]
+1 for "search local messages"

**Comment by moshpirit** [comment]
+1

**Comment by moshpirit** [comment]
>Would this be searching for a message within a specific conversation or **searching through all conversations**?

That would be amazing too and also would deal with the non-space in the chat menu.  
For chat search it could be an option to press the conversation and get a menu that allowed us to "search locally".

**Comment by mytbk** [comment]
I also need a feature "search locally", because I have a lot of chat history saved on my phone and it's hard to find a message with a certain keyword.

**Comment by Dehumanizer77** [comment]
Any news on the local message search? Is it hard to implement?

**Comment by vanitasvitae** [comment]
It would be really cool to have this feature. Would be a nice task for GSoC, wouldn't it?

**Comment by TheGrave** [comment]
And how does that work? I found only this in the changelog which means nothing to me:

Version 1.12.3

    start typing in StartConversationsActivity to search

**Comment by licaon-kter** [comment]
Search messages is not implemented.

The changelog talks about contact search.

**Comment by moshpirit** [comment]
Is the Bounty official for this feature? I mean, if we get the 200$ goal is it sure that we can get this feature (a chat searcher) on Conversations for real?

**Comment by licaon-kter** [comment]
Either https://github.com/siacs/Conversations/pull/2446 or someone could port the one from Pix-Art

**Comment by weiss** [comment]
> or someone could port the one from Pix-Art

Judging from the screen shots I've seen, Pix-Art added this as a new feature from scratch.  Wouldn't it make more sense to re-use the existing contact/groupchat search (at least UI-wise but presumably also code-wise)?

**Comment by iNPUTmice** [comment]
Implementing this »properly« is fairly complicated on multiple levels. It has become a bit easier due to the UI refactor in 2.0 though.
(The UI in terms of how the search bar looks like is probably rather insignificant compared to the rest)
In any case message search has finally made it on my internal TODO list after Berlin. Not giving any ETAs but it is on there.

**Comment by alexara** [comment]
@iNPUTmice Since 2.2.0-beta offers a simple message search, which already works pretty good is quiet fast, 
it would be great if you could also jump to the message in the history by clicking on a search result (and to be able to go back to the message search again). :-)

**Comment by iNPUTmice** [comment]
This has been implemented in 2.2.0 which is available on F-Droid and rolling out on Google Play right now.
