### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by balamurugann** [siacs/Conversations#1318]
08-06 15:04:36.653: E/AndroidRuntime(29205): java.lang.NoClassDefFoundError: org.whispersystems.libaxolotl.state.StorageProtos$IdentityKeyPairStructure

I am getting this crash issue and am using tool Eclipse.

Please provide the solution for this.

**Comment by iNPUTmice** [comment]
please use Android Studio (or a manual gradle based build)
