### ISSUE TITLE
Message Carbons not working as expected?

### ISSUE THREAD

**Issue by kr428** [siacs/Conversations#1319]
Folks;

not sure whether this is an actual bug or a misconfiguration, but it's difficult to know where to start searching: Our openfire server does support Message Carbons. When using Xabber on Android while at the same time being connected via pidgin on the desktop, I manage to receive the message on both clients. However, being connected via Conversations, messages seem to only be received on the mobile device. That's a bit strange but I am unsure how to trace this down. Any ideas?
TIA and all the best,
Kristian

**Comment by iNPUTmice** [comment]
to my knowledge neither pidgin nor xabber support carbons.
which means messages sent from pidgin or xabber will show up on
conversations. but not vice versa.
incoming messages will always show up in conversations *and* which ever
client the message would have normally be routed to. (the one with the
highest priority)

don't use xabber. put pidgin in a higher priority than conversations (aka
>0) or use a client with carbon support on your desktop like gajim.

**Comment by kr428** [comment]
First off, thanks a bunch for your continuing support and your patience. ;) Actually, this all is to some point pretty confusing; it's difficult to figure out which application does support which XEP / spec in which quality and what needs to be done to actually achieve a certain behaviour.

Right now, with Conversations / pidgin, I need to manually disable accounts on the smartphone to make sure accounts appear on the desktop. This is strange. I'll have a look at gajim, didn't use this for ages. Actually, maybe I'm just too stupid to do it right, but in the end, all I want to achieve is a setup where...

- messages appear first on my desktop if I'm online,
- messages appear first on my phone whenever my desktop is offline or "away",
- full message log is available to all connected devices.

So far I figured out that priority settings, Message Carbons and server-sided message archives would do the job, but I am more and more unsure...

**Comment by iNPUTmice** [comment]
if you have carbons in all your clients you don't have to set priorities
any more.

so carbon support is what you are really after. go with gajim or maybe
mcabber in a screen session somewhere. that's what most (citation needed)
Conversations users do these days.

**Comment by kr428** [comment]
Thanks... I'll give it a try then. As far as I have seen by now, gajim does support message archives but doesn't fetch old messages off the archive so I lose history this way. Seems one price is always to be paid for this...

**Comment by kr428** [comment]
I'll close this now. It doesn't seem a Conversation issue and I continuously (now) fail to get it working as desired with _any_ combination of clients. Posted this to the openfire forum (https://community.igniterealtime.org/message/251094#251094 , for whatever it's worth); maybe someone over there knows. Thanks for your support!

**Comment by djmaze** [comment]
@kr428 You could also try a patched version of Pidgin with carbon support. [For Windows](https://github.com/Draghtnod/Pidgin-GPG/releases) or [for Linux (build instructions)](https://developer.pidgin.im/ticket/15508#comment:22).

Also, it sounds like this will be finally incorporated into Pidgin [officially](https://developer.pidgin.im/ticket/15508#comment:45).
