### ISSUE TITLE
Axolotl -> Multi_end no keys can be used

### ISSUE THREAD

**Issue by danielegobbetti** [siacs/Conversations#1320]
Hello,

I compiled the development version at first when 1.5.2 was out (I'm sorry I don't have the original commit id I used for the build) and tested axolotl support with one of my contacts. This means we both generated axolotl keys and we were able to exchange messages encrypted with axolotl.

After upgrading to 1.6.0 beta (both of us), we cannot use axolotl anymore. We tried removing each other's keys (which worked) but now we cannot add the keys again. When we start an axolotl conversation the activity to trust the other contact's key is shown, but remain empty.

I wanted to try removing my own axolotl key and generating a new one, but it seems to be unsupported. As I would like to keep my OTR fingerprint, can you suggest a way to fix the issue? Is there something I can do to help you preventing it from happening to other users?

Thanks!

**Comment by strb** [comment]
Hey, thanks for reporting. I've got some theories as to what caused this, but I need a few more pieces of information. What exactly do you mean when you say that you couldn't use it after the update anymore? The option was not selectable in the menu? The messages were not delivered? Also, how exactly did you remove each other's keys? Via the long-press "Purge Key" action?

As a temporary fix you could set SHOW_REGENERATE_AXOLOLTL_KEYS_BUTTON to true in Config.java:45. This will give you a button to regenerate your key.

**Comment by danielegobbetti** [comment]
Hi, sorry for not being more clear reporting the issue!

The option was selectable and the message appeared as normally sent (with lock and all) but were never received by the other party. (maybe they were delivered but not shown by conversations? I don't know)

We both deleted the keys using the long press functionality,  yes.

The multi end option is still available to both of us, but no key is shown after sending the first message.

Thanks for the workaround! I can keep the current key if it could be useful for further tests. :)
--

**Comment by strb** [comment]
As far as your initial problem with messages not arriving is concerned, it's hard to tell what caused this. Now that the keys are purged, they will never be used by Conversations anymore anyway, so we can't test this further. So just go ahead and regenerate the keys. But if this problem reoccurs, and you're able to reproduce it, please try to get adb logcat output from both devices.

The fact that you can't re-add a key after long-press purging it is a "feature". Once you purge a key, Conversations will consider it compromised. It will not show the key to you any more, but it will remember to never accept that key again. Maybe we could word the confirmation pop-up message more clearly on this...

Multi-end still being available if there are no viable keys for the contact is a bug. You should never be dropped into the TrustKeysActivity if there are no keys you can trust. I'll work on a fix for that.

**Comment by danielegobbetti** [comment]
I see. I believe that TrustKeyActivity could be shown, but it should show a big fat advice that no keys can be trusted for the contact. In fact I fear that disallowing the option for multi end encryption could be confusing for the user, if he knows that both him and the person he is speaking with have multi end encryption support.

--

**Comment by iNPUTmice** [comment]
fixed in 1.6.0
