### ISSUE TITLE
Share with Contact & Return

### ISSUE THREAD

**Issue by allo-** [siacs/Conversations#1321]
There should be some options to share from an app and fast returning to it.

current situation (5 steps):

- share with conversations
- select contact / open conversation
- send
- Hit back
- Hit back

Feature 1: Share & Return (3 steps)

- share with conversations
- select contact
- send (closes conversations, returning to the app before)

Feature 2: Instant share (2 Steps)

- share with conversations
- preview of text (i.e. url) is shown, contact/conversations list as well
- touch one and the text is sent and conversations closed afterwards

Feature 3 (maybe): Share with specific/last contact (1 Step)
- Share with conversions (last contact): Instantly sends the text, not even showing conversations (but some toast / notification area text)

As this might clutter the "share with" menu, there should be options to select, which intents should be offered, and for Feature 3 there could be an option "add share with THIS_CONTACT to share-menu".

**Comment by allo-** [comment]
Is there a reason, why this was only implemented for android 6.0? Easier API for such things?

**Comment by iNPUTmice** [comment]
> Is there a reason, why this was only implemented for android 6.0? Easier API for such things?

yes

**Comment by allo-** [comment]
Isn't it possible to have some way for android 4/5 as well? Like choosing the contact like before, but after hitting send the activity is closed.

**Comment by allo-** [comment]
While this works on Android 6 for "share via message" like intents, it neither works for "share url" in firefox nor for "share tweet" in twitter, while the "Conversations" App without direct share is available. This should be extended to the more general "share text" intent, so things like fastly sharing an url is possible.
