### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by hemin8390** [siacs/Conversations#1325]
I am an android developer and currently working on a chat app using your code of Conversation app. Now i am able to communicate between device, but somehow i am not able to understand its database flow.

I have a query as i want to implement an auto delete functionality in database like when i set time while sending the XML of message and when received it should check the time and after that time it should be deleted from database. So the concept is to delete the message after few seconds or minutes or any particular time. Please guide me how can i delete the messages from your created database.

Thanks in advance.

**Comment by iNPUTmice** [comment]
Hi,

this is not the right place to ask this kind of questions. If you need help modifying Conversations to suit your personal needs please use the contact information provided under 'Need professional support?' on our website: http://conversations.im/#support
