### ISSUE TITLE
[request] vCard support

### ISSUE THREAD

**Issue by Dragnucs** [siacs/Conversations#1327]
Hello,

I think it would be great if Conversations support vCard and even pubsub. being able to see information about ones contacts vias vCard like, Avatar, email, location, bio etc. is very useful to me.

Also a pubsub support like in webclients like jappix and movim would make Conversations the best XMPP in the world.

Thank you.

**Comment by iNPUTmice** [comment]
Conversations is deliberately not a social networking app. If you want social networking there are already alternatives like movim for example.

**Comment by ildar** [comment]
@iNPUTmice, you must have got it wrong. This is not about social nets features.
vCard is used in xmpp to get basic contact's information like Name and Surname.
Actually it's ridiculous that a user can't get any information about his peer besides JID (useless) and photo (which is optional).

**Comment by Dragnucs** [comment]
@iNPUTmice +1

On 16 April 2016 05:25:10 WEST, ildar <notifications@github.com> wrote:
>@iNPUTmice, you must have got it wrong. This is not about social nets
>features.
>vCard is used in xmpp to get basic contact's information like Name and
>Surname.
>Actually it's ridiculous that a user can't get any information about
>his peer besides JID (useless) and photo (which is optional).
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/siacs/Conversations/issues/1327#issuecomment-210733420

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by petmue** [comment]
> @iNPUTmice, you must have got it wrong. This is not about social nets features.
vCard is used in xmpp to get basic contact's information like Name and Surname.
Actually it's ridiculous that a user can't get any information about his peer besides JID (useless) and photo (which is optional).

I am completely in line with you.

**Comment by vlopezj** [comment]
I agree with @ildar . 
As an example of non-social use case for vCard, the [mod_email_pass](https://github.com/dhotson/prosody-modules/tree/master/mod_email_pass) Prosody module uses the e-mail address in the vCard in order to provide password reset functionality.

**Comment by tuxayo** [comment]
Thanks for creating this issue. Now I get why I never get to see the "cosmetic" name that contacts elect. And only the JID.
