### ISSUE TITLE
Pushbullet API quick-reply support

### ISSUE THREAD

**Issue by Natanji** [siacs/Conversations#1332]
Pushbullet is a widely-used app that enables forwarding notifications from Android to one or multiple other devices, e.g. PCs. They provide an [API](https://docs.pushbullet.com/#messaging) that Conversations could use to quick-reply to incoming messages - without having to glance at the phone, right from the PC that the chat notification was forwarded to.

Would this be a welcome enhancement to Conversations?

**Comment by NOgoogleBits** [comment]
Not If This Requires Either gapps, Or Google framework.

It seems more likely that pushbullet would benefit FROM Xmpp Texting, or Zero MQ.

**Comment by iNPUTmice** [comment]
On of the benefits of XMPP is that you can actually log in on your desktop as well.
