### ISSUE TITLE
[Feature request] Delete messages which could not be send

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1333]
Please let one delete a single or all messages which could not be send. The red text of the error message is rather distracting and when there are many failed messages the message log becomes confusing.

**Comment by iNPUTmice** [comment]
avoiding problems by trying not to look at them might be a common thing among humans but I'd much rather fix the problem than hiding it away.

**Comment by alexara** [comment]
In this case I think it might be helpful if there is a more detailed error message than only "delivary failed". Maby you can introduce error codes in brackets?

**Comment by iNPUTmice** [comment]
adb logcat will show you the error message.
