### ISSUE TITLE
long (>1000 lines) messages break the app

### ISSUE THREAD

**Issue by ajs124** [siacs/Conversations#1338]
Hey,

I wanted to copy and paste someone a text file. So I opened it, copied its content (around 3500 lines), opened the conversation, pasted the content and maybe even managed to hit send.

The app didn't manage to send the message and is basically unresponsive now, every time I open it up, even after rebooting the device.

**Comment by iNPUTmice** [comment]
This has been fixed some versions ago. I just forgot to close here.
