### ISSUE TITLE
Conversations sends error messages when presence error

### ISSUE THREAD

**Issue by aperalesf** [siacs/Conversations#1340]
When I'm on my desktop client and a contact is using Conversations, sometimes it appears a conversation window with messages that say "recipient-unavailable" (not a contact message itself, but a "status change"-like message). I think that happens because Conversations sends an error `<message>` besides the corresponding `<presence>` error. Is the message necessary?

One time I opened the XML console to log this problem, and this is what I got (JIDs are deleted due to privacy reasons). Although the log is from past month, the problem persists. 

```
<!-- In mié 08 jul 2015 18:16:39 CEST -->
<presence from='[CONTACT]' to='[ME]' type='error' id='320'>
<error type='cancel'>
<recipient-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
</error>
</presence>

<!-- In mié 08 jul 2015 18:16:39 CEST -->
<message from=[CONTACT]' to='[ME]'' type='error'>
<error type='cancel'>
<recipient-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
</error>
</message>
```

**Comment by strb** [comment]
These messages most likely originate from your contact's server, indicating that your contact's stream management timed out. Conversations doesn't send these.

**Comment by aperalesf** [comment]
Ah, ok. Thank you @strb :) I'll report to corresponding projects.
