### ISSUE TITLE
Please upgrade the F-droid version 

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#1344]
We still have the 1.5.2 version and the 1.6.0 version was released a week ago, would you mind to upgrade this version, please?

**Comment by andersruneson** [comment]
You should report this to fdroid then.

**Comment by andersruneson** [comment]
Also 1.6 was not released a week ago? Only one or two days ago.

**Comment by iNPUTmice** [comment]
We are not responsible for what ever fdroid does
