### ISSUE TITLE
force encryption

### ISSUE THREAD

**Issue by marix11** [siacs/Conversations#1345]
Force encryption gone in v1.6?  Why?

**Comment by iNPUTmice** [comment]
The force encryption setting was just a work around for a flaky encryption settings. (The lock icon would reset to plain text in unpredictable intervals.) This has been fixed now. And thus the setting is no longer necessary.

If you have further questions please join our conference for further discussions as this is a bug tracker and not a forum.

**Comment by marix11** [comment]
Sorry i didnt know where to ask this. Its very needed option. After upgrading to 1.6 always forgetting encryption

**Comment by pravi** [comment]
I don't want to use plain text at all and this setting was very useful. Consider reintroducing it.

**Comment by iNPUTmice** [comment]
I repeat myself: This setting has only been introduced because of unpredictable behaviour of the 'per conversation' encryption setting. This issue has been fixed and thus makes the setting obsolete.
Just give the new variant a shot for a few days and you'll see you don't need that setting anymore.

On top of that we will probably make  #1350 in the near future.

**Comment by marix11** [comment]
Its more then needed. I cant teach my father everytime enable encryption for example. All chats clients has this option. Like pravi said i dint ever need plain text

**Comment by pravi** [comment]
Even though the original rationale was different, it was useful for people who does not want to use plain text. So I consider it a regression.

**Comment by marix11** [comment]
Its even worse then i through. Other side sens you encrypted msg. You return unencrypted. Please return this option asap

**Comment by d9h02f** [comment]
You only need to select your preferred encryption method _once_. What's the problem?

**Comment by marix11** [comment]
The problem you get msg and reply, used thats auto encrypted like it was till now, but now you reply plain text. Ok you select prefered but need select everytime. For me its very big security issue

**Comment by marix11** [comment]
I still miss this feature. It was very useful for people. 
d9h02f: its not once. Everytime new conversation you need select it. You close chat and need select it again and again

**Comment by marix11** [comment]
Why default is unencrypted always. Maybe you could make it to remember my prefered or last used method. If i select otr or omemo it could remmeber next time
