### ISSUE TITLE
move openpgp option to settings

### ISSUE THREAD

**Issue by pravi** [siacs/Conversations#1351]
I think with omemo available, openpgp option could be moved to settings (ie, show it only when enabled from settings). This will reduce confusion for less technical users while still giving more technical users the option to use it. I think it is an advanced option for most of the users to find it useful. MUC can keep openpgp option.

**Comment by iNPUTmice** [comment]
Not gonna happen for now. Too many people are still using OpenPGP. Conversations 2 will - at some point in the future - only offer OMEMO. But we are no there yet.

**Comment by QuentinC** [comment]
@iNPUTmice I just want to say that PGP has to stay at least while other clients won't offer OMEMO (I'm thinking about Gajim that a lot of people use on computers...).
Right now, the only way to have MAM/Carbons and crypto is PGP, if you aren't only using Conversations !

Thanks !

**Comment by pravi** [comment]
@QuentinC I never got any other client to work reliably with OpenPGP though. I tried two plugins for pidgin (decryption worked with one plugin) and Gajim. So conversations is the only client that works well with GPG anyway. And the gpg XEP has been deprecated already.
