### ISSUE TITLE
Receiving duplicate messages on session reconnects if server provides MAM (jabber.at)

### ISSUE THREAD

**Issue by Tokodomo** [siacs/Conversations#1357]
I am getting duplicate messages on session reconnects, not always but sometimes. PGP encryption is enabled and jabber.at provides MAM. These duplicate messages are not stored on the server, but stored in the database of Conversations. Please take look at my screenshots, one from the client itself and one from the database. The last message ("Aber gut zu wissen...") is a duplicate, something seems wrong with the uuid, timeSent and remoteMsgId in the database.

Conversations-Version: 1.6.3 from Play Store

![msgdup_client](https://cloud.githubusercontent.com/assets/13941754/9438724/c6bf13c0-4a60-11e5-8f9d-1c742e592b63.png)
![msgdup_database](https://cloud.githubusercontent.com/assets/13941754/9438727/d1031be2-4a60-11e5-8dbd-0d45cec1a419.png)

**Comment by ripixxx** [comment]
I have the same Problem with Version 1.6.3. The XMPP-Server running with OpenFire 3.10.2 on Debian Wheezy. The battery is empty very fast and constantly is a server connection.
![screenshot_2015-08-24-19-51-36](https://cloud.githubusercontent.com/assets/3306312/9448056/c2d9a97a-4a9a-11e5-8ee2-d746577b8530.png)
