### ISSUE TITLE
Conversation suddenly causes huge logs in ejabberd

### ISSUE THREAD

**Issue by Jutosa** [siacs/Conversations#1358]
Yesterday I noticed my ejabberd log had grown to a size of 18GB all of a sudden. I couldn't open the file itself anymore but "tail -f" showed me a constant stream of what I think are presence notifications.

As soon as I login the app checks the roster, checks the pubsubs and then announces the presence status to everyone in the roster. I assume it should stop after that but it continues doing so in an endless loop.

I'm using the the version from the play store. I updated to 1.6.3 in the hope it would fix it but it didn't.

I'm running a fairly old ejabberd version on Ubuntu 12.04 LTS -> ejabberd 2.1.10

**Comment by iNPUTmice** [comment]
can you give an example of the kind of presence notifications Conversations
presumably creates?

**Comment by Jutosa** [comment]
The problem isn't that it creates them but that they don't stop.

First the app requests the whole roster, than all the pubsubs and then there are these presence things for every user in the roster.

If that is done it starts again. Over and over again.

The log grows by about 10MB every couple of seconds and it stops when I disconnect the app from the server. I'm the only user that uses the conversations app so it's easy for me to verify that the problem is some sort of interaction between my ejabberd version and one of the recent conversations versions.

I've been using the app for a year now and this is the first time this has happened.

The log is pretty huge so I tried to get the parts that appear to be repeated a lot.


```
=INFO REPORT==== 2015-08-24 14:28:29 ===
D(<0.2069.0>:ejabberd_router:313) : route
    from {jid,"p***","*****.de","mobile","p***","*****.de","mobile"}
    to {jid,"c******","*****.de",[],"c******","*****.de",[]}
    packet {xmlelement,"presence",[{"type","probe"}],[]}
```

```
=INFO REPORT==== 2015-08-24 14:28:29 ===
D(<0.906.0>:ejabberd_local:300) : local route
from {jid,"e**","***.de","home","e**","***.de","home"}
to {jid,"e**","*****.de",[],"e**","*****.de",[]}
packet {xmlelement,"iq",
                       [{"type","get"},{"id",[...]}],
                       [{xmlelement,[...],...}]}

=INFO REPORT==== 2015-08-24 14:28:29 ===
D(<0.906.0>:ejabberd_sm:411) : session manager
from {jid,"e**","*****.de","home","e**","*****.de","home"}
to {jid,"e**","*****.de",[],"e**","*****.de",[]}
packet {xmlelement,"iq",
                          [{"type","get"},{"id",[...]}],
                            [{xmlelement,[...],...}]}
```

**Comment by iNPUTmice** [comment]
duplicate to #1359
