### ISSUE TITLE
[UI] Account Details: It is unclear what "Show QR code" shows

### ISSUE THREAD

**Issue by RalfJung** [siacs/Conversations#1360]
I my account details, I now have two keys: One for OTR, and one for OMEMO. Both of these have a "copy" button right next to them, but there is still just one "Show QR code" in the menu behind the three dots. I used to think that this QR code shows my key, but now I realize it probably does not. So maybe it shows my JID? Some indication of what this QR code shows would be helpful, I think.

**Comment by rigid** [comment]
:+1: (for all QR code applications) it would be useful to provide UI access of the actually encoded data anyway. Something like "long press qrcode -> details"

**Comment by Aeyoun** [comment]
I assumed the QR code was an ad to get your friends to install the app. Now you got me wondering what it’s really about.
