### ISSUE TITLE
OMEMO option not available

### ISSUE THREAD

**Issue by otr2015** [siacs/Conversations#1361]
I tried to establish encryption with OMEMO but it didn't show me the option "OMEMO", only the options "None", "OTR" and "OpenPGP" were shown in the menu.
Both contacts are registered on a server running with prosody 0.9.4 and on the homepage of prosody it is written that XEP-0163 is supported since version 0.5 (https://prosody.im/doc/xeplist).

Thanks.

**Comment by iNPUTmice** [comment]
does pep show up in the server info (overflow menu in account details)?
