### ISSUE TITLE
Issue: How to publish avatar of the user in the app?

### ISSUE THREAD

**Issue by sushrita** [siacs/Conversations#1367]
when I go to Publish avatar activity  the avatar of the user is not publishing and the error is showing as:
your server does not support avatars.But the avatar of the contacts is visible.Can you please tell me what should I do to solve this?
![avatarpublish](https://cloud.githubusercontent.com/assets/10562247/9513008/a9d6941a-4ca7-11e5-8580-b966790baf23.png)

**Comment by andersruneson** [comment]
You should use a server that supports pep avatars.

The avatars you see from your contacts are either from your phones contacts
or from legacy vcard avatars.

**Comment by sushrita** [comment]
How to do settings for the server to support PEP Avatars?

**Comment by andersruneson** [comment]
I guess you will have to look at the server documentation for that.

Ask in the muc if you can't get it working (as this is a issue tracker and
not a support forum).
