### ISSUE TITLE
Multiple Instance of the Application

### ISSUE THREAD

**Issue by starryprabin** [siacs/Conversations#1368]
I think I found a bug. I don't know exactly if it is a bug or not; but the following steps will reproduce it at least in my mobile (Sony Xperia z3 Android 5.1.1).

1. Clear all chat conversations. (You should be in contacts list).
2. Open Conversation App.
3. Press Home button (Not back button) to go to the desktop.
4. Open Conversation App again.
5. Press Home button again.
6. Repeat steps 1, 2 few more times.
7. Open Conversation App again.
8. Now press back button to close the app (No Home button this time).

Everytime you press back button, a new instance of the app will pop up. The total number of instances will be the number of times you have opened through steps 1 and 2 plus the 7th one.

Edit: Added Step 1. 

Regards.

**Comment by iNPUTmice** [comment]
what is an instance in that case? how do you quantify that? or rather what
are the effects you are seeing?

**Comment by starryprabin** [comment]
An instance is the whole application resurfacing or I should say opening up. Every time I press back button, the application pops up. I don't know if it is intentional or a bug.

**Comment by iNPUTmice** [comment]
fixed in: ca262d352374622145056b3d3dea99484e035594
