### ISSUE TITLE
sending files with dots in filename are shown as link

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1373]
I've already added the file type to well-known file types and this is working well, but this doesn't work for files containing dots in the filename. They are shown as links instead of a button to download.

**Comment by lookshe** [comment]
You have to change the method extractRelevantExtension in the Message class.
Feel free to use this implementation:
```
         private static String extractRelevantExtension(URL url) {
                 String path = url.getPath();
                 return extractRelevantExtension(path);
         }
 
         private static String extractRelevantExtension(String path) {
                 if (path == null || path.isEmpty()) {
                         return null;
                 }
 
                 String filename = path.substring(path.lastIndexOf('/') + 1).toLowerCase();
 
                 int dotPosition = filename.lastIndexOf(".");
 
                 if (dotPosition != -1)
                 {
                         String extension = filename.substring(dotPosition + 1);
 
                         // we want the real file extension, not the crypto one
                         if (Arrays.asList(Transferable.VALID_CRYPTO_EXTENSIONS).contains(extension)) {
                                 return extractRelevantExtension(path.substring(0,dotPosition));
                         } else {
                                 return extension;
                         }
                 }
                 return null;
         }
```
[Link to patch file](http://www.thehappy.de/~lookshe/pub/0001-Fixes-FS-38-Issues-with-URLs-with-multiple-dots-in-f.patch)

**Comment by iNPUTmice** [comment]
@lookshe if you create a PR for this I will happily merge this.

**Comment by lookshe** [comment]
As mentioned in the chat there could be also a problem in this line, but at least I did not verify this:
https://github.com/siacs/Conversations/blob/0dfb9bd1a06436ffb6dd7a5cfbdefa11d3ae130e/src/main/java/eu/siacs/conversations/xmpp/jingle/JingleConnection.java#L324
== should be >=

**Comment by deoren** [comment]
Not sure if you need further confirmation, but I noticed this behavior today as well.
