### ISSUE TITLE
No application found to open received file: Let the user choose one.

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1374]
When a user receives a file for which no application is known to open it, let the user choose an application from a list of the installed apps and allow to save the chosen app as default (opt-in checkbox).

Currently, it only says that no suitable application was found and it's not known where received files are stored.

**Comment by iNPUTmice** [comment]
What files are we talking about here? If android is unable to detect what application to choose to open the file even though there is a proper app installed for that it might be worthwhile fixing the detection instead of implementing the work around of showing all applications.

**Comment by alexara** [comment]
In this case we are talking about a unix like text file which has no filename extension.

**Comment by philipflohr** [comment]
This seems to be a bug of the text editor you use. 
This app should include  <data android:mimeType="text/plain" > in its manifest file
see http://stackoverflow.com/questions/23137890/how-to-register-my-android-app-to-open-my-custom-file-extension-and-not-for-all

An app which does not offer to open a specific file should not be used to open it (may eat your cat...), letting the user decide which app to use therefore seems like a bad idea to me
