### ISSUE TITLE
"receiving file" should be "sending file"

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1377]
After accepting a file transfer the text changes to "receiving file". But the chat bubble points to the user who actually sends the file. So it from a logical point of view it should be "sending file".

**Comment by kriztan** [comment]
I think that means, that you receive a file from this user and not this user sends a file to you.

**Comment by alexara** [comment]
I know how it's meant but I find it a confusing when the user who sends a file says "receiving file".

**Comment by strb** [comment]
Well by the same logic you could say it's confusing when my app is telling me it's sending something. Neither one is more "correct" than the other. If anything, this issue should be about maybe using more neutral language that works in both perspectives. (like "transferring file" or something)

@SamWhited I guess this strengthens your case against the chat bubble "tails" ;)
