### ISSUE TITLE
Notification behavior has changed to notify for every message in a MUC 

### ISSUE THREAD

**Issue by schmickers** [siacs/Conversations#1380]
Since the most recent updates to Conversations, notification behavior has changed. The previous behavior was to notify the user for the following situations:

A message sent directly to the user from another user;
A message broadcast to multiple users;
A message posted to a MUC room that included the users nickname.

This behavior is the default behavior for most XMPP clients.

Since the most recent updates to Conversations this behaviour has changed. Now every message in a MUC triggers a notification.

This behavior is undesirable. It renders notifications of little value as if you are idling in a busy MUC your phone will be notified constantly, even if the messages are not intended for you. The only option to prevent the device constantly receiving notifications are to either turn off notifications for the MUC in question, or to disable notifications in the app. Turning off notifications for the room is also undesirable, as it triggers a warning whenever you enter the MUC, by way of a persistent line at the bottom of the chat, and also because it will also prevent notifications when messages are sent including your username.

The previous behavior reflects the standard notification behavior demonstrated in other XMPP apps (for instance, Pidjin, Trillion, Psi) and I believe it should either be restored or a toggle added to enable users to choose between the two notification behaviors.

I am using Conversations 1.6.7 on a Sony Xperia Z1 running the latest nighties of Cyanogenmod 12.1 and I am connecting to a private XMPP server for a large online MMO guild.

**Comment by iNPUTmice** [comment]
This change has only happened for private and non-anonymous MUCs. Can you confirm that the room in question matches both of the criteria (private and non-anonymous)?

**Comment by schmickers** [comment]
This is a private server and it is non-anonymous. The server is running Prosody.

**Comment by laszlovl** [comment]
Same here, I'm suddenly getting a flood of notifications for messages in MUCs that are not directed to me.

Indeed only some rooms are affected, it looks like the problem does **not** occur when a room is set to "publicly searchable". However, I don't understand what the private/public setting has to do with the notification behavior?

**Comment by iNPUTmice** [comment]
fixed in HEAD
