### ISSUE TITLE
Filetransfer error with big files

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1381]
I've noticed that Conversations will only show an unspecified error `delivery failed` if the file to transfer via HttpUploadComponent is too big. It would more user friendly to tell the user, that the file is too big.

**Comment by philipflohr** [comment]
This should be quite easy to implement as 
https://github.com/siacs/HttpUploadComponent/blob/master/httpupload/server.py (http://xmpp.org/extensions/xep-0363.html)
reports"file too large" and even the maximum allowed file size

**Comment by iNPUTmice** [comment]
HTTP upload now reports the file size so we can avoid sending the file via HTTP in the first place.

**Comment by kriztan** [comment]
But the python script doesn't yet.
https://github.com/siacs/HttpUploadComponent/issues/67

**Comment by iNPUTmice** [comment]
@kriztan that's right. Patch the python script or use the module in your server.
