### ISSUE TITLE
Share Pictures

### ISSUE THREAD

**Issue by thfree** [siacs/Conversations#1382]
Gallery > Share > Conversation > + >  Contact

The file is transferred twice

**Comment by jkufner** [comment]
Same here, version 1.6.7 from F-Droid.

**Comment by strb** [comment]
I can't reproduce this. What type of file transfer? (Jingle or HTTP upload?) Encryption enabled, and if so, which one?

**Comment by strb** [comment]
Actually, forget what I said, I can reproduce it now. Didn't notice that you were talking about the "new conversation" + button in the action bar.
