### ISSUE TITLE
OMEMO option is shown grayed out

### ISSUE THREAD

**Issue by otr2015** [siacs/Conversations#1385]
Hi,
when I open the encryption menu I cannot choose the option "OMEMO" because it is shown grayed out.
This appears with a custom ROM based on Cyanogenmod 12.1 and with a original Samsung Android 4.4.4 ROM. The funny thing is that I tried it with another phone of Samsung also based on Android 4.4.4 and the option is not shown grayed out.
I already tried to change XMPP servers but it doesn't seem to be the source of the problem because both of the accounts used on the custom ROM based on Cyanogenmod 12.1 and the account on the phone where it works are based on the latest prosody release and are hosted on the same server.

Thank you.

**Comment by strb** [comment]
Did you try on your different devices for the same contact? OMEMO will discover whether your contact supports it. If they don't it will not be selectable.

**Comment by otr2015** [comment]
I tried it now with two different accounts on the latest prosody and ejabberd versions and the OMEMO option still can't be selected. The other contact I tried to communicate with has the option visible.

**Comment by otr2015** [comment]
The accounts where it didn't work are on system.im and jix.im .
Thanks.

**Comment by otr2015** [comment]
And yes, I tried it on several custom ROMs with one account and on another device with the original Samsung Android ROM with another account.

**Comment by iNPUTmice** [comment]
This probably has nothing to do with your Operating System or the hardware it's running on.
It's more likely that your contacts server either doesn't offer PEP (you can have your contact check in their account details (enable server info in the overflow menu)) or has a broken PEP ie on an old ejabberd.

**Comment by otr2015** [comment]
After @strb wrote it could be a problem of the accounts and the server, I changed now my account and the account on another phone I tried to communicate with. And it fu*king works.
I have no idea what was the problem before because also the other servers are based on the latest prosody release.
Thank you so much for your help. @strb @iNPUTmice 

I also have another question: Can you send offline messages with OMEMO?

**Comment by strb** [comment]
The server needs to offer PEP. Simply being the newest version of a server implementation doesn't guarantee this is the case. It needs to be configured to advertise this.

And yes, OMEMO can send offline messages.
