### ISSUE TITLE
Group fs and emotions

### ISSUE THREAD

**Issue by nikolanik** [siacs/Conversations#1388]
It would be great to add emotions (stickers) sending and group file sending (maybe only picture/video/audio).

**Comment by iNPUTmice** [comment]
> emotions (stickers)

What are those? Well I guess I know what emotions are. But I'm unsure on how Conversations can assist you in expressing those?

> sending and group file sending (maybe only picture/video/audio).

Please use a server that supports Http File Upload

**Comment by nikolanik** [comment]
Great for groups :-)  thanks!

For stickers... like Viber/WhatsApp...
