### ISSUE TITLE
Avatar semms not to be broadcasted, but can receive from e.g. Pidgin

### ISSUE THREAD

**Issue by cantonduck** [siacs/Conversations#1389]
I am not sure about following issue. Did not found an according thread for that.
Everything works fine, but when trying to publish an avatar picture from conversations, other conversations users cannot see the published avatar. 

But when for example when using Pidgin from a PC, the avatar of that pidgin contact is shown on the android device in conversations. Seems like it works only one way with conversations (receiving avatars, but no broadcast?)

When set up the avatar in conversations, toast says: broadcasted...

Any ideas? 

- - - -
Conversations 1.67 on Android 4.3 // Samsung i9505 // Openfire Server 3.9.3 on Synology Diskstation with MariaDB 5.5.43-0033 (utf8_general_ci) and Java SE embedded 1.8.0-1

**Comment by andersruneson** [comment]
Openfire was buggy in 3.9.3. I hade the same issue before i switched to
prosody.

**Comment by cantonduck** [comment]
ah thx... as far as I could see, since Missilehugger discontinued his work, there are no more SPK packages to update Openfire for synology users. I was looking for alternatives and found ejabbered so far, but did not tried this server yet. So I will try to find out more about Prosody and ejabbered, since I have no idea how to implement ignite realtimes latest Openfire installations on a Synology Server.

**Comment by cantonduck** [comment]
"just managed to install 3.10.2 in my synology NAS, came from 3.9.3.
Same issue like before (https://github.com/siacs/Conversations/issues/1428): conversations client pusblishes avatar, pidgin client, does not get/see avatar.
whereas pidgin client publishes avatar, but conversations client sees the pidgin avatar...

also tried this one: https://el-tramo.be/blog/vcardextpres/ but no success

any ideas?"
