### ISSUE TITLE
"Timeout in DNS" error when connecting from WIFI

### ISSUE THREAD

**Issue by mafio19** [siacs/Conversations#1392]
Yesterday night I was at my girlfriend's place and while connected to WIFI both of our smartphones failed to connect to my XMPP server (Ejabberd 15.07).
The weird thing is that on the very same smartphones another XMPP client (yaxim) works fine with the same server and same users.
Here is the error in adb logcat:
...
09-04 22:35:28.159 D/conversations( 2665): user@domain: connecting
09-04 22:35:28.172 D/conversations( 2665): using dns server: 192.168.1.1 to look up domain
09-04 22:35:33.174 D/conversations( 2665): user@domain: timeout in dns
09-04 22:35:45.199 D/conversations( 2665): user@domain: connecting
09-04 22:35:45.210 D/conversations( 2665): using dns server: 192.168.1.1 to look up domain
09-04 22:35:50.214 D/conversations( 2665): user@domain: timeout in dns
...
This goes on forever and Conversation (version 1.6.7) is never able to connect.
From adb shell I can ping my domain (the DNS resolve it correctly) so it shouldn't be a problem of DNS resolution but rather something Conversation does wrong.

Edit: I forgot to mention than till a couple of weeks ago we never had any problem connecting from the same WIFI.

**Comment by iNPUTmice** [comment]
a32a577e3691e20366c89e2c5eec5156d8ae2af9 might have a work around for that.
I'd be interested in seeing a logcat output for that in the same wifi (assuming the workaround works)

**Comment by mafio19** [comment]
Will this patch be included in the next release?
I'll post the new log as soon as I can.
Thanks.

**Comment by nikolanik** [comment]
I have the same problem.

**Comment by marix11** [comment]
Confirm this issue

**Comment by iNPUTmice** [comment]
Please update to 1.6.9 and report back if the problem remains

**Comment by Black-Fry** [comment]
Unfortunately the problem remains

**Comment by iNPUTmice** [comment]
Please post an adb logcat output of the connection attempt (and please
don't redact the domain name - if you have privacy concerns please send me
an email to inputmice@siacs.eu)
furthermore it would be interesting to know what DNS server / router you
are using)

**Comment by peterjw** [comment]
I might have tracked this down to a broken DNS server. Here are the details:

I'm  having the same problem, using version provided by F-Droid. Just got a status "offline" with 1.6.7, getting a "Timeout in DNS" with 1.6.9. on two different phones.

* HTC Vision (aka DesireZ) is running CyanogenMod Ford "AlterAndromadus" (10.1-20140302-UNOFFICIAL-vision) which corresponds to Android 4.2.2 (obviously rooted)
* Sony Tipo Duo running manufacturers Android 4.0.4 (not rooted) (didn't try 1.6.7 with this one)

As far as I can see, these 3 lines are the only relevant ones from the logcat output:
 D/conversations(10269): XXXXX@jabber.org: connecting
 D/conversations(10269): using dns server: 192.168.42.1 to look up jabber.org
 D/conversations(10269): XXXXX@jabber.org: error connecting account. try again in 111s for the 5 time

XXXXX is of course a replacement for my jabber.org ID, which I like to keep private. A check from linux command line to the DNS server in question (which is an outdated DSL Router D-LINK DSL-G644T) gives:

~ $ host -d jabber.org 192.168.42.1 
Trying "jabber.org"
Using domain server:
Name: 192.168.42.1
Address: 192.168.42.1#53
Aliases: 

;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63142
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;jabber.org.                    IN      A

;; ANSWER SECTION:
jabber.org.             317     IN      A       208.68.163.218

Received 44 bytes from 192.168.42.1#53 in 267 ms
Trying "jabber.org"
;; Warning: Message parser reports malformed message packet.
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25959
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;jabber.org.                    IN      AAAA

Received 28 bytes from 192.168.42.1#53 in 3 ms
Trying "jabber.org"
;; connection timed out; no servers could be reached
~ $

Same test with the upstream DNS server gives:
~ $ host -d jabber.org 62.109.121.1 
Trying "jabber.org"
Using domain server:
Name: 62.109.121.1
Address: 62.109.121.1#53
Aliases: 

;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62986
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;jabber.org.                    IN      A

;; ANSWER SECTION:
jabber.org.             19      IN      A       208.68.163.218

Received 44 bytes from 62.109.121.1#53 in 183 ms
Trying "jabber.org"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49954
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;jabber.org.                    IN      AAAA

;; AUTHORITY SECTION:
jabber.org.             494     IN      SOA     xmpp.org. hostmaster.xmpp.org. 2015090401 1800 900 604800 900

Received 80 bytes from 62.109.121.1#53 in 18 ms
Trying "jabber.org"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56951
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;jabber.org.                    IN      MX

;; ANSWER SECTION:
jabber.org.             494     IN      MX      5 mail.jabber.org.

Received 49 bytes from 62.109.121.1#53 in 64 ms
~ $

So, obvisously the DNS server in my Router is somewhat broken. However, this has been the first time It is really causing troubles. Limiting the DNS request (to the router) to the A records avoids the malformed message packet warning, limiting it to the MX record results in an timeout.

**Comment by mafio19** [comment]
@peterjw also in my case the router is a very old D-Link (DI-624)
At this point the issue might very well be the router itself, I got myself another DI-624 and I'll try to replicate the issue with it.
It's also interesting to note that when connected to this particular wifi with android 5.1.1 (cyanogenmod) the wifi icon has an exclamation mark.
Everything else seems to work fine (from both the smartphone and a laptop with fedora) even if I completely disable mobile data so DNS resolution does work at least at some point.

**Comment by iNPUTmice** [comment]
@mafio19 @peterjw you might wan to report this directly to [rtreffer/minidns](https://github.com/rtreffer/minidns)

**Comment by lookshe** [comment]
@peterjw the DNS timeout only appears when asking for the AAAA-records, the A-record was retreived correctly. So you might want to check whether this timeout only appears while querying the AAAA-record, which seems not to be supported by your router.

As I saw in the code (https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/utils/DNSHelper.java#L144) there are always A- and AAAA-Records queried which might be the problem in your case, because your network is only IPv4.

**Comment by iNPUTmice** [comment]
@lookshe the DNSHelper probably doesn't even get to the point where it requests the AAAA record. The timeout happens on the SRV query. (Timeouts on A and AAAA queries are being ignored)

**Comment by lookshe** [comment]
So then "_xmpp-client._tcp.jabber.org" should be queried for testing the DNS in the first step.
And the next question comes up: Why are timeouts on A and AAAA are ignored and the first on SRV not?

**Comment by peterjw** [comment]
@lookshe: As far as I can see, there are no timeouts for A and AAAA records in my case. Are your referring to the code? I haven't looked into it yet. While not providing a AAAA record, requests for it via my router do not run into an timeout either. 
But requests for _xmpp-client._tcp.jabber.org get a timeout, while direct queries to upstream provide a result in time. 

However, I changed the configuration of the DHCP server of my router not to provide itself as first DNS server, but its upstream. (Which I have to change manually, if my provider moves it to another IP) and dis- and reconnected my phone to the wifi.

Conversations runs like a charm again ...

**Comment by iNPUTmice** [comment]
> And the next question comes up: Why are timeouts on A and AAAA are ignored

to avoid potential problems in miss-configured/malfunctioning DNS servers on IPv4-only or IPv6-only networks

> the first on SRV not?

because a) the SRV record is more essential. If anything goes wrong with the A record can leave this to the system resolver but the SRV lookup can not be handled by the system resolver. b) it didn't came to my attention until recently that SRV lookups might cause problems on otherwise working DNS servers.

current HEAD tries to work around that a little bit bit trying the domain on port 5222 if the SRV record lookup times out. but honestly if your DNS servers behaves strange there is only so much we can do.

**Comment by lookshe** [comment]
@peterjw I referred to the output of "host -d jabber.org 192.168.42.1" which first queries for A- and the AAAA-record. And the second one results in a connection timeout, as your output says.

@iNPUTmice the reason for handling timeouts is obviously, which leads to my question, why not all queries were handled the same way. And of course I know the problem with querying the system resolver with anything other than A- and AAAA-records. But this should be a reason to not handle a timeout while querying SRV. The fallback of course afterwards will not be able to query SRV, but ignoring a known problem in 1 of 3 cases seems weird.

**Comment by iNPUTmice** [comment]
@lookshe so the desired workflow in your case should be what exactly?

**Comment by peterjw** [comment]
@lookshe: I believe the request to AAAA finishes in line "Received 28 bytes from 192.168.42.1#53 in 3 ms". At least, there is no timeout when limiting the request to AAAA (host -t AAAA ...) although the empty result is wrong.

**Comment by marix11** [comment]
1.6.9 fixed this error in cm12 5.1.1. But on cm11 4.4.4

**Comment by marix11** [comment]
On android 4.4.4 'timeout in dns' very often when changing networks

**Comment by mafio19** [comment]
I can confirm that with version 1.6.11 the issue is gone, now I can connect to my server without problems using the same AP that was giving problems before.
Sorry for taking me so long and thank you for your support @iNPUTmice
