### ISSUE TITLE
Own Identity Key shows up as untrusted (red lock)

### ISSUE THREAD

**Issue by iNPUTmice** [siacs/Conversations#1394]
After pressing *clear devices* a couple of times and changing trust status on my other devices keys a couple of times in order to debug #1393 I managed to get to a state where OMEMO messages sent from a device show up with a red lock on the very same device. The column omemoFingerprint in the database has the correct fingerprint which matches the fingerprint shown in Account Details.

**Comment by strb** [comment]
Fixed in e2d506c96a0a72b7a903d28d9b3a858430700266
