### ISSUE TITLE
support XEP-0138: Stream Compression 

### ISSUE THREAD

**Issue by mingqlin** [siacs/Conversations#1395]

**Comment by singpolyma** [comment]
If you use TLS, this should be unnecessary.

**Comment by iNPUTmice** [comment]
support for stream compression has been removed a long time ago because of security reasons.

**Comment by strb** [comment]
If you use TLS (which you should) I hope to god you haven't enabled TLS compression. It has some pretty significant security implications (compare BREACH and CRIME). While XEP-0138 might be slightly better security-wise, you'd still have to flush on stanza boundaries which significantly decreases the compression ratio. At that point it's kinda not worth it any more.

**Comment by SamWhited** [comment]
> which significantly decreases the compression ratio

It does, but XML is also highly compressible. At HipChat when we enabled stream compression we saw a decrease in network traffic by a factor of 0.58... that's a huge gain (especially when you're fetching a MUC list with 10,000 rooms in it).

I'd actually love to see this come back as well (with proper security considerations); as long as you flush on stanza boundaries, and don't compress when e2e encryption is on, I suspect it's safe.

**Comment by phragment** [comment]
Did I get this correctly, XEP-0138 only advises using TLS compression? Is there really no XEP which standardizes compression on the "stream level"? As SamWhited wrote, XML is highly compressible.

**Comment by SamWhited** [comment]
No, XEP-0138 specifies stream level compression, it has nothing to do with TLS compression (which you shouldn't use).

**Comment by phragment** [comment]
Thank you for making things clear.
