### ISSUE TITLE
Failed to connect to Facebook

### ISSUE THREAD

**Issue by pingu8007** [siacs/Conversations#1397]
I used to connecting Facebook by Conversations, recently I found it not work anymore.
It still can connect, and auth successful since I can distinguish by just input wrong passwords. But it always stop at connecting, there is no chat, no contact list, no online status.
I've tried some other client like Xabber and Conversejs.org, and I'm sure chat.facebook.com still working.

Device: Nexus 4
Android Ver: Stock ROM, 5.1.1 LMY48I
Conversations Ver: 1.6.7 (but I'm not sure it started since when, I don't have much friend on Facebook)

If there is anything I can help pls let me know.

**Comment by jkufner** [comment]
Facebook turned off their XMPP gateway to Facebook chat. You should install a Facebook transport to your Jabber server.

**Comment by pingu8007** [comment]
Did you mean there are some workarounds inside Xabber or other client that still working with Facebook?

Just like Microsoft shutting down WLM but the server still living there for a long period. I feel that Facebook hasn't shutting it down totally.

**Comment by andersruneson** [comment]
You may happen to connect to different  servers, some with support still
active some inactive.

But anyway nobody is willing to work on fixing or investigation when
Facebook have announced shut down of xmpp.

**Comment by pingu8007** [comment]
Thanks, I got it.
