### ISSUE TITLE
block a contact is not working

### ISSUE THREAD

**Issue by jagdishkk1989** [siacs/Conversations#1400]
I am able to run the conversations successfully. It works very smooth and fine. but when I am trying to block a particular user then it returning an error.

D/xmppConnectionService(24373): block result type ERROR result string:<iq xmlns="jabber:client" to="+91-1111999922@enovate-it.com/mobile" id="426uo2ph00" type="error"><block xmlns="urn:xmpp:blocking"><item xmlns="urn:xmpp:blocking" jid="+91-1111999911@enovate-it.com"/></block><error xmlns="jabber:client" type="cancel" code="503"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>

Second, I also tried with the below protocol to block the user.
http://xmpp.org/extensions/xep-0016.html#protocol-active
Example 48. User blocks globally
and getting the result xml as well. but blocked user still able to send the messages.

Configuration:-
Openfire 3.10.2
Conversations xmpp client 1.5

If anyone have idea. Please reply.
Thanks in advance!!

**Comment by strb** [comment]
Looks like your server doesn't support XEP-0191: Blocking command. Google also confirms that OpenFire doesn't have support for it. Conversations doesn't do XEP-0016, so I'm not sure how you tested this, but if it doesn't work then that's something you need to report with you server.

**Comment by jagdishkk1989** [comment]
Thanks for quick response. We just call the block user function instead of context menu item, because it invisible by-default based on get feature list. Do you have any idea how to support XEP-0191 in openfire 3.10.2 server? Have you worked on blocked feature?
Thanks again..:)

**Comment by jagdishkk1989** [comment]
I fixed this by XEP-0016.

First user need to add the users to block in the privacy list and then active the list. The flow of the functions as below:-

public void sendBlockRequest1(final Blockable blockable) {
		if (blockable != null && blockable.getBlockedJid() != null) {
			final Jid jid = blockable.getBlockedJid();
			final Jid myJid = getAccounts().get(0).getJid();
			this.sendIqPacket(blockable.getAccount(), getIqGenerator().generateSetBlockUserRequest(myJid, jid), new OnIqPacketReceived() {
				@Override
				public void onIqPacketReceived(final Account account, final IqPacket packet) {
					Log.d("XmppConnectionService","Send block user request result:"+packet.toString());
					setActiveList(blockable);
				}
			});
		}
	}

public void setActiveList(final Blockable blockable) {
		if (blockable != null && blockable.getBlockedJid() != null) {
			final Jid jid = blockable.getBlockedJid();
			final Jid myJid = getAccounts().get(0).getJid();
			this.sendIqPacket(blockable.getAccount(), getIqGenerator().getActiveListRequest(myJid), new OnIqPacketReceived() {
				@Override
				public void onIqPacketReceived(final Account account, final IqPacket packet) {
					Log.d("XmppConnectionService","Send block user request result:"+packet.toString());
					if (packet.getType() == IqPacket.TYPE.RESULT) {
						account.getBlocklist().add(jid);
						updateBlocklistUi(OnUpdateBlocklist.Status.BLOCKED);
					}
				}
			});
		}
}

// generate the request format 
public IqPacket generateSetBlockUserRequest(final Jid myJid,final Jid jid) {
		final IqPacket iq = new IqPacket(IqPacket.TYPE.SET);

		iq.setAttribute("from",myJid.toBareJid().toString());
		iq.setAttribute("id","iq1");
		final Element query = iq.addChild("query", Xmlns.BLOCKING_CHAT);
		final Element list = query.addChild("list").setAttribute("name", "blockedlist");
		Hashtable attributes = new Hashtable<String, String>();
		attributes.put("type","jid");
		attributes.put("value", jid.toBareJid().toString());
		attributes.put("action", "deny");
		attributes.put("order", "1");

		Element item = list.addChild("item").setAttributes(attributes);
		item.addChild("message");
		Log.d("IqGenerator", "Block User request: " + iq.toString());
		return iq;
	}

for unblock just need to change the action to "allow" and call the activelist function for get unblocked user.

I hope this will help others.
Thanks!!

**Comment by jagdishkk1989** [comment]
Finally. I did based on XEP-0016 privacy list.

public void sendBlockRequest1(final Blockable blockable) {
		if (blockable != null && blockable.getBlockedJid() != null) {
			final Jid jid = blockable.getBlockedJid();
			final Jid myJid = getAccounts().get(0).getJid();
			this.sendIqPacket(blockable.getAccount(), getIqGenerator().generateSetBlockUserRequest(myJid, jid), new OnIqPacketReceived() {
				@Override
				public void onIqPacketReceived(final Account account, final IqPacket packet) {
					Log.d("XmppConnectionService","Send block user request result:"+packet.toString());
					setActiveList(blockable);
				}
			});
		}
	}

public void setActiveList(final Blockable blockable) {
		if (blockable != null && blockable.getBlockedJid() != null) {
			final Jid jid = blockable.getBlockedJid();
			final Jid myJid = getAccounts().get(0).getJid();
			this.sendIqPacket(blockable.getAccount(), getIqGenerator().getActiveListRequest(myJid), new OnIqPacketReceived() {
				@Override
				public void onIqPacketReceived(final Account account, final IqPacket packet) {
					Log.d("XmppConnectionService","Send block user request result:"+packet.toString());
					if (packet.getType() == IqPacket.TYPE.RESULT) {
						account.getBlocklist().add(jid);
						updateBlocklistUi(OnUpdateBlocklist.Status.BLOCKED);
					}
				}
			});
		}
	}
// generate request format
public IqPacket generateSetBlockUserRequest(final Jid myJid,final Jid jid) {
		final IqPacket iq = new IqPacket(IqPacket.TYPE.SET);

		iq.setAttribute("from",myJid.toBareJid().toString());
		iq.setAttribute("id","iq1");
		final Element query = iq.addChild("query", Xmlns.BLOCKING_CHAT);
		final Element list = query.addChild("list").setAttribute("name", "blockedlist");
		Hashtable attributes = new Hashtable<String, String>();
		attributes.put("type","jid");
		attributes.put("value", jid.toBareJid().toString());
		attributes.put("action", "deny");
		attributes.put("order", "1");

		Element item = list.addChild("item").setAttributes(attributes);
		item.addChild("message");
		Log.d("IqGenerator", "Block User request: " + iq.toString());
		return iq;
	}

I hope this will help to others.
Thanks!!

**Comment by iNPUTmice** [comment]
where did you click on block contact? in what view/activity? because conversations should usually hide the menu item if blocking is not available

**Comment by jagdishkk1989** [comment]
You are right!! But I put the another value on Xlmns.BLOCKING = "jabber:iq:privacy" instead of "urn:xmpp:blocking". Because in code visible the button based on feature available of blocking. 

Thanks!!

**Comment by vishaldeshai** [comment]
@jagdishkk1989 After you blocked user, are you getting messages from blocked user??
thanks
