### ISSUE TITLE
Possibility to add a participant of a conference to own contacts

### ISSUE THREAD

**Issue by seanlilmateus** [siacs/Conversations#1401]
There is no possibility to add an unknown conference participant to own contacts,

###Reproduction:
1. User A is invited to a conference with User B and C
2. User A doesn't have user C in his/her contacts
3. User A can't add user C to his contact

**Comment by strb** [comment]
If the conference is non-anonymous, you can go to the conference details, long-press the user in that list, and select start conversation.

If the conference is anonymous, you don't know the JID of the participant, so it's impossible to start a conversation with them or add them to your roster.
