### ISSUE TITLE
Publishing on Jolla Store

### ISSUE THREAD

**Issue by tigre-bleu** [siacs/Conversations#1402]
I use a [Jolla](http://jolla.com/) phone and installed Conversations using the android virtual machine. Everything works great and it may be interesting to publish the app on the Jolla Store.

I understand that you may focus on Google Play in order to distribute your app, but putting in in the jolla store would bring the best jabber experience to Jolla phone owners since Google Play is not installed on Jolla Devices.

If you agree and don't want to bother with this process, I could submit and manage the Q/A to [Jolla Harbour](https://harbour.jolla.com) on your behalf.

What do you think?

**Comment by iNPUTmice** [comment]
I submitted the app and it is currently pending review,

**Comment by iNPUTmice** [comment]
done

**Comment by tigre-bleu** [comment]
Great. For information if one wants to have the notifications in Jolla notification panel, the following file shall be modified:

`devel-su`
`vi /usr/share/lipstick/androidnotificationproperties`

Add the following lines:
`Conversations;chat,chat_exists`
`package:eu.siacs.conversations;chat,chat_exists`
