### ISSUE TITLE
DNS requests done directly instead of via the system resolver

### ISSUE THREAD

**Issue by jinnko** [siacs/Conversations#1404]
When I have my AFWall+ firewall turned on (iptables) and all traffic routed via my VPN, Conversations is unable to connect.

After much debugging I've found that Conversations is making direct DNS requests.  From what I've gathered from the AFWall+ [wiki](https://github.com/ukanth/afwall/wiki/DNS#commands-to-check-if-dns-is-working) and [issues](https://github.com/ukanth/afwall/issues/18) this is intentionally disabled, and in fact it is undesirable to allow these requests when the VPN is connected, therefore it is [disabled when the firewall is enabled](https://github.com/ukanth/afwall/wiki/FAQ#14-udp-port-53-dns-is-blocked-if-whitelisting-mode-is-enabled-why).

I've found that when the VPN is connected all other apps are resolving via the system DNS service and are able to successfully resolve names via the DNS provided inside the VPN.

Conversations on the other hand is making DNS requests directly to the pre-VPN configured resolver outside the VPN.  These are being blocked and thus Conversations is unable to connect to the XMPP server.

The expected behaviour would be for Conversations to resolve names via the system resolver, thereby not leaking information and functioning correctly regardless of how routing and tunnelling are set up.

**Comment by iNPUTmice** [comment]
Does your VPN server push DNS servers to you that are inside the VPN? Starting with 1.6.9 Conversations should be able to use those.

**Comment by jinnko** [comment]
Yes, it does push DNS servers.  I don't have GApps and am using Conversations via F-Droid where the latest version is 1.6.7.  As soon as the version there is bumped I'll test and confirm with 1.6.9.

**Comment by jinnko** [comment]
The upgrade to 1.6.9 has resolved the problem.  Thanks.
