### ISSUE TITLE
openpgp unable to read my own messages

### ISSUE THREAD

**Issue by tristan-k** [siacs/Conversations#1405]
I'm unable to read my own openpgp encrpyted messages when I send something from a desktop client (for example Gajim & Psiplus) to Conversation. If I send messages the other way around I will get no message at all.

Myself:
desktop client -> conversations = "Decryption failed. Maybe you don't have the proper privat key."
conversations -> desktop client = No Message at all

Somebody:
desktop client -> conversations = Decrypted
conversations -> desktop client = Decrypted

Yes, I double checked that I have the proper privat key on both sides!

Maybe this is related to https://github.com/siacs/Conversations/pull/1317 ?

**Comment by iNPUTmice** [comment]
I know for a fact that when using both mcabber and Conversations at the same time everything works as expected. Messages send and received on either client will show up on both clients.
Thus I can only assume that your desktop client is not encrypting the message to yourself. (Decryption failed. Maybe you don't have the proper privat key.) and maybe not picking up encrypted messages from carbons (No Message at all)
so please report this to the vendor of your desktop client.
