### ISSUE TITLE
Images uploaded via http_upload are presented as URLs in groups instead of auto-downloaded

### ISSUE THREAD

**Issue by martinsauter** [siacs/Conversations#1406]
When sending a picture to a multi user chat group via the http_upload feature, only the sender and the owner of the group sees the picture automatically. All other participants of the group that also use Conversations only see a link. They can short or long click on the link to download it in Conversations or the browser, which works just fine, but they should be auto-loaded just like for the owner of the group.

I've tried it in different variants for a couple of days now on a number of different phones, all with Conversation 1.6.9 installed, two personal xmpp servers running Prosody with the http_upload module activated, and also with an account on the public jabber.at server that that has http_upload feature activated. Same result in all combinations.

![http-upload-issue-sm](https://cloud.githubusercontent.com/assets/3988874/9837732/333f8d02-5a49-11e5-9a8e-12bf4881388b.jpg)

**Comment by SamWhited** [comment]
This is desired behavior. Your conference is anonymous, meaning that we can't check if the contact is in your roster (the condition for which auto-download is triggered). If the conference is non-anonymous and you have the sender in your roster, the image will be downloaded automatically.

**Comment by martinsauter** [comment]
Wow, that must have been the fastest answer ever! Thanks! Wow, good to know!
