### ISSUE TITLE
OMEMO file encryption uses SHA1

### ISSUE THREAD

**Issue by knoy** [siacs/Conversations#1408]
According to the XEP, under "Communicating the Checksum or Hashing Algorithm" , although no specific algorithm is mentioned, the example given for file transfers uses the SHA-1 hashing algorithm:
```
<hash xmlns='urn:xmpp:hashes:1' algo='sha-1'>552da749930852c69ae5d2141d3766b1</hash>
```

I'm not sure if this is used as an integrity or security checksum, but there are collision attacks against SHA-1 which reduce bruteforcing it to 2^60 time. This is significantly weaker than the 128-bits of security provided by AES-128-GMC, and judging by past history hashing functions will probably degrade faster than symmetric ciphers. I understand the attack vectors are limited but I think at least SHA-256 should be used.

**Comment by iNPUTmice** [comment]
The checksum is over the encrypted file. So this is basically only used to
check for transfer failures and is only in there to a) be compatible with
the jingle file transfer stack b) clarify that the checksum is for the
encrypted file and not for plaintext file to avoid implementors leaking
plain text information by hashing the plaintext.
So imho it is completely irrelevant security wise and thus there is no
reason to diverge from the default hashing algorithm in regular file
transfer.

**Comment by knoy** [comment]
Thank you for this info, I wholeheartedly agree
