### ISSUE TITLE
How to enforce SSL connections?

### ISSUE THREAD

**Issue by M-Reimer** [siacs/Conversations#1410]
I'm using Conversations to connect to my mailbox.org XMPP account. I use the same password, I also use for my mail at mailbox.org.

How can I get sure, that this password is encrypted before sending? I cannot find any setting about connection security.

**Comment by iNPUTmice** [comment]
Conversations won't allow plain text connections at all. #sanedefaults

**Comment by M-Reimer** [comment]
Thank you for this information. This is great news. Maybe this should be communicated somehow?

**Comment by knoy** [comment]
I don't really see a need for this, the XMPP community has been pretty rigorous in it's support for mandatory TLS encryption (on c2s and s2s connections)
