### ISSUE TITLE
Desktop / Command-Line version

### ISSUE THREAD

**Issue by rogerbraun** [siacs/Conversations#1413]
As Conversations is quickly becoming not only the best mobile client, but also the best jabber client overall, it would be great to have non-mobile frontends that can use the existing infrastructure. How hard would it be to make, for example, a command line interface? Are the backend-type functions clearly separated from the frontend?

**Comment by knoy** [comment]
Very hard. You are free to port the Java code to another platform if you wish but I think you will find it increasingly difficult to do anything beyond a very simple port (i.e: to Chrome OS)
