### ISSUE TITLE
Unusual handling of DNS queries

### ISSUE THREAD

**Issue by rsenger2** [siacs/Conversations#1414]
I am currently experimenting with a local DNSSEC aware validating resolver, and managed to compile Unbound for Android KitKat (with help from a project here on github). 

To make use of DNSSEC validation, DNS queries from all services and apps must be sent to the local resolver at 127.0.0.1 and/or ::1, respectively, rather than the ones configured via DHCP. On Android 4.4, this can be achieved with a small script that must be run right after connecting to Wifi/Mobile Network, or with a working DNS changer app (could not find any).

Once ::1 is set as resolver, almost all apps query the local validating resolver, except "Ping & DNS" (a network diagnostic tool), and Conversations. Conversations seems to bypass the system settings, and still queries the nameservers configured via DHCP.

I would suggest that Conversations better use the standard Android API for DNS queries, to be compatible not only with setups like mine but also with various DNS changer apps.

**Comment by iNPUTmice** [comment]
> I would suggest that Conversations better use the standard Android API for DNS queries, to be compatible not only with setups like mine but also with various DNS changer apps.

What is the standard API for DNS (SRV) queries?

**Comment by rsenger2** [comment]
Dunno. I am not very familiar with Android app development. All I see is that if DNS settings are changed on the android device, almost all apps and android services like Facebook, Twitter, all browsers, all the Google Play stuff, all tested email clients honor these settings, but Conversations does not*. That's why I assumed that there is something like a "standard way" to query DNS.

This is not a critical issue, as it does not break Conversations functionality at all.

But, to be a little bit pathetic: The majority of people in the world has to use unfree, insecure, censored and surveillanced internet connections. One possibility to bypass censorship is to change DNS from the local provider's censored servers to uncensored servers like Google's 8.8.8.8 for example. Censorship may or may not affect major Jabber services, dunno, but I think it would be good if Conversations would honor the user's choice which nameservers to be used. 

Cheers,
Robert

* if you want details of my setup and diagnosis, let me know!

**Comment by iNPUTmice** [comment]
most apps do not need to resolve SRV records and thus can use the system
resolver. we however have to query the dns server directly. which usually
is not a problem. the question in your case is why your local dns server is
not being discovered by Conversations. (if it were this all wouldn't be a
problem) however as I do not know what exactly your script is doing and how
it is setting the dns servers I don't know what Conversations could be
doing differently to be able to discover your local dns server.

for the record. If you change the dns server in the network settings to for
example 8.8.8.8 it works perfectly fine.
