### ISSUE TITLE
feature request: implement XEP-0174

### ISSUE THREAD

**Issue by BrainDamage** [siacs/Conversations#1415]
It would be nice if conversations would have support for [XEP-0174: Serverless Messaging](https://xmpp.org/extensions/xep-0174.html) which is handy to talk to friends/coworkers in the same network segment without having to setup a dedicated server

**Comment by Natureshadow** [comment]
+1

I think this is what Gajim calls the "Local" account?

**Comment by iNPUTmice** [comment]
This very rare usecase is not on our todo list right now.

**Comment by Damianuscz** [comment]
Up? After chatsecure drop support for android it would be great to have mobile client with this feature. Local comunication is hudge useful tool!

**Comment by garywill** [comment]
UP.
I want this feature too.
For other people who want this, I found [this android project](https://github.com/KayO-GH/NSD-offline-chat-android) which may be using this XEP ( haven't read the code)

**Comment by ao2** [comment]
JFTR, there is a draft implementation in the Smack XMPP library: https://github.com/igniterealtime/Smack/pull/25

**Comment by Damianuscz** [comment]
Implementation is in gajim too. Local account

**Comment by pmeckoni** [comment]
XEP-0174: Serverless Messaging is available in Pidgin (via the Bonjour prpl). [Source](https://developer.pidgin.im/wiki/SupportedXEPs).

Addition to conversations.im will be wonderful.

**Comment by alexanderadam** [comment]
Is there any alternative for a mobile application supporting Bonjour?

Or is there any chance that you'd consider putting in on the TODO list, @iNPUTmice?

**Comment by hhartzer** [comment]
It looks like things have moved over to Codeberg. I created a new issue for this here: https://codeberg.org/iNPUTmice/Conversations/issues/211
