### ISSUE TITLE
Slash commands in conference/MUC

### ISSUE THREAD

**Issue by sokai** [siacs/Conversations#1417]
Hey, since some days I use Conversations with chat rooms/conferences/MUCs and Prosody.
At first: Thanks for that possibility – it works …

But: From the desktop (normally Pidgin) I'm used to use slash commands (/config, /mood, /nick). This seems not possible ATM with Conversations …
→ Is that true or I'm missing something?
→ If it's true, will there be some changes/improvements for the future?

Thanks and best regards

**Comment by sokai** [comment]
well, I figured `/msg $nick $msg` in Conversation out → `$nick: $msg` \*nice\*

**Comment by iNPUTmice** [comment]
slash commands are usually something for keyboard centric devices to avoid having to go through settings.
Conversations should offer most things via (more or less) comfortable touch gestures. Highlighting people in MUCs for example works be touching the avatar of the other person. Private messages can be send by long pressing the avatar. Conference settings are available via the Conference Details.

**Comment by doak** [comment]
@sokai, `/me` works by the way ;)
