### ISSUE TITLE
Windows Phone version with Bridge for Android

### ISSUE THREAD

**Issue by tigre-bleu** [siacs/Conversations#1423]
Microsoft announced and launched as a preview a gate to package android apps to Windows 10 (Desktop and Phone)

http://bridgeforandroid.windows.com/

I wonder if somebody with a WP device could give a shot to this solution and see if it is possible to painlessly provide Conversations to this platform.

There is currently no WP app dedicated to XMPP that comes close to what Conversations can offer (especially, nothing using Message Archive and HTTP-Upload XEPs)

**Comment by iNPUTmice** [comment]
WP doesn't allow for background services. so running Conversations in the
compatibility mode of WP will be difficult and would at the very least
require to implement WP specific push notifications.

**Comment by tigre-bleu** [comment]
Would this help when mature?
https://blog.process-one.net/my-gsoc-2015-project-push-for-xmpp/

**Comment by iNPUTmice** [comment]
For this to work Microsoft will have to expose the operating system side of
push notifications (receiving events, creating credentials) into the
Android stack. I'm not sure if they are doing this.
