### ISSUE TITLE
Automatically resend failed messages ${X} times

### ISSUE THREAD

**Issue by tYGjQCsvVI** [siacs/Conversations#1425]
One common case I've noticed with conversations-to-conversations communication between me and a friend (Who lives in a poor 3G-covered area) is if I send them a message after they drop offline and they don't get online again within the five-or-so minutes allocated to them by XEP-0198, then when they finally do drop offline the message delivery fails, however if I then resend the message, they'll receive it as normal when they login again (Using OMEMO).

Is there anyway to implement a feature that automatically tries to resend failed messages three times or something of that nature?

**Comment by iNPUTmice** [comment]
this has been discussed numerous times before.
