### ISSUE TITLE
jingle voice calling support

### ISSUE THREAD

**Issue by willstdueswissen** [siacs/Conversations#1427]
My question is what the title say.
I would an voice support in conversation.
How do you think?
conversation ist the best xmpp client for android, but if you need calling,you need a other client.

**Comment by andersruneson** [comment]
Duplicate?

**Comment by willstdueswissen** [comment]
sorry, but where?
I did not find this request!
And sorry for my Bad english.

**Comment by iNPUTmice** [comment]
duplicate of #1234

**Comment by whitetornado** [comment]
is this still actual? i also wants a voip option for conversations

**Comment by licaon-kter** [comment]
@whitetornado As the post above says, see #1234
