### ISSUE TITLE
ERROR UNKNOWN -Conference

### ISSUE THREAD

**Issue by androidtintin** [siacs/Conversations#1429]
Hi , 

I am getting ERROR UNKNOWN and conference not found incase reciever wants to join invited group . 
Always getting snackbar of conference not found . There is no issue creating group and inviting but joining or saying any hi message pops out the message .

**Comment by DoM1niC** [comment]
Yea the same like here....

Prosody 0.10 trunk 

If I create a MUC Group over Pidgin it works to join etc. 

I tried with stable without success -.-

**Comment by iNPUTmice** [comment]
Please provide steps to reproduce and I will open this issue again
