### ISSUE TITLE
cryptic Message logs

### ISSUE THREAD

**Issue by cantonduck** [siacs/Conversations#1431]
Hi,

in the shown massage history of a particular chat, there are some messages that does not show the written messages, but some cryptic characters beginning with "?OTR:"

not all past OTR Messages are now shown in these cryptic strings, but some are. Does this occur when using different xmpp clients AND OTR? Noticed that some cleints like Pidgin or Gajim asked, to which client OTRs should be sent.

If so, how can I fix this? tried to delete the more than one Fingerprints on the chat partners client. And if so, can ich delete OTR Fingerprints centraly from phpmyadmin?

Or how are those cryptical messages explainable?

**Comment by iNPUTmice** [comment]
That's probably your other clients not setting the processing hints described in [XEP-0364](http://xmpp.org/extensions/xep-0364.html#sect-idp627760).
