### ISSUE TITLE
Feature request: Manual filetransfer proxy specification

### ISSUE THREAD

**Issue by Picard0147** [siacs/Conversations#1433]
It will be very usefull to add option to specify external filetransfer proxy in case that server doesn't support it, lot of desktop clients has such option and I'd like to see it also in Conversations. 

I know about work on http upload but even it should be faster and more suitable for group chats, it isn't solution for conversation between two persons because whether the file will be accesible after upload only for those who have proper link depends on server security settings (it's a thing that common users cannot affect) and also when server doesn't support proxy or http upload then users have only two optins - slow in-band transfers or migrate to other server including all complications with "teaching" friends to use other JID to contact them and also not having JID apearance what they like.

**Comment by iNPUTmice** [comment]
Sorry not gonna happen as this is against our design principles. Using a modern server will give you a lot more benefits than just being able to send files.

**Comment by Picard0147** [comment]
OK, when it's against your design principles then I cannot do anything even for myself (because of my lack of programming skils)... 
I uderstand that modern and well configured server realy has lot of advantages including this one but, and please don't get me wrong, I'm just curious, are your design principles definitely good for normal users which aren't able to configure server what they are using (no matter if because of no admin access to server or insuficient knowlege) and don't want to change JID because of it - realy no other person than me wants this option?
Or you just only belive that it's better not to give such option?
