### ISSUE TITLE
Hang 'waiting' using OTR

### ISSUE THREAD

**Issue by viric** [siacs/Conversations#1434]
From time to time, in OTR chats messages do not work; what I write remains to "waiting..."

I use to unlock this by sending an unencrypted message, and then sending OTR messages again. Sometimes it works, sometimes not, but uses to.

I think that this started in 1.6.7. I'm at 1.6.10 and this still happens.

**Comment by iNPUTmice** [comment]
are you and your contact using stream management?

**Comment by viric** [comment]
we both use Conv >= 1.6.7, both at jabber.at. Does that answer? I don't know what is the stream management.

**Comment by marix11** [comment]
Yes noticed that too. And every other message still 'waiting'. You need to 'End conversation' to send next message

**Comment by alexara** [comment]
@iNPUTmice Jabber.at uses ejabberd 14.12 together with Stream Management.

**Comment by viric** [comment]
As for the frequency of the problem... I face it more than twice a day. I use to send "zzz" unciphered to unblock it, and then I switch back OTR and resend the failed messages (which were hanging before the "zzz" send).

**Comment by iNPUTmice** [comment]
if possible try to use OMEMO.

**Comment by viric** [comment]
I know about OMEMO. Is OTR going to be removed? Won't it be fixed?

**Comment by iNPUTmice** [comment]
it will be very difficult to fix. don't expect a fix any time soon.

**Comment by viric** [comment]
Omemo fails sending most pictures I tried. Error sending, it says. Retries did not help. (1.6.10)

**Comment by marix11** [comment]
Yes confirm. Omemo fails sending pictures, need to change to otr to send them

**Comment by iNPUTmice** [comment]
If you both are using jabber.at their HTTP Upload Component is down right
now afaik.

**Comment by viric** [comment]
how can we know if we are using that component? I did the tests yesterday evening, and I managed to send 1 of 4 pictures.

**Comment by viric** [comment]
@iNPUTmice isn't that 'http upload component' used regardless of otr or omemo? Otr worked, omemo not.

**Comment by iNPUTmice** [comment]
@viric no OTR doesn't use HTTP upload. Because otr is end-to-end anyway.

In your account settings select server info from the overflow menu to see if your server supports HTTP upload. But as I said. I think the one on jabber.at is broken right now.

**Comment by marix11** [comment]
My server is dukgo

**Comment by iNPUTmice** [comment]
@marix11 please provide an adb logcat output for the failed attempt to send files

**Comment by marix11** [comment]
Ok. Will do later today. Also quotestion on maybe similar to otr 'waiting'. On omemo message sent but never delivered many times. From logcat:

09-30 11:17:24.706 D/conversations(7660): AxolotlService (..@jabber.calyxinstitute.org): Finding devices without session for ..@..
09-30 11:07:58.333 W/conversations(7660): AxolotlService (@..): Have no target devices in PEP!
09-30 11:17:24.716 D/conversations(7660): AxolotlService (..@..): Cache miss: 6310f0d3-07b0-408b-bcfb-6dca8b0c0dfd
09-30 11:17:24.716 D/conversations(7660): AxolotlService (@): Building axolotl foreign keyElements...
09-30 11:17:24.716 V/conversations(7660): AxolotlService (@): ..@..:343030656
09-30 11:17:24.746 D/conversations(7660): AxolotlService (@): Building axolotl own keyElements...
09-30 11:17:24.756 D/conversations(7660): AxolotlService (@): Generated message, caching: 6310f0d3-07b0-408b-bcfb-6dca8b0c0dfd
09-30 11:17:24.756 D/conversations(7660): AxolotlService (@): Cache hit: 6310f0d3-07b0-408b-bcfb-6dca8b0c0dfd
09-30 11:17:24.776 D/conversations(7660): ..@..: requesting ack for message stanza #240
09-30 11:17:25.286 D/conversations(7660): ..@..: server acknowledged stanza #240

**Comment by marix11** [comment]
Thats logcat of sending omemo picture:

09-30 12:25:47.824 D/conversations(17962): AxolotlService (..@..): Building axolotl own keyElements...
09-30 12:25:47.834 D/conversations(17962): no primary candidate of our own was found
09-30 12:25:49.796 D/conversations(17962): marjan33@dukgo.com: other party received offer
09-30 12:25:49.956 D/conversations(17962): received candidate error
09-30 12:25:49.956 D/conversations(17962): could not find suitable candidate
09-30 12:25:49.956 D/conversations(17962): sending fallback to ibb

**Comment by POTION4** [comment]
Waiting forever too, but OMEMO works well.

**Comment by iNPUTmice** [comment]
I added some logging in 0ca4a33bfb76d63a3c2d4447643a5bd90ac5315f. Please install that version and post the output of adb logcat

**Comment by iNPUTmice** [comment]
OMEMO now works on the desktop as well. So there is no reason to use OTR anymore.
