### ISSUE TITLE
question: are filenames ciphered with otr?

### ISSUE THREAD

**Issue by viric** [siacs/Conversations#1436]
If we send a file with otr, I guess the file transfer is ciphered, and so is the file name. Is it?

Thank you!

**Comment by iNPUTmice** [comment]
This is a bug tracker and not a forum for general questions. Please join our conference if you have questions.

**Comment by aeuii** [comment]
I'm also curious. @viric how was the answer?

**Comment by aeuii** [comment]
@iNPUTmice is there any archive, preferably searchable, of the conference? thanks
