### ISSUE TITLE
Before OTR keys are exchanged all unencrypted messages are "green"

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1440]
Hi!

I added a new contact on Conversations 1.6.10. All plain text messages were marked as "green" or in other words as encrypted until we initialized an OTR encrypted conversation. (exchange and verifying of the OTR keys for the very first time.)
First then plain text messages had a red background.

Kind Regards

**Comment by strb** [comment]
> marked as "green" or in other words as encrypted until we initialized an
OTR encrypted conversation.

Green doesn't mean encrypted. That's just the design of the app. Encrypted
messages are marked by a lock icon in the chat bubble.

Messages are colored red if their encryption status mismatches that of the
session that is enabled (or was enabled at the time the message was
received). This not only applies to unencrypted messages, but also for
example to received PGP messages while you're in an OTR session.

**Comment by alexara** [comment]
@strb Please have a look at https://github.com/siacs/Conversations/commit/77920c7aa608bd92391ade653eb8971b977eb7d5
It says "Plaintext messages that were received while in an encrypted session are
now colored red"

Or has this feature been changed since then?

**Comment by iNPUTmice** [comment]
Yes in 74ab36fda2d977e1b97b755a8298c488e6d74ba2

**Comment by alexara** [comment]
Good to know. I think since Conversations wants to be an app for everyone and since this feature is enabled by default, it should be clearly communicated what it does without the necessarity for trial and error or to google.

That's why I suggest to 1) either change the explanation of the option in the settings 
2) or to add description text of an feature eg by long pressing on the option or by adding an symbol "?".
I am thinking of an hovering text field like it's common on the desktop OS.

Kind Regards

**Comment by iNPUTmice** [comment]
> either change the explanation of the option in the settings 

there is no setting for this

**Comment by alexara** [comment]
@iNPUTmice What about "Use a white background for incoming messages" ?
Isn't that the option to disable this unexplained feature?

**Comment by iNPUTmice** [comment]
nope. this just disables the green background for people who hate green

**Comment by alexara** [comment]
I see. However,  I stay at my point, I think for an average user it'd be better to explain this feature. For example when an encryption mismatch happens for the first time. 
In this context there could also an indicator implemented which shows the encryption type the other participant uses (eg next to the encryption type). If it mismatch the lock symbol could be altered. 

My 2 cents.

**Comment by aeuii** [comment]
Hi, I also initially got confused about the colors. I thought that green means encrypted and red unencrypted. I actually like the strong colors, but the possible confusion they cause should be re-thought.

Is there any good reason, why Conversations does not synchronize the encryption, e.g. if I have set OTR and my partner sends me an OMEMO message, my Conversation client could automatically switch to OMEMO?
