### ISSUE TITLE
Encryption color indicator changes when changing the encryption type

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1441]
Conversations offers several kind of encryptions. When within an conversation one participant changes his/her encryption (eg from OTR to OMEMO) the last received OTR encrypted messages becomes red. When the user reverts the encryption change, the message becomes green again.

**Comment by therob84** [comment]
I can exatly confirm this behaviour and don't understand why this behaviour exits, thus I tend to regard it as a bug.

In my opinion it would make more sense if the colors around a message just reflect their encryption type for faster visibility (although OTR/OMEMO/...is written below as plain text).
Thus already received messages should not change color if I change current encryption type.

Also colors could reflect encryption strength in a more consquent manner, e.g.:
OMEMO =  green
PGP & OTR = yellow
not encrypted = red
[the current (v 1.7.2) color changing behaviour is quite non-intuitiv for me ...]
Any comments on this?

**Comment by iNPUTmice** [comment]
This is expected behaviour
