### ISSUE TITLE
send an empty message

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1443]
With Conversations it is possible to send empty messages. 
You can try it by typing only a space and touch on send button. The message which was sent is an empty message. This should not happen.
Conversations seems to cut of spaces as first chars.

**Comment by iNPUTmice** [comment]
Which part of this should not happen and why?

**Comment by kriztan** [comment]
What is the reason for sending empty messages? I've no idea, why this should be possible. So Conversations should recognize that after clearing whitespaces at the beginning, if there were more characters or not. If not, it should not send the message, because it is empty.
Or am I missing

**Comment by iNPUTmice** [comment]
I don't see a good reason to prevent that. It's not like that happens on accident all the time or anything. And by the way the massage is not empty. It contains whitespaces.
