### ISSUE TITLE
Feature request: LaTeX support

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1444]
Coming from a natural-scientific background it would be great to send mathematical expressions formatted with LaTeX. 
Pidgin offers such a pludgin for example. Typing $$a^{expression}$$ will be translated to an image which then will be send.

**Comment by iNPUTmice** [comment]
Out of scope.

I wouldn't even know how to enter ```$$a^{expression}$$``` on a regular softkeyboard.
