### ISSUE TITLE
Facebook OpenPGP

### ISSUE THREAD

**Issue by JoeTac** [siacs/Conversations#1448]
I am trying to configure facebook to use openpgp, but I'm getting the following error "No OpenPGP Key found". I setup gtalk perfectly fine, and even included the facebook email in the identity

background:
phone 1: contains primary email (gmail), and facebook email
phone 2: contains primary email, secondary email(gmail), and facebook email

Test Cases:
phone 1 sending gtalk openpgp to phone 2 (success)
phone 1 able to receive and decrypt from from gtalk from phone 2 (success)
phone 1 sending facebook openpgp to phone 2 (fail)
phone 1 able to receive and decrypt from from facebook from phone 2 (fail)

phone 2 sending gtalk openpgp to phone 1 (success)
phone 2 able to receive and decrypt from from gtalk from phone 1 (success)
phone 2 sending facebook openpgp to phone 1 (fail)
phone 2 able to receive and decrypt from from facebook from phone 1 (fail)

If you need more information let me know. Any help would be appreciated.

**Comment by iNPUTmice** [comment]
If you want to use the encryption capabilities you better use a proper XMPP server as this is a) way better for your battery consumption and overall reliability b) less error prone as *fake-xmpp* services like gtalk or facebook might be stripping/suppressing data that is required for openpgp to work c) as your contact needs to use a supporting client anyways there is no reason not to use a proper xmpp server to communicate with that contact.
