### ISSUE TITLE
omemo messages not delivered

### ISSUE THREAD

**Issue by marix11** [siacs/Conversations#1449]
I many times have omemo messages sent but not delivered. Maybe logcat could help

09-30 11:17:24.706 D/conversations(7660): AxolotlService (..@jabber.calyxinstitute.org): Finding devices without session for ..@..
09-30 11:07:58.333 W/conversations(7660): AxolotlService (@..): Have no target devices in PEP!
09-30 11:17:24.716 D/conversations(7660): AxolotlService (..@..): Cache miss: 6310f0d3-07b0-408b-bcfb-6dca8b0c0dfd
09-30 11:17:24.716 D/conversations(7660): AxolotlService (@): Building axolotl foreign keyElements...
09-30 11:17:24.716 V/conversations(7660): AxolotlService (@): ..@..:343030656
09-30 11:17:24.746 D/conversations(7660): AxolotlService (@): Building axolotl own keyElements...
09-30 11:17:24.756 D/conversations(7660): AxolotlService (@): Generated message, caching: 6310f0d3-07b0-408b-bcfb-6dca8b0c0dfd
09-30 11:17:24.756 D/conversations(7660): AxolotlService (@): Cache hit: 6310f0d3-07b0-408b-bcfb-6dca8b0c0dfd
09-30 11:17:24.776 D/conversations(7660): ..@..: requesting ack for message stanza #240
09-30 11:17:25.286 D/conversations(7660): ..@..: server acknowledged stanza #240

**Comment by iNPUTmice** [comment]
according to the logcat the message is being send correctly. So the problem must be on the receiving side. Is your contact online when you send this message?

**Comment by marix11** [comment]
Its say online, but on mobile, not stable connection

**Comment by iNPUTmice** [comment]
it seems like your xmpp server is forcing you to use otr https://www.calyxinstitute.org/projects/public_jabber_xmpp_server

**Comment by iNPUTmice** [comment]
ok never mind my previous statement. that should not influence omemo messages. anyway. probably check with your receiving server.
