### ISSUE TITLE
Implement XEP-0136

### ISSUE THREAD

**Issue by SphinxC0re** [siacs/Conversations#1450]

**Comment by strb** [comment]
Why? What are common use-cases that are not already covered by XEP-0313?

**Comment by SphinxC0re** [comment]
I think this won't work with the current client: https://www.ejabberd.im/mod_archive

**Comment by strb** [comment]
This doesn't really answer the question. Of course you can't use the XEP-0136 module for ejabberd, but that's not a use-case in and of itself. What specific end-user-visible functionality is missing when using MAM, that would be covered by this?

**Comment by SphinxC0re** [comment]
You can't see messages written on and to other clients that you own?!

**Comment by iNPUTmice** [comment]
@SphinxC0re Conversations supports XEP 0313 and so does ejabberd.

**Comment by strb** [comment]
@SphinxC0re That's covered by XEP-0280.

**Comment by SphinxC0re** [comment]
Thanks for your support :smile:
