### ISSUE TITLE
HttpUpload not used for files which could not be send, before component was installed

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1451]
I recently installed and activated the HttpUpload component on the server. I thought I now could resend some old images (which could not be delivered before the installtion of HttpUpload) with enhanced speed of HttpUpload.
Unfortunately resending these images use the old inband transfer.

Suggestion: Always try to use HttpUpload when it's available.

**Comment by iNPUTmice** [comment]
I can not reproduce this.

**Comment by alexara** [comment]
Then I will close here until I have time to try to reproduce it again.
