### ISSUE TITLE
Message saying could not be delivered, is actually delivered

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1453]
Hi!

I wrote a friend whose internet connection was not stable a message. Conversation said that the message could not be delivered. But a minute later he answered my question, which means that the message actually was delivered. The status of the "not delivered" message won't be updated then.

We both use Conversations 1.6.10, OMEMO with ejabberd 15.07 where all XEPs are activated.

**Comment by iNPUTmice** [comment]
You can tell your stream management not to fail the messages if you want to rely on MAM
