### ISSUE TITLE
Encryption color indicator - wrong behaviour with PGP

### ISSUE THREAD

**Issue by tbeitter** [siacs/Conversations#1454]
If I chat over OMEMO encrypted messages the first non-encrypted message received get coloured red. In the same situation with PGP this message is not indicated as unencrypted at first, but gets red with the next encrypted answer from me. This should work the same, no matter which encryption is enabled.

**Comment by therob84** [comment]
Hey. I would point you to similar issues (where I still waiting for a real response/change), maybe you can drop in there: #1456 (and #1441)
Cheers, Robert

**Comment by iNPUTmice** [comment]
Can you make a screenshot next time this happens?

**Comment by iNPUTmice** [comment]
Can somebody confirm this and provide me with screenshots. Because I don't understand exactly what is happening here @tbeitter

**Comment by adithyaphilip** [comment]
<b>With "Hello" being sent as OMEMO and the reply "Hey" unencrypted</b>
<img src="https://cloud.githubusercontent.com/assets/5712241/12615247/88f3d2fc-c52a-11e5-8fb8-b2cbd0e64d06.png" width = 200>
The first unencrypted reply is marked red.
<b>With "Hello pgp" being sent as PGP and the reply "Hey" unencrypted</b>
<img src="https://cloud.githubusercontent.com/assets/5712241/12615374/4ffae598-c52b-11e5-8992-0e84177d74d4.png" width = 200>
In the case of PGP (or OTR, for that matter), the first unencrypted reply remains green until the user sends another PGP/OTR message, at which point it is marked red:
<img src="https://cloud.githubusercontent.com/assets/5712241/12615376/50f20cd8-c52b-11e5-9a15-343077b0ba41.png" width = 200>

I guess the desired behaviour from both OTR and PGP is that displayed by OMEMO?

**Comment by iNPUTmice** [comment]
I'm actually not able to reproduce this with OTR. However I can see how this might happen with PGP.

Can you check if the problem remains with: 28ebf927fb6cadc64a4f138cb84bac91c9903fdf

**Comment by adithyaphilip** [comment]
https://github.com/siacs/Conversations/commit/28ebf927fb6cadc64a4f138cb84bac91c9903fdf fixes it, thank you :) and OTR works too, I must have been mistaken.
