### ISSUE TITLE
Feature request: If message could not be sent, let the user change it again

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1455]
When a message could not be delivered, allow the user to change it afterwards before resending it.

**Comment by Christian-X** [comment]
You can long press he failed message, select "copy Text", and paste that into your input bar...

**Comment by alexara** [comment]
Just to clearify: When a message is resend will the other participant receive this message at the very end of his chat history or will the message be treated as it was send at the original time?

If the first point is true, my suggestion is not valid.

**Comment by iNPUTmice** [comment]
The time will be set to now. Also you can use copy text like @Christian-X if you decide to modify it.
