### ISSUE TITLE
pictures sent through conversations don't show up in other chat clients

### ISSUE THREAD

**Issue by agodlydeciple** [siacs/Conversations#1457]
When sending a picture from the Conversations app to a desktop app such as Pidgin doesn't ever show up.

Don't even receive a notification or option to accept attachment or anything.

**Comment by SafwatHalaby** [comment]
This is not an issue with Conversations.

The reason is that Pidgin uses an old file transfer method while Conversation uses newer XEPs such XEP-0065. If you find a Pidgin alternative, file transfer should work. [Gajim](https://gajim.org/) supports XEP-0065 so it *should* work with Conversations. But I haven't tried it.

**Comment by iNPUTmice** [comment]
Try using HTTP Upload. That is compatible with all clients. Or use gajim on the desktop side.

**Comment by Jens14L** [comment]
XEP-0065 is a draft protocol and not a final standard. I appreciate new protocols, more security and functions. But could you also support one of the current standards as fall-back alternative?
* https://xmpp.org/extensions/xep-0065.html

**Comment by SamWhited** [comment]
In XMPP land "Draft" effectively means "Standard". Yes, it's not final, but Draft means it's widely implemented and not likely to change unless a major flaw is found. This IS the current widely supported standard.

Note the description of draft in [XEP-0001 § 9.3](https://xmpp.org/extensions/xep-0001.html#states-Draft):

> A Standards Track XEP is in the Draft state after it has undergone extensive discussion and technical review on the Standards list and has been voted forward on the standards track by the XMPP Council.
> 
> Note: Once an XMPP Extension Protocol has been advanced to a status of Draft, it is expected that the specification will be basis for widespread implementation and for deployment in production environments. As a result of such implementation and deployment experience, the protocol may be subject to modification, including changes that are backwards-incompatible. Although such backwards-incompatible modifications shall be avoided if at all possible, deployment of a Draft protocol in mission-critical application may not be advisable.
