### ISSUE TITLE
Fix / Clean up Logo

### ISSUE THREAD

**Issue by iNPUTmice** [siacs/Conversations#1458]
If you zoom into the Conversations logo there a a few tiny flaws. Some of the doted outlines don't have round corners. The outline in the most bottom right corner has a tiny whole in it and so on. If someone with some inkscape skills could help clean those up that would be highly appreciated.

All svg files in are in the art folder of this repo.

The monochrome version (notification icon) probably needs the same clean ups. But this is not very urgent.

![flaws](https://cloud.githubusercontent.com/assets/192229/10262600/1e610790-69cf-11e5-8341-fe5b6d777262.png)

**Comment by Natureshadow** [comment]
I will take this if you want :).
