### ISSUE TITLE
UI bug when "Accept files" is set to "never"

### ISSUE THREAD

**Issue by SafwatHalaby** [siacs/Conversations#1459]
Below is an illustrating screenshot. The same image was sent twice using XEP-0363 (HTTP).

![3](https://cloud.githubusercontent.com/assets/5030488/10266874/452e50c6-6a83-11e5-98e2-83fa6c456a7c.jpg)

**First message:** Auto accept set to only accept files larger than 256 KiB, Conversations behaves as expected.
**Second message:** Auto accept set to "never", Conversations does not behave as expected, a "Download Image" button should appear instead of a link.

**Comment by iNPUTmice** [comment]
Not a bug. This is expected behaviour to still be able to open the URL in a browser. (Or download them manually by long pressing) (Doesn't happen by the for for encrypted messages because opening them in a browser wouldn't yield the expected result.

**Comment by timosl** [comment]
Why would this be the expected behaviour if the URL points to an image file? You normally wouldn't want to open the browser just to view a single image.

**Comment by SafwatHalaby** [comment]
Why would modifying the auto-download setting affect whether a URL or a "Download image" button is shown?
