### ISSUE TITLE
Notification on phone what chatting on laptop

### ISSUE THREAD

**Issue by RalfJung** [siacs/Conversations#1463]
I am having essentially the issue described at #1222. In that bug, it was said that Conversations will notice when it gets a carbon from a conversation going on elsewhere, and will not display notifications on that conversation for 60sec or so. That doesn't seem to work here, I often get notifications shown on my phone even though I sent a message from my laptop only a few seconds earlier. This bug is primarily about that "grace period" not working.

**Comment by RalfJung** [comment]
More generally speaking, the entire situation is pretty unsatisfying: I have to unlock my phone several times a day to remove notifications that conversations put there, because it doesn't notice that I am actually chatting elsewhere. Together with OTR messages ending up at the wrong client, this must be the most frustrating part of my "multi-client jabber experience".

Now, I do realize that conversation can't even know I am chatting elsewhere currently, so this probably asks for some extension of XMPP. For example, what is the technology that conversation uses to tell me which messages have already been read by my peer? Couldn't it use the same kind of notification to learn that I have read a particular message at another client? If clients tell the server anyway that I just read a particular message, then this may just as well get forwarded to not only my peer, but also all the other clients I am logged in with.
Of course, this assumes clients do this properly and actually test for window focus or things. I just imagine the notification on my phone to disappear the moment I switch the chat tab on my laptop... that'd be amazing :D
Is this a kind of bug/proposal you'd like to track in a separate bug?

**Comment by iNPUTmice** [comment]
2015-10-05 15:01 GMT+02:00 Ralf Jung <notifications@github.com>:

**Comment by iNPUTmice** [comment]
To clarify the grace period just disables the sound. It does not suppress the notification.

Whats the desktop client you are using?

**Comment by RalfJung** [comment]
> To clarify the grace period just disables the sound. It does not suppress the notification.

Oh, okay. Then things are probably working as intended - it may be that there is no sound, but the notification LED definitely starts flashing.

> Whats the desktop client you are using?

I used Pidgin, currently I'm trying Gajim. I can't say I'm really satisfied with either of them...

**Comment by iNPUTmice** [comment]
> Couldn't it use the same kind of notification to learn that I have read a particular message at another client? If clients tell the server anyway that I just read a particular message, then this may just as well get forwarded to not only my peer, but also all the other clients I am logged in with.

fwiw this is already the case if your client support Chat Markers. For example if your other client is another Conversations (on a tablet for example or in ARC) or jappix this is exactly what happens. Read messages on one device - send read marker to contact - other Conversations clears notification.

**Comment by RalfJung** [comment]
Oh, wow, that's great. So I just need to find a desktop client that supports them... and potentially a server.

**Comment by SafwatHalaby** [comment]
I think chat markers are server-agnostic.
I think you should try the ARC Welder. It allows you to run Conversations inside Chrome/Chromium.

**Comment by RalfJung** [comment]
Maybe I should, maybe I will. Can't say I'm a huge fan of either of these browsers, though. My phone is already google-infected, no need to let this creep over to my laptop ;-)

/me hopes *some* desktop client will implement OMEMO in the foreseeable future

Anyways, it seems that everything is working as intended and with a desktop client that supports chat markers, my issue will be solved. Closing this. Thanks!

**Comment by SafwatHalaby** [comment]
Consider Chromium; It s not Google-infected.

**Comment by RalfJung** [comment]
We seem to have different standards ;-)
