### ISSUE TITLE
groups for contacts for different accounts

### ISSUE THREAD

**Issue by muzirian** [siacs/Conversations#1464]
currently if multiple accounts are using from the client , contacts from both accounts are listed together and it doesnt show which contact is from which account.And this is more confusing if same account is on the contact list of those multiple accounts as the big contact list will now show duplicated contacts .Condition is same for open conversations, can't distinguish between which account is being used to chat unless looking on contact details from conversation screen.

**Comment by iNPUTmice** [comment]
It was decided very early on that the scenario where you have the same contact in different rosters is not one to optimize for because it rarely happens. (Despite of test cases and the such)
If you must differentiate between those contacts you can give one of them a different name.

**Comment by muzirian** [comment]
Is remembering which name is used for a roster particular account practical for normal users,? wouldn't t be better if we cud identify which roster was on which account,or  have an option to d tap and hold to select which account from which message is to be sent or at least tap and hold  on atleast tap and hold to a contact to view details.

**Comment by strb** [comment]
It doesn't have to be "practical for normal users", because "normal users" don't have this problem in the first place. <sup>[Citation needed]</sup>

I'm sure the UX for this edge case could be improved, but it's not really worth the effort of doing so. Patches are probably welcome though.
