### ISSUE TITLE
Conversations doesn't export the logs to the SDcard 

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#1465]
It exports the logs to /storage/emulated/0/Conversations/logs
Maybe it could be the default path but allowed to be modified by the user. 

BTW,  how often does it export the logs? On my phone it does a lot of times per day and I don't know if it supposed to works like that so I'm not sure if I should open a different issue for that in case of bug.

**Comment by iNPUTmice** [comment]
> BTW, how often does it export the logs? On my phone it does a lot of times per day and I don't know if it supposed to works like that

it should only export the log when you click export

**Comment by moshpirit** [comment]
Mm it doesn't :\ I *think* that every time I get reconnected my accounts it exports the logs but I have no idea if that's what really happens.

How can I send you more information?

**Comment by moshpirit** [comment]
Right now I have these accounts:

- 3 connected and normally used.
- 1 old disconnected account that I used to use
- 1 disconnected and never used

**Comment by iNPUTmice** [comment]
The multiple export thing is fixed in: 1d2a24c9c02dd34b9d3d8758dff9124d72a154a7

As for the SD card thing. That'll hopefully fix itself with Android 6.0 - The way android handles SD cards and what users expect from it has been pretty terrible. I simply can not support something like that.

**Comment by moshpirit** [comment]
Ok, thank you! 
Have you considered the option periodically export the logs? For non tech people it would be a nice feature in my view. Maybe once a day could be fine :)
