### ISSUE TITLE
Group received files in folders and save path

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1466]
Hi!

Right now Conversations saves all received files in ```/storage/emulated/0/Pictures/Conversations```.
But despite the folder's name is "Pictures" it saves all kind of data there and everything in one single folder.

I suggest to handle this issue as it is done do it for SD-Cards logs:
Create a folder for each user and within these folders create subfolders e.g. "images", "videos", "audio", "misc" to keep the data structured.
(Since files have cryptic names it's additionally hard to find a specific one)

In this context it would also be convenient to change the save path to any path.

Kind Regards

**Comment by iNPUTmice** [comment]
> But despite the folder's name is "Pictures" it saves all kind of data there and everything in one single folder.

I don't think this is true. Conversations - unless there are bugs I don't know of - saves pictures in ```/storage/emulated/0/Pictures/Conversations``` and all other files in ```/storage/emulated/0/Conversations```

If you are experiencing different behaviour and are seeing a file store where it doesn't belong please describe how the file got there. Was it a file you send. If so how did you select it? Was it a file you received? What was the name of the file.

**Comment by alexara** [comment]
Then it's a bug on my device. I use CM 12.1 and Conversations 1.6.11.
In  ```/storage/emulated/0/Conversations``` there's currently only the folder ```logs```.

All received and send files go to  ```/storage/emulated/0/Pictures/Conversations```:
* 09333d4f3-[...]-[....]-a9246890f3c.amr
* *.webp
* *.foo
* *.asc

It concers all files send / received, no matter how I select them in Conversations ("send image, capture image, send file, record audio ...)

**Comment by iNPUTmice** [comment]
fixed in 32abc766898a5524c7e945adf64bd97ffb404c2b

**Comment by alexara** [comment]
This was quick. Thanks!
