### ISSUE TITLE
Feature request: Import / restore log

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1467]
Since it's now possible to export a log, it would be great to restore it.
E.g. in the case the smartphone is changed or the device had to to be resetted.

**Comment by iNPUTmice** [comment]
The log export is meant to create a human readable archive that can be read with a simple text editor. It misses a lot of status information that would be required to re import it back into conversations. If you want to make a backup of Conversations (for example to use it on a new phone) please use regular backup tools.
