### ISSUE TITLE
OpenPGP encryption chooses revoked key over newly created

### ISSUE THREAD

**Issue by fr34kyn01535** [siacs/Conversations#1468]
I revoked a key a while ago and then created a new, however people trying to contact me still cant reach me because Conversation says it has been revoked.https://sks-keyservers.net/pks/lookup?op=vindex&search=fr34kyn01535%40bam.yt&fingerprint=on ​

**Comment by fr34kyn01535** [comment]
It looks like fetchKeyId in src/main/java/eu/siacs/conversations/crypto/PgpEngine.java is returning the very first key only, even if its revoked. When others try to write me encrypted messages a OpenKeychain intent opens, showing the key search and the id of my revoked key. Feel free to add me and try it out adding me on fr34kyn01535@bam.yt.

**Comment by falsechicken** [comment]
This has happened to me. I have manually imported the non-revoked key using the "cloud" but every time I try and send an encrypted message to the other user it still opens the "cloud" key menu and displays the revoked key.

**Comment by iNPUTmice** [comment]
Have you 're-announced' the key?

**Comment by fr34kyn01535** [comment]
How would i go about re-announcing the key?
As you can see on https://sks-keyservers.net/pks/lookup?op=vindex&search=fr34kyn01535%40bam.yt&fingerprint=on there are only 2 keys, one of them is revoked.

**Comment by fr34kyn01535** [comment]
Works now, ty!
