### ISSUE TITLE
Featurerequest: Separate "delivery" and "read" receipt option

### ISSUE THREAD

**Issue by sebastian1911** [siacs/Conversations#1469]
to make it short: my wife does not need to know if I read a message, only that I received it (green tick at message). The read receipt option should be separated from the delivery receipt option. Maybe you add a button "Mark read" at the last message so I can manually mark it as read.

**Comment by iNPUTmice** [comment]
This has been discussed before. With proper severs there should be no need for delivery receipts anyway. You can simply turn them off.
