### ISSUE TITLE
Enable "Move to SD card" - app + data takes up many megabytes of internal memory.

### ISSUE THREAD

**Issue by chr15m** [siacs/Conversations#1470]
```
<manifest ... android:installLocation="auto" ...>
...
</manifest>
```

**Comment by iNPUTmice** [comment]
It's fine if you do that for yourself but I'm unable to merge this and provide support for the masses for this.
There is a closed PR for this already were I go a bit into details why I won't be able to support this.

**Comment by chr15m** [comment]
Hi @iNPUTmice,

Thank you for considering the pull request and referring me to the conversation on #1060.

I humbly submit that this is still a good idea, and I will list your points raised against merging below with my reasoning as to why I think it is still a good idea.

> Maybe the App does not get killed when you access your device over MTP?

That's correct, the app is not killed in that instance. The majority of devices are currently running versions of Android that will be unaffected by this change:

https://developer.android.com/about/dashboards/index.html

> But 'small' still means a couple of hundred MiB I'm guessing. What I'm saying is that moving the 10-20MiB or what ever Conversations actually consumes won't make too much of a difference storage wise
> ...
> I don't think that the database file size will ever become too much of a problem.

Conversations does not consume 10-20M.

![screenshot_2015-11-12-18-55-29](https://cloud.githubusercontent.com/assets/67130/11203325/f261a42e-8d2d-11e5-9ebc-6be8190e8e4e.png)

As you can see the app currently uses 182M.

On my device, and presumably that of many other people with similar phones, this is a significant fraction of the available space.

> might come with huge side effects

Many apps have this feature enable and do not have huge side effects. It's very common to have this feature enabled.

The main side-effect you seem to be concerned about is speed of read/writes which are mitigated by modern fast SD cards.

> SD cards can be very slow and an app that does regular disks read and writes - like Conversations does - might be slowed down tremendously.

This is not a problem that newer SD cards suffer.

> Considering that Conversations already stores all its actual files (images) on the SD card I'm wondering whether or not this is even necessary.

In the screenshot above it appears that 0M of data are stored on the SD card in my case.

>  If some users have very little internal storage space they might be better of moving another App to the SD card that doesn't need to do frequent synchronous writes to the disk.

I have already moved all other possible apps to the SD card.

> That considered I don't think allowing this would lead to good results for the general (novice) user.

If the novice user knows how to "move to SD card" then I am sure they will understand the tradeoffs involved from having previously installed apps to the SD card.

> A user who knows what he is doing can always patch this himself.

I can't patch this myself as I do not have access to a working Android SDK currently.

I also want to recommend this app to my daughter and other family members who can't compile the app themselves.

I agree with @SamWhited when he says:

> I just generally think this should be for the user to determine.

Thanks for your consideration.
