### ISSUE TITLE
Quick-Reply is not encrypted without any warning

### ISSUE THREAD

**Issue by RalfJung** [siacs/Conversations#1472]
With Conversations having some kind of support for Enigmail for decryption and signature verification, I kind of assumed that it would also have support for encryption. That, however, does not seem to be the case: When I use quick-reply to send a mail to someone of whom I have a trusted key, the mail still goes out unencrypted. I learned this by accidentally sending a mail in unencrypted form that I wanted to be encrypted. (Lucky enough, there was no personal or private data in that mail.)

Conversations could at the least inform users (maybe as part of its setup process) that it will never encrypt quick-replies. Even better, of course, would be extending the enigmail support to also cover sending :D

**Comment by strb** [comment]
I'm not sure I understand your problem correctly. First of all, the terminology you're using is a little confusing. Enigmail is an extension for Mozilla Thunderbird, which is an email client, and has nothing to do with XMPP. You also keep referring to sending "mail". I assume that you are talking about PGP encryption (which is what Enigmail uses as well), correct?

I'm also not sure what these quick replies are that you're referring to. Is this some kind of Android feature that I've just never heard of? Googling digs up some (apparently still in closed-ish beta?) app that supposedly enables a text-input field under heads up notifications, is this what you're referring to?

**Comment by RalfJung** [comment]
I'm so sorry, I mean to report this against the Thunderbird extension "Conversations" and trusted my browser history too well to find the right project. Sorry for the hassle :(
