### ISSUE TITLE
Feature request: While scrolling ask to jump to last message

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1473]
While scrolling through a large message history, an incoming message let you jump automatically to the very last message and your scrolling session starts again.

I suggest to add an overlay button "Jump the last message?" when the user scrolled up.

**Comment by erdmark** [comment]
Tis is annoying.especially in group chats when looking what was said before

**Comment by licaon-kter** [comment]
/close this

Fixed in 2.1
