### ISSUE TITLE
audio records are displayed in Android's audio player

### ISSUE THREAD

**Issue by LogicParrot** [siacs/Conversations#1477]
Audio recordings are displayed in Android's audio player. This can cause some akward social situations if a private recording is played during a random playlist shuffle.

**Comment by d9h02f** [comment]
You can add a file called ".nomedia" in the directory where the recordings are saved to prevent the files in that directory from being indexed (so they won't show up in the media player).

**Comment by SafwatHalaby** [comment]
Thanks :)
Conversations should do this automatically though. This may be related to the [Voice Plugin](https://github.com/siacs/VoiceRecorder).

**Comment by iNPUTmice** [comment]
fixed in 281cb6504683ae2b8b957e18ff3f7f7f94941777

you also need to update your Voice Recorder Plugin
