### ISSUE TITLE
Ant Build doesn't work

### ISSUE THREAD

**Issue by tcuje** [siacs/Conversations#1479]
According to the README one should build the apk file using ant. I just checked out the latest release, but ant crashes with:
Buildfile: build.xml does not exist!
Build failed

I think Gradle should be the build system now.

**Comment by SafwatHalaby** [comment]
Gradle is the build system, that might be an outdated README.
`./gradlew build`

**Comment by SafwatHalaby** [comment]
The README was updated. For further building reference, see [this](https://github.com/siacs/Conversations#how-do-i-build-conversations).

**Comment by tcuje** [comment]
Thank you very much for the fast responses. Differing from the README I used the "local.properties" file to specify my Android home directory. Works fine as well.
