### ISSUE TITLE
end this conversation

### ISSUE THREAD

**Issue by tcuje** [siacs/Conversations#1483]
At least for the German translation I think it's a bit confusing that it says "end this conversation" instead of "archive this conversation", because thats what the app does technically, right?

Furthermore if you choose "end conversation" or "clear history" and "check end conversation" the timestamp for the conversation is not updated. This means if you restart a conversation with someone he/she doesn't show up on top of the list, but instead you have to dig threw the complete list to find it.

And last but not least I think a conversation should only be started when someone writes something. Just viewing a contact shouldn't result in an active conversation or at least hide them in the overview if they're empty.

**Comment by mcepl** [comment]
Also, there seems to be something wrong with "ending" (whatever it actually means). Although, I have ended a conversation repeatedly and even killed Conversation couple of times I am still getting messages from one particular MUC. When I open it, the old conference tab is opened with the error message "Conversation was not found. Leave?" (back-translation from Czech, so it is probably not 100% same string).

Also (which is even worse), it seems that Conversation somehow didn't leave the MUC properly, so I am there on the server now twice (once from other desktop client) and getting all messages twice (in the desktop client, Conversation gets the message only once).

**Comment by iNPUTmice** [comment]
Conversations has been calling this 'Close this conversation' for a while now.
