### ISSUE TITLE
Chrome: Hotspots for clicking on the menu items is off

### ISSUE THREAD

**Issue by rubin110** [siacs/Conversations#1485]
When running through Chrome by way of building with the ARC Welder or grabbing the prebuilt bundle off of the Chrome Store, the menu the drops down from pretty much any view seems to have its hotspots for clicking offset by one spot up. For instance if I want to click on Manage accounts, I need to click above it on Disable notifications.

**Comment by rubin110** [comment]
Also not sure if this is the right spit for Chrome issues. :)

**Comment by iNPUTmice** [comment]
I noticed that as well but I don't think there is anything I can do about it. I think it's an ARC bug.

Do you experience this bug on Chrome OS as well? (Just out of curiosity. Not that this changes anything)

**Comment by rubin110** [comment]
I've seen this on all Chrome based platforms I've gotten Conversations working on, which includes Linux and Windows 10.
