### ISSUE TITLE
OMEMO: What other clients support it?

### ISSUE THREAD

**Issue by rubin110** [siacs/Conversations#1488]
This might not be the right place to ask, but I'm wondering if there are any other clients that support OMEMO at this time? Thanks.

**Comment by d9h02f** [comment]
Not yet.

**Comment by iNPUTmice** [comment]
currently none. as soon as there is an implementation we will include that on conversations.im/omemo

**Comment by Mikaela** [comment]
Pidgin [has a ticket about it](https://developer.pidgin.im/ticket/16801) and Jolla Together [has a feature request](https://together.jolla.com/question/1866/feature-request-xmpp-omemo-support-in-messages/) about it.

**Comment by andersruneson** [comment]
Gajim has preliminary support.

**Comment by Loki-Afro** [comment]
No Adium support yet ... https://trac.adium.im/ticket/17090

**Comment by Natureshadow** [comment]
Should be easy for libpurple (Pidgin, Adium) as it has Signal support, though.

**Comment by Loki-Afro** [comment]
@Natureshadow its already implemented in Pidgin though .... https://developer.pidgin.im/ticket/16801

**Comment by Natureshadow** [comment]
>@Natureshadow its already implemented in Pidgin though ....
>https://developer.pidgin.im/ticket/16801


Ah!
