### ISSUE TITLE
Multiple links in messages, tapping broken

### ISSUE THREAD

**Issue by Natureshadow** [siacs/Conversations#1489]
If a message contains multiple links, e.g. seperated by newline, tapping any of them always opens the first link.

**Comment by iNPUTmice** [comment]
Thats an Android bug. We don't do the linking ourself. Afaik this got fixed in 5.0?

**Comment by Natureshadow** [comment]
I am running Android 5.1.1. This bug only appears in conversations, sending the same message by SMS or e-mail produces working seperate links.
