### ISSUE TITLE
History support

### ISSUE THREAD

**Issue by Myppomeu** [siacs/Conversations#1491]
Support of browsing full history of messages with any roster contact (unclude MAM-messages)

**Comment by iNPUTmice** [comment]
Conversations supports MAM.

**Comment by Myppomeu** [comment]
1. About MAM. Conversations only sends messages to database, but dont receive them
2. I talk about history integrally

**Comment by Myppomeu** [comment]
What can I do force Conversations show received MAM messages?

**Comment by SafwatHalaby** [comment]
I think that conversations also receives MAM messages.

**Comment by Myppomeu** [comment]
>I think that conversations also receives MAM messages.

Where can I look at them? MAM messages does not displayed in messages list.
