### ISSUE TITLE
Connection status indicator

### ISSUE THREAD

**Issue by Myppomeu** [siacs/Conversations#1492]
If connection to server is lost, Conversations does not notify about this. Suggest 2 things:
1. Icon in system tray that notifies about lost connection
2. Sound notification

**Comment by iNPUTmice** [comment]
Conversations displays a notification if there is a permanent connection error. If you don't get the notification your client must be stuck in a reconnection loop. In that case try to get an adb logcat caputre.

**Comment by Myppomeu** [comment]
>stuck in a reconnection loop
Yes, I told about this. Conversations is actually offline (trying to connect), but I dont know about that

**Comment by marix11** [comment]
Indicator is nice idea. I have daily reconnection loop and cant notice it. Still same timeout in dns error

**Comment by jkufner** [comment]
Fixing the bug is better idea. Such loops should not happen.

**Comment by Myppomeu** [comment]
>Fixing the bug is better idea

Not always. For example, I have server in local network (it is dont available from internet). Sometimes phone lost wifi, Conversations try to reconnect with mobile internet and I did not see that I am offline.

**Comment by jkufner** [comment]
Then you should get notification about the failure. That is already implemented.

**Comment by iNPUTmice** [comment]
> Not always. For example, I have server in local network (it is dont available from internet). Sometimes phone lost wifi, Conversations try to reconnect with mobile internet and I did not see that I am offline.

That should trigger a Server not found notification. As I said. Please post an adb logcat output of the failed connection attempt if that doesn't trigger a notification for you.

**Comment by Myppomeu** [comment]
>Unable to open log device '/dev/log/main': No such file or directory

It is result of every attempt to run logcat

**Comment by andersruneson** [comment]
Maybe this ?
http://stackoverflow.com/questions/6941710/unable-to-open-log-device-dev-log-main-no-such-file-or-directory
