### ISSUE TITLE
XEP-0199: XMPP Ping support

### ISSUE THREAD

**Issue by Myppomeu** [siacs/Conversations#1493]
Mobile internet is unstable. Server must know if Conversations actually goes offline.

**Comment by iNPUTmice** [comment]
Conversations already answers to ping requests.

**Comment by jkufner** [comment]
... and since Conversations supports Stream Management, there is no need for pings.

**Comment by Myppomeu** [comment]
>Conversations already answers to ping requests.

Then can you add it in the list of supported XEPs?
