### ISSUE TITLE
No HTTPUpload image preview

### ISSUE THREAD

**Issue by JonnyTischbein** [siacs/Conversations#1497]
When I receive a picture via HTTPUpload I just get a hyperlink and not an image preview. If I tap and hold on that link and select "Download image" I receive the Error Message: "Download failed. File not found". The link is correct anyway. I can see the picture if I'm following the link with a browser or wget.
At the server the following plugin is running (Method "On VirtualHosts") [1].
With Gajim the Image preview (a plugin is used) via HTTPUpload works fine.

Is that a bug or a missing feature ?

I attached a screenshot and the log (I guess it isn't really useful because it's just the chat history)
Is there a possibility to get an advanced log ?

Conversations version: 1.6.11 (F-Droid source)
Android version: 5.0
Kernel version: 3.10.54

[1] - https://modules.prosody.im/mod_http_upload.html

![screenshot](https://cloud.githubusercontent.com/assets/10757520/10450769/eef34666-718b-11e5-9dbd-34b701404f3d.png)

LOG:

    (2015-10-09T13:50:55) wg@conference.riotcat.ddns.net/Nick: xxxx
    (2015-10-09T13:54:58) wg@conference.riotcat.ddns.net/Nick: xxx
    (2015-10-09T13:55:08) wg@conference.riotcat.ddns.net/Nick: xxxx\ 
    Memers Only\ 
    passwort protectet
    (2015-10-11T12:36:50) nick@riotcat.ddns.net/Gajim_: http://riotcat.ddns.net:5280/upload/9c622181-b6cd-4923-9f42-330c3e26f0c2/12074998_10153687553914438_3232317774618942518_n.jpg
    (2015-10-11T12:36:56) nick@riotcat.ddns.net/Gajim_: xxxxx
    (2015-10-11T12:36:59) nick@riotcat.ddns.net/Gajim_: xxxx
    (2015-10-11T12:37:26) jonny@riotcat.ddns.net: xxxx
    (2015-10-11T12:38:29) nick@riotcat.ddns.net/Gajim_: xxxx
    (2015-10-11T12:41:24) xxxx@riotcat.ddns.net/mobile: xxxxx
    (2015-10-11T14:45:39) nick@riotcat.ddns.net/Gajim_: xxxxx
    (2015-10-11T14:45:45) nick@riotcat.ddns.net/Gajim_: xxxxx

**Comment by SafwatHalaby** [comment]
Does everything work properly when auto accept is turned on? If the answer is yes, then this is exactly issue #1459, which was closed for some reason?

**Comment by JonnyTischbein** [comment]
I tried the different auto accept file sizes.
Everything greater than 256KiB does the same. With 256KiB and auto accept never I can see a Download button [Screenshot-1]  but if I click it these error message appear [Screenshot-2].
![screenshot-1](https://cloud.githubusercontent.com/assets/10757520/10453660/a8e306a4-719d-11e5-91b2-ffe9fac72341.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/10757520/10453662/ab0e7b3e-719d-11e5-989f-297e278dd7bf.png)

**Comment by DoM1niC** [comment]
Yep same issue here, I think a Small fix will help ☺

**Comment by SafwatHalaby** [comment]
@iNPUTmice , please re-consider #1459 . When auto-accept is turned off, image previews are turned off. That is a bug.

**Comment by andersruneson** [comment]
But how do you think the image is downloaded for a preview? If you don't
have auto-accept then Conversations don't download the image and no preview
can be displayed.

**Comment by SafwatHalaby** [comment]
@JonnyTischbein , the download error probably means your server is misconfigured. The fact that a link shows instead of a download buttons is bug #1459.

@andersruneson , if you don't have auto-accept, a "Download image" button should show.

**Comment by SafwatHalaby** [comment]
@JonnyTischbein does the image open properly in a browser?

**Comment by andersruneson** [comment]
Yes "The link is correct anyway. I can see the picture if I'm following the
link with a browser or wget."

**Comment by SafwatHalaby** [comment]
I cannot help further, sorry. I should note that this is not the same as #1469.

**Comment by SafwatHalaby** [comment]
I removed my revious comments because I misread something, and they are irrelevant.

**Comment by iNPUTmice** [comment]
make sure your server answers to HEAD requests

**Comment by JonnyTischbein** [comment]
I logged with 

    adb -d logcat -v time -s conversations

when I tapped and hold and choose "Download image" the Download button appears (see upper post Screenshot-1) and following log shows up

    10-13 15:24:58.617 D/conversations(23308): retrieve file size. interactive:true

When I tap the download button the same error message appears ("Download failed: File not found", see upper post Screenshot-2) but nothing is logged via adb.

**Comment by JonnyTischbein** [comment]
Where do I check If my

**Comment by JonnyTischbein** [comment]
>  iNPUTmice commented 13 minutes ago
>  make sure your server answers to HEAD requests

Where do I check whether my server does it or not ? Is that about a plugin or the server configuration itself ?

**Comment by SafwatHalaby** [comment]
@JonnyTischbein I checked this for you. your server handles HEAD requests properly. @iNPUTmice , this isn't the problem.

```
wget -S --spider http://riotcat.ddns.net:5280/upload/9c622181-b6cd-4923-9f42-330c3e26f0c2/12074998_10153687553914438_3232317774618942518_n.jpg
Spider mode enabled. Check if remote file exists.
--2015-10-13 18:41:55--  http://riotcat.ddns.net:5280/upload/9c622181-b6cd-4923-9f42-330c3e26f0c2/12074998_10153687553914438_3232317774618942518_n.jpg
Resolving riotcat.ddns.net (riotcat.ddns.net)... 93.220.14.50
Connecting to riotcat.ddns.net (riotcat.ddns.net)|93.220.14.50|:5280... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Connection: Keep-Alive
  Content-Type: image/jpeg
  Date: Tue, 13 Oct 2015 15:41:06 GMT
  Etag: b302-3fb39-dbb2-561a3bc3
  Content-Length: 56242
  Last-Modified: Sun, 11 Oct 2015 10:36:51 GMT
Length: 56242 (55K) [image/jpeg]
Remote file exists.

```

**Comment by iNPUTmice** [comment]
I don't know who or what is serving your files. but it seems like the response to HEAD requests is the same as for GET requests. (ie it's serving the file). And java is tripping over that.
fix your server!

**Comment by SafwatHalaby** [comment]
Oh, I mis-interpreted the wget response. Sorry.

**Comment by JonnyTischbein** [comment]
I don't get the problem right now

    wget -S --spider

does a GET request without downloading anything  but printing servers response, right ? And a HEAD request should be just the head without any body (META information). In our case the server respond just the size of the requested file

    local function serve_head(event, path)
    event.send = size_only;
    return serve_uploaded_files(event, path);
    end

(from: https://hg.prosody.im/prosody-modules/file/5d84b7fbe3aa/mod_http_upload/mod_http_upload.lua#l126gaji)

What does conversations except as an correct answer ?

**Comment by strb** [comment]
@JonnyTischbein The problem is that that's not what actually happens.

    echo -ne 'HEAD /upload/9c622181-b6cd-4923-9f42-330c3e26f0c2/12074998_10153687553914438_3232317774618942518_n.jpg HTTP/1.1\r\nUser-Agent: curl/7.39.0\r\nHost: riotcat.ddns.net:5280\r\nAccept: */*\r\n\r\n' | nc -v riotcat.ddns.net 5280

Your server clearly responds with the actual file here. This problem is not on our end.

**Comment by SafwatHalaby** [comment]
@strb, are you sure?

I tried this, just in case:
```
wget -S --spider https://assets-cdn.github.com/images/modules/dashboard/bootcamp/octocat_setup.png
Spider mode enabled. Check if remote file exists.
--2015-10-13 20:31:34--  https://assets-cdn.github.com/images/modules/dashboard/bootcamp/octocat_setup.png
Resolving assets-cdn.github.com (assets-cdn.github.com)... 185.31.19.133
Connecting to assets-cdn.github.com (assets-cdn.github.com)|185.31.19.133|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Server: GitHub.com
  Content-Type: image/png
  Last-Modified: Tue, 01 Sep 2015 20:29:05 GMT
  Expires: Wed, 12 Oct 2016 17:30:45 GMT
  Cache-Control: max-age=31536000, public
  Timing-Allow-Origin: https://github.com
  Content-Length: 7926
  Accept-Ranges: bytes
  Date: Tue, 13 Oct 2015 17:30:45 GMT
  Via: 1.1 varnish
  Age: 0
  Connection: keep-alive
  X-Served-By: cache-lhr6329-LHR
  X-Cache: MISS
  X-Cache-Hits: 0
  X-Timer: S1444757445.589273,VS0,VE357
  Vary: Accept-Encoding
Length: 7926 (7.7K) [image/png]
Remote file exists.
```
As you can see, it's roughly the same wget output as the output @JonnyTischbein 's server generated.

I also tried this:
```
url -I http://riotcat.ddns.net:5280/upload/9c622181-b6cd-4923-9f42-330c3e26f0c2/12074998_10153687553914438_3232317774618942518_n.jpg
```

**Comment by SafwatHalaby** [comment]
fixed bad formatting

**Comment by strb** [comment]
@SafwatHalaby 
Yes, I'm sure. Maybe your tooling is hiding/ignoring this extraneous data. Run the command I posted. That way, you'll see the raw response.

**Comment by SafwatHalaby** [comment]
That's interesting. What are the odds that both `curl` and `wget` don't handle an unhealthy HEAD response correctly?

**Comment by strb** [comment]
Probably a best-effort implementation on their part. People generally seem to play fast and loose with the HTTP specification. Either way, RFC 2616 clearly states

    The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response.

So the server is clearly not conformant to spec here.

**Comment by SafwatHalaby** [comment]
I'll a mail upstream, to the author of the [responsible code](https://hg.prosody.im/prosody-modules/file/5d84b7fbe3aa/mod_http_upload/mod_http_upload.lua#l126gaji).

**Comment by SafwatHalaby** [comment]
@JonnyTischbein , in case the code turns out to be fine, it must be something with your setup.

**Comment by Zash** [comment]
Should be fixed in https://hg.prosody.im/prosody-modules/rev/43fac0c2c772

**Comment by JonnyTischbein** [comment]
Zash commented 2 hours ago
    Should be fixed in https://hg.prosody.im/prosody-modules/rev/43fac0c2c772

It works! Thank you.

**Comment by Polynomdivison** [comment]
The Plugin in Gajim HttpUpload 0.3.1 is only working when you click "Send file via http upload" and not "Send image via http upload".
When you click on "Send image via http upload" it appears only a empty message on the conversations screen.

After the fixed in the prosody module the image preview plugin 0.6.3 from Gajim isn't working anymore.

**Comment by strb** [comment]
@Polynomdivison This is neither gajim's nor prosody-modules' issue tracker. Please take up these problems with the respective involved parties directly. If you are encountering an actual issue with Conversations, please open a separate issue.
