### ISSUE TITLE
resizing when uploading image removes exifinfo

### ISSUE THREAD

**Issue by lsanderson** [siacs/Conversations#1499]
If I want to share an image with Conversations, and the image is too large, Conversations will resize it. In this proces it discards the exif information from the image. It is only done when resizing, images small enough are uploaded untouched.

I think it could be handy to have this as an option (removing possibly sensitive GPS and date stamps), but not as default. :-)

**Comment by knoy** [comment]
I strongly support this! Most people are unaware of exif info from their phone or camera leaking their GPS location

**Comment by strb** [comment]
If anything, we should be stripping EXIF data by default on all images, so I'd consider it to be a bug that at the moment we only do so when resizing. Retaining EXIF should be opt-in, if anything. 

@lsanderson May I ask, do you have specific use-cases in mind where it would be important to you that such meta-data is retained in the sent image? I understand their utility in a general sense, but I'm not so sure how this information would be useful in an IM context. At least how I use it, exchanged messages and images tend to be more ephemeral in nature (i.e. less "look at this nice macro photograph!" and more "look at this funny street sign I just spotted!")

**Comment by lsanderson** [comment]
@strb I agree that mostly the option is used for "funny street signs" or party snapshots, but ocasionally I want to save some of these and I mainly use date for sorting photos and when no EXIF data is there, I have to manually set it.
I am aware that I could just "send file" instead of "take picture" and Conversations will not mess with it. But the "take picture" option is the one I use most since taking a picture and sending it from within Conversations in one action is very handy :-) 

Would be nice to have EXIF info removal as an option, but I agree that it at least should be consistent.

**Comment by iNPUTmice** [comment]
There is an option now where you can enable or disable resizing (and exif removal)
