### ISSUE TITLE
synchronize encryption protocols

### ISSUE THREAD

**Issue by ghost** [siacs/Conversations#1501]
At the moment, it is possible that two users of Conversations choose two different encryption methods, e.g. user A selects OTR and user B selects OMEMO.

I think this should not happen and Conversations should prevent such situation. My suggestion is that when a user A selects OTR, it should be noticed by the Conversations of B and start talking OTR too. As soon as B decides to change to OMEMO, the client of A should notice that too and switch seamlessly to OMEMO. Such behavior seem more intuitive and less obtrusive (as I understand, one of the main goals of Conversations). Is there any disadvantage of that?

(Currently agreement or disagreement in protocol selection is indicated by green and red background. It is a poor UI, because it is not clear and confusing for new and old users. Not clear -- especially for new users -- because it could equally be just a colorful theme and there's no indication that the colors have any meaning. Confusing -- because people aware of encryption intuitively associate the colors with encrypted/unencrypted status of the message, which is wrong.)

**Comment by iNPUTmice** [comment]
The disadvantage of this is that your contact can dictate an inferior encryption protocol without you noticing. You don't want anyone sneaking OTR messages into your OMEMO conversation.

**Comment by aeuii** [comment]
Yes, it makes sense. There should be a clear indication of which protocol is being used that is visible even just before pressing the send button (issue #1456 is related). The change of protocol would not go without noticing.

In my experience, when I introduce Conversations to new users, this manual protocol synchronization is a big hurdle. People are already overwhelmed because it is a new program and this extra effort does not help.

The scenario that you described, someone sneaking OTR messages into an OMEMO session, could be solved with clear indication of the protocol. Typically, once the protocol has been established (manually or automatically) people just tend to use it and confirm from time to time that it's encrypted, preferably with OMEMO. If someone maliciously and persistently sneaks OTR into OMEMO ;) then you probably have a bigger problem anyway.

For me the easier (automatic) protocol synchronization has more immediate and useful advantages, than this not-so-common disadvantage, which could be solved by proper UI indications.

**Comment by iNPUTmice** [comment]
What I don't understand here is why a novice user would want to change
encryption protocols anyway.

> Typically, once the protocol has been established (manually or
automatically) people just tend to use it and confirm from time to time
that it's encrypted, preferably with OMEMO.

once a protocol has been established (two parties agreeing whether they
won't to use OTR or OMEMO there shouldn't be a problem. Meaning there
should be no further negotiation or changes. Thats why Conversations tries
to stick with whatever the user selected.

> If someone maliciously and persistently sneaks OTR into OMEMO ;) then you
probably have a bigger problem anyway.

Well this is exactly what end-to-end encryption is trying to protect you
from.

**Comment by aeuii** [comment]
> What I don't understand here is why a novice user would want to change
> encryption protocols anyway.

When chatting for the first time, everyone has to change from
unencrypted to some encryption protocol.  It takes a while to explain a
novice user what and how to do.

If the encryption protocol were selected automatically, it would not be
necessary.  At the beginning of the first conversation Alice would
select OMEMO and Bob would not have to think or even know about it.  I
think about a situation, where one party turn on the encryption the
other client starts to respond with the same protocol.  I think that
other clients do it this way.

What do you think?

**Comment by SamWhited** [comment]
> I think about a situation, where one party turn on the encryption the other client starts to respond with the same protocol.

Like @iNPUTmice said, this isn't actually a good thing. I might not want to turn encryption on (eg. if one of my mechanisms is signed-PGP [not actually supported by Conversations, but it's just an example] a remote user could trick me into sending messages with absolutely no form of plausable deniability). Alternatively, if I'm using OMEMO and a user switches, suddenly I could be using a known-broken version of some other encryption protocol, or they could turn encryption off altogether and I might not notice.

Things like this should NEVER be done automatically without the users consent.

**Comment by aeuii** [comment]
PS I often write “automatically” when refering to protocol selection,
but I really mean semi-automatically, because one party has to do it
manually.  However, preferably the process should be fully automatic and
users should not care about such detail as how to activate encryption
and which type to use. Semi-automatic is a step towards that in my
opinion.

**Comment by SafwatHalaby** [comment]
One could allow "automatic upgrade" but dis-allow "automatic downgrade".
E.g.
If the setting was previousloy PGP or OTR, allow auto-switching to OMEMO
If the setting was previously OMEMO, do not allow auto-switching to PGP or OTR
If the setting was previously no-encryption, allow auto-switching to any form of encryption
If the setting was previously any form of encryption, do not allow auto-switching to no-encryption
Regarding The switch between PGP and OTR, should probably be disallowed both ways.

Not sure if this is a good idea, just bringing it up.

**Comment by SafwatHalaby** [comment]
Diagram:
```
None --> PGP / OTR --> OMEMO
```
Auto switching only allowed from left to right.

**Comment by aeuii** [comment]
>> I think about a situation, where one party turn on the encryption the other client starts to respond with the same protocol.
>
> Like @iNPUTmice said, this isn't actually a good thing. I might not want to turn encryption on (eg. if one of my mechanisms is signed-PGP [not actually supported by Conversations, but it's just an example] a remote user could trick me into sending messages with absolutely no form of plausable deniability). Alternatively, if I'm using OMEMO and a user switches, suddenly I could be using a known-broken version of some other encryption protocol, or they could turn encryption off altogether and I might not notice.
>
> Things like this should NEVER be done automatically without the users consent.

Thanks for entering the conversation.

I see your point.

What do you think about seamless/semi-automatic upgrade from unencrypted
to any encrypted protocol?  It would solve the problem of the initial
conversation.

As for the change between different forms of encryption, I agree with
you.  But the current indication (background colors) is confusing and
perhaps could more explicit.

Cheers

**Comment by SamWhited** [comment]
> One could allow "automatic upgrade" but dis-allow "automatic downgrade".
> If the setting was previousloy PGP or OTR, allow auto-switching to OMEMO
> If the setting was previously OMEMO, do not allow auto-switching to PGP or OTR
> If the setting was previously no-encryption, allow auto-switching to any form of encryption
> If the setting was previously any form of encryption, do not allow auto-switching to no-encryption
> Regarding The switch between PGP and OTR, should probably be disallowed both ways.

>What do you think about seamless/semi-automatic upgrade from unencrypted to any encrypted protocol? It would solve the problem of the initial conversation.

That's starting to get very complicated for little to no benefit as far as I can tell (especially since the behavior will be inconsistant between clients), and None->PGP or PGP->anythingelse may still be a bad thing depending on the use case... there isn't a strict "this encryption mechanism is better" upgrade path, even between "plain" and "encrypted". It all depends on your use case / threat model.

The "solution" is as simple as: "if you want encryption, turn on encryption; if you don't know what encryption is, then your contact can tell you to 'click the OMEMO' button". I don't really see why this is that difficult.

**Comment by SafwatHalaby** [comment]
@SamWhited , slightly off-topic: Under which circumnstances is PGP better than OMEMO?

**Comment by SamWhited** [comment]
@SafwatHalaby When you want something without malleable encryption (OMEMO messages can be "faked" afterwards by a third party to provide a form of deniability), for example.

**Comment by aeuii** [comment]
On Fri, Oct 16 2015, Sam Whited <notifications@github.com> wrote:

>> One could allow "automatic upgrade" but dis-allow "automatic downgrade".
>> If the setting was previousloy PGP or OTR, allow auto-switching to OMEMO
>> If the setting was previously OMEMO, do not allow auto-switching to PGP or OTR
>> If the setting was previously no-encryption, allow auto-switching to any form of encryption
>> If the setting was previously any form of encryption, do not allow auto-switching to no-encryption
>> Regarding The switch between PGP and OTR, should probably be disallowed both ways.
>
>>What do you think about seamless/semi-automatic upgrade from
>>unencrypted to any encrypted protocol? It would solve the problem of
>>the initial conversation.
>
> That's starting to get very complicated for little to no benefit as
> far as I can tell (especially since the behavior will be inconsistant
> between clients), and None->PGP or PGP->anythingelse may still be a
> bad thing depending on the use case... there isn't a strict "this
> encryption mechanism is better" upgrade path, even between "plain" and
> "encrypted". It all depends on your use case / threat model.

I agree about too many states.  But the single upgrade from "plain" to
any "encrypted" solves a typical use case for novice users.  Every time
I introduce Conversations to someone, I always have to explain how to do
it.


> The "solution" is as simple as: "if you want encryption, turn on
> encryption; if you don't know what encryption is, then your contact
> can tell you to 'click the OMEMO' button". I don't really see why this
> is that difficult.

For me it's really OK as it is now and I'm really glad you put your
effort into the app.

I opened this issue and described the problem from the perspective of
novice users.  I saw that they almost always have some friction there:
you have to explain something about the program, so they can use it
properly.  It's not a technical problem, just usability improvement.

 2¢

**Comment by iNPUTmice** [comment]
If an user never explicitly made a choice and receives an encrypted message Conversations will automatically select the same encryption mechanism for the answer. Sending plain text messages only happens if the user (at some point) explicitly selected 'None'.

**Comment by marix11** [comment]
But why default is unencrypted, why everytime you need select. Would be nice if stay on last selection
