### ISSUE TITLE
SHA-1 depricated soon?

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1502]
Security researcher says it's only a matter of time until SHA-1 is decleared to be insecure and it should no longer be used:
https://sites.google.com/site/itstheshappening/
https://eprint.iacr.org/2015/967.pdf

Since Conversation claims to be an app for secure communication, will it move on to SHA-2 in the future?

Kind Regards

**Comment by SamWhited** [comment]
If any server actually supported SCRAM-SHA-2 out of the box the changes would be rather trivial to make. I've got a branch with SCRAM-SHA-2 support that I'm happy to make a PR for, but it doesn't seem all that useful yet.

**Comment by knoy** [comment]
Maybe this should be added for future proofing? If the changes to client-side are trivial it shouldn't be too hard to make something like a ejabberd or prosody module in theory ?
