### ISSUE TITLE
https config ends up as http link using http_upload

### ISSUE THREAD

**Issue by samweisgamdschie** [siacs/Conversations#1507]
I configured put_url and get_url as https://myhostname:5444 but when I use jappix as the receiving client I get an http://host:5444 link.

Although it  works with other conversations clients it looks like the full link is transfered plaintext.

**Comment by andersruneson** [comment]
This should be reported either with HttpUploadComponent or to Jappix.
Or please describe how this issue is related to Conversations.

**Comment by samweisgamdschie** [comment]
I use conversations to send a picture. It should ask the server for the put and get urls. It must  receive my configured https links from ejabberd. When it finally sends the file it creates an http:host:5444.... link. At least I get such a link in jappix as a real link since jappix does not speak xep-0363 and just shows the link.

I do not really know where to locate this case (say which component exactly generates this link). Neither I

**Comment by iNPUTmice** [comment]
What URL do you get when you long press on the picture in Conversations and select copy-url?

**Comment by samweisgamdschie** [comment]
I get this as an example (just replaced host) http://host:5444/0a35e9c98a7b1e95a567021156faa1d272a9b6/9nwfStGBo7pM0H2i4WyKjlwfNw897ITnBHtP6WL/a1d09326-5082-417b-a1ec-fe7e31eb7dd1.jpg

**Comment by samweisgamdschie** [comment]
I turns out, that there was an override in the configuration of the ejabberd server. It has to be configured in the modules own config file. Now it works like a charm! sorry for the inconvenience and thanks for your support.
