### ISSUE TITLE
otr vs omemo

### ISSUE THREAD

**Issue by marix11** [siacs/Conversations#1509]
Whats more secure? What is stronger encryption?

**Comment by strb** [comment]
This is an issue tracker, not a discussion forum. For more information on OMEMO, see the [info page](http://conversations.im/omemo/).

**Comment by SafwatHalaby** [comment]
And the [faq](https://github.com/siacs/Conversations#why-are-there-three-end-to-end-encryption-methods-and-which-one-should-i-choose).
