### ISSUE TITLE
Disconnect breaks OTR session

### ISSUE THREAD

**Issue by bugtrapper** [siacs/Conversations#1512]
Whenever I'm in an OTR session and get a involuntary disconnect, the OTR sessions fails. My conversation partner then gets error messages whenever he wants to send something or gets messages that I use multiple OTR-sessions when I send something. The old OTR-session doesn't seem to be getting closed, even 10 minutes after I opened a new one.
Clients used: Conversations 1.6.11, Pidgin 2.10.11
Server Software used: ejabberd (not 100% sure, though)

I never had this problem with another client on Android and couldn't reproduce it there, while it is reproducible (for me) with opening an OTR-session, write something, activate airplane mode, deactivate airplane mode and then try to continue the conversation.
Is this a security feature? It is rather bothersome when my connection is dropping out frequently, which happens quite often on longer journeys.

**Comment by iNPUTmice** [comment]
If not doing so already you be using a server with stream management.

**Comment by LoschmidtParadox** [comment]
I'm getting similar issues. Whenever I or my contact changes wifi/data networks OTR fails and all subsequent messages are marked as failed. I've been working around this by sending an unencrypted message followed by an OTR message, which I assume renews the session until the next network change.

**Comment by marmeladenfaust** [comment]
As iNPUTmice said: Maybe your server doesn't have stream management enabled. Please check the server info, displayed by conversations in the account details. "XEP-0198: Stream Management" has to be followed by "yes"

**Comment by bugtrapper** [comment]
Hey marmeladenfaust, thanks for pointing that out - didn't know Conversations could do that. I checked both servers, they both have stream management enabled.

**Comment by LoschmidtParadox** [comment]
Wow, that's really convenient! Looks like the servers I've been using don't have stream management. :(
