### ISSUE TITLE
Share to Conversations.

### ISSUE THREAD

**Issue by Bretos** [siacs/Conversations#1515]
In a case that I use Android share option, and choose to share a file to Conversations (eg. from gallery), it uses xmpp in-band file transfer instead of httpupload, even if it's available. Shouldn't Conversations first try to share the file through httpupload, and if fail/not available fall back to "old" xmpp file transfer?

**Comment by SafwatHalaby** [comment]
I can't reproduce this.

**Comment by Bretos** [comment]
Forgot to mention few details:

the phone is LG Spirit 4G LTE with stock firmware, running Android Lolipop (with included LG crapware, not-rooted)

**Comment by moshpirit** [comment]
Why should it try first HTTP upload instead of Jingle?

**Comment by d9h02f** [comment]
(in every single possible case, HTTP upload works better)

**Comment by moshpirit** [comment]
Oh, OK thanks!

**Comment by singpolyma** [comment]
@d9h02f in *every possible case*? citation needed :P

**Comment by iNPUTmice** [comment]
fixed with 5e151c7311bed98ce7eafa041735484c32bd7dda
