### ISSUE TITLE
HTTP Upload Bug: Files remain in "waiting..." state when they shouldn't

### ISSUE THREAD

**Issue by SafwatHalaby** [siacs/Conversations#1518]
In a very specific scenario, transmitted files can stay in a "Waiting..." state:

1. You are offline, either because there's no connectivity or because account is disabled.
2. You send a file while you are offline, the file enters the "waiting..." state and awaits connection.
3. You log in, but the contact is offline.
4. The file should start transmitting, but it doesn't.
5. When the contact logs in, transmission starts.

This behavior was almost definitely accidentally inherited from the traditional file transfer, in which the two contacts must be online.

**Comment by bangarharshit** [comment]
I am getting the same issue. Can it be related to xep-0363 file uploading. I guess we need to enable it for offline transfer.

**Comment by SafwatHalaby** [comment]
Yes, XEP-0363 should be enabled for offline file transfer.
This talks solely about XEP-0363 though, it exists only when XEP-0363 is enabled.

**Comment by knoy** [comment]
I agree.. this would be a great improvement to increase reliability when both users are experiencing intermittent connectivity (as is often the case with mobile users)

**Comment by alexara** [comment]
> When the contact logs in, transmission starts.

The http_upload service discovery takes some time (at least a few seconds) on my ejabberd 15.10 server with mod_http_upload. However, the file transmission starts immediately when the user comes online and for this reason it always uses jingle first in this special case.

Maby that's also the reason why XEP-0363 does not work when the other user is offline: Because Conversation simply does not know whether the other user supports XEP-0363 or not.

**Comment by strb** [comment]
> Maby that's also the reason why XEP-0363 does not work when the other user is offline: Because Conversation simply does not know whether the other user supports XEP-0363 or not.

XEP-0363 does not need client support on the receiving side.

**Comment by SafwatHalaby** [comment]
>However, the file transmission starts immediately when the user comes online and for this reason it always uses jingle first in this special case.

You've removed that line but it might be of use. Some other issue complained about clients not using HTTP upload even when it's available, this bug might be related.

**Comment by iNPUTmice** [comment]
fixed with 5e151c7311bed98ce7eafa041735484c32bd7dda
