### ISSUE TITLE
When offline (im)possible to "Create contact".

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1519]
When your accounts are offline, you can still click on the "+" button to start or create a new conversation.
However, the contact list there is obviously empty and from here clicking on the "create contact" button doesn't make any sense at all since you cannot add any contact without being logged in.

Suggestion: Disable "+" button when all accounts are offline.

**Comment by iNPUTmice** [comment]
The contact will be pushed to the server once you come online. And the contact list won't be empty if you have been online before.

**Comment by alexara** [comment]
I cannot choose any account for which I would like to create a contact. And I have been online before.
So is this a bug?

**Comment by iNPUTmice** [comment]
I can't reproduce this unless by offline you mean disabled maybe

**Comment by alexara** [comment]
I am sorry I got this wrong: I meant "disabled"! I think it doesn't make sense to allow the user to click on the "+" when all accounts are disabled. It should be grayed out.

**Comment by alexara** [comment]
So, isn't it confusing to open a screen where you cannot do anything? Don't you agree that it doesn't make sense?
Most programs do disable menu items when they are not available for logical reason.
