### ISSUE TITLE
Conversations occasionally resends messages I've sent in the past

### ISSUE THREAD

**Issue by thefinn93** [siacs/Conversations#1522]
I'm running into an issue where conversations will sometimes resend the last message or last few messages i've sent to a contact. I haven't been able to find any pattern for when this occurs, but I only notice it when a friend gets a message from an old conversation that doesn't make sense out of context and asks me wtf I'm talking about, so I may be missing some of them. I've seen similar resent messages from the few friends of mine who also use Conversations.

**Comment by iNPUTmice** [comment]
What server software are you using?

If you are using a rather old version of prosody please update the smack module.

**Comment by thefinn93** [comment]
dpkg says Prosody 0.9.7-1, I'm running the version of `mod_smakcs` from hg. I'll try updating it and see if that fixes it. Thanks!

**Comment by srguglielmo** [comment]
@thefinn93 Prosody has a apt repository for the latest versions of prosody: https://prosody.im/download/package_repository

**Comment by thefinn93** [comment]
Yeah, I am using those, and I examined things more closely, dpkg had the `prosody` package cached, but it isn't installed. `prosody-trunk` is installed though:

```
$ dpkg -l | grep prosody
ii  lua-sec-prosody                  0.5.1-2~sid                  amd64        SSL socket library for the Lua language version 5.1
rc  prosody                          0.9.7-1                      amd64        Lightweight Jabber/XMPP server
ii  prosody-trunk                    1nightly591-1~sid            amd64        Lightweight Jabber/XMPP server
```

**Comment by iNPUTmice** [comment]
Make sure you are running the latest version of mod_smacks. As it had bugs in the past that were causing those issues you are talking about.

**Comment by thefinn93** [comment]
Welp, I updated everything again after you said that. I think I had messed up previously when attempting to updating the prosody-plugins hg repo (don't use hg much), and I haven't seen this resurface, nor have the people who reported it originally. Thanks for the help!
