### ISSUE TITLE
Share location feature is kept secret

### ISSUE THREAD

**Issue by jkufner** [siacs/Conversations#1525]
There is option to set quick action button to share location feature. But once set, it only says that there is no such app installed. No explanation, nothing. There should be some better message about missing plugin with a link where to get the plugin.

Also there should be a list of available plugins (installed or not) with some short description and maybe few screenshots. Similar to the About screen and also available from settings menu. So an user can easily discover that there is more to have fun with. This list should have links to Google Play or F-Droid depending from where it was installed. And it would be a good place to promote bitcoin address where donations can be sent.

**Comment by iNPUTmice** [comment]
I can't reproduce this. On my devices it opens the Playstore or the website
if the plugin is not installed.

**Comment by jkufner** [comment]
I don't have Play store enabled, so it cannot open it. But it looks like problem with F-Droid application, when checking log, I now noticed some notification which I would not expect there. And there is nothing in log from Conversations. I will explore it a bit deeper.

**Comment by jkufner** [comment]
Ok, it looks like F-Droid problem -- better issue here: https://gitlab.com/fdroid/fdroidclient/issues/480

**Comment by venkatesh-prabu** [comment]
I can't able to integrate location plugin with conversation project. I am getting,

Error:Execution failed for task ':transformClassesWithDexForFreeDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_05\bin\java.exe'' finished with non-zero exit value 2

Problem caused after including  compile 'com.google.android.gms:play-services:6.5.87'

Please help me out to fix this issue.
