### ISSUE TITLE
Change status message with availability

### ISSUE THREAD

**Issue by QuentinC** [siacs/Conversations#1526]
Hello,

As far as I know, Conversation always put "online" as presence message:
![Screensot from Gajim](https://quentin.open-to-repair.fr/Captures/2015-10-27_23-30-55.png)

With the new version, the presence change with screen off / silent mode, but not the message.

I think it should follow the status, and maybe be translated in the user language not ?

Thanks,

Quentin

**Comment by iNPUTmice** [comment]
The 'online' status message is just a something we had to do to get PGP working. As the PGP code is being refactored right now we hopefully can get rid of this.
