### ISSUE TITLE
If I send a picture via URL with text the picture is not shown

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#1527]
If I send the URL of some picture without any text, the URL become a picture, there's no problem there. But if I do it with text the URL is not transformed into the picture.

**Comment by andersruneson** [comment]
That is not a bug, it's the intended behavior.

**Comment by moshpirit** [comment]
Well, I think that it should show always the pictures :\

**Comment by singpolyma** [comment]
I also would like this feature.

**Comment by iNPUTmice** [comment]
duplicate of #1421
