### ISSUE TITLE
prevent conference topic to be updated when no change is required

### ISSUE THREAD

**Issue by stevenroose** [siacs/Conversations#1528]
When you are the admin of a conference chat room and you have set a topic for the room in Conversations, Conversations automatically updates the topic to that value everytime you log in. (Or at least it looks like that since the other clients I have connected to the conference notify me of the change.)

This is cumbersome for the clients that show topic changes and when the topic has not been changed since the last update, this update is unnecessary. 

Thus, I propose to compare the status that is stored in Conversations with the current status of the Conference and only publish a change when the two differ.

**Comment by d9h02f** [comment]
Are you maybe experiencing this? https://github.com/siacs/Conversations/issues/1269

**Comment by stevenroose** [comment]
Well, yes, but in other clients. I could ask the devs of that client to
prevent notifications of (un)changed topics, but preventing the broadcast
is also a step in the right direction..

**Comment by iNPUTmice** [comment]
Conversations doesn't update the subject unless you hit the subject edit button in the conference details.

**Comment by stevenroose** [comment]
Thank you, that's good to know! Will have to file an issue elsewhere then.
