### ISSUE TITLE
[Feature Request] XA on vibrate

### ISSUE THREAD

**Issue by pheerai** [siacs/Conversations#1530]
Fisrt of all, thank you for your work. I especially like the new feature that enables XA if the phone is silent.

Now, usually, I (and many friends of mine) don't put my phone into this state, but use vibration instead. It would be really nice to have an option that includes this state when deciding whether to set auto-away or not.

**Comment by jkufner** [comment]
But some users, like me, use vibrate and silent modes only. Vibrate is normal state and silent is XA. And some user have phone always silent and once a time they call back on missed calls. This feature should be configurable to allow multiple ways of phone usage. However, configuration should be simple to make it easy to use.

**Comment by pheerai** [comment]
What I had in mind was something like this:

 * You  have the current option for "XA on silent" that behaves the same way it currently does
 * Additionally, there's another checkbox that gets selectable once the first option is "active". This one reads " include vibrate for auto XA" or similar, and does exactly that.

**Comment by asdil1991** [comment]
+1

**Comment by petmue** [comment]
Just out of curiosity, what does the abbreviation XA stand for?

**Comment by andersruneson** [comment]
Extended away.
