### ISSUE TITLE
Retransmit failed messages automatically

### ISSUE THREAD

**Issue by Elmi77** [siacs/Conversations#1531]
When sending a message it more or less regularly happens, I get some feedback "Message could not be delivered" (red text). When I send the same message again by usingthe resend-function, the message can be delivered without any problems, until now it never happened the second try failed too.

So two possibilities:

1. This is a bug in Conversations - please be so kind fix it
2. This happens for some other reason - please add a possibility to try sending such a failed message again and automatically (once).

**Comment by strb** [comment]
See #229
