### ISSUE TITLE
Concatenate two Jabber-servers into one tab in Conversations

### ISSUE THREAD

**Issue by Elmi77** [siacs/Conversations#1532]
Jabber is a nice and cool alternative, unfortunately the servers out there are more than instable. Sometimes they are offline, sometimes messages can't be sent and are on hold for hours, sometimes they reject messages. Resulting from that to have a reliable connection to a chat partner, most people I know do have at least two accounts on two different servers.

Now handling these two accounts is a bit tricky and nothing that would be accepted by a user without technical skills (means the standard WhatsApp user).

So as a suggestion to overcome this problem: is it possible to offer a possibility to create one account in Conversations that internally handles two jabber-accounts on two different servers and always sends messages using the other server when the first one fails? I know this is already possible (manually) by having two separate accounts and identities in Conversations, but I think it would be much better to let Conversations automate this. Most of the "standard" users will not do this but need a simple and easy to use solution - and reliable connections that do work most of the time.

**Comment by andersruneson** [comment]
I don't agree with the servers are instable. Have you tested jabber.at?
Second, it's not the job of the client to fix shortcomings in the server,
especially not over complex ways like connecting to several servers.

**Comment by Elmi77** [comment]
jabber.at is one of the two more or less stable servers I use (but also needs a second, backup server mainly because it often delivers messages with a delay of up to 6 hours and often does not transmit images).

I agree with you, it is not up to the client to workaround problems of servers - but what is the alternative? Users are not interested in _why_ a system is instable, they simply want to have a running system. And when both, client and server are not able to solve a problem, the related technology never will be used by more than only a few geeks.

**Comment by Elmi77** [comment]
Very friendly to close it without any comment :-1:

**Comment by jkufner** [comment]
@Elmi77 You've already got comment from @andersruneson. If your Jabber server is unstable, complain to your server's administrator. This is completely out of Conversation's scope. Some Jabber servers can run on multiple servers to allow failover when one of them fails, but that is server-side thing, client only connects somewhere and reconnects (to the same node or another) when connection fails, so there is nothing else Conversations can do about that.

**Comment by Elmi77** [comment]
Sorry, but there is no such thing like a stable Jabber server!

To sum this up: normal users please go away, Jabber is not usable for non-technical persons (which is the majority), they should keep away from this and better use WhatsApp - simply because it is working stable and reliable.

**Comment by kriztan** [comment]
@Elmi77 I have to disagree with you. I'm running my own Jabber server for more than one year and have all my friends and family there. All in all, it's very stable, reliable and as good as whatsapp is, if you fulfill some conditions on server side and you and your partners are using Conversations. So don't spread any false facts about stability and reliability. Try out other Jabber services and be happy or go back to whatsapp (to your pacifying, whatsapp is also an Jabber service)...
