### ISSUE TITLE
Conversation does not close stream correctly

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1535]
I've noticed a strange behaviour within my prosody which seems to be related on a not correctly closed stream from Conversations 1.7.0. I'm getting a lot of `write-error: closed` entries in my prosody log and mod_smacks does not close the streams if I log out (disable the account). https://prosody.im/issues/issue/559

During a log out, ADB shows:
`10-31 16:53:02.585 D/conversations(14964): user@domain.de: error connecting account. try again in -17s for the 1 time`
`10-31 16:53:02.630 D/conversations(14964): user@domain.de: disconnecting force=false`
`10-31 16:53:02.630 D/conversations(14964): user@domain.de: closing stream`
`10-31 16:53:02.630 D/conversations(14964): user@domain.de: Socket closed`
`10-31 16:53:02.630 D/conversations(14964): user@domain.de: error connecting account. try again in -17s for the 1 time`

**Comment by iNPUTmice** [comment]
Can you test if fb9ba0a734c4b854918f1c58940977c6037a6afa improves the situation for you.

**Comment by kriztan** [comment]
Thanks, I'm trying it out and report back.

**Comment by kriztan** [comment]
Your fix closes the streams correctly, and mod_smacks doesn't hibernate the sessions after logging off. But I've still `write-error: closed` in my prosody logs though and I've no idea what is causing this errors.
