### ISSUE TITLE
Frequently repeting own messages on Slack XMPP gateway

### ISSUE THREAD

**Issue by msjoberg** [siacs/Conversations#1536]
This relates to the issue #1475 which was partially fixed in v1.7.0 but still occurs frequently enough to make Conversations unusable for Slack for me. (I've also tested with current version 1.7.2.) When this happens a message I have sent to a conference remains as "Sending ..." even though it gets through fine, and gets resent each time I restart Conversations (or the connection gets reset due to connectivity issues, e.g. when traveling). At restart it typically resends several old messages that got "stuck" in this way. (Even week old messages.)

This doesn't happen for every message, but for some reason including a URL link in the message seems to always trigger it.

**Comment by iNPUTmice** [comment]
This can only be fixed by writing a workaround specifically for slack. For this I need to discover that the server is a slack server. So I either need to get a test account on a slack server or someone to post for example the output of a disco#info on the slack server. (Maybe we can use information from there to determine we are running on a slack gateway)

**Comment by msjoberg** [comment]
You can always create a free account to test with at <https://slack.com/>. But I'll gladly do any testing needed if you can just point me into the right direction :-)

I'm pretty fresh when it comes to XMPP, but experimenting with Pidgin's XMPP console I sent this stanza (I've replaced some identifying things):

    <iq type='get' to='foobar.xmpp.slack.com' from='sazius@foobar.xmpp.slack.com/theeX5Ee' id='info1'>
  	    <query xmlns='http://jabber.org/protocol/disco#info'/>
    </iq>

And got this response:

```
<iq from='foobar.xmpp.slack.com' to='sazius@foobar.xmpp.slack.com/theeX5Ee' type='result' id='info1'>
	<query xmlns='http://jabber.org/protocol/disco#info'>
		<identity name='Slack-XMPP' type='im' category='server'/>
		<feature var='http://jabber.org/protocol/disco#info'/>
		<feature var='jabber:iq:last'/>
		<feature var='jabber:iq:version'/>
		<feature var='http://jabber.org/protocol/disco#items'/>
		<feature var='jabber:iq:privacy'/>
		<feature var='vcard-temp'/>
		<feature var='urn:xmpp:ping'/>
	</query>
</iq>
```

I suppose the identity field would be enough to identify it?

**Comment by iNPUTmice** [comment]
Can you test this branch? https://github.com/siacs/Conversations/tree/slack_workaround

**Comment by msjoberg** [comment]
I managed to compile it and install it but now I get a "No certificates found - The app Conversations has requested a certificate..." dialog box when I start it or try to add a new account. (I had to remove my previous install of Conversations (from F-droid) to install the newly compiled version.

**Comment by iNPUTmice** [comment]
checkout that branch again. I temporarily pushed a wrong config. but I
force pushed the right config shortly after

**Comment by msjoberg** [comment]
OK, now I got it working. Many thanks! So far it seems to work, I have been unable to reproduce the bug with the new build... I will run the whole day to be sure, and report back here.

**Comment by msjoberg** [comment]
OK, I used it the whole day without any issues. I think `slack_workaround` branch has it fixed! :-)

**Comment by singpolyma** [comment]
I also have this issue, so if the workaround works that will be exciting!

@iNPUTmice I read the code and understand the workaround.  Curious if you have any theory on what might be the bug in slack to begin with?

**Comment by iNPUTmice** [comment]
slack modifies the message (both the id and apparently in some cases the
body) thus conversations is unable to recognize it's our message.

**Comment by iNPUTmice** [comment]
merged
