### ISSUE TITLE
Store attachments in unique folder for each contact or conversation

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1540]
Current situation is that all image files go to:

```
/storage/emulated/0/Pictures/Conversations
```

and all other files go to: 

```
/storage/emulated/0/Conversations
```

all with encrypted file names.
This makes it impossible to filter files from one conversation, which you would like to delete/backup/open etc.

Suggestion: Since each contact as a unique name and each MUC has one it'd be easy and very clear to store files from each conversation in it's own folder:

```
/storage/emulated/0/Conversations/logs/<jid/username>
/storage/emulated/0/Conversations/files/<jid/username>
/storage/emulated/0/Pictures/Conversations/<jid/username>
```

Since the number of MUCs can grow large over time and so the number of folders, it may be wise to store all "muc"-folders within a subdirectory:

```
/storage/emulated/0/Pictures/Conversations/muc/<muc-id>
```

Kind Regards

**Comment by kriztan** [comment]
:+1: the cryptic filenames are not usefull. It would be better to store it this way `yyyyMMdd_HHmmssSSS` with the sent/received date and time. So clearing a chat and fetching from MAM again does not cause duplicate files like it is currently the case because files have different filenames on each download.

**Comment by tmolitor-stud-tu** [comment]
This would be very nice, indeed!
+1

**Comment by therob84** [comment]
Are there any work going on in this matter (also same question for in #1047and #2285)?
I find it is way more an important feature than nice new emojis...
Anywhere I can help in beta testing?

**Comment by iNPUTmice** [comment]
The way some (most?) gallery apps work is that it would clutter the gallery with folders of thousands of contacts. this is not desirable.

**Comment by Hund** [comment]
Most galleries has two views today: by folder and by date (new to old). I'm pretty sure that everyone's using the date view.

**Comment by aslmx** [comment]
If subfolders are really not wanted, is there any chance to discuss the filenaming then please?
