### ISSUE TITLE
No Contact pictures shown in MUC if user is not mod or admin

### ISSUE THREAD

**Issue by philipflohr** [siacs/Conversations#1541]
Steps to reproduce:

1. Join a muc as normal user
--> No contact pictures are shown even if the contacts are known and their pictures are shown in a normal chat. (You'll only see the Letters)

2. Ask the MUC admin for Mod privileges
--> As soon as you have mod rights, you'll see the contact pictures of the other users

3. Ask the MUC admin to reset you to a normal user
--> As soon as you are a normal user again, only the letters are shown again.
The contact pcitures you saw during your time as mod stay at their places.

**Comment by andersruneson** [comment]
Is this an anonymous muc where you don't know others jids? Then change the
muc to a non-anonymous muc.

Conversations does not support vcard avatars in mucs but only pep avatars
which means that Conversations must know the users jid to get the avatar.

**Comment by strb** [comment]
By the way, is there a specific reason we don't support vCard in MUC? I can see from the source code why this is, but was this a deliberate choice? (paging @iNPUTmice)

**Comment by philipflohr** [comment]
@andersruneson this is a MUC started by Conversations, all users use accounts on the same server and know each other.

**Comment by strb** [comment]
@philipflohr How did you start this MUC? Can you have the Owner of the room check that it is a non-anonymous conference? (Cog icon in Conference details)

**Comment by iNPUTmice** [comment]
@strb not vasting bandwidth by downloading avatars of random people in some
random muc was the original intention behind that.

i though about some sort of middle ground were we show the avatar if we
already downloaded it before. ie if we recognize the hash. while this might
lead to more avatars being shown in general it will become completely
unexplainable.

but I'm open for discussions to either download every avater no matter what
or to do the thing mentioned above.

**Comment by philipflohr** [comment]
@strb I just retested this with a MUC I just started using Conversations, exactly the same results
@iNPUTmice I would show as much avatar pictures as possible, especially if the phone is connected to a wifi this should not be a big problem. Usually the set of contacts does not change very fast, so once the avatars are downloaded the additional bandwidth usage should be low

**Comment by strb** [comment]
@philipflohr You're not answering my question. How specifically did you start this MUC? By inviting people? By "joining" a not-previously-existing MUC from the StartConversationActivity? And please confirm that the MUC is non-anonymous.

**Comment by iNPUTmice** [comment]
just as an FYI. even if conversations were to start showing vCard avatars
in MUCs this won't magically make all avatars appear. Conversions doesn't
publish vCard information in its presence. this will only show avatars for
some desktop users.

**Comment by philipflohr** [comment]
What is the actual technical difference between a user, a moderator an an admin of a MUC?
Do "normal" users have access to the jids of other users?

**Comment by strb** [comment]
They do, in non-anonymous MUCs, which is why we're asking about that. That's pretty much the definition of non-anonymous MUCs. For additional differences, please refer to http://xmpp.org/extensions/xep-0045.html#associations

**Comment by philipflohr** [comment]
Are there any additional prerequisites for downloading the avatar picture besides of knowing the jid?
If not I would suggest to just download and display the avatar picture

**Comment by strb** [comment]
As @andersruneson has already said, if we know the JID, we *do* fetch avatars from PEP. For this, the room needs to either be non-anonymous, or you need to have sufficient privileges (e.g. moderator, admin).

I'm closing here as we're not actually talking about the issue any more.Unless you can confirm that you're experiencing your original issue in non-anonymous rooms as well, I will assume that this is not the case.  If you are interested in further discussion I suggest you join our conference channel.

**Comment by andersruneson** [comment]
Is this an anonymous muc where you don't know others jids? Then change the
muc to a non-anonymous muc.
