### ISSUE TITLE
File transfer - The .OGG format is not considered a media file.

### ISSUE THREAD

**Issue by SafwatHalaby** [siacs/Conversations#1546]
When a `*.mp4` is recieved, the button says "Open Video". However, when `*.ogg` is received, the button says "Open Application/OGG". Conversations should treat OGG as a media format.

Note that OGG is a container format which may contain either audio (Vorbis) or video (Theora), Conversations may need to differentiate between those two in order to choose between showing an "Open Audio" button and showing an "Open Video" button. An alternative, simpler solution would be showing a generic "Open Media" button for `ogg`.

**Comment by bastlwasti** [comment]
jep. Many phones have a soundrecorder app which just produces .ogg. So this could help then.

**Comment by LogicParrot** [comment]
There's also one more file extension: Sometimes Theora-containing OGG is called `*.vgg`.

**Comment by SamWhited** [comment]
> There's also one more file extension: Sometimes Theora-containing OGG is called *.vgg.

Who does that? I've seen ogg, ogv, and oga, but never vgg.

I'm not convinced we need to add lots of stuff like this though; we can grow the file extensions list indefinitely and never make a dent in the number of things people will name stuff. There must be a better way…

**Comment by LogicParrot** [comment]
I might be confusing `vgg` with `ovg`. 

>we can grow the file extensions list indefinitely and never make a dent in the number of things people will name stuff

At the very least `.ogg` should be included until you find that better way, since it is the native format of many voice recorders.

**Comment by LogicParrot** [comment]
I might be confusing `vgg` with `ogv`. 

>we can grow the file extensions list indefinitely and never make a dent in the number of things people will name stuff

At the very least `.ogg` should be included until you find that better way, since it is the native format of many voice recorders.

**Comment by bittorf** [comment]
can't we just include "file":

   user@linux ~ $ file 1464262253.ogg
   1464262253.ogg: Ogg data, Vorbis audio, mono, 8000 Hz, ~22400 bps, created by: Xiph.Org libVorbis I

so, we dont need the extension anymore.

**Comment by iNPUTmice** [comment]
Ogg is an outdated file extension. You should use oga.

**Comment by zak333** [comment]
> Ogg is an outdated file extension.

This seems to be correct for FLAC, Ghost and OggPCM, but not for Vorbis encoded audio.

See: https://wiki.xiph.org/MIME_Types_and_File_Extensions

> .ogg applies now for Vorbis I files only

> Vorbis and Speex may use .oga, but it is not the prefered method of distributing these files because of backwards-compatibility issues.
