### ISSUE TITLE
PC version

### ISSUE THREAD

**Issue by JStyle21** [siacs/Conversations#1550]
Hey Daniel,

Quick question, will there also be a pc version of this? kinda similar to whatsup web or textsecure browser.

**Comment by strb** [comment]
Might happen at some point, might not. There are no concrete plans at the moment. We would like to do it, but it would be a significant time investment. So, no promises.

As an aside, this is a bug tracker, not a discussion forum. It exists so we can keep track of issues with the software. Off-topic posts like this can be very distracting, as they clutter up the list and spam everyone watching the repository with emails. If you have such general questions, in the future, please take them to our conference. Thank you for understanding!

**Comment by SafwatHalaby** [comment]
In a sense, there's already a "desktop version". Conversations can work with Chrome/Chromium using [ARC Welder](https://developer.chrome.com/apps/getstarted_arc).

**Comment by strb** [comment]
True, but note that you won't be able to use OMEMO that way due to some weird bugs that we haven't had the time to figure out yet.

**Comment by tchncs** [comment]
A ```conversations-desktop``` will be **that** thing!
Like the Telegram Desktop.

The actual Desktop Clients for Jabber are very crappy.
Its no wonder, that the most people prefer things link telegram or whatsapp this time.

**Comment by JStyle21** [comment]
@tchncs Couldn't agree more.

**Comment by jkufner** [comment]
One of good desktop clients is [Gajim](https://gajim.org/). It supports MAM, Stream Management and Carbons and other XEPs.

I'm not sure about conversations on desktop since the user interface is built in Android way and not desktop way. It would require a lot of tweaks to desktopize it.

**Comment by d9h02f** [comment]
@jkufner Yeah, but the interface is twelve years old, none of the useful stuff is enabled by default and you need to go through incredibly complicated menus to enable everything you (everyone) need(s). It is usable only by XMPP experts, and even that only barely. It's currently the only option a desktop user has, but it isn't actually any good.

**Comment by jkufner** [comment]
@d9h02f Old user interface is not a bad thing. There is not much to invent on a chat window with contact list. But otherwise you are right. It is very sad situation.

**Comment by Natureshadow** [comment]
I use Gajim daily and do not at all find it "barely usable".

**Comment by LogicParrot** [comment]
Note that gajim can support HTTP File Upload via a plugin. This makes file transfer between Gajim and Conversations very easy.

**Comment by tchncs** [comment]
I tryed Gajim yesterday:

Inline Images look **damn** crappy if there are bigger than...no idea...400px?
Also i was unable to chat with some contacts...again also filetransfers was without any functionality. 
Checked this this some contacts on some different servers also my own.

This application is much more a bad example for xmpp as pidgin is, but with more potential i guess.
