### ISSUE TITLE
[Feature] FadingActionBar

### ISSUE THREAD

**Issue by DoM1niC** [siacs/Conversations#1551]
Its a Design think but its pretty awesome 4 the ContactDetails ;)

https://github.com/ManuelPeinado/FadingActionBar

**Comment by philipflohr** [comment]
While this would allow to show the current chat while also showing the contact details I don't think there is any benefit in implementing this.
But as @DoM1niC said - it's a design choice

**Comment by DoM1niC** [comment]
@philipflohr coud you create a basic code 4 me :)
