### ISSUE TITLE
Enable/disable mam for a specific muc

### ISSUE THREAD

**Issue by andersruneson** [siacs/Conversations#1553]
Normally mam is disabled for all new mucs (server side setting) so it would be nice if the moderator/admin of a muc easily can enable/disable muc mam.

In Google Hangouts, one can disable/enable something similar to mam by pressing menu-button (in any chat) and then "turn history on/off" maybe something like that for Conversations?

**Comment by Natureshadow** [comment]
What you want is actually setting room options.

Limitting this to the mam option seems nonsense, but implementing it in full would mean implementing all the XMPP forms thing.

**Comment by iNPUTmice** [comment]
For rooms created with Conversations Conversations will set mam to true now.
