### ISSUE TITLE
Battery / network use in recent builds?

### ISSUE THREAD

**Issue by kr428** [siacs/Conversations#1554]
Using Conversations again on a new device again after not using it very much since 1.6. Outcome: Conversations sees all my server sided history now. Great, even though unsure whether caused by upgrading our openfire server or by upgrading Conversations.

However now, Conversations behaves a bit odd. Had it running for about 20 minutes, phone on standby. After that, phone has lost 15% battery, most of it to Conversations. Plus: Conversations in this time obviously has used about 6 megabytes of mobile data. Is this a known or intended behaviour? How to track down what happens here?

**Comment by iNPUTmice** [comment]
Use adb logcat to see if Conversations is repeating a certain action over
and over again.

**Comment by kr428** [comment]
I see continuing 'skipping message...' statements in the log as the app apparently seems to download *all* the server sided archive on each start. Is this a server side issue then?

**Comment by iNPUTmice** [comment]
depends. at the beginning conversations logs what mam information it
requests. with date range and so on. if that query is not properly limited
it might be a conversations issue as well.

**Comment by kr428** [comment]
I see. Which input do you need to reproduce this? Looking at what I see on the phone, the app already has (initially?) downloaded most if not all the conversations successfully and tries the same over and over again. What should I look for in the logcat messages?

**Comment by iNPUTmice** [comment]
Ich brauche erstmal die log Line aus dem log die sagt requesting mam
archive with... begin... end...

Daran kann ich sehen ob Conversations überhaupt etwas falsch macht.

**Comment by kr428** [comment]
Danke für den Hinweis. Dann scheint's ein Server-Problem zu sein - soweit ich sehe, fragt Conversations maximal zwei Tage History an, aber der Server liefert deutlich ältere Nachrichten. Damit muß ich die openfire-Leute ärgern.

**Comment by kortwotze** [comment]
Mh - also bei mir zieht Conversations in der letzten Version auch unverhältnismässig viel Akku. Hab aber grade kein Logcat parat dazu. :/
