### ISSUE TITLE
PGP Images send via http upload are not decrypted

### ISSUE THREAD

**Issue by Polynomdivison** [siacs/Conversations#1555]
Hi,
when I encrypt an image and send it via http upload the file is not decrypted by the recipient so only the link is shown.
Furthermore the ending is only .pgp and not jpg.pgp or something like this. So you can't decrypt it with Openkeychain and view it automatically as an image.

Sending encrypted images with OMEMO and http_upload is working.

**Comment by iNPUTmice** [comment]
fixed in 1.7.3
