### ISSUE TITLE
getting "incompatible server" server on login

### ISSUE THREAD

**Issue by jagdishkk1989** [siacs/Conversations#1556]
I am getting "incompatible server" error while login using conversations. I am able to login with same credentials using spark or another xmpp client for android like xabber. This error occurred after clone my open fire server to another subdomain.

**Is it related conversations xmpp client issue or openfire server issue? I am very confusing..:(**

If anyone have idea. Please help me.
Thanks in advance.

**Comment by kriztan** [comment]
Please read the FAQ: https://github.com/siacs/Conversations#i-get-incompatible-server

**Comment by jagdishkk1989** [comment]
@kriztan  Thanks for response. I read that point but no idea how to provide the STARTTLS on openfire server. Is there required any certificate for openfire server or just enable some setting from admin console of openfire. For example: Openfire server-> Server->Server Settings->Security Settings->Server connection security->Accept self-signed certificates. Server dialback over TLS is now available [Checked/Unchecked]).

**Comment by kriztan** [comment]
@jagdishkk1989 I think this is not a Conversations issue, you should ask the openfire community for support.

**Comment by jagdishkk1989** [comment]
@kriztan  Thanks a lot for suggestion.:)
