### ISSUE TITLE
What is XEP for showing "outgoing" msg from elsewhere?

### ISSUE THREAD

**Issue by andrey-utkin** [siacs/Conversations#1564]
Please describe a XEP name for such behaviour.

A@somewhere is logged in from both Conversations (A@somewhere/Conversations) and other client (e.g. Pidgin, mcabber - A@somewhere/desktop). B@somewhere is its buddy.

When A@somewhere/desktop sends a message within a chat to B, Conversations show up that message in a chat window (which is a great feature!). When A@somewhere/Conversations sends a message, Pidgin, Gajim, mcabber **don't** show that message in their chat window.

I am interested it pointing this to aforementioned apps developers as an issue. In order to do this, I need to figure out how this functionality is codified in XEPs. Could you please give references to documents and/or Conversations code? Thank you.

**Comment by andersruneson** [comment]
Are you thinking about carbons?
Gajim supports this though in recent versions.

**Comment by strb** [comment]
You're looking for [XEP-0280: Message Carbons](http://xmpp.org/extensions/xep-0280.html). 

In the future, please refer to [this list](https://github.com/siacs/Conversations#xmpp-features), or [this list](http://conversations.im/#xmpp), or ask in our [conference](https://github.com/siacs/Conversations#conversations-doesnt-work-for-me-where-can-i-get-help). Please understand that this is not a forum for general questions and discussion, but an issue tracker. We use it to keep track of bugs and missing features, and threads like this one clutter up the tracker, as well as spamming the ~180 people that are watching this repository with emails.
