### ISSUE TITLE
Resend image after failure

### ISSUE THREAD

**Issue by singpolyma** [siacs/Conversations#1566]
Sometimes sending an image fails, but it always works when I retry.  Would be nice if Conversations could automatically retry once after first failure.

**Comment by martinsauter** [comment]
Yes, would be a nice feature, not only for images but also for text. I do have this scenario sometimes when the recipient is no longer online. When sending something to him the server times out and I get a "not delivered". When sending it again, the server then knows that the recipient is no longer reachable and stores the images and text for me and forwards them when the recipient comes online again.

**Comment by moshpirit** [comment]
And videos. Both sides. If the video has been uploaded and we want to download it but we miss the Internet connection, it shows an error so we can't see the video. But with a "retry" option we would be able to download it again with a stable internet connection.

**Comment by jacksgt** [comment]
Hey, any update on this functionality?

I think automatic resending should be tried at least one to two times, as this silent failure is very confusing for novice users and annoying for advanced users.

**Comment by licaon-kter** [comment]
I did have contacts telling me I posted pictures/text twice....just because of network connection glitches. I for one would not like this.

**Comment by iNPUTmice** [comment]
closing in favor of #1678
