### ISSUE TITLE
PGP: must tap 3 times to enable

### ISSUE THREAD

**Issue by andrey-utkin** [siacs/Conversations#1567]
When you tap a lock icon, and select OpenPGP, it raises some dialogs two times, AFAIR first one is about key selection for your account, second one is to unlock the key with OpenKeychain, and only after third time the text input field changes prompt to "Send OpenPGP encrypted message".

**Comment by andrey-utkin** [comment]
I give free account on my MAM & Message Carbons enabled public server decent.im to developers who fix this issue. Or any other Conversations issue. Security and privacy related issues are especially favoured, so such issues give you two accounts :)

**Comment by adithyaphilip** [comment]
Can be closed, fixed with https://github.com/siacs/Conversations/commit/a9a3ef0f6783a235575740553daffb0d8d4c586b.

**Comment by andrey-utkin** [comment]
Great! Thank you, will try that out.
