### ISSUE TITLE
Feature request: dark theme, optional day/night mode?

### ISSUE THREAD

**Issue by rejhgadellaa** [siacs/Conversations#1573]
Would be nice for amoled screen users to have a dark theme. Maybe also include an option to automatically switch for day/night (easier on the eyes).

I'd be happy to have a go at building the theme (layouts with modified colors) if the devs are willing to incorporate it?

/Sorry if this is a duplicate, mobile github site doesn't support search?

**Comment by andersruneson** [comment]
It's a duplicate yes.

**Comment by iNPUTmice** [comment]
duplicate of #529
