### ISSUE TITLE
Jabber Resources

### ISSUE THREAD

**Issue by policy-bob** [siacs/Conversations#1574]
I bought conversations trough playstore and noticed that conversations can not deal with different jabber resources. I tried to send a message from gajim (pc) to conversations (smartphone) to a different JID but the message was only received on the pc (gajim) and not on smartphone (conversations). Did I oversee something and if is there a way to send myself or a different JID a message on a different resource?

Just in case somebody dont understand what i mean: http://wiki.xmpp.org/web/Jabber_Resources

**Comment by strb** [comment]
I'm not sure I understand exactly the situation you describe, but the solution is [Message Carbons](http://xmpp.org/extensions/xep-0280.html). Conversations supports this, however your server apparently doesn't.
