### ISSUE TITLE
File transfer doesn't work when PGP is enabled

### ISSUE THREAD

**Issue by weiss** [siacs/Conversations#1577]
#1575 is about sending PGP-encrypted files to MUCs, but this also doesn't work for 1:1 chats.  With HTTP Upload, files are PGP-encrypted but not automatically decrypted.  With Jingle, the transfer somehow doesn't happen at all (I can have a closer look if that would help).

**Comment by Polynomdivison** [comment]
Same as:
#1555

**Comment by weiss** [comment]
Ah, thanks.  I'll close this one.
