### ISSUE TITLE
Crashed when sending crash reports

### ISSUE THREAD

**Issue by ccloli** [siacs/Conversations#1579]
When turned off "Never send crash reports" and chose "Send now", Conversations crashed. After that, each time I opened Conversations, it crashed when starting. 

So I spent the whole night to check what's wrong. lol. I use Helium to backup Conversation data, then unpack it. With SQLite Database Browser, I found the database "History" is strange. The last message is sent to `bugs@siacs.eu`, after deleting it, the database file size reduced significantly, from 8572 KB to 644 KB. That means the size of crash log is about 8 MB. 

Compared with the previous backup, I noticed that Conversations stores crash stack at `apps\eu.siacs.conversations\f\stacktrace.txt`, which is 8 MB too in old backup. By the way, after restoring old backup and choosing output crash stack to SD Card, it crashed again.

So here is my suggestion: Storing crash logs in SD Card (`mnt/sdcard/Android/data/eu.siacs.conversations`) instead of app data. So that users can send crash logs in another way, also avoid crashing when outputting crash logs to SD Card. Besides, crash logs is calculated as "Application Data" is also annoying. 
![20151121_163639png](https://cloud.githubusercontent.com/assets/8115912/11317592/63d7eb34-906e-11e5-85b0-28be77687954.jpg)

Crash log is also uploaded.

[stacktrace.txt](https://github.com/siacs/Conversations/files/40766/stacktrace.txt)

**Comment by philipflohr** [comment]
This is the strangest android crashdump I've ever seen. And also the biggest one;)

As it starts at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) and never mentions Conversations this is most likely not a problem of Conversations at all.
@ccloli can you provide more information about your phone (OS Version / custom rom /...) and write a setp-by-step guideline how to reproduce your problem?

**Comment by ccloli** [comment]
Screenshots of phone info are here:
[result-2015-11-26-20-16-23.png](https://cloud.githubusercontent.com/assets/8115912/11422938/1d39bd22-947b-11e5-843b-c942eaf62a9e.png)
[result-2015-11-26-20-17-43](https://cloud.githubusercontent.com/assets/8115912/11422956/4d5715ae-947b-11e5-9ce4-96fec2eb04d8.png)
Some tips are not mentioned:
1. My phone language is Simplified Chinese;
2. My phone's free storage size is less than 400 MB;
3. My previous Conversations version is 1.6.7 and installed from [coolapk](http://coolapk.com/apk/eu.siacs.conversations) (a Chinese app store), before that is 0.10 (maybe installed from F-Droid);
4. I installed current version (1.7.0) of Conversations from [F-Droid](https://f-droid.org/repository/browse/?fdid=eu.siacs.conversations) because my phone doesn't have Google Play Service;
5. I installed the latest version (1.7.2) from F-Droid before, but it crashed when opening, so I rolled back to 1.7.0;
6. Sometimes it crashes when scrolling too quick;
7. It usually crashes when receiving images (maybe lack of storage? I delete some files and it sometimes works fine, but before deleting the free space is larger than 200 MB);
8. Server is Openfire 3.10.3, JVM 1.8.0_40 Oracle Corporation -- Java HotSpot(TM) 64-Bit Server VM, Linux / amd64.

I don't know how to describe that how to reproduce, maybe install old version of Conversations, then turn on "Never send crash reports" and start using it? Maybe the crash logs are recorded from my first time to install, so it is very large. (As I mentioned, I backed-up Conversations data before I installed the latest version, and at that time the backup file is larger than 8 MB. The file uploaded at the first time is the log from the backed-up data. ) Then update to latest version, turn off "Never send crash reports", choose "Send now", and it crashes. 

BTW, I also backed up a new data when crashed every time, I found the file stacktrace.txt is 1 KB, not 8 MB, but the database is 8 MB. So I guess Conversations read and clear stacktrace.txt when reporting bug, then push data into the database, but the data is too large, so Conversations crashed every time.

Here is the stacktrace.txt of the second backup data.
[stacktrace (2).txt](https://github.com/siacs/Conversations/files/44962/stacktrace.2.txt)
