### ISSUE TITLE
README picture update?

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#1580]
It's happened a lot of time since these screenshots were taken, maybe a little update could be fine. I know that's silly, but it's just a little suggestion. 

Thank you very much for your effort!!

**Comment by alexara** [comment]
> It's happened a lot of time since these screenshots were taken, maybe a little update could be fine. I know that's silly, but it's just a little suggestion. 

Which screenshots? I cannot see any. Could you also describe your issue a little more, so it becomes clear what you are talking about?

**Comment by moshpirit** [comment]
Oh, I mean the screenshots of the aesthetic of Conversations. I'll put a link to the picture

**Comment by andersruneson** [comment]
The same with screens in play store.

Please help by taking some screens!

**Comment by moshpirit** [comment]
![This is the picture](https://raw.githubusercontent.com/siacs/Conversations/master/screenshots.png)
