### ISSUE TITLE
cannot join remote MUC via conversations while other clients work fine

### ISSUE THREAD

**Issue by dahabakuk** [siacs/Conversations#1583]
hi,

im using prosody 0.9 with the module block_strangers [1] which basically filters out messages from contacts which are not in my roster.
as soon as i unload the module, i can join remote MUCs just fine.
local muc rooms work without problem.

also other desktop clients like swift-im and gajim work without a problem with this module loaded.

any ideas why this is happening with conversations?

[1] http://hg.prosody.im/prosody-modules/file/0c3ba5ff7a3b/mod_block_strangers/mod_block_strangers.lua

br

**Comment by iNPUTmice** [comment]
Before joining a conference Conversations sends out an disco#info request to the conference. Looks like that module is blocking the answer and thus Conversations never joins the conference.

**Comment by iNPUTmice** [comment]
If you have further questions join our conference. This is not a Conversations issue but if you want i can help you to fix the prosody module
