### ISSUE TITLE
implement xep 0189 for kontalk compatibility

### ISSUE THREAD

**Issue by pravi** [siacs/Conversations#1584]
Kontalk developers say conversations should be able to fetch keys but it is not working https://github.com/kontalk/client-adapters/issues/8

**Comment by pravi** [comment]
@iNPUTmice does Conversations implement http://xmpp.org/extensions/xep-0189.html ?

**Comment by iNPUTmice** [comment]
>@iNPUTmice does Conversations implement http://xmpp.org/extensions/xep-0189.html ?

no. It uses XEP-0027

**Comment by pravi** [comment]
Ok, I just found out from here https://github.com/siacs/Conversations/blob/master/docs/XEPs.md  It is not yet implemented. Can this be implemented for kontalk compatibility? @iNPUTmice Would you be willing to mentor someone to implement it?

**Comment by sheetalsh456** [comment]
Hey, I am Sheetal S, currently doing my 2nd year Btech in Computer Science. I am interested to work on the implementation of xep 0189 or OMEMO for kontalk. I have prior experience in the basics of Android App Developemnt, and am developing tools for an open source software presently. I have also studied through kontalk and conversations and the need for their interoperability. I would be glad if i can be guided and mentored on how to go about this. 
Thank You.

**Comment by iNPUTmice** [comment]
Not on the TODO list right now. Compatibility with Kontalk could best be achieved by using OX on both sides.

**Comment by pravi** [comment]
Its is planned for kontalk 4.1 https://github.com/kontalk/androidclient/issues/633

**Comment by daniele-athome** [comment]
I second that. I'd rather support OX to benefit both of our projects.
