### ISSUE TITLE
Show online status in conversation list and in conversation

### ISSUE THREAD

**Issue by workoft** [siacs/Conversations#1585]
I really like the UI of conversations. But there is one thing that bothers me: Checking a persons online status is cumbersome.
If you are like me, you probably just keep a conversation open and enter them from the conversations list rather than from the rooster. I like that my conversations are sorted by last message and not by buddy's online status. But since people aren't necessarily online 24/7, I'd really like a way to quickly see my buddy's status. I don't want to check the roster (those tags are really messy by the way. Showing groups there is fine, but mixing groups with online status isn't a good idea imho), I want to see the status directly in both the conversation list (colour is enough) and in the conversation (maybe a bit more detailed. The way WhatsApp and Xabber do it is good, enriching the online status by a "last seen" entry. A status message may be good too).

A previous approach suggested a coloured bar next to the buddy icons in the roster to indicate online status. I find this approach very neat. It doesn't take up much space and it looks elegant. For group conversations the bar could be split up with each bit showing the status for each buddy, there could be a small bar next to each icon or the bar could just be left out. I also highly recommend you use this to show online status in the roster because I don't think that groups and online status should be mixed. Also, everyone has a status so there is no reason not to show it in the same place for every buddy.

**Comment by andersruneson** [comment]
You can enable showing presence status with the send button in the
conversation also.

Duplicate issue.

**Comment by workoft** [comment]
I didn't know about the send button status indicator. It's sufficient inside the conversation. What about showing the online status in the conversations list? And if it's a duplicate, where is the other bug? I did use the search.

**Comment by andersruneson** [comment]
You wrote a lengthy comment in the correct issue before posting a new issue
so you did find it. (If I remember correctly)

**Comment by workoft** [comment]
That issue was about showing the online status in the buddy list. It was never merged because the tag option was preferred. What I am talking about here is showing the online status in the chat list (and in the chats themselves, which has been fixed, as you pointed out).

**Comment by andersruneson** [comment]
It's been stated in several places, the chat, github readme and numerous
issues how the devs feel about online presence. I don't think you'll get
them to change their minds.

You could ask them instead if they are willing to merge such change if you
do them and do it well.
