### ISSUE TITLE
opt-out annoying notifications that server can't be found

### ISSUE THREAD

**Issue by bastlwasti** [siacs/Conversations#1589]
Hi there,

first, thanks for this great App. I am so far pretty happy, it has all the features I dreamed of. I therefore try to convince as many friends as possible to install this app and with my own xmpp server. In our use case, the most missing feature would be to opt out or by default not show the notifications that there was again a problem finding the xmpp server. 

Most friends I know just install conversations to do me a favour, and use whatsapp most of the time. so they just want a very simple to use app, and dont want to see any error messages if my xmpp server just doesn't work for a short period of time, or the mobile network which they use all the day just has some problems. 

Unfortunately the notifications asks the user to decide if they should "edit the settings" or "disable" the account. it would be better to have a button like "do nothing. Just wait until server is up again" or sth. like that. Often some users just push any button like "disable", and then afterwards, when my server is up again, they have no clue what they did, or how to reach the account settings... ;-) :-D

I think to be according to the design principles of "easy to use", it would be great to have some option in settings to disable those notifications, or just have to enable those warnings by default. 

ok, hope it got clear why this would be useful,
thanks a lot,

:)

**Comment by gjedeer** [comment]
I agree, similar to OP I convinced some people to use Conversations and this notification is confusing to them.

**Comment by singpolyma** [comment]
+1

**Comment by SafwatHalaby** [comment]
I think there should be an in-app notification, but not a notification in the Android drawer.

**Comment by iNPUTmice** [comment]
You should use a reliable server.

**Comment by singpolyma** [comment]
I'm not sure why these notifications are ever generated. The reconnect works fine.

@iNPUTmice the server is not likely to blame, but the cell internet

**Comment by QuentinC** [comment]
Hello,

I agree with this, sometimes (eg. when moving), there is a little time with the notification.
I don't think that there is a reason to keep it shown, Conversation should stay connecting, but maybe with an increasing delay ?

To my mind, the notification should be an option for developers and sys-admins only !

There is never such a notification in Facebook or Whatsapp...

Thanks !

**Comment by chpio** [comment]
i assume this feature is not planed yet?
@iNPUTmice  would you accept a pr which would add this feature?

**Comment by LogicParrot** [comment]
Please consider the fact that the server is likely not the problem, it's often the cell towers and it's a common occurence for many users.

It may still be a good idea to show a note in-app, but a notification which will go away soon anyways is simply annoying and unnecessary.

**Comment by bastlwasti** [comment]
^like whatsapp, telegram, wechat... do it too. - For good reason.
