### ISSUE TITLE
share original images, not low-res versions of it

### ISSUE THREAD

**Issue by bastlwasti** [siacs/Conversations#1590]
hello there,

When I add a photo to my conversation with the according menu, conversations creates an additional file in my photo album folder with a similar name, but smaller in size. Then it also creates a file with a random file-name in the conversations Picture folder, and transfers that to my xmpp server and stores it there via http-upload. Thus I got 3 different version of the single image file. Why those 2 additional files on my phone?

I like to share the original file, so I use "share file" instead of "share image". This works great, but is tedious if I want to share more than one "image". If I mark multiple images I cant "share file" them.... or in other words, if I share multiple files in my file manager, they are shared as images, not as files. :-(

Would be great if there were some setting, which influences the share behavoir, such that images are shared as files or not. 

thanks for your attention :)

**Comment by deoren** [comment]
+1

**Comment by iNPUTmice** [comment]
fixed in 4ab8fe13dea85e23f856bbe853fbf81af908edea
