### ISSUE TITLE
xmpp ejabberd online offline status issue when internet connection loss

### ISSUE THREAD

**Issue by nectarbits** [siacs/Conversations#1591]
I have ejabberd setup to be the xmpp server between mobile apps, ie. custom iPhone and Android app.But I've seemingly run into a limitation of the way ejabberd handles online status. Assume there are two users A & B friends to each other and having current live chat conversation. Suppose one of them loss his internet connection then there is no way to instantly update his status to server. So his status remains online. One solution to this problem is using mod_ping module in xmpp. But it's also have certain limitation, it will ping every clients after 32 seconds interval. So there is always 30 to 40 seconds delay in status update of user. I want to update any user's status instantly (less than 10 seconds) in good network condition like what's up. This is very first scenario of chat app everyone face and i hope someone will help me through this.

**Comment by andersruneson** [comment]
PLEASE stop.
I just got 6 mails from you. This is an issue tracker, not your help
service.
