### ISSUE TITLE
HTTP upload: Sends empty message

### ISSUE THREAD

**Issue by jkufner** [siacs/Conversations#1594]
When sending photo via HTTP upload from Conversations to ICQ or Facebook transport, only empty message is delivered. However, I can see the link in Gajim (via message carbons).

In XML console in Gajim, I can see that Conversations send HTML message with img tag, but Gajim sends just plain text URL. I guess the transports cannot handle HTML messages.

In some older version it worked fine and I could post photos from Conversations to Facebook chat (via transport) with no problem. Was there a change in format of sent messages?

**Comment by iNPUTmice** [comment]
Conversations sends both. Plain body and the xhtml-im tag.
