### ISSUE TITLE
Support XEP-0048 (Bookmarks) with PubSub storage

### ISSUE THREAD

**Issue by singpolyma** [siacs/Conversations#1596]
The XEP these days recommends pubsub storage instead of private xml storage.  Some clients (notably candy) only add to the PubSub storage and so these bookmarks do not show up in Conversations.

**Comment by Natureshadow** [comment]
Shouldn't Candy be fixed to use both if both are available?

If course Conversations should do so as well, yes.

Maybe an XMPP server should optionally make efforts to sync both ...

Hmm!

**Comment by iNPUTmice** [comment]
This work as of a couple of versions ago (if your server supports the conversion feature)
