### ISSUE TITLE
slack - direct messages from me show as other user in Conversations

### ISSUE THREAD

**Issue by bufke** [siacs/Conversations#1597]
1. Enable slack's xmpp
2. Open a Direct message with Joe user using the slack web interface
3. Send something
4. In Conversations the message that I wrote appears to be from Joe user. It will however say [my username] in the message which actually makes it worse since it triggers a notification.

It seems to happen every time for me.

**Comment by iNPUTmice** [comment]
Thats sounds a lot like slack is handling direct messages in a very weird way.

If you get me the stanza of such a message I can see if we can implement a work around.

**Comment by bufke** [comment]
From what I understand the slack xmpp support is horrible - but slack is very popular. Are there instructions somewhere for capturing the stanza?

**Comment by bufke** [comment]
Nvm I found the xmpp console for Pidgin. Ok.

```
<message from='slackbot@redacted.xmpp.slack.com' to='dburke@redacted.xmpp.slack.com/AmBPX1d2oV4=' type='chat' ts='1449181794.000007'>
	<body>[dburke] blarg</body>
	<html xmlns='http://jabber.org/protocol/xhtml-im'>
		<body xmlns='http://www.w3.org/1999/xhtml'>[dburke] blarg</body>
	</html>
</message>
```

Image showing that I said Blarg and not slackbot.
![screenshot from 2015-12-03 17-31-26](https://cloud.githubusercontent.com/assets/739307/11576317/bf7e2c68-99e3-11e5-945f-d9994845dfa6.png)

**Comment by iNPUTmice** [comment]
Yeah I don't know what to do about that. That message stanza doesn't even contain the information to whom that private message was sent to in the first place.

How does a stanza look like if you receive a message? I'm guessing it comes from the some sender jid but has a different name in the brackets?

**Comment by singpolyma** [comment]
This is a bug report for Slack.  They should be using carbons, but instead do this garbage.
