### ISSUE TITLE
{Feature Request} If conversations is domain locked, show add friend and muc without full jid.

### ISSUE THREAD

**Issue by Aluisyo** [siacs/Conversations#1598]
If conversations is domain locked it should only show username without domain e.g "suzyo@siacs.eu" should just be "suzyo" when domain lock is activated. this should apply when adding a friend, in the accounts section and also in conference section. with conference it should just be e.g "conversations" and not "conversations@siacs.eu" if domain is locked.

**Comment by philipflohr** [comment]
Can you explain what you mean with "domain lock"? Is there any XEP?

**Comment by iNPUTmice** [comment]
> Can you explain what you mean with "domain lock"? Is there any XEP?

https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/Config.java#L16

@Aluisyo the domain lock is a feature of the commercially available white label solution and usually only gets support if you purchase it. (see our website [conversations.im](http://conversations.im/#support))
