### ISSUE TITLE
letsencrypt.org cert

### ISSUE THREAD

**Issue by hschraep** [siacs/Conversations#1599]
Hi, is conversation accepting letsencrypt.org certs by default? Or does conversation use the internal CA certs of Android?

**Comment by jkufner** [comment]
Yes. Letsencrypt's certs are cross signed by IdenTrust which is widely accepted authority, so these certs work practically everywhere.

**Comment by hschraep** [comment]
Habe it test now but if i usw the cert from letsencrypt I get also the message that's the cert is not trusted by a known CA. And I have to choose once,abort or always. So it is the same as with a self signed cert. Installed OS is CyanogenMod 12.1 .

**Comment by jkufner** [comment]
My letsencrypt cert works just fine. Tested in Gajim and Psi on Debian and in Conversations.

**Comment by hschraep** [comment]
With conversations in witch Android verson form witch manufacturer have you tested?

**Comment by jkufner** [comment]
Samsung S4 mini (gt-i9195i, Android 4.4.4) and few Sony Xperia, both original and CyanogenMod (Android 4.1 and 4.4).

**Comment by hschraep** [comment]
And you get no message that the cert is not trusted? Can you have a look within the cm android at the configuration menu under security and then trusted CA certificates. Can you find there IdenTrust?

**Comment by jkufner** [comment]
Web browser says the cert is trusted. List of installed certs is too messy to find there anything.

**Comment by hschraep** [comment]
Yes within the browser my certs also trusted. I have tested this with Firefox 42 on android cm 12.1 and on Ubuntu Linux. I think this works because Firefox comes with there own CA certifications. But if I ad my account with the same cert within conversation I get a untrusted message and have the choose to add it once or forever. So I think conversation use not it own root CA's but this there come with Android and there I can't find IdenTrust. If this is so I wood open a request at CyanogenMod if the can add IdenTrust by default. Can any confirm this, if my thinking is right.

**Comment by d9h02f** [comment]
Just checked on a device running AOSP 5.1 and there is no IdenTrust to be found in the list of system certificates.

**Comment by jkufner** [comment]
The cross-signing certificate name is `Digital Signature Trust Co., DST Root CA X3` (as found in my Samsung S4 mini).

**Comment by BrianBlade** [comment]
@jkufner  is right: The letsencrypt `ISRG CA X1` intermediate is cross signed by `DST Root CA X3` *Digital Signature Trust Co.*, c.f. https://letsencrypt.org/certificates/ 
That anchor is available in CM 12.1 and apparently comes as system CA with Android since Gingerbread: https://community.letsencrypt.org/t/which-browsers-and-operating-systems-support-lets-encrypt/4394

To troubleshoot your problem:
 * Double check if you enabled the *Mistrust System CA* option in expert settings
 * Make sure your server sends all necessary intermediate certs. To check the trust chain your server actually delivers you could use: `openssl s_client -connect HOST.DOMAIN:PORT -showcerts -starttls xmpp`

**Comment by hschraep** [comment]
@BrianBlade thanks for the helpfully command. Figured out that something is wrong with that. So the problem was, that prosody has no configuration option for a chain.pem file. So you need to add the chain file at the end of the cert.pem file or you can use the fullchain.pem file. Last one is server cert + intermediates. And this i have to use instead of the cert.pem file. Now it works perfect. 

Many thaks @all now solved

**Comment by andersruneson** [comment]
Please close issue.
