### ISSUE TITLE
OMEMO not available

### ISSUE THREAD

**Issue by rudi59** [siacs/Conversations#1600]
I cannot choose the new OMEMO (writen in light gray) encryption on Conversations 1.7.3, OTR and OpenPGP is available (writen in black). Is there anything i could check, or to enable that OMEMO would work?

**Comment by iNPUTmice** [comment]
You and your contact both need a server with pep support. You can check
this in account details if you select server info from the menu.

**Comment by rudi59** [comment]
Oh, ok - i have tested it with an Desktop Client and Conversations. Conversations to Conversations works fine. Thank You!

**Comment by licaon-kter** [comment]
Close this then.
