### ISSUE TITLE
Discussion: Gateway Create Contact

### ISSUE THREAD

**Issue by singpolyma** [siacs/Conversations#1601]
Related to https://github.com/siacs/Conversations/issues/913 I'd like to implement UI for adding a contact through a gateway that is already on the user's roster.  I just want to run my initial UI idea by you all before I start implementing anything.  My proposal is that when a gateway is present in the roster of the account selected (using "Your account" dropdown in the "create contact" dialog) that the dialog change to this (if, say, it were an sms-type gateway):

![g4](https://cloud.githubusercontent.com/assets/12770/11641636/4e9aa82e-9d07-11e5-97e6-612a16cc4929.png)

and then selecting the "SMS" tab reveals:

![raster-404111](https://cloud.githubusercontent.com/assets/12770/11641649/5f9ba0c4-9d07-11e5-8f26-5d4991d42133.png)

**Comment by iNPUTmice** [comment]
So selecting the 'sms' checkbox / tab would basically just add
@sms-gateway.yourserver.tld to the number you've entered? how is this
saving time compared to selecting @sms-gateway from the auto suggestions?

**Comment by singpolyma** [comment]
I would use jabbe:iq:gateway protocol to generate the JID, which will often do sanitization, etc, that the local UI could not do for itself.

**Comment by msva** [comment]
and what if there are tons of transports in user's roster? Create buttons for all of them? :)

**Comment by singpolyma** [comment]
@msva is having such a large number common? What do you think should happen? :)

**Comment by iNPUTmice** [comment]
See my comment in the related PR.
