### ISSUE TITLE
Custome Hostname and Server Configiration

### ISSUE THREAD

**Issue by YogeshwarSharma** [siacs/Conversations#1604]
Where to specify custom hostname,post or Server info.

**Comment by andersruneson** [comment]
https://github.com/siacs/Conversations/blob/master/README.md#where-can-i-set-up-a-custom-hostname--port

Please close issue. Thx.

**Comment by jkufner** [comment]
In DNS records of your server - see http://wiki.xmpp.org/web/SRV_Records.

**Comment by YogeshwarSharma** [comment]
I mean, in which class i have to place custom hostname and own server info in Conversation package for android.

**Comment by andersruneson** [comment]
This is not a support channel for development of you're own fork.
Please join the muc if you have questions.
