### ISSUE TITLE
Only the first of multiple links is opened in a merged message

### ISSUE THREAD

**Issue by philipflohr** [siacs/Conversations#1606]
Scenario: the receiver uses Conversations
Steps to reproduce:

1. Send a link to a Conversations user
2. Send another link
--> Conversations combines the two messages

3. click the first link
--> works as expected
4. click the second link
--> the first link is opened again

**Comment by Natureshadow** [comment]
I reported that a while ago but it was closed as invalid, because it was thought to be an Android issue.

But it isn't - other apps do not show this behaviour.

Maybe the devs agree this time.

**Comment by iNPUTmice** [comment]
If you put two different links into a TextView (seperated by a space or a line break) the second link wont be clickable. You can test this behaviour completely independent of Conversations. If other Apps don't show this behaviour they have modified the linkify code. If one of these apps is Open Source @Natureshadow we can probably use their linkify.

**Comment by petmue** [comment]
@iNPUTmice These solutions sound sufficient: 
http://stackoverflow.com/a/28720364
http://stackoverflow.com/a/30365618

You may also have a look at
https://github.com/vortexwolf/2ch-Browser/blob/79da45711dc2fb07a794ed0e0d47f619fb77ad09/src/com/vortexwolf/dvach/common/controls/ClickableLinksTextView.java

Here's probably the reason explained why the android bug occurs and how it can be resolved without modyfing the Linkify code:
http://stackoverflow.com/a/15192570

**Comment by iNPUTmice** [comment]
@petmue unfortunately neither of these resources work or have anything to do with the bug at hand. The all deal with either autoMask=0 (not the case for us) or selectabletext=false (not the case for us)

However I admit that this bug is really annoying and maybe we should make the text none selectable since we have an alternative way of selecting the text.

**Comment by singpolyma** [comment]
Does https://github.com/vortexwolf/2ch-Browser/blob/79da45711dc2fb07a794ed0e0d47f619fb77ad09/src/com/vortexwolf/dvach/common/controls/ClickableLinksTextView.java not work?

**Comment by iNPUTmice** [comment]
Not for me. If you read the code it checks if autolinkmask is 0 which is
not the case for us. But feel free to try it yourself.

**Comment by singpolyma** [comment]
do we need it to be nonzero?
