### ISSUE TITLE
Feature: Delete Sent Message and Self Distraction Message  on recipient end 

### ISSUE THREAD

**Issue by chathudan** [siacs/Conversations#1608]
Would like to have feature like Delete Sent Message  and Self Distraction message on recipient end , then the sender can delete messages from recipient end .

**Comment by licaon-kter** [comment]
Destruction :)

That might work if they both use Conversations only, not sure if there's a XEP for this though.

**Comment by chathudan** [comment]
yes there is no XEP, this will work if they both use Conversations only.but Conversation can introduce new XEP. 
ex : 
Burn message in 30 seconds 
      ```<message to='chathura@trackme.lk' from='abs@trackme.lk' id='message22' type='chat'>
            <body>Art thou not Romeo, and a Montague?</body>
            <burn>30 </burn>
       </message>```


Burn sent message, I this won't effect to other chat clients since  message type is burn
    ```xml
<message to='chathura@trackme.lk' from='abs@trackme.lk' id='message22' type='burn'>
            <burn>
               <id>eu67-tr456-455</id>
               <time>1</time>
            </burn>
       </message>```

**Comment by d9h02f** [comment]
- the recipient can take a screenshot
- the messages are saved in cache
- the messages are saved on the server(s) involved

**Comment by licaon-kter** [comment]
The recipient can run a custom Conversations build that does not actually respect the burn timer.
