### ISSUE TITLE
Cannot send file/picture. Delivery failed.

### ISSUE THREAD

**Issue by aplicret** [siacs/Conversations#1609]
The android chat app works fine except file transfer. I am always getting 'delivery failed' message while sending any file or image. What's wrong? Help needed.

**Comment by philipflohr** [comment]
This can have several reasons...
1. Your server supports http-upload, but the file you're sending is too big
2. Your server does not support http-upload and there is no direct connection between the sending and the receiving device. - and your server does not offer a file sending proxy
3.......

Please provide a logfile for more valuable information;)
