### ISSUE TITLE
http upload fails sporadically

### ISSUE THREAD

**Issue by pasdVn** [siacs/Conversations#1612]
I discovered a problem using conversations 1.8.1 (from f-droid) and the http file-upload:

When sending a file the http-upload seems to fail sporadically. Here is a log of a working file-upload
```
12-23 19:22:19.836 D/conversations( 9795): get original path for uri: content://media/external/images/media/6900
12-23 19:22:19.890 D/conversations( 9795): reading bitmap with sample size 1
12-23 19:22:20.183 D/conversations( 9795): send file message
12-23 19:22:20.281 D/conversations( 9795): uploading to https://jabber.de:5281/upload/****.jpg
12-23 19:22:21.535 D/conversations( 9795): finished uploading file
```
In this case the client receives a message with the http-link, etc.

Sometimes the log of an http-upload ends looks like this
```
12-23 18:26:10.558 D/conversations( 9795): get original path for uri: content://media/external/images/media/10591
12-23 18:26:10.648 D/conversations( 9795): reading bitmap with sample size 1
12-23 18:26:11.261 D/conversations( 9795): send file message
12-23 18:26:11.347 D/conversations( 9795): uploading to https://jabber.de:5281/upload/****.jpg
# nothing more her -> upload seems to fail
```
In this case not mesage is send to the receipient. Additionally, the file really is not present on the server (pasting the link from the log into a browser gives a 404 http-error). The sender client does not mark this file upload as "failed" or unsucessfull. It is shown as 100% uploaded.
 
Firstly I thought, this is only related to files that are uploaded very fast (small files), but that does not seem to be the whole truth. Anyways I can reproduce this beviour always, i if i take a picture with the front-camera of my galaxysmtd out of conversations, which produces 25kB-Files.

This could also be a server bug, but i am not sure about that. Even if this is the case (i try to invetigated that further) there anyway should be a better reporting in conversations about the failed http-upload:
 - an appropriate error message in the android log
 - also a note in the UI for the user, that the upload did not succeed

My "test environment":
- conversations 1.8.1 on different android devices and versions
- jabber.de - runs prosody, as i think
- pidigin as receiving client to get a closer look on xmpp stanzas

Probably this issue is not related to the 1.8.1 version, but the guys from jabber.de obviously added the http-upload-module in the last days.

**Comment by pasdVn** [comment]
I debugged this issue:

Obviously the reponse from the server to the http-put is missing. Conversations "hangs" at [connection.getResponseCode()] (https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/http/HttpUploadConnection.java#L192). For some reason i only manged to reproduces this bug at an galaxysmtd running cm10.2.1 (android 4.3.1).

After 30min an IOException is thrown and i get
```
* D/conversations(13817): http upload failed null
```
and the upload is shown as "failed" in the UI. So I guess this is really a server problem. 
Is there any easy way to do some sniffing on http level in conversations/android (ssl decrypted)?

I also noticed, that there is a difference in the ui between "100% uploaded, but not yet fully done" and "fully done" in the UI, so my suggestion above is not correct...

**Comment by daradib** [comment]
I think I'm having the same problem. Same logcat messages, stuck on 100% uploaded, but not actually uploaded. I'm using Conversations 1.8.2 (F-Droid) on Nexus 6P running Android 6.0.1.

On the server side I'm running Prosody 0.10 with mod_http_upload. In the server debug logs I only see SSL handshake messages (5281 is the Prosody web server port):

    Dec 30 22:05:45 c2s1a20820      debug   Handled 17 incoming stanzas
    Dec 30 22:05:45 c2s1a20820      debug   Received[c2s]: <iq id='qqoosc1alm' type='get' to='<mydomain>' from='<myjid>/phone'>
    Dec 30 22:05:45 c2s1a20820      debug   #queue = 7
    Dec 30 22:05:45 c2s1a20820      debug   Received[c2s]: <a xmlns='urn:xmpp:sm:3' h='29'>
    Dec 30 22:05:45 c2s1a20820      debug   #queue = 0
    Dec 30 22:05:45 socket  debug   accepted incoming client connection from: <myip> 40887 to 5281 
    Dec 30 22:05:45 socket  debug   starting handshake... 
    Dec 30 22:05:45 socket  debug   ssl handshake of client with id:table: 0x1fed730, attempt:1 
    Dec 30 22:05:46 socket  debug   ssl handshake of client with id:table: 0x1fed730, attempt:2 
    Dec 30 22:05:46 socket  debug   ssl handshake done
    # nothing more, no http/http_upload messages

**Comment by pasdVn** [comment]
I also discoverd this bug with a Nexus 5 running android 6.0.1 in the meantime...

I set up a local prosody server, but I am not abled to reproduce this problem here. I tried prosody 0.9.8 (that is also used by jabber.de) and the current HEAD of prosody'S trunk as well (btw: with "0.10" you mean "trunk"!?).

I also did some sniffing with wireshark, which is a bit of guessing - of course - because of the ssl-encrpytion, but following the TCP-stream I can see/guess that the server response is really missing after the "big blop" from the client.
Maybe  the server is indeed expecting more content that in fact is transferred by the client (http content-lengt). At least i can observe an identical behaviour (logs, etc.) if i modify the prosody code manually (increase expected content length in net/http/server.lua).

@daradib Can you do some debugging in your enviroment?

**Comment by SamWhited** [comment]
> btw: with "0.10" you mean "trunk"!?

Not sure what was meant, but it's worth noting that 0.10 and trunk are two different branches. It's important to be specific and not confuse the two here.

**Comment by pasdVn** [comment]
> Not sure what was meant, but it's worth noting that 0.10 and trunk are two different branches. It's important to be specific and not confuse the two here.

Thank you for the hint! I just looked at the tags, not at the branches and was confused. Nevertheless I cant't reproduce this bug here with the 0.10 branch :-(

**Comment by daradib** [comment]
I am using prosody-0.10 installed from the prosody APT repository. I've removed http upload module for now. I will try to test again soon (in a week or two), hopefully disabling ephemeral ciphers to decrypt with wireshark.

**Comment by pasdVn** [comment]
FYI: I can reproduce the problem in my local environment now. It is only occurring when "use_libevent = true" is configured in prosody.
-> This seems to be definitely a prosody problem. I will report this issue there.

**Comment by pasdVn** [comment]
See https://prosody.im/issues/issue/583 (issue resolved)

**Comment by daradib** [comment]
@pasdVn nice work and thanks for finding out a workaround.
