### ISSUE TITLE
Images via http links are not downloadable 

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1614]
I've noticed that Conversations 1.8.2 sometimes doesn't download images and only shows the http image link. Long touching and choose download image doesn't load the image but opens the link in the browser. Any ideas?

**Comment by iNPUTmice** [comment]
Please provide logcat output for this

**Comment by SamWhited** [comment]
I'm also experiencing this behavior; absolutely nothing in the ADB logs of any significance.

In my case, it's actually when I remove my finger that the web browser is launched. The contextual menu appears, but then as soon as I move my finger to go press download the browser intent is launched.

I stepped through the relavant code with a debugger, but didn't see anything immediately obvious. I suspect it's actually an Android issue (though admittedly, I didn't look for very long).

**Comment by andersruneson** [comment]
Happened to me as well, exactly as Sam describes it.

**Comment by kriztan** [comment]
Does be91c0741f5e6d28124981380fbff9d687f0edf2 fix this issue too?
