### ISSUE TITLE
Can no longer select text in a message

### ISSUE THREAD

**Issue by singpolyma** [siacs/Conversations#1615]
Double-tap used to let me select text in a message, but it doesn't seem to work since my last update.

**Comment by iNPUTmice** [comment]
Yes. That's expected behavior. Use long press and copy text.

**Comment by singpolyma** [comment]
That only lets me copy whole messages. So now I have to paste into a text editor in order to select text...

**Comment by licaon-kter** [comment]
It's this: https://github.com/siacs/Conversations/issues/1606

**Comment by SamWhited** [comment]
I have not read the older discussion, but when you have somone send several long messages within the merge window, it gets really annoying when you want to copy the phone number, address, etc. they sent you into a text field and you have to paste the whole message instead (especially when the field is a single line one such as the address bar in your favorite web browser).

It's a small thing seemingly, but I suspect this has a pretty big impact on user experience (though I'm guessing, I have no idea how common copy/paste actually is).

**Comment by andersruneson** [comment]
In Hangouts chat it's only possible copying the whole message, I've seen
this as a pro for Conversations with the same reason Sam mentions.

On 26 Dec 2015 8:55 a.m., "Sam Whited" <notifications@github.com> wrote:
>
> I have not read the older discussion, but when you have somone send
several long messages within the merge window, it gets really annoying when
you want to copy the phone number, address, etc. they sent you into a text
field and you have to paste the whole message instead (especially when the
field is a single line one such as the address bar in your favorite web
browser).
>
> It's a small thing seemingly, but I suspect this has a pretty big impact
on user experience (though I'm guessing, I have no idea how common
copy/paste actually is).

**Comment by petmue** [comment]
> It's a small thing seemingly, but I suspect this has a pretty big impact on user experience (though I'm guessing, I have no idea how common copy/paste actually is).

From my friends' and my own point of view it's a big impact, and we wish the feature back to select and copy only a part of a message for the same reason Sam stated.

**Comment by iNPUTmice** [comment]
Well android is broken. We can only have either click able links or
selectable text.

**Comment by singpolyma** [comment]
What if, in addition to "copy text" on long press there was also the option to "select text", which would disable the links in that textview and make it selectable and select all the text. Then the user can modify the text selection as they prefer and copy only whatever part of the message, but normally links will work.

**Comment by iNPUTmice** [comment]
I'm not sure that the text selection mode can be triggered
programmatically. A quick Google search didn't yield anything

**Comment by SamWhited** [comment]
> Well android is broken. We can only have either click able links or selectable text.

Ah, typical. Personally I'd say the two-link sissue is way less annoying thatn the lack of selectable text, but I have no idea if that's a normal use case or not.

Maybe it would be a good idea to build in some opt-in analytics to get data for these sorts of decisions.

**Comment by andersruneson** [comment]
I guess there is also the option to not merge messages?
