### ISSUE TITLE
File transfers were sometimes received as link

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1617]
Currently I've noticed that file transfers via HTTP Upload were sometimes received as link instead of button or embedded image. I've reported this also in #1614. The ADB logcat doesn't show any interesting things. 
I've noticed that behaviour in Conversations 1.8.2 and also with 1.8.3 in regions with slow network connections. Sometimes messeges were received via mam and files are also shown as links.

**Comment by iNPUTmice** [comment]
fixed in 09d87965fbd77d5c3e463a168c56e4c9bac9fc2e
