### ISSUE TITLE
jolla : application can't start

### ISSUE THREAD

**Issue by vbelloir** [siacs/Conversations#1619]
Hi all,
I'm trying to use Conversations on a Jolla device, as this apps if officially in the Jolla Store.
I installed the app via the jolla store (version 1.8.1), or via f-droid (version 1.8.2). With both stores, I can't start the app. The login screen appears, and just after, I get the message "Unfortunately, Conversations has stopped."

What can I do?
Thanks for your job.
Vincent

**Comment by iNPUTmice** [comment]
According to the comments in the jolla store you have to allow android apps to access your contacts.

**Comment by vbelloir** [comment]
OK, I works. Thanks a lot.
