### ISSUE TITLE
Application won't start on Android M

### ISSUE THREAD

**Issue by SphinxC0re** [siacs/Conversations#1620]
The application seems to freeze on startup.

Android 6.0.1

**Comment by andersruneson** [comment]
As Conversations works well for most of us on 6.0.1 you'll have to provide
some debug logs:
https://github.com/siacs/Conversations/blob/master/README.md#how-do-i-debug-conversations
Thanks

**Comment by iNPUTmice** [comment]
Can reproduce. Sorry

**Comment by SphinxC0re** [comment]
Yeah, seems like it has been fixed. Nice work!
