### ISSUE TITLE
support XEP-0030 (XMPP service discovery)

### ISSUE THREAD

**Issue by rigid** [siacs/Conversations#1622]
i'm not sure which XEP that would be, but it would be awesome :)

**Comment by licaon-kter** [comment]
https://github.com/siacs/Conversations#how-do-i-create-an-account ?

**Comment by rigid** [comment]
ok, i looked it up. I mean http://xmpp.org/extensions/xep-0030.html

**Comment by iNPUTmice** [comment]
Conversations automatically looks up services it knows how to talk to. Like MUC servers or HTTP Upload components.

Please describe your use case for a general service discovery.

**Comment by rigid** [comment]
on pidgin i use the XMPP service discovery plugin to register with jabber transports. (irc, facebook, etc)  I'm prompted with a login/password form to register once. After that, the transport adds contacts to my roster, provides MUCs etc.

**Comment by iNPUTmice** [comment]
duplicate of #913
