### ISSUE TITLE
Connection settings for new Account are missing

### ISSUE THREAD

**Issue by lphooge** [siacs/Conversations#1623]
And that is simply terrible.
Yes, a custom hostname does break federation*, a SRV record would be better.

But thats not the point, as the user (not the administrator!) I do not have control over that.
Please do not assume everybody just uses their own one-man-single-account servers - which is unfortunatly mostly still the case for jabber, but surely not what everybody aims for.

I am aware there are already issues about this, I would post there if I could.

The alternative to posting this here would have been downvoting the app in the play store.

* Use case: Internal corporate server, federation is not even wanted.

**Comment by licaon-kter** [comment]
https://github.com/siacs/Conversations#where-can-i-set-up-a-custom-hostname--port !

/mark as wontfix ?

**Comment by iNPUTmice** [comment]
> The alternative to posting this here would have been downvoting the app in the play store.

Or you can request a refund.
