### ISSUE TITLE
Auto-activate OMEMO encryption, auto-accept OMEMO keys

### ISSUE THREAD

**Issue by zzottel** [siacs/Conversations#1626]
1) If OMEMO encryption is available for all resources of the contact, automatically activate it. I don't see how this could lead to problems, and it would be one step less to tell non-computer-savy persons to take.

2) Auto-accept all contacts' OMEMO keys by default. Correct me if I'm wrong, but as far as I understood the matter, an attacker would need the Jabber account credentials to be able to inject another resource with its own OMEMO key. This is relevant for people who fear to be actually targeted by secret services, but not for normal casual chat. So to make encryption easy for normal folks, all keys should be accepted by default without user interaction. In order to keep Conversations usable for more paranoid users, this should, of course, be made an option that can be disabled.

**Comment by zzottel** [comment]
If this is possible within the proposed XEP (can that still be changed?), maybe a good idea would be to allow a decision if my keys should be auto-accepted. I.e.: Ideally, there should be an option to auto-accept all keys locally (default on), and an option to allow my own keys to be auto-accepted by my contacts (also default on). If the latter is set to false, all my contacts will be asked to accept a new key regardless of their local setting to auto-accept keys or not.

**Comment by strb** [comment]
Regarding 1) This can and will lead to problems where not all clients support OMEMO. If we were to implement this change, we would effectively cause vendor lock-in for Conversations users, rendering them unable to send messages to their contacts' desktop clients if they have a Conversations device. Such a change might make sense at some point down the road, when there are reasonable adoption rates across the main clients, but at the moment, this is just going to confuse people.

Regarding 2) An attacker could also have compromised the server. Or the server administrators could be malicious. If all you're worried about is outside passive eavesdroppers, you don't really need end-to-end encryption anyway, as nowadays messages are pretty much always encrypted in transport via TLS. Auto-accept would have grave consequences, as it's completely transparent to the user. You wouldn't even notice that you've been compromised. It's really not that hard to press accept. If you don't care that much, you don't actually have to verify the fingerprint. And you only need to do it once. It's not that big of a deal.

**Comment by Natureshadow** [comment]
strb, read the very first sentence of the original post again, please...

**Comment by andersruneson** [comment]
Let me know how to know that clients connected in the future supports
omemo, like in 2 weeks or in 2 minutes. They might want the backlog from
mam.

**Comment by strb** [comment]
What @andersruneson said. Plus, even for the ressources that are online at any given moment, it's literally impossible to discover whether they support OMEMO.
