### ISSUE TITLE
PEP-Detection not working properly

### ISSUE THREAD

**Issue by improti** [siacs/Conversations#1628]
I read about OMEMO and want to use it instead of OTR with counterparts using Conversations too. Using my account on my own server (ejabberd) I successfully switch to using OMEMO with one contact (which is using an account on a different server). So I wanted to do the same with several other accounts that are running on the my server (as my own account is, that I'm using with OMEMO as mentioned above). However I only get an error that there is no key available.

To test I added a new account for testing - same problem. Now even if I create two new accounts on my server and try to activate OMEMO between those, the same error comes up. As this happens with newly created accounts, this probably is not about deleting a key?

I couldn't find detailed documentation on OMEMO and how it is supposed to work. Issue #1369 deals with the question of regenerating keys and advises that removing a contact and readding it should solve the problem by regenerating keys. I tried that but still get the same error. So somethings going wrong here, but what?

I now enabled adb debugging and looked at logcat, where I always seem to get this sequence:
```
D/conversations(15345): AxolotlService (id1@myserver.net): Finding devices without session for id2@myserver.net
D/conversations(15345): AxolotlService (id1@myserver.net): Found device id1@myserver.net:1943754004
D/conversations(15345): AxolotlService (id1@myserver.net): skipping over id2@myserver.net:1943754004 because it's broken
```

I noticed how for id1 a device is found and returned with this ID number. The "skipping over" then appears for id2 with the ID number returned for id1. Is this how it is supposed to be?

This is using 1.8.2 installed from F-Droid with some differences in the clients (one is a Samsung device with the original installation of Android including all the Samsung and Google stuff, one is on Cyanogen without any Google Services.

I'm completely lost here by now. No option to fix, the known workaround is not working and no clue what to try next. Any help appreciated.

**Comment by strb** [comment]
First of all, just to clear this up. You would need to delete your **account** from conversations, not a contact. This triggers key regeneration because removing an account pretty much clears all data associated with that account from the database (including the key), so when it is added again later on, a new key is generated.

From your description it sounds like you weren't able to establish OMEMO sessions with *any* contacts on your own server, correct? Are you sure that you have ```mod_pep``` enabled? Also, what is your ejabberd version? There are some ancient versions where PEP is just completely broken.

Now as for your problem, it would be very helpful to get the logcat output from immediately after Conversations is started. The reason for this is that after fetching a key failed with an error for the first time, it is not retried until the app is stopped/killed at some point. (This might sound stupid but there are good reasons for this that I can't go into right now, and we will revisit this logic to refine it at some point.) As a consequence, the actual error will only get printed out to the log the first time this is tried, which is generally on the first connect after the app is started.

So to get those logs, hook up logcat, then swipe the app out of the recent apps list (this kills it), and then start it manually. There should be a logline that looks like one of the following:
 * preKey IQ packet invalid: [...]
 * Error building session for [...]
 * Error received while building session: [...]

If you could give me those I can help you fix this.

**Comment by improti** [comment]
> First of all, just to clear this up. You would need to delete your account from conversations, not a contact. This triggers key regeneration because removing an account pretty much clears all data associated with that account from the database (including the key), so when it is added again later on, a new key is generated.

Thx for making this clear. I will try this later but first want to see if we can find out what went wrong.

> From your description it sounds like you weren't able to establish OMEMO sessions with any contacts on your own server, correct? Are you sure that you have mod_pep enabled? Also, what is your ejabberd version? There are some ancient versions where PEP is just completely broken.

That is correct but OMEMO is working with a contact that is not on the same server. And I'm not sure about enabled PEP, but the "Server Info" of Conversations tells me so. In the config I found PEP as this:
```
  {mod_pubsub,   [ % requires mod_caps
                  {access_createnode, pubsub_createnode},
                  {pep_sendlast_offline, false},
                  {last_item_cache, false},
                  %%{plugins, ["default", "pep"]}
                  {plugins, ["flat", "hometree", "pep"]}  % pep requires mod_caps
```
Version is 2.0.1 (Ubuntu Package). I already noticed I'd need something newer for the shared history goodies and alike. Is there any good guide on setting up a server capable of all the things Conversation supports?

I'll get back to this with some logcat later ...

**Comment by improti** [comment]
Damn, I completely forgot to thank you for your time and effort. That was a good explanation in addition to the guidance on what to look for. Awesome!

I did as you advised and am looking at the logcat output. I'm unsure what parts should better be kept confidential, so I'm not going to post the whole thing here. In what I post I have changed IDs, addresses etc., so do not rely on any of those (always did "replace all" though, so that any links between those should be intact).

After starting Conversations I get:
```
01-02 17:39:09.132 D/conversations(30212): restoring roster
01-02 17:39:09.157 D/conversations(30212): update unread count to 0
01-02 17:39:09.173 D/conversations(30212): main@ownserver.net: connecting
01-02 17:39:09.186 D/conversations(30212): main@ownserver.net: connect to ownserver.net via TOR
01-02 17:39:09.201 D/conversations(30212): AxolotlService (main@ownserver.net): Got Axolotl signed prekey record:1
```
... followed by 67 more lines (the record increases by one each line). Then comes:
```
01-02 17:39:09.212 D/conversations(30212): AxolotlService (main@ownserver.net): Building session for remote address: workingomemo@otherserver.net:1569018258
01-02 17:39:09.229 D/conversations(30212): app switched into foreground
01-02 17:39:09.231 D/conversations(30212): restoring messages
01-02 17:39:09.369 D/conversations(30212): restored all messages
01-02 17:39:09.544 D/conversations(30212): start merging phone contacts with roster
01-02 17:39:09.545 D/conversations(30212): finished merging phone contacts
01-02 17:39:10.630 D/conversations(30212): main@ownserver.net: TLS connection established
01-02 17:39:10.920 D/conversations(30212): main@ownserver.net/mobile: Authenticating with SCRAM-SHA-1
01-02 17:39:11.513 D/conversations(30212): main@ownserver.net: logged in
01-02 17:39:12.030 D/conversations(30212): main@ownserver.net: starting service discovery
01-02 17:39:12.577 D/conversations(30212): main@ownserver.net: server name: ejabberd
01-02 17:39:13.052 D/conversations(30212): main@ownserver.net: done with service discovery
01-02 17:39:13.052 D/conversations(30212): main@ownserver.net: online with resource mobile
01-02 17:39:13.103 D/conversations(30212): main@ownserver.net: fetching roster
01-02 17:39:13.124 D/conversations(30212): AxolotlService : Couldn't find <item> in bundle IQ packet: <iq to="main@ownserver.net/mobile" from="main@ownserver.net" xmlns="jabber:client" type="result" id="at4let912f"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="eu.siacs.conversations.axolotl.bundles:1234567890" xmlns="http://jabber.org/protocol/pubsub"/></pubsub></iq>
01-02 17:39:13.124 W/conversations(30212): AxolotlService (main@ownserver.net): Received invalid bundle:<iq to="main@ownserver.net/mobile" from="main@ownserver.net" xmlns="jabber:client" type="result" id="at4let912f"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="eu.siacs.conversations.axolotl.bundles:1234567890" xmlns="http://jabber.org/protocol/pubsub"/></pubsub></iq>
01-02 17:39:13.125 W/conversations(30212): AxolotlService (main@ownserver.net): Received invalid prekeys:<iq to="main@ownserver.net/mobile" from="main@ownserver.net" xmlns="jabber:client" type="result" id="at4let912f"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="eu.siacs.conversations.axolotl.bundles:1234567890" xmlns="http://jabber.org/protocol/pubsub"/></pubsub></iq>
01-02 17:39:13.127 I/conversations(30212): AxolotlService (main@ownserver.net): Adding own IdentityKey org.whispersystems.libaxolotl.IdentityKey@123abc01 to PEP.
01-02 17:39:13.134 I/conversations(30212): AxolotlService (main@ownserver.net): Adding new signedPreKey with ID 69 to PEP.
01-02 17:39:15.896 I/conversations(30212): AxolotlService (main@ownserver.net): Adding 100 new preKeys to PEP.
01-02 17:39:15.905 D/conversations(30212): AxolotlService (main@ownserver.net): : Bundle 1234567890 in PEP not current. Publishing: <iq type="set"><pubsub xmlns="http://jabber.org/protocol/pubsub"><publish node="eu.siacs.conversations.axolotl.bundles:1234567890"><item><bundle xmlns="eu.siacs.conversations.axolotl"><signedPreKeyPublic signedPreKeyId="69">
```
Here I cut out many lines with keys and signatures, seems like the "what is going to be published". At the end of the key-list strange things seem to appear. After many lines with keys the last one was incomplete like this:
```
01-02 17:39:15.905 D/conversations(30212): </preKeyPublic><preKeyPublic preKeyId="7213">Bs8FITiCsRnS3k7nO/G9abl027kKsEp2ch3iIoIRATcq
01-02 17:39:15.905 D/conversations(30212): </preKeyPublic><preKeyP
01-02 17:39:16.010 D/conversations(30212): AxolotlService (main@ownserver.net): Received PEP device list update from main@ownserver.net, processing...
01-02 17:39:16.010 D/conversations(30212): AxolotlService (main@ownserver.net): Own device 1234567890 not in PEP devicelist.
01-02 17:39:16.010 W/conversations(30212): AxolotlService (main@ownserver.net): Own device list empty, attempting to publish (try 1)
01-02 17:39:16.020 D/conversations(30212): AxolotlService (main@ownserver.net): Received PEP device list update from main@ownserver.net, processing...
01-02 17:39:16.020 D/conversations(30212): AxolotlService (main@ownserver.net): Own device 1234567890 not in PEP devicelist.
01-02 17:39:16.020 W/conversations(30212): AxolotlService (main@ownserver.net): Own device list empty, attempting to publish (try 2)
01-02 17:39:17.161 D/conversations(30212): AxolotlService (main@ownserver.net): Received PEP device list update from workingomemo@otherserver.net, processing...
01-02 17:39:20.392 D/conversations(30212): AxolotlService (main@ownserver.net): Successfully published bundle. 
01-02 17:39:20.392 D/conversations(30212): AxolotlService (main@ownserver.net): Announcing device 1234567890
01-02 17:39:20.458 D/conversations(30212): AxolotlService (main@ownserver.net): Received PEP device list update from main@ownserver.net, processing...
01-02 17:39:20.459 D/conversations(30212): AxolotlService (main@ownserver.net): Received non-empty own device list. Resetting publish attemps and pepBroken status.
01-02 17:39:20.489 D/conversations(30212): AxolotlService (main@ownserver.net): Received PEP device list update from main@ownserver.net, processing...
01-02 17:39:20.489 D/conversations(30212): AxolotlService (main@ownserver.net): Received non-empty own device list. Resetting publish attemps and pepBroken status.
01-02 17:39:22.583 D/conversations(30212): AxolotlService (main@ownserver.net): Own device 1234567890 not in PEP devicelist.
01-02 17:39:22.583 W/conversations(30212): AxolotlService (main@ownserver.net): Own device list empty, attempting to publish (try 1)
01-02 17:39:23.821 D/conversations(30212): main@ownserver.net: error executing mam: <iq to="main@ownserver.net/mobile" from="conversations@conference.siacs.eu" xmlns="jabber:client" type="error" id="1ina1lc5vw"><error xmlns="jabber:client" type="cancel"><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>
01-02 17:39:23.895 D/conversations(30212): AxolotlService (main@ownserver.net): Received PEP device list update from main@ownserver.net, processing...
01-02 17:39:23.895 D/conversations(30212): AxolotlService (main@ownserver.net): Received non-empty own device list. Resetting publish attemps and pepBroken status.
```
Can you make sense out of this? Hope I included all relevant parts intact enough. The puzzling thing for me still is that it seems to work if one of the involved accounts is on an external server, but not if both are on my own server. Any further help welcome.

**Comment by andersruneson** [comment]
You are using a rather old version of ejabberd. I suggest you upgrade
before putting more work on this.

If you got omemo working for contacts on other server that may be because
their pep server is being used in that case.

**Comment by strb** [comment]
Thanks for all the detailed information. @andersruneson is right. Your ejabberd is almost definitely the problem here. You should upgrade to the most recent version. It won't retain the info that is published in PEP. Usually, the server information in the EditAccountsActivity should also reflect this, not sure what's going on there, but I will look into it... But this is also in line with the behavior you're observing. You're able to initiate OMEMO sessions with people on other servers because in order to initiate OMEMO with someone, *their* server has to have working PEP support (because you need to be able to fetch their PreKey, yours will be included in the message you send to them).

**Comment by improti** [comment]
Thx mate. If PEP isn't working, then the server-info-dialogue maybe shouldn't show it as working?

I upgraded the OS and got ejabberd 2.1.11 now. Upon restarting Conversations the logcat looks pretty much the same though. Please excuse if I repeat my question from above:

> Is there any good guide on setting up a server capable of all the things Conversation supports?

Other hints on how to go an appreciated ...

**Comment by andersruneson** [comment]
There are even newer releases of ejabberd, don't use distribution packages.

**Comment by strb** [comment]
> If PEP isn't working, then the server-info-dialogue maybe shouldn't show it as working?

You're right, and usually it isn't. The problem here is that old ejabberd versions will announce that they support PEP, but the implementation is broken in some ways. We have workarounds to detect this, and disable some features based on that detection, but apparently it doesn't catch every case yet. So we'll work on that.

> I upgraded the OS and got ejabberd 2.1.11 now.

That's way too old still. Distribution packages tend to be really far behind for some reason. You're going to want something with major version 15, and at that point you'll have to get it from some external source anyway (i.e. not ubuntu's repository), so just get the most recent upstream release, which seems to be 15.11.

**Comment by andersruneson** [comment]
jabber.at maintains packages for ejabberd for ubuntu.

**Comment by improti** [comment]
Ok, I will try to get a more recent version. Thank you for your time and advise.

I changed the title of the issue, because I assume the detection is something you want to / are going to fix? Otherwise feel free to close this issue if it is in your way.

**Comment by improti** [comment]
For server-admins hitting this too, if you upgrade to Debian "Jessie" or Ubuntu >= "Vivid" you will get a version of ejabberd > 14 which seems to make OMEMO work.
