### ISSUE TITLE
Preview photos in rooms (muc)

### ISSUE THREAD

**Issue by susobaco** [siacs/Conversations#1630]
Hi, so I've seen, the photographs are not previewed in theaters, conversations shows a web link to the picture that opens with the browser. This does not happen when the picture is sent directly from one user to another. In this case it is perfectly previews. Is this a bug or is not implemented ?. I think it would be great to be working. Thanks for your time and job.

**Comment by andersruneson** [comment]
The muc needs to be non-anonymous which means users in the muc can see each
others jid. Further you need to be each others roster. Then images will be
downloaded automatically.

This is for security reasons.

**Comment by iNPUTmice** [comment]
09d87965fbd77d5c3e463a168c56e4c9bac9fc2e will display a button in that case
