### ISSUE TITLE
Weird discrepancy in fingerprints

### ISSUE THREAD

**Issue by RalfJung** [siacs/Conversations#1631]
For some reason, OMEMO keys seem to be shown differently for the owner (in the account details): When I check my own fingerprint, it starts `05c613` and it consists of 8 blocks of 8 characters, plus a last block of 2 characters. When a friend checks my contact details, the fingerprint starts with `c613` and consists of exactly 8 blocks.

The same goes the other way around: When he checks his key in his own account, it starts with `05`. When I check his key, it doesn't. It seems almost as if Conversations just adds `05` to the beginning of all local keys...

**Comment by iNPUTmice** [comment]
You are using different versions. Version 1.8.3 strips a leading 0x05 from
all fingerprints.

**Comment by RalfJung** [comment]
We both just upgraded to version 1.8.3, right before this test.

Maybe it forgets to strip the leading 0x05 in some views, e.g., the view thats used for my own keys in the account details?
