### ISSUE TITLE
Feature suggestion: XMPP URI such as "xmpp:coven@chat.shakespeare.lit?join" as link

### ISSUE THREAD

**Issue by MRYingLEE** [siacs/Conversations#1634]
This is useful for a private MUC invitation in another (maybe public) MUC.

1. To show such a kind of URI as link,
2. To join MUC by clicking the link.

You may find the detail protocol and samples at:
http://xmpp.org/extensions/xep-0045.html#registrar-querytypes .

Thank you in advance,

Ying

**Comment by jkufner** [comment]
I like it, but it should not be limited to MUC. See [XEP-0147: XMPP URI Scheme Query Components](http://xmpp.org/extensions/xep-0147.html)

**Comment by MRYingLEE** [comment]
Just for your reference, https://github.com/jappix/jappix (WEB chat) supports this feature. Maybe some logic can be borrowed.

**Comment by tasn** [comment]
This works. Just tested it with the link in: https://conversations.im/#support
I don't know if the full standard is supported, but at least the example in the title does.

**Comment by MRYingLEE** [comment]
@tasn I bought the version from Google Play and I updated to the latest version (1.9.4), but such a kind of link is still not supported.

BTW, Gajim on PC (https://gajim.org/) has a good support on such a kind of URI also. It is souce opened.

**Comment by tasn** [comment]
So why did you close it if it's not fixed? I also tried with 1.9.4.

Have you tried the link I pointed out to?

**Comment by licaon-kter** [comment]
I guess s/he pressed *Comment and Close instead* of *Comment*

**Comment by MRYingLEE** [comment]
Sorry, I thought the "close" is to close the page.

I visited the link and in the linked page I downloaded the latest version from Google play. Actually I joined beta testing also, but so far, no newer version was fund.

**Comment by iNPUTmice** [comment]
This is not supported (yet) as a link inside Conversations. I think what he
was talking about is that he can open a link on a website which will then
open Conversations.
