### ISSUE TITLE
Duplicate images in some MUCs

### ISSUE THREAD

**Issue by moyamo** [siacs/Conversations#1635]
In some MUCs conversations duplicates images it sends.

Suppose `flawedmuc@example.com` is a MUC where conversation duplicates images and `normalmuc@example.com` is a MUC that works normally (no duplicates)

These stanza were captured from Pidgin's XML console.

Text message to normal MUC (no duplicate)

```
<message from='normalmuc@example.com/moyamo' to='moyamo@jabber.zone/PidginLaptop' lang='en' id='59f75362-376f-4cdb-8ca9-f559ab8a5557' type='groupchat'>
	<body>hi</body>
</message>
```

Image to normal MUC (no duplicate)

```
<message from='normalmuc@example.com/moyamo' to='moyamo@jabber.zone/PidginLaptop' lang='en' id='bc8a2fa0-cfe1-493c-90fb-cf853e7b4465' type='groupchat'>
	<body>https://account.jabber.at/media/http_upload/Q09M5IuySVdVP727fFwXojSQPn0vW9QQ/bc8a2fa0-cfe1-493c-90fb-cf853e7b4465.jpg</body>
	<html xmlns='http://jabber.org/protocol/xhtml-im'>
		<body xmlns='http://www.w3.org/1999/xhtml'>
			<img width='800' height='600' src='https://account.jabber.at/media/http_upload/Q09M5IuySVdVP727fFwXojSQPn0vW9QQ/bc8a2fa0-cfe1-493c-90fb-cf853e7b4465.jpg'/>
		</body>
	</html>
</message>
```

Text message to flawed MUC (no duplicate)
```
<message from='flawedmuc@example.com/moyamo' to='moyamo@jabber.zone/PidginLaptop' type='groupchat'>
	<body>hi</body>
</message>
```

Image to flawed MUC (duplicate)
```
<message from='flawedmuc@example.com/moyamo' to='moyamo@jabber.zone/PidginLaptop' type='groupchat'>
	<body>https://account.jabber.at/media/http_upload/13Rq023GU33dqqdMc7f89DikfnTxuMFj/8679af8d-78c7-4e1b-bb3a-276e09e637bd.jpg</body>
	<html xmlns='http://jabber.org/protocol/xhtml-im'>
		<body xmlns='http://www.w3.org/1999/xhtml'>
			<img height='600' src='https://account.jabber.at/media/http_upload/13Rq023GU33dqqdMc7f89DikfnTxuMFj/8679af8d-78c7-4e1b-bb3a-276e09e637bd.jpg' width='800'/>
		</body>
	</html>
</message>
```

The only difference I see between the flawed MUC and the normal MUC  is that in the `img` tag of the message to the flawed MUC, the width is at the end of the tag.

**Comment by andersruneson** [comment]
The xhtml part have been removed from Conversations beta version. Please
try that and close this issue.
Thanks

**Comment by moyamo** [comment]
Using the latest master branch this problem still persists.

The new message is (from Gajim)

```
<message from='flawedmuc@example.com/moyamo' to='moyamo@jabber.zone/Gajim' type='groupchat'>
<body>https://account.jabber.at/media/http_upload/g8HqRh07UDpI5URm4fzQnAwEtDl9VWoq/dad1e547-b157-451f-ac33-57084f53db6f.jpg</body>
</message>
```
And it still shows duplicates. I'm not sure if this is a Conversations problem or a server problem. The only other difference that I can see is that the flawed MUCs actual names is more like this: 232912389-2139128308@transport.example.com . Could it the fully numeric identifier cause a problem?

**Comment by iNPUTmice** [comment]
@moyamo can you verify that current HEAD fixes the issue for you?

**Comment by moyamo** [comment]
This works! Thanks :)
