### ISSUE TITLE
Whispers in MUC change to public after rotation

### ISSUE THREAD

**Issue by andrewd18** [siacs/Conversations#1637]
Using Conversations 1.8.3

Description
========
When I start a whisper, then rotate my phone, the target of a MUC whisper is changed to the MUC room itself. This has caused me to send private information to a semi-public MUC numerous times.

Steps to Reproduce
===============
1. Phone has rotation enabled in system settings.
1. Start Conversations.
1. Join a MUC.
1. Long-press on a user's name to start a whisper. Text says "Send private message to <name>".
1. Rotate phone 90 degrees. Text says "Send unencrypted message".

**Comment by Natureshadow** [comment]
Reproducible here.

**Comment by petmue** [comment]
Reminds me of the following:
> The number you have dialed is imaginary. Please rotate your phone by 90 degrees and try it again.
