### ISSUE TITLE
Battery consumption

### ISSUE THREAD

**Issue by spaetz** [siacs/Conversations#1638]
Sorry, this is a rather unspecific report, I am happy to help out debugging if I can. This is on my Moto G2 (Android 5.0.2), rooted but original firmware, conversations 1.8.2 from fdroid.org.
After a long sleep on wlan, conversation has used 57% of all energy according to the battery stats. Following Android OS 7%, Android system 3%, mobile standby 2%, Display 1%.

This seems rather high, is there any way I can help to debug this? If not feel free to close this and thanks for conversations.

**Comment by andersruneson** [comment]
Have you used Conversations for a long time or is this the first time and you've hit this issue?
Has this happened before?
How many accounts are you using? 
What servers are you using?

**Comment by licaon-kter** [comment]
Screenshots: main screen battery, netguard battery ?

**Comment by spaetz** [comment]
Yes, I am using conversations for quite a long time, and it has never shown up this dominant in the stats. The only change I can imagine, is that I had it lying "unused" (but turned on and online) for some time.

Screenshot of the consumption usage here:
![image1844518137](https://cloud.githubusercontent.com/assets/63132/12125135/e815f7bc-b3e9-11e5-8350-5b77dcf55939.jpg)

**Comment by SamWhited** [comment]
Does it give you actual absolute power consumption numbers somewhere? The percentage is a somewhat dubious number, because if the device is sitting idle and Conversations is the only thing using the network or doing anything at all, it's obviously going to be using a much higher percentage of the power consumption than everything else (even though that's still a tiny amount of power). No idea if that's what's happening here, but it could be.

**Comment by licaon-kter** [comment]
Now:
* Enter NetGuard there ash make a screenshot.
* Enter Android System (one of those) and make a screenshot.

**Comment by spaetz** [comment]
Checking network usage, I see a huge spike around January 1 which happened during a rather short time and levelled off. This seemed to be a one-off event. I will close this issue now, I have installed a battery monitor that measures absolute numbers and will report back if I have more specific information. Thanks for your suggestions, much appreciated!
