### ISSUE TITLE
Service Discovery for roster items

### ISSUE THREAD

**Issue by singpolyma** [siacs/Conversations#1643]
Am I correct in reading from the code that currently disco is only done on our servers and our own bare JID and not on roster items or other contacts?

For the purposes of #913, #1601, and similar, I propose that discovery (along with caching as per https://xmpp.org/extensions/xep-0115.html) be done for all roster items.  This could also be used for disabling file transfer UI when the remote does not support any file transfer protocol, etc.

If I am mistaken, please let me know.  Would the right place to start adding this be in XmppConnection along with the existing disco calls?

**Comment by iNPUTmice** [comment]
I would start on parsing incoming presences for the caps hash in the presence parser (we really don't want to do disco#info on entities that don't have a caps) and then add a method like fetchEntityCaps(Account, Jid, Hash) to the XmppConnectionService! that either looks up the features in our database or if they are not cached issues a new disco#info iq request to that Jid. You can utilize IqParser and IqGenerator to put the hash verification code and iq result parsing in. (You can access both class from within the XmppConnectionService.

**Comment by singpolyma** [comment]
> we really don't want to do disco#info on entities that don't have a caps

You think that'll be too expensive?  To do a disco on items that don't have caps (which shouldn't be many these days) when they come online?  (Genuine question.)

**Comment by iNPUTmice** [comment]
> You think that'll be too expensive? To do a disco on items that don't have caps (which shouldn't be many these days) when they come online?

Yes way too expensive. We would have to do this on every reconnect. Keep people in mind that don't have Stream Management. And if those people have entities in their roster that don't have stream management either (meaning they have presence changes all the time.) that'll will add up to **a lot**.

But like you said clients that don't do caps are rare these days anyway.

**Comment by singpolyma** [comment]
@iNPUTmice opinion on where to store the caps cache?  Add a table to DatabaseBackend?

**Comment by singpolyma** [comment]
I think the right place to put caps parsed from presence is to change

    private final Hashtable<String, Integer> presences

to

    private final Hashtable<String, Presence> presences

with a new `Presence` class that has the status integer and also caps (and in the future maybe other things).  Since caps can definitely be different per resource.

**Comment by iNPUTmice** [comment]
@singpolyma yes in its own table is probably the best solution. Just two columns hash and features where the later one holds a json array or something.

But only for the cached ones. I'd keep the live ones (those associated with a presence) in RAM for faster access. (We have to trigger UI elements based on that). You can probably refactor entities.Presences a little bit to hold the information. (Now that I'm looking at it it seems terrible to name that Presence**s**. While you are at it you can probably name this Presence instead and have a contact just hold a list of those or something.)

**Comment by singpolyma** [comment]
> I'd keep the live ones (those associated with a presence) in RAM for faster access

So, do the lookup in the presence parser, and store the actual disco information in the proposed `Presence` object instead of just the caps hash?

**Comment by iNPUTmice** [comment]
> So, do the lookup in the presence parser, and store the actual disco information in the proposed Presence object instead of just the caps hash?

yes.

**Comment by singpolyma** [comment]
So, because discovery results can be extended with arbitrary data forms (and said forms do affect the caps hash) maybe it makes the most sense to store as XML instead of a JSON array or whatever. The XML parser seems to assume there's an InputStream, though I imagine there's some string-backed InputStream I could use -- thoughts on that approach?

**Comment by iNPUTmice** [comment]
> So, because discovery results can be extended with arbitrary data forms

once we calculated and verified the hash we don't need to store the data forms. Just a list of features and maybe the client name + identity are fine for now. When we need more information later on we can cherry pick them from the data forms and put them into special fields in json. (But I'm fairly certain that we won't need them anyway)
