### ISSUE TITLE
[feature request] MUC: delete a room

### ISSUE THREAD

**Issue by jotwewe** [siacs/Conversations#1644]
One is able to create a room from within Conversations and to edit some of its properties, invite and ban users. As I was told on conversations@conference.siacs.eu, Conversations provides no way of deleting a room again (I know servers support this from doing so from within a client called 'psi-plus').
As of today, the usual messenger user does use his smartphone only, not a PC/laptop. So either Conversations must provide a way to delete rooms, or rooms have to auto-delete on the server (users might not like this) or a pile of unused rooms will fill servers (administrators and users might not like this).
I think the most obvious way is implementing room deletion in Conversations. Please do so.

**Comment by mlangguth** [comment]
+1 
is kind of needed

**Comment by d9h02f** [comment]
> a pile of unused rooms will fill servers

This is already the case, check out any public server and it's filled with thousands and thousands of empty rooms. I don't think adding a delete feature now to Conversations would be of much help anymore. If anything rooms should automatically be deleted once no one is in there anymore.

**Comment by jotwewe** [comment]
A delete feature in Conversations would not be useful as far as all
those forgotten and unused rooms are concerned, but it is better in
terms of user interface design: a room that is gone just because one
has not used it for eight weeks means unexpected behaviour and people
being upset.

However, automatically deleting a room by the server (after maybe a
year of not being used and only after sending a notice which informs
of the pending deletion in maybe two weeks) might make sense.

**Comment by iNPUTmice** [comment]
The ability to destory rooms has been introduced in 2.3.11
