### ISSUE TITLE
PEP and new contact

### ISSUE THREAD

**Issue by DeLadoss** [siacs/Conversations#1645]
Hi,

Test case: client A and B on different servers (not sure if this is important or not).
Both servers support PEP.

Client B add contact A and send a message (not encrypted).
Client A receive the message and press the black button to add also B as a contact.
Client A does not see B avatar and can't select OMEMO to send an encrypted message.
Client B can't select OMEMO to send an encrypted message (not sure about the A avatar since A has no avatar but it is probably the same).

Client A: disable account temporary to disconnect and then reconnect.
Avatar of B is availabe, OMEMO is available on client A so everything works.

It seems the PEP info are not recovered when a contact is first added.

Regards,

**Comment by iNPUTmice** [comment]
PEP info are not 'retrieved' but pushed by the server. Please open this issue with the vendor of your server.
