### ISSUE TITLE
[Bounty] Explore possible synergies with project "Jitsi"

### ISSUE THREAD

**Issue by improti** [siacs/Conversations#1646]
Not sure this is the best way, but trying it this way anyhow. I wrote a comment on an issue in the Jitsi projects (https://github.com/jitsi/jitsi/issues/199), which I thought you might want to or even should consider too. Jitsi is a Java program supporting VoIP in addition to chat. As both projects are Java based I imagine there should be quite some possible synergies. The actual issue there was about supporting OMEMO and I'm sure we all agree it would be great to be able to switch a conversation to the desktop including pictures and in a secure way. Java (I assume) is much about using libraries and as such "meta-knowledge", maybe you guys could get in touch and investigate if you could co-operate here and there? The concrete example there should be doable somehow, i.e. find the libraries needed to support OMEMO and use them instead of doing own ones in Jitsi? Wouldn't that reduce the effort needed and at the same time increase the capacity available for support/review?

In the issue I imagined a common backend (for some components only?). This would ensure interoperability, also, which again would profit the whole ecosphere or XMPP world. Plus I would dream about conversations providing the VoIP (with ZRTP) where there currently is no nice Android app either (although working with CSipSimple) - and that is stuff that Jitsi seems to have on the desktop, although I haven't got it to work with my server yet. Guess you get the dream/idea?

Feel free to close this if inapproriate or something. As I'm not into any of the libraries at all, I guess I would have a hard time to be of any help. On the other hand, if you have any specific tasks towards this that I could do, let me know. Would like to help but feel clueless how I could ... If you point out some basic ideas about how the OMEMO part could be used there, I would go and carry that info over, for example.

**Comment by improti** [comment]
I hadn't realised this before and it seems worth pointing this out: The ZRTP in Jitsi works over XMPP. I just put a note in the according issue. 

So my current point of view on the potentials on co-operation are:

Jitsi from Conversations:
* OMEMO
* MAM
* maybe ideas from the "simple" GUI?

Conversations from Jitsi:
* a compatible desktop-counterpart that is available cross-plattform (would really help the ecosphere?!)
* Voice and Video (with ZRTP) over XMPP
* SIP-stack if wanted, although to me it "feels" like we might actually not need SIP in the client anymore if we get that working over XMPP nicely (can still connect SIP on the server-side to an XMPP account then?)

I'd like to make an offer here. I am willing to pay @iNPUTmice (or anyone or group he wants to "send") 50€ and an additional 50€ for a (group of) "main" developer(s) of Jitsi if you get together for an extended chat/conference (I'd expect you guys to reserve more than an hour for this) to discuss possibilities according to the following agenda:

* (shortly) introduce the architecture of your projects to each other
* (shortly) talk about libraries used
* discuss the features listed above and other possible "fruitful exchanges" feature-wise to evaluate how the projects could benefit from a co-operation
 
If it to you then feels like feature-wise an exchange would make sense, maybe further start a discussion of:

* an abstraction-layer above the network stack to encapsulate the XEP functionality so that the libraries can be used by both projects and each only needs to adjust according to the underlying network-layer and the GUI above (might exist? might make sense? double-power for review and support of the core libraries then?)
* determine documentation needs (I could and would be willing to get into this and drive discussions and documentation of that common layer)
* determine tasks that can be distributed to the broader community - refactoring, documentation, API, whatever is needed there and can be done without already knowing all the code etc.

A wish (but no must) would be that you trial out the "other" project, i.e. Conversations-people do a call with XMPP/ZRTP using Jitsi and Jitsi-people do an OMEMO chat using Conversations. That would probably help to get an understanding how different the projects are atm. 

If you guys come up with some kind of meeting notes according to these things (as far as approriate), then I will transfer 50€ to each project/group/dev (i.e. not more than 100 € in total) as you wish. I don't care if it is a personal bank account or a project-fund. I will pay if you get together and discuss these things, even if you decide it's all bullshit and that I should f* off. Just to be clear, the bounty is just for a discussion/meeting, not for any actual development. I would need to see the (common) meeting-notes being published somehow on both projects issues/wiki or alike, though. E-Mail with GPG available in addition to OTR/OMEMO on XMPP for exchanging bank-details (I don't do PayPal and alike). I hope this offer is interesting to you guys.

**Comment by iNPUTmice** [comment]
The Jitsi people already said enough about this. I share there thoughts for the most part.
