### ISSUE TITLE
publish avatar failes with big source files

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1650]
I have a problem with publishing an avatar from a source with > 8 MPixel with the latest HEAD. 
Steps to reproduce:
1. In manage accounts, long touch on account and chose publish avatar
2. touch avatar to chose new one
3. chose one from image picker and select crop to maximum of the picture as possible
4. Message "Conversations has stopped" appears and publich avatar activity is starting again
The ADB logs doesn't show any errors, it seems that the log is cleared with starting the activity again.

I'm using a SG S3 with SlimKat Android 4.4.4.

**Comment by kriztan** [comment]
I've tried to find out the problem and found out, that it is an out of memory error:

`01-15 18:50:09.315 16030 16030 I dalvikvm-heap: Forcing collection of SoftReferences for 15335072-byte allocation: eu.siacs.conversations
01-15 18:50:09.335 16030 16030 E dalvikvm-heap: Out of memory on a 15335072-byte allocation.: eu.siacs.conversations
01-15 18:50:09.340 16030 16030 I dalvikvm: "main" prio=5 tid=1 RUNNABLE: eu.siacs.conversations
01-15 18:50:09.340 16030 16030 I dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x41900d08 self=0x401b3468: eu.siacs.conversations
01-15 18:50:09.340 16030 16030 I dalvikvm:   | sysTid=16030 nice=0 sched=0/0 cgrp=apps handle=1074843988: eu.siacs.conversations
01-15 18:50:09.340 16030 16030 I dalvikvm:   | state=R schedstat=( 4808233867 963706975 12628 ) utm=318 stm=162 core=3: eu.siacs.conversations
01-15 18:50:09.340 16030 16030 I dalvikvm:   at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method): eu.siacs.conversations
01-15 18:50:09.340 16030 16030 I dalvikvm:   at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:188): eu.siacs.conversations
01-15 18:50:09.340 16030 16030 I dalvikvm:   at com.soundcloud.android.crop.CropImageActivity.decodeRegionCrop(CropImageActivity.java:346): eu.siacs.conversations
01-15 18:50:09.340 16030 16030 I dalvikvm:   at com.soundcloud.android.crop.CropImageActivity.onSaveClicked(CropImageActivity.java:290): eu.siacs.conversations
01-15 18:50:09.340 16030 16030 I dalvikvm:   at com.soundcloud.android.crop.CropImageActivity.access$000(CropImageActivity.java:45): eu.siacs.conversations
01-15 18:50:09.345 16030 16030 I dalvikvm:   at com.soundcloud.android.crop.CropImageActivity$3.onClick(CropImageActivity.java:114): eu.siacs.conversations
01-15 18:50:09.345 16030 16030 I dalvikvm:   at android.view.View.performClick(View.java:4438): eu.siacs.conversations
01-15 18:50:09.345 16030 16030 I dalvikvm:   at android.view.View$PerformClick.run(View.java:18439): eu.siacs.conversations
01-15 18:50:09.345 16030 16030 I dalvikvm:   at android.os.Handler.handleCallback(Handler.java:733): eu.siacs.conversations
01-15 18:50:09.345 16030 16030 I dalvikvm:   at android.os.Handler.dispatchMessage(Handler.java:95): eu.siacs.conversations
01-15 18:50:09.345 16030 16030 I dalvikvm:   at android.os.Looper.loop(Looper.java:136): eu.siacs.conversations
01-15 18:50:09.345 16030 16030 I dalvikvm:   at android.app.ActivityThread.main(ActivityThread.java:5034): eu.siacs.conversations
01-15 18:50:09.345 16030 16030 I dalvikvm:   at java.lang.reflect.Method.invokeNative(Native Method): eu.siacs.conversations
01-15 18:50:09.345 16030 16030 I dalvikvm:   at java.lang.reflect.Method.invoke(Method.java:515): eu.siacs.conversations
01-15 18:50:09.345 16030 16030 I dalvikvm:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795): eu.siacs.conversations
01-15 18:50:09.345 16030 16030 I dalvikvm:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611): eu.siacs.conversations
01-15 18:50:09.345 16030 16030 I dalvikvm:   at dalvik.system.NativeStart.main(Native Method): eu.siacs.conversations
01-15 18:50:09.345 16030 16030 I dalvikvm: : eu.siacs.conversations
01-15 18:50:09.350 16030 16030 W dalvikvm: JNI WARNING: JNI function SetIntField called with exception pending: eu.siacs.conversations
01-15 18:50:09.350 16030 16030 W dalvikvm:              in Landroid/graphics/BitmapRegionDecoder;.nativeDecodeRegion:(IIIIILandroid/graphics/BitmapFactory$Options;)Landroid/graphics/Bitmap; (SetIntField): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 W dalvikvm: Pending exception is:: eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: java.lang.OutOfMemoryError:: eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:188): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at com.soundcloud.android.crop.CropImageActivity.decodeRegionCrop(CropImageActivity.java:346): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at com.soundcloud.android.crop.CropImageActivity.onSaveClicked(CropImageActivity.java:290): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at com.soundcloud.android.crop.CropImageActivity.access$000(CropImageActivity.java:45): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at com.soundcloud.android.crop.CropImageActivity$3.onClick(CropImageActivity.java:114): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at android.view.View.performClick(View.java:4438): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at android.view.View$PerformClick.run(View.java:18439): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at android.os.Handler.handleCallback(Handler.java:733): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at android.os.Handler.dispatchMessage(Handler.java:95): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at android.os.Looper.loop(Looper.java:136): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at android.app.ActivityThread.main(ActivityThread.java:5034): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at java.lang.reflect.Method.invokeNative(Native Method): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at java.lang.reflect.Method.invoke(Method.java:515): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: 	at dalvik.system.NativeStart.main(Native Method): eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm: "main" prio=5 tid=1 NATIVE: eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x41900d08 self=0x401b3468: eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm:   | sysTid=16030 nice=0 sched=0/0 cgrp=apps handle=1074843988: eu.siacs.conversations
01-15 18:50:09.350 16030 16030 I dalvikvm:   | state=R schedstat=( 4814759159 966366683 12675 ) utm=318 stm=163 core=3: eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #00  pc 0000132e  /system/lib/libcorkscrew.so (unwind_backtrace_thread+29): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #01  pc 0005d326  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+33): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #02  pc 00051360  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+395): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #03  pc 000513ce  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+25): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #04  pc 0003565c  /system/lib/libdvm.so: eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #05  pc 0003aee0  /system/lib/libdvm.so: eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #06  pc 0005faee  /system/lib/libandroid_runtime.so: eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #07  pc 0007b3e6  /system/lib/libandroid_runtime.so: eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #08  pc 0001dd50  /system/lib/libdvm.so (dvmPlatformInvoke+116): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #09  pc 0004af1a  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+397): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #10  pc 00027160  /system/lib/libdvm.so: eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #11  pc 0002bac0  /system/lib/libdvm.so (dvmMterpStd(Thread*)+144): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #12  pc 0002abdc  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+252): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #13  pc 0005d538  /system/lib/libdvm.so (dvmInvokeMethod(Object*, Method const*, ArrayObject*, ArrayObject*, ClassObject*, bool)+391): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #14  pc 00065686  /system/lib/libdvm.so: eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #15  pc 00027160  /system/lib/libdvm.so: eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #16  pc 0002bac0  /system/lib/libdvm.so (dvmMterpStd(Thread*)+144): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #17  pc 0002abdc  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+252): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #18  pc 0005d256  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+337): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #19  pc 00046b02  /system/lib/libdvm.so: eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #20  pc 0004c8ae  /system/lib/libandroid_runtime.so: eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #21  pc 0004d5ba  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, char const*)+353): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #22  pc 0000105a  /system/bin/app_process: eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   #23  pc 0000e31c  /system/lib/libc.so (__libc_init+47): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:188): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at com.soundcloud.android.crop.CropImageActivity.decodeRegionCrop(CropImageActivity.java:346): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at com.soundcloud.android.crop.CropImageActivity.onSaveClicked(CropImageActivity.java:290): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at com.soundcloud.android.crop.CropImageActivity.access$000(CropImageActivity.java:45): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at com.soundcloud.android.crop.CropImageActivity$3.onClick(CropImageActivity.java:114): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at android.view.View.performClick(View.java:4438): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at android.view.View$PerformClick.run(View.java:18439): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at android.os.Handler.handleCallback(Handler.java:733): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at android.os.Handler.dispatchMessage(Handler.java:95): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at android.os.Looper.loop(Looper.java:136): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at android.app.ActivityThread.main(ActivityThread.java:5034): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at java.lang.reflect.Method.invokeNative(Native Method): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at java.lang.reflect.Method.invoke(Method.java:515): eu.siacs.conversations
01-15 18:50:09.360 16030 16030 I dalvikvm:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795): eu.siacs.conversations
01-15 18:50:09.365 16030 16030 I dalvikvm:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611): eu.siacs.conversations
01-15 18:50:09.365 16030 16030 I dalvikvm:   at dalvik.system.NativeStart.main(Native Method): eu.siacs.conversations
01-15 18:50:09.365 16030 16030 I dalvikvm: : eu.siacs.conversations
01-15 18:50:09.365 16030 16030 E dalvikvm: VM aborting: eu.siacs.conversations
01-15 18:50:09.365 16030 16030 F libc    : Fatal signal 6 (SIGABRT) at 0x00003e9e (code=-6), thread 16030 (s.conversations): eu.siacs.conversations
01-15 18:50:09.465  1890  1890 I DEBUG   : pid: 16030, tid: 16030, name: s.conversations  >>> eu.siacs.conversations <<<: /system/bin/debuggerd
01-15 18:50:10.060  2312 19908 I am_crash: [2312,0,eu.siacs.conversations,8961606,Native crash,Aborted,unknown,0]: system_server`

While testing around I found out, that is is sometimes working. Perhaps 9 of 10 are failing.

**Comment by licaon-kter** [comment]
Use https://gist.github.com to post logs.

**Comment by kriztan** [comment]
Thanks, updated.

**Comment by iNPUTmice** [comment]
https://github.com/jdamcd/android-crop/issues/198
