### ISSUE TITLE
Show more details of client and server software in contact details

### ISSUE THREAD

**Issue by petmue** [siacs/Conversations#1652]
Hi! Out of curiosity, for debugging purposes and to check which features I could expect of my contact

it would be great to see in the contact details which ```client software``` (eg Conversations 1.8.0) my contact uses and (also in my own account details) which ```server``` software (eg ejabberd 15.07) is used.

Sincerly
PM

**Comment by licaon-kter** [comment]
And the add a toggle to hide them. ;)

**Comment by iNPUTmice** [comment]
Not the Conversations way. A users should not be bothered with something like this.
