### ISSUE TITLE
[enhancement] search for offline contacts

### ISSUE THREAD

**Issue by kousu** [siacs/Conversations#1653]
In Gajim, if I have "Show offline contacts" off, but type a name in the search box, it will show them even if they are offline.  This way my contact list isn't cluttered at a glance but I can quickly find people to message if I have a specific thought in mind.

Doing the same thing in Conversations requires unticking Hide Offline, and then reticking when I'm done.

**Comment by jkufner** [comment]
Yes, good point. I like this feature in Gajim too.

**Comment by singpolyma** [comment]
Why does conversations even have a "hide offline" option?  Seems to not be consistent with the model and already a pretty advanced-users-only feature

**Comment by kousu** [comment]
Yay!  Best patch!

**Comment by kousu** [comment]
I just got these in the latest Conversations and immediately noticed something I hadn't thought about: when using this feature, the Hide Offline checkbox still appears in the menu and appears to be broken because it does nothing. Can it be greyed out or removed? Or like @singpolyma suggested, just remove it entirely so that the only way to contact offline contacts is search or by receiving a message from an invisible contact.

**Comment by singpolyma** [comment]
That is definitely not what I was suggesting! I never want so-called "offline" contacts to be hidden.
