### ISSUE TITLE
Please hide all undecypherable OTR messages

### ISSUE THREAD

**Issue by arkenoi** [siacs/Conversations#1656]
( related issue is #1370 )

If there is more than one client device and/or a misbehaving server (which in turn could be outside of user's control), I see a lot of encrypted messages. It is very annoying. Could we hide it or make it visible only if there is a configuration option set? It might be worth sending a notice like "xxx OTR messages for unknown key received from blabla@blabla.org" or something, but not showing a lot of garbage like it does now.

**Comment by iNPUTmice** [comment]
Instead of spamming our issue tracker with duplicate issues you should tell the client developers who are causing this issue.

**Comment by arkenoi** [comment]
Ok, maybe there are misbehaving clients. Does this fact really prevent us from having a usable workaround?
