### ISSUE TITLE
MUC notifications in 1.9.0

### ISSUE THREAD

**Issue by susobaco** [siacs/Conversations#1659]
Hi, I see you've gone the option of the new message notification on the MUC. It is a judgment or decision? I think it's great to have this option. I use it a lot in family rooms.

**Comment by iNPUTmice** [comment]
The muc notification setting have been moved into their respective muc
details screen. (overflow menu conference details)

**Comment by susobaco** [comment]
Ok I understand. Anyway, I think there is a failure for not notify me when a message comes in. I have enabled the option. You could check it ?, thanks

**Comment by susobaco** [comment]
I already know what happens. When changing settings specifically for each room in the change notification messages with the name goes on. In the options of the room you can change the type of notification. Roger that, good job!!
