### ISSUE TITLE
OTR session not established with converse.js

### ISSUE THREAD

**Issue by devdan** [siacs/Conversations#1660]
When trying to have an OTR-encrypted chat with convese.js, the session is not established and it is impossible to communicate.

When the session is initialized by converse.js, all I see in conversations is "?OTRv23?".

When trying to start the chat from conversations, all I see is a very large message starting with "?OTR|" and a large alpha numeric sequence.

I don't know if this is an issue of conversations or converse.js.

**Comment by iNPUTmice** [comment]
I'm closing because this is a converse issue.
