### ISSUE TITLE
Sync rooms with other Clients.

### ISSUE THREAD

**Issue by thundergreen** [siacs/Conversations#1663]
Let the user decide whether he/she wants to sync the bookmarks and autojoin the rooms. This option should be in "advanced settings"

**Comment by yrii2121** [comment]
I agree, it would be convenient.

**Comment by singpolyma** [comment]
You are not required to bookmark MUCs that you join with Conversations.  It's already optional.

**Comment by weiss** [comment]
> You are not required to bookmark MUCs that you join with Conversations.

But Conversations will auto-join rooms bookmarked with other clients, which might not be what you want on mobile devices.

**Comment by thundergreen** [comment]
I especially think about people with different transports like irc ...by
joining these rooms on mobile devices it produces a lot of traffic ... And
I'm sure some people might not want to join dev channels on their phone .

Thorsten Fröhlich
Am 25.01.2016 10:03 schrieb "Holger Weiß" <notifications@github.com>:

**Comment by singpolyma** [comment]
Only if you set those bookmarks to auto-join, yeah? So if you don't want that, keep the bookmark for easy access from all your clients but set it as not an auto-join bookmark

**Comment by weiss** [comment]
> Only if you set those bookmarks to auto-join, yeah?

Yes.

> So if you don't want that, keep the bookmark for easy access from all your clients but set it as not an auto-join bookmark

The point is that you might want different things on desktop/web clients on the one hand and on mobile clients on the other.

**Comment by yrii2121** [comment]
>So if you don't want that, keep the bookmark for easy access from all your clients but set it as not an auto-join bookmark

I want Conversations not automatically connected with certain rooms, but the host computer is automatically connected with all the rooms in my bookmarks.

Sorry for my English (I not speak English).

**Comment by thundergreen** [comment]
That's exactly our intention with this threat here ; good English dude! ™}

Thorsten Fröhlich
Am 25.01.2016 19:21 schrieb "yrii2121" <notifications@github.com>:

**Comment by thundergreen** [comment]
closed, fixed in [https://github.com/siacs/Conversations/issues/1666](url)
