### ISSUE TITLE
No connection to HTTPUpload after server restart

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1665]
Yesterday I've updated prosody and all Conversations clients didn't reconnect to HTTPUpload after this restart itself. A manual disconnect and connect in the Conversations account settings didn't help. I had to exit Conversations completely within android app manager and started the app again, and now Conversations connected successfully to HTTPUpload component.

**Comment by iNPUTmice** [comment]
What do you mean by 'does not connect to'? Is HTTP Upload available in the
server info? Or did the upload fail?

**Comment by kriztan** [comment]
In server info httpupload isn't available. In the server logs there are no incoming queries searching for the httpupload component.

**Comment by iNPUTmice** [comment]
I can't reproduce this issue

**Comment by kriztan** [comment]
I'll try to provide some logs.

**Comment by iNPUTmice** [comment]
Can reproduce. Sorry.
