### ISSUE TITLE
MAM retrieval problem with OMEMO messages

### ISSUE THREAD

**Issue by sezuan** [siacs/Conversations#1668]
Conversations stops fetching mam messages when there are too many OMEMO encrypted messages in a row.

**Comment by iNPUTmice** [comment]
does 58c6f9bfb283f5c54695b9662b5b4b08e5d4357f fix the problem for you?

**Comment by sezuan** [comment]
Seems not to work. It appears that it stucks in a mam fetch loop. I'll check the server logs later.

**Comment by sezuan** [comment]
Logcat out, which repeats forever:

    D/conversations( 7930): matthias@sucksass.de: finished mam after 50 messages
    I/NotificationService( 1143): cancelToast pkg=eu.siacs.conversations callback=android.app.ITransientNotification$Stub$Proxy@2bc99141
    D/conversations( 7930): load more messages for <*removed*> prior to 2016-01-24T20:46:29Z
    D/conversations( 7930): matthias@sucksass.de: running mam query with=<*removed*>, start=1970-01-01T00:00:00Z, end=2016-01-24T20:46:28Z
    I/NotificationService( 1143): cancelToast pkg=eu.siacs.conversations callback=android.app.ITransientNotification$Stub$Proxy@285ad6e6
    W/NotificationService( 1143): Toast already cancelled. pkg=eu.siacs.conversations callback=android.app.ITransientNotification$Stub$Proxy@285ad6e6
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.InvalidMessageException: No valid sessions.
    D/conversations( 7930): AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/phone No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@3faf42f6
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.InvalidMessageException: No valid sessions.
    D/conversations( 7930): AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/phone No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@44aa6f7
    D/conversations( 7930): AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/phone No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@2cb28964
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.DuplicateMessageException: Received message with old counter: 1 , 0
    D/conversations( 7930): AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/phone No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@153927cd
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.DuplicateMessageException: Received message with old counter: 1 , 0
    D/conversations( 7930): AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/phone No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@9049882
    D/conversations( 7930): AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/phone No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@33f8bb93
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.DuplicateMessageException: Received message with old counter: 3 , 0
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.DuplicateMessageException: Received message with old counter: 3 , 1
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.DuplicateMessageException: Received message with old counter: 3 , 2
    D/conversations( 7930): AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/phone No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@10c0d7d0
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.DuplicateMessageException: Received message with old counter: 1 , 0
    D/conversations( 7930): AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/phone No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@1ebd73c9
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.DuplicateMessageException: Received message with old counter: 4 , 0
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.DuplicateMessageException: Received message with old counter: 4 , 1
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.DuplicateMessageException: Received message with old counter: 4 , 2
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.DuplicateMessageException: Received message with old counter: 4 , 3
    D/conversations( 7930): AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/phone No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@2667bace
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.InvalidMessageException: No valid sessions.
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.InvalidMessageException: No valid sessions.
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.InvalidMessageException: No valid sessions.
    D/conversations( 7930): AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/phone No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@3e697def
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.InvalidMessageException: No valid sessions.
    I/conversations( 7930): AxolotlService (matthias@sucksass.de): WhisperMessage received
    W/conversations( 7930): AxolotlService (matthias@sucksass.de): Error decrypting axolotl header, org.whispersystems.libaxolotl.InvalidMessageException: No valid sessions.
    D/conversations( 7930): matthias@sucksass.de: finished mam after 50 messages

**Comment by iNPUTmice** [comment]
What about 0911669b07b062b30d41da0623ff0e7288ad2ddd ?

**Comment by sezuan** [comment]
Unchanged:

    adb logcat -v time | grep mam.query
    
    02-03 22:50:52.969 D/conversations( 3024): matthias@sucksass.de: running mam query with=<*removed*>, start=1970-01-01T00:00:00Z, end=2016-01-24T20:46:28Z
    02-03 22:50:56.650 D/conversations( 3024): matthias@sucksass.de: running mam query with=<*removed*>, start=1970-01-01T00:00:00Z, end=2016-01-24T20:46:28Z
    02-03 22:51:00.298 D/conversations( 3024): matthias@sucksass.de: running mam query with=<*removed*>, start=1970-01-01T00:00:00Z, end=2016-01-24T20:46:28Z
    02-03 22:51:03.506 D/conversations( 3024): matthias@sucksass.de: running mam query with=<*removed*>, start=1970-01-01T00:00:00Z, end=2016-01-24T20:46:28Z
    02-03 22:51:08.408 D/conversations( 3024): matthias@sucksass.de: running mam query with=<*removed*>, start=1970-01-01T00:00:00Z, end=2016-01-24T20:46:28Z

**Comment by iNPUTmice** [comment]
mhhh more difficult than I thought.

Can you try again with HEAD?

**Comment by sezuan** [comment]
Works. Thank you.

**Comment by sezuan** [comment]
Not sure why, but it happend again:

02-13 19:49:40.763  6093  6093 D conversations: matthias@sucksass.de: running mam query with=<snip>, start=1970-01-01T00:00:00Z, end=2016-02-13T18:49:40Z
	02-13 19:49:41.092  6093 14999 D conversations: AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/mobile No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@7bd8e51
	02-13 19:49:41.173  6093 14999 D conversations: AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/mobile No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@b876b6
	02-13 19:49:41.361  6093 14999 D conversations: AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/mobile No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@97a2fb7
	02-13 19:49:41.653  6093 14999 D conversations: AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/mobile No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@21a4324
	02-13 19:49:41.813  6093 14999 D conversations: AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/mobile No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@77bbe8d
	02-13 19:49:41.958  6093 14999 D conversations: AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/mobile No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@1cd4842
	02-13 19:49:42.101  6093 14999 D conversations: AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/mobile No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@5781053
	02-13 19:49:42.164  6093 14999 D conversations: AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/mobile No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@c4a6d90
	02-13 19:49:42.220  6093 14999 D conversations: AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/mobile No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@672b689
	02-13 19:49:42.376  6093 14999 D conversations: AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/mobile No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@96ba68e
	02-13 19:49:42.420  6093 14999 D conversations: AxolotlService (matthias@sucksass.de): Account: matthias@sucksass.de/mobile No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@f695eaf
	02-13 19:49:42.964  6093 14999 D conversations: matthias@sucksass.de: finished mam after 50 messages. messages left=true

After `finished mam after 50 messages. messages left=true` no more messages are fetched.

**Comment by iNPUTmice** [comment]
If you switch back and forth to another conversation will that make the messages start loading? (or at least more messages)

**Comment by sezuan** [comment]
No, **but** it seems when there's at least one decryptable message in the first set of retrieved messages, all other messages will be fetched.

**Comment by iNPUTmice** [comment]
Ok. So can I assume that this problem occurs in conversations that are
otherwise completely empty (meaning no messages)? Does the problem go away
if you write a message (and then maybe switch back and forth to another
conversation)

2016-02-15 9:31 GMT+01:00 Matthias Rieber <notifications@github.com>:

**Comment by sezuan** [comment]
Exactly, when I write one message, everything will be fetched.

**Comment by iNPUTmice** [comment]
d2cfac222ef7c144047eb7518a32f7cf9b39144f should fix this then
