### ISSUE TITLE
feature request: set Priority

### ISSUE THREAD

**Issue by doczkal** [siacs/Conversations#1669]
Please add an option to set the "priority" flag to higher then 0.

Currently I face the following Issue:
I use conversation (always Priority 0) and Pidgin (priority 1 if available, priority 0 if do not disturb and possibly something else if in status "chatty")
I would like to send an OTR message to someone having connected two instances of Conversations (both priority 0). I have all (2 OTR and 2 OMEMO) encryption Keys verified on my Conversations Client (mobile). But cannot do with Pidgin as Pidgin is not able to connect to the Client. This might be a Pidgin Issue here, but nevertheless I have this issue with Conversations Clients only.

What works:
Conversations to Conversations using OMEMO encryption.

What does not work:
Send a message from Pidgin (mine) to Conversations.

**Comment by singpolyma** [comment]
You should be able to set Pidgin to priority 0

**Comment by doczkal** [comment]
Yes,  but that doesn't solve the problem of not being able to send a message to the other person.

On January 24, 2016 11:53:49 PM GMT+01:00, Stephen Paul Weber <notifications@github.com> wrote:
>You should be able to set Pidgin to priority 0
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/siacs/Conversations/issues/1669#issuecomment-174349994

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by singpolyma** [comment]
Oh, I see.  Pidgin won't let you select which resource to chat with and messages end up going to the one you didn't want?

**Comment by doczkal** [comment]
As far as I can tell the other person is not receiving a message at all. This makes it really difficult (not to say impossible) to verify the OTR fingerprints of the clients with pidgin. 

On January 24, 2016 11:58:39 PM GMT+01:00, Stephen Paul Weber <notifications@github.com> wrote:
>Oh, I see.  Pidgin won't let you select which resource to chat with and
>messages end up going to the one you didn't want?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/siacs/Conversations/issues/1669#issuecomment-174350299

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by singpolyma** [comment]
sounds like a more fundamental issue than priority, maybe?

**Comment by doczkal** [comment]
Maybe. I don't know what the root cause is but if you require more information to troubleshoot this then let me know. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by iNPUTmice** [comment]
Does it work if you take one of the two receiving clients offline?

Do unencrypted messages arrive?

**Comment by doczkal** [comment]
Unfortunately I haven't reached him yesterday so cannot tell for sure. 

I think we tried to send messages while one client is connected only but this doesn't work. 

Sending unencrypted messages while both clients are connected doesn't work. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
