### ISSUE TITLE
[MUC] roster updates/synchronisation

### ISSUE THREAD

**Issue by sokai** [siacs/Conversations#1672]
Hi!

I'm connected with two clients (e.g. Pidgin and Conversations) and the same account.
Now in Pidgin I add a MUC to my roster (the two options to make the MUC persistent and open the MUC after reconnect are checked).
That MUC is not in the roster of Conversations and I have to manually add the MUC in Conversations again.

→ **Wish:** Please always sync the MUCs in the roster.

(BTW: If I add the MUC with conversations and ckeck "add to roster", the MUC will not appear in the Pidgin roster, too … :-/ – Maybe that's a general problem in XMPP/for every client software!?)

Thanks and best regards!

**Comment by edhelas** [comment]
@sokai Pidgin afaik doesn't implement XEP-0048 - Bookmarks (see https://developer.pidgin.im/ticket/6353) and the ticket is open for 8 years now.

**Comment by sokai** [comment]
@edhelas Oh, thanks – didn't know that … :-/

(Can someone close this issue, plz!?)

**Comment by andersruneson** [comment]
You can close it.
