### ISSUE TITLE
IO exception in http file size checker with httpupload

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1673]
I've just updated prosody to use the mod_http_upload instead of the external python script as external component and ended up with the following error:
https://gist.github.com/kriztan/46aa45bf8a24e099cf1f
I've a valid certificate for my domain/subdomain, I don't know what's wrong and the image link is working as expected in the browser but Conversations fails.

Any ideas?

**Comment by iNPUTmice** [comment]
does 7dd9545ea3777972b1d80e59dfc5166dd53cceb0 fix this issue for you?

**Comment by kriztan** [comment]
I think yes, it is fixed now
