### ISSUE TITLE
OTR encryption not restarting

### ISSUE THREAD

**Issue by albertohcd** [siacs/Conversations#1675]
In the single conversations, the OTR encryption starts receiving each member the key and changing the status from PLAINTEXT to ENCRYPTED, but after a few minutes the otrSession loose it and never can comunicate with OTR encryption. Is there any way to force to re-send the encryption key (the long alphanumerical string that starts with "?OTR:")? Because I've tried to startOtrIfNeeded but it doesn't work and each time that I send a message it keeps waiting.

Thanks.

**Comment by iNPUTmice** [comment]
If you know your session is broken you can call resetOtrSession() and then startOtrIfNeeded again.

**Comment by albertohcd** [comment]
I've tried, but it doesn't work.

**Comment by mroemore** [comment]
I'm having a similar issue, this started after we upgraded our Openfire version from 3.10.3 to 4.0.1, downgrading is not an option since it causes issues with signing in. All messages that should be coming through encrypted are marked by Conversations as 'Unencrypted' and are highlighted in red instead of the standard green. They also start with "?OTR:" as albertohcd mentioned. If i try to send a message back, it never sends, the delivery message is "waiting...". The ADB debug log doesn't give any further information.

**Comment by mroemore** [comment]
Actually I think I was wrong about the ADB logs having no info. If I restart the Conversations app, there's this:

`02-16 12:50:37.586 D/conversations( 9829): AxolotlService : Couldn't find <item> in bundle IQ packet: <iq to="myname@mychat.com/mobile" from="myname@mychat.com" xmlns="jabber:client" id="i6kcgkhseo" type="result"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="eu.siacs.conversations.axolotl.bundles:663547653" xmlns="http://jabber.org/protocol/pubsub"/></pubsub></iq>
02-16 12:50:37.586 W/conversations( 9829): AxolotlService (myname@mychat.com): Received invalid bundle:<iq to="myname@mychat.com/mobile" from="myname@mychat.com" xmlns="jabber:client" id="i6kcgkhseo" type="result"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="eu.siacs.conversations.axolotl.bundles:663547653" xmlns="http://jabber.org/protocol/pubsub"/></pubsub></iq>
02-16 12:50:37.586 W/conversations( 9829): AxolotlService (myname@mychat.com): Received invalid prekeys:<iq to="myname@mychat.com/mobile" from="myname@mychat.com" xmlns="jabber:client" id="i6kcgkhseo" type="result"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="eu.siacs.conversations.axolotl.bundles:663547653" xmlns="http://jabber.org/protocol/pubsub"/></pubsub></iq>
02-16 12:50:37.977 I/conversations( 9829): AxolotlService (myname@mychat.com): Adding own IdentityKey org.whispersystems.libaxolotl.IdentityKey@6f89fb2b to PEP.
02-16 12:50:38.003 I/conversations( 9829): AxolotlService (myname@mychat.com): Adding new signedPreKey with ID 482 to PEP.
02-16 12:50:44.540 I/conversations( 9829): AxolotlService (myname@mychat.com): Adding 100 new preKeys to PEP.
02-16 12:50:44.550 D/conversations( 9829): AxolotlService (myname@mychat.com): : Bundle 663547653 in PEP not current. Publishing: <iq type="set"><pubsub xmlns="http://jabber.org/protocol/pubsub"><publish node="eu.siacs.conversations.axolotl.bundles:663547653"><item><bundle xmlns="eu.siacs.conversations.axolotl"><signedPreKeyPublic signedPreKeyId="482">BbXsfkA5kJ1ahMYxD+sJVMaNKzX/anzYh/rITaNxFRof
02-16 12:50:44.550 D/conversations( 9829): </signedPreKeyPublic><signedPreKeySignature>ABFgRAb+8Did1Dg6WfGgxidTqoPPDQWKmmlbg+TGSHUjWICkrNcFoBS3p7mu/nnphm4WfHBrsMfe
02-16 12:50:44.550 D/conversations( 9829): urbtVxXChQ==
02-16 12:50:44.550 D/conversations( 9829): </signedPreKeySignature><identityKey>BW/rvGbE6tKlzokk5tHQymgECyP51Zipa5pXof/CINtR
02-16 12:50:44.550 D/conversations( 9829): </identityKey><prekeys xmlns="eu.siacs.conversations.axolotl"><preKeyPublic preKeyId="48101">BanAId1LLLR5NNfa7jdgol5qOg1kMGPElIAD3LuGceZ8
02-16 12:50:44.550 D/conversations( 9829): </preKeyPublic><preKeyPublic preKeyId="48079">BR+D+N0Zi6ctmR6y1c6wlQcZQ5qMrLVdC7ZS61L2LQUC`

And it goes on like that for a bit, with more preKeyPublic lines.

**Comment by iNPUTmice** [comment]
Hi @mroemore slightly different problem in your case I think. I included some more logging in the current HEAD. Can you update and test again? Please start the logging at the time when you first start writing OTR messages and don't include the stuff before. (Those failed OMEMO stanzas are irrelevant)

**Comment by iNPUTmice** [comment]
I'm closing this because ever since OMEMO got enough traction there is no point in trying to fix a broken protocol.
