### ISSUE TITLE
swipe to view images

### ISSUE THREAD

**Issue by silberzwiebel** [siacs/Conversations#1681]
Hi,

if one touches a posted image it is shown in fullscreen, which is nice.
Now, it would be cool, if one could swipe to the left/right to access the previous/next image that was posted in the chat. At the moment, you have to go back to the chat view and touch the picture you want to see...

Thanks,
silberzwiebel

**Comment by iNPUTmice** [comment]
To do this we would have to include our own image view which is not something on our TODO list.

**Comment by tigre-bleu** [comment]
Too bad, this is one feature leading to a comment like "Mmm, It's easier in whatsapp" when we show conversations/xmpp to potential users.

**Comment by contrapunctus-1** [comment]
Bump. Now that Conversations has a built-in image viewer...how about it? 😀

**Comment by licaon-kter** [comment]
It doesn't have that.
