### ISSUE TITLE
Voice message plays by itself after unlock triggered by incoming message

### ISSUE THREAD

**Issue by petmue** [siacs/Conversations#1682]
Conversations 1.9.3 on CM 12.1

During listening to a voice message lock the screen and wait until the voice message ends.
When you now unlock the screen nothings happens, you will go straight back to the standard android audio player.

Result changes when you receive an incoming message while the screen is locked:
When you now unlock the screen the audio messages plays again by itself.

I'm not sure whether this is an android bug or it's related to Conversations. However, I wanted to let you know.

**Comment by iNPUTmice** [comment]
There is no code in Conversations that could possible auto play voice message. That is handled by external apps.
