### ISSUE TITLE
mp3 files not recognized as audio files

### ISSUE THREAD

**Issue by kevinkk525** [siacs/Conversations#1683]
If I send audio files to someone else using Conversations the audio files are not being recognized as such and only a link to the file is shown. Same happens for wav,amr,txt,zip...
On my side they are recognized and shown as their filetype but not on the recipient's side. He only gets a link whereas pictures work.

Server used: ejabberd 16.01 with mod_http_upload
Conversations 1.9.3

**Comment by iNPUTmice** [comment]
fixed in 09d87965fbd77d5c3e463a168c56e4c9bac9fc2e
