### ISSUE TITLE
audio plugin. otr sends. omemo fails.

### ISSUE THREAD

**Issue by Jello16** [siacs/Conversations#1684]
Am I misunderstanding something?

I set the send key to be audio message.  Composing no text I hit the green mic.  I pick the plugin as default.  immediately a recording prompt. then share to send the audio snippet.  

In an OTR session the audio snippet is conveyed

In an OMEMO session sending always fails. 

(by always I mean between myself on chatme.im to myself on xmpp.zone, both capable, myself in the same client on the same phone handset)

**Comment by iNPUTmice** [comment]
xmpp.zone recently had problems with their HTTP upload component which should be fixed now.
