### ISSUE TITLE
Sending message while no internett connection cause infinite repeated messages

### ISSUE THREAD

**Issue by pointhi** [siacs/Conversations#1685]
When I send a message, while my phone has no internet connection, the phone is repeatedly sending this message whenever an internet connection is there until I clear the history. The message is always marked as ```sending...``` when a internet connection is there, and ```waiting...``` when no one is there.

Furthermore, no User identification is send on those repeatedly messages (at least no user identification is visible on pidgin for those messages).

As side note: the message was posted into a group chat.

**Comment by iNPUTmice** [comment]
What server are you using?
Can I assume from your wording that this does not happen when you are online while sending the message initially?

> Furthermore, no User identification is send

I don't know what that means

**Comment by pointhi** [comment]
> What server are you using?

XMPP-Server: ```ejabberd-2.1.10-4+deb7u1```

> Can I assume from your wording that this does not happen when you are online while sending the message initially?

Yep, that bug only happens when conversations try to send a message which was created while beeing offline.

>   >  Furthermore, no User identification is send
> 
> I don't know what that means

Here is an image to describe it. The first message was sent from my phone, while it was connected (no problem).

The two messages later are the message which was sent while my phone was not connected. There is no user identification visible in pidgin, and the message was sent repeated.

![bildschirmfoto von 2016-02-07 18-06-03](https://cloud.githubusercontent.com/assets/1652144/12873752/e82d0ff6-cdc5-11e5-9f95-233c0110e011.png)

expected behaviour would be no difference between message was send online vs message was created offline and then sent automatically after connecting to the internet.

**Comment by iNPUTmice** [comment]
can you check if 1bb38e25f2e9d7fbe03ba7cd9173f780b42fe5d4 fixes this issue for you?

**Comment by pointhi** [comment]
Hy @iNPUTmice, https://github.com/siacs/Conversations/commit/1bb38e25f2e9d7fbe03ba7cd9173f780b42fe5d4 seems to fixes this issue
