### ISSUE TITLE
Security error: Unable to connect 

### ISSUE THREAD

**Issue by anmol26s** [siacs/Conversations#1686]
Hi

I am getting "security error" while connecting through conversations. This problem started last week.
I tried connecting with another xmpp accounts but I get the same error.
I am trying to export logs but I don't know where the log file is being saved on the phone.

**Comment by iNPUTmice** [comment]
please provide adb logcat output. (see FAQ 'How do i debug Conversations')

**Comment by anmol26s** [comment]
It was my phone's problem (xiaomi mi3). After the latest update the bug has been fixed.
Thanks
