### ISSUE TITLE
pseudo-joined conferences

### ISSUE THREAD

**Issue by kousu** [siacs/Conversations#1687]
I discovered that Conversations will open a MUC window if it receives
```
<message type='groupchat' from='channel@conference.example.com/nick' to='user@example.com/Conversations'>....
```
without having first been in `channel`.  For example, [the Slack XMPP gateway](https://get.slack.help/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP) [does this](https://gist.github.com/kousu/e6ba7b18aa864be17e32), because it's just so easy for a transport to relay messages without really thinking about them.

There are at least two bugs with how Conversations handles this case.  If I interact with the room, intermittently I get a message from JID "slack.com" that says "Use name 'kousu' instead of 'null' when joining Slack channels.". I think I know what's going on: Conversations knows I am not in the the room and attempts to join it; but because I haven't gone through the normal add-conference UI, the handle is null, and that is getting serialized to the string "null", which can't be what you intended.  The second bug is that Conversations hovers "Conference not found    [Leave]" over the chat for the entire duration of it being open, even though I am clearly in the chat, because it didn't recognize being told it had joined a room.

My reading of [XEP 0045](http://xmpp.org/extensions/xep-0045.html) doesn't explicitly disallow what Slack is doing or how you are responding to it, but I think the XEP is underspecified here---it never thought about server-initiated channels. What you could do is handle that initial unexpected <presence> stanza the same as an expected one. You could also send back an error on it but then also pretend you got an <invite>, triggering an extra round-trip to probe the server and get the rest of the room roster properly. You could also do what Pidgin and Gajim do, which is drop these messages silently---and then I would be able to badger Slack and other gateways into being more standards compliant and damand that <invite> is the only supported kind of server-initiated join.

**Comment by iNPUTmice** [comment]
> the handle is null, and that is getting serialized to the string "null", which can't be what you intended.

can you provide a screenshot for this? Because with this stanza the nick should show as 'nick'.

**Comment by kousu** [comment]
I'm sorry, I haven't been able to reproduce this. It happened several times and never since then. Maybe the server got tweaked. I'm going to close this until I see it again.
