### ISSUE TITLE
Random DCs?

### ISSUE THREAD

**Issue by jsmith000** [siacs/Conversations#1699]
Heya,

I am not sure why but the app randomly DCs from jabber (I am using Duckduckgo's server) and unless I manually reconnect to it, it is not possible to receive or send any msgs. Sending msgs from the app will say "Wait.." under the msg while sending msgs from pidgin won't show me any error but I don't receive anything. I am using OTR if that matters.

Thank you!

**Comment by iNPUTmice** [comment]
duplicate of #1434
