### ISSUE TITLE
PGP key ID of q contact cannot be changed

### ISSUE THREAD

**Issue by bastoon06** [siacs/Conversations#1703]
If a contact changes his PGP key it seems not to be updatable in Conversation with OpenKeyChain.
The PGP key ID of the contact is stored on the contact data along with other information. But unlike the OTR fingerprints it cannot be deleted or subsituted.
Moreover, if you delete the key from OpenKeyChain and try to send an OpenPGP message to the related contact it will generate an online search with the original PGP key ID. If user change the search, the selected key won't be substituted.

**Comment by iNPUTmice** [comment]
Your contact needs to re-announce his or hers key. This is how PGP in XMPP works.

**Comment by bastoon06** [comment]
The key has been revoqued and I retrieved the new one in OpenKeyChain. My contact is using Conversation, how could he announce the new key?

**Comment by iNPUTmice** [comment]
Long press on the account in the account overview and select publish key

**Comment by bastoon06** [comment]
Great, thanks a lot.Sent from my Honor Mobile-------- Original Message --------Subject: Re: [Conversations] PGP key ID of q contact cannot be changed (#1703)From: Daniel Gultsch To: siacs/Conversations CC: bastoon06 Long press on the account in the account overview and select publish key
