### ISSUE TITLE
Offline messages are lost

### ISSUE THREAD

**Issue by philipflohr** [siacs/Conversations#1704]
Setup:
2 mobile devices running Conversations 1.9.4
1 prosody XMPP server (with autoloaded offline storage plugin using default settings)

1. Both devices are online. Send some messages (OEMO encrypted)
--> Messages are deliverd as expected
2. Disconnect one device 
3. Use the other device to send some messages
--> The messages appear as sended
4. reconnect the first device
--> The messages which were send while the device was offline do not appear
5. continue chatting with the two devices 
--> new messages are delievred as expected

--> After about one day the missing messages are marked as undelivered on the phone from which they were sent

**Comment by iNPUTmice** [comment]
You should use MAM and/or the smacks_offline module.
What I don't get is why it takes a day for the delivery failed to appear.
But this is a server problem.
