### ISSUE TITLE
Online status indicator not working anymore

### ISSUE THREAD

**Issue by nagua** [siacs/Conversations#1705]
Hey

since version 1.9.4 the online status indication is no longer working for me.
I can't see it via the send button and I can't see it as tags. The only contact working for me is my own contact in the list.
In Mirada IM I can see that the contacts are online.
I tried to downgrade to 1.9.3 but it crashed with the 1.9.4 data.

Do you need any more information for this?

Greetings
Nagua

**Comment by petmue** [comment]
Works for me with Conversations 1.9.4 and ejabberd 16.01.

Which server do you and your contacts use?

**Comment by nagua** [comment]
I'm also running ejabberd 16.01 and my contacts are on my server.
Yesterday I could see their status again after removing the right to see the online status and adding it again. But today I can't see the status again.

**Comment by S2-** [comment]
works for me too with prosody 0.9 and 1.9.4

**Comment by tmolitor-stud-tu** [comment]
I sometimes have the same issue. Some contacts don't show the correct online status.
I suspect this only happens with users using multiple clients. Maybe when one resource goes offline ore something like that.

System: current prosody 0.10 + conversations 1.9.4 (+ gajim 0.16.5 for users having multiple resources)

**Comment by iNPUTmice** [comment]
@tmolitor-stud-tu Do they show the wrong status in both Gajim and Conversations or only in Conversations?

**Comment by nagua** [comment]
The contacts that I refer to only use conversations and no other messager at the same time. When I log in via Miranda I can see that the person is online. But conversations shows the contact as offline.

**Comment by solariiknight** [comment]
Same trouble for me here. I'm using ejabberd 16.01-2 and conversations 1.9.4. I use multiple clients.

**Comment by petmue** [comment]
I have to change statement: One of the clients using Conversations 1.10.1 on Android 4.4.4 and ejabberd 16.01 does not see other specific clients online.

**Comment by tmolitor-stud-tu** [comment]
Only in conversations. The status in Gajim is as expected (online).

**Comment by tmolitor-stud-tu** [comment]
Okay. Now I have this problem with a chat partner only using Conversations exclusively.
I'm still using Gajim and Conversations at the same time though.

Could it be, that conversations doesn't handle carbon copied presence stanzas correctly?
In the Gajim XML-console I see the following:
`<!-- In Do 03 Mär 2016 08:28:38 CET -->`
`<presence to='tmolitor@example.org' from='otheruser@example.org/mobile'>`
`<c hash='sha-1' ver='awFXsZbojIZAIYyJ3DSTK++CZqY=' node='http://conversations.im' xmlns='http://jabber.org/protocol/caps'/>`
`</presence>`

This presence seems not to have reached Conversations somehow.

**Comment by nagua** [comment]
I have the problem me and chat partner using conversations exclusively.
So I can't think of problems with carbon copied presence stanzas.

**Comment by chaoscommander** [comment]
I'm on the same server as nagua and for me everyone except ICQ Transport contacts (maybe a hint to look at?) often disappears a few seconds after login. I never have more than one device online at a time. Conversations 1.11.2

**Comment by saqura** [comment]
61997912 solved this issue for me, so maybe give that a try. There might be multiple causes for this bug though depending on when the status is displayed correctly.

 >contacts often disappear a few seconds after login

I think this is the type of wrong status indication that should be fixed by the commit I linked.
