### ISSUE TITLE
support led blink on notification

### ISSUE THREAD

**Issue by S2-** [siacs/Conversations#1707]
My phone has a led, and when i get a message (notification) with whatsapp or telegram and the phone is in standby, the led starts to blink green. It does not do that with conversations. Would it be possible to make the led come on when a new notification is received by conversations?

**Comment by S2-** [comment]
maybe add something like
`mBuilder.setLights(Color.BLUE, 500, 500)`
in https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/services/NotificationService.java#L253
?

**Comment by S2-** [comment]
oh, i see it's already there: https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/services/NotificationService.java#L213
has to be a problem with my phone then? can I somehow help debug this?

**Comment by iNPUTmice** [comment]
I can't reproduce. So this is probably something with your device. I'm happy to merge a PR

**Comment by DianeRay** [comment]
Sorry about that, it was my mistake. I am very interested in your project. I am studying the source code.

Best Regards,
Ruikang Dai

**Comment by DianeRay** [comment]
Oh, I am wrong again.

**Comment by S2-** [comment]
it works now. i don't know. it fixed itself. we will never know what was wrong.
