### ISSUE TITLE
Feature Request: Conference Browser

### ISSUE THREAD

**Issue by jprjr** [siacs/Conversations#1708]
Hi there -

I've been using Conversations with Prosody and Spectrum2 and really enjoy it - I'm able to use one single app to stay connected with all my chat networks.

A really useful feature for my use-case would be a conference browser, under the conferences tab. Right now, Spectrum2 doesn't seem to auto-invite me into group chats, but they are available if I use something like Pidgin's XMPP Service Discovery tool to browse components. Having Conversations query my connected chat servers for available conferences (instead of just showing what I've bookmarked) would be great, because then I could join my group chats.

**Comment by andersruneson** [comment]
Duplicate.

**Comment by jprjr** [comment]
Apologies! I didn't see the other open issue (https://github.com/siacs/Conversations/issues/279) - closing.
