### ISSUE TITLE
Allow sending messages when role="visitor"

### ISSUE THREAD

**Issue by kousu** [siacs/Conversations#1710]
If you go into a room and are told you're `role="visitor"`, Conversations cleverly disables the text input box and says "You are not participating" in it.  It's **too** clever: the MUC spec [says](http://xmpp.org/extensions/xep-0045.html#roles-priv)
> ** An implementation MAY grant voice by default to visitors in unmoderated rooms.

I am writing an IRC transport, and mapping `+v`/`-v` to `"participant"`/ `"visitor"`. It is typical in IRC for most users to be voiceless but still be able to talk. By locking out the input bar, Conversations can't communicate in channels that other clients---Pidgin and Gajim for starters---can.  I can just lie (this is what  biboumi and ejabberd's mod_irc do) and claim everyone is a `"participant"`, but that's losing social information. Mind you, it's cliquey, social hierarchy information, but it's still information and if people choose to use it I want to offer them access to it.

Conversations locks the bar even if the room is unmoderated, which is the equivalent of a stand:
```
RECV: <iq id="j9vhg1712i" to="test@irc.galleon" type="get" from="kousu@galleon/conversations"><query xmlns="http://jabber.org/protocol/disco#info" /></iq>
Received disco info query from <kousu@galleon/conversations> to <test@irc.galleon>.
SEND: <iq type="result" id="j9vhg1712i" to="kousu@galleon/conversations" from="test@irc.galleon"><query xmlns="http://jabber.org/protocol/disco#info"><identity category="conference" name="test" type="text" /><feature var="http://jabber.org/protocol/muc" /><feature var="muc_nonanonymous" /><feature var="muc_unmoderated" /></query></iq>
RECV: <presence to="test@irc.galleon/kousu" from="kousu@galleon/conversations"><x xmlns="http://jabber.org/protocol/muc"><history since="2016-02-20T09:35:14Z" /></x></presence>
```

Pidgin and Gajim send messages regardless, and if the server rejects them then tough luck. That's one approach. Arguably you are more spec-compliant by locking the bar, since if the server claims the room is moderated and you're not a participant then it also shouldn't accept your messages so why bother trying? But the spec does allow visitors to talk sometimes, and I am one of the 2% who will ever use this feature.

**Comment by iNPUTmice** [comment]
fixed in ed740b4868884b159cce284ebfbd80cefc904520

**Comment by kousu** [comment]
That was so fast.  Thank you!

**Comment by kousu** [comment]
I have Conversations 1.10.1 and the patch is glitchy.

The first time I join an unmoderated room where I'm `role="visitor"`, I can type.
If I open a different room, and then come back to the unmoderated room, I suddenly can't. It's like `hasFeature("muc_unmoderated")` is getting forgotten.
If I leave the room and rejoin it from my bookmarks, I can type again.
If I leave the room and press the "Undo" button on the bubble that appears, I cannot.

Also it says "You are not participating" in the input box no matter what the state is. That fits with me not being a participant---not a participant == not participating---I suppose, but it feels wrong.  I think it should only say that text it locks me out, and otherwise fall back on the normal "Send unencrypted message".

**Comment by iNPUTmice** [comment]
Is this transport running somewhere so I can easily use it? If not you might have to debug this yourself since the code looks right to me.

The XmppConnectionService has a method called fetchConferenceConfiguration()
You can start there and try to see if 'muc_unmoderated' actually gets received and parsed correctly.

**Comment by iNPUTmice** [comment]
FWIW I tried to replicate this and didn't find anything wrong. I can write in fine in a conference when it sets muc_unmoderated idenpentend of my role.

However latest HEAD prints the muc configuration to adb logcat. So it should be easier for you to debug.

**Comment by kousu** [comment]
That's a kind offer of you.  It's a toss up but I think it will be quicker if I zero in on the issue with both sides of the code in hand.  I'll take a look at logcat, and hopefully isolate a test case of stanzas that trigger it.
