### ISSUE TITLE
Multi-client OTR

### ISSUE THREAD

**Issue by Aeyoun** [siacs/Conversations#1711]
Conversations asks me to “Choose a presence” when sending a OTR message to a contact that is connected on multiple clients. I want to send it to all of that contact’s clients as usual. The [OTR protocol supports this](https://lists.cypherpunks.ca/pipermail/otr-announce/2012-September/000058.html), so this looks like an arbitrary limitation set by Conversations. Please support this feature as I have no idea which of my clients my friends are actively using at any given time.

**Comment by iNPUTmice** [comment]
No it does not.

OTR was never made for XMPP. It does not provide multi-end-to-multi-end encryption. You should be using OMEMO encryption for this.
