### ISSUE TITLE
Handle all the exit codes

### ISSUE THREAD

**Issue by kousu** [siacs/Conversations#1712]
There's a [bunch](http://xmpp.org/extensions/xep-0045.html#registrar-statuscodes) of [reasons](http://xmpp.org/extensions/xep-0045.html#destroyroom) why you might be removed from a MUC. If I send any of them (tested: 322, 332, `<destroy>`), except for kick (307) I see "Unknown error received  [Try Again]". Ideally this message would say something appropriate to each status code/`<destroy>` stanza, but at the very least it should read "You are no longer in this conference [Join]". "[Try Again]" is unclear.

Even more ideally, any `<presence type="unavailable">` that tells Conversations its own nick is out should trigger this fallback message.

**Comment by iNPUTmice** [comment]
fixed in a0d0ed34ae38f2377fdb3ad2c661b74b85f2df28

**Comment by kousu** [comment]
Wow, that was quick.  Thank you!

Does this handle <destroy>?
