### ISSUE TITLE
Is it possible realtime voice chatting?

### ISSUE THREAD

**Issue by snowww1014** [siacs/Conversations#1714]
I love this app and I want my chatting app having realtime voice chatting function.
Can I implement this function by using Conversations app?

Best regards.

**Comment by jkufner** [comment]
This feature request has been there a few times, but it is a bit too complicated and developers' focus is on excellent text chat.

Anyway if you want to implement it, it should be possible to do so as standalone plugin (there are at least two already to start with, but none for voice chat).

However, Android phones know SIP, so there is another way to (video)call already.

**Comment by snowww1014** [comment]
Thank you, jkufner.
I am gonna realize this with voip and then integrate with openfire server.
Is it possible?
Which app is the best for xmpp & sip?
