### ISSUE TITLE
Extremely high data usage

### ISSUE THREAD

**Issue by damonsmith** [siacs/Conversations#1716]
I have conversations installed with a HipChat (xmpp) account for work and it seems to have used 1.39 GB of data in less than a month, with only a few messages and group chats with a pretty low message volume. I would have expected more like in the tens of megabytes, not the thousands. Is there any way to get a view of how many messages are going through and what size they are? Maybe I'm getting all messages for all rooms in hipchat or something.

**Comment by iNPUTmice** [comment]
Have a lock at adb logcat. (See FAQ 'How do i debug Conversations') Maybe it is repeating a specific action over and over again.

**Comment by hanswundersam** [comment]
I know this issue is old (probably because not many people use Conversations with Hipchat), but I encounter the exact same problem today. Conversations used almost 1 GB of my mobile data in less than a month.

**App:** Conversations 1.23.8 (from F-droid) 
**OS:** LineageOS 14.1-20180124-nightly (Android 7.1.2); no Google Play Services installed
**Device:** LG Nexus 5

`adb logcat | grep conversations` tells me:

```
03-14 17:59:56.610 12052 22617 D conversations: XXXXXXX@chat.hipchat.com: xml parser mishandled SSLException(Read error: ssl=0x95e1cac0: I/O error during system call, Connection reset by peer)
03-14 18:00:06.630 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: connecting
03-14 18:00:06.883 12052 28595 D conversations: Resolver: [Result{ip='null', hostame='chat.hipchat.com', port=5222, directTls=false, authenticated=false, priority=1}]
03-14 18:00:06.942 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: using values from dns chat.hipchat.com:5222 tls: false
03-14 18:00:07.714 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: TLS connection established
03-14 18:00:07.833 12052 28595 D conversations: XXXXXXX@chat.hipchat.com/conversations_proxy|pubproxy-d100_proxy|pubproxy-d100_proxy|pubproxy-d100_proxy|pubproxy-d100_proxy|pubproxy-c100_proxy|pubproxy-c100_proxy|pubproxy-c100_proxy|pubproxy-c100_proxy|pubproxy-d100_proxy|pubproxy-b100_proxy|pubproxy-d100_proxy|pubproxy-b100_proxy|pubproxy-d100_proxy|pubproxy-d100_proxy|pubproxy-d100_proxy|pubproxy-b100_proxy|pubproxy-c100_proxy|pubproxy-d100_proxy|pubproxy-c100_proxy|pubproxy-b100_proxy|pubproxy-d100_proxy|pubproxy-b100_proxy|pubproxy-c100_proxy|pubproxy-d100_proxy|pubproxy-c100_proxy|pubproxy-b100.hipchat.com|5292_proxy|pubproxy-d100.hipchat.com|5272_proxy|pubproxy-b100.hipchat.com|5252||proxy|pubproxy-b100.hipchat.com|5272: Authenticating with PLAIN
03-14 18:00:08.071 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: logged in
03-14 18:00:08.627 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: sending legacy session to outdated server
03-14 18:00:08.753 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: starting service discovery
03-14 18:00:08.754 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: do not wait for service discovery
03-14 18:00:08.755 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: online with resource conversations_proxy|pubproxy-d100_proxy|pubproxy-d100_proxy|pubproxy-d100_proxy|pubproxy-d100_proxy|pubproxy-c100_proxy|pubproxy-c100_proxy|pubproxy-c100_proxy|pubproxy-c100_proxy|pubproxy-d100_proxy|pubproxy-b100_proxy|pubproxy-d100_proxy|pubproxy-b100_proxy|pubproxy-d100_proxy|pubproxy-d100_proxy|pubproxy-d100_proxy|pubproxy-b100_proxy|pubproxy-c100_proxy|pubproxy-d100_proxy|pubproxy-c100_proxy|pubproxy-b100_proxy|pubproxy-d100_proxy|pubproxy-b100_proxy|pubproxy-c100_proxy|pubproxy-d100_proxy|pubproxy-c100_proxy|pubproxy-b100.hipchat.com|5292_proxy|pubproxy-d100.hipchat.com|5272_proxy|pubproxy-b100.hipchat.com|5252_proxy|pubproxy-b100.hipchat.com|5272||proxy|pubproxy-c100.hipchat.com|5282
03-14 18:00:08.755 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: fetching roster version 2018-03-11T09:40:22Z
03-14 18:00:08.909 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: could not query disco info for XXXXXXX@chat.hipchat.com
03-14 18:00:09.090 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: joining conversation XXXXXXX@conf.hipchat.com/XXXXXXX
03-14 18:00:09.102 12052 12200 D conversations: skipping shortcut update
03-14 18:00:09.103 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: fetched muc configuration for XXXXXXX@conf.hipchat.com - [http://jabber.org/protocol/muc, muc_membersonly]
03-14 18:00:09.104 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: joining conversation XXXXXXX@conf.hipchat.com/XXXXXXX
03-14 18:00:09.108 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: fetched muc configuration for XXXXXXX@conf.hipchat.com - [http://jabber.org/protocol/muc, muc_membersonly]
03-14 18:00:09.108 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: joining conversation XXXXXXX@conf.hipchat.com/XXXXXXX
03-14 18:00:09.112 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: fetched muc configuration for XXXXXXX@conf.hipchat.com - [http://jabber.org/protocol/muc, muc_membersonly]
03-14 18:00:09.113 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: joining conversation XXXXXXX@conf.hipchat.com/XXXXXXX
03-14 18:00:09.116 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: fetched muc configuration for XXXXXXX@conf.hipchat.com - [http://jabber.org/protocol/muc, muc_membersonly]
03-14 18:00:09.197 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: joining conversation XXXXXXX@conf.hipchat.com/XXXXXXX
03-14 18:00:09.201 12052 28595 D conversations: XXXXXXX@chat.hipchat.com: fetched muc configuration for XXXXXXX@conf.hipchat.com - [http://jabber.org/protocol/muc, muc_membersonly]
03-14 18:00:09.283 12052 28595 D conversations: skipping duplicate message with XXXXXXX@conf.hipchat.com/XXXXXXX. serverMsgIdUpdated=false
03-14 18:00:09.288 12052 28595 D conversations: skipping duplicate message with XXXXXXX@conf.hipchat.com/XXXXXXX. serverMsgIdUpdated=false

```

The last two outputs "skipping duplicate message" are then repeated about 50 times for all my chat partners. This complete output happens about every 3 minutes no matter if Conversations is in foreground or not. 

My suspicion is that it might have to do with Android energy saver killing the XMPP connection every few minutes but I am really no expert. I switched off the Android energy saver mechanism for Conversations to see if it makes any difference and will report back. 

But it could of course also be linked to how Hipchat implements XMPP right? Thanks for letting me know if you see anything in this logcat.

**Comment by hanswundersam** [comment]
Unfortunately, deactivating Android's energy saver did *not* stop the error messages above to reappear every few minutes. It kind of looks as if the server disconnects and then Conversations reestablishes the connection (and perhaps downloads a whole lot of data at that moment)...

**Comment by SamWhited** [comment]
> But it could of course also be linked to how Hipchat implements XMPP right?

This is most likely a HipChat problem, unfortunately they're dropping XMPP/third party client support from the cloud version anyways; server will continue to use XMPP, though it's not likely to fix this.

> repeated about 50 times for all my chat partners

Are these all MUCs? I'm guessing that if you count this it will end up being at most 75 times per room (this is the amount of backlog it sends by default). If so, they're most likely not going to fix this, but it's also probably not the issue and will only happen when you first join a MUC (and every time you reconnect).

**Comment by iNPUTmice** [comment]
Apparently HipChat will close the TCP connection after 150s of inactivity and they suggest to ping every 60s.
Probably not really worth pursuing. Pinging every 60s will even be impossible on most modern Androids and borderline insane on the older ones.

**Comment by hanswundersam** [comment]
Sorry for the late reply and thank you very much for your replies @iNPUTmice and @SamWhited. Pity that everyone seems to close up their services... :(
