### ISSUE TITLE
XEP-0308 is enabled with OMEMO by default

### ISSUE THREAD

**Issue by xnyhps** [siacs/Conversations#1720]
I've just updated to 1.10.0 and noticed Conversations now supports [XEP-0308 Last Message Correction](https://xmpp.org/extensions/xep-0308.html). XEP-0308 seems to also work when OMEMO encryption is enabled (I didn't test with OTR or PGP), which is a bad idea for the following reasons:

* A malicious server can inject a `<replace xmlns='urn:xmpp:message-correct:0' id='1234'>` into an OMEMO encrypted message to hide the message with id 1234. There's no way to find out what the message did say as the original is not visible, even if "Allow message correction" is turned off later.
* A malicious server can inject a `<replace xmlns='urn:xmpp:message-correct:0' id='1234'>` into an OMEMO encrypted message when the message with id 1234 is scrolled out of view, hoping to make this message go unnoticed (there appears to be no notification of a correction, though the conversation is marked as having unread content).
* Possibly a minor issue, but it reveals to servers which messages are corrections of each other.

Luckily, it seems that replacing a message with a message from a different OMEMO endpoint or with an unencrypted message isn't allowed.

The server can of course already drop arbitrary messages and reorder them, however, Axolotl should be able to recover from reorderings and inform the user when some messages are missing. With XEP-0308, this guarantee is now broken.

**Comment by iNPUTmice** [comment]
You are right.

> I didn't test with OTR or PGP

It's the same. Actually the situation is slightly worse because because it does check the fingerprints (yet).

So the only winning move here is to disallow message correction entirely. Message correction is already opt-out. So maybe we should make this opt-in?

**Comment by QuentinC** [comment]
Wow,
I clearly understand why not enabling this by default, but isn't there a better way to do this ?

Some people never get into settings, and will never use this functionality, this is too bad I think...

**Comment by d9h02f** [comment]
I doubt anyone really uses this anyway. Why it's even necessary when just sending _*word_ after you sent _wrod_ already easily gets the point across is beyond me.
