### ISSUE TITLE
sync remote http_uploads files || distributed history

### ISSUE THREAD

**Issue by bastlwasti** [siacs/Conversations#1727]
hello,

my problem is that some users upload their files to jabber servers (e.g. jabber.de) where the uploads are deleted after a while. Thus, I got my messages on the MAM server, and the files of all the users who use my jabber sever too, but other http uploades files of other users are lost, or I would need to sync somehow the http upload files present on my smartphone with my http server.... in short, some parts are saved locally, some also on my server,... 

are there any plans to implement a way to sync the whole history in one way or other?

best greets

**Comment by lovetox** [comment]
without saving the pictures forever on the server (nobody wants that) personally i have no idea how you could achieve something like that.

**Comment by iNPUTmice** [comment]
This is a bug tracker and not a forum. There is a conference available if you have general questions.
