### ISSUE TITLE
Conversations partially ignores the nick sent to it

### ISSUE THREAD

**Issue by kousu** [siacs/Conversations#1732]
In continuing my gateway adventures, I am explicitly disallowing joining a MUC to change your IRC nick---unlike, say, ejabberd's mod_irc, which caused me no end of grief in constantly bouncing on and off IRC and changing my identity if I wasn't very careful.  But this means that my gateway replies to clients with a nick they don't think they have.  I've found that Conversations partially respects and partially rejects this, so there must be some glitchiness hiding. Here's a sniff of a join log (from Pidgin, but it shows the same stanzas you'd expect) 
```
<presence to='#hurrrrr@conference.znc.kousu.ca/nick'>
	<priority>1</priority>
	<c xmlns='http://jabber.org/protocol/caps' node='http://pidgin.im/' hash='sha-1' ver='AcN1/PEN8nq7AHD+9jpxMV4U6YM=' ext='voice-v1 camera-v1 video-v1'/>
	<x xmlns='http://jabber.org/protocol/muc'/>
</presence>
<message type='chat' to='nick@kousu.ca' from='znc.kousu.ca'>
	<body>WARNING: You are trying to join #hurrrrr as nick, but you are already signed into the server as kousu. If you wish to change your nickname, use /nick or /register. You will be joined to the channel as kousu.</body>
</message>
<presence to='nick@kousu.ca' from='#hurrrrr@conference.znc.kousu.ca/kousu'>
	<x xmlns='http://jabber.org/protocol/muc#user'>
		<item jid='kousu@znc.kousu.ca' role='moderator' affiliation='member'/>
		<status code='110'/>
	</x>
</presence>
<iq type='get' id='purple6ba18dca' to='#hurrrrr@conference.znc.kousu.ca'>
	<query xmlns='http://jabber.org/protocol/disco#info' node='http://jabber.org/protocol/muc#traffic'/>
</iq>
<presence to='nick@kousu.ca' from='#hurrrrr@conference.znc.kousu.ca/kousu'>
	<x xmlns='http://jabber.org/protocol/muc#user'>
		<item jid='kousu@znc.kousu.ca' role='moderator' affiliation='member'/>
		<status code='110'/>
	</x>
</presence>
```

That `<status code='110'/>` tells the client who it is. It asked to join as #hurrrrr@conference.znc.kousu.ca/nick and was told it was #hurrrrr@conference.znc.kousu.ca/kousu.

Conversations displays this result in its GUI:

![c87c0d62-0c4e-4d54-a98c-a52b335ed8d3](https://cloud.githubusercontent.com/assets/987487/13395712/89b2db5e-debe-11e5-95a9-fac89ac657a2.jpg)

But it ignores that information when it parts, still thinking it is "nick"
```
<presence to='#hurrrrr@conference.znc.kousu.ca/nick' type='unavailable'/>
<message type='chat' to='nick@kousu.ca' from='znc.kousu.ca'>
	<body>WARNING: Parting #hurrrrr as nick, but you are signed into the server as kousu.</body>
</message>
```

I would expect that to say `<presence to='#hurrrrr@conference.znc.kousu.ca/kousu' type='unavailable'/>`, since it was told that that was its nick.

(Pidgin has the same issue, but Pidgin doesn't even try to show you which nick is yours; the only reason what you type says it's from you is that it's up to the server to decide what your nick is and to echoes to echo back)

**Comment by kousu** [comment]
I've looked closer at the spec and it is vague, but I think it says you're supposed to look for code 210 to change a roomnick. It seems awful fragile, since code 110 is supposed to mean both "end of room roster" *and* "this is your self-presence", which overlaps with the meaning of 210.

Under [Example #22](http://xmpp.org/extensions/xep-0045.html#enter-pres):
> The service MAY rewrite the new occupant's roomnick (e.g., if roomnicks are locked down or based on some other policy).

and then it detours through " Service Denies Room Join Because Roomnicks Are Locked Down" and then to in "Service Sends New Occupant's Presence to New Occupant" it shows 210 being used:
```
<presence
    from='coven@chat.shakespeare.lit/thirdwitch'
    id='n13mt3l'
    to='hag66@shakespeare.lit/pda'>
  <x xmlns='http://jabber.org/protocol/muc#user'>
    <item affiliation='member' role='participant'/>
    <status code='110'/>
    <status code='210'/>
  </x>
</presence>
```

It also uses 210 for "Example 51. Occupant Changes Nickname, Modified by Service".

Personally, I would just assume whatever nick is in the 110 presence is the nick to use. If that nick differs from what you had before, you can fire update handlers. It shouldn't have to be sent along in the protocol, or at least it should only be to give user feedback. But maybe you want to be pickier about the spec than I do.  I don't think any client has gotten this part of the spec fully right.

**Comment by iNPUTmice** [comment]
I think 210 never goes alone. It goes on top of 110 to inform you that a server has changed the nick. So listening on 110 seems totally fine if you don't care about the information whether it was you or the server who decided upon the nick.

**Comment by kousu** [comment]
That makes a lot of sense to me! 

Gajim disagrees. If there's a nick mismatch it hangs until I send 210. I ~~think~~hope it is the only one that cares.

**Comment by kousu** [comment]
I've found another bug which I *think* but am not sure is the same as this. I would like to report it here just in case this patch doesn't take care of it.

If Conversations tries to join a room as one nick but receives a room roster that contains that nick *which is not itself* (i.e. not the one with `<status code=110>`), then it can send and receive messages (which show up from the correct nicks, because the room is in control of each message) to the room but the roster list under Conference Details is empty.

Here's a log (as seen by my server, so sending and receiving are reversed).
```
RECV: <presence to="#test2@conference.irc/anna" id="gajim_muc_68_a9ae82" xml:lang="en" from="kousu@galleon/Gajim"><x xmlns="vcard-temp:x:update" /><c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="http://gajim.org" ver="OHkcneXc9eqyD5VIJDibu4fR0QY=" /><x xmlns="http://jabber.org/protocol/muc"><history since="2016-03-06T19:27:25Z" maxstanzas="20" /></x></presence>

SEND: <presence to="kousu@galleon" from="#test2@conference.irc/anna"><x xmlns="http://jabber.org/protocol/muc#user"><item role="moderator" affiliation="member" jid="anna@irc" /></x></presence>
SEND: <presence to="kousu@galleon" from="#test2@conference.irc/kousu"><x xmlns="http://jabber.org/protocol/muc#user"><item role="visitor" affiliation="member" jid="kousu@galleon" /><status code="100" /><status code="110" /><status code="210" /></x></presence>
```

Notice that Cnversations wants to be `#test2@conference.irc/anna`, but is told that while there exists `#test2@conference.irc/anna` that it is `#test2@conference.irc/kousu`. Here's the result:
![](https://cloud.githubusercontent.com/assets/987487/13558129/97cf405e-e3ca-11e5-8f86-803a44490bba.jpg)

**Comment by iNPUTmice** [comment]
Yes this is totally a bug. Thank you for pointing this out.
It happens because Conversations looks for two conditions: Is the presence our original join-nick or does the presence contain the the status code 110. In both cases it assumes the presence is our presence. So both presences are considered self presences. In your case this is obviously incorrect. However I believe the code is in there because some (very old) MUC servers don't use the status codes.

So I have to be careful when changing this.



By the way: This seems to be very good work you are doing there. Is this going to be open source? Is there somewhere I can find more information about your project?

**Comment by iNPUTmice** [comment]
Looked this up pretty quickly. It seems that status codes where only added in 2006. So removing the one condition would basically break all servers that are older than that. Not saying I wont do it just mentioning it here for the record.

**Comment by kousu** [comment]
Thank you!  I'm working at https://gitlab.com/kousu/ircgate. It's on top of [Slixmpp](http://slixmpp.readthedocs.org/) and [irc3](https://github.com/gawel/irc3/). It'll be BSD or so. I haven't publicized it yet because I'm writing it out of a cranky itch that the other IRC gateways gave me, and I feel a bit rude about it so I'm making up for that by polishing it to make it clear what I'm doing differently. Like, I think IRC nicks should get first-class JIDs, and that bouncing should be built in because MUC history/offline messaging is built in to XMPP (and more importantly, people get really mad at you when your phone bounces on and off and on and off and on and off their IRC channels).

I have managed to use it to rig up Facebook (via [bitlbee](https://wiki.bitlbee.org/HowtoFacebookMQTT)) back to XMPP like it used to be, which works remarkably well considering how sketchy my code is right now and how absurd daisy chaining IM systems is :)
