### ISSUE TITLE
[Feature Request] Implement XEP-0013

### ISSUE THREAD

**Issue by petmue** [siacs/Conversations#1734]
Please implement XEP-0013: Flexible Offline Message Retrieval [1]

ejabberd supports it officially since version 16.02 [2]:
– Support for flexible offline retrieval, aka XEP-0013. This is a big win for mobile developers.

[1] http://www.xmpp.org/extensions/xep-0013.html
[2] https://blog.process-one.net/ejabberd-16-02-happy-leap-day/

**Comment by iNPUTmice** [comment]
What problem exactly is this trying to solve?

**Comment by devurandom** [comment]
I assume that the user could decide not to download offline messages on expensive mobile connections. E.g. if they usually receive large amounts of offline messages.

**Comment by petmue** [comment]
> I assume that the OPs suggestions is that the user could decide not to download offline messages on expensive mobile connections. E.g. if they usually receive large amounts of offline messages.

Yes. Flexible Offline Message Retrieval provides a method for a finer control of the delivery of offline messages during a client's login. It allows a client to check the quantity of offline messages, and fetch and remove the specific or all messages.

It'd be useful at least to me.

**Comment by jkufner** [comment]
To be honest, I never needed such thing. Since at least one of my clients is regularly logged in, the amount of offline messages is never large enough to bother me.

Useful feature could be to mark messages as unread when I do not want to deal with them instantly, so I get another notification on desktop later. Or at least do not mark them as read until I really see the conversation. However, I'm not sure how exactly it behaves right now.

**Comment by iNPUTmice** [comment]
@petmue so do you regularly have thousands of offline messages?

Usually Conversations goal is to catch up with all messages that were sent while it was offline (through the means of MAM)

I'm on the verge of closing this issue since I suspect most users actually want to have a full history.

**Comment by lovetox** [comment]
in today times, there is probably not even a long timespan where you are "offline" especially not with a smartphone, and this will get even more rare.
