### ISSUE TITLE
Avatar Error 

### ISSUE THREAD

**Issue by vivekebics** [siacs/Conversations#1738]
I can't get avatars working. It's getting really frustrating. Sometimes it works. Please help me to address it.Thank You

**Comment by andersruneson** [comment]
More info needed.
One-on-one chat? Muc? Anonymous muc?
Pep avatars or vcard?

**Comment by petmue** [comment]
Personally I experience a similar issue using
`ejabberd 16.02`, `Conversations 1.10.2`, `One-on-one-Chat`, `pep`

My own avater always shows up, as well as the avatar of a friend who uses jabber.ccc.de.
However, I don't see the avatars of other users from the server I use.
And here's what's so weird about it: The other participants on the server do not face this issue as far as I know.

Is there any way to debug this?

**Comment by andersruneson** [comment]
Could be that your contacts use a client without pep avatar support?

**Comment by petmue** [comment]
> Could be that your contacts use a client without pep avatar support?

They all use the latest version of Conversations and granted the access to share their avatars.

**Comment by iNPUTmice** [comment]
> However, I don't see the avatars of other users from the server I use.

maybe the pep storage is broken on your server

**Comment by petmue** [comment]
I think this somehow related to https://github.com/siacs/Conversations/issues/1738
After an avater got republished, it's displayed again.

**Comment by iNPUTmice** [comment]
No reaction from op. And not a proper bug report but rather a question that should belong into the conference. Closing.
