### ISSUE TITLE
SUGGESTION to avoid "delivery failed" some minutes after recipient went offline (but is still recognized as online)

### ISSUE THREAD

**Issue by therob84** [siacs/Conversations#1742]
After having from time to time "delivery failed" error in Conversations 1.10.1 (jabber.de), I think I got yesterday a hint, from where the problem comes and I want to know if it can be fixed by you conversations-guys or what the background is. I already read the paragraph at the [conversations page](https://conversations.im/) and have the following thoughts:

I sent a message from device1 to device2 (via OMEMO, both at jabber.de, both at good WLAN) in two cases: 
a) 10 seconds after I disabled device2s WLAN (no internet connection anymore)
b) 1 min after I disconnected the accound of device2 via the "account" menu of conversations

My observations:
- In both cases the status of device2 was still green/yellow while sending (active/away) with device1
- In both cases I got the message "delivery failed" after something between 10-60 minutes
- in both cases the message was true: the message was not delivered, also after setting device2 online again after some hours.

**My question is now (regarding a bug/improvement/feature request)**
- Why the error also occurs when I properly disconnect the accound of device2? Why device1 not immediately recognizes device2 as offline?
- Where is the "time frame" defined/set/adjusted in which the recipient has the time to collect the message, before it will be seen as "failed"? Is it a the server, or in conversations?

**Idea for solution:**
Could be the following way possible to implement in conversations (if the problem can not be solved at the server side):
- If Conversations received a "delivery failed" message, the message should not be discarded completely  (as it is now) but Conversations should check whether the contact is now **really** recognized as "offline" and just send the message again - now as a **real "offline" message** which then for sure will be delivered, after device2 is online again.

It seems, that a real "offline"-message (with omemo) is more relieable delivered, than a message with a buggy connection or shortly after a lost connection of the recipient. In my opinion this should definitively not be the case and could be solved with my above raised suggestion.

**What dou you say? Did I oversaw anything?**

Would be glad if you could implement it or provide another solution, as I find it until now not very relyful if I don't know if the message is sent or not. I will only see the error message, if I check conversations the next time....which easily cann only the next day...than it could be to late

The only positive about this problem is, that I can definitively trust this error message and that we can also see it under the messages text and try again. 

Hope for a solution or good explanation. Cheers, Robert

**Comment by iNPUTmice** [comment]
This has been discussed several time. Search the issue tracker for 'delivery failed' or something.
