### ISSUE TITLE
Automatic avatar republishing

### ISSUE THREAD

**Issue by mt403** [siacs/Conversations#1744]
It would be nice if conversations was able to republish the avatar in case the server was restarted/rebooted. Don't know if this is possible somehow.

**Comment by steffanson** [comment]
Or at least to republish the avatar manually. Current state is that the "publish" button is grayed out until the same or a new image is chosen again.

**Comment by tmolitor-stud-tu** [comment]
Right, that would be a very nice feature.
On my prosody 0.10 server I solved this issue by using mod_pep_vcard_avatar (see: https://modules.prosody.im/mod_pep_vcard_avatar.html) which transfers avatars published via PEP to the user's vcard (and vice versa).
Conversations supports reading avatars from user's vcards, so this plugin makes the avatar persistent across server reboots.

**Comment by mt403** [comment]
@tmolitor-stud-tu thanks for the hint, it's a nice workaround but raises another issue.

Since conversations publishes avatars only in webp format this breaks interop with a lot of clients.
XEP-0084 requires to publish a png version of the avatar to avoid exactly this.

https://xmpp.org/extensions/xep-0084.html#proto-info

**Comment by tmolitor-stud-tu** [comment]
@mt403 oh, I see. As I'm only using Conversations and Gajim, this is not so much an issue for me, but for others it can be.

It would be very nice if Conversations would drop the webp format and use the correct format required by the XEP (which is png). All other clients do this, too, so it clearly is possible.

**Comment by therob84** [comment]
+1 to make the "Publish" button always clickable to allow for "Re-Publish" the avater picture!
Or make it automatically, if avater is lost on server.

Furthermore: I can still see my avatar in Conversations while my contacts do not see the avater picture anymore (e.g. after server restart). There is no way to check in Conversations manually, if my avater is vanished at the servers' side. ...But it should be possible!

Changelog of 1.11.4: "Improved broken PEP detection"
Is this connected with #1744 and what was done there?

**Comment by iNPUTmice** [comment]
closed by: 7ff890e513212f1cf03667e4ea7e429431d811c4

**Comment by therob84** [comment]
I can confirm that my avatar is republished without doing anything exept updating to 1.11.7., although it is not mentioned explicitely in the changelog... Thanks for this!

Only a manual re-publishing is not possible, but if the automatic one is working properly (as it seems) it should be in deed not neccassary.
