### ISSUE TITLE
Precise error message on failed file transmission (eg file too large)

### ISSUE THREAD

**Issue by steffanson** [siacs/Conversations#1745]
Currently Conversation only says "transmission failed" if a file sent over HTTPUpload was too large and leaves the user confused.

However, it could precise the error message when a server responds with an accurate error message as it is defined in XEP-0363: http://xmpp.org/extensions/xep-0363.html#errors

I would appreciate it if these error states (unknown, too large, quota reached, premium only, ...) could be implemented on the client side. Is there anything planned?

**Comment by tmolitor-stud-tu** [comment]
Yes, I would like to see this, too.
A friend of mine got very confused when she tried to send me a video which was too large.
Definitely something that should be changed/made more clear.

**Comment by iNPUTmice** [comment]
If the server reports this you can now view this by long pressing and selecting 'show error'
