### ISSUE TITLE
Share File/Image in MUC

### ISSUE THREAD

**Issue by kruks23** [siacs/Conversations#175]
Hi,

Is nowadays possible to share images in multiuser chat? If it is possible it would be a great feature to add to Conversations.

**Comment by someone672388** [comment]
The lack of this feature might be more of a problem than you realize. I would really appreciate if a priliminary solution would be found. As mentioned by @iNPUTmice there is always the option to send it directly to every group member. (ofc. up until a maximum)

**Comment by ixti** [comment]
@SamWhited Good to know. Thanks. Showing a notification isn't an issue IMO, upon attempt to upload an image/other data it can show a popup dialog asking which service user wants to use, so that it will not get "silently" becoming public...

@someone672388 :+1:

**Comment by JannisHeinen** [comment]
This point is also very important to me to convince "Whatsapp'ler" to change to Jabber/Conversations. 
We will have small conferences with about 5-10 participants. And I have to find a solution for our company. 
Will Conversations be able to send images into conferences in near future? 
How long will this approximately take?

**Comment by moshpirit** [comment]
I think that if you're are representing here a company, maybe you could see to make a donation for focusing on this question as an inversion.
And you're right, sharing files in MUC and Legacy XEP for file sharing are the two most important points IMO.

**Comment by JannisHeinen** [comment]
I think it's very hard to convince a company not to use Whatsapp and to use Conversations/Jabber instead. No good arguments would be to ask them at the beginning to pay to get the software ready. They would say "The hell with you ... Whatsapp is ready".
You understand what I mean.
Conversations is worth to donate for and I will do my very best afterwards when I was able to confince them installing Conversations.

But missing this feature I am concerned that companies and conferences are not the target-group of Conversations. Till now I have bought a handfull of licences privately to test conversations. I will test it some more days and will observe the development.

**Comment by plsng** [comment]
The most convincing argument is that Conversations is free software and you can host your own servers, whereas WhatsApp is proprietary and everything you send through it is on their servers. Not very good for a company, I'd say.

**Comment by moshpirit** [comment]
Well, technically, they don't "save" this content in their servers, but they can change the term and conditions whenever they want. But yes, it's basic for a company to control this kind of information.

**Comment by iNPUTmice** [comment]
> Will Conversations be able to send images into conferences in near future?

yes.


>How long will this approximately take?

This is probably gonna be the next big thing after 1.0 has been released. However I won't give hard ETAs unless someone pays for them.

**Comment by ixti** [comment]
@plsng I might have been dealing with bad companies before, but none of them were really caring about "where" the stuff is stored. All main players provide privacy policies which seems like more than enough for many companies.

Although I *REALLY* want this feature, I completely understand (and share this POV) that:

> won't give hard ETAs unless someone pays for them

**Comment by moshpirit** [comment]
Excuse my ignorance but, what's an EPA?

**Comment by ixti** [comment]
[ETA](http://www.abbreviations.com/ETA) in this case is Estimated Time of Arrival. In other words: soft deadline.

**Comment by ixti** [comment]
Or I horribly misunderstood you...

**Comment by moshpirit** [comment]
Ok, thanks!

**Comment by d00de** [comment]
I doubt implementing this is much of a challenge. It is very bad practice to expect money for a feature that is of absolute necessity.

**Comment by plsng** [comment]
d00de: if it's not much of a challenge, feel free to do it yourself!

**Comment by JannisHeinen** [comment]
I do understand the developer who want's to be paid for extawishes and I would support this by asking my own company to pay for it.
But I fear it's not a good idea for this topic - because my Company would say "That's no extrawish it's a k.o.-criterium!" .. and then my idea to convince them to use conversations instead of whatsapp would be dad.

If they e.g. would wish a Gateway between Whatsapp and Conversations/Jabber than it would be no problem to get paid from them.

I think we should let iNPUTmice do his job and he does a really great job - and in some weeks this necessary feature will apear :-) And I hope millions of users will use (and pay) this app instead of wa.

**Comment by ixti** [comment]
Geez! I'm sorry, but although I'm really desperately *WANT* this feature, I'm totally disagree with:

> my Company would say "That's no extrawish it's a k.o.-criterium!"

- developer owns nothing to anybody
- developer spends *HIS* own time, and thus *HE CHOOSES* what's *MUST HAVE* and what's not

More than that. In my group where we use Conversations everyone but me thinks that "sharing an image is must have for a modern client". For me it's really not that important. But that's my own point of view. Anything that's not on the developer's roadmap is an extra-wish, even if somebody thinks that it's a core feature.

Being developer myself, I would say that there is only ONE reason to implement one feature or another: personal interest. Which can be either organically driven (i need this by myself) or enforced with money. As developer spends his *own* time for developing feature, that means he "pays" his ours on his own, so he is the one to decide which features to implement first. Want to dictate what should be first - pay. All simple :D

**Comment by the-solipsist** [comment]
+1, @ixti.

**Comment by moshpirit** [comment]
@ixti I've proposed #971 maybe it could help

**Comment by hschraep** [comment]
+1

**Comment by eolyy** [comment]
>> How long will this approximately take?

> This is probably gonna be the next big thing after 1.0 has been released. However I won't give hard ETAs unless someone pays for them.

[![bountysource](https://www.bountysource.com/badge/issue?issue_id=2478257)](https://www.bountysource.com/issues/2478257-share-file-image-in-muc)

**Comment by halemmerich** [comment]
Seeing this feature as a new XEP would be great. In the meantime sending the data to all users could be a viable solution.

**Comment by iNPUTmice** [comment]
Conversations 1.5 (upcoming) will have build in support to upload files to an HTTP host on the XMPP server. This requires for a special component to be installed on the users server. The source code for that component is available here: https://github.com/siacs/HttpUploadComponent The necessary changes to Conversations are now available in the development branch of Conversations. Automatic download of these files will only happen in non-anonymous MUCs for known contacts. But even in anonymous MUCs the user can long press the link and download the image in place.

**Comment by iNPUTmice** [comment]
1.5 is out. The [HTTPUploadComponent](https://github.com/siacs/HttpUploadComponent) is out. So I guess I can close here.

**Comment by chaotix-** [comment]
I have a followup question to this. I don't know if it is a bug or I just misunderstood how it is supposed to work.

In the HTTPUploadComponent-server there is a whitelist section so only users with XMPP accounts an the specified servers can upload images there. How is this supposed to work? My tests only showed that users from the XMPP server with the HTTPUploadComponent installed sent out a disco request to discover the eu:siacs:conversations:http:upload feature. So why is there this whitelist feature if only users from one server can find the service anyway?

I think it would be optimal if Conversations would detect not only the HTTPUploadComponent on the server it is connected to but also on the server which hosts a conference (for MUCs) or of the server from the account it is talking to (for private chats).

So when I host my own XMPP server I can supply the HTTPUploadComponent to all users in conferences on my server (or at least the users I know and have whitelisted in the configfile). I guess most people are not using self-hosted accounts and would probably never benefit from this feature if this is not changed.

**Comment by iNPUTmice** [comment]
@chaotix- while the component is only added to the disco items of your own server no one is preventing users from talking to the component directly if the jid is known. Meaning if I can guess that your components JIDs is upload.yourserver.tld I can send out requests to that component. That's what the white list is for.
Plus if you are hosting multiple domains maybe even across multiple servers you only need to run one HttpUploadComponent and add the components jid to the disco items manually.

> I guess most people are not using self-hosted accounts and would probably never benefit from this feature if this is not changed.

The idea is that server providers will just install this. (Or similar components that speak the same protocol)

**Comment by chaotix-** [comment]
Thanks for the clarification.

I thought whitelists would not be needed for accounts on the local server of the component as I thought the component should be able to get the information from the server if the account is local.

> The idea is that server providers will just install this. (Or similar components that speak the same protocol)

While I think this would be a great idea, I just don't see it happening in the forseeable future. I don't even know a public XMPP server that has XEP-0313 MAM support. So in my opinion chances of servers widely adopting a protocol that does not even have a XEP-number are slim.

I know your are not a fan of options in Conversations but would it be possible to add the option to use some known components JID for uploading if automatic discovery of the conference servers or remote chat partners servers component is not wanted or possible.

Don't get me wrong. I'm very grateful for this feature (and Conversations as a whole), but I think it would be so much more useful if a server admin could offer this to users of his chat rooms or chat partners even if it would require manual intervention to use the server for the upload.

(And on another note: Most images are uploaded as webp. Is this something Android does or is this the format of choice of Conversations? If the latter: Would it be possible to change this? As far as I know webp is only supported by Google (Android and Chrome/Chromium). This is fine if one only talks to people using Conversations, but most people with different clients (especially Desktop-Clients) won't be able to see the pictures inline or even at all when they are not using Chrome by default (and probably have no clue what webp is).)
