### ISSUE TITLE
 Bookmarks are keyed on (room, server) instead of (room, server, nick)

### ISSUE THREAD

**Issue by kousu** [siacs/Conversations#1750]
If I use Gajim to create two MUC bookmarks with the same room and server fields but different nicks, Conversations summarily ignores one of them.

With different room fields:

![gajim-dis](https://cloud.githubusercontent.com/assets/987487/13558069/f3d6600a-e3c8-11e5-8521-3911f128b954.png)
![conv-dis](https://cloud.githubusercontent.com/assets/987487/13558068/f3c7e8d6-e3c8-11e5-88dd-7220a20a51c0.png)

With identical room fields:
![gajim](https://cloud.githubusercontent.com/assets/987487/13558075/fbdb8488-e3c8-11e5-8481-4cf610c01156.png)
![conv](https://cloud.githubusercontent.com/assets/987487/13558074/fbd0dea2-e3c8-11e5-8479-9f4011af83e1.png)

This is low priority. You'd never use this in real life. I only ran across this because I'm debugging. Still, it's an inconsistency.

I also noticed that bookmarks are only updated at sign in. I don't know if you consider that a bug or a feature. Again, it doesn't matter in real life.

**Comment by iNPUTmice** [comment]
> If I use Gajim to create two MUC bookmarks with the same room and server fields but different nicks, Conversations summarily ignores one of them.

This is kinda on purpose to avoid some nasty duplication issues when using prosodys server-side bookmarks. Not an ideal solution but as you said:

> You'd never use this in real life.


If it'll ever become somewhat important one could maybe take the nick into account as well.

> I also noticed that bookmarks are only updated at sign in. I don't know if you consider that a bug or a feature. Again, it doesn't matter in real life.

This is sort of a limitation to the XEP. One could probably use PEP to store the bookmarks. I think there is an open issue about this already.

**Comment by kousu** [comment]
That satisfies me. XMPP is a large sprawling spec, and taming it into something user-friendly requires being a bit opinionated about what trade-offs you'll take. :)
