### ISSUE TITLE
Swiped out conversations reappear when new session is opened

### ISSUE THREAD

**Issue by weiss** [siacs/Conversations#1751]
If a conversation is removed from the list of conversations, it'll reappear when the next session is opened.  This only happens if MAM is enabled.  To reproduce:
1. Swipe out a conversation.
2. Disable the account.
3. Re-enable the account.

**Comment by Ashaman-** [comment]
Isn't this the point of MAM? The conversion is archived on the server, so the client can retrieve it?
Or are you saying that swiping away a conversation should wipe the mam archive? That would make it too easy to unintentionally delete a chat. 
We do need some functionality for configuring MAM, such as setting default (always/never/on request), and settings for individual roster members.

**Comment by weiss** [comment]
> Or are you saying that swiping away a conversation should wipe the mam archive?

No.  All I'm saying is that if you swipe away a conversation, it shouldn't reappear until a new message is received.

> We do need some functionality for configuring MAM, such as setting default (always/never/on request)

You configure MAM from the menu in the account details.

**Comment by licaon-kter** [comment]
I saw this on a device with 1.18.3 too.
It does not do this now, but it did it for a while.

**Comment by iNPUTmice** [comment]
This should be fixed in HEAD assuming your server supports stanza-id and the latest MAM version.

**Comment by licaon-kter** [comment]
I guess I can see this in 1.23.6 too, still MAM related.

Basically (on an account with Archive:Always):
* have 2 chats
* select 1
* see the toast with "downloading messages"
* hit menu->close chat
* see "no more messages" toast
* see that the chat was reopened

If I wait for the "no more messages" toast to pass, then I can close the chat and it won't reappear.

Hope this helps.
