### ISSUE TITLE
Add button "Get it on F-Droid"

### ISSUE THREAD

**Issue by PanderMusubi** [siacs/Conversations#1752]
Please, add a button "Get it on F-Droid" with a PNG file from https://commons.wikimedia.org/wiki/File:Get_it_on_F-Droid.svg in your README file with the appropriate link to the page of your app on F-Droid.

**Comment by andersruneson** [comment]
The fdroid version is not an official version by the author. And the author
much rather wants people to buy his software on Google play.

**Comment by PanderMusubi** [comment]
Understandable. F-Droid supports also other means of support such as Flattr, PayPal and Bitcoin, albeit not compulsory. Looking into alternative ways of gathering financial support for apps and in app purchases might be interesting.

**Comment by PanderMusubi** [comment]
Woudl this request apply better to the (not yet existing) README.md of https://github.com/siacs/VoiceRecorder ?
