### ISSUE TITLE
After some time, app cannot connect and account stays "Offilne" until the app is force stopped

### ISSUE THREAD

**Issue by crosser** [siacs/Conversations#1757]
After some hours or days of running, the app shows the triangle icon saying that it fails to connect. When I open the account editing dialogue and save it without changing it tries to connect, and then says "Offline". After Force stopping the app and opening it again, it connects normally. This happens to me maybe a couple times a month. Version 1.11.0 but it happened in many previous versions. Logs of both cases attached.

[conversations.canconnect.txt](https://github.com/siacs/Conversations/files/167705/conversations.canconnect.txt)
[conversations.cannotconnect.txt](https://github.com/siacs/Conversations/files/167706/conversations.cannotconnect.txt)

**Comment by iNPUTmice** [comment]
This logs like a server error. 817d344521835622a625c8263141dc1148fff451 logs the reason for it.

**Comment by crosser** [comment]
I will re-post logs if/when the problem happens in the next version with 817d344 included.

The behaviour definitely _looks_ like a server error, **but** attempt to reconnect without stopping the app consistently fails, while after force stopping the app connect consistently succeeds. Which suggests that something gets rotten in the app's address space on android...

**Comment by iNPUTmice** [comment]
Does disabling and enabling the account help?

**Comment by crosser** [comment]
I will try disabling and enabling the account next time.
In the meanwhile, server side log included (ip address replaced).
[jabberd2.txt](https://github.com/siacs/Conversations/files/168701/jabberd2.txt)

**Comment by iNPUTmice** [comment]
1.11.1 includes the above mentioned commit

**Comment by crosser** [comment]
This happened for me again, with version 1.11.2.
Disabling and enabling account did not help. After force-stop and start, it connected successfully at once.
Unfortunately, I have no log: interesting bits scrolled away from the buffer by a lot of

`I/UsageStatsDatabase(  865): Moving file /data/system/usagestats/0/yearly/1419115975726 to /data/system/usagestats/0/yearly/1419115969258`

messages. Will post the log next time it happens.

**Comment by crosser** [comment]
Got the logs! Sequence of events:

- open edit server from "Manage connections" and close w/0 editing
- Switch enable/disable a couple of times in "Manage connections"
- Settings -> Apps -> Conversations -> Force stop

then it successfully connected.

The relevant part is I think this:

```
04-07 15:37:59.978 D/conversations( 4596): crosser@average.org: TLS connection established
04-07 15:38:00.152 D/conversations( 4596): crosser@average.org: Authenticating with PLAIN
04-07 15:38:00.228 D/conversations( 4596): crosser@average.org: logged in
04-07 15:38:00.512 D/conversations( 4596): crosser@average.org: disconnecting because of bind failure (<iq xmlns="jabber:client" id="jo833rghcd" type="error"><error xmlns="jabber:client" type="modify" code="400"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource xmlns="urn:ietf:params:xml:ns:xmpp-bind"/></bind></iq>
04-07 15:38:00.512 D/conversations( 4596): crosser@average.org: disconnecting force=true
```

that looks like a server problem, but it disappeared after killing and restarting the client.

It might be interesting to see the request that caused 400 response from the server. I could try to set up verbose debugging on the server side some time, and try to catch it again...

[conversations-1.11.3-cantconnect.txt](https://github.com/siacs/Conversations/files/208380/conversations-1.11.3-cantconnect.txt)

**Comment by crosser** [comment]
The problem did not happen since upgrade to Marshmallow. I think it can be closed, I'll reopen if it happens again.

**Comment by licaon-kter** [comment]
Close it yourself.

**Comment by crosser** [comment]
It started to happen agan today, conversations 1.23.6, jabberd2 2.6.1, did not change the server recently.

```
02-21 22:41:57.328 12456 16039 D conversations: crosser@average.org: disconnecting because of bind failure (<iq xmlns="jabber:client" id="IoGFeEJcJ6w9p7pz0XaFxByRiyxsmi22TQRWq2pQtIX4E7p2b1Y2fxISU2FWhrQdbC8" type="error"><error xmlns="jabber:client" type="modify" code="400"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource xmlns="urn:ietf:params:xml:ns:xmpp-bind"/></bind></iq>
```
This time it persisted after a few "force stops" of the app. Then after another force stop it connected fine (without any actions on the server side).
