### ISSUE TITLE
Feature Request: Reject roster request and show notification when someone try to add me to their roster list

### ISSUE THREAD

**Issue by chengliu22** [siacs/Conversations#1758]
Hi ,

Thank you very much for your awesome code. I'm now facing two problems and they are all about roster request. The first one is when someone try to add me to their roster list, I have no way to reject their request. When I use Spark on Linux, I can click the refuse button to reject their request. The second problem is I want to show notification when I receive an roster request.

Could you give some hint to do that?

Thank you.

**Comment by qamble** [comment]
That seems most like XEP 0016, Privacy Manager

https://xmpp.org/extensions/xep-0016.html

**Comment by iNPUTmice** [comment]
If you swipe away the Conversation without answering it will reject the request.
