### ISSUE TITLE
Scan QR Code

### ISSUE THREAD

**Issue by vivekebics** [siacs/Conversations#1760]

**Comment by iNPUTmice** [comment]
I don't understand what you mean

**Comment by vivekebics** [comment]
We have three types verification in conversation code in that scan QR Verification not working.
When I started to verify it asked me to install  Bar code reader app. I have installed that too. Again I selected the Scan QR code for verification bar  code scanner opened. When  I captured back to activity it tells "could not copy ". This is my problem

**Comment by iNPUTmice** [comment]
Please provide steps to reproduce. I can't find the string "could not copy" anywhere in Conversations.

**Comment by vivekebics** [comment]
<string name="could_not_verify_fingerprint">Could not verify fingerprint</string>

**Comment by vivekebics** [comment]
<string name="could_not_verify_fingerprint">Could not verify fingerprint</string>

**Comment by iNPUTmice** [comment]
You are probably scanning the wrong fingerprint.

Please provide steps to reproduce.

**Comment by vivekebics** [comment]
Can you please explain me the steps to follow ?

**Comment by iNPUTmice** [comment]
This is a bug tracker. If you have questions please ask in our conference.
