### ISSUE TITLE
Push Notifications seems not to work

### ISSUE THREAD

**Issue by B-eugen** [siacs/Conversations#1761]
When i close the app via taskmanager and someone sends me a message you will see this in the log:

debug   Received[c2s]: <active xmlns='urn:xmpp:csi:0'>
debug   Handled 17 incoming stanzas
debug   Received[c2s]: <message type='chat' to='sdf@XXXXX/mobile' from='asdf@XXXXX/mobile'>
debug   #queue = 2
debug   hibernating, stanza queued
debug   Handled 18 incoming stanzas
debug   Received[c2s]: <message id='XXXXX' type='chat' to='sdf@XXXXX' from='asdf@XXXXX/mobile'>
debug   Received[c2s]: <r xmlns='urn:xmpp:sm:3'>
smacks      debug   Received ack request, acking for 18
debug   Received[c2s]: <inactive xmlns='urn:xmpp:csi:0'>

Nothing about push. I have the playstore version and here are my included prosody modules:

                "proxy65";
                "pep";
                "smacks";
                "carbons"; 
                --"mam"; 
                "csi"; 
                "http_upload"; 
                "cloud_notify";

**Comment by andersruneson** [comment]
Do you have some other client online at the same time?

**Comment by B-eugen** [comment]
Only the sender of the message.

**Comment by B-eugen** [comment]
Is it possible that i have to set a host for this? Something like host : "push.example.net" ?

**Comment by iNPUTmice** [comment]
In prosody the recipient must be offline to receive push notifications.
*not* in the 5 minute stream managment window.

if you use the play store version there is no further configuration
necessary.

**Comment by B-eugen** [comment]
Hi Daniel,
didn't know that  "*not* in the 5 minute stream managment window"
Thank you!
