### ISSUE TITLE
More detailed delivery-failed information

### ISSUE THREAD

**Issue by devurandom** [siacs/Conversations#1762]
When I try to send a message to a certain contact of mine, I immediately get a "delivery failed" response from Conversations. However, there is no indicator as to what happened. RFC6120 describes several distinct error types for the `<error>` element of the stanza in [Section 8.3](http://tools.ietf.org/html/rfc6120#section-8.3), which could be shown (in addition to the `<body>` element of the stanza) to the user in a "details" long-press menu option.

**Comment by iNPUTmice** [comment]
fwiw the error is being logged to the debug console.

Not really sure if it's worth implementing extra UI for this.

**Comment by devurandom** [comment]
A simple map of the one dozen or so error codes in RFC6120 to more descriptive strings, shown in a dialogue would be very helpful already. Without having to fiddle with the debug console one could destinguish at least the category of error: Is it a client issue, is my own server at fault, does the remote server have a problem, ...

**Comment by iNPUTmice** [comment]
There is a 'show error' in more recent version of Conversations.
