### ISSUE TITLE
Conference Details overflows RAM

### ISSUE THREAD

**Issue by kousu** [siacs/Conversations#1763]
You're going to roll your eyes at this one but I'm reporting it anyway.

If you join a room with over a thousand users Conversations can handle the message but not the roster load.  You can chat but if you try to open Conference Details it hangs hard and then eventually crashes, presumably because it's making widgets for each of the thousand users.

You could probably generate a thousand bots on a test server to demonstrate this, but the place I found it is using my transport with #python. You should be able to reproduce by:
1) add znc.kousu.ca as an XMPP contact.
2) Message it with

> register kousue_ircgate test1 test1
> connect
> 3) Make sure it works by joining #test@conference.znc.kousu.ca. You should see the fluctuating roster of about 30 people that are in ircs://irc.freenode.net:6697/#test at any one time and be able to send and receive messages.
> 4) Join #python@conference.znc.kousu.ca, and wait a minute or so for the `<presence>` flood to stop. This channel is very busy, flucutating between 1500 and 2000 users.
> 5) At this point you should be "kousue_ircgate_t" in ircs://irc.freenode.net:6697/#python and you should be receiving live messages at at least 1/minute and up to 15/minute. 
> 6) Try to open Conference Details
> 7) ???
> 8) Crash!

Conversations handles message history lazily, which is why actually chatting works fine. It should do the same for the room's userlist, or maybe special-case rooms with more than 100 members or so to some different UI.

**Comment by jugrajsingh** [comment]
Has anyone address this issue?
I faced same issue with a room of huge participants.

**Comment by amarjeetkapoor1** [comment]
I have solved this issue with following changes.

https://github.com/GreatDevelopers/sunehaG/blob/master/src/main/java/in/gndec/sunehag/ui/ConferenceDetailsActivity.java#L618

https://github.com/GreatDevelopers/sunehaG/blob/master/src/main/java/in/gndec/sunehag/ui/ConferenceDetailsActivity.java#L58

I have divided the list of contacts into the list of some given number (by default 200) and Only one list is shown at a time and then added two buttons: 
1. Load more contacts: Which is shown only when there are some lists after the current list
2. Load Previous contacts: which is shown only if there are some lists before the current list. 

example: if there are 1000 members in groups then 5 sets of contacts will be created and if we are on set 0 then there will be an option to load next list of contacts.

If you think above approach is correct. I can sent a pull request.

**Comment by kousu** [comment]
That is a very nice piece of work, amarjeet. It certainly solves most of the problem. The button seems awkward though. It would be slicker if instead of an explicit onClick you loaded the new users on scrolling, the way an AJAXey website works.

**Comment by amarjeetkapoor1** [comment]
Okay, thanks. I will try that.

**Comment by uchchishta** [comment]
@amarjeetkapoor1 Hi, can you send a PR? Thanks.

**Comment by amarjeetkapoor1** [comment]
I had only implemented the one with button only not like mentioned by kousu above. Will the PR with the solution with button work?

**Comment by iNPUTmice** [comment]
I would prefer an entirely seperate view based on the ListItemAdapter that
scrolls through all members in a performant way.
Show the first 5 members in the overview and put a link to 'show all' that
opens that scrollable activity.

**Comment by amarjeetkapoor1** [comment]
Hi,

I tried my hands on this and I was able to get the following result but the contextMenu is not working.
If UX is okay, I could try to solve although I tried but was unable to solve.

![screenshot from 2018-02-10 23-51-21](https://user-images.githubusercontent.com/13377588/36071343-cac285e4-0f32-11e8-8144-ba9b2fbed764.png)

![screenshot from 2018-02-10 23-51-21](https://user-images.githubusercontent.com/13377588/36071347-d687be9e-0f32-11e8-983a-9565598fdeda.png)

<img src="https://user-images.githubusercontent.com/13377588/36071367-10cea130-0f33-11e8-9b99-fab9f99e29e0.png" width="480"></img>

**Comment by BlauerHunger** [comment]
I'm experiencing the same problem over my ejabberd irc transport on #archlinux on chat.freenode.net

**Comment by iNPUTmice** [comment]
Fixed in latest master
