### ISSUE TITLE
Option for writing received files on SD card

### ISSUE THREAD

**Issue by Testertime** [siacs/Conversations#1765]
I would like to see a new option in the future which allows us to choose the received files directory, allowing us to save files on the SD card. I'm sometimes using Conversations for transferring some really big files and it works well, but that it saves everything always into the internal memory is a serious pain. While it isn't super worse (but still very **annoying!**) on my device, there are some more serious real world examples: Your mother is using Conversations for secure chatting, and she has no big clue about technical details. Her device has very limited internal memory, while she has a much **much** bigger SD card in her phone (heck, she purchased the card _because_ the memory is so low). Let's imagine the small internal memory is 200 MB big, with 100 MB left. I won't be able to send her files bigger than 100 MB. Most importantly, don't expect standard users to move these files to the SD card by hand. So, these 100 MB are most likely your permanent space for file transfers to her, unless you are going to visit her for fixing "IT stuff"...

Thanks for reading and hopefully you are considering this as important!

**Comment by iNPUTmice** [comment]
That's something that should be handled by the operating system. Conversations gets one path from the OS and always safes the messages there. It's up to the OS to decide what path it feeds into Conversations.

**Comment by sbrl** [comment]
How can I tell android to save things to the SD card?
