### ISSUE TITLE
Feature request: Full encryption of the app and encrypted storage for received files.

### ISSUE THREAD

**Issue by nexus4fun** [siacs/Conversations#1766]
Hello, wanted to ask if there is any plans to add full encryption of the app? Something like ChatSecure. Was nice if there was a future to keep received Pictures/Files in an encrypted folder.

**Comment by d9h02f** [comment]
Encrypt your device.

**Comment by lovetox** [comment]
newer android version have an encrypted harddisk, i think

**Comment by iNPUTmice** [comment]
duplicate of #1002
