### ISSUE TITLE
No longer receiving message after being hibernated or killed by Cleaner software

### ISSUE THREAD

**Issue by ezraimanuel** [siacs/Conversations#1769]
Hello,

is there anyway to make application up again and continue receiving connection after being hibernated or killed by cleaner software? (Just like WhatsApp or Telegram)

I tried with GCM method and it doesn't work somehow, though device registrations appeared in GCM statistics page.

oh, one more thing, I use ejabberd, and i keep getting this message (and disconnection) minutes after i turned off my screen: `conversations: account@domain Read error: ssl=0x78f13470: I/O error during system call, Connection reset by peer`. And it will only reconnect after I manually called the UI.

Is there anyway to check connection and reconnect from the background service?

much appreciated
vic

**Comment by iNPUTmice** [comment]
Push does exactly that. Are you using the Playstore version and is Push
marked as available in the server info in your account details?

**Comment by ezraimanuel** [comment]
Hello,

Yes exactly, I compiled with Playstore flavour.

GCM registration seems always successful according to GCM statistics page (HTTP 200 OK). Also debug log showed that Push is available whenever the device connecting to the server, I even added some debug message to check either the receiver function is called or not. all seems working well. (screenshots attached below)

oh, one more thing, I use ejabberd, and i keep getting this message (and disconnection) minutes after i turned off my screen: `conversations: account@domain Read error: ssl=0x78f13470: I/O error during system call, Connection reset by peer`. And it will only reconnect after I manually called the UI. (It behaves like Signal, where we get bunch of messages after we manually calls the UI)

Is there anyway to periodically check connection and reconnect from the background service?

![push-support](https://cloud.githubusercontent.com/assets/2414895/13838694/97dd841c-ec48-11e5-82f8-e2a9614e5864.png)
![gcm-statistics](https://cloud.githubusercontent.com/assets/2414895/13838696/9dc90f40-ec48-11e5-99ac-3df120c2f58a.png)

**Comment by iNPUTmice** [comment]
You should check if your push server actually issues the push.

**Comment by ezraimanuel** [comment]
I added log message inside `EventReceiver` class (`onReceive`), when i turn off the screen it receives broadcast messages from the server (and yes after sometimes I got `conversations: account@domain Read error: ssl=0x78f13470: I/O error during system call, Connection reset by peer`)

![eventreceiver](https://cloud.githubusercontent.com/assets/2414895/13839151/89c90ba0-ec4b-11e5-9d3c-38dc2306e72f.png)

I also added log message inside `InstanceIdService` class (`onMessageReceived`), but the log never showed, seems its not receiving GCM message.

**Comment by iNPUTmice** [comment]
The 'Broadcast received' is no indicator on whether or not a push notification has been received. Conversations will log any arriving push message with a ```gcm push message arrived in service.```

You need to make sure your App server is actually sending out a push message.

**Comment by ezraimanuel** [comment]
Thank you, I'll check the App server.

By the way, is there anyway add some kind of function in background service to reconnect whenever the app disconnected from the server? in my case when I got `Read error: ssl=0x78f13470: I/O error during system call, Connection reset by peer` error message. I think most of the time my app won't wake up because its silently got disconnected from the server, and it doesn't try to reconnect.

**Comment by iNPUTmice** [comment]
> is there anyway add some kind of function in background service to reconnect whenever the app disconnected from the server?

this is already the case. However it seems like your phone is killing the network connection in the background.
In any case this doesn't seem to be a bug report but rather a collection of more general questions. Please ask questions in our conference and only open issues if you have a (reproducible) bug.
