### ISSUE TITLE
Show offline members in private conferences...

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1775]
...it would be nice to show also offline conference members in private conferences, so you have a better overview of the members and the admin and/or owner can also change the user affiliations while the members are offline.
Thanks

**Comment by iNPUTmice** [comment]
implemented in current HEAD. for this to work properly your server needs to send affiliation changes and allow non admins to query the members list. We have already enabled that on conversations.im

**Comment by kriztan** [comment]
Thanks a lot :)

**Comment by iNPUTmice** [comment]
It should be noted that for this to work properly your server needs to implement some niche features from the XEP.
For prosody there are two feature requests:
https://prosody.im/issues/issue/682
https://prosody.im/issues/issue/445

Our very own [conversations.im](https://account.conversations.im) of course already has support for that.
