### ISSUE TITLE
Video compression

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#1777]
Does exist any way to compress not just the pictures but also the videos?

**Comment by licaon-kter** [comment]
Via https://developer.android.com/reference/android/media/MediaCodec.html maybe.

**Comment by kriztan** [comment]
An integrated video compression feature would be very nice.

**Comment by tmolitor-stud-tu** [comment]
Yes, indeed. I need that, too.

**Comment by iNPUTmice** [comment]
This is apparently rather complicated. I tried researching this for a while
and it seems that using ffmpeg for this is the best option. However this is
not a functionality we want to have in an instant messenger.

So the best way to do it would be as an external program. (Like those 'Send
compressed' ones that exist for images)

**Comment by moshpirit** [comment]
I think that what Telegram (the app on F-droid) does is resizing the pictures loosing quality, doing this way a 4MB video from a 50MB one. 

I don't know if this could help in order to reuse this code, but thank you anyway for your huge job!

**Comment by herrwusel** [comment]
@iNPUTmice According to telegram's wiki [site](https://telegram.wiki/android/androidvideocompression) about videos, the compression is done by api. So is it still no option for Conversations?

**Comment by licaon-kter** [comment]
Version 1.21.0 introduced attach->take video, where videos over 8 seconds will be auto-compressed.
Also, you camera app should allow the reduction of the resolution on capture, hence smaller files.

But, see https://github.com/siacs/Conversations/issues/2644 too
