### ISSUE TITLE
"fixing some bugs when sharing files" breaks "Send reduced"

### ISSUE THREAD

**Issue by peterjw** [siacs/Conversations#1781]
After upgrading to 1.11.1, picture condensed by "Send reduced" (https://f-droid.org/repository/browse/?fdfilter=send+reduced&fdid=mobi.omegacentauri.SendReduced) are not accepted by conversations any more. Meaning, instead of the image showing up as  message, only a space ist kind of typed into the text writing area.
All worked well with 1.11.0

**Comment by iNPUTmice** [comment]
This is already fixed in HEAD. I'll see if I get around releasing a 1.11.2 today.
