### ISSUE TITLE
problem with conferences - no members shown

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1787]
Since Version 1.11.2 I'm running in problems with conferences. Sometimes, after a restart or reconnect, I see an empty conference. The conference details shows no members, but there are members online and writing. Messages were received as expected. 

The ADB log shows:
03-29 13:26:15.500 18090 18090 I am_on_resume_called: [0,eu.siacs.conversations.ui.ConversationActivity]: eu.siacs.conversations
03-29 13:26:15.550 18090  9955 D conversations: me@domain.de: joining conversation room@room.domain.de/Me: eu.siacs.conversations
03-29 13:26:15.580 18090  9955 D conversations: me@domain.de: running mam query to=room@room.domain.de, start=2016-03-29T11:19:03Z, end=2016-03-29T11:26:15Z: eu.siacs.conversations
03-29 13:26:15.580 18090  9955 D conversations: me@domain.de: fetching members for room: eu.siacs.conversations
03-29 13:26:15.580 18090  9955 D conversations: me@domain.de: fetched muc configuration for room@room.domain.de - [http://jabber.org/protocol/muc, muc_hidden, muc_persistent, urn:xmpp:mam:0, muc_membersonly, muc_unmoderated, muc_nonanonymous, muc_unsecured]: eu.siacs.conversations
03-29 13:26:15.845 21556 21556 I notification_cancel: [eu.siacs.conversations,9026,NULL,0,0,64]: system_server
03-29 13:26:15.890 18090  9955 D conversations: me@domain.de: finished mam after 1 messages. messages left=true: eu.siacs.conversations
03-29 13:26:15.910 18090  9955 D conversations: me@domain.de: retrieved members for room@room.domain.de: [member1@domain.de, member2@domain.de, member3@domain.de, me@domain.de, member4@domain.de]: eu.siacs.conversations

Any ideas?

**Comment by iNPUTmice** [comment]
https://prosody.im/issues/issue/641

**Comment by kriztan** [comment]
Yes, that's it. Thanks
