### ISSUE TITLE
No way to 'whisper' to a lurking MUC participant

### ISSUE THREAD

**Issue by gkirilov** [siacs/Conversations#1789]
The only way of 'whispering' to someone in a MUC seems to be long-pressing the avatar in a message of theirs in the group chat.
If the participant hasn't yet said anything there, there's no way to 'whisper' to them.
Long press in the participants list only offers private chat to the real JID, but not to the room JID (whispering).

Maybe add an extra item in the long-press menu (in the MUC participants list)?

**Comment by iNPUTmice** [comment]
that's on purpose. because you really shouldn't be using whispers if you have a better alternative (1:1 chats)
if you don't have the real jid Conversations will offer to whisper to that participant.

**Comment by gkirilov** [comment]
I agree about preferring real JID's. It's just that almost all of the people in this MUC use the Candy web client, in a quite restricted form. They don't use rosters, can't "add" me or anything. And when I send them a "real" PM, Candy shows me as offline, even warns them about me. With "room" PM's everything seems fine.
It's no Conversation's problem of course.
Thanks for clarifying anyway.
