### ISSUE TITLE
Message deduplication fails

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [siacs/Conversations#1790]
If a message comes in that has a different timestamp than the same message (even if it is only less than a second difference), the message is not deduplicated correctly and shown twice.

This can happen when multiple instances add timestamps to messages at different stages of message transport, like prosody's mod_smacks when resending a queued message or such.

In gajim we use only "from", "to" and "body" for deduplication and this works pretty well.
If you don't want to ignore the timestamp altogether you could at least add a proper timeframe in which timestamps are considered to be the same (like 60 seconds, or 1 hour for example).

That would make the message deduplication even more robust.

**Comment by iNPUTmice** [comment]
The time stamp is only looked at when the the message doesn't have an id. What client are you sending those messages with that don't have an id?
There is a 20 second time frame for cases where those messages don't have an id

> In gajim we use only "from", "to" and "body" for deduplication and this works pretty well.

What happens with messages like 'Hi' that appear rather frequently

**Comment by iNPUTmice** [comment]
I'm closing this is invalid for now. Please provide two complete stanzas for messages that you think should be de-duplicated but aren't and I will reopen. Thanks

**Comment by tmolitor-stud-tu** [comment]
Sorry, I forgot to list the id, gajim of course uses "id", "from", "to", and "body" for deduplication.

Here are the stanzas:
```
<!-- Out Di 05 Apr 2016 16:25:22 CEST -->
<message xmlns="jabber:client" to="test@example.org/mobile" type="chat" id="a2">
<body>hi there</body>
<delay stamp='2016-04-04T16:00:02Z' xmlns='urn:xmpp:delay'/>
</message>

<!-- Out Di 05 Apr 2016 16:25:30 CEST -->
<message xmlns="jabber:client" to="test@example.org/mobile" type="chat" id="a2">
<body>hi there</body>
<delay stamp='2016-04-04T16:00:12Z' xmlns='urn:xmpp:delay'/>
</message>

```
But if I send the same message stanza without the delay tag the deduplication doesn't work either.
I suspect your deduplication is broken altogether.

PS:
Prosody sometimes adds timestamps like "2016-04-04T16:00:12Z.456" (or was it "2016-04-04T16:00:12.456Z", I don't remember).
I don't know if you handle such stamps correctly, too.

**Comment by iNPUTmice** [comment]
Wait. Are you just sending those stanzas directly? Why would Conversations run de-duplication on that? Conversations only de-duplicates messages that are coming from MAM or MUC history.

**Comment by tmolitor-stud-tu** [comment]
Ah! That explains this. Yes, I do.

Well, when a smacks session times out and the unacked messages are saved as offline messages, they get resent when the client reconnects. If those messages where already received (but the ack is missing), this messages are displayed twice.

And I'm sure there are some more cases where a deduplication for incoming messages would make sense.

**Comment by tmolitor-stud-tu** [comment]
See https://prosody.im/issues/issue/383#comment-5 for an example of duplicated incoming messages when using mod_smacks and mod_smacks_offline in prosody.
