### ISSUE TITLE
Question: why does it sometimes take 5 or 10 minutes to send a message?

### ISSUE THREAD

**Issue by netge** [siacs/Conversations#1791]
On several occasions it took 5 or 10 minutes for a message to be delivered between chat clients, even when both parties were using the Conversations app on Android and the receiver was actively playing with the app. So Conversations was definitely running and both devices had Internet connection.

In a second scenario this happened with the sender using Conversations and the receiver using Pidgin with OTR plugin. I am attaching a screenshot of this case showing the timestamp of the message being sent at 20:41 and the time the message was delivered was 20:45. Could it be that OTR session setup is the problem here?

I was not able to strictly reproduce the issue but it happens frequently enough to be annoying. I am using instant messaging when I need immediate response, else I could better use email. :-)

![conversations takes long2](https://cloud.githubusercontent.com/assets/18294374/14296740/ceee91a2-fb7b-11e5-999b-ce272f1d73f0.png)

**Comment by iNPUTmice** [comment]
> Could it be that OTR session setup is the problem here?

yes this is most likely the case. You shouldn't be using OTR. Use OMEMO. There is a gajim plugin available for it.

Also this is not a bug report. For questions please join our conference.

**Comment by netge** [comment]
Why is this not a bug report? In instance messenger not delivering messages instantly has a bug.

**Comment by licaon-kter** [comment]
What did you do to convince them to install Gajim in the first place? Just do that again. :)

**Comment by iNPUTmice** [comment]
> Why is this not a bug report?

because it neither contains an adb logcat nor steps to reproduce. and because your *question* is labeled "Question:  why does it sometimes take 5 or 10 minutes to send a message?"

If you are able to actually reproduce this and get the 'sometimes' down to a specific situation we can reopen this as a bug report.

Also make sure your server has stream management enabled. That makes the OTR symptoms less bad.

**Comment by netge** [comment]
> What did you do to convince them to install Gajim in the first place? Just do that again. :)

Exactly ;) I tried Gajim myself but it had trouble re-connecting when my (Windows) firewall configuration changed, leaving me offline. (That firewall on one of my machines is something I cannot change). So I concluded that Pidgin, although a bit messy, is probably the most mature app and it also has a more native L&F both on Linux and Windows.

**Comment by netge** [comment]
> because it neither contains an adb logcat nor steps to reproduce.

If I manage to get hold of that info I will submit it.

In the mean time; could it be part of the problem that Conversations tries to initiate an OTR session immediately when sending the first message? In Pidgin OTR there is an option where you can choose whether or not to initiate OTR automatically. I thought it might work better to start every chat unencrypted and only activate encryption later on. In Conversations however, there is no such option. It always seems to fall back into the previous chat that one had with the same person (if it exists), and OTR seems to be automatically re-enabled.

I am not enough an expert to say whether changing that behavior would help; perhaps you can think about it.
