### ISSUE TITLE
Using notifications with Google Play version [question]

### ISSUE THREAD

**Issue by lepasserby** [siacs/Conversations#1793]
Hi!
Basically, I've been waiting for a long time for proper Jabber+notifications to happen on Android

So, I am ready to buy it from Google Play, but try as I might I can not find a Jabber server online that would support XEP-0357.

Do I have to rent a VPS and set up a Jabber server myself ( :( ) or is there a public server for this kind of thing? 

Maybe Conversations team could run one for paid Google Play clients ? _(methinks it might even be done in a manner that does not allow pirated installs to use the server, which would take a nice stab at apk pirates)_

**Comment by d9h02f** [comment]
'Pirating' Conversations isn't possible because it's free software. I didn't check but so far at least jabber.at has supported everything Conversations wants, did you take a look at that?

**Comment by andersruneson** [comment]
Conversations is available on fdroid for no cost and that's not piracy.

Even if the server supports push, Conversations would still connect and try
to keep the connection online. So why do you really need push?

Push is still very new and few server and clients support it.

**Comment by iNPUTmice** [comment]
The push modules in prosody and ejabberd can be considered experimental. I would expect public servers to enable them once they are more mature. maybe in a few month?

until then you either have to run your own or just wait.

as this is really not a bug report please head into our conference for further dicsussions. maybe someone can let you use their server. 

btw siacs.eu is public and has push enabled.

**Comment by DamienGrand** [comment]
Hi! I just stumbled upon this issue - tried to register on siacs.eu and no cigar :(

**Comment by d9h02f** [comment]
I think the server has just been down for a couple of hours.

**Comment by DamienGrand** [comment]
Is still down as far as I see. https://xmpp.net/result.php?domain=siacs.eu&type=client 
And here I wanted to try out push...
BTW, @iNPUTmice  any plans to implement XEP-0357 on conversations.im server ?
