### ISSUE TITLE
Support for proxy/server in account setup

### ISSUE THREAD

**Issue by mathiasfriman** [siacs/Conversations#1794]
Conversations is by far the best XMPP client for Android in my book, but I lack the possibility to manually select a server to connect to. 

I would like to use Conversations for chatting on I2P, which is an encrypted overlay network that supports all sorts of protocols. To use it, one needs to create a proxy tunnel on localhost, lets say http://localhost:5222

This is all done in the I2P router. When that is all done, one proceeds to create the account in a XMPP client, like below:

**user:** username@xmpp.server.i2p
**password:** password
**server:** localhost
**port:** 5222

Since Conversations only supports the "user" setting and not the explicit "server" setting, it is not possible to connect to I2P. 

Could this be done with some sort of "advanced" account setup perhaps? I see that you already have a checkbox for TOR. Perhaps one could add one for I2P also?

**Comment by licaon-kter** [comment]
Why don't you use the advanced settings?

/close as invalid

**Comment by mathiasfriman** [comment]
Sorry, since I know this isn't a support forum, but where do I find the advanced settings? I've been looking all over but seems to have missed them.

**Comment by andersruneson** [comment]
Settings / expert settings.

**Comment by mathiasfriman** [comment]
It certainly helped to upgrade from 1.8.4 to the current version. Found it! Thanks for the trouble :)

**Comment by licaon-kter** [comment]
That's a rule: when reporting issues, always use the latest version.
