### ISSUE TITLE
App terminating on Nexus 4

### ISSUE THREAD

**Issue by singpolyma** [siacs/Conversations#1795]
Seems to be fine with "enable foreground service", but hard to get users to be ok with a permanent notification.  Used to work fine (hardly ever saw a long disconnect) but recently started happening often.  Change in Conversations or change in OS?  Any tips on how to debug?

**Comment by licaon-kter** [comment]
If you have root use aLogCat or if not developer options `adb logcat...` while connected to a PC.

Not sure what you mean by foreground and users ok with notification, that's needed so Android does not kill the process, yes on Android 5 you can hide it but you'll hide new message notifications too.

**Comment by iNPUTmice** [comment]
What Android version?

**Comment by singpolyma** [comment]
Phone is running Android 5.1.1

**Comment by iNPUTmice** [comment]
There hasn't been a change in the connection handling in for ever. Feel free to try with older versions though. (Depending on what consider recent)

**Comment by singpolyma** [comment]
And there's no way to make it foreground without a persistent notification, right?  That's an Android limitation?

**Comment by iNPUTmice** [comment]
> And there's no way to make it foreground without a persistent notification, right? That's an Android limitation?

yes
