### ISSUE TITLE
occurs INCOMPATIBLE_SERVER after throw IncompatibleServerException.

### ISSUE THREAD

**Issue by sfe2014** [siacs/Conversations#1797]
Hi, everyone, i found an issue that when app is killed by user, and then restart app, it always throws IncompatibleServerException.
the code in XmppConnection 
--> processStreamFeatures()
--> if (this.streamFeatures.hasChild("bind")) {
				sendBindRequest();
			} else {
				throw new IncompatibleServerException();
			}
Is there anybody can help me to find out the reason? i will appreciate it.
Thanks a lot.

**Comment by iNPUTmice** [comment]
Is this error persistent or does it disappear on the next try?

**Comment by iNPUTmice** [comment]
No responds from OP. closing for now.
