### ISSUE TITLE
Search User- New functionality ..Not an Issue

### ISSUE THREAD

**Issue by rahulwali** [siacs/Conversations#1798]
I need to add search user functionality ..However I am unable to understand how to do it in conversation code.. Please Can any one help/guide.. I have spend one week in this however there has been no result.. Your help is needed... 

Thanks ..

**Comment by andersruneson** [comment]
There's already a search-user function in Conversations.

**Comment by rahulwali** [comment]
Thanks for quick response … We need to implement jabber:iq:search. (xep-0055) & (Customised functionality) .The requirement is that we need realtime online users that are not on roaster . Based  on  input by the user, the system will search and retrieve the list of  online users. The search  can be on Username, emailID or name.  The search input  will take input  as  wild card character.. 
We have already implemented this functionality at server end in open-fire and client app  IOS that provides list of online users(Not only from Rosters) 
 
Now we need to implement same functionality in android..  I have been unable to see the  search functionality like this in conversation.. Please help/ Guide me.

**Comment by iNPUTmice** [comment]
This is out of scope for a bug tracker. If you need customizations on the code base of Conversations I'm available for hire. [My website](https://gultsch.de) has contact information.
