### ISSUE TITLE
OMEMO silently fails after adb restore

### ISSUE THREAD

**Issue by danielegobbetti** [siacs/Conversations#1799]
I believe I identified an issue that occurred to me some times already:
after restoring an old version of conversations through "adb restore", it is impossible to exchange OMEMO encrypted messages with some contacts.
Worst of all, the failure is completely invisible to both ends of the conversations: messages appear as sent but never reach the other party. This happens to both partners: messages cannot be seen and no error is shown. The only exception is sending a picture:in this case the other party receives a black image.
Plain text messages can be exchanged just fine.

This may be solved by deleting the offending entry in the "sessions" table of the DB (tested on my side of the communication, where previously an old version was restored with with adb).

This does not happen with every contact, I strongly believe it affects only the contacts with whom messages were exchanged after the "adb backup" was made (perhaps related to PFS???)

Ideally an error message should be shown when this happens, and a means to "reset" or "delete" the offending "session" should be provided.

PS: another fix for the issue is completely removing the account from the phone and readd it, but this is far from ideal.

**Comment by iNPUTmice** [comment]
To clarify on this.

You made the backup. Then kept exchanging messages. Then you restored the backup?

Then yes this makes perfect sense because the ratchet was advanced without the backup knowing.

**Comment by danielegobbetti** [comment]
Your summary is correct. :)

**Comment by iNPUTmice** [comment]
This doesn't work due to the forward secrecy. You have to generate new key material. Depending on your restore reason you might either recreate your account (if your device got stolen) or be more careful not to exchange any messages between backup and restore. If for example you are migrating devices or switching ROMs just disable your account beforehand and keep it disabled until you restored it.

**Comment by danielegobbetti** [comment]
Perhaps I wasn't clear in my initial posting, I understand that in this situation normal message exchange is not possible (and must not be!).

I was wondering - and still am - if there was a better strategy rather than simply making messages disappear without any hint to both ends. I believe that this situation is also very similar to a MITM attack (where another party could have broke the PFS).

In both cases, I think it would be good to give a clue to the involved users ("There is something very wrong with this user's OMEMO status, please ensure that the devices were not compromised.")  and perhaps a button to clean the offending row from session table?
