### ISSUE TITLE
file transfer without XEP 363

### ISSUE THREAD

**Issue by fleixi** [siacs/Conversations#1800]
Im using an Server without XEP 363 but with XEP 0066, XEP 0096 and XEP 234. if i try to send a picture to an other user in the same Server nothing happen. My messenger say "offering" but the other user dont geht a messege and there is no log in the Server about this.

**Comment by andersruneson** [comment]
That are the normal issues when not using 363, clients supporting different
versions of xeps, not supporting them at all or just have bugs in the
implementations.

If you try transferring files between two Conversations clients then it
might work, just maybe, and it may take a long time if there's no file
transfer proxy.

**Comment by iNPUTmice** [comment]
As @andersruneson said for P2P file transfer both clients have to be compatible. The only compatible clients right now are Conversations and Gajim.
If you are trying between Conversations and Conversations or Conversations and gajim please post an adb logcat output and I will reopen.

**Comment by iamale** [comment]
@iNPUTmice I don't get it. Isn't incompatibility with other clients bad?

**Comment by andersruneson** [comment]
Conversations can't fix other clients.

**Comment by fleixi** [comment]
No but it would be better to support more XEPs with filetransfer. Other XEPs a much more commen than 363

Am 16. April 2016 09:15:15 MESZ, schrieb Anders Sandblad <notifications@github.com>:

**Comment by LogicParrot** [comment]
>Conversations is trying to get rid of old behaviours and set an example for other clients.

-*README.md*

I think that is why the authors will not implement any more file transfer XEPs.

**Comment by iamale** [comment]
@LogicParrot This point is about using Chat markers and Carbon messages. Sending files for example over Jingle isn't considered an “old behaviour” in the Jabber community, I believe.

**Comment by d9h02f** [comment]
If it isn't, it should be.

**Comment by LogicParrot** [comment]
>This point is about using Chat markers and Carbon messages.

@iamale explicitly, yes, indeed. But judging from the generation atmosphere I see around, I believe this is also the implicit spirit throughout Conversations.

**Comment by LogicParrot** [comment]
>This point is about using Chat markers and Carbon messages.

@iamale explicitly, yes, indeed. But judging from the general atmosphere I see around, I believe this is also the implicit spirit throughout Conversations.

**Comment by iamale** [comment]
I love this overall attitude too, but implementing _an almost essential feature_ in a way that 99% clients/servers don't support yet is too much, I think.

**Comment by iNPUTmice** [comment]
Conversations supports the following methods for file transfer:

> XEP-0234: Jingle File Transfer
> XEP-0363: HTTP File Upload

in case of jingle you need support in the receiving client which as previously stated only Gajim has.
In case of HTTP File Upload you need support in your server.

**Comment by andersruneson** [comment]
Supporting more protocols requires more man hours and since Conversations
already supports two of the modern file transfer methods, those man hours
could be put in better use then old protocols to make Conversations
compatible with all non-maintained clients. If those were still maintained,
they would implement or fix this support themselves.

**Comment by jkufner** [comment]
None of the older file sharing methods ever worked for me. The first good and reliable method is HTTP upload. Don't waste your time on this old garbage.
