### ISSUE TITLE
Conversations keep logging off

### ISSUE THREAD

**Issue by Loader23** [siacs/Conversations#1801]
Hi,

i got a Problem with one of my Conversations Clients. Its a Galaxy A3 (2016). I got an Openfire Server running.
At some point, i dont know when, the A3 is listed as offline on the server and Messages won't be delivered. Only a restart of the device is helping then. I already switched from the Openfire 4.0.2 version to my old 3.10.3 but no difference. My old Galaxy S2 does not have any of these problems.
 
Even after a restart of the server my S2 logs in but the A3 remains offline. So I assume its not a server Error. I do not get any log files when it happens. The Conversations App is 1.11.3 but i had the same problems with 1.11.0. And Iam out of ideas now. Hopefully, you got some for me :-)
Thanks in advance

**Comment by andersruneson** [comment]
Check the debug log
https://github.com/siacs/Conversations/blob/master/README.md#how-do-i-debug-conversations

**Comment by Loader23** [comment]
I need root for that, right? Because i dont have root on the A3 and don't want to root it while it has warranty.

**Comment by andersruneson** [comment]
You don't need root.

**Comment by Loader23** [comment]
Yeah, sorry i was too quick.^^ It was an old Thread where i found that info.^^

Well ok. Great, i look into it and respond what the log says, thanks :-) Since i cannot force this to happen, it could take a day or two.

**Comment by Loader23** [comment]
Hi,
it took a bit longer but just wanted to inform that this Thread can be closed.
I switched from Openfire to prosody and that is working a lot better :-)

**Comment by andersruneson** [comment]
You can close it yourself, for issues you opened.
