### ISSUE TITLE
Background service killed in 'free' build flavor

### ISSUE THREAD

**Issue by pasdVn** [siacs/Conversations#1803]
I am using the F-Froid build of conversations and I am discovering the following issue since some months (some releases):

When I swipe out conversations from the recent apps list, the conversations background service immediately is killed and (in the very most cases) not restarted. Thus conversations can not receive any messages until I start the app manually again. Here an example log:
```
$ adb  logcat -v time | grep conversations
04-13 21:38:58.913 D/conversations( 3320): app switched into background
04-13 21:38:59.382 W/PackageManager(26516): Failure retrieving resources for eu.siacs.conversations: Resource ID #0x0
04-13 21:39:04.028 D/conversations( 3320): ####: leaving muc ####
04-13 21:39:04.033 D/conversations( 3320): ####: disconnecting force=false
04-13 21:39:04.033 D/conversations( 3320): ####: closing stream
04-13 21:39:04.083 D/conversations( 3320): good bye
04-13 21:39:04.086 I/ActivityManager( 2069): Killing 3320:eu.siacs.conversations/u0a75 (adj 16): remove task

<here nothing happens until I start the app manually again>

04-13 21:40:02.803 I/Timeline( 2600): Timeline: Activity_launch_request id:eu.siacs.conversations time:131734643
04-13 21:40:02.805 I/ActivityManager( 2069): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=eu.siacs.conversations/.ui.ConversationActivity bnds=[357,509][474,663] (has extras)} from uid 10018 on display 0

< and so on...>
```

The background services of other apps (like k9 mail) are also killed if you swipe them away, but at least they are started again right after they where killed (background services are quite strange in android as far as I read...).

I just read the FAQ about XEP-0357 and so I suppose, that it is somehow connected to the 'free' build flavour, that is not supporting the push notification (which is used at the F-Droid repository) and so requires a running background service in contrast to this one using the Google Cloud Notifications!?

I tested this on different devices (cm12.1 and android 6.0.1) with the same results (always the official F-Droid builds).

**Comment by d9h02f** [comment]
The solution is very easy: don't remove it from the recent apps.

**Comment by licaon-kter** [comment]
@pasdVn So you have `Conversations->Settings->Expert Settings->Keep in foreground` checked and you have a notification in the status bar, yet when you swipe, *both* the app and the notification disappear?

**Comment by pasdVn** [comment]
@d9h02f Yes, I know I could simply not swipe the app - that is my current workaround :)

@licaon-kter I'm not using the foreground option. With this option the process keeps alive - of course.

My expectation would be, that it is also working correctly (i.e. the process stays alive) when conversations is running as background service. Correct me if I am wrong...

As far as I understand the idea of services in android background services simply have a lower priority and *may* be killed if the the device is running out of memory while foreground services (with a notification in the status bar) are kept alive as long as possible.

**Comment by andersruneson** [comment]
Some phones needs to have the foreground service running to keep the app
from getting killed. Either use this or stop swiping the app away.

**Comment by licaon-kter** [comment]
This looks like a ROM issue (aggressive killing).

/close as invalid

**Comment by iNPUTmice** [comment]
This is intentional behavior to give users the possibility to kill or restart the app.
Just resist swiping it away or if you can't enable the foreground service.

**Comment by pasdVn** [comment]
I don't see the use case where a normal user needs to kill or restart the app. Moreover I think a normal user expects a communication app like conversation to always be abled to receive messages if the app is not active (WhatsApp, Skype, K9, Google Hangouts etc.) as long as he/she did not explicitly choose any option in the app's preferences to behave differently. In my eyes this behaviour is more confusing to a normal user than anything else.

By the way: I'm not a "swiper" myself, but my friends and family to those I want to advertise conversations as an alternative to an other well known IM app ;)

**Comment by andersruneson** [comment]
But as long as you don't have push and android, or the user, decides to
kill Conversations, there's not much Conversations can do about that??

**Comment by pasdVn** [comment]
My experience is, that the user does not want to terminate/kill an app if they remove it from the recent apps list. Neither they want a foreground process (an extra, permanent notification) for background services (if every background service would run in foreground mode, your notification area would be really confusing).

If a user does not want to run conversations (i.e. don't receive any messages) he/she can disable xmpp accounts.

I see that not many people are sharing my opinion here, but maybe it would a compromise to make this expert-setting have 3 states:
- foreground service
- not-dying background service ****new****
- terminatable background service (current default)

**Comment by iNPUTmice** [comment]
> not-dying background service *new*

this is not possible in Android without a foreground service. Android will kill your background service when you swipe away an activity.

**Comment by pasdVn** [comment]
But the service is restarted immediately which is no different from the user's point of view.

I just tried it and removed the logoutAndSave() in XmppConnectionService::XmppConnectionService() and it works for me.

Besides I think (if i rember right, maybe I should double check that) I also have seen services, that did not get killed when swiping it out (WhatsApp), but I don't know how this is done...
