### ISSUE TITLE
[Feature Request] Allow creation of wildcard and/or regex based notification filters

### ISSUE THREAD

**Issue by kabili207** [siacs/Conversations#1804]
I would love to be able to enable/disable notifications using wildcards or regular expressions. I use several transport services and would like to disable notifications for an entire service as they would be redundant on certain devices.

Example filters:
- From SMS transport
    - Wildcard: `*@sms.example.com`
    - Regex: `^.+@sms\.example\.com$`
- Account ends with "smith": 
    - Wildcard: `*smith@*`
    - Regex: `^.+smith@.+$`
- Any account on example.com that doesn't start with "sys-"
    - Regex: `^(?!sys-).+@example\.com$`

**Comment by iNPUTmice** [comment]
Not in the scope of the project. You might be able to hard code this right into the NotificationService

**Comment by kabili207** [comment]
If I implemented this feature myself and created a pull request, is it something you would consider merging?

**Comment by jkufner** [comment]
Take a look at [https://xmpp.org/extensions/xep-0016.html](XEP-0016: Privacy Lists). Filtering happens on server and it is possible to have multiple filter lists, different for each client. As far as I know, Conversations does not implement this, at least it is not possible to choose list to use with Conversations.

**Comment by kabili207** [comment]
I'm not trying to filter the messages, just the notifications for those messages. XEP-0016 doesn't handle the second and third examples I gave anyway, so it wouldn't be of much use to me.
