### ISSUE TITLE
SRV DNS record not used for HTTP Upload

### ISSUE THREAD

**Issue by martinsauter** [siacs/Conversations#1809]
When connecting to my XMPP server, Conversations correctly queries the DNS SRV record for XMPP. For HTTP Upload (Port 5281), however, a DNS A record lookup is made which points to a different server than the SRV record in my configuration. 

As a consequence I can't upload pictures with the http-upload mechanism without configuring port forwarding in my network of port 5281 from one server to the other. 

This is a bit of a kludge. Would it be possible for Conversations to query the XMPP SRV DNS record for the http-upload functionality as well?

**Comment by iNPUTmice** [comment]
No. Even if Conversations would do that. The recipient wouldn't do that. You can host your HTTP on a different domain though. (upload.domain.tld for example)

**Comment by martinsauter** [comment]
Makes sense, wouldn't work, agree. Thanks!
