### ISSUE TITLE
Conversations now always notifies for conferences

### ISSUE THREAD

**Issue by melloc** [siacs/Conversations#1810]
Until a recent update, I would only get notifications from conferences when my username was mentioned, which was the behavior I preferred. Now, it gives me a notification for ever message in the room, including after reconnecting to a server a printing the room's current subject. This is frustrating because sometimes my phone reconnects a lot and I'll get a notification for five rooms at once, but they're all just the room's subject.

Could there be an option to only get notifications from a conference room when my username is mentioned, like it used to work? I find this behavior much more useful, since some of the the MUCs I'm in can be rather chatty.

**Comment by iNPUTmice** [comment]
You can change this behavior in the conference details (either the group icon in the action bar or the entry in the overflow menu).

> including after reconnecting to a server a printing the room's current subject.

this is a bug in old versions of ejabberd by the way. You should update the server that hosts your conferences.

**Comment by melloc** [comment]
Ah, I missed that option. Thanks!

**Comment by SamWhited** [comment]
@iNPUTmice will that not prevent me from being notified when someone mentions me in a room too? At least from the name "Disable notifications" that's what I expect would happen, but that feels sub optimal to me.

I also had a hard time finding this option for whatever reason (in fact, I remembered this issue and had to come back to see where it was); I was expecting it to be a global option, I think (given that if ones preference is to not alert unless directly mentioned they'd have to go enable this for every new room they joined as opposed to setting the default globally and then changing individual rooms).
