### ISSUE TITLE
Certificate validation based on domain

### ISSUE THREAD

**Issue by jmhoya** [siacs/Conversations#1814]
Hello,

Apparently the application checks that the server certificate CN matches with the account domain instead of the hostname. So, for example, if I set my account to user@domain.com and the server is located at xmpp.domain.com, then the certificate check will fail if the common name is xmpp.domain.com instead of domain.com.

Is anyone else having this issue? Maybe in the future the settings could be detected automatically by checking the SRV records.

Regards,

Jose María

**Comment by iNPUTmice** [comment]
This is correct behavior. Your certificate must be valid for the domain part of the JID since this is the only thing you enter. You don't enter the hostname. Validating the hostname makes little sense as DNS can be spoofed by an attacker. 

https://tools.ietf.org/html/rfc6120#section-13.7
