### ISSUE TITLE
time of writing not respected

### ISSUE THREAD

**Issue by bastlwasti** [siacs/Conversations#1816]
Hello,

I noticed the following unexpected behavior: When you use conversations while offline, and later when you have again good connection, it may send all the photos and messages, but sometimes there are some photos which give a "failed to send". When you then press "resend", it finally is sent successfully. Unfortunately however the "date" of the photo is wrong and therefore it's position in the stream too.

The photo is sorted in the stream according to the date it was eventually sent successfully, not when it was written. For example, if you take one photo, add some describing message, then a second one, and a describing photo, and also  a third while offline, then it happens sometimes that when you are online the messages are sent successfully, but the photos not. In the end, you press 3x "resend", and the photos are also sent successfully, but unfortunately, the describing messages are above the photos, and it is no more clear which messages described which photo.

maybe you can fix this, thanks for the great app

happy day :)

**Comment by iNPUTmice** [comment]
Conversations is deliberately resetting the date when resending messages
because apparently some users expect it to be like this. (I guess this
comes from the idea that otherwise a resent message could be buried in
history)

I'm leaving this open maybe people can share their thoughts on this.

**Comment by petmue** [comment]
I got a decent idea:

Show the delayed message at the end of the conversation. 
However, add a symbol that indicates clearly that the message was meant to be received earlier. Then let the user swipe the message to the left in order to put it back into the correct chronological order. Voilá.

**Comment by bastlwasti** [comment]
xabber and whatsapp save time of writing, time received and time sent.
Thats probably the best way, to save all these times.

to solve the problem above, that they are not overlooked:
maybe for active chats, sort the new messages according to the time received, and the messages which were received before opening the conversation by time of writing?

**Comment by bastoon06** [comment]
Petmue's idea is good to me.

**Comment by tigre-bleu** [comment]
I personnaly prefer to have the messages in the same order as the receiver's list.

what could be done is to keep the message at the actual send position and to add a "ghost" message (maybe greyed out) at the location of the failed message in the timeline. We could also have in the status line instead of the time of sending something like "Re-sent at XX:XX:XX"

**Comment by bastlwasti** [comment]
in whatsapp, there is a special line inserted saying "unread messages". After that the unread are shown, and above that everything is in order of sending. 

Maybe the best approach is thus to have two sections: first a message sequence, which can be sorted accoriding to time of writing/time received/time of sending. Above that message which were not yet read.

**Comment by blevant** [comment]
User menu option to set preferred behavior?
