### ISSUE TITLE
add Delayed Delivery (XEP-0203)

### ISSUE THREAD

**Issue by NF117** [siacs/Conversations#1817]
Pls add support for protocol XEP-0203 (Delayed Delivery).

I want to write a message to an offline contact. Then I turn off my Internet. The server should be deliver the message if the contact come online.

**Comment by iNPUTmice** [comment]
I'm afraid that XEP doesn't do what you think it does.

I suggest you step by our conference room if you have general questions regarding Conversations or XMPP in general. 

Reading between the lines here I think you are trying to send OTR encrypted messages. That won't work. OTR is not capable of sending messages to offline contacts. You should use OMEMO instead.
If you were talking about unencrypted messages the server of your contact might be at fault. In any case the conference is a better place to discus those things.

FWIW: Conversations already supports delayed delivery.

**Comment by NF117** [comment]
Thanks for the tip. With OMEMO offline chat works very well :+1:
