### ISSUE TITLE
Inexact scheduleWakeUpCall

### ISSUE THREAD

**Issue by llweifall** [siacs/Conversations#1818]
Hello developers of Conversations,

I have found that `AlarmManager.set` is used in `XmppConnectionService.scheduleWakeUpCall` to schedule intents.

However, on devices with OS newer than KitKat, it is treated to send the alarm at a not exact time (Found in [API Guide](http://developer.android.com/intl/zh-cn/reference/android/app/AlarmManager.html#set(int,%20long,%20android.app.PendingIntent))). The system may delay the alarm scheduled by this API. A new API `setExact` was introduced to send alarms at exact time.

Since the method `scheduleWakeUpCall` is invoked in many places, I cannot ensure that if it is essential to schedule the alarms at a every exact time so I report this issue for your reference.

Hope this information is useful.
Thanks a lot.

**Comment by iNPUTmice** [comment]
Not it is not. But thanks
