### ISSUE TITLE
Android 6 Direct Share not working from many apps

### ISSUE THREAD

**Issue by allo-** [siacs/Conversations#1819]
The share intent from firefox, twitter and many other apps only allows the **non-direct** share intent, which opens the buddylist first.
Probably the problem is, that the direct share intent has a too narrow list of accept content types and these apps send them as another type.

(extending the comment https://github.com/siacs/Conversations/issues/1321#issuecomment-206321015 in an fixed issue to a new bug here).

**Comment by iNPUTmice** [comment]
The intent filters are exactly the same.

This is a problem with the apps. They don't wrap their intent in an chooser intent which would enable the direct share.

**Comment by allo-** [comment]
This is true for a lot of apps, while the feature to share with one contact when something just calls an intent "share text/plain" is a feature which would be very useful.
