### ISSUE TITLE
Only one notification for new messages in group chats

### ISSUE THREAD

**Issue by schiesbn** [siacs/Conversations#1820]
Currently I get for every new message in a group chat a new notification and couldn't find a way tweak the behavior. Getting a notification for every message can be quite annoying if a lot of conversations happen in a group chat. I would like to have following behavior, at least as a option:

- Receive a notification for the first new message
- No notification for any follow-up message (at least not with a extra sound for every message)
- Only after I looked at the chat I should get again a notification if a new message pop up

**Comment by iNPUTmice** [comment]
You can tell Conversations to notify you only when your name is mentioned. Does this solve your problem?

**Comment by MRZA-MRZA** [comment]
I can't find an option to notify me if my name is mentioned. With latest update I get notification for every message in MUCs.

**Comment by d9h02f** [comment]
It's in the details page for the MUC.

**Comment by MRZA-MRZA** [comment]
Thank you. It wasn't to obvious for me because it was a global option previously.

**Comment by schiesbn** [comment]
> You can tell Conversations to notify you only when your name is mentioned. Does this solve your problem?

Not really. I would like to get a notification if something happens, also if I don't get mentioned. I just want that during a intensive discussion in one group chat my mobile phone beeps every second. Therefore the suggestion I mentioned above

**Comment by petmue** [comment]
> Not really. I would like to get a notification if something happens, also if I don't get mentioned. So that I can look at it and see if it is interesting for me. I just don't want that during a intensive discussion in a group chat my mobile phone beeps every few seconds. Therefore the suggestion I mentioned above

Sounds like a duplicate to me of https://github.com/siacs/Conversations/issues/1746 and https://github.com/siacs/Conversations/issues/762

**Comment by schiesbn** [comment]
Yes, just with a other proposed solution. But I can move this over to the other issue, so let's close this one as duplicate
