### ISSUE TITLE
Keep draft even when correcting previously sent message

### ISSUE THREAD

**Issue by axelsimon** [siacs/Conversations#1822]
Hi,
Currently, Conversations saves drafts of unsent messages, which is great.

However, I noticed a small inconvenience, since introducing the possibility to correct previous messages: if one starts typing a message (call it message 1), then decides to correct a previously sent message (call it message 0), what was currently in the text box (1) gets replaced by the message to be corrected (0). Makes sense.

Once the corrected message has been sent (0), the text entry box stays empty.

It would be very convenient if the original message one had started to type (1) was kept as draft and the text entry box went back to that message (1) after sending the corrected message (0).

I hope this makes sense, it's quite obvious when one starts using the correction function a bit.

Thanks again for making Conversations!

**Comment by singhalok641** [comment]
I'd like to work on this issue. Any suggestions for implementation are welcome.
