### ISSUE TITLE
[Feature request] Send and display typing notifications in group chats

### ISSUE THREAD

**Issue by thundergreen** [siacs/Conversations#1823]
A typing notification in muc would be nice.maybe this will find a place in mix?

**Comment by kriztan** [comment]
:+1:

**Comment by blevant** [comment]
RTT would be great also

xep 0301

**Comment by badarsh2** [comment]
There is already an issue meant for this? (Though it was created later)
https://github.com/siacs/Conversations/issues/2312

**Comment by iNPUTmice** [comment]
Forgot about this issue. This was fixed in 1.17.0 I believe.
