### ISSUE TITLE
[Feature] Pop Up Reply

### ISSUE THREAD

**Issue by DoM1niC** [siacs/Conversations#1824]
Hey.

Currently a lot of ppl ask about the popup reply feature in Notification. I hope there is possible to make a Option for a Quick Reply Feature like Whatsapp....

**Comment by iNPUTmice** [comment]
This will have to wait for Android N as this brings the required API.

**Comment by amenk** [comment]
How is WhatsApp (for example) doing it?

**Comment by iNPUTmice** [comment]
Fixed in Conversations 1.14 for Android N

**Comment by licaon-kter** [comment]
So this can't be backported to Android 6/5 ?

I'm now using [QuickReply](https://play.google.com/store/apps/details?id=com.jamworks.quickreply) to get this, but a native option would be nicer.
