### ISSUE TITLE
Fallback to direct transmission on HTTP Upload file size exceeded

### ISSUE THREAD

**Issue by bitboulder** [siacs/Conversations#1828]
My server provides HTTP Upload feature for file transmissions with a file size limit. If I try to transmit a file larger than the limit, I get an send failed error. So I cannot share large files.

Would it be possible to fallback to direct transmission in case of file size limit exceeded? According to XEP-0363 the server should inform the client about the limit on service discovery.

**Comment by iNPUTmice** [comment]
Conversations does check for this. Maybe your server doesn't report the limit? Or your counterpart doesn't support jingle. A logcat might help

**Comment by bitboulder** [comment]
You find the logcat at: http://www.bitboulder.de/logcat
I connected to the server and tried to send a file larger than the limit two times (lines with "send file message").

With OTR encryption the direct transmission works on that server, but with OMEMO encryption and unencrypted I cannot send files larger than ~10MB. The counterpart also uses conversations on the same server.

How can I see which limit the server reports?

**Comment by iNPUTmice** [comment]
Ask your server operator if they are using the latest version of the plugin or query the server manually with a client that lets you send XML or update Conversations. The current HEAD includes some more logging for the fallback.

**Comment by bitboulder** [comment]
I used XML console of gajim to do service discovery on the server.
You find the log at: http://www.bitboulder.de/xml_log.txt

Seems that the server doesn't report any information about the http.upload feature except it's existence. On requesting an upload slot I get an error with the message "File too large".
Is it possible to fallback to jingle on this error message?

I currently had not the time to compile and run the current HEAD to test the extended logging, but I will do that. Thank you for that support.

**Comment by iNPUTmice** [comment]
Falling back to Jingle after the fact is a bit complicated. Thats why the protocol has the ability to report the filesize. jabber.de should just update the module.

**Comment by bitboulder** [comment]
jabber.de now updated the plugin and by using XML console the limit is reported
(see lines 31-38 in http://www.bitboulder.de/xml_log2.txt),
but I still get a send failed error for large files.

I created a logcat with the version 1.12.2 (including extended logging) and found the line:
"server did not report max file size for http upload" (see http://www.bitboulder.de/logcat3).

**Comment by iNPUTmice** [comment]
@bitboulder ok thanks.

The problem is that Conversations caches the disco responds from the server but doesn't save the from data. I wasn't aware that prosody is offering the HTTP Upload stuff on its server jid.

I put it on my todo list.

**Comment by notfoss** [comment]
I am facing the same issue and was wondering if there has been any progress to fix this?

**Comment by iNPUTmice** [comment]
This has been fixed a long long time ago and Conversations does not attempt
to use http upload if the expected file site exceeds the limit.

**Comment by notfoss** [comment]
Ah, thanks for the info. So, my issue wasn't exactly the same, instead it is about upload quota (**x** number of files in **y** number of minutes). I was assuming that this issue will handle that as well.

So, when a quota is reached, Conversations can fall back to direct transfers.

That should be example 8 on https://xmpp.org/extensions/xep-0363.html

If that hasn't been implemented, then shall I open a separate bug report for it? Also, I am using jabber.at, if that helps.
