### ISSUE TITLE
OMEMO: Add device description, creating date and rejection tag

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1830]
Hi!

The status quo is that it is only known to whom a OMEMO fingerprint belongs but it is not easily to determine to which device it belongs and if it is still in use or has been rejected. This applies especially when a user has many devices and accordingly has many OMEMO fingerprints.

To resolve this problem I suggest 
* expand the OMEMO-XEP by allowing the user to additionally set a device name
* add a time stamp of creation of the OMEMO key
* let the user manually reject a key
* add a tag in case the OMEMO key was rejected

and share all these information when exchanging the OMEMO key with contacts.

Best Greetings

**Comment by d9h02f** [comment]
Why?

**Comment by iNPUTmice** [comment]
I don't know what 'rejecting a key' means. You can decide not to trust keys.

**Comment by alexara** [comment]
> Why

Please become more concrete and specify your question. However I try to guess:

The issue here is, when a contact reinstalls Conversations again on his/her phone a new OMEMO key is generated. This means I have two OMEMO keys of my contact for the same device.
Now let the contact do the same on another device.

Whenever a new OMEMO key is generated I am only asked to accept it, I don't know why there is a new one unless my contact tells me.
Now a fifths key is generated.

* Let's consider he/she tells me the key belongs to a new device. Then we are finished here. All OMEMO keys are still valid.

* If he/she tells me that he had to reinstall Conversation on the same device, one of the OMEMO keys become invalid.
So, to go back to the example with the four keys: which of the four keys do I have delete or mistrust now (without trial and error)? (Normally no one starts memorizing or writing which key belongs to a device.)


Is this question clear or did I miss something? Please enlighten me.

**Comment by iNPUTmice** [comment]
> This means I also have these two keys of my contact. Now my contact reinstalls Conversations on one of his devices and a new key is generated. Now there are three keys.

Your contact should select 'clear devices' from the account details. This will invalidate the old key from the installation.

The problem with device labels is that those labels can be used to lie to you by someone who tries to sneak more keys into your trusted device list.

**Comment by alexara** [comment]
> Your contact should select 'clear devices' from the account details. This will invalidate the old key from the installation.

Where is this button "clear devices"? Do you mean I have to delete the grayed out key under "other devices"? If my contact does it, will the key automatically become invalid on my device too?

> The problem with device labels is that those labels can be used to lie to you by someone who tries to sneak more keys into your trusted device list.

I see.

**Comment by iNPUTmice** [comment]
> Where is this button "clear devices"? 

In the menu

> Do you mean I have to delete the grayed out key under "other devices"? 

no. but this will make the unused keys appear grayed out. On both your client and the client of your contacts. Grayed out keys won't be used any more.

> I see. But having device tags would at least help myself to know which key each of my own devices has.

How many active devices do you have? Three? This makes two 'other devices'. It shouldn't be too hard to differentiate between them if you must.

By the way touching your avatar or your contacts avatar in a specific message will mark the key used for this particular message.

**Comment by alexara** [comment]
> > Where is this button "clear devices"?

> In the menu

Can you make a screenshot? I only have "Show QR, show blacklist, show server info, archive settings, change password and settings"
In the settings there's nothing similiar to "clear devices".

**Comment by d9h02f** [comment]
It's in between change password and settings for me.
