### ISSUE TITLE
Avatar of contact linked to address book

### ISSUE THREAD

**Issue by bastoon06** [siacs/Conversations#1836]
When a XMPP contact is linked to the Android address book, conversation will use the picture provided by the address book rather than the avatar provided by XEP.

It would be better to :
- by default use the user provided avatar. User may talk about his new avatar, you won't notice it.
- add an option if you want to replace it with a static picture.

**Comment by iNPUTmice** [comment]
Matter of taste. There are no plans to change the behavior. You can remove the JID from the address book though if you don't want it.
