### ISSUE TITLE
Incompatible server / error connecting account

### ISSUE THREAD

**Issue by dpocock** [siacs/Conversations#1837]
When I try to connect to Prosody, I see "Incompatible server" in the accounts list part of the UI

I look at the logcat output and I see:

```
TLS connection established
error connecting account. try again in 56s for the 3 time
```

What does this error mean?  Can you include more verbose logging, for example, this log doesn't tell me if it is failing because of the certificate, the password or something else.

**Comment by dpocock** [comment]
After a Prosody restart, the problem has gone away, but the lack of log messages means I have no further detail to give the Prosody developers.

**Comment by iNPUTmice** [comment]
There is an FAQ entry for this.
