### ISSUE TITLE
Subject being set results in repeated notifications

### ISSUE THREAD

**Issue by traylenator** [siacs/Conversations#1840]
When a subject is set in a conference room repeated notifications are sent despite the subject
not changing.

![image](https://cloud.githubusercontent.com/assets/135205/15206813/3dd11f28-1822-11e6-8324-e85e895ab192.png)

**Comment by d9h02f** [comment]
https://github.com/siacs/Conversations/issues/1269

**Comment by traylenator** [comment]
It's ejabberd so that sounds like it - thanks.
