### ISSUE TITLE
[UI] accounts settings are hidden

### ISSUE THREAD

**Issue by Djamoussa** [siacs/Conversations#1841]
Hi !

In accounts list, when you type settings, the first line is truncated (see picture below) 

![screenshot](https://cloud.githubusercontent.com/assets/10303655/15210606/7b8184ce-1837-11e6-89ec-4c2163c0bc84.jpg)

**Comment by iNPUTmice** [comment]
The translation is just too long. Do you have a shorter one?

**Comment by Djamoussa** [comment]
Hum not in staying clear and/or keeping exactly the same meaning.
It could be "account with certificate" in shorter...
No way to make the window more "text responsive" ?

**Comment by iNPUTmice** [comment]
> No way to make the window more "text responsive" ?

no

**Comment by Djamoussa** [comment]
Ok, translation update
