### ISSUE TITLE
C does not check the installed certificate

### ISSUE THREAD

**Issue by gerroon** [siacs/Conversations#1843]
Hi

I am not sure if this is a feature or a bug but when I installed it and added my account it did not rely on the installed certificate. I am running my own xmpp instance and I already imported my server certificate to device but C did not care about it and it still asked me if I wanted to trust the certificate or not.

thanks

**Comment by iNPUTmice** [comment]
Worked for me. Afaik you have to install the root certificate though. Not
the server certificate.
If anything this is a bug in your Android version. but probably not. You
probably installed the wrong certificate or something else in the
certificate is wrong (signed the Hostname and not the domain name for
example )
Conversations doesn't make a difference between user installed certificates
and system default certificates.

**Comment by gerroon** [comment]
I do not have a root certificate, this is a self signed certificate and it works in other apps that require connecting to my server. 

Anyways thanks for your help, I will dig around a bit.

**Comment by andersruneson** [comment]
Use letsencrypt?
