### ISSUE TITLE
Issue with status updates

### ISSUE THREAD

**Issue by gerroon** [siacs/Conversations#1845]
Hi

When I stop Conversations (using apps->stop) on one device, the status of the killed android client still  shows up as "online" on another device. I am not sure if this is an issue with my ejabberd server or something to do with Conversation on the other device.

The devices are Samsung S7s and the Ejabberd is running on Debian Wheezy.

thanks

**Comment by gerroon** [comment]
Ok, replying to myself. This is most likely ejabberd issue, I was able to somewhat make it reasonable by enabling mod_ping in the server settings.

**Comment by andersruneson** [comment]
Won't mod ping drain your battery? Or how often does it ping?

**Comment by gerroon** [comment]
Well, I set it to 200 secs. What is a good ping amount?

Do you know any other solution to this problem?

**Comment by andersruneson** [comment]
Don't kill Conversations and don't care about the online status?

Ping time of 3-4 minutes seems like it will kill your battery pretty fast.

**Comment by gerroon** [comment]
@andersruneson 
It is not just killing the app, this is also an issue if there is no wifi available. 

I will set it to 10 mins I guess. 

I need some way of letting the server know that the client is unaccessible. I cant find a way to do that beside this ping way.
