### ISSUE TITLE
Server not found after wifi connection is regained.

### ISSUE THREAD

**Issue by gerroon** [siacs/Conversations#1846]
Hi

If I loose the wifi and reconnect after a while, Conversations claim that the server not found in the account page. If the user does not click on the manage account page, he/she will never know that the connection is dropped. That is the first isssue

The second issue is that why cant find the server? If I gently disable and enable the account, it is able to connect to the server just fine. So within the time frame of the lost and the regained connection something does not go right. Or something does not go right after the system is able to connect to a wifi.

I use custom certificate with the host name defined in the Hosts file (via Adaway). I am using Android 5.1.1 on S7

thanks

**Comment by iNPUTmice** [comment]
Please read the contributing guidelines and use the issue template to
create bug reports. Network related issues must contain an adb logcat
otherwise we can't help you.
