### ISSUE TITLE
OMEMO not available 

### ISSUE THREAD

**Issue by JasperWeiss** [siacs/Conversations#1848]
I'm testing conversations and made several burner accounts within the app so that I can send messages to one another. But OMEMO never seems to be available. 
Does OMEMO require any sort of server-side support?
Also, messages fail to deliver when the recipient account is offline. Is that just my server lacking support for offline messages?

**Comment by iNPUTmice** [comment]
* Please read the [Contributing guidelines](https://github.com/siacs/Conversations/blob/master/.github/CONTRIBUTING.md).
* For general questions please use our conference *[conversations@conference.siacs.eu](xmpp:conversations@conference.siacs.eu?join)*
* If you create a bug report use the provided template.
