### ISSUE TITLE
Cannot initiate OMEMO encrypted session with newly added contact

### ISSUE THREAD

**Issue by aurabindo** [siacs/Conversations#1850]
#### General information

* **Device:** Xperia L
* **Android Version:** Cyanogenmod 12.1
* **Server name:** diasp.in
* **Conversations source:** fdroid, version 1.12.2

After I add a new contact and start a conversation, I am unable to initiate a OMEMO encrypted chat. The option is disabled for me. While the other contact I just added, can initiate encrypted chat from their side.

**Comment by pravi** [comment]
I have also noticed this issue.

**Comment by iNPUTmice** [comment]
Assuming that your server supports PEP and runs prosody I'm fairly certain this is a prosody bug. https://prosody.im/issues/issue/673

fwiw. If you relogin (deactive and activate your account) OMEMO should be available.

**Comment by iNPUTmice** [comment]
seems to be fixed: https://hg.prosody.im/0.9/rev/ad0b15f253ee
