### ISSUE TITLE
After tabbing on "delete key" while proofing new omemo-key nothing happens

### ISSUE THREAD

**Issue by alexxthehood** [siacs/Conversations#1851]
#### General information
- **Device:** eg Google Nexus 5
- **Android Version:** Android 6 Cyanogenmod
- **Server software:** ejabberd 16.04
- **Installed server modules:** Stream Managment, CSI, MAM
- **Conversations source:** F-Droid
#### Steps to reproduce
1. Start a new conversation with a contact where you need to proof his/her OMEMO key
2. When you check the key and there's another old one you can long press on it and tab to delete it
#### Expected result

> What is the expected output? What do you see instead?
> The key should be deleted but nothing happens.

**Comment by SoyaLeaf** [comment]
is it outdated? @iNPUTmice

**Comment by iNPUTmice** [comment]
@SoyaLeaf I don’t know. I've never been able to reproduce this.
