### ISSUE TITLE
[Feature request] timed message à la Telegram's secret chat

### ISSUE THREAD

**Issue by davidlatapie** [siacs/Conversations#1852]
There is always a moment when you will forget to delete a data. And, Murphy helping, this is when this oversight will cost you. You have taken great care of preventing man-in-the-middle and intiating end-to-end… but then your phone had been seized - and considering the present state of Android, you can't expect a strong password to protect you from serious forensics

Automatically deleting messages after a while is a way to mitigate this weakness, so thank you to consider optional timed messages. Ideally, timed messages should be enforced on both sides (what Telegram does) but even if they are only enforced in one side, this is better than nothing.

**Comment by iNPUTmice** [comment]
timed messages where the sender sets a timeout are currently not on our TOD list. 

maybe one day we will implement something like #1424 - but even that's not very high on our priority list.
