### ISSUE TITLE
Last activity not shown

### ISSUE THREAD

**Issue by kevinkk525** [siacs/Conversations#1853]
#### General information

* **Device:**Oppo Find 7
* **Android Version:**  Android 5.1 Cyanogenmod
* **Server name:** jabber.at, self hosted
* **Server software:** ejabberd 15.09
* **Installed server modules:** Stream Managment, CSI, MAM, a lot more
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Use Conversations 1.12.3
2. Check contact details --> no last activity shown; with the previous version of conversations the last activity was shown above the dynamic tag

#### Expected result

Show last activity

**Comment by iNPUTmice** [comment]
This 'feature' has been removed because it was unreliable and just didn't exactly do what it promissed.

**Comment by kevinkk525** [comment]
Well that is sad. For me it worked very acceptable and it was useful in my eyes.
Will there be a similar feature?
