### ISSUE TITLE
[Feature] Make it possible to change status message while keeping dynamic tags

### ISSUE THREAD

**Issue by kevinkk525** [siacs/Conversations#1854]
Recently the feature to change the status with a status message and tag was added.
I'd like to see the possibility to change the status message but not the tag so that the tag still is being set automatically as it is without that option.

Additionally it would be awesome if that feature could be activated per account, not globally.

**Comment by iNPUTmice** [comment]
Not on our TODO list.
If you want to transmit permanent information in your presence message that doesn't change even if the presence itself changes you might be abusing the presence message for something it is not.
