### ISSUE TITLE
syncing keys in omemo conferences

### ISSUE THREAD

**Issue by pravi** [siacs/Conversations#1855]
Following up on #1849

Currently omemo can be enabled only if all participants are in a roster. So when I create a conference and enable omemo, others may not have everyone in their roster. In Signal groups, when a new member is added, their keys are synced with all members as well. We should find a way to synchronise keys of all members.

**Comment by iNPUTmice** [comment]
Please note that the original ticket #1372 has not been closed yet.
The current way of transporting group messages over MUC is just a workaround until MIX comes along
