### ISSUE TITLE
MAM fetch with a lot of files let Conversations hang...

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1856]
#### General information
- **Device:** Samsung Galaxy S3
- **Android Version:** Android 4.4.4 SlimRom
- **Server name:** self hosted
- **Server software:** prosody trunk
- **Installed server modules:** all required for Conversations except CSI
- **Conversations source:** self build (latest HEAD)
#### Steps to reproduce
1. Send or receive messages with a lot of files (e.g. 10 or more)
2. Clear message history
3. Load messages via MAM from server
4. Conversations loads all files at the same time and hangs (ADB shows `The application may be doing too much work on its main thread.` and Android shows a dialog `Conversations isn't responding. Do you want to close it?`)
5. After waiting some more secondes Conversations is responding again and had downloaded all files.
#### Expected result

Conversations should fetch the messages and add the downloads into a queue so that it stays responsable for the user.
#### Debug output

There is no output getting hint of failures but `The application may be doing too much work on its main thread.`

**Comment by kriztan** [comment]
Am I the only one having this issue? To reproduce this, you can try to scroll the message list during receiving or sending a file. Scrolling is lacking. Especially on slow connections or with bigger files, which could not be sent/received within a few seconds it breaks the UX and on multiple files it causes Conversations to hang and android askes to wait or kill the app.
I've figured out that this is caused by the up-/downloading process of files. Updating the progress should be updated in background or within an async task.

**Comment by iNPUTmice** [comment]
I'm unable to reproduce this issue and I'm also not seeing any ANRs in the Google Play developer console for this.
