### ISSUE TITLE
Crash when deleting an online account

### ISSUE THREAD

**Issue by LogicParrot** [siacs/Conversations#1861]
#### General information

* **Device:** Nexus 5
* **Android Version:**Android 6.0 Rev 49
* **Conversations source:** f-droid, v 1.12.2

#### Steps to reproduce

1. Create an account on some server.
2. Long-press the account in the "Manage accounts" menu and then tap "Delete account".
3. Conversations crashes. (If that fails, see notes for precise reproduction)

Notes:
- In my case, I had 2 accounts, and the one I tried deleting is the more recently added account, which was the 2nd in the menu. Both accounts were online.
- Taking the account offline prior to deleting it resolves this.

#### Expected result

I expect the account to be deleted.

#### Debug output

I do not have one. I can try providing one if this is essential.

**Comment by iNPUTmice** [comment]
> I do not have one. I can try providing one if this is essential.

this would be great. because in a quick test I wasn't able to reproduce this

**Comment by LogicParrot** [comment]
I broke my Android, so the log could take a while.
In the meanwhile, here are some more details:

- As mentioned, I had 2 online accounts and tried deleting the **second** one.
- Both accounts had active conversations.
- The second account was logged in to a conference. This might be a factor.
- The crash did not completely close Conversations. Instead, it takes me back to the contacts menu. So it seems like an activity crash or something.
- The crash was reliably repeatable.
