### ISSUE TITLE
[Feature Request] Jump to a highlighted/whispered message in MUC

### ISSUE THREAD

**Issue by gkirilov** [siacs/Conversations#1862]
Currently, when I get a notification for a highlighted message (my nickname is mentioned) or a whisper, pressing it opens the MUC, but jumps to the end of the chat, not the message itself.
If there are many group messages after that, it can take a lot of swiping to get to it.
And back to the end. (#1473)

**Comment by alexara** [comment]
Maby there could be a button which filters all highlighted / whispered messages and when clicking on one the these you would jump the message in the MUC history.

**Comment by iNPUTmice** [comment]
Jumping to the last unread message will probably happen at some point. But treating whisper messages differently (or even filtering for them) will not happen. Conversations is actively trying to steer people away from using private MUC messages.
