### ISSUE TITLE
Cannot save received files of unknown type

### ISSUE THREAD

**Issue by viric** [siacs/Conversations#1864]
Version: 1.12.3

I send a file "dictionary.zim" to a contact, and he receives it, but he can only "Open file" with some program. None of the programs listed can open the file.

The file is meant for the application Kiwix, that does not associate itself with ".zim" files, so it even does not appear in the list of programs to run. A common usage is to start Kiwix, and make it open a file stored in the SD card. But we cannot save the Conversations sent "dictionary.zim" file to any specific place.

The same would apply for any file that no one is expected to have an App for, like a ".odt" file more meant for a computer than a phone.

Couldn't there be an option like "save to..."?

**Comment by iNPUTmice** [comment]
Well the file is already stored on your SD card. Can you not just point Kiwix to it?
Or if you must use a file explorer to move the file?

**Comment by viric** [comment]
How to know where the file is?

**Comment by licaon-kter** [comment]
It's usually in **/sdcard/Download** or in the older **/storage/emulated/0/Download**

**Comment by viric** [comment]
What is the rule for where do files go? Images sent don't go there, right?

**Comment by viric** [comment]
Conversations does not even say the filename anywhere, at least me - as a sender - does not see it.

**Comment by iNPUTmice** [comment]
> The file is meant for the application Kiwix, that does not associate itself with ".zim" files, so it even does not appear in the list of programs to run

I think this is the real issue here.

> What is the rule for where do files go? Images sent don't go there, right?

Images go in the pictures folder.

**Comment by erdmark** [comment]
You can use Send to SD card (Copy things to the local storage) - https://f-droid.org/app/ru.gelin.android.sendtosd

Usage: long press on sent file, share via, choose Send to Sd and let it save where you want

**Comment by viric** [comment]
@iNPUTmice So what to do, when I send a file that is not expected to have an association with any Android program? I think Conversations should at least offer a way to show the filename or its path in the SD.

**Comment by viric** [comment]
For example, it has a "Copy URL" function, which just renders into ciphered jibberish - so it is pretty useless. Why couldn't there be something that shows the file path?

**Comment by iNPUTmice** [comment]
> I send a file that is not expected to have an association with any Android program

ask yourself the question why you sent this file to an Android phone in the first place

Or use the solution suggested by @erdmark

**Comment by viric** [comment]
I send the file with Android because Conversations might be one of the few ways I have to send files ciphered to colleagues easily.

**Comment by d9h02f** [comment]
You have a need to send encrypted offline copies of Wikipedia articles to people?

**Comment by luweitest** [comment]
I encountered this today. This is a real issue that should not be closed. "Send to SD card" is just a workaround. Conversations could provide an option in itself to open the download directory.

**Comment by licaon-kter** [comment]
It's not "send to sdcard" ....the file is saved anyway....point the app to open /sdcard/Conversations/....

**Comment by luweitest** [comment]
Yes, but Conversations should give normal users an option to open the saved directory for later process. I searched using File manager plus, but quite a lot people do not even know Android has a file manager.
