### ISSUE TITLE
PGP: Not detecting self compiled OpenKeychain

### ISSUE THREAD

**Issue by MarcinWieczorek** [siacs/Conversations#1866]
Because of freedom I decided to compile OpenKeychain by myself. Unfortunately the app still asks me to install it from F-Droid or the store. Should I enable it somewhere else?

**Comment by licaon-kter** [comment]
But it detects the one from F-Droid:  https://f-droid.org/repository/browse/?fdfilter=pgp&fdid=org.sufficientlysecure.keychain ?

**Comment by iNPUTmice** [comment]
Maybe you've built the debug version which uses a different package name.
Either build the release version or change name package name in the
Conversations source code

**Comment by MarcinWieczorek** [comment]
I might have built debug version. Will let you know if release works.

**Comment by MarcinWieczorek** [comment]
Thanks ;)
