### ISSUE TITLE
[Feature/Question] Conversations as Message History Hub

### ISSUE THREAD

**Issue by amenk** [siacs/Conversations#1867]
#### Steps to reproduce

Server does not support message archiving; Carbons are on

1. Chat on my laptop computer (Gajim)
2. Chat on my mobile (Conversations)
3. Later open my home computer (Gajim)

#### Expected result

Messages I wrote on the laptop appear also on my home computer.

#### Question / Suggestion

While this is supposed to work with message archiving, it would be cool if it could work without depending on the server.

As my mobile is always-on, the history is usually complete.

Could a feature be added so that Conversations resends the messages to the new client to sync the history? Is there a XEP for that? Is a XEP needed?

**Comment by iNPUTmice** [comment]
You could probably make Gajim request the messages with MAM from Conversations. But that requires both work on Gajim and Conversation. Feel free to try that (I'm happy to give you some pointers if you join our conference) but I personally don't see the benefit over a server side archive.

**Comment by andersruneson** [comment]
I guess you should first start with writing a XEP. But why not change to a
better server? Or request from the server operator to install mam?

**Comment by amenk** [comment]
I am going to search a better server.

Thanks anyways !

**Comment by amenk** [comment]
Okay sorry to be off topic - but can you recommend me a hosted server that supports MAM + OMEMO + Custom Domains and isn't very expensive? I went trough http://wiki.xmpp.org/web/Jabber_Hosting_Possibilities and all had issues ...
