### ISSUE TITLE
'Handsfree' (voice/speech to text)

### ISSUE THREAD

**Issue by markfoodyburton** [siacs/Conversations#1868]
I'd like to see Conversations supporting input via speech input so it can be used hands-free. If this was done properly (rather than using e.g. the voice keyboard), the entire interaction could be made handsfree (even eyes free). 

(Is anybody working on something like this?)

Cheers
Mark.

**Comment by iNPUTmice** [comment]
> (Is anybody working on something like this?)

not that I know of.

**Comment by markfoodyburton** [comment]
If you like the idea, and you want me to have a go, then give me a couple of pointers about where in your code I should look to integrate something like this, and I'll take a look.

**Comment by iNPUTmice** [comment]
Not sure what you need to know for this. Not sure what is actually required for this in terms of library support or anything. Maybe step by our conference if you have questions.

**Comment by phrokton** [comment]
> speech input 

So [jingle](http://xmpp.org/about/technology-overview.html#jingle)?

**Comment by markfoodyburton** [comment]
Actually the original idea is not to construct multi-media streams, rather send text over the XMPP stream as it is, but to arrive at that text without recourse to touching anything, e.g. just with speech. You can do this today on a phone using the Google voice keyboard but the experience would be a lot better if the app took control - specifically it should be possible to be totally hands (and eyes) free.

**Comment by bastlwasti** [comment]
wechat has a "walki-talkie" mode.. maybe you can get some inspiration from there :)

**Comment by markfoodyburton** [comment]
So I put a pull request together. For me, it's working really nicely. I've got it set up to 'only work on bluetooth', so - I get into my car, and conversations does all the right things for me to not have an accident :-) - In the meantime it looks like there may be conflicts, if you need help sorting it out, let me know.....
BTW - I believe this is the ONLY IM client that handled hands-free correctly (and works). There is one other in the app store, but I couldn't get it to work at all. 
For me - this is a really helpful function, it means you can safely continue IM's while on the move (or if you are visually impaired, or find typing slow and hard).

Anyway - @iNPUTmice  let me know if I can help more.

**Comment by thundergreen** [comment]
@markfoodyburton did u already successfully integrated this feature?

**Comment by markfoodyburton** [comment]
@thundergreen .... Yes - the feature is working pretty well. I have a little issue with bluetooth connection, but apart from that, leave your phone in your pocket, and keep chatting to your friends/colleagues totally hands free.

@iNPUTmice hans't commented on the pull request - I'd appreciate feedback, and if there is anything I can do to help let me know (time is limited, but... I'll try :-) )

**Comment by thundergreen** [comment]
But u don't have the newest version of conversations.. Could u update your
fork maybe to the last version and your feature?  Would love to try

Thorsten Fröhlich
Am 30.06.2016 10:37 schrieb "markfoodyburton" <notifications@github.com>:

@thundergreen <https://github.com/thundergreen> .... Yes - the feature is
working pretty well. I have a little issue with bluetooth connection, but
apart from that, leave your phone in your pocket, and keep chatting to your
friends/colleagues totally hands free.

@iNPUTmice <https://github.com/iNPUTmice> hans't commented on the pull
request - I'd appreciate feedback, and if there is anything I can do to
help let me know (time is limited, but... I'll try :-) )

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/siacs/Conversations/issues/1868#issuecomment-229597411>,
or mute the thread
<https://github.com/notifications/unsubscribe/AMtAfxARXLURQlqn8nqS0YCSSv9pDngZks5qQ4BfgaJpZM4IkBg6>
.

**Comment by markfoodyburton** [comment]
Your right - I forked from a branch that already supported the latest version of studio, before the work that has just been carried out to do the same. I haven't followed the latest updates, so I dont know how far from the current code base my patch is...

In all honesty - I will get to this, but I dont have much time,  if you had a moment to take a look and see where the major conflicts are, that would help enormously....

**Comment by thundergreen** [comment]
Unfortunately I'm not a coder...  I follow up the conversions project for a
long time and help some testing with ejabberd.. I won't be any help. But
maybe there's someone out there being able to?
Would be highly appreciated as inputmice didn't reply to my question of he
wants to implement it in his version

Could u send me some Screenshots or a short video of this feature?  Would
be interested

My jid is thorsten@emevth.no-ip.biz

Greetz

Thorsten Fröhlich
Am 30.06.2016 11:22 schrieb "markfoodyburton" <notifications@github.com>:

**Comment by markfoodyburton** [comment]
Thorsten,
I'd very much appreciate it if you could test my branch, and see if it works for you. I've tried on 2 different blue-tooth's - but "two swallows dont make a summer" :-)

Cheers
Mark.

**Comment by thundergreen** [comment]
Hi.  The problem for me is that I don't have the possibility to compile
conversations..  Would it somehow be possible to send me the apk?

Then testing will be sure

Greetz

Thorsten Fröhlich
Am 30.06.2016 23:08 schrieb "markfoodyburton" <notifications@github.com>:

**Comment by mglinux** [comment]
Hi guys!

Tried to compile it with sdk v25 and get the following error:
failed to find target with hash string 'android-24' in: /opt/android-sdk

Seems your patch uses conversations v1.12.4. Right now conversations is @1.13.3

I don't think openjdk caused the compiler error but don't know exactly.

**Comment by markfoodyburton** [comment]
I had to install all android-23 to get it to compile... your right - I branched before the recent work.

**Comment by mglinux** [comment]
Had to insert line "multiDexEnabled true" in build.gradle. Then it builds the apk just fine

**Comment by mglinux** [comment]
[Conversations-1.12.4-free-debug.zip](https://github.com/siacs/Conversations/files/343556/Conversations-1.12.4-free-debug.zip)

**Comment by markfoodyburton** [comment]
Thanks  @mglinux - let me know if you have feedback.
there is one issue I know about - if you use blue tooth mode, right now, when you connect to bluetooth the thing doesn't switch to handsfree mode straight away  - I know the problem, and I have a fix, but I haven't tested it yet :-)

**Comment by thundergreen** [comment]
Hi all. I have error in parsing when trying to install on Android 4.4.2

Thorsten Fröhlich
Am 01.07.2016 15:45 schrieb "markfoodyburton" <notifications@github.com>:

**Comment by markfoodyburton** [comment]
Whats the error? (I'm not sure I can help, but maybe @mglinux will be able to, but I guess he'll need more information?)

**Comment by mglinux** [comment]
Seems I have to sign the apk. What is the min required android version to run this? 4.4 or 5+ ?

**Comment by markfoodyburton** [comment]
I suspect I've accidentally made it only work on 5, but we could back port I think....

**Comment by iNPUTmice** [comment]
See my related comment in the PR. This is not something that is suited for mainline Conversations.

**Comment by markfoodyburton** [comment]
By the way, this is linked to pull request : #1905

**Comment by gjedeer** [comment]
Woow. This is awesome. I'm going to build and use this branch.

**Comment by markfoodyburton** [comment]
Let me know if you have any feedback

**Comment by stopANALytics** [comment]
I would like this if it was instead Push To Talk

for example

https://verizonwireless.com/biz/solutions-and-services/push-to-talk-plus/

https://verizonwireless.com/businessportals/support/faqs/DataServices/faq_push_to_talk.html

https://att.com/shop/wireless/features/enhanced-push-to-talk-sku6290267.html

No, I am not suggesting a mobile provider feature compatible option... even though Volte is xmpp+sip

**Comment by markfoodyburton** [comment]
My view is that the less interaction with the handset while (for instance) driving, the better. Hence the app, at the moment, tries to give you reasonable opportunities to reply to messages etc. However, it's true, it means you have to wait for somebody to say something before replying. IMHO - thats not a bad thing when you really are hands free :-). On the other hand, I can see that having a big "push to talk" button might be a nice option. Right now, if the app is closed, and you open it, you get the opportunity to talk (which is a sort of 'push to talk button' - the idea is that you are never 'in' the app (your driving, your watching the road, you have a GPS running perhaps).... hence tapping the app itself provides your sort of 'push to talk' functionality..... but I dont think it's something that should be encouraged?)

We could have a 'push to talk widget' - but that would amount to the same thing I suspect?

BTW, in non-bluetooth mode, I think if you press the little arrow/mic button, you get the push to talk functionality you want - it's just in bluetooth mode that it's more restrictive (if memory serves me right, but it's a while since I played with that :-) )

**Comment by gelft** [comment]
Push To Talk could be actuated by BT headset

**Comment by luke-jr** [comment]
More and more governments are banning texting while driving. Handsfree seems like an important feature, not a niche one.

**Comment by markfoodyburton** [comment]
One option is to leave this to a 'system wide' service. The issue is that it turns out that for 'chat' there are a bunch of things, and a way of interacting, that are fairly special to the 'chat', hence my belief is that this is better handled in Coversations itself.

This patch set has fallen off the train a long time ago. My personal interest in Conversations has diminished as we have migrated to Matrix (I'd be interested in https://github.com/siacs/Conversations/issues/3427 - then I would re-base these patches :-) )

**Comment by luke-jr** [comment]
Is there a decent system-wide service for this?

**Comment by markfoodyburton** [comment]
None that I've tried.
