### ISSUE TITLE
Lots of Partial Wakelocks?

### ISSUE THREAD

**Issue by gerroon** [siacs/Conversations#1869]
Hi

I was checking my battery stats and I see that it did 1288 partial wakelocks in 10 hours of battery use. I am not sure how much it contributes to the battery drain. It seems like Em_ADDR has the highens number of partial wakelocks on the system. Most apps are under 100. I am wondering if this can be fine tuned abit to be more battery friendly.

I am on 5.1.1 Samsung phone. And I am using the background service. This is the latest Fdroid build. And my server is the latest ejabberd server on Debian.

**Comment by iNPUTmice** [comment]
This is not a bug report but a general question. Please use our conference for those.

**Comment by gerroon** [comment]
Hi
:
How do I joın your conf? I tried adding it as a room, not avail, I tried getting an account from the conf server,did not succeeed.
