### ISSUE TITLE
Automatically fetching MAM after reconnect

### ISSUE THREAD

**Issue by amenk** [siacs/Conversations#1870]
#### General information

* **Device:** Google Nexus 4
* **Android Version:** eg Android 5.0 Stock
* **Server name:** self hosted ejabberd
* **Server software:** ejabberd 16.04
* **Installed server modules:** MAM, Stream Management, Carbons, MAM, CSI
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Log off on conversations
2. Chat via Gajim (OMEMO on or off)
3. Reconnect on conversations

#### Expected result

The messages written via Gajim should appear in the conversation.
MAM is working (in Gajim I see the message history in case I was offline in Gajim)

#### Questions

Is this supposed to work and a bug? Can I manually fetch the MAM messages?

**Comment by iNPUTmice** [comment]
> Is this supposed to work and a bug? 

yes this usually works

> Can I manually fetch the MAM messages?

if you clear the history in a conversation it will reload


Please provide adb logcat and check if your server time is in sync with your phone.

**Comment by amenk** [comment]
There is a bug:

* On the first try I used the "activate" button inside of the (disconnected) conversation -> does not work
* On a second try, I disconnected and reconnected using the accounts screen -> does work

What is not working are messages with OMEMO - this is crucial as well. Shall I open a second issue for that? (I believe server side it is working, because I can see the OMEMO messages in Gajim when I was offline in Gajim)

**Comment by amenk** [comment]
Phone time is around 25 seconds in the future - can this be the reason? No clue why it is like that, as it should sync. Do you still need the logcat or can you reproduce it already?

**Comment by iNPUTmice** [comment]
> Do you still need the logcat 

yes

**Comment by amenk** [comment]
Actually I was wrong with my assumption - it works also with the activate button in the chat window ...
Can't reproduce currently with logcat on.

Concerning OMEMO & MAM shall I make a new issue or is there one?

**Comment by iNPUTmice** [comment]
> Concerning OMEMO & MAM shall I make a new issue or is there one?

usually this is working as well. You should check with logcat and make sure your server is actually storing those in MAM. (MAM is not offline storage by the way and might have different rules)

**Comment by amenk** [comment]
It does work ... the problem seems to be in Gajim:

1.
* Contact is writing from conversations
* Gets stored in MAM (verified with DB dump in ejabberd)
* Is restored in conversations after reconnet

2.
* Contact is writing from conversations
* Does not get stored in MAM (verified with DB dump in ejabberd)
* And of course it's not restored

So I will direct my research to Gajim

**Comment by amenk** [comment]
https://github.com/omemo/gajim-omemo/issues/36
