### ISSUE TITLE
"Last seen" in contact details disappeared after update

### ISSUE THREAD

**Issue by Testertime** [siacs/Conversations#1874]
Hello! I have updated from version 1.9.4 to 1.12.4, and I have noticed that the "Last seen" info at the contact details has disappeared. I'm hoping that this is a bug and that it wasn't removed intentionally.

Steps to reproduce:

1. Open up Conversations ("Start conversation" screen)
2. Long press on a contact, choose "View contact details"
3. The "Last seen" info isn't available anymore like it used to.

Expected result:

The "Last seen" info should be visible.

Downgrading back to 1.9.4 brought this info back again, so I don't think that this has to do with a special device, server or anything like that. I haven't saved all older versions of Conversations, so I can't really say since which version it happens. So far I have seen that it is the same with version 1.12.3 as well. As a side note, the Android version is 4.4.4. If you can't reproduce this problem, please post here. Again, I'm hoping that this feature isn't intentionally removed... Thanks!

**Comment by alexara** [comment]
> I'm hoping that this is a bug and that it wasn't removed intentionally.

I am sorry to disappoint you but it has been removed intentionally as it never had worked reliable.
