### ISSUE TITLE
[Feature Request] media overview

### ISSUE THREAD

**Issue by ghost** [siacs/Conversations#1876]
Is it possible to include an menupoint like this one from e.g. Threema. or others?

![screenshot_20160525-155501](https://cloud.githubusercontent.com/assets/19575227/15547777/a271d53e-22a5-11e6-8bbe-ad93ceee2d29.png)

![screenshot_20160525-155616](https://cloud.githubusercontent.com/assets/19575227/15547792/a6d07130-22a5-11e6-9ae7-fd5d584c0f92.png)

Thanks

**Comment by Dionis0s** [comment]
push
i think it will be great

**Comment by Lykos153** [comment]
Duplicate of #1047

**Comment by steffanson** [comment]
WIP: https://github.com/siacs/Conversations/commit/7a0c53aa71c7f405d5bd9b838a90f69ead9a021a & https://github.com/siacs/Conversations/commit/06972ec95c77194d42b593b3ee25685ce6f3f278

**Comment by iNPUTmice** [comment]
Implemented in 2.3.0-beta
