### ISSUE TITLE
choose default encryption option

### ISSUE THREAD

**Issue by bastlwasti** [siacs/Conversations#1878]
hey,

as omemo is now default, it would be great to have some option in the preferences, to choose which encryption to use by default. I prefer to use only transport-encryption, to keep my MAM history safe :)

Greets

**Comment by iNPUTmice** [comment]
a preference for this would not control your contacts though.

**Comment by bastlwasti** [comment]
yes, you are right. If the other contact starts with me a conversation, it might be that he has a different preference than me.
