### ISSUE TITLE
[FR] Preview media inside App

### ISSUE THREAD

**Issue by de-live-gdev** [siacs/Conversations#1880]
#### General information

* **Device:** Google Nexus 5
* **Android Version:** CM13
* **Server name:** not relevant
* **Server software:** not relevant
* **Installed server modules:**not relevant
* **Conversations source:**F-Droid

#### Steps to reproduce

* Tap on media
  * Image
  * Video
  * Audio / audio recording

#### Expected result

Fullscreen image & video display, playback of audio file inside app (so no external app is needed).
There should be a way to still open the file with an other app installed on the phone. (e.g. settings option, or item on Tool/ActionBar)

#### Debug output

not relevant

**Comment by iNPUTmice** [comment]
Why? What is the benefit compared to using the exsiting viewers/players?

**Comment by de-live-gdev** [comment]
**Mostly usability and speed.**  
Feels quite bad when a tap *for example  on a picture* opens another app, makes transistion animations, and need to load longer. Showing a pic in fullscreen for example in fullscreen needs not that much code, and makes the app better useable.

**Just examples:**  

Show external, no default app selected
![device-2016-05-26-164351](https://cloud.githubusercontent.com/assets/6735650/15578703/d391f132-2361-11e6-8449-8f2226767760.gif)  

Show external, default app selected
![device-2016-05-26-164418](https://cloud.githubusercontent.com/assets/6735650/15578729/ef6255c8-2361-11e6-93a9-6c2bde627ec6.gif)

Show inside app:
![device-2016-05-26-164608](https://cloud.githubusercontent.com/assets/6735650/15578736/f658f77e-2361-11e6-89e7-95acc1361e52.gif)

..and just as sidenote, pretty much every messaging app I used till now on android shows their media inside the app. If it's some really ugly file type, sure thats no way to go, but common things like pics should be consumeable within Conversations.

**Comment by iNPUTmice** [comment]
Sorry I really don't see the benefit. Once you choose 'Always' when opening a picture its the same amounts of clicks. And you don't have to re implement zooming, shareing skipping play/pause or what ever.

**Comment by vanitasvitae** [comment]
I'd really like conversations implementing this really basic feature. I do have multiple apps that are capable of displaying images, but every one has a unique feature for another use case, so I cannot set one as default. In conversations I always only just want to see the image and do stuff like zooming. The lack of an in-app image viewer is really a downside of the app.

**Comment by tristan-k** [comment]
I second that! In terms of usability playing audio or video in app would be appreciated. It also streamlines the user experience. Have a look at the recent Signal update. Following the unix philosophy to make each program do one thing well it would be bad choice. Maybe a option to enable it in the advanced settings or deliever it through the [voice recorder plugin](https://github.com/siacs/VoiceRecorder)?
