### ISSUE TITLE
Treat geo: URLs like all other links

### ISSUE THREAD

**Issue by gjedeer** [siacs/Conversations#1881]
Sending a message like:

`geo:13.4125,103.8667`

displays a "Show Location" button, which is nice.

Sending a message like:

`Click here to see my location: geo:13.4125,103.8667`

does not render the geo:... as link (or as a button).

Such messages are generated by 3rd party apps having "share location" support, including the one I'm maintaining right now and the Share option in OSMAnd.

It would be great if it was a clickable link just like http:// etc.

**Comment by iNPUTmice** [comment]
Out of curiosity what app are you maintaining right now? When I originally implemented the share location feature I did not find a lot of app that were actually able to share the location as a geo uri.

**Comment by gjedeer** [comment]
Hi, it's https://github.com/gjedeer/mylocation - i did similar research and found this crappy, abandoned app, but it filled the gap.

Ideally it would just share the geo: link and additionally google maps or osm as a browser-compatible fallback, but the very spotty support for geo urls made me add a ridiculous number of alternative map links, to make the links open a map app on as many devices as possible.

**Comment by iNPUTmice** [comment]
While I have no general problem merging your PR I'm wondering if the 'Here is my location geo:xxx' isn't just useless information. Wouldn't sharing just the geo uri be enough?

**Comment by gjedeer** [comment]
If you're asking about general use case, osmand does this so maybe it would be nice if the most popular free messaging app worked with the most popular free gps app.

If you're asking about the app i'm maintaining, it's not limited to jabber. I might want to quickly share my location via email too, and sending a bunch of links without explanation would not work eg.  for my Dad.

**Comment by iNPUTmice** [comment]
closed by your PR

**Comment by gjedeer** [comment]
Thanks!

On May 28, 2016 5:08:58 PM CEST, Daniel Gultsch <notifications@github.com> wrote:
>closed by your PR
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/siacs/Conversations/issues/1881#issuecomment-222313251

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
