### ISSUE TITLE
Conversations hangs when receiving very long messages

### ISSUE THREAD

**Issue by cvoinf** [siacs/Conversations#1883]
#### General information

* **Device:** Acer Z130, 512MB Memory
* **Android Version:** Android 4.2.2
* **Server name:**  jabber.de
* **Conversations source:**  F-Droid

#### Steps to reproduce
Receive a very long message, written with gajim, omemo-encrypted.

Somebody sent me by accident a very long message (several hundred lines). Now conversations hangs and does not respond anymore. Even my phone does not react for a while. After some seconds a message appears: "Conversations does not react. Do you want to close this app". I tried to click "Wait" several times, I even could see the end of the message once, but the message seems to be reanalysed again and again so it is not possible to use Conversations anymore. The only solution is to click "OK" thus quit Conversations. When restarting it, Conversations starts to analyse the message again so it is unusable.

The only workaround is to try to swipe the contact away right at the beginning, when I start Conversations. If I am fast enough, the contact is cancelled and I can use Conversations again. Only when I try to add the contact again or if the person of that account sends me a new message, Conversations hangs again. So I am not able to chat with my contact anymore, since the message is saved at server-side....

If others are also affected by this issue, this is a serious bug (a kind of DoS.attack) which should be closed as soon as possible. I would like to emphasise that I was using omemo encryption, since it might be necessary to reproduce this issue. The small amount of memory on my device could also promote the problem.

Regards,

ThS

**Comment by iNPUTmice** [comment]
Are you on 1.12.4?

**Comment by cvoinf** [comment]
Yes, 1.12.4 from f-droid.

**Comment by iNPUTmice** [comment]
Apparently pros pre render text in the background before displaying it…  http://instagram-engineering.tumblr.com/post/114508858967/improving-comment-rendering-on-android

422fd1847fa18553398a2747c72f835d9227f172 limits the impact by capping the text at 5k chars.

**Comment by cvoinf** [comment]
Wau, you are FAST!!! Thank you!
