### ISSUE TITLE
[Feature Request] irc transport

### ISSUE THREAD

**Issue by volga629** [siacs/Conversations#1884]
Hello Everyone,
Will be nice to have irc transport support. That will allow join irc channels from same client. 
Ejabberd mod_irc.

**Comment by iNPUTmice** [comment]
This is something that is handled on the server side.

**Comment by volga629** [comment]
How to join from client ? My is configured, but it just open muc room.

**Comment by iNPUTmice** [comment]
Depends on your setup. You best consult the documentation of your server.
But it's usually a muc with an address of
channel%xxirc.server@irc.yourserver.tld or something

**Comment by volga629** [comment]
thanks
