### ISSUE TITLE
Cannot choose the new OMEMO

### ISSUE THREAD

**Issue by kriegerkl** [siacs/Conversations#1885]
#### General information

* Version: 1.12.3
* Device: Sony Experia Z3 Mini
* Android Version: Android 5.1.1
* Server name: self hosted
* Server software: ejabberd
* Installed server modules: PEP
* Conversations source: F-Droid

I cannot choose the new OMEMO (writen in light gray) encryption on Conversations 1.12.3, OTR and OpenPGP is available (writen in black). 
My ejabberd-server has pep support. I have checked this in account details if I select server info from the menu:
XEP-0163: yes
XEP-0191: yes
XEP-0198: no
XEP-0237: no
XEP-0280: no
XEP-0313: no
XEP-0352: no
XEP-0363: no

**Comment by iNPUTmice** [comment]
What ejabberd version are you using? If it is anything older that 15.something it won't work.

**Comment by kriegerkl** [comment]
The version of ejabberd is 2.1.13-1.
That means, it is not working?

**Comment by andersruneson** [comment]
That's way to old. You should upgrade.
