### ISSUE TITLE
Please reconsider XMPP Resource Priority support

### ISSUE THREAD

**Issue by rgpublic** [siacs/Conversations#1887]
I've read the FAQ and I see why message carbon etc. might be useful in many other cases. Nevertheless, I think they don't solve all use cases. I simply don't want to receive any messages on my phone when I'm at my office desktop and vice versa. How can I configure this easily without priorities? I think this is still a valid feature for those who like it.

**Comment by iNPUTmice** [comment]
> I simply don't want to receive any messages on my phone when I'm at my office desktop and vice versa.

If you don't want to receive messages you can go offline.

**Comment by rgpublic** [comment]
Hm. But then I'd lose the feature that coworkers can see whether I'm at 
the office that day but only away (say for a lunch break) or not there 
at all (computer switched off). I think what I want (and what works 
flawlessly with other mobile XMPP clients) isnt that exotic, really:

1) I've got a desktop client (Pidgin). When I'm at the office, my 
computer is switched on. I'm online. There's an auto-away feature in 
Pidgin like in most desktop clients: When I'm not moving the mouse or 
typing on the keyboard, my status changes to "Auto Away" after 2 
minutes. My coworkers see I'm at my desk today but perhaps out for lunch 
or sth.

2) When I'm not at my desk, I've got my mobile phone with me. I want 
messages to arrive there. Before I get to work. After work. And on the 
lunch-break. But I don't want to clear out notifications all day of 
messages I've already read when I'm at my desk. And I don't want to 
switch the Jabber status on the phone to online/offline manually 
everytime I come and leave. The phone however, can't detect whether I'm 
moving the mouse or keyboard on my desktop PC, obviously.

This is all extremely simple to configure with priorities. And honestly 
I don't think that the concept of assigning a number to say which client 
matters the most is so horribly unfriendly for users or to complicated 
to understand. It's great that Conversations supports all the shiny new 
stuff as well (Carbon etc). Kudos for that and for delivering an 
otherweise superb app. But implementing an advanced setting section with 
the ability to enter a simple number couldnt hurt that much, could it?



Am 31.05.2016 um 21:37 schrieb Daniel Gultsch:

**Comment by SamWhited** [comment]
[![There are probably children out there holding down spacebar to stay warm in the winter! YOUR UPDATE MURDERS CHILDREN.](https://imgs.xkcd.com/comics/workflow.png)](https://xkcd.com/1172/)

And more importantly, trying to support every workflow is a recipe for disaster.

**Comment by d9h02f** [comment]
If you can have sane defaults, options are a bad thing.

I'm sure at some point there will be an XEP which makes sure once something is read on any device, it no longer shows up as unread on other devices, and then priorities will be completely obsolete.

**Comment by iNPUTmice** [comment]
> I'm sure at some point there will be an XEP which makes sure once something is read on any device, it no longer shows up as unread on other devices, and then priorities will be completely obsolete.

that's called XEP-0333: Chat Markers and XEP-0085: Chat State Notifications

**Comment by rgpublic** [comment]
AFAICT, Chat Markers mean that you see if your chat partner has read 
your message. And Chat State Notifications means you can see if your 
chat partner has the chat actively open. This is known e.g from 
WhatsApp. Both great features, indeed. Only problem is they can't undo a 
notification. Someone sends me a message. Without any priorities, It 
appears at the same time on my desktop PC and on my mobile phone. OK, 
great. Now I've got an icon and status message in the Android toolbar of 
my phone which I need to wipe away later and my phone made a beep sound 
because of the incoming message. All for no apparent reason, because I'm 
at my desk and saw the message there anyway. If you send the message to 
all the devices at the same time without any concept of priorities then 
all devices will inform you in one way or the other. It doesnt matter 
when you notice later on that the message is read on one of the devices. 
Because you can't travel back in time you cannot unhear the notification 
beep you've heard, for example.


Am 01.06.2016 um 00:15 schrieb Daniel Gultsch:

**Comment by iNPUTmice** [comment]
Both the read chat marker as well as the active and typing chat state sent
out by your desktop client will be carbon copied to your mobile phone and
used to mark the chat as read and dismiss the notification. (and vice
versa)

**Comment by d9h02f** [comment]
Oh, great, I didn't know that.

**Comment by iNPUTmice** [comment]
I'm closing here.

For further references here is what you do if you want to use Conversations with multiple devices and not get notifications if you are actively using your desktop client.

* get a server that supports Message Carbons
* get a desktop client that emits chat states. (A lot of them do)
* set the Grace Period to *Medium* or *Long*
* Sit back. Trust that Conversations will do the right thing. Stop worrying about presences and priorities once and for all.

**Comment by luke-jr** [comment]
What about for people who don't want/like message carbons?

**Comment by iNPUTmice** [comment]
Is there a compelling reason to disable carbons besides not wanting to
receive notifications which Conversations already takes care of by
detecting if you are currently using another client?

**Comment by luke-jr** [comment]
Not having ever used a client with Carbon support before, I suspect it will break my ability to send messages directly to specific clients/resources and not others.

**Comment by jkufner** [comment]
@luke-jr Don't suspect, just try it. It works fine. Even better if you have MAM support on the server.
