### ISSUE TITLE
Last time seen is not longer shown

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#1888]
#### General information

* **Version:** 1.12.8
* **Device:** BQ Aquaris M5
* **Android Version:** Android 6.0
* **Server name:** suchat.org, mijabber.es & quitter.es
* **Server software:** sorry, no idea
* **Installed server modules:** Stream Managment, CSI and MAM are installed in some of them (suchat.org has every XEP shown on "server information")
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Open a conversation
2. Check the contact's details

#### Expected result

Last seen (eg. 2 minutes ago). I found nothing, it just doesn't appear.

**Comment by d9h02f** [comment]
https://github.com/siacs/Conversations/issues/1874

**Comment by moshpirit** [comment]
I'm sorry, I didn't see that one, thanks for the comment :)
