### ISSUE TITLE
[Issue] offline MUC participants doesn't show because the MUC need to be refresh

### ISSUE THREAD

**Issue by DoM1niC** [siacs/Conversations#1890]
#### General information

* **Version:** latest HEAD
* **Device:** LG G4
* **Android Version:** Android 6.01 Cyanogenmod
* **Server name:** flowx.im
* **Server software:** prosody 0.10
* **Installed server modules:** Carbon,Smacks,Smacks Offline, and so ...
* **Conversations source:** self build (latest HEAD)

#### Problem
Offline MUC participants doesn't show because the MUC need to be refresh.
#### Steps to reproduce

App restart and the offline Users in MUC will visible like solution.

**Comment by iNPUTmice** [comment]
There is an open bug report/feature request for this on the prosody issue
tracker.

**Comment by DoM1niC** [comment]
Ahhh THX but I thought there is an Client Issue because, App restart fixed the Problem... mhh... ok good 2 know :(
