### ISSUE TITLE
[Feature request] Conference Avatar

### ISSUE THREAD

**Issue by mat321** [siacs/Conversations#1894]
It would be very nice to have Avatars for Conferences instead of the combination of Member Avatars.
Like Signal has its Group-Avatars.
Would that be possible?

**Comment by hareshkh** [comment]
@iNPUTmice, is [this](http://stackoverflow.com/questions/35308977/xmpp-multi-user-chat-setting-avatar-image-for-the-group-chat) a possible solution for this?

**Comment by Matthias84** [comment]
@hareshkh This isn't any formal XEP, is it? https://xmpp.org/extensions/

**Comment by Matthias84** [comment]
@licaon-kter  Can you plz. share an screenshot and refer the corresponding XEP? I didn't found any spec :thinking:

**Comment by Mikaela** [comment]
I think this could be closed already.

**Comment by iNPUTmice** [comment]
Conference avatars are now supported.
