### ISSUE TITLE
Permission problems with Android M

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1896]
#### General information

* **Version:** 1.12.9
* **Device:** Samsung SGS 3
* **Android Version:** Android 6.0 crDroid
* **Server name:** self hosted
* **Server software:** prosody trunk
* **Installed server modules:** all for work with Conversations
* **Conversations source:** PlayStore

##### Export logs
1. make a fresh install of Conversations and log in
2. go into the settings and start exporting logs
3. Android asks to grant storage permissions
4. touch grant, but no logs are written until app is restarted (app manager, kill app and start again)

##### Receive file
1. make a fresh install of Conversations and log in
2. receive a file from a contact
3. Android asks to grant storage permissions
4. touch grant, but file could not be downloaded (download failed: file not found) until app is restarted (app manager, kill app and start again)

##### Send file
1. make a fresh install of Conversations and log in
2. choose a file to send to a contact
3. Android asks to grant storage permissions
4. touch grant, but file could not be sent (Conversations hangs, black screen, Android asks to wait or kill) until app is restarted (app manager, kill app and start again)

#### Expected result

After granting permissions Conversations should do the task without a manual restart. If a restart is necessary, Conversations should do it automatically (after asking the user)

#### Debug output

````
no logs available yet, but can be provided later if necessary.
````

**Comment by iNPUTmice** [comment]
Kinda looks like a ROM issue to me. Does granting contacts permission
reload the contact list with the contact pictures?

**Comment by kriztan** [comment]
It seems to be a problem with the ROM, closing it.
