### ISSUE TITLE
Nickname capitalization cannot be changed

### ISSUE THREAD

**Issue by Mikaela** [siacs/Conversations#1897]
I had three clients in one conference from which two were Conversations and one was Gajim. Gajim said I was at the conference two times, with Conversations (mikaela) and BitlBee (Mikaela).

I tried to rename Conversations from `mikaela` to `Mikaela`, but it silently ignored the casing correction and did nothing. I was able to fix it by renaming to `Mikaelaa` and then to `Mikaela`.

I removed the difficult issue template as multiple people on conversations@conference.siacs.eu managed to reproduce.

**Comment by iNPUTmice** [comment]
Works for me. I highly suspect this to be a server thing.
