### ISSUE TITLE
roaster still shows contacts as online even if network connection is interrupted

### ISSUE THREAD

**Issue by mdkuser** [siacs/Conversations#1898]
issue: The roaster view does not get updated if the network connection is lost (or cut off because of no data roaming allowed) it still shows contacts as online (and never gets updated/refreshed for a long period)...

expected: The roaster view should update and show contacts as offline if network connection is lost

**Comment by mdkuser** [comment]
Yes, but that's not supposed for an XMPP client. The standard behaviour of almost any xmpp client out there is to show contacts offline if you are not connected to the Jabber server or connection to the server is lost.
It should display the actual connection state, not the "who was online before the connection got lost". So if actual connection state is disconnected, contact status should be shown as offline because the client is currently offline!
I wouldn't mind if the roaster is updating is delayed a bit, but if it keeps the contact status remaining online for hours after the client actually lost its connection to the server, this is IMHO not what it should be.

**Comment by mdkuser** [comment]
Also, I figured out status update changes of your contacts got only reflected immediately in the roaster if you send an own status update (e.g. by sending "online if phone display is switched on and "away" if phone display is switched off) or if you connect with another xmpp client on the same device.
There are times where the contact status is offline or extended away which is shown with the color of the sending button in active chat, while in the roster view the status remains unchanged...

**Comment by iNPUTmice** [comment]
On a mobile connection you might loose connection rather frequently. Always showing contacts as offline just because we are for a few seconds will cause the status to flicker.

Thats by the way also the reason we don't show presence by default at all. Because in a mobile context it doesn't have the same meaning it used to have.
