### ISSUE TITLE
OMEMO option for some contacts greyed out in Conferences

### ISSUE THREAD

**Issue by mdkuser** [siacs/Conversations#1899]
Only some contacts that use all same Conversation version (1.12.9) doesn't have OMEMO available in private conferences (greyed out in encryption options), however exept for conferences OMEMO works for those contacts and they can choose it from encryption options (is not greyed out) for normal IM chats.

**Comment by iNPUTmice** [comment]
Did you read the FAQ? Is your conference non-anonymous?

**Comment by mdkuser** [comment]
Yes, I read the FAQ and my conference is non anonymous and privte (members only). From 3 members only one is unable to use OMEMO in this conference all other 2 (inc. the Moderator) can use OMEMO in this conference. However it's confirmed that all those contacts can use OMEMO in normal chats (non conference) with each other.
Seems there is something wrong with the one account.


BTW: Is it normal, that members can only invite one other member to the confernece and then the "invite button" is not visible anymore? It seems that in latest conversation only the moderator (conference owner) can invite more that one member...

**Comment by bastoon06** [comment]
mdkuser, I experienced this situation maybe it will help you.
Concersation failed in listing all the member allowed in a MUC. I had some old JID not supporting OMEMO and as soon as only one disable the ability to OMEMO encipher (with Conversations) I could not encipher the MUC anymore.
So use another client and edit the member list, remove bad JID.

**Comment by iNPUTmice** [comment]
Or update your server and Conversations will show the members list.

**Comment by bastoon06** [comment]
This issue also raise the following question : should Conversations disable the ability to send OMEMO messaging because one people is not supporting OMEMO?

With the current situation any attacker can downgrade the current security level of a MUC, which is moreover not anonymous because of OMEMO requirements.

I would opt to be able to force OMEMO from client side along with https://github.com/siacs/Conversations/issues/1901

**Comment by mdkuser** [comment]
Solved. Indeed there was a member that is cabable of OMEMO but has no keys assigned yet...
Removing this member solves the issue...
To me OMEMO should work als long as all online members sopport it and not fail because one member who is not online anyway has sisabled omemo...
