### ISSUE TITLE
Feature request: Possibility to delete an avatar

### ISSUE THREAD

**Issue by ghost** [siacs/Conversations#1900]
#### General information
- **Version:** eg 1.12.9
- **Conversations source:** PlayStore
#### Issue

If am no longer satisfied with my avatar, I need to choose a different one on my cellphone.
In case I don't have another suitable image, I would like to simply annul my avatar.
This is currently not possible.

--Alex

**Comment by blevant** [comment]
+1

**Comment by x-jokay** [comment]
+1

**Comment by iNPUTmice** [comment]
duplicate of #2235
