### ISSUE TITLE
a grammar mistake in the Russian locale

### ISSUE THREAD

**Issue by slalik** [siacs/Conversations#1902]
Hello,

in Russian locale the phrase "Send unencrypted message"
is translated as "Отправить не зашифрованное сообщение".

There must not be a space between "не" and "зашифрованное", the same like in English.  So the correct phrase is:
"Отправить незашифрованное сообщение"

This is very unpleasant bug, because this statement is before eyes all the time!

**Comment by licaon-kter** [comment]
https://www.transifex.com/siacs/conversations/dashboard/ -> Login with Github -> Ask to be a member of the team -> Fix it your self! 

/close as "read the readme"
