### ISSUE TITLE
conversations does not connect to _xmpps-client._tcp when when 5222 is blocked

### ISSUE THREAD

**Issue by pravi** [siacs/Conversations#1903]
#### General information

* **Version:** eg 1.12.9
* **Device:** Yu Yuphoria
* **Android Version:** Cyanogenmod
* **Server name:** poddery.com
* **Server software:** prosody 0.9.7 (debian package, from jessie/stable)
* **Installed server modules:** all XEPs conversations looks for
* **Conversations source:**  F-Droid, 

#### Steps to reproduce

1. … Block port 5222 on firewall
2. … connect to server

#### Expected result

What is the expected output? 

It should connect to 443 when 5222 fails as _xmpps-client._tcp.poddery.com. is set to 443 poddery.com. in SRV records

```
$ dig srv _xmpps-client._tcp.poddery.com

; <<>> DiG 9.9.5-12.1-Debian <<>> srv _xmpps-client._tcp.poddery.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41858
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;_xmpps-client._tcp.poddery.com.	IN	SRV

;; ANSWER SECTION:
_xmpps-client._tcp.poddery.com.	10800 IN SRV	0 5 443 poddery.com.

;; Query time: 413 msec
;; SERVER: 178.17.170.67#53(178.17.170.67)
;; WHEN: Thu Jun 09 22:12:47 IST 2016
;; MSG SIZE  rcvd: 79
```

What do you see instead?

conversations gives, 'server not found' error. I just setup XEP 0368 on poddery.com and may be I missed some settings. I can connect to the server using pidgin if I manually specify port 443.

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by licaon-kter** [comment]
Manually specifying 443 works?

**Comment by pravi** [comment]
@licaon-kter yes, I can connect from pidgin if I set port 443 in advanced.

**Comment by licaon-kter** [comment]
Yes, I've read that, I meant, in Conversations when you specify the port in advanced options?

**Comment by pravi** [comment]
I got tip from conversations room to enable legacy_ssl and forward 443 to 5223. Trying that.

**Comment by pravi** [comment]
This was solved after updating sslh to latest version that support ALPN. I can now connect to 5222, 5223 and 443 ports from conversations when port is manually specified and no ports are blocked.

But when I block port 5222, conversations does not fall back to using 443. I can access https pages on the same server via browser so firewall is not blocking 443. Even when I manually specify 5223 or 443 it does not work (I guess that is expected as these are tls ports and normal xmpp won't work).

Now _xmpp-client._tcp.poddery.com. and _xmpps-client._tcp.poddery.com. is set in SRV records.

**Comment by pravi** [comment]
```
openssl s_client -connect poddery.com:443 -alpn xmpp-client -servername poddery.com
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = poddery.com
verify return:1
---
Certificate chain
 0 s:/CN=poddery.com
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFQzCCBCugAwIBAgISAwIrIVL/VMmAkwQkfoCjAInMMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xNjA2MDkwODMxMDBaFw0x
NjA5MDcwODMxMDBaMBYxFDASBgNVBAMTC3BvZGRlcnkuY29tMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4Sw+DJejS3tXLX6V3jXeNQBfbVma0ZW+UmgE
zq2zlr/TiD8PDC0JIdfugCUyMtJ2O7tobxrRNUc/6vEpfNo3UPBQDP6NQ9RI9JAB
n21gzK3G6QdE9/6ySJfE/4oAYe69YdIk10R+pDeGfPwMRebeDYBU3pn17JnUWKkL
1m6dK+kF7ReP8qqzILCywLbyCFz8vZ6vuuml14HhDjwZ6KrY7QxmOvT+mLo5Deiq
7WU2nj3IUdsqX2SxsYVqe+5KlsAlvIbnayYaQklcpU+8VaToEq5YxwTKddSQ8YmB
cMn1/AUikggz/MzWnttrSp7oPTtsi0GWM7GLuzjXcr3WZIkbuQIDAQABo4ICVTCC
AlEwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
AjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRp/A/KE0kSxXegwjHNHafB7TZieDAf
BgNVHSMEGDAWgBSoSmpjBH3duubRObemRWXv86jsoTBwBggrBgEFBQcBAQRkMGIw
LwYIKwYBBQUHMAGGI2h0dHA6Ly9vY3NwLmludC14My5sZXRzZW5jcnlwdC5vcmcv
MC8GCCsGAQUFBzAChiNodHRwOi8vY2VydC5pbnQteDMubGV0c2VuY3J5cHQub3Jn
LzBfBgNVHREEWDBWghJncm91cHMucG9kZGVyeS5jb22CC3BvZGRlcnkuY29tghB0
ZXN0LnBvZGRlcnkuY29tgg93d3cucG9kZGVyeS5jb22CEHhtcHAucG9kZGVyeS5j
b20wgf4GA1UdIASB9jCB8zAIBgZngQwBAgEwgeYGCysGAQQBgt8TAQEBMIHWMCYG
CCsGAQUFBwIBFhpodHRwOi8vY3BzLmxldHNlbmNyeXB0Lm9yZzCBqwYIKwYBBQUH
AgIwgZ4MgZtUaGlzIENlcnRpZmljYXRlIG1heSBvbmx5IGJlIHJlbGllZCB1cG9u
IGJ5IFJlbHlpbmcgUGFydGllcyBhbmQgb25seSBpbiBhY2NvcmRhbmNlIHdpdGgg
dGhlIENlcnRpZmljYXRlIFBvbGljeSBmb3VuZCBhdCBodHRwczovL2xldHNlbmNy
eXB0Lm9yZy9yZXBvc2l0b3J5LzANBgkqhkiG9w0BAQsFAAOCAQEAcFVPKHVygEL3
R8kxaznr4vdz8EWaV55JIYFUZDax4UYik9elhCNJUMtKVytVsL1a4CbP0tvbrJtx
lAm/mwvF8KSZxjBO6+qZxvpRQnbiV3z6B9IzJayzChWygNsVjDaVUOqp7Z6+XaY/
7T0gWBhrLRvbPvbnK6O2oRD/iN1p1j9Jp5sEI3zLdVjcJQkTeo87a0E4c+byTno2
84tW+CbxLoxM0WAIUsuyStYlyqWwijrOqzb+grEeqYES3LZxeuznYLzJ3CB0rZbg
xUXKHjhdIvX7jtjst2wccsQ1JQthweyXjBj9/BkKJ5b5B6NZgOzjRXI2w5IqMMEJ
bbsARp5n2w==
-----END CERTIFICATE-----
subject=/CN=poddery.com
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 3219 bytes and written 479 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 6E37E22EF5A8EA94AAE025C991EFDE06F21E20A8622ED7B24E0CC464C40CA7A8
    Session-ID-ctx: 
    Master-Key: FBCCE708DF9C7007B38BD2110D14BB13875A3D3D320F0DFF3960ADFD8279812239852FE2723736D5708649C905427847
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 4d 54 37 c7 e1 2a 15 8a-1b af fa ce a4 88 15 e6   MT7..*..........
    0010 - d2 3f 91 1c 4e bd 72 45-91 c6 6c 01 ed fb cb 74   .?..N.rE..l....t
    0020 - be 24 22 10 32 7d ec ad-d4 97 68 35 ac f3 ad 35   .$".2}....h5...5
    0030 - c8 f5 5e 2c bd bd 68 fc-79 2f b6 24 a2 15 ce 46   ..^,..h.y/.$...F
    0040 - 5c ed 40 31 96 59 47 90-e4 43 51 d5 be 62 82 7b   \.@1.YG..CQ..b.{
    0050 - 6f 0e 43 8f fa 5a de 0e-a5 4c 79 25 66 a2 ae 43   o.C..Z...Ly%f..C
    0060 - 92 5a 30 56 ff cd 64 ce-06 06 1e 01 db 16 38 46   .Z0V..d.......8F
    0070 - 57 d0 6f f7 d8 4a e9 41-13 3c b4 67 aa 02 4e 99   W.o..J.A.<.g..N.
    0080 - 7f 4d 2f 3a 3f 33 d2 67-3a 1f 03 83 7c 3e fd 6d   .M/:?3.g:...|>.m
    0090 - 5e ba 17 85 09 b2 45 c2-45 f2 29 78 49 7f 96 9f   ^.....E.E.)xI...
    00a0 - fc e1 21 cd dd 0c 8c 02-7d e8 75 5d 55 ed 90 69   ..!.....}.u]U..i
    00b0 - 15 b4 c7 3b 0c 56 94 54-1d 56 c6 96 7e ca dd 8f   ...;.V.T.V..~...

    Start Time: 1465541108
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by pravi** [comment]
Server is setup following https://wiki.debian.org/Diaspora/XMPP (XMPP over HTTPS is relevant section)

**Comment by pravi** [comment]
After changing legacy_ssl_ports = 5223 to ssl_ports = 5223 in prosody, it is working now.

**Comment by pravi** [comment]
Ah! It was just a change in dhcp ip that opened 5222 port again for my phone. The issue is still there.

**Comment by pravi** [comment]
It seems an sslh configuration issue, openssl manual connect it going to nginx and not prosody.

my sslh config (protocol section),

```
protocols: 
(
   { name: "xmpp"; host: "localhost"; port: "5223"; alpn_protocols: [ "xmpp-client" ]; sni_hostnames: [ "pod.pxq.in" ]; log_level: 0;}, 
   { name: "tls"; host: "localhost"; port: "443";} 
);
```

**Comment by pravi** [comment]
Looks like I have to update my openssl to at least 1.0.2 for alpn support.

**Comment by pravi** [comment]
@moparisthebest confirmed 443/tls goes to prosody (via openssl commandline). I have updated SRV records and will try again tomorrow if different priorities will change anything. I think conversations should try both options with equal priority if one of them fails.

**Comment by moparisthebest** [comment]
Just for info, this is what adb logcat looks like when telling you what server/port you are connected to:

`D conversations: jid@domain.com: using values from dns domain.com[192.168.1.197]:5222 tls: false`
tls: false means not XEP-0368, not straight TLS, but regular style XMPP

But something like:
`D conversations: jid@domain.com: using values from dns domain.com[192.168.1.197]:443 tls: true`
Means it's using XEP-0368-style direct TLS.

**Comment by pravi** [comment]
conversations( 2209): testuser@poddery.com sending csi//intive
conversations( 2209): AxolotlService (testuser@poddery.com
 Received PEP device list update from testuser@poddery.com
processing...

**Comment by pravi** [comment]
Yes, I can now confirm from logcat, it is using 443 tls: true.
