### ISSUE TITLE
Grace period - how long is "long"?

### ISSUE THREAD

**Issue by jkufner** [siacs/Conversations#1907]
In settings menu, the grace period option (not sure about english name, it is "Četnost upozornění" in czech) has three options: Short, Medium and Long. But how long is "long"? Isn't "short" too short? From user's point of view there is simply not enough data to make the decision.

It would be better if the length of the period was specified more accurately (number of seconds/minutes), so the user knows what to expect.

(Version 1.12.9 from F-Droid)

**Comment by iNPUTmice** [comment]
This is deliberately not specified in minutes as this is some kind of try and error thing anyway. Just toy around with it a little bit to find your personal preference.
