### ISSUE TITLE
Feature: disable "Battery optimizations enabled" when it's unnecessary

### ISSUE THREAD

**Issue by kousu** [siacs/Conversations#1910]
#### General information

* **Version:** eg 1.12.9
* **Device:** Moto E
* **Android Version:** Android 6.0 Cyanogenmod
* **Server name:** self hosted
* **Server software:** 0.9.7-2+deb8u3
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Add any account on a fresh install
2. Go to account details
3. See "Battery optimizations enabled" with the warning about losing messages

This is strange to me because you [advertise battery friendly operation](https://conversations.im/#optimizations claims). I recommended Conversations to a friend but lost him because it ate too much of his battery, and I suspect it was because of this; I ran into it myself after an update to Android 6: over the next few days I watched as Conversations would eat 20% of my total battery. I don't remember it doing that before, which I assume is because Android 4 would not allow Conversations to ask for that.

My understanding is that "battery optimizations" means "killing inactive connections" or maybe "killing connections for apps that haven't been opened in a while", and you want to disable this to make sure you don't lose your TCP connection[*]. But if XEP 198 solves that, disable them? I tried re-enabling optimizations and found that Conversations still got messages from all the MUCs I'm in and went back to using only like 4% of my power. Today I am enabling XEP 198 for just in case, and it occurred to me that this could be better.

Instead of a scary "Android might lead to message loss" message, I would like to see this UI reworked softer. It should only show this message for accounts that don't have XEP 198 and/or 352 available, and for those it should explain "Your server does not have the optimizations enabled, so to prevent message loss consider disabling Android's battery optimizations."

[*] My understanding is lost messages happen in XMPP when a device rapidly switches networks: the server hasn't received `<presence type='unavailable'>` or noticed a dropped TCP connection, so it sends stanzas down the pipe and forgets them, before knowing if they got there or not.  I guess the kernel TCP buffers will try to resend the missing pieces until the kernel gives up on the TCP connection entirely and if you reconnect from the same address shortly enough they will arrive, but if you reconnect at a new IP address, as happens in switching cellular to wifi they are lost.

**Comment by iNPUTmice** [comment]
You suspect wrong. Android 6 is doing optimizations that it wasn't doing
before. Read up on 'doze' if you are interested. Your power consumption on
Android 6 - with those optimizations disabled - won't be higher than before.
This warning sign unfortunately remains necessary.
