### ISSUE TITLE
Feature request: per-account bandwidth

### ISSUE THREAD

**Issue by kousu** [siacs/Conversations#1911]
Android lets you see how much bandwidth an app has taken over time. I see conversations regularly eating 50megs a day and I am not sure where that is going because I have several accounts active. I suspect it's the Slack that's eating the most, because it doesn't support CSI or SMACKS, but I have no way to tell.

A per-account bandwidth meter inside Conversations would let us figure out what servers are eating our bandwidth. This feels like feature creep to me, but I don't know how else I would figure this out.

**Comment by iNPUTmice** [comment]
You can monitor Conversations with adb logcat and you should be able to see
fairly quickly which account produces the most debug output. A lot of
reconnects means a lot of traffic.
