### ISSUE TITLE
[Feature request] color scheme

### ISSUE THREAD

**Issue by thundergreen** [siacs/Conversations#1912]
#### General information

* **Version:** 1.13. 1
* **Device:** cubot x11
* **Android Version:**  Android 4.4.2
* **Server name:** conversations.im
* **Server software:** ejabberd 16.04 
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** PlayStore Beta Channel,

#### Steps to reproduce

1. Mention someone in muc by short press on muc member.  
2. Send private message in muc via long press in muc

#### Expected result

I'd like for a better overview having all messages related to my username in muc being in another background color. 
I was thinking about having a light cream background with black letters. 
It's hard sometimes to find private messages in muc related to me and as conversations has no new tab for private messages it would be visible which messages have been sent to me. 

Other feature request but already opened issue would be message search.  But in the meanwhile I guess a different color scheme would help out a lot

**Comment by mglinux** [comment]
Agree! Highlight like gajim does

**Comment by thundergreen** [comment]
Hi all.is this feature kicked out of the list or ciuld we get just a short feeeback from devs if they at least takr this into account?

lg thunder

**Comment by iNPUTmice** [comment]
private muc messages is not something we are planning to support in the long run.
