### ISSUE TITLE
[Feature request] Group users in the MUC conference user list 

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#1913]
#### General information

* **Version:** 1.13.0
* **Exemplary MUC:** conference.siacs.eu

#### Step to reproduce

1. About 100 users have the tag "no membership" under their name in the offical `conference.siacs.eu` MUC
2. Few have tags like "owner" or "admin"
3. Having 100 single "no membership" tags doesn't help with the overview.
4. While scrolling through the list you will get accustom to "no membership" which will lead to oversee the few members

#### Suggestion
Add an option to sort the MUC list:
* 1. by membership:
    * Sort users hierarchically: Admin on the top, then members, finally the rest
    * Within a group, sort them alphabetically
* 2. by alphabet
     * as it is right now

-- Alex

**Comment by iNPUTmice** [comment]
Is there a deeper reason behind you wanting to know who the admin of a giving conference is?

**Comment by alexara** [comment]
> Is there a deeper reason behind you wanting to know who the admin of a giving conference is?

* In Gajim or IRC it's common to sort that way
* In case there's an issue with the server or with members of the MUC you quickly know whom you need to contact
* It's possible to quickly proof whose answers are authoritative

Those are the points which came to my mind.
