### ISSUE TITLE
Toggle OMEMO fingerprints with keyboard

### ISSUE THREAD

**Issue by mw80** [siacs/Conversations#1915]
#### General information
- **Version:** eg 1.12.2
  1.13
#### Steps to reproduce

The touchscreen of my mobile phoen is broken. It is only possible to operate via the hardware keyboard. Currently it seems not possible in conversations to toggle OMEMO fingerprints for other devices via keyboard.
#### Expected result

Toggle OMEMO fingerprints with a dedicated key.

**Comment by mw80** [comment]
Is it possible to implement this?

"Since "toggle the buttons" is an event, it can be sent from everywhere as you wish. In your situation, you can listen the event of keyboard action and operate SwitchButton after that. There is no coupled relation between SwitchButton and keyboard event."
https://github.com/kyleduo/SwitchButton/issues/52

**Comment by iNPUTmice** [comment]
I think this is possible now since we switched away from that library to default widgets
