### ISSUE TITLE
App hangs on the login screen when you login just after you sign up for account on server.

### ISSUE THREAD

**Issue by gakwaya** [siacs/Conversations#1916]
#### General information

* **Version:** eg 1.10.0
* **Device:** LG
* **Android Version:** eg Android 4
* **Server name:** self hosted ejabberd

* **Conversations source:** self build 

#### Steps to reproduce

  1.Install fresh copy of Conversations

  2.Sign up for account on server(It logs in automatically)

  3.Go into Manage Accounts ,long click on the account-->>Delete Account.
    Hit the back button a couple of times till the Login screen is shown.

  4.Type in user name and password and hit the confirm button.

#### Expected result
  When app logs in for the StartConversation activity to be shown

#### What I see instead

 Hangs on the login screen even after the app has logged in.(Can see that from logcat).

Possible Reason :

```
private OnStatusChanged statusListener = new OnStatusChanged() {

		@Override
		public void onStatusChanged(Account account) {
			Log.d(TAG, "onStatusChanged() called with: " + "account = [" + account + "]");
			XmppConnection connection = account.getXmppConnection();

			

			if (mOnAccountUpdate != null) {
				mOnAccountUpdate.onAccountUpdate();
				Log.d(TAG,"mOnAccountUpdate is NOT NULL ,ACCOUNT :"+account.getJid()+" status is :"+account.getStatus().toString());
			}
			
			....
			}
			}
```
Inside XmppConnectionService ,the onAccountUpdate() override of the OnStatusChanged interface is not called as  the mOnAccountUpdate member variable is not initialized yet.The solution I could come up with was to send a broadcast with the update that there has been an account update.Interested activities simply listen to that broadcast.This fixes my problem.
This may not be the best solution as I am still discovering my way around the android platform.Better suggestions are welcome.Just an ending note ,good job to the developers of Conversations.

**Comment by iNPUTmice** [comment]
> 1.10.0

really?

**Comment by gakwaya** [comment]
My clone of the project is dated back then ,I haven't updated because some of my changes conflict with yours.If the upstream branch doesn't have this problem then just ignore this issue.
