### ISSUE TITLE
Allow EmojiOne to render emoticons

### ISSUE THREAD

**Issue by PanderMusubi** [siacs/Conversations#1918]
Please allow rendering of emoticons such as: smile: with EmojiOne font http://emojione.com/ (which is usually available on Android) 

* **Version:** 1.13.1
* **Conversations source:** F-Droid

**Comment by iNPUTmice** [comment]
Emojis render fine for me. But you need at least Android 4.4 or something for them to be included.

**Comment by PanderMusubi** [comment]
I have Android 6.0.1 with Cyanogen OS 13.1 and they don't render. Please reopen this issue.

**Comment by iNPUTmice** [comment]
We are talking about unicode emojis here right? Those are displayed by the
operating system. So either we are talking about different things or your
ROM is broken.

**Comment by PanderMusubi** [comment]
Yes, they work fine in other apps such as Telegram and AnySoftKeyboard.

**Comment by licaon-kter** [comment]
Pics in Telegram and Conversations?

**Comment by PanderMusubi** [comment]
![tmp_22629-screenshot_20160621-2229151946872726](https://cloud.githubusercontent.com/assets/198964/16245169/e3101e92-37ff-11e6-96c3-b4b08d3ee0da.png)

![tmp_22629-screenshot_20160621-2227121626510550](https://cloud.githubusercontent.com/assets/198964/16245183/eee47182-37ff-11e6-95f7-ab7fd1e7db88.png)

![tmp_22629-screenshot_20160621-222601-910117666](https://cloud.githubusercontent.com/assets/198964/16245195/feb69c48-37ff-11e6-8716-1b5e2436c457.png)

**Comment by iNPUTmice** [comment]
You realize that there is an emoji in the screenshot of Conversations you just posted?

**Comment by PanderMusubi** [comment]
Yes, but not triggered by words between colons such as :smile:

**Comment by PanderMusubi** [comment]
: smile : (spaces added to illustrate the point)

**Comment by iNPUTmice** [comment]
Oh sorry I didn't understand that you were talking about replacing the string ```:smile:``` with an emoji.
That's currently not on our TODO list. Just like we do not replace strings like ```:-)``` with what arguable is or is not the corresponding emoji.

**Comment by PanderMusubi** [comment]
Sorry for the confusion here too. Can it be implemented as a feature that can be switched on and off. Separate features for the two types of replacements. The first is used a lot by users of Slack. The second you do not want when copy pasting code. That might be good defaults as well.

**Comment by PanderMusubi** [comment]
It can be two independent issues. The latter only basic support for :-) :) ;-) ;) :-( :( :S :-S

**Comment by iNPUTmice** [comment]
>  Can it be implemented as a feature that can be switched on and off. 

sure. you can implement what ever you want.

**Comment by PanderMusubi** [comment]
😂

**Comment by PanderMusubi** [comment]
Can this issue be reopened please?
