### ISSUE TITLE
High battery consumption

### ISSUE THREAD

**Issue by Eibriel** [siacs/Conversations#1920]
#### General information

* **Version:** 1.31.1 (the problem started on this version apparently)
* **Device:** Motirola G 3 2015 16gb
* **Android Version:** Android 5.1.1 Cyanogenmod
* **Server name:** jabberes.org, group: salas.suchat.org
* **Server software:** ?
* **Installed server modules:** ?
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Run Comversations, check battery usage after a while

#### Expected result

About 64% battery consumotion by Conversations
![tmp_7200-screenshot_2016-06-19-11-55-00497963136](https://cloud.githubusercontent.com/assets/172656/16178481/764fe800-361f-11e6-85e6-950e47d46271.png)

**Comment by licaon-kter** [comment]
Picture of Conversation battery details?

**Comment by Eibriel** [comment]
![tmp_11551-screenshot_2016-06-19-14-55-27-1754105748](https://cloud.githubusercontent.com/assets/172656/16178990/62e17860-362e-11e6-926d-7b42fda7e29a.png)

Is dropping because I've disconnected my account.
I don't chat much with conversations, and I'm on a group that is mostly inactive.
So Conversations is IDLE most of the time.
Because my phone have 2gb ram is probable that the software is rinnung even when I'm not using it (I'm not sure how memory management works)

**Comment by Eibriel** [comment]
Version 1.13.2 is working fine
