### ISSUE TITLE
[Feature request] Option for custom ressource name (not urgent at all!)

### ISSUE THREAD

**Issue by conrad-heimbold** [siacs/Conversations#1922]
It would be nice to have an option to give a XMPP account a custom ressource name that you can type in (feature request), not only a list to choose from (current state). 
For example, if you have two android devices both with Conversations and Xabber installed (I do like Xabber more for some features), how would you choose?
I would prefer a custom scheme for those ressources like: 
    `<app/program>/<operating system>/<device-type>`, 
so e.g.
     `conversations/android/smartphone`
     `pidgin/ubuntu/laptop`
     `xabber/cyanogenmod/tablet`
etc.

That would make naming a lot more easier. 

At least for advanced users who know what "ressource" means. Maybe you can also change the description under "ressource" in the settings app a little bit, "The name this client identifies itself with" sounds as if the user would have to remember something. 

However, this feature request is not at all urgent.

**Comment by iNPUTmice** [comment]
We had this request before. Please search the bug tracker.

We would like to get rid of resources completely sooner than later.
