### ISSUE TITLE
Wrong background color in Expert settings

### ISSUE THREAD

**Issue by gkirilov** [siacs/Conversations#1925]
#### General information

* **Version:** 1.13.2
* **Device:** Samsung Galaxy S4 Mini Plus
* **Android Version:** Android 4.4.4
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Switch to the dark theme
1. Open Settings->Expert settings

#### Expected result

The background color should be the same as in the main Settings screen.
It is quite darker, instead.
(I can actually see a slight difference in the light theme as well. I believe it is not intentional there either.)

**Comment by iNPUTmice** [comment]
The settings are being rendered by the framework. We have no influence on that.

> (I can actually see a slight difference in the light theme as well.

the difference is very slight and I have no interest in actually taking screenshots and checking the hex values but I believe the Android System Settings show the same behaviour.

Maybe that's Androids idea of showing you that you are in a sub-settings

**Comment by gkirilov** [comment]
I don't see such a behavior in Android System Settings.
The background stays the same everywhere, unless there is a modal pop-up - then the background gets shaded.

But Expert settings is just a "normal" screen, hence I expected it not to get shaded.
Maybe the wrong "type" has been used for this screen.

**Comment by iNPUTmice** [comment]
Feel free to send in a PR if you spot any wrong 'type'.
