### ISSUE TITLE
where is call atention?

### ISSUE THREAD

**Issue by burzum0** [siacs/Conversations#1927]
Hello every body.

Sorry if I didn't write in the good way.

How could I activate the call atention?

Thanks I'd like contribute in the developtment of this app.

**Comment by benediktg** [comment]
What do you mean with "call attention"? Could you elaborate on this? :wink:

**Comment by burzum0** [comment]
https://developer.pidgin.im/ticket/14714

Here is explained

Sorry muy english

**Comment by burzum0** [comment]
You can call to other phone.

Xabber client can do it.

**Comment by iNPUTmice** [comment]
It's not implement and there are no plans to implement it.
