### ISSUE TITLE
Show Online Status in Conversation Window

### ISSUE THREAD

**Issue by mastad0n** [siacs/Conversations#1928]
#### General information

* **Version:** 1.13.2
* **Device:** Motorola Moto E
* **Android Version:** Android 6.0 Cyanogenmod
* **Server name:** conversations.im
* **Conversations source:**  F-Droid

#### Steps to reproduce

1. Open a Conversation Chat Window.

#### Expected result

See online status next to (or bellow) contact name.

**Comment by d9h02f** [comment]
Settings -> Send button indicates status

On mobile devices, online context is pretty meaningless though.

**Comment by jkufner** [comment]
@d9h02f It is not always a mobile device on the other end.
