### ISSUE TITLE
restart OTR encryption

### ISSUE THREAD

**Issue by burzum0** [siacs/Conversations#1931]
Hello.

Sometimes OTR message is saying OTR error (maybe you lose connection) and we must restart OTR for create a new pass.

Are there any way for do this?

**Comment by benediktg** [comment]
I would say that if you have the option to use OMEMO then use that – OTR does not play very well with mobile devices and aynchronous chats by design…

**Comment by benediktg** [comment]
I would say that if you have the option to use OMEMO then use that – OTR does not play very well with mobile devices and aynchronous chats by design… :wink:

**Comment by burzum0** [comment]
Thanks benedicktg for your answer.

I am using xabber with OTR, is working very good. Restarting OTR you can solve the most of problems.

**Comment by iNPUTmice** [comment]
You can sent an unencrypted message. That will restart the session. Or end the conversations and start it again.

**Comment by iNPUTmice** [comment]
> I am using xabber with OTR, is working very good. Restarting OTR you can solve the most of problems.
With OMEMO you don't have to fall back to those work arounds.
