### ISSUE TITLE
simplify process to compare OMEMO fingerprint for new contacts

### ISSUE THREAD

**Issue by hermann-san** [siacs/Conversations#1935]
Hi, I just installed conversations and I have a comment about the process to compare the fingerprints between two contacts that have added each other. 
Lets say user A adds user B to the contact list and then it sends a message to user B. Then user A gets a message with the fingerprint of User B, but it doesn't say where to look on the  device of user B. 
To make this more intuitive it would be nice to tell user A where user B should look to find the fingerprint (e.g. go to Accounts - click on the corresponding account name and there is the fingerprint).
This is probably also documented somewhere, but you know how users are ;-)  they like to have it intuitive instead of looking in the docs...
Just my 2 cents to make it even simpler for the user.
Cheers.

**Comment by iNPUTmice** [comment]
I think this can be merged into #1632
