### ISSUE TITLE
No good way to detect if users are online

### ISSUE THREAD

**Issue by dnut** [siacs/Conversations#1940]
Once I have a conversation created for each contact, the buddy list is useless. The status indicators should really be in the conversation list. Clicking on each conversation to see if the send button is green is not a very good solution.

**Comment by d9h02f** [comment]
https://github.com/siacs/Conversations/issues/1937

**Comment by benediktg** [comment]
With modern XMPP (i. e. the MAM plugin is loaded among others) it should not make a difference whether the other contact is online or not AFAIK.

**Comment by dnut** [comment]
That's like saying it doesn't matter if anyone answers your phone calls because you can leave a voicemail.

**Comment by d9h02f** [comment]
The only thing 'online' used to mean was 'the chance of your messages not arriving on my computer is slim'. The problem of disappearing messages has been solved, and so online statuses no longer have any real use.

**Comment by dnut** [comment]
Not at all. The purpose is to indicate whether someone is available. Even when disappearing messages was a problem, this was still the primary purpose of online statuses.
