### ISSUE TITLE
Security issues with Google & TOR 

### ISSUE THREAD

**Issue by alanthehat** [siacs/Conversations#1941]
#### General information

* **Version:**  1.13.0 and earlier
* **Device:** several
* **Android Version:** several  Android
* **Server name:** Google
* **Server software:** unknown 
* **Installed server modules:** unknown 
* **Conversations source:**  F-Droid 

#### Steps to reproduce

1. Connect through TOR 
2. …

At irregular intervals Google locks the account(s) & sends a message that "unknown device" has attempted to log in

#### Expected result

no messages & lockouts from Google 

#### Debug output

irrelevant

**Comment by vanitasvitae** [comment]
I guess that this is an unpreventable side effect of using tor.

**Comment by iNPUTmice** [comment]
Unless you also have an idea on what Conversations could be doing different I'd say that there is nothing the client can do about it.

**Comment by alanthehat** [comment]
Is there nothing in the standards to identify the device, much like html headers? 
If there is it would be nice if it is configurable. 
Do you know what Google's 'talk' or 'hangouts' do?

**Comment by licaon-kter** [comment]
Tor exit nodes are a known/listable thing. Google likes predictable behaviour, hence any not normal/new traffic (say VPN or Tor) is flagged and access is blocked, for your security.

If you expect privacy not sure why you would use Google (services) anyway.

**Comment by alanthehat** [comment]
It's not privacy per se that I'm looking for here, it's mostly government interference that I'm trying to bypass.
The government has insisted that my ISP provides them 2 services - denying access to a list of sites is annoying, but the other is storing a trace of my internet use. 
I didn't agree to either of these &, like everybody else, I wasn't asked.TOR resolves both problems for me while increasing TOR traffic which helps to hide those that need privacy.

**Comment by licaon-kter** [comment]
Again, Google even has a "state level data request notification" thing for you.

**Comment by alanthehat** [comment]
I'm sorry, I don't know what that means?

**Comment by licaon-kter** [comment]
It means that it will notify you if a "state level actor/agency" (whatever state) is detected/trying to get access to your mail (not sure how though, hacking, force password, certificate foul-play, you name it).

**Comment by alanthehat** [comment]
I believe that's for official requests for a dump of records or logs, not hacking. 
It does nothing to address the ISP logs noted earlier or, for the paranoid, the possibility of man-in-the-middle at Menwith Hill or Goonhilly Down (in the UK, other countries have equivalents) 
#SnoopersCharter is almost passed into legislation in the UK, it's time to use TOR exclusively. :-(
