### ISSUE TITLE
Password and messages in database

### ISSUE THREAD

**Issue by herbert777** [siacs/Conversations#1942]
#### General information
- **Version:** 1.13.2
- **Android Version: tested on 4.2.2 and 6.0
- **Conversations source:  F-Droid and self build

I have noticed 2 issues:
1- the password is kept unencrypted in the history file that is in data/data/eu.siacs.conversations/databases
2- if I delete all the messages from a conversation they don t appear anymore in the app, but they are still visible (all of them) in the databases' history file.
Is it normal behaviour?

**Comment by iNPUTmice** [comment]
>  the password is kept unencrypted in the history file that is in data/data/eu.siacs.conversations/databases

we need to login to the server with that password

> if I delete all the messages from a conversation they don t appear anymore in the app, but they are still visible (all of them) in the databases' history file.

This I can not reproduce. Do the messages re-appear in the UI if you end the conversation and reopen it again?

**Comment by herbert777** [comment]
If I end the conversation and reopen it again (without leaving the app) the messages appear again.
If I clear history, the messages don t appear anymore in the app but they are still in the database.
If I clear history and end the conversation, the messages don t appear in the app anymore and are gone from the database too.

**Comment by papermate** [comment]
> we need to login to the server with that password
Most servers support hashed password, and they are often hashed in the local database. Is there any way to implement this, maybe by also adding a setting to store plain password for servers that don't use any hashing?

**Comment by jkufner** [comment]
There is one way to do this: Login with password to a server, generate new unique private/public key pair or hashed token, then use this token to authenticate later from the device. This approach is common on web applications, but I don't think any Jabber server supports this.

**Comment by Marsupio** [comment]
Prosody has an article on this issue. They say they are waiting for more clients to support SCRAM.
https://prosody.im/doc/plain_or_hashed
