### ISSUE TITLE
Conversation uses xep-0363 with unencrypted data

### ISSUE THREAD

**Issue by lupusmeatus** [siacs/Conversations#1943]
An average user does not expect, that files sent in a chat are stored forever.
Some means should be established, to prevent that files are published via XEP-0363 by accident.

Quote from http://xmpp.org/extensions/xep-0363.html:
8. Security Considerations
    Client implementors MUST consider the fact that without additional end-to-end-encryption files uploaded to a service described in this document will store those files in plain text on that service. Client implementors SHOULD either use this only for semi public files (for example files shared in a public MUC or a PEP Avatar) or implement appropriate end-to-end encryption.

#### General information

* **Version:** 1.13.3

#### Steps to reproduce

1. Send Image without encryption enabled

#### Expected result

What is the expected output?
E.g. a warning before uploading the file. 
Or a setting that prevents the usage of XEP-0363 with unencrypted files.

What do you see instead?
File is uploaded and (depending on the server-configuration) there is no way to delete it.

**Comment by iNPUTmice** [comment]
Why do you think files should be treated different from messages? An unencrypted text messages is also stored on the server for ever without a way to delete it (depending on server configuration)
Do you propose we should warn before sending any kind of message?

**Comment by lupusmeatus** [comment]
The point is that using xep-0363, there is a single URL that makes the sensitive information available.
From a jurist point of you may have published the information by making it accessible over an URL, which anybody can retrieve. So let us assume the URL is published somewhere. Who will be blamed:
* the owner of chat-server?
* the one who published the URL? 
* the one who published the data, by sending the data by sending an unencrypted private message. 

I am not a jurist, but I guess the one who published the data, by sending a private message.
So I think the use of xep-0363 does make a difference. Anybody out here that can clarify this?

I can follow your argumentation, too. 

So may this issue has to be closed.

> Do you propose we should warn before sending any kind of message?
Yes, I like this idea.
But lets go in detail about that in https://github.com/siacs/Conversations/issues/1944
