### ISSUE TITLE
verification - secret question

### ISSUE THREAD

**Issue by rabbit111** [siacs/Conversations#1945]
* **Version:** 1.13.4
* **Device:** BB q10
* **Android Version:** eg Android 6.0 Stock or Android 5.1 Cyanogenmod
* **Conversations source:**F-droid

Verification by secret question is very slow ca. 1-2 minutes or app is crashing/freezing. (conversation -pidgin, pidgin-conversation, chatsecure - conversation, conversation - chatsecure).

**Comment by iNPUTmice** [comment]
If Conversations is crashing please provide the stack trace
