### ISSUE TITLE
no visible reaction upon invitation to MUC

### ISSUE THREAD

**Issue by silberzwiebel** [siacs/Conversations#1946]
#### General information

* **Version:** 1.13.4
* **Device:** Motorola Defy+
* **Android Version:** Android 4.4 Cyanogenmod
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** Stream Management, MAM
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Create a MUC
2. Invite participants

#### Expected result

I'd expect that all participants I invited to the MUC are shown as members instantly. Maybe they can be marked as 'invited, but not online yet'. Otherwise, I do not know if I really invited them to the MUC. I guess they appear as members if their client fetches the invitation but this is non-intuitive, in particular for non-techy people. I invited the same persons several times because I wasn't sure whether they were really invited.

I saw that it is also possible to select more than one contact at once but since I didn't get any response from Conversations I thought this multiple-at-once invitation was not working. At the moment I have no clue, if it is working or not.

Thanks for considering this.

**Comment by iNPUTmice** [comment]
Your server should announce affiliation changes (from none to member in that case) via message if the user is not in the room.
See Example 190 or 176 in the MUC XEP (there are other examples as well)

The MUC server on conversations.im for example already does this.

**Comment by silberzwiebel** [comment]
okay, do I need any special server-config for this? Because it is not working for me at the moment...
I'm using prosody 0.10 nightly and didn't payed much detail to the MUC config...

**Comment by iNPUTmice** [comment]
I think you need to implement that in prosody or ask the prosody developer
to do so. I thought there was an issue about this on the bug tracker but I
couldn't find it when I was searching for this before.

**Comment by silberzwiebel** [comment]
for the record: it's still not fixed in prosody but there is a patch around, see here: https://prosody.im/issues/345
