### ISSUE TITLE
Security Error on Huawei MediaTab T1 7.0

### ISSUE THREAD

**Issue by vanitasvitae** [siacs/Conversations#1947]
#### General information

* **Version:** eg 1.13.4
* **Device:** eg Huawei MediaTab T1 7.0
* **Android Version:** eg Android 4.4.2
* **Server name:** selfhosted with Lets Encrypt certificate
* **Server software:** ejabberd 16.04
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Create account (inband registration or existing account)
2. Click connect

#### Expected result

I expect conversations to connect to the server.

Instead it shows a red triangle with "Sicherheitsfehler" ("Security Error")
On other devices it is working just fine.

#### Debug output

````
adb logcat -s conversations

W/System.err( 2115): javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
W/System.err( 2115): 	at com.android.org.conscrypt.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:146)
W/System.err( 2115): 	at de.duenndns.ssl.MemorizingTrustManager$MemorizingHostnameVerifier.verify(MemorizingTrustManager.java:673)
W/System.err( 2115): 	at de.duenndns.ssl.MemorizingTrustManager$MemorizingHostnameVerifier.verify(MemorizingTrustManager.java:694)
W/System.err( 2115): 	at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:730)
W/System.err( 2115): 	at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:455)
W/System.err( 2115): 	at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:355)
W/System.err( 2115): 	at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:444)
W/System.err( 2115): 	at java.lang.Thread.run(Thread.java:841)
D/conversations( 2115): user@myserver: TLS certificate verification failed
D/conversations( 2115): user@myserver: error connecting account. try again in 32s for the 2 time
V/AlarmManager(  668): set(PendingIntent{42059320: PendingIntentRecord{421a8050 eu.siacs.conversations broadcastIntent}}) : type=2 triggerAtTime=779196 win=-1 tElapsed=779196 maxElapsed=803945 interval=0 standalone=false
````

**Comment by mimi89999** [comment]
Is your cert chain complete? Are let's encrypt certs trusted by your device? What protocols does your server support and what ciphers?

**Comment by vanitasvitae** [comment]
How can I test, whether my chain is complete? I'm not facing any problems with other devices/services so far...
If I open up my cloud website (same cert) I get no certificate errors or messages about my device not trusting the certificate.
I only activated secure ciphers on my server.
`    protocol_options:
      - "no_sslv2"
      - "no_sslv3"
      - "no_tlsv1"
      - "no_tlsv1_1"
    ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"`

**Comment by mimi89999** [comment]
You have an ECDSA cert, right?

**Comment by vanitasvitae** [comment]
Yes it is.

**Comment by mimi89999** [comment]
I would say it is because that isn't supported by the ssl/tls lib on your device. Can you open your website in the Android web browser or only in Firefox/Fennec/Iceweasel?

**Comment by iNPUTmice** [comment]
Does your pem file contain two certs?

**Comment by vanitasvitae** [comment]
I can open my website in the preinstalled browser, as well as in Chrome.

@iNPUTmice My pem file contains two certs and the private key.

**Comment by vanitasvitae** [comment]
> You have an ECDSA cert, right?

Oh I just saw, that I missread. I have a RSA4096 Key.

**Comment by mimi89999** [comment]
That cipher is supported by Conversations: https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/Config.java#L114

**Comment by SamWhited** [comment]
> That cipher is supported by Conversations: https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/Config.java#L114

Only if it's supported by the system running Conversations.

**Comment by mimi89999** [comment]
@vanitasvitae If you want, you can try with my server: lebihan.pl

**Comment by vanitasvitae** [comment]
@mimi89999 Do you use the same ciphers?

I successfully connected to another account on jabber.ccc.de

**Comment by mimi89999** [comment]
I have a Let's encrypt certificate, only support TLSv1.2, and AES256 or 128 with ECDHE or DHE with a 4096 bit key as ciphers.

**Comment by vanitasvitae** [comment]
It was a missing cipher option. I added ECDHE-RSA-AES256-SHA and now it works. Thank you very much for helping me out @mimi89999 :)
