### ISSUE TITLE
Store encrypted HTTP files on /data/data not /sdcard

### ISSUE THREAD

**Issue by dllud** [siacs/Conversations#1948]
On most Android devices, Full Device Encryption (FDE) only encrypts the `/data` directory. Files in `/sdcard`are left out.

Currently, when Conversations downloads an HTTP uploaded file, it saves *all* image files to `/sdcard/Pictures/Conversations` and *all* other files (e.g. audio) to `/sdcard/Conversations`, no matter whether they were sent in plaintext or encrypted with OMEMO.

If someone finds my lost phone, they'll be able to read all the data in `/sdcard`, which will contain files that my contacts had taken care to send in an encrypted form.

The correct behaviour, implemented in messengers such as Telegram, is:
- Store all files sent through an encrypted channel in `/data/data/eu.siacs.conversations/files`.
- Store files sent in plaintext in `/sdcard/Conversations` as you currently do.

**Comment by licaon-kter** [comment]
Telegram stores files in */sdcard/Telegram/...* here, not sure what you mean.

**Comment by iNPUTmice** [comment]
Most users want to be able to access the pictures from their computer which is not possible if the files are stored in the Apps private directory. Very early version of Conversations actually did use ```/data/data``` but it was deliberately changed after user requests.

If your phone doesn't encrypt the SD card that's a problem of your phone. And actually…

> On most Android devices, Full Device Encryption (FDE) only encrypts the ```/data``` directory. Files in /sdcardare left out.

I would like to have a source for that claim because I don't think that's true.

**Comment by licaon-kter** [comment]
> On most Android devices, Full Device Encryption (FDE) only encrypts the /data directory. Files in /sdcard are left out.

There might be a misunderstanding here. Usually /sdcard is not an actual SD card but the internal memory, that SHOULD be encrypted on FDE. 
Actual SD cards end up in /sdcard1/ or other locations and those might not be encrypted, yes.

**Comment by dllud** [comment]
The full story is: encryption of `/sdcard` is device dependent. It depends on how the vendor arranged partitions in the phone's internal memory. Android only encrypts the `/data` partition.

Newer devices have a single partition and emulate sdcard storage. They store data to `/data/media`,  and `/sdcard` is just a link to it. This way everything gets encrypted.
On the other hand, older devices have a physically separate sdcard-partition on the phone, which is directly mounted to `/sdcard` and will not be touched by encryption.
There is a full discussion at: [Does Replicant also encrypt the internal storage?](http://redmine.replicant.us/boards/9/topics/7497?r=8307)

Telegram does what I mentioned above. When I received images through a "Secret Chat" none of them are stored in `/sdcard/Telegram/`. They only get stored there if they are sent through unencrypted chats.

> Most users want to be able to access the pictures from their computer which is not possible if the files are stored in the Apps private directory.

Sure. The correct way to deal with that, while keeping your files encrypted, is to do what Telegram does: place a "Save to Gallery" button.
![save-to-gallery](https://cloud.githubusercontent.com/assets/1716156/16708193/ecccf3c0-45e1-11e6-9850-2eb8a70b6a7d.png)
In Conversations it could be a "Save to sdcard" button, that appears after long-pressing the image or sound in the chat activity.
