### ISSUE TITLE
Ejabberds muc sub support?

### ISSUE THREAD

**Issue by driminicus** [siacs/Conversations#1951]
In [this](https://blog.process-one.net/xmpp-mobile-groupchat-introducing-muc-subscription/) post process-one talks about muc sub; a way to handle offline users in a muc on xmpp which should be faster to make than [MIX](https://xmpp.org/extensions/xep-0369.html). The details are [here](https://docs.ejabberd.im/developer/proposed-extensions/muc-sub/) and it's supposed to be enabled for ejabberd 16.7.

Will conversations get support for this feature?

**Comment by iNPUTmice** [comment]
The main benefits of muc sub only come to play if you use ejabberds proprietary push system. So no there are no plans to support muc sub.

**Comment by driminicus** [comment]
That makes sense. Thanks for clarifying.

**Comment by pravi** [comment]
@iNPUTmice their blog (linked above) says,

> Rely on existing Push components (ProcessOne extension or XEP-0357: Push Notifications) to send events to mobile devices when application is asleep.

Did I miss anything?

**Comment by iNPUTmice** [comment]
Regular push will work with hibernating stream management sessions. That
means even without muc sub you are still in the room.
Tge ejabberd push on the other hand works with offline messages. This
requires the muc to send you offline messages. And that's pretty much what
muc sub does.
