### ISSUE TITLE
OMEMO is default encryption

### ISSUE THREAD

**Issue by guy6498765413168978463153248** [siacs/Conversations#1952]
#### General information

* **Version:** 1.13.4
* **Device:** Google Nexus 5
* **Android Version:** 6.0.1
* **Server software:** unknown
* **Installed server modules:** unknown
* **Conversations source:** F-Droid

#### Steps to reproduce

1. begin new conversation with user on friend list
2. usually change from un-encrypted message to OTR. recently default encryption method is set to OMEMO despite never setting it up or attempting to use it.

#### Expected result

What is the expected output? What do you see instead?
I see OMEMO as the default encryption method on a new conversation. OTR will stick when set but I usually don't save messages for any period of time.

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

*will update with logcat info*

**Comment by licaon-kter** [comment]
See FAQ, it's by design to promote the move to the newer/better OMEMO.

**Comment by goofankle** [comment]
"OMEMO should be preferred over OTR for contacts who use Conversations."

But it's not preferred in my case, none of my other contacts utilize OMEMO. I prefer OMEMO. Is there a way to disable or force OTR by default?

**Comment by iNPUTmice** [comment]
OMEMO will only be the default if your contacts support it. 

>  Is there a way to disable or force OTR by default?

Yes if you recompile Conversations you can disable OMEMO via flag in Config.java

But you really want to use OMEMO if your contacts support it.

**Comment by guy6498765413168978463153248** [comment]
well ok
