### ISSUE TITLE
General I/O Error , Maybe you ran out of space

### ISSUE THREAD

**Issue by markwaters** [siacs/Conversations#1953]
#### General information
* **Version:** 1.13.5
* **Device:** Samsung Galaxy S2
* **Android Version:** Cyanogenmod CM-13.0-20160707-NIGHTLY Android 6.0.1
* **Server name:** im.collective-b.org.uk (self-hosted)
* **Server software:** prosody 0.9.10-1~wheezy1
* **Installed server modules:** 
* **Conversations source:** F-Droid

#### Steps to reproduce
1. Click Paperclip
2. Click Take Picture
3. Use camera to snap photo
4. Error message - General I/O Error , Maybe you ran out of space

#### Expected result
Photo should be sent , but isn't

Storage shows 1.12 Gb of 1.97 Gb used in internal storage and 7.79 Gb of 11.49 Gb of sdcard used.
Cyanogenmod has storage and contacts permission enabled for conversations.
I have the same version installed on my Android 4.4.4 tablet and this works as expected.

**Comment by alexara** [comment]
A friend of mine experienced this issue twice on his phone, one time on CM 5.1.1 and another time on CM 6.0.1. Only a complete wipe and fresh flash helped in his case. :walking:

**Comment by markwaters** [comment]
Damn , I only just wiped and flashed this fresh a week ago.
Thanks @alexara
