### ISSUE TITLE
[Feature Request] "Silent while screen on" -mode to avoid unnecessary notification sounds

### ISSUE THREAD

**Issue by gustavGuns** [siacs/Conversations#1957]
Hey there, 
i've got the idea about putting a "Silent while screen on" -mode in the "Quiet Hours" -category.
Just to avoid unnecessary notification sounds while using the phone.
I'm no developer. i can not code so i thought the idea is worth a request. I like the app very much and this could be a nice tweak. 
Thanks to all contributors

**Comment by iNPUTmice** [comment]
This is something your OS should do. It doesn’t make sense to put this into every app.
