### ISSUE TITLE
"Do not save encrypted messages" doesn't work

### ISSUE THREAD

**Issue by angrydonut** [siacs/Conversations#1958]
Hello!
This option worked only 1 time just after clear installation on Huawei H60-L04  (5.1.1). The messages made in openPGP mode were held for 10 minutes, after that disappeared. Stopped working after reboot. Cloudn't enable again, tryed to reinstall, re-enable, etc. Didn't work also on Alcatell (4.4.4) and Samsung (5.1.1).
My opinion is that auto destroying the sensitive history by the fixed timeout this is wery convenient option.

Version: 1.13.5  + Openkeychain 4.0.3  (OpenGPG keys imported)
Device: Samsung Galaxy J3 2016 (SM-J320F); Alcatell 5042D; Huawei H60-L04;
Android Version: 5.1.1 stock; 4.4.4 stock; 5.1.1 stock;
Server name: self hosted
Server software: ejabberd 14.07 (ubuntu 14)
Installed server modules: mod_adhoc, mod_announce, mod_caps, mod_carboncopy, mod_configure, mod_disco, mod_http_bind, mod_last, mod_muc, mod_offline, mod_privacy, mod_private, mod_proxy65, mod_pubsub, mod_register, mod_roster, mod_shared_roster, mod_vcard, mod_version.
Conversations source: F-Droid, Android market

PS: thank you for the best messenger!

**Comment by iNPUTmice** [comment]
Please provide steps to reproduce. I fail to understand what exactly you are talking about.
