### ISSUE TITLE
(FR) Account status notification icon

### ISSUE THREAD

**Issue by keshto** [siacs/Conversations#1959]
#### General information

* **Version:** eg 1.12.2
1.13.6 aggressive ping
* **Device:** eg Google Nexus 5
Moto droid
* **Android Version:** eg Android 6.0 Stock or 
Android 6 stock
* **Server name:** eg conversations.im, jabber.at or self hosted
Conversations.im
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

Linked in issue thread

#### Feature

I spoke on this in https://github.com/siacs/Conversations/issues/1954 and maybe my issue and the OP had different ideas. You mentioned it would be fix in 1.1 3.6 but I still don't see any options of setting a notification icon that I can always seeswhat the status of my accounts connectivity. It is importan to me to know if I am connected or not by glancing at the top of my screen and not having to open a chat and look at the send button's color.

**Comment by iNPUTmice** [comment]
You will get notified if you are not connected and 3 automatic re-connection attempts failed. If this is not working for you please post a the output of adb logcat so we can show an notification in case something goes wrong.

**Comment by keshto** [comment]
This is different then what I asked. I would like to know if I am connected
or not by looking at the notification icon (think persistent icon) also I
would like it to continue to reconnect ever X seconds. Just telling me
connection has failed and quiting is not helpful. If I am driving through a
dead spot I don't want to have to manually reconnect after I get out of the
dead spot just because the 3 retries failed.

**Comment by iNPUTmice** [comment]
Conversations will try to keep connecting even if the notification is displayed.

> This is different then what I asked. I would like to know if I am connected or not by looking at the notification icon (think persistent icon)

I understand you well. However being connected is normal. Telling the user that every thing is normal all the time doesn't make sense. Conversations tells the user if something is **not** normal.

If you experience issues with that behavior - like Conversations failing to detect that you are offline - feel free to open a specific bug report and we'll try to solve that issue.
