### ISSUE TITLE
Provide XEP-0146 support

### ISSUE THREAD

**Issue by tanty** [siacs/Conversations#1960]
Please, add support for:
XEP-0146: Remote Controlling Clients
http://www.xmpp.org/extensions/xep-0146.html

Thanks!

**Comment by iNPUTmice** [comment]
This is not on our todo list right now.

**Comment by tanty** [comment]
May I suggest to keep the issue open and apply a "later" label, or something like that?

Unless you really think this is out of the scope of what it will ever be developed for Conversations, of course...

**Comment by iNPUTmice** [comment]
> Unless you really think this is out of the scope of what it will ever be developed for Conversations, of course...

Yes I think it is.

Out of curiosity what exactly are you trying to do with this? Do you want to remote control other clients or do you want Conversations to be remote controlled? What 'problems' are you trying to solve with this?

**Comment by tanty** [comment]
Both ways would be ideal (able to command other clients and be commanded).

In any case, my use case would be to use it for commanding other clients.

I would be interested on having a "headless" jabber client running in my 24/7 machine with low priority so only when no other client would be available the messages would be delivered to it.

Whenever back online with another of my full featured clients, I could command this headless jabber to forward all unread messages.

I'm actually not sure this extension would completely allow my use case, which would be not only forwarding messages directly delivered to my JID, but also those posted in MUC's in which the "headless" jabber client would be in ...

**Comment by andersruneson** [comment]
Sounds like you need xep 313 message archive, which Conversations already
supports, but you want to do this in a really strange way and a use case
rather few would ever use.

**Comment by tanty** [comment]
The problem with XEP 313, AFAIU, is that it has to be implemented by the server hosting the MUC and that you can request the messages when you were not present in the room but have permissions to enter it.

I find it misleading since it is not clear for the people in that room that you would be able to read the messages later, when you log in.

In any case, you may be right and it would just be a matter of configuring the MUCs (would you have the possibility of doing so) and the archive properly ...

**Comment by iNPUTmice** [comment]
Yeah I had a feeling that you were after the requesting messages stuff. This is really something that should be handled by MAM.

FWIW depending on the server (prosody) and the specific config the users do know (or could know if the client displays it) that the room is being logged.
