### ISSUE TITLE
Decode embedded HTML

### ISSUE THREAD

**Issue by bysteven** [siacs/Conversations#1963]
Some clients send embedded HTML-formatted text, this should be decoded or at least extracted, removing all HTML tags to make it readable.

Example (from Trillian with OTR plugin):
<HTML><BODY BGCOLOR="#ffffff"><font lang="DE">hello world</BODY></HTML>

#### General information

* **Version:** eg 1.12.2
* **Device:** eg Google Nexus 5
* **Android Version:** eg Android 6.0 Stock or Android 5.1 Cyanogenmod
* **Server name:** eg conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by bysteven** [comment]
** < ** HTML><BODY BGCOLOR="#ffffff"><font lang="DE">:(</BODY></HTML>

**Comment by bysteven** [comment]
damnit, github actually decodes the HTML - anyway you know what I'm talking about.

**Comment by iNPUTmice** [comment]
Trillian... didn't know that was a still a thing.

If you Trillian supports XEP-0115 and you get me the client identity name I can add it to the HTML escaping white list.

(but really don't use Trillian or OTR).

**Comment by bysteven** [comment]
Yeah, it's actually the only slim decent looking client for Windows with lots of plugins and functionality. Pidgin and Gajim look like last century crap compared to Trillian. Their UI is really really bad. Plus it supports OTR (I only need it for online chatting so OMEMO is not required with its offline message function) and TOR routing, that's all I need!

**Comment by bysteven** [comment]
My friend google tells me that Triilian supports XEP-0115, how can I obtain the identity name?

**Comment by iNPUTmice** [comment]
You can get the identity name with gajim for example by right clicking on the contact and selecting 'information' The pop up has the client name.

**Comment by iNPUTmice** [comment]
I'm suspecting that the identity name is just ```Trillian```. If you are building Conversations yourself you can add Trillian to that list here https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/parser/MessageParser.java#L43 and see if this changes the behaviour for you.
