### ISSUE TITLE
presence configuration awkward

### ISSUE THREAD

**Issue by gdt** [siacs/Conversations#1965]
#### General information

* 1.13.5 from F-Droid
* Nexus 5
* CM 12.1 (5.1)
* self-hosted, jabberd2

#### Steps to reproduce

Try to configure presence in a way that plays well with what presence means on a  phone and interoperates well when using other clients.  In my case, I run Conversations on my phone (always), and also another client on a laptop (always running, but laptop is suspended sometimes, and often I am not at it).  My goals are to have the following in priority order; I think this is normal rather than odd.
 - appear online/available when my desktop client is not idle
 - appear online but away on my phone, regardless of what I'm doing with the phone
 - appear online/away from my desktop if phone is not connected
 
I'm currently doing this my 'manually set presence'.  But really I'd like to be able to set a default presence when active of away/nexus5 ('phone' is ambiguous about being on a call), and still have the unavailable in silent mode feature work.

#### suggested changes

Implement support for priority.  It's always 0.  That's sort of ok, because I can set the priority of the other client for online and away above ane below.

Implement a default presence, similar to manual presence, but intended to be how Conversations presents itself when online, so that one can use that and 'be offline in silent mode'.

Probably, have two of these, to allow choosing presence for silent/vibrate/normal.  (In my case, I wish to be reachable via xmpp on the phone, but not show up as available, so I'd pick the same for vibrate/normal.)

**Comment by benediktg** [comment]
@gdt: Have a look into the expert settings, there are some settings about the state. E.g. becoming "away" when your screen is turned off or "not available" when is is muted.

**Comment by gdt** [comment]
@benediktg: Before posting, I looked at all those and tried them.  I don't want my presence to change when I look at my phone briefly, so tying it to the screen being on/off isn't ok.   I realize this is all a bit complicated and that phone use of xmpp requires rethinking of what presence really means.

**Comment by iNPUTmice** [comment]
@gdt I highly suggest that you ignore presence and just let Message Carbons route your message to every device.

**Comment by gdt** [comment]
For me, presence is the point, and messaging is rare.   But I get it that Conversations doesn't care about that usage style, so I'll stop bothering you :-)
