### ISSUE TITLE
Detect deleted files

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1968]
#### General information

* **Version:** 1.13.5
* **Device:** Galaxy S3
* **Android Version:** Android 6.0 Cyanogenmod
* **Server name:** self hosted
* **Server software:** prosody trunk
* **Installed server modules:** all supported for Conversations
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Send a file eg an image
2. Delete the image from file system eg with gallery app or file explorer
3. Open Conversations, the image preview is appearing
4. Touching the preview shows toast that the image was deleted

#### Expected result

Conversations should check if the file exists and if not delete the preview. There is currently no possibility to delete and reload the the image manually. Long clicking and touching delete file doesn't help.

**Comment by iNPUTmice** [comment]
Works for me. Do you have this problem on the sending or the receiving
side? And did you attach a file or an image.

**Comment by kriztan** [comment]
I've just tried it with a second device, an Galaxy S5 mini with android 5.1 stock and it's not working, too.

I'm on the sending side. The file was in androids download directory and I've shared it from the gallery app. I've also deleted the image, which was still located in the download directory, with the gallery app. I thought Conversations copies files to the private directory ../pictures/Conversations?

**Comment by kriztan** [comment]
Thanks for your patch. Is this already implemented in the beta 1.13.7 from PlayStore? If yes, it's not working. I've tested it on two different devices with to different android versions, and it doesn't matter if I'm the sender or receiver of a file/image. See the attached screenshot, there is a preview of the image at the bottom shown, which original I've deleted with the stock gallery app. Touching the image shows the toast message, that the image was deleted.
![screenshot_20160726-190449](https://cloud.githubusercontent.com/assets/3350754/17148573/0643cf7a-5368-11e6-97de-d147ec396262.png)

**Comment by iNPUTmice** [comment]
Works for me. I pushed some commits that enable more logging. Can you test those and post the corresponding adb logcat?

**Comment by kriztan** [comment]
Thanks, are these changes available with a playstore version?

**Comment by kriztan** [comment]
I've tested it again and again and it seems to be fixed for files which are deleted by a file explorer e.g. ES File Explorer on both devices. Images which are deleted via the gallery app were not detected correctly on both devices. In the log files are no hints about that. I think this is not a Conversations issue anymore.
Thanks!
