### ISSUE TITLE
Conversations repeating last received message when reconnecting to a slack server

### ISSUE THREAD

**Issue by jgkamat** [siacs/Conversations#1970]
Unfortunately, I think I found yet another bug with slack (which is probably a fault on their end but I wanted to see if someone could take a look at it).

#### General information

* **Version:** eg 1.13.5
* **Device:** eg OnePlus One
* **Android Version:** CyanogenOS 13.1 (Android 6.0.1)
* **Server name:** Slack xmpp Gateway
* **Server software:** Slack
* **Installed server modules:** Unknown
* **Conversations source:** FDroid

#### Steps to reproduce

1. Sign into a slack xmpp gateway
2. Send yourself a message with this gateway (your_username@servername.xmpp.slack.com)
3. Disconnect from slack server (Manage accounts -> disable slack account)
4. Reconnect to slack server (same as above)
5. See that a new message has appeared, the one you just sent to yourself.

This seems to happen if anyone sends you a message (that person keeps sending you messages each time you login to slack). This is NOT replicated on the slack server itself, just on the conversations client.
This is only a single message (no repeating unless you toggle the connection), but this can get quite annoying if you are in a spotty area though.

#### Expected result

No message received

#### Debug output
I've changed my slack domain to `myslack`. Let me know if I'm getting these debug logs wrong, its my first time.
````
D/conversations(17535): app switched into foreground
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: leaving muc it@conference.myslack.xmpp.slack.com/jgkamat
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: leaving muc robocup@conference.myslack.xmpp.slack.com/jgkamat
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: leaving muc general@conference.myslack.xmpp.slack.com/jgkamat
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: disconnecting force=false
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: closing stream
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: xml parser mishandled java.net.SocketException
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: push mode false
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: connecting
D/conversations(17535): used lollipop variant to discover dns servers in 1 networks
D/conversations(17535): using dns server: 8.8.4.4 to look up myslack.xmpp.slack.com
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: using values from dns myslack.xmpp.slack.com[52.201.37.114]:5222 tls: false
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: TLS connection established
D/conversations(17535): jgkamat@myslack.xmpp.slack.com/conversations: Authenticating with PLAIN
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: logged in
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: sending legacy session to outdated server
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: starting service discovery
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: server name: Slack-XMPP
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: could not query disco info for jgkamat@myslack.xmpp.slack.com
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: activating grace period till 21:49:08
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: online with resource conversations
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: fetching roster
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: could not fetch bookmarks
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: joining conversation it@conference.myslack.xmpp.slack.com/jgkamat
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: joining conversation robocup@conference.myslack.xmpp.slack.com/jgkamat
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: joining conversation general@conference.myslack.xmpp.slack.com/jgkamat
I/ActivityManager( 4707): START u0 {cmp=eu.siacs.conversations/.ui.ManageAccountActivity} from uid 10251 on display 0
I/ActivityManager( 4707): Displayed eu.siacs.conversations/.ui.ManageAccountActivity: +80ms
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: error connecting account. try again in 12s for the 1 time
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: leaving muc it@conference.myslack.xmpp.slack.com/jgkamat
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: leaving muc robocup@conference.myslack.xmpp.slack.com/jgkamat
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: leaving muc general@conference.myslack.xmpp.slack.com/jgkamat
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: disconnecting force=false
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: waiting for tag writer to finish
D/conversations(17535): interrupted
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: leaving muc it@conference.myslack.xmpp.slack.com/jgkamat
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: leaving muc robocup@conference.myslack.xmpp.slack.com/jgkamat
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: leaving muc general@conference.myslack.xmpp.slack.com/jgkamat
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: disconnecting force=false
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: closing stream
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: xml parser mishandled java.net.SocketException
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: push mode false
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: connecting
D/conversations(17535): used lollipop variant to discover dns servers in 1 networks
D/conversations(17535): using dns server: 8.8.4.4 to look up myslack.xmpp.slack.com
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: using values from dns myslack.xmpp.slack.com[52.86.239.137]:5222 tls: false
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: TLS connection established
D/conversations(17535): jgkamat@myslack.xmpp.slack.com/conversations: Authenticating with PLAIN
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: logged in
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: sending legacy session to outdated server
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: starting service discovery
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: server name: Slack-XMPP
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: could not query disco info for jgkamat@myslack.xmpp.slack.com
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: activating grace period till 21:49:25
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: online with resource conversations
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: fetching roster
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: could not fetch bookmarks
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: joining conversation it@conference.myslack.xmpp.slack.com/jgkamat
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: joining conversation robocup@conference.myslack.xmpp.slack.com/jgkamat
D/conversations(17535): jgkamat@myslack.xmpp.slack.com: joining conversation general@conference.myslack.xmpp.slack.com/jgkamat
D/conversations(17535): app switched into background

````

This is probably related to #1536 and/or #1475

**Comment by jgkamat** [comment]
This is actually an issue on slack's end (I contacted slack support as well). I'm closing this issue now.

**Comment by selurvedu** [comment]
@jgkamat, could you please explain what is their purpose for doing this?

**Comment by jgkamat** [comment]
The slack gateways are extremely frustrating, and it's fairly clear that slack dosen't put any effort into them (I've found terrible bugs in both the irc and xmpp gateways, as well as the normal web client). I don't really have any interest in persuing this further because I've completely removed slack from my workflow due to these issues, and I highly doubt that anything will improve on their end. 

Here's the email chain I've had with them:

> The little bit of message history is there to ensure you don't miss any messages and provide context since XMPP lacks history over Slack. I'll let the team know that you don't enjoy this behavior.


>Personally, I think this dosen't help make sure I miss message history, as it only sends the last message (and not the whole unread conversation). An option to turn this off would be nice (as people are not expecting this behavior when using xmpp/irc). In my opinion, slack should behave just like a normal XMPP server. (There are ways to verify if a client has received the message, which you could use to turn this off?).
If you wanted to do this properly, I suggest that you implement http://xmpp.org/extensions/xep-0203.html, (and take a look at http://xmpp.org/extensions/xep-0160.html). My true XMPP group chats handle offline messaging just fine (even on groupchats, with images). There's also http://xmpp.org/extensions/xep-0313.html (which seems better) but it's in active development.

> We do hope to improve our gateway experience as time goes on and I am happy to share your feedback with our developers. I agree with you that a flag to disable this would make sense.


I've contacted slack many times for many bugs in their gateways (irc/xmpp), web clients, and apps, and all have gotten similar stock responses with no bugs fixed. I highly recommend using a native xmpp server, the experience is honestly much better than slack has ever been. (maybe conversations.im or fysh.in)

Also, I noticed that there's another bug with the slack xmpp server which causes messages to loop infinitely, spamming a group. I suspect this is because slack is incorrectly implementing their xmpp gateway by not acknowledging message sent receipts. Because of this, I wouldn't reccomend using the xmpp gateway at all, since it can spam groups you're in under your name.

**Comment by selurvedu** [comment]
> Essentially they've implemented a broken bouncer on top of their xmpp gateway for some reason.

Yeah, this was my first impression after using the gateway.

I was considering using a transport via [spectrum2](http://spectrum.im/) tied to [slack-libpurple](https://github.com/dylex/slack-libpurple), but I don't own an XMPP server and I have no plans of setting up one.

Simply ditching Slack is the easiest solution here, but it is not always acceptable to do so.
