### ISSUE TITLE
presently presence is problematic 

### ISSUE THREAD

**Issue by GavelRust** [siacs/Conversations#1976]
Is there a preferred methodology for troubleshooting presence issues?   I have been upgrading friends to xmpp texting but with some of them my quick icon is always black whereas theirs is frequently green.  I have abandoned chatme.im because of downtime in favor of xmpp.zone 

#### General information

* **Version:** eg 1.12.2
* **Device:** eg Samsung Galaxy S4
* **Android Version:** eg Android 4.4.4 stock
* **Server name:** jabber.zone & xmpp.zone (same provider)
* **Server software:** ejabberd according to xmpp.net
* **Installed server modules:** eg  all available shown by conversations
* **Conversations source:** eg F-Droid, none of my devices have gapps

#### Steps to reproduce

1. create account for device1
2. add to device1
3. create acct dev2
4. add dev2
5. add acct2 to device1
6. allow app on device2 to add acct1 
7. accept presence defaults

#### Expected result

to see presence of acct2 on dev1

#### Debug output

I couldn't sort out how to do this on the phone

**Comment by GavelRust** [comment]
I can't edit post on mobile

conversations version  1.13.6

**Comment by GavelRust** [comment]
ejabberd 16.04

**Comment by iNPUTmice** [comment]
There are two checkboxes in the contact details that tell you the subscription status.
