### ISSUE TITLE
Ideas for phone number based contact discovery

### ISSUE THREAD

**Issue by h-2** [siacs/Conversations#1978]
@iNPUTmice Since our last discussion on phone number hashing over at kontalk's github, I have thought about the problem and come up with some ideas that IMHO would add significant usability improvements to XMMP on mobile, although they don't solve the contact discovery problem as completely as other solutions. Here it goes:

# Adress book integration and contact discovery for XMPP

## Address book integration

The XMPP-Client shall integrate with the address-book available on the device / operating system. This includes matching xmpp-contacts to address-book contacts via "Jabber" fields of the VCards or a similiar mechanism.
The client shall use existing matches and motivate the user to create complete mappings and/or help with this, e.g. by automatic matching of names...

## Contact discovery

Client can start contact discovery by the following method:

* generate a salt
* for every person in address book **without a known XMPP ID** (alternatively a chosen subset):
  * hash another attribute of that person (preferrably phone-number or e-mail-address) in combination with the salt and remember the attribute type
  * send to all contacts **with known XMPP IDs** and whose client supports this extension the list of (attribute-hash, attribute-type)-tupels
    * all of the contacts then go through their address book entries **with known XMPP IDs** and hash their attributes with the given salt to look for a match
    * if a match occurs the XMPP ID for a given contact is reported back the requester
  * if an answer is received, the local address book entry is updated and it is possible to communicate via XMPP with the person
  * optionally the client could immediately ask to subscribe to the "new contact's" presence, initiate key-exchange et cetera

It would also be possible to forward these requests so that you ask friends' friends, as well.

## What's the point ?

  1. many modern messengers use telephone numbers as identifiers, and thereby ease contact discovery significantly
  2. however most of thee approaches cause significant risks to privacy and/or security, none of them work reliably in a federated or decentralised manner
  3. this approach models phone number discovery based on the assumption that most people in your address book know some other people in your address book; if you know one person's xmpp account out of a group of mutual friends, this will be enough to be discover the others of the group
  4. it has the positive side effect that xmpp accounts are stored in your address book which is likely backupped through some 3rd party mechanism. In the event that your xmpp server shuts down over night, you can easily move to another one without loosing you contacts.

## Limitations

* Initially you need to have some xmpp IDs of some people or you won't be able to discover anyone
* you might never discover that a person has an xmpp account, if you know no one else who knows about it

## Privacy and Security

* there are no central parties involved, at all
* since you are only submitting salted hashes of address-book content you are only sharing information with contacts that these contacts already have, i.e. you are only telling Bob that you know Alice, if Bob knows Alice already.
* the fact that you know Alice is of course a piece of information that Bob might not have, but this is still much better than e.g. Telegram where you submit your entire address book to a central server or Signal, where bits of your address book are floating through the entire network and can in theory be re-assembled by a third party
* when you ask Bob for Alice's XMPP ID based on your shared knowledge of Alice's phone number, Bob can still lie to you and just give you a wrong XMPP ID, but we assume that you trust the people in your address book; also since you are asking multiple people, chances are good that Charly might have the right XMPP ID of Alice and you will be notified of a conflict
* you can scale up the effectiveness of the algorithm at the cost of reliability of the information by allowing an additional hop of the requests through the network (asking friends' friends, too) -- this could be a user-definable option, either on the side of the original requester or on the side of the requestees (whether they wish to forward or not)

**Comment by Aluisyo** [comment]
+1

**Comment by h-2** [comment]
[I know hat conversations already has some address book integration, but right now it feels very "optional" and the user is not actively told by the program to do the mapping]

**Comment by h-2** [comment]
@grote In case you are interested, I guess something like this would also be possible for Briar!

**Comment by iNPUTmice** [comment]
Hi,

I appreciate you thinking about this and developing strategies on how to get a decentralized phone number look up working. So I'm gonna be honest with instead of just letting this issue rot.

I'm personally not going to invest any time in anything related to phone number lookup. Here is an incomplete list of why:

* I don't believe phone number lookup is **the** missing piece on the XMPP route to world domination. There are XMPP based instant messengers that provide a phone number based lookup and they don't seem to be very successful either. 
* A lot of people actually choose XMPP because it does not rely on phone numbers. Because they don't want to share their phone number with every one. Or because they want to use a device that doesn't have a SIM card.
* XMPP should advertise it's strength instead of copying every so called feature of other IM clients.
* I'm really not sure that phone numbers in it's current form will actually exist in 10 years.

That being said this shouldn't stop you from implementing such a service if you don't agree with me.

**Comment by andersruneson** [comment]
I think the ideas are cool and wish you would take them to the xsf as a
xep, that way more clients could use this.

**Comment by Natureshadow** [comment]
I completely agree with @iNPUTMICE.

Even today, no customer of Deutsche Telekom has a phone number anymore, but a SIP address (which is transparently constructed from a phone number though). With the world moving towards IP based telephony, using phone numbers as a primary key really doesn't make much sense anymore (not that it ever did).

**Comment by grote** [comment]
Hi @h-2,

interesting proposal. What I didn't understand is how the hashes should match if a random salt is used? Or do you want everybody to use the same salt? If so, why use a salt at all?
How do you reliably get hash matches when "another attribute" is used?

I am doubtful whether the proposed protocol would be interesting for use with Briar as one of the main design goals is to hide metadata. Associating actual identifying people in address books with Briar identities is quite dangerous, because this information is usually stored unencrypted on people's phone and might also leak through address book synchronization. Also, people might not want to reveal that they know certain other persons or that they are communicating with these people using Briar. Depending on how you design the contact hashing, your proposal might not only disclose all your contacts to all other contacts, but also their phone numbers. Imagine a journalist who communicates with secret sources, but also with other people who should not learn the identity of those sources.

**Comment by h-2** [comment]
@iNPUTmice 

> I appreciate you thinking about this and developing strategies on how to get a decentralized phone number look up working. So I'm gonna be honest with instead of just letting this issue rot.

Thanks.

> I'm personally not going to invest any time in anything related to phone number lookup. Here is an incomplete list of why:

Although your mind seems to be made up, since you had a different position before[1], I would still like to follow up on your response

> I don't believe phone number lookup is the missing piece on the XMPP route to world domination. 

Out of curiosity, what do you think it is? To many of my non-technical peers it is exactly about quickly "finding" their friends 

> There are XMPP based instant messengers that provide a phone number based lookup and they don't seem to be very successful either.

That's true, but they lack other features like proper federation, iOS-client,  forward-secrecy... which makes it more difficult to advertise for.

>  A lot of people actually choose XMPP because it does not rely on phone numbers. Because they don't want to share their phone number with every one. Or because they want to use a device that doesn't have a SIM card.

Yes these are very good properties of XMPP and nothing in my proposal anywhere suggested giving up xmpp-ids. It is not about changing the way xmpp works, it just adds an additional layer for discovering the xmpp-id **on top of the current system**. This is 100% compatible to existing xmpp and no-one forced to take part.

>  XMPP should advertise it's strength instead of copying every so called feature of other IM clients.

:+1: I think the above system is not copying other features, but actually implementing a similar feature, but with superior privacy properties and based on the decentral strengths of xmpp.

>  I'm really not sure that phone numbers in it's current form will actually exist in 10 years.

Yeah, could be. But who knows if people will be using text then at all and not virtual reality video FOOBAR.  ¯\_(ツ)_/¯ 

But, please also note that above system is in no way specific to phone numbers as secondary identifiers. You can just as well use e-mail-addresses or even names (although I think the latter is less reliable because of regular people not using consistent naming schemes).

@Natureshadow 

> With the world moving towards IP based telephony, using phone numbers as a primary key really doesn't make much sense anymore (not that it ever did).

You did not understand the proposal correctly :) it's not about replacing xmpp-ids, it's about optionally adding secondary identifiers. Once you have associated a contact and found their xmpp-id you will never have to rely on the {phone number|secondary identifier} again, as all communication always happens through regular xmpp.

I see this as strengthening the xmpp-id, not weakening it, because people use the mechanism once to switch away from the secondary id and are then free (but still provide the same service to their peers).

@grote 

>  What I didn't understand is how the hashes should match if a random salt is used? 

You send the hash with your query.

> Or do you want everybody to use the same salt? If so, why use a salt at all?

Of course not :scream: 

> How do you reliably get hash matches when "another attribute" is used?

Example:

You have three people in your address book

            |bob | alice | karl
-------- | ------ | ----- | -------
xmpp|   bob@foo.im| ? | ?
mail | bob@foo.com| alice@web.com | ?
fon| 012345678 | ? | 9876789

You want to find out about alice's and karl's xmpp so you ask bob, but you do it, as described:

* you generate the salt `666666666666`
* since you don't have alice's number, you hash her e-mail address with the salt
* since you have karl's number, you hash it
* you send to bob:
   1. the salt `666666666666`
   2. `(EMAIL_TAG, 253e0d56fb16180a315dc8c60b93fe6b)`
   3. `(PHONE_TAG, fc9b2ddc4548bebe5984a30518ebb3a8)`

Then bob hashes the email and the phone numbers in his xmpp subset of his address book. If there is a match he reports the xmpp-id back to you with the corresponding category. This all happens automatically.

>  Associating actual identifying people in address books with Briar identities is quite dangerous,

Ok, then this is not for you. Although I seriously think this is really important for most people that are not being actively targeted.

> because this information is usually stored unencrypted on people's phone and might also leak through address book synchronization.

Yes, but especially if you are a briar user who as you said is super-worried about metadata, you are probably not syncing with google, are you?

> Depending on how you design the contact hashing, your proposal might not only disclose all your contacts to all other contacts, but also their phone numbers

nono, you misunderstood the system.  Only in the event that you share the knowledge of a secondary identifier of a third party with a second party, do you disclose your own knowledge of the third party to the second party. And then it is still only a request for an xmpp-id, nothing more, no meta data, no intent to communicate, just an automatic discovery request.
Only in the case where the briar-id itself would compromise metadata of the third party this would be a problem. If this is the case with briar you shouldn't publish it on your homepage as you suggested elsewhere. But maybe we can stick to XMPP in this thread for now and we will talk about briar another time? :smile:

**Comment by jkufner** [comment]
@h-2 This sounds interesting. Idea of sending salted hash may solve the privacy leak problem of asking. I would like to see some formal proof, that this schema is really secure.

About the feature: I don't think it should be part of Conversations nor limited to XMPP. This should be more general tool. Federated services have a big problem when looking up data in the network. On the Web we have Google. But there is no such thing for e-mail, Jabber and other services, but also PGP has this problem.

Think big. What about building a federated search engine?

What about performance? If other person has a lot of contacts inaddressbook, then to answer the question he must hash all these contacts with the provided salt, meaning there is no way to optimize the lookup. What if one wants to ask server with a few thousand users or a slow phone with few hundred contacts?

**Comment by grote** [comment]
Thanks for explaining your proposal in more detail now. It might be secure when a strong enough hash algorithm is used. I would just be worried that not enough people manually establish the connection between JIDs and their address book contacts, so the impact would be limited. However, good luck getting maybe others interested in your proposal since Conversations doesn't seem to be.

**Comment by erdmark** [comment]
Even strong hash algorithms don't use much because you can do a table of all possible phone numbers and corresponding hashes and run binary search on it.

**Comment by grote** [comment]
> Even strong hash algorithms don't use much because you can do a table of all possible phone numbers and corresponding hashes and run binary search on it.

That is why @h-2 proposes to add a different random salt with each discovery request.

**Comment by iNPUTmice** [comment]
I have now introduced [Quicksy](https://quicksy.im) which is my attempt at providing phone number lookup for in the Jabber world.
Here are are [the slides](https://github.com/iNPUTmice/talks/blob/master/2018_11_14_-_the_making_of_a_new_feature.md) for me introducing this new spin of. And here are [recordings of the German talk](https://media.ccc.de/v/dg-94) I gave.

**Comment by Echolon** [comment]
That's why "never say never" :smiley: 

:)

**Comment by h-2** [comment]
@iNPUTmice I had a look at quicksy and it has some nice things, although you'll have to admit it goes in an entirely different direction from what I proposed, because it is in fact a centralised service on top of XMPP. It doesn't federate and it wouldn't scale to multiple servers even if you released the source which you apparently decided not to.
Furthermore it leaks your phone number to the public and makes you as a service provider subject to court orders that involve the phone number. That's not saying it's worse than other services, it's just not a lot better IMHO.
