### ISSUE TITLE
Detect Tor status and ask if user wants to start it

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#1980]
Like ChatSecure does: https://github.com/guardianproject/ChatSecureAndroid/blob/master/src/info/guardianproject/onionkit/ui/OrbotHelper.java

Right now Conversations detects Tor as not running in the Accounts view, maybe you can pop a dialogue up asking: `Orbot doesn't appear to be running. Would you like to start it up and connect to Tor? Yes/No` and pull the trigger on the Orbot start intent.

**Comment by moshpirit** [comment]
When would be asking this question Conversations? Just when it's started? Every time you connect your account? Just once after installing the app? Cause I don't want to be asked this every time I open the app, there's a setting to run it under TOR already

**Comment by licaon-kter** [comment]
When Orbot is not actually running.

If Orbot app is dying that's not a Conversations problem, it's your/Orbot problem.

Not sure what you mean besides this.

**Comment by moshpirit** [comment]
So, as an user that do not use Conversations under TOR (even when I use Orbot for other apps so it's installed in my phone), how would I notice this change? That's what I meant

**Comment by licaon-kter** [comment]
You won't, since Conversations does/should not care about Tor then.

**Comment by moshpirit** [comment]
Great then! Though it was a change to promote new users to use TOR.

**Comment by licaon-kter** [comment]
No, just a small thing to help Tor users, this and #1930 should make Conversations a bit better.

**Comment by xpressengine3** [comment]
+1

**Comment by harshitbansal05** [comment]
I am giving a try to it..

**Comment by harshitbansal05** [comment]
@iNPUTmice @licaon-kter should I use a snackbar like the ones used in conversation fragment with two actions, namely `Uncheck Tor` and `Start Orbot`, or should I use a dialog? Also if a dialog is shown, and a user dismisses it, what should be the time interval after which other such dialog is shown?

**Comment by licaon-kter** [comment]
I do like the stack bar, but you might need more actions so maybe a dialogue is better.

What's the timeout now? (The one that shows the "trouble connecting" notification)

**Comment by harshitbansal05** [comment]
@licaon-kter each time the user sends a message while orbot is shutdown, he receives a notification saying `Unable to connect to account`.
