### ISSUE TITLE
Synchronize with contacts is not really optional

### ISSUE THREAD

**Issue by TheLastProject** [siacs/Conversations#1981]
#### General information

* **Version:** 1.13.7
* **Device:** Motorola Moto E 2015 (surnia)
* **Android Version:** CyanogenMod 13.0 nightly (Android 6.0.1)
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Open contact list
2. Get "Synchronize with contacts" dialog, in which Conversations explains it wants access to your contacts
3. Hit next
4. Hit deny
5. Open contact list
6. Get "Synchronize with contacts" dialog

#### Expected result

Either step 2 contain a "No thanks" and "Ask me later" option, or after hitting Deny in step 4 Conversations gives the option to not ask again. Also, Conversations should have an option in settings to not synchronize.

This may sound weird but I prefer my XMPP contacts to NOT be synced to my contact list, as I use XMPP on my desktop as well, where there is no mobile contact list to sync, which will cause my contacts to be displayed differently on my phone or on my desktop, which I consider an inconvenience.

#### Actual result

Conversations asks for contact permission every single time I open the contact list, basically forcing me to allow it against my wishes.

#### Debug output

Logcat returns no output at all during this action.

**Comment by iNPUTmice** [comment]
Android itself has that mechanism build in. If you deny that request two times or something android will allow you to deny it forever.

**Comment by TheLastProject** [comment]
That doesn't seem to work though. Maybe it's a CyanogenMod bug, but I've denied it at very least more than 20 times by now because I go through this every time I open the contact list on Conversations.

**Comment by licaon-kter** [comment]
Settings->Apps->Conversation->Permissions is set up how?

**Comment by iNPUTmice** [comment]
@TheLastProject do you never get the 'Never ask again' checkbox in that dialog or does selecting that checkbox doesn't have any effect?

I checked on a CM13 N4 and it works fine for me.

**Comment by TheLastProject** [comment]
Oh, indeed checking "Never ask again" in the Android dialog works. I had no clue apps could even tell that was selected. My bad!
