### ISSUE TITLE
Attachment option is not enable by default in Group chat

### ISSUE THREAD

**Issue by AsfakSaiyed** [siacs/Conversations#1984]
#### How can I enable file attachment option in Group chat window.

* **Version:** eg 1.13.7
* **Device:** eg Samsung Galaxy Note 2
* **Android Version:** eg Android 6.0 Stock or Android 5.1 Cyanogenmod
* **Server name:** eg self hosted
* **Server software:** openfire 3.9.3
* **Conversations source:** eg self build (latest HEAD)

#### Steps to reproduce

1. Create any group from application.
2. Try to open that group window you , no attachment option is available.

#### Expected result

There must be attachment option available for group chat.

#### What I had tried

I have enable that option forcefully by removing argument from #### setVisible() method
`menuAttach.setVisible(getSelectedConversation().getAccount().httpUploadAvailable() && getSelectedConversation().getMucOptions().participating());`

And set argument value to be **true** , so it will display option. But when I try to send attachment it is giving warning like

> Sending this without mutual presence updates could cause unexpected problems. Go to contact details to verify your presence subscriptions.

But I have already allow and done with presence subscription for all members in group. Is attachment not send problem is due to this presence subscription ? If it is then what is correct way to achieve this ? 

If any workaround for this issue then that would be appreciable.

**Comment by andersruneson** [comment]
Your server must support xep 0363, "http upload".

**Comment by AsfakSaiyed** [comment]
I had tried it but having same problem as mention [here](http://stackoverflow.com/questions/33628272/how-to-upload-the-siacs-httpuploadcomponent-for-file-sharing-in-openfire-localho).

Did you have any idea about that ?

**Comment by andersruneson** [comment]
No, I wouldn't use openfire. Either try prosody or ejabberd or if you can't
fix yourself, use a public server like jabber.at or conversations.im.

But you can close this issue. This has nothing to do with Conversations and
it's not a support channel for various servers.
Thanks.
