### ISSUE TITLE
[Feature request] Querying for a list of public chat rooms hosted by a server

### ISSUE THREAD

**Issue by Marsupio** [siacs/Conversations#1986]
In http://xmpp.org/extensions/xep-0045.html we can find that feature

6.3 Discovering Rooms

The service discovery items ("disco#items") protocol enables an entity to query a service for a list of associated items, which in the case of a chat service would consist of the specific chat rooms hosted by the service.

Example 5. Entity Queries Chat Service for Rooms

<iq from='hag66@shakespeare.lit/pda'
    id='zb8q41f4'
    to='chat.shakespeare.lit'
    type='get'>
  <query xmlns='http://jabber.org/protocol/disco#items'/>
</iq>
    

The service SHOULD return a full list of the public rooms it hosts (i.e., not return any rooms that are hidden).

**Comment by andersruneson** [comment]
Feels like this feature request already exist and is still open. Please
have a look and then close this.
