### ISSUE TITLE
League of Legends chat server

### ISSUE THREAD

**Issue by arg2009** [siacs/Conversations#1990]
The League of Legends chat server uses an implementation of ejabberd. I have used Pidgin and Xabber to log in to it and it works fine. 

I am not sure if this is an issue with the server (as I do not have access to the server) or with Conversations but when I attempt to log into the server using Conversations I get an error saying "Stream error".

Again, this may or may not be a Conversations error but I thought I would post it here in case it was. 

#### General information

* **Version:** 1.13.8
* **Device:** Samsung Galaxy Note 3
* **Android Version:** Android 4.4.2
* **Server name:** chat.oc1.lol.riotgames.com
* **Server software:** ejabberd variant
* **Installed server modules:** Unknown
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Add league of legends jabber account as specified on this post: [http://leagueoflegends.wikia.com/wiki/User_blog:Sevenix/Connecting_to_the_LoL_chat_using_XMPP]

#### Expected result

See online contacts is expected. 

Instead the account doesn't successfully log in and says "stream error" in the username field of the account creation screen.

![screenshot_2016-08-17-13-01-36](https://cloud.githubusercontent.com/assets/10524173/17723187/762e50f2-647b-11e6-8a88-c34a75ff5ef3.png)

**Comment by licaon-kter** [comment]
The port is 5223 there and the image shows it truncated, right?

**Comment by arg2009** [comment]
Yes that is correct.

**Comment by iNPUTmice** [comment]
Please provide the adb logcat of an connection attempt. This will give details regarding the stream error.

**Comment by arg2009** [comment]
Ok will do next week. Going away this weekend.

**Comment by arg2009** [comment]
Pardon me. I looked further into Xabber and it also throws a Stream Error when you look up client details. It must be the "variation" that Riot games did to the XMPP protocol.

**Comment by iNPUTmice** [comment]
Might still be interesting to see what adb logcat has to say. Maybe it is
fixable.
