### ISSUE TITLE
Disabling registration

### ISSUE THREAD

**Issue by Marsupio** [siacs/Conversations#1992]
DISALLOW_REGISTRATION_IN_UI (Config.java) disables registration in EditAccountActivity, but it does not in WellcomeActivity. I think DISALLOW_REGISTRATION_IN_UI should be called DISALLOW_REGISTRATION_IN_EDIT_ACCOUNT_ACTIVITY, and there should be another one called DISALLOW_REGISTRATION_IN_WELLCOME_ACTIVITY

**Comment by iNPUTmice** [comment]
You can set the magic create domain to null that will disable the welcome
activity. (there is no point in having it if you want to disallow
registration)

**Comment by Marsupio** [comment]
I think users should still receive a wellcome message first time they run the app.

**Comment by iNPUTmice** [comment]
The settings in Config.java are only meant as customization options for paying customers.
