### ISSUE TITLE
Black theme.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [siacs/Conversations#1993]
I'd like a third theme to be available in settings. The background should be 100% black. Optionally the place where one types in the message could be black, the upper bar containing the contact name and the padlock icon could be black or dark grey. Even these squares with letters (I hate those since I don't use avatars) inside could be made dark grey or black, although a better solution would be to have an option to simply turn them off.

I'm down for as much dark as possible.

Why?
Saves A LOT of battery in phones with AMOLED screens which are more and more popular lately (they are cheaper than IPS now).
Much better for texting in dark places with no external source of light in terms of eye comfort and annoyance given to the surrounding people (who may want to sleep).
Slick design for those that like dark stuff.
Easy to implement.

Thanks!

**Comment by iNPUTmice** [comment]
This is not on our todo list for now. We try to stick to the material
design guidelines.

**Comment by treakiandroid** [comment]
check out cyanogenmod 13, there you have a lot of options like inverting the screen, doing a colour adjustment (like all green) and a modular extendable theme engine...
