### ISSUE TITLE
Feature Request: MarkDown

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#1994]
Bold, italic, underline and cross formats could make a nice interface on Conversations. Also lists would be really appreciatted.

Thanks a lot!!

**Comment by turnovec** [comment]
I'm not sure if it's a good idea. How would the other clients cope with thatM

**Comment by kabili207** [comment]
I think markdown is really only needed as a way of entering HTML formatting, which other clients can already send and receive.

**Comment by 4elta** [comment]
> How would the other clients cope with that?

other clients will just print the format/meta characters, which for markdown are very minimal ... that's the beauty of markdown 😉

eg., instead of **bold** they might display `**bold**`.

i think it's a great idea.

**Comment by tmolitor-stud-tu** [comment]
+1

**Comment by iNPUTmice** [comment]
@tmolitor-stud-tu github has a dedicated +1 feature. You don't have to write an extra comment for that.

**Comment by tmolitor-stud-tu** [comment]
I know, but I didn't have the impression that you are even seeing/considering those +1

**Comment by iNPUTmice** [comment]
Conversations now supports Message Styling (which isn’t really mark down but pretty close to what WhatsApp and Slack are doing as well)
