### ISSUE TITLE
Prevent Android from automatically creating screenshots of the application.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [siacs/Conversations#1995]
As of now in Conversations the screen is captured as an image and saved to disk when the user switches apps or locks the screen. When one triggers the "switch app" view in Android, the screenshot containing private data is visible. This is a privacy and possibly security issue.

Preventing Android from doing this would be appreciated.

Silence and Signal IMs do this, one can perhaps find out the way they do it by looking at their code. I think this option may be a part of Android itself.

**Comment by iNPUTmice** [comment]
Anyone who would possibly be able to get their hands on that screenshot could just as well open the app and get their hands on that 'private' data.
On the other hand this prevents people from making screenshots.

**Comment by gerg5c42g542g2c54g52c** [comment]
This is mentioned in the "Ugly" part of this analysis: https://medium.com/@thegrugq/operational-whatsapp-on-ios-ce9a4231a034

It seems like this is in fact an issue. From what I can think of, these screenshots are then out of control of the application meaning they can be left on device or even be accessible to third-parties after the messages are deleted by the user, even after the app itself is deleted. Perhaps there's more. Looking at WhatsApp example (the SQLite problem), such small things can be very severe issues.

I know it's not a bug in Conversations, but a feature of Android probably added without taking thinking about privacy, but certainly tighter privacy guidelines are a proper objective to aim at.

Ability to prevent oneself from making screenshots could be considered a feature and could be an opt-in/opt-out one.

**Comment by d9h02f** [comment]
I've always been able to take screenshots of Signal, without it ever realising I did so, without even installing any special software. If you can't trust your device to not take screenshots automatically, you can't trust it with anything, and this anti-feature won't help at all.

**Comment by SamWhited** [comment]
I added the option to turn off screenshots in Signal originally; IIRC it was to prevent a very specific type of attack that's probably only relavant to a tiny group of people trying to make sophisticated targeted attacks a bit harder. This is probably not something that's worth fixing in Conversations. The cited blog post is assuming a system that should be as secure as possible against a wide variety of threats at any cost, but this is not the main goal of Conversations (or Signal, really, but this was before it was named Signal and I think people were still figuring out what the app should become), and making it opt-in would just clutter up the settings UI for (possibly) no benefit.

**Comment by Natureshadow** [comment]
Where are these files stores? If they are dumped to /sdcard like regular screenshots, then they are effectively 777 to any other app on the system, as opposed to only the system.

**Comment by gerg5c42g542g2c54g52c** [comment]
@d9h02f It's nice that you could take screenshots of Signal, but Android by itself did not, this is the point.

What is this attack?

I don't see why it shouldn't be a Conversations' goal to be secure.

There's no need to clutter Settings UI, one can put this in Expert settings.

**Comment by d9h02f** [comment]
Again, it adds no security whatsoever. If someone has such far-reaching access to your device that they can record your screen without you even noticing, nothing will help you anymore.

**Comment by licaon-kter** [comment]
This case covers the "apps using the accessibility service and/or screen overlay permission" maybe?

Say "an attacker" installs such an app (without you knowing), that on a trigger/remote/interval make a screenshot.
