### ISSUE TITLE
zwj and zwnj should be allowed in muc nicknames

### ISSUE THREAD

**Issue by pravi** [siacs/Conversations#1996]
With zwj - പ്രവീണ്‍, without zwj - പ്രവീണ്. Its fine inside message. Its pronunciation and display changes with zwj.

Background and relevant standards
http://thottingal.in/blog/2011/01/08/identifiers-in-indic-languages/

**Comment by SamWhited** [comment]
Can you list the exact bytes in UTF-8 encoding for what you're trying to display? Apparently GitHub or my browser or something is normalizing those strings (they are identical for me).

**Comment by pravi** [comment]
Relevant rfcs, 

http://www.rfc-base.org/rfc-6122.html current-old way
https://tools.ietf.org/html/rfc7564 the new way
https://tools.ietf.org/html/rfc7622 obsoletes 6122

**Comment by pravi** [comment]
I have emailed authors of RFC 7564 to consider this change to allow ZWJ and ZWNJ in these contexts.

**Comment by anivar** [comment]
ZWJ is extremely important on Emoji's too 
http://www.unicode.org/emoji/charts/emoji-zwj-sequences.html

**Comment by pravi** [comment]
@anivar , ZWJ works inside normal messages, only nicknames are problematic. I don't know if its important to support emojis inside nicknames.

**Comment by anivar** [comment]
@pravi  thank you for corrcting. I havnt noticed nickname part .  If i am taking my name  അനിവര്‍ in malyalam as nickname ZWJ is essential to shape the last letter . Else itwill be displayed as ആനിവര്

**Comment by SamWhited** [comment]
@pravi Was the example broken before? It appears to be different for me now; anyways, if the zero width joinder is used correctly like it now is (before it was at the end of the word so PRECIS would strip it and it wouldn't be very useful anyways) it should work fine with the PRECIS nickname profile as long as it's used in a way that conforms to the contextj rule of precis.

**Comment by pravi** [comment]
@SamWhited did you use a different browser? I don't know what changed, it was at the end of the word before as well.

 For example,Thottingal, in Malayalam- തോട്ടിങ്ങല്‍ (0D24 0D4B 0D1F 0D4D 0D1F 0D3F 0D19 0D4D 0D19 0D32 0D4D 200D)

and the last 200D (ZWJ) should not be stripped.

From https://wiki.python.org/moin/ZwjAndZwnjAsIdentifiers

```
Allow ZWJ in a conjunct context. That is, a sequence of the form:

    A Letter, followed by a Virama, followed by a ZWJ
    This corresponds to the following regular expression (in Perl-style syntax): /$L $V ZWJ/ where:
        $L= [:General_Category=Letter:] $V = [:Canonical_Combining_Class=Virama:] 
```

So ZWJ should be allowed in this particular context. Same for ZWNJ, (see link above where ZWNJ is allowed)

**Comment by SamWhited** [comment]
The same browser (and version) on two machines; I'm not sure why it's displaying it differently. My mistake with the zwj on the end too; I see what's happening now.

Let me double check the contextj rule and the Nickname profile to make sure my implementation is correct and I'll get back to you.

**Comment by iNPUTmice** [comment]
Conversations now uses a proper JID implementation that should support this. However your server might not.
