### ISSUE TITLE
More user-friendly OTR-decryption failure messages to work around dumb clients

### ISSUE THREAD

**Issue by shtrom** [siacs/Conversations#1998]
#### General information

When receiving OTR-encrypted messages that it cannot decrypt (e.g., old keys, or for another resource), Conversations dumps the OTR-encrypted payload, colours it green, and fires toasts and notifications. A nicer representation of undecipherable messages would be better, along with a prominent way of refreshing the OTR session if desired, as well as a throttling of notifications for encrypted messages (e.g., only one every $x$ minutes regardless on the number of undecipherable messages received).

A very similar issue has already been discussed in #1275. This is not a core issue with Conversations and the root-cause is with other (well, libpurple-based) clients, but leads to substandard experience when chatting with people using those less-abled clients.
- **Version:** eg 1.13.9
- **Device:** Google Nexus 5
- **Android Version:** Android 6.0.1 Cyanogenmod 13.0
- **Server name:** self hosted
- **Server software:** ejabberd
- **Installed server modules:** eg Stream Managment, CSI, MAM
- **Conversations source:** F-Droid
#### Steps to reproduce
1. Start Conversations and another Jabber client for one account
2. Have a libpurple-based client connect to another account
3. Start chatting between the libpurple and the other non-Conversations client
#### Expected result

What is the expected output?

Small red or orange message bubble saying something like

```
An encrypted message from <CONTACT> could not be decrypted.
```

Notifications should only be sent every so often, rather than on every unreadable message.

What do you see instead?

Conversations receives a series of `?OTR:...` messages, display them in green bubbles, and sends notifications.

![screenshot_20160823-154604](https://cloud.githubusercontent.com/assets/160280/17882139/ea0c7b9e-694d-11e6-89f4-c40f7457ea88.png)

**Comment by varac** [comment]
Please fix this soon.

**Comment by iNPUTmice** [comment]
Closing as invalid since OTR has been removed in 2.0.0

**Comment by varac** [comment]
@iNPUTmice I don't understand, this is ignoring the fact that there are other clients out there that try to setup OTR sessions with me.
Presenting the user with lengthy encrypted blobs is user-unfriendly and will turn ppl away from it.
I find this behaviour annoying, and I think it would be an easy fix to detect OTR messages and replace them with a user-friendly message.
I'm not debating the removal of OTR here I'm just trying to improve the UX of conversations.
