### ISSUE TITLE
Bug when MAGIC_CREATE_DOMAIN is set to null

### ISSUE THREAD

**Issue by Marsupio** [siacs/Conversations#2001]
app closes when clicking Up Navigation in Edit Account Activity

**Comment by licaon-kter** [comment]
App version? App source? Device? Android version?

**Comment by Marsupio** [comment]
It does not seem a matter of versions. I tried with different emulated devices and latest version. Action Bar (app bar) is set as navigation but it should not, since there's no other activity to go when MAGIC_CREATE_DOMAIN is set to null

**Comment by iNPUTmice** [comment]
Please provide the stack trace for this. I can not reproduce this.

**Comment by Marsupio** [comment]
Have you checked that you have no account created yet?

**Comment by iNPUTmice** [comment]
Yes

**Comment by Marsupio** [comment]
The Manifest has no parent activity declared in EditAccountActivity. So I don't know how  _Up Navigation_ is implemented. https://developer.android.com/training/implementing-navigation/ancestral.html

**Comment by Marsupio** [comment]
The debugger throws this
    public native Object invoke(Object var1, Object... var2) throws IllegalAccessException, IllegalArgumentException, InvocationTargetException;

Why did you close issue?
