### ISSUE TITLE
Ejabberd throws strange when clients using Conversations connect.

### ISSUE THREAD

**Issue by Ashaman-** [siacs/Conversations#2004]
#### General information

* **Version:** eg 1.13.9
* **Device:** Any
* **Android Version:** Cyanogenmod, SGS 5 AT&T Stock, others
* **Server name:** psyberia.im (my public server)
* **Server software:** ejabberd 16.08, error was present in 16.06 and 16.04, postgresql backend since 16.06, mysql backend before. default_db: sql
* **Installed server modules:** All the things except push app server
* **Conversations source:** eg PlayStore

#### Steps to reproduce
Sign in to ejabberd server from Conversations
Observe in ejabberd log file:
[info] <0.17508.0>@ejabberd_s2s_out:log_s2s_out:1253 Trying to open s2s connection: psyberia.im -> push.siacs.eu with TLS=true
[error] <0.9735.0>@mod_pubsub:transaction_retry:4123 transaction return internal error: {aborted,{badarg,[{erlang,binary_to_list,[null],[]},{str,tokens,2,[{file,"src/str.erl"},{line,242}]},{node_flat_sql,decode_subscriptions,1,[{file,"src/node_flat_sql.erl"},{line,1000}]},{node_pep_sql,'-get_entity_subscriptions_for_send_last/2-fun-0-',1,[{file,"src/node_pep_sql.erl"},{line,184}]},{lists,map,2,[{file,"lists.erl"},{line,1238}]},{node_pep_sql,get_entity_subscriptions_for_send_last,2,[{file,"src/node_pep_sql.erl"},{line,180}]},{mod_pubsub,node_call,4,[{file,"src/mod_pubsub.erl"},{line,4050}]},{ejabberd_sql,execute_bloc,1,[{file,"src/ejabberd_sql.erl"},{line,495}]}]}}

#### Expected result

No error message.

**Comment by iNPUTmice** [comment]
This question belongs into the ejabberd muc.
