### ISSUE TITLE
setting up conversation with ejabbered on local

### ISSUE THREAD

**Issue by johnnyAnd** [siacs/Conversations#2005]
#### General information

* **Version:** eg 1.12.2
* **Device:** eg Google Nexus 5
* **Android Version:** 5.0
* **Server name:** self hosted
* **Server software:** ejabberd 16.08
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** F-Droid

#### Steps to reproduce

1. I have installed ejabbered on my window 7 machine, which appear to works fine, I start it and open the front page, I give it an admin password while installation, my admin page is at localhost:5840/admin
2. Now I open the conversation app and tap on USE MY OWN PROVIDER, I enter the address like admin@{SERVER-NAME} normally in case of ejabbered it is Pc -name

when i tap next, it says server not found, I also tried to change the server-name to my ip, 192.xxxxxx..xxx

Am i missing something ?

#### Expected result

It should connect to my xmpp client .

Do we need public IP or address to run a xmpp server ? cant we test this on localhost or private IPs (of course it wont be accessible to whole world )

Thanks

**Comment by iNPUTmice** [comment]
Your local DNS server probably doesn't resolve {SERVER-NAME}. You can either make your local dns server resolve that name correctly or in Conversations go to settings -> expert settings -> show extended connection options. 
And the back in the account screen you can enter the jid as admin@server-name and specify the IP in the host field.

**Comment by johnnyAnd** [comment]
@iNPUTmice I tried that , but still it is giving server not found error.

**Comment by iNPUTmice** [comment]
Maybe there is a firewall preventing you from accessing your computer from your mobile phone.

**Comment by johnnyAnd** [comment]
@iNPUTmice "Your local DNS server probably doesn't resolve {SERVER-NAME}" , what does that mean exactly ? do I have to resolve this at router level or it is related to host file in widows ?

also is there any log ? I have disabled firewall.

**Comment by johnnyAnd** [comment]
@iNPUTmice 

this is my log

2016-09-10 01:36:26.003 [info] <0.490.0>@ejabberd_listener:accept:333 (#Port<0.24824>) Accepted connection 192.168.100.6:36411 -> 192.168.100.14:5280
2016-09-10 01:36:26.003 [info] <0.508.0>@ejabberd_http:init:158 started: {gen_tcp,#Port<0.24824>}
2016-09-10 01:37:56.909 [info] <0.490.0>@ejabberd_listener:accept:333 (#Port<0.24825>) Accepted connection 192.168.100.6:59785 -> 192.168.100.14:5280
2016-09-10 01:37:56.909 [info] <0.511.0>@ejabberd_http:init:158 started: {gen_tcp,#Port<0.24825>}

nothing happens after it

**Comment by iNPUTmice** [comment]
Please ask your questions in our conference conversations@conference.siacs.eu. This is a more appropriate place to ask questions than our bug tracker. Which is for bugs only.

5280 doesn't look like the right port to me. (Unless you explicitly configured c2s to listen on that port)

**Comment by johnnyAnd** [comment]
@iNPUTmice  well 
1 -this ofcourse is a bug if it is not connedting but showing connection accepted 
2- one bug is already in which we have to create admin user from app again to make it working from server. (that will be done in next release)

I tried to email at above address you mentioned but it failed

**Comment by iNPUTmice** [comment]
@johnnyAnd It's not an email address but a MUC, a XMPP chat room. You need an XMPP account on a server connected to the internet to join.

**Comment by licaon-kter** [comment]
@johnnyAnd Use Conversations to join that MUC, it's not an e-mail address.

**Comment by johnnyAnd** [comment]
@licaon-kter alright, but accessing this over mobile and pasting logs etc will be mess. just saying.

**Comment by johnnyAnd** [comment]
@licaon-kter  have you tried conversations on windows 7 with 16.08 jabber ?

**Comment by licaon-kter** [comment]
No

**Comment by mos3b2001** [comment]
Hello,
I have installed Prosody server  on my Debian machine, and build conversation IM in android studio, also I have  local DNS server probably  resolve {SERVER-NAME}. when I enter the address like admin@{SERVER-NAME}  the client display "stream error"
please help me?

**Comment by licaon-kter** [comment]
Please join the support conference, see the Readme.
