### ISSUE TITLE
disabled and deleted accounts still get messages

### ISSUE THREAD

**Issue by silberzwiebel** [siacs/Conversations#2006]
#### General information

* **Version:** 1.14.0
* **Device:** Motorola Defy+
* **Android Version:** Android 4.4. Cyanogenmod
* **Server name:**  self hosted
* **Server software:** prosody 0.10 
* **Installed server modules:** Stream Managment, CSI, MAM, PEP, ...
* **Conversations source:** F-Droid

When I disable an account temporarily I still get notifications and the corresponding messages that were sent to this account. While this might be okay (and I guess after the smacks timeout I won't get any messages anymore), this is at least surprising and one might think that deactivating an account does not do anything.
What bothers me more is: When I delete an account, I still get the messages for the deleted account (at least messages send directly after deleting the account.) 

#### Steps to reproduce

Create an account in Conversations that already exist on the server. Delete or disable the account. Send a message to the deleted account with another client.

#### Expected result

Expected: The message is not shown in Conversations.
Actual Result: The message is shown in Conversations.

#### Debug output

Sorry, no time for this at the moment. If really needed, I can deliver this later.

**Comment by iNPUTmice** [comment]
I can't replicate that bug (and I doubt many people can). This is a very essential part of the software that I'm sure gets used fairly regular. If that bug where to happen on a broader scale I'm sure somebody would have complained about it before. So we'll definitely  need a logcat for that.

**Comment by silberzwiebel** [comment]
I couldn't replicate the bug with a newly created test account neither. 
But it still exists for my normal user account:
To reproduce the bug I was online with gajim with two accounts, and online with conversations with only one account. I send a message with account 2 (on a different server) to the active account in conversations. Then I deactivated this account in Conversations and send another message. I saw a notification and the message in Conversations. (The account disabled in conversations was online all the time in gajim. I reproduced the bug, however, also with the account being offline in gajim.)
[I've recorded an anonymized log of this procedure (hopefully everything that is needed is in there.)](https://gist.github.com/anonymous/7a57fd710e1e1ebf0843176c481d9e0a)
I think the line at 16:35:16 denotes the message that I received although the account was deactivated (it is the same time in gajim for sending the message.)

**Comment by iNPUTmice** [comment]
416481bb656c5fc73d0500b09a0c4ec62590dc00 might address this

**Comment by silberzwiebel** [comment]
Is this already in the release 1.14.1? Should I try if I can reproduce the bug with 1.14.1?

**Comment by iNPUTmice** [comment]
Yes this is part of the 1.14.1 release

**Comment by silberzwiebel** [comment]
I couldn't reproduce with 1.14.1, so I guess this is fixed. Thank you!
