### ISSUE TITLE
No self-avatar picture

### ISSUE THREAD

**Issue by Sec42** [siacs/Conversations#2008]
I have a picture for myself published on my jabber server (with a different client), but conversations does not pick it up, and shows myself still as an ugly letter.

Other people can see my avatar just fine.

It would be great if there was any way to get a picture in there for myself.

#### General information

* **Version:** 1.13.4
* **Server name:** jabber.ccc.de
* **Conversations source:** F-Droid

**Comment by milaq** [comment]
unfortunately, not fixed in  1.14.9

same problem as mentioned above.
has been a problem from the very beginning. always happens when starting from a fresh conversations deployment.

republishing avatar spits out an error message "The server rejected your publication".
Nothing of interest in logcat.

**Comment by iNPUTmice** [comment]
@milaq this is most likely not the same issue. It looks like your server doesn't support PEP. (Or it's implementation is broken)

**Comment by milaq** [comment]
thanks for your fast reply.

vcard image is set and readable via all kind of clients but doesn't seem to get pulled.
using ejabberd 16.09 with mod_pubsub configured with "pep" plugin; publishing avatar worked in the past with conversations.
also nothing in the server logs.

**Comment by iNPUTmice** [comment]
> vcard image is set and readable via all kind of clients but doesn't seem to get pulled.

It can only get pulled if you are logged in with another client that annouces the hash of the vcard avatar in its presence.

**Comment by milaq** [comment]
> It can only get pulled if you are logged in with another client that annouces the hash of the vcard avatar in its presence.

i understand.
will try once back in office.

reg. pep [maybe out of the scope of this issue]:
still, i am quite wondering why the publishing worked and now it doesn't anymore. i didn't change anything in the server's configuration. is this a common problem with ejabberd instances?
