### ISSUE TITLE
No way to see or choose other users' resource

### ISSUE THREAD

**Issue by legovini** [siacs/Conversations#2010]
In Conversations I found no way to see (or choose) the XMPP resource of another user.
Is it a choice not to implement it, or is Conversations still lacking the feature?
I'm using 1.14.0 from f-droid.

**Comment by iNPUTmice** [comment]
You will be asked for the device to contact when ever it is necessary. Ie when ever the message you are sending can only be sent to one particular device. For example everything OTR encrypted or file transfers if you don't use HTTP upload

**Comment by legovini** [comment]
What if I want to change the destination device, for example if the other user has two clients using OTR, and I want to switch from one to the other?

**Comment by iNPUTmice** [comment]
If a new device comes online you will be asked again. If your contact switches the device and sends you OTR messages from the other device your session will switch to the new device.
If you want to switch devices right in the middle of something without your contact initiating this you have to send an unencrypted message in between or briefly end the conversations by swiping it away and reopening it.
