### ISSUE TITLE
Google's DNS in de.measite.minidns

### ISSUE THREAD

**Issue by herbert777** [siacs/Conversations#2012]
Version: 1.14.0
Conversations source: self build (latest HEAD)

It's not properly speaking an issue but I just wanted to let you guys know that google's DNS are in minidns-0.1.7.jar. Some people may not care about it, but I'm sure that some do.
The DNS aren'in the source code, but they are present in the compiled version since they have been incorporated by minidns-0.1.7.jar during build.
For those interested they are located in:
Conversations-1.14.0-free-release-unsigned-disasm\smali\de\measite\minidns\Client.smali
Change the values with whatever suits you or even better, edit them directly in minidns-0.1.7.jar so that you'll be OK if you build the app again...

**Comment by iNPUTmice** [comment]
They might be in that libray but they don't get used in Conversations.
