### ISSUE TITLE
Trust server certificate option

### ISSUE THREAD

**Issue by Marsupio** [siacs/Conversations#2016]
It seems experts option _don't trust server CA_ is activated by default but tick box is unmarked

**Comment by iNPUTmice** [comment]
What makes you think that?

**Comment by Marsupio** [comment]
I get warnings when I first connect to server with a new user, so i need to manually accept unknown server certificate. But tick box is unmarked.

**Comment by iNPUTmice** [comment]
What server? Is the certificate signed by a CA that is recognized by your system?

**Comment by Marsupio** [comment]
It is signed by StartCom

**Comment by iNPUTmice** [comment]
What does xmpp.net has to say about your server?

**Comment by Marsupio** [comment]
Could you tell me how to know that?

**Comment by licaon-kter** [comment]
https://xmpp.net/ -> enter server address -> Check?

**Comment by Marsupio** [comment]
It says grade T

**Comment by licaon-kter** [comment]
More details?

**Comment by Marsupio** [comment]
I was mistaken, it is self-signed. I guess that with a StartCom cert there would be no warning

**Comment by Marsupio** [comment]
Excuse me, i have a question. Since i want the app to connect only to a especific list of XMPP servers in a local area network, how could i bypass server certificate check?
