### ISSUE TITLE
Can't connect to Facebook

### ISSUE THREAD

**Issue by JimmyS83** [siacs/Conversations#2021]
Hello,

I cant connect to facebook. I have my username on FB, and I tried either username, or my own email used to register at facebook, nothing works :(  I am using Trillian, and he is still able to connect to FB using XAMPP (but seems to me, he uses my own email as username though), so that API still should work..

#### General information

* **Version:**  1.14.1
* **Device:**  LG L90
* **Android Version:** 4.0 stock
* **Server name:** facebook
* **Server software:** chat.facebook.com
* **Installed server modules:** N/A
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Find username from FB:  xxx.yyy in my case
2. Find your reg. email to FB:  xxx.yyy@zzz.zz in my case
3. Try to connect on hostname chat.facebook.com, port 5222
  a) Tried only FB username: xxx.yyy   - Conversations doesnt allow me to do that, not valid Jabber ID
  b) Tried FBusername@chat.facebook.com   - doesnt sign in
  c) Tried my own reg. email: xxx.yyy@zzz.zz  - certificate pops out and ask something about certificate, that its not valid for zzz.zz but for chat.facebook.com and ask me, if it could proceed.  When click Once, still, doesnt sign in :(

#### Expected result

Login to chat.facebook.com via 5222 XAMPP service

#### Debug output
N/A at this time

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
There won't be any affords from our side to bring back facebook support. If that's even possible. Feel free to look at this yourself and if you find anything I'm happy to merge a PR.
We never set out to support Facebook.
You might want to look at transports.

**Comment by JimmyS83** [comment]
Ah.. I was thinking that FB use XAMPP protocol (found threads about chat.facebook.com username for pidgin etc.)
