### ISSUE TITLE
RFE: Ignore messages from people not in my contact list

### ISSUE THREAD

**Issue by tradej** [siacs/Conversations#2022]
#### General information

* **Version:** 1.13.6
* **Device:** Moto G 4G
* **Android Version:** Cyanogenmod 13
* **Conversations source:** F-Droid

Hi, can we have an option to ignore messages from people not in my contact list? I get spammed like crazy by Russian spambots (at least one notification every 20 minutes), so it's a life saver for me. Thanks.

**Comment by iNPUTmice** [comment]
The only way to do this properly right now is to use [XEP-0016: Privacy Lists](http://xmpp.org/extensions/xep-0016.html). However the XEP is way too complex to provide a sane user interface for this. And there have been thoughts to deprecate the XEP. For this reason there won't be any implementation in Conversations any time soon.
However if you want this setting permanently it is fairly straight forward to enter into an XML console. I suggest you do that. Maybe we can write down the steps needed for that in a central place.

I might add a notification setting to not notify on messages from people not in your contact list.

**Comment by iNPUTmice** [comment]
Create a new list that blocks messages and IQs (but not new subscription requests) from users not in your roster.
````
<iq from='romeo@example.net/orchard' type='set' id='msg3'>
<query xmlns='jabber:iq:privacy'>
  <list name='block-all-non-subscription'>
    <item type='subscription'
          value='none'
          action='deny'
          order='1'>
      <message/>
    </item>
  </list>
</query>
</iq>
````

And then set this list as your default list:
````
<iq from='romeo@example.net/orchard' type='set' id='default1'>
<query xmlns='jabber:iq:privacy'>
  <default name='block-all-non-subscription'/>
</query>
</iq>

````

I haven't tested this but this should do the trick.

**Comment by krushmp** [comment]
Privacy Lists seems like the right fit for me too. Would you please consider it as a conversations plug-in?  This allows for informed consent extension of interface complexity.   

🎉

**Comment by iNPUTmice** [comment]
@jkufner I believe the first three actions don't do anything. Default is allow and with no other deny action you can just rely on the last subscription=none deny action.

Incorporating this into Conversations in a feasible manner doesn't seem possible though right.
