### ISSUE TITLE
Check if Freelab Messenger complies to the GPL

### ISSUE THREAD

**Issue by krushmp** [siacs/Conversations#2024]
https://play.google.com/store/apps/details?id=cc.freelab.messenger 

Is this a legitimate use of your license for conversations?

**Comment by licaon-kter** [comment]
It's someone boasting 2004-2016 on that LoreIpsum ridden home page.

**Comment by iNPUTmice** [comment]
I actually don't know. I can't download it from my country and check if my copyright notice and the GPL license information is still available. Usually in the settings under version. Maybe someone else can check?

**Comment by licaon-kter** [comment]
S/he just changed the title and the default server.
The About screen mentions you. :-|

**Comment by iNPUTmice** [comment]
I checked myself by getting the APK from somewhere else.

**Comment by licaon-kter** [comment]
So this is closed because it complies or?

**Comment by iNPUTmice** [comment]
No it doesn't comply in my opinion. But that's not something that needs to
be dealt with on the Conversations issue tracker.
