### ISSUE TITLE
Give user notification when sendind a message failed

### ISSUE THREAD

**Issue by ni720** [siacs/Conversations#2025]
Hello!

Often when I just send a message and minimize the app I do not verify if the message has been sent.
When I check back after hours only then I see, that the message has not been sent, because it failed.

This can be very annoying. So I think the user should get a notification, that the sending of the message has failed.

Thx.

**Comment by fuelflo** [comment]
+1

**Comment by iNPUTmice** [comment]
duplicate of #229 (and others)
TLDR: The recipients server should make sure that this doesn't happen.
