### ISSUE TITLE
Feature request: Quoting messages

### ISSUE THREAD

**Issue by Lykos153** [siacs/Conversations#2032]
Telegram is able to add a quotation to a new message, which I find a decent feature. It's a very convenient way to reply to earlier questions after the conversation has developed into another direction or when confronted with several offline messages after going online again.

I'm not sure if the XMPP protocol already has a solution for this. I read something about threads, but that might be something different. However, it could be achieved email-style with a line prefix such as

```
> quoted message
reply
```

which could be easily detected by Conversations as well as by humans whose client doesn't support this feature. What do you think?

**Comment by Natureshadow** [comment]
I do this all the time. Simply right-click (long-press…) the message, copy it, and paste it behind a "> " character you typed in the message box.

A "Quote" shortcut would maybe be nice, but somehow this is not so much of a fuzz when doing it manually.

**Comment by bastlwasti** [comment]
I also regularly want this. It would be nice to have something to put in the clipboard the text and the "-quotation marks back and forth and maybe a "user X said at xx:xx:xx that:"blabla". 

This can be done manually so nicely...

**Comment by alexara** [comment]
This FR has been implemented by https://github.com/siacs/Conversations/pull/2127.
