### ISSUE TITLE
feature request: app pin

### ISSUE THREAD

**Issue by treakiandroid** [siacs/Conversations#2034]
hi,

could you add an Option to secure the app access with a pin like Threema dose it.

thanks

**Comment by d9h02f** [comment]
Encrypt your device, much better solution.

**Comment by matthaab** [comment]
Database encryption like Signal or Chatsecure would be nice!

**Comment by iNPUTmice** [comment]
An individual app should not replicate something the operating system already does quite well.

**Comment by treakiandroid** [comment]
thanks for the reply, its not about encryption, my device is already encrypted, its meant as an additional security level when you giving out your phone to someone who is to much curious. For example he or she is supposed to read that articel on the www or whatch that video but instead is reading your chat messages. So the normal display unlock pattern dosnt aply here. 

So i and my friends do have the opinion that this feature is important, so if you dont think so ask other peoples manny think that such feature is good to have. And apps like owncloud and threema sure have a reason to have such a feature implemented. thanks

**Comment by matthaab** [comment]
An individual app shoud ne as secure as possible by itself!
Don't trust in other things too much. 
Signal did that the right way.

**Comment by treakiandroid** [comment]
sorry, what do you mean with " shoud ne as "? thanks

**Comment by iNPUTmice** [comment]
>  For example he or she is supposed to read that articel on the www or whatch that video but instead is reading your chat messages. So the normal display unlock pattern dosnt aply here. 

That's whats App Pinning or the User switcher are for.

> An individual app shoud ne as secure as possible by itself!
Don't trust in other things too much. 

There are other closed issues that explain why encrypting the database is completely useless. Just because another App does this doesn't mean it makes sense security wise.

**Comment by d9h02f** [comment]
If you give someone you don't trust access to your device in any way, you've already lost.

**Comment by matthaab** [comment]
But it makes a lot of sense security wise.
I want the database of a secure app to be encrypted with another layer of encrytion than the phone storage. It IS more secure in some use cases.
@d9h02f: you can argue that you've already lost if you use an smartphone. But that is not the use case.

**Comment by matthaab** [comment]
https://guardianproject.info/code/sqlcipher/

**Comment by Natureshadow** [comment]
I absolutely agree with @iNPUTmice here.

Do not give others access to your user session, and secure that user session.

Single apps adding another level of authentication, encryption, whatever is slow and unnecessary.

**Comment by matthaab** [comment]
Don,t tell users how to use their smartphones.
Every app sould be as secure as possible on it's own.

**Comment by d9h02f** [comment]
You gravely misunderstand security.

**Comment by matthaab** [comment]
I don't think so.

**Comment by orlyjamie** [comment]
"Do not give others access to your user session."

It's all about perspective bro, its a bit different when you get your door kicked in or get your shit taken at a border checkpoint. 

Juzzz sayin...

@ghost account deleted, looks like one of the above might have happened to him
