### ISSUE TITLE
Omemo priority failure

### ISSUE THREAD

**Issue by mray** [siacs/Conversations#2036]
#### General information

* **Version:**  1.14.3
* **Device:** Google Nexus 5
* **Android Version:**  Cyanogenmod 13
* **Server name:** jabber.org
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Setup: 2 accounts (A/B), both using mobile(Conversations) and desktop(Gajim)  + OMEMO encryption
2. Send message from account A/Gajim or A/conversations only appears on A/Gajim, A/conversations, B/Gajim -  *NOT* B/conversations!!!
3. Send message from account B to A works fine, all 4 devices receive the message.
4. When explicitly sending the message to the specified resource via Gajim B/conversations *GETS* the message!  

#### Expected result

All four devices should always get every message. 

Is there a way to set the priority in conversations? It currently is displayed as "0" in gajim.

**Comment by iNPUTmice** [comment]
Looks to me like your server doesn't support Carbon Messages.

**Comment by mray** [comment]
I'm sorry to tell you: You are right!
@jabber.org does in fact not support "XEP 0280"Message Carbons" - what a **shame!**
Why is that? I'm baffled. It is *their* protocol. I can see how they don't want to offer transports but this...?!

Thanks for the help!
