### ISSUE TITLE
Omemo not working after restoring conversations from backup

### ISSUE THREAD

**Issue by dicer** [siacs/Conversations#2038]
#### General information

* **Version:** 1.14.3
* **Device:** Motorola Droid 4
* **Android Version:** Cyanogenmod 13
* **Server name:** self hosted
* **Server software:** ejabberd 14.07-4+deb8u3
* **Installed server modules:**
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Damage your phone so you need to get a new one
2. Restore backup from 17 days ago
3. Send OMEMO message to an existing contact

#### Expected result

The message is sent, but the green tick is never added. Messages by that contact are also never shown on my device. Sending unencrypted messages to that contact works.
I'm suspect that the published keys don't have a matching private key anymore cause I had to restore the backup. Switching to unencrypted on both sides works, but does not make omemo work after again.

Is there a way I can clear the prekeys either on the server or in the conversations DB? I definitely want to keep my chat history.

#### Debug output

09-26 13:50:56.974  5816  5834 D conversations: restoring roster
09-26 13:50:57.014  5816  5816 D conversations: update unread count to 0
09-26 13:50:57.050  5816  5816 D conversations: schedule next idle ping
09-26 13:50:57.141  5816  5837 D conversations: me@myserver: socket was null during force close
09-26 13:50:57.142  5816  5837 D conversations: me@myserver: connecting
09-26 13:50:57.184  5816  5837 D conversations: used lollipop variant to discover dns servers in 1 networks
09-26 13:50:57.184  5816  5837 D conversations: using dns server: 193.189.244.206 to look up myserver
09-26 13:50:57.255  5816  5816 D conversations: app switched into foreground
09-26 13:50:57.673  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:1
09-26 13:50:57.674  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:2
09-26 13:50:57.674  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:3
09-26 13:50:57.674  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:4
09-26 13:50:57.674  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:5
09-26 13:50:57.674  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:6
09-26 13:50:57.674  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:7
09-26 13:50:57.674  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:8
09-26 13:50:57.674  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:9
09-26 13:50:57.674  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:10
09-26 13:50:57.674  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:11
09-26 13:50:57.677  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:12
09-26 13:50:57.677  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:13
09-26 13:50:57.677  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:14
09-26 13:50:57.677  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:15
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:16
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:17
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:18
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:19
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:20
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:21
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:22
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:23
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:24
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:25
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:26
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:27
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:28
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:29
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:30
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:31
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:32
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:33
09-26 13:50:57.678  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:34
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:35
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:36
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:37
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:38
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:39
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:40
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:41
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:42
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:43
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:44
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:45
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:46
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:47
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:48
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:49
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:50
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:51
09-26 13:50:57.679  5816  5834 D conversations: AxolotlService (me@myserver): Got Axolotl signed prekey record:52
09-26 13:50:57.683  5816  5834 D conversations: AxolotlService (me@myserver): Building session for remote address: me@myserver:119077737
09-26 13:50:57.865  5816  5834 D conversations: AxolotlService (me@myserver): Building session for remote address: otheraccount@myserver:390332815
09-26 13:50:57.866  5816  5834 D conversations: AxolotlService (me@myserver): Building session for remote address: otheraccount@myserver:1180890676
09-26 13:50:57.906  5816  5834 D conversations: restoring messages
09-26 13:50:57.908  5816  5832 D conversations: start merging phone contacts with roster
09-26 13:50:57.909  5816  5832 D conversations: finished merging phone contacts
09-26 13:50:58.968  5816  5837 D conversations: me@myserver: using values from dns xmpp.myserver[x.xx.x.xxx]:5222 tls: false
09-26 13:51:03.107  5816  5837 D conversations: me@myserver: TLS connection established
09-26 13:51:03.214  5816  5837 D conversations: me@myserver/mobile: Authenticating with SCRAM-SHA-1
09-26 13:51:03.780  5816  5837 D conversations: me@myserver: logged in
09-26 13:51:03.897  5816  5834 D conversations: update unread count to 1
09-26 13:51:03.900  5816  5834 D conversations: restored all messages
09-26 13:51:04.677  5816  5837 D conversations: me@myserver: sending legacy session to outdated server
09-26 13:51:04.763  5816  5837 D conversations: me@myserver: starting service discovery
09-26 13:51:04.827  5816  5837 D conversations: me@myserver: server caps came from cache
09-26 13:51:04.859  5816  5837 D conversations: me@myserver: stream management(3) enabled (resumable)
09-26 13:51:05.417  5816  5837 D conversations: me@myserver: Requesting block list
09-26 13:51:05.956  5816  5837 D conversations: me@myserver: successfully enabled carbons
09-26 13:51:05.970  5816  5837 D conversations: Received blocklist update from server
09-26 13:51:06.810  5816  5837 D conversations: AxolotlService (me@myserver): Bundle 315808133 in PEP was current
09-26 13:51:06.810  5816  5837 D conversations: AxolotlService (me@myserver): Announcing device 315808133
09-26 13:51:07.017  5816  5837 D conversations: unknown error in conference: <presence from="testroom@conference.myserver/Me" xmlns="jabber:client" type="unavailable" to="me@myserver/mobile"><status xmlns="jabber:client">Replaced by new connection</status><x xmlns="http://jabber.org/protocol/muc#user"><item xmlns="http://jabber.org/protocol/muc#user" role="none" jid="me@myserver/mobile" affiliation="owner"/><status xmlns="http://jabber.org/protocol/muc#user" code="110"/><status xmlns="http://jabber.org/protocol/muc#user" code="100"/></x></presence>
09-26 13:51:07.908  5816  5837 D conversations: me@myserver: online with resource mobile
09-26 13:51:07.908  5816  5837 D conversations: me@myserver: fetching roster
09-26 13:51:14.810  5816  5837 D conversations: me@myserver: joining conversation testroom@conference.myserver/Me
09-26 13:51:14.812  5816  5837 D conversations: me@myserver: fetching members for testroom
09-26 13:51:14.812  5816  5837 D conversations: me@myserver: fetched muc configuration for testroom@conference.myserver - [vcard-temp, http://jabber.org/protocol/muc, muc_hidden, muc_persistent, muc_membersonly, muc_nonanonymous, muc_moderated, muc_unsecured]
09-26 13:51:15.339  5816  5837 D conversations: AxolotlService (me@myserver): Received PEP device list update from me@myserver, processing...
09-26 13:51:15.339  5816  5837 D conversations: AxolotlService (me@myserver): Received non-empty own device list. Resetting publish attempts and pepBroken status.
09-26 13:51:15.841  5816  5837 D conversations: me@myserver: retrieved members for testroom@conference.myserver: []

Test message 1:

09-26 13:51:54.832  5816  5816 D conversations: AxolotlService (me@myserver): Finding devices without session for otheraccount@myserver
09-26 13:51:54.832  5816  5816 W conversations: AxolotlService (me@myserver): Have no target devices in PEP!
09-26 13:51:54.835  5816  5816 D conversations: AxolotlService (me@myserver): Cache miss: b2fe27c6-ba58-4bfe-8ddf-fe12d664abb8
09-26 13:51:54.840  5816  5846 D conversations: AxolotlService (me@myserver): Building axolotl foreign keyElements...
09-26 13:51:54.840  5816  5846 V conversations: AxolotlService (me@myserver): otheraccount@myserver:1180890676
09-26 13:51:54.937  5816  5846 V conversations: AxolotlService (me@myserver): otheraccount@myserver:390332815
09-26 13:51:54.971  5816  5846 D conversations: AxolotlService (me@myserver): Building axolotl own keyElements...
09-26 13:51:54.971  5816  5846 V conversations: AxolotlService (me@myserver): me@myserver:119077737
09-26 13:51:54.975  5816  5846 D conversations: AxolotlService (me@myserver): Generated message, caching: b2fe27c6-ba58-4bfe-8ddf-fe12d664abb8
09-26 13:51:54.976  5816  5846 D conversations: AxolotlService (me@myserver): Cache hit: b2fe27c6-ba58-4bfe-8ddf-fe12d664abb8

Test message 2:

09-26 13:52:03.304  5816  5816 D conversations: AxolotlService (me@myserver): Finding devices without session for otheraccount@myserver
09-26 13:52:03.304  5816  5816 W conversations: AxolotlService (me@myserver): Have no target devices in PEP!
09-26 13:52:03.306  5816  5816 D conversations: AxolotlService (me@myserver): Cache miss: 53a90c0b-b2f0-41f0-b49c-d075a63fb3ce
09-26 13:52:03.307  5816  5846 D conversations: AxolotlService (me@myserver): Building axolotl foreign keyElements...
09-26 13:52:03.307  5816  5846 V conversations: AxolotlService (me@myserver): otheraccount@myserver:1180890676
09-26 13:52:03.364  5816  5846 V conversations: AxolotlService (me@myserver): otheraccount@myserver:390332815
09-26 13:52:03.439  5816  5846 D conversations: AxolotlService (me@myserver): Building axolotl own keyElements...
09-26 13:52:03.439  5816  5846 V conversations: AxolotlService (me@myserver): me@myserver:119077737
09-26 13:52:03.440  5816  5846 D conversations: AxolotlService (me@myserver): Generated message, caching: 53a90c0b-b2f0-41f0-b49c-d075a63fb3ce
09-26 13:52:03.442  5816  5846 D conversations: AxolotlService (me@myserver): Cache hit: 53a90c0b-b2f0-41f0-b49c-d075a63fb3ce

Message from contact:
09-26 13:38:23.250  4309  5547 I conversations: AxolotlService (me@myserver): WhisperMessage received
09-26 13:38:23.299  4309  5547 W conversations: AxolotlService (me@myserver): Error decrypting axolotl header, org.whispersystems.libaxolotl.InvalidMessageException: No valid sessions.

**Comment by iNPUTmice** [comment]
If you have root access on your device you can just clear all axolotl tables from the internal database. If not you are out of luck.

**Comment by licaon-kter** [comment]
Cyanogenmod 13 means root access available. ;)

**Comment by dicer** [comment]
Yeah, I got root.
So what I tried so far:
1. Deleted all the pubsub tables/files from ejabberd (in /var/lib/ejabberd/)
This did not prove successful, but now I'm at least sure all the prekeys in pubsub are valid.

2. Killed conversations and did "sqlite3 history":
delete from prekeys;
delete from sessions;
delete from signed_prekeys;

Now I can't select omemo as encryption method for the contact anymore. I am on a train with bad reception though and remember that it took a while to show up when first using it. So I'll wait till tomorrow and report back here.

Any table I missed?
Is there any way to kill a session through the GUI? Would be a rather helpful option for the expert settings, wouldn't it? Or something like "Reset all omemo keys/sessions"?

**Comment by dicer** [comment]
Thanks for the expert option!
Wouldn't it also be helpful to show the invalid session in the GUI?
Currently messages get lost if there is no session. I'm talking about
this warning in the log, which does not show up in the GUI in any way:
09-26 13:38:23.299 4309 5547 W conversations: AxolotlService
(me@myserver): Error decrypting axolotl header,
org.whispersystems.libaxolotl.InvalidMessageException: No valid sessions.
