### ISSUE TITLE
There is no way to set the connect server

### ISSUE THREAD

**Issue by alaricd** [siacs/Conversations#2040]
There is no way to change the connect server, or disable SRV lookups.

#### General information

* **Version:** eg 1.12.2
* **Device:** eg Google Nexus 5
* **Android Version:** eg Android 6.0 Stock or Android 5.1 Cyanogenmod
* **Server name:** eg conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
Yes there is: https://github.com/siacs/Conversations/blob/master/README.md#where-can-i-set-up-a-custom-hostname--port
