### ISSUE TITLE
Underlined text

### ISSUE THREAD

**Issue by gmendrala** [siacs/Conversations#2041]
#### General information

* **Version:** the latest
* **Device:** LG G5
* **Android Version:** eg Android 6.1..

#### Steps to reproduce

Why are classic text underlined? You can see on the image [https://s21.postimg.org/s17d9c3bb/Screenshot_2016_09_28_19_41_27_edit.png](https://s21.postimg.org/s17d9c3bb/Screenshot_2016_09_28_19_41_27_edit.png)? Links works OK.

**Comment by iNPUTmice** [comment]
Androids URL pattern matching recognizes anything with a dot in it as a domain.

**Comment by gmendrala** [comment]
Ok, and is possible fixed or "feature"? :-) Whatsapp is ok for example (same text).
