### ISSUE TITLE
Messages sent a whule before contact goes offlibe are silently dropped.

### ISSUE THREAD

**Issue by marmistrz** [siacs/Conversations#2042]
#### General information

* **Version:** 1.14.4
* **Device:** OnePlus 3
* **Android Version:** CM 13.0
* **Server name:** swissjabber.org
* **Server software:** according to xmpp.net, Prosody 0.9.10
* **Installed server modules:** unknown
* **Conversations source:** F-Droid

#### Steps to reproduce

Alice sends a message to Bob while Bob is still online. Bob turns off wifi before the message reaches him.

#### Actual result
Bob never receives the message. Alice sees the date below the message and a padlock indicating encryption but no green tick indicating delivery.

#### Expected result

Messege is delivered to Bob when he connects to Internet the next time. Alice sees that the message is awaiting delivery until then.

#### Debug output

I don't currently have access to another Android device. Let me know if it's still needed, I'll find a way to get the log.

#### Additional information
Using OTR encryption. 

It's a big problem, since 
the delivery reports are turned off by default so Alice will thing Bob has received the message.

**Comment by licaon-kter** [comment]
The server is your problem, look here: https://gultsch.de/compliance.html
More green means better, your problem is that the server does not support **XEP-0313: Message Archive Management**

Either contact them, point the to the table so maybe the fix it, else better look at a different server, those with all-green lines are better.

/close as invalid

**Comment by marmistrz** [comment]
Thanks!

Which XMPP server software can be used to provide all the features mentioned in the compliance link?
-- 
Marcin

**Comment by licaon-kter** [comment]
Both prosody and ejabberd support all the needed features (in modules).

**Comment by marmistrz** [comment]
Thanks!
