### ISSUE TITLE
Boot Conversations is very slow

### ISSUE THREAD

**Issue by geniewin** [siacs/Conversations#2043]
#### General information

* **Device: HUAWEI P9 PLUS
* **Android Version: Android 6.0 

Boot Conversations is very slow, need 10 seconds
But my other old mobile phone starts quickly, it only takes 2 seconds.
The performance of the new cell phone is better than that of the old one, but the new cell phone is not NFC.
Do not know what is the reason led to the start of the new mobile phone Conversations slow down

**Comment by iNPUTmice** [comment]
define boot.

**Comment by iNPUTmice** [comment]
no reaction from op. closing.
