### ISSUE TITLE
Inserting image results in double message

### ISSUE THREAD

**Issue by bastlwasti** [siacs/Conversations#2045]
#### Steps to reproduce
1. Sometimes it happens that when I want to insert a photo, the camera app opens, then I click to make the photo, and the photo app disappears, but in Conversations 2 photos are inserted. And it seem to be the same photo.
#### Expected result

But if I take one photo, there should be only one photo inserted, right? :-)
It seems to be the fault of Conversations because when i delete on of those two photos, not one photo is deleted but both of them!!

Somehow "photo message" is inserted in the chat which refers to the same picture file. maybe some race condition or whatever.

Did anyone else experience that?

**Comment by licaon-kter** [comment]
What server? Where did you get the app?

**Comment by bastlwasti** [comment]
own server, with prosody 0.10, I got it from f-droid,  no google apps on my phone :)

**Comment by bastlwasti** [comment]
If the problem is also experienced by others and not also of interest for me, I can also try to debug it a bit.

**Comment by iNPUTmice** [comment]
Does this only happen if you use take picture? Or does this happen when you select pictures from the gallery as well?
Does the recipient receive two messages as well?

**Comment by kriztan** [comment]
I have the same issue, but with a self compiled version. For me it's only happening when I make a photo within conversations in landscape mode.

**Comment by iNPUTmice** [comment]
Please provide detailed steps to reproduce. Include if and when you rotate
your screen into what mode.

**Comment by bastlwasti** [comment]
1.) so far it only happened when I took the photo, and never when selecting any existing.
2.) That's a good question. I assumed it would be send 2x, but this may be a false assumption. I will check my friend's chat history ASAP.

**Comment by iNPUTmice** [comment]
I added more logging to the current HEAD. Please install latest HEAD and provide the output of adb logcat when this happens again.

**Comment by bastlwasti** [comment]
Thank you! I will update immediately!

**Comment by iNPUTmice** [comment]
Have you been able to reproduce this yet with logging enabled?

**Comment by iNPUTmice** [comment]
I’m fairly certain that this should no longer happen in Conversations 2.0 - the logic has been rewritten entirely. If it still happens please open a new issue.
