### ISSUE TITLE
backup attachments: folder structure not easy to grasp?

### ISSUE THREAD

**Issue by bastlwasti** [siacs/Conversations#2046]
I use Conversations since version 0.4 and regularly backup my phone images and conversations files, but only now realized where conversations saves its files. If I got it now right, it sends the files it downloaded from the server -- usually those I received from someone -- in the "Conversations" folder. And those photos I took and which are displayed in Conversations are saved in DCIM-folder.

So in short, image files I sent and files I received are saved at different places. I find this a bit strange, and not so easy to graps for everyone if you want to backup your data.

I suggest to save all image files in a Conversations folder, in particular also those Conversations created in DCIM. to move them also in the Conversations folder. This would make it more easy for everyone to grasp which file to backup.

Or would there be any other drawbacks with that?

greets

**Comment by d9h02f** [comment]
DCIM is used for pictures you take with the camera, and nothing else.

**Comment by licaon-kter** [comment]
Conversations just gets the photo from the place your camera decides to save it, usually DCIM.

You actually want Conversations to save a duplicate copy of that (sent) file too?

**Comment by bastlwasti** [comment]
If I take a photo with Conversation there is the original .jpg-file from the camera-app. Besides that there is a second file, which is maybe smaller in size, depending on my shrinking-settings of Conversations. It has a similar name and is also in the DCIM folder, even though it is created by Conversations, and rather -- according to my opinion -- should be in some Conversations\... folder.

Got it clear now?

**Comment by bastlwasti** [comment]
And the Conversations plugins e.g. the VoiceRecorder plugin also creates a own folder in the root folder of my disk. It would be probably also a good idea to put data files of Conversations plugins also in the Conversations folder... e.g. in Conversations\VoiceRecorder\...

**Comment by iNPUTmice** [comment]
> If I take a photo with Conversation there is the original .jpg-file from the camera-app. Besides that there is a second file, which is maybe smaller in size, depending on my shrinking-settings of Conversations. It has a similar name and is also in the DCIM folder, even though it is created by Conversations, and rather -- according to my opinion -- should be in some Conversations... folder.

The smaller version should be in the Conversations folder unless there is a very very strange bug. Please provide screenshots of the meta information (resolution, filename) of the files in question.

Under normal conditions there are two options use the original file or copy a smaller version to the Conversations directory. Conversations should not create a smaller version in the same directory as the original file.

**Comment by bastlwasti** [comment]
ok, it seems to have changed. I checked it again:
-- when I use the "always compress" setting the following files exist:
the original file in DCIM
a second file in DCIM with a similar filename, but the same size
a third file in the Pictures\Conversations folder with random filename, and smaller size

-- when I use the "never compress" setting
there is a single file, the original one in DCIM
no second file in the DCIM folder, and also no file in Pictures\Conversations


Is this as intended?

And if so, what are the consequences for backing up the complete Conversations history?
-- when using "always compress"
I just need to copy the Pictures\Conversations folder to backup the photos, and the message db as root

what about the two files in DCIM? -- they are not necessary to backup to see the complete history in Conversations with all photos, right?

**Comment by iNPUTmice** [comment]
Only the file with the the miliseconds in the file name is created by the camera on behalf of Conversations. If there are other files then those are created by the camera app without us requesting this.

If you use always compress you only need to backup the Conversations directory. If you choose never or automatically Conversations tries to use the original file and thus you need to backup the original files as well

**Comment by bastlwasti** [comment]
ok thank you Daniel!

Usually my Camera app just creates a single file with seconds in the filename, no milliseconds. When I use the camera app with Conversations it creates the usual file with seconds, and one with miliseconds (here in the example the file IMG_20161002_195840.jpg and IMG_20161002_19583889.jpg)

Well, I actually backup all my DCIM files as well, so its no big problem. However, for users who use the "never compress" or "automatically compress" setting it might be a good idea to provide some means to "identify" those files which are part of the conversations attachment universe :-). 

Maybe some sort of "backup all to folder" or "backup all to server" feature might be the most elegant solution for this. But you probably got other things to do first :-)

**Comment by juup** [comment]
I backup and restored conversations with oandbackup on new device with lineage 14.1 instead of cm13. Everything seems to be fine, but the photos are not shown (gray box). I'm afraid to activate account (OMEMO), because of 

>  It is important that your deactivate your account before backup and activate it only after a successful restore. Otherwise OMEMO might not work afterwards. 

The conversations folder is in same place and all "resized" picture are in.
How do I get the pictures back in chat?

**Comment by juup** [comment]
Solved in MUC:
Conversations need storage permission. Just try to attach any file and conversation will ask for permission. After restart, all pictures are in.
