### ISSUE TITLE
GTalk user cannot approve subscription

### ISSUE THREAD

**Issue by singpolyma** [siacs/Conversations#2047]
I use Conversations and so does my Dad. I and my wife are on a Prosody I manage, he is on Google talk. He and I talk regularly this way.

Today I tried to add him to my wife's Conversations. He got the subscription request, but when he taps "accept" I just comes back. When he opens contact details and tried to check the boxes they uncheck themselves. He can send messages to her, but trying to send messages back to him gets "delivery failure".

I asked him to add her to his roster manually and it says the contact already exists.

I'm sure this I just more Google being dumb... but does anyone know a workaround?

**Comment by licaon-kter** [comment]
A logcat of such an error would help.

**Comment by bastlwasti** [comment]
Isn't gtalk no more supported by most jabber servers since TLS encryption got mandatory?

**Comment by singpolyma** [comment]
gtalk is no longer supported by Google, but it happens to work a lot of the time.

**Comment by MontyJam** [comment]
Maybe it's time he moves to a privacy-centric (or at least privacy-respecting xmpp server)?

Help stop #PrivacyRaping one user at a time.

**Comment by iNPUTmice** [comment]
gtalk is no more
