### ISSUE TITLE
new feature : XMPP XEP-0070 with wordpress

### ISSUE THREAD

**Issue by tomamplius** [siacs/Conversations#2049]
#### New feature

I use xmpp-auth for wordpress. It's work with Pidgin but it's not work with conversation.
https://fr.wordpress.org/plugins/xmpp-auth/

**Comment by iNPUTmice** [comment]
duplicate

**Comment by iNPUTmice** [comment]
The fallback should work though of course. Are you not seeing the message or is the plugin not dealing with you sending 'YES'.
