### ISSUE TITLE
Set received- and read-confirmation per contact

### ISSUE THREAD

**Issue by STPKITT** [siacs/Conversations#2050]
#### General information

* **Version:** most current
* **Device:** Samsung Galaxy S III mini
* **Android Version:** Android 5.1.1 Cyanogenmod
* **Server name:** jabber.at

Requested feature:
It should be possible to set the received- and confirmation option per contact. GUI-wise I think it would be best to
1. ask the according question when adding a new contact
and
2. to offer a toogle for that setting on every contact detail page.

**Comment by iNPUTmice** [comment]
This level of fine grained control is out of scope for Conversations.

Just don't give people presence subscription if you don't want them to know.

Pro-tip: You can swipe away a conversation and press the undo button to mark a conversation as read without sending the read notification. (If you temporarily for some reason don't want to send the read marker right now)

**Comment by STPKITT** [comment]
I didn't remember that the presence subscription is a per contact-setting and I didn't know that it does affect read-confirmation. If I disable presence subscription for a certain user, will that user also be unable to see that I'm online in a conference we are both members in?
With "out of scope for Conversations" do you mean technically or purely as a design decision? If it's the latter I'd counter that I think that the concerned feature is one that's sought after by many users.

**Comment by iNPUTmice** [comment]
> If I disable presence subscription for a certain user, will that user also be unable to see that I'm online in a conference we are both members in?

No they can still see you as a member of that conference. However OMEMO won't work

> With "out of scope for Conversations" do you mean technically or purely as a design decision?

design decision.

**Comment by STPKITT** [comment]
>> 

    If I disable presence subscription for a certain user, will that user also be unable to see that I'm online in a conference we are both members in?

>No they can still see you as a member of that conference. However OMEMO won't work

I just disabled presence subscription for two contacts, who are also members of a three-member-conference, in which I'm the third member. I then wrote a message with OMEMO enabled in the conference and both could read the message and reply using OMEMO also. What's going on?
