### ISSUE TITLE
Split the received- and read-confirmation option into two

### ISSUE THREAD

**Issue by STPKITT** [siacs/Conversations#2051]
#### General information

* **Version:** most current
* **Device:** Samsung Galaxy S III mini
* **Android Version:** Android 5.1.1 Cyanogenmod
* **Server name:** jabber.at

Feature requested:
The received- and read-confirmation option should really be split into two separate settings. The issue #2050 I also created is kind of connected to this issue.

**Comment by iNPUTmice** [comment]
Delivery receipts are unnecessary on properly configured server and don't even work in all situations. (That's why Conversations doesn't request them by default).

**Comment by STPKITT** [comment]
I knew that, but that wasn't the issue I adressed. I don't know though, if under the hood the received- and read-confirmations are technically the same thing or at least dependend on each other.

**Comment by iNPUTmice** [comment]
No on an XMPP level they do not depend on each other.

However delivery receipts are useless so if you want to disable read markers just disable the setting.
