### ISSUE TITLE
Buggy behavior when trying to register an account via Conversations' GUI

### ISSUE THREAD

**Issue by STPKITT** [siacs/Conversations#2053]
#### General information
- **Version:** 1.14.4
- **Device:** Samsung Galaxy S III mini
- **Android Version:** Android 5.1.1 Cyanogenmod
- **Server name:** jabber.at
#### Steps to reproduce
1. on a freshly installed Conversations (experienced this on 1.14.4) try to create a new account via marking the option "Neues Konto auf Server erstellen" on i. e. jabber.at (I guess it's the same behaviour whenever trying to register a new account from Conversations' GUI on a server that doesn't support account-creation via client)
2. Conversations will tell you "Der Server unterstützt keine Registrierung".
3. Now go to the XMPP-providers' website and register the same account you tried to create via the GUI before.
4. Add the account created in step 3 in Conversations without marking the option "Neues Konto auf Server erstellen". This results in a message "Das Konto existiert bereits".

I then tried again but accidently mistyped the account-name the first time I retried, I then retried a second time with the right spelling and it then worked, however the result was that there were two accounts with the same name in "Konten verwalten" and of course only one of them was the working one.
#### Expected result

Step 4 should result in a successfully added account, no matter if the user formerly failed to add/create+add that same account.

**Comment by licaon-kter** [comment]
Repro this with another server? Say one of these that have a green line: https://gultsch.de/compliance.html

**Comment by STPKITT** [comment]
The compliance-table would really benefit from an additional tab showing a servers support of in-client-account-creation, because the first I just tried (jabber-germany.de) created a new account just fine from within Conversations, so I could trigger the bug on that try. I'll try to find another server which only let's you create an account from it's website.

**Comment by STPKITT** [comment]
Ok, I could reproduce the problem with accounts on datenknoten.me and found out additional stuff.
I could reproduce the problem on two different devices, one Samsung Galaxy S III mini running Cyanogenmod 12.1 (Android 5.1.1) and a Motorola Moto G 3. Gen running Cyanogenmod 13 (Android 6).
On the first try I just did I didn't leave the new account screen of Conversations while registering the account on datenknoten.me's website. I then just unmarked "Neues Konto auf Server erstellen" and pressed "WEITER", which did not reproduce the issue this is all about, but presented another, because instead of successfully login in I got the message "Der Server unterstützt keine Registrierung" again! Another click on "WEITER" successfully logged me in. On the next try with another new account it worked a expected, but I got the impression, that Conversations tries to create a new account on the server multiple times while not touching the display in the meantime, because the message "Der Server unterstützt keine Registrierung" seemed to re-popup.
I then found out that the original issue this topic was all about only occurs, when after getting the message "Der Server unterstützt keine Registrierung" for the first time you press "ABBRECHEN". So can then see the account being already listed by conversations in the "Konten verwalten" view, with the corresponding error message "Der Server unterstützt keine Registrierung" written in red letter below it. So the issue this topic is about then occurs when you then press the button for adding another account, entering the same account again. The result will be the message "Das Konto existiert bereits", which is true of course. When you then enter a fictional account, that doesn't exist and then click on "WEITER" you get the right message "Server nicht gefunden" or "Ungültige Zugangsdaten", depending on what you typed in. When you then type in the right account again and click on "WEITER", Conversations will not tell you "Das Konto existiert bereits" again, which would be the right behavior, but instead Conversations creates another account despite the same account being already there in the "Konten verwalten"-list, circumventing the duplicate check.

**Comment by licaon-kter** [comment]
Since you have root, do try to save a `logcat` of the moment when you reproduce this.
Upload it to https://gist.github.com and post the link here.

**Comment by blevant** [comment]
which xep shows forms for [advanced (captcha)] registration?

**Comment by iNPUTmice** [comment]
The process has been reworked for Conversations 2.0
