### ISSUE TITLE
upload menu does not appear in group chat

### ISSUE THREAD

**Issue by opensource93** [siacs/Conversations#2056]
* **Version:**  1.14.5
* **Device:** Samsung Note 2
* **Android Version:** Android 6.0 Cyanogenmod
* **Server name:** self-hosted
* **Server software:** Openfire

As title.... upload menu does not appear in group chat.  upload menu appear only In single chat

**Comment by andersruneson** [comment]
Then your server doesn't support HttpUpload, XEP-0363.

**Comment by iNPUTmice** [comment]
On OpenFire you need the https://github.com/siacs/HttpUploadComponent
