### ISSUE TITLE
Expired certificate on conference.siacs.eu

### ISSUE THREAD

**Issue by ronnicek** [siacs/Conversations#2059]
Hi,

This bug is not so much about Conversations itself, but I do not know where else report it. There is expired certificate on conference.siacs.eu

conference.siacs.eu has a valid certificate with a 4096-bit RSA key and a RSA-SHA256 signature that expired 1 day and 18 hours ago issued by Let's Encrypt Authority X3

Could you renew it? My server accept only valid certificates :)

Thanks!

**Comment by iNPUTmice** [comment]
fixed
