### ISSUE TITLE
You can crash Conversations with an OMEMO device, sid, or rid > 2^31-1

### ISSUE THREAD

**Issue by chrisballinger** [siacs/Conversations#2061]
We accidentally discovered this while implementing OMEMO and accidentally used a random number `uint32_t` with an upper bound of 2^32-1 and happened to get number that was greater than 2^31-1. The crash is during the XML parsing using Java's parseInt because Java ints are . It might also crash for other stuff like non-numbers but I didn't try it.

**Comment by iNPUTmice** [comment]
fixed in 0af13fc746d7101bfa5af7fe68e10178d22fa7f7
