### ISSUE TITLE
implement smacks revision 1.5

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [siacs/Conversations#2062]
Revision 1.5 of XEP-0198 states:

> Noted that the server MAY include a 'h' attribute when failing to resume a session because it has been timed out

Please implement this in conversations. I would effectively prevent message duplications because of a smacks timeout.

I'll add support for this to the prosody smacks module soon :)

**Comment by iNPUTmice** [comment]
This has been implemented a long time ago.

**Comment by tmolitor-stud-tu** [comment]
Oh, I'm sorry then!
Nice to hear btw. :)
Is the prosody part already implemented, too?
