### ISSUE TITLE
Unknown error when receiving self presence after joining conferences

### ISSUE THREAD

**Issue by SamWhited** [siacs/Conversations#2064]
#### General information

* **Version:** 1.14.5
* **Device:** Nexus 5x Bullhead
* **Android Version:** Cyanogenmod 13.0 nightly
* **Server name:** self hosted
* **Server software:** Prosody 1nightly713-1~wheezy
* **Installed server modules:** Stream Managment, CSI, MAM, others
* **Conversations source:** Play Store

Every now and then I reconnect for one reason or another and Conversations receives the previous self presence from the server when joining MUCs and fills the logs with complaints about receiving an unknown error. I've been getting into reconnect loops lately, but I'm not sure if this is related, or just a side effect.

#### Debug output

```
10-08 09:50:18.088  2156 17276 D conversations: sam@samwhited.com: sending offline presence
10-08 09:50:18.089  2156 17276 D conversations: sam@samwhited.com: disconnecting force=false
10-08 09:50:18.090  2156 17276 D conversations: sam@samwhited.com: closing stream
10-08 09:50:18.090  2156 17276 D conversations: sam@samwhited.com: io exception during disconnect (Socket is closed)
10-08 09:50:18.553  2156  2156 D conversations: sam@samwhited.com: push mode=false listeners=false
10-08 09:50:18.591  2156 17281 D conversations: sam@samwhited.com: connecting
10-08 09:50:18.595  2156 17281 D conversations: used lollipop variant to discover dns servers in 2 networks
10-08 09:50:18.595  2156 17281 D conversations: using dns server: 192.168.5.1 to look up samwhited.com
10-08 09:50:18.612  2156 17281 D conversations: sam@samwhited.com: using values from dns chat.samwhited.com[[2600:3c02:0:0:f03c:91ff:feae:8071]]:5222 tls: false
10-08 09:50:19.494  2156 17281 D conversations: sam@samwhited.com: TLS connection established
10-08 09:50:19.568  2156 17281 D conversations: sam@samwhited.com/conversations: Authenticating with SCRAM-SHA-1
10-08 09:50:19.690  2156 17281 D conversations: sam@samwhited.com: logged in
10-08 09:50:19.876  2156 17281 D conversations: sam@samwhited.com: starting service discovery
10-08 09:50:19.888  2156 17281 D conversations: sam@samwhited.com: server caps came from cache
10-08 09:50:19.930  2156 17281 D conversations: unknown error in conference: <presence from="jdev@conference.jabber.org/SamWhited" xmlns="jabber:client" to="sam@samwhited.com/conversations"
type="unavailable"><c node="http://conversations.im" xmlns="http://jabber.org/protocol/caps" hash="sha-1" ver="BRggJ5OmTJYdrejh1n+F9wFuRzg="/><x xmlns="http://jabber.org/protocol/muc#user">$
item xmlns="http://jabber.org/protocol/muc#user" role="none" affiliation="none"/><status xmlns="http://jabber.org/protocol/muc#user" code="110"/></x></presence>
10-08 09:50:19.953  2156 17281 D conversations: unknown error in conference: <presence from="jabber@conference.jabber.org/SamWhited" xmlns="jabber:client" to="sam@samwhited.com/conversation$
" type="unavailable"><c node="http://conversations.im" xmlns="http://jabber.org/protocol/caps" hash="sha-1" ver="BRggJ5OmTJYdrejh1n+F9wFuRzg="/><x xmlns="http://jabber.org/protocol/muc#user$
><item xmlns="http://jabber.org/protocol/muc#user" role="none" affiliation="none"/><status xmlns="http://jabber.org/protocol/muc#user" code="110"/></x></presence>
10-08 09:50:19.966  2156 17281 D conversations: sam@samwhited.com: stream management(3) enabled (resumable)
10-08 09:50:19.986  2156 17281 D conversations: unknown error in conference: <presence from="oauth@jabber.ietf.org/SamWhited" xmlns="jabber:client" to="sam@samwhited.com/conversations" type$
"unavailable"><status xmlns="jabber:client">Disconnected: Replaced by new connection</status><x xmlns="http://jabber.org/protocol/muc#user"><item xmlns="http://jabber.org/protocol/muc#user"
role="none" jid="sam@samwhited.com/conversations" affiliation="none"/><status xmlns="http://jabber.org/protocol/muc#user" code="110"/></x></presence>
…
```

**Comment by iNPUTmice** [comment]
To clarify that just fills the logs and doesn't stop Conversations from joining the MUC just fine afterwards?

**Comment by SamWhited** [comment]
I'm not sure if it's related or is just a red herring, but I only noticed this because I saw myself (via another client) joining and parting a few mucs relatively quickly. I looked at the logs and was suprised that Conversations thought the self-presence was an error, although I'm not sure if it's the reason for the disconnects or not.

**Comment by iNPUTmice** [comment]
No it doesn't mean anything. It just means that we received an unavailable presence (which are usually errors) that we don't know how to handle. It won't trigger Conversations to do a reconnect or something like that.

The question is why Conversations is doing this:
> ```10-08 09:50:18.088  2156 17276 D conversations: sam@samwhited.com: sending offline presence````

This is only being done if you disable an account of swipe the app away or otherwise do a controlled shutdown. Or at least it should only be done in those cases. Logging from before that point might be interesting...

**Comment by SamWhited** [comment]
> Logging from before that point might be interesting...

I don't remember seeing anything interesting, just that it suddenly disconnected. If it disconnects again I'll see about grabbing some more logs (it just rotated, and hasn't reconnected since the logs I posted).

**Comment by iNPUTmice** [comment]
A re connection loop if it were to happen shouldn't start with
> `conversations: sam@samwhited.com: sending offline presence`

That should only happen if you trigger some kind of UI action (disable, editing, creating). The only code path that leads to a `sending offline presence` is through the reconnectAccountInBackground method. That should be fairly easy to track. If you really see `sending offline presence` during your loop it would be very helpful if you could track the caller of that method.

**Comment by SamWhited** [comment]
It's quite possible that this happened after the reconnects and was just a red herring then. I'll dig some more and let you know if I find anything.
