### ISSUE TITLE
Message entry field loses text when focus changes away from Conversations

### ISSUE THREAD

**Issue by actcontpr** [siacs/Conversations#2066]
#### General information
- **Version:** 1.14.5
- **Device:** Moto G2
- **Android Version:** Moto G2 official Android 6.0 release
- **Server name:** jabber.de
- **Server software:** - don't know -
- **Installed server modules:** None I think. Unless OTR needs one. Then I have a module/plugin installed. :-)
- **Conversations source:** PlayStore
#### Steps to reproduce
1. Write text in message field.
2. Change focus to other app or android homescreen before sending.
3. Return to see empty message entry field.
#### Expected result

The message field should retain the last entered text beyond an focus change. If I'm writing a long message and perhaps looking up a translation or a link and come back, the entry field should still have the last text I entered - even if I close the app entirely, the last message entry field contents should be retained, if I didn't send the message yet.
### Debug Info

This isn't a full-blown bug in an existing feature, but rather than a missing standard feature. Please add it. Right now I have to copy/paste messages into the clipboard to safely change app-focus away from conversations. Not really a solution.

Otherwise I'd like to thank the Conversations Crew for their excellent implementation of a modern-day megacorp free mobile messaging app. I will continue to recommend it. Thanks a lot!

**Comment by andersruneson** [comment]
This does not happen to me and never have.

**Comment by licaon-kter** [comment]
@actcontpr This happens with "Keep in foreground" setting too?

**Comment by iNPUTmice** [comment]
Can you try typing something in one conversation and then switching back and forth to another conversation without closing the app. Does the text remain in that case?

**Comment by iNPUTmice** [comment]
Conversations is now keeping the draft even across restarts.
