### ISSUE TITLE
Clarify "8 Euro a year"

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2067]
`8 Euro a year. First 6 month free. App remains free of charge.`

So, you can see where the app was bought from when connecting to the server?
Or it's store based, say you confirm e-mail from buyer on store and account creator?

Then you deduct the app price from 8 euros so the app remains free?

Let me first state that I understand why they (app/server) cost, but I want the disclaimer text to be clearer somewhat.

/PS: [typo in 'Independend of external funding'](https://account.conversations.im/)

**Comment by iNPUTmice** [comment]
Do you have a suggestion?

**Comment by iNPUTmice** [comment]
What about

> Optional conversations.im account €8/year. First 6 month free.

**Comment by licaon-kter** [comment]
Better yes.

**Comment by dkellner** [comment]
There should also be some information (at least on https://account.conversations.im/) about *how* users are supposed to pay after the free period. And what happens if they don't pay: Will the account be disabled? Deleted? Can other users register an account with the same name?
