### ISSUE TITLE
How service keep alive when i remove task?

### ISSUE THREAD

**Issue by dhnikolas** [siacs/Conversations#2068]
Android doesn't kill my background service in my own aplication only when the service has notifications. But I see in  this application service work well without notifications.

**Comment by Mishiranu** [comment]
START_STICKY result in onStartCommand keeps service started, but doesn't prevent process kill.
For example, when you swipe app from recents, android will kill process, but sticky service will cause it to start a new one.
Foreground service (with notification) can protect your process from being killed.
