### ISSUE TITLE
XEP-0313 MAM Unavailable in MUC

### ISSUE THREAD

**Issue by tgrosinger** [siacs/Conversations#2071]
#### General information
- **Version:** eg 1.14.6
- **Device:** eg Google Nexus 6P
- **Android Version:** Android 6.0 Stock
- **Server name:** self hosted
- **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
- **Installed server modules:** adhoc, admin_adhoc, auth_internal_plain, c2s, carbons, csi, dialback, disco, filter_chatstates, http, iq, mam, mam_muc, message, offline, pep, ping, presence, private, register, roster, s2s, saslauth, smacks, storage_sql, throttle_presence, time, tls, uptime, vcard, version
- **Conversations source:** F-Droid
#### Steps to reproduce
1. Create new conference, invite users
2. Open conference settings, enable advanced mode
#### Expected result

Because server has both mam and mam_muc, expected XEP-0313 to be listed as available. Instead it is listed as unavailable.

**Comment by iNPUTmice** [comment]
There is no (standardized) setting to turn on MAM in a room. Until then you have to set your prosody config to always enable MAM for all rooms.

**Comment by tgrosinger** [comment]
I will give that a try and close the issue if successful. Thank you.

**Comment by tgrosinger** [comment]
Hmm, adding `muc_log_all_rooms = true;` did not seem to solve the problem. But I do understand that it's a difficult one to solve when there is no standard.

**Comment by shiba89** [comment]
Are you sure you are using at least prosody 0.10 with sql backend?

**Comment by tmolitor-stud-tu** [comment]
mam-muc does work like a charm for me (latest prosody 0.10 with mod_mam_muc and conversations 1.13.x to 1.14.x)

**Comment by schiessle** [comment]
> Are you sure you are using at least prosody 0.10 with sql backend?

Is the sql backend a requirement to make it work? I have prosody 0.10, mod_mam_muc and the config settings as described here https://github.com/siacs/Conversations/issues/2071#issuecomment-253816206 but currently the server runs without a sql backend. MAM is still unavailable for my MUC.

**Comment by tmolitor-stud-tu** [comment]
To my knowledge the sql backend is needed for at least the mam archive storage.
If you want to use the sql backend only for the mam archive (and "internal" for all other things) you could use something like this:

    default_storage = "internal" -- Default is "internal"
    sql = { driver = "SQLite3", database = "prosody.sqlite" } -- 'database' is the filename.
    storage = {
            -- This makes mod_mam_muc use the sql storage backend (others will use internal)
            -- which at the time of this writing is the only one supporting stanza archives
            muc_log = "sql";
            archive2 = "sql";
    }

This can also be used to set sqlite3 backend for "normal" data and mysql or postgresql backend for mam archive storage.

Additionally I'm using this mam settings (just for reference):

    -- mam settings
    default_archive_policy = true
    max_archive_query_results = 32
    archive_expires_after = "never"
    muc_log_by_default = true
    muc_log_all_rooms = true

I hope this helps :)

**Comment by tmolitor-stud-tu** [comment]
Additional info: You can also use the xmlstorage backend if you don't want to use sql.
See https://modules.prosody.im/mod_storage_xmlarchive.html

**Comment by schiessle** [comment]
@tmolitor-stud-tu thanks, works no for me with the xmlarchive. Additionally I added 

````
          modules_enabled = {
            "mam_muc",
          }
````

to the muc component. Maybe this is also useful for others.
