### ISSUE TITLE
Consolidate join/create conference buttons

### ISSUE THREAD

**Issue by knoy** [siacs/Conversations#2078]
I think it's redundant to have two different buttons depending on whether a conference already exists or not (something a user may not know in advance). There should simply be a join button, and if a conference is joined that doesn't already exist, it should automatically be created

**Comment by licaon-kter** [comment]
Some sort of message should be shown to the user about the state (new vs. existing).

**Comment by knoy** [comment]
I think it would be pretty obvious by checking the conference participants in 'conference details'? Or there could be a 'conference created' pill bar message. 

I just think the fact Conversations allows you to 'join' an empty conference, in which you can do nothing but leave, is bad UX.

**Comment by iNPUTmice** [comment]
The create conference button triggers some magic where you don't have to worry about the JID and where you can choose participants in the same step.
The join conference button on the other hand is for 'expert users' who know the JID of an existing conference or want to influence the naming of the JID. XMPP makes no difference between joining or creating.

> Some sort of message should be shown to the user about the state (new vs. existing)?

Why? It doesn't make a difference whether the user joined an empty room or created a new empty room.

If anything one could think about removing the 'Join conference' button and rely on the assumption that you either want to create a new conference or be invited to an existing one. However that doesn't work with how XMPP is used in the wild.

I'm quite happy with how it works right now.
