### ISSUE TITLE
Touch notification marks all chats as read

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#2079]
#### General information
- **Version:** 1.14.6
- **Device:** OnePlus 3
- **Android Version:** Android 6.0 Stock
- **Server name:** self hosted
- **Server software:** prosody trunk
- **Installed server modules:** Stream Management, CSI, MAM, ...
- **Conversations source:** self build (latest HEAD)
#### Steps to reproduce
1. receive multiple messages from multiple contacts and conferences
2. touch the notification jumps to one chat to read
3. touch back to get to the chat overview
4. all other chats are marked as read
#### Expected result

Jumping to one chat from multiple chat notifications should only mark this chat as read and not all other chats with unread messages too.
It would also be better if it would jump to the chat overview instead of jumping to one chat. So let the user decide which chat to read first.

**Comment by iNPUTmice** [comment]
I suspect that this is not all conversations but only the conversation that was open before. Can you confirm or deny that?

**Comment by kriztan** [comment]
@iNPUTmice I can confirm, that **not** all, but the **last** open conversation is marked as read.
