### ISSUE TITLE
Create contact should create contact if they are valid.

### ISSUE THREAD

**Issue by amarjeetkapoor1** [siacs/Conversations#2082]
#### General information
* **Version:** eg 1.12.2
* **Android Version:** eg Android 6.0 Stock 
* **Server name:** e self hosted
* **Server software:** ejabberd 16.04
* **Conversations source:** self build (latest HEAD)

On creating contact it should check whether that account exit on server or not before creating account on local as create contact is meant for creating contact for that account need to be on server i.e. valid account. Otherwise it create contact but we are not able to send message

And this thing may cause problem if we create contact and when we send message it keeps in waiting state and overloads the server plus create problem when sending message in other contact as they are also keep waiting for some time and some time that message is delivered multiple times.

#### Steps to reproduce
1.  Add contact with not valid contact id.
2.  Contact is created

#### Expected result

What is the expected output? What do you see instead?

Expected output is contact should not be created as their is no account corresponding to it.

### Note
If this would take time to get solved or you don't think its a issue. Please give us pointers how it can be solved that is check if account exit before creating contact for it.

**Comment by iNPUTmice** [comment]
Looks like a server issue to me. You could just bounce the messages.

**Comment by amarjeetkapoor1** [comment]
You mean if I have used another server then new contact wouldn't be created if their is no account corresponding to it on sever. I doubt that.  Although problem of message being in wait state could be due to server..

As main issue is if I create a contact with jabber id suppos abc@server and if there is no account on server with jid abc tgen that contact should not be created.
