### ISSUE TITLE
OMEMO verification methods: QR code + NFC

### ISSUE THREAD

**Issue by knoy** [siacs/Conversations#2084]
This has been available for OTR in Conversations for a long time. I think as the officially supported algorithm it should be able to use QR codes or NFC to verify as well.

**Comment by blevant** [comment]
If qr, 
Please also ISO 24778: Aztec Code

**Comment by knoy** [comment]
@blevant I imagine what the implementation may end up doing is relying on an external app like Conversations currently does for OTR QR-code scanning. So it will fall onto the app that actually scans the barcode on what type of code it can support

**Comment by MontyJam** [comment]
The library most everyone seems to use has long ago adopted reading and creating Aztec Code, the superior matrix in much MUCH wider use than mere mobile.

**Comment by iNPUTmice** [comment]
The last couple of commits implement a way to verify OMEMO fingerprints (instead of just 'trusting' them by moving the slider over.) Verification can be done over NFC and QR.
