### ISSUE TITLE
[Feature] Function to Crop Images before sending

### ISSUE THREAD

**Issue by eLement87** [siacs/Conversations#2085]
Hello,

in the Settings Menu -> About Conversations i found that already implemented a Library to Crop Images [#1534 ](https://github.com/siacs/Conversations/issues/1534l)

But this function is only available for the Avatar.

Is it possible to implement this into "Send Picture" before sending the Image? Like in Threema or other Messengers.
![Sending Pictures like Threema](https://cloud.githubusercontent.com/assets/1385582/19625289/af9e1bf6-9914-11e6-9037-bed0e3a5711e.png)

Hope it's not duplicated with [#1879 ](https://github.com/siacs/Conversations/issues/1879)

I would like to contribute something, but unfortunately I don't know much about android programming.

Best Regards
Ben

**Comment by licaon-kter** [comment]
Did you read #1681 ?

**Comment by eLement87** [comment]
Thanks for your reply.

Nope. I only searched for "Crop" "Resize" .
Ok, i unterstand. 

Maybe someday.

**Comment by iNPUTmice** [comment]
For now we want to focus on being an instant messenger and not become an image editor as well.

**Comment by Mishiranu** [comment]
There is a non-public Intent which often supported by many image viewer apps:

```Java
Intent intent = new Intent("com.android.camera.action.CROP");
intent.setDataAndType(uri, "image/*");
intent.putExtra("scale", true);
intent.putExtra("return-data", true); // Optional
intent.putExtra("noFaceDetection", true);
startActivityForResult(intent, REQUEST_CODE_CROP);
```

It will return you cropped image URI or parcelable image itself. This feature is not necessary for me, but if you want to implement cropping easily, you can use it.
