### ISSUE TITLE
[Feature] Missing response message for user on send error

### ISSUE THREAD

**Issue by fanningert** [siacs/Conversations#2086]
#### General information

* **Version:** 1.14.6
* **Device:** Google Nexus 6P
* **Android Version:** 7.1.1
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** CSI, MAM, ..
* **Conversations source:** PlayStore

I am using the module `mod_e2e_policy` of prosody. It is working perfectly, but under Conversation I get only the message "Zustellung fehlgeschlagen" and not "Zustellung fehlgeschlagen( For security reasons, OMEMO, OTR or PGP encryption is required for conversations on this server. )", when I send a unecrypted message.

Here the XML-Stream from Gajim, when I send a unencrypted message via Gajim.
```
<!-- In Son 23 Okt 2016 12:14:57 CEST -->
<message id='1844b058-f9d0-4a22-be7a-5fc7886c6e8e' type='error' to='clientA@example.im/Gajim' from='ClientB@example.im/mobile'>
<error type='modify'>
<policy-violation xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
<text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>For security reasons, OMEMO, OTR or PGP encryption is required for conversations on this server.</text>
</error>
</message>
```

**Comment by iNPUTmice** [comment]
Starting from 1.14.7 this information is available via the context menu.
