### ISSUE TITLE
[Improvement] Faster access to Extended connection settings

### ISSUE THREAD

**Issue by Ampli-fier** [siacs/Conversations#2087]
#### General information

* **Version:** 1.14.5
* **Device:** Any (I use Samsung Galaxy S2)
* **Android Version:** Android 5.1.1 Cyanogenmod
* **Server name:** not applicable
* **Server software:** not applicable
* **Installed server modules:** not applicable
* **Conversations source:** F-Droid

#### Steps to reproduce
My use case is: Add account with extended settings.

The advanced settings for a new account are hidden in the Expert settings menu.

The default screen for adding an account looks like:

````
Jabber ID

Password

[ ] Register new account on server
````

One needs to click and scroll 8 times to have the expert settings available:

1. ... Menu
2. Settings
3. Scroll down to 'Advanced'
4. Expert settings
5. Scroll down to 'Connection'
6. Mark 'Extended connection settings'
7. Back to Settings
8. Back to the screen for adding an account

This could be made much simpler, by providing a checkbox directly on the screen.
For example below the checkbox for registering a new account:

````
Jabber ID

Password

[ ] Register new account on server

[ ] Advanced Server Settings
````

When marking the checkbox, the advanced settings (Hostname & Port) could appear below:

````
Jabber ID

Password

[ ] Register new account on server

[x] Advanced Server Settings

Hostname                Port

````

To me 'Advanced Server Settings' is more suitable than 'Extended connection settings'.

With a checkbox, the usability would be improved. Especially for people who start Conversations for the first time.

**Comment by iNPUTmice** [comment]
If you are targeting novice users you should set up your server properly in a way that those extended connection options are not needed.

I'll think about renaming the option but putting it in the main screen will only confuse regular users. There are virtually no reasons not to setup SRV records for your users.

**Comment by Ampli-fier** [comment]
I am targeting every user who needs to use the Extended settings.
I mentioned first time users, as for them it is even more time consuming to find their way through an unknown menu structure. The efficiency gain is the same, no matter how experienced a user is.

For me it is not improper setup, if the Jabber domain does not match the DNS name of the server.
Or if the server port is different to Standard (e.g. better Security).

**Comment by iNPUTmice** [comment]
Domain != hostname not uncommon. However that's what SRV records are for. So are different ports.

This is by the way not how security works.

**Comment by Ampli-fier** [comment]
I only learned today what a SRV record is. 
However, I don't want to use it.

I'm happy with Extended settings (to keep my port number private) and that the app does not tell me to use "SRV records" instead ;-)
