### ISSUE TITLE
Anonymous P2P chat

### ISSUE THREAD

**Issue by neomodern** [siacs/Conversations#2088]
Chris Ballinger came up with a [very intriguing idea](https://chatsecure.org/blog/using-ed25519-public-keys-as-identifiers/) to use Ed25519 public keys as XMPP identifiers to allow end-to-end anonymous peer-to-peer chat via Tor hidden services. 

This is essentially what Ricochet has done on desktop and they're by far the most anonymous messenger currently available.

**Comment by knoy** [comment]
Doesn't Conversations already support tor + .onion JIDs? That should essentially be the only thing needed

>This is essentially what Ricochet has done on desktop and they're by far the most anonymous messenger currently available.
FYI Tor is also a hotbed for extortionists, nation states, poisoned exit nodes, vigilante security research, government 0days, etc and perhaps not as anonymous as you may think from a network security level

**Comment by blevant** [comment]
you might prefer ensichat

https://github.com/Nutomic/ensichat

**Comment by iNPUTmice** [comment]
I don't agree with the premise to get rid of XMPP servers.
