### ISSUE TITLE
Disposable account

### ISSUE THREAD

**Issue by AlphaOmega3** [siacs/Conversations#2094]
Add an ability to create a disposable account like Chatsecure

**Comment by licaon-kter** [comment]
On which server? Who pays for a server hosting burner accounts?

**Comment by AlphaOmega3** [comment]
I read this:
https://chatsecure.org/blog/chatsecure-conversations-zom/

I did not mean to ask to take the task of paying you the server, but only to enable their use as did ChatSecure. Then "copy" the offer skills ChatSecure and enable the following records:

dukgo.com
jabber.otr.im
jabber.calyxinstitute.org (disposable)
xmpp.jp
jabberpl.org
neko.im

**Comment by d9h02f** [comment]
What?

**Comment by iNPUTmice** [comment]
This is not on our list of planned features.
