### ISSUE TITLE
Time counter

### ISSUE THREAD

**Issue by AlphaOmega3** [siacs/Conversations#2095]
Add, in the settings, a time counter to know the remaining time of the account (ie the account is disabled in x months / weeks / days / hours);

**Comment by licaon-kter** [comment]
You mean for conversations.im server only or what? Is this a "standard" XMPP thing even?

**Comment by AlphaOmega3** [comment]
Sorry, but I have no idea .. I ask only one way to know when the account will be deactivated. maybe a message, etc.

**Comment by licaon-kter** [comment]
This depends on your server only, that you did not even mention. Do raise this issue with the server admins.

/close this

**Comment by iNPUTmice** [comment]
If you are talking about conversations.im you can look this up on account.conversations.im/login (and we will also warn you in time via a message.)

If you were referring to #2094 then i'm closing this as invalid
