### ISSUE TITLE
Support (HTTP) Public Key Pinning (HPKP)

### ISSUE THREAD

**Issue by rugk** [siacs/Conversations#2098]
I know you can distrust the system CAs in the settings, however when you don't do this, does Conversations support HPKP?
If not, take this as a feature request.

Here some links explaining what HPKP is:
* https://developer.mozilla.org/de/docs/Web/Security/Public_Key_Pinning
* https://scotthelme.co.uk/hpkp-http-public-key-pinning/
* https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning

**Comment by mimi89999** [comment]
@rugk AFAIK that isn't supported.

**Comment by iNPUTmice** [comment]
There is no comparable mechanism in XMPP (yet).

**Comment by SamWhited** [comment]
There's [draft-miller-xmpp-dnssec-prooftype](https://datatracker.ietf.org/doc/draft-miller-xmpp-dnssec-prooftype/), but it never made it past the ID phase. I'm not sure if there's been any more recent work on the matter. Either way, using DANE would be sensible.

**Comment by rugk** [comment]
Hmm, okay. DNSSEC is is course another thing, but you can also use it for the same aim.

In any way: in some cases also XMPP uses HTTP AFAIK, for example for HTTP Uploads. Is HPKP supported there? If not at least this might be implemented.

**Comment by SamWhited** [comment]
> DNSSEC is is course another thing, but you can also use it for the same aim.

It's DANE that's the important part; not DNSSEC.
