### ISSUE TITLE
"Nickname is already in use" in MUC

### ISSUE THREAD

**Issue by skddc** [siacs/Conversations#2101]
#### General information

* **Version:** 1.14.7
* **Device:** OnePlus X
* **Android Version:** Android 6.0 OxygenOS
* **Server name:** self hosted
* **Server software:** prosody 0.9.10
* **Installed server modules:** core modules
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Join chat in Pidgin for Linux on desktop
2. Try to set the same username for the account in Conversations' chat settings

#### Expected result

What is the expected output? What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
This is a server issue. Some servers don't allow you to merge two nicks into one. However if you specify the desired nick on join by entering the full jid `room@server.tld/nick` it will work out fine.

**Comment by skddc** [comment]
That worked, thanks!
