### ISSUE TITLE
Feature Request: Client Icons

### ISSUE THREAD

**Issue by BlauerHunger** [siacs/Conversations#2104]
In Gajim there is a plugin "Clients icons" which shows you the icon of the clients your contacts are currently using. 
It's a nice feature as this information allows you to support them if they have problems with their client without the need to ask them which one they are using. It's also interesting to know as you can use this info to estimate which features they support and which could cause problems. 

I'd like to also use this feature in Conversations, getting displayed either the name or the icon of the client the contact uses, for example in the "Contact-Details" window.

**Comment by falsefifth** [comment]
too much clutter.  This would be better in the contacts option page

**Comment by iNPUTmice** [comment]
I don't believe it is in the spirit of Conversations to highlight the differences between the clients. Things should just work.

**Comment by BlauerHunger** [comment]
I agree with your statement that "things should just work", but I mentioned another use case: It makes it easier to help someone who needs help with his/her XMPP-Client. The client have different UIs and not everyone is able to use Conversations, so it might be helpful to see that quickly without having to ask. 
Since Conversations implements XEP-0115: Entity Capabilities (afaik), adding this information wouldn't require that much effort (please correct me if I'm wrong; I'm not an android app developer).
