### ISSUE TITLE
Please have the Playstore APK attached to Github releases

### ISSUE THREAD

**Issue by IzzySoft** [siacs/Conversations#2112]
If I understand correctly, the main difference between the F-Droid build and Playstore is the GCM functionality. And if I'm assuming correctly, a reason behind that is to avoid the "unfree dependencies" flag. As GCM is also possible without GApps (using e.g. microG – which I can confirm working fine with apps using GCM, as I'm using that), would you consider attaching a corresponding `.apk` file to your releases on Github – to be used by those without Playstore accounts? I'd then offer to pick that up and place it into [my F-Droid compatible repo](https://android.izzysoft.de/repo), which would include automatic updates within ~24h for its users. This would be especially helpful to those unable to self-compile from the sources.

Thanks in advance for consideration!

**Comment by iNPUTmice** [comment]
We might setup an fdroid repository at some point in the future but we won't just upload APK files somewhere. We already have enough users who don't update.

**Comment by IzzySoft** [comment]
OK, fair enough. If you decide otherwise, my offer stands. As for now, permit me one question then: If I use the F-Droid version, is there some "GCM pendant" established to I get notified of new messages? According to [your FAQ](https://github.com/siacs/Conversations#how-do-xep-0357-push-notifications-work), I'd *need to be running the Play Store version of Conversations* for that. I (and others as well) rather like to avoid Playstore whenever possible. If that's not the case, is self-compiling the only alternative?

**Comment by iNPUTmice** [comment]
> OK, fair enough. If you decide otherwise, my offer stands. As for now, permit me one question then: If I use the F-Droid version, is there some "GCM pendant" established to I get notified of new messages? 

No. Conversations works just as well without it. In fact the optional GCM push is a recent addition.

**Comment by IzzySoft** [comment]
OK, thanks again! Then I'll pick it from F-Droid and give it a go. Sounds like the GCM part is hyped a bit :)
