### ISSUE TITLE
PGP send request when changing status setting

### ISSUE THREAD

**Issue by rugk** [siacs/Conversations#2113]
#### General information

* **Version:** 1.14.9
* **Device:** Cyanogenmod
* **Android Version:** Cyanogenmod 13/Android 6
* **Server name:**  self hosted
* **Server software:** ejabberd
* **Conversations source:** F-Droid

#### Steps to reproduce

0. PGP should be activated.
1. Go into advanced settings.
2. Check or uncheck the box "Change status" (which enabled/disables the option to change your status by tipping on your avatar)

#### Current result

Toast message: "You have to publish your  OpenPGP keys!" is shown.

#### Expected result

Do not show this toast message as I see no relation to whether the (status) option is enabled or not.

**Comment by iNPUTmice** [comment]
> Do not show this toast message as I see no relation to whether the (status) option is enabled or not.

The PGP key is announced in the presence and signs the status message. If you change the status message you need to resign it.
