### ISSUE TITLE
XEP-0071: XHTML-IM support

### ISSUE THREAD

**Issue by andypl** [siacs/Conversations#2114]
Hi,

Conversation lack of XEP-0071. Today, most im apps can allow send and receive pictures in the messages, html formatted text, emoticons etc.
In issue https://github.com/siacs/Conversations/issues/433 when @jonkerj ask for implementation of XHTML-IM in conversationsomeone from conversation dev team closed it with comment: "Sorry but no. Way to complex. Will never work correctly / completely / as expected."

Maybe U guys should rethink this decision? SMACK library got implementations of that XEP, so it would by easy to implement it in Conversation.

http://download.igniterealtime.org/smack/docs/latest/documentation/extensions/xhtml.html
http://download.igniterealtime.org/smack/docs/latest/javadoc/

**Comment by d9h02f** [comment]
Does WhatsApp support HTML? No? I don't see any of its one billion useds complaining about that.

**Comment by andypl** [comment]
I dont use WhatsApp, so I cant answer for this question, but Facebook Messanger allow to send htmled messages to friends. I can send an image in a message (not as a file using http://xmpp.org/extensions/xep-0096.html or http://xmpp.org/extensions/xep-0234.html or http://xmpp.org/extensions/xep-0363.html.

**Comment by licaon-kter** [comment]
So you write HTML in the conversation box? How do you use this exactly? Sample?

**Comment by andypl** [comment]
Not exactly. U dont write HTML code in Conversation. App do it for you. Take a look at spec http://www.xmpp.org/extensions/xep-0071.html

How I see this? 
When U open a new conversation with your friend Conversation app detect using http://xmpp.org/extensions/xep-0030.html that your friend support xhtml and show additional toolbar with buttons like bold, italic etc.
