### ISSUE TITLE
cannot send images to adium 

### ISSUE THREAD

**Issue by MontyJam** [siacs/Conversations#2116]
#### General information

* **Version:**  1.14.9
* **Device:**  samsung note4
* **Android Version:** android 4.4.4 stock
* **Server name:**  conversations.im to chinwag.im
* **Installed server modules:** server info shows all available
* **Conversations source:**  F-Droid

#### Steps to reproduce

1. android logged into conversations
2. adium logged into chinwag.im
3. otr mutual verified, otr enabled, text exchanges
4. conversations paperclip, take photo, accept, send
5. conversations image 'offering'
6. adium message 

?FILETRANSFERv1:c59dee0ea0ae4748baff1881371b012878fa2f334382f16c9561a3ccec3b8a6e

7. conversations never sends
8. adium never receives

#### Expected result

expect image to send and receive

**Comment by iNPUTmice** [comment]
Unfortunately there is no standard for OTR encrypted file transfer.
If you want regular file transfer to work I advise you to use Swift instead (for your MacOS X friends).
Windows/Linux contacts should use Gajim where in combination with OMEMO and HTTP Upload encrypted file transfer is possible.
