### ISSUE TITLE
OMEMO encryption in MUC dropped when user adds new device

### ISSUE THREAD

**Issue by slizzered** [siacs/Conversations#2119]
We noticed that Conversations sometimes drops the OMEMO encryption in MUC, when one user added a new device/key (related to #2117).

In one case, after a new device was added by another user, Conversations sent the next message unencrypted. That means **encryption was dropped, because another user added a new device/key**. This is the second time that it happened and, frankly, this must never happen. The MUC is encrypted for a reason. If encryption of my sent messages silently fails, without interaction on my side, this is a bug. Moreover, it was not possible to actually accept the key until the other user sent a message first. That means, encrpytion of the whole chat can be broken by a single user that adds a device and stays offline afterwards.

After the user with the new device sent a message, things started working as expected (prompt to accept new key)

If accepting keys is impossible due to technical reasons, at least the sender should be warned.
Note, that a text in the (empty) textfield ist not enough. Consider the case where I compose a long message and while doing so, another user connects a new device and goes offline again. In that case, I can't see the background-text of the textfield that tells me about sending a plaintext message.

Apart from that corner case, not everybody pays attention to the smaller details (closed padlock symbol, etc.) for every single message. If encryption is enabled 99% of the time, users stop thinking about it 99% of the time. The 1%-case when encryption is disabled must be communicated very clearly, before the message is sent. It's nice that sent plaintext messages are on a red background. But that is **only visible after the information is leaked**.

#### General information

* **Version:** 1.14.6
* **Device:** Jolla Phone
* **Android Version:** Sailfish OS, emulating Android 4.2
* **Server name:** suchat.org
* **Server software:** ejabberd 16.09
* **Installed server modules:** PEP, MUC, MAM, CSI, Stream Management, Message Carbons, Blocking Command, Entity Capabilities, HTTP File Upload, SOCKS5 Bytestreams.
* **Conversations source:** self build

#### Steps to reproduce

(does not happen reliably!)
0. All users register account on same server (see above)
1. Start a MUC with OMEMO enabled, everyone (Users A, B, C) accepts all keys and send a few messages each.
2. User A creates a new OMEMO key (e.g. with gajim)
3. User B now sends a message to the MUC

#### Expected result

What is the expected output?  
 - An offer to verify the key.
 - Ideally with a way to actually check the key if the other person is not standing next to me.

What do you see instead?  
 - No prompt whatsoever.
 - The message is sent unencrypted to **everybody** (A, B, C, and a possible third party), without a clear warning or anything.
 - It is even impossible to activate the key manually, as long as the other user didn't send a first message.

**Comment by iNPUTmice** [comment]
Yes you are right.
This was a side effect of the automatic encryption which is disabled now in 035d0c79572d5981c53d1bff7f30b484c6542f17
