### ISSUE TITLE
Feature request: Make settings im-/exportable from within the app

### ISSUE THREAD

**Issue by BlauerHunger** [siacs/Conversations#2123]
I recently had the idea that it might be helpful for people who assist others in setting up their XMPP-Account to be able to send someone a file which contains settings in conversations and which can be easily imported by someone who needs help (for example, if someone comes to me and says "hey, my conversations gets killed regularly although I allowed it to run in background", I could send them a file which activates the foreground service and which they can import. Or if someone comes to me and says "hey, I used [insert legacy messenger here] for a long time, and I miss some features from it", I could send them a file which configures conversations so that it can be used just like that legacy messenger)

Another possible advantage of the requested feature might be that I could copy settings from one to another device or restore the settings in no time when I reset my device.

**Comment by iNPUTmice** [comment]
> Another possible advantage of the requested feature might be that I could copy settings from one to another device or restore the settings in no time when I reset my device.

Have a look on how to backup Conversations in the readme

> my conversations gets killed regularly

we are trying to detect this now and enable the the foreground service automatically

In any case: If there are so many settings that there is an actual need to import/export them we have too many settings and/or wrong defaults. If you have suggestions to change defaults for some settings please join our muc and share your ideas.
