### ISSUE TITLE
UI: OTR fingerprints should be copieable

### ISSUE THREAD

**Issue by sedrubal** [siacs/Conversations#2124]
#### General information

* **Version:** 1.14.9
* **Device:** Google Nexus 5
* **Android Version:** Android 6.0.1 Cyanogenmod
* **Server name:** any
* **Server software:** any
* **Installed server modules:** any
* **Conversations source:** F-Droid

#### Feature Request

When tapping on the "verify fingerprint" box in a OTR chat then "verify manual" it should be possible to copy the fingerprint (your own and the remote one) to verify it on another channel (e.g. using another messenger or to transport it on your PC and verify it there).
It is possible to copy it in `manage accounts` > `account name` but not in the manual verification dialog.

**Comment by iNPUTmice** [comment]
OTR support has been removed in 2.0
