### ISSUE TITLE
Messages are repeated, appear in wrong order and/or are omitted

### ISSUE THREAD

**Issue by 0sifr** [siacs/Conversations#2128]
#### General information

* **Sender version:** 1.14.9
* **Recipient version:** unknown
* **Sender server name:** jabber.otr.im over hidden service 5rgdtlawqkcplz75.onion
* **Recipient server name:** jabber.otr.im over hidden service 5rgdtlawqkcplz75.onion
* **Conversations source:** F-Droid
* **Encryption used:** OMEMO

**Bug 1: messages are repeated:**
#### Steps to reproduce
This bug is reproducable on multiple accounts on the same phone:
1. Recipient is offline.
2. Sender sends message but uses the 'correct message' feature to alter message.
3. Recipient comes online

#### Expected result

_What is the expected output?_ 
  Message should be received once.
_What do you see instead?_
  Recipient receives message more than once

**Bug 2: Messages appear in wrong order**
  unable to reproduce bug on multiple accounts on same phone

**Bug 3: Messages are omitted**
  unable to reproduce bug on multiple accounts on same phone

**Comment by mimi89999** [comment]
@3897 Probably a problem with the server not supporting some XEPs.

**Comment by tmolitor-stud-tu** [comment]
@mimi89999 as far as I know XEP-0308 (https://xmpp.org/extensions/attic/xep-0308-0.1.html) "last message correction" is entirely client side and should work on every server.

**Comment by mimi89999** [comment]
I thought about MAM...

**Comment by tmolitor-stud-tu** [comment]
@mimi89999 you mean the "old" message is pulled in via MAM in addition to the corrected one?
That could indeed be the case but would be a bug in conversations.

But in this case the server would be supporting "some XEPs" (the MAM XEP) rather than not tupporting them ;)

**Comment by licaon-kter** [comment]
But can you repro on another server?

**Comment by iNPUTmice** [comment]
Make sure your server supports the latest version of MAM.
