### ISSUE TITLE
Sending file directly to contact

### ISSUE THREAD

**Issue by Myppomeu** [siacs/Conversations#2132]
#### General information

* **Version:** 1.14.9
* **Device:** HTC One SV
* **Android Version:** 4.1.2
* **Server name:** jabber.ru
* **Server software:** ejabberd
* **Installed server modules:** not known
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Send file to contact.

#### Expected result

I expect to file will be sended directly to my contact. At fact it sended through server and arrives in form of link. In 1.12.* problem does not exist.

#### Debug output

There is no working logcat on my phone.

**Comment by Natureshadow** [comment]
>I expect to file will be sended directly to my contact. At fact it
>sended through server and arrives in form of link. In 1.12.* problem
>does not exist.

It's HTTPFileUpload, and it's a feature.

**Comment by Myppomeu** [comment]
> It's HTTPFileUpload, and it's a feature.

Can it be disabled? This feature is very undesirable for me and I can't find any way to disable it.

**Comment by Natureshadow** [comment]
>> It's HTTPFileUpload, and it's a feature.
>
>Can it be disabled? This feature is very undesirable for me and I can't
>find any way to disable it.

I don't think so.

Can you elaborate on why it is undesirable?

It results in the same. Using HTTP is basically just another way of transferring a file. Maybe the annoying part is that the recipient uses a client that handles it in an unhelpful way?

**Comment by Myppomeu** [comment]
> Can you elaborate on why it is undesirable?

We use openpgp encryption.

In a case of picture in previous Conversations versions contact that receives file can see it in in chat. For now he should manually download and decrypt it. Contact uses Conversations version 1.14.9 too.

In a case of other files in previous Conversations versions contact tap one button to receive file and it automatically receives and decrypted. Now he should wait while browser runs, download it and manually decrypt.

It is:
1. uncomfortable to do more clicks and wait much more time to receive file
2. hard to train my contact how to manually decrypt files

And it would great to have a choise how to send file.

**Comment by Natureshadow** [comment]
>In a case of other files in previous Conversations versions contact tap
>one button to receive file and it automatically receives and decrypted.
>Now he should wait while browser runs, download it and manually
>decrypt.

Then the point here is to find out why Conversations does not behave just like that for HTTP (it should).

**Comment by Myppomeu** [comment]
> Then the point here is to find out why Conversations does not behave just like that for HTTP (it should).

I can't help with that besause of:
- logcat is broken on my phone
- my contact is very distant for me and he would not able to provide debug information

So it seems for me filesending in Conversations is lost.

**Comment by Natureshadow** [comment]
>So it seems for me filesending in Conversations is lost.

You could switch to OMEMO (at least for testing).

OMEMO and HTTPFileUpload are both components of modern XMPP.

**Comment by iNPUTmice** [comment]
Maybe the recipient has set the auto accept file size to 0 or you are not in each others contacts lists. In either case you can long press the message and select 'download image'.

**Comment by Myppomeu** [comment]
> You could switch to OMEMO (at least for testing).

Is this the technology does not let me have the same history on different devices and backup keys? I does not remember why I rejected this.

**Comment by Natureshadow** [comment]
>Is this the technology does not let me have the same history on
>different devices and backup keys?

It is the technology that *does* offer that.

**Comment by Myppomeu** [comment]
> Maybe the recipient has set the auto accept file size to 0

Is this necessary in last versions? As I remember in previous version was button like "accept". Can I force Conversations to display it now?

> or you are not in each others contacts lists

We are in contact list of each other.

> In either case you can long press the message and select 'download image'.

Yes, this works for images, thanks!

**Comment by Myppomeu** [comment]
Setting auto accept to minimum value forces Conversations to display "download" button. Its the answer for me, thanks!
Should I close issue or that behaviour planning to be changed to more obvious?
