### ISSUE TITLE
does select servers?

### ISSUE THREAD

**Issue by gwasher** [siacs/Conversations#2134]
Does conversations suggest servers from the mostly- or all green column tested servers via

https://gultsch.de/compliance.html 

![server xep as tested](https://cloud.githubusercontent.com/assets/23587635/20459758/48f3c044-ae82-11e6-811e-f64b71470759.png)

**Comment by mimi89999** [comment]
@gwasher AFAIK Conversations app doesn't recommend any server except their conversations.im

**Comment by iNPUTmice** [comment]
No. Suggesting specific is not really possible because we can't foresee that these servers will exists in the future. Also there are other factors like reliability and privacy policy that should be taken into account and we can't vet dozens of third party servers.
