### ISSUE TITLE
paperclip: videos instead of 'files'

### ISSUE THREAD

**Issue by gwasher** [siacs/Conversations#2135]
inline [mp4] videos show a thumbnail as expected but seem not to be autoaccepted.  Please provide an autoaccept for videos with file size range, and any size option.

**Comment by iNPUTmice** [comment]
Usually video files are automatically accepted just like regular files. (With the exception of PGP encrypted files.)
If this is not working for you please provide more information on what encryption is used and if the sender is in your contact list.
(Also the title of your issue doesn't seem to have anything to do with the text)

**Comment by iNPUTmice** [comment]
No reaction from op. Also doesn't really seem like a bug report or feature request to me. If you have further questions please visit our conference.
