### ISSUE TITLE
Configurable file deletion

### ISSUE THREAD

**Issue by devurandom** [siacs/Conversations#2137]
#### General information

* **Version:** 1.14.9
* **Device:** Samsung Galaxy S4 Mini LTE (serranoltexx)
* **Android Version:** Android 6.0.1 CyanogenMod 13.0-20160820
* **Server name:** self hosted
* **Server software:** prosody 0.10 (c420a38db5ef)
* **Installed server modules:** SM, CSI, MAM, SIFT, CC, WS, TURN, PN
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Send a message with a picture attached
2. Come back a week later to see that "the file has been deleted"

#### Expected result

I would expect that there was some option to disable automatic deletion of files, e.g. by storing the files in the Android Gallery folders.

Conversation currently seems to automatically delete attachments after an undefined amount of time / messages. This can be problematic, if the XMPP/HTTP server is configured to also delete uploads after a certain amount of time. In addition the "undefined amount of time" part is problematic, as it is unexpected by users: I do not recall there being obvious information that attachments are not stored indefinitely.

#### Debug output

Please get back to me, if this is actually necessary.

**Comment by iNPUTmice** [comment]
Conversation does not automatically delete files. If anything you removed
the file yourself in the gallery or the filesystem

**Comment by licaon-kter** [comment]
@devurandom You did not save the file locally, right?

**Comment by devurandom** [comment]
@licaon-kter No, I did not.
@iNPUTmice I could swear I did not. But maybe it got lost when my phone'was shut down uncleanly due to an empty battery...
