### ISSUE TITLE
Contact of myself doesn't show avatar in conversations list

### ISSUE THREAD

**Issue by participante0** [siacs/Conversations#2138]
#### General information

* **Version:** 1.14.9
* **Device:** It doesn't matter
* **Android Version:** Android 4.1.2
* **Server name:** trashserver.net
* **Server software:** Prosody 0.9.11
* **Installed server modules:** All of https://gultsch.de/compliance.html
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Publish avatar image
2. Add yourself from yourself as contact

#### Expected result

I expect to see my own image in the conversations list.
I see instead the first letter of my username.

**Comment by participante0** [comment]
This is useful to identify a conversation when having more than one account. For example:
`will@server.com` and `william@anotherserver.net`. In this case both have the same avatar: `W`.

**Comment by andersruneson** [comment]
Screenshot please.

**Comment by participante0** [comment]
Sorry, I tried but I can't take a screenshot in my old phone. But there is a very simple issue. Just try to chat to yourself, you can't see your own avatar.

**Comment by andersruneson** [comment]
I don't think chatting with yourself is a useful use case.

**Comment by participante0** [comment]
I use it all the time, for reminders, urls, long passwords. But anyway, that's another topic. You can create an issue "Eliminate the possibility of talking to yourself".
