### ISSUE TITLE
Switching always to foreground service after some time

### ISSUE THREAD

**Issue by amenk** [siacs/Conversations#2142]
#### General information

* **Version:** current play store version
* **Device:** Sony Xperia 5 Compact
* **Android Version:** Current VErsion
* **Server name:** self hosted
* **Server software:** ejabberd
* **Conversations source:**  PlayStore

#### Steps to reproduce

1. Activate Expert Settings -> run service in foreground

... after some time decide you do not want that ...
2. Deactivate run service in foreground
3. Foreground service is deactivated
4. Check settings: still off

So far so good

5. After some hours, it is in foreground again

#### Expected result

Run service in foreground should stay off

Very annoying, because it drains my battery.

**Comment by andersruneson** [comment]
Are you swiping away conversations from the recent apps list? If not, the
os is probably killing conversations rather often resulting in bad battery
and data usage as conversations then restarts all the time and need to
reestablish the connection without being able to reuse xmpp session.

This is a rather new feature in conversations to mitigate bad behavior of
the os.

I have some friends with Sony phones that are affected by this and for them
data and battery usage was much better with foreground service.

**Comment by amenk** [comment]
Sometimes I swipe it away I think, but not always.
The funny thing is, that the setting in Expert setting "run as foreground" just becomes ticked again. Shouldn't that stay as it is?

Before- without foreground service - the battery usage was perfect, but sometimes I had disconnects which was not as worse as the situation now :-)

**Comment by participante0** [comment]
Same as #2133.

**Comment by amenk** [comment]
Yep, a dupe, thanks for pointing out
