### ISSUE TITLE
Broken state for PM messages from MUCs

### ISSUE THREAD

**Issue by Apromixately** [siacs/Conversations#2143]
#### General information

* **Version:** eg 1.14.9
* **Conversations source:** Play Store

#### Steps to reproduce

1. Join a random MUC with Gajim from the same account
2. Send a private message to anybody there with Gajim
3. Now Conversations will open a new chat window for the PMs but sending there does not work and carbon copies show up in the MUC on Gajim side.

#### Expected result

I guess if Conversations wants to or has to display a separate window for PMs from other resources it should handle them fully and allow responding.

#### Debug output

Looking at one of the carbon copy stanzas that Gajim receives we have:
```
<!-- In Tue 22 Nov 2016 23:25:00 CET -->
<message from='user@server.org' to='user@server.org/Gajim_' xmlns='jabber:client' type='chat'>
<sent xmlns='urn:xmpp:carbons:2'>
<forwarded xmlns='urn:xmpp:forward:0'>
<message xml:lang='en' from='user@server.org/phone' id='c6799a45-ff30-4f63-9b8f-e2fa64aa3cfe' type='chat' to='gajim@conference.gajim.org' xmlns='jabber:client'>
<body>Test</body>
<markable xmlns='urn:xmpp:chat-markers:0'/>
</message>
</forwarded>
</sent>
</message>
<r xmlns='urn:xmpp:sm:2'/>
```

While if we initiate a PM from a MUC in Conversations we get:
```
<!-- In Tue 22 Nov 2016 23:26:59 CET -->
<message from=user@server.org' to='user@server.org/Gajim_' xmlns='jabber:client' type='chat'>
<sent xmlns='urn:xmpp:carbons:2'>
<forwarded xmlns='urn:xmpp:forward:0'>
<message xml:lang='en' from='user@server.org/phone' id='db389f2d-d1f6-4aa5-bd36-06dc92dd9212' type='chat' to='gajim@conference.gajim.org/OtherUser' xmlns='jabber:client'>
<body>Test2</body>
</message>
</forwarded>
</sent>
</message>
<r xmlns='urn:xmpp:sm:2'/>
```

So it looks like the /OtherUser is missing from the "to" field.

**Comment by iNPUTmice** [comment]
Screenshots from Conversations please and specify your server and the
server which hosts the muc. It might be that the muc server doesn't mark
the PM as PM.

**Comment by Apromixately** [comment]
The MUC server is conference.gajim.org as shown in the debug data.

**Comment by iNPUTmice** [comment]
The initial incoming stanza is the interesting one. Not the outgoing. And I
don't know what server software gajim.org is running on.

**Comment by iNPUTmice** [comment]
No reaction from op. closing this.
