### ISSUE TITLE
Certificate verification is based on JID, not actual server

### ISSUE THREAD

**Issue by klement** [siacs/Conversations#2144]
My JID is klement@<server>.tech, but I'm using the expert setting to connect to <server>.sk

I'm getting "Server could not authenticate as "<server>.tech". The certificate is only valid for:
[2] *.<server>.sk
[2] <server>.sk

I think should pass without warning as the certificate is valid for the <server>.sk.

**Comment by iNPUTmice** [comment]
No it should not. The standard says the server must have a certificate for the domain.
