### ISSUE TITLE
Feature Request: Changeable LED Color

### ISSUE THREAD

**Issue by derkalle4** [siacs/Conversations#2149]
Dear Community,

I searched the opened Issues fo "LED" but can't find anything related to this feature request. I would like the possibility to change the LED indication color on my Samsug Galaxy S7 like in WhatsApp or other Apps. Sure I can use a third party App for that but that's probably an overhead I don't want.

**Comment by andersruneson** [comment]
You could try searching for closed issues.
Thanks

**Comment by derkalle4** [comment]
Oh thanks I've forgot that. As far as I can see there where a pull request for changing that light already but it seems that this isn't currently in the release branch? But thanks anyway :)

**Comment by iNPUTmice** [comment]
With the new notification channels in place this feature request needs to be posted on the Android issue tracker.

**Comment by chippisc** [comment]
Is there any chance for this to be implemented?
Conversations already uses some methods that require API 26, the listener for the preferences would just be an additional one. By creating a new channel every time the led color settings are changed, the app-settings in android are kept clean as well.
If i am not mistaken the preference can even be hidden when the API-level is lower than 26 so it does not annoy users who cannot use it.

If there is any chance for this feature to be implemented I offer uploading some code I started writing for testing - works from api 26 upwards.
