### ISSUE TITLE
Share Action did not work in Conference

### ISSUE THREAD

**Issue by jugrajsingh** [siacs/Conversations#2151]
#### General information

* **Version:** self
* **Device:** Google Nexus 5x
* **Android Version:** Android 7.1 Stock
* **Server name:** self hosted
* **Server software:** ejabberd 16.04
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:**self build (latest HEAD)

#### Steps to reproduce

I Share Uri of a conference to my friend in conversations It contains "_" underscore
When my friend click the link "xmpp:test_group?join" It start startconversationactivity

#### Expected result

What is the expected output? What do you see instead?
I want the app the show join conversation dialog on clicking the link.
But nothing appears

**Comment by mimi89999** [comment]
What does ***version:*** *self* mean?

**Comment by iNPUTmice** [comment]
I'm I understanding you correctly? Conversations shows the correct behavior on your friends phone but not on your phone?
Is the URI underlined on your phone? (Recognizable as an URI I mean)

Did you actually send the link like this `xmpp:test_group?join` or is there a server part?

**Comment by jugrajsingh** [comment]
Me and my friend have same built of the app.
I send him link to join the conference i created over the server myself. link even not work for me
There is another conference i created xmpp:grouptest?join that works fine

Yes xmpp:test_group?join is the link/uri

**Comment by jugrajsingh** [comment]
Version is one below the latest HEAD.
I merge new update now

**Comment by jugrajsingh** [comment]
I am using domain_lock for my our server so we only required the local-part to proceed

**Comment by iNPUTmice** [comment]
test_group is not a valid JID. You can not omit the domain part of it. (Because what you are actually doing is omitting the localpart and a domain part can't contain underscores)

**Comment by jugrajsingh** [comment]
but it works for xmpp:grouptest?join
I want user to just show the local part in the textfield and in backend i add the domainpart when user click join.
but in my case showjoindialog is not appearing
