### ISSUE TITLE
mysterious and persistent OMEMO failures

### ISSUE THREAD

**Issue by ghostlands** [siacs/Conversations#2152]
* **Versions:** 1.14.8 - 1.14.9
* **Android Versions:** Android 4.4 - Cyanogenmod 13
* **Conversations sources:** F-Droid - F-Droid

WARNING: saga ahead.

Set up two devices to run Conversations and communicate via OMEMO. Both XMPP accounts use the same server/provider. OMEMO was available and working fine.

One of the devices (the Cyanogenmod 13 one) had its OS wiped completely. Then underwent a new install of the same OS (same version, 13, just an update). Not a restore from backup, a new install. After reinstalling Conversations and logging in to the server, found OMEMO option greyed out for all conversations that were attempted.

For the Android 4.4 instance, OMEMO never was lost as an option, never at any point greyed out.

Back on the Cyanogenmod 13 device, used expert settings to delete fingerprints, ended all conversations and deleted all relevant contacts. Re-scanned QR of the Android 4.4 device, and on the Android 4.4 device re-scanned the QR from the Cyanogenmod 13 device. The Cyanogenmod 13 device still did not have OMEMO option. Still greyed out.

Restarted the Cyanogenmod 13 device twice. On that device, deleted the fingerprint in expert settings and re-scanned several times, deleted contacts on both devices and re-scanned several times. Still no OMEMO on the Cyanogenmod 13 device. OTR works fine.

One additional oddity is that on the Android 4.4 device, the OTR fingerprint (the Android 4.4 device now shows no OMEMO fingerprint for the Cyanogenmod 13 user) of the Cyanogenmod 13 contact could not be deleted.

When trying to send an OMEMO encrypted message from the OMEMO-enabled Android 4.4 user to the OMEMO-crippled Cyanogenmod user, the Android 4.4 Conversations states: "**Error** There are no usable keys available for this contact. If you have purged any of their keys, they need to generate new ones."

Again - the Cyanogenmod 13 user has indeed deleted OMEMO identities and assumedly automatically re-generated them, after which their contact was deleted from the Android 4.4 device and then re-scanned via QR.

EDIT: Finally deleted OMEMO identity of the Android 4.4. device, and now it too has OMEMO grayed out for conversations it attempts to initiate.

There isn't any apparent reason that the OMEMO option should be grayed. So either we have user error, in which case the interface should explain better why the user deserves this fate, or something is able to get broken in what is ultimately a pretty average use case. What is the road to OMEMo here? The server supports it, supports PEP. I'm left with no clue how I ever got OMEMO in the first place or how to get it back.

:/

**Comment by iNPUTmice** [comment]
This is not a bug report but a support request. If you need help please visit our conference.
You can long press the lock icon to get a hint why it is not working. If it says 'Missing keys' I suspect this to be a server issue. And you should update to 1.15.0

**Comment by ghostlands** [comment]
@iNPUTmice thanks for the long-press hint, missing OMEMO keys is what it read.

1.14.9 is the latest on F-Droid as of today.
