### ISSUE TITLE
Make Videos visible in Gallery

### ISSUE THREAD

**Issue by AleXburnA** [siacs/Conversations#2153]
#### General information

* **Version:** eg 1.15.0
* **Device:** Samsung Galaxy S6 edge
* **Android Version:** Android 6.0 Stock
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** PEP, Stream Managment, Roster Versioning, Message Carbons, CSI, MAM, Push, HTTP File Upload
* **Conversations source:** PlayStore

#### Steps to reproduce

1. receive a self-shot video (.mp4)
2. the .nomedia file in the /conversations folder prevents it from being visible in the Android gallery
3. if the .nomedia file is deleted, all the videos are shown in the gallery, until it gets recreated by Conversations

#### Expected result
Received mp4 videos should be visible in gallery

#### Debug output

none needed, I guess...

**Comment by licaon-kter** [comment]
That's a privacy issue, if you want them seen do copy them elsewhere, otherwise they should be visible in the current app (Conversations) only.

**Comment by iNPUTmice** [comment]
This has been added in 1.16.0
