### ISSUE TITLE
Feature Request: Import contacts from address book

### ISSUE THREAD

**Issue by sedrubal** [siacs/Conversations#2155]
#### General information

* **Version:** eg 1.15.0
* **Device:** eg Google Nexus 5
* **Android Version:** Android 7.0.1 Cyanogenmod
* **Server name:** mailbox.org
* **Conversations source:** F-Droid

#### Description

It should be possible to import contacts from android address book to the current jabber account.

Conversation should walk through all contacts in address book and if there are jabber IDs it should import the contact and link it to the address book.

**Comment by licaon-kter** [comment]
You did give it Contacts permission, right?

**Comment by sedrubal** [comment]
Yes

**Comment by iNPUTmice** [comment]
This is implemented in the current version but will be removed because it turns out it is very annoying and impractical. You can still click a contact from the address book to open a conversation with them.
