### ISSUE TITLE
New version 1.15.0 sets all existing fingerprints to untrusted

### ISSUE THREAD

**Issue by RD07a** [siacs/Conversations#2156]
#### General information

* **Version:** eg 1.15.0
* **Device:** Samsung Galaxy S5 Neo
* **Android Version:** Android 6.0.1 Stock
* **Server name:** self hosted
* **Server software:** Prosody 0.9.11
* **Installed server modules:** PEP, Stream Managment, Roster versioning, Message carbons, CSI, HTTP File Upload
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Conversations update to v1.15.0 via PlayStore
2. ALL existing OMEMO encrypted communications show a red lock symbol
3. In the contact details the switch next to the OMEMO fingerprint is put to the right (trusted). All fingerprint have been manually verified in the past.

The only way to get the lock symbol back to green is to use the new barcode scanning function.
This is not acceptable as the verification has been done already succesfully and it would be a very high effort to re-verify all contacts.
Also it should still be possible to use alternative verification options like manual fingerprint comparison. 

#### Expected result

All existing and verified communications should keep their trust status without need for another trust confirmation after a version update of Conversations is applied.

**Comment by iNPUTmice** [comment]
Sorry this was a necessary step in the migration because we couldn't guess if you had actually verified the fingerprints or just blindly accepted them before.

Manual verification will not be possible. The [Blind Trust Before Verification](https://gultsch.de/trust.html) document explains why.

**Comment by iNPUTmice** [comment]
Also note that no behavior change has resulted through this. It's just the color of the lock that changed.

**Comment by martinsauter** [comment]
It would have been really great if there had been an "info" pop-up after the app update. It has cost me an hour to figure out why suddenly the locks were red including purged and thus blocked keys. It's really a great feature but it was mightily confusing if you are not aware of it. Sometimes I wished I was a normob and wouldn't worry about locks running from white to red without explanation.

**Comment by licaon-kter** [comment]
I was about to open an issue too, but I'll use this one, while I know about the changes, it's not clear how does one verify the key now. Long press "scan 2d barcode" or?

**Comment by BlauerHunger** [comment]
You can either scan a barcode to get the xmpp uri of your contact with the omemo fingerprint embedded or aquire the xmpp uri otherwise and have conversations process it. Then it'll automatically trust the omemo fingerprints in the uri.

**Comment by licaon-kter** [comment]
Ye, but this needs some sort of warning or pop-up or toast in the fingerprint screen saying "hey, you have these but they need to be authenticated (again) or else red lock; do this by scanning...."

**Comment by TheLastProject** [comment]
While I understand this decision, I'm very disappointed by the way this was handled. Especially with the new blind trust setting, Conversations silently lowered my security settings. I also seem to no longer be able to trust the keys manually, which is a serious problem because not all my friends are using Conversations, and thus not all of them can even generate these QR codes. I literally can no longer trust my contacts...

**Comment by iNPUTmice** [comment]
@TheLastProject you can still trust them. You just can't verify them. You can completely restore the old behaviour by opting out of BTBV in the expert settings.

**Comment by TheLastProject** [comment]
@iNPUTmice I am literally not supposed to be able to verify users who aren't on Conversations anymore?

**Comment by iNPUTmice** [comment]
> @iNPUTmice I am literally not supposed to be able to verify users who aren't on Conversations anymore?

Of course you can still verify users that use other clients. They just have to display a barcode. Which gajim can do for example.

**Comment by licaon-kter** [comment]
@TheLastProject In BTBV defense, it's in "Expert settings", if one feels experty enough to enable it, one will find a way to verify it.

That being said #2166 awaits further input on how to make the experience better UI wise.

**Comment by TheLastProject** [comment]
@licaon-kter It seemed to be enabled by default for me though. So with the update my client started to silently trust new devices.

**Comment by mimi89999** [comment]
@TheLastProject @licaon-kter 
https://github.com/siacs/Conversations/blob/master/src/main/res/xml/preferences.xml#L169

**Comment by licaon-kter** [comment]
@mimi89999 It wasn't true on my test devices after upgrade, IIRC I specifically went in Expert settings to set it up for testing. Hence my comments.

**Comment by muv** [comment]
@iNPUTmice 

> You can completely restore the old behaviour by opting out of BTBV in the expert settings.

I have disabled it and the locks on OMEMO messages from my verified contact are still red.

Manual verification is critical to me. My contacts may not use a barcode-capable client. I may not have a working camera.

**Comment by iNPUTmice** [comment]
> I have disabled it and the locks on OMEMO messages from my verified contact are still red.

yes they are red because you haven't verified them. But you can still decide whether you want to trust them.

**Comment by muv** [comment]
Contact details have OMEMO fingerprint turned "on" (trusted).
I did verify the fingerprint on previous versions. I carefully checked every symbol of the fingerprint with what I received via existing trusted channel. That's why the fingerprint is trusted.
Still confused. Are "trusted" and "verified" different concepts now?

**Comment by licaon-kter** [comment]
See the FAQ search for "blind"

**Comment by BlauerHunger** [comment]
Yes, they are. Now "trusted" only means that you trust that the fingerprint is correct, but did not verify it (maybe you just want to exchange messages but these are not that secret and you don't have the opportunity to verify the fingerprints) . "Verified", the new status means, that you actually verified that the fingerprint is correct by either scanning a barcode or exchanging a XMPP URI over a trusted channel. You just can't set them to "verified" manually (probably as a luser-protection). 

The problem with the old solution (and probably the reason why it was replaced) was that you only had two states (trusted and untrusted) and you had to trust a key to exchange messages. Because of this many people forgot to verify the fingerprint manually later.

**Comment by ArchangeGabriel** [comment]
It’s not just that, else this would be insufficient to justify the removal of manual verification.

The idea behind the removal of manual verification is that you don’t want people to be able to easily check it without actually having verified.

I think that @muv expected the expert setting to allow him to manually verify the key, but instead it apparently reverts to the old 2-states behaviour, which indeed wasn’t good.

**Comment by licaon-kter** [comment]
And now you manually check the key with a different method, send a MMS, meet in person and scan... there are ways.

**Comment by RD07a** [comment]
Dear all,

after reading all the explanations and comments my conclusion raiser of the issue is the following:

- I got the point why the change was implemented and understand the motivation and security benefits but I believe is was/is not communicated to the end users in the right way. When such big changes are implemented that even have an impact on existing contacts and conversations (even if only visual) it should be explained in a very clear way, e.g. by openening a popup on the first start of the new version after updating.

- There is the need to outline much clearer the difference between "trust" and "verification" incl. related visualization (background color, lock symbol color, ...)

- The configuration menu containing the fingerprint(s) should be optimized, e.g. by given a textual status information for each fingerprint (e.g. "untrusted and not verified", "trusted but not verified", "trusted and verified") and more clear options to trigger both actions (trust and verification). Maybe there could be an additional button below the slider for the trust like "request verification from contact" sending them a predefined message to share his barcode, xmpp:uri or http link.

So finally its more about usability and unser information than technical implementations and problems.

Some of these things have already been addressed in the separate thread #2166 from @licaon-kter . So let's see what  happens next.

Let's keep having the best XMPP app on Android! 

And many thanks for the support of all contributing developers.

   Oliver

**Comment by dln-dev** [comment]
The way I see it is that it's quite close to the way Threema handles trust status. I personally don't use it but from what I've heard, there's a red dot for unknown users, yellow or orange for known users (their phone number is in your contacts) and green for actual physical fingerprint verification.

The red lock symbol is pretty much equivalent to the yellow dot in Threema where it indicates you "kinda know" that person, but can't be sure it's indeed their key you're encrypting with. To me and all people I've asked who use Conversations, red strongly indicates some serious failure. A few have mistaken it to mean there's no encryption at all. 

So I'd say, as was also mentioned in issue #2175, making the lock symbol yellow or orange reduces the misconceptions about its meaning. 

I also agree about the "Show QR code" option being hidden too deep in the menu. Perhaps a "verify" button on top of a conversation that directly leads to the QR codes and disappears after verification is an alternative?

**Comment by licaon-kter** [comment]
Do use #2166 for ideas though :)

**Comment by muv** [comment]
I've read the [FAQ](https://gultsch.de/trust.html) several times but I still don't get it.

* I have manually verified a fingerprint of my contacts. They are both "trusted" and "verified" for me. It worked correctly in 1.14.9.
* Conversations shows me red locks and wants me to accept inconvenience in favor of _some_ users who tend to ignore fingerprints.

I disagree to be forced to use camera and barcode scanner. What if I use custom ROM with broken camera driver? What if I don't trust camera firmware and disabled it physically? What if my device doesn't have camera at all?

So my only option is some "XMPP URI" mentioned by @BlauerHunger (thanks) which I have no idea how to use.

I appreciate all the intentions to prevent users from silly mistakes. But ignoring fingerprints is a serious mistake for privacy wanters. Perhaps those users need Viber or WhatsApp.

I feel handicapped by this "luser protection".

**Comment by licaon-kter** [comment]
Indeed, looks like there's an issue here, if you don't have a camera.

Say, from unencrypted you activate OMEMO, it asks you to "generate a key for the contact" which sounds wrong. Then you can only open the camera... so you are stuck there.

**Comment by 0mark** [comment]
Thats not the only problem. I am very well able to verify a Fingerprint by reading and comparing it to the one i got over a secure third channel.
It is then truly and really verified. And trusted. Why should this way not be possible?

**Comment by iNPUTmice** [comment]
> It is then truly and really verified. And trusted. Why should this way not be possible?

This is possible. Disable BTBV ignore the fact that the locks are red and you've restored previous behavior.

**Comment by licaon-kter** [comment]
@iNPUTmice If BTBV is disabled why are the locks still red? This will add more to the confusion though.

**Comment by 0mark** [comment]
Indeed

**Comment by RD07a** [comment]
Ok, let's summarize again (pure independent user view):

- After upgrading to v1.15.0 there is no way to restore 100% the old behaviour as it brings the new trust&verification modell.
- The new modell works as follows:
1. New fingerprints/contacts are "untrusted" and "not verified" by default
2. Contacts/fingerprints can be manually "trusted" by moving the slider next to the fingerprint (contact details) to the right. In this stage the contact is still "not verified" and therfore the lock symbol appears red. This is also the situation with all existing contacts that you probably marked as trusted already before.
3. The only way to get your contacts in status "verified" is to retreive from them either their barcode, their xmpp:uri or their html link and confirm this. Then the contact is formally "verified" and the color of the lock symbol changes to white. The argumentation of the developers is that a manual check is not secure/trustworth enough to work as a real verification.

So conclusion for me is:
a) Send your own barcode/xmpp:uri or html link via your account menu to all your contacts. That allows them to put you into state "verified" on their devices.
b) Ask all of your contacts to send you their barcode/xmpp:uri or html link. That will put them into state "verified" on your phone.

And finally don't forget: This is not only about trusting a "contact" but a dedicated fingerprint per device. So you and they have to repeat it for every device in use.

This will definitively take some while...

Or alternatively as stated by @iNPUTmice : if you don't mind disable BTBV and live with red lock symbols

Overall for me the new concept in principle looks ok and acceptable for new contacts to be added but it is really a pain if you have a lot of already existing contacts/fingerprints and have do do now a massive verification campaign (incl. explanation of the why and how to all the non-techi friends...)

**Comment by licaon-kter** [comment]
Don't forget that if you don't have a contact key (eg. you deleted a key) you can't add one without a camera right now.
