### ISSUE TITLE
After updating to 1.15.0 conversations diverts to unencrypted

### ISSUE THREAD

**Issue by gnujedi** [siacs/Conversations#2157]
#### General information

* **Version:** 1.15.0
* **Device:** Nexus 6P
* **Android Version:** CopperheadOS (Android 7.0)
* **Server name:** conversations.im
* **Conversations source:** F-droid

Had OMEMO set up with contacts, but now it defaults to unencrypted. If this is due to the new verification protocol, I understand, but it should warn users first.

**Comment by iNPUTmice** [comment]
No. That's a separate change of not having a default encryption anymore. You have to set it once for a conversation now. There is an FAQ entry for that.
