### ISSUE TITLE
Upgrade to 1.15.0 disables OMEMO in conversations

### ISSUE THREAD

**Issue by nobse** [siacs/Conversations#2158]
I realized that two contacts were sending me unencrypted messages, even if we previously had OMEMO enabled in the conversation. After upgrading Conversations from 1.14.9 to 1.15.0 myself, I faced the same issue... OMEMO encryption was suddenly disabled in all conversations, I had to reenable it manually. Just exchanging a few messages didn't help, also not when no other client was connected to the same account.

My contacts are using the Google Play version (using default LG and Samsung firmwares based on Android 6.0.1), I am using the F-Droid build on CyanogenMod 14.1.

**Comment by licaon-kter** [comment]
Did you read #2156 or #2157 or the FAQ?

**Comment by nobse** [comment]
I have read the FAQ (but I overlooked the already open issues, sorry for that). The FAQ does not explain why in the past encrypted chats are suddenly no longer encrypted. It only explains that encryption is no longer enabled by default (read: for new chats).

Daniel explained it in #2156, but wouldn't it be better to just set the keys to "blind accepted" in that case instead of disabling encryption silently without notifying the user about it?

**Comment by licaon-kter** [comment]
Past opened chats went from OMEMO to unencrypted? That's might be different and rather nasty issue.

**Comment by nobse** [comment]
Yes, past opened chats went from OMEMO to unencrypted after upgrading to 1.15.0.

**Comment by mimi89999** [comment]
For me chats passed only to unencrypted if I:
1) Updated Conversations to 1.15.0
2) Didn't do anything in that chat in Conversations, but wrote a message from Gajim with the gajim-omemo plugin enabled...
3) My contact has 1.14.9, but I don't know if that is important here because only I and one contact have updated to 1.15.0 (for today...).

**Comment by nobse** [comment]
If it is not the intended behaviour that in the past opened chats going from OMEMO to unencrypted after upgrading to 1.15.0, then this issue should be reopened.

**Comment by nobse** [comment]
Unfortunately I'm unable to reopen this issue myself. @iNPUTmice?

**Comment by iNPUTmice** [comment]
@nobse this is intended behavior as long as you never explicitly chose an encryption for those conversations yourself

**Comment by mimi89999** [comment]
So you are silently disabling OMEMO if it was activated automatically?
