### ISSUE TITLE
CAPTCHA support for SPAM filtering

### ISSUE THREAD

**Issue by IUnderstandLetsChangeMyUsername** [siacs/Conversations#2159]
This is a feature request.

Due to immense amounts of spam in XMPP federated network, which mostly has a malicious nature (e,g, promoting criminal services instead of a "regular" supplements advertising etc.), there should be measures implemented on a client side as soon as possible.

Some desktop clients recently gained basic customizable CAPTCHA support, e.g. Gajim's plugin "Anti Spam", which now offers an option to set up own question/answer pair to weed out unwanted automatized first time contacts. It is very easy and still works perfectly.

This is very much described in [XEP-0158](http://www.xmpp.org/extensions/xep-0158.html), however at first this may be implemented in a basic yet effective form, for example in Gajim plugin's way. Once the protection will be in place, Conversations may again become a first choice of an XMPP client for many owners of public JIDs.

**Comment by iNPUTmice** [comment]
I'm sorry you are having problems with SPIM. However I don't think this is something that should be 'fixed' on the client side.
Valerian Saliou recently wrote a lengthy [blog post](https://journal.valeriansaliou.name/announcing-providence-a-spam-filter-for-xmpp/) about future strategies to prevent SPIM you might want to participate in that process if this topic interests you.

**Comment by IUnderstandLetsChangeMyUsername** [comment]
Not so fast, Daniel. For now there are no server-side solutions, and there will be no any in the nearest foreseeable future. Now he volume of spam/SPIM is immense. What should be done is to let users at least a generic feature to filter such messages. It will work here and now.

If you are so reluctant to implement such a basic feature yourself, maybe there are contributors who could help?

**Comment by github-k8n** [comment]
Probably this is not identical to the original request? but I think  XEP-0158 has been implemented in ejabberd, it "works", but it would be nice to have the captcha flow within Conversations itself (i.e. interpret the challenge stanza and show the captcha image that has been sent and return the entered challenge).
Currently having to click on a link and enter the captcha there just feels a bit awkward.

I know it might not be high priority but it would just perfect the polish of a great app like conversations. :D
