### ISSUE TITLE
Feature request: add option to remove permanent notification.

### ISSUE THREAD

**Issue by qwazix** [siacs/Conversations#2160]
Please add the option to disable the permanent notification. It's annoying and unfortunately I cannot downgrade to a previous version without having to remove the app, thus losing everything

**Comment by iNPUTmice** [comment]
What version are you on?

**Comment by qwazix** [comment]
1.15.0 (latest on F-Droid)

**Comment by iNPUTmice** [comment]
Please provide the adb logcat. If the foreground notification gets enabled
on 1.15.0 there is probably something wrong with your phone and you better
keep it enabled.

**Comment by licaon-kter** [comment]
@qwazix Since https://github.com/siacs/Conversations/commit/bca8f11c9c2d3df9dcfc2253bc108fc6e9a241ef if the app gets killed often by your unnamed device (do detail what device and Android version do you have please) then the background service (and the obligatory notification, as per Android requirements) will be enabled. 

You can disable this service in the Experimental settings, and see if it comes back after a while, if it does then you have a problem with your system: eg. you need to whitelist the app in Doze or Battery optimisations or anywhere else.

**Comment by qwazix** [comment]
I have conversations whitelisted. My device is a Sony Xperia XZ on 6.0.1. The notification appeared after I upgraded conversations (from an older version, don't remember which).

Let me get a copy of adb to provide a logcat.

**Comment by iNPUTmice** [comment]
Sony devices are somewhat known to kill the app extremely frequently. In
that case it actually might be better to keep the service. Or find the
secret Sony setting that triggers those killings.

**Comment by qwazix** [comment]
Ok, I will debug it. I will post logcat later if there is something that looks pertinent, for now I'm gonna try to avoid it as it contains some information I'd rather not post publicly.

For the time being the app hasn't been killed by the system yet. Maybe it's because its connected with usb to the computer for the logcat and battery optimizations don't kick in.

Thanks for the quick responses.

**Comment by licaon-kter** [comment]
@iNPUTmice Not sure where you got that impression about Sony devices. Pre-MM you have Stamina and you whitelist an app there for continous internet access (else you get periodic connection only) and since MM you have Doze. There was no app killer in any version. 

BTW, Google Doze is mostly modeled after Sony's Stamina, but it only gets on par since Nougat. In MM it's useless unfortunately, and Stamina is removed leaving only an UI setting with that name for Doze.

**Comment by iNPUTmice** [comment]
> @iNPUTmice Not sure where you got that impression about Sony devices

People in the conference telling me about this problem. Actually it's these people why that 'feature' exists now. I'm not saying it happens on every Sony. It might not even be a sony feature but just a weird memory strategy or what ever.

**Comment by qwazix** [comment]
Today the notification appeared again. Both times it happened after leaving the phone connected to PC on MTP mode for a while. I know it's probably unrelated but I thought I'd mention it.

**Comment by licaon-kter** [comment]
Log?

**Comment by qwazix** [comment]
Sorry for the delay.

I cannot see something relevant in the log. I left it connected for about an hour or so, but after 40min the computer went to sleep so the log stops.

```
--------- beginning of system
--------- beginning of main
12-08 11:50:31.339  4301  4382 D conversations: deleted file /storage/emulated/0/[redacted]/Cache/Thumbnail
12-08 11:51:03.421  4301  4382 D conversations: deleted file /storage/emulated/0/[redacted]/Cache/Thumbnail
12-08 11:51:35.501  4301  4382 D conversations: deleted file /storage/emulated/0/[redacted]/Cache/Thumbnail
12-08 11:52:07.578  4301  4382 D conversations: deleted file /storage/emulated/0/[redacted]/Cache/Thumbnail
12-08 11:52:39.658  4301  4382 D conversations: deleted file /storage/emulated/0/[redacted]/Cache/Thumbnail
12-08 11:53:12.074  4301  4382 D conversations: deleted file /storage/emulated/0/[redacted]/Cache/Thumbnail
12-08 11:53:33.619  4301  4301 D conversations: schedule next idle ping
12-08 11:54:55.431  4301  4301 D conversations: [redacted]@[redacted].[rd] send ping (action=ping,lowTimeout=false)
12-08 12:03:11.514  4301  4301 D conversations: [redacted]@[redacted].[rd] send ping (action=ping,lowTimeout=false)
12-08 12:07:41.241  4301  4301 D conversations: [redacted]@[redacted].[rd] send ping (action=ui,lowTimeout=false)
12-08 12:07:41.244  4301  4301 D conversations: app switched into foreground
12-08 12:07:46.421  4301  4301 D conversations: app switched into background
12-08 12:07:55.194  4301  4379 D conversations: resetting start time counter
12-08 12:08:26.826  4301  4301 D conversations: schedule next idle ping
12-08 12:08:27.250  4301  4382 D conversations: deleted file /storage/emulated/0/Android/data/dk.[redacted].android.[redacted].full/files/backup/[redacted]_backup.db
12-08 12:08:27.269  4301  4382 D conversations: deleted file /storage/emulated/0/Android/data/dk.[redacted].android.[redacted].full/files/backup/[redacted]_backup.db
12-08 12:12:42.330  4301  4301 D conversations: [redacted]@[redacted].[rd] send ping (action=ping,lowTimeout=false)
12-08 12:18:26.924  4301  4301 D conversations: [redacted]@[redacted].[rd] send ping (action=ping,lowTimeout=false)
12-08 12:18:27.878  4301  4301 D conversations: schedule next idle ping
12-08 12:21:13.164  4301  4301 D conversations: start merging phone contacts with roster
12-08 12:21:13.164  4301  4301 D conversations: finished merging phone contacts
12-08 12:23:27.951  4301  4301 D conversations: [redacted]@[redacted].[rd] send ping (action=ping,lowTimeout=false)
12-08 12:28:29.146  4301  4301 D conversations: schedule next idle ping
12-08 12:28:29.150  4301  4301 D conversations: [redacted]@[redacted].[rd] send ping (action=idle_ping,lowTimeout=false)
```

**Comment by iNPUTmice** [comment]
since cb9c4d43278dfee9c6ef0e24153bd5a3a2c2688a the foreground service won't get enabled automatically anymore.

**Comment by qwazix** [comment]
Fwiw since the nougat update, it hasn't enabled itself (maybe 1.15.2
already has cb9c4d4 though)
