### ISSUE TITLE
Add contact details share options

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2162]
...like you have in Account share options, meaning add:
* 2D barcode
* HTTP link

**Comment by srgcdev** [comment]
I would go further and I would add this option in muc details too.

For example in this scenario:

1. One person create a muc where he knows all contacts, but the other contacts maybe don't know each other.
2. If he wants to enable OMEMO in this room it would be very useful to share one link with all the jid's of the participants with their OMEMO keys (his jid included).

**Comment by iNPUTmice** [comment]
acc78145dbf430ce0472c0373bc453fe647f59c6
