### ISSUE TITLE
Remove useless icon in "change presence" titlebar

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2165]
...you can use the back button and arrow to get back to "Account details" anyway

**Comment by iNPUTmice** [comment]
It's not useless. You can access the 'change presence' activity by clicking your own avatar. That icon gives you a way to then enter your accout details.

**Comment by licaon-kter** [comment]
You already have "configure accounts" in the menu

**Comment by iNPUTmice** [comment]
> You already have "configure accounts" in the menu

That doesn't bring you to that particular account though

**Comment by licaon-kter** [comment]
I know, either way it feels as unneeded.
