### ISSUE TITLE
Better UI regarding BTBV encryption

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2166]
As a continuation from #2156 given the changes that [BTBV](https://github.com/siacs/Conversations#what-is-blind-trust-before-verification--why-are-messages-marked-with-a-red-lock) has brought, here are some ideas:

* Account details, near the fingerprint copy icon put an icon for `show 2D barcode`, don't hide it in the menu ( also, ironically the share menu does no have the most important `show 2D barcode` item )
* Contact details, near the fingerprint toggle put an icon for `scan 2D barcode` if unverified, don't hide it behind a long press.
* While the party that started OMEMO in a conversation got a toast about BTBV, the other side did not get any, both should get it.

**Comment by sicherha** [comment]
Another idea for usability improvement from my side: It would be great if there were a possibility to display not only one's own 2D barcode, but also the barcode of a contact whose fingerprints the user has previously verified. This would make it easier to propagate trust in a contact's fingerprints to one's other devices.

For illustration, assume the following scenario. Alice owns two devices running Conversations: a mobile phone and a tablet for on-the-sofa use. She scans her colleague Bob's barcode at work using her phone. Alice's phone now trusts Bob's fingerprints, but her tablet doesn't. Alice would either have to bring her tablet to work and scan Bob's barcode again, or she would have to store a photograph of Bob's barcode on her phone and scan it at home.

**Comment by mimi89999** [comment]
I would put the verify button/"SCAN 2D BARCODE" under the fingerprints. I propose that:
![screenshot_1481124316](https://cloud.githubusercontent.com/assets/8530546/20985054/131fa3b2-bcc3-11e6-96dd-1cf177b7ec53.png)
The button would be entirely invisible if there are no fingerprints.

**Comment by mimi89999** [comment]
Currently:
1. It is not obvious where it is.
2. It is too easy to press several cm below and mark a fingerprint as compromised. 😞

**Comment by Selaron** [comment]
@sicherha Barcode Scanner APP is capable to redisplay Barcodes scanned and saved in History.
History -> Scanned code -> Share-> Clipboard. Now Alice can scan thus using her tablet.
Conversations.im should not include any barcode en-/decoder libs but simply delegate this task to scanner app as it currently does.

**Comment by sicherha** [comment]
@Selaron Nice, I wasn't aware of that. Still a bit complicated, but it does the trick for me.

**Comment by DreamFlasher** [comment]
As I wrote here: https://github.com/siacs/Conversations/issues/2204 I suggest the following UI improvements:

- Add documentation for the meaning of the security icons (red lock, grey lock, grey shield) in app (eg. longpress to get some info) (also: I couldn't find any documentation about the meaning of the differene between the grey lock and the grey shield -- does anybody know?)
- Add capability of sharing the barcode on social media (eg. a sharing button)

**Comment by BlauerHunger** [comment]
Sharing the barcode (=verification) via social media (you probably mean twitter, facebook etc.) is a bit problematic because for real verification you have to ultimately trust the channel you are using for verification. But imo social media isn't trustworthy at all.

**Comment by DreamFlasher** [comment]
It's recommended in the Readme: https://github.com/siacs/Conversations/blob/master/README.md

**Comment by tohojo** [comment]
For showing different trust levels, I would suggest doing something similar to Threema (a proprietary secure messenger, https://threema.ch/en) - that has three levels of trust: red, yellow and green, shown as three dots that can be filled in and that changes colour when the trust level increases. See here for screenshots: https://ctovision.com/threema-seriously-secure-messaging-application-check/

Making the trust level a property of the contact not of each message makes it possible to display it more prominently. The coloured shields could still be displayed per message, of course...

**Comment by mimi89999** [comment]
@iNPUTmice Can we have that option moved, as I proposed?

**Comment by griffindoors** [comment]
How can the readme be spawned from within the app?

**Comment by griffindoors** [comment]
> doing something similar to Threema

That does not seem like an improvement.

**Comment by DreamFlasher** [comment]
>That does not seem like an improvement.

Did you have a look at it? Threema does it significantly better than Conversations right now. The only system that is IMHO even better in verification is keybase. It would be great if conversations would integrate with keybase.

**Comment by Selaron** [comment]
> How can the readme be spawned from within the app?

Simply make the OS open a Hyperlink like this: https://github.com/siacs/Conversations/blob/master/README.md#head-of-development

**Comment by DreamFlasher** [comment]
Instead of just opening a hyperlink users should be taught why it's important to do verification and then how to do it.

**Comment by Selaron** [comment]
This would then be the task of the linked readme or other fancy web page IMHO.
But defining a concept on how to integrate documentation with UI for daily use without messing it up might be worth a new issue because this is not limited to BTBV.

**Comment by licaon-kter** [comment]
Can we at least, for an unverified key, get a modified text underneath that says:
`OMEMO fingerprint (long press to Scan 2D barcode and verify)`

instead of:

![modtext](https://i.imgur.com/5dBULcG.png)

where you don't get a clue on how to verify it?
