### ISSUE TITLE
OMEMO trust mechanism and scanning

### ISSUE THREAD

**Issue by blacoste** [siacs/Conversations#2169]
Conversations version 1.15.0 enhanced the OMEMO fingerprint trust verification:
- one can still enable or disable encipherment for specific device
- but exchanges with a specific device are marked untrusted unless the fingerprint barcode has been previously scanned.

I agree that it is a good idea to distinguish encryption from trusted authentication. But in this case this is non acceptable situation when a third-party user or another device of the user is not able to generate the 2D barcode expected by Conversations.

So I propose that:

1/ User shall be able to manually validate its own fingerprints for its own other devices, and third-party correspondent fingerprints. 
For instance on the fingerprint GUI object, when making a long press, use a combo-box:
- Disable communication emission
- Enable communication emission
- Trust

When selecting "Trust", a message will popup: "Please consider to carefully check the fingerprint otherwise select "Enable communication emission" only as it will only add an untrusted display mark on the message and won't affect communication. OK / Cancel.

Messages received should always be displayed although they are untrusted. User shall be notified of untrusted message but shall not miss an important information because of trust mechanism complexity.

2/ To be able to publish fingerprints. User shall be able to export the barcode generated, as an image and as text. This is especially tricky to retrieve the omemo-sid as it is not printed anywhere.

3/ "Scan 2D barcode" action is not as the right place. It is accessible by doing a long press on an OMEMO key. This should be accessible in the global menu as it is not a unique key related action (barcode contains several fingerprints).

The main risk of the current situation is that due to the complexity of the trust verification (scanning), users will be trained to talk to correspondents marked as untrusted, which downgrades the security level.

**Comment by iNPUTmice** [comment]
1) Operates under the false assumption that there are clients out there which can not display a QR code. Gajim can for example
2) Thats already possible. Use the share button in account details.
3) We haven't finalized the UI yet
