### ISSUE TITLE
Enter password manually 

### ISSUE THREAD

**Issue by willhelm-mueller** [siacs/Conversations#2170]
Hi, 

i would like to request a new feature. A new checkbox 'Save password'. If checked the pw will be stored on disk otherwise the pw needs be entered on the inital connection. Afterwards the pw could be stored in memory but not on disk.

**Comment by iNPUTmice** [comment]
Android will kill and restart Conversations in frequent and random intervals. Storing the password in memory only will cause a completely unusable user experience.
