### ISSUE TITLE
red encryption locks

### ISSUE THREAD

**Issue by mvhulten** [siacs/Conversations#2173]
#### General information

* **Version:** 1.15.0
* **Device:** Google Nexus 7
* **Android Version:** Cyanogenmod 13
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Enable recipient OMEMO key.
2. Send OMEMO-encrypted message.

#### Expected result

A green, closed lock next to the message was expected, but it was a red, closed lock. The colour red suggests that the key is not verified, or something else is wrong. However, the key is verified, and I now do not know whether my connection is secure.

**Comment by revuwa** [comment]
Just have a look at the changelog (https://github.com/siacs/Conversations/blob/HEAD/CHANGELOG.md) of v1.15.0, especially this: https://gultsch.de/trust.html
