### ISSUE TITLE
[feature request] scanning barcodes without 'Barcode Scanner' app dependency

### ISSUE THREAD

**Issue by revuwa** [siacs/Conversations#2174]
#### General information

* **Version:** 1.15.0
* **Device:** Samsung GT-I9300
* **Android Version:** Android 7.1 Cyanogenmod
* **Conversations source:** F-Droid

#### My question
I very appreciate the new 'Blind Trust Before Verification' mode.
So I wanted to scan my very first contact's qr code, but the app said, that it depends on the 'Barcode Scanner' app, which wasn't installed on both of the devices which I wanted to verify each other.

The thing is, I (personally) don't like that Barcode Scanner app, with its 10(!) needed Android permissions and (IMHO) for Conversations not needed (bloated) functionalities.

So I thought it would be really great if Conversations could possibly:

1. support other, (in my case already installed) apps, like Obsqr (source: https://github.com/trikita/obsqr), which needs only one single permission (android.permission.CAMERA), or
2. embedding the qr scan functionality as other apps, like OneTimePad (source: https://github.com/kckrinke/onetimepad) already did, to scan qr codes without external dependencies.

I would prefer the second variant, but I don't know how much effort this means.
What do you think?

**Comment by ArchangeGabriel** [comment]
See https://github.com/siacs/Conversations/issues/2154.

Personally, I’m in favour of 2.

**Comment by iNPUTmice** [comment]
It is undesirable for Conversations to replicate the behavior of other apps and to include permissions for the camera.
If there are others Apps that can be invoked by intents and are able to scan Aztec codes I'll happily integrate them. Just point me to documentation of those Intents. The suggested obsqr doesn't seem to have such intents.

**Comment by iNPUTmice** [comment]
You could for example implement https://github.com/trikita/obsqr/issues/2

**Comment by PeterEdens** [comment]
Why not use https://github.com/dlazaro66/QRCodeReaderView embedded into the app, It uses the zxing library.
