### ISSUE TITLE
Reenable manual verification

### ISSUE THREAD

**Issue by 0mark** [siacs/Conversations#2175]
#### General information

* **Version:** 1.15.0

#### Expected result

I understand the idea behind blind trust. But i am able to verify contacts manually by ways *I* choose. I have lots of contacts i never see in real life, or who have a device without a camera. Most of the time we already have other secure ways of communication to use for verification. Some of those are not even able to transfer images.

It would be awesome if manual verification would be made possible again (at least optional), it is a vital feature for me, most of my contacts and probably many other people.

**Comment by licaon-kter** [comment]
Why does it matter if the lock is red? How does that change anything?

Also #2166 awaits input ;)

**Comment by 0mark** [comment]
If this red lock is the only thing that differs a "barcode verified" contact from an "otherwise verified" contact, then the color does not really matter, although it is kinda annoying cause red indicates usually trouble. But i dont know. Since https://gultsch.de/trust.html states: "A manual verification is not possible" I doubt that that is the only difference.

But even if the red color is the only difference, its kinda annoying. We really do verify each new contact, even each new device. We use secure channels for that. Getting told "use this, you guys never do this right else" is a bit bitter.

**Comment by ArchangeGabriel** [comment]
FWIU, you have now three possibilities:

1. No lock, no encryption. You don’t want that.
2. Red lock: encryption, not verified.
3. (Green?) lock: barcode verified.

So no, it’s not the only difference, because there is no such thing as otherwise verified.

**Comment by sixtyfive** [comment]
@iNPUTmice There was a conversation going on here about the topic. It's a bit rude or at the very least unhelpful to just barge in and close the issue without saying a word, don't you think? As @0mark correctly assumes, there's a lot of people interested in verification without a barcode. C'mon!

**Comment by YoukaiCat** [comment]
As a workaround you can create QR code by yourself if you know the contact JID, device ID and the key fingerprint.
I wrote a small script for this purpose using the QR code generation function from the Gajim OMEMO plugin: https://gist.github.com/YoukaiCat/402696233a0ec9fa3600b31bc1e4c159 (depends on python2, qrcode)
