### ISSUE TITLE
Feature requests: Encrypted chats only

### ISSUE THREAD

**Issue by lagosazules** [siacs/Conversations#2176]
Not all servers block unencrypted messages,  some less attentive people don't notice they sending a unencrypted message,  a option to block this will be a good security option.

**Comment by licaon-kter** [comment]
The grey barely visible text in the chat input field, where one writes text, actually states the current state. Not sure how that's that unnoticeable.

**Comment by lagosazules** [comment]
Yes it is for you and my,  but like I wrote "less attentive people" and believe me there are many of them and they write to us, this is a security issue.

**Comment by BlauerHunger** [comment]
Would a switch in the settings that brings back the old omemo-by-default behavior solve your problem?

**Comment by lagosazules** [comment]
It happens sometimes,  especially with people using OTR and when they are a longer period offline
