### ISSUE TITLE
Conversations 1.14.9 uses way too much traffic

### ISSUE THREAD

**Issue by mirabilos** [siacs/Conversations#2177]
#### General information

* **Version:** 1.14.9
* **Device:** HTC Desire (bravo)
* **Android Version:** LiquidSmooth 4.4
* **Server name:** self hosted
* **Server software:** ejabberd
* **Installed server modules:** don't know
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Install Conversations
2. Use it at most(!) once a day, and most of the time over WLAN

#### Expected result

What is the expected output?

That Conversations uses, I don't know, 100 KiB or so a month, at best, after the initial roster download, etc.

What do you see instead?

That Conversations uses about 1 MiB of mobile traffic a day, using 30% of my entire mobile traffic plan!

To add insult to injury, Conversations auto-starts itself with the device. I would have expected to start it like a normal Jabber client and be able to exit it, which also seems to not be possible. **This is probably a privacy leak: it leaks the status (turned on or off) of my mobile device to all contacts and the server operator.**

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

Not possible because I reboot the device at least once daily, if not more often.

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
You have to include more details regarding your server (what modules you have installed) and you should include the output of adb logcat. You don't have to include the output for the entire lifetime of Conversations just for an hour or two. This should be enough to detect irregular behavior.

**Comment by jplitza** [comment]
I don't suspect irregular behavior here. It's more that downloading contact's avatars and reconnecting whenever the mobile connection is flaky simply eats away data.

Things that might or might not improve the data usage are XEP-0198 Stream Management, XEP-0237 Roster Versioning and XEP-0352 Client State Indication. You can check whether your server supports them selecting "Server info" from the menu in the account details dialog.
