### ISSUE TITLE
DOMAIN LOCK

### ISSUE THREAD

**Issue by Ruhallah93** [siacs/Conversations#2178]
Hi Mr
I set DOMAIN_LOCK to IP but it changed in Jid to host name
and host_name not found because application found just with IP

**Comment by iNPUTmice** [comment]
This is intended behavior. domain lock locks the domain not the hostname. there is no code in Conversations that will lock the hostname

**Comment by Ruhallah93** [comment]
thank you Mr
but my host name isn't identifiable in conversations
conversations found host just with IP
i implemented OpenFire in my local network ,not internet
i need to store ip in JID not hostName

**Comment by iNPUTmice** [comment]
> i need to store ip in JID not hostName

This works fine for me. If I set `DOMAIN_LOCK` to `192.168.1.1` for example conversations generates JIDs with `username@192.168.1.1` (only for new accounts though)

Please don't open up new issues for the same topic.
