### ISSUE TITLE
Feature Request: Unread messages counter for every chat separately

### ISSUE THREAD

**Issue by participante0** [siacs/Conversations#2181]
Currently, the counter is global. The number is the sum of all unread messages of all conversations of all enabled accounts.

It would be helpful to have the number of unread messages of one conversation. For example, if I have new messages on 10 different conversations and the count is 850, I want to know which conversation had more activity.

The same feature exists on WhatsApp, Telegram and others, so the people is already used to this.

**Comment by hareshkh** [comment]
Where is the current *global count* of messages being displayed? In my case I am only able to see the total number of chats which have unread messages.

**Screenshot 1** : I have unread messages from two conversations and no unread count for the individual conversations.
![screenshot_2017-03-03-00-50-49-114_eu siacs conversations](https://cloud.githubusercontent.com/assets/16576273/23523355/92102058-ffac-11e6-9161-38d9d886f103.png)

**Screenshot 2** : Only the number of conversations with unread messages are displayed.
![screenshot_2017-03-03-00-51-11-687_eu siacs conversations](https://cloud.githubusercontent.com/assets/16576273/23523356/9211bfd0-ffac-11e6-885b-7ed5b74c0f92.png)

**Comment by iNPUTmice** [comment]
The global count is only available if your ROM supports it. It is displayed as a small bubble in the app icon in the launcher.

**Comment by hareshkh** [comment]
Can I take up this issue to make a separate count for each chat?

**Comment by iNPUTmice** [comment]
@hareshkh yes you can. Have a look at this unfinshed PR https://github.com/siacs/Conversations/pull/2210 and my comments on that.
