### ISSUE TITLE
[Feature request]: Disable notification when higher priority client or a certain resource is connected

### ISSUE THREAD

**Issue by shiba89** [siacs/Conversations#2183]
Having my phone continuously vibrating and ringing when I'm chatting over PC (namely Gajim) is very annoying. Completely muting my phone is not an option, as I might very likely miss other important notifications. As of now, I'm trying to get used to put Conversations offline, but I often forget to come back online when I'm not on my PC.

Would it be possible to implement a mechanism that turns Conversations notifications off when a higher priority client or a certain resource is connected?

**Comment by iNPUTmice** [comment]
Please have a look at the Grace Period feature and choose medium or long. This should cover your use case better than what you are proposing (because what happens if you forget to turn of your computer or reset the priority)

**Comment by shiba89** [comment]
Just an idea: Gajim has an auto-afk feature and can set a specific priority for each status, so the "forgotten powered on PC" problem could be mitigated this way. I know this is probably a too specific circumstance (maybe even Gajim-only?) and I understand how you would rather not over encumber Conversations, so please don't take this opinion too seriously. I will try the long grace period you suggested and in a couple of weeks I will report back how it feels. Thanks for your support :D

**Comment by shiba89** [comment]
Ok, I tried this for a long time. I still don't fully get it, but long grace period works fine when Gajim conversation window is focused, it doesn't (aka vibrating and ringing right away) when it's not. So maybe it is a Gajim problem, but I don't really know where to look.

**Comment by mbirth** [comment]
Same problem here. Grace period set to "long". I have Gajim open the whole day and am, of course, not have Gajim focused the whole time. Whenever a message arrives, my phone's screen turns on and shows the notification, although I've just sent a message from my desktop Gajim 10 seconds ago.

Is there really no way to detect, if Conversations is receiving a message carbon (i.e. no need to notify the user (right-away)), if there's another client with same or higher priority present and/or that client was active in the last minute?

**Comment by iNPUTmice** [comment]
> Same problem here. Grace period set to "long". I have Gajim open the whole day and, of course, not have Gajim focused the whole time. Whenever a message arrives, my phone's screen turns on and shows the notification, although I've just sent a message from my desktop Gajim 10 seconds ago.

Showing the notification is expected behavior. But it shouldn't vibrate or ring.

**Comment by mbirth** [comment]
Yes, you're correct. But with the display being one of the largest power consumer in a phone, I'd like it to only show up when there's a "worthy" notification, i.e. one that would also make it vibrate/ring. Could you make this configurable, please?

**Comment by iNPUTmice** [comment]
What ROM does turn on the display when receiving a notification? Does it do that for every Notification? Or just for notifications with a certain priority?

**Comment by mbirth** [comment]
It's the BlackBerry PRIV, stock ROM. And no, I don't think this happens for all priorities. I have a Tasker script showing/updating a "Low" priority notification and that one doesn't wake the screen. Same for e.g. "Deliveries" checking the status.

**Comment by iNPUTmice** [comment]
23a91e5019f3b1005ca9f1bb03e33b72f037b323 should lower the priority of a notification when the grace period is active. Feel free to test if this is working on your ROM as well. (It did on mine after enabling the Ambient Display. Didn't know that was a thing.)
