### ISSUE TITLE
[Feature Request] Option to disable Notification if Sender is not in my Roster (SPAM/SPIM)

### ISSUE THREAD

**Issue by vic42** [siacs/Conversations#2184]
As Daniel mentioned in some other thread about SPAM filtering, I agree this would be a reasonable approach to handle ever increasing russian malware spam:

  An options checkbox "Only notify me if sender is in my roster"

The most annoying thing is the notification. Checking this option would still allow you to get contacted by not-yet-contacts for the first time. These "first time contacts" simply would not trigger a visible or audible notification.

**Comment by klement** [comment]
I am now getting a lot of russian spam daily. Would really appreciate not getting the notifications for that.

Though the original idea is somewhat usable:

> An options checkbox "Only notify me if sender is in my roster"

a better approach would be to provide a way to define and apply rules, e.g.

IF in-contact-list(<contact>) THEN allow,notify
IF domain-is(<contact>, "russian-spam-domain.ru") THEN drop
IF NOT domain-is(<contact>, "company-domain.com") THEN drop
IF matches-regexp(<contact>, ".*@.*\.ru") THEN drop
IF NOT in-contact-list(<contact>) THEN allow

I would hide this in the expert settings and provide a few knobs for basic uses cases, allowing non-tech-savvy users to use the feature without too much headaches.

1.) don't notify if the contact is not in the same domain as me
2.) don't notify if the contact is not in the contact list
... etc.

**Comment by griffindoors** [comment]
xep0016 as whitelisting

ftw

**Comment by vic42** [comment]
As I read it, xep0016 defines complete blocking of messages/stanzas. I don't think it will serve the purpose. I still want to be able to get contacted by persons not in my roster or from a foreign domain. Just the audible notification of my mobile needs to be muted for those.
Blocking specific domains won't work as my russian spammers use multiple benign public XMPP servers for distribution of their "offers". They seem to have a large repository of accounts.
