### ISSUE TITLE
While fetching history a chat may open again by itself though it was closed

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#2186]
#### General information

* **Version:** 1.15.0
* **Device:** Google Nexus 5
* **Android Version:** Android 6. Cyanogenmod
* **Server name:** conversations.im
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Join a MUC
2. Before history is completely fetched: Choose "delete history and close chat afterwards"

#### Expected result

What is the expected output?
The MUC should stay closed.

What do you see instead?
It opens again showing more fetched messages.

**Comment by iNPUTmice** [comment]
Fixed in 2.0
