### ISSUE TITLE
Prank conversations.im users by letting non contacts join any MUC :-)

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#2187]
**Server name:** eg conversations.im
**Client**: Conversations 1.15.0

#### Steps to reproduce

1. Invite any conversations.im user to any MUC

#### Expected result

The user may follow your invitation if he's on your roster list. That's clear.

However:
Even if he's not on your roster list he will follow the invitation and autojoin the MUC.
The best thing is, he won't even know who invited him. :-)

Maby you should reconsider https://github.com/siacs/Conversations/issues/358 and at least show a toast from whome the invitation came.

#### Further comments
Could be reproduced three times with three different conversations.im accounts which don't know each other. Did not work with users from different servers.

**Comment by iNPUTmice** [comment]
working as intended.
