### ISSUE TITLE
Blind trust verification with x509

### ISSUE THREAD

**Issue by Fenisu** [siacs/Conversations#2188]
#### General information

* **Version:** 1.15.0
* **Device:** Google Nexus 5
* **Android Version:**  Android 6.0 Stock
* **Server name:** self hosted
* **Server software:** ejabberd 16.04
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** self build with x509 verification

#### Thoughts

I was testing and trying this setup and how should this actually work? If you use only one server (no s2s) and everybody uses x509, there should be no way to end up with two devices not automatically verified, right?

The possession of the certificate and to be connected to that server should be enough to be always verified automatically, either you have 1 device or multiple, and you send to 1 or multiple.

**Comment by iNPUTmice** [comment]
Yes everything signed by x509 should automatically end up as 'verified' in the BTBV mode. Thus the users should never be in a situation where they have to make a trust decision.

**Comment by Fenisu** [comment]
OK, then I think I have found a couple of cases where the parties are not being verified automatically. I am going to look a bit deeper in that and I will report back.

**Comment by Fenisu** [comment]
Maybe this issue is related to https://github.com/siacs/Conversations/issues/2227

After some testing with latest build 1.15.2, I can reproduce the problem I had. The testcase which also happens before the blind verification commit (with x509), is when the Presence somehow got "out of sync", and only one of the parties is sending the presence status, but both receiving, and the user that is not sending.

I have been able to reproduce two problems. One scenario is that OMEMO does not become available even after activating presence in both ways, which I then was able to get it back available once by logging out and then logging in, and once I had to delete omemo keys. Difficult to reproduce this problem.

The other scenario is that the OMEMO is available, but only one of the users can verify. This problem is easy to reproduce:
Step 1A
- 2 users (A and B) with omemo activated and working.
- Deactivate send presence updates at user A.
- Regenerate certificate or delete omemo keys at same user A.
- Send a new message from the same user A, which it is going to be sent after automatically fetching keys, to user B.
Step 1B
- 2 users (A and B) added as contacts for the first time and both checkboxes activated.
- Send unencrypted messages as OMEMO is not available.
- Choose OMEMO.
- Deactivate send presence updates at user A.
- Send a new message from the same user A, which it is going to be sent after automatically fetching keys, to user B.
Step 2
- The other user B, will receive the messge and it will say v/OMEMO from now on. You send a new message and it will fail, popping up the Trust OMEMO Fingerprint View, forcing you to verify manually, which should not happen with x509, sometimes even the manual verification is done automatically (the switch is in "on" state without having it pressed previously). 
- At this point, the presence updates checkbox do not help anymore, and only a renew certificate/delete omemo keys allows a new verification process, which will fail again if the presence are not activated in both users.

There should be some kind of trigger to do the verification process whenever the presence state between the parties is updated.

**Comment by Fenisu** [comment]
It seems to work now, I guess it was fixed in https://github.com/siacs/Conversations/commit/0c0ff882a957b24cb78775e6fff87dcee380dd5a.
