### ISSUE TITLE
If a delivery of a message fails, it should be retried. If it is aborted, a notification should be displayed.

### ISSUE THREAD

**Issue by marmistrz** [siacs/Conversations#2191]
#### General information

* **Version:** 1.15.0
* **Conversations source:** F-Droid

When a delivery of a message fails, a red text `delivery failed` appears below the message body. But if the user presses the home button straight after sending the message, they won't know about it until they visit the conversation again. This makes the communication unreliable.

A notification should be spawned when a delivery fails, so that the user gets to know their message has not been sent and so that they can resend it ASAP

**Comment by licaon-kter** [comment]
This might get tricky fast, say when your network won't work, you'll get swamped in notifications.

How do you show such notification, generic "Some message failed" or show content (watch out for privacy issues)?

**Comment by jkufner** [comment]
It is simple. There are two cases:

1. Delivery failed to one recipient: Show a single notification, after clicking the notification open the chat.

2. Delivery failed to multiple recipients: Show a single notification with number of failed recipients and open roster after clicking the notification. And in the roster show error icon next to each recipient with failed messages.

**Comment by BlauerHunger** [comment]
Until now I only got these "delivery failed" tags on messages when the recipient's server was down,  where quickly resending isn't that useful, or when sending an image via Jingle File Transfer to a contact with unstable internet, in which case an automatic retry would probably be the best option. 
But a notification like "Your message to xyz failed to send" or a mark in the conversations overview would be nice.

**Comment by jkufner** [comment]
The primary use-case for the notification should be: "Something is wrong with Jabber, I should send SMS instead."

**Comment by marmistrz** [comment]
@jkufner not really. I'm really angry when I notice that a message has not been delivered after a week or more and someone resents why I have not answered. 

I basically get them when the Internet connection is poor, but don't remember at whose side. Probably mine, as otherwise MAM would handle that.

**Comment by stopANALytics** [comment]
> resents why I have not answered.

At least with jabber texting they know you have read the message very much unlike sms texting.

**Comment by marmistrz** [comment]
Not really. It depends on which XEPs are implemented by the other
client. In particular, Gajim support delivery receipts but not read
receipts.

**Comment by marmistrz** [comment]
This would not be a problem if Conversations tried to deliver the message again even if it fails. If I send a message after the remote side loses Internet connection but before they get offline, they message fails to be delivered (in the past it was silently dropped unless MAM was employed).

It would be great if automatic retrying were a part of Conversations. Of course, we can't retry forever, so when we run out of the number of attempts, a notification should be displayed.

**Comment by marmistrz** [comment]
@iNPUTmice
Why was that issue closed? Can you please share the rationale?

**Comment by iNPUTmice** [comment]
@marmistrz please have a look at the FAQ our the duplicate issues. This can and should be fixed on the server side.

**Comment by marmistrz** [comment]
#3083 and #3207 are really good reasons why such notifications would be a good thing to reconsider. Additionally, such notifications could help discover server misconfiguration. 

Would you accept PR adding notifications for failed messages (opt-in)?
