### ISSUE TITLE
Processing bitmaps in UI Thread

### ISSUE THREAD

**Issue by struggggle** [siacs/Conversations#2198]
Dear developers,
I am analyzing Conversations using a static code checker. I found some potential slow operations of bitmap displaying in Conversations. 

Android documentation says this: 
https://developer.android.com/training/displaying-bitmaps/process-bitmap.html
" The BitmapFactory.decode* methods should not be executed on the main UI thread if the source data is read from disk or a network location (or really any source other than memory)."

In the position of Conversation:
eu.siacs.conversations.persistance.FileBackend.java     cropCenter()
the bitmap object is created with the invocation of decodeStream(), and the source data is read from a network location. 
I found cropCenter() is invoked indirectly by:
(1) eu.siacs.conversations.ui.adapter.MessageAdapter.java    getView()
(2) eu.siacs.conversations.ui.adapter.AccountAdapter.java    getView()
and image decoding is done in UI thread. getView() callbacks are frequently invoked and this means that there will be many bitmap objects being created.
Since image decoding is slow, for performance considerations, we should perform these operations in worker threads (e.g., via AsyncTask).

I noticed that cropCenter() is also invoked indirectly by:
(1) eu.siacs.conversations.ui.adapter.ListItemAdapter.java     getView()
(2) eu.siacs.conversations.ui.adapter.ConversationAdapter.java getView()
and in such cases worker threads (via AsyncTask) are used. So I am curious why in the earlier cases, image decoding is done directly in UI thread?

In addition, in the following position, image decoding is also done in UI thread:
eu.siacs.conversations.persistance.FileBackend.java cropCenterSquare()
which is invoked indirectly by: eu.siacs.conversations.ui.adapter.MessageAdapter.java android.view.View getView()

Looking forward to your response and hope I can help improve Conversations.
Thanks.

**Comment by iNPUTmice** [comment]
Fixed in 1fd3bbfe2529d5488914babde0cf76b0de621840 and cdf2bd07df20e4745dc0cbbe93ae23c0ae399f97
