### ISSUE TITLE
history

### ISSUE THREAD

**Issue by Ruhallah93** [siacs/Conversations#2199]
Hello Mr
when i add a account ,i need to history of my conversations
but conversations page is empty.
Is there a solution?

thank you.

**Comment by licaon-kter** [comment]
You've erased the issue template text please provide that info, it's important.

**Comment by Ruhallah93** [comment]
I could not understand you
i used local network
i just need to all conversation history in all of time ,not just after log in
merC

**Comment by licaon-kter** [comment]
When you create an issue here you need to provide the requested info: device, android version, app version, app store source, server, modules used on the server, etc.

**Comment by Ruhallah93** [comment]
device : asus fonepad 8
android version : 5
app version : 1.15.0
app store source : run from android studio
server : local
modules used on the server : all in server is default

**Comment by Ruhallah93** [comment]
server is open fire in my local network
OS : win 10

**Comment by iNPUTmice** [comment]
I don't think OpenFire supports Message Archive. At least not by default.

**Comment by Ruhallah93** [comment]
Is it possible to not be removed from the local?

**Comment by Ruhallah93** [comment]
hi 
i need to refresh conversation list from database
i need to recreate conversation list but i can't find way it
