### ISSUE TITLE
Android 7.0 flickering

### ISSUE THREAD

**Issue by patrick7** [siacs/Conversations#2201]
#### General information

* **Version:** 1.15.2
* **Device:** Huawei Mate 9
* **Android Version:** 7.0 / EMUI 5
* **Server name:** self hosted
* **Server software:** ejabberd
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Open App
2. Click on a contact

#### Expected result

The title bar starts flickering. Expected is not to do so. 

#### Debug output

https://gist.github.com/patrickvelder/f1aa29a25d663d07ecc0b258b17a5b5d
See also http://pvl.pw/VID_20161224_223321.mp4

**Comment by conrad-heimbold** [comment]
Have you tried turning off battery optimisation for the app Conversations? I once heard it could be related (had the same problem with the app Apps2Org), but I am not sure (it didn't help in that case, unfortunately).

**Comment by athanasio** [comment]
I can report the same problem. It started immediately after the upgrade from EMUI 4.1 (Android 6) to EMUI 5.0 (Android 7) last week, with no other change. Ignoring optimisations doesn't have an effect.

* **Version:** 1.16.1
* **Device:** Honor 8
* **Android Version:** Android 7.0 EMUI 5.0
* **Server name:** self hosted
* **Server software:** prosody 0.10 and ejabberd (two different accounts)
* **Installed server modules:** all supported by conversations 
* **Conversations source:** PlayStore Beta Channel

**Comment by iNPUTmice** [comment]
I'm just gonna say that and I'm not trying to be ignorant but don't expect a fix from my end. It'll take someone with such a device to maybe find a work around for this. I don't have such a device. So this bug is going to be open for ever unless one of you guys step in and fix this yourself.

**Comment by athanasio** [comment]
I can give it a try - do we have a confirmation that this is EMUI/Huawei specific and not Android Nougat specific?

**Comment by iNPUTmice** [comment]
> do we have a confirmation that this is EMUI/Huawei specific and not Android Nougat specific?

It doesn't flicker on my Google Nexus 5X with Stock ROM and it also doesn't flicker on my Nexus 4 Lineage 7.1 and this far I've only heard complains from Huawei users.

**Comment by mimi89999** [comment]
I also don't experience that issue on self built LineageOS 14.1 (Android 7.1.1). Do you experience that issue **only** in Conversations?

**Comment by patrick7** [comment]
I sold my Mate 9 (was unhappy with it), so I'm not able to help. 
On my Oneplus 3T (Android 7) I don't experience this issue.

**Comment by athanasio** [comment]
I experience this issue **only** on conversations until now, but I have been using it with Android 7.0 only for the past week. Based on the feedback, it appears to be an issue with EMUI.

**Comment by athanasio** [comment]
After a little bit of research, I think I found the reason: the function updateActionBarTitle() runs multiple times when a message is being sent, received, delivered, merged with the previous sent message etc. The "flickering" is a repeated fade-in effect of the title bar of the conversation every time an update happens and the title bar is redrawn, which apparently is part of the EMUI featureset. It usually happens three times every time I sent a message. 
I managed to stop it from happening at least inside a conversation by commenting out updateActionBarTitle(); on line 1743 of the ConversationActivity.java (in the refreshUiReal() definition). I didn't see any other negative effect - it actually became more snappy. I didn't try it in a conference though, only on a single conversation. Exiting and entering the conversation was correctly updating the title bar. Is there a particular reason it is required to refresh the action bar title so many times? 
I'm no java developer so I can't be sure whether I didn't break something - I can try to create a PR if you want but I guess you would like to make more changes than just a commenting-out of a line.

**Comment by herrwusel** [comment]
I have the same problem. I tried to contact Huawei about the problem but couldn't describe the flickering precisley as you did @athanasio. Maybe you can head to Huawei support with your findings.

**Comment by iNPUTmice** [comment]
> Is there a particular reason it is required to refresh the action bar title so many times?

I general now. However when the subject in a conference changes (or the display name of a contact) it is required to update the action bar title.
What we could do however is something like `if (!actionbar.getTitle().equals(new_title)) actionbar.setTitle(new_title));`
Feel free to check if this helps. I imagine it will still flicker when switching between conversations.

**Comment by athanasio** [comment]
Hello again,
I've pinpointed the problem in setDisplayHomeAsUpEnabled(), it seems to redraw the whole ActionBar when enabled/disabled, and this action is greatly smoothed by EMUI 5.0 with a fade animation. When power-saving features are enabled on the phone, animations are reduced or removed and the problem almost disappears as well. I've implemented a solution based on what you proposed (check if the title has changed) and it seems to work well for most of the cases, which is good enough for now. I'll send a pull request for you to consider.
The problem seems to be Theme.Material connected. I've implemented a (buggy) solution of using Theme.AppCompat instead of Holo/Material, and it looks like it is also solving the problem - I don't know if you want to go to that direction. I looked into the parameters of Theme.Material, and I couldn't find out how I can change the transition timings which could be another mitigation. If you or anyone else wants to look at it, please do.

**Comment by iNPUTmice** [comment]
@athanasio the status of DisplayHomeAsUp can probably be queried by Actionbar.getDisplayOptions() (there is a constant called ActionBar.DISPLAY_HOME_AS_UP) and with that help we can probably only update the actionbar when this variable needs to change.
This is better than the 'hack' with the title becaus the title hacks fails in (rare cases) where app-name = conversation name.

**Comment by iNPUTmice** [comment]
does abaabae853f67b4048b194131bd7b72114e86ba1 fixes this for you?

**Comment by athanasio** [comment]
yes it does, thanks very much!
