### ISSUE TITLE
Cannot downgrade to 1.15.0

### ISSUE THREAD

**Issue by astro** [siacs/Conversations#2203]
I upgraded to 1.15.1 which doesn't work. The next version hasn't arrived in F-Droid yet. Unfortunately, downgrading doesn't work either. There is not much output in adb regarding that.

**Can I download the new release's apk somewhere?**

I tried building Conversations myself but failed to correlate missing dependency messages with the package names in the Google SDK manager UI.

**Comment by iNPUTmice** [comment]
You can not switch between versions signed with a different release key. Even if you'd be able to download the official PlayStore version without the PlayStore you couldn't install it over your Fdroid version.
A fresh install (which means loosing your data) would work of course though.

**Comment by mimi89999** [comment]
@astro I am using version 1.15.1 from F-Droid and I don't have any major issues with it...

**Comment by astro** [comment]
1.15.2 just landed in F-Droid \o/

**Comment by mimi89999** [comment]
@astro Did 1.15.2 fix your issue(s)?

**Comment by astro** [comment]
Yes, just as you said in #2200 :-)

Sorry for bothering and thank you all once again for your great work! See you at 33c3?
