### ISSUE TITLE
Missing documentation for security icons

### ISSUE THREAD

**Issue by DreamFlasher** [siacs/Conversations#2204]
In the last months (different conversations versions) I've observed the following icons below my chat messages: Grey lock, red lock and grey shield. 
What is the meaning of the symbols? Especially the red lock looked like an error. People who are using conversations.im are interested in security, so it makes sense to document the meaning of the symbols somewhere. 

#### General information

* **Version:** 1.15.2
* **Device:** BlackBerry Priv
* **Android Version:** Android 6.0

**Comment by licaon-kter** [comment]
See https://github.com/siacs/Conversations/blob/master/README.md

**Comment by DreamFlasher** [comment]
Thank you! A quick google search didn't bring up anything (also part why I created this issue) and there is no in-app documentation of this. Imho there should be an info when you longpress on the message. 
Furthermore it's not clear how to change the grey lock to the grey shield (how to do the verification).

**Comment by licaon-kter** [comment]
Yes, and that link explains what you need to do, either verify or disable BlindTrust in Settings.

**Comment by DreamFlasher** [comment]
It doesn't explain the difference between the grey lock and the grey shield.
Furthermore I can't find a possibility to share my barcode on social media. I can of course display it -- but then what?

**Comment by licaon-kter** [comment]
Close this and voice your opinion on https://github.com/siacs/Conversations/issues/2166

**Comment by DreamFlasher** [comment]
I will do that, thank you! :)

**Comment by griffindoors** [comment]
> https://github.com/siacs/Conversations/blob/master/README.md

Where in the ui is there an option to spawn this url in a browser?
