### ISSUE TITLE
Feature Request: urn:xmpp:mam:1

### ISSUE THREAD

**Issue by asgharkhare2016** [siacs/Conversations#2205]
version 0.5.1 of xep-0313 (the latest version till now) does not supported by conversations. Tigase xmpp server v 7.2.0 only support this version of message archiving management.
is it possible to add support for 'urn:xmpp:mam:1' ?

**Comment by iNPUTmice** [comment]
Can you provide me with a test account on a Tigase server?

**Comment by asgharkhare2016** [comment]
It's on my local host, 
one of the differences in tigase is service discovery string, it sends urn:xmpp:archive:manage instead of urn:xmpp:mam:1
another difference from xep-0313 is, it sends the result set without first and last tags:
```
<iq type='result' id='q29302'>
  <fin xmlns='urn:xmpp:mam:1'>
    <set xmlns='http://jabber.org/protocol/rsm'>
      <count>20</count>
    </set>
  </fin>
</iq>
```
but the rest of the implementation of tigase 7.2.0 message archiving is based on xep-0313 v 0.5.1.

**Comment by devurandom** [comment]
Prosody 0.10 in Hg also [switched to urn:xmpp:mam:1](https://hg.prosody.im/0.10/file/tip/plugins/mod_mam/mod_mam.lua#l12). (The module was [previously provided via prosody-modules](https://hg.prosody.im/prosody-modules/file/tip/mod_mam/mod_mam.lua).)

**Comment by iNPUTmice** [comment]
MAM namespace was bumped in b90a1fe1db9b19547093474da4b6af727570fd13
