### ISSUE TITLE
dont close conversations by wiping to the left

### ISSUE THREAD

**Issue by treakiandroid** [siacs/Conversations#2208]
hi,

if you are inside a conversation and just want to view the list of other's, you would wipe from the left edge of the screen to the right, the oposit you would do to close it again, but if you do that it is much to easy to start wiping to the left inside the conversation list area not outside. Thereby you would end a conversation but not close the list of conversations. So if you could improve the that so conversations can only closed by wiping to the right, not to the left (same as closing the list) you would prevent a lot of accidentally closing conversation's.

thanks

**Comment by BlauerHunger** [comment]
I think this is solved
