### ISSUE TITLE
feature request, easier enabling omemo on multi user chats

### ISSUE THREAD

**Issue by treakiandroid** [siacs/Conversations#2209]
hi,

it lookes like everyone inside an omemo chat must have enabled omemo in privat chat with all other members. That's very complicated, maybe you schould add a feature which makes that more easy.

thanks

**Comment by BlauerHunger** [comment]
What kind of feature do you think of? Option for adding all muc members to roster and retrieving all omemo identities?

**Comment by treakiandroid** [comment]
yes, something like that, or maybe just reviving there omemo keys without adding to contact list

**Comment by treakiandroid** [comment]
with pgp it uses keyserver for all recipient s but here it should be as easy as. at least i would like a message like you still have to add/verify/whatever until you can, instead of making the omemo action gray

**Comment by treakiandroid** [comment]
like it is now the end to end encryption cant be used for large groups where not all persons know each other by there self's

**Comment by BlauerHunger** [comment]
Afaik the omemo prekeys can only be retrieved if you accept the requesting person to your roster

**Comment by iNPUTmice** [comment]
OMEMO currently needs mutual presence subscription with every participant in the MUC.

**Comment by orlyjamie** [comment]
I might be bothered to port OMEMO to utilise XEP-0189, what do you think @iNPUTmice? 

This way we can benefit from the existing key pinning that Conversations does as well as not rely on presence subscription among users for key retrieval.

**Comment by licaon-kter** [comment]
@orlyjamie we are well beyond this 2016 issue, prosody and ejabberd since 2018 will help an encrypted group chat members to get each others keys

**Comment by orlyjamie** [comment]
Thanks @licaon-kter can you share with me the specific link for ejabberd, are you talking about XEP-0189 or something else?
