### ISSUE TITLE
problem with scanning own fingerprints twice

### ISSUE THREAD

**Issue by treakiandroid** [siacs/Conversations#2211]
latest froid version,

i tryed now where you have made it nessesery to scan codes (where earlier just validing the fingerprints manual) to scan the codes of my own devices. once i scanned the same code twice, the problem with that was that the secound time it tryed to add myself to the contact list. please fix that and make sure a sensible action happened with scanning an already scanned code (no matter if its from an own account or not). Like opening the key view and showing a note, code already verified.

thanks

**Comment by mimi89999** [comment]
There is an icon indicating, that a key is verified.
