### ISSUE TITLE
Missing documentation: Publish OpenPGP Key

### ISSUE THREAD

**Issue by DreamFlasher** [siacs/Conversations#2213]
A Google search did not yield any information on this feature, that's why I'm creating this issue for future reference. 

What does Publish OpenPGP key do?
Where does it publish the key?

**Comment by mimi89999** [comment]
Guessing it is publishing the public PGP/GPG key via PEP.

**Comment by DreamFlasher** [comment]
Do you have a reference what this does? It's different from publishing to a keyserver right?

**Comment by iNPUTmice** [comment]
It signs your presence. Documentation can be found in XEP-0027.

**Comment by DreamFlasher** [comment]
Thank you Daniel!
