### ISSUE TITLE
Online status of "buddy" is wrong and inconsistent

### ISSUE THREAD

**Issue by netge** [siacs/Conversations#2215]
#### General information

* **Version:**
1.14.6
* **Device:**
Sony Xperia T, Huawei GR3, Motorola Moto G3
* **Android Version:**
4.3, 5.1, 5.1 CyanogenMod
* **Server name:**
chinwag.im
* **Server software:**
prosody
* **Installed server modules:**
Server has all recommended features according to your list
* **Conversations source:** 
F-Droid
* **Encryption:**
OMEMO

#### Steps to reproduce

1. Switch on two phones, start Conversations app, walk around the city or do something else, not sure if that matters, all power saving magic disabled as far as possible on all phones
2. check online status of buddy

#### Expected result

What is the expected output? What do you see instead?
Standing next to my buddy, both of us with phones in our hands, connected to Internet, looking at Conversations app, sometimes me or my buddy is shown as Offline.

This frequently happens when using mobile data; not sure I ever saw this while on WIFI.

Also the Online status is sometimes inconsistent between tag shown in buddy list when I press (+) and the "send arrow", i.e. for example the tag shows "Online" and the "send arrow" is grey (not green) or vice versa.

#### Debug output

Attached (does not seem to contain anything useful)
Comment lines starting with *** describe what I did at that time.
Log is same as for #2216.

[2016-12-30-14-09-51-adb-clean.txt](https://github.com/siacs/Conversations/files/678931/2016-12-30-14-09-51-adb-clean.txt)

**Comment by licaon-kter** [comment]
Could you update to the latest version and retest?

**Comment by netge** [comment]
Not sure. My "users" have lost trust and patience (understandably). Will try but it could take some time.

**Comment by licaon-kter** [comment]
And they don't update any of their apps?

**Comment by netge** [comment]
Rarely solves any problems. But will try to get them to do so.

**Comment by licaon-kter** [comment]
Given the amount of issues you see here that get fixed I'm not sure what you base that statement on.
The nature of the project, open source, makes things pretty transparent, bug wise and development wise.

**Comment by netge** [comment]
It was more of a general comment about software and automatic updates; not referring to this project in particular.

**Comment by iNPUTmice** [comment]
The send button incorporates your own status as well. Meaning if you are currently offline the send button is gray as well.
