### ISSUE TITLE
Message delivery unreliable and delayed

### ISSUE THREAD

**Issue by netge** [siacs/Conversations#2216]
[2016-12-30-14-09-51-adb-clean.txt](https://github.com/siacs/Conversations/files/678930/2016-12-30-14-09-51-adb-clean.txt)
#### General information

* **Version:**
1.14.6
* **Device:**
Sony Xperia T, Huawei GR3, Motorola Moto G3
* **Android Version:**
4.3, 5.1, 5.1 CyanogenMod
* **Server name:**
chinwag.im
* **Server software:**
prosody
* **Installed server modules:**
Server has all recommended features according to your list
* **Conversations source:** 
F-Droid
* **Encryption:**
OMEMO

#### Steps to reproduce

1. Switch on two phones, start Conversations app, walk around the city or do something else, not sure if that matters, all power saving magic disabled as far as possible on all phones
2. send messages to buddy

#### Expected result

What is the expected output? What do you see instead?
First messages were received. Then 2 message were not received even after about 1 hour. Even standing next to my buddy, both of us with phones in our hands, connected to Internet, looking at Conversations app, the messages were not there.

This happened when using mobile data; not sure I ever saw this while on WIFI.

When checking again 2 hours later, the messages were there (we were on WIFI by that time, ie. connectivity changed in between).

I do not think the server was down; I use it from my desktop all day long and it seems to be highly available.

Have been trying to get Conversations to work reliably for about 12 months now but it seems impossible. 4 different phones, no single pair works reliably.

#### Debug output

Attached (does not seem to contain anything useful)
Comment lines starting with *** describe what I did at that time.

**Comment by licaon-kter** [comment]
As the other one, always report bugs using the latest version, 1.15.2 now.

**Comment by iNPUTmice** [comment]
Are you using OTR?

**Comment by netge** [comment]
I had pretty much the same problem a couple of months ago. Since then I
a) switched from OTR to OMEMO
b) switched to a server with all the features required
c) updated Conversations
But symptoms are still the same.

**Comment by iNPUTmice** [comment]
From what I gather from the comments in the logcat the message are not stuck at sending or waiting but simply don't have a check mark. If that's the case the problem is on the receiving end. Try disable power and traffic savers on the receiving end and maybe enable the foreground service.

**Comment by netge** [comment]
As I wrote, we were standing side by side, phones online, Conversations running and messages were not received. Next time I will try to remember and check on both phones whether each is logged in to the account.  On two other occasions, when I went into "Manage Accounts" I found that login had failed. Flipping the knob next to the account solved the problem, but it had not happened automatically.

**Comment by mimi89999** [comment]
@netge What if you disable OMEMO? Does the problem persist?
