### ISSUE TITLE
Changing avatar origin from PEP to vcard

### ISSUE THREAD

**Issue by Aasaqt** [siacs/Conversations#2221]
Hey
I currently want to change the avatar origin from PEP to vcard . Is there any method I can use vcard rather than pep for fetching and publishing avatars because all my other server are using Vcard for fetching and publishing avatars.

**Comment by Natureshadow** [comment]
I have also always been in desperate need for this!

**Comment by iNPUTmice** [comment]
No. Search the issue tracker for vcard for the reasons on why we don't use vcards.
