### ISSUE TITLE
Wrong domain for HTTP Uploads

### ISSUE THREAD

**Issue by ValdikSS** [siacs/Conversations#2222]
#### General information

* **Version:** 1.15.2
* **Device:** Blackberry Q10
* **Android Version:** Android 4.3 compatibility layer
* **Server name:** Self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** Stream Managment, CSI, MAM,  HTTP Upload
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Configure prosody to announce HTTP Upload on upload.xmppdomain.com
2. Try to upload file from Conversations

#### Expected result

Conversations grab upload slot and contact upload.xmppdomain.com for file upload

#### Actual result

Conversations tries to upload to the main domain xmppdomain.com.

#### Debug output

```
<iq type="result" to="iam@valdikss.org.ru/laptop" id="ab47a" from="xup.valdikss.org.ru">
<query xmlns="http://jabber.org/protocol/disco#info">
<identity type="file" category="store" name="HTTP File Upload"/>
<feature var="urn:xmpp:http:upload"/>
<feature var="http://jabber.org/protocol/disco#info"/>
<feature var="http://jabber.org/protocol/disco#items"/>
<x xmlns="jabber:x:data" type="result">
<field type="hidden" var="FORM_TYPE">
<value>urn:xmpp:http:upload</value>
</field>
<field type="text-single" var="max-file-size">
<value>10485760</value>
</field>
</x>
</query>
</iq>

D/conversations( 2337): uploading to https://valdikss.org.ru:5281/upload/e57110fa-fa11-4616-9abe-42979edc60f3/815f94ab-ee9a-4bad-a92f-ced516bad93e.jpg
D/conversations( 2337): http upload failed failed to connect to valdikss.org.ru/5.45.183.10 (port 5281) after 15000ms: isConnected failed: ECONNREFUSED (Connection refused)
```

**Comment by ValdikSS** [comment]
Server has been configured to announce HTTP Upload on both main and subdomain. Sorry for the hassle.

**Comment by raudy66** [comment]
Hi Valdik,
I have a related question to you.
How do I know which port to open for http_upload? I can not find good documentation. 
Is the one shown in your logfile standard? If not - where can I change it?
Port 5281
Greetings

**Comment by ValdikSS** [comment]
@raudy66 Well you configure it yourself. Default port depends on your XMPP server.
