### ISSUE TITLE
Client goes offline although "keep service in foreground" is activated.

### ISSUE THREAD

**Issue by michel2323** [siacs/Conversations#2225]
#### General information

Conversations disconnects after a while. I suppose it is killed. The workaround used to be to enable "keep in forground". However, since 7.1.1, this does not work anymore. I cannot receive messages even with push activated while the phone is in standby.

* **Version:** 1.15.2
* **Device:** Nexus 5X
* **Android Version:** Stock 7.1.1
* **Server name:** self hosted
* **Server software:** Prosody 0.9.11
* **Installed server modules:** PEP, Stream Management, Roster Versioning, Message Carbons, MAM, Client State Indication, Push, HTTP File Upload
* **Conversations source:** Play Store
#### Steps to reproduce

1. Switch off screen of the phone and wait
2. Conversation disconnects and my status is offline for my buddies

#### Expected result

Stay only continuously while being able to receive messages. 

#### Debug output

There is no crash or system output in the debug log. In the main section there are messages in cleartext, so I won't post them here. I suppose it's the log since the last restart, starting with all the messages being received that were sent while I was offline.

**Comment by iNPUTmice** [comment]
You might want to disable doze for Conversations.

**Comment by michel2323** [comment]
Thank you very much. That does the trick. I can now even disable "keep service in foreground". This however a tad bit confusing for less technically skilled users. Can't doze for conversations be disabled by default?

**Comment by licaon-kter** [comment]
> Can't doze for conversations be disabled by default?

Nope, complain to Google, it's their policy.

**Comment by michel2323** [comment]
I certainly don't blame you.

Unfortunately, it still happens with doze disabled for conversations and "keep service in foreground" activated. Just to let you know.

**Comment by iNPUTmice** [comment]
> Unfortunately, it still happens with doze disabled for Conversations and "keep service in foreground" activated.

Your client goes offline even though you have doze disabled?

**Comment by michel2323** [comment]
Yes. Happened several times now on mobile and on wifi. It reconnects after using the phone for a while, when the messages are received in bulk, all at once.

**Comment by iNPUTmice** [comment]
I can't reproduce this. Same phone; same OS. And adb logcat will be helpful. You can of course remove the messages.

**Comment by mimi89999** [comment]
@michel2323 Check the server log...

**Comment by michel2323** [comment]
It happened two times now in 3 days. It seems it's just when the connection is lost. I guess it is resolved then.
