### ISSUE TITLE
Avatar publication does not work with Openfire 4.1.1

### ISSUE THREAD

**Issue by Dehumanizer77** [siacs/Conversations#2229]
#### General information

* **Version:** eg 1.15.2
* **Device:** Lenovo P70
* **Android Version:** Android 5.1 Cyanogenmod 12.1
* **Server name:** self hosted
* **Server software:**  Openfire 4.1.1
* **Installed server modules:** 
* **Conversations source:** F-Droid

#### Steps to reproduce

1. long press manage accounts
2. select "publish avatar"
3. click avatar
4. select an image
5. press "publish" 

#### Expected result

The avatar should get published

#### Actual result

Error message "The server rejected your publication" appears. 
Openfire supports avatar publication as per their website: http://download.igniterealtime.org/openfire/docs/latest/documentation/protocol-support.html

#### Debug output

No relevant logs come out of logcat. After the initial startup, no log output is beeing produced while setting up and unsuccessfull publication of the avatar. The last two lines are:
D/conversations(11227): user@server: finished mam after 0 messages. messages left=true
D/conversations(11227): app switched into background

**Comment by Dehumanizer77** [comment]
Note: when I update the avatar using other client (psi+ on desktop), the avatar even correctly updates in Conversations, so it's clearly not a server-side issue.

**Comment by andersruneson** [comment]
Does the other clients you tested use pep avatars? Last time I used
openfire it did NOT support pep avatars.

**Comment by Dehumanizer77** [comment]
I see, you might be right, I haven't thought about this. And I just read some comments that the PEP support is incomplete so OMEMO also doesn't work with Openfire. My fault, sorry, closing the issue now.
