### ISSUE TITLE
Self-destructing messages

### ISSUE THREAD

**Issue by Sirove** [siacs/Conversations#2231]
A Self-destruct timer as in Telegram would be a really useful privacy enhancement in case your phone gets stolen.

**Comment by iNPUTmice** [comment]
Please search the issue tracker for duplicate issues before you create new ones. #2223

**Comment by licaon-kter** [comment]
> in case your phone gets stolen

The encryption will protect you.

**Comment by Natureshadow** [comment]
Can't we put up a big sign somewhere, saying "If you think any data can
reliably do such a thing as self-distruct, you are completely lost and
probably shouldn't be drafting privacy features"?
