### ISSUE TITLE
Support s/foo/bar/ for last message correction

### ISSUE THREAD

**Issue by Natureshadow** [siacs/Conversations#2232]
Writing a message only containing a regex replacement of the form s/foo/bar/ could trigger the last message correction feature, applying the replacement to the last message.

Skype does this ever since it got support for message correction, so I suppose it's something also non-tech-savvy people use.

**Comment by griffindoors** [comment]
could not also click-holding a message be used to edit?

Otherwise i forsee fun with macros:  send message, wait ms, send correction

**Comment by supreme96** [comment]
Hi.
It seems like the click-holding and editing feature is already available on a one to one chat. It is however yet unavailable for group chats. If nobody's working on this, I would like to work on this issue.

**Comment by supreme96** [comment]
One more thing I would like to add is that it would probably a useful little feature to notify the recipient which particular message in the history has been corrected.

**Comment by hareshkh** [comment]
@supreme96 : Are you working on this?

**Comment by supreme96** [comment]
@hareshkh yeah. I'm working on this one.

**Comment by uchchishta** [comment]
@Supreme96 regarding it not working in mucs, it is available only in private mucs (it was actually removed from anon mucs)

**Comment by supreme96** [comment]
@uchchishta i dont understand what mucs is.

**Comment by licaon-kter** [comment]
MUC  - multi user conference

**Comment by supreme96** [comment]
@licaon-kter thnx for the simplification
 and 
@uchchishta i figured that it was available in the private mucs, so i dont think we really have a need for any changes to this feature here. however i still think working on having a notification when a message has been edited would be useful.

**Comment by uchchishta** [comment]
@supreme96 yes.

**Comment by daivat15** [comment]
Can someone just explain the meaning of 's/foo/bar' please.

**Comment by SoyaLeaf** [comment]
@daivat15  maybe :) 
https://en.wikipedia.org/wiki/Foobar

**Comment by SamWhited** [comment]
@daivat15 this means "replace the word 'foo' with the word 'bar'". It's the way you write find and replace sccripts in [sed(1)](https://www.freebsd.org/cgi/man.cgi?query=sed&sektion=1) tool. Sorry for the confusion!

**Comment by harshitbansal05** [comment]
@iNPUTmice can I work on it?

**Comment by iNPUTmice** [comment]
I think this is a feature we don’t really need. Too niche. People rarely use hardware keyboards with Conversations anyway.
