### ISSUE TITLE
"automagically select default encryption" as an Option

### ISSUE THREAD

**Issue by matthaab** [siacs/Conversations#2234]
It would be very nice to have that that as an option. Maybe in the "expert-option" menu.

**Comment by licaon-kter** [comment]
You did read the part about default encryption in the Readme, right?

**Comment by matthaab** [comment]
Sure

**Comment by LogicParrot** [comment]
Note that with the recent update, `OMEMO` is somewhat "automagical" if the two sides support it.
See: https://gultsch.de/trust.html

**Comment by iNPUTmice** [comment]
We won't provide a setting to control the default setting for another setting.
When the time is right we'll enable OMEMO by default. By the time isn't right yet.

**Comment by flosse** [comment]
> When the time is right we'll enable OMEMO by default. By the time isn't right yet.

What has to happen that you'd say it's the right time? What are the criteria?

**Comment by licaon-kter** [comment]
Other clients support, stable server support, I guess.
