### ISSUE TITLE
Humongous data usage

### ISSUE THREAD

**Issue by Rudd-O** [siacs/Conversations#2236]
#### General information

Latest stable on F-Droid on copperhead OS in a Nexus 5X device.  Servers used: gmail's xmpp and jabber CCC.

NO images or audio transferred during this period of time.  See data usage in screenshot.
![screenshot_20170117-012406](https://cloud.githubusercontent.com/assets/346306/22003466/c300e302-dc4b-11e6-831c-08cfcc97d734.png)

What happened?

**Comment by licaon-kter** [comment]
Can you test with a server that supports MAM ( see here: https://gultsch.de/compliance.html ) ?

**Comment by Rudd-O** [comment]
On 01/17/2017 06:33 AM, licaon-kter wrote:
>
> Can you test with a server that supports MAM ( see here:
> https://gultsch.de/compliance.html ) ?
>

Probably not, because I need to remain on the Google XMPP server and the
CCC server for Conversations to be useful on a daily basis :-(

-- 

    Rudd-O
    http://rudd-o.com/

**Comment by iNPUTmice** [comment]
If I were to guess it's probably a combination of a bad network (maybe low NAT timeouts) and the gmail XMPP server not supporting Stream Management.
You can temporarily disable the gmail account to see if this is the gmail account causing this.
If you want to steer towards a solution you can try to lower the ping timeout in the Config.java to maybe a minute or so.
In any case without adb logcat these are only guesses.

**Comment by gjedeer** [comment]
Maybe just add the gmail account as a transport on your XMPP account? That works for me and, since the main XMPP server supports all the modern XEPs, I get to use gtalk and have low data usage.
