### ISSUE TITLE
How to prevent notification "Touch to open Conversations"

### ISSUE THREAD

**Issue by PanderMusubi** [siacs/Conversations#2239]
#### General information

* **Version:** 1.15.3
* **Device:** One Plus One
* **Android Version:** Android 6.0.1 Cyanogen OS 13.1.2
* **Server name:** n/a
* **Server software:** n/a
* **Installed server modules:** n/a
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Use conversation with several acounts and rooms
2. Disable notification of any kind

#### Expected result

What is the expected output?

Not to see the notification "Touch to open Conversations"

 What do you see instead?

At least daily the notification "Touch to open Conversations"

**Comment by mimi89999** [comment]
@PanderMusubi 
It is the "keep service on first plan" that gets activated when Conversations detects that the connection is being killed.

**Comment by PanderMusubi** [comment]
Duplicate of which issue, please?

**Comment by licaon-kter** [comment]
#2160

**Comment by tmolitor-stud-tu** [comment]
Wouldn't it be better to only disable the automatic foreground enabler when conversations is configured to not show notifications?
The automatic foreground enabler is really useful imho.

**Comment by licaon-kter** [comment]
Is anyone using any chat app without notifications? What does that work, you open it from time to time?

**Comment by tmolitor-stud-tu** [comment]
@licaon-kter I don't know anyone, but it was the usecase PanderMusubi described (point 2: disable any notifications). So it would be enough to disable the automatic foreground enabler for this specific usecase instead of disabling it for everyone.

At least if there aren't more complaints about this feature (and I doubt so).

**Comment by licaon-kter** [comment]
After the last commits foreground will not active automaticly, brace yourselves for the "Conversations closes itself" issues as ROMs "optimize" memory usage or users swipe the app and are surprised that it gets killed.

**Comment by PanderMusubi** [comment]
My colleagues and me use it without notifications, we use other channels to notify we will start a chat there. For the rest, we check regularly when it is convenient to us if there are new messages. So an option in settings to enable or disable this would have our preference.

**Comment by licaon-kter** [comment]
So, in expert settings enable foreground and in Android notifications settings block/hide Conversations notifications. Simples.

**Comment by PanderMusubi** [comment]
I already have these settings but that doesn't do it.

**Comment by licaon-kter** [comment]
What do you mean? Hiding the notification with Android settings does not actually work?

**Comment by PanderMusubi** [comment]
Ah, okay, found the "Block all" for Conversations in Android App notifications. However, I do think that this should be configurable from within the app. Sometimes we do work with notifications for a short time and a 'one stop shop' for controlling this should be settings from the app itself. If (some of) you agree, please reopen this issue.

**Comment by iNPUTmice** [comment]
@PanderMusubi this issue was about making the parament notification go away. This has been implement in 1.15.5. (You only have to disable this one more time in the settings)
