### ISSUE TITLE
Side menu last message status

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2240]
Now we have the last message only, it would be nice to have all the icons the message has too eg: encryption lock, trust/validation shield, read checkmark.

**Comment by licaon-kter** [comment]
Also to clarify who wrote what maybe add "Me: " if the (that) last message is actually mine.

**Comment by hareshkh** [comment]
@licaon-kter, @iNPUTmice : Now that #2335 is merged I would like to work on this. We can have a discussion on how to implement this. Moreover does the current message entity provide me with the sender?

**Comment by uchchishta** [comment]
It would be nice if there was a count badge above bell icon showing how many times I was mentioned if I had set it to notify only when mentioned..

**Comment by hareshkh** [comment]
@uchchishta, the bell icon is itself very small. So showing a count badge on top of that wont look very good on the UI. What do you say @iNPUTmice?

**Comment by iNPUTmice** [comment]
let's leave it as it is for now. I'm currently considering changing the unread count to reflect the number of mentions in 'mention only' MUCs.

**Comment by hareshkh** [comment]
@iNPUTmice, that will be great. I would like to work on it.

**Comment by licaon-kter** [comment]
Thanks
