### ISSUE TITLE
When starting the app the first conversation in conversations list is not in bold despite there are new messages

### ISSUE THREAD

**Issue by srgcdev** [siacs/Conversations#2245]
#### General information

* **Version:** eg 1.15.4
* **Device:** eg Google Nexus 5x
* **Android Version:** Android 6.0 Cyanogenmod
* **Server name:** conversations.im
* **Server software:** ejabberd 16.09
* **Installed server modules:** Stream Managment, CSI, MAM...
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Turn the phone off for a while
2. Turn the phone on
3. I have some new messages from rooms but the conversation in the first place in the conversations list is not with the text in bold. The others conversations with new messages are in bold.

**Comment by licaon-kter** [comment]
You mean "the open conversation is not bold" ? That's normal.
