### ISSUE TITLE
Having Issues Connecting

### ISSUE THREAD

**Issue by Taekus** [siacs/Conversations#2249]
#### General information

* **Version:** 1.15.4
* **Device:** LG K10 (LG-K428)
* **Android Version:** Android6.0.1
* **Server name:** Self Hosted
* **Server software:** Openfire 4.2.2
* **Installed server modules:** None
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Install Application
2. Attempt to Connect to Self Hosted Server.

#### Expected result

What is the expected output? What do you see instead?
Expected Outout, Successfull connection.
Instead, No Connection

#### Debug output

01-20 11:54:12.582 D/conversations(11022): taek@host.omitted: connecting
01-20 11:54:12.662 D/conversations(11022): used lollipop variant to discover dns servers in 2 networks
01-20 11:54:12.662 D/conversations(11022): using dns server: ip.omitted to look up host.omitted
01-20 11:54:27.657 D/conversations(11022): using dns server: ip.omitted to look up host.omitted
01-20 11:54:27.754 D/conversations(11022): taek@host.omitted: using values from dns host.omitted[ip.omitted]:5222 tls: false
01-20 11:54:28.100 D/conversations(11022): taek@host.omitted: TLS connection established
01-20 11:54:28.102 D/conversations(11022): taek@host.omitted: xml parser mishandled javax.net.ssl.SSLProtocolException
01-20 11:54:32.710 D/conversations(11022): taek@host.omitted: sending offline presence
01-20 11:54:32.710 D/conversations(11022): taek@host.omitted: disconnecting force=false
01-20 11:54:32.710 D/conversations(11022): taek@host.omitted: closing stream
01-20 11:54:32.711 D/conversations(11022): taek@host.omitted: io exception during disconnect (Socket is closed)

**Comment by iNPUTmice** [comment]
My guess would be an outdated TLS stack in an old Java runtime.

**Comment by mimi89999** [comment]
@Taekus Probably an error on the server side.

**Comment by Taekus** [comment]
From what I can guess, the DNS SRC records are broken.

**Comment by iNPUTmice** [comment]
> From what I can guess, the DNS SRC records are broken.

Ok? Fix your DNS then?

**Comment by Taekus** [comment]
What ever the issue is, it's Conversations. Pidgin, Gajim and ChatSecure all have no problem connecting to my server.

**Comment by mimi89999** [comment]
@Taekus Try with a different server.

**Comment by Taekus** [comment]
Seems the issue has something to do with using Port 5222, it connected when I told it to use Legacy Port 5223

**Comment by iNPUTmice** [comment]
If you share your domain with us we might be able to have a look. But in general we can't provide support on how to setup your own XMPP server.

**Comment by iNPUTmice** [comment]
Apparently there seems to be something weird about the certificate that makes Android 6.0 unable to connect. The detailed error messages looks like this:
```
01-21 21:11:57.220 D/conversations( 6185): teak@missingtech.net: using values from dns im.missingtech.net[98.244.9.197]:5222 tls: false
01-21 21:11:59.088 D/conversations( 6185): teak@missingtech.net: TLS connection established
01-21 21:11:59.089 D/conversations( 6185): teak@missingtech.net: xml parser mishandled SSLProtocolException(Read error: ssl=0xb7b23eb8: Failure in SSL library, usually a protocol error
01-21 21:11:59.089 D/conversations( 6185): error:0c0890ba:ASN.1 encoding routines:asn1_check_tlen:WRONG_TAG (external/boringssl/src/crypto/asn1/tasn_dec.c:1313 0xaa0db50f:0x00000000)
01-21 21:11:59.089 D/conversations( 6185): error:0c09309d:ASN.1 encoding routines:asn1_template_ex_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:572 0xb7abf368:0x00000001)
01-21 21:11:59.089 D/conversations( 6185): error:0c09409d:ASN.1 encoding routines:asn1_template_noexp_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:735 0xaa0db50f:0x00000000)
01-21 21:11:59.089 D/conversations( 6185): error:0c07909d:ASN.1 encoding routines:ASN1_item_ex_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:343 0xb76f4810:0x00000001)
01-21 21:11:59.089 D/conversations( 6185): error:0c09409d:ASN.1 encoding routines:asn1_template_noexp_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:711 0xaa0db50f:0x00000000))
```
Googling did not bring up much. Something about comments in the certs maybe? All I can say is that it is working fine on my Android 7.1

**Comment by Taekus** [comment]
Since the Openfire server is being setup with a new domain name I would rather not release server details publically. However, You can contact me directly over XMPP: taek@kode.im

**Comment by iNPUTmice** [comment]
@Taekus have you seen my previous answer? Please check your certificate.

**Comment by Taekus** [comment]
Okay, so the issue with the connection is a crappy SSLv3 protocol that Openfire ships with, sometimes on installation it is enabled, sometimes it's not. I now have it working. Manually disabling the SSLv3 protocol in the Client Connection Properties on Openfire 4.2.2 does not disable it.

**Comment by danielrosero** [comment]
@Taekus Hey, I'm aslo facing this issue. How did you disable it? can you help me out?

**Comment by Taekus** [comment]
You have to disable SSLv3 in the client - Also i've since switched to prosody and have had Zero issues.

**Comment by danielrosero** [comment]
I tried disabling it through Server Settings > Client Connection > Advanced
configuration and then unchecked SSLv3, but nothing happened. Do you know
another way to do it?

Thanks

**Comment by Taekus** [comment]
Depending on the version of Openfire, you may have to disable SSLv3 in the server configuration also. Since it would try to force the client to use SSLv3 also.

**Comment by mortezaadi** [comment]
This is nothing to do with openfire i believe, I can connect with other jabber client to the same server, I used Empathy to test the client connection and it works fine. also text secure works with same server.
I'm getting this error in conversation.

java.io.IOException: xml parser mishandled SSLProtocolException(Read error: ssl=0xaab287c0: Failure in SSL library, usually a protocol error
error:0c0890ba:ASN.1 encoding routines:asn1_check_tlen:WRONG_TAG (external/boringssl/src/crypto/asn1/tasn_dec.c:1313 0xaac72d97:0x00000000)
error:0c09309d:ASN.1 encoding routines:asn1_template_ex_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:572 0xa15888a0:0x00000001)
error:0c09409d:ASN.1 encoding routines:asn1_template_noexp_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:735 0xaac72d97:0x00000000)
error:0c07909d:ASN.1 encoding routines:ASN1_item_ex_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:343 0xa1588900:0x00000001)
error:0c09409d:ASN.1 encoding routines:asn1_template_noexp_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:711 0xaac72d97:0x00000000))


javax.net.ssl.SSLProtocolException: Read error: ssl=0xaab287c0: Failure in SSL library, usually a protocol error
error:0c0890ba:ASN.1 encoding routines:asn1_check_tlen:WRONG_TAG (external/boringssl/src/crypto/asn1/tasn_dec.c:1313 0xaac72d97:0x00000000)
error:0c09309d:ASN.1 encoding routines:asn1_template_ex_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:572 0xa15888a0:0x00000001)
error:0c09409d:ASN.1 encoding routines:asn1_template_noexp_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:735 0xaac72d97:0x00000000)
error:0c07909d:ASN.1 encoding routines:ASN1_item_ex_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:343 0xa1588900:0x00000001)
error:0c09409d:ASN.1 encoding routines:asn1_template_noexp_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:711 0xaac72d97:0x00000000)

**Comment by iNPUTmice** [comment]
@mortezaadi the TLS stacks of Android/Conversations and OpenFire (Are you using Windows?) seem to be incompatible to each other. I don't know why. If you find a work around on the Conversations side of things I'm happy to merge them.

**Comment by mortezaadi** [comment]
@iNPUTmice  I'm using fedora 23(64bit) and ran the conversations on android 5 emulator and also android 7 (samsung galaxy 8 device) end up with the same result. I'm not familiar to conversations SSL handshake process though I'm trying to find a workaround.
 Please let me know if you've found any clues.

**Comment by iNPUTmice** [comment]
Have a look at this https://community.igniterealtime.org/thread/58030 OpenFire support forum thread or ask them again.

For people having this problem it might also be useful to compare the Java version and maybe ask in the OpenFire support forums or something.

**Comment by iNPUTmice** [comment]
OpenFire related TLS problems (actually caused by the self signed certs) should be fixed in current master.

**Comment by aesthesisM** [comment]
openfire 4.0.3 has not this problem but when we tried to connect on openfire 4.1.5 we got this problem. i think its related to openfire.

**Comment by mortezaadi** [comment]
@aesthesisM we have the same problem and there is no way to use conversation with openfire above 4.0.3 with self signed certificate.However i don't believe that it is an Openfire problem. The same version of openfire that the Conversations has a problem with, works perfectly with other xmpp clients. Beside that there is no any changes in 4.0.4 regards certificates.

**Comment by iNPUTmice** [comment]
@aesthesisM @mortezaadi like I said I believe this has been fixed in 1.19.4

**Comment by Flowdalic** [comment]
@iNPUTmice  I'm curious: Which commit in conversations is the (supposed) fix?

**Comment by mortezaadi** [comment]
@iNPUTmice thanks its works fine! How does openfire generate this kind of certificate then! :))

**Comment by iNPUTmice** [comment]
@Flowdalic 8afe7efc2cef82e5736b43e25c2bbec9cc968342 (see commit message)
However as it turns out checking if a cert is self signed with the code introduced in that commit reliably crashes the TLS stack on Android <4.4. Thus there is https://github.com/siacs/Conversations/commit/c8bd5bc1f5f16120a60cf2f836e0b2d12c76a66a

**Comment by mortezaadi** [comment]
@Flowdalic 
https://github.com/siacs/Conversations/commit/8afe7efc2cef82e5736b43e25c2bbec9cc968342
