### ISSUE TITLE
Notify in muc when received mam messages

### ISSUE THREAD

**Issue by srgcdev** [siacs/Conversations#2251]
#### General information

* **Version:** 1.15.4
* **Muc with mam enabled**

#### Steps to reproduce

When I'm offline for a while and then I'm online again, I'm notified about messages in 1 to 1 chats, messages in mucs without mam but I'm not notified about messages in mucs with mam enabled

#### Expected result

I think conversations should notifiy messages in mucs with mam enabled too because almost people (regular users) have only one device and is preferable that those who have two clients being notified two times than those who have only one device (I think they are almost people if xmpp where widely used) not being notified

Maybe conversations shouldn't notify muc mam messages when you are online in another device because it's suppossed you have been notified about these messages in the other device.

**Comment by petmos** [comment]
+1
We ran into the same pitfall. It would be really useful to get notifications in this case.

**Comment by petmos** [comment]
And it would be fine if MUC with enabled MAM **and** OMEMO creates notifications.

**Comment by srgcdev** [comment]
I think this is solved since 1.17.0. Thanks
