### ISSUE TITLE
improvement suggestion: how to style attachment UX

### ISSUE THREAD

**Issue by conrad-heimbold** [siacs/Conversations#2252]
Having the last-used share-a-file-option in the input field , but all the other share-a-file-options in the top row is an artificial distinction IMHO, so not intuitive/user-friendly. Also, the share-a-file option in the top row takes up two much space on small screen devices (From most of my contacts, I can't see the family names). 

Therefore, my suggestion: a pop-up menu in the bottom conversation input field, which opens a selection menu for sending an attachment by type (similar to the ones in Telegram, Hangouts, etc.). Tapping on one of these attachment icons should make an appropriate intent to android to open a suitable app. 

My first draft: 
![how_to_style_conversations_ux](https://cloud.githubusercontent.com/assets/17474312/22179127/84df84c2-e04a-11e6-99f9-c3cd2be1710c.png) . 
1. Tap on the attachment icon on the left
=> green row with attachment file options opens
2. Tap on the attachment icon again
=> green row closes
again. 

This is just a rough draft, it could definitely get some more fine-tuning. But I think, I would fit good to Android's flat design. Please give your opinions! 

I am new to Android app development and would really like to contribute to Conversations to implement that thing, i just don't know where to start or look for? Could you give me some advice? Thank you in advance!

**Comment by conrad-heimbold** [comment]
Having a separate row for sending of attachments also allows you to make a description for the file you just sent. So far, you have to write a second message, to make a description for the file/photo/video/etc. However, XMPP actually allows you to send a file **together** with some description, AFAIK.

**Comment by iNPUTmice** [comment]
I'm open to such a change. One has to be a bit careful about this to not rob users of important vertical screen estate.
Both Hangouts, the SMS app, and Wire display that attachment bar underneath the text input. So this might also be worth a consideration.
Hangouts and Wire even display it permanently. (Which would allow us to get rid of the extra attach button toggle to the left.)

ConversationFragment is the class you are looking for.

**Comment by licaon-kter** [comment]
What happened?

**Comment by conrad-heimbold** [comment]
@licaon-kter : The drop-down menu (now) has icons, I thought that would be enough.
