### ISSUE TITLE
Manual verification option when blind trust enabled

### ISSUE THREAD

**Issue by tohojo** [siacs/Conversations#2254]
#### General information

* **Version:** 1.15.5
* **Device:** HTC One m9
* **Android Version:** Android 6.0 Cyanogenmod
* **Server name:** self hosted

When blind trust is enabled it would be useful to be able to trigger the "contact is verified" behaviour without scanning a barcode. I.e. say I have an out-of-band trusted channel to verify a contact's textual fingerprint. I should be able to indicate this to conversation, so it will switch to warning when a new device shows up for that contact (as it does when a fingerprint is verified via barcode). Right now, the only way to get this behaviour is by turning off blind trust entirely.

**Comment by mimi89999** [comment]
I don't understand the issue. It is an expected behaviour.

**Comment by tohojo** [comment]
Hmm, let's see if I can explain it better:

Quoting from https://gultsch.de/trust.html:

> After such a verification happened Conversations will no longer blindly trust new devices that are created after the verification. By doing verification the user has proven three things a) they are capable of scanning barcodes b) they have some sort of out-of-band channel where such a verification can happen c) they have some interest in verified communication.

Basically, I would like to be able to prove b) and c) without proving a) (i.e. say my out-of-band channel is text-only so I cannot transfer a barcode, but I can transfer the textual fingerprint). I currently have no way of indicating to Conversations that I have verified the textual fingerprint manually.

**Comment by iNPUTmice** [comment]
@tohojo you can exchange and click an XMPP uri that contains the key. A pure visual comparison is currently not on our to do list. For the reasons described in that document.

**Comment by mimi89999** [comment]
Go to account settings, press on share and choose the 2 or 3 option.

**Comment by tohojo** [comment]
Ah, so if I receive such a URL on my phone, conversations will offer to handle it and that will constitute a verification?

Is this compatible with any other clients?

**Comment by licaon-kter** [comment]
#2166 awaits more input ;)

**Comment by iNPUTmice** [comment]
> Ah, so if I receive such a URL on my phone, conversations will offer to handle it and that will constitute a verification?

yes
