### ISSUE TITLE
UI: OMEMO fails silently when status permission has not been granted to contact

### ISSUE THREAD

**Issue by tohojo** [siacs/Conversations#2255]
#### General information

* **Version:** 1.15.5
* **Android Version:** Android 6.0 Cyanogenmod
* **Server name:** self hosted
* **Server software:** ejabberd 16.12

When a contact in your roster is not permitted to see your online status OMEMO fails. This is indicated in coversations by OMEMO being greyed out, with no indication as to why. It would be useful if conversations could detect this situation and offer to grant the required permissions instead of just refusing to initiate OMEMO.

**Comment by PacoBell** [comment]
It does eventually tell you the reason if you long-press on the lock icon, but that's obviously quite obtuse.

Relevant: https://youtu.be/BtqXLwNj2RE

**Comment by gelft** [comment]
That's an obtuse use of obtuse.  @PacoBell  ;p
