### ISSUE TITLE
XEP-0066 receiving support

### ISSUE THREAD

**Issue by singpolyma** [siacs/Conversations#2256]
#### General information

* **Version:** 1.15.0
* **Device:** Blackberry Q10
* **Server name:** self hosted
* **Server software:** Prosody 0.9.1
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Open XML console in Gajim
2. Paste this:

```
<message to="singpolyma@singpolyma.net/q10" type="chat">
   <x xmlns='jabber:x:oob'>
      <url>https://singpolyma.net/avatar-big.jpg</url>
   </x>
</message>
```

#### Expected result

I expect to get a picture message in my Conversations.  Instead I get nothing.

**Comment by mimi89999** [comment]
@singpolyma Why would you need that?

**Comment by singpolyma** [comment]
@mimi89999 for a message that has an image but no accompanying text?

**Comment by mimi89999** [comment]
@singpolyma Which XMPP client parses them like that (because I suppose you aren't normally writting XML in the Gajim console).

**Comment by singpolyma** [comment]
@mimi89999 Gajim happily supports this format (though they have a bug where they only parse it when `<body>some other text</body>` is present.

I'd like to use this XEP as one of the ways I do file transfers from a gateway component.

**Comment by iNPUTmice** [comment]
I suggest you put the URL in the body as well. This will trigger the desired behavior in Conversations.

**Comment by singpolyma** [comment]
Yes, that is the hack we are using for now, but it produces less nice behaviour in other clients (who show the URL as a text message) and also means we cannot include text along with an image in the same message.
