### ISSUE TITLE
UI: Add another swipe level to the right of the "chat view" for "chat details"

### ISSUE THREAD

**Issue by paskalito** [siacs/Conversations#2257]
I think it would be great from a usability standpoint that one could swipe to the right when you are in the "chat view" and get details about it such as, who is in the conference, options to add remove reinvitete. (if its a conference) mute chats or people. end a conference. maybe also access the fingerprints of people right away.

it would be more straighforward and through the possibility of just listing up things (because its scrollable) you decrease menupoints and therefore neccessary clicks. also its super extendable then for the future.

**Comment by iNPUTmice** [comment]
I think that's too much swiping. That's not a Android design pattern.

**Comment by uchchishta** [comment]
Or just swipe right/left to go into conference/contact details directly?
