### ISSUE TITLE
XEP-0363: Make random file names shorter

### ISSUE THREAD

**Issue by ge0rg** [siacs/Conversations#2263]
When uploading an image via HTTP-Upload, Conversations (tested on 1.15.5) is generating the file name as `hex-UUID.jpg`. While using a roughly 128-bit random identifier is great for security, the overly long file name makes for horrible UX if you want to copy&paste the URL to different media (email clients like Outlook are notorious for breaking long links), or if you are using a console client. Prosody [is doing the same](https://prosody.im/issues/issue/822), so the eventual URL ends up with two 36-char UUIDs, e.g:

    https://xmpp.yaxim.org:5281/upload/7ce25f9f-2247-41cc-aecb-443a1acfba2a/a5f532df-0fef-47c4-81a9-2aff690419fc.jpg

Please replace the 36-character hexadecimal UUID with a significantly shorter random file name using more characters for entropy. Maybe you can appropriate the internal XMPP password generator function, or at least use url-safe-base64(128bit-random). Maybe it would even be feasible to reduce the number of entropy bits to get even shorter.

Thanks :)

**Comment by iNPUTmice** [comment]
This has been implemented a couple of days ago here: c9e6d05fa0db1810f16980bffa661fa7ae5fd10d
