### ISSUE TITLE
Feature Request: add UI to see who within a groupchat has seen an individual message

### ISSUE THREAD

**Issue by paskalito** [siacs/Conversations#2264]
It would be great to get some menu/screen/option when i long click on a message within a group conversation that would allow me to see who of the group (who's sharing that information with me) has already seen that certain message.

**Comment by BlauerHunger** [comment]
is that even possible in mucs?

**Comment by paskalito** [comment]
a) i don't know the protocoll almost at all
b) i've seen that whatsapp is doing it, but i don't know if that is an
extension made by them
c) according to my knowledge (state of xmpp talk last lear) a sucessor
of muc is currently in development, maybe it's at part of that new
standard to come

**Comment by griffindoors** [comment]
for those clients who list participants it seems a ui element could be placed next to nick

**Comment by bhavikmandalia** [comment]
any update on this ??

**Comment by iNPUTmice** [comment]
this is implemented in 1.22.0 or something
