### ISSUE TITLE
Conversations app icon does not show number of unread messages on Android 7.0 Nougat

### ISSUE THREAD

**Issue by holgis** [siacs/Conversations#2268]
#### General information

* **Version:** 1.15.5
* **Device:** Samsung Galaxy S7
* **Android Version:** Android 7.0 Stock
* **Conversations source:** F-Droid

#### Steps to reproduce

1. On Android 7.0, get a new message
2. Conversations app icon on homescreen or app menu does not show number of unread messages

#### Expected result

Show number of unread messages as it is shown on Android 6.0

**Comment by iNPUTmice** [comment]
https://github.com/leolin310148/ShortcutBadger/issues/146
