### ISSUE TITLE
Conversations doesn't receive messages once display goes off and they get lost

### ISSUE THREAD

**Issue by andreygursky** [siacs/Conversations#2269]
#### General information

* **Version:** 1.14.x - 1.15.5
* **Device:** LG G4, other
* **Android Version:** Android 5.x Stock
* **Server name:** jabber.ccc.de / self hosted prosody
* **Server software:** ejabberd (?) before update to 17.01 / prosody 0.9.12
* **Installed server modules:** see ComplianceTester results / Stream Management, no MAM
* **Conversations source:** F-Droid / self build

#### Steps to reproduce

1. Wait until Display goes off.
2. Send message to that contact, which claims to be online (from Gajim).
3. Wait more than 5 minutes.
4. Open Conversations.

#### Expected result

The message will be received but it is missing despite Conversations claimed all this time to be online.

This doesn't happen, if "keep in foreground" is activated. (Activating is unfortunately not an option due to higher battery usage.) It seems that Conversations must sign off by the server once it receives the corresponding event from Android (instead of "Away") otherwise it is not really online anymore in fact. Which confuses the server and instead of buffering the message until the contact goes online, it tries to deliver it and after small timeout drops the message. Messages sent to Conversations being offline seem to be delivered reliably.

#### Debug output

Since the issue depends on the power consumption management, it is hard to obtain logcat without affecting the faulty behavior (i.e. USB doesn't fit at all, but even transmission over WLAN would force Android to switch it on, while it might be longer off).

**Comment by iNPUTmice** [comment]
The power manager of your operating system is either killing Conversations or killing the TCP connection. Your server does not have MAM so it can re-retrieve messages when coming back online. 
You said enabling the foreground service fixes this. Than this is one of your options; Or pick a server that provides MAM and maybe Push.

**Comment by andreygursky** [comment]
> The power manager of your operating system is either killing Conversations or killing the TCP connection.

Doesn't it applies for Android in general?

> Your server does not have MAM so it can re-retrieve messages when coming back online.

Daniel, could you tell me please what re-retrieving do you mean?

> You said enabling the foreground service fixes this. Than this is one of your options; Or pick a server that provides MAM and maybe Push.

But for servers without MAM is it not better to introduce an expert option "go Offline" after display goes off (similar to set "Away")?

**Comment by iNPUTmice** [comment]
>> The power manager of your operating system is either killing Conversations or killing the TCP connection.

> Doesn't it applies for Android in general?

No. It does not.

> Daniel, could you tell me please what re-retrieving do you mean?

Use MAM to fetch the messages that were send while being offline.

> But for servers without MAM is it not better to introduce an expert option "go Offline" after display goes off (similar to set "Away")?

I don't think it is desirable for users not to get notified of new messages.

**Comment by andersruneson** [comment]
You could probably set your operating system to disable battery optimization for conversations, that way conversations/tcp may still be running when screen goes off.
This does actually not consume much battery normally.

**Comment by i-need-to-tell-you-something** [comment]
"MAM" means [Media Asset Management](https://en.wikipedia.org/wiki/Media_asset_management) here?

**Comment by mimi89999** [comment]
@i-need-to-tell-you-something 
XEP-0313: Message Archive Management
