### ISSUE TITLE
Feature request :: show chat datewise

### ISSUE THREAD

**Issue by bhavikmandalia** [siacs/Conversations#2271]
It will be a good feature to show conversation date wise using sticky header .Now a days,many XMPP based app having this kind of features.

**Comment by iNPUTmice** [comment]
I don't know what you mean. Do you have a screenshot?

**Comment by licaon-kter** [comment]
I guess s/he wants the "December 12" thing: https://i.imgur.com/spqTDVS.png ?!

+1 from me

Meaning:
* don't tag each message with date
* keep only time in line with the message text (makes it more compact)
* but group messages by days, showing that "December 12" separator

**Comment by bhavikmandalia** [comment]
@licaon-kter your screenshot shows explain my concern exactly

@iNPUTmice  i am asking same as @licaon-kter  says...

**Comment by bhavikmandalia** [comment]
Any update on this ???

**Comment by licaon-kter** [comment]
@bhavikmandalia It's great that you've asked for this, but unless you actually start developing this feature it will only get on a project priority queue and stay there until it gets its turn. Also, UI modifications are not that urgent. ;)

/PS: annoying the dev by posting here will not help, but...

**Comment by kriztan** [comment]
@iNPUTmice if you are interested in integrating date bubbles in chat list, take a look into my commit https://github.com/kriztan/Pix-Art-Messenger/commit/b753e545286d5fd9562b72e119cf244f30da0a38

here is a screenshot:
![2017-02-16_21-02-27_sonq5l6l0gm9](https://cloud.githubusercontent.com/assets/3350754/23038717/57693c72-f48b-11e6-8b3a-a3c858774417.jpg)

**Comment by Aluisyo** [comment]
+1

Great work chris
