### ISSUE TITLE
[feature request] Integrate PGP directly into Conversations

### ISSUE THREAD

**Issue by broncheolus** [siacs/Conversations#2273]
Version: 1.15.5
Device: Jolla1, Intex Aquafish
OS Version: Sailfish OS 2.0.*; with Android support
Server name: conversations.im
Conversations source: F-Droid

Dear iNPUTmice,

it would be great if there  were the possibility to create the openPGP key from within Conversations because it seems that somtimes there is a comunication problem between C and OpenKeyChain. (C does not find OKCh although installed and running or the correct key can not be found to decipher messages) I in my case Idont want to use Omemo because I would like to have the possibility of recovering messages without external backup tool using the server archive. 
If using OMEMO it would be better to have the possibility to export all messages in clear text to back them up if ther is no other way.

Thanks and congrats to this great messanger and good luck for the future, broncheolus.

**Comment by mimi89999** [comment]
You can export your messages to the SD card. It is the last option in advanced settings accessed from settings.

**Comment by moparisthebest** [comment]
Conversations and OpenKeychain work flawlessly together for me (and at least 2 other people I know), if they don't for you I'd suggest you focus on getting that bug fixed rather than trying to re-implement all of OpenKeychain inside of Conversations, which sounds like a terrible idea.

**Comment by iNPUTmice** [comment]
Pretty much what @moparisthebest said.
