### ISSUE TITLE
Cannot have a transparent background .png file for Avatars

### ISSUE THREAD

**Issue by uchchishta** [siacs/Conversations#2274]
#### General information

* **Version:** 1.15.5
* **Device:** Samsung Galaxy Tab 4 / Galaxy j2
* **Android Version:** 4.4.3 / 6.0.1
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Upload a transparent background .png for a avatar

#### Expected result

It would be cool to have transparent background images for avatars in chat, but uploaded .png files do not have transparency. Instead they have a black background.

**Comment by mimi89999** [comment]
It worked for me...

**Comment by Natureshadow** [comment]
It's a (known) limitation of your proprietary Android derivative.

Go get a free and recent OS :)!

**Comment by uchchishta** [comment]
It just realised its my kitkat tab, which does that. Thanks, Natureshadow, but it doesn't have a custom OS :(

I'm closing this issue.

**Comment by mimi89999** [comment]
Maybe you can find CyanogenMod for your device...

**Comment by mimi89999** [comment]
Maybe you can find CyanogenMod for your device...

**Comment by uchchishta** [comment]
No mimi89999, I searched everywhere. There's not a single rom. They say it's because of marvell's proprietary chipset :(. I searched github now, I found they have released some sources @android-marvell only for the wifi variant :(, still I don't know to build a rom :(
