### ISSUE TITLE
Unable to send file when "http_upload" is enabled in Prosody server configuration

### ISSUE THREAD

**Issue by Myhappyapps** [siacs/Conversations#2275]
I would like to express my sincere thanks for providing great project Conversations. I enabled "http_upload" in Prosody server so that i am getting attachment icon in conference chat and XEP-0363 is available in Server Info also. 

My issue is if i enabled "http_upload" in Prosody server then I am unable to send files even in single contact as well as in Conference chat. But if i disable "http_upload" , i am able to send files in single contacts.

Please help. Thanking you.

**Comment by Aluisyo** [comment]
please report this in prosody muc.
