### ISSUE TITLE
OMEMO and carbons Messages, could not sent my messages to a second device

### ISSUE THREAD

**Issue by hschraep** [siacs/Conversations#2281]
#### General information

* **Version:**  1.15.5
* **Device:** Samsung S4
* **Android Version:**  Android 6.1 Cyanogenmod
* **Server name:** self hosted
* **Server software:** Prosody 0.9.10
* **Installed server modules:** Stream Managment, CSI, MAM,HTTP upload, Carbons, BLocking   Command, PEP
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Send a message to one of your contacts with OMEMO encryption from Gajim (0.16.5 with omemo 1.0.2) or Conversation
2. The receiver get the message but not my second client Gajim with carbons enabled and OMEMO encryption
3. If the receiver answer me both devices get the message Gajim and Conversations

The same is it in the other direction

#### Expected result

I get carbons with omemo encryption on but if i send it out to other my second client (gajim or the other way conversations) did not get my send message.
If i do it unencryptet all is working as it should

#### Debug output

what logs can i provide???
````

**Comment by kriztan** [comment]
You have to verify your own devices with each other. After that, it should work fine.

**Comment by hschraep** [comment]
What did you mean with verified. Is the device verified only if i have within conversation this singed symbol at the omemo fingerprint instant of the button?

**Comment by mimi89999** [comment]
Press on your avatar or go to account details and see if you enable all of your OMEMO keys.

**Comment by hschraep** [comment]
yes this omemo keys are enabled. but it is not the problem to send a omemo message to a other contact. It is problem that i do not get my one written messages one my second device in this case my ubuntu PC with gajim installed. But tjis is only not working if omemo is enabled. If i write unencrypted my pc get my own written message. so i think it is not a problem of carbons messages instead of omemo.

**Comment by mimi89999** [comment]
Not the contact keys. Your keys.

**Comment by kriztan** [comment]
That is were we talk about. You have to go into your own contact details and there you have to verify your own keys from other device(s).

**Comment by hschraep** [comment]
Ok you mean under "Konten verwalten" > "My konto" . There is only my jabber id and password and under this i have my otr finger print and my OMEMO fingerprint. Thats all.

**Comment by kriztan** [comment]
This should look like this, if it doesn't, something seems to be missconfigured. For me carbons are working fine, but other devices must be verified in account details for all devices.

![2017-02-07_14-27-02_en12ble4ooy7](https://cloud.githubusercontent.com/assets/3350754/22693093/2bd74ee6-ed42-11e6-8f67-336e11d4e273.jpg)

**Comment by hschraep** [comment]
Ok, so is the question why i have not this entry’s under my account and how can i get this.

**Comment by hschraep** [comment]
Could it be help to use "reset omemo identity" under expert options? So i have to verify all my contacts new but if its helps. Or is this a bad idea?

**Comment by mimi89999** [comment]
Bad idea. Maybe try sending yourself a message from Gajim.

**Comment by hschraep** [comment]
hm, this i have already try. But it change nothing. I get no extra device under my account within conversations.

**Comment by mimi89999** [comment]
Try opening and quitting Gajim, connecting and disconnecting in Gajim while being connected in Conversations.

**Comment by mimi89999** [comment]
Ah, and try on another server.

**Comment by olerem** [comment]
I had recently with Gajim lots of problems, the latest nighly version seems to work now. What gajim version are you using?

**Comment by mimi89999** [comment]
@olerem Was in the issue description:
> Gajim 0.16.5 with omemo [plugin] 1.0.2

**Comment by olerem** [comment]
I use 0.16.7 with omemo [plugin] 1.0.2.. it is mostly working. Your issue is not reproducible, But i'm really unhappy with it.
For example right now i get some echo messages from the past.

**Comment by hschraep** [comment]
I have now make some tests with a new account on my server and on a other server both are working.
So i think i must delete this device entry under my original account within conversations by my self or my little daughter ;-). 
So if it deleted could it be that it could not newly recreated? If so have i to delete my account and start from beginning or could the "reset omemo identity" under expert configuration help?

**Comment by mimi89999** [comment]
@hschraep First of all, are you 100% sure that your server is well configured?

**Comment by hschraep** [comment]
Yes because with a newly generated account it works perfect with omemo encryption.

**Comment by mimi89999** [comment]
@hschraep Did you manage to fix your issue?

**Comment by hschraep** [comment]
I have no Chance to get back the  omemo device Fingerprint under my account settings within conversations if there was deleted? If it is so, I could only delete this account and create it new. In this last case the problem is fixed, because with a newly created user on my server carbons work with omemo encryption.

**Comment by hschraep** [comment]
I have tried first to delete my account on the server this looks good from view of the omemo fingerprints. But to create a account with the same name was no good idea. So it looks like for me that is all good but nobody has seen my online status. And I could not choose omemo at any one. So I have decide use a new account name and all works as it should. Thanks for your help.

**Comment by stopANALytics** [comment]
Please update to current versions of gajim and omemo plugin, 0.16.7 and 1.0.3, respectively
