### ISSUE TITLE
[Feature Request] Review attachments before sending

### ISSUE THREAD

**Issue by santifa** [siacs/Conversations#2282]
It would be a nice feature to get the chance to verify attachments before sending.
At the moment an attachment is sent right after the selection or camera app returns.
Like other apps (Signal) a "second" verification may be useful to prevent sending wrong files or low-quality pictures directly from the camera app. This could be done with showing a thumbnail or something else within Conversation and by pressing the send button instead of only selecting the media file.

**Comment by iNPUTmice** [comment]
duplicate of #1879

**Comment by tmolitor-stud-tu** [comment]
See #1879
