### ISSUE TITLE
Preview generation is lagging UI

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#2283]
#### General information

* **Version:** 1.16.0
* **Device:** OnePlus 3
* **Android Version:** Android 7.0 Stock
* **Server name:** self hosted
* **Server software:** prosody
* **Installed server modules:** Stream Managment, CSI, MAM,...
* **Conversations source:** PlayStore, PlayStore Beta Channel

#### Steps to reproduce

1. Share some videos, gifs and images
2. first creation of previews is lagging the UI, you can not scroll since all previews are created

#### Expected result
Scrolling should be smooth and previews should be created async.

This could be partially related to #2198 

#### Debug output

````
D/Conversations: target size overlay: 244.5 overlay bitmap size was 384
I/Choreographer: Skipped 122 frames!  The application may be doing too much work on its main thread.
````

**Comment by stopANALytics** [comment]
How much ram does your device have in total? and 3 minutes after booting how much is free?
