### ISSUE TITLE
JabberID from external source opens blank Conversations

### ISSUE THREAD

**Issue by Fenisu** [siacs/Conversations#2287]
#### General information

* **Version:** 1.16.0
* **Device:** Google Nexus 5
* **Android Version:**  Android 6.0 Stock
* **Server name:** self hosted
* **Server software:** ejabberd 16.04
* **Installed server modules:** Stream Managment, CSI
* **Conversations source:** self build with x509 verification

#### Thoughts

2 phones, 2 new accounts, both set up and online.

Locally stored JabberID on one phone, press on the link and Conversations opens to handle the Jabber ID. Conversations comes to foreground but nothing happens (most of the times).

#### Expected result

The expected result is to see always a small popup window where Conversations asks to add the user because it is not a user from your personal roaster. If you try this process multiple times, it works eventually.

**Comment by iNPUTmice** [comment]
fixed in 4cddf31ad29eae68c467b9bde918fb4be07a38a9

**Comment by Fenisu** [comment]
Thanks!
