### ISSUE TITLE
Allow to set a nickname in the account for MUCs

### ISSUE THREAD

**Issue by Ppjet6** [siacs/Conversations#2288]
#### General information

* **Version:** 1.16.0
* **Conversations source:** F-Droid

I am using both poezio and conversations, and my default nick on poezio is not the same as the nodepart of my JID. So when I join a MUC that is not bookmarked with a nick (foo@bar/baz), with both clients, I end up having two different nicks.

Is there a way to set a default nickname? I haven't found anything for this.

**Comment by iNPUTmice** [comment]
you can enter a full jid in the join dialog.

**Comment by SamWhited** [comment]
FWIW, even knowing what a full JID is, I never think about this or expect it to be a thing and end up running into issues where I can't change my nick because it's already in use.
