### ISSUE TITLE
E2E Encrypt by default

### ISSUE THREAD

**Issue by cxxuzbim** [siacs/Conversations#2291]
When starting a new conversatoin, use the best possible e2e encryption by default instead of unencrypted.

Chatsecure for iOS functions this way.

If you don't want to enable for all servers, at least when both are using conversations.im.

**Comment by tonghuix** [comment]
I would like to suggest add options for user choosing which policy for e2e encryption: 

- Require encryption using OTR
- Require encryption using OMEMO
- Automatic try the best concretion (which will response from the sender, follow by the sender's encryption method, OTR or OMEMO)
- Manual choose and start encryption

**Comment by licaon-kter** [comment]
Read the Readme please.

/Close as invalid

**Comment by cxxuzbim** [comment]
I respectfully disagree. E2E is as important as TLS was previously.

Proper defaults keep people safe and secure. A messenger app without default E2E is not meet modern competitive security needs.

**Comment by mimi89999** [comment]
@cxxuzbim https://gultsch.de/trust.html

**Comment by stopANALytics** [comment]
TLS/ssl requires trusting the server

e2e requires trusting the contact

**Comment by matthaab** [comment]
Let us choos!

**Comment by devurandom** [comment]
In case someone else might be wondering: The ["Security" section of the readme](https://github.com/siacs/Conversations#security) contains the answer. Out of that section, the paragraph "Why is Conversations not end-to-end encrypted by default" answers this question specifically, but the surrounding paragraphs are helpful to understand the reasoning behind it.
