### ISSUE TITLE
Redirection OMEMO temp to XEP-0384?

### ISSUE THREAD

**Issue by Neustradamus** [siacs/Conversations#2292]
Can you redirect the old temp XEP to real XEP-0384?
https://conversations.im/xeps/multi-end.html to https://xmpp.org/extensions/xep-0384.html

**Comment by iNPUTmice** [comment]
I think there is a value in having the old XEP around to describe how the current implementation works

**Comment by Neustradamus** [comment]
The final version is better for users and developpers...
