### ISSUE TITLE
Describe support of Easy XMPP standards in Conversations IM website

### ISSUE THREAD

**Issue by MurzNN** [siacs/Conversations#2294]
The XMPP Standards Foundation describe list of usability features that must make XMPP clients more friendly for normal users, here is page about this initiative: https://wiki.xmpp.org/web/Category:Easy_XMPP

Seems that Conversations IM already implement most of described features, so will be good to recheck this and descibe in Conversations IM website that our messenger have full support of Easy XMPP features.

**Comment by iNPUTmice** [comment]
I currently see no marketing value in mentioning that Conversations supports 'Easy XMPP'. I don't think people know what 'Easy XMPP' means.

**Comment by SamWhited** [comment]
> The XMPP Standards Foundation describe list of usability features that must make XMPP clients more friendly for normal users

No, someone on the wiki just described things they think makes them easier. That list is in no way a recommendation of the XSF, or an official publication, etc.

**Comment by stopANALytics** [comment]
> The XMPP Standards Foundation describe

Refer to pink highlight problem

![ohmy](https://cloud.githubusercontent.com/assets/25807247/23004325/cc687fce-f3aa-11e6-9f4e-014baa2d01a6.png)
