### ISSUE TITLE
bug reports sent from app

### ISSUE THREAD

**Issue by stopANALytics** [siacs/Conversations#2297]
Are stored where?  Is my JID exposed as world readable somewhere?

**Comment by licaon-kter** [comment]
Second question is #1588

**Comment by iNPUTmice** [comment]
Please use our group chat for general questions This is a bug tracker.

**Comment by gelft** [comment]
> our group chat 

Please offer less vague advice.

**Comment by andersruneson** [comment]
https://github.com/siacs/Conversations/blob/master/README.md#conversations-doesnt-work-for-me-where-can-i-get-help
