### ISSUE TITLE
xep compliance, link to ranked

### ISSUE THREAD

**Issue by stopANALytics** [siacs/Conversations#2299]
Please add a link to 

https://gultsch.de/compliance.html

for

https://gultsch.de/compliance_ranked.html

**Comment by iNPUTmice** [comment]
Being compliant doesn't say anything about the overall quality. That's why we don't link the compliance tester on the website or from the app. Because it is in a way meaningless.

**Comment by licaon-kter** [comment]
Just put a link there since you don't a column sorting.
