### ISSUE TITLE
blacklist lobby muc

### ISSUE THREAD

**Issue by stopANALytics** [siacs/Conversations#2301]
https://github.com/siacs/Conversations/issues/358

To reduce the vexatious experience by users new to _jabber texting_ create a blacklist of common muc inflicted bookmarks, oh, say, like chinwag.im uses, to reduce the amount of complaining along the lines of,

>  "I hate this.  Why won't you just use normal phone texting"

**Comment by iNPUTmice** [comment]
I don't think Conversations should black list anything
