### ISSUE TITLE
Show Barcode and a button to scan one when first account is added

### ISSUE THREAD

**Issue by subpub** [siacs/Conversations#2309]
When a new user creates their new account, they are welcomed with an empty  screen. It would be helpful if they were showed a "Scan your contacts 2d code"  button and their own 2d code on that screen too.

**Comment by gelft** [comment]
An support  ISO/IEC 24778:2008, Aztec Code, a 2D matrix.

**Comment by uchchishta** [comment]
@gelft but those are unnecessary because you scan through conversations via a single app. And also Aztec is what it shows.
