### ISSUE TITLE
Persistent empty notification

### ISSUE THREAD

**Issue by abbradar** [siacs/Conversations#2310]
#### General information

* **Version:** 1.16.1
* **Device:** Xiaomi Mi 5
* **Android Version:** MIUI 8 Global 7.2.9 (Beta), Android 7.0 NRD90M
* **Server name:** fmap.me
* **Server software:** Prosody (unknown version)
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Run Conversations.

#### Expected result

An empty notification is seen, like this one:

![screenshot_2017-02-16-19-42-54-489_eu siacs conversations](https://cloud.githubusercontent.com/assets/1174810/23031519/b07de8f4-f48a-11e6-9ca5-3ef262f1a2c7.png)

It persists and re-appears, even when the app is in background.

#### Debug output

This is for roughly a second since starting the app after killing it. The notification appears almost instantly, before the connection is made.

````
02-16 19:55:58.944 22405 22422 D conversations: restoring roster
02-16 19:55:58.949 22405 22405 D conversations: update unread count to 0
02-16 19:55:58.956 22405 22405 D conversations: schedule next idle ping
02-16 19:55:58.976 22405 22425 D conversations: ab@fmap.me: socket was null during force close
02-16 19:55:58.976 22405 22425 D conversations: ab@fmap.me: connecting
02-16 19:55:58.987 22405 22425 D conversations: used lollipop variant to discover dns servers in 1 networks
02-16 19:55:58.988 22405 22425 D conversations: using dns server: 217.118.66.243 to look up fmap.me
02-16 19:55:59.020 22405 22405 D conversations: app switched into foreground
02-16 19:55:59.023 22405 22422 D conversations: AxolotlService (ab@fmap.me): Got Axolotl signed prekey record:1
02-16 19:55:59.036 22405 22422 D conversations: restoring messages
02-16 19:55:59.037 22405 22421 D conversations: start merging phone contacts with roster
02-16 19:55:59.038 22405 22421 D conversations: finished merging phone contacts
02-16 19:55:59.077 22405 22422 D conversations: restored all messages
02-16 19:55:59.111 22405 22425 D conversations: ab@fmap.me: using values from dns fmap.me[91.92.66.84]:5222 tls: false
02-16 19:55:59.226 22405 22405 D conversations: load more messages for teaparty prior to 2017-02-11T19:37:43.000Z
02-16 19:55:59.274 22405 22405 D conversations: resetting all attempt counts
02-16 19:55:59.831 22405 22425 D conversations: ab@fmap.me: TLS connection established
02-16 19:55:59.948 22405 22425 D conversations: ab@fmap.me/phone: Authenticating with PLAIN
````

Should have added: I didn't have this on the previous version, and I don't remember exactly which one (I haven't updated for some time).

**Comment by iNPUTmice** [comment]
Check if you have the foreground service enabled in the expert settings.

**Comment by abbradar** [comment]
@iNPUTmice No: if I have it enabled I have two notifications instead (with one "Touch to open Conversations").

**Comment by abbradar** [comment]
More experiments:

1. If it's swiped away it won't always reappear instantly;
2. It always reappears when Conversations is restarted.

**Comment by licaon-kter** [comment]
Long press it, what process is it from?

**Comment by abbradar** [comment]
Haven't known that it's possible, thanks. However I see Conversations notification settings when I do that; does that mean it's from Conversations? 
-- 
Nikolay.

**Comment by abbradar** [comment]
I've did version-level bisect with F-Droid. Problem appeared in 1.16.0; 1.15.5 is fine.

**Comment by licaon-kter** [comment]
When you have 2 of them, both say they're from Conversations?

**Comment by abbradar** [comment]
Both open Conversations notification settings at least. And I can't (expectably) swipe off the "Touch to open..." one.

**Comment by licaon-kter** [comment]
The `touch to open` one can't be swiped, it's ok.

Now, you need to dissect the commits one by one...

**Comment by abbradar** [comment]
I hoped it won't come to this :D I'll try on holidays somewhere next week.

**Comment by abbradar** [comment]
Is there a simple way to hardcode login credentials so that Conversations starts without first-run wizard, directly to contact list? This would speed up bisect considerably (I won't need to touch the phone at all, just look if the notification pops up).

**Comment by iNPUTmice** [comment]
@abbradar please revert the dependency ShortcutBadger back to version 1.1.11 (from 1.1.13) and try again.

**Comment by iNPUTmice** [comment]
This bug is being tracked here: https://github.com/leolin310148/ShortcutBadger/issues/170

**Comment by abbradar** [comment]
I won't be able to do this until next week or later because I don't have a working Android SDK environment. If you can build an APK for me I can test it earlier.

**Comment by abbradar** [comment]
1.16.2 fixed that for me, thanks!
