### ISSUE TITLE
Feature request :: show typing and message indication in group chat

### ISSUE THREAD

**Issue by bhavikmandalia** [siacs/Conversations#2312]
It would be great to show typing indication in group  chat and also the message receipts(read,delivered) for each message.

**Comment by badarsh2** [comment]
Can I take up this task?
If yes, are there any guidelines I have to follow beforehand?

**Comment by iNPUTmice** [comment]
@badarsh2 if I can make a suggestion just tackle the typing indication first. That's actually a bit easier than read markers and yet enough work for a teaser task.

I suggest you store the current chat state in the MucOptions.User objects.

**Comment by badarsh2** [comment]
I have a couple of doubts to clarify....
I have added a field for chatstatus in the user object. Basically everytime the editText is nonempty, I have to change the chatstatus (of self).
I am not clear about how and where I should update it in the server. Kindly clarify on this.
In the conversations fragment, should I have to asynchronously keep calling the mucoptions.getUsers() method? Or should I create a receiver similar to receiving normal messages?

**Comment by iNPUTmice** [comment]
Conversations.setOutgoingChatState() sets a limitation for MUC; you need to remove that. Afterwards you need to adapt the generateChatState methode to set the message type to groupchat for MUC conversations.

For parsing and setting the chatstate just have a look at how this is done for single mode conversations. For single mode conversations we'll just trigger an updateConversationUi() when a chatstate has been changed.

**Comment by griffindoors** [comment]
It would be fun to include Real Time Text

xep0301

**Comment by badarsh2** [comment]
@iNPUTmice I have a couple more doubts:

- in single user chat, "user has read upto this point" condition is being checked by going through all the messages of the person the user is chatting with. In case of MUC, Say X, Y, Z are in a conversation. How do I keep track of the read status for each user?
- Say X, Y have read the messages upto this point, and Z is typing something. Should my status message just be "Z is typing..."?

**Comment by hareshkh** [comment]
@sabarirangan : User to user chat does have that feature.

**Comment by singhalok641** [comment]
Is anyone working on this issue ?

**Comment by hareshkh** [comment]
@iNPUTmice commented on #1823 : `Forgot about this issue. This was fixed in 1.17.0 I believe.`
@iNPUTmice I think this issue can be closed.

**Comment by singhalok641** [comment]
@hareshkh  Yeah right !

**Comment by uchchishta** [comment]
>and also the message receipts(read,delivered) for each message.

**Comment by iNPUTmice** [comment]
Fixed in 1.17.0
