### ISSUE TITLE
[feature request] Possibility to deaktivate "touch to open conversations"

### ISSUE THREAD

**Issue by broncheolus** [siacs/Conversations#2317]
Version: 1.16.2
Device: Jolla 1
Android Version: Android simulation
Server name: conversations.im 
Conversations source: F-Droid 

Dear  iNPUTmice,
on my Jolla I have to activate the expert setting "run in foreground" in order to get notifications. There has been the issue around that conversations is coming up with the notification "touch to open conversations".
It seems to me that these notifications are triggered for example every time my phone loses connection to the internet when changing the mobile cell or when having a bad connection. I don't understand the purpose behind it. 
Wouldn't it be good to be able to deactivate this function in case these notifications are triggered and unwanted maybe directly underneath the expert setting for "running in foreground".
You know, getting a lot of notifications which are no notifications can sometimes be nerve wrecking.

Thanx a lot for your great work! Greetings, broncheolus.

**Comment by licaon-kter** [comment]
On your device you need to enable "Run in foreground" because your operating system is killing Conversations, hence no notifications.

What's the issue with the "touch to open" permanent notification exactly?

**Comment by iNPUTmice** [comment]
The notification is a consequence of the the foreground service. That's how Android indicates to the user that a process runs in foreground. The notification is required.

**Comment by broncheolus** [comment]
On sailfish os you have the posibility to let apps run in background when closing it. Conversation keeps running in the background and is not killed comlpletely. With whatsapp or signal (or libresignal) this setting is enough to keep notifications coming through. and there are no notifications like mentioned above.

It may be correct that technically it's on all the time but the GUI is closed for me. So it is difficult to understand that these empty notifications are crucial for Android when other messenger services are doing without. But I think the difference will be in the dept of the used protocoll. So the posibility to let conversations "swallow" this notif. would be great, because my conversations process  had not been killed and does not have not to be restarted, the only thing is that this notif. are always coming up when disconnected for even half a second.
Thanx for your replies and for you making efford, broncheolus.
