### ISSUE TITLE
[Suggestion] Option to disable non-OMEMO protocols, or to stick to certain protocol/s - for all contacts or per contact.

### ISSUE THREAD

**Issue by Wikinaut** [siacs/Conversations#2321]
It happens that messages have been sent *unencrypted* *by* *mistake*. 

In order to make the chats more secure, I suggest a way to disable / disallow insecure (because unencrypted) protocols if this is possible.

#### Suggestion
It would be nice to have an option, perhaps *per* *contact* or for all contacts 

* to disallow certain protocols ; or
* to fix protocol to a certain type, most important to fix to OMEMO.

**Comment by licaon-kter** [comment]
You did read this: https://github.com/siacs/Conversations#why-is-conversations-not-end-to-end-encrypted-by-default right?

**Comment by Wikinaut** [comment]
@licaon-kter Yes, I read this. I did not suggest here to have this setting *by* *default*.

**Comment by iNPUTmice** [comment]
This has been discussed several times (search the issue tracker.) The time isn't right for this.
