### ISSUE TITLE
Incompatible server

### ISSUE THREAD

**Issue by mama21mama** [siacs/Conversations#2322]
Server: mamalibre.com.ar 

App xabber work.

No certificate is required. If an application forces you. Using certificate is bad.

**Comment by iNPUTmice** [comment]
The server must provide STARTLS or Conversations won't connect. That's a security measure.

**Comment by mama21mama** [comment]
Server does not use encryption and will not use any more. The question is the following Why does the application discriminate the way the server is connected?

**Comment by iNPUTmice** [comment]
> The question is the following Why does the application discriminate the way the server is connected?

The XMPP standard says a server MUST provide TLS. If the server doesn't offer TLS it is not an XMPP server. Conversations is an XMPP client that doesn't aim to offer support for other proprietary protocols.

**Comment by mama21mama** [comment]
The standard is encrypted or unencrypted connection. That is decided by the administrator. Not an app. In this application there are no parameters for an encrypted or unencrypted connection. That's because it's an inefficient code. This app in a home-like home environment would not work. Only work with Internet.

**Comment by iNPUTmice** [comment]
If you must there is a compile time parameter to allow non TLS connections in [Config.java:46](https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/Config.java#L46).

> The standard is encrypted or unencrypted connection.

[It is not](https://tools.ietf.org/html/rfc6120#section-5.2).

**Comment by Aluisyo** [comment]
Please read:

http://conversations.im/#security

**Comment by mama21mama** [comment]
Para un ambiente cerrado corporativo no sirve la app. Por que necesita de Internet.

**Comment by SamWhited** [comment]
You're correct, but a corporate closed environment is not the target audience of Conversations. If you'r ein a corporate closed environment, you (or whomever handles your provisioning and software distribution) can build it yourself.

**Comment by mama21mama** [comment]
That's why I use the Xabber application. He is freer. Thanks for nothing.

**Comment by mimi89999** [comment]
@mama21mama Allowing non encrypted connections defeats all purpose of having encrypted connections.

Any MITM attacker can trick a client into connecting to his middle box (by changing DNS replies). His middle box can advertise as a server not supporting TLS. The client wouldn't verify then, that it is the real server (no cert needed) and the real server would just receive data from that middle box as if it was your client sending it. Nobody would even notice that his credentials and messages have been intercepted.


Since Conversations main feature is security, it can't allow connections without TLS.

Please don't be angry about that...

**Comment by mama21mama** [comment]
I speak of closed environment. Club for example. Or company for example. Both without internet connection. Therefore no tls connection would be needed. Closed environment I mean network with no internet connection.

**Comment by rollierollie** [comment]
I agree with mama21mama. If for example, one sets up an XMPP server as a Tor hidden service, they will be unable to connect as the endpoint may not be serving an SSL certificate but should be considered secure. Use of TLS should be an option that is activated by default, not an absolute requirement.

**Comment by Xohoo** [comment]
@mama21mama 
1.) download conversations source 
2.) goto  Conversations/src/main/java/eu/siacs/conversations/Config.java 
3.) change "public static final boolean ALLOW_NON_TLS_CONNECTIONS = false;" => into true
4.) buld the app 
there you have your conversations app witch allows non tls connections but as @mimi89999 said its very dangerus
