### ISSUE TITLE
Plugin to share image via ingur.com

### ISSUE THREAD

**Issue by PanderMusubi** [siacs/Conversations#2323]
#### General information

* **Version:** 1.16.2
* **Device:** n/a
* **Android Version:** 6.0.1
* **Server name:** self hosted by others
* **Server software:** n/a
* **Installed server modules:** n/a
* **Conversations source:** n/a

#### Steps to reproduce

1. Try to send image in conversation that doesn't support images (e.g. minimal service or Slack over XMPP)

#### Expected result

What is the expected output? What do you see instead?

Have this app offer a plugin that allows sending pictures, only it uploads the image to imgur.com (or alternative services) and posts the URL.

**Comment by licaon-kter** [comment]
Not a Conversations issue, use the imgur.com app and share the link to Conversations at the end.

/close this

**Comment by iNPUTmice** [comment]
Pretty much what @licaon-kter said. Supporting proprietary third party services is not something that should be integrated into Conversations. And when you think about it as a third party plugin you can either do it yourself or recognize that something like 'Share with Imgur' already exists (probably) and just use that.

**Comment by PanderMusubi** [comment]
Thanks for the feedback. The 'share with imgur' is only available when installing proprietary app from them, hence this idea. I understand that supporting third party sites is not the aim of Conversations.

**Comment by PanderMusubi** [comment]
Which free and open (non-proprietary non-commercial) image sharing alternatives to Imgur would be considered okay in this context for Conversations?

**Comment by licaon-kter** [comment]
This might work: https://github.com/Kennyc1012/Opengur/

**Comment by PanderMusubi** [comment]
Thanks. Too bad the project got frozen recently and is not yet on F-Droid. Hope to get some activity going there.

**Comment by PanderMusubi** [comment]
To close this discussion here, please see and vote for https://gitlab.com/fdroid/rfp/issues/83

**Comment by PanderMusubi** [comment]
I have found non-commercial alternatieve for Imgur, please see https://lut.im/ and https://framapic.org/ Example code for Android app can be found in https://f-droid.org/repository/browse/?fdfilter=goblim&fdid=fr.mobdev.goblim and https://git.mob-dev.fr/Schoumi/Goblim and http://www.gobl.im/

Is this reason enough to reopen this issue?
