### ISSUE TITLE
no automatic image download

### ISSUE THREAD

**Issue by Griswold666** [siacs/Conversations#2325]
#### General information

* **Version:**  1.16.1 (F-Droid)
* **Device:** eg HTC One M7
* **Android Version:** eg Android 6.0.1 Cyanogenmod
* **Server name:** self hosted
* **Server software:** prosody 0.9.10 

If I send an image via httpUpload by a self written python client (sleekxmpp), on my conversations client on mobile I just get an "check filesize on host" button. After clicking the button image downloads. With any other client as sender (another mobile with conversations or gajim on laptop) image downloads automatically. Auto accept files is set to 10MB.

Do I have to send image file size in the message to conversations to automatically download the image? 

LOG: (logcat conversations:V *:S)

02-28 16:57:10.743  1645  4199 D conversations: update unread count to 1
02-28 16:57:13.119  1645  1645 D conversations: app switched into foreground
02-28 16:57:13.123  1645  1645 D conversations: update unread count to 0
02-28 16:57:13.286  1645  1645 D conversations: load more messages for wetterbot prior to 2017-02-28T15:29:57.294Z
02-28 16:57:15.155  1645  9902 D conversations: retrieve file size. interactive:true
02-28 16:57:15.159  1645  9902 D conversations: url: https://XXXXXXXX:5281/upload/28646725-9516-4dbc-bc63-33455f44141a/google.png
02-28 16:57:15.159  1645  9902 D conversations: connection: com.android.okhttp.internal.huc.HttpURLConnectionImpl:https://XXXXXXXX:5281/upload/28646725-9516-4dbc-bc63-33455f44141a/google.png
02-28 16:57:48.792  1645  1645 D conversations: app switched into background

Regards
Chris

**Comment by iNPUTmice** [comment]
My guess is that the server doesn't respond to HEAD requests. But you censoring the domain name doesn't make guessing easy.

**Comment by Griswold666** [comment]
@iNPUTmice:
you are right, so I tested the server response for HEAD request by myself. I think that the server responds correctly, am I right? (same response if client is not within LAN)

 wget -S --spider https://XXXXXXXX.de:5281/upload/28646725-9516-4dbc-bc63-33455f44141a/google.png

Spider-Modus eingeschaltet.  Prüfe ob die Datei auf dem Server existiert.
--2017-02-28 19:50:25--  https://XXXXXXXX.de:5281/upload/28646725-9516-4dbc-bc63-33455f44141a/google.png
Auflösen des Hostnamen »XXXXXXXX (XXXXXXXX)«... 192.168.6.120
Verbindungsaufbau zu XXXXXXXX (XXXXXXXX)|192.168.6.120|:5281... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort...
  HTTP/1.1 200 OK
  Connection: Keep-Alive
  Content-Type: image/png
  Date: Tue, 28 Feb 2017 18:50:25 GMT
  Etag: 801-8095f-13df-58b59dd8
  Content-Length: 5087
  Last-Modified: Tue, 28 Feb 2017 15:57:12 GMT
Länge: 5087 (5,0K) [image/png]
Datei auf dem Server existiert.

**Comment by iNPUTmice** [comment]
You need to have mutual presence subscription with the sender

**Comment by Griswold666** [comment]
Thanks, that works great.

**Comment by licaon-kter** [comment]
Still having this issue on 1.18.0, at any auto size.

wget output: https://gist.github.com/licaon-kter/55d11e76446d93fe3b675649687f64b9

**Comment by licaon-kter** [comment]
Update, after downgrading another device to 1.17.1 auto-download works between these two, so I guess #2418 might be at fault here.
