### ISSUE TITLE
Part of dialog remains on screen after closing on Asus Zenfone 2

### ISSUE THREAD

**Issue by DMantis** [siacs/Conversations#2326]
#### General information

* **Version:** 1.16.2
* **Device:** Asus Zenfone ZE550ML (Z008D)
* **Android Version:** Android 5.0 stock
* **Server name:** conversations.im
* **Conversations source:** F-Droid

#### Steps to reproduce
1. Open any chat and get back to contacts screen

#### Expected result
Expect to see the contact screen without part of the chat.

#### What I really see
[![photo_2017-02-28_20-55-48.jpg](https://s27.postimg.org/ny3craour/photo_2017_02_28_20_55_48.jpg)](https://postimg.org/image/924tjpdfz/)

#### Debug output
D/conversations(11548): restoring roster
D/conversations(11548): update unread count to 0
D/conversations(11548): changed@conversations.im: socket was null during force close
D/conversations(11548): changed@conversations.im: connecting
D/conversations(11548): used lollipop variant to discover dns servers in 1 networks
D/conversations(11548): using dns server: 217.118.66.243 to look up conversations.im
D/conversations(11548): AxolotlService (changed@conversations.im): Got Axolotl signed prekey record:1
D/conversations(11548): restoring messages
D/conversations(11548): restored all messages
D/conversations(11548): app switched into foreground
D/conversations(11548): load more messages for conversations.im prior to 2017-02-28T16:47:30.178Z
D/conversations(11548): start merging phone contacts with roster
D/conversations(11548): finished merging phone contacts
D/conversations(11548): resetting all attempt counts
D/conversations(11548): using dns server: 10.10.32.10 to look up conversations.im
D/conversations(11548): changed@conversations.im: using values from dns xmpps.conversations.im[5.175.28.100]:443 tls: true
D/conversations(11548): app switched into background
D/conversations(11548): changed@conversations.im/phone: Authenticating with SCRAM-SHA-1
D/conversations(11548): app switched into foreground
D/conversations(11548): setting scroll position on fragment
D/conversations(11548): load more messages for conversations.im prior to 2017-02-28T16:47:30.178Z
D/conversations(11548): changed@conversations.im: logged in
D/conversations(11548): changed@conversations.im: starting service discovery
D/conversations(11548): changed@conversations.im: server caps came from cache
D/conversations(11548): changed@conversations.im: stream management(3) enabled (resumable)
D/conversations(11548): changed@conversations.im: Requesting block list
D/conversations(11548): changed@conversations.im: successfully enabled carbons
D/conversations(11548): Received blocklist update from server
D/conversations(11548): AxolotlService (changed@conversations.im): Bundle 1800662932 in PEP was current
D/conversations(11548): AxolotlService (changed@conversations.im): Announcing device 1800662932
D/conversations(11548): changed@conversations.im: online with resource phone
D/conversations(11548):changed@conversations.im: fetching roster version 833864e06dea5c4e3f171c7a40a592a8b883bddd
D/conversations(11548): changed@conversations.im: running mam query with=*, start=2017-02-28T16:47:30.178Z, end=2017-02-28T17:58:56.026Z, order=NORMAL, catchup=true
D/conversations(11548): changed@conversations.im sending csi//active
D/conversations(11548): changed@conversations.im: retrieved own device list: [1800662932]
D/conversations(11548): changed@conversations.im: finished mam after 0(0) messages. messages left=true
D/conversations(11548): AxolotlService (changed@conversations.im): Received PEP device list ([1800662932]) update from changed@conversations.im, processing...
D/conversations(11548): start merging phone contacts with roster
D/conversations(11548): finished merging phone contacts
D/conversations(11548): start merging phone contacts with roster
D/conversations(11548): finished merging phone contacts
D/conversations(11548): start merging phone contacts with roster
D/conversations(11548): finished merging phone contacts
D/conversations(11548): start merging phone contacts with roster
D/conversations(11548): finished merging phone contacts
D/conversations(11548): start merging phone contacts with roster
D/conversations(11548): finished merging phone contacts
D/conversations(11548): start merging phone contacts with roster
D/conversations(11548): finished merging phone contacts
D/conversations(11548): start merging phone contacts with roster
D/conversations(11548): finished merging phone contacts

**Comment by SamWhited** [comment]
This is just how the "drawer" works in Android; it's not a Conversations specific thing.

**Comment by DMantis** [comment]
I don't have that problem in other applications. What should I do then?

**Comment by licaon-kter** [comment]
It's ok, that's what it should be. 

/Close this as invalid

**Comment by uchchishta** [comment]
It's called Sliding Panel Layout.

**Comment by DMantis** [comment]
Oh, ok. But I think the part of conversation on main screen is a bit weird. Looks like it has been made for tablets screens. There should be an option to choose.

**Comment by mimi89999** [comment]
I 100% agree. That part of a conversation on the right is a waist of space. Especially on small screens.

Instead of using the drawer, we could have a separate fragment for conversations list.
