### ISSUE TITLE
[Enhancement/FR] More Material Elements, Like Material Cards

### ISSUE THREAD

**Issue by uchchishta** [siacs/Conversations#2327]
It would be nice if there's:
Material Cards Chatlist
Material Cards contacts
Material Cards in acc|contact|conference details
Forced material icons in >lolipop
(Maybe some material motion)

**Comment by iNPUTmice** [comment]
I'm closing this because there is nobody around to do that for now. If you are a UI coder yourself feel free to create some demos on how you think it would look like and/or create a PR.

**Comment by kamalcha** [comment]
Hi @iNPUTmice I would like to jump in and try to design this. Is still opportunity still available?

**Comment by iNPUTmice** [comment]
@kamalcha yes sure.

**Comment by uchchishta** [comment]
@kamalcha are you working it? Any updates? :)

**Comment by Yasha08** [comment]
Hey @iNPUTmice, I would love to contribute with the designs. 
Is the opportunity still available?

**Comment by Erioldoesdesign** [comment]
Can someone let me know if I can close the associated open source design job for this issue? https://opensourcedesign.net/jobs/jobs/2017-03-15-Enhance-UI-Aspects-in-Conversations-app
