### ISSUE TITLE
Add support for Enter to send by default on CB/more obvious UI for that change?

### ISSUE THREAD

**Issue by jaduncan** [siacs/Conversations#2328]
I'm using Conversations on a Chromebook, and reaching up to the touch screen to send a message is a break in flow. My pony request is that pressing Enter on a physical keyboard would send a message rather than creating a need to use the touchscreen.

**Comment by licaon-kter** [comment]
The `Expert setting` of `ENTER sends` does not help?

**Comment by jaduncan** [comment]
It does, and please accept my apologies. I'm not sure how expert that is on chromebook in particular, though; in a desktop environment, this seems like expected behaviour.

**Comment by Aluisyo** [comment]
Already implemented.  Check in settings

**Comment by licaon-kter** [comment]
/close this

Chromebooks are a small % ;)

**Comment by iNPUTmice** [comment]
@jaduncan two questions

1) Is the PlayStore available on Chromebooks these days? Can one just install Conversations from there? Or are there extra steps involved?
2) I'm trying to change the default setting for Chromebooks - or more specifically for devices with a hardware keyboard. Are you willing to test that? You'll have to reinstall Conversations to see if the default setting works. Here is the commit: 8cce653a1f16e7b9ab4dd3aadb7320572928dcde

**Comment by jaduncan** [comment]
@iNPUTmice 

1) The Play Store is rolling out for all Chromebooks. Yes, it just runs the PS and then you can click through.
2) I'm willing to test it, and will get back to you when I've done so.

**Comment by licaon-kter** [comment]
@iNPUTmice https://developer.android.com/topic/arc/index.html#update-manifest too maybe
