### ISSUE TITLE
[FR] Sort users by last conversation date

### ISSUE THREAD

**Issue by ildar** [siacs/Conversations#2331]
Pushing "+" shows the list of contacts in alphabetical order.
I think having users sorted by last conversation date is much more natural, just like in main view.
The option for this would be great.

**Comment by griffindoors** [comment]
Or by most frequently contacted? 

Advanced: priority sort?

**Comment by ildar** [comment]
yeah, why not.

**Comment by iNPUTmice** [comment]
That's what the conversation overview is for.

**Comment by ildar** [comment]
I am sorry. Just installed the most recent version and still don't see any
"Overview" that would show the list of contacts "last contacted on top".
Could you please guide me? Or give a screenshot?
Thanks!

**Comment by licaon-kter** [comment]
The list of **active** chats is sorted like this.

The contact list however it is not.

**Comment by ildar** [comment]
This is obvious. Thanks.
The initial request was about the "Contact list", not the "Active chats".

**Comment by ildar** [comment]
@iNPUTmice , reopen?
