### ISSUE TITLE
[FR] Show some text in place of a cropped image in chat list

### ISSUE THREAD

**Issue by hareshkh** [siacs/Conversations#2333]
Currently, when a conversation has its last message as an image, a cropped image is displayed on the chat list. In place of this, a text can be displayed as : **You sent a photo** or **You received a photo**.

![screenshot_2017-03-03-01-38-51-637_eu siacs conversations](https://cloud.githubusercontent.com/assets/16576273/23524904/8f148686-ffb2-11e6-982b-dc4ae3a853ac.png)

**Comment by griffindoors** [comment]
I greatly prefer the image slice

**Comment by iNPUTmice** [comment]
I actually prefer the image as well
