### ISSUE TITLE
When viewing the block list, there should be an option to add a JID

### ISSUE THREAD

**Issue by SamWhited** [siacs/Conversations#2336]
Currently to add a JID to the block list I have to open a conversation with that JID, then block them, then close the conversation.

When viewing the block list from account details it would be nice if there was a way to add a JID to the list directly without opening a conversation.

**Comment by iNPUTmice** [comment]
When implementing that one shouldn't forget to revert that commit that disables the 'Show Block list' menu item on an empty block list.

**Comment by philpsst** [comment]
Can the block list be viewed directly without viewing contact

**Comment by licaon-kter** [comment]
Accounts->choose one->menu->show block list ?
