### ISSUE TITLE
The font size of the title of a conference changes while rotating the screen

### ISSUE THREAD

**Issue by participante0** [siacs/Conversations#2337]
#### General information

* **Version:** 1.16.2
* **Device:** Google Nexus 5X
* **Android Version:** Android 7.1.1 Stock
* **Server name:** -
* **Server software:** -
* **Installed server modules:** -
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Open a conference (MUC)
2. Rotate the screen

#### Expected result

I expect that the font size of the title remains the same when rotating the screen.
Instead, when the screen is vertically oriented, the font size is bigger than when it is horizontally oriented.

**Comment by iNPUTmice** [comment]
This is true for every single activity in Android.
