### ISSUE TITLE
Write a message to a specific resource.

### ISSUE THREAD

**Issue by Spacewalker2** [siacs/Conversations#2355]
#### General information

* **Version:** eg 1.12.2
* **Device:** eg Google Nexus 5
* **Android Version:** eg Android 6.0 Stock or Android 5.1 Cyanogenmod
* **Server name:** eg conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by hareshkh** [comment]
@Spacewalker2, would you explain you issue in a bit more detail.

**Comment by iNPUTmice** [comment]
Please read the `README.md` and search the issue tracker for similar issues before you open new ones.
