### ISSUE TITLE
Quick UI for spam control: Block sender & End Conversation

### ISSUE THREAD

**Issue by ahilliard** [siacs/Conversations#2358]
#### General information

* Version 1.16.2
* Android 6.1 Stock

#### Steps to reproduce

1. Receive spam
2. Click conversation
2a. Spammer gets read receipt, ensuring more spam
3. Click top right menu
4. Click 'Contact Details'
5. Click top-right menu
6. Click 'Block Contact'
7. Click Back
8 Click top-right menu
9. Click 'End Conversation'

#### Desired result

1. Longpress, swipe, or otherwise select spammer's conversation
2. Sender is blocked, conversation ended without sending read receipt
3. Undo option offered

**Comment by iNPUTmice** [comment]
> Spammer gets read receipt, ensuring more spam

That's not true. RR are only send to contacts with mutual presence subscription.

**Comment by ahilliard** [comment]
Ah, glad to hear it. They keep sending more nevertheless... Look forward  to any UI efficiency to cope with it.
