### ISSUE TITLE
Feature request: Read only out-of-band file transfer support

### ISSUE THREAD

**Issue by SamWhited** [siacs/Conversations#2359]
When receiving a message with a file enclosed via [XEP-0066: Out of Band Data](https://xmpp.org/extensions/xep-0066.html) or an OOB IQ where the out of band URI has a scheme of `http:` or `https:`, it would be nice if Conversations could show the download button just as it does for messages transfered with HTTP upload.

**Comment by badarsh2** [comment]
@iNPUTmice I would like to propose an approach but I'm not sure whether it's quite robust:
- Identify whether the message has a scheme of `http:` or `https:`
- Identify whether it is a link to a file, for eg. PDF, mp3, mp4 etc
- Do the appropriate intent action as per the file extension after download completes

**Comment by badarsh2** [comment]
@iNPUTmice In the latest version, this feature already seems to be there for the user receiving the message, but for the sender, the message still appears as a URL....
