### ISSUE TITLE
Standard operation mode

### ISSUE THREAD

**Issue by mirabilos** [siacs/Conversations#2360]
I would like to request another operating mode, as opposed to the always-on mode Conversations currently provides.

I wish to be able to start Conversations like a normal program (like mcabber or Gajim), and for it to only go online then, and to have an Exit entry in the menu, and to go offline then, and to never use any network connectivity while offline, and to never go online automatically or at system boot time.

**Comment by SamWhited** [comment]
If you open your running apps list in Android and swipe it away, Conversations will close (this is the standard way to close apps on Android). The only time it runs in always on mode is if you've enabled the foreground notification (if you have a permanent notification from conversations in the status bar), but this is optional and can always be disabled again if you've enabled it and forgotten.

**Comment by iNPUTmice** [comment]
Exit buttons are an anti feature on Android. If you want to 'go offline' just disable the account(s).

**Comment by mirabilos** [comment]
Daniel Gultsch dixit:

>Exit buttons are an anti feature on Android. If you want to 'go
>offline' just disable the account(s).

Eh, nice attitude, arsehole. You could be a systemd developer.

Goodnight,
//mirabilos
-- 
(gnutls can also be used, but if you are compiling lynx for your own use,
there is no reason to consider using that package)
	-- Thomas E. Dickey on the Lynx mailing list, about OpenSSL

**Comment by mirabilos** [comment]
Sam Whited dixit:

>If you open your running apps list in Android and swipe it away,
>Conversations will close (this is the standard way to close apps on
>Android). The only time it runs in always on mode is if you've enabled
>the foreground notification (if you have a permanent notification from
>conversations in the status bar), but this is optional and can always
>be disabled again if you've enabled it and forgotten.

This is not correct.


Every time the mobile device starts and has network connection,
Conversations goes online on the jabber server, thus disclosing
to all contacts on the roster and the associated server admins
that the mobile device is started.

This is a huge privacy violation.


Furthermore, this leads to confusion when people then think that
the user is “online” and can thus talk, which is not necessarily
true, especially when the mobile device is used in a manner not
unlike a desktop client such as Gajim.


bye,
//mirabilos
-- 
18:47⎜<mirabilos:#!/bin/mksh> well channels… you see, I see everything in the
same window anyway      18:48⎜<xpt:#!/bin/mksh> i know, you have some kind of
telnet with automatic pong         18:48⎜<mirabilos:#!/bin/mksh> haha, yes :D
18:49⎜<mirabilos:#!/bin/mksh> though that's more tinyirc – sirc is more comfy

**Comment by SamWhited** [comment]
Apologies, you're right; you have to sign out of the acount and then swipe it away, I left out a step.
