### ISSUE TITLE
Feature request: Message self-destruct

### ISSUE THREAD

**Issue by qooob** [siacs/Conversations#2371]
Hi, Daniel.

It would be good to have a global option in settings to provide an ability to self-destruct a message (wipe from device).

**Options would have:**

1. Enable/disable self-destruct;
2. Timeout to self-destruct a message, after it was seen (default 10 seconds);
3. Ability to disable self-destruct by long press on the message.
----
Another one, it would also be good to have a long press and delete a message selectively. Not sure why it's still not there. In case correction is available by server, it would also be awesome to have an ability to delete the sent message by replacing previously sent message with `Message deleted` text.

**Comment by participante0** [comment]
> Please search the issue tracker for duplicate issues before you create new ones. #2223

**Comment by qooob** [comment]
_Self-destruct_ is the right way to call it. _Disappearing_ is not the right term.

**Comment by licaon-kter** [comment]
So this is only for your device (while the mentioned issue is for the partner) ?

You already have message deletion, albeit with a minimum of 24 hours, you want to propose maybe an optional timeframe input field, say for setting up deletion after XXX seconds?

**Comment by qooob** [comment]
No, it's not good.

I want to have an options described above. I don't always want to delete all messages. I don't want them to be deleted within 24 hours, as there should definitely an option for the time-to-live for the message.

**Comment by licaon-kter** [comment]
Again, only on **your** device, right?

**Comment by qooob** [comment]
Yes, I was talking about my device. For both in and out.

**Comment by qooob** [comment]
For the feature about `Delete for all` (like in Viber), the idea behind would be is to basically correct the message with a localized message saying `Message deleted`, in case supported by the server.

Having self-destruct messages within defined amount of seconds is a must for such software!

**Comment by iNPUTmice** [comment]
This feature is currently not on our todo list.

**Comment by qooob** [comment]
Why not?

**Comment by SamWhited** [comment]
Presumably for the same reason it's closed every single time someone opens this issue. Please read the duplicates that someone linked earlier.

**Comment by qooob** [comment]
I have read through the other threads. I couldn't find any _mindful_ responses to that.

> iNPUTmice: We don't want this kind of features in Conversations.

This kind of comment is definitely going against the idea of open-source project. Don't know, but by `we` who do you really mean? Whoever it is but it's not _us_.

This is security feature, whether you like to see it or not. This kind of _denial_ (closing and later locking the issue not letting people discuss it) potentially raises a lot questions and tarnishes the good name of Conversations.

----

Ask your self, whether you do the project _for people and driven by people_, where the underlying idea is _**freedom**_ or you satisfy your/some vague interests.

**Comment by iNPUTmice** [comment]
> This kind of comment is definitely going against the idea of open-source project.

You might be confusing *open-source project* with *democracy*.

Someone has to steer Conversations in the right direction otherwise we end up with unmaintainable mess of not working features.

**Comment by qooob** [comment]
I don't intend that. When we speak about the _core_ it should be done, even if the complexity is going to rise. Conversations is about security, privacy and freedom. It is not another proprietary app for chatting. At the same time, it's one of the many. 

Unless _Conversations_ has all possible (at least basic) advantages of security app, there would be no much reason in switching to it (for the vast majority). Nowadays even _Viber_ lets you delete sent messages for both sides - yourself and the recipient. _Conversations_ doesn't. At the same time, there is technical and straight forward solution to that.

About self-destructing messages it's a bit harder. Thinking about the code, I would suggest to make this option appear as per/contact feature, where you can directly set timeout.

Thinking further, self-destructive messages could be replaced with the _swipe-right_ to delete the message and _swipe-left_ to delete for yourself and recipient (in case the message was sent by you).
Not having delete option for _desired messages_ is crazy (sorry for being harsh).

The other very **serious security-wise flaw** of Conversations is that it _let's itself_ to be saved to Google Backup. Saying that, _it doesn't matter how_ secure your dialogs are, and which encryption do you use OMEMO/OTR/OpenPGP - **_it's not secure_**, because when you setup your phone and install the app, Google will restore all of the content of Conversations, including dialogs and of course accounts. It mean third-party has direct access to your <s>secure and free</s> way of chatting. 
I know that you can prevent in Android settings this feature in Backup & Restore section but it's not enough. It should be _**off/blocked**_ by nature. It's possible to do. Some apps prevent this from happening and _don't let Google Backup to access the app's data_.

---

I don't think I do confuse it with democracy.

> “Free software” means software that respects users' freedom and community. “free software” is a matter of liberty, not price."

**Comment by blaueente** [comment]
I totally agree that conversations should never forcibly restrict its users.
However, if correctly engineered, this feature will greatly enhance privacy exactly when I trust myself *and* the conversation contact.
The following is about convenience and "security by default", not about that "snapchat"-style-enforcement.

What about a message to the contact(s): "XXX asks that you set the automatic expiry for future messages of this chat to X days/hours... Do you agree?"  This expiry time could be set per chat, even as default.
and also, retroactively:
"XXX requests that the last N messages are deleted within X days/hours, should conversations do that automatically?"

Reasoning: Let's say, I chat about some sensitive topic, say, health, politics, whatever, with one trusted contact or in a trusted group chat. Then this will be on record forever on my phone, and everybody else's phone and thus might endanger us forever, as phones get lost, or stolen, or hacked, or infected, or seized.

1. Local:  I delete the whole history, but first, I must actively do that each time after I said something sensitive, and I lose all history, not just the few messages from the current sensitive conversation.
2. Contacts: I trust the other person(s) to respect my wish to delete of specific parts, and they might agree. So I ask them to do the same.
But they might not know how to delete the log, or forget, or might not want to loose all history, or might not have the opportunity to.

**Comment by blaueente** [comment]
> The other very **serious security-wise flaw** of Conversations is that it _let's itself_ to be saved to Google Backup. Saying that, _it doesn't matter how_ secure your dialogs are, and which encryption do you use OMEMO/OTR/OpenPGP - **_it's not secure_**, because when you setup your phone and install the app, Google will restore all of the content of Conversations, including dialogs and of course accounts. It mean third-party has direct access to your secure and free way of chatting.
> I know that you can prevent in Android settings this feature in Backup & Restore section but it's not enough. It should be _**off/blocked**_ by nature. It's possible to do. Some apps prevent this from happening and _don't let Google Backup to access the app's data_.

Blocking google backup also blocks local backup-and-restore for that app. I think this is deliberate, in that this setting is mostly used to enforce backup-replay against (!) the user, and I consider this an anti-feature. Specifically if you are security conscious and disable google backup, this setting also denies you the possibility to have any other local backup.
I suspect google wants to make it as hard as possible for a user to not use the cloud.

**Comment by licaon-kter** [comment]
> Blocking google backup

Is already done, for a while now. You can only use the in-app Backup&Restore.
