### ISSUE TITLE
XEP-0191 missing Domain blocking

### ISSUE THREAD

**Issue by sgawlik** [siacs/Conversations#2373]
Any Chance Conversations support Domain (@domain.tld) blocking as defined in XEP-0191?

See https://xmpp.org/extensions/xep-0191.html Chapter 6 - JID Matching.

As Conversations claims to support XEP-0191 it would be nice to see the full XEP-Support as well.

Currently there is only the User blocking command available in the app?

thnx, Sven

**Comment by SamWhited** [comment]
You can block a domain the exact same way you block a user; either go to the block list (in recent versions) and hit add (and then type in a domain instead of a user's JID) or start a conversation with the domain and hit block.

**Comment by sgawlik** [comment]
Ok, my fault. Thnx for the hint.

**Comment by klement** [comment]
Where is this block list located? I wasn't able to find it in (per play store) latest conversations - 1.17...

**Comment by sgawlik** [comment]
Easy to find in "Konten verwalten" (Manage Accounts) - choose your Account and klick on the three dots.
There you find "Sperrlisten anzeigen" (Show Blocklist).
