### ISSUE TITLE
Make the user aware of encrypted chat options

### ISSUE THREAD

**Issue by zuglufttier** [siacs/Conversations#2374]
In https://github.com/siacs/Conversations/commit/035d0c79572d5981c53d1bff7f30b484c6542f17 the default encryption was removed. I understand that there are reasons for this.

However encryption should be as easy as possible to use for the end user. The average user might possibly never enable OMEMO because she looks at WhatsApp or other messengers which do encryption automagically and she thinks that Conversations is encrypted by default, too. 

How about OMEMO is enabled by default if the chat partner is using a recent version of Conversations, too?

Alternatively, unencrypted chats should be penalized more so that the user is aware that something is not working as good as possible. Something like accepting a self-signed certificate in a browser, e.g.: "I am aware that the content of this chat can be monitored by third parties."

**Comment by andersruneson** [comment]
How do Conversations know that any of the two users will join with a non-omemo-suppprting client after omemo is enabled by default? Then the joining client won't have working carbon messages and won't be able to read the encrypted mam log. Conversations cannot then degrade to non-encrypted automatically.

**Comment by weiss** [comment]
> However encryption should be as easy as possible to use for the end user.

Enabling E2EE by default *does* break things for some fraction of the end users.  Handling that breakage will be anything but easy for most of them.  Many will perceive it as yet another example of "XMPP just doesn't work reliably".

So there's a trade-off.  You might view the ubiquitous use of payload encryption as critical enough to warrant the issues.  Personally, I find it more important to make the UX in a federated network as good as possible in order to minimize the number of users switching back to centralized services.

> How about OMEMO is enabled by default if the chat partner is using a recent version of Conversations, too?

As @andersruneson pointed out, you can never know what clients your contacts are using unless all of them are currently online.

**Comment by zuglufttier** [comment]
Thanks for your clarification, all this is very hard to understand for the average user.

I tend to agree that usability is more important right now, to make make things work in all federated systems.

But what about penalizing unencrypted chats? I don't think it's enough to say that a chat is unencrypted.
Can we make something like: "Are you sure you want to send an unencrypted message? You could use OMEMO instead."

**Comment by weiss** [comment]
I think nagging the user to enable OMEMO has the same implications as simply enabling OMEMO by default.

In my view, the way forward is fixing the underlying issue, i.e. adding OMEMO support to all popular clients.

**Comment by mimi89999** [comment]
On top of that, encryption is worth nothing without fingerprint verification. A MITMing party can be an OMEMO end in the middle...

**Comment by uchchishta** [comment]
> Make the user aware of encrypted chat
https://github.com/KeepSafe/TapTargetView helps?

**Comment by loveuvfreight** [comment]
i would not consider it nagging to show texting bubbles in a different color, or even outlined in a high contrast color

maybe blink the padlock or use a callout once?

even after verifying otr stuff with new zom contact i was largely unaware the padlock was the solution to send somethinf other than unencrypted text (as shown in composition window,and announcement from zom server)

**Comment by zuglufttier** [comment]
Maybe a tutorial would clarify some things. Not that everybody might use it. What @uchchishta suggested looks interesting.

I don't think this is of high importance right now but it would surely help some people in understanding the app and its possibilities.

**Comment by Varbin** [comment]
Why can't you let the user decide if he wants to use OMEMO by default?

Telling a user every day that on on specific chat encryption is off is probably the wrong way.  But what about asking it for a (later changable) global setting? Like global off or on. At the first start the user is asked but can later change this in the settings.

Additionally a user should be able to decide if he wants to turn encryption on or off in a specific chat or not.

I personally think that this is the best and most user friendly solution.

**Comment by iNPUTmice** [comment]
C2 makes e2ee by default. so the regular users doesn’t need to be aware of this.
