### ISSUE TITLE
Please use QR-Code instead of Aztec-Code

### ISSUE THREAD

**Issue by Buntbart** [siacs/Conversations#2375]
Recognition of Conversations' Aztec 2D-Code is quite poor in comparison to Gajim's QR-Codes. Is it possible to switch to QR for the OMEMO-Key?

**Comment by ventrciousn** [comment]
no

orders of magnitude more is aztec use in the world than qr code

aztec is the superior encoding PER SE

**Comment by Buntbart** [comment]
If I can not read it, it is superior and useless

**Comment by licaon-kter** [comment]
You don't read it, an application does.

What application do you use that does not support it?

**Comment by Buntbart** [comment]
Barcode Scanner from F-Droid. You have to adjust the camera perfectly to the barcode, and even then it hardly works most of the times.
