### ISSUE TITLE
Text box keeps the text you type after press send button

### ISSUE THREAD

**Issue by srgcdev** [siacs/Conversations#2377]
#### General information

* **Version:** 1.17.0
* **Device:** Google Nexus 5x, nexus 10
* **Android Version:** eg Android 6.0 Cyanogenmod
* **Server name:** conversations.im
* **Server software:** ejabberd 16.09
* **Installed server modules:** Stream Managment, CSI, MAM...
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Type a message and press the send button
2. Sometimes the message is keept in the text box although the message was sent

#### Expected result

What is the expected output? What do you see instead?
Text box should be always empty after send a message

**Comment by iNPUTmice** [comment]
Can you narrow down the conditions under which this is happening? Are you using any kind of encryption?

**Comment by srgcdev** [comment]
I don't how is happening. I have OMEMO enabled and it just happens only 3 - 4 times (with OMEMO enabled and disabled). But there is a few days I can't reproduce the error...

**Comment by srgcdev** [comment]
I can reproduce the problem. The problem is produced with some misspelled words and you send the message.

For example, if you type "casu" or "mathe" with english language selected with stock keyboard from cyanogenmod or omnirom and you send the message.

**Comment by licaon-kter** [comment]
Disabing spellcheck (or whatever you have there, autocompletion, dictionary etc) helps?

**Comment by srgcdev** [comment]
If I disable the option "Show correction suggestions" in Settings -> Language & input -> Android keyboard (AOSP) -> Text Correction -> Show correction suggestions, then the problem can not be reproduced.

**Comment by iNPUTmice** [comment]
This should be 'fixed' with 1.17.1

Interestingly this is probably a bug in the keyboard application that's why I had you hunt down the bug a little more even though a work around has been made available a couple of days ago.

**Comment by srgcdev** [comment]
Thanks. Works well in 1.17.1.
