### ISSUE TITLE
The last online status is wrong

### ISSUE THREAD

**Issue by mimi89999** [siacs/Conversations#2378]
#### General information

* **Version:** 1.17.0
* **Device:** Samsung Galaxy S4 Mini (serranoltexx)
* **Android Version:** LineageOS 14.1 (Android 7.1.1)
* **Server name:** self hosted
* **Server software:** Prosody trunk
* **Installed server modules:** All for Conversations compliance tester
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Connect with two clients (in that case Gajim and Conversations)
2. Logout from one client (in that case Gajim)
3. Wait a bit....
4. Logout from the other client (Conversations)
5. Ask your contact to tap on your avatar and check when you were last online.
Sometimes, Conversations won't display the time of Logout from last resource, but the time of logout from the other resource. In my case the contact logged out from Gajim 6 hours before me checking and from Conversations 20 minutes ago (actually he probably turned off his phone or lost WiFi). Conversations said he was last online 6 hours ago...

#### Expected result

Show the real last online time.

**Comment by therob84** [comment]
I can confirm this bug with Conversations 1.18.4 and jabber.de with all contacts (most also use jabber.de and conversations, some ChatSecure).

**Comment by iNPUTmice** [comment]
XMPP doesn't provide information to make this 100% reliable. And I personally don't care enough about this 'feature' to change that.
