### ISSUE TITLE
Carbon copy

### ISSUE THREAD

**Issue by suchatorg** [siacs/Conversations#2380]
#### General information

Version:
1.17.0

With Gajim open the messages do not enter into Conversations.
I do not know if it's Gajin's problem or Conversations, the server supports carbon copy.

**Comment by WildYorkies** [comment]
@suchatorg Are you using a certain kind of encryption? If all of your devices are using different forms of encryption, it may prevent carbon copies. See: https://xmpp.org/extensions/xep-0280.html#security

Not sure how it works exactly, though.

**Comment by suchatorg** [comment]
Do not use any type of encryption, I did the test with Gajim and other clients worked well, the problem is only with Conversations

**Comment by suchatorg** [comment]
It seems that the problem is not Conversations
, with other clients I get the first message, the rest not when Gajim is open.

Thank you very much.
