### ISSUE TITLE
mam_muc doesn't work with prosody anymore

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [siacs/Conversations#2381]
#### General information

* **Version:** 1.17.0
* **Device:** LG G3
* **Android Version:** Lineageos 14
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** smacks, mam, mam_muc
* **Conversations source:** f-droid

Since the latest revision of prosody's community module `mod_mam_muc` the module doesn't support the mam:0 namespace anymore but the mam:1 namespace.
Conversations since 1.17.0 doesn't support mam:1 and only mam:0 or mam:2.

Could you add support for mam:1 in conversations?

It seems supporting mam:2 in mod_mam_muc seems to be complicated in prosody, hence only the support of mam:1

Latest module revision:
https://hg.prosody.im/prosody-modules/rev/b8a66805459e

**Comment by iNPUTmice** [comment]
I suggest you downgrade to an older version. Or bump the namespace.

**Comment by shiba89** [comment]
Actually from what I tested Conversations seems to be able to retrieve messages even if it says that mam is not supported

**Comment by tmolitor-stud-tu** [comment]
> Actually from what I tested Conversations seems to be able to retrieve
> messages even if it says that mam is not supported
The newest mod_mam_muc provides the latest mam namespace version (mam:2), so 
all is well now.

When I talked to the prosody developers it sounded like it would take several 
month to update the module to the latest namespace.

In reality it only took about one month :)
