### ISSUE TITLE
Don't show @conversations.im while I'm typing new username.

### ISSUE THREAD

**Issue by wetubeyou** [siacs/Conversations#2383]
0. I'm using my own XMPP server(company network)
1. Click "add user" button.
2. Conversations suggest to push "(inputwords)@conversations.im" - I don't need it.

**Comment by iNPUTmice** [comment]
It will suggest all known XMPP servers. It might not be useful for you. But it sure is for others.

**Comment by wetubeyou** [comment]
Then why not allow user to hide this?
