### ISSUE TITLE
identify contact's client, notifye of limitations

### ISSUE THREAD

**Issue by loveuvfreight** [siacs/Conversations#2385]
list would obviously not be exhaustive 

is there some way to interrogate contact's client?  like a matrix show for server capabilities

**Comment by iNPUTmice** [comment]
This is not on our todo list for now.

**Comment by STPKITT** [comment]
I really support this feature request. I could help several contacts that had problems with OMEMO and other stuff by just using Gajim to look up the client and version of the client used by them. So I'd appreciate if Conversations would show the client(s) used by a contact in the contact's details.
