### ISSUE TITLE
Add option to show QR code for verified other own device

### ISSUE THREAD

**Issue by RalfJung** [siacs/Conversations#2388]
#### General information

* **Version:** eg 1.17.0
* **Conversations source:** F-Droid

#### Usecase

I have scanned my Laptop's OMEMO key QR code with my phone, so my phone trusts my laptop. Now I am meeting a friend and want him to verify my OMEMO keys. I can show him the QR code of my phone's key, so he can verify that one, but since I do not always carry my laptop with me I cannot show him my laptop's OMEMO key QR code. Since scanning a QR code is the only way (that I found so far) to make a key "trusted and verified" in Conversations, this means messages from my laptop will stay unverified for most people.

#### Proposed solution

Add an option for my phone to show the QR code of my laptop. So for "own devices" with a verified key, e.g. long-pressing that key could show an option like "show QR code". My friend can scan that code from my phone's screen to verify my laptop's key.

#### Alternative solution that goes even further

To make the key verification less of a hassle, my phone could actually put all fingerprints of all my active devices that it trusts into one QR code. So now my friend wouldn't have to scan one QR code per device of mine (we're sure going to forget one), instead he'd scan one code and get the full set of currently active trusted devices.
Scanning such a QR-code could even optionally *untrust* all QR codes that are not shown, making sure that my friend trusts exactly the same set of devices for my account as my phone does.

**Comment by iNPUTmice** [comment]
> To make the key verification less of a hassle, my phone could actually put all fingerprints of all my active devices that it trusts into one QR code.

That's already implemented

**Comment by RalfJung** [comment]
Oh, strange. That didn't seem to work yesterday then when I did key syncing with my friends. But maybe we did the scanning in the wrong order, first scanning the laptops and then the phones, and hence did not notice...

So, well, thanks for implementing this :)
