### ISSUE TITLE
[UX suggestion] Get rid of the 'last attachment action' button and move the 'choose attachment action' button to its place.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [siacs/Conversations#2389]
I very often find myself tapping the last attachment action button (on the bottom of the screen), then pressing back and tapping the choose attachment action (on the top of the screen) button and choosing a different action, because I didn't want to do what the first button did.

It's absolutely pointless to have two buttons for one action in my opinion. The single additional tap is insanely little in comparison to the hassle of waiting till the camera/file browser/voice recorder opens, closing it and then tapping two times.

It should be very simple to change too.

**Comment by iNPUTmice** [comment]
You can disable the quick action in the settings.
