### ISSUE TITLE
Wrongly identifies server messages as message from stranger

### ISSUE THREAD

**Issue by Natureshadow** [siacs/Conversations#2394]
#### General information

* **Version:** 1.17.0
* **Device:** SAMSUNG Galaxy Note 4
* **Android Version:** LineageOS 14.1
* **Server name:** self hosted
* **Server software:** ejabberd 16.04
* **Installed server modules:** all the cool stuff
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Get a server message

#### Expected result

Conversations treats the sender as stranger and does not notify, etc. The server JID should be an exception to that handling and not be expected to be on the roster.

#### Debug output

Not necessary.

**Comment by iNPUTmice** [comment]
This has been fixed in 1.17.1
