### ISSUE TITLE
On build: PushManagementService.java:94: error: cannot find symbol

### ISSUE THREAD

**Issue by petercelentano** [siacs/Conversations#2396]
Hi all, 

When attempting to build this project, I get the following error:

~/Conversations/src/playstore/java/eu/siacs/conversations/services/PushManagementService.java:94: error: cannot find symbol
                                        String token = instanceID.getToken(mXmppConnectionService.getString(R.string.gcm_defaultSenderId), GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);

What can I do to rectify this issue?

My build env is setup in centos 7 with android-sdk version 25.0.4

Thank you!

**Comment by Kandr0s** [comment]
https://github.com/siacs/Conversations/blob/master/README.md#how-do-i-build-conversations

**Comment by petercelentano** [comment]
Sorry, I missed that in the readme.  Maybe it's worth having a separate BUILD.md?
