### ISSUE TITLE
Security enhanced fork of Conversations

### ISSUE THREAD

**Issue by AltNico** [siacs/Conversations#2397]
First of all: thank you for your amazing messenger. Vielen vielen Dank!

I'm thinking of creating a security enhanced fork of Conversations, but before I take any actions I want to make sure that the original developers are okay with it.

These are the main changes I intend to do:
* [Disable unencrypted messages](https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/Config.java#L15)
* [Only use internal storage](https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/Config.java#L103)
* Disable option to trust certificate by simply pressing "Yes" (user has to import the certificate)

About these changes I'm unsure:
* Only allow OMEMO at all, to simplify usage
* [Hide messages text in notifications](https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/Config.java#L48)
* [Encrypt on HTTP upload](https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/Config.java#L97)
* [Force usage of TOR](https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/Config.java#L47)

For sure I'll not use the name "Conversations" for the app nor the app icon. I want to clearly state that the app is not affiliated in any kind to Conversations and that people should consider to regularly donate to Conversations if they like the app.

The app should be signed with my key and available over the following ways, prioritized by their order:
* Reproducible built in F-Droid
* GitHub/GitLab releases
* Google Play  

So, @iNPUTmice: are you okay with this fork? If so, you can close this issue and I thank you for the attention.

**Comment by Natureshadow** [comment]
>* Disable encrypted messages

WTF?

**Comment by AltNico** [comment]
@Natureshadow 
> WTF?

Oops! Sorry, I meant unencrypted. Thanks for the hint!

**Comment by SamWhited** [comment]
> TOR

Obligatory nit pick: the product is called "Tor" (like the onion).

**Comment by d9h02f** [comment]
https://github.com/siacs/Conversations/blob/master/LICENSE

You don't have to ask for permission, just follow the license.

**Comment by licaon-kter** [comment]
While forking is within your rights, I guess this would work better as added features to Conversations, less fragmentation.

I can imagine these as first-start options during a tour of features of sorts that explains them.

**Comment by andreygursky** [comment]
> Only allow OMEMO at all, to simplify usage

The decision of CoyIM not to support OMEMO is not friendly (e.g., https://github.com/twstrike/coyim/issues/421). Please do not make the same (though instead of dropping OMEMO, drop OTR). Clear you can have no time to support many different encryption methods. Then a compromise is to modularize it. Make an OMEMO module and offer others to implement OTR,.. ones, which you would include in your sources.

**Comment by andreygursky** [comment]
> Encrypt on HTTP upload

Do you consider HTTP upload secure enough? Wouldn't it leak privacy information on public MUCs?

**Comment by iNPUTmice** [comment]
The GPL allows you to do that.
