### ISSUE TITLE
Allow user to change contact images.

### ISSUE THREAD

**Issue by ghost** [siacs/Conversations#2399]
1. In Contacts tab, long press people, and select "view details".
2. Tap "A" or something(very big alphabet).

Expected result:
Let user to pick images immediately. Simple.

Actual result:
Asking to add this XMPP user to address book.
I don't use contacts app, in fact I disable it. When select "add", conversation immediately cancel it.

Also, why should I want to add XMPP account(not email) to android's address book? Make no sense.

**Comment by iNPUTmice** [comment]
> why should I want to add XMPP account(not email) to android's address book?

To assign them the name and picture from the address book.
