### ISSUE TITLE
Add an option to forbid sending files.

### ISSUE THREAD

**Issue by ghost** [siacs/Conversations#2400]
[X] Don't allow me to send nor receive files(not text) if I'm not using Wifi.

Because 3G/4G/5G costs money and this is not unlimited.
You might say "don't tap download then", but accident might happen(tap by mistake due to condition or bad screen calibration).

If this option is enabled, the sender who tried to send a file will got a rejection notice automatically.

**Comment by d9h02f** [comment]
> (tap by mistake due to condition or bad screen calibration)

Then calibrate your screen correctly, and tap 'cancel' when you accidentally hit 'download'.

**Comment by iNPUTmice** [comment]
This is currently not on our todo list
