### ISSUE TITLE
"Hide offline" as visual improvement

### ISSUE THREAD

**Issue by ghost** [siacs/Conversations#2401]
Without checking "Hide offline", this could be improved.

e.g.,

User1
User3
---
User4

See, it's separated by 1 line. Upper part is online, and lower part is offline.
Many IM software like Pidgin or Tox already have this option, instead of hiding contacts.

**Comment by chris-stones** [comment]
I would love to see this implemented too.
It would nice to see who is offline without having to toggle the 'hide offline' setting, and looking for who dissapears. Perhaps grey-out offline contacts, or perhaps add a red dot / 'x' / whatever.

**Comment by licaon-kter** [comment]
Why isn't "enable dynamic tags" is Settings enough?

**Comment by licaon-kter** [comment]
Why isn't "enable dynamic tags" is Settings enough?

**Comment by chris-stones** [comment]
"Show dynamic tags - display read only tags underneath contacts"

Ahh... The feature is already implemented... Just hidden behind a cryptic setting....

May I suggest having that setting enabled by default, or giving it a sane name. Perhaps 'show online status'.

Thanks!
Really enjoying this app!

**Comment by licaon-kter** [comment]
"Online" in the desktop world is pretty simple: internet or not.

But in the mobile world, trickier: is it Wi-Fi, is it mobile, do you have signal, how much signal, what network type (2G/3G/...), did Doze hibernate your app, do you have Google services, did you install the app from the store so you have Push, or from elsewhere and it checks every 5 mins, did you turn off all internet and gone to sleep... many variables, but the server side should cover them (MAM, Stream, etc), as in: just write your message and it will be delivered (eventually maybe even right now).

**Comment by licaon-kter** [comment]
@chris-stones: 
"Online" for a desktop means simply: internet or not.
On the mobile side things are trickier, too many variables: Wi-Fi, mobile data, signal strength, network type, Push services or not, etc, and these should be taken care of by the server side (MAM, Streams etc), so just write, it will be delivered eventually (or even right now).

@iNPUTmice: Do close this.
