### ISSUE TITLE
"End this conversation" as "X" button

### ISSUE THREAD

**Issue by ghost** [siacs/Conversations#2402]
When you talk to your lover, you'll get this GUI:

> <- lover (keymark) (binder) (...) (X)
> "what?"
> 
> _____->

Adding (X) to top-right corner. If you tap it, it'll show this:
"Do you want to end conversation and delete history?" "No"     "Yes"

Because current method take some time.
(...) tapped -> eyeroll. "Damn... Where is 'end this conversation'..." -> finally found it, tap -> Asked -> Ugrrr!

**Comment by licaon-kter** [comment]
What other Android app did you see to have something like this? That's some sort of desktop paradigm stitched here.
