### ISSUE TITLE
A '>' character before a line starts a quote

### ISSUE THREAD

**Issue by jmf** [siacs/Conversations#2403]
#### General information

* **Version:** 1.17.0
* **Device:** Samsung Galaxy S4 Mini and 
* **Android Version:** Android 4.3.1 Cyanogenmod
* **Server name:** any server
* **Conversations source:**  F-Droid

#### Steps to reproduce

1. Write the character '>' followed by some other characters

#### Expected result
The character '>' with text behind it should be displayed. 

#### Actual result
Instead the piece of text after the '>' is treated like a quote. While this might be desirable in some situation, it is very annoying when using the character for other things, like smileys.
This could possibly be made a choice in the options menu.

**Comment by iNPUTmice** [comment]
Can you provide an example for such a smiley that gets interpreted as a
quote?

**Comment by uchchishta** [comment]
@inputmice >:) outputs a empty bubble (I just tried now)

**Comment by licaon-kter** [comment]
Maybe you can separate a quote from a smiley by always expecting a space:
* smiley is: `>:(`
* quote is: `>SPACE:(`

**Comment by jmf** [comment]
An other example would be Japanese-Style smileys like >u< and the like.

**Comment by iNPUTmice** [comment]
Fixed in 2302122d8ed0ea975f99138e2ed2b07d3f504b8a
