### ISSUE TITLE
[Q] What is (2) mean?

### ISSUE THREAD

**Issue by ghost** [siacs/Conversations#2405]
When I registered to Duckgo public XMPP server for the first time, my contact shows

> xxxx@dukgo.com (2)

What is "(2)"? I didn't use this account on any devies except this one.
Does this mean someone using my account?

https://duck.co/blog/post/2/using-pidgin-with-xmpp-jabber

**Comment by iNPUTmice** [comment]
It means your contact is logged in with two devices.
