### ISSUE TITLE
Notifications while Conversations is opened

### ISSUE THREAD

**Issue by l-jonas** [siacs/Conversations#2406]
It's required to close Conversations (open the Homescreen, ...) to get a notification and the notification sound. It would be good if the notification sound would be played (eventually optional via a setting) when Conversations is in the foreground.

**Comment by Buntbart** [comment]
+1

**Comment by renarena** [comment]
+1

**Comment by tmolitor-stud-tu** [comment]
+1

**Comment by l-jonas** [comment]
https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/services/NotificationService.java#L179 needs to get changed. Instead of doing nothing, a sound should be played (ideally only if chosen at the preferences).

**Comment by mis2417** [comment]
+1

**Comment by Nits2407** [comment]
Conversation app not connecting with Openfire (4.1.4)

**Comment by WarrenBKN** [comment]
https://play.google.com/store/apps/details?id=com.rageconsulting.android.lightflow&hl=en

enable sound when screen on is an option

You can fire notifications for people or message contents and other fun options

**Comment by azrdev** [comment]
possible duplicate: #1582

**Comment by l-jonas** [comment]
This is a duplicate of https://github.com/siacs/Conversations/issues/2276
