### ISSUE TITLE
Cancel OTR "waiting" messages

### ISSUE THREAD

**Issue by Cryptosaurus** [siacs/Conversations#2408]
I've tried to send an OTR message to a contact using Google Hangout.  Since Hangout doesn't support OTR, he received a message saying "I would like to start a private (OTR encrypted) conversation but your client doesn't seem to support that".  So far, so good.
The problem is that Conversations keeps trying to send the OTR message (it is shown as "waiting..."), and the contact receives the error message over and over...  Is there a way to cancel the "waiting" message?

#### General information

* **Version:** 1.16.2
* **Android Version:** Cyanogenmod 12 Unofficial
* **Server name:** gmail.com
* **Conversations source:** F-Droid

**Comment by iNPUTmice** [comment]
Yes. Send an unecrypted one.

**Comment by Cryptosaurus** [comment]
I feel a bit stupid, that worked just fine...
Thanks!
