### ISSUE TITLE
File Transfer to Zom Android

### ISSUE THREAD

**Issue by stephendaniel** [siacs/Conversations#2411]
Hi, I try to send image from Conversation to Zom Android, but it always failed. I am using ejabberd as my xmpp server and already turn on the mod_http_uplod. Is it possible to send image to different xmpp client other than conversation?

**Comment by mimi89999** [comment]
IIRC files are only sent over Jingle when OTR is enabled.

**Comment by stephendaniel** [comment]
I am sorry, but can you please elaborate your answer in more detail? I still not get what you mean :(

**Comment by mimi89999** [comment]
How does it fail?

**Comment by stephendaniel** [comment]
on my Conversation app, the status of image attachment in chat window is always waiting. It won't send the image attachment to Zom Android app.

**Comment by mimi89999** [comment]
1. If you send the image to another Conversations user, if you long press on the image, can you see "copy link" as an option?

2. Are you using OTR with the Zom contact?

**Comment by stephendaniel** [comment]
1. I don't see any "copy link" option
2. I use OTR with the zom contact

![whatsapp image 2017-03-27 at 3 19 13 pm](https://cloud.githubusercontent.com/assets/10130399/24346989/f8070112-1300-11e7-94e8-d8e21edebe46.jpeg)

**Comment by iNPUTmice** [comment]
File transfer to Zom doesn't work. Apperently they are working on HTTP-Upload and OMEMO support to be compatible with Conversations. Until then I recommend you stick with Conversations.
