### ISSUE TITLE
How to properly keep the connection on?

### ISSUE THREAD

**Issue by anthologist** [siacs/Conversations#2412]
Android 7.1.1, Conversations 1.17.1 .
I already disabled battery optimizations for Conversations, but when I turn on the screen after some time I see the Wifi symbol appears after a second to reconnect. If I quickly open Conversations I see my account is reconnecting.
Do I need to enable ALSO the "keep on foreground option" in expert settings? I don't really understand when that option should be used. Thanks.

**Comment by monojp** [comment]
If I'm not mistaken your Wi-Fi problem should be fixed by setting Wi-Fi - Settings - Keep Wi-Fi on during sleep to "Always". As long as you have enough memory you should not need the "keep on foreground option". But you could try it out and use that also if your system is closing the process.

**Comment by anthologist** [comment]
I missed that WiFi option, thanks! I hope the problem was only that one.
