### ISSUE TITLE
Wrong avatars getting displayed after restore from backup

### ISSUE THREAD

**Issue by ghost** [siacs/Conversations#2413]
#### General information

* **Version:** 1.17.1
* **Device:** Google Pixel (Stock Android 7.1.1) and Nexus 6P (LineageOS 14.1)
* **Server name:** self hosted
* **Server software:** ejabberd 16.09
* **Installed server modules:** PEP, Blocking, Stream Managment, Roster Versioning, CSI, HTTP File Upload
* **Conversations source:** PlayStore & F-Droid

#### Steps to reproduce

1. Make a backup of Conversations with Oandbackup or Helium Backup
2. Factory reset your smartphone
3. Reinstall Conversations and restore data from backup

#### Expected result

Conversations works fine after restore, but displays the wrong avatars for some contacts. I get the avatar of contact a displayed on contact a and b. Contact b has a correct avatar on the server, and before the restore, Conversations displayed the correct avatars for both contacts.

**Comment by bochi** [comment]
Same happens to me, but "suddenly" - never restored from backup.

## **Genreal Information** 
**Version** 1.18.5
**Device** Samsung Galaxy S7 with LineageOS 14.1 (Android 7.1.2)
**Server name** self hosted 
**Server software** ejabberd 16.09
**Installed server modules** PEP, Blocking, Stream Managment, Roster Versioning, CSI, HTTP File Upload
**Conversations source** F-Droid

Gajim as well as Jappix are showing the correct avatars.

**Comment by licaon-kter** [comment]
@bochi Last version in F-Droid is 1.19.5, do update first!

**Comment by bochi** [comment]
@licaon-kter updated to the latest version, still happens

**Comment by bochi** [comment]
Any news on this one? Still happens on 2.2.5+fcr.

**Comment by iNPUTmice** [comment]
@bochi Are you still on ejabberd 16.09? I don’t think this is a Conversations issue.

**Comment by iNPUTmice** [comment]
No reaction from op. There was a caching bug in some version of ejabberd that could potentially cause this. This is a more realistic explanation of the described problem.
