### ISSUE TITLE
Magnify graphical symbols (Emoticons and others) or provide an option to upscale the chat font

### ISSUE THREAD

**Issue by av2k** [siacs/Conversations#2417]
#### General information

* **Version:** all versions
* **Device:** all devices except those with a huge display and magnification 
* **Android Version:** all versions
* **Server name:** all servers (doesn't matter)
* **Server software:** all servers (doesn't matter)
* **Installed server modules:** doesn't matter
* **Conversations source:** F-Droid

#### Steps to reproduce

1. compose a message
2. the fonts are rendered very small, especially emoticons and non-latin fonts

#### Expected result

Emoticons are upscaled and identifyable from a normal eye distance.
The chat text is easily readable from an arm's length distance.

I like Conversations very much and appreciate the very good software.
It would be even better if the fonts are larger by default and/or there
was an option to use larger fonts.

The home page of Conversations shows an example Conversations screenshot:
https://conversations.im/images/screenshot_encryption_selection.jpg

Although I do not suffer from bad view, I can hardly read the text.

Additionally, it would be useful if Emojis would be displayed much larger by default
or if there was an option to enable this function. Many of the standard emojis look
somehow similar and it's hard to keep them apart when they are displayed very small.

#### Debug output

none

**Comment by licaon-kter** [comment]
The `Use bigger font` setting helps? If not, better make fonts larger from Android system Settings .

**Comment by av2k** [comment]
I already use the "Use bigger fonts" option, but it's not enough. A scaling option, either a font size slider or a factor wheel or something similar, would be much better.

The Emojis are still much too small, it is barely possible to keep e.g. the different yellow Smiley emojis apart. Emojis should be 1.5x to 2x the selected font size, unless the font size is already above a certain (huge) font size.

**Comment by iNPUTmice** [comment]
Usually the system provides a font scaling option. The font size in Conversations should be comparable with the font size in Gmail for example or the SMS app. Is that not the case for you? Or can you not read those as well?

**Comment by av2k** [comment]
It is comparable to the SMS size, but for a chat it is too small IMO.

I think a mixture between the screen-estate utilization of Telegram (Avatar only once at the top menu bar; full-width chat paragraphs; timestamp at the end of the chat paragraph) and Emoji display of Skype (much larger Emojis if only a single Emoji was sent, and greater text size overall) would make the chats more readable and clearly arranged.

**Comment by SamWhited** [comment]
FWIW, this is the only thing a few of my friends complained about when I asked them what they didn't like about Conversations; their first response was "it doesn't follow Google design guidelines", and when I drilled them on what that meant it boiled down to "the font is tiny, and only normal sized if I select the 'big' font option, and even then it's too small". I do not know if their phones provide a scaling option or not.

**Comment by tmolitor-stud-tu** [comment]
I can read normal text just fine, thus the font is large enough for me,
BUT: the emojis are way too small to be readable.

It would be VERY nice if conversations was able to upscale emojis! (other apps do this, too)

**Comment by hermann-san** [comment]
the new version ov Conversations 1.20 has made emojis bigger when only an emoji is send. That is nice!
On small smartphones however (like S4 mini)  the emojis are still way too small  when posting together with other text. I know that there is an option to increase the font size in Conversations and that would also make emojis bigger, but on S4 mini it's still too small. It would be great if there was an option to make font size (thus emojis) even bigger.

**Comment by iNPUTmice** [comment]
Conversations 2.1.0 has options to choose 3 different font settings and will make emojis larger.
