### ISSUE TITLE
XEP-0363: HTTP File Upload consistency 

### ISSUE THREAD

**Issue by pommm** [siacs/Conversations#2418]
Hi,

We've been unable to use the "XEP-0363: HTTP File Upload" support on
Conversation since we first tried it a month or two ago. At first we
thought it might be a server setup issue (Prosody-0.10), but we've
confirmed that it is a bug in Conversations. Here is a description:

- Server info on Conversations client says "XEP-0363: HTTP File
  Upload  available"

- Sending from Conversations to gajim on desktop, image appears as
  expected

- Sending from Conversations to Conversations shows image as expected
  on sender's side (with green check mark suggesting receiver has
  received the image), but receiver gets a button that says "CHECK
  IMAGE SIZE ON <server hostname>".
  - Clicking this button says "Dowload failed: File not found"

But...

  - Long clicking this button gives a pop-up menu. When I select "Copy
    original URL" and paste the URL into a web browser (on the same
    device), image shows in browser correctly

Note that all of the above was tested with various settings in
Conversations, including "Automatically accept files smaller than
10MiB" and both "Always" and "Automatic" for "Compress and resize
pictures".

The above suggests to me that Conversations sender is sending the images
properly, Prosody is handling upload and download properly,
Conversations receiver is receiving the correct URL, but is for some
reason unable to display the image.

Has anyone else experienced similar behavior?

#### General information
Conversations
* **Version:** 1.17.1
* **Device:** Sony Xperia Z5
* **Android Version:** Android 6.0 Stock 
* **Server name:** self hosted 
* **Server software:** Prosody 0.10
* **Installed server modules:**  Stream Managment, CSI, MAM,roster,mam,mam_archive,bosh,http,http_files,http_upload,proxy65
* **Conversations source:** PlayStore

**Comment by olerem** [comment]
I had problems with pictures only behind a company firewall. After some firewall reconfiguration works just fine.

**Comment by gjedeer** [comment]
I've had this problem on my parents' phone with Conversations 17 and Android 6. No corporate firewalls. Works as a charm on other phones using the same server.

**Comment by pommm** [comment]
We've seen this problem on all 4 android devices we tried it on using the same server. And it doesn't appear to be a firewall (or other server) issue since when we "copy URL" from Conversations and paste into a browser on the same device, the images loads and displays fine.

So the question is: what is Conversions doing the would cause it to say "file not found" when the browser (Chrome) loads the exact same URL without any problem?

Maybe an even better question is: which file is not found? Is Conversations looking in a local cache without ever downloading it?

Is there anything more we can do on our side to help debug this?

**Comment by olerem** [comment]
I would suggest to disable encryption and monitor the traffic with tcpdump or wireshar on gateway or access point. Combine this information logs provided by conversations and the server.

**Comment by licaon-kter** [comment]
What do you see in the logs?

Here on 1.18.0 it says:
```
D/conversations(): retrieve file size. interactive:true 

D/conversations(): io exception in http file size checker: null
```

Xperia 5.1.1 or 6.0.1

**Comment by ded5r** [comment]
We are having the same problem as the original @pommm post above, but our URL link in Conversations seems to be the issue. It begins with aesgcm:// instead of what we would guess it should be https:// ... We know the server is Prosody with the mod_http_upload plugin. (Maybe though this is an issue with the plugin? If so, can anyone tell us where to file the issue?) Thank you.

**Comment by licaon-kter** [comment]
Testing this further, on both ejabberd and prosody servers, the same result.

@ded5r Indeed the link is created like that since https://github.com/siacs/Conversations/commit/401329caaa5d3152ad59453ec6050a4810af0164 and going back to 1.17.1 (to https://) it works again.

**Comment by ded5r** [comment]
Thanks @licaon-kter for the insight! We downgraded to the 1.17.1 release and can confirm it all works now as it should, with https:// links. No more "Check Image Size.." nor "Download failed: File not found". So we will keep with 1.17.1 for now.

**Comment by licaon-kter** [comment]
Hence, this might not be the same issue that @pommm sees, as s/he had 1.17.1 already.

**Comment by ded5r** [comment]
That's true. So here are some other potential differences in case it helps...

Android Version: Cyanogenmod 11 (Android 4.4.4)
Server Software: Prosody 0.9.12 (server runs solely on Tor / can only connect to it through Tor)
Modules: PEP, Stream Management, Roster Versioning, HTTP File Upload
Source: F-Droid

And 1.17.1 (https:// links) work but 1.18.0 (aesgcm:// links) did not.

**Comment by iNPUTmice** [comment]
I feel like all three of you have different issues. It is impossible to keep track of them in on thread. Please use our MUC instead; This is an issue tracker and not a general support forum.

A few general pointers:
1) Your server must respond to HEAD requests
2) Starting with 1.18.0 the HTTP url must either include a key (be encrypted) OR be repeated in the oob tag. (Conversation is doing that for ages but your third party scripts might not)
3) You must have mutual presence subscription with the sender. Otherwise it will only show up as download button and not download automatically.

**Comment by licaon-kter** [comment]
Points 1&3 are #2325 - see my log there

2 not sure what that means exactly, servers need to be updated or what? Right now, files sent with Conversations 1.18.0 that end up as aesgcm:// can't be opened by Conversations 1.18.0.

**Comment by olerem** [comment]
@licaon-kter , not true. Works just fine for me. I use Google Nexus 5 -> Conversations 1.18.0 -> jabber.de -> Conversations 1.18.0 -> Google Pixel

**Comment by licaon-kter** [comment]
@olorom Which part is not true for you?

**Comment by olerem** [comment]
@licaon-kter, "Right now, files sent with Conversations 1.18.0 that end up as aesgcm:// can't be opened by Conversations 1.18.0." - This for by me, just fine. Gajim can't open it right now, but conversation can do it.

**Comment by licaon-kter** [comment]
I'm glad for you, not sure what was the point for your post though. ;)

@iNPUTmice Point 4 is on by default afaics, Polipo 8118

**Comment by olerem** [comment]
@licaon-kter , the point of the post to show that it is not "not working at all" case. Usually it helps to troubleshoot by identifying what is the difference in working case and not working scenario.

**Comment by lovetox** [comment]
@olerem Gajim can open these files, you have to add in the Advanced Config Editor under `uri_scheme` - `aesgcm://`

then Gajim recognizes it.

**Comment by olerem** [comment]
@lovetox , thx, good tip. Will it be available in some gajim version by default? I use gajim-nightly 20170411-1 right now.

**Comment by lovetox** [comment]
i just pushed a new omemo-plugin version, it also adds this scheme to the config.

**Comment by olerem** [comment]
@lovetox , wow. this was fast. just got notification about update :D

**Comment by pommm** [comment]
It appears there was a lot of traffic on this thread over the past few days. But most of it doesn't seem to look like the issue we are having. We've tested further and found that "ChatSecure" has no problems receiving the messages sent by Conversations. A tcpdump of the send shows that Conversations successfully does a HEAD request with the correct URL and receives the image. For some reason I can't understand, it does another HEAD request on the same URL and receives it again. Requesting the exact URL in the HEAD request from a browser (Chromium) shows the image that was sent, suggesting that the sending and serving are working fine and that the URL Conversations is trying to download is the correct URL. But Conversations app says "Download failed: file not found" which is strange since the tcpdump shows that the file was found and the correct amount of data was sent (with "JFIF" in the header).

So the only issue we are having is that Conversations appears to be receiving the file but unable to view it. Other clients receive and are able to view. 

To be clear, in our case the URL is correct and works well, so this isn't the aesgcm issue mentioned above.

@iNPUTmice, can you explain your #2 on the post 3 days ago? For #1, we've confirmed with tcpdump that the HEAD request is working. For #3 we have mutual presence requests and the tcpdump shows that the download is happening automatically, even though it doesn't show in the app. For #4, we are not using Tor.

But I'm not sure if #2 relates to us.

Any help would be appreciated.

**Comment by froghorn82** [comment]
Found this thread have exactly same problem with version 2.3.0. Downgraded to 2.2.9-beta and problem is fixed - Tested with the exact same server and connection. This has nothing to do with mutual presence or server not responding to HEAD requests etc.

**Comment by licaon-kter** [comment]
@froghorn82 More info? Server?

**Comment by froghorn82** [comment]
@licaon-kter all servers i tested, including conversations.im. The latest 2.3.1 version also works fine. The problem was with version 2.3.0 only from my testing.

**Comment by Aersaud** [comment]
I know there has been no posts on this since last year, however I host an ejabberd server and we are using this app and I notice the same thing. Uploads and download works fine but there is always a button that you must click to Check The Image Size. Once you click that it displays the image as expected.  Settings on both Pixel 2 XL's are set to Accept Files automatically up to 10MiB, Image Compression Auto on both, and Video Quality Medium. Conversations 2.5.3 on both. We are using omemo and the links start with aesgcm when copying the URL.

Any known fix/work around?

**Comment by licaon-kter** [comment]
@Aersaud The server does not decide who you talk to and who is on your contacts list. Yes, people in your contact list are deemed more trustworthy so you get the benefit of file autodownload. People not in...not so much, hence the app doesn't start downloading random $hit any spammer might send your way.
