### ISSUE TITLE
Open contact details by tapping the header bar

### ISSUE THREAD

**Issue by tdemin** [siacs/Conversations#2421]
Most of other popular messaging apps (i.e. WhatsApp, Telegram, Signal) open contact details by tapping the header bar with the contact's name in it. In Conversations, you have to extra tap by opening the menu.
This seems to be confusing. Can we change this behaviour?

**Comment by licaon-kter** [comment]
It's not confusing, but I like your idea too.

**Comment by iNPUTmice** [comment]
You can touch the other persons avatar to open the contact details.
