### ISSUE TITLE
Starting a conversation and doing nothing leaves an unused tab

### ISSUE THREAD

**Issue by tdemin** [siacs/Conversations#2422]
So, we open a conversation and do nothing but switch to another tab. This leaves a tab with contact's name on it. This tab doesn't do anything but annoys you any time you look at it when swiping left. Is this just as planned?

**Comment by licaon-kter** [comment]
Menu->Close conversation ?

**Comment by tdemin** [comment]
@licaon-kter this is an odd extra move — the user probably opened the conversation by mistake and it should not require any extra steps to close such a conversation.

**Comment by licaon-kter** [comment]
So we'll next have issues with "empty conversation keeps on disappearing" ?

**Comment by tdemin** [comment]
@licaon-kter why would someone want to keep an empty conversation (s)he can always reopen?

**Comment by licaon-kter** [comment]
Maybe they want to talk later, say when they see the contact is online. Disappearing elements without user interaction (rhyme or reason) are bad UX.

**Comment by uchchishta** [comment]
>why would someone want to keep an empty conversation (s)he can always reopen?

Reopen as in, go back to contact list>search contact>click (3 extra steps) just because you wanted to see something in another chat? No thanks.
Don't start unwanted conversation
Just swipe the unwanted chat away if you did.

**Comment by tdemin** [comment]
@licaon-kter this seems more like an odd appearing element that will confuse the user.

@uchchishta opening unwanted chats is more common and much less annoying than closing them.

**Comment by d9h02f** [comment]
@tdemin: you close a chat by swiping it to the right.

**Comment by tdemin** [comment]
@d9h02f I know, I just don't want to.

**Comment by uchchishta** [comment]
@tdemin I find chats closing even after I opened them more annoying.

**Comment by licaon-kter** [comment]
What other chat app decides to close empty chats?

**Comment by tdemin** [comment]
@licaon-kter at least WhatsApp and Telegram do, didn't test Signal, but I'm pretty sure it does.

**Comment by iNPUTmice** [comment]
I agree with what @licaon-kter said.
