### ISSUE TITLE
MUC name changes on bad internet connection

### ISSUE THREAD

**Issue by conrad-heimbold** [siacs/Conversations#2425]
#### General information

**Version:** 1.17.1
**Device:** Motorola Moto G falcon
**Android Version:** Android 6.0.1 Cyanogenmod
**Server name:** stud.uni-hannover.de
**Server software:** prosody
**Installed server modules:** 
XEP0163: yes
XEP0191: no
XEP0198: yes
XEP0237: yes
XEP0280: yes
XEP0313: no
XEP0352: no
XEP0363: no

**Conversations source:** F-Droid

#### Steps to reproduce

1. Create a new MUC with a random (computer-generated) name. 
2. Set the display name for this MUC to something which you can remember better. 
3. Get a bad / flaky internet connection, e.g. on mobile internet.  

#### Expected result

What is the expected output? 

Once Conversations has received the human-readable group name, it should cache/keep it as long as it doesn't get notified of a changed one. 

What do you see instead?

The name for the group (MUC) in the top bar sometimes shows the human-readable group name (if the internet connection is good), but unfortunately also the random, machine group name (if the internet connection is bad / not existant).

### Debug output
Unfortunately, I could not get any useful adb debug logcat.

**Comment by pworldx** [comment]
Any solution to this.I am also facing same problem

**Comment by licaon-kter** [comment]
Same server? Same server software? What Conversations version?

**Comment by conrad-heimbold** [comment]
I couldn't reproduce it so far though, because I use WiFi mostly. 

Do you have any tip? 

Could I maybe limit bandwidth of my WiFi artificially or set up random connection losses (runs on linux - wifi hotspot on ubuntu/fedora laptop or wifi on openwrt router), in order to simulate mobile internet conditions?

**Comment by pworldx** [comment]
I am using conversation version 1.18

**Comment by philipflohr** [comment]
@conrad-heimbold I observed a similar behaviour after updateing Conversations.
But there not the muc url but the topic which was set on the first connection (at least I think so - maybe it's just an old one) to the muc is shown.
The names are updated after some seconds

**Comment by licaon-kter** [comment]
#2882 explains this better


/Close this
