### ISSUE TITLE
Feature request: add contact status on converations page

### ISSUE THREAD

**Issue by borrodion** [siacs/Conversations#2426]
Please add contact status labels on the conversations page and even within the conversations, because often it is unclear whether the contact is online or not. I can only see statuses if I tap "Start conversation", which shows the list of all contacts with statuses. Alternatively, can you add a separate button/tab on top of the screen to go to contacts directly to see who's online? Version: 1.17.1

**Comment by uchchishta** [comment]
Btw you can see status inside the conversations if you turn on "send button indicates status" in  settings

**Comment by borrodion** [comment]
Okay, thanks, but it would be more logical and user-friendly to see the tag 'online' below the contact name, anyway.

**Comment by KingKili** [comment]
The PR https://github.com/siacs/Conversations/pull/2370 fixes the problem even better.
