### ISSUE TITLE
Feature request: configurable number of pings to the server per hour to reduce battery drain

### ISSUE THREAD

**Issue by borrodion** [siacs/Conversations#2427]
Hi, I am not a heavy user, but Conversation appears to be a heavy battery user. :) BetterBatteryStats show that it wakes the device up pretty often to ping the server and is battery drainer No. 1 among my apps (also in Settings/Battery). Can you add a setting to specify the number of such pings per hour so that it's controllable? I mean when when nobody's chatting, and the app is idling. For me, I guess it would be optimal to send keep-alive packets, say, once in 5 minutes. When there is an ongoing chat, the picture is different, it's clear.

Just a question: would battery consumption change if I install GCM (as I have none)?

My setup: 1.17.1, CyanogenMod 13, no GCM. The app is not in the list of energy saving exceptions, but it does not complain and works fine (except the battery consumption comparable to screen).

**Comment by iNPUTmice** [comment]
The issue template exists for a reason. If you complain about battery consumption it is very important that we know what server you are using or how it is configured.

> . Can you add a setting to specify the number of such pings per hour so that it's controllable? 

That’s a violation of our design principals  

> For me, I guess it would be optimal to send keep-alive packets, say, once in 5 minutes.

The ping interval is set to 300s
