### ISSUE TITLE
The number of unread messages doesn't have a limit

### ISSUE THREAD

**Issue by participante0** [siacs/Conversations#2428]
#### General information

* **Version:** 1.17.1
* **Device:** Google Nexus 5X
* **Android Version:** Android 7.1.1 Stock
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Wait enough time in order to receive a lot of messages in a conversation (especially a muc).

#### Expected result

The number increases more than 1000, but it doesn't fit in the circle.

![screenshot_20170325-093119 2](https://cloud.githubusercontent.com/assets/10296795/24706225/403a562c-1a0f-11e7-8f63-d1778e16c00b.png)

I expect to read all the information.
Suggestions for the limit: `1K`, `1 k`, `1K+`, `9 K`, `9k+`, `∞`.

**Comment by iNPUTmice** [comment]
fixed in f75eb6bc435b5f8ab07b1c4faf32c067d89a5a43
