### ISSUE TITLE
Feature request: lots of emojis but saddly missing the one worth having ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by alecbl** [siacs/Conversations#2429]
The title says at all. As a chat app, this emoji: ¯\_(ツ)_/¯ is basically essential for communication in the 21st century. Words alone cannot replace it and there is no known work around.

**Comment by SamWhited** [comment]
¯\\_(ツ)_/¯

**Comment by borrodion** [comment]
By the way, why not enable adding custom smiley packs? I, personally, like kolobok smileys very much. [http://www.en.kolobok.us/](url) Is it possible to add these animated emoji?

**Comment by iNPUTmice** [comment]
@alecbl I fully agree; however emojis are composed by your keyboard. Not by Conversations. You should file this feature request with your soft keyboard vendor.
