### ISSUE TITLE
Add Android Auto support

### ISSUE THREAD

**Issue by morgenroth** [siacs/Conversations#2434]
Since Google's Android Auto is available as standalone app a wide range of users might use it for handsfree communication. It would be really cool, if my favorite messenger (guess which one) would support Android Auto for play messages and replying to them.

According to the existing [documentation](https://developer.android.com/training/auto/messaging/index.html) it shouldn't be too hard to realize. I do not want to promise too much, but if I find some time this could be my first contribution to this project. But before I start, I wanted to know if this feature has a chance to get merged or not.

**Comment by iNPUTmice** [comment]
Yes pull requests regarding Android Auto are welcome.

**Comment by morgenroth** [comment]
Great. I started to work on that and have a possibly stupid question. ;-)

I need to implement a PendingIntent for a "mark as read" action and other kinds of those have been made unique by combining the uuid with a magical number like this...

> int id =  conversation.getUuid().hashCode() % (dismissAfterReply ? 402359 : 426583);

Now my question: How is the number chosen? Just random? Is there a pattern?
