### ISSUE TITLE
Conversations doesn't work over tun0 dev alone.

### ISSUE THREAD

**Issue by Sur3** [siacs/Conversations#2436]
#### General information

* **Version:** 1.17.1
* **Device:** Samsung Galaxy S3
* **Android Version:** Android 7.1.1 LineageOS 14.1
* **Server name:** jabber.otr.im
* **Conversations source:** F-Droid

#### Steps to reproduce

1. disable wifi and gsm internet connections.
2. connect via tun0 eg with SimpleRT over USB.
3. try to send or receive messages.

#### Expected result

Sending and Receiving Messages like eg Whatsapp does, but Conversations just says its waiting to send but no message goes in or out.

**Comment by mimi89999** [comment]
@Sur3 Did you forward also XMPP and DNS ports?

**Comment by Sur3** [comment]
Well SimpleRT creates a tun0 dev and forwards it via iptables, therefore everything should be forwarded:```

ifconfig tun0 10.1.1.1/24 up
iptables -I FORWARD -j ACCEPT
iptables -t nat -I POSTROUTING -s 10.1.1.0/24 -o eth0 -j MASQUERADE
```

DNS works, XMPP-Ports should work too, didn't test them though yet.

**Comment by Sur3** [comment]
Just testet with Xabber it works, so i think it's not the ports.

**Comment by Sur3** [comment]
SimpleRT states: "Some apps do not recognize the reverse tethered internet connection due to ConnectivityManager policy."
Probably that information helps to resolve the issue.

**Comment by iNPUTmice** [comment]
> SimpleRT states: "Some apps do not recognize the reverse tethered internet connection due to ConnectivityManager policy."

@Sur3 if you read a bit further along the SimpleRT readme provides you with a solution.

> Just leave WiFi or 3g connection active, connection will go through SimpleRT anyway.

**Comment by Sur3** [comment]
> Just leave WiFi or 3g connection active, connection will go through SimpleRT anyway.
That solution is merely a workaround and doesnt work for me as i do reverse tethering to get rid of the wifi connection, leaving it active would be counterproductive.
Fixing it inside Conversations is the right way to go, as with eg. Xabber it works, therefore it's really an implementation issue i think.

**Comment by iNPUTmice** [comment]
If you want you can patch Conversations and make [`hasInternetConnection()`](https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/services/XmppConnectionService.java#L967) always return true.

**Comment by Sur3** [comment]
That would probably be a workaround but I think the method of Xabber or Whatsapp is probably more sophisticated than that?! Or how would this solution react if using Conversations without internet connection, i mean there's probably a reason for that query?!?

**Comment by mimi89999** [comment]
Server unreachable means:

1. No internet access
2. Internet access, but server is down

That's the reason for checking this...

**Comment by Sur3** [comment]
I had a look into the source-code of Xabber and it uses:
```
ConnectivityManager cm = (ConnectivityManager) Application.getInstance()
                .getSystemService(Context.CONNECTIVITY_SERVICE);
```
instead of Conversations:
```
ConnectivityManager cm = (ConnectivityManager) getApplicationContext()
.getSystemService(Context.CONNECTIVITY_SERVICE);
```
Probably that little change getting the cm with this other function is enough to make it work.
Can someone compile an experimental apk with this change for me to test if that works to solve the problem?

**Comment by Sur3** [comment]
I had a deeper look into the issue and upstream ( https://issuetracker.google.com/issues/37109422 ) reports the issue "wont be fixed" and suggests a downstream solution.. ( https://github.com/vvviperrr/SimpleRT/issues/3#issuecomment-294283202 ) i hope that solution will work therefore i'll close this bug.
