### ISSUE TITLE
XEP-* are enabled in server, but Conversations didn't detect it.

### ISSUE THREAD

**Issue by yoursoftwarebug** [siacs/Conversations#2438]
guest9943: Hello, I'm using prosody and Conversations(android). When I enable PEP in prosody config and restart it, conversations said "XEP0163: PEP unavailable".
guest9943: https://prosody.im/pastebin/9c7708fb-4367-4af9-9bac-b4496b530435
guest9943: modules_enabled = {"roster";..."pep";...};
guest9943: Any idea why? I already tried reconnect/restart both server/client.
marcos has left (Disconnected: Replaced by new connection)
marcos has joined
guest9943: I also have "csi" in enabled{} but Conversations said "unavailable".
psYchotic has left (Kicked: recipient unavailable)
psYchotic has joined
guest9943: But when I tried DuckDuckgo xmpp service, it shows them "available", so I think this is a prosody issue.
waqas has joined
uc has left (Replaced by new connection)
uc has joined

Latest Conversations.

**Comment by yoursoftwarebug** [comment]
Conversations think "pep" and "csi" are disabled, but they are already enabled in server side.

**Comment by mimi89999** [comment]
@yoursoftwarebug Could you give exact Prosody and Conversations versions?

**Comment by mimi89999** [comment]
@yoursoftwarebug Also, you left Prosody MUC before anybody could reply.
