### ISSUE TITLE
Not able to login on openfire server version 4.0.3 if install in window pc 

### ISSUE THREAD

**Issue by NarendraSickarwar** [siacs/Conversations#2439]
#### General information

* **Version:** 1.12.2
* **Device:** Google Nexus 5
* **Android Version:** Android 6.0 Stock 
* **Server name:**self hosted 
* **Server software:**open fire 4.0.3 install in window pc
* **Installed server modules:
* **Conversations source:** github code

#### Steps to reproduce

1. … just install openfire server and install 4.0.3 server on window pc

#### Expected result

should be login with both port 5222 and 5223 in android

**Comment by mimi89999** [comment]
@NarendraSickarwar 
> Version: 1.12.2

Get the latest version, please.

**Comment by mimi89999** [comment]
Duplicate of #2430 or #2249?

**Comment by NarendraSickarwar** [comment]
I am also try with latest version 4.1.3 but also i am getting same issue but if server install in linux pc then if i want to connect with 5222 port then its working fine on same 4.0.3 version server.

**Comment by mimi89999** [comment]
@NarendraSickarwar 
> if server install in linux

That would be a server issue. Please report it to Openfire then.

**Comment by NarendraSickarwar** [comment]
@mimi89999 
but if am try with smack-android lib then i am able to login on all type server of xmpp.

**Comment by mimi89999** [comment]
@NarendraSickarwar Maybe bad TLS config?

**Comment by NarendraSickarwar** [comment]
@mimi89999 i am faceing this error on latest version server. 


xml parser mishandled SSLProtocolException(Read error: ssl=0xb7b23eb8: Failure in SSL library, usually a protocol error
01-21 21:11:59.089 D/conversations( 6185): error:0c0890ba:ASN.1 encoding routines:asn1_check_tlen:WRONG_TAG (external/boringssl/src/crypto/asn1/tasn_dec.c:1313 0xaa0db50f:0x00000000)
01-21 21:11:59.089 D/conversations( 6185): error:0c09309d:ASN.1 encoding routines:asn1_template_ex_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:572 0xb7abf368:0x00000001)
01-21 21:11:59.089 D/conversations( 6185): error:0c09409d:ASN.1 encoding routines:asn1_template_noexp_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:735 0xaa0db50f:0x00000000)
01-21 21:11:59.089 D/conversations( 6185): error:0c07909d:ASN.1 encoding routines:ASN1_item_ex_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:343 0xb76f4810:0x00000001)
01-21 21:11:59.089 D/conversations( 6185): error:0c09409d:ASN.1 encoding routines:asn1_template_noexp_d2i:NESTED_ASN1_ERROR (external/boringssl/src/crypto/asn1/tasn_dec.c:711 0xaa0db50f:0x00000000))

**Comment by NarendraSickarwar** [comment]
@mimi89999 Maybe bad TLS config?

how can i check ???

**Comment by mimi89999** [comment]
@NarendraSickarwar 
> how can i check ???

https://tls.imirhil.fr/
Choose XMPP from the menu.

**Comment by NarendraSickarwar** [comment]
@mimi89999 but open fire self signed TLS support already

**Comment by NarendraSickarwar** [comment]
@mimi89999 right now i am using ip address not domain for testing.

**Comment by mimi89999** [comment]
LAN IP address... I see...

**Comment by NarendraSickarwar** [comment]
@mimi89999 how can we solve this???

**Comment by mimi89999** [comment]
@NarendraSickarwar On port 5223, you can test with:
`nmap --script ssl-enum-ciphers -p 5223 server_ip`
or
`openssl s_client -connect server_ip:5223`
and on port 5222 with
`openssl s_client -connect server_ip:5222`

You need to do that from a Linux computer.

If the protocol will be lower than TLSv1.0, than you need to enable them in Openfire...

**Comment by mimi89999** [comment]
@NarendraSickarwar Also, not connecting to servers with weak ciphers or protocols is a Conversations feature.

**Comment by NarendraSickarwar** [comment]
@mimi89999 i am using window 2012 so how can i solve on this.

**Comment by vanitasvitae** [comment]
@NarendraSickarwar please join open_chat@conference.igniterealtime.org and ask there for server support.

**Comment by NarendraSickarwar** [comment]
@mimi89999 on my local pc window is 2008 and its is working fine so i think this is not a openfire issue. on both port 5222 and 5223.

**Comment by vanitasvitae** [comment]
@NarendraSickarwar if it works fine on your local machine than its probably not a conversations issue...

**Comment by NarendraSickarwar** [comment]
but its not working on window server 2012 on different two machine and in my local i am using window not server

**Comment by strb** [comment]
This is an issue tracker, not a chatroom for debugging server setups.
