### ISSUE TITLE
Feature request(s): App pin, disable screenshots & custom auto delete times.

### ISSUE THREAD

**Issue by davepb16** [siacs/Conversations#2443]
First off I apologise if these have been requested before.  I had a quick search but couldn't find anything. 

I really enjoy using this app and it would be nice to see the following added:

Custom auto delete time - So we could change it to less than 1 hour. And maybe the option to set different auto delete times on different conversations. 

App pin: Kind of explains itself. The ability to set a pin to enter the app would be good. 

Disable screenshots: An option to disable the ability to take screenshots of the open conversations app.  I've seen this feature in many other Android apps.

Thanks for all the work the devs do for us users.

**Comment by licaon-kter** [comment]
#1002
#1995
#2364

/Close this
