### ISSUE TITLE
When Connecting via Tor/Orbot Cannot Download aesgcm://  File Links

### ISSUE THREAD

**Issue by ded5r** [siacs/Conversations#2444]
#### General information

* **Version:** 1.18.0
* **Android Version:** 4.4.4
* **Server name:** jabber.de
* **Server software:** ???
* **Installed server modules:** Everything in "Server Info" section of Conversations is available
* **Conversations source:** F-Droid

#### Additional Information

Both contacts have accounts on same server. Both contacts have "Send presence updates" and "Receive presence updates" checked. Both contacts have automatically accept files set to 10 MiB. Both contacts are using OMEMO in Conversations. Both contacts are connecting through Tor/Orbot to the server.

#### Problem

For both contacts, when sending an image, the file is uploaded to server. Person receiving the file gets a button that states: "Check image size on jabber.de". Clicking this button creates a pop-up: "Download failed: File not found". If we long-press the button and copy original URL, it gives: "aesgcm://jabber.de:5281/upload/bunch-of-randomness/bunch-of-randomness.png#bunch-of-randomness. (All settings of Compress Pictures are then tried.) We have no way of receiving or downloading file.

#### What Worked

We downgraded to version 1.17.1 (with https:// links for files) and that works, none of the issues described above!

To experiment, we upgraded back to version 1.18.0 (with aesgcm:// links), but this time we connect without checking the Connect via Tor box. (All other settings remain exactly the same.) Without the Tor box checked, on version 1.18.0, everything works!

#### Conclusion

Therefore, there seems to be an issue with Tor/Orbot's ability to handle aesgcm:// links.

**Comment by licaon-kter** [comment]
Not sure those are handled by Orbot directly. Why would they be anyway?

@iNPUTmice mentioned port 8118 but that's the default Polipo http proxy port as expected, also that code in this app was not touched in 6 months.

**Comment by iNPUTmice** [comment]
Thanks for the report; Working on a fix right now.
