### ISSUE TITLE
api

### ISSUE THREAD

**Issue by montotone** [siacs/Conversations#2447]
i think ,may you consider to offer  api

**Comment by licaon-kter** [comment]
Do detail...

**Comment by montotone** [comment]
offer some documents ,the project is really complex

**Comment by licaon-kter** [comment]
What for exactly, what do you want to do? Remember that they offer to help you too: https://conversations.im/#support

**Comment by mimi89999** [comment]
There is no special API. Conversations is an XMPP client. XEPs are documented.
