### ISSUE TITLE
Make it obvious when sending a PM in groups

### ISSUE THREAD

**Issue by uchchishta** [siacs/Conversations#2449]
**Version** 1.18.0

PMing in the MUCs won't show any indication of if you're PMing. If you get distracted (after half typing) or keep changing b/w group post and PMs, you'll inevitably post to the wrong recipient(s); the text ```send a (private) message to user``` goes away if you type something.

If there was something like a border highlight to the input field when PMing, it will help.

**Comment by licaon-kter** [comment]
The send icon did not change from a triangle to a circle with an X inside (that you press to exit private mode) ?

**Comment by uchchishta** [comment]
Nope,it doesn't work like that, it also changes back into send icon if I start typing. You  can't distinguish between normal and  PM afterwards.

**Comment by licaon-kter** [comment]
So you see the text and the changed button but you ignore them and complain here that you need yet ANOTHER way to distinguish it? What if you ignore that too?

**Comment by uchchishta** [comment]
If said : if you **get distracted**( after half typing) you can't make a difference. Why don't you understand the issue first.

**Comment by contrapunctus-1** [comment]
I strongly agree with @uchchishta - I've seen way too many users new to whispers - and even experienced ones - get confused as to whether they're whispering or not. I too mix them up, sometimes, if I pause/do something else after writing, but not sending, a message.

PS - Whispers are also somewhat well-hidden and undocumented (to the user). Perhaps we can let them know about them, the first time they either -
1. receive a whisper, or
2. long-press an avatar in an MUC (probably by accident)

**Comment by d9h02f** [comment]
The question is maybe whether whispers are really necessary in the first place.

**Comment by licaon-kter** [comment]
They are, not all the chatter needs to be public, from both a privacy stand and a courtesy one.

**Comment by d9h02f** [comment]
Okay, but if you're going to be talking privately with someone, why would they not be in your contacts?

**Comment by thomashermes** [comment]
couldnt agree more

**Comment by uchchishta** [comment]
Whispers are more contextual.

Search through  roster, message, wait for them to switch chat != A single Long click.

**Comment by d9h02f** [comment]
Your example works in the opposite direction as well: if someone gets a whisper in a busy group chat, they first have to find it in the sea of messages, whereas they can immediately see any private message pop up. I strongly doubt it takes more than a split second extra to send a message in a private chat than sending a whisper in a group chat.

**Comment by uchchishta** [comment]
I guess if ` the sender can see the room is busy`   then `sender should know whisper will probably not be seen` # like a _whisper_ in a loud hall
Whisper has its uses, but is not a replacement for main 1on1 chat (vice versa) IMHO
----
On a second reading,
> if someone gets a whisper in a busy group chat, they first have to find it in the sea of message

You can also say this for when someone mentions you. So it should be removed too?

**Comment by LeSpocky** [comment]
> Okay, but if you're going to be talking privately with someone, why would they not be in your contacts?

On an open MUC (for example some free software projects use that for chat as alternative to IRC) you don't necessarily see the JID of the other chat room participants, but you may want to talk to someone in private (just like /query on IRC) although you don't have him or her in your roster. I would call that a reasonable use case.

**Comment by Yky** [comment]
> 
> 
> Okay, but if you're going to be talking privately with someone, why would they not be in your contacts?

There is also no simple way of creating a new chat with a user from a MUC, such as long-press on the name in the MUC or even by scrolling through the list of group members.

**Comment by licaon-kter** [comment]
You now have to choose to start whispering, it's not only long press. Maybe this can be closed?

**Comment by iNPUTmice** [comment]
fixed in 8a1a9f4f5547a37a3f47659d3f2448bfdaf4b018
