### ISSUE TITLE
Lock screen support

### ISSUE THREAD

**Issue by luke-jr** [siacs/Conversations#2454]
Would it be possible to allow Conversations to be used as the lock screen, so children need to ask permission to unlock their phone? (maybe an automatic request sent on swipe?)

And then the parent can answer over XMPP with a keyword or something...?

**Comment by mimi89999** [comment]
That would be a separate app that is a lockscreen, that sends requests over XMPP.

**Comment by luke-jr** [comment]
How would it share the XMPP connection with Conversations?

**Comment by mimi89999** [comment]
It would use a different account. So kid-lockscreen@example.com would send yes/no to parent@example.com and the parent would reply from Conversations.

But handling the lockscreen is a very specific functionality that Conversations won't have. It has to be in a separate app.

**Comment by iNPUTmice** [comment]
This is out of scope for Conversations. Conversations is an instant messenger and not a RPC/Tasker/whatever app. Maybe have a look at [Project MAXS](http://projectmaxs.org/homepage/).
