### ISSUE TITLE
Too much wakelocks of the phone, no sleep, drain battery

### ISSUE THREAD

**Issue by barsthebars** [siacs/Conversations#2459]
#### General information

* **Version:** 1.18.2
* **Device:** Highscreen Easy F Pro
* **Android Version:**  Android 5.1 Stock
* **Server name:** jabbim.com
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. General use of the phone, chatting by 10-20 times a day.

#### Expected result

What is the expected output? 
Sleep with the phone, no drain of the battery.

What do you see instead?
Total phone awake, no sleep, drastic drain of the battery, till power of on low percents - about 30-40% and suddenly power off because of total awake.
About 22 wakelocks awake by 19 minutes.
About 407 wakelocks awake by 11 hours.

![screenshot_2017-04-20-10-43-47](https://cloud.githubusercontent.com/assets/12436109/25333843/9f99db94-28f4-11e7-84f4-f04932527adf.png)

When Conversations was freezed - phone returned to its regular  state  - sleeped ok, no drain of the battery.

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
Please fill in the entire issue template. Especially the server extensions and the logcat output. Otherwise we can't help you.

**Comment by licaon-kter** [comment]
What do you use for battery stats? BetterBatteryStats or what? Provide some pics from that apps output

**Comment by barsthebars** [comment]
UPD.
Updated for a screenshot of the wakelocks. I'm using Wakelock Detector Full.
"Especially the server extensions and the logcat output."
Sorry, but for now I don't know what is "server extensions" and how to do "adb logcat". Sorry. 
Maybe a link on "how-to", if you please?...

**Comment by licaon-kter** [comment]
The awakes number does not matter that much, battery drain matters. How much did the app consume?

**Comment by barsthebars** [comment]
I think, that Conversations wakes up phone for approx. every 1.5 min. So phone do no go in deep sleep mode, and drains battery much. More than 10% (approx. 10-15-20% for an hour), like being always on\used . This makes battery live only 5-6 hours maximum to live, then suddenly power off, because of high power consumption for every second and no decreasing this power consumption automatically by no usig the phone by me. In simple - engine is running in max power continiously, every second, no matter - I'm using the phone, or it's laying down for hours non touched by me.

**Comment by barsthebars** [comment]
I've installed a CatLog app on the phone, and it's recording some log for now, I think... Maybe, I'll be able to see it, and to put it here...

**Comment by licaon-kter** [comment]
That would be kinda useless, I mean not post it all but only what happens when/why it wakes up.

Do get the app I've recommended and export stats after one 100%-5% battery cycle too.

**Comment by barsthebars** [comment]
UPD.#3

LogCat from approx. 3PM till 8PM. But CatLog app reported, that log is too big, can't save,  so attaching the one I have:
[2017-04-24-15-14-34.txt](https://github.com/siacs/Conversations/files/952671/2017-04-24-15-14-34.txt)
Sorry for big txt, but the site refused .zip - "not supported file". I don't know why....
And screenshots of power state.
![screenshot_2017-04-24-20-52-59](https://cloud.githubusercontent.com/assets/12436109/25351563/a168af58-2931-11e7-92b9-74fc77ca96b4.png)
![screenshot_2017-04-24-20-53-12](https://cloud.githubusercontent.com/assets/12436109/25351565/a16deb94-2931-11e7-9c1e-6231d597d3db.png)
![screenshot_2017-04-24-20-53-29](https://cloud.githubusercontent.com/assets/12436109/25351564/a169db26-2931-11e7-9d0e-9fd21fcc479a.png)

For real, not bad for today, the state of deep sleep was as normal for testing hours... I have no idea why... 
But, it seems to me, too many wakeups by the Conversations still are in the log.

**Comment by iNPUTmice** [comment]
@barsthebars 
1) The screenshots of the battery stats doesn't even show Conversations
2) the gmail and the odnoklassniki.ru server do not support Stream Management or any other modern XMPP extension that can aid Conversations to optimize battery life. Please use servers that comply to the [2016 Compliance Suite](https://gultsch.de/compliance_ranked.html)
3) The number of wake locks is completely irrelevant.
4) This is an issue tracker not a general support. Please use our conference (MUC) for general questions.
5) logcat looks mostly fine besides the observation I made in (2)

**Comment by barsthebars** [comment]
@iNPUTmice 
Thank you for advises and spending some time seeing my difficulties. 
And thanks for developing Conversations - it's the best for now. imho.
Best regards,
Bars
