### ISSUE TITLE
Can not use OMEMO with a certain contact via different accounts

### ISSUE THREAD

**Issue by menaceone** [siacs/Conversations#2460]
#### General information

* **Version: 1.15.5
* **Device: One Plus One
* **Android Version: Android 7.1 Lineage OS
* **Server name: Jabber.de, mailbox.org, jabber.ccc.de
* **Installed server modules: PEP, Stream Managment, CSI, MAM
* **Conversations source: PlayStore,

#### Steps to reproduce

1. Add account A (PEP enabled)
2. Add user a to account A
3. Start OMEMO conversation with user a
4. Add account B (PEP enabled) and deactivate account A 
5. Add user a to account B
6. Start Conversation with user a

#### Expected result

In the 2nd Conversation via Account B OMEMO should be available. 
But with additional accounts I can't use OMEMO with the same contact.
Is this behaviour intended?

Greetings

**Comment by mimi89999** [comment]
> Version: 1.15.5

@menaceone It won't work on 1.15.5

**Comment by iNPUTmice** [comment]
Please ask general questions in our conference (MUC). This is an issue tracker and not a support forum.
