### ISSUE TITLE
Conversations crashes on message send

### ISSUE THREAD

**Issue by jgkamat** [siacs/Conversations#2461]
#### General information

* **Version:**  1.18.2 (no problem on 1.18.0)
* **Device:** one plus one
* **Android Version:** cyanogenos 13.x
* **Server name:**  conversations.im, fysh.in
* **Server software:** unknown
* **Installed server modules:** unknown
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Send a message

#### Expected result

What is the expected output? What do you see instead?
Message sent

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
E/AndroidRuntime(18798): Process: eu.siacs.conversations, PID: 18798
E/AndroidRuntime(18798): java.lang.NullPointerException: Attempt to invoke virtual method 'eu.siacs.conversations.entities.Account eu.siacs.conversations.entities.Conversation.getAccount()' on a null object reference
E/AndroidRuntime(18798): 	at eu.siacs.conversations.services.XmppConnectionService.sendMessage(XmppConnectionService.java:1198)
E/AndroidRuntime(18798): 	at eu.siacs.conversations.services.XmppConnectionService.sendMessage(XmppConnectionService.java:1194)
E/AndroidRuntime(18798): 	at eu.siacs.conversations.ui.ConversationFragment.sendAxolotlMessage(ConversationFragment.java:1509)
E/AndroidRuntime(18798): 	at eu.siacs.conversations.ui.ConversationFragment.sendMessage(ConversationFragment.java:409)
E/AndroidRuntime(18798): 	at eu.siacs.conversations.ui.ConversationFragment.access$400(ConversationFragment.java:81)
E/AndroidRuntime(18798): 	at eu.siacs.conversations.ui.ConversationFragment$9.onClick(ConversationFragment.java:360)
W/ActivityManager( 4742):   Force finishing activity eu.siacs.conversations/.ui.ConversationActivity
W/ActivityManager( 4742): Activity pause timeout for ActivityRecord{736347 u0 eu.siacs.conversations/.ui.ConversationActivity t2969 f}
I/chatty  (18798): uid=10251(eu.siacs.conversations) expire 1 line
I/WindowState( 4742): WIN DEATH: Window{c1037e6 u0 eu.siacs.conversations/eu.siacs.conversations.ui.ConversationActivity}
I/ActivityManager( 4742): Process eu.siacs.conversations (pid 18798) has died
W/ActivityManager( 4742): Scheduling restart of crashed service eu.siacs.conversations/.services.XmppConnectionService in 1000ms
I/ActivityManager( 4742): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=eu.siacs.conversations cmp=eu.siacs.conversations/.ui.ConversationActivity} from uid 1000 on display 0
I/ActivityManager( 4742): Start proc 19056:eu.siacs.conversations/u0a251 for activity eu.siacs.conversations/.ui.ConversationActivity
I/chatty  (19056): uid=10251(eu.siacs.conversations) expire 13 lines
I/chatty  (19056): uid=10251(eu.siacs.conversations) expire 3 lines
I/chatty  (19056): uid=10251(eu.siacs.conversations) expire 48 lines
I/chatty  (19056): uid=10251(eu.siacs.conversations) expire 20 lines
I/chatty  (19056): uid=10251(eu.siacs.conversations) expire 36 lines
````

Sorry for the lack of information, typing this on my phone. I get a crash when in upgraded to 18.2 when sending any message. I think I got the stack trace, let me know if thats not enough and I'll try and get the full logs. 

Let me know if you need anything else, and sorry if this is a dupe (on my phone, I'll clean this up later)

**Comment by iNPUTmice** [comment]
Is this for every conversation?
What happens if you send a non-encrypted messages?
What happens if you open the contact details of that conversation.

**Comment by jgkamat** [comment]
This happens for every conversation I've tried with, MUC and single chats. This happens with encryption on and off. Opening the contact details page of the conversations does the expected behavior (no crash). 

I can try getting more logs if that would be helpful, would it?

**Comment by bodems** [comment]
Crashes on my phone too, but not with every message.

- Version: 1.18.2
- Device: Motorola Moto E (2. Generation) LTE
- Android Version: Android 5.0.2
- Server name: jabber.space.bi
- Server software: Prosody (don't know the version)
- Installed server modules: unknown
- Conversations source: F-Droid

I don't have any debug outputs to paste here, but I sent crashlogs directly via Conversations. This happend twice since the update to 1.18.2 last weekend. I hope this helps

**Comment by jgkamat** [comment]
Is there any pattern to working around your crash? I can't seem to find a workaround for now... :cry:

**Comment by iNPUTmice** [comment]
FWIW i don't think @jgkamat and @bodems are experiencing the same crash. 1.18.3 fixed a crash that was introduced in 1.18.2 for which I received a lot of stack traces. I believe this is what @bodems was is seeing.
However your crash @jgkamat is pretty weird. There shouldn't be a code path that leads to that situation. Maybe update to 1.18.3 as well. Certainly doesn't hurt. But it doesn't explicitly fix what ever causes your app to crash.

**Comment by jgkamat** [comment]
I really needed to get on xmpp so I did a clean install of conversations and that seemed to fix the issue for me. I think that it must be some weird state when upgrading from an older conversations. I can't reproduce this anymore, so feel free to close it if you want.

**Comment by iNPUTmice** [comment]
Ok I'm closing here. Like I said this was a very strange bug; We probably would have needed a debugger to get to the bottom of this. By looking at the code I couldn't find a code path to would lead to the conversations object being null at this point. (The same object is used earlier)
