### ISSUE TITLE
Make images / videos sent by plain URLs downloadable again

### ISSUE THREAD

**Issue by SoftwareSchlosser** [siacs/Conversations#2462]
#### General information

* **Version:** 1.18.0
* **Device:** Samsung Galaxy S4
* **Android Version:** Android 7.1.1 LineageOS 14.1
* **Server software:** prosody 0.10
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Send plain URL to image / video to Conversations Client

#### Expected result

In the past images were shown directly or a "download" button appeared for videos and larger images. This was very useful and I would like to know how to get the old behavior back.

**Comment by iNPUTmice** [comment]
Fix the sending client to include the URL in the oob tag. (In case of Gajim this means upgrade the HTTP upload plugin.)
Plain text URLs will no longer be recognized as downloadable for security reasons.

**Comment by SoftwareSchlosser** [comment]
This is not the same as the file has to be downloaded to the sending client first. The old behavior was very handy because you could just send the URL without having to download anything before sending. I see there are security issues with this but an option in the expert settings would be a good solution in my opinion.
