### ISSUE TITLE
Compatibility with ChatSecure on iOS (OMEMO+OTR)

### ISSUE THREAD

**Issue by n00b12345** [siacs/Conversations#2464]
ChatSecure has an OMEMO+OTR mode on iOS, enabling which leads to constant errors in Conversations about incompatible plugins in the Conversations app. Is this not supported yet? If so, could you please consider adding such a feature?

Thank you. I love Conversations. It's a great app.

**Comment by iNPUTmice** [comment]
OTR is obsolete these days. To prevent the plugin warning ChatSecure should send OTR encrypted messages to the full jid. But at this point it's probably easier to just disable OTR than to fix it.
