### ISSUE TITLE
New conference: When initiated by conversations, Gajim client cant connect

### ISSUE THREAD

**Issue by JimmyS83** [siacs/Conversations#2466]
#### General information

* **Version:** 1.18.2
* **Device:** LG L-90
* **Android Version:** 4.4
* **Server name:** jabjab.de
* **Server software:** ejabberd 17.01
* **Installed server modules:** All important (carbon msg., push, etc.)
* **Conversations source:** F-Droid
Gajim version:  0.16.7, Windows 7

#### Steps to reproduce

1. Create new conference in Conversations
2. Invite people with Gajim PC program
3. User PC got the invite, can click on accept, but for some reason, he cant connect to the conference (conference JID is somehow shown in contact list after accepting, but he cant join it.

I tried this with and without "use name of conference instead JID" in Conversation menu. It doesnt matter. When I create conference within Gajim PC client, Conversation user can connect without problem.

Also, when I didnt invite people, and conference is public, I can join from Gajim Windows afterwords through the list of conferences. Even when it is created by conversations. Therefore I think, there is some problem with invitation format message, created by conversations.

#### Expected result

After conversations.im iniciate the conference, Gajim Windows users should be able to connect normally to the conference.

**Comment by iNPUTmice** [comment]
This is a Gajim bug. Please report it to them. The invite is generated by the server.
