### ISSUE TITLE
[Bug report] Conversations does not display the own OpenPGP fingerprint and does not allow for deletion of an own OpenPGP key

### ISSUE THREAD

**Issue by Olf0** [siacs/Conversations#2470]
Prelude: 
I had to revoke an OpenPGP key of one of my XMPP accounts due to technical reasons (in OpenKeychain).  Now I want to publish the newly created OpenPGP key for that account in Conversations, but it always re-publishes the old key.  So I figured one has to stop using that key in Conversations first (i.e. deleting it there). 

Bug report: 

a. Conversations does not display the published OpenPGP key's fingerprint for a XMPP account under "Manage accounts".  IMO it should be listed below the OTR and OMEMO fingerprints. 

b. An OpenPGP key listed there (represented by its fingerprint) should be deleteable with a grey "X", allowing to publish a different OpenPGP key thereafter. 

Tested with Conversations 1.18.0 and 1.18.2 under Android 4.1.2.

Kudos for continuously enhancing the world's best XMPP-Client! 

*Edit:* Rectified Conversations' version numbers, above.

**Comment by uchchishta** [comment]
You mean 1.18.0 and 1.18.2?

**Comment by Olf0** [comment]
@uchchishta: Thanks for pointing out the incorrect version numbers.

**Comment by Olf0** [comment]
@iNPUTmice: Yes, it took me a while to understand that this seems to be the root cause of what is described in issue #2100. Hence I tried to describe an approach, which is as simple as possible. 

Sorry for the brief bug report, but I assumed this would already describe the core issue and possible solution appropriately.  If you need more information (e.g. logs etc.), please let me know.

**Comment by Olf0** [comment]
@iNPUTmice: Wow, that was quick, plus containing some small OTR handling enhancements / fixes.
Thanks a lot, [commit f98888d](https://github.com/siacs/Conversations/commit/f98888d796728b5ef1fea1ad1db19ca60df21fbc) is looking good to me (though I am *not* a Java programmer at all).  I will test, when released, and may provide additional feedback then, but only if necessary (i.e. if I experience anything unexpected).
Cheers and kudos to you.

**Comment by Olf0** [comment]
And (quick as usual) released with Conversations 1.18.4: 
Working nicely, one round trip tested (deleting an OpenPGP key, then publishing it again). 
Thanks, again.
