### ISSUE TITLE
[Bug report] Conversations does not allow to distrust an OpenPGP key of a communication partner

### ISSUE THREAD

**Issue by Olf0** [siacs/Conversations#2471]
Background:
Conversations cannot detect revoked or simply distrusted foreign OpenPGP keys (i.e. in OpenKeychain). 
It would need much tighter integration of OpenKeychain in Conversations to enable that, which is not worth the effort, IMO. 
Hence the trust state of OpenPGP keys of communication partners has to be handled manually in Conversations.  

Bug report: 
While the fingerprint of a published and once trusted OpenPGP key from a communication partner is nicely displayed under "Contact details" below the OTR and OMEMO fingerprints, it cannot be distrusted (in contrast to the OMEMO certificates) there. 

Please provide a switch for distrusting OpenPGP keys there (just as it is already implemented for OMEMO certificates).

Tested with Conversations 1.18.0 and 1.18.2 under Android 4.1.2. 

Many thanks for all your efforts and the excellent result: Conversations

**Comment by iNPUTmice** [comment]
OpenPGP keys are never manually trusted in the first place (as far as
Conversations is concerned). It will blindly encrypt to any key the other
party announces.
Thus 'untrusting' a key doesn't really make sense without changing the
entire OpenPGP workflow.
Also note that the PGP integration is pretty much unmaintained as I'm not
really using it myself and the focus has shifted to using OMEMO. So don't
expect anything to happen on that front if you don't do it yourself.

**Comment by Olf0** [comment]
@iNPUTmice: Mmmh, I believe I have to think a little more about your statement: 
> Thus 'untrusting' a key doesn't really make sense without changing the entire OpenPGP workflow. 

Currently, I cannot see that this is the really case.  I feel I shall try to simulate a couple of scenarios ("workflows") around OpenPGP encryption, before stating something (hopefully) more conclusive (but without a solution to issue #2470 this is tricky and tedious to achieve).

**Comment by Olf0** [comment]
Ah, now I believe to understand that the simple modeling of foreign OpenPGP keys is basically: 
Do simply not switch to OpenPGP encryption, if you do not want to use a communication partner's OpenPGP key.  Conversations will just take published OpenPGP keys and offer them to be used to encrypt messages. 

O.K., this leaves issue #2470 as the only blocker from a working (though minimalistic) OpenPGP key management over whole (ones own) key lifecycles, thus closing this issue.
