### ISSUE TITLE
Documentation for Conversations

### ISSUE THREAD

**Issue by Ankur008** [siacs/Conversations#2472]
#### General information

* **Version:** 
* **Device:** 
* **Android Version:** 
* **Server name:** 
* **Server software:** ejabberd 
* **Installed server modules:** 
* **Conversations source:** 

I am looking for the android client for XMPP. I have tried smack but stuck with somewhere so thinking to switch on another XMPP Android client. I have few questions:

   1. Is there any documentation available for the conversations
   2. How do I integrate conversations with the android? 
   3. I have setup the server using the ejabberd and have all contact list jabber ids. Do I need to re-register these jabber ids in order to use the conversations?

**Comment by hareshkh** [comment]
What do you mean here by integrating Conversations with Android? Conversations already has an Android application.

**Comment by licaon-kter** [comment]
What happens when you use the app? What's the problem?

**Comment by Ankur008** [comment]
I know conversations has their own android application. I am thinking if I can use conversations API to build own chat system. Is it possible? @hareshkh

**Comment by licaon-kter** [comment]
What API? What's a chat system?

If you want an app of your own do cont(r)act Daniel Gultsch ( https://gultsch.de/ )

**Comment by Ankur008** [comment]
thanks @licaon-kter . Let me correct if I am wrong basically conversations is the android app for chat not an XMPP android client like smack which provides the API to send the message.

**Comment by iNPUTmice** [comment]
Conversations is not a library. If you want to build your own client you should be using Smack.
