### ISSUE TITLE
Confirmation for "End Conversation"

### ISSUE THREAD

**Issue by nekoswag** [siacs/Conversations#2473]
#### General information

* **Version:** 1.18.2
* **Device:** LG G4 h815
* **Android Version:** Android 6.0, Kernel 3.10.84
* **Server name:** self hosted
* **Server software:** Prosod 0.9.12
* **Installed server modules:** roster, saslauth, tls, dialback, disco, private, vcard, version, uptime, time, ping, pep, register, admin_adhoc, posix, blocking, smacks, carbons, mam, csi, http, http_upload, muc
* **Conversations source:** F-Droid

When selecting "End Conversation" from the menu, the entire chatlog is deleted without confirmation. It would be nice if there was a confirmation dialog before.

**Comment by uchchishta** [comment]
"End conversation" does not delete the chat, it only closes it. If the contact messages you again (or vise versa) it will reopen.
Only `clear chat` deletes it with a confirmation.
