### ISSUE TITLE
A bug in Export history

### ISSUE THREAD

**Issue by participante0** [siacs/Conversations#2478]
#### General information

* **Version:** 1.18.4 beta
* **Device:** Google Nexus 5X
* **Android Version:** Android 7.1.2 Stock
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

Let's assume I had a conversation with my contact _AAA_
1. Expert settings – Export history
2. Reinstall Conversations
3. Chat again with _AAA_
4. Expert settings – Export history

Maybe the step 2. can be replaced with:
2. Clean the history in the conversation with _AAA_
...but I didn't test that.

#### Expected result

I expect the new history be added at the end of the log file.
Instead, the new history **REPLACED** the old one, causing a loss of data when the server didn't save the history (OMEMO or MAM disabled).

**Comment by iNPUTmice** [comment]
I don’t consider this a bug. You should move the files away before exporting them again. However export to plain text files is a flawed concept and is replaced by 'proper' backup/restore in 2.4.0
