### ISSUE TITLE
Repeadly sent GCM messages

### ISSUE THREAD

**Issue by dazzzl** [siacs/Conversations#2480]
I've found a lot (>100) of GCM messages for Conversations sent in a very short period. Maybe this is correlated with sometimes high battery drain and high amount of transferred data. 

#### General information

* **Version:** 1.18.4
* **Device:** Sony Xperia M
* **Android Version:** Lineageos 14.1 (Android 7.1) 
* **Server name:** self hosted
* **Server software:** prosody trunk 
* **Installed server modules:** Stream Managment, CSI, MAM, could_notify, csi_battery_saver, 
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Smartphone is running on batttery
2. plug in USB and open logcat

#### Expected result

Not >100 GCM messeages during 10 seconds 

#### Debug output

Log is shortened to only few entries. More than 100 entries between around 8 seconds. 

`05-11 14:46:52.447 D/conversations(13521): gcm push message arrived in service. extras=Bundle[{google.sent_time=1494506747432, account=xx, google.message_id=0:1494506747434763%8ded97dff9fd7ecd}]
05-11 14:46:52.451 D/conversations(13521): xx send ping (action=gcm_message_received,lowTimeout=true)
05-11 14:46:52.509 D/conversations(13521): gcm push message arrived in service. extras=Bundle[{google.sent_time=1494506747427, account=xx, google.message_id=0:1494506747429597%8ded97dff9fd7ecd}]
05-11 14:46:52.516 D/conversations(13521): xx send ping (action=gcm_message_received,lowTimeout=true)
05-11 14:46:52.569 D/conversations(13521): gcm push message arrived in service. extras=Bundle[{google.sent_time=1494506747434, account=xx, google.message_id=0:1494506747435296%8ded97dff9fd7ecd}]
05-11 14:46:52.573 D/conversations(13521): xx send ping (action=gcm_message_received,lowTimeout=true)
05-11 14:46:52.611 D/conversations(13521): gcm push message arrived in service. extras=Bundle[{google.sent_time=1494506747454, account=xx, google.message_id=0:1494506747461742%8ded97dff9fd7ecd}]
05-11 14:46:52.614 D/conversations(13521): xx send ping (action=gcm_message_received,lowTimeout=true)
05-11 14:46:52.689 D/conversations(13521): gcm push message arrived in service. extras=Bundle[{google.sent_time=1494506747455, account=xx4, google.message_id=0:1494506747457704%8ded97dff9fd7ecd}]
05-11 14:46:52.693 D/conversations(13521): xx send ping (action=gcm_message_received,lowTimeout=true)
05-11 14:46:52.740 D/conversations(13521): gcm push message arrived in service. extras=Bundle[{google.sent_time=1494506747451, account=xx google.message_id=0:1494506747451199%8ded97dff9fd7ecd}]
05-11 14:46:52.745 D/conversations(13521): xx send ping (action=gcm_message_received,lowTimeout=true)
`

**Comment by iNPUTmice** [comment]
Your server is creating these pushes. Our app server just proxies them. There is no reason our App server should throttle the incoming pushes.
