### ISSUE TITLE
If body tag is not under message tag then message is not parsed

### ISSUE THREAD

**Issue by PeterEdens** [siacs/Conversations#2481]
Send an http-upload file message from jsxc to conversations and it is not received because the body tag is not the first under the message tag.  
`<message type="chat" xmlns="jabber:client" id="1494550262068:msg" to="admin@domain" from="peter@domain/45701948953295201063820572430078852969999701042805870553"><html xmlns="http://jabber.org/protocol/xhtml-im"><body xmlns="http://www.w3.org/1999/xhtml"><a href="https://domain/chat-files/c5b0c01d2c83150b096a76694fc9305120bf1ec4/k4JHM4Y4y44wiCmTP5HOcXX2uGHiZT1nLbgJKtkT/ejabberd.yml" data-name="ejabberd.yml" data-size="16375" data-type="" xmlns="http://www.w3.org/1999/xhtml">https://domain/chat-files/c5b0c01d2c83150b096a76694fc9305120bf1ec4/k4JHM4Y4y44wiCmTP5HOcXX2uGHiZT1nLbgJKtkT/ejabberd.yml</a></body></html><request xmlns="urn:xmpp:receipts"/><active xmlns="http://jabber.org/protocol/chatstates"/></message>`

In MessageParser.java line 335:
final String body = packet.getBody();

This only checks the children of the message element so body will not be found.

A recursive check would probably add a lot of overhead so possibly just check 1 extra level down?

**Comment by iNPUTmice** [comment]
Conversations doesn't support XHTML-IM nor does it advertise support for it.
The message should always include a body as well. In this particular case it is advisable that the body contains the URL and just the URL. If JSXC also includes a xoob tag (XEP-0066) containing that URL Conversations will display that as a download. Technically for Conversations it would be enough to just put the URL into an xoob tag but there will be other clients that don't support XHTML-IM and XEP-0066.

Please open a bug on the JSXC tracker.
