### ISSUE TITLE
Scrolling to top jumps to bottom

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2484]
#### General information

* **Version:** 1.18.4
* **Device:** Xperia
* **Android Version:** Android 6.0.1 stock
* **Conversations source:** F-Droid

#### Steps to reproduce

Scroll up fast (slow works ok)

#### Expected result

It stops at the first message

#### Actual result

It jumps back to the last message

#### Debug output

Soon

**Comment by iNPUTmice** [comment]
I think ef980ff5cff9653f105fb16bb9a617fab5c82704 might have fixed this as a byproduct.

**Comment by licaon-kter** [comment]
Great, will close once confirmed. :+1:

**Comment by licaon-kter** [comment]
Looks ok so far. Thanks

**Comment by licaon-kter** [comment]
Some more info, it's better now, altough you can still pull hard and it will hit the first message (loaded so far) and the recoil can send it back to the lat one.
