### ISSUE TITLE
Prioritize load XMPP MAM history from last messages and for current opened contact

### ISSUE THREAD

**Issue by MurzNN** [siacs/Conversations#2487]
I actively talk via Jabber account on desktop computer, and sometimes connects to it via Conversations.
And after long offline time Conversations loads XMPP MAM history very long time, and from older message to newer.
So I need wait long time when history was synced to see last messages for current contact.

Can you prioritize loading XMPP MAM history backwards - load at first last messages by timestamp?

Additionally, great improvement will be if I open chat dialog with some contact - prioritize loading XMPP MAM history only for current opened contact.

What do you think about this feature request?

**Comment by MurzNN** [comment]
Javascript XMPP client https://conversejs.org works like described, so if I open chat window - it instantly load only some last messages from current contact history, and loads other history on background, by request.

**Comment by iNPUTmice** [comment]
loading the history backwards will create all sorts of troubles. For example chat markers can not be properly processed. Also this will create gaps in the local history which will become harder and harder to fill. Loading history only for single contacts also robs us of the ability to have a single MAM reference pointer which we can use to start loading the history.

I understand that this situation is not ideal if you only turn on Conversations every couple of days. But Conversations is designed to be an always on messenger and we try to optimize for that use case.

**Comment by MurzNN** [comment]
Thanks for detailed description! I understand those hard impementation of this MAM syncing, if we broke whole sync process to parts.

As easy workaround I see the way when got chat open event - load MAM history temporary only for display on screen, without saving to local history database, and after this continue syncing history database in background.  This way will not broke MAM syncing process and solve problem with looking last messages from contact.

**Comment by MurzNN** [comment]
At now using Conversations in not "always on" mode is too uncomfortable: always after each time I go online (with many not synced messages) - I must wait long time to receive many messages (and each offline already read message in other clients receives with sound), and only after this can normally use application for talking.

But I can't find any other XMPP client for Android that can sync MAM history from server :(
