### ISSUE TITLE
Delivery failed in groupchat after server restart

### ISSUE THREAD

**Issue by Fank** [siacs/Conversations#2489]
#### General information

* **Version:** 1.18.4
* **Device:** OnePlus 3
* **Android Version:** Android 7.1.1 OxygenOs 4.1.3
* **Server name:** fankserver.com (self hosted)
* **Server software:** prosody 0.10
* **Installed server modules:** Alot, incl. (HTTP, and HTTP upload)
* **Conversations source:** F-Droid

#### Steps to reproduce

Me to remote
1. Join remote groupchat (hosted on not the same server as connected)
2. Restart the xmpp server, you are connected with
3. Now write something in the groupchat (1.) and see message could not be delivered (error: "not acceptable")

Remote to me
1. Join remote groupchat (hosted on not the same server as connected)
2. Restart the remote xmpp server
3. Now write something in the groupchat (1.) and see message could not be delivered (error: "not acceptable")

#### Expected result

Message should be send

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

No adb output just delivery failed.

Workaround for fixing this issue, is leaving the group and rejoin it.

**Comment by Fank** [comment]
After some debugging i found following:

The stanza which is send:
```
<message type='groupchat' to='test@conference.fankserver.com' from='frozen_byte@neko.im/mobile' id='3d5366b6-e17b-42ca-8cde-46a5ae61d4f5'><body>asd</body><origin-id id='3d5366b6-e17b-42ca-8cde-46a5ae61d4f5' xmlns='urn:xmpp:sid:0'/></message>
```

And the stanza which is received from the server:
```
<message id='3d5366b6-e17b-42ca-8cde-46a5ae61d4f5' type='error' to='frozen_byte@neko.im/mobile' from='test@conference.fankserver.com'><error type='cancel'><not-acceptable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></message>
```

Because the group session is not available anymore, the client should connect to the groupchat again.

**Comment by Fank** [comment]
Is it possible to try a rejoin if `<error type='cancel'><not-acceptable` is received on send?

**Comment by mimi89999** [comment]
Can't reproduce. It is an issue with your server. Please ask support in the official MUC (linked in the README)

**Comment by Fank** [comment]
@mimi89999 Register on server a, join muc on server b, restart server b, write something in chat and notice error.
I did not notice this error in other clients.

**Comment by mimi89999** [comment]
Works well. Also, latest version in F-Droid is 1.18.5

**Comment by Fank** [comment]
Can't find the official muc in readme, can you link them?

**Comment by mimi89999** [comment]
conversations@conference.siacs.eu

**Comment by Fank** [comment]
@mimi89999 Thanks for helping debbung, its a prosody 0.10 issue, its fixed in prosody trunk

**Comment by ldvc** [comment]
@Fank A bit late but I might be suffering the same issue Conversations + Prosody 0.10. Could you please point me to the Prosody issue link? Thanks!

**Comment by Fank** [comment]
I don't know the prosody issue, just used trunk and it worked
