### ISSUE TITLE
Copy & Paste?

### ISSUE THREAD

**Issue by Urodela** [siacs/Conversations#2490]
#### General information

* **Version:** 1.18.4
* **Device:** LG SmartWine H410
* **Android Version:** Android 5.1.1 Stock
* **Conversations source:** F-Droid
----
Hi there and sorry for my poor English :) The Changelog says: removed 'copy text' in favor of 'select text' and 'share with'

But now, how i am able to Copy & Paste? I can select the text but i don't see what for. The "marked text" isn't in the clipboard and i cant paste it.

Now i need to "share with" (a text editor for example), mark the text in the editor and copy the text there, switch back to Conversations and finally paste it. Is this how it should work? Cant see the use of "select text" besides its selecting text.

Thanks for reading and any help :)

**Comment by licaon-kter** [comment]
Your Android should select the whole message and have the cursors at start and end, plus the floating bar with cut/copy/whatever.

**Comment by Xohoo** [comment]
1.)	Select share with
2.)	Chose in the app list conversations
3.)	Chose the contact u want to send the text
4.)	Press send

**Comment by Urodela** [comment]
Thanks for answering! @Topic: Thats on my Wife's phone, she is still at work. But as far as I remember there is no "floating bar" or anything. But i check again as soon as i have the Phone at Home. Maybe i can make a Screenshot too.

**Comment by licaon-kter** [comment]
Xperia 6.0.1 looks like this: https://lut.im/sZcFPRMHmr/tFL7yiw7pG13u3xR.jpeg

**Comment by Urodela** [comment]
@Xohoo: your way works, thanks for this "workaround"! @licaon-kter: not on this Phone. Long press on the Text brings up the context menu which says "select text" and "share with". Now if i choose "select text" the only thing that happen is that the text is marked. Looks the same like on your Screenshot but without the Start and End points. If i touch the "marked text" again it gets unmarked instantly. So it just do what it says: Selecting Text.

This LG Phone have a Hardware Keyboard, maybe there's a Problem. But "share with Conversation" is working so it should be ok i guess. Thanks for your answers and your time! :)

**Comment by licaon-kter** [comment]
But you get such a menu in other apps? Any open source apps that we can see what code they use?

**Comment by Urodela** [comment]
@licaon-kter: Prior to 1.18.4 it was working with Conversations too. Just Long press >> choose "copy text" >> paste it. Thats all! But as the Changelog says, "copy text" got removed!

**Comment by iNPUTmice** [comment]
At least newer versions of Android also have share with… Cliploard
