### ISSUE TITLE
'TLS error' is too generic, is there a way to get the list of attempted ciphers?

### ISSUE THREAD

**Issue by evaryont** [siacs/Conversations#2497]
#### General information

* **Version:** 1.18.4
* **Device:** Galaxy S7 (SM-G930T)
* **Android Version:** Android 7.0, March 1st security patch level
* **Server name:** self-hosted
* **Server software:** prosody 0.9 on CentOS 7
* **Installed server modules:** numerous, but it passes the Advanced Server and Client suites from XEP-0387 per [ComplianceTester](https://github.com/iNPUTmice/ComplianceTester)
* **Conversations source:** Google Play Store

#### Steps to reproduce

1. Configure prosody to use [Mozilla's recommended TLS cipher list](https://wiki.mozilla.org/Security/Server_Side_TLS), Modern configuration:
```
VirtualHost "example.com"
        enabled = true -- Remove this line to enable this host
        http_external_url = "https://chat.example.com"

        -- Assign this host a certificate for TLS, otherwise it would use the one
        -- set in the global section (if any).
        -- Note that old-style SSL on port 5223 only supports one certificate, and will always
        -- use the global one.
        ssl = {
                key = "/etc/dehydrated/certs/example.com/privkey.pem";
                certificate = "/etc/dehydrated/certs/example.com/fullchain.pem";
                protocol = "tlsv1_2";
                ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256";
        }
```

2. Try to connect to the server with various XMPP clients (Gajim on Win10, Jitsi on Win10, Conversations on Android)
3. Notice that Conversations is the only one that complains about TLS errors.
4. Append *:AES128-GCM-SHA256:AES256-GCM-SHA384* to the list of cipher suites, and Conversations stops complaining.

#### Expected result

Conversations should have connected without errors using moden cipher suites.

**Comment by iNPUTmice** [comment]
This is primarily limited by your Android distribution. Conversations just *excludes* some very weak ciphers. https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/Config.java#L148

**Comment by evaryont** [comment]
Do you know of a way to query the list of ciphers used in attempts to connect to the server? I've used Samsung's browser to load the webserver configured with the same cipher list (just Mozilla's modern configuration) without error. I don't have much connecting to the server, but it seems like Conversations is the only application that does have an issue.

**Comment by iNPUTmice** [comment]
Browsers usually bring their own TLS stack.
I think you can print this platformCiphers Array https://github.com/siacs/Conversations/blob/6c34763d32f1619b8ff2496d7c728c27d6823083/src/main/java/eu/siacs/conversations/utils/CryptoHelper.java#L121-L121
