### ISSUE TITLE
Is the message saved in encrypted after received ?

### ISSUE THREAD

**Issue by dodaeche** [siacs/Conversations#2499]
#### General information

* **Version:** e.g. 1.18.1
* **Device:** e.g. Samsung Galaxy A5, A500S
* **Android Version:** eg Android 6.0 
* **Server name:** eg self hosted
* **Server software:** openfire 4.1.0 
* **Installed server modules:** eg I don't know..
* **Conversations source:** eg self build 

When I've got messages from contact with OMEMO protocol, the messages will be stored on my android machine. At this time, does Conversations save the message being encrypted? It will be not  a plain/text.
How do I verify that messages is stored with encrypted or not in my android device? or in Conversations source code repository.

**Comment by iNPUTmice** [comment]
It is not stored encrypted on the device. OMEMO is end-to-end encryption. Not on-end encryption. You need to encrypt your Android if you want to have on device encryption.
By the way we have a group chat that is more suited for these kind of questions.
