### ISSUE TITLE
Message sending problems

### ISSUE THREAD

**Issue by Dionis0s** [siacs/Conversations#2501]
#### General information

* **Version:** 1.18.4
* **Device:** Google Nexus 5
* **Android Version:** Android 7.1.2 LineageOS 20170516
* **Server name:** mailbox.org to trashserver.net
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Send a unencrypted message from an mailbox.org account to an trashserver.net account (Message will not receive, OMEMO grayed out)
2. Send a unencrypted message from an trashserver.net account to an mailbox.org account (Message will receive, but OMEMO grayed out)

#### Debug output

E-Mail from mailbox.org:

> Sie sind nicht die einzige Person, bei der Probleme in der Kommunikation mit Conversations und trashserver.net auftreten.
> 
> Wir haben uns jetzt hier trashserver-Accounts geholt und rumgespielt. Dabei ergab sich eher das Bild, dass das Initiieren der Omemo-verschlüsselten Verbindungen nicht richtig klappt:
> Szenario:
> * Trashserver-Account ist mit 2 Clients angemeldet (Gajim und Conversations)
> * mailbox.org-Account nur mit Gajim
> * Zu einem der Trashserver-Clients wird eine Omemo-Verbindung hergestellt und die
> Nachrichten kommen an.
> * Zum zweiten Trashserver-Client schlägt das erstmal fehlt. Bei mir war in Gajim kein Omemo-Knopf da. Bei meinem Kollegen, der das Spielchen auch gemacht hat, fehlte der Omemo-Schalter in Conversations.
> So kamen auf einem Trashserver-Client die Nachrichten nicht an. Im Log taucht dazu nichts auf. Da werden nur erwähnt, die erfolgreich an die eine Ressource zugestellt wurden.
> Später, als ich alles mal neu connected hatte, ging es aber mit beiden Geräten.
> 
> Das sieht also ehrlich gesagt aus meiner Sicht eher nach einem **Client-Problem** aus... daher können wir von unserer Seite aus nichts machen.

**Comment by iNPUTmice** [comment]
> Später, als ich alles mal neu connected hatte, ging es aber mit beiden Geräten.

This is symptomatic of some prosody versions not sending PEP notifications after gaining mutual presence subscriptions. This has been fixed some time ago but I'm not sure if this was only fixed for 0.10 or 0.9 as well.

> Send a unencrypted message from an mailbox.org account to an trashserver.net account (Message will not receive, OMEMO grayed out)

This problem may or may not be related. Does the message change from *sending…* to sent (indicated by showing the timestamp or *just now*)
If yes your server has received the message and is now responsible for handling the message.

Also in your scenario where mailbox.org can't deliver messages to trashserver.net it us no surprise that the mailbox contacts has a grayed out omemo as the PEP notifications wouldn't go through either.

In any case. We don't use this issue tracker as a support forum. Please use our group chat if you have further questions.
