### ISSUE TITLE
[Translation] [French] About the sentence to send a message (un)crypted

### ISSUE THREAD

**Issue by blankoworld** [siacs/Conversations#2502]
#### General information

* **Version:** 1.18.3

#### Explanation

While using Conversations to send a message, in French you have 4 sentences that could appears in the sending area (where you write the message before you send it) : 

  * a sentence to send a message to a MUC without encryption
  * a sentence to send a crypted message to a MUC
  * a sentence to send a message to a specific contact without encryption
  * a sentence to send a crypted message to a specific contact

In French, for "crypted"/"uncrypted", it uses these words:

  * non chiffré (uncrypted)
  * chiffré (crypted)

The problem is that if you use the same word for uncrypted and crypted, you can send by error a message uncrypted in place of a crypted one. Because the word looks like a lot the second one.

##### Suggestion

So in fact, in French we have some other words to explain the same thing, I suggest so to use these words for the translation in the 4 sentences I talk about:

  * en clair (uncrypted)
  * chiffré (crypted)

In this way the user saw directly with another word that something changed (encryption or not).

Do you think that it's possible to do something about that?

FYI, I'm connected to Transifex under this pseudo: blankoworld.

I thanks you in advance for the help you can give.

Have a nice day,

Olivier alias blankoworld.

**Comment by licaon-kter** [comment]
Just edit it on Transifex and be done, if one does not like it s/he should comment there.

/Close as invalid

**Comment by iNPUTmice** [comment]
I accepted your join request.
