### ISSUE TITLE
OOB registration via external URL gives only general error

### ISSUE THREAD

**Issue by ramack** [siacs/Conversations#2503]
#### General information
* **Version:** 1.18.5
* **Device:** Samsung XCover 4
* **Android Version:** Android 7.0 Stock
* **Server name:** self hosted
* **Server software:** prosody 0.9.7
* **Installed server modules:** register_redirect
* **Conversations source:** F-Droid

#### Steps to reproduce
1. create new account
2. check the box to create account on server
3. press continue

#### Expected result
Conversations should open a warning with the registrtion link or directly open the link in the web browser. Instead it just tells "Registration failed".

registration_url  is set in prosody config as shown in https://modules.prosody.im/mod_register_redirect.html
Gajim nicely opens a dialog box telling the configured message on how to register.

**Comment by iNPUTmice** [comment]
Do you have an example server (domain) where this module is deployed?

**Comment by iNPUTmice** [comment]
Can you send me that domain again? I did some modifications on the registration code and want to avoid any regressions.
