### ISSUE TITLE
Connection Issue with Openfire (4.1.4)

### ISSUE THREAD

**Issue by Nits2407** [siacs/Conversations#2506]

**Comment by iNPUTmice** [comment]
Please search the bug tracker for duplicate issues.

**Comment by Nits2407** [comment]
give me the bug no,there are 231 bugs

**Comment by licaon-kter** [comment]
Search: https://github.com/siacs/Conversations/issues?utf8=%E2%9C%93&q=is%3Aissue%20connect%20Openfire%20is%3Aclosed%20

**Comment by iNPUTmice** [comment]
#2249 is the issue that currently holds the most useful information.
