### ISSUE TITLE
UI to obtain reasons that OMEMO cannot be enabled

### ISSUE THREAD

**Issue by adrien-n** [siacs/Conversations#2507]
Currently  when OMEMO cannot be used, the entry in the menu is simply greyed out. This makes it difficult to understand why it is not available. 

Below is a UI proposal to give the user access to the reasons it fails. Possible messages include "Server does not support Avatar/OMEMO (XEP-0163)", "OMEMO key for one of the correspondant is not available" (this seems to happen with MUCs), ...

The idea is that instead of having greyed out text that cannot be interacted with, the user would be able to click on it and get a helpful message. Obviously, colors can be changed (and the conversations behind was already OMEMO'ed) but the core of the proposal remains and the bright red helps pinpoint the change. :) 

![UI Proposal](http://notk.org/~adrien/conversations_omemo_failure_help.png)

**Comment by leloeoe** [comment]
Hi,
on my phone (honor5c, android 6, un-rooted) it is greyed out as well.
i am just a user, so i do not have a deeper understanding of "MUCs" and so forth.
![screenshot_2017-06-22-09-33-38](https://user-images.githubusercontent.com/29622988/27423384-b918fb70-5731-11e7-94c9-e07793e61dec.png)

it be nice to have some tipp how to go about to make omemo work on my device, Thanks in advance.

**Comment by licaon-kter** [comment]
In a MUC (conference) OMEMO will be active if you already have all the contacts OMEMO keys on your /each others devices, IIRC.

Regarding in 1:1 chat, it's enough to have your contact, confirm the keys ( read Settings -> Blind trust... ) aka [this](https://github.com/siacs/Conversations/#what-is-blind-trust-before-verification--why-are-messages-marked-with-a-red-lock)

**Comment by guillaume-uH57J9** [comment]
The request from @adrien-n make sense, I've added using OMEMO a couple times with contacts and wondered why the OMEMO option was greyed out.

**Comment by d9h02f** [comment]
I agree. It would be a good thing if there were some short clues for how to make OMEMO work, like "You need to tick both boxes in your contact's details" or "All members of the group chat need to tick both boxes for all other members". Phrasing could be better, but this would help solve the most common problems.

**Comment by adrien-n** [comment]
I would like to remind that this is just a proposal and I hope this can lead to a discussion about such changes. It occured to me that this one could be simple enough to do and to use but that's only my opinion. Other ideas and mockups are also welcome.

**Comment by iNPUTmice** [comment]
@adrien-n FWIW in conferences you can long press the lock icon to reveal information on why OMEMO is not available. Doing the UI in a way you suggested would have been my first choice (compared to the non obvious way it is right now.) but that is difficult because you can't hook into the default android widget very easily to retrieve onClick events from disabled menu items. Pull requests are welcome though. The actual information is there; it is merely a UI job now.

**Comment by leloeoe** [comment]
it "works for me" now ;)  took a while till i found how it was meant to be put to work ( it needs to have a running chat than it´s not geryed out) Thanks

**Comment by adrien-n** [comment]
Oh, thanks. I understand the problem. I'm not familiar enough with Android to work on this by myself so I'll try to grab a few friends IRL to find another approach that is doable.

**Comment by corincorvus** [comment]
If not all user have each other, but are in the MUC, they never can use OMEMO. An option to use OMEMO without add all is the best solution i think.

**Comment by iNPUTmice** [comment]
OMEMO can now always be enabled (unless of course in public mucs).
Success will still depend on whether or not the contacts’ servers support the Conversations Compliance Suite.

**Comment by adrien-n** [comment]
Thanks. I noticed the change you mention and I was wondering if it
invalidated this ticket. I only had a couple occasions to test but the
change looked like a notable improvement already. IIRC the error message
goes away fairly quickly but that's an issue for another entry and I
feel this one should indeed be closed.
