### ISSUE TITLE
Sent files not saved locally

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2511]
#### General information

* **Version:** 1.18.5
* **Device:** Sony 5.1.1/6.0.1
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Sent a file (directly or via another app eg. [SendReduced](https://github.com/arpruss/sendreduced))

#### Expected result

1. Files can be found in chat by scrolling back at them (on device chat, archive set to none)
2. Files are saved in _/sdcard/Conversations/..._

#### What actually happens

1. Files start to disappear from the chat after a random time frame (`file deleted`)
2. Files are not in _/sdcard/Conversations/..._

This seemed to work for a while, I have some files that I've sent in the past.

**Comment by iNPUTmice** [comment]
If Conversations can get access to the real path it will not copy the file to local storage. Saving sent files to local storage is only a work around if the sharing application only 'streams' the file. SendReduced in your case probably shares the full path and discards the file at some point.
