### ISSUE TITLE
Sending/receiving files to/from other clients issue.

### ISSUE THREAD

**Issue by cpt-piper** [siacs/Conversations#2512]
* **Version:** 1.18.5
* **Device:** Any
* **Android Version:**  Android 6.0 
* **Server name:** jabber.cat
* **Conversations source:** PlayStore

I can't send and receive pics, audio and other files from ChatSecure XMPP (and Gajim too) client users whether it's encrypted message or not, so I wanted to ask if you are working on that. Many thanks.

**Comment by licaon-kter** [comment]
Error message? Logs?

**Comment by olerem** [comment]
For Gajim you need to install HttpUploadPlugin, it works just fine for me.
