### ISSUE TITLE
Move "Automatic message deletion" out of Expert settings

### ISSUE THREAD

**Issue by labdsf** [siacs/Conversations#2514]
Automatic message deletion is a thing that is easy to understand and does not require knowledge of technical terms, such as certificate, fingerprint, hostname and port, compared to other "expert" settings. The only thing user must understand is that messages are not removed from any other devices, but option description clearly says "this device". I also looked for similar issues and found #50, #627, #1037, #1100, #1407, #1748, #2267, and looks like the fact that messages are removed only from one device is the most common comment.

I don't know if #1424 is opened because user (throwaway account @tYGjQCsvVI) was not able to find an option or it was not implemented then.

Also, #1852 was closed because it was not high priority. Has anything changed since then? [Signal also added disappearing messages](https://whispersystems.org/blog/disappearing-messages/) since the issue was closed and I think they clearly explained why it is not a no-nonsense privacy feature: "Disappearing messages are a way for you and your friends to keep your message history tidy. They are a collaborative feature for conversations where all participants want to automate minimalist data hygiene, not for situations where your contact is your adversary — after all, if someone who receives a disappearing message really wants a record of it, they can always use another camera to take a photo of the screen before the message disappears." So it makes sense to implement timers on top of XMPP as a XEP, even if some clients will not support this feature. If the other party does not support timers, it is still possible to warn user about it and clear message history locally.

**Comment by iNPUTmice** [comment]
My opinion on self destructible messages has not changed.

**Comment by labdsf** [comment]
Well, the issue is not about self-destructing messages, but about "Automatic message deletion" being in expert settings.

**Comment by iNPUTmice** [comment]
Since only a very tiny fraction of users are using this feature I think it's good where it is.

**Comment by labdsf** [comment]
> only a very tiny fraction of users are using this feature

I wonder how do you know. It is impossible to track on server and Conversations, apparently, doesn't have telemetry.
