### ISSUE TITLE
How to see packet for IQ?Not only logcat

### ISSUE THREAD

**Issue by JakeWoki** [siacs/Conversations#2517]

**Comment by iNPUTmice** [comment]
Please use our MUC for questions.

**Comment by JakeWoki** [comment]
@iNPUTmice what mean?
I want to see like this:
<iq id="99l9L-6" to="test@conference.apitest.com" type="get"><query xmlns="http://jabber.org/protocol/muc#admin"><item affiliation="member"></item></query></iq>

**Comment by iNPUTmice** [comment]
That's not possible without patching Conversations and using adb logcat.
If you have further questions refer to the question sections of our FAQ: https://github.com/siacs/Conversations#conversations-doesnt-work-for-me-where-can-i-get-help

**Comment by JakeWoki** [comment]
I had add `conversations@conference.siacs.eu`,but nobody to answer my question.Can you give me some help for more detailed?Thanks
