### ISSUE TITLE
XMPP Resource not used for File Transfers

### ISSUE THREAD

**Issue by markwaters** [siacs/Conversations#2519]
#### General information

* **Version:** 1.18.4
* **Device:** Multiple
* **Android Version:** Android 4.4.2 and Cyanogenmod 6.0.1
* **Server name:** self hosted
* **Server software:** prosody 0.9.12
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Gallery.
2. Share.
3. Choose user with multiple devices.
4. Choose Device - Computer or Mobile Phone or Mobile Phone

#### Expected result

Instead of Computer or Mobile Phone(s) could we be shown the remote users XMPP resource ?
This would make it easier to differentiate between Mobile Phone and Tablet.

Thanks.

**Comment by licaon-kter** [comment]
Do test with 1.18.5 too.

**Comment by iNPUTmice** [comment]
Please post screenshots and the resources used at time of taking the screenshots. The intended behavior is to show the resource as well if the type isn't unique.

**Comment by markwaters** [comment]
Just checked version 1.18.5  on my phone and that is the same , shows 'Computer and Mobile Phone' not XMPP resource.
In Gajim I can see this remote client has his Computer set to a long random string and his Mobile phone set to 'htc 10'

**Comment by iNPUTmice** [comment]
> Just checked version 1.18.5 on my phone and that is the same , shows 'Computer and Mobile Phone' not XMPP resource.

As long as those are unique this is the intended behavior. Resources should not be used to identify clients. Future releases will prevent the user from picking a resource at all.

**Comment by iNPUTmice** [comment]
It would also be interesting to know what tablet you are using since tablets should normally identify themselves as tablet to prevent exactly this kind of situation in the first place.

**Comment by markwaters** [comment]
Here is the screenshot the remote client saw when trying to send me a photo.
https://drive.google.com/file/d/0B7Ob1JNjKbzsTU9wdTIzX2lHQms/view?usp=sharing
I would have thought XMPP Resources of Desktop , Phone and Tablet would be clearer.
The tablet is an Aoson M706T which I think is actually a 'phablet'.

**Comment by drjnet** [comment]
Hi,
I agree with Mark it would be much less confusing to use the resource as the visible name on the remote device. Particular in some cases where the user may have several phones all running the xmpp client, there is no way to differentiate between 'Mobiles' if you just use a category style name.

**Comment by licaon-kter** [comment]
`OMEMO is an XMPP Extension Protocol (XEP) for secure multi-client end-to-end encryption.`

Not using it?

**Comment by markwaters** [comment]
@licaon-kter My XMPP server uses 4096bit SSL and we are both users of it so I didn't think it was necessary , if I communicate with others 'off-server' then I would use OMEMO.

How would this extra encryption layer be related to the XMPP resource usage issue ?

**Comment by licaon-kter** [comment]
`multi-client` is the focus for OMEMO (here and in general), aka if I send you something you will get it (everywhere) no matter what device is connected (now).
