### ISSUE TITLE
Warn about old versions (<1.16) not able to read changed encryption

### ISSUE THREAD

**Issue by azrdev** [siacs/Conversations#2520]
See https://github.com/dino/dino/issues/109#issuecomment-310390809 (highlights by me): 
> @mweinelt There was a ***breaking change in the way Conversations sends OMEMO messages in 1.18.0 which makes it impossible for client versions below 1.16.0 to decrypt*** the messages. Dino only supports the new version. Current conversation versions can still read both OMEMO versions, but send the new OMEMO version. Thus, if you write messages with a contact that has a Conversation version < 1.16.0, you can read their messages on your mobile but not on Dino, as it can't decrypt the messages. In that case the problem is not related to carbons, as the messages do in fact arrive.

Seems to me there should be at least a warning that users of conversations <1.16 might not be able to read messages by newer clients, and should upgrade.

**Comment by iNPUTmice** [comment]
Have a look at the changelog.
