### ISSUE TITLE
Push questions

### ISSUE THREAD

**Issue by HenkiedeHenkie** [siacs/Conversations#2524]
Sorry for not using the standard format, but my questions are not tied to a specific device or version of Conversations... I want to run my own XMPP Server, which will be based on a Tor Hidden Service. Beside that, I want to use Conversations from the F-Droid Store instead of Google Play. My question is how push will work regarding the hidden service (does Conversations support push when the certificate is self-signed) and if the F-droid version supports push messages in general. Thanks!

**Comment by iNPUTmice** [comment]
There is a FAQ entry regarding Push/Google Cloud Messaging and there is this [The State of Mobile XMPP in 2016](https://gultsch.de/xmpp_2016.html) clearing up misconceptions behind 'Push'.

**Comment by HenkiedeHenkie** [comment]
So, to make a long story short: the self-signed cert will not work as this will not allow for a signed TLS connection between my server and that of Conversations and the F-droid version doesn't support push at all, due to the absence of GCM, so this will never work? Thanks!
