### ISSUE TITLE
How to Change image stanza request 

### ISSUE THREAD

**Issue by jyotisolanki** [siacs/Conversations#2525]
Hello,

i have to pass stanza in my code like in this below format:

`     <message type="set" id="ANY_ID_NAME" from="919586082989@abc.com" to="919033301266@abc.com" chattype="singlechat"><data xmlns="http://jabber.org/protocol/ibb" seq="1" sid="i781hf64">imgdata</data><timestamp>2017-06-16 17:08:37</timestamp><mediatype>image</mediatype></message>`

how will i able to do because i am not getting the stanza request sending class not getting proper function from where did i edit code.

As in code i found this function from which stanza string generate : 

```
private synchronized void sendPacket(final AbstractStanza packet) {
		if (stanzasSent == Integer.MAX_VALUE) {
			resetStreamId();
			disconnect(true);
			return;
		}
		synchronized (this.mStanzaQueue) {
			tagWriter.writeStanzaAsync(packet);
			if (packet instanceof AbstractAcknowledgeableStanza) {
				AbstractAcknowledgeableStanza stanza = (AbstractAcknowledgeableStanza) packet;
				++stanzasSent;
				this.mStanzaQueue.append(stanzasSent, stanza);
				if (stanza instanceof MessagePacket && stanza.getId() != null && getFeatures().sm()) {
					if (Config.EXTENDED_SM_LOGGING) {
						Log.d(Config.LOGTAG, account.getJid().toBareJid() + ": requesting ack for message stanza #" + stanzasSent);
					}
					tagWriter.writeStanzaAsync(new RequestPacket(this.smVersion));
				}
			}
		}
	} 

```

2)   and also found this function in XmppConnection class . as is this is correct method which i found

```
private void sendStartStream() throws IOException {
		final Tag stream = Tag.start("stream:stream");
		stream.setAttribute("to", account.getServer().toString());
		stream.setAttribute("version", "1.0");
		stream.setAttribute("xml:lang", "en");
		stream.setAttribute("xmlns", "jabber:client");
		stream.setAttribute("xmlns:stream", "http://etherx.jabber.org/streams");
		tagWriter.writeTag(stream);
	}
```

Please suggest me how did i change my image stanza request which i posted above.

**Comment by iNPUTmice** [comment]
This is a bug tracker not a support forum for general questions.
