### ISSUE TITLE
Push Follow-up...

### ISSUE THREAD

**Issue by HenkiedeHenkie** [siacs/Conversations#2526]
Sorry for creating a new issue (will be the last one) but as you closed my previous issue, I had no possibility to ask any follow-up question. As for the docs toy referenced to, just to confirm, the self-signed cert will not work as this will not allow for a signed TLS connection between my server and that of Conversations and the F-droid version doesn't support push at all, due to the absence of GCM, so this will never work? 

Will the only solution be to ditch the Hidden Service plan and configure my server to use a CA signed certificate instead, so I can use the F-droid client and make use of push? Sorry for the inconvenience but you're a great help Daniel!

**Comment by iNPUTmice** [comment]
the Conversations will accept self signed certificates. But of course not
call back to a Tor hidden service.
It is important to understand that you don't need GCM.
And no the fdroid version will of course not work.
