### ISSUE TITLE
OMEMO: No notification if receiving OMEMO encrypted message on Android 6

### ISSUE THREAD

**Issue by kafisc** [siacs/Conversations#2528]
#### General information

Version: 1.18.5
Device: Nexus 4
Android Version: Android 6.0 Cyanogenmod
Server name: prosody
Server software: prosody trunk
Installed server modules: "mod_post_msg"; "carbons";"smacks";"admin_web";"mam";"http_upload";"pinger";"smacks_noerror";"delay";"measure_cpu";"csi";"offline";"compression";"csi_battery_saver";

Conversations source: F-Droid

#### Steps to reproduce

1. Send OMEMO encrypted message from Smartphone 1 (Conversations from Android 7) to Smartphone 2 (Conversations from Android 6). Conversations shows that the message is not received on Smrtphone 2 (now green checkmark is displayed).
2. Nothing happenes, if I open Conversation, then the message is showing up.
3. If try the same with OTR-encryption, the message notification is displayed properly and also the green chekmark is displayes on smartphone 1.

#### Expected result

A notification for a new message

**Comment by iNPUTmice** [comment]
> csi_battery_saver

holds back your omemo messages because they don't have a body.
