### ISSUE TITLE
Image sharing issue

### ISSUE THREAD

**Issue by jyotisolanki** [siacs/Conversations#2529]
Hello,

While using conversation app when i am sharing image from android to ios app , the image is not receiving at ios end and as also when i share image from conversation app to other chat application the image not receiving.

Is there any possibility to get working on this type of problem.?

**Comment by licaon-kter** [comment]
Please fill the required info: Android version? Conversations version? Source of the app? Server used?

**Comment by jyotisolanki** [comment]
Checking image sharing with
Android version : 5.0 or above 
Conversations version : I am using latest version of conversation apk
Source of the app : Download the source form this github repository 
Server used : I am using ejabbered server for chat and eJabbered version is 16.09

**Comment by iNPUTmice** [comment]
> Is there any possibility to get working on this type of problem.?

Yes. Feel free to start working on this.
