### ISSUE TITLE
Registration not working in android 4.4 versions, but working in android above 5.0

### ISSUE THREAD

**Issue by ThameemAK** [siacs/Conversations#2530]
#### General information

* **Version:** 1.18.5
* **Device:** HTC Desire
* **Android Version:** 4.4.2
* **Server name:** Openfire
* **Server software:** Openfire 4.1.4
* **Installed server modules:** 
* **Conversations source:** Tag 1.18.5

#### Expected result

Registration in openfire.

#### Debug output
Jid Not register in server.

java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

TLS connection established
xml parser mishandled SSLProtocolException(Read error: ssl=0x8199a3d8: Failure in SSL library, usually a protocol error)
not changing status to CONNECTING because thread was interrupted
````

Is there any way auto accept the certificate rather than accepting every time?

**Comment by licaon-kter** [comment]
Did you read #2249 and all the other issues pertaining to Openfice 4.1.4?

**Comment by ThameemAK** [comment]
Ya i read this #2249

I tried disabling it through Server Settings > Client Connection > Advanced
configuration and then unchecked SSLv3, but nothing happened.

Am using Java 1.8 only as **answered** in this link https://community.igniterealtime.org/thread/58030 

Is there any way to accept certificate like this Xabber client 

 if (SettingsManager.securityCheckCertificate()) {
                SSLContext sslContext = SSLContext.getInstance("TLS");
                MemorizingTrustManager mtm = new MemorizingTrustManager(Application.getInstance());
                sslContext.init(null, new X509TrustManager[]{mtm}, new java.security.SecureRandom());
                builder.setCustomSSLContext(sslContext);
                builder.setHostnameVerifier(
                        mtm.wrapHostnameVerifier(new org.apache.http.conn.ssl.StrictHostnameVerifier()));
            } else {
                TLSUtils.acceptAllCertificates(builder);
                TLSUtils.disableHostnameVerificationForTlsCertificicates(builder);
            }

**Comment by iNPUTmice** [comment]
Conversations does have the ability to to trust self signed certificates if that's what you are asking.

**Comment by ThameemAK** [comment]
How to disable the TLS encryption? 

mAccount.setOption(Account.OPTION_USETLS, false);

I used the above code to disable TLS but its not working.

How to do this?

**Comment by licaon-kter** [comment]
> How to disable the TLS encryption?

Edit [Config.java:46](https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/Config.java#L46) to `true`

**Comment by ThameemAK** [comment]
ALLOW_NON_TLS_CONNECTIONS = true

After changed the to true, it still asking to accept the certificate.

How can i connect to server without accepting the certificate?

**Comment by iNPUTmice** [comment]
This is a bug tracker for Conversations. Not a support forum on how to do Android software development.
