### ISSUE TITLE
HTTP Upload does not use specified onion connect address for delivering files.

### ISSUE THREAD

**Issue by Ashaman-** [siacs/Conversations#2531]
#### General information
When sending a file via HTTP Upload with TOR enabled and an onion address specified for the connect server, the connection for the file upload occurs via a TOR exit node rather than the onion connect address specified in conversations. 
The hidden service is configured to relay traffic to ejabberd listening ports, including http upload.

* **Version:** Newest
* **Device:** Unknown
* **Android Version:** Unknown
* **Server name:** psyberia.im (self-hosted, federated server)
* **Server software:** ejabberd 17.04
* **Installed server modules:** XEP-0163, XEP-0191, XEP-0198, XEP-0237, XEP-0280, XEP-0313, XEP-0352, XEP-0363
* **Conversations source:** Sending side - F-Droid, Receiving side - play store

#### Steps to reproduce

1. Set 'hide_sensitive_log_data: false' in ejabberd settings for debugging purposes 
2. Enable TOR in Conversations and connect to a server that supports XEP-0363 via onion connect address.
3. Send file to buddy with OMEMO encryption set.
4. Observer ejabberd log file:
 [info] <0.340.0>@ejabberd_listener:accept:311 (<0.6790.1>) Accepted connection ::FFFF:216.218.222.13:20218 -> ::FFFF:Public.IP.of.server:5443
5. Verify that 216.218.222.13 is a TOR exit node at https://torstatus.blutmagie.de/

#### Expected result

HTTP Upload connection for file transfer should be accepted from TOR daemon running hidden service, not a tor exit node.

#### Debug output

I do not have access to the sending device to produce this information.

**Comment by iNPUTmice** [comment]
without access to the logs I can only guess but it seems that ejabberd is not handing out `.onion` HTTP upload slots.

**Comment by Ashaman-** [comment]
That makes perfect sense, actually. Closing the issue. Thank you for the quick response!
