### ISSUE TITLE
Proposal of Feature: AdHoc commands

### ISSUE THREAD

**Issue by mightyBroccoli** [siacs/Conversations#2532]
I really love the conversations app and bought it in the AppStore to support its development.
But I have one big issue with it. 
I am running prosody with some adhoc modules installed, to trigger and invite link or stuff like that.
Will there be support within conversations to support adhoc commands? Or am I even stupid and missed this feature?
I am running the latest version from the AppStore with Prosody 0.10 nightly.

**Comment by iNPUTmice** [comment]
This is not within the scope of this project. Conversations is an IM client. Not a tool for system administrators.

**Comment by mightyBroccoli** [comment]
There are many mods which use adhoc commands for the userbase. Most importantly mod invite which generates an invite link.

**Comment by dchokola** [comment]
I would like to be able to use ad-hoc commands to allow per-user configuration 
of Biboumi. This should fall within the scope of an IM client.

**Comment by ilmaisin** [comment]
I have no idea whatsoever what would make ad-hoc commands only (or even primarily) useful for sysadmins. I think they are mostly used for Transport configuration, which is an end-user task.
