### ISSUE TITLE
ejabberd room title test not shown

### ISSUE THREAD

**Issue by adahary** [siacs/Conversations#2536]
#### General information

* **Version:** eg 1.8.4
* **Device:** DOOGEE Y6, Samsung Note 5
* **Android Version:** eg Android 6.0 Stock 
* **Server name:** eg conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:**  self build (latest HEAD)

#### Steps to reproduce
1. Create muc on the ejabberd server 
ejabberdctl create_room muc1...
2. Set the muc title 
 ejabberdctl change_room_option muc1 muc.domain.com title "My Conference Room"

The Conversation app on each room member shows the pushed muc from the server but instead of the  
"My Conference Room" name/title is displays the room members jids.

When I restart 'ejabberdctl restart' I can see for a moment that the right title is being displayed but then switch back to the jid members list.

Under Settings the Conference_name is checked  but still same no desired title is displayed  (the same when uncheck) (I think this option for local created muc).

How to make the Conversation.im app to reflect the created ejabberd  muc title ?

Thanks

**Comment by iNPUTmice** [comment]
There is no setting for that. You can just switch between subject and JID.
This might change in the future but when we started out the room's subject was more frequently used than the room's name.
