### ISSUE TITLE
Force language

### ISSUE THREAD

**Issue by pannal** [siacs/Conversations#2537]
#### General information

* **Version:** 1.85.0
* **Device:** Google Nexus 5X
* **Android Version:** Android 7.1.1
* **Server name:** custom
* **Server software:** prosody

I'd like to force the language of the UI of `conversations` to English regardless of my Android system language.

**Comment by licaon-kter** [comment]
Why? If the translation is bad just fix it.

**Comment by pannal** [comment]
Because I don't want certain (chat) applications to appear in my local language. Most of the apps I use support that.

**Comment by SamWhited** [comment]
> Most of the apps I use support that.

What apps support this, out of curiosity? This isn't something I've ever seen, but I'd be curious to know and look up some examples if it's a common pattern. Thanks.

**Comment by pannal** [comment]
Signal, Settle Up, LastPass, Inoreader - were just the top of my app list.

**Comment by pannal** [comment]
TypeApp, ES File Explorer, (I think Slack), Tasker, TypeApp, Titanium Backup.

**Comment by d9h02f** [comment]
Why do you want your chat applications to appear exclusively in English? I doubt this will become an option either way because nobody would use it.

**Comment by pannal** [comment]
I don't know, I've just gotten used to that as so many of my daily driver apps support it. I like my system localized and my apps forced-english.

I guess people *would* use it, for what reason would the other app developers have implemented it, if not per user-request?

**Comment by nonegit** [comment]
You forgot Orbot :P It can change language too.
Of course many people want this. Why only local language?

Default: your system language. Can change from settings.

language = my.language;
if (my.profile.language.overrided === true)
 language = my.selected.language
endif

**Comment by licaon-kter** [comment]
In Orbot it goes back to English on restart, not a good example.

**Comment by iNPUTmice** [comment]
That's not on our todo list for now.

**Comment by subpub** [comment]
I would like to do the opposite. If I see an app that has high quality translation in my language, I turn it on. If not, no. Same for the OS vendors.

**Comment by licaon-kter** [comment]
@subpub you know that it's a volunteer stuff and you can "junt fix it yourself", right?

**Comment by subpub** [comment]
@licaon-kter I'm just adding to an issue request that was already turned down. So, just adding a voice. By your logic every issue can just be "juxt fix it yourself". Don't need be so passive aggressive. It's okay, I won't be participating anymore.
