### ISSUE TITLE
With Orbot mode enabled, try to connect it even Wifi/Mobile is turned off.

### ISSUE THREAD

**Issue by nonegit** [siacs/Conversations#2538]
Current:
Your app refuse to connect if I didn't connect to any network. But I'm using a USB network so your app
can connect to 127.0.0.1:9050.

Expected:
When asked, and Orbot mode is active, try to knock 127.0.0.1:9050. And if it is opened(= something is opened the port), try to use it. <--

**Comment by nonegit** [comment]
https://gitlab.com/fdroid/fdroidclient/issues/1099

**Comment by licaon-kter** [comment]
What's up with that F-Droid issue?

Does Conversations from F-Droid have this issue but Conversations from Google Play store does not?

**Comment by iNPUTmice** [comment]
I don't think this problem is specific to Orbot but rather your USB reverse tether not properly creating network interfaces that make Android believe that there is a network connection.

**Comment by licaon-kter** [comment]
Conversations supports running Orbot only (#1980 would be nice).

For "other proxy" (like you want) see #1930
