### ISSUE TITLE
Missing French translations

### ISSUE THREAD

**Issue by moussetc** [siacs/Conversations#2541]
Hello, 

The new version 1.19.0 is missing (at least) the French translation for "today" -> "Aujourd'hui" :)

Thank you for your work& have a nice day !

**Comment by iNPUTmice** [comment]
Translations are managed on transifex. Looks like the respective translators hasn't submitted translations in time.

**Comment by moussetc** [comment]
Hi, thanks for your quick answer ! If I got this right, the release is made whether the translators are done or not, but are the translators part of the project team or can anyone contribute ? If I want a complete French translation, do I have to do it myself, or just wait ? ;)

**Comment by iNPUTmice** [comment]
Yes the release is made no matter what. (We can't wait for 20+ languages to be translated by volunteers)

And yes you can contribute yourself: https://www.transifex.com/siacs/conversations/dashboard/ not sure if the current translators are still active.
