### ISSUE TITLE
Feature Request: Set status message when "Away when screen is off" is set

### ISSUE THREAD

**Issue by DavidRabel-b1** [siacs/Conversations#2544]
#### General information

* **Version:** eg 1.19.0

#### Feature request

When option "Away when screen is off" is activated, setting a status message is disabled.

It would be great to set a status message, even when this option is activated.

Regards
  David

**Comment by harshitbansal05** [comment]
@DavidRabel-b1 sorry, but I could not understand by "setting a status message". Could you please explain it to me?

**Comment by DavidRabel-b1** [comment]
In the current version of conversations I do not find how to set a status message at all. Has it been removed entirely?
In my desktop xmpp client (gajim) it is possible to set a status message. I do not know about the xmpp interna.

**Comment by licaon-kter** [comment]
Indeed, when "away when off" or "do not disturb when silent" are activated you can't change your status.

**Comment by iNPUTmice** [comment]
2.0 now lets you set the status message independently of visibility.
