### ISSUE TITLE
Hide "Unknown OTR fingerprint" and replace it with a shield icon on the first message sent

### ISSUE THREAD

**Issue by tdemin** [siacs/Conversations#2545]
Conversations actually allows you to message if the recipient's OTR fingerprint has not been verified yet. But the *"Unknown OTR fingerprint"* snackbar is always shown and it annoys the user.

The solution might be as follows:
1) Show the snackbar after a fingerprint was received (i.e. the first OTR session was initiated).
2) If user sends a message, the snackbar is hidden, but a padlock icon shown on sent messages is replaced with the one used for blind trust in OMEMO (the shield icon).

The user will know the fingerprint hasn't been verified, but he/she won't be annoyed with the snackbar being always present on the screen.

**Comment by iNPUTmice** [comment]
I won't put any more work into OTR related things.
