### ISSUE TITLE
Feature Request: Make 'Dark Theme' really dark for better appearance on OLED displays

### ISSUE THREAD

**Issue by imperators** [siacs/Conversations#2546]
I think a dark theme should be an entire dark experience. Actually the dark theme is some dark grey/light black coloured thing. On LC-displays this may be okay (since they often show black as some dark grey because of their backlight), but on OLED displays it looks poor and costs unnecessary battery power. I would like you to add an oled oriented dark theme which works with real black (oled pixel is off), very little portions of grey (contour lines) and white (text), - and light colours only in avatars and messages (e.g. pictures). The top of the screen (app's headlines and Android's time-and-notification area) should also be black, if possible.

![conversations real black](https://user-images.githubusercontent.com/30113575/28114700-36a0d16e-6702-11e7-9d37-c3292be79348.png)

**Comment by licaon-kter** [comment]
Did you read #1993 ? Or all the other *closed* issues mentioning `dark`...

**Comment by imperators** [comment]
I've read all pages of open issues and some pages of the closed ones to prevent a duplicate, but I forgot to use the search. :-/

OK, I see, there is a closed duplicate of my request. But I don't understand why not to implement the real black feature. It has many advantages, and the power savings are mentioned on the front page of the website conversations.im as a feature of the app, so it is a main goal of the developers to save energy since it is an app for mobile devices. I think it's not only a cosmetic issue but also a performance one. And it looks better. :)

**Comment by licaon-kter** [comment]
/close as duplicate

Do remember that Pull Requests have more weight ;)
