### ISSUE TITLE
Chat view scrolls automatically to the beginning of a message when clicking an link, get transfered to the browser and come back afterwards

### ISSUE THREAD

**Issue by imperators** [siacs/Conversations#2547]
#### General information

* **Version:** latest
* **Device:** Samsung Galaxy S5 Mini
* **Android Version:** Android 6.0.1
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Get a long message (especially longer than the screen height), containing a link (in the middle or end of the message, so you must scroll to see the link).
2. Click the link to view the content in the associated app (e.g. an url in the browser)
3. Come back to Conversations.

#### Expected result

I expect to see the state (mostly the scroll position of the message) it was before clicking the link. But I see the beginning of the message that was on the very top of my screen while clicking the link. This can be the same message containing the link (when following the steps above), but may also be the previous message if it is longer than the screen height and the url message is a short one.

**Comment by iNPUTmice** [comment]
This has been fixed in 2.0
