### ISSUE TITLE
DNSSEC hostname check description is misleading

### ISSUE THREAD

**Issue by TCM2** [siacs/Conversations#2548]
#### General information

* **Version:** 1.19.3
* **Conversations source:** PlayStore

#### Steps to reproduce

~~1. Be a MitM
2. redirect victim to your own IP address on the IP layer
3. present any certificate with the desired name
4. Profit~~

#### Expected result

~~Not that.~~

~~Why was this blatant security issue implemented? Getting a valid cert is easy these days. DNSSEC only protects DNS->IP address. You would also need IPsec in this case.~~

~~Please remove this security hole.~~

Edit: On further thought, I hope this isn't what this setting does and that it's just that the description is misleading. In case I am misunderstandig what this setting does, here's my interpretation of the changelog and the setting description text:

If the DNS name we requested was verified by DNSSEC, skip TLS validation and just assume that any certificate we receive is valid.

**Comment by iNPUTmice** [comment]
This is a bug tracker and not a support forum. If you have questions please use the conference room.
