### ISSUE TITLE
bug? extenend delete history to delete local inline images

### ISSUE THREAD

**Issue by WarrenBKN** [siacs/Conversations#2551]
I expected setting purge history to also purge images from gallery.  Some ofy friends are annoyed it doesn't and threaten to discontinue xmpp texting.  I bought one of them tasker and cteated two profiles to effect the desired purge.

**Comment by licaon-kter** [comment]
/duplicate of #2367 or #1474, fixed by #2368 (once merged)

Please use the search function!

**Comment by WarrenBKN** [comment]
where?  Can't find the option on mobile web

**Comment by licaon-kter** [comment]
Use Forkhub or another app.
Or go to lower right "Desktop mode"->hit back (because the dumb link sends you back to the main site for some dumb reason!?!?)-> then use the site as usual
