### ISSUE TITLE
Very high background data usage

### ISSUE THREAD

**Issue by luke-jr** [siacs/Conversations#2553]
#### General information

* **Version:** 1.18.5
* **Device:** Moto E LTE
* **Android Version:** LineageOS 14.1 (Android 7.1)
* **Server name:** self-hosted
* **Server software:** ejabberd 16.09
* **Installed server modules:** mostly defaults
* **Conversations source:** PlayStore

#### Steps to reproduce

Not sure.

#### Expected result

Normally Conversations uses very little data (the service plan it's on has 500 MB max per motnh).

#### Actual result

Over 300 MB background data used in the last week.

**Comment by iNPUTmice** [comment]
We can't help you if you don't provide an adb logcat
