### ISSUE TITLE
Images transferred over OTR often stuck at 99% and never complete

### ISSUE THREAD

**Issue by crosser** [siacs/Conversations#2554]
#### General information

* **Version:**  1.19.0
* **Device:** Sony Xperia Z3 D6603
* **Android Version:** Android 6.0.1 Stock
* **Server name:** self hosted
* **Server software:** jabberd2 2.3.4
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Use OTR and send pictures
2. Observe that some percentage get stuck and transfer never goes beyond 99%, even after explicit cancellation of transfer and resend. This does not depend on the quality of network connectivity.

#### Expected result

All pictures should get through

#### Debug output

attached

[convers.file.txt](https://github.com/siacs/Conversations/files/1153945/convers.file.txt)

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
Is it specific pictures that repeatedly don't go through while others work?

**Comment by crosser** [comment]
It seems that those are specific files. Anyway attempt to resend the same file usually(?) fails over again. I can try to get hold of one if I can and then I attach it here.

**Comment by crosser** [comment]
Here is one file that cannot pass through: ![file that cannot pass](https://user-images.githubusercontent.com/1404921/28312143-5d12b25e-6bb2-11e7-9baf-2074d151cf69.jpg) It is the copy that is already scaled down by conversations on the sending side.
@iNPUTmice , please remove the file from github after you've downloaded it.

**Comment by iNPUTmice** [comment]
This is fixed in 2a198793b1fac99b30553262ae89b41f0900d07e. Will be made available with 1.20.0

Note that if you install 1.20.0 it will break OTR encrypted jingle file transfer with everything below 1.20.0

By the way: You are one of the few remaining people to use OTR encrypted file transfer with ibb jingle. You should consider installing HTTP upload on your server or at least enable a file transfer proxy. File transfers don't have take ages.

**Comment by crosser** [comment]
Thanks!
I have http upload server (from siacs) installed, and it works for unencrypted conversations. But OTR insists on using ibb for whatever reason... (Now if I could make OMEMO work with my correspondent... but this is a different problem.)
