### ISSUE TITLE
OTR messages sent after switch of connectivity (WiFi/Cellular) often stuck in "waiting"

### ISSUE THREAD

**Issue by crosser** [siacs/Conversations#2555]
#### General information

* **Version:** 1.19.0
* **Device:** Sony Xperia Z3 D6603
* **Android Version:** Android 6.0.1 Stock
* **Server name:** self hosted
* **Server software:** jabberd2 2.3.4
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Use OTR.
2. Send messages regularly, while moving between WiFi and cellular covered areas.
3. Observe that sometimes, messages that you send after entering WiFi covered area got stuck in "waiting" indefinitely.
4. More messages that you send also stay in "waiting" state.
5. Reconnect to the server ("disable" then "enable" the account in "Manage accounts") and observe all waiting messages get delivered and confirmed with green mark in a few seconds.

#### Expected result

Messages should be delivered (or failed) without the need to manually reconnect to the server.

#### Debug output

It is not easy to get, it does not happen every time. But I can try to catch the problem in `adb log` if requested.

#### Note

Could it have the same root cause as the issue #2554 ?

**Comment by iNPUTmice** [comment]
You should really switch to OMEMO. OTR is unreliable by design and I'm not planning on investing more time into finding work arounds for OTR.

**Comment by crosser** [comment]
@iNPUTmice, what would be a right place to ask for help in troubleshooting OMEMO?
