### ISSUE TITLE
Conversations >= 1.19.0 will not downgrade to IPv4 if unable to connect via IPv6

### ISSUE THREAD

**Issue by bowlofeggs** [siacs/Conversations#2556]
Hello!

I recently learned (thanks to @iNPUTmice) that my ejabberd server wasn't configured to listen on IPv6. Unfortunately I did not realize this for years and had given it AAAA records. I never experienced problems that I noticed so I thought everything was fine until I upgraded to Conversations 1.19.0. Starting with that version, it seems that Conversations does not attempt to connect to IPv4 if IPv6 fails to connect. When I downgraded to 1.18.5 I was able to connect again.

While this was most certainly a problem with my chat server configs in the end, I would suggest that it would be good to restore the old fallback behavior. There is at least one network that I sometimes connect to that has IPv6 but does not globally route (weird, I know). On that network, Conversations would not be able to connect on IPv6 and would not fall back to IPv4 like it used to.

I know this is a weird use case, so I won't be upset if it gets closed as wontfix (and how could I be upset at open source software anyway ☺). I just wanted to pitch the idea and mention that there was a slight feature regression in 1.19.0 (if you consider this a feature).

**Comment by iNPUTmice** [comment]
If you set up your SRV records properly (do not point it to a cname) it
will try both.
