### ISSUE TITLE
getting this "This conference is members only" error when login with multiple devices with same account

### ISSUE THREAD

**Issue by Nits2407** [siacs/Conversations#2557]
#### General information

    Version: 1.19.0
    Device: Android Emulator
    Android Version: Android 6.0
    Server name: jabber.ru
    Server software: ejabberd
    Conversations source: self build (at 1.13.6 release commit)

#### Steps to reproduce

    

- Login to device
-     Start chat
-     Login with another device with same account
-     After succesfully logged in shows This conference is members only

#### Expected result

What is the expected output? What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by d9h20f** [comment]
Conversations 1.13.6 was released more than a year ago.

**Comment by iNPUTmice** [comment]
This message is generated by the conference server.
