### ISSUE TITLE
Forbid automatic OOB downloads from servers other than HTTP upload server

### ISSUE THREAD

**Issue by labdsf** [siacs/Conversations#2558]
Bug #2462 mentions that plain URLs are not downloaded automatically for security reasons.

Still, nothing prevents from manually constructing a message similar to:
```
<message to="user@jabber.example.com" type="chat">
<body>http://tracker.example.com/tracker.gif</body>
<x xmlns='jabber:x:oob'><url>http://tracker.example.com/tracker.png</url></x>
</message>
```
or the same without body. In both cases Conversations with default parameters tries to automatically download the file, leaking user IP to any "trusted" (as in [Message.trusted()](https://github.com/siacs/Conversations/blob/74cde1d60a9f1ec2110060868bdf63ba65b9139a/src/main/java/eu/siacs/conversations/entities/Message.java#L575)) user. This also happens in MUC.

However, [XEP-0363](https://xmpp.org/extensions/xep-0363.html) does not provide any way to determine which host is the upload server, it can even provide different hosts for different slots.
There are several solutions:
1. Automatically trust all subdomains of XMPP server
2. Ask user if he trusts any additional service and remember choice
3. Extend XEP-0363 to provide a list of trusted download domains during discovery.

What do you think?

**Comment by iNPUTmice** [comment]
The security implications of HTTP upload are comparable to those of Jingle. If you don't like them you can disable automatic file download by setting the file size to 0 in the the settings.
