### ISSUE TITLE
Tor without Orbot?

### ISSUE THREAD

**Issue by HenkiedeHenkie** [siacs/Conversations#2559]
Is there any way I can use Tor in combination without Conversations without requiring Orbot (and so root)? Looking at Chatsecure for iOS, they provide a "Enable Tor" option when connecting or setting up an account on a server that supports a Tor hidden service connection... 

When providing Conversations with a hostname that is a .onion address, it says that it can't find the server. Is this expected behaviour?

**Comment by iNPUTmice** [comment]
This is a bug tracker. If you have questions please use the group chat on [`xmpp:conversations@conference.siacs.eu?join`](https://conversations.im/j/conversations@conference.siacs.eu)

**Comment by crosser** [comment]
except the group chat does not work, does it? So where would one troubleshoot the malfunction of the troubleshooting forum?
![chatroom-2017-07-21-10-22-19](https://user-images.githubusercontent.com/1404921/28455710-41e5a3b0-6e00-11e7-868f-86e8b9c1aa5e.png)

**Comment by iNPUTmice** [comment]
@crosser this is your server blocking access to the conference. So I don't know where you would troubleshoot that… Probably your server admin? Or, you know, unblock the conference?!

**Comment by crosser** [comment]
Oops, I forgot that every conference server needs a special entriy in the privacy table :( Sorry.
