### ISSUE TITLE
Conversations no longer sends fallback body.

### ISSUE THREAD

**Issue by GigabyteProductions** [siacs/Conversations#2560]
#### General information

* **Version:** 1.19.3
* **Device:** Google Pixel XL
* **Android Version:** Android 7.1.2 LineageOS 14.1
* **Server name:** self hosted
* **Server software:** ejabberd 16.09
* **Installed server modules:** mod_adhoc mod_announce mod_blocking mod_caps mod_carboncopy mod_client_state mod_configure mod_disco mod_http_bind mod_last mod_muc mod_offline mod_ping mod_privacy mod_private mod_proxy65 mod_pubsub mod_roster mod_shared_roster mod_stats mod_time mod_vcard mod_version mod_http_upload
* **Conversations source:** self build (refs/tags/1.19.3)

#### Steps to reproduce

1. Enable logging of message stanzas (I use XMPP Console in Pidgin with [carbons](https://github.com/gkdr/carbons/) installed).
2. Send an OMEMO encrypted message to a contact.

#### Expected result

<pre>
&lt;message from='...' to='...' type='chat' id='...'&gt;
	<b>&lt;body&gt;I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo&lt;/body&gt;</b>
	&lt;encrypted xmlns='eu.siacs.conversations.axolotl'&gt;
...
	&lt;/encrypted&gt;
	&lt;store xmlns='urn:xmpp:hints'/&gt;
	&lt;encryption xmlns='urn:xmpp:eme:0' name='OMEMO' namespace='eu.siacs.conversations.axolotl'/&gt;
&lt;/message&gt;
</pre>

#### Additional information

I suspect it might be caused by https://github.com/siacs/Conversations/commit/2803d342e1f008217aa6f003d917423b6e6e106b

Why is the `Config.supportUnencrypted()` check even here? This is not an unencrypted version of the same message. However, it appears that it is intended to always return true, as the logic in [src/main/java/eu/siacs/conversations/Config.java](https://github.com/siacs/Conversations/blob/1.19.3/src/main/java/eu/siacs/conversations/Config.java#L10) effecitvely results in `X=1; if (((X | Y) & X) != 0) return true;` (more specifically to the file: `if ((15 & 1) != 0)`, or `if (1 != 0)`, effectively `if (true)`).

**Comment by iNPUTmice** [comment]
The fallback messages is only include if there are clients currently online that do not support OMEMO.

And yes as you rightly pointed out supportUnencrypted() always return true. Thus the commit you referenced has not changed the behavior.

**Comment by GigabyteProductions** [comment]
I had a suspicion it was based on the OMEMO support of the clients, so I disabled OMEMO in one of my clients, and started another client that never supported it in the first place. Body tags are still not being sent.

Also, is this list of clients based on presence notifications?

**Comment by iNPUTmice** [comment]
The fallback message is now always being included.
