### ISSUE TITLE
Feature request: Port to PC

### ISSUE THREAD

**Issue by r57zone** [siacs/Conversations#2562]
It would be great to see this program for PC.

**Comment by licaon-kter** [comment]
Gajim and https://swift.im/ are not enough?

/Close as invalid

**Comment by r57zone** [comment]
Conversations are a modern, convenient client, and there are today for pc's obsolete.

**Comment by iNPUTmice** [comment]
There is no such thing as 'porting' an App from Android to PC or vice versa.
This would mean a complete rewrite.

**Comment by silberzwiebel** [comment]
@r57zone have a look at https://github.com/dino/dino
