### ISSUE TITLE
accept donations from liberapay

### ISSUE THREAD

**Issue by silberzwiebel** [siacs/Conversations#2563]
[Liberapay](https://liberapay.com/) is a platform for recurrent donations. Other than one-time donations, these donations are something you can count on on a regular basis.

I do think you are making a great job and you helped me to be able to communicate with friends and family using only free, self-hosted software. Thanks!

To show my support [I promised to donate the siacs team 0,25€](https://liberapay.com/on/github/siacs) (or should this be directly going to @iNPUTmice?). I know, this is not much, but what if every user of Conversations paid this amount every week?

Please consider to register Conversations on liberapay to accept the donations from me and other grateful users.

**Comment by iNPUTmice** [comment]
Hi. Thank you for your offer.
Unfortunately it is not very economical to be on every single donation platform.
For EU and especially German citizens who want to donate regularly I suggest setting up a recurring bank transfer. This cuts out any middle man. I'll give out my bank details if you send me [an email](https://gultsch.de). (I'm working on a way to publish this on my homepage directly.)
For more privacy aware option there is bitcoin and to a degree flattr or PayPal.  (You do have your full name on your website though :-) )

**Comment by silberzwiebel** [comment]
Alright, I get your point.

Just some thoughts:
- flattr takes 10% fee, liberapay takes only 0.6 % for bank transfer (a
bit more for credit cards, ~2.2 %, but still way less than flattr)
- liberapay is non-profit; flattr is (I guess) for-profit, so they are
earning money that is intended for other people (the same goes for
paypal, etc.)
- using liberapay makes it easier for donors, as donations are only
single clicks in contrast to setting up a recurring bank transfer
- liberapay strengthens the community, as projects are searchable (not
sure for flattr, as a non-member, I couldn't do this)

If I convinced you, feel free to sign up at liberapay. Otherwise I'll
write you an e-mail later.

**Comment by silberzwiebel** [comment]
Great that you've changed your mind :)
I've just canceled my bank transfer and my pledge to the siacs team and instead start donating via your [liberapay profile](https://liberapay.com/iNPUTmice/). You might want to add a badge to the github README and to the F-Droid app, too: https://f-droid.org/2018/03/02/liberapay-support.html

**Comment by tuxayo** [comment]
@iNPUTmice Thanks a lot for taking donations through this libre and very convenient way.
You might also want to link the organizational account, because some people are finding it and pledging donations to it instead of your personal account. https://liberapay.com/on/github/siacs

You can link it from the pledge page. Not sure if one can link two GitHub accounts though.
