### ISSUE TITLE
"Quiet hours" depends on the current time-zone

### ISSUE THREAD

**Issue by n00bus** [siacs/Conversations#2565]
#### General information

* **Version:** 1.19.5
* **Device:** Jiayu G2, Lenovo A820
* **Android Version:** Android 4.x Stock
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Set Quiet Hours 21 to 7 in options.
2. Change current time zone to current+2.
3. Quiet Hours changed to 23 to 9 in options.

#### Expected result

~~In my opinion Quiet Hours shouldn't depend on the current time zone, they should be fixed (constant).~~ Thanks.
UPD1: thanks to **d9h20f**. It seems to be a cosmetic issue (though i'm not sure). In options "quiet hours" should be shown in local time without applying offsets. Now tz difference applies - and (for example) instead of 9pm user can see 11:30pm when he moves to +2,5 time zone.

**Comment by d9h20f** [comment]
What's wrong here? If you set quiet hours from 19 to 7 and travel to the other side of the world, do you want to receive no notifications during the day and wake up in the middle of the night because someone's sending you messages?

**Comment by n00bus** [comment]
**d9h20f**, are you sure you reproduced those steps and saw the result?

**Comment by n00bus** [comment]
I mean, first thing that i do when i come to different time zone - i change time zone to proper one. I believe that by default (but i prefer to change manually) - it's changed automatically. In current situation if you set to 19 to 7 and go to +2,5 timezone from your place - you'll get 21,5 to 9,5 automatically. So you described current situation.

**Comment by d9h20f** [comment]
Oh, then the problem is opposite of what you described: quiet hours don't follow timezone changes, but they should.

**Comment by n00bus** [comment]
sorry, can't understand your logic. but i think it's a terminology difference only.
according to my understanding: when you set 9, it shouldn't be connected with utc with offsets. 9 should be 9 always. but now qh are seem to be in utc and depend on tz-offset.
so description seems to be ok.

**Comment by n00bus** [comment]
but ok, it depends on the comparison format inside the application. my description was from the user interface point of view.

**Comment by n00bus** [comment]
Calendar.getInstance().getTimeInMillis() gives us time in utc, so maybe it's just a cosmetic issue.

**Comment by iNPUTmice** [comment]
I don't use Quite Hours myself but I'd welcome a PR for this.
