### ISSUE TITLE
After srv record set up tls negotiation failed

### ISSUE THREAD

**Issue by pworldx** [siacs/Conversations#2567]
General information

Version: 1.19
Device: One plus one, Google Nexus 9
Android Version: LineageOS 14.1 on Nexus 5, Android 7.1.1 on Nexus 9
Conversations source: F-Droid
Steps to reproduce

It was working fine when I connected to direct ejabberd server i.e xmpp1.stcollege.com but after src record its saying tls negotiation failed
I expect to successfully connect to the server, but instead I get a security error. The TLS negotiation failed, no peer certificate,tls certificate failed. see debug output. Opening stcollege.com in browser app with https works without problems.

Debug output

07-28 17:18:36.468 14996-7549/eu.siacs.conversations D/conversations: Resolver: [Result{ip='35.185.115.216', hostame='xmpp1.stcollege.com', port=5222, directTls=true, authenticated=false, priority=0}, Result{ip='104.196.3.62', hostame='xmpp2.stcollege.com', port=5222, directTls=true, authenticated=false, priority=0}]
07-28 17:18:36.468 14996-7549/eu.siacs.conversations D/conversations: bxncv@stcollege.com: using values from dns xmpp2.stcollege.com/35.185.115.216:5222 tls: true
07-28 17:18:36.748 14996-14996/eu.siacs.conversations D/AbsListView: Get MotionRecognitionManager
07-28 17:18:37.129 14996-7549/eu.siacs.conversations W/System.err: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
07-28 17:18:37.139 14996-7549/eu.siacs.conversations W/System.err:     at com.android.org.conscrypt.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:146)
07-28 17:18:37.139 14996-7549/eu.siacs.conversations W/System.err:     at de.duenndns.ssl.MemorizingTrustManager$MemorizingHostnameVerifier.verify(MemorizingTrustManager.java:803)
07-28 17:18:37.149 14996-7549/eu.siacs.conversations W/System.err:     at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:392)
07-28 17:18:37.169 14996-7549/eu.siacs.conversations W/System.err:     at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:505)
07-28 17:18:37.169 14996-7549/eu.siacs.conversations W/System.err:     at java.lang.Thread.run(Thread.java:841)
07-28 17:18:37.199 14996-7549/eu.siacs.conversations D/conversations: bxncv@stcollege.com: TLS certificate verification failed
07-28 17:18:37.199 14996-7549/eu.siacs.conversations D/conversations: bxncv@stcollege.com: Socket is closed(java.net.SocketException)
07-28 17:18:37.199 14996-7549/eu.siacs.conversations D/conversations: bxncv@stcollege.com: using values from dns xmpp1.stcollege.com/104.196.3.62:5222 tls: true
07-28 17:18:37.839 14996-7549/eu.siacs.conversations W/System.err: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
07-28 17:18:37.839 14996-7549/eu.siacs.conversations W/System.err:     at com.android.org.conscrypt.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:146)
07-28 17:18:37.839 14996-7549/eu.siacs.conversations W/System.err:     at de.duenndns.ssl.MemorizingTrustManager$MemorizingHostnameVerifier.verify(MemorizingTrustManager.java:803)
07-28 17:18:37.839 14996-7549/eu.siacs.conversations W/System.err:     at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:392)
07-28 17:18:37.839 14996-7549/eu.siacs.conversations W/System.err:     at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:505)
07-28 17:18:37.839 14996-7549/eu.siacs.conversations W/System.err:     at java.lang.Thread.run(Thread.java:841)
07-28 17:18:37.839 14996-7549/eu.siacs.conversations D/conversations: bxncv@stcollege.com: TLS certificate verification failed

**Comment by licaon-kter** [comment]
1.19 or 1.19.5 ?

**Comment by pworldx** [comment]
1.19.5

**Comment by licaon-kter** [comment]
Does that "dnssec" expert option help?

**Comment by pworldx** [comment]
I do not have dnssec set in my host.Its connected when I connected to single host.But srv record its saying failed TLS certificate verification failed

**Comment by iNPUTmice** [comment]
You set up a direct TLS srv record (xmpps) for something that is STARTTLS.
