### ISSUE TITLE
[Feature Request] Scroll to bottom floating button(like whatsapp) to reach most recent messages 

### ISSUE THREAD

**Issue by shenjun100** [siacs/Conversations#2568]
Hi ,

May consider to add a floating button(like whatsapp have this feature) that can be used to scroll to bottom when user is viewing the old messages history and user want to scroll back to bottom of message list. Also if new messages are coming in when user is viewing the history, a badge of unread message count could be shown on the floating button to notify user to scroll to bottom. 

![image](https://user-images.githubusercontent.com/16997788/28765914-b0c40b3a-75ff-11e7-8885-d31f2baa7585.png)

Thanks

**Comment by uchchishta** [comment]
>Also if new messages are coming in when user is viewing the history, a badge of unread message count could be shown on the floating button to notify user to scroll to bottom. 

#2276

**Comment by Echolon** [comment]
What additionally would be great: A marker-line which indicates where you have stopped reading the last time - it should will be visible until you read the latest message or until you leave the chat screen.
(Similar to the lines or markers which indicates a new day at 0.00 am)

**Comment by harshitbansal05** [comment]
@iNPUTmice may I work on it?
