### ISSUE TITLE
Connection(?) problems "Server not found"

### ISSUE THREAD

**Issue by Wikinaut** [siacs/Conversations#2569]
#### General information

* Conversations Google Play version 1.19.5
* HUAWEI P8 LITE with Android 6.0 and also on
* HUAWEI P8 LITE 2017 with Android 7.0

#### Problem

Since about two weeks, the servers (I use jabber.de and jabber.ccc.de) cannot be found, and this problem renders the app currently unusable. I already tried start/stopping the App, cleared the app cache and also tried a reinstallation. Nothing helps.

Any idea what could be wrong ?

Is it a regression in the Conversations App?

**Comment by iNPUTmice** [comment]
Please fill in the entire template and provide the output of adb logcat. Otherwise we can't help you.

**Comment by Wikinaut** [comment]
Problem solved (Handy war im limitierten Gastzugang eingeloggt).

**Comment by stef204** [comment]
I am having the same issue. It would be more helpful to have an explanation of the resolution of this problem.  What caused you/Conversations to be logged on as Guest? How do you check it and remedy it?
