### ISSUE TITLE
OutOfMemoryError in reconnectAccount

### ISSUE THREAD

**Issue by PeterEdens** [siacs/Conversations#2571]
I am getting OutOfMemoryError occuring in reconnectAccount in XmppConnectionService.java when it tries to start the thread:

				Thread thread = new Thread(connection);
				connection.setInteractive(interactive);
				connection.prepareNewConnection();
				connection.interrupt();
				thread.start();

It is occuring on several Android 7 devices but also some 4.4.4 devices, I suspect the thread is never terminating and being garbage collected so creating a new thread is probably not a good idea.  Something in the Run function may be blocking so it never exits and the thread is not garbage collected.  I will add a WeakReference to the thread in my fork of the code so that I can check to see if there is already a thread running for this connection, it may be a good idea to add something similar to the main branch.

**Comment by iNPUTmice** [comment]
What version of Conversations are you using?

**Comment by PeterEdens** [comment]
It is forked from 1.14.9

**Comment by licaon-kter** [comment]
9 months later, umm

**Comment by PeterEdens** [comment]
Yes I will update at some point but I just though it might be a good idea to keep track of the new Thread objects being created in the code snipet above so that they can be interrupted and garbage collected if they are still running to avoid creating too many Threads.  I have done this in my fork and am testing the fix now.
