### ISSUE TITLE
DNSSEC only works when using DNSSEC capable DNS server

### ISSUE THREAD

**Issue by msebald** [siacs/Conversations#2573]
#### General information

* **Version:** 1.20.0-beta
* **Device:** Xiaomi Mi Max Prime 128GB
* **Android Version:** Android 7.0 MIUI 8.5.1.0
* **Server name:** jabber.hot-chilli.net
* **Server software:** prosody 0.9 nightly284
* **Installed server modules:** several
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. turn on DNSSEC in expert settings
2. try to connect to XMPP server when using a DNS server with DNSSEC capability and one without
3. connection only works when DNS server understands DNSSEC

#### Expected result

DNSSEC feature is not usable as most internet providers don't offer DNS servers with DNSSEC capability. So a good feature would be to use DNSSEC if the DNS server understands, and if not, don't use DNSSEC. Or maybe give the user the choice if connecting without DNSSEC in this case should happen or not.

But at least please mention in the export settings that it only works when DNS server understands DNSSEC.

**Comment by iNPUTmice** [comment]
It works with regular DNS servers as well. Just not with some broken ones.

**Comment by msebald** [comment]
Well, it did not work with o2 mobile internet and it also did not work with an unmodified Fritzbox 7490 (newest firmware) on a standard T-DSL line.

**Comment by owhen** [comment]
@iNPUTmice Can you please give us some more information about this? What is a broken dns server for you?

**Comment by licaon-kter** [comment]
@owhen Do you have such a problem too? Details about your setup?
