### ISSUE TITLE
Feature Request: get custom notification sound from contacts

### ISSUE THREAD

**Issue by jahlives** [siacs/Conversations#2575]
#### General information

* **Version:** 1.19.5
* **Device:** Samsung S7
* **Android Version:** Android 7.0 Stock
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Add a custom notification sound to record in contact based on jabber-id

#### Expected result

Conversation should play the notification sound defined by property of corresponding contact. But instead it only plays the sound that is configured globally in Conversations settings.
Other data (like contact name) are taken from contacts but not the custom notification sound

Please eigther read custom notification sound from contact or allow to define a custom notification sound for each chat

**Comment by iNPUTmice** [comment]
I don't think contacts have custom notification sounds. They only have custom ring tones. And that's not the same. I can't play an entire ringtone when a messages arrives.

Also what @licaon-kter said.

**Comment by jahlives** [comment]
On my Android 7 I can set custom notification tones per contact based on on jabber id in case of a xmpp contact.
I mean contacts in my android system addressbook not contacts in the app (like conversations) :-)

----- Originale Nachricht -----
Von: Daniel Gultsch <notifications@github.com>
Gesendet: 05.08.2017 - 06:55
An: siacs/Conversations <Conversations@noreply.github.com>
Betreff: Re: [siacs/Conversations] Feature Request: get custom notification sound from contacts (#2575)

**Comment by iNPUTmice** [comment]
Do you have a screenshot for that? I can't find that on my Android 7.1 and I also can't find API documentation for accessing this.

**Comment by jahlives** [comment]
attached a screenshot from contact on my Android 7. "Nachrichtenton" is the custom sound for notifications for that contact.

**Comment by jahlives** [comment]
![20170805_130009](https://user-images.githubusercontent.com/5271804/28995092-8c65d460-79df-11e7-9f3c-332feff8d21a.png)
Sorry my reply via mail got the screenshot attachment cut off

**Comment by iNPUTmice** [comment]
Interesting. Seems to be a proprietary Samsung thing. Feel free to figure out how to access this from Conversations and provide a pull request. I don't have a Samsung phone myself.

**Comment by jahlives** [comment]
It seems to me that conversations already access the contact data from addressbook. So is the name of the contact taken from it if conversations find a matching jabber id in contacts.
Not so sure that I will be able to figure out how to access it from conversations but I try my best :-)

----- Originale Nachricht -----
Von: Daniel Gultsch <notifications@github.com>
Gesendet: 05.08.2017 - 13:36
An: siacs/Conversations <Conversations@noreply.github.com>
Betreff: Re: [siacs/Conversations] Feature Request: get custom notification sound from contacts (#2575)

**Comment by KlavsKlavsen** [comment]
Well.. isn't there a field for this on stock android? On LineageOS here (android 7.1) - and - when editing a contact, I can choose "in menu - upper right" - to 'set ringtone' - which is then for that contact specificly.
Oddly enough the stock contacts app does not actually show which ringtone is set.. but it should hopefully be stored and accessible by conversations?

And if so.. used by conversations when messages arrive ? or could there perhaps be an option in conversations to "use ringtone set per contact if set" ?

**Comment by d9h20f** [comment]
Those are ringtones and not IM tones as @iNPUTmice already said:
>I don't think contacts have custom notification sounds. They only have custom ring tones. And that's not the same.
