### ISSUE TITLE
Unable to parse certificate

### ISSUE THREAD

**Issue by Convers1** [siacs/Conversations#2577]
General information
Version: 1.19.5
Device: various
Android Version: 4.2.2, 4.4, 5.1, 6.0.

Conversations source: various - PlayStore, F-Droid, self build(1.19.5).

Steps to reproduce
Tap "add account with certificate", choose certificate, click "allow". 

Expected result
Certificate must import successfully. Instead I see error "unable to parse certificate". Desktop client both Gajim and SwiftIM accept certificate.
Conclusion: problem on the client side.
Question: problem already knowed or not for community? If answer yes, did developers solve it in next release? I am surprised that nobody notice the error.

**Comment by iNPUTmice** [comment]
Does your client certificate contain the jid as its common name?

**Comment by Convers1** [comment]
Yes. 
JID and Common Name are the same. Maybe, domain name must not be local ip address? I used d@10.1.1.4 account for testing. Messenger work in local net. All others functions work perfectly.
Must I launch debug in Android Studio to help you investigate error?

**Comment by iNPUTmice** [comment]
Yes adb should have some more detailed logging

**Comment by Convers1** [comment]
08-07 16:13:17.177 11815-14304/eu.siacs.conversations W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-07 16:13:17.178 11815-14304/eu.siacs.conversations W/System.err:     at eu.siacs.conversations.utils.CryptoHelper.extractJidAndName(CryptoHelper.java:165)
08-07 16:13:17.179 11815-14304/eu.siacs.conversations W/System.err:     at eu.siacs.conversations.services.XmppConnectionService$26.run(XmppConnectionService.java:1837)
08-07 16:13:17.180 11815-14304/eu.siacs.conversations W/System.err:     at java.lang.Thread.run(Thread.java:838)

**Comment by Convers1** [comment]
Attach a cert file. Password - ddd.
[ddd.zip](https://github.com/siacs/Conversations/files/1204949/ddd.zip)

**Comment by iNPUTmice** [comment]
I forgot - haven't used that in quite a while - JID has to be in the email or on of the SAN fields.

**Comment by iNPUTmice** [comment]
cce5a7b39f9ebdb54fe2838e55f5d2060acb47dd will parse the CN as well. Not sure this will work on the server side though…
