### ISSUE TITLE
non-standard aes-gcm IV length

### ISSUE THREAD

**Issue by moparisthebest** [siacs/Conversations#2578]
I was trying to implement some code compatible with this scheme in rust last night when I discovered that essentially aes-gcm always should use a 12 byte IV, not the current 16 byte IV that Conversations uses.

[NIST guidelines](http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf) say
> For IVs, it is recommended that implementations restrict support to the length of 96 bits, to
promote interoperability, efficiency, and simplicity of design.

Two [rust](https://github.com/briansmith/ring/issues/22) [libs](https://github.com/DaGenix/rust-crypto/issues/422) are hard-coded to only support 12 byte IVs.

And bouncycastle (lib Conversations uses) jumps through some [pretty large hoops](https://android.googlesource.com/platform/external/bouncycastle/+/d3dea7fcf0e206859d8df1af01523f40d8008195/bcprov/src/main/java/org/bouncycastle/crypto/modes/GCMBlockCipher.java#150) to support non-12-byte IVs.

[Stackoverflow](https://crypto.stackexchange.com/questions/41601/aes-gcm-recommended-iv-size-why-12-bytes) explains the issue fairly well if I understand it correctly.  Essentially anything greater than 12 bytes gets hashed down to 12 bytes, which increases the chance of (catastrophic) IV collisions compared to simply supplying a random 12 byte IV in the first place

So the question is, can this be fixed, and where would it need to be fixed at?  I know the gajim plugin also supports aesgcm://, anything else?  It would be easy to look at the length of the http anchor to determine IV length and support receiving both for quite awhile.  Currently the anchor is 48 bytes, meaning 16 IV and 32 key, if the anchor only had 44 bytes we could assume a 12 IV and 32 key.  If backwards compat was an issue in the near-term we could add this receiving code, and still send files with 16 byte IVs for a long enough time to be confident most everyone has upgraded.

If you can give me guidance on how you want it fixed I can write the code and issue a pull request.

Thanks!

**Comment by iNPUTmice** [comment]
Relevant code is here: https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/entities/DownloadableFile.java#L53

and here: https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/entities/Message.java#L673

(maybe other places but those are a good starting point)

However we need to do read support first and then in 6 month or a year switch the sending part over.

**Comment by moparisthebest** [comment]
@iNPUTmice is it about time to start *sending* 12 byte IVs now?  (have all other clients implemented at least read support for it by now?)

**Comment by dartraiden** [comment]
https://github.com/xsf/xeps/pull/894

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/xsf/xeps/pull/894

**Comment by Neustradamus** [comment]
Several years after, it is now solved:
- https://github.com/dino/dino/commit/cd5b639a826ccafe5741a51f10cc8ca76ebfdd14
- https://github.com/dino/dino/commit/1956f63179c4f3ac3232cc4a2da8046565fad2a1 (https://github.com/dino/dino/issues/909)

**Comment by Neustradamus** [comment]
It is now official, Dino 0.2.0 (2020-11-12) is now "good":
- https://github.com/dino/dino/issues/265#issuecomment-726389726
