### ISSUE TITLE
Recipients keep losing messages in MUCs when internet connection is unstable (presumed cause)

### ISSUE THREAD

**Issue by rojoweko** [siacs/Conversations#2579]
#### General information

* **Version:** 1.19.5 and earlier
* **Device:** Samsung Galaxy A3 (2015) and others
* **Android Version:** Android 6.0 Stock and newer
* **Server name:** trashserver.net
* **Server software:** prosody 0.9
* **Installed server modules:** Stream Managment, CSI, XMPP over TLS, PEP, Blocking, Roster Versioning, Message Carbons, HTTP File Upload, Push Notifications
* **Conversations source:** F-Droid

* **Special remark:** MAM in MUCs is not available on this server.

#### Steps to reproduce

1. Start a MUC with at least 3 participants.
2. Enable OMEMO.
3. One recipient should have an unstable internet connection (eg bad mobile connection).
4. Keep sending messages until the recipient loses a message.

#### Expected result

Expected result: All messages should be received by both recipients.
Current behavior: Sometimes messages will not be received by one recipient.

#### Debug output

Not available at the moment.

**Comment by d9h20f** [comment]
I've encountered this issue many times with MAM in MUCs enabled.

**Comment by rojoweko** [comment]
According to this thread, this is probably not related to MAM in MUCs: https://github.com/siacs/Conversations/issues/2197

**Comment by iNPUTmice** [comment]
You need MAM support for OMEMO to work. Missing MAM might not be the only cause of problems but it needs to be ruled out before debugging this issue.

**Comment by mimi89999** [comment]
@rojoweko There was an issue in Prosody, but after it got fixed, MAM MUC should work well with OMEMO now.

**Comment by Tschaeggaer** [comment]
I'm still encountering this issue on trashserver.net, MAM enabled. Prosody is 0.10, Conversations version 1.21.0.

**Comment by iNPUTmice** [comment]
Make sure you have the latest version of muc mam
