### ISSUE TITLE
OMEMO fingerprints not matching

### ISSUE THREAD

**Issue by uchchishta** [siacs/Conversations#2581]
#### General information

* **Version:** 1.20.0
* **Android Version:** Android 5.0.1 Stock
* **Device:** Micromax A106
* **Server name:** jabjab.de
* **Server software:** ejabberd version 17.01
* **Installed server modules:** not known. ComplianceTester result: https://raw.githubusercontent.com/iNPUTmice/ComplianceTester/master/reports/jabjab.de.txt
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. Attempt to register account on kuchen.io. Fails because registration is closed
2. Successfully register an account on jabjab.de
3. Add a contact, enable OMEMO, [blindly] trust keys, start chatting...
4. Contact goes to contact details (of my account) and scans my OMEMO fingerprints on both of their devices
5. On their phone the fingerprint matches and gets verified ![screenshot](https://user-images.githubusercontent.com/25387925/29065115-b4aaf354-7c48-11e7-876d-5edc09e082d1.jpg) but the one on their tab doesn't match ![screenshot](https://user-images.githubusercontent.com/25387925/29065093-a119b97e-7c48-11e7-95ec-2c8215ac4ef5.jpg) so doesn't get verified. I can see the OMEMO messages they were sending from phone and tab. I only have one device.

#### Expected result

My fingerprint to be the same on all of the devices of my contacts and to match the one I see in account details.

#### Debug output

Nothing relevant in the logs. However, I took Conversations database from my device and my contact's tab.

Relevant part of the identities table form my contact's tab:

| account								| name				| ownkey | fingerprint														  |	certificate | trusted	| key		| trust		| active | last_activation |
|:-------------------------------------:|:-----------------:|:------:|:------------------------------------------------------------------:|:-----------:|:---------:|:---------:|:---------:|:------:|:---------------:|
| e6f340c2-6432-415b-99e1-3d247dd3917c	| REMOVED@jabjab.de	| 0		 | 05cb41f0654f389982eb5b693106a55ac1a352ef9b14cf16fc3dd179238fa21377 |	null		| null		| REMOVED	| TRUSTED	| 1      | -1404445648     |
| e6f340c2-6432-415b-99e1-3d247dd3917c	| REMOVED@jabjab.de	| 0		 | 055ef2ca28426b7266aebe954cad05ca6e17e2b656df80814a94f390a73141960c |	null		| null		| null		| VERIFIED	| 0      | null            |

Relevant part of the identities table form my device:

| account                              | name              | ownkey | fingerprint                                                        | certificate | trust    | active | last_activation | key     |
|:------------------------------------:|:-----------------:|:------:|:------------------------------------------------------------------:|:-----------:|:--------:|:------:|:---------------:|:-------:|
| 8673f93c-3ee0-4122-b280-5b689d736ef9 | REMOVED@kuchen.io | 1      | 05cb41f0654f389982eb5b693106a55ac1a352ef9b14cf16fc3dd179238fa21377 | null        | VERIFIED | 1      | null            | REMOVED |
| 8673f93c-3ee0-4122-b280-5b689d736ef9 | REMOVED@jabjab.de | 1      | 055ef2ca28426b7266aebe954cad05ca6e17e2b656df80814a94f390a73141960c | null        | VERIFIED | 1      | null            | REMOVED |

**Comment by mimi89999** [comment]
The correct fingerprint (5ef2ca28426b7266aebe954cad05ca6e17e2b656df80814a94f390a73141960c) came in the tab database most likely as a result of scanning the QR code.

**Comment by iNPUTmice** [comment]
See if you can still reproduce this bug with this branch: https://github.com/siacs/Conversations/tree/recreate_axolotl_on_jid_change

Note: It won't magically fix your old setup. You will have to recreate the whole situation with that branch.

**Comment by uchchishta** [comment]
@iNPUTmice it's ok now. 👍 
`````
08-11 01:03:51.526 D/conversations(15974): REMOVED@kuchen.io: destroying old axolotl service. no longer in use
08-11 01:03:51.526 D/conversations(15974): AxolotlService REMOVED@kuchen.io): >>> WIPING AXOLOTL DATABASE FOR ACCOUNT 3bac74e5-5613-4663-8d0f-09e6db55a7b3 <<<
08-11 01:03:51.526 D/conversations(15974): REMOVED@jabjab.de: make new axolotl service
`````
Though, I would suggest it should not try to autoconnect after Xsecs if registration failed, rather when one manually clicks "Next" again.

**Comment by uchchishta** [comment]
....because 
````
 08-11 06:36:39.194 D/conversations(12411): REMOVED@kuchen.io: error connecting account. try again in 36s for the 3 time. lowPingTimeout=false 
```` 
by the time this reconnects the other account is registering... In the UI it shows `registeration not allowed` as though `jabjab.de` does not allow it.. (Corrects it at next try)

**Comment by mimi89999** [comment]
@iNPUTmice Thanks
