### ISSUE TITLE
OTR security bug?

### ISSUE THREAD

**Issue by trin467** [siacs/Conversations#2582]
Version: 1.19.5
Steps to reproduce
1. Create Account1@conversations.im.
2. Create Account2@conversations.im.
3. Login to Account1 on Device1 with XMPP resource as Android.
4. Login to Account2 on Device2 with XMPP resource as Android.
5. Start OTR chat on Device2 from Account2 to Account1.
6. Verify OTR fingerprints on Device1 and Device2.
7. Continue chat on Device1 and Device2.
8. Login to Account2 on Device3 with XMPP resource as Conversations.
9. Start OTR chat on Device3 from Account2 to Account1.
10. Not verify OTR fingerprint.
11. Continue chat on Device1: messages are sending to Account2 with nonverified fingerprint on Device3 but no to Account2 with verified fingerprint on Device2.

**Comment by iNPUTmice** [comment]
Please use OMEMO if you can. The trust model is superior and it can deal with multiple devices.

**Comment by trin467** [comment]
No, I want to use OTR.
What's problem to realize sending messages only to verified devices?
But in Conversations in OMEMO mode is there no notifications about new devices on my accounts.

**Comment by iNPUTmice** [comment]
> What's problem to realize sending messages only to verified devices?

Nothing in particular. Feel free to implement it. (OTR related development has been discontinued in favor of OMEMO)

**Comment by trin467** [comment]
But in this case it's open security bug that must know everything, isn't it?

**Comment by iNPUTmice** [comment]
OTR in Conversations behaves similar to other OTR implements on a trust everything approach. (And print a warning dialog on unverified sessions). If you want a trust before sending model use OMEMO and disable BTBV.

**Comment by trin467** [comment]
OTR is a very security time-tested protocol for one-to-one communications.
> And print a warning dialog on unverified sessions
>
Not seen. When it should appear?

> If you want a trust before sending model use OMEMO and disable BTBV.
>
But if I want guaranteed one-to-one correspondence?
Again, in Conversations not even a notification when new device connect to my account.

**Comment by iNPUTmice** [comment]
> Again, in Conversations not even a notification when new device connect to my account.

disable BTBV to get that warning. Please take further questions to the conference room. This is a bug tracker and not a support forum.
