### ISSUE TITLE
No notifications about new connected devices in IMEMO

### ISSUE THREAD

**Issue by trin467** [siacs/Conversations#2583]
#Version: 1.19.5
Steps to reproduce
1. Create Account1@conversations.im.
2. Create Account2@conversations.im.
3. Login to Account1 on Device1.
4. Disable Blind Trust Before Verification on Account1.
4. Login to Account2 on Device2.
5. Start OMEMO chat from Account2 to Account1.
6. Verify fingerprints on Device1 and Device2.
7. Login to Account2 on Device3.
8. No notificatons on Device2 with Account2 about new connected Device3 but Account1 has warning notification when Account2 on Device3 start chat.

**Comment by licaon-kter** [comment]
Why would you expect this exactly? Did I miss the README?

You should get one if you talk from Device3&Account2 to Device1&Account1, yes...
But you can't talk from Device3&Account2 to Device2&Account2... you can't talk to yourself.

**Comment by trin467** [comment]
> you can't talk to yourself.
>
It's about security.
If someone knowing my password to connect from other device I don't get notification about it.

**Comment by iNPUTmice** [comment]
The 'Trust OMEMO keys' screen will appear on the first message with that new device. Not right after it connected.

And seriously this is a bug tracker. Please take your questions to the conference.

**Comment by trin467** [comment]
> The 'Trust OMEMO keys' screen will appear on the first message with that new device. Not right after it connected.
>
Yes, in my contacts if they disable BTBV but how can I find out what connected a new device in my own account?

**Comment by iNPUTmice** [comment]
If A is your old device and B is your new device and A has disabled BTBV it will show the fingerprint of B as soon as you write the first OMEMO encrypted message from A to any contact.

**Comment by licaon-kter** [comment]
> If someone knowing my password to connect from other device I don't get notification about it

Do you get a notification from your browser when someone connects to your e-mail account? No, but you might get one from the server... 

> it will show the fingerprint of B as soon as you write the first OMEMO encrypted message from A to any contact

So your friend will ask "hey, when did **trin467** get a new phone?"... so maybe they'll call you to confirm... the whole point of BTBV...

**Comment by trin467** [comment]
> If A is your old device and B is your new device and A has disabled BTBV it will show the fingerprint of B as soon as you write the first OMEMO encrypted message from A to any contact.
>
It's obviously. I wrote this above. How even easier to explain...
On the example of Telegram. When someone connect to my account from another device I'll get a notification immediately and not wait until the new device will start to write to my contacts.
