### ISSUE TITLE
Sending multiple images at once

### ISSUE THREAD

**Issue by olerem** [siacs/Conversations#2584]
#### General information

* **Version:** 1.20.0-beta
* **Device:** Google Nexus 5
* **Android Version:** Android 6.0.1 Stock
* **Server name:** conversations.im
* **Server software:**
* **Installed server modules:** 
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. From conversation chat window choice to send an image
2. Click to  "Fotos" -> "Kamera" -> "Fotos auswählen"
3. Click on multiple images and press "Fertig" (Ready button)
4. as result only one of choice images will be send

#### Expected result
Expected that all choice image will be send.

**Comment by iNPUTmice** [comment]
I can't reproduce this. Please provide adb logcat output.

**Comment by olerem** [comment]
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
--------- beginning of system
--------- beginning of main
08-12 15:36:18.305 25273 25295 D conversations: deleted file /storage/emulated/0/Nikon_WU/Cache/Thumbnail
08-12 15:36:25.933 25273 25273 D conversations: resetting all attempt counts
08-12 15:36:25.966 25273 25273 D conversations: oxxxxm@conversations.im send ping (action=android.net.conn.CONNECTIVITY_CHANGE,lowTimeout=false)
08-12 15:36:25.977 25273 25273 D conversations: resetting all attempt counts
08-12 15:36:55.367 25273  1883 D conversations: oxxxxm@conversations.im: xml parser mishandled SSLException(Read error: ssl=0xaee34ac0: I/O error during system call, Connection timed out)
08-12 15:36:56.410 25273 25295 D conversations: deleted file /storage/emulated/0/Nikon_WU/Cache/Thumbnail
08-12 15:37:03.375 25273  3747 D conversations: oxxxxm@conversations.im: connecting
08-12 15:37:14.906 25273  3747 D conversations: Resolver: [Result{ip='5.175.28.100', hostame='xmpps.conversations.im', port=443, directTls=true, authenticated=false, priority=1}, Result{ip='92.51.148.190', hostame='xmpp.conversations.im', port=5222, directTls=false, authenticated=false, priority=5}]
08-12 15:37:14.906 25273  3747 D conversations: oxxxxm@conversations.im: using values from dns xmpps.conversations.im/5.175.28.100:443 tls: true
08-12 15:37:15.483 25273  3747 D conversations: oxxxxm@conversations.im/mobile: Authenticating with SCRAM-SHA-1
08-12 15:37:15.608 25273  3747 D conversations: oxxxxm@conversations.im: logged in
08-12 15:37:15.746 25273  3747 D conversations: oxxxxm@conversations.im: session resumed
08-12 15:37:15.746 25273  3747 D conversations: resending 0 stanzas
08-12 15:37:15.746 25273  3747 D conversations: oxxxxm@conversations.im: online with resource mobile
08-12 15:37:15.746 25273  3747 D conversations: oxxxxm@conversations.im sending csi//inactive
08-12 15:37:16.023 25273  3747 D conversations: oxxxxm@conversations.im: SM catchup complete (0)
08-12 15:38:00.569 25273 25295 D conversations: deleted file /storage/emulated/0/Nikon_WU/Cache/Thumbnail
08-12 15:39:04.766 25273 25295 D conversations: deleted file /storage/emulated/0/Nikon_WU/Cache/Thumbnail
08-12 15:39:32.092 25273 25273 D conversations: oxxxxm@conversations.im send ping (action=ui,lowTimeout=false)
08-12 15:39:32.096 25273 25273 D conversations: app switched into foreground
08-12 15:39:35.932 25273 25273 D conversations: app switched into background
08-12 15:40:23.980 25273 25295 D conversations: deleted file /storage/emulated/0/Android/data/com.google.android.youtube/cache/cache-1537244297probe
08-12 15:41:13.110 25273 25273 D conversations: oxxxxm@conversations.im send ping (action=ui,lowTimeout=false)
08-12 15:41:13.114 25273 25273 D conversations: app switched into foreground
08-12 15:41:14.783 25273 25273 D conversations: AxolotlService (oxxxxm@conversations.im): Finding devices without session for ixxxxr@conversations.im
08-12 15:41:15.326 25273 25273 D conversations: app switched into background
08-12 15:41:27.408 25273 25273 D conversations: start merging phone contacts with roster
08-12 15:41:27.481 25273 25273 D conversations: finished merging phone contacts
08-12 15:41:28.420 25273 25273 D conversations: app switched into foreground
08-12 15:41:28.442 25273 25273 D conversations: ConversationsActivity.onBackendConnected() - attaching image to conversations. stopping=false
08-12 15:41:28.500 25273 19881 D conversations: copy image (content://com.google.android.apps.photos.contentprovider/0/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F50217/ORIGINAL/NONE/1671488487) to private storage /storage/emulated/0/Conversations/Media/Conversations Images/ea258b78-4ae3-4fa3-9d49-67e79a046892.jpg
08-12 15:41:28.517 25273 19881 D conversations: reading bitmap with sample size 1
08-12 15:41:29.098 25273 19881 D conversations: send file message
08-12 15:41:29.276 25273  6798 D conversations: uploading to https://share.conversations.im/oxxxxm/QjjqFzsOpTNwkqUs/6iWLeErjT6OdSWfnmgRokg.jpg w/ read timeout of 94s
08-12 15:41:29.935 25273  6798 D conversations: finished uploading file
08-12 15:41:29.946 25273  6798 D conversations: AxolotlService (oxxxxm@conversations.im): Cache miss: ea258b78-4ae3-4fa3-9d49-67e79a046892
08-12 15:41:30.069 25273 19013 D conversations: AxolotlService (oxxxxm@conversations.im): Generated message, caching: ea258b78-4ae3-4fa3-9d49-67e79a046892
08-12 15:41:30.069 25273 19013 D conversations: AxolotlService (oxxxxm@conversations.im): Cache hit: ea258b78-4ae3-4fa3-9d49-67e79a046892
08-12 15:41:36.416 25273 25273 D conversations: app switched into background
08-12 15:41:36.673 25273 25273 D conversations: app switched into foreground
08-12 15:41:36.725 25273 25273 D conversations: setting scroll position on fragment

**Comment by annafallasktick** [comment]
I have experienced this in prior versions. It functions as expected in 1.21.0.

**Comment by iNPUTmice** [comment]
This is working since 2.2.0
