### ISSUE TITLE
Conversations does not log out from server before disconnection when disabling a connected account.

### ISSUE THREAD

**Issue by persmule** [siacs/Conversations#2585]
#### General information

* **Version:** 1.19.5
* **Device:** Google Nexus 5
* **Android Version:** Android 7.1 Resurrection Remix
* **Server name:** yax.im and chinwag.im
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Log on an account "a" with Conversations, by enabling the disabled account.
2. Log on another account "b" which has subscribed "a" (so "b" can know whether "a" is online) with another client, wait until "b" can see that "a" is online.
3. Disable the connected account "a" on Conversations.

#### Expected result

"b" is expected to be noticed that "a" has logged out, but in the view of "b", "a" remains online, until a certain amount of timeout depending on the server.

**Comment by mightyBroccoli** [comment]
Smacks should be the reason why. 
It retains the status for some time (default 5min but I am not sure) and after that time the status changes. That is to give mobile users the ability to reaccess their session if thier connection is shit or stuff like that.

**Comment by persmule** [comment]
But the status should NOT be retained when I actively disable a connected account, rather than connection is lost due to the network's poverty.

**Comment by iNPUTmice** [comment]
Does this problem persist with Conversations 1.20.1?

**Comment by persmule** [comment]
Confirm this problem solved in 1.23.3.
