### ISSUE TITLE
Cannot send GIF until allowing permission to use sd card

### ISSUE THREAD

**Issue by PeterEdens** [siacs/Conversations#2589]
#### General information

* **Version:** eg 1.19.5
* **Device:** Google Nexus 5
* **Android Version:** eg Android 7.0
* **Server name:** self hosted
* **Server software:** ejabberd 16.01
* **Installed server modules:** 
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Install the app 
2. Add a contact and try to send a GIF
3. Message about problem writing to sd card is shown

If you then send a GIF from the other contact and then allow access to the sd card you can then send a GIF back

There needs to be a check for permissions before trying to send a GIF.

**Comment by iNPUTmice** [comment]
You mean with the keyboard?

**Comment by PeterEdens** [comment]
Yes, you select to add a GIF from the keyboard and it fails to get added.
