### ISSUE TITLE
Nickname not being displayed correctly when real jid is accessible

### ISSUE THREAD

**Issue by Ppjet6** [siacs/Conversations#2590]
#### General information

* **Version:** 1.19.5
* **Device:** N/A
* **Android Version:** N/A
* **Server name:** N/A
* **Server software:** prosody-trunk
* **Installed server modules:** N/A
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Join a non-anonymous MUC where you can see real jids

#### Expected result

The displayed nicknames should be what (other) users have set.

#### What happens instead

The localpart of their jid seems to be displayed. See the example below, "linkmauve" is supposed to be "Link Mauve". Weirdly enough, the other visible user in this picture seems to be displayed correctly ("`" is not part of his jid)

![screenshot_20170820-170736](https://user-images.githubusercontent.com/138302/29497201-c53ef476-85db-11e7-8fdf-03d1a0336ad6.png)

It seems to behave correctly in non-anonymous rooms and semi-anonymous rooms where I don't have any specific permissions. I am not sure this happens only in this case. I also saw this happen when restoring history of a muc (mam_muc?)

**Comment by iNPUTmice** [comment]
That's because he is in your roster. For contacts it will prefer the same name that is used in 1:1 chats. This is working as intended.
