### ISSUE TITLE
Color of the avatar used for <composing/> differ from the one used in the room.

### ISSUE THREAD

**Issue by Ppjet6** [siacs/Conversations#2591]
#### General information

* **Version:** 1.19.5
* **Device:** N/A
* **Android Version:** N/A
* **Server name:** N/A
* **Server software:** prosody-trunk
* **Installed server modules:** N/A
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Join a muc.
2. Wait for a user to send a `<composing />` chatstate.

#### Expected result

The color of the generated avatar in the "[..] is typing..." message should be the same as the color used for that user in the room, but it currently differs. See picture below.

![screenshot_20170820-170736](https://user-images.githubusercontent.com/138302/29497201-c53ef476-85db-11e7-8fdf-03d1a0336ad6.png)

Is it the expected behavior? Maybe related to #2590?

**Comment by Ppjet6** [comment]
Just realized it's not just for chatstates. His color in the discussion list is also pink, and brown in the 1:1 tab.

**Comment by iNPUTmice** [comment]
Please check with 1.20.1
