### ISSUE TITLE
Allow Avatar Gifs to play in the Contact Details

### ISSUE THREAD

**Issue by subpub** [siacs/Conversations#2593]
* **Version:** 1.20.0-beta

Avatar Gifs (animated Webps) can be played _only_ in the `contact details` what do you think? 👍or👎

**Comment by knoy** [comment]
Why not in the Conversation List activity as well?

**Comment by annafallasktick** [comment]
nopes, and extra nopes.

**Comment by harshitbansal05** [comment]
@uchchishta I am confuesd, how can we make a gif from a contact image? Could you please help?

**Comment by subpub** [comment]
> The issue tracker on Github is for bug reports only.

see https://github.com/siacs/Conversations/blob/master/.github/CONTRIBUTING.md#reporting-bugs-and-getting-help
