### ISSUE TITLE
have a new set as profile picture activity

### ISSUE THREAD

**Issue by uchchishta** [siacs/Conversations#2594]
* **Version:** 1.20.0-beta

have a `set as profile picture` activity so it can be easy to set a profile pic from any gallery or directly from the browser

#### Steps to reproduce

1. open an image from gallery or browser
2. select `set as`
3. see no `Conversations Profile Picture`

##### What is the expected output? What do you see instead?

other apps like WhatsApp allow to set as profile picture.

**Comment by iNPUTmice** [comment]
Note to self. The Intent is called `Intent.ACTION_ATTACH_DATA`
