### ISSUE TITLE
Conversations not up-to-date in Amazon store

### ISSUE THREAD

**Issue by rfc2822** [siacs/Conversations#2597]
Thanks for this great software! I have bought it in Amazon store to support it, but I don't see the most recent version here. In Amazon, the latest version is 1.19.1, but in F-Droid it's 1.20.0 and on Github it's 1.20.1.

**Comment by licaon-kter** [comment]
F-Droid has 1.20.1 already ;)

**Comment by iNPUTmice** [comment]
I think amazon should have the latest version now.

**Comment by rfc2822** [comment]
Thank you!
