### ISSUE TITLE
Feature Request: show symbol on main screen & Android notification for undelivered messages

### ISSUE THREAD

**Issue by STPKITT** [siacs/Conversations#2602]
I sometimes had it happen that I had send a message and immidiately after pressing the send-button I pressed the back-button, so I went back to the main screen before the sending process finished so that I could not see if a message got sent or if there was a problem with the transmission. The result was that I thought I had sent something only to discover later by going back into that chat that the sending failed.
So my feature request is to have a symbol on a chat in the mainscreen that indicates that there are failed sending attempts in that chat. Android does this on the default SMS-app, however in that app the symbol has not timeout, so if sending an SMS failed one year ago the symbol will still be there.
In addition to the symbol in Conversations' mainscreen it should also have an Android notification in case you leave Conversations right after pressing the send-button.

**Comment by iNPUTmice** [comment]
I suggest you try to fix the problem of undeliverable messages instead.
