### ISSUE TITLE
Feature request: Separate 1-to-1-chats & MUCs into two tabs

### ISSUE THREAD

**Issue by STPKITT** [siacs/Conversations#2604]
I'm a member of several huge MUCs with lots of activity. That results in the MUCs nearly always being shown on the top of Conversations' mainscreen, so much so that on my device I only see MUCs without scrolling down.
My feature request to deal with that is to introduce two clickable tabs on the top of Conversations' mainscreen, one tab, preferably the left one, for 1-to-1-chats and the other for MUCs.

**Comment by iNPUTmice** [comment]
This doesn't fit the spirit of Conversations. Large multi user conferences is not a use case Conversations tries to cover.

**Comment by STPKITT** [comment]
I just observed the same UI problem in WhatsApp on my father's smartphone. Since most of the groups he's a member of (all private groups with 10 to 20 members) have more recent activity than his 1:1 chats the groups are all listed on top of his chat list. I asked him and he said that he finds that annoying.
