### ISSUE TITLE
Feature Request: option to disable sliding gestures

### ISSUE THREAD

**Issue by STPKITT** [siacs/Conversations#2605]
Currently there are sliding gestures to close a chat and to slide in the chat which is partly shown on the very right of the main screen.

1. I would like an option to be able to disable the "slide to close"-gesture to avoid accidently closing chats, which happened to me often and I had reports from other people also having that trouble and therefor not liking that gesture.

2. I would also like to be able to disable that small part of the chat last entered that's shown on the right of Conversations' mainscreen, because I would rather use the space to show more of MUC topics etc.. Along with that the corresponding gesture should also be able to get deactivated.
Point 2 also correlates to the feature request I just opened here: https://github.com/siacs/Conversations/issues/2604

**Comment by licaon-kter** [comment]
> accidently closing chats,

**Comment by iNPUTmice** [comment]
>  would also like to be able to disable that small part of the chat last entered that's shown on the right of Conversations' mainscreen, because I would rather use the space to show more of MUC topics etc.. Along with that the corresponding gesture should also be able to get deactivated.
Point 2 also correlates to the feature request I just opened here: #2604 

This is equivalent to a complete UI refactoring which I currently don't have time for.
