### ISSUE TITLE
Proposals how to deal with PMs in MUCs

### ISSUE THREAD

**Issue by STPKITT** [siacs/Conversations#2606]
In very crowded MUCs it's often difficult to find PMs sent to you. What about tacking PMs from people that are not in your roster on to the top of the chat window of that MUC?

And if you send a PM from a MUC to someone who's also in your roster Conversations should redirect that message so that it's transmitted via 1-on-1-chat.

**Comment by iNPUTmice** [comment]
> And if you send a PM from a MUC to someone who's also in your roster Conversations should redirect that message so that it's transmitted via 1-on-1-chat.

This is the end goal but there is no time frame for that feature.

**Comment by ycau** [comment]
I'd prefer to mark PMs just with colors inline of the MUC.
I like the inline PMs in conversations and prefer them over the separate chats like in Gajim.
To mark PMs with colors should be less programming effort, too.
