### ISSUE TITLE
where are the messages are stored on the device when they are not deleted?

### ISSUE THREAD

**Issue by whitetornado** [siacs/Conversations#2607]
#### General information

* **Version:**1.20.0 beta
* **Device:** s6 samsung
* **Android Version:** 7.x
* **Server name:** selfhosted xmpp
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg f-droid

i want to know where on the phone i can find the messages what stays in the App. On the server i can not find any log or something and on the device also not...
so please let me know where !!

**Comment by iNPUTmice** [comment]
This is a bug tracker. Not a support forum. If you want free support please use the community group chat at conversations@conference.siacs.eu

**Comment by whitetornado** [comment]
Final-Recipient: rfc822; conversations@conference.siacs.eu
Action: failed
Status: 4.0.0
Diagnostic-Code: smtp; DNS Error: 15084348 DNS type 'mx' lookup of
conference.siacs.eu responded with code NOERROR

**Comment by PeterEdens** [comment]
It is an XMPP address not an email address
