### ISSUE TITLE
Improve PM visibility with colors

### ISSUE THREAD

**Issue by ycau** [siacs/Conversations#2610]
Both 
- the chat balloon and 
- the writing line
for PMs could be highlighted with slight colour differences to the normal colours.

Why?
Before you start writing you clearly see the info "Write private message to USER". But after starting to type I often delete the whole text again because I forgot whether I am in PM or in MUC writing mode. Quite annoying how often I delete text just to switch beteween the modes or realizing everything is right already.
The chat balloons are already cleary marked PM.

I'd suggust a somewhat lighter or darker green than for the normal chat and this color then also for the writing line when in PM mode. Additionally with the name of the recipiant in front of the line.

iNPUTmice, I thank you 4 the great messenger. I use it everyday and it makes my life brighter :).

This is superset of the issue #2606.

**Comment by uchchishta** [comment]
See also #2449

**Comment by iNPUTmice** [comment]
We currently have no plans to change the color. Your other request is duplicate.

**Comment by ycau** [comment]
How do you find the idea to have a feedback about whether you are writing in PM or MUC mode? Don't you find it useful?
