### ISSUE TITLE
Ask "Battery Optimization -> disable" on first start

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2611]
...instead of hiding it in "Account view" for some strange reason.

(Android >=6)

**Comment by iNPUTmice** [comment]
Thats already the case. It will ask only once.

**Comment by licaon-kter** [comment]
Of a dozen installs and even more starts, I did see Storage/Contacts every time, but battery only once... after I posted this here actually. So imagine my surprise to see that, of all places, the Account view has a battery option.
