### ISSUE TITLE
XEP-0163 PEP (Avatars/OMEMO) marked as unavailable since Conversations 1.20 on Prosody server

### ISSUE THREAD

**Issue by mfvescovi** [siacs/Conversations#2612]
Hi!

As reported at [#873174](https://bugs.debian.org/873174) in Debian BTS, since Conversations 1.20 the XEP-0163 PEP module is marked as unavailable on Prosody server based on Debian 9 "stretch" (running 0.9.12 version).

Same configuration of Prosody server works just fine with Conversations <= 1.20 (tested on 1.19.5 for sure).

Thanks in advance for the efforts spent to fix this issue.

**Comment by mightyBroccoli** [comment]
Follow the little questions mark.
The pep module itself is not meant. It is the publish-options which is a new feature to pep not yet released to prosody pep.

https://github.com/iNPUTmice/ComplianceTester/blob/master/src/main/java/eu/siacs/compliance/tests/OMEMO.java

**Comment by iNPUTmice** [comment]
Nothing to worry about. OMEMO will work just as before. Only the new features wont be supported.

**Comment by nougad** [comment]
For reference: prosody issue for tracking this feature: https://prosody.im/issues/issue/965

**Comment by devurandom** [comment]
From the Prosody report it appears what is missing is not XEP-0163 but a part of XEP-0060. Should the "server info" list be changed to show them separately?
