### ISSUE TITLE
Use HTTP upload instead of sending file directly

### ISSUE THREAD

**Issue by jkufner** [siacs/Conversations#2614]
#### General information

* **Version:** 1.20.1
* **Device:** Samsung S4 mini
* **Android Version:** 4.4.4
* **Server name:** self hosted
* **Server software:** ejabberd 16.04
* **Installed server modules:** all
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Send a photo
2. Conversations asks where to send the photo and then tries to send it in a stupid broken way.

#### Expected result

Photo is uploaded to server using HTTP upload and link is sent to recipient.

It worked before just fine.

**Comment by licaon-kter** [comment]
Logs from device while sending?

**Comment by iNPUTmice** [comment]
This is not a support forum. Please use the group chat if you have questions.

**Comment by jkufner** [comment]
This is not a question, this is a regression or feature request. I'm not sure which one.

A few moments ago, I sent a picture. For some reason Conversations chose to use file transfer rather than HTTP upload. And of course, the transport failed.

The problem is, there is no way to tell Conversations to use HTTP upload and nothing else.

**Comment by BlauerHunger** [comment]
Conversations uses HTTP File Upload whenever it's possible. Please check whether HTTP File Upload is configured properly on your server. Another reason why it didn't use HTTP File Upload might be that the file was too large.
