### ISSUE TITLE
Record voice option is not shown in latest versions

### ISSUE THREAD

**Issue by sambeiber** [siacs/Conversations#2617]
Hi ..After compile this source code i tested it into different devices it show multiple options in attachment like this
* Record voice (work for me in version 4 and 5)
* Take picture
* Choose Picture
* Choose file
but when i test this same Apk into latest version (like 6 and 7) its  didn't give me option of " Record voice "  and when i  received any  recorded voice from any other device try to open this the app was crash and close..while this recorded voice is placed in internal storage in conversation folder. i want to use record voice option in latest version of Android..Kindly help to resolve this  issue ..Thanks

* **Device:** google nexus 7 and QMobile LT700
* **Android Version:**  Android 6.0 and Android 7.0
* **Server name:**  self hosted
* **Server software:** ejabberd 17
* **Conversations source:**self build

**Comment by iNPUTmice** [comment]
You need the Voice Recorder Plugin (or any other app that can record voice messages)
In the future please use the group chat for free community support. This issue tracker is for bug reports only.
