### ISSUE TITLE
Contacts permission description text should appear on first request

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2618]
Right now it does not:
* install app
* start app
* login
* app ask for "Contacts"
* refuse
* close app
* start app a 2-nd time
* app ask for "Contacts"
* refuse
* close app
* start app a 3-rd time
* repeat 3 or 4 more times
* start app
* > Conversations wants to match your XMPP roster with your contacts to show their full names and avatars.\n\nConversations will only read your contacts and match them locally without uploading them to your server.\n\nYou will now be asked to grant permission to access your contacts.
* refuse
* start app
* > Conversations wants to match ....
* now repeats every time

**Comment by iNPUTmice** [comment]
The current behaviour follows android design guidelines.

**Comment by licaon-kter** [comment]
So you are not allowed to explain why you'll ask for that permission on first start? 
You are allowed to "explain" only after the first "refuse"?

**Comment by Kandr0s** [comment]
![](https://i.stack.imgur.com/xLds8.png)

**Comment by licaon-kter** [comment]
This feels wrong though, I kinda reject that on first start anyway... BUT having the explanation I understood WHY and accepted it. After the first deny, in general, for the second one I won't bother reading the text "stop trying to steal my contacts"  :)

**Comment by Kandr0s** [comment]
Imagine the following App. You got an overlay, with a button "open camera". Why would you need an explanation for the following Permission Request. Its obvious why the app needs the camera permission to open a camera activity.
Everyone who denys this, obviously needs a detailed dialog, which tells him: "you dumbass, i cant open the camera without permission"

**Comment by licaon-kter** [comment]
Umm, "chat app wants to read your contacts"... you did read their terms of service and privacy policy on their site before installing the app from the store, right? they siphon your contacts email addresses? phone numbers? they upload them to their servers? they share them with a 3-rd party? What ? Why? Exactly...

Not sure why you'd mention camera here... :-1:

**Comment by Kandr0s** [comment]
I Said: "imagine". It was Just a scenario to show you why  the Android guidelines (especially the permission requests Part) is reasoned. You dont need an explanation the First time.
