### ISSUE TITLE
Unused resources

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2619]
While correcting some translations I kept seeing some strings that are never used, yet I had to translate them:

```
pref_force_encryption
pref_force_encryption_summary
...
and some 36 more
```

Are these forgotten, for the future or what?

**Comment by iNPUTmice** [comment]
They are forgotten.

**Comment by licaon-kter** [comment]
Took care of the strings.

Now, Android Studio says some images are not used either, should I dare to clean them up too?

**Comment by iNPUTmice** [comment]
> Now, Android Studio says some images are not used either, should I dare to clean them up too?

sure. as long as they are not false negatives.
