### ISSUE TITLE
Show "partial" PEP availability if publish-options isn't available

### ISSUE THREAD

**Issue by strugee** [siacs/Conversations#2621]
I recently went to investigate why Conversations showed PEP as "unavailable" on my server, then found #2612 and processone/ejabberd#1974 - apparently there's no issue.

Since PEP works just fine, but doesn't have some optional features, "unavailable" is a bit misleading. It would be nice if Conversations said "partial availability" or something like that.

**Comment by vomitous** [comment]
functionality, like gender, is a binary state

**Comment by kousu** [comment]
I just noticed the same thing. "partial" is still confusing and worrying though; is "OMEMO is only available to contacts with mutual presence subscription." the only implication of this? It would be helpful if the word partial was a link that explained exactly what is crippled.
