### ISSUE TITLE
Show warning if keys wont match

### ISSUE THREAD

**Issue by uchchishta** [siacs/Conversations#2627]
#### General information

* **Version:** 1.20.0-beta

#### Steps to reproduce

1. Scan Contacts QRcode
1. Contact's JID matches but OMEMO key doesn't match
2. Conversations doesn't show anything in the UI

#### Expected result

**What is the expected output? What do you see instead?**

   Conversations should show a very visible Warning. Preferably using custom Red toasts (see [toasty](https://github.com/GrenderG/Toasty)) with long on-screen duration or if anyone has any other better idea.

**Comment by iNPUTmice** [comment]
(yet) unknown keys will be pre-verified in case this key will become available later. it is a complete legitimate case that I scan a users qr code *before* initializing a session.

**Comment by licaon-kter** [comment]
So they're kept cached for this contact? Interesting...

**Comment by uchchishta** [comment]
Can you make it known to the user that:

1.  The keys were added to archive for future use.

   - Make the new keys known to the user in the UI

     For eg. Tag it `NEW`

1.  How many keys were verified:  All?

**Comment by iNPUTmice** [comment]
@uchchishta your feedback will be taken into consideration.
