### ISSUE TITLE
1.20.0 - display emoji-only messages slightly larger - slightly inconsistent

### ISSUE THREAD

**Issue by aslmx** [siacs/Conversations#2628]
#### General information

* **Version:** 1.20.1
* **Device:** Different Huawei Models (P9, P10), but same behavior on Sending and Receiving side
* **Android Version:** 7.0
* **Server name:**  self hosted
* **Server software:** Prosody 0.9
* **Conversations source:**  F-Droid

#### Steps to reproduce

1. Send different Emojis with different Skin Colors
2. Notice result

#### Expected result
- All Emojis that are the only message content are displayed sligthly larger (or not), regardless of skin color/tone

What is the expected output? What do you see instead?
Not all Emojis are sent "slightly" larger when used as the only message content.
See screenshot for example.

#### Debug output
n/a

![screenshot_20170911-165513](https://user-images.githubusercontent.com/13053017/30284944-c3b3e600-971c-11e7-8ae3-5ebf56786a3c.png)
![screenshot_20170911-165519](https://user-images.githubusercontent.com/13053017/30284942-c3b290d4-971c-11e7-9805-302c9ced7ee2.png)
![screenshot_20170911-165552](https://user-images.githubusercontent.com/13053017/30284943-c3b3a546-971c-11e7-825b-92dc1ab241a1.png)
![img_20170911_181450](https://user-images.githubusercontent.com/13053017/30285048-1d431218-971d-11e7-95d3-ff3c3bec89ca.jpg)

**Comment by iNPUTmice** [comment]
This is a known problem with the upstream emoji library.
I think https://github.com/vdurmont/emoji-java/issues/69 is tracking this issue.
