### ISSUE TITLE
DNS Lookup of server takes a long time due to bad 49.0.0.0 and 56.0.0.0 entries

### ISSUE THREAD

**Issue by PeterEdens** [siacs/Conversations#2629]
#### General information

* **Version:** 1.19.5
* **Device:** Samsung S3
* **Android Version:** 4.1.2
* **Server name:** self hosted
* **Server software:** ejabberd 16.02
* **Installed server modules:** MAM
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Try to connect to account
2. Takes a long time, put a breakpoint in findDNS() and you will see that servers 49.0.0.0 and 56.0.0.0 are added as DNS servers but they timeout

I  tried blacklisting them but the code in minidns 0.2.2 does not return the list correctly after removing the blacklisted servers.  I found adding DNSClient.removeDNSServerLookupMechanixm(AndroidUsingExec.INSTANCE); works to remove the bad DNS servers.  I call this at the start of connect()

**Comment by licaon-kter** [comment]
The latest version is 1.20.1, are you on HEAD or not?

Where do 49.0.0.0 and 56.0.0.0 come from exactly? Not from your connection settings?

**Comment by PeterEdens** [comment]
It was HEAD when I built a few weeks ago so now it is not HEAD.

49.0.0.0 and 56.0.0.0 come from the android system, in 4.0 the android system appears to add these when getting DNS servers using the Exec method.  Using the Reflection method these servers do not get listed so the DNS lookup is much faster.

**Comment by licaon-kter** [comment]
Retest with HEAD, as some commits touch DNS too.

**Comment by iNPUTmice** [comment]
You should report this to minidns

**Comment by devurandom** [comment]
Did anyone report this to minidns? Could they please post a link to the issue here, so we can follow the progress?

**Comment by PeterEdens** [comment]
I reported it and it appears to have been fixed [https://github.com/MiniDNS/minidns/issues/69](https://github.com/MiniDNS/minidns/issues/69)
