### ISSUE TITLE
Allow showing QR code when account is disconnected

### ISSUE THREAD

**Issue by mimi89999** [siacs/Conversations#2630]
#### General information

* **Version:** 1.20.1
* **Device:** Samsung Galaxy S4 Mini
* **Android Version:** LineageOS 14.1 (Android 7.1.2)
* **Server name:** self hosted
* **Server software:** prosody trunk
* **Installed server modules:** not important
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Have an OMEMO encrypted conversation that is not verified (yet)
2. Meet with the contact in a place without WiFi and not mobile data (basically a situation without internet access)
3. Try to show your QR code for verifying fingerprints.
4. The only option in the menu will then be 'settings' making it impossible to how the QR code for verification

#### Expected result

Be able to show the QR code even without internet access.

#### Debug output

Doesn't seem necessary here...

**Comment by licaon-kter** [comment]
Share menu-> as Barcode -> my.jpg -> Gallery app -> Show image ?

**Comment by mimi89999** [comment]
Not obvious...

**Comment by vomitous** [comment]
@soupeater me two

**Comment by mimi89999** [comment]
Thanks
