### ISSUE TITLE
Wrong tooltip on "new conversation" icon

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2635]
#### General information

* **Version:** 1.20.1
* **Android Version:** Android 6.0.1 Stock
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Open app
2. Open a conversation
3. Press arrow to see the overview
4. Long press on the + (new conversation) icon

#### Expected result

Toast saying "New conversation" that pops-up near the icon.

#### Actual result

Toast at the bottom of the screen with encryption tooltip, the exact one that you get when, inside the said conversation, you long press the lock icon:
* No toast if encrypted
* "Missing OMEMO keys"
* "Missing presence subscription"

/PS: You need to enter the conversation first in order to see this bug.

**Comment by kriztan** [comment]
Hi, this patch is still not working as expected.
Please follow the steps from @licaon-kter to reproduce it. The actual result changed from @licaon-kter actual result to only no toast.

**Comment by licaon-kter** [comment]
I can confirm, no toast is better than any message about keys and OMEMO :) :)

**Comment by iNPUTmice** [comment]
Doesn’t seem to be fixable in Android <8. 
But the tool tip will go away sooner or later anyway so it doesn't really matter.
