### ISSUE TITLE
Some HTML are not displayed (namely ones received from the Telegram spectrum backend)

### ISSUE THREAD

**Issue by DexterLB** [siacs/Conversations#2641]
#### General information

* **Version:** commit 129b84bda (latest at time of writing)
* **Device:** Lenovo A6000
* **Android Version:** Android 4.4 Stock
* **Server name:** self hosted
* **Server software:** ejabberd 17.08
* **Installed server modules:** HTTP uploads
* **Conversations source:** self build (latest HEAD)

I receive the following stanza:

    
    <message to='dexterlb@qtrp.org/Client' from='other_user@telegram.qtrp.org/bot' type='chat'>
        <archived by='dexterlb@qtrp.org' id='1506500036850419' xmlns='urn:xmpp:mam:tmp'/>
        <stanza-id by='dexterlb@qtrp.org' id='1506500036850419' xmlns='urn:xmpp:sid:0'/>
        <html xmlns='http://jabber.org/protocol/xhtml-im'>
            <body xmlns='http://www.w3.org/1999/xhtml'>
                <br/>
                <img src='https://rnd.qtrp.org/spectrum/9d4483d22d4f3046ccb5e450be3aa7234e025772.jpg' alt=''/>
            </body>
        </html>
        <body>
        </body>
    </message>

In desktop clients (for example Gajim), it is displayed as an inline image. Conversations displays it as a blank message.

Note: this might actually not be a Conversations issue. Any pointers as to what might be wrong with the stanza are much appreciated.

**Comment by iNPUTmice** [comment]
Tell them to format the stanza as follows (omitting the stanza-ids here that are added by your server)
```
<message>
  <body>https://rnd.qtrp.org/spectrum/9d4483d22d4f3046ccb5e450be3aa7234e025772.jpg</body>
  <x xmlns='jabber:x:oob'>
    <url>https://rnd.qtrp.org/spectrum/9d4483d22d4f3046ccb5e450be3aa7234e025772.jpg</url>
  </x>
</message>
```

They can leave in the `<xhtml>` tag as well if they think it is necessary.
However the `<body>` must be included or it wont work in clients that don’t support xhtml. (It's not just Conversations)
The additional oob-tag will make Conversations treat this as an inline image instead of a link.

**Comment by nanderer** [comment]
I dont understand whats the problem in just showing all jpg and png links as image, just head them and if mimetype and filesize maches do your stuff ;) but i did forwarded this (not without saying my oppinion about this particular way of thinking)...

Thanks for taking this note

No offence
Regards
