### ISSUE TITLE
allow message corrections

### ISSUE THREAD

**Issue by ShallNotInfringe** [siacs/Conversations#2648]
#### General information

* **Version:** eg 1210
* **Device:** eg Active
* **Android Version:** Android 5.1
* **Server name:** conversations.im, 
* **Conversations source:** , F-Droid, 

 
enable expert, allow message correction.

enable on all contacts' devices

can edit prior line of text

CANNOT edit voice recorded audio (plugin)

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by ShallNotInfringe** [comment]
oh, fun, cannot edit ticket on mobile

**Comment by licaon-kter** [comment]
You can Edit in the Forkhub app :)

**Comment by iNPUTmice** [comment]
Message corrections are activated by default (again) on 1.21.0
