### ISSUE TITLE
When sharing images, request permission to access storage

### ISSUE THREAD

**Issue by YtvwlD** [siacs/Conversations#2649]
#### General information

* **Version:** 1.21.0
* **Device:** FP2
* **Android Version:** Android 6.0 Stock
* ~~Server name~~
* ~~Server software~~
* ~~Installed server modules~~
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Install Conversations.
2. Restore data from previous install. (I don't know if this is neccessary.)
3. Try to share an image from the gallery. (Open the gallery, select an image, select Share, select a conversation.)

#### Expected result

The image should be shared.

#### Actual result

The image isn't being shared.
There is something about missing permissions in the logs.

#### workaround

1. Open Conversations.
2. Open a conversation.
3. Try to select an image.
4. Grant Conversations the permission to access the storage.

Sharing now works from the gallery, too.

Perhaps I just missed a step in the setup process when I restored the application data from an old install on Android 4.4, but I think Conversations should ask for the permission to access the storage when sharing images.

**Comment by iNPUTmice** [comment]
82e5a28f4934831a04d5577d9099f8ecea7d48e7
