### ISSUE TITLE
Add OMEMO fingerprints authentication with OpenPGP

### ISSUE THREAD

**Issue by blacoste** [siacs/Conversations#2651]
Sum-up of the request: 
Add a mechanism to auto-approve OMEMO fingerprints based on OpenPGP.  This may imply writing a new XEP (or update) as it would need protocol update.

Context / Feedback of current implementation of OMEMO: 
Nowadays, user shall check for OMEMO fingerprints of a contact via another communication channel. It includes face-to-face (QR Code scanning, manual fingerprint checking), or remotely (voice call, SMS, ...). My experience is that I do it most of time remotely, with blind trust. The more contacts you have, the more boring the process is. In my case I have only 10 contacts, each one owns several devices. People often add and remove devices, which makes the problem recurrent. I am regularly encouraged not to check the fingerprints. I just sympathize with people who would try to use it in bigger organizations...

Detailed description of new feature: 
- [Implemented] [XEP-0373] User turns on OpenPGP on its XMPP account by publishing its own OpenPGP public key
- [Implemented] User authorizes the list of OMEMO fingerprints its own account (one for each device).
- [Todo] XMPP client signs with OpenPGP the trusted OMEMO fingerprints and publish it to the server. 
- [Todo] Retrieved OMEMO fingerprints are auto-accepted by the device if they come with a valid OpenPGP signature. This is applicable for user's own fingerprints (trust propagation on all its devices) and for other XMPP contacts.

Signing of fingerprints:
Because OpenPGP might not be available on all devices: 
- Each device may independently sign its OMEMO fingerprint with the OpenPGP key.
- And at least one of the user's devices is able to sign all the trusted OMEMO fingerprints of its own account.
So, several signatures may come from one device, or they may be generated by separate devices. 

Publishing Fingerprints:
- Signed fingerprints are published to XMPP server account on each signature operation, so turning on/off device off does not affect the retrieved content.
- Fingerprints may be added / removed / revoked

Unsigned/unrecognized fingerprints should not affect be affected by this proposed changes and shall continue to use the currently implemented verification process (non-automatic approval).

Keywords : OpenPGP, PGP, OMEMO, fingerprints, trust, encryption.

**Comment by iNPUTmice** [comment]
I don't see a reason to mix different encryption technologies. I see the incentive to to cross sign OMEMO identities. But not with OpenPGP.
