### ISSUE TITLE
Share video from WhatsApp to Conversations causes duplicates

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#2652]
#### General information

* **Version:** 1.21.0
* **Device:** OnePlus 3, but doesn't matter
* **Android Version:** Android 7.1 Lineage OS, but doesn't matter
* **Server name:** self hosted, but doesn't matter
* **Server software:** prosody, but doesn't matter
* **Installed server modules:** all relevant for Conversations
* **Conversations source:** PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD), but doesn't matter

#### Steps to reproduce

1. open WhatsApp
2. share a video from WhatApp to a contact within Conversations directly (not from the gallery app)

#### Expected result

The video should be uploaded/sent once.

#### Actual result

The video will be uploaded/sent twice.

#### Debug output

I can't provide any debug logs, because I don't have WhatsApp to test. 
This seems to be a sender side issue, because the sender uploads the file twice. I'm only on the receiving side.

**Comment by GlasFrost** [comment]
As discussed with @kriztan I'm attaching a logcat file. It has been cleaned to contain only Conversations' and WhatsApp's entries. JIDs have been replaced.
[logcat_2017-10-12_16-25-59_filtered.txt](https://github.com/siacs/Conversations/files/1379726/logcat_2017-10-12_16-25-59_filtered.txt)

**Comment by GlasFrost** [comment]
I was able to reproduce this btw.

Server: conversations.im
Client: Conversations 1.21.0 from PlayStore
WhatsApp version: 2.17.351 (latest available from PlayStore at the time of writing)
OS: LineageOS 14.1 (Android 7.1.2)
Device: OnePlus 3T

**Comment by GlasFrost** [comment]
Further testing revealed that the issue also occurs on video files that are shared from other apps (LineageOS Gallery, among others). However, if the file is too large and needs to be compressed, it is uploaded and sent once. Video files that are small enough to be sent directly are uploaded and sent twice.

**Comment by kriztan** [comment]
I think I've found the problem:
in https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/services/AttachFileToConversationRunnable.java#L134

the file is handled as video, with ends up in onTranscodeFailed
https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/services/AttachFileToConversationRunnable.java#L124

At this point you start sending the file as is with prossessAsFile() and throw an Exception.

This Exception ist catched in run() at 
https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/services/AttachFileToConversationRunnable.java#L135
which also starts sending the file as is with prossessAsFile()

I'll test this in the evening and report back.

**Comment by licaon-kter** [comment]
I guess as #2644 the video file is treated as "recorded by Conversations" (if longer than 8 seconds it gets re-compressed even) instead of just attaching it.

**Comment by iNPUTmice** [comment]
> At this point you start sending the file as is with prossessAsFile() and throw an Exception.

I don't throw an Exception. Where exactly is the exception coming from?

**Comment by iNPUTmice** [comment]
Can you check out branch https://github.com/siacs/Conversations/tree/fix_duplicate_video_sharing and see if this fixes the issue? (also please post the adb logcat even if it fixes the issue)

**Comment by kriztan** [comment]
Your fix seems also fix that issue. 
[2017-10-14 logcat.txt](https://github.com/siacs/Conversations/files/1384853/2017-10-14.logcat.txt)
