### ISSUE TITLE
Cannot HTTP Upload Files: "Unexpected response code for CONNECT: 403" Error When Connecting via Tor/Orbot

### ISSUE THREAD

**Issue by ded5r** [siacs/Conversations#2656]
#### General Information

* **Version:** 1.21.0
* **Android Version:** 4.3.1
* **Server name:** jabber.systemli.org
* **Installed server modules:** Everything in "Server Info" section is available (PEP partial)
* **Conversations source:** F-Droid

#### Additional Information

Both contacts have accounts on same server. Both contacts have "Send presence updates" and "Receive presence updates" checked. Both contacts have automatically accept files set to 10 MiB. Both contacts are using OMEMO in Conversations. Both contacts are connecting through Tor/Orbot to the server.

#### Problem

For both contacts, when sending a file, it says "delivery failed". Person receiving the file recieves nothing. On sender's side, long-pressing the failed file reveals "Show error message" option. Error Message states: "Unexpected response code for CONNECT: 403". We have no way of sending or receiving files.

#### What Worked

We log out, disable Connect via Tor, then reconnect to jabber.systemli.org. (All other settings remain exactly the same.) Without connection via Tor, everything works, files upload!

#### Conclusion

There seems to be an issue with file transfers (http_upload) when connected to a server via Tor/Orbot.

**Comment by licaon-kter** [comment]
What if one connects through Tor and the other directly?

**Comment by ded5r** [comment]
The upload or download of the file works no matter for whomever does not connect to the server via Tor, even if the other person at the time is not logged in at all and offline. If the upload is successful (because the person sending the file is not connected via Tor), the person connected via Tor receiving the file gets a message saying, "Check image size on jabber.systemli.org". If that is pressed, a brief pop-up states, "Download failed: File not found". If it is long-pressed, a "Copy original URL" option becomes available, which gives the usual full aesgcm:// URL.

**Comment by iNPUTmice** [comment]
Make sure your orbot has the http proxy thing configured.

**Comment by ded5r** [comment]
If you mean the proxy ports in Orbot, they have always been the defaults...

Tor SOCKS         Port 9050
Tor TransProxy   Port 9040
Tor DNS              Port 5400

And by the way, there is of course no problem with connecting to the server, logging in, or sending OMEMO messages via Tor connection. It is only a problem when trying to upload or download a file via Tor connection to server.

**Comment by ded5r** [comment]
Upgraded Orbot from 15.4.1-RC-1-multi to 15.4.2-RC-1-multi-SDK16 and now all file uploads and downloads work as it should via Tor. Don't know or understand how that changed anything but closing the issue. Thank you for the help.
