### ISSUE TITLE
Uploads not respecting custom hostname

### ISSUE THREAD

**Issue by nikksno** [siacs/Conversations#2658]
#### General information

* 1.20.1
* oneplus 3 AND ARC-welder
* Resurrection Remix [based on 6.0] AND macOS sierra
* self hosted [os.vu] with [aenigma.xyz](https://github.com/openspace42/aenigma) v0.5
* ejabberd 17.08
* MUC, MAM, HTTP uploads, etc...
* F-Droid

The os.vu xmpp domain uses SRV records to point it to ae.os.vu and the ejabberd config specifies the uploads hostname to be `xu.@HOST@`, so `xu.os.vu`.

Conversations, instead, is trying to send the file to `os.vu`.

I have found no way to confirm it's a Conversations issue and not an ejabberd issue, but the config seems solid and the `host: xc.@HOST@` directive for mod_muc works perfectly.

#### Steps to reproduce

1. Upload a picture / file [it fails]
2. Check error message

#### Expected result

It should actually upload

#### Actual result

`failed to connect to os.vu/[ip] (port 5444) after 15000ms`

[notice, in fact, it's sending to `os.vu` and not `xu.os.vu`.]

#### Debug output

[Not available right now, sorry, I'll update asap]

Thanks!

**Comment by licaon-kter** [comment]
Same with 1.21.0 ?

**Comment by nikksno** [comment]
Yes, just tested it now

**Comment by iNPUTmice** [comment]
This is not a Conversations issue. Please fix your ejabberd config.

```
put_url: "https://@HOST@:5444"
```

**Comment by nikksno** [comment]
@iNPUTmice you're right, it was an ejabberd problem, not sure how it slipped through. I'm very sorry to disturb, but as you know better than anyone, it's extremely hard to find another client that supports the latest standards and that was at least developed in this millenium. I don't have an iOS device lying around, so chatsecure is out of the question. Anyway, thanks.
