### ISSUE TITLE
how does conversations store message

### ISSUE THREAD

**Issue by sambeiber** [siacs/Conversations#2662]
#### General information
Hi ...i am review the code of conversations app, ejabberd server is use with it and i had disabled the MAM module. Is there any where chat or key stored in my phone ? The conversations folder which is created in phone only contain file and images that  i have send or received . I am testing it using rooted phone.

* **Version:** eg 1.14.0
* **Device:**  GT I9300
* **Server name:**  self hosted
* **Server software:** ejabberd 17.04  
* **Installed server modules:** 
* **Conversations source:**  self build

**Comment by monojp** [comment]
Hi,
Android apps in general have private data dirs under /data/data I think. Conversations is doing nothing special here.

**Comment by licaon-kter** [comment]
FYI, the latest version in 1.21.0.

It has a sqlite database in /data/data/eu.siacs.conversations/...that holds all the messages. In theory deleting messages in app should update said database.
