### ISSUE TITLE
Allow change storage location for media.

### ISSUE THREAD

**Issue by Gatak** [siacs/Conversations#2663]
#### General information

* **Version:**  1.21.0
* **Device:** Moto G 3rd Gen
* **Android Version:** Android 6.0.1 Stock 
* **Server name:**  self hosted
* **Server software:** prosody 0.10
* **Installed server modules:**  Stream Managment, CSI, MAM, and all default/stock mods.
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. Receive lots of files from a contact.
2. Your internal storage gets full.
3. No option to limit storage usage or warning in the app.

#### Expected result

1) An option to store received files on external sdcard.

#### Actual result

Phone ran out of internal storage.

This phone does not allow moving apps to the sdcard, nor does it allow me to use sdcard as internal storage.
Another phone i have does allow sdcard as internal storage only if it is encrypted. This means if phone crashes, all files are unrecoverable, which mostly isn't a good alternative.

**Comment by licaon-kter** [comment]
> if phone crashes

Backup?

**Comment by Gatak** [comment]
Backup is of course important, but it still doesn't solve the other issues such as full internal storage.

**Comment by iNPUTmice** [comment]
Internal + External storage is an outdated concept. Proper Androids will merge the two anyway.
