### ISSUE TITLE
Dont advertise empty avatar on presence

### ISSUE THREAD

**Issue by lovetox** [siacs/Conversations#2664]
#### General information

* **Version:** whatever you current use iNPUTmice

#### Steps to reproduce

It seems conversations adds this to its presence

```
<x xmlns='vcard-temp:x:update'>
<photo/>
</x>
```
while this is technically true, there is no avatar in the vcard storage, this

```
<presence>
  <x xmlns='vcard-temp:x:update'/>
</presence>
```

would be more appropriate, as conversations publishes the avatar on pubsub

This is a minor inconvenience for Clients who support both protocols, as the presence always reaches the Client first, then i remove the Avatar from the Roster, and 2 seconds later the PEP Event arrives and i have to add it again.

This is also mentioned in the XEP

```Note: This enables recipients to distinguish between the absence of an image (empty photo element) and mere support for the protocol (empty update child).```

**Comment by iNPUTmice** [comment]
I don't think Conversations adds this.
Maybe some servers do.

**Comment by lovetox** [comment]
do you have this pep to vcard avatar extension on gultsch.de installed?

**Comment by iNPUTmice** [comment]
> do you have this pep to vcard avatar extension on gultsch.de installed?

No. But I think there is an ejabberd module that adds the vcard avatar hash to outgoing presence.
