### ISSUE TITLE
File transmission fails first time alone

### ISSUE THREAD

**Issue by nee2shaji** [siacs/Conversations#2666]
#### General information

* **Version:** 1.21.0
* **Device:** Google Nexus 5
* **Android Version:** Android 7.1 (API 25)
* **Server name:** self hosted
* **Server software:** openfire
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

In config.java, DOMAIN_LOCK="XXXX" and registration in UI is disallowed.
No conversations user files/folders exist and the APK is installed for the first time.
1. Login from two devices (APK is installed for the first time) 
2. Send an image from one device to another.
3. "Delivery Failed" at the sender side and "File transmission failed" at the receiver end.
4. Try to send image again. It works.

#### Expected result

Image should be transmitted the first time.

#### Actual result

"Delivery Failed" at the sender side and "File transmission failed" at the receiver end.
Image transfer happens successfully the second time onwards. Same issue happens in the case of file transfer too.

#### Debug output

[log.txt](https://github.com/siacs/Conversations/files/1415771/log.txt)

**Comment by licaon-kter** [comment]
Unencrypted? OMEMO?

**Comment by nee2shaji** [comment]
Unencrypted..

**Comment by iNPUTmice** [comment]
Please check if 396ad3361f41a11d06164be56f31f660dc6a43be fixes the issue for you.

**Comment by iNPUTmice** [comment]
Closing due to lack of communication by op.
