### ISSUE TITLE
Error reporting for HTTP Upload could be more helpful

### ISSUE THREAD

**Issue by devurandom** [siacs/Conversations#2667]
#### General information

* **Version:** 1.21.0
* **Device:** Samsung Galaxy S4 Mini LTE (serranoltexx)
* **Android Version:** LineageOS 14.1 (Android 7.1.2)
* **Server name:** self hosted
* **Server software:** Prosody 0.10
* **Installed server modules:** Stream Managment, CSI, MAM, HTTP Upload and more
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Unknown
2. Send file to contact
3. See text like "offering" and an ultra slow transmission that gets interrupted when someone goes offline
4. Observe that no new HTTP Upload directory is being created for this file

#### Expected result

I would expect there to be a more accurate explanation of why `HTTP Upload: available` in `Manage Accounts > [Account] > Server Info` does not lead to a HTTP upload.  Maybe, upon ticking `Server Info`, Conversations could create a test connection to the server.

Also, it would be nice, if the maximum supported file size would be displayed in `Server Info`.

#### Actual result

A very slow file transmission and the other side has to accept the file transfer, which should not happen, if HTTP Upload was actually working.

#### Debug output

```
http upload is not available for files with size 8963975 (max is 1048576)
```

**Comment by iNPUTmice** [comment]
The server info is not really meant for server admins to debug their server. If anything that's what the adb logcat output is for.

**Comment by devurandom** [comment]
While it needed me as a server admin to figure out that there is an (unreasonably low) size limit on files transmitted using HTTP Upload, I think that regular users would benefit from that info, too. If they were told "the size limit for fast and nice file transfers is 10 MiB", they might adjust their behaviour accordingly. If file transfers are just unreasonably cumbersome and slow for unknown and apparently random reasons, they might get annoyed and think "WhatsApp was nicer". I doubt many people will think "something must be wrong, let me debug this together with the server admin for fifteen minutes".

**Comment by licaon-kter** [comment]
@iNPUTmice Since the client knows the this limitation, can't it be shown in the lonpress-error message?

**Comment by devurandom** [comment]
> @iNPUTmice Since the client knows the this limitation, can't it be shown in the lonpress-error message?

There is no error message, since Conversations falls back to Jingle or in-band transmission of the file.
