### ISSUE TITLE
BadPaddingException when sending files to odler versions using OTR

### ISSUE THREAD

**Issue by horin** [siacs/Conversations#2668]
#### General information

* **Version:** 1.21.0 - 1.17.0
* **Device:** Google Nexus 5x
* **Android Version:** Android 8.0 Stock and Android 6.0 Stock
* **Server software:** ejabberd 16.04
* **Conversations source:** self build (latest HEAD)

Recently we have switched from relatively old build (from March 2017) to the latest build and we are unable to send files through OTR encrypted messages. When sending from older version (1.17.0) to newer (1.21.0) logs says that there is `javax.crypto.BadPaddingException:     Decryption error`. When sending from newer to older it looks like last message data part never gets send because session is killed just before that. For example if sending small files (80 bytes) sending device says 0% progress, receiving device says 83% progress and it halts just there.

Was there any commit in past which removed backward file sending compatibility while using OTR?

This is the exception caught in receiving device (newer):

**Comment by iNPUTmice** [comment]
Yes. This is a known lack of backward compatibility. Use the chance to stop using OTR in favour of OMEMO.
