### ISSUE TITLE
The connection is probably killed by the operating system even if a persistent notification is displayed.

### ISSUE THREAD

**Issue by marmistrz** [siacs/Conversations#2669]
A bug observed on a device belonging to a friend of mine, @taki-jaro

#### General information

* **Version:** 1.21.0
* **Device:** Xiaomi Redmi 4X
* **Android Version:** Android 6.0.1
* **Server name:** dismail.de
* **Server software:** unknown
* **Installed server modules:** unknown
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Launch Conversations
2. Make sure that foreground service option is enabled
3. Move to other activities, use other apps

#### Expected result
The user is online all the time

#### Actual result
When observing the user's status from another device with an account on wiuwiu.de, the contact becomes offline after a few minutes.

#### Debug output

I'm not the device owner, so I can't post the logcat myself.

**Comment by licaon-kter** [comment]
Tell your friend to do the 5 magic spells, and pray: https://www.forbes.com/sites/bensin/2016/11/17/how-to-fix-push-notifications-on-xiaomis-miui-8-for-real/

**Comment by iNPUTmice** [comment]
Support requests are better handled in the group chat and not on the issue tracker.

**Comment by marmistrz** [comment]
I rather thought about it rather like: _Android started doing some new nasty thing and expects the apps to accommodate_, hence reported it here. I'm not watching the new "features" of Android actively.

**Comment by licaon-kter** [comment]
@marmistrz Not Android, but Xiaomi

**Comment by marmistrz** [comment]
@licaon-kter Yeah, now I know, I just explained what I had thought when I reported the issue.
