### ISSUE TITLE
Conversations unusable after typing a certain message

### ISSUE THREAD

**Issue by rtomanek** [siacs/Conversations#2670]
#### General information

* **Version:** 1.20.1
* **Device:** Samsung Galaxy S7
* **Android Version:** Android 7.0 Stock
* **Server name:** self hosted
* **Server software:** prosody 0.10, latest
* **Installed server modules:** 0191, 0198, 0237, 0280, 0313, 0352, 0363
* **Conversations source:** self build 

#### Steps to reproduce

1. Type: "💙💚💫💥🍇🍒🍓🍌🍉🍊🍏🍎🍃🍃🍂🌹🥀🌷🏵️💮🌸💐🌷🍁🌺🌴🌵🌾🌿☘️🍀🍁🐙🦋🐉🐳🐋🐬🐟🐠🐡🐌🕸️🕷️🦉🐘👑💎👡👠👟🎓🗻🌋💒🕍🕌🗽🎠🎠🌌🎡💈🎨⛺⛲🌑🌒🌓🌔🌕🌖🌗🌞🌠🌡️☀️🌛🌜🌙⭐🌟⛅🌩️🌨️🌧️🌦️🌥️🌤️⛈️☁️⚡❄️☃️☄️☄️☂️🌂🌈🌀🌀🌫️🌪️☔💧🌊🌊🎃🎄🎇🎇✨🎈🎉🎊🎋🎍🎎🎏🎐🎑🎀🎁🎗️🎫🎫🎖️🏆🎱🎾♦️♥️🃏🎮🎵🎶🎷🎧🎧📯🎚️🎹📀💿🥁🎻🎺🕯️🔮🗝️🔑🦄🐩⚓🛤️🚛🚙🚖🚕🚕🚖🚘🚘🚙🚚🚛🚜🚲🛴🛵🚏🛣️🛤️⛽🚨🚥🚦🚧🛑⚓🍇🍈🍉🍊🍋🍌🍍🍎🍏🍑🍑🍒🍓🍓🥝🍅🥑🥔🍆🍆🥔🥕🌽🌶️🥞🍕🍔🍟🥐🥖🍳🍳🥙🌯🥓🥐🥐🍞🍖🌯🌮🌭🍕🌯🥒🍄🥜🌰🍞🥐🥖🥞🧀🍖🍗🥓🍟🍟🍕🌭🌮🌯🥙🥚🍳🥘🍲🥗🍿🍱🍘🍙🍚🍛🍜🍝🍠🍢🍣🍤🍥🦌🐮🐮🐂🐃🐵🐒🦍🐶🐕🐩🐺🦊🐱🐈🦁🐯🐯🐅🐆🐴🐎🦄🦌🐮🐂🐃🐄🐖🐗🐽🐏🐑🐐🐪🐫🐘🦏🐭🐁🐀🐹🐇🐇🐿️🦇🐻🐨🐤🦉🐼🐥🐸🐾🐦🐊🦃🐧🐢🦃🐧🐢🐔🕊️🦎🐓🦅🐍🐣🦆🐲🐉🦈🦋🐙🐛🐋🐚🐜🐬🦀🐝🐟🦐🐞🐠🦑🕷️🐡🐌🕸️🦂🌺🌴💐🌻🌵🌸🌼💮🌷🌾🌿🏵️🌱☘️🌹🌲🍀🥀🌳🍁🍂🍃🍇🍎🍅🍈🍏🥑🍉🍐🍆🍑🍑🥔🍋🍒🥕🍌🍓🌽🍍🥝🌶️🥒🥞🍕🍄🧀🌭🍖🌮🌰🍗🌯🍞🍔🥙🥐🥐🍔🥚🥖🍟🍳🥖🥘🍚🍤🍲🍛🍥🥗🍜🍡🍿🍝🍦🍱🍠🍧🍘🍢🍨🍙🍣🍩🍪🍯🍷🎂🥛🍸🍰🥛🍼🍹🍫☕🍺🍬🍵🍻🍭🍶🥂🍮🍾🥃🍽️🍴🥄🔪🏺🌍⛰️🏞️🌎🌋🏟️🌏🗻🏛️🌐🏕️🏗️🗺️🏖️🏘️🗾🏜️🏙️🏔️🏝️🏚️🏠🏨🏰🏡🏩💒🏢🏪🗼🏣🏫🗽🏤🏤🏬⛪🏥🏭🕌🏦🏯🕍⛩️🌅🎡🕋🌆🎢🌇⛲🌇💈⛺🌉🎪🌉🌁♨️🎭🌃🌌🖼️🌄🎠🎨🎰🚈🚍🚂🚉🚐🚃🚊🚐🚅🚝🚑🚅🚞🚒🚆🚋🏧🚼🚸🚮🚾⛔🚰🛂🚫♿🛃🚳🚹🛄🚭🚺🛅🚯🚻⚠️🚱📵➡️↔️📵↘️↩️🔞⬇️↪️☢️↙️↙️⤴️☣️⬅️📣🔇🔔🎛️🔈🔕🎤🔉🎼🎧🔊🎵📻📢🎶🎷📣🎙️🎸📯🎚️🎹🎺📟⌨️🎻📠🖱️🥁🔋💽📱🔌💽📲💻💾☎️🖥️💿📞🖨️📀🎥📹📹☎️🔋🎥💾🥁📀💻📠🖨️📲📠📞📞💽🎻💿🔌⌨️🖥️📱📟😀😆😙😁😉😚😂😊😚🤣😋☺️😃😎🙂🤗😍😄😅😘🤔😐😮😛😑🤐😜🙄😯😝😑🤐😜😶😯😝😏🙄😪🤤😒😣😫😓😣😴😓😥😌😔😕😞😨🙃😟😟🦍🐈🎷㊙️◽🔹🈺◾🔺🈵⬛🔻▪⬜💠▫️🔶🔘◻️🔷🔲🔲◼️🎯🕹️🀄⛳🎲🎴⛸️♠️🎣♥️🎽♦️🎿♣️🎮🃏⛳🏅🏐🏑🥇🏈🏒🥈🏉🏓🥉🎾🏸⚽🥊🥊⚾🎳🥋🏀🏏🥅🎃🎊🎀🎄🎋🎁🎁🎆🎍🎗️🎇🎎🎟️✨🎏🎫🎈🎐🎖️🎉🎑🏆🌪️☔🔥🌫️⛱️💧🌬️⚡🌊⚡🌀❄️🌈☃️🌂⛄☂️☄️🌘🌝⛈️🌙🌞🌥️🌚⭐🌚⭐🌥️🌛🌟🌦️🌜🌠🌧️🌡️☁️☁️🇦🇺🏁🇦🇩🇦🇴🚩🇦🇪🇦🇶🎌🇦🇫🇦🇫🏴🇦🇬🇦🇬🇦🇷🇦🇷🇦🇸🇦🇶🇦🇸🇦🇬🏴🏳️🇦🇮🇦🇹🇦🇹🏳️‍🌈🇦🇱🇦🇺🇦🇨🇦🇲🇦🇼🇦🇿🇧🇭🇧🇶🇦🇽🇧🇬🇧🇴🇧🇦🇧🇮🇧🇷🇧🇧🇧🇯🇧🇸🇧🇩🇧🇱🇧🇹🇧🇪🇧🇲🇧🇼🇧🇫🇧🇾🇧🇳🇧🇾🏁🚩🎌🏴🏳️🏳️🏳️‍🌈🇦🇨🇦🇩🇦🇪🇦🇫🇦🇬🇦🇮🇦🇱🇦🇲🇦🇲🇦🇴🇦🇶🇦🇷🇦🇸🇦🇸🇦🇹🇦🇺🇦🇺🇦🇼🇦🇼⚪⚫🔴🔵🇧🇿🇨🇮🇨🇺🇨🇦🇨🇰🇨🇻🇨🇨🇨🇱🇨🇼🇨🇩🇨🇲🇨🇽🇨🇫🇨🇳🇨🇾🇨🇬🇨🇴🇨🇿🇨🇭🇨🇷🇦🇽🇧🇬🇧🇴🇦🇿🇧🇶🇧🇮🇧🇭😂😊😊🇨🇭😊👽🤓🤢👹🤡🤖💩🤰🎅👼🔸🔳🆖🈁🈚🅾️🈂️🈲🆗🈷️🉑🅿️🈶⛰️🌐💲📩📭🖌️📨📬💉🔮⛓️🛢️🔗🗿⚖️⚱️⚗️⚰️🗜️🚬⚙️💊🛒💉🔮🔏🔩🔩🔓⚒️🔧🔒⛏️🛡️🗑️🔨🏹🗑️🗝️🔫🗃️🔑⚔️✂️🔐🗡️📅📊🗂️📉📏🗂️📈🖇️📁📇📎💼🗓️📍🗒️🗒️📌🖍️📆📋🎯🕹️🀄⛳🎲🎴⛸️♠️🎣♥️🎽♦️🎿♣️🎮🃏🐻🐘🐙🐚🌷🎃🎄🎆🎇✨🎈🎉🎊🎋🎍🎎🎏🎐🎑🎀🎁🎟️🎟️🎫🎖️🏆🍽️🍴🥄🏺🕌🕍🌌🎠🎨🎨⛺🌁🌅🌆🌆🌇🌉🚞🚉🚄🚋"
2. Yeah, this really happened, my daughter was trying to be sweet and did that :)

#### Expected result

The message gets sent.

#### Actual result

Message status is "Sending...", unable to send any further messages -- Conversations is stuck, I am no longer able to send any messages. Receiving messages works fine, carbons for messages sent from other clients work fine.

**Comment by iNPUTmice** [comment]
Works for me (if you ignore the fact that font rendering is a bit slow). Please post logcat (Maybe a policy violation on the server)

**Comment by rtomanek** [comment]
Please find attached the log from the stuck client, right from device boot.

[conversations-emoji-1-anonymised.log](https://github.com/siacs/Conversations/files/1428964/conversations-emoji-1-anonymised.log)

Server log doesn't seem to include anything out of the ordinary.

**Comment by rtomanek** [comment]
I've compiled a debug version of conversations, haven't noticed anything of interest in the log. 

Enabled debug output for prosody -- same. 

Is conversations trying to resend the offending message at all?

Secondly, I noticed the message above was cut due to a limitation somewhere in my transfer process (5 symbols missing at the end). This looks like a more complete thing:
"💙💚💫💥🍇🍒🍓🍌🍉🍊🍏🍎🍃🍃🍂🌹🥀🌷🏵️💮🌸💐🌷🍁🌺🌴🌵🌾🌿☘️🍀🍁🐙🦋🐉🐳🐋🐬🐟🐠🐡🐌🕸️🕷️🦉🐘👑💎👡👠👟🎓🗻🌋💒🕍🕌🗽🎠🎠🌌🎡💈🎨⛺⛲🌑🌒🌓🌔🌕🌖🌗🌞🌠🌡️☀️🌛🌜🌙⭐🌟⛅🌩️🌨️🌧️🌦️🌥️🌤️⛈️☁️⚡❄️☃️☄️☄️☂️🌂🌈🌀🌀🌫️🌪️☔💧🌊🌊🎃🎄🎇🎇✨🎈🎉🎊🎋🎍🎎🎏🎐🎑🎀🎁🎗️🎫🎫🎖️🏆🎱🎾♦️♥️🃏🎮🎵🎶🎷🎧🎧📯🎚️🎹📀💿🥁🎻🎺🕯️🔮🗝️🔑🦄🐩⚓🛤️🚛🚙🚖🚕🚕🚖🚘🚘🚙🚚🚛🚜🚲🛴🛵🚏🛣️🛤️⛽🚨🚥🚦🚧🛑⚓🍇🍈🍉🍊🍋🍌🍍🍎🍏🍑🍑🍒🍓🍓🥝🍅🥑🥔🍆🍆🥔🥕🌽🌶️🥞🍕🍔🍟🥐🥖🍳🍳🥙🌯🥓🥐🥐🍞🍖🌯🌮🌭🍕🌯🥒🍄🥜🌰🍞🥐🥖🥞🧀🍖🍗🥓🍟🍟🍕🌭🌮🌯🥙🥚🍳🥘🍲🥗🍿🍱🍘🍙🍚🍛🍜🍝🍠🍢🍣🍤🍥🦌🐮🐮🐂🐃🐵🐒🦍🐶🐕🐩🐺🦊🐱🐈🦁🐯🐯🐅🐆🐴🐎🦄🦌🐮🐂🐃🐄🐖🐗🐽🐏🐑🐐🐪🐫🐘🦏🐭🐁🐀🐹🐇🐇🐿️🦇🐻🐨🐤🦉🐼🐥🐸🐾🐦🐊🦃🐧🐢🦃🐧🐢🐔🕊️🦎🐓🦅🐍🐣🦆🐲🐉🦈🦋🐙🐛🐋🐚🐜🐬🦀🐝🐟🦐🐞🐠🦑🕷️🐡🐌🕸️🦂🌺🌴💐🌻🌵🌸🌼💮🌷🌾🌿🏵️🌱☘️🌹🌲🍀🥀🌳🍁🍂🍃🍇🍎🍅🍈🍏🥑🍉🍐🍆🍑🍑🥔🍋🍒🥕🍌🍓🌽🍍🥝🌶️🥒🥞🍕🍄🧀🌭🍖🌮🌰🍗🌯🍞🍔🥙🥐🥐🍔🥚🥖🍟🍳🥖🥘🍚🍤🍲🍛🍥🥗🍜🍡🍿🍝🍦🍱🍠🍧🍘🍢🍨🍙🍣🍩🍪🍯🍷🎂🥛🍸🍰🥛🍼🍹🍫☕🍺🍬🍵🍻🍭🍶🥂🍮🍾🥃🍽️🍴🥄🔪🏺🌍⛰️🏞️🌎🌋🏟️🌏🗻🏛️🌐🏕️🏗️🗺️🏖️🏘️🗾🏜️🏙️🏔️🏝️🏚️🏠🏨🏰🏡🏩💒🏢🏪🗼🏣🏫🗽🏤🏤🏬⛪🏥🏭🕌🏦🏯🕍⛩️🌅🎡🕋🌆🎢🌇⛲🌇💈⛺🌉🎪🌉🌁♨️🎭🌃🌌🖼️🌄🎠🎨🎰🚈🚍🚂🚉🚐🚃🚊🚐🚅🚝🚑🚅🚞🚒🚆🚋🏧🚼🚸🚮🚾⛔🚰🛂🚫♿🛃🚳🚹🛄🚭🚺🛅🚯🚻⚠️🚱📵➡️↔️📵↘️↩️🔞⬇️↪️☢️↙️↙️⤴️☣️⬅️📣🔇🔔🎛️🔈🔕🎤🔉🎼🎧🔊🎵📻📢🎶🎷📣🎙️🎸📯🎚️🎹🎺📟⌨️🎻📠🖱️🥁🔋💽📱🔌💽📲💻💾☎️🖥️💿📞🖨️📀🎥📹📹☎️🔋🎥💾🥁📀💻📠🖨️📲📠📞📞💽🎻💿🔌⌨️🖥️📱📟😀😆😙😁😉😚😂😊😚🤣😋☺️😃😎🙂🤗😍😄😅😘🤔😐😮😛😑🤐😜🙄😯😝😑🤐😜😶😯😝😏🙄😪🤤😒😣😫😓😣😴😓😥😌😔😕😞😨🙃😟😟🦍🐈🎷㊙️◽🔹🈺◾🔺🈵⬛🔻▪⬜💠▫️🔶🔘◻️🔷🔲🔲◼️🎯🕹️🀄⛳🎲🎴⛸️♠️🎣♥️🎽♦️🎿♣️🎮🃏⛳🏅🏐🏑🥇🏈🏒🥈🏉🏓🥉🎾🏸⚽🥊🥊⚾🎳🥋🏀🏏🥅🎃🎊🎀🎄🎋🎁🎁🎆🎍🎗️🎇🎎🎟️✨🎏🎫🎈🎐🎖️🎉🎑🏆🌪️☔🔥🌫️⛱️💧🌬️⚡🌊⚡🌀❄️🌈☃️🌂⛄☂️☄️🌘🌝⛈️🌙🌞🌥️🌚⭐🌚⭐🌥️🌛🌟🌦️🌜🌠🌧️🌡️☁️☁️🇦🇺🏁🇦🇩🇦🇴🚩🇦🇪🇦🇶🎌🇦🇫🇦🇫🏴🇦🇬🇦🇬🇦🇷🇦🇷🇦🇸🇦🇶🇦🇸🇦🇬🏴🏳️🇦🇮🇦🇹🇦🇹🏳️‍🌈🇦🇱🇦🇺🇦🇨🇦🇲🇦🇼🇦🇿🇧🇭🇧🇶🇦🇽🇧🇬🇧🇴🇧🇦🇧🇮🇧🇷🇧🇧🇧🇯🇧🇸🇧🇩🇧🇱🇧🇹🇧🇪🇧🇲🇧🇼🇧🇫🇧🇾🇧🇳🇧🇾🏁🚩🎌🏴🏳️🏳️🏳️‍🌈🇦🇨🇦🇩🇦🇪🇦🇫🇦🇬🇦🇮🇦🇱🇦🇲🇦🇲🇦🇴🇦🇶🇦🇷🇦🇸🇦🇸🇦🇹🇦🇺🇦🇺🇦🇼🇦🇼⚪⚫🔴🔵🇧🇿🇨🇮🇨🇺🇨🇦🇨🇰🇨🇻🇨🇨🇨🇱🇨🇼🇨🇩🇨🇲🇨🇽🇨🇫🇨🇳🇨🇾🇨🇬🇨🇴🇨🇿🇨🇭🇨🇷🇦🇽🇧🇬🇧🇴🇦🇿🇧🇶🇧🇮🇧🇭😂😊😊🇨🇭😊👽🤓🤢👹🤡🤖💩🤰🎅👼🔸🔳🆖🈁🈚🅾️🈂️🈲🆗🈷️🉑🅿️🈶⛰️🌐💲📩📭🖌️📨📬💉🔮⛓️🛢️🔗🗿⚖️⚱️⚗️⚰️🗜️🚬⚙️💊🛒💉🔮🔏🔩🔩🔓⚒️🔧🔒⛏️🛡️🗑️🔨🏹🗑️🗝️🔫🗃️🔑⚔️✂️🔐🗡️📅📊🗂️📉📏🗂️📈🖇️📁📇📎💼🗓️📍🗒️🗒️📌🖍️📆📋🎯🕹️🀄⛳🎲🎴⛸️♠️🎣♥️🎽♦️🎿♣️🎮🃏🐻🐘🐙🐚🌷🎃🎄🎆🎇✨🎈🎉🎊🎋🎍🎎🎏🎐🎑🎀🎁🎟️🎟️🎫🎖️🏆🍽️🍴🥄🏺🕌🕍🌌🎠🎨🎨⛺🌁🌅🌆🌆🌇🌉🚞🚉🚄🚋🚌🚓🚞🚊🚉"

I am also attaching a raw file (share text on message -> save to Google Drive).
[conversations-message-of-death️.txt](https://github.com/siacs/Conversations/files/1430336/conversations-message-of-death.txt)

Export history from Settings -> Advanced doesn't include this message, unfortunately.

**Comment by iNPUTmice** [comment]
The longer message works fine for me as well.

> Is conversations trying to resend the offending message at all?

Yes.

**Comment by rtomanek** [comment]
Hmm, in this case I am now interested the most in making this conversations installation usable again. 

How do I go about that without having to clear data and starting from scratch?

Is there any way to either remove the offending message or manually acknowledge it so that it no longer blocks the queue for subsequent messages?

**Comment by licaon-kter** [comment]
Delete conversation - reopen (but you'll lose past messages)

Else #2267

**Comment by rtomanek** [comment]
Thank you. 

Erasing history is something I want to avoid at all costs.

The issue is now "solved" -- I can use this installation again.

For anyone looking to solve this in the future: after looking at conversations code and logs I disabled smacks, mam, mam_archive, csi modules in prosody server, plus all reasonably looking message ack options in conversations as these were likely the culprits -- this helped.

I was lucky as I own the server and can easily tweak the config. 

The other clients I use (mostly Miranda NG) implement message resending timeouts, it would make sense to have something like this for conversations as well I feel.

BTW, there's a similar issue with PEP (a particular dataset makes conversations unable to send messages).
