### ISSUE TITLE
move privacy options to expert settings

### ISSUE THREAD

**Issue by traumal** [siacs/Conversations#2671]
A number of less savvy contacts have opened options and disabled most of the interactive presence features negating much of the value of xmpp.  Please consider either moving these to the bottom, or better yet moving them to expert settings.

**Comment by licaon-kter** [comment]
Which options? Remember that most are off by default.

**Comment by LegacyTextingCosts** [comment]
I have this issue with some contacts as well - given that I have both purchased the app for them and configured it.  Original Poster likely refers to the first 5 checkboxes in settings. I check all 5. This _configuration_ _ought_ _be_ _the_ _default_.  

💮grant presence
💮confirm messages [are read]
💮typing notifications 
💮broadcast last user interaction

Also I set the 💮"send button indicates status".  

Then in expert settings I enable:

💮allow message correction

💮show enter key

💮set away when screen is off
