### ISSUE TITLE
Unauthorized when connecting

### ISSUE THREAD

**Issue by shah-95** [siacs/Conversations#2675]
Unauthorized error when connecting to nimbuzz, even when password is correct, checked multiple accounts and all have same issue

Version: 1.21.0
Device: Samsung Galaxy S7 Edge
Android Version: Android 7.0 Stock
Server name: nimbuzz.com
Server software: unknown
Installed server modules: don't know
Conversations source: F-Droid

#### Steps to reproduce

1. Login any nimbuzz id on conversations

#### Expected result

Conversations should connect to the server as bombusmod and miranda on pc are connecting.

#### Actual result

Unauthorised error, when password is correct.

**Comment by iNPUTmice** [comment]
It used to work in the past but seems like Nimbuzz are trying increasingly hard to lock out external apps. You are welcome to try to patch this yourself and create a PR but I'm not willing to waste my time trying to make proprietary services work that are deliberately trying to lock us out.

**Comment by shah-95** [comment]
Sir if you could give me any steps to patch it myself i will much appreciate. Thanks and yeah they suck big time by locking out good apps.
