### ISSUE TITLE
[Thinking] Study if the price can be a drag for new users

### ISSUE THREAD

**Issue by Postroutine** [siacs/Conversations#2678]
Since I try to convince my friends and family members tu use Jabber and Conversation, there is always something that stop them: The application is not free. 

With WhatsApp and other internet messaging app, people seems to consider their free access as acquired.

I know people around me are not representative of all (potential) users, but it could be interesting to study if the price of Conversation is really a drag for new users. Conversation need money, but if paying for it can convince some users to not use it, maybe think to another way to get it.

**Comment by licaon-kter** [comment]
FYI
There was this: https://twitter.com/iNPUTmice/status/898791518252781568
And then this: https://twitter.com/iNPUTmice/status/899192770539261952

**Comment by iNPUTmice** [comment]
This has been discussed many times before. (Search the issue tracker)
