### ISSUE TITLE
Round avatars in the chat window and across the app

### ISSUE THREAD

**Issue by tdemin** [siacs/Conversations#2681]
https://material.io/guidelines/style/icons.html#icons-app-shortcut-icons

See "Single avatars". Material Design guidelines propose avatars to be round. And yes, rounded avatars just look better. 😉

**Comment by mimi89999** [comment]
I could try to work on it.

**Comment by LegacyTextingCosts** [comment]
I _greatly_ prefer square icons.  There is less tinkering in GIMP required to predict the appearance.

**Comment by iNPUTmice** [comment]
Seems a lot of people in the chat room (myself included) prefer the square avatars.

**Comment by tdemin** [comment]
@LegacyTextingCosts you don't need to do anything with GIMP if the rounded preview of your avatar is shown before you set it.

**Comment by tdemin** [comment]
@iNPUTmice looks like Conversations will never be ready for Material Design. 😕

**Comment by d9h20f** [comment]
Luckily Material Design is ugly beyond belief and will be completely dropped by Google in a couple of years, as always.

**Comment by licaon-kter** [comment]
@tdemin Like round icons would matter for those 72% of Android users that will never even get Android 7.

**Comment by uchchishta** [comment]
## This is Material Design?
![](https://lut.im/WOFuU86jMr/Pckf3FjKAsbseh40)
![](https://www.theandroidsoul.com/wp-content/uploads/2017/05/AndroidO_emojis.png)
![](https://www.androidpolice.com/wp-content/uploads/2016/11/nexus2cee_Evolution-of-Google-App-Icons-1.jpg)
**material design is a guideline not a rule. You can't have non round avatars at all, no custom PNG avatars. But as it is now you _can_ upload a circle cropped avatar if one wants**
