### ISSUE TITLE
Facebook-transported groupchat messages are not detected as delivered, thus repeated, leading to flooding the groupchat

### ISSUE THREAD

**Issue by truenicoco** [siacs/Conversations#2684]
#### General information

* **Version:** 1.21.0
* **Device:** Honor 5X
* **Android Version:** LinageOS 14.1-20171101-NIGHTLY-kiwi
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** facebook transport via spectrum/libpurple-facebook, MAM, carbon
* **Conversations source:** F-Droid

#### Steps to reproduce

Send a message to a Facebook transported group chat.

#### Expected result

The message being sent once.

#### Actual result

The message is still tagged "sending…", and sent multiple times, at irregular intervals (real case example: 08:35:52,768, 08:47:55,288, 09:32:38,058, 10:01:57,944 and 11:56:12,296). It can be read in Conversations, but as if sent by another user. It looks like Conversations doesn't realize that my Jabber Account and my Facebook Name are the same person, i.e., me. Single user chat works fine. After a while, the message is tagged as "failed delivery" and stops being sent.

After some investigation, I concluded it is a Conversations issue because none of these problems occur when using Gajim, at least for the short time I've been experimenting.

#### Debug output

Prosody, spectrum, and libpurple-facebook logs show nothing unusual, except the message being sent multiple times.

I don't have the tools or knowledge to do android debugging for now. I'll investigate this later if needed.

If only I could get facebook transport to work properly, I'm sure I would bring many new users to Conversations… then we'll all ditch Facebook eventually! :)

**Comment by iNPUTmice** [comment]
What's probably happening is that the Facebook transport assigns you a different nick name than the one you are trying to join with.
Meaning you are trying to join as `truenicoco` but the transport reassigns you the nick `foobar`. That's fine in theory however it might be that Conversations doesn't recognize that reassignment. To stick with this example this would probably show as the user `foobar` being shown in the list of participants when you open the conference details.

To debug this i need the join presence and all the presences the transport sends in return. You can probably get those with the Gajim console.

**Comment by truenicoco** [comment]
I think I have it. I disconnected from the group chat, opened gajim XML console, hid everything but Presence st. Then I opened the group chat again, and even sent a message just to be sure. I have a quite long log, I'm not sure what is relevant and/or confidential. Is it OK if I send it to you by email?

**Comment by truenicoco** [comment]
Interesting fact I just noticed: in Gajim, I also appear twice in the participant list (jabber name and facebook name). When I post a message, it doesn't appear perfectly as if I was mine (I have a specific color set for my own messages). However, they aren't sent multiple times and it's not that big of a deal, i.e., it doesn't make everybody hate me on my group chats.

**Comment by iNPUTmice** [comment]
For reference after looking at the stanzas: Spectrum doesn't rename you. So you join as `truenicoco` and spectrum doesn't rename you to `foobar`. However reflected messages are coming from `foobar`. So spectrum should either rename you on join to `foobar` or reflect messages back to as coming from `truenicoco`.

Hint to the spectrum developers: Renaming on join is pretty easy. Instead of `<presence from='room/truenicoco'><status code='110'/></presence>` you just send `<presence from='room/foobar'><status code='110'/></presence>` instead. Modern clients can use the status to recognize that this is their own presence and that a rename has happened.

**Comment by linkmauve** [comment]
Status code 210 should also be used in that case, to signal the room modified the nick, fyi.

**Comment by truenicoco** [comment]
For reference this was fixed in spectrum: https://github.com/SpectrumIM/spectrum2/commit/401deee43baac1b0102438b414501188e39dd7ff
