### ISSUE TITLE
OTR and multiple clients

### ISSUE THREAD

**Issue by ericbodden** [siacs/Conversations#2685]
I am using the current build of Conversation on Android.

#### Steps to reproduce

Start an OTR conversation on _another_ client. (I am using Adium on OSX.)

#### Expected result

The conversation should be shown decrypted also in _Conversation_.

#### Actual result

An OTR encrypted conversation, i.e., gibberish.

According to this message it should be possible to make this work:
https://lists.cypherpunks.ca/pipermail/otr-users/2012-September/002071.html

**Comment by iNPUTmice** [comment]
No this message is wrong. Read more about it here: https://github.com/siacs/Conversations/blob/master/docs/observations.md or even better start using OMEMO.
