### ISSUE TITLE
Bug with Chrome tabs

### ISSUE THREAD

**Issue by jugendhacker** [siacs/Conversations#2687]
When I open a link from Conversations it always opens in the same tab. So when I open a second link it opens in the tab of the first and not in a second tab!

**Comment by iNPUTmice** [comment]
Please fill in the issue template and provide details regarding your phone and operating system (Android version).

**Comment by jugendhacker** [comment]
#### General information

* **Version:** 1.21.0
* **Device:** LG K8 LTE
* **Android Version:** eg Android 6.0 stock
* **Server name:** wiuwiu.de
* **Server software:** prosody
* **Installed server modules:** I don't know
* **Conversations source:** f-droid


#### Steps to reproduce

1. Click on a link
2. Open another link
3. It opens in the same tab


#### Expected result

It should open in a other tab!


#### Actual result

It opens in the same tab and I can't see the Website I opened bevor!


#### Debug output

I can't do this in the moment so I can't see the output.

````
adb logcat -s conversations
````

**Comment by jugendhacker** [comment]
Sorry I mean I have a Android 6.0 Stock (without the eg)

**Comment by licaon-kter** [comment]
Conversations version 1.2**1** not 1.2**2** ?

**Comment by jugendhacker** [comment]
@licaon-kter Version 1.21 (1.22 isn't available on f-droid)

**Comment by licaon-kter** [comment]
Indeed, missed it in your report.

**Comment by jugendhacker** [comment]
No I wrote it in the report

**Comment by licaon-kter** [comment]
Indeed, (I) missed it in your report.

**Comment by jugendhacker** [comment]
Aha ok but that doesn't solves the bug!

**Comment by Kandr0s** [comment]
I'm using 1.22 and it works as intended. Every Click on a link opens a new Tab in my Chrome App.

**Comment by jugendhacker** [comment]
@Kandr0s OK but I didn't get the 1.22 from f-droid in the moment so I can't test!

**Comment by iNPUTmice** [comment]
Please check with 1.22.0

**Comment by jugendhacker** [comment]
It's still not working! Also not with Firefox!

**Comment by iNPUTmice** [comment]
Sorry I meant to say 1.22.1

**Comment by jugendhacker** [comment]
it isn't on f-droid

**Comment by licaon-kter** [comment]
It was pulled, but it depends on Gradle 4.3.1 and that was not yet deployed, so for [now it fails to compile](https://f-droid.org/wiki/page/eu.siacs.conversations/lastbuild_240).

**Comment by jugendhacker** [comment]
Ok

**Comment by licaon-kter** [comment]
Seeing this in 1.22.**0**, always opens first tab in Firefox.

But, looks like it works ok in 1.22.**1**, thanks.

**Comment by jugendhacker** [comment]
OK I will try it when I can get the 1.22.1 from f-droid!

**Comment by licaon-kter** [comment]
Here is a [test build](
https://mega.nz/#!4MAXURgB!8YnoeFqsEzYmfTfjlt-6I9k2BahYMxqvgsS6D3FoXFU) that I made for #2698. (It has a different name and ID so it won't overwrite you current Conversations)

**Comment by harshitbansal05** [comment]
I am currently using version 1.23.3 and opening a link from Conversations opens it on the same chrome tab. Phone: Xiaomi Redmi Note 3(Android: 5.1.1)
Can I work on this?

**Comment by iNPUTmice** [comment]
@harshitbansal05 yes.
