### ISSUE TITLE
Gradle version needed for forTasks() method

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2688]
#### General information
* **Version:** 1.22.0
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce
1. Android Studio 3
2. Build

#### Actual result
```
Error:Failed to complete Gradle execution.

Cause:
The version of Gradle you are using (3.3) does not support the forTasks() method on BuildActionExecuter. Support for this is available in Gradle 3.5 and all later versions.
```

#### Fix
[Here](https://github.com/siacs/Conversations/blob/master/gradle/wrapper/gradle-wrapper.properties#L5)
_distributionUrl=https\://services.gradle.org/distributions/gradle-3._**3**_-all.zip_
change to
_distributionUrl=https\://services.gradle.org/distributions/gradle-3._**5**_-all.zip_

But, how is it that you did not change this already, it builds ok with 3.3 for you ?!

**Comment by iNPUTmice** [comment]
I think it builds fine on Android Studio 2.x and on the command line. Apparently it works on Travis as well.
