### ISSUE TITLE
Omemo On Conferances

### ISSUE THREAD

**Issue by unkn19wn** [siacs/Conversations#2691]
Hi 
in Conferences when every one accepted each other`s omemo key still the omemo option will not turn on (it`s gray and not activeable)

#### General information
* **Version:** eg 1.21.0
* **Device:** eg Samsung j7
* **Android Version: Android 6.0 
* **Server name: Ejabberd
* **Server software:** ejabberd 16.04

**Comment by iNPUTmice** [comment]
Hi,

please use the group chat for general questions. You might also want to read the FAQ.
