### ISSUE TITLE
Hide shared images in the gallery app

### ISSUE THREAD

**Issue by srgcdev** [siacs/Conversations#2693]
#### General information

* **Version:** 1.21.0
* **Device:** Google Nexus 5x
* **Android Version:** Android 7.1LineageOS
* **Server name:** self hosteg
* **Server software:** ejabberd 17.09
* **Installed server modules:** Stream Managment, CSI, MAM...
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Share a picture to a contact

#### Expected result

What is the expected output? 
It would be nice not seeing the compressed picture in the gallery app

#### Actual result

What do you see instead?
The compressed picture is duplicated in the gallery with the original one

**Comment by licaon-kter** [comment]
Create a `.nomedia` file inside that folder.

**Comment by srgcdev** [comment]
Could conversations create it automatically? I don't see my mother creating this file for her own.

Thanks

**Comment by iNPUTmice** [comment]
Hiding them is not a good idea as this gives users no choice of deleting them. Avoiding them could be an option later on but that requires major changes to the way media files are handled.

**Comment by srgcdev** [comment]
Could we please keep this issue open? I know the solution needs a big refactor but I think its something that needs to be done in the future because other im clients do.

**Comment by brighterness** [comment]
> Create a .nomedia file inside that folder.

It is an uphill fight to motivate many people to adopt Jabber Texting.  Having them install a third party file manager allowing them to touch this file into existence?  Not likely at all
