### ISSUE TITLE
Message to confirm before you share a picture/file

### ISSUE THREAD

**Issue by srgcdev** [siacs/Conversations#2694]
#### General information

* **Version:** 1.21.0
* **Device:** Google Nexus 5x
* **Android Version:** Android 7.1 LineageOS
* **Server name:** Self hosted
* **Server software:** ejabberd 17.09
* **Installed server modules:** Stream Managment, CSI, MAM...
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Go to the gallery app and chose a picture.
2. Share it with a conversation contact or group chat

Or 

1. In a conversation with a contact attach a picture/file to your contact.

#### Expected result

What is the expected output? 
It would be nice if a confirm message its shown because sometimes you can make a mistake by choosing the contact or the picture you want to share.
The best solution would be a nice preview of the picture/file in the conversation and you could cancel it.

#### Actual result

What do you see instead?
You share the picture/file immediately with no possibility of cancel it.

**Comment by iNPUTmice** [comment]
Please search the issue tracker for duplicate feature requests.

#1879

**Comment by srgcdev** [comment]
Sorry, I was looking for it and I didn't find it so I opened the issue.
