### ISSUE TITLE
Text cut by one letter in Add account

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2695]
#### General information

* **Version:** 1.22.0
* **Conversations source:** F-Droid
* **Android OEM/version:** Xperia/Samsung 6.0.1

#### Steps to reproduce

1. Open accounts
2. Press Add account
3. check "Register new account on serve**r**"

#### Expected result

"Register new account on serve**r**" box is checked

#### Actual result

The box is checked but the text now says "Register new account on serve" <- **missing last letter**

It does not happen all the time, just retry a lot, it happens both in portrait and in landscape view, it happens in English, French and other.

Pic: 

![proof](https://i.imgur.com/U7ytb6a.jpg)

**Comment by iNPUTmice** [comment]
Please provide screenshots and fill in the issue template especially in regards to the ROM used.

**Comment by licaon-kter** [comment]
Updated!

**Comment by licaon-kter** [comment]
And with Android showing the layouts

**Comment by daivat15** [comment]
@licaon-kter I am unable to reproduce the issue. Has it been fixed? If it hasn't, I believe a similar issue should occur when we try to edit account details also.

**Comment by licaon-kter** [comment]
I'll have to retry on that specific device & Android version combo.

**Comment by licaon-kter** [comment]
Still an issue with 1.23.6 on Android 6.0.1.
But I can't repro on Android 8.0.0.

**Comment by licaon-kter** [comment]
Can't repro now.
