### ISSUE TITLE
Wrong Emoji - No selectable Emoji - Cropped Emoji - Downgrade not possible

### ISSUE THREAD

**Issue by github-tomster** [siacs/Conversations#2697]
#### General information

* **Version:** 1.22.0
* **Conversations source:** F-Droid

#### Steps to reproduce

1. insert emoji. look at recieved emoji.

#### Expected result

display the emoji that i inserted and which is shown on my keyboard.

#### Actual result

i see an emoji that is not the one i have choosen.
and btw. like in 1.20 emojis are cropped...

#### Debug output
and the downgrade to 1.21 fails due to unknown error via fdroid...

**Comment by iNPUTmice** [comment]
Conversations 1.22.0 uses an embedded emoji font in an attempt to a) make them look the same in all Conversations version across all platforms b) bring the latest emojis to old platforms.

Emojis not looking the same in the app and in the keyboard is something we have to live with to make a and b possible.

Please provide a screenshot for the cropped part.

**Comment by github-tomster** [comment]
feel free to use an embedded emoji font,
do not force the user to use it though!

screenshot:  Something went really wrong, and we can’t process that file. ...

**Comment by github-tomster** [comment]
untill now i thought:
> Conversations is a Jabber/XMPP client for Android 4.0+ smartphones that has been optimized to provide a unique mobile experience.

what does:

> a) make them look the same in all Conversations version across all platforms

mean? what platforms?

**Comment by github-tomster** [comment]
workaround for the screenshot.
[http://screenshotcomparison.com/comparison/123749](url)
i choose 1.21!

**Comment by licaon-kter** [comment]
@github-tomster Do you really think it's better to send an emoji with 2-adults-1-child from Android 6 only to have Android 5 users receive an emoji with 2-Adults-2-children instead?

This update brings universal compatibility to ALL devices no matter what emoji font the OEM, Google or the keyboard maker included or not in the system.

**Comment by github-tomster** [comment]
@iNPUTmice 
let at least the user decide.
for the sake of the 'not-knowing-what-they-are-doing-users': let it be default.
but for the sake of the users who want to use their own system notocoloremoji.ttf:
do not impose the usage of the embedded emojis.

am i the only one seeing the same emoji on my keyboard and in my conversations
or textmessages? it would be no surprise though...

this should ONLY be an option to users not able/where it is not possible
to change the notocoloremoji.ttf.

@licaon-kter 

> Do you really think it's better to send an emoji with 2-adults-1-child from Android 6 only to have Android 5 users receive an emoji with 2-Adults-2-children instead?

well...
do you really really think

> Emojis not looking the same in the app and in the keyboard is something we have to live with to make a and b possible.

is that way better?!
funny fact: i have never had none of these 'features'...
thx to 1.22: now i am up to date.
different emoji on keyboard an message.
LUKY ME!

**Comment by licaon-kter** [comment]
@github-tomster Not sure if I get it, but what part of "what you write is NOT what your contact sees" sounds ok to you in a CHAT app?

**Comment by github-tomster** [comment]
@licaon-kter 
we miss the essential point here:
**it was taken away the ability to use the system notocoloremoji**
hence this issue is opened!

> Not sure if I get it, but what part of "what you write is NOT what your contact sees" sounds ok to you in a CHAT app?

do you have a dream?
a dream that one day ALL CHATs only have ONE emoji style?
1.22 is the way to go for you!
but wait, what about the other clients? it does not work!
it only works on conversation2conversation!

so my conclusion is: 
1.22 is not able to realize a consistent emoji experience cross-plattform!
it only can provide a non configurable emoji experience conversations2conversations.

**Comment by uchchishta** [comment]
You seem to be in the 1% that can _modify system fonts._  Just recompile the app to your desire ☺ 
Other apps **will** start using [EmojiCompat](https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat.html) too.

**Comment by github-tomster** [comment]
@uchchishta 
you are the issue-hero so far from my side! a solution in sight!

so there it is:

> How does EmojiCompat work?
...
You can configure EmojiCompat with **either** bundled or downloadable fonts.
... 

thist **'either'** is the whole issue about!
**so please please with sugar on top: let the 1% user use the system font.**

**Comment by uchchishta** [comment]
No. The _downloadable_  fonts require Google play services.
/close this

**Comment by github-tomster** [comment]
**a perfect example of: a retrograde step as an illusion of great progress!**
got it.
a google-play-service requirement... uh...
i have to admit,
i am one of the <0.0(how many zeros to add?)1% no-google-# users

so it seems that only recompiling will be it. so far i/we have to stay on 1.21
as long as the issue exists.

**Comment by licaon-kter** [comment]
Can you please update your emoji font: https://is.gd/dmL2Rm

Backup your old font, remember to set up permissions back to 644 or rw-r--r-- if you replace it from a file manager, reboot, and enjoy.

Then close this.

BTW, I just did this on Android 5.1.1 and works as expected.

**Comment by github-tomster** [comment]
@licaon-kter 
**NO!**

how could i?!
the issue,
that notocoloremoji systemfont,
that is installed on the device,
does not work anymore;
i am being told,
is a new exciting feature. **LOL**
instead it brings an ugly non changeable embedded one. excellent.

i am the pest here, fine. maybe others find this issue and agree.
time will tell.

@iNPUTmice 
humans are writing the code
...
humans are using the code
...
i will keep an eye on the changelog
...

**Comment by licaon-kter** [comment]
You will have the same emojis in keyboard as in the app, isn't that what you wanted?

Also stop writing in haikus FFS.

The app devs can't fix the old Android versions that won't get the updated fonts, humans or not.

**Comment by iNPUTmice** [comment]
Both of your *opinions* have been heard. They will be taken into consideration. No need to repeat them over and over again.

**Comment by iNPUTmice** [comment]
Check with current master (=beta on the PlayStore) if the cropping issue still occurs.

**Comment by twenty-fifth-kislev** [comment]
Embedded emoji font is really good idea but if it is an option. Some smart users change emoji font for some reasons and now they MUST see Google emoji even if they don't like it.
I doubt it is too hard for Daniel (if he could find this useful :) ) to make this as an option with checkbox: "Use system Emoji (AndroidEmoji, NotoColorEmoji etc.)" or "Use embedded into Conversations". Hope it would be helpful to resolve some complications with some of Conversetions fans ;).

**Comment by github-tomster** [comment]
@inputmice
sorry to say, i have downgraded to 1.21.. since an easy version change is
not possible the chance to test the cropping issue was not there.

after checking the changelog i have an REQUEST:
please alter the changelog to make CLEAR what happend to emojis!
now it states:

> Version 1.22.0

    Text markup bold, italic,monospace and strikethrough
    Use same emoji style on all Android versions
    Display emojis slightly larger within continuous text

it should read

> Version 1.22.0

    Text markup bold, italic,monospace and strikethrough
    Use same Conversations embedded emoji style on all Android versions (not customizable)
    Display emojis slightly larger within continuous text

imho it should also be mentioned that the idea of 
"Use same emoji style on all Android versions"
works only in conversations!
should i open another issue because of that incomplete changelog?

if the changelog would be more clear,
this issue could be much more calm...

**Comment by licaon-kter** [comment]
@github-tomster Here is a [test build of the latest commits](
https://mega.nz/#!tZIHEDrA!SzSi7SXc58wbWilEfylkfAZB0RtmjembLl-1q7VS5x4) with a different app ID so it won't replace your version.

Are the emojis are still cut?

**Comment by github-tomster** [comment]
@licaon-kter 
no more cropping.
thank you for the testbuild.

**Comment by iNPUTmice** [comment]
> no more cropping.
> thank you for the testbuild.

Awesome. Thank you for the feedback.

**Comment by github-tomster** [comment]
so here is an update from my site to anyone who wants to have the very last word on emoji!
the pix-art messenger: https://github.com/kriztan/Pix-Art-Messenger
is capable of: https://github.com/siacs/Conversations/pull/2710
