### ISSUE TITLE
Wrong Emoji - mixed up when using styling

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2698]
#### General information

* **Version:** 1.22.0
* **Android Version:** Xperia 6.0.1
* **Conversations source:** F-Droid

#### Steps to reproduce

1. write `*emoji* emoji`

#### Expected result

Same emoji shown

#### Actual result

The emoji between the styling formatting * uses the system included emoji style and not the new emoji-compat. The input box is ok, but once sent it looks like this:

![proof](https://i.imgur.com/snsQmUl.jpg)

**Comment by iNPUTmice** [comment]
Feel free to report this to Google.

**Comment by licaon-kter** [comment]
Umm what? Why?

When starting with * the styling starts, can't you *not style* if the content is an emoji?

**Comment by iNPUTmice** [comment]
Not styling doesn't work if the style contains both and emoji and text. The
Google library should work either way. Seems to be a bug in the library.

**Comment by iNPUTmice** [comment]
FWIW I can’t reproduce this on Android 7.1

**Comment by whitetornado** [comment]
exact FWIW

2017-11-17 10:07 GMT+01:00 Daniel Gultsch <notifications@github.com>:

**Comment by licaon-kter** [comment]
Android 6.0.1 and 5.1.1, exactly the base that benefits the most from the emoji-compat client update.

**Comment by iNPUTmice** [comment]
Anyone else besides @licaon-kter seeing this? Please state your OS version and vendor.

**Comment by licaon-kter** [comment]
Also Samsung 6.0.1.

**Comment by chris-est** [comment]
I have this too.
Android 7.1.2 (LineageOS 20171003-nightly)
Conversations 1.22.0 (source: F-Droid)

**Comment by steffanson** [comment]
Cannot reproduce this on
Android 7.1.2 (LineageOS 20171020-nightly, Serranoltexx)
Conversations 1.22.0 (source: F-Droid)

**Comment by licaon-kter** [comment]
@steffanson Picture ? 
Also, a picture with the emoji selector of the keyboard please (so we can exclude the case where the latest NotoColorEmoji font is already included in your custom ROM)

**Comment by steffanson** [comment]
> Also, a picture with the emoji selector of the keyboard please

![screenshot_20171121-184123](https://user-images.githubusercontent.com/17642285/33087779-dd9fb4fc-ceeb-11e7-9ca8-a311585df214.png)

**Comment by licaon-kter** [comment]
@steffanson And one picture like mine from the first post please.

**Comment by steffanson** [comment]
> @steffanson And one picture like mine from the first post please.

The input field shows a different emoticon version for me compared to the application and the chat bubble:

![aasdas](https://user-images.githubusercontent.com/17642285/33095094-b7fae548-cf02-11e7-9610-7655e105a9cd.png)

**Comment by licaon-kter** [comment]
@steffanson So you *actually have* the same issue too.

Interesting that you actually showed it erring out in a different way than my example.

`* emoji * space emoji` = `* old-emoji * space new-emoji`

`* emoji * emoji` = `* old-emoji * old-emoji`

**Comment by iNPUTmice** [comment]
Please check if this branch resolves the issue https://github.com/siacs/Conversations/tree/emoji_using_process

**Comment by licaon-kter** [comment]
Fixed, thanks

![pic](https://lut.im/kYXAVScajD/zcBGidxVqV8ok00Z.jpeg)
