### ISSUE TITLE
Automatically enable OMEMO when the other person uses OMEMO

### ISSUE THREAD

**Issue by allo-** [siacs/Conversations#2701]
Suddenly contacts using Conversations send me unencrypted messages, even when I send OMEMO messages. They used OMEMO before. I suspect that Conversations disabled this, when I was online with a client which does not support OMEMO.

I think it would be reasonble to automatically start a OMEMO session when the contact uses OMEMO unless it is explicitely disabled by the user. Another nice feature would be a button "request encrypted session" where the contact gets a message "your contact wants an encrypted chat, click here to enable OMEMO".

**Comment by whitetornado** [comment]
i agree will be the best option to add a default encryption (default is
OMEMO) instead of none

2017-11-17 19:21 GMT+01:00 allo- <notifications@github.com>:

**Comment by iNPUTmice** [comment]
We are currently focusing our efforts towards making OMEMO the default encryption.
