### ISSUE TITLE
Chat list - styling not applied to last message preview

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2705]
#### General information

* **Version:** 1.22.0
* **Device:** Xperia 6.0.1
* **Conversations source:** F-Droid

Pic:
![proof](https://lut.im/giOEB9hw9W/NPp4s6RTKkImWIPY.jpeg)

**Comment by harshitbansal05** [comment]
@licaon-kter i could'nt exactly get the issue, could you please help?

**Comment by licaon-kter** [comment]
Write a text... that specific text and look in the chat overview... `some` should be **bold**

**Comment by harshitbansal05** [comment]
@licaon-kter can I start to work on this issue?

**Comment by licaon-kter** [comment]
Feel free...

**Comment by iNPUTmice** [comment]
closed by 7ca719b8beec5d8dd8f4b26701143490af4f9186
