### ISSUE TITLE
Is Chrome OS support deprecated? Conversations still in Chrome Web Store. (Chromebook)

### ISSUE THREAD

**Issue by j12i** [siacs/Conversations#2707]
Hello,
I have a Chromebook Peppy with stock Chrome OS and put Conversations on it today from the Chrome Web Store. I had a problem with OMEMO encrypted messages, but in the process of filing a bug I noticed that the version I got is 1.6.11.
So I was wondering if there was even any use in filing a bug, or running Conversations on Chrome OS is not supported anymore. A quick google, this issue tracker and readme.md didn't answer my question.

Thanks

**Comment by licaon-kter** [comment]
Things changed in 1.16 iirc.

**Comment by j12i** [comment]
I can't just install an .apk on my Chromebook. It only asks me with which app I want to open the apk.
Maybe there is a way through console, I'll try a web search on this later.

**Comment by iNPUTmice** [comment]
There was never official support for ChromeOS. To my understanding ChromeOS will soon support Android Apps natively (as in you can install them directly from the PlayStore. See [this article](https://www.digitaltrends.com/computing/how-to-get-android-apps-on-a-chromebook/) for example.
If your Chromebook is not on the list you can toy around with ArcWelder trying to get it to work. But you will be on your own mostly when it comes to fixing bugs.
