### ISSUE TITLE
"Use System Emojis" Option

### ISSUE THREAD

**Issue by Urodela** [siacs/Conversations#2709]
#### General information

* **Version:** 1.22+
* **Device:** LG SmartWine H410
* **Android Version:** Android 5.1.1 Stock
* **Conversations source:** F-Droid
---

Hello,

i'm not sure if it's okay to ask here cause the guideline says "The issue tracker on Github is for bug reports only. It is not a general support forum." so yeah, feel free to remove it if its not okay! Sorry in that case!

I would like to "request" some sort of switch in the options to use the system Emoji font instead of the "built-in" Emojis.

My wife uses Conversations on her LG phone, I use Pidgin. We have replaced the LG smilies with standard Android 5.0 smilies and I use an Android 5.0 theme on Pidgin = Same smilies on both.

Now with 1.22+ she gets different smilies than I send her. I've changed my pidgin theme to match the new Conversations smilies, but they're somehow incomplete. I can send a hurricane, for example, but she can't see him.

But worst of all, she still sees the smilies we replaced. So she can't even send the new smilies because the keyboard doesn't display them at all.

I'm not quite sure why the smilies were changed but anyway, is there a chance to get an option like "use system emojis"?

Okay, thanks for reading, sorry for your time, excuse my English :( and have a nice day! bb

**Comment by Dobli** [comment]
I would also opt for that option, in my opinion the new Android Oreo emojis used by default now are really awefull, I even went the way to replace them by the old blob emojis on the system level and was happy that Conversations just used the system ones. Staying on 1.21 for now.

**Comment by iNPUTmice** [comment]
Such an option is not on our TODO list. I'm willing to merge a PR that adds a multi dimensional gradle flavor that can be used to build a version without the emoji support library.

**Comment by Dobli** [comment]
Wouldn't it be better to just have an option in the applications settings? It is only a matter of using an additional parameter in your init() method in the AbstractEmojiService. If 		config.setReplaceAll(**false**) is used insted of **true** it will default to the system emoji font where possible (and only use the awkward new ones when not available in the system font), the value could then be set during calling init() from the ConversationActivity which retreives it from the preferences.

I could create a PR for that, if that solution would also be okay with you.

**Comment by iNPUTmice** [comment]
@Dobli no I prefer I build flavor. Having a setting for that is unnecessary for 99.9% of all users. A build flavor would be a compromise for people how want to compile Conversations themselves and don't want to keep merging their own modifications.

**Comment by github-tomster** [comment]
+1 for the emoji-less!

i am still to stupid to get the point:
why building another non-configurable-emoji-eco-system into conversations?

and thank the universe i am not alone!
https://github.com/siacs/Conversations/issues/2697

**Comment by radiocane** [comment]
Working on it radiocane@a3049ebfc186486c5580a44f2f361a4b4a937b61

**Comment by iNPUTmice** [comment]
@radiocane if we just give the emoji dimension a higher merge/overwrite order it should be enough to just make the system flavor reimplement EmojiService and EmojiWrapper with nops, no? (I haven't actually tried anything with multi dimensions but that seems like the 'logical' approach.

**Comment by radiocane** [comment]
I'm new to gradle and flavors, I'm still learning. I'll try what you  
suggested :)
-- 
https://twrh.noblogs.org ~ printf "%X\n" 44203

**Comment by radiocane** [comment]
@iNPUTmice I tried it and it looks like it's not possible to have src/flavor/java/something.java overwrite src/main/java/something.java. The doc https://developer.android.com/studio/build/build-variants.html#sourceset-build says exacly "For a given build variant, Gradle throws a build error if it encounters two or more source set directories that have defined the same Java class."
I've given "emoji" a higher priority (commit coming soon), but it'd still be necessary to remove AbstractEmojiService.java and EmojiWrapper.java from main and have three different copies of them, one for each source set/flavor (playstore, systemFree and compatFree).

**Comment by radiocane** [comment]
radiocane@9d6d7dc6f567c20c1ddd11c2dcb98993499468a7
