### ISSUE TITLE
Wrong/Incomplete ChangeLog

### ISSUE THREAD

**Issue by github-tomster** [siacs/Conversations#2712]
https://github.com/siacs/Conversations/blob/master/CHANGELOG.md
states:

> Use same emoji style on all Android versions

this is misleading and not even half the information what was changed!
it should read:

> Start using Conversations own embedded emoji style on all Android versions

also it should be warned:
**Conversations own embedded emoji style is NOT configurable!**

**Comment by iNPUTmice** [comment]
I disagree with that.
