### ISSUE TITLE
Unknown "Buddies" string

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2716]
Conversations from HEAD
Prosody 0.10 server

Where does this come from? It's not in the app source
![Pic](https://i.imgur.com/jMq4cXy.jpg)

**Comment by SamWhited** [comment]
What is "this"? If you mean the "buddies" tag, that is a roster group that was created by one of your other clients (Pidgin automatically puts everyone into a group called buddies, IIRC).

**Comment by licaon-kter** [comment]
Ok, thanks, did not realise that clients can add up to that entry.
