### ISSUE TITLE
Use xmpp-addr library from babbler project instead of own Jid

### ISSUE THREAD

**Issue by iNPUTmice** [siacs/Conversations#2717]
Refactor the entire code to use the xmpp-addr / Jid implementation from the babbler project instead of our own Jid class (which unfortunately seems to have some broken stringprep profiles)

**Comment by iNPUTmice** [comment]
This depends on #2714 because the babbler library uses Java 8.

**Comment by vikiCoder** [comment]
I would like to work on this issue. Shall I proceed?

**Comment by SoyaLeaf** [comment]
I tried it.Unfortunately, Android does not seem to provide JAXB. >_<~

**Comment by iNPUTmice** [comment]
I don't think you need the entire babbler project. Just xmpp-addr. And that comes without the JAXB dependency.

**Comment by vikiCoder** [comment]
So basically you are suggesting that just copy-paste the xmpp-addr from babbler into conversation and refactor according to it.... Am I right?

**Comment by SoyaLeaf** [comment]
@iNPUTmice  I just add  xmpp-addr ` implementation 'rocks.xmpp:xmpp-addr:0.7.5'`，maybe it also need JAXB. 
```Java
@XmlJavaTypeAdapter(JidAdapter.class)`
public final class Jid implements Comparable<Jid>, Serializable, CharSequence {
...
}
```
```Java
final class JidAdapter extends XmlAdapter<String, Jid> {
...
}
```
It seems that there is no good way, what am I doing wrong?

**Comment by iNPUTmice** [comment]
No i meant to just use the xmpp-addr library. I kinda checked it with 0.7.4 - maybe something has changed that doesn't allow us to use this anymore. In that case disregard this entire issue.

**Comment by SoyaLeaf** [comment]
I switched to 0.7.4, but with the same result, I'm afraid I did something wrong. :(
@iNPUTmice

**Comment by iNPUTmice** [comment]
What error message are you getting and where?

**Comment by SoyaLeaf** [comment]
Same as when I used  0.7.5 
```
Warning:rocks.xmpp.addr.JidAdapter: can't find superclass or interface javax.xml.bind.annotation.adapters.XmlAdapter
Warning:rocks.xmpp.addr.Jid: can't find referenced class javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter
Warning:rocks.xmpp.addr.JidAdapter: can't find referenced class javax.xml.bind.annotation.adapters.XmlAdapter
Warning:there were 5 unresolved references to classes or interfaces.
```

**Comment by iNPUTmice** [comment]
Oh that might just be proguard and can be ignored by editing `proguard-rules.pro` and add a `-donwarn rock.xmpp.addr.*` or something.

**Comment by SoyaLeaf** [comment]
I tried to add `-dontwarn rock.xmpp.addr.**` but get the same message. I'm not sure but I guess  Android 
does not support  `interface javax.xml.bind.annotation.adapters.XmlAdapter` , because it went wrong when I  looking at the source

![image](https://user-images.githubusercontent.com/20620071/36308846-3b91416a-135d-11e8-9898-a1556d193153.png)

**Comment by iNPUTmice** [comment]
There is a branch from last year where i toyed around with this: https://github.com/siacs/Conversations/tree/xmpp_addr

At this time Conversations wasn't using proguard then.

however this issue is not super important. if it doesn't work it doesn't work.
