### ISSUE TITLE
Not connecting to server after android upgrade to 8.1.0

### ISSUE THREAD

**Issue by afraga-br** [siacs/Conversations#2725]
#### General information

* **Version:** [the current one]
* **Device:**  Google pixel
* **Android Version:** Android 8.1.0

**Comment by iNPUTmice** [comment]
Please fill in the entire issue template and provide the output of adb
logcat or we are unable to help you. Connects fine on my Android 8.1 - so
this is not something that happens on all 8.1 but is specific to your
network or your server.
