### ISSUE TITLE
Limit encryption methods to OMEMO by default for new users

### ISSUE THREAD

**Issue by devurandom** [siacs/Conversations#2728]
New, non-technical users observed by me during their first use of Conversations appear to be discouraged by the encryption menu. It appears that the many choices (OMEMO, OTR, PGP) are confusing to people who do not know what these acronyms mean and what implications the different methods have.

Hence I propose to limit the encryption methods to only OMEMO by default, but allow the others to be enabled in the expert settings, if desired by the user. The drop-down encryption button would turn into a simple toggle, i.e. offer no sub-choice at all anymore -- just "off" (no encryption) and "on" (OMEMO). This would be in order to reduce the amount of technical choices new users have to make.

For existing users, the enabled encryption methods in the settings would be all of them (OMEMO, OTR, PGP), but for new installations only OMEMO would be active by default in the settings.

**Comment by iNPUTmice** [comment]
The path to OMEMO by default is a very long one and relies currently on the OMEMO section in the [compliance tester](https://conversations.im/compliance/) to turn green for all relevant servers.

OTR will be removed in Conversations 2.0.

There are currently no plans to remove the encryption button entirely.

**Comment by devurandom** [comment]
> The path to OMEMO by default is a very long one and relies currently on the OMEMO section in the compliance tester to turn green for all relevant servers.

Assuming this was meant to be "OMEMO on by default": It is not what I am suggesting. This was already discussed and explained in #2291 and others, and I understand the [reasons for not doing it](https://github.com/siacs/Conversations#security).

> OTR will be removed in Conversations 2.0.

Nice!

> There are currently no plans to remove the encryption button entirely.

I did not dare to imagine this ever happening.

---

I am not suggesting to enable encryption by default. I only suggest to limit the available choices of encryption methods for new users to exactly one, OMEMO. This method shall not be enabled automatically for new chats, just as encryption is not being enabled right now, [for valid reasons](https://github.com/siacs/Conversations#security). But I believe the number of unknown acronyms that especially inexperienced users face when trying to enable encryption hinders adoption of any encryption method at all.

Thus the suggestion to allow only OMEMO for new installations of Conversations, and hide OTR and PGP behind a setting. This would simplify the situation for new users, but still allows more experienced users to choose other supported encryption methods, if so desired (by enabling the setting). For existing installations, OTR and PGP would be enabled automatically, so as to not create any surprises for existing users.

**Comment by iNPUTmice** [comment]
I will consider making pgp only available after the key has been published.
But only after Conversations 2.0 has been released and OTR has been
removed. I figure making omemo default and removing OTR will already make
that menu less confusing. Afterwards we will see if 'hiding' pgp is still
necessary.

**Comment by devurandom** [comment]
Sounds like a very good approach. If OTR is removed and PGP only available when an associated key is found (and maybe if the menu becomes a button, if only one choice is available), that would match my desired outcome and likely make encryption less daunting for inexperienced users.

What will be important, is to document the conditions for availability of PGP to the (experienced) user, e.g. by mentioning it in (account) settings.

Thanks for the great work you're doing!

**Comment by donnovannie** [comment]
> There are currently no plans to remove the encryption button entirely.

awesome
