### ISSUE TITLE
Keep the screen on while playing audios or keep playing them with the screen off.

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#2733]
#### General information

* **Version:** 1.23.1
* **Device:** BQ Aquaris M5
* **Android Version:** Android 6.1.0 Stock
* **Server name:** suchat.org
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Receive an audio with a duration (eg. 2 min) longer than the duration of the screen waiting (eg. 1 min)
2. Wait until the screen goes off

#### Expected result

The audio doesn't get stopped

#### Actual result

The audio is stopped when the screen is turned off

**Comment by licaon-kter** [comment]
It's complicated, either you keep the screen ON (10 minutes? 20?) or you implement an audio player like functionality with notification and such so one can close the screen.

**Comment by moshpirit** [comment]
I'm not comparing or anything, just saying this is possible to do, but on Telegram we can listen to an audio and turn off the screen, maybe that can be easier to implement?

**Comment by ialokim** [comment]
On my phone (Android 7.1.2, Conversation 2.2.3) this problem still persists: The screen turns off after the normal screen timeout (e.g. after 1 minute) and the audio stops playing.

I'm not really sure why the fix by @iNPUTmice does not work on my phone.

**Comment by unicorntaco** [comment]
Could be used for Push To Talk also :man_dancing: 

https://github.com/siacs/Conversations/issues/1239
https://github.com/siacs/Conversations/issues/1234

PTT is an extant XEP

audio/video calls is attempted in this hybrid
https://github.com/cmeng-git/atalk-android

> It's complicated, either 

Borrow from NewPipe?
https://github.com/TeamNewPipe/NewPipe
