### ISSUE TITLE
no messages recieves when phone sleeps

### ISSUE THREAD

**Issue by whitetornado** [siacs/Conversations#2735]
#### General information

* **Version:** 1.21
* **Device:** eg Moto C3
* **Android Version:** 6.0
* **Server name:** eg self hosted xmpp
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** self compiled

#### Steps to reproduce

1. when phone sleeps it will not accept messages
2. when phone is awake then it will accept messages.

#### Expected result

how to wake up the phone when a message is received? I already choose to run on the background when i installed (battery save yes/no i choose n). Connection by WiFi

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by licaon-kter** [comment]
So it's version 1.2**3.3** and not 1.2**1** ?

**Comment by whitetornado** [comment]
1.21.0

Op 25 dec. 2017 18:45 schreef "Licaon_Kter" <notifications@github.com>:

So it's version 1.2*3.3* and not 1.2*1* ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/siacs/Conversations/issues/2735#issuecomment-353882265>,
or mute the thread

**Comment by licaon-kter** [comment]
Always report bugs with the latest version, update, test if it crashes, get logs.

**Comment by whitetornado** [comment]
it's a knowing issue? and is fixed in newer version?

2017-12-26 11:03 GMT+01:00 Licaon_Kter <notifications@github.com>:

**Comment by licaon-kter** [comment]
No, also it's a pain to debug different versions.

**Comment by Kandr0s** [comment]
Self Compiled. Free or Playstore Version?

**Comment by whitetornado** [comment]
solved, it was a app what closed connection
