### ISSUE TITLE
Bump chat with draft to top

### ISSUE THREAD

**Issue by contrapunctus-1** [siacs/Conversations#2738]
v1.23.3, F-Droid

To reproduce -
1. Have many chats open
2. Type a message in a chat, but do not send it
3. Press the Back button to show the chat list

Current behavior - the chat stays where it was in the list.

Suggested behavior - the chat should be bumped to the top of the list. Optionally, the message preview for that chat in the list could show the draft message instead of the last message.

**Comment by iNPUTmice** [comment]
2.0 does that

**Comment by contrapunctus-1** [comment]
I'm afraid I don't observe the desired behavior in v2.0.0-beta from F-Droid.

**Comment by licaon-kter** [comment]
@contrapunctus-1 

2.0 final

**Comment by contrapunctus-1** [comment]
Yeah, it's there. Excellent, thanks!
