### ISSUE TITLE
middle ground, 'has read up to here'

### ISSUE THREAD

**Issue by donnovannie** [siacs/Conversations#2741]
One friend will read messages via notifications and swipe them away.  I get no indication of my messages being read. This bugs the F outta me.  I would like to have an indication in my chat that this has happened, or the option to disallow reading via notification on my side impacting his side.

**Comment by licaon-kter** [comment]
His client marks "as read" when it either opens the app or sends a "mark as read" (eg. tte notification has such a function via QuickReply app or Android 7 and later).

This is a privacy feature, users should be able to control if it appears as read or if they just want to dismiss the notification.

/Close as invalid
