### ISSUE TITLE
Crash when trying to enable encryption

### ISSUE THREAD

**Issue by ghc2018** [siacs/Conversations#2744]
#### General information

* **Version:** 1.23.3
* **Device:** ZTE blade V8
* **Android Version:** 7.0 security patchlevel 2017-02-01
* **Server name:** jabber.ccc.de and trashserver.net
* **Conversations source:** F-Droid

#### Steps to reproduce

1. launch Conversations
2. click on padlock to enable encryption

#### Expected result

closed padlock and encryption enabled

#### Actual result

Conversation crashes and Android immediately asks wether to restart it.

#### Debug output

--------- beginning of crash
--------- beginning of system
--------- beginning of main
01-01 23:29:10.452  2492  2492 D conversations: pinsel@trashserver.net send ping (action=ui,lowTimeout=false)
01-01 23:29:10.456  2492  2492 D conversations: pinsel@jabber.ccc.de send ping (action=ui,lowTimeout=false)
01-01 23:29:10.460  2492  2492 D conversations: app switched into foreground
01-01 23:29:26.628  3255  3255 D conversations: initializing database...
01-01 23:29:26.628  3255  3255 D conversations: restoring accounts...
01-01 23:29:26.675  3255  3255 D conversations: restoring conversations...
01-01 23:29:26.702  3255  3255 D conversations: finished restoring conversations in 27ms
01-01 23:29:26.705  3255  3274 D conversations: restoring roster...
01-01 23:29:26.713  3255  3255 D conversations: stopped foreground service
01-01 23:29:26.714  3255  3255 D conversations: update unread count to 0
01-01 23:29:26.750  3255  3277 D conversations: pinsel@jabber.ccc.de: socket was null during force close
01-01 23:29:26.750  3255  3277 D conversations: pinsel@jabber.ccc.de: connecting
01-01 23:29:26.760  3255  3255 D conversations: pinsel@trashserver.net: not changing status to CONNECTING because thread was interrupted
01-01 23:29:26.763  3255  3281 D conversations: pinsel@trashserver.net: socket was null during force close
01-01 23:29:26.763  3255  3281 D conversations: pinsel@trashserver.net: connecting
01-01 23:29:26.764  3255  3274 D conversations: restoring messages...
01-01 23:29:26.778  3255  3255 D conversations: resetting all attempt counts
01-01 23:29:26.797  3255  3274 D conversations: finished restoring messages in 32ms
01-01 23:29:26.804  3255  3255 D conversations: start merging phone contacts with roster
01-01 23:29:26.821  3255  3255 D conversations: finished merging phone contacts
01-01 23:29:26.883  3255  3281 D conversations: Resolver: [Result{ip='5.1.76.122', hostame='h-pollux.650thz.de', port=5222, directTls=false, authenticated=false, priority=5}, Result{ip='2a00:f820:417::27e9:4b06', hostame='h-pollux.650thz.de', port=5222, directTls=false, authenticated=false, priority=5}, Result{ip='5.1.76.150', hostame='camo.trashserver.net', port=443, directTls=true, authenticated=false, priority=10}]
01-01 23:29:26.883  3255  3281 D conversations: pinsel@trashserver.net: using values from dns h-pollux.650thz.de/5.1.76.122:5222 tls: false
01-01 23:29:26.919  3255  3277 D conversations: Resolver: [Result{ip='146.255.57.229', hostame='jabberd.jabber.ccc.de', port=5222, directTls=false, authenticated=false, priority=10}, Result{ip='2a02:1b8:10:31::229', hostame='jabberd.jabber.ccc.de', port=5222, directTls=false, authenticated=false, priority=10}, Result{ip='146.255.57.229', hostame='jabberd.jabber.ccc.de', port=80, directTls=false, authenticated=false, priority=20}, Result{ip='2a02:1b8:10:31::229', hostame='jabberd.jabber.ccc.de', port=80, directTls=false, authenticated=false, priority=20}, Result{ip='2a02:1b8:10:31::229', hostame='jabberd-ipv6.jabber.ccc.de', port=5222, directTls=false, authenticated=false, priority=30}, Result{ip='null', hostame='jabberd-ipv6.jabber.ccc.de', port=5222, directTls=false, authenticated=false, priority=30}, Result{ip='146.255.57.229', hostame='jabberd-ipv4.jabber.ccc.de', port=5222, directTls=false, authenticated=false, priority=31}]
01-01 23:29:26.919  3255  3277 D conversations: pinsel@jabber.ccc.de: using values from dns jabberd.jabber.ccc.de/146.255.57.229:5222 tls: false
01-01 23:29:27.149  3255  3277 D conversations: pinsel@jabber.ccc.de: TLS connection established
01-01 23:29:27.168  3255  3281 D conversations: pinsel@trashserver.net: TLS connection established
01-01 23:29:27.213  3255  3277 D conversations: pinsel@jabber.ccc.de/phone: Authenticating with SCRAM-SHA-1
01-01 23:29:27.217  3255  3281 D conversations: pinsel@trashserver.net/phone: Authenticating with SCRAM-SHA-1
01-01 23:29:27.565  3255  3277 D conversations: pinsel@jabber.ccc.de: logged in
01-01 23:29:27.616  3255  3281 D conversations: pinsel@trashserver.net: logged in
01-01 23:29:27.727  3255  3281 D conversations: pinsel@trashserver.net: not counting stanza(IqPacket). Not in smacks session.
01-01 23:29:27.728  3255  3281 D conversations: pinsel@trashserver.net: starting service discovery
01-01 23:29:27.735  3255  3281 D conversations: pinsel@trashserver.net: server caps came from cache
01-01 23:29:27.750  3255  3281 D conversations: pinsel@trashserver.net: stream management(3) enabled (resumable)
01-01 23:29:27.798  3255  3277 D conversations: pinsel@jabber.ccc.de: not counting stanza(IqPacket). Not in smacks session.
01-01 23:29:27.799  3255  3277 D conversations: pinsel@jabber.ccc.de: starting service discovery
01-01 23:29:27.806  3255  3277 D conversations: pinsel@jabber.ccc.de: server caps came from cache
01-01 23:29:27.828  3255  3277 D conversations: pinsel@jabber.ccc.de: stream management(3) enabled (resumable)
01-01 23:29:27.880  3255  3281 D conversations: pinsel@trashserver.net: Requesting block list
01-01 23:29:27.885  3255  3281 D conversations: pinsel@trashserver.net: has pep but is not persistent
01-01 23:29:27.943  3255  3281 D conversations: pinsel@trashserver.net: successfully enabled carbons
01-01 23:29:27.955  3255  3281 D conversations: Received blocklist update from server
01-01 23:29:27.961  3255  3277 D conversations: pinsel@jabber.ccc.de: Requesting block list
01-01 23:29:28.101  3255  3277 D conversations: pinsel@jabber.ccc.de: successfully enabled carbons
01-01 23:29:28.110  3255  3277 D conversations: Received blocklist update from server
01-01 23:29:28.666  3255  3281 D conversations: AxolotlService (pinsel@trashserver.net): Bundle 535667222 in PEP was current
01-01 23:29:28.666  3255  3281 D conversations: AxolotlService (pinsel@trashserver.net): Announcing device 535667222
01-01 23:29:28.781  3255  3277 D conversations: AxolotlService (pinsel@jabber.ccc.de): Bundle 2052386591 in PEP was current
01-01 23:29:28.781  3255  3277 D conversations: AxolotlService (pinsel@jabber.ccc.de): Announcing device 2052386591
01-01 23:29:28.844  3255  3281 D conversations: pinsel@trashserver.net: online with resource phone
01-01 23:29:28.844  3255  3281 D conversations: pinsel@trashserver.net: fetching roster
01-01 23:29:28.848  3255  3281 D conversations: pinsel@trashserver.net sending csi//inactive
01-01 23:29:28.885  3255  3281 D conversations: pinsel@trashserver.net: retrieved own device list: [2129866795, 1892586673, 535667222, 729823352]
01-01 23:29:28.908  3255  3281 D conversations: pinsel@trashserver.net: gained mutual presence subscription with argus@466buer.de
01-01 23:29:28.908  3255  3281 D conversations: pinsel@trashserver.net: gained mutual presence subscription with lena@trashserver.net
01-01 23:29:28.908  3255  3281 D conversations: pinsel@trashserver.net: gained mutual presence subscription with wolf-453@jabber.ccc.de
01-01 23:29:28.945  3255  3281 D conversations: AxolotlService (pinsel@trashserver.net): Received PEP device list [2129866795, 1892586673, 535667222, 729823352] update from pinsel@trashserver.net, processing... 
01-01 23:29:28.945  3255  3281 D conversations: pinsel@trashserver.net: ignoring duplicate own device id list
01-01 23:29:28.991  3255  3281 D conversations: AxolotlService (pinsel@trashserver.net): Received PEP device list [487026640] update from lena@trashserver.net, processing... 
01-01 23:29:29.091  3255  3281 D conversations: AxolotlService (pinsel@trashserver.net): Received PEP device list [194308481] update from wolf-453@jabber.ccc.de, processing... 
01-01 23:29:29.125  3255  3281 D conversations: AxolotlService (pinsel@trashserver.net): Received PEP device list [194308481] update from wolf-453@jabber.ccc.de, processing... 
01-01 23:29:29.223  3255  3277 D conversations: pinsel@jabber.ccc.de: online with resource phone
01-01 23:29:29.223  3255  3277 D conversations: pinsel@jabber.ccc.de: fetching roster
01-01 23:29:29.227  3255  3277 D conversations: pinsel@jabber.ccc.de: running mam query with=*, start=2018-01-01T22:04:32.422Z, end=2018-01-01T22:29:27.808Z, order=NORMAL, catchup=true
01-01 23:29:29.228  3255  3277 D conversations: pinsel@jabber.ccc.de sending csi//inactive
01-01 23:29:29.257  3255  3281 D conversations: AxolotlService (pinsel@trashserver.net): Received PEP device list [749908650] update from argus@466buer.de, processing... 
01-01 23:29:29.264  3255  3277 D conversations: pinsel@jabber.ccc.de: retrieved own device list: [62957370, 1325541452, 2070556225, 2052386591]
01-01 23:29:29.804  3255  3277 D conversations: pinsel@jabber.ccc.de: gained mutual presence subscription with andyp161@jabber.ccc.de
01-01 23:29:29.804  3255  3277 D conversations: pinsel@jabber.ccc.de: gained mutual presence subscription with batfa@jabber.ccc.de
01-01 23:29:29.804  3255  3277 D conversations: pinsel@jabber.ccc.de: gained mutual presence subscription with floflo@jabber.ccc.de
01-01 23:29:29.805  3255  3277 D conversations: pinsel@jabber.ccc.de: gained mutual presence subscription with gretel@conversations.im
01-01 23:29:29.805  3255  3277 D conversations: pinsel@jabber.ccc.de: gained mutual presence subscription with gretel@jabber.ccc.de
01-01 23:29:29.805  3255  3277 D conversations: pinsel@jabber.ccc.de: gained mutual presence subscription with lena75@jabber.ccc.de
01-01 23:29:29.805  3255  3277 D conversations: pinsel@jabber.ccc.de: gained mutual presence subscription with wolf-453@jabber.ccc.de
01-01 23:29:30.024  3255  3277 W conversations: AxolotlService (pinsel@jabber.ccc.de): Failed to decrypt message from wolf-453@jabber.ccc.de: Error decrypting WhisperMessage DuplicateMessageException: Received message with old counter: 8 , 7
01-01 23:29:30.060  3255  3277 D conversations: skipping duplicate message with bugs@conversations.im. serverMsgIdUpdated=true
01-01 23:29:30.101  3255  3277 D conversations: skipping duplicate message with bugs@conversations.im. serverMsgIdUpdated=true
01-01 23:29:30.128  3255  3277 D conversations: pinsel@jabber.ccc.de: finished mam after 3(0) messages. messages left=true

Unfortunately the crash doesn't seem to create any related output in logcat!

It is asked wether to send a stack trace which I did several times.

**Comment by iNPUTmice** [comment]
Your phone is broken. Please complain to the manufacturer or return your phone to where you bought it.
https://twitter.com/iNPUTmice/status/875017794814922752

**Comment by ghc2018** [comment]
Thanks for the hint. I will address my seller and the phone's vendor.
