### ISSUE TITLE
Duplicate message when messaging to own account

### ISSUE THREAD

**Issue by vanitasvitae** [siacs/Conversations#2746]
#### General information

* **Version:** eg 1.23.3
* **Device:** Google Nexus 6p
* **Android Version:** Android 8.1.0
* **Server name:** self hosted
* **Server software:** ejabberd 17.12
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** F-Droid

#### Steps to reproduce

1.  Send message to yourself (if I'm bob@a.org, I send message to bob@a.org)

#### Expected result

What is the expected output? 
My message appears only once in the chat history, eg

```
bob: Hi!
```

#### Actual result

What do you see instead?
The message appears twice, eg.

```
bob: Hi!
bob: Hi!
```

I suspect this may has to do with how conversations handles carbons, but thats only a guess.
Gajim for example handles this correctly.

**Comment by iNPUTmice** [comment]
For the record; This is basically how XMPP works. If you message yourself the message will land in MAM twice as well and every client (with carbons enabled) will also receive the message twice. - I'm saying this in case someone finds this thread later for some reason.
However starting with current `master` Conversations now does some fancy de-duplication to only display each message once.
