### ISSUE TITLE
UX: hide sent image copies from gallery apps

### ISSUE THREAD

**Issue by SamWhited** [siacs/Conversations#2747]
When sending an image it is copied to the Conversations folder which is picked up by gallery apps. This is desirable for inbound images, but for outbound images you end up seeing the image twice when scrolling through your pictures (the original and the copy). If the original is from a media directory it would be nice if the copy could be created in a subdirectory that can't be scanned by image gallery applications.

**Comment by licaon-kter** [comment]
This is #2285 with a .nomedia file inside?

**Comment by SamWhited** [comment]
Looks the same, yes.
