### ISSUE TITLE
http_upload: Privatize username in a link

### ISSUE THREAD

**Issue by andypl** [siacs/Conversations#2749]
When sending files via http_uplad to conversations.im server generate link like this: https://share/domain.tld/username/hash/filename.ext. 
Placing a real username in a link is a very bad idea...Server should privatize this information e.g changing it to a hash https://share.domain.tld/hash/hash/filname.ext

**Comment by licaon-kter** [comment]
And this concerns Conversations how?

**Comment by iNPUTmice** [comment]
This is something that can only be configured on the server side.

**Comment by andypl** [comment]
@iNPUTmice I know that and this is why I created this issue here. I use conversations.im server.
