### ISSUE TITLE
bot spam: automated adding of my JID

### ISSUE THREAD

**Issue by delvethop** [siacs/Conversations#2750]
#### General information

* **Version:** current, either Fdroid or play store
* **Device:** samsung note
* **Android Version:** android 7 stock
* **Server name:** conversations.im, and jabber.cat 

Ignoring adds is easy when it is occasional.  When it is dozens a day less so.  Blocking is non-trivial at this point.  Please add an option to "block all non-contacts" for temporary relief.

**Comment by iNPUTmice** [comment]
Spam filtering should happen on the server side. We are working on that.
