### ISSUE TITLE
New messages block pop-up in MUC details

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2754]
#### General information

* **Version:** 1.23.3
* **Device:** Xperia 6.0.1
* **Server name:** self hosted
* **Server software:** prosody 0.10 or ejabberd 17.12 (did not test on a public server as the test case behaves like a DDOS)
* **Installed server modules:** most
* **Conversations source:** self build

#### Steps to reproduce

1. Create a MUC, so you are the admin
2. Use the [Slixmpp MUC bot example](https://slixmpp.readthedocs.io/getting_started/muc.html) to add 2 bots that just post indefinitely (a bot sees a message and responds, then the other bots sees the new message and responds, etc) 
3. Decide to block/ban a bot, go to MUC details, long press on a bot

#### Expected result

Pop-up appears with options to block/ban a bot

#### Actual result

The long press animation plays out but the pop-up never appears, I guess the view gets reset on a new message (and the bots responds continuously!)

#### Debug output

There is nothing in the logcat.

**Comment by licaon-kter** [comment]
I was hoping that the `app_compat` rewrite would fix this, but it's still an issue.

**Comment by iNPUTmice** [comment]
Fixed in latest master
