### ISSUE TITLE
Conversations uses wrong certificate for prosody's virtual hosts

### ISSUE THREAD

**Issue by owhen** [siacs/Conversations#2761]
#### General information

* **Version:** 1.23.3
* **Device:** BQ Aquaris E5 HD
* **Android Version:** Android 5.0
* **Server name:** wiuwiu.de / several virtual hosts
* **Server software:** Prosody 0.10
* **Conversations source:** PlayStore

#### Steps to reproduce

When connecting from virtual host example.com and enabled "Don't trust system CAs", you will get the prosody global certificate (issued for example.net) and the certificate for the specific virtual host (example.com).
If you trust the vhost specific certificate (not the global one!), you will no longer get the global certificate when you connect.

The problem cannot be reproduced with other XMPP Clients (e.g. Gajim or Dino).

#### Expected result

The client should only use the vhost-specific certificate if it does NOT connect via XMPP Over TLS.

#### Actual result

The client uses the global and vhost specific certificate, after accepting the vhost specific certificate, the client does not use the global one. (Client does not connect via XMPP Over TLS)

**Comment by mightyBroccoli** [comment]
Same issue here.
**Version**: 1.23.3
**Device**: Samsung Galaxy S7
**Android Version**: Android 7.0
**Server name**: magicbroccoli.de / another virtual hosts
**Server software**: Prosody 0.10
**Conversations source**: PlayStore

**Comment by iNPUTmice** [comment]
Conversations doesn’t *choose* a certificate. It chooses a connection mechanism and the server picks the certificate.
