### ISSUE TITLE
Since there is no video/audio calling it would be nice to have a button to start a call via nextcloud talk

### ISSUE THREAD

**Issue by kafisc** [siacs/Conversations#2762]
Since there is no video/audio calling integrated in conversations in conversations it would be nice to have an optional button to start a video-call via nextcloud-talk. 

Talk Addon for Nextcloud Server: See [](https://github.com/nextcloud/spreed)
Talk Addon for Nextcloud Android: See [](https://github.com/nextcloud/talk-android)

**Comment by iNPUTmice** [comment]
Not sure how this would work. Is there a specific intent I can call?

**Comment by tdemin** [comment]
No better than videocalling Allo users from Google Duo.

**Comment by iNPUTmice** [comment]
Closing for now b/c no reaction from op.
