### ISSUE TITLE
Pressing the soft keyboard next button in edit text of Add Account activity does nothing

### ISSUE THREAD

**Issue by harshitbansal05** [siacs/Conversations#2763]
#### General information

* **Version:**  1.23.3
* **Device:** Redmi Note 3
* **Android Version:** Android 5.1.1 Lollipop
* **Server name:** xmpp.jp
* **Installed server modules:** MAM
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

In **Add Account** activity, while entering the **Jabber ID**, pressing the soft keyboard next button does not move it to the next edit text. 

#### Expected result

What is the expected output? 

Pressing the soft keyboard next button after entering the **Jabber ID** should move it to the password edit text.

#### Actual result

What do you see instead?

Nothing happens and the focus still remains on the autocompletetextview of **Jabber ID**.

**Comment by harshitbansal05** [comment]
I would also like to work on the issue.

**Comment by iNPUTmice** [comment]
fixed in a3bb7c346b1df79f5eae9b6c2b4a71954ea49100
