### ISSUE TITLE
OMEMO doesn't work in MUCs if there is only one participant

### ISSUE THREAD

**Issue by wiktor-k** [siacs/Conversations#2768]
#### General information

* **Version:** 1.23.4
* **Device:** Note 8
* **Android Version:** Android 7.1
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** Play Store

#### Steps to reproduce

1. Create private, non-anonymous MUC room
2. Make sure you're the only one in it
3. Enable OMEMO encryption
4. Try to send the message

#### Expected result

Message has been sent and is visible on all devices.

#### Actual result

"Error sending the message" red text underneath the message.

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

Enabling OMEMO for MUC:
```
01-24 14:47:06.016 27657 27657 D conversations: AxolotlService ([hidden]): Enabled axolotl for Contact [hidden]
```
Sending a message produces only this:
```
01-24 14:47:07.334 27657 27657 D conversations: AxolotlService ([hidden]): Cache miss: 0640322f-2cae-4984-ad0d-d922d13e91b6
```

**Comment by licaon-kter** [comment]
There is workaround, so, with this account:
* Device A - start MUC, add a contact, enable OMEMO, accept key, send a message.
* Device B - join MUC, enable OMEMO, accept key, send a message
* ...
* Device X - join MUC, enable OMEMO, accept key, send a message
* any device - Kick the contact out
* Enjoy

So basically, as long as any device has already sent a message in the MUC while the contact is present, it will be able to use the MUC with OMEMO.
BUT, any new device that joins the MUC will error out... unless you add a contact, accept on this new contacts key, then kick the contact out...

**Comment by iNPUTmice** [comment]
This is *fixed* in current in current `master`. However starting with `master` I would suggest you just message your own account. This has a much nicer UI with working read markers and everything. (You can use the 'create contact' dialog to start a conversation with yourself.

**Comment by wiktor-k** [comment]
Thank you!
