### ISSUE TITLE
[QUESTION] How to connect to localhost/server

### ISSUE THREAD

**Issue by aresares** [siacs/Conversations#2769]
Hi, where can I change host/server:port IP in app?

Thx

**Comment by licaon-kter** [comment]
You need an actual certificate, a self signed one, but the trick is to generate it to your IP as a special domain:
Eg. `192.168.100.76.xip.io`

See http://xip.io for more info.

Do first check that your DNS servers correctly resolvs this, I've seen some that don't.
Eg. `dig 192.168.100.76` should answer with `192.168.100.76`

**Comment by aresares** [comment]
Thanks for responding, but I have an XMPP server on my localhost an Im using AndroidStudio emulator and I access to my localhost with 10.0.2.2 from android emulator, but inside Conversations sources I can not find where to insert that IP address (10.0.2.2 -> my localhost) in order to point to my server

**Comment by iNPUTmice** [comment]
> Hi, where can I change host/server:port IP in app?

Enable advanced connection options in the expert settings. Use the conference for further questions.
