### ISSUE TITLE
A Desktop Build ?

### ISSUE THREAD

**Issue by RebelCoderRU** [siacs/Conversations#2770]
Hello.

Thanks for your awesome work and an amazing XMPP client. I am wondering if you are planing to release a desktop client? I mean all Linux clients are horrible, with out of date text markdowns. Gajim seems to be one of the most updated but still is just horrible for a proper use.

Maybe your client could be wrapped in Electron or something? Just wondering. Would love to switch to XMPP chats only if I had a good Linux client.

![screenshot_20180125_122855](https://user-images.githubusercontent.com/20476773/35436365-671b3c94-028e-11e8-8b8a-bdc91f466803.png)

Regards.

**Comment by RebelCoderRU** [comment]
Unfortunately, this client is super buggy (does not deliver messages, has trey icon issues, etc...), still has horrible design and usability. Very dry I have to say. Nothing comes close to Conversations so far. So if we could get a desktop client from conversations guys, that could be awesome and we could replace Telegram, Slack, etc....

**Comment by licaon-kter** [comment]
Dino is far along already, compared to a Desktop-Conversations starting now.

Desktop Android emulators not helping?

**Comment by RebelCoderRU** [comment]
Desktop emulators? Not productive at all. I am talking about serious and stable desktop client. Dino is not far at all, as it's current version is v0.1. It is full of bugs and has tons of issues with message delivery, URL parsing and display and much more. Basically it is unusable for every day team work that needs OMEMO. So far there is no good Desktop client at all. Gajim comes close, but still, as I have said above, just horrible.

**Comment by d9h20f** [comment]
Gajim will have a version 1.0 soon, two alpha versions have already been released so you can check them out. It's much more usable now.

**Comment by kollix** [comment]
I use https://gitlab.com/kadu/kadu/wikis/home but sadly they stopped development. It's still usable (but one can not send images)

**Comment by iNPUTmice** [comment]
There is not gonna be *a desktop build*. If anything it is gonna be a complete new app written from scratch. And I don't see why Dino can not just become this.

**Comment by RebelCoderRU** [comment]
Dino, Gajim. Two most developed Jabber clients are horrible and are not suitable for every day work in teams. the just don't work. So having just Mobile Client like Conversations, that is amazing, is only 50% of the equation and not a reason to switch to Jabber with OMEMO. Sad. Staying on Telegram. I just thought you guys could solve this Desktop Client Abomination issue.

**Comment by d9h20f** [comment]
Dino is still in a fairly early stage of development (in fact it isn't even released yet). Gajim's first beta of version 1.0 was released a few days ago. Conversations recreated XMPP, have some patience for other clients to catch up. Dino will most likely become the Conversations equivalent on the desktop. You can open bug reports and feature requests to help fix problems asap.
