### ISSUE TITLE
FR: more ways to scan QR-Codes

### ISSUE THREAD

**Issue by Buntbart** [siacs/Conversations#2772]
I would like to have faster access to the function of scanning QR codes. For example, I find a corresponding menu item in the contact details obvious. Or even faster: Longpressing the contact icon in the chat window could open the barcode scanner.

**Comment by licaon-kter** [comment]
In 1:1 chats, touch icon, longpress OMEMO fingerprint, scan... ?

**Comment by Buntbart** [comment]
aha, thank you! I thought I already knew Conversations quite well, but that has remained hidden from me so far. I always find it very user-friendly when functions can be called up analogously. In this way, the user's own QR code should also be displayed in the same way when tapping on the user's fingerprint in the account management. And in analogy to the display of your own QR-code with longpress on your own icon, the barcode scanner should be called on the icon of the chat partner.

**Comment by licaon-kter** [comment]
Well... https://github.com/siacs/Conversations/pull/2626 ;)

**Comment by iNPUTmice** [comment]
Conversations 2.0 has more ways to scan a QR code.

**Comment by whitetornado** [comment]
When can we expect vers 2.0 ?

2018-03-12 15:19 GMT+01:00 Daniel Gultsch <notifications@github.com>:

**Comment by iNPUTmice** [comment]
March 24th.
And it's already available in the Play Store beta channel.

**Comment by whitetornado** [comment]
oh cool, can you add some screenshots? or list what will be changed?

2018-03-12 15:25 GMT+01:00 Daniel Gultsch <notifications@github.com>:
