### ISSUE TITLE
New contact message not correct

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2778]
When a new user contacts you, you'll see this in the chat:

![pic](https://lut.im/9LSJsVIAqn/0vNlYQktbfk97txe.jpeg)

So:
* `Contact added you to contact list` - great
* `Add back` - it's a new user, you could add it yes

When translating this I did not get the sense of _reciprocity_ like `Add this contact too` only the sense of _was on the list before, was deleted, add contact back_ hence my translation.

Can this be made clearer like `Add too` ?

**Comment by d9h20f** [comment]
It's clear enough in English, but there could definitely be a note for translators that it's about reciprocity and not about redoing something you undid.

**Comment by iNPUTmice** [comment]
I believe this is correct. (As pointed out in the group chat.)
