### ISSUE TITLE
[Feature Request] Implement Asynchronous Ratcheting Tree (ART)

### ISSUE THREAD

**Issue by Hoeze** [siacs/Conversations#2779]
Proposal for better group chat encryption:
https://github.com/facebookresearch/asynchronousratchetingtree

**Comment by carlosladsal** [comment]
The license is incompatible with conversations.

https://github.com/facebookresearch/asynchronousratchetingtree/blob/master/README.md#license

**Comment by Hoeze** [comment]
Yes, thats true, but only for the reference implementation.
The concept itself is not.

**Comment by licaon-kter** [comment]
What issue do you have with OMEMO in group chat exactly?

**Comment by Hoeze** [comment]
No issue, i just read that OMEMO encryption is less secure in group chats than in normal chats and ARP tries to correct that :)

I thought this might be an interesting OMEMO extension, so I opened this issue.
Of course the project authors can close this issue if they want to.

**Comment by licaon-kter** [comment]
> i just read that OMEMO encryption is less secure in group chats than in normal chats

Where did you read that? It works just like on 1:1 chats

> gets problematic with bigger groups

Links, please

>  which ARP tries to correct :)

What is ARP? You mean FART ( Facebook Async...) :rofl:

**Comment by Hoeze** [comment]
haha, sry, I corrected the typo :D (ARP -> too much biochemistry...)

Do you understand German?
https://www.golem.de/news/asynchronous-ratcheting-tree-facebook-demonstriert-sicheren-gruppenchat-fuer-apps-1801-132095.html

**Comment by Hoeze** [comment]
I am no cryptologist, I just tried to point Conversations on this project :)

**Comment by vanitasvitae** [comment]
I am not sure, but wasn't that the group chat protocol which recently had security issues?

**Comment by licaon-kter** [comment]
@vanitasvitae That was the current Signal based one, this is a new one, not sure if deployed anywhere or only 'white paper'

**Comment by iNPUTmice** [comment]
Currently not on our todo list. FWIW Conversations uses the 'inefficient' variant that 'doesn't scale well' the article is talking about. Not the insecure way.
