### ISSUE TITLE
transformClassesWithAndroidGradleClassShrinkerForFreeDebug

### ISSUE THREAD

**Issue by yinyanrong** [siacs/Conversations#2782]
#### General information

* **Version:** eg 1.21.0
* **Device:** eg Google Nexus 5
* **Android Version:** eg Android 6.0 Stock or Android 5.1 Cyanogenmod
* **Server name:** eg conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by licaon-kter** [comment]
Could you please write the asked details?

And attach the log (paste it at https://gist.github.com and put the link here).

**Comment by yinyanrong** [comment]
prompted this error when I imported the project

Error:Execution failed for task ':transformClassesWithAndroidGradleClassShrinkerForFreeDebug'.
> SHA-256 digest error for org/bouncycastle/mail/smime/CMSProcessableBodyPart.class

**Comment by licaon-kter** [comment]
You want to fork the project? Try to use the conference: https://github.com/siacs/Conversations#conversations-doesnt-work-for-me-where-can-i-get-help
