### ISSUE TITLE
Updation of ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by jindalAnuj** [siacs/Conversations#2783]
#### Update proposal in [ISSUE_TEMPLATE](https://github.com/siacs/Conversations/blob/master/.github/ISSUE_TEMPLATE.md)

we can add screenshot section in ISSUE_TEMPLATE
we can add a short description in steps to reproduce that what `# Steps to reproduce` is like or we can adds few lines like how do error can be reproduced

@iNPUTmice can i work on above issue If you find it useful

**Comment by iNPUTmice** [comment]
I think the issue template is fine. I don't need screenshots from users to debug the issue.
