### ISSUE TITLE
404 not found error when upload image in server using xmpp?

### ISSUE THREAD

**Issue by Spaculus** [siacs/Conversations#2784]
We are using following link to upload image.we got a get and put url but not upload image in server.
https://xmpp.org/extensions/xep-0363.html

**This is my Response of get & put url**
 
<iq xmlns="jabber:client" to="ios126@localhost/iphone" from="upload.localhost" type="result" id="493162D2-54B8-48DA-9F73-6219AC847D2B">
<slot xmlns="urn:xmpp:http:upload"><get>http://192.168.1.36:5443/upload/fef7d04f1b6a30662156224da3523c9dc12d927d/9AjkATMlOWNzCHLtGNgILegizE4NfVt5mMWlVhaq/493162D2-54B8-48DA-9F73-6219AC847D2B.jpg</get><put>http://192.168.1.36:5443/upload/fef7d04f1b6a30662156224da3523c9dc12d927d/9AjkATMlOWNzCHLtGNgILegizE4NfVt5mMWlVhaq/493162D2-54B8-48DA-9F73-6219AC847D2B.jpg</put>
</slot>
</iq>

**ios code to upload image**

  NSString *urlStr = putValue ;
            NSURL *url = [NSURL URLWithString:urlStr];

            NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url cachePolicy:NSURLRequestUseProtocolCachePolicy timeoutInterval:5.0f];
            request.HTTPMethod = @"PUT";
            
            NSURLSession *session = [NSURLSession sharedSession];
            NSURLSessionUploadTask *upload = [session uploadTaskWithRequest:request fromData:data completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
                
                NSString *strResponse = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
                dispatch_async(dispatch_get_main_queue(),^{
                    [MBProgressHUD hideHUDForView:self.view animated:YES];
                });
                
                if (error != nil) {
                    [CommonUtils showAlertWithTitle:AlertTitle message:error.description];
                } else {
                    NSHTTPURLResponse *httpResponse = (NSHTTPURLResponse *)response;
                    if ([httpResponse statusCode] == 201)
                    {
                        XMPPJID * friendNameJid = [XMPPJID jidWithString:[NSString stringWithFormat:@"%@@%@",[NSString useNameWithUserJid:self.userInfromation.jidStr],kDOMAIN]];
                        XMPPMessage *msg = [XMPPMessage messageWithType:@"chat" to:friendNameJid];
                        [msg addBody:putValue];
                        [[HQXMPPManager shareXMPPManager].xmppStream sendElement:msg];
                    }
                    else
                    {
                        [CommonUtils showAlertWithTitle:AlertTitle message:strResponse];
                    }
                }
                [NSThread sleepForTimeInterval:5.0f];
            }];
            [upload resume];
        }

**response**
![simulator screen shot - iphone 5s - 2018-02-06 at 19 04 34](https://user-images.githubusercontent.com/11421323/35862072-5a8e7316-0b70-11e8-9d15-c48680646739.png)

**Comment by d9h20f** [comment]
What does this have to do with Conversations?
