### ISSUE TITLE
Blank screen while starting new conversation using barcode scanner

### ISSUE THREAD

**Issue by daivat15** [siacs/Conversations#2787]
If one clicks new conversation and then selects 2d barcode scanner, the app pops up with a dialogue prompting the user to install the barcode scanner. In the case that the user rejects this, the app shows a blank screen.
However, a simple tap on the back button can be used to get back to the start conversation screen.
Just thought the app should not show a blank screen.

**Comment by iNPUTmice** [comment]
fixed in eed2d9314558934fd14710970cfa128bb2a13147
