### ISSUE TITLE
No http_upload available since 1.23.5

### ISSUE THREAD

**Issue by Echse27** [siacs/Conversations#2792]
#### General information

* **Version:** e1.23.5
* **Device:** Motorola Moto G4
* **Android Version:** LineageOS 7.1.2
* **Server name:** self hosted 
* **Server software:** Openfire 4.3.0
* **Installed server modules:** Stream Managment, MAM, http_upload
* **Conversations source:**  F-Droid

#### Steps to reproduce

1. Since Update to Conversations 1.23.5 there is no http_upload available in Conversations
2. i'm using a external component to serve this service in Openfire, and i't works great before Conversations 1.23.5 but know Conversations don't detect it.

#### Actual result

No http_upload available inside Conversations...

#### Debug output
No relevant output Data....
````
adb logcat -s conversations
````

**Comment by kriztan** [comment]
Please have a look into #2788
