### ISSUE TITLE
No option to forward a message.

### ISSUE THREAD

**Issue by harshitbansal05** [siacs/Conversations#2802]
#### Expected result

There should be an option to resend or forward a message. 

#### Actual result

Presently, there is no option to forward a message. The user must either copy the message to clipboard and then paste or opt the share option and subsequently choose Conversations. This is however somewhat tedious for the user.

**Comment by licaon-kter** [comment]
What would forward word exactly?

**Comment by harshitbansal05** [comment]
@licaon-kter forward would help user send a message to another contact...

**Comment by iNPUTmice** [comment]
'Share with…' already does that with the 'downside' that you have to select Conversations first but with the upside that it works with other apps as well.
