### ISSUE TITLE
Switch to AppCompat theme 

### ISSUE THREAD

**Issue by iNPUTmice** [siacs/Conversations#2804]
* Switch to AppCompat theme
* Unify API `<21` theme and `>= 21` theme
* ~Add Toolbar instead of ActionBar to every Activity~ (Probably not necessary)

Bonus work:
* Switch the password visibility toggle to the one provided by the support library
* Switch the toggles in the omemo activity to the one from app compat

**Comment by iNPUTmice** [comment]
I wanted to check the feasibility of this change and started a branch here: https://github.com/siacs/Conversations/tree/app_compat

**Comment by iNPUTmice** [comment]
I made a few more changes to said branch

**Comment by harshitbansal05** [comment]
@iNPUTmice i wanted to work on the bonus features.. can I work?

**Comment by iNPUTmice** [comment]
@harshitbansal05 sure. please do two separate PRs though please if you want to do both.

**Comment by daivat15** [comment]
Memorizing Trust Manager library has been removed?

**Comment by daivat15** [comment]
@iNPUTmice you have already merged the two themes right? I think one of the things that is left is to extend AppCompatActivity instead of Activity.
Other than merging the two themes, is there anything else you are looking for?

**Comment by daivat15** [comment]
Is there a workaround for fragments? The v7 appCompat library is not compatible with the v4 Fragment library. I don't think there is a v7 library for fragments.

**Comment by iNPUTmice** [comment]
i don't think you need to touch the fragments at all. This is just for even earlier android versions that don't support fragments.

**Comment by daivat15** [comment]
@iNPUTmice aren't you going to merge the above branch with master?
