### ISSUE TITLE
Problem sending images.

### ISSUE THREAD

**Issue by m53956** [siacs/Conversations#2807]
Hi,

at least since version 1.23.6 sending images is no longer possible. It used to work for a few years with previous versions of Conversations (maybe something introduced with commit  64928d0ff12521bac2805a0e04e1ee0d6c74ace6: "http upload: do not crash on invalid slot responses"?).

I can see on the server that an upload slot is allocated, but no image sent. Conversations immediately says "delivery failed", I can't see any attempt to actually send the image...

The server or the systems on our mobile phones hasn't changed, the only thing changed was the version of Conversations.

Regards
Martin

#### General information

* **Version:** 1.23.6
* **Device:** Google Nexus 6P, HTC One M7
* **Android Version:** Android 6.0.1
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Conversations source:** F-Droid

#### Steps to reproduce

1. send any image

#### Expected result

Image should be sent.

#### Actual result

Image is not sent, instead a message appears under the message that says something like "sending failed"

**Comment by licaon-kter** [comment]
Long press on failed image-> show error message?

Oh, first, update your http_upload_* modules.

**Comment by m53956** [comment]
Long press on the images yields a context menu with these entries (roughly translated, since it is in German):
- share with...
- send again
- delete image

Regarding http_upload modules: I have the latest packages from my distribution, and I wouldn't like to change that right now, because moving yet another part might make troubleshooting this issue more difficult.

It always worked with the server, I've send many images with the current settings and version. As I said, the only thing changed was the version of Conversations...

**Comment by iNPUTmice** [comment]
Downgrade Conversations or upgrade your community modules.

https://github.com/siacs/Conversations/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+http+upload

**Comment by licaon-kter** [comment]
Long press on failed image-> show error message?

Oh, first, update your http_upload_* modules.

**Comment by iNPUTmice** [comment]
By the way you can include multiple paths in your prosody config.

So you can put http_upload from the community repository in a single folder somewhere and add that folder to the paths https://prosody.im/doc/installing_modules then you don't have to change anything with your distributions packages.

**Comment by m53956** [comment]
Thanks for the fast response, updating the modules worked.
