### ISSUE TITLE
Switch From Speaker To Handset While Playing Sound .

### ISSUE THREAD

**Issue by unkn19wn** [siacs/Conversations#2813]
Hi
it`s not Issue but it`s some kind of tricky bug

when we play a received sound every one in room can hear it
it would be good if we could select to heart it from speaker or not .
Thanks For Your Good Worl

**Comment by licaon-kter** [comment]
Lower sound volume?!

/Close as invalid

**Comment by unkn19wn** [comment]
i did not mean lower sound volume

i meant play sounds not on speaker
did you used telegram or something like that ??
what i`m trying to say is if you want to hear a message in public everyone can hear the voice !

**Comment by licaon-kter** [comment]
So when you put the device to your ear (like you do with a phone call) the sound would switch from speaker to... ear piece (or what is that called)? 

Yes, that sounds useful.

**Comment by unkn19wn** [comment]
Exactly what i meant.

**Comment by licaon-kter** [comment]
It's 88 lines on signal https://github.com/signalapp/Signal-Android/commit/2ec3999302672f79f2913dfff2026d75b05d089b

**Comment by harshitbansal05** [comment]
I would be working on this issue..

**Comment by iNPUTmice** [comment]
Note to self; should probably also turn off the display https://github.com/zoff99/Signal-Android/pull/54/commits/07c8db824e87c9926797233a489763099196adcf

**Comment by iNPUTmice** [comment]
Implemented in current `master`.
