### ISSUE TITLE
FR - Custom notifications for individual chats

### ISSUE THREAD

**Issue by daivat15** [siacs/Conversations#2816]
It would be great if users can set custom notifications i.e., change ringtones and notification lights for different contacts in private chat. The feature can be extended to change even vibration patterns for different users. I believe this is possible from API 26 onwards.

**Comment by daivat15** [comment]
@licaon-kter I believe this is a upgrade to 2002. Personally I as a user am very particular about the color of the notification lights also.

**Comment by licaon-kter** [comment]
If it's the same issue, add your voice there.

**Comment by daivat15** [comment]
@licaon-kter Noted :)
