### ISSUE TITLE
Why not using native network libraries?

### ISSUE THREAD

**Issue by aurora-potter** [siacs/Conversations#2819]
A native network library works faster and is more compatible.
C and C++ libraries can bypass Java-based app-wide proxies, in cases of unwanted traffic interception or malicious manipulation of the app to proxy all network data.

Find a list of native network libraries <a href="https://stackoverflow.com/questions/118945/best-c-c-network-library">here</a>.

**Comment by iNPUTmice** [comment]
Nope.

**Comment by aurora-potter** [comment]
@iNPUTmice Why?
