### ISSUE TITLE
[feature request] Provide support for Tox protocol

### ISSUE THREAD

**Issue by aurora-potter** [siacs/Conversations#2820]
Read more about this open-source protocol at <a href="https://en.wikipedia.org/wiki/Tox_(protocol)">Wikipedia</a>.

**Comment by SamWhited** [comment]
Conversations already has a messaging protocol, it doesn't need another. Please try to explain why you want something, what benefits it would provide, etc. before opening feature requests. Thanks!

**Comment by licaon-kter** [comment]
@aurora-potter Use Trifa or Antox.

**Comment by aurora-potter** [comment]
Because Tox is an open protocol and it could be a good companion for XMPP.
Bringing the anonymity and PGP encryption powers of Conversations and the security of Tox in one place is wonderful.


@licaon-kter I'm already familiar with Anyox, but that doesn't support user-defined encryption or Tor proxy.

**Comment by licaon-kter** [comment]
@aurora-potter Antox supports Tor, [albeit not perfect](https://github.com/Antox/Antox/issues/created_by/licaon-kter). But enough with this.
