### ISSUE TITLE
Feature Request: Protecting the App with Password

### ISSUE THREAD

**Issue by max421** [siacs/Conversations#2821]
#### General information

* Version: 1.23.6
* Device: Xperia Z3
* Android Version: CarbonROM 5.1 (Android 7.1.2)
* Conversations source: F-Droid

I would be happy if is possible to protect the app with a password and enrypted the already received messages. I'm make this request because i used Signal in past and i like this feature very much.

**Comment by daivat15** [comment]
I understand encrypting the already received messages. Could you just elaborate on "protecting the app"? Is an app lock not appropriate?

**Comment by iNPUTmice** [comment]
see my argument in #2390
