### ISSUE TITLE
GPG-MUC Default-Memberlist for disconnects

### ISSUE THREAD

**Issue by Xziped** [siacs/Conversations#283]
Thanks for this nice MUC-Crypto-Client.
We have the Problem that when we send a message to the MUC and someone is Offline or have a short disconnect he cant read the Message because the Message is not written for the Offline People. It would be nice to have the Possibility to set a Default-Member-Group to a Conference. So we can define that all Messages to this Conference would be readable by the default-member-group also when they where offline :)

**Comment by benediktg** [comment]
I think what you want is MAM (message archive management) for MUCs.
