### ISSUE TITLE
HTTP upload unavailable with Version 1.23.5 and 1.23.6

### ISSUE THREAD

**Issue by eptesicus** [siacs/Conversations#2832]
#### General information

* **Version:** 1.23.5 + 1.23.6
* **Device:** various
* **Android Version:**  Android 7.1
* **Server name:** self hosted
* **Server software:** prosody 0.9.12
* **Installed server modules:** Stream Managment, CSI, MAM, Carbons, HTTP Upload
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Install Conversations >= v1.23.5
2. Open account details
3. Show server info

#### Expected result

XEP-0363: HTTP File Upload available

#### Actual result

XEP-0363: HTTP File Upload unavailable

HTTP upload does not work with Version 1.23.5 and 1.23.6. After manually downgrading to v1.23.4 HTTP upload works again.

**Comment by licaon-kter** [comment]
/duplicate of duplicate of #2807 #2792 #2788 #2818 #2796 #2822

Update your http_upload_* modules

**Comment by eptesicus** [comment]
Thanks, sorry for the noise.
