### ISSUE TITLE
[Feature request] Send a custom expression

### ISSUE THREAD

**Issue by SoyaLeaf** [siacs/Conversations#2835]
Something like this：
![screenshot_2018-02-25-14-49-22](https://user-images.githubusercontent.com/20620071/36640639-eeb537e0-1a5d-11e8-8d85-d1331f0ad589.png)

In fact, just send a picture,

but a bit different:

1. Provide a local repository for storing pictures.
2. Provide shortcuts, user-friendly to send.
3. Send the picture size limit.

**Comment by licaon-kter** [comment]
Duplicate of #2122 #2757 #1388

**Comment by SoyaLeaf** [comment]
Thanks for reminding :)
