### ISSUE TITLE
HTTP-Upload error: invalid response to slot request

### ISSUE THREAD

**Issue by allo-** [siacs/Conversations#2836]
#### General information

* **Version:** 1.23.6
* **Server name:** self-hosted
* **Server software:** prosody 0.9
* **Installed server modules:** http_upload
* **Conversations source:** PlayStore

#### Steps to reproduce

Try to send an image or to resend an failed image upload.

#### Expected result

Image is sent

#### Actual result

upload fails

#### Debug output

````
02-26 18:39:15.157 26224 16087 D conversations: user@host/phone: invalid response to slot request <iq to="user@host/phone" from="host" xmlns="jabber:client" type="result" id="XXX"><slot xmlns="urn:xmpp:http:upload:0"><get xmlns="urn:xmpp:http:upload:0">https://host:5281/upload/YYY.jpg</get><put xmlns="urn:xmpp:http:upload:0">https://host:5281/upload/YYY.jpg</put></slot></iq>
````

It seems, that this changed with a conversations update some time ago. There were no changes on my server and it fails when sending to several other servers including conversations.im.

**Comment by licaon-kter** [comment]
/duplicate of duplicate of #2807 #2792 #2788 #2818 #2796 #2822 #2832

Update your http_upload_* modules

**Comment by allo-** [comment]
Thank you.
