### ISSUE TITLE
gradle test target does not work because of compilation issues

### ISSUE THREAD

**Issue by michaxm** [siacs/Conversations#2837]
#### General information

* **Version:**
current master, commit 7e09fac1da1a8e3783dbc40952f3324acc57ad84

#### Steps to reproduce

1. ./gradlew test

[yay, tests! first thing I execute with a new code base...]

#### Expected result

Test run (hopefully successful).

#### Actual result

./gradlew test

> Configure project :libs:EnhancedListView 
Configuration 'compile' in project ':libs:EnhancedListView' is deprecated. Use 'implementation' instead.
The CompileOptions.bootClasspath property has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the CompileOptions.bootstrapClasspath property instead.

> Task :compilePlaystoreDebugJavaWithJavac 
/home/axm/projects/Conversations/src/playstore/java/eu/siacs/conversations/services/PushManagementService.java:48: error: cannot find symbol
                                                                Element x = command.findChild("x", Namespace.DATA);
                                                                                                   ^
  symbol: variable Namespace
/home/axm/projects/Conversations/src/playstore/java/eu/siacs/conversations/services/PushManagementService.java:94: error: cannot find symbol
                                        String token = instanceID.getToken(mXmppConnectionService.getString(R.string.gcm_defaultSenderId), GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);
                                                                                                                    ^
  symbol:   variable gcm_defaultSenderId
  location: class string
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compilePlaystoreDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

=> either remove tests or fix compilation?

**Comment by michaxm** [comment]
Also fails on release 1.23.6, but with different errors.

**Comment by iNPUTmice** [comment]
Please read the Readme. (that should really be the first step before
running tests even)
You need to compile the free flavor

**Comment by michaxm** [comment]
I did and generating build/outputs/apk/free/debug/Conversations-1.23.6-free-debug.apk was not a problem (I am a newb and still figuring out how to install this in lineage os) - I considered the broken tests as a separate issue - at least I have not yet spotted what the README has to do with it.

But nevermind.
