### ISSUE TITLE
SuppressLint missing in conversation fragment

### ISSUE THREAD

**Issue by harshitbansal05** [siacs/Conversations#2840]
There is a false lint warning regarding invalid string format in Conversation fragment line `Toast.makeText(activity, activity.getString(R.string.user_has_left_conference, user.getResourcepart()), Toast.LENGTH_SHORT).show();`. We must use the SuppressLint annotation to suppress this warning.

**Comment by eanekrasov** [comment]
I think, the better way is change `%s` to `%1$s` in all `strings.xml` files.

**Comment by iNPUTmice** [comment]
The issue is caused by the polish translation not having the `%s` in it. Not having `%1$s` doesn't make a difference I don't think
(I've been meaning to tell the polish translators about the issue but didn't get around to it)
