### ISSUE TITLE
When i Sending the image  the Android to IOS client. not secure(image not) coming. 

### ISSUE THREAD

**Issue by shravanteegala** [siacs/Conversations#2842]
#### General information

* **Version:** eg 1.21.0
* **Device:** eg Google Nexus 5
* **Android Version:** eg Android 6.0 Stock or Android 5.1 Cyanogenmod
* **Server name:** eg conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````
Hi,
Every one plz. solve my issue.

i text chat is working fine Android to android . and aandroid to Ios and viceversa.
But When i trying to sending image Android to android woking..
but Android to IOS Client not working. (it shows the url is not secure.)
How  I can solve this issue. plz help me.

**Comment by iNPUTmice** [comment]
Everything you send with a closed lock icon and that has the lock (or verified icon in the bubble) will be encrypted.

**Comment by shravanteegala** [comment]
Hi,
My problem is text chat is working fine Android to IOS   but.  When i sending the image Android to IOS the image is not coming (Due to encrypted url string. ) .

How i convert Encrypted url ( coming from android ) to Decrypt in IOS .
plz help me.
