### ISSUE TITLE
How i Can remove the  encryption & decryption, when i send the images to other plaform ?

### ISSUE THREAD

**Issue by shravanteegala** [siacs/Conversations#2843]
#### General information

* **Version:** eg 1.21.0
* **Device:** eg Google Nexus 5
* **Android Version:** eg Android 6.0 Stock or Android 5.1 Cyanogenmod
* **Server name:** eg conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. …
2. …

Hello.
How  I can remove the when i send the image url (encrypted) to other ploatforms like javascript(web),Ios clients. how ii Decrypted it.

plz solve me this one.

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
There is https://github.com/iNPUTmice/ImageDownloader/

For general questions the chat room is a better place then opining tickets on github.
