### ISSUE TITLE
How i decrypt received image url to other chat clients . like JavaScript,ios etc from Android Client(image sending ..client ).

### ISSUE THREAD

**Issue by shravanteegala** [siacs/Conversations#2846]
Hi,
My problem is text chat is working fine Android to IOS but. When i sending the image Android to IOS the image is not coming (Due to encrypted url string. ) .

How i convert Encrypted url ( coming from android ) to Decrypt in IOS .
plz help me.

**Comment by d9h20f** [comment]
The other client needs to support encrypted file links, that's it. Also, this is a bug tracker and not a place for general questions. For that, go to the Conversations group chat: https://conversations.im/j/conversations@conference.siacs.eu

**Comment by iNPUTmice** [comment]
please have a look at the link in the other issue.
