### ISSUE TITLE
White screen persisting for some duration on app startup

### ISSUE THREAD

**Issue by harshitbansal05** [siacs/Conversations#2847]
#### General information

* **Version:** 1.23.7 (Branch: `app_compat`)
* **Device:** Redmi Note 3
* **Android Version:**  Android 5.1 Stock
* **Server name:** xmpp.jp
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

Open Conversations application.

#### Expected result

The white screen should be replaced by the logo of the Conversations app.

#### Actual result

A white screen persists for some duration of time.

**Comment by licaon-kter** [comment]
So the app loads really slow on your device?

On every startup?

I can't repro this on Huawei 8.0 or Samsung 6.0.1

**Comment by harshitbansal05** [comment]
@licaon-kter It occurs when I open app after completely closing it (swiping from the recents screen). Probably, the problem with white background is caused because of android's cold start while the app loads to memory.

**Comment by licaon-kter** [comment]
And compared to the normal app version, that one starts fast?

**Comment by harshitbansal05** [comment]
@licaon-kter it shows a blank screen with an action bar in the normal app version.

**Comment by licaon-kter** [comment]
What actionbar? You mean titlebar?

**Comment by harshitbansal05** [comment]
yes @licaon-kter...

**Comment by harshitbansal05** [comment]
@licaon-kter is it worth working?

**Comment by licaon-kter** [comment]
Do get some logs of the start process

**Comment by iNPUTmice** [comment]
This depends on the number of open conversations and the speed of the storage and can happen - I experience this myself because a have **a lot** of open conversations with **a lot** of messages in them.

Not sure that a loading screen is the right solution though. It's kind of an anti pattern on android.

**Comment by licaon-kter** [comment]
@iNPUTmice Didn't Google backtrack on this since Material? Eg. https://material.io/guidelines/patterns/launch-screens.html

**Comment by iNPUTmice** [comment]
Maybe. I don’t see a lot of the Google apps using it though.

**Comment by licaon-kter** [comment]
@iNPUTmice I saw it on YouTube and Hangouts at least.

**Comment by iNPUTmice** [comment]
The app compat branch has a splash screen.
