### ISSUE TITLE
FR: Show which client software a contact uses & it's version

### ISSUE THREAD

**Issue by STPKITT** [siacs/Conversations#2853]
In Gajim the user can right click a contact and then select "Information". This will show the user the name of the client software the contact uses and also the version of that client software (provided the contact sends that information of course).
Conversations should also offer that feature, because it would massively help figuring out issues people encounter using Jabber.

**Comment by iNPUTmice** [comment]
Conversations is aiming to be a tool to debug other peoples clients.

**Comment by STPKITT** [comment]
Pretty ignorant answer since your mantra was to make Conversations a client for the masses. Conversations should help to at least debug it's own customers, cause most problems came from people running too old Conversations versions. Alternatively Conversations should push some kind of message to people running versions of Conversations that are practically incompatible with the current version, as it happened when something in OMEMO was changed last year.

**Comment by licaon-kter** [comment]
@STPKITT If users don't want to pay iNPUTmice for his work, why don't they just install F-Droid and keep Conversations up to date?

**Comment by STPKITT** [comment]
@licaon-kter your comment makes zero sense since it has absolutely nothing to do with this feature request.

**Comment by licaon-kter** [comment]
Didn't you just say:

> _most problems came from people running too old Conversations versions_

Why are they doing that?

> _it happened when something in OMEMO was changed last year_

Exactly this happened, they were all downloading APKs from the F-Droid page calling it a day, 1 year later, oops... incompatibility.

**Comment by STPKITT** [comment]
Ok, this still has nothing to do with getting Conversations from Playstore or F-Droid, I don't know how you came up with that.
People run old versions because they disabled auto-updates, Google Play telling them not enough space on device, they are afraid to update anything because of bad experiences they made with updates in the past (not Conversations, but in general), they swipe away update notifications because those pop up when people are doing other stuff & not wanting to deal with technical stuff in that moment.

Consider: all above observations do not apply to experte, nerds etc. but the average Joe NOT into tech at all.
I'd like to be able to help those people solve the problems they may incounter with XMPP before they get frustrated and stop using it.

**Comment by licaon-kter** [comment]
The average Joe does not disable auto-updates.

Auto-updates don't take additional space, but will fail indeed if there is not enough free space.

The version number is in Settings, either opening that is hard or updating from (a) Store is easier.

Anyway, this feels like a wrong solution for would-be problems.

**Comment by STPKITT** [comment]
Maybe I know extraordinary average Joes.

One problem I came across three times already is that auto updates by default are only done when there's a WLAN connection. Trouble is I know people who never use WLAN with the result, that they never get auto updates.

Yes, the version number is in settings, but a user using a Conversations version prior to that OMEMO change would've never even become aware of a problem, because he never got an error message. It was just that the chat partner never received those messages. So how would the average Joe know? It was great that I could see people running outdated version in my Gajim rooster, otherwise I too would've never known that several people could not communicate with me anymore.

So to me it would be awesome if Conversations would offer a button in contact details menu to show the contacts client information. It would't even clutter the GUI that way.

**Comment by iNPUTmice** [comment]
> Alternatively Conversations should push some kind of message to people running versions of Conversations that are practically incompatible with the current version

This is a way better solution to the problem you are describing because it works independently of having a tech savvy friend who checks your Conversations version for you.

**Comment by STPKITT** [comment]
Ok, I imagine that it might be more difficult to implement though, but I'm not a programmer. If it's feasible please go for it, I think it would be an awesome feature applicable to the broad userbase.
