### ISSUE TITLE
Forced OMEMO breaks message sending to non-compatible clients

### ISSUE THREAD

**Issue by mrDoctorWho** [siacs/Conversations#2855]
#### General information

* **Version:** 2.0.0 beta
* **Device:** Google Pixel
* **Android Version:** 8.1.0 Stock
* **Server name:** self hosted
* **Server software:** prosody trunk
* **Installed server modules:** Stream Managment, CSI, MAM, http upload external
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. Find a contact that doesn't support OMEMO and never had this enabled
2. Write a message / pick a file to send
3. Conversations tries to receive OMEMO fingerprints and fails, which causes messages not to be sent

#### Expected result

I expected that message will be sent.

#### Actual result

An activity with title "Trust OMEMO Fingerprints" appeared and said that there was an error receiving OMEMO keys.

**Comment by licaon-kter** [comment]
So it should downgrade to unencrypted?

**Comment by mrDoctorWho** [comment]
In my opinion, it's useless to force something that's not supported, especially when it makes the application unusable. I understand that conversations must be encrypted at the endpoints, but that's just not the case, in my opinion.

For a regular user who has no idea about OMEMO and stuff it might be a little weird that application can't "just work".

**Comment by iNPUTmice** [comment]
Thankfully it is not forced but only the default.
Steps to send an unencrypted message:
1) Find the encryption icon in the action bar
2) Click the encryption icon
3) Select 'None'
4) Send message
5) …
6) Profit

There will be a series of blog post leading up to the release of Conversations 2.0 that will explain some of the changes.

**Comment by mrDoctorWho** [comment]
Yeah, I said that wrong, but I don't think that's a good idea after all.

Thanks for the reply anyways.
