### ISSUE TITLE
Forced OMEMO breaks - something

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2858]
Current way of thing does not give any clue on "why" it fails.

Eg. Contact is OFFLINE: It fails because of a lack of keys... and you know that means little for *most* of the users, but what matters is that you leave them in that screen that only has a CANCEL button, you don't inform them that `hey just press back, lock, unencrypted and it WILL work`. The current message is a dead end.

My thought, ok you want OMEMO by default ([and you've changed your mind](https://github.com/siacs/Conversations/commit/035d0c79572d5981c53d1bff7f30b484c6542f17)) then try to use OMEMO, but if it fails **now**, try later.

So:
* try
* no keys
* show dialogue: `Not currently possible: SEND UNENCRYPTED AND RETRY/ONLY UNENCRYPTED`
* if RETRY: now you send unencrypted, but later (hours/days), retry, if you succeed switch to OMEMO, if not, retry later

Thoughts?

**Comment by mrDoctorWho** [comment]
In my opinion, the dialogue should offer the user to disable OMEMO. That at least won't be so harsh after enabling it for all contacts.

**Comment by iNPUTmice** [comment]
beta.3 has that dialog build in.
