### ISSUE TITLE
GUI glitch in certain MUC situation

### ISSUE THREAD

**Issue by STPKITT** [siacs/Conversations#2865]
#### General information

* **Version:** 1.23.8
* **Device:** Samsung Galaxy S3 Mini
* **Android Version:** Android 5.1.1 Cyanogenmod 12.1
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Join a public MUC, where you become a visitor (no rights to write something) when joining, for example xmpp:support@room.pix-art.de?join / https://conversations.im/j/support@room.pix-art.de

2. Short click on a user name. That will put "username:" into the typing area

The problem is now that you can't get rid of the username in the typing area (since when being a visitor you can't bring up the keyboard by clicking the typing area as you'd normally do). You can add more usernames to it by clicking them, but the only way to get back to the original state (showing the user "Du bist kein Mitglied" /"You're not a member") of the typing area is by long-clicking a username as if you'd do to start writing a PM and then canceling that.

#### Steps to reproduce
Proposed solution: short-clicking a username in the MUC in which you're currently only a visitor should not trigger putting the username into the typing area. Instead maybe a popup message could remind the user that he is currently not permitted to write anything in this MUC apart from PMs.

**Comment by l-jonas** [comment]
I will work on this
