### ISSUE TITLE
App not working in wireless lan

### ISSUE THREAD

**Issue by patrikreiske** [siacs/Conversations#2870]
#### General information

* **Version:** 1.23.8
* **Device:** Google Pixel 2
* **Android Version:** Android 8.1.0 Stock
* **Server name:** iodoru.org
* **Server software:** _unknown_
* **Installed server modules:** _unknown_
* **Conversations source:** Google Play Store

#### Steps to reproduce

1. Connect to wireless lan
2. Add account as well as send/receive messages

#### Expected result

Log in account respectively Messages being send/received

#### Actual result

Nothing happens. There's not even an error message

**Comment by SoyaLeaf** [comment]
Maybe you can try to connect to the server with other clients. :)

**Comment by patrikreiske** [comment]
The app is working when I'm not in my wireless lan network. But when I'm using dino.im on my notebook (in my wireless lan network) it is working. Same firewall settings for both, phone and notebook

**Comment by iNPUTmice** [comment]
Please provide the output of adb logcat during that connection attempt.

**Comment by patrikreiske** [comment]
Sorry, I don't have the time at the moment. Can't you just test it? Or is there a way to simply automatically send the report from within the app?

**Comment by iNPUTmice** [comment]
No. I can't just test it. It works fine for a couple of thousands users including myself. So it has to be something specific to your Wifi.

**Comment by patrikreiske** [comment]
Funny thing: The app seems to be working now fine using wireless LAN networks. Closing this ticket.
