### ISSUE TITLE
Send image to all devices without asking

### ISSUE THREAD

**Issue by hubgitbb** [siacs/Conversations#2871]
#### General information

Version: 1.23.8
Device: different devices
Android Version: Android 7.0 Stock and Android 6.0.1
Server name: self hosted
Server software: prosody 0.10
Installed server modules: smacks, mam, carbons. roster, saslauth, tls, disco, private, default_vcard, bosh, http, http_upload, proxy65, posix
Conversations source: F-Droid

#### Actual result

1. user1 sends image via android conversations app  to user2 with android device and gajim 
2. user1 gets asked to wich of the devices from user2 he wants to send the image 

#### Expected result

dont ask user1
send image to all devices of user2 

Conversation 1.22 does not have this behavior.

Regards

**Comment by iNPUTmice** [comment]
Please update your http upload module.

**Comment by hubgitbb** [comment]
the  http upload module is uptodate.
