### ISSUE TITLE
Beta crashes on app startup

### ISSUE THREAD

**Issue by ibot87** [siacs/Conversations#2873]
#### General information

* **Version:** 2.0.0-beta.2
* **Device:** Cyrus CM16
* **Android Version:** Android 4.2.2 Stock
* **Server name:** fem-net.de
* **Server software:** ejabberd 18.01
* **Installed server modules:** completely green on Compliance
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. Start conversations.

#### Expected result

1. Conversations should start.

#### Actual result

The conversations logo shows up for ca. 1 second. After that the app crashes ("Conversations has ended." I can choose between report and OK.)

#### Debug output

Unfortunately there is not much:

````
adb -d logcat -v time -s conversations
03-13 20:57:07.802 D/conversations(20251): onCreateView
03-13 20:57:07.850 D/conversations(20251): ConversationsOverviewFragment.onStart()
03-13 20:57:07.850 D/conversations(20251): ConversationsOverviewFragment.onResume()
03-13 20:57:07.859 D/conversations(20251): EmojiService succeeded in loading fonts
````
The previous version (1.23.8) worked fine for several months. If I go back from beta to 1.23.8 there is also no problem:
````
03-13 21:06:36.608 D/conversations(21376): EmojiService succeeded in loading fonts
03-13 21:06:36.781 D/conversations(21376): initializing database...
03-13 21:06:36.781 D/conversations(21376): restoring accounts...
03-13 21:06:36.830 D/conversations(21376): restoring conversations...
03-13 21:06:37.012 D/conversations(21376): finished restoring conversations in 181ms
03-13 21:06:37.012 D/conversations(21376): restoring roster...
03-13 21:06:37.018 D/conversations(21376): stopped foreground service
03-13 21:06:37.019 D/conversations(21376): update unread count to 0
03-13 21:06:37.165 D/conversations(21376): name@fem-net.de: socket was null during force close
03-13 21:06:37.165 D/conversations(21376): name@fem-net.de: connecting
03-13 21:06:37.468 D/conversations(21376): app switched into foreground
03-13 21:06:38.316 D/conversations(21376): Resolver: [Result{ip='IP', hostame='xmpp.fem-net.de', port=5222, directTls=false, authenticated=false, priority=10}, Result{ip='IP', hostame='xmpp.fem-net.de', port=5222, directTls=false, authenticated=false, priority=10}]
03-13 21:06:38.329 D/conversations(21376): name@fem-net.de: using values from dns xmpp.fem-net.de/IP:5222 tls: false
03-13 21:06:39.137 D/conversations(21376): name@fem-net.de: TLS connection established
03-13 21:06:39.166 D/conversations(21376): name@fem-net.de/phone: Authenticating with SCRAM-SHA-1
03-13 21:06:39.378 D/conversations(21376): restoring messages...
03-13 21:06:39.556 D/conversations(21376): start merging phone contacts with roster
03-13 21:06:39.558 D/conversations(21376): finished merging phone contacts
03-13 21:06:39.966 D/conversations(21376): name@fem-net.de: logged in
03-13 21:06:39.998 D/conversations(21376): update unread count to 2
03-13 21:06:40.000 D/conversations(21376): finished restoring messages in 622ms
````
I've got no problems with conversations beta and this account on another device.

**Comment by iNPUTmice** [comment]
You have to omit the `-s conversations` to record crashes.

**Comment by ibot87** [comment]
Ok, i tried to get the log only from the beginning of the application start. You can find the log here:
[conversations-log.txt](https://github.com/siacs/Conversations/files/1808620/conversations-log.txt)

**Comment by iNPUTmice** [comment]
Thank you for the report. Unfortunately this is nothing I'm planning to fix. Apparently the library we now use to handle Jids doesn't support pre KitKat. Thus we bumped the minimum android version to 4.4.
Conversations 1.23.8 will continue to work though and will remain compatible for quite some time I imagine.

**Comment by maikkeli** [comment]
Should 2.0.0-beta.2 refuse to install on 4.2.2?

My 4.2.2 device happily installed it (and failed to run it of course) -- is there a minimum version/feature that should be set in AndroidManifest.xml to prevent <4.4 installing it?

**Comment by licaon-kter** [comment]
Yes, 4.4 is now the new minimum.
