### ISSUE TITLE
Use newly introduced notification channels

### ISSUE THREAD

**Issue by harshitbansal05** [siacs/Conversations#2875]
Since from api level 26, `NotificationCompat.Builder(Context context)` is deprecated, I think it would be better to use notification channels, introduced in Android O. They would give us the ability to group notifications into groups and at the same time make it easy for user to manage notification channels.

**Comment by iNPUTmice** [comment]
There is already a pull request for this. But I currently don’t know enough about notification channels to properly review it.

**Comment by licaon-kter** [comment]
This would be nice. Eg. Put the useless "Conversations is running Touch to open" that you are forced to have with Foreground service in a "service" channel and then hide only that since you can control visibility per channel.

**Comment by daivat15** [comment]
@licaon-kter are you sure foreground services can be hidden from the notification bar? The whole point of having a foreground service is to keep the user and the Android system actively aware that such a service is running. Hiding it will destroy the whole point. It is a really good idea, but are you sure Android allows this?

**Comment by licaon-kter** [comment]
No, these are not exclusive. The notification is there because Android forces you, but it allows you to hide notifications.

**Comment by daivat15** [comment]
@licaon-kter I did some research. I believe this is allowed only after Android 8.1 (API 27). Am I right?

**Comment by licaon-kter** [comment]
The channels yes, the hiding is there since 5.0, albeit you'll hide new messages notifications dn Conversations case thene

**Comment by daivat15** [comment]
@licaon-kter I think we can hide the notification when the app is writing logs also. What say?

**Comment by iNPUTmice** [comment]
The export log notification is used to track the progress. Hiding that
would be problematic

**Comment by daivat15** [comment]
@iNPUTmice Noted thanks!

**Comment by iNPUTmice** [comment]
has been implement in 2.3.0
