### ISSUE TITLE
Use of lambda expressions throughout the app.

### ISSUE THREAD

**Issue by harshitbansal05** [siacs/Conversations#2876]
Currently, lambda expressions are not used everywhere in the app. We should make use of them as they are easier to use and also helpful in writing cleaner code.

**Comment by SoyaLeaf** [comment]
Sorry, but I don't think this can be a issue，I mean maybe this question doesn't need to be discussed，
 you can update it if you have free time ,I think @iNPUTmice  will be happy to merge it. I'm sorry if I'm offended. :)
