### ISSUE TITLE
Servers that append information to requested resourcepart can lead to invalid JIDs

### ISSUE THREAD

**Issue by SamWhited** [siacs/Conversations#2877]
#### General information

* **Version:** 2.0.0-beta2
* **Server name:** self hosted / private
* **Server software:** HipChat Server
* **Installed server modules:** Roster versioning… that's about it.
* **Conversations source:** self build (fe90e70b)

HipChat Server always adds routing information to the end of the resource part requested by the client during bind. Conversations then saves the JID, and the next time it reconnects it requests the same JID (including the routing information added by HipChat Server). Unfortunately, HipChat server then adds new routing information to the end of that JID and sends it back. The next time it connects, Conversation sends the updated (even longer) JID, etc.

After a few reconnects the JID is too long to be valid and parsing it at [`XmppConnection.java:1023`](https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/xmpp/XmppConnection.java#L1023) fails (`IllegalArgumentException` is thrown and "server reported invalid jid … on bind" is logged).

I have temporarily enabled the `USE_RANDOM_RESOURCE_ON_EVERY_BIND` build option to fix this. A more permanent fix might be to make that the default, or to reconnect with the resourcepart that the user has selected (eg. "Conversations" or "Phone") and not save the server generated resourcepart.

I am not sure if this happens with other servers.

**Comment by iNPUTmice** [comment]
Usually we want to connect with the same resource again because a) that will usually kick potential stale sessions b) we want the resource to be semi persistent to ease debugging on the server side

1bfc0b8da6953639535805cb19a60c7630eb765d attempts to be a bit smarter about this and only remove the part the server added.

**Comment by SamWhited** [comment]
That seems to have fixed it; thanks.
