### ISSUE TITLE
Read marker like Whatsapp

### ISSUE THREAD

**Issue by rajil** [siacs/Conversations#2878]
Whatsapp shows a tick for delivered message and another one for read message. Is it possible to show the read marker in Conversations?

**Comment by licaon-kter** [comment]
If both contacts have presence (see contact details) enabled, and Settings -Privacy (all 3 boxes), you see that _"contact has read up to this point"_

**Comment by rajil** [comment]
I did not see the markers between gajim and conversations. I guess gajim doesnt support this feature.
