### ISSUE TITLE
XEPs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [siacs/Conversations#2879]
It is possible to have a XEPs support page with version?
https://conversations.im/

Examples:
- https://metronome.im/supported-xeps-list
- https://trac.gajim.org/wiki/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by iNPUTmice** [comment]
there is `docs/XEPs.md`

**Comment by Neustradamus** [comment]
No, version is not :)
Can you add XEP versions?

**Comment by Neustradamus** [comment]
For the link without RFCs and XEPs version: https://github.com/siacs/Conversations/blob/master/docs/XEPs.md

**Comment by Neustradamus** [comment]
@iNPUTmice: Can you add versions?

Example:
- RFCXXXX
- XEP-XXXX v1.2
