### ISSUE TITLE
Don't have "Larger fonts" option in beta of version 2.0

### ISSUE THREAD

**Issue by ruNightRomantic** [siacs/Conversations#2884]
Option to enlarge text in Conversations is quite useful to me, I always had it enabled prior to version 2.0 beta. Now there's no such option in application settings. Please, consider returning it, maybe to advanced settings (if it was removed to simplify settings UI).

To clarify, I use larger system fonts in Android, and also had this option in Conversations enabled (i.e. just larger system fonts in Android is not sufficient).

#### General information

* **Version:** eg 2.0.0-beta.2 (F-Droid)
* **Device:** Samsung Galaxy s3
* **Android Version:** Android 7.1.2 LineageOS
* **Conversations source:** F-Droid

#### Expected result

I'd like to see an option to enlarge font/text size in Conversations settings screen.

#### Actual result

There is no such option in version 2.0.0-beta2 (and beta1 also).

**Comment by licaon-kter** [comment]
Doesn't Android 7 have two UI+font size options?

**Comment by ruNightRomantic** [comment]
The way I had it was: Android UI font size: "Large" (one step larger than default) + enabled large text setting in Conversations, and that was perfect balance for me.

Right now with Conversations 2.0 beta if I set Android UI font size to "Maximum", then I have some UI elements (in Android as well as Conversations) uncomfortably large -- while chat text size in Conversations still quite small. Setting Android UI "Display size" option to "Large" doesn't rectify the problem.

I understand these relative text sizes are controlled by OS theming. My point is it can be useful for some users to have the ability to enlarge **chat text size** in Conversations in addition to global system settings. It certainly was for me.

**Comment by SamWhited** [comment]
On a relatively stock Android device I also was using this option. I can bump the system font size up, but Conversations appears to have a smaller font size (or maybe there's just more text crammed together because it's chat so it looks smaller?) by default than most of the apps I use day to day, so by the time it's big enough to be readable those apps are too large.

**Comment by iNPUTmice** [comment]
If the font size appears or actually is smaller than those of other apps
it'd be interested in finding out why. (independently of that option coming
back in a revised form).
Conversations is using exactly the font size and font weight recommended by
the material design guidelines and they have the exact Pixel height as the
Gmail app for example. I took Screenshots and measured it.

**Comment by ruNightRomantic** [comment]
Daniel, I've made additional checks.
You're completely right, font size and weight used by Conversations 2.0 is exactly the same as the demo text in Android Settings -> Font Size and other apps that use default font size. Problem is, this font size is too small for me to read long messages/conversations (i.e. dialogues) comfortably. 
Thing is, Conversations is one of the most used apps for me on my phone -- although most of the time I use desktop jabber/xmpp client. When I'm reading on my phone -- most of the times it's chats in 
Conversations.

Regarding other apps. 
- Browsers generally have some means to enlarge website's font or to enable "Reader mode". 
- Email client (I use K9 Mail) -- most letters are html and font size is defined by html template used, therefore some mails are comfortable to read and some aren't. For letters in plain text K9 Mail uses standard font size (the same as Conversations 2.0) and I have to strain a bit, but I seldom read log emails on my phone.
- SMS/Messages app -- Lineage default. This one's a bit interesting. It uses default font size for *list* of messages, but then uses *larger* font for actual sms texts. I checked to see if I enabled some special option for that and found none. It seems app developer had experience similar to mine ) Then again, sms's are generally not very long.
- I started to use Signal some time ago (could not agitate a person to switch to jabber) -- it has an option to increase font size *for dialogues only*, without changing any UI elements.
- I use no other messenger apps, can't say if they are doing anything to increase readability.

Implementation in Signal is the best one in my opinion. I can choose size of UI elements using Android settings -- globally for all apps. And if the size of text contents I **actually need to read** is not comfortable -- I can adjust it for application I care about (Conversations).

If it's not too much to ask)

It's quite subjective, of course.  For me, I think, it's a combination of my near-sightedness and not very big screen size of my phone (hence too big UI elements are not desirable).

**Comment by SamWhited** [comment]
> Conversations is using exactly the font size and font weight recommended by the material design guidelines and they have the exact Pixel height as the Gmail app for example. I took Screenshots and measured it.

Then I suspect it's just harder to read because messages tend to be short, but dense (and a lot of them pile up). The line height may also be different and is worth looking at. If message density is an issue, adjusting the line height is probably a better fix than adjusting the font size anyways.

**Comment by iNPUTmice** [comment]
> The line height may also be different and is worth looking at. 

I just use the default material text style which sets color, font weight font size and I assume line height as well. So I'd actually be surprised if that’s different.
However a font size setting (not just a boolean make large but a tri state small medium large with small being the default == what it is right now) will probably make a comeback. It’s just not very high up my priority list. 

What do other people think about just increasing the font size in the bubbles?

**Comment by d9h20f** [comment]
I've also always thought the font in Conversations looked small compared to other applications. Maybe the reason it feels strange is because the font in the text entry box is substantially larger than the font in the bubbles. I'd even change the font size in the bubbles to the same size as the text box, although you'd then have to scroll around a lot in a busy group chat.

**Comment by tdemin** [comment]
https://twitter.com/iNPUTmice/status/977463785383395329

As this poll of @iNPUTmice suggests, most people actually want the return of that option. :wink:

**Comment by sakrum** [comment]
The poll on Twitter reflects a misunderstanding imho.
The built in option to increase font size on os level affects both: chat bubble and UI.  
The feature desperately missed by most users is the second option in the Twitter poll. It was the effect on the option in the v1.x I think

**Comment by aladar42** [comment]
Just leaving a +1 here. I have massive problems with my eyesight and making the font larger was the only ting that let me operate the app comfortably.

**Comment by Hund** [comment]
I was a bit surprised by this as well. I have also turned up the font size in Android and Conversation never respected this, which wasn't an issue since you could change it in Conversation itself.

The font is so small that I had to downgrade.

**Comment by ailicic** [comment]
The font size is too small for myself and my wife. After upgrading, wife insisted on rolling back. I have downgraded as well. Please provide an option for larger text. Thank you!

**Comment by iNPUTmice** [comment]
This is going to be fixed in 2.1.0
