### ISSUE TITLE
Trailing slash disappears from clickable link after another message is received

### ISSUE THREAD

**Issue by Nothing4You** [siacs/Conversations#2887]
#### General information

* **Version:** 1.23.8, 2.0.0-rc.1
* **Device:** LG G3 (D855), Pixel 2 XL
* **Android Version:** Android 7.1.2 (LineageOS 14.1), Android 8.1.0 stock rom
* **Server name:** self hosted
* **Server software:** prosody 0.10, ejabberd
* **Installed server modules:** plenty, can list if needed
* **Conversations source:** F-Droid, PlayStore Beta

Reproduced on both my phone (F-Droid) and a friends phone (PlayStore Beta).

#### Steps to reproduce

1. Receive message `https://example.com/foo/`
2. Right now the entire link is a clickable link
3. Receive any other message, e.g. a simple `.`
4. Now the trailing slash is no longer part of the linked text, resulting in this:

> [https://example.com/foo](https://example.com/foo)/

#### Expected result

What is the expected output? 

Future messages should not change existing links.

#### Actual result

What do you see instead?

Trailing slashes are removed from the linked text, as a result causing a different url to be called - this breaks several websites when they expect a trailing slash e.g. for url rewriting.

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

If required I can get this, since I've reproduced it on a friends phone aswell I don't think this should be needed.

**Comment by iNPUTmice** [comment]
This has been fixed in 2.2.x
