### ISSUE TITLE
TLS negotiation failed

### ISSUE THREAD

**Issue by keverets** [siacs/Conversations#2888]
#### General information

* **Version:** 1.23.8
* **Device:** BlackBerry Q10
* **Android Version:** BlackBerry OS 10.3.3.1463
* **Server name:** dismail.de
* **Server software:** unknown
* **Installed server modules:** unknown
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Add an existing account at hcoop.net. Note that the connection works fine
2. Add an account at dismail.de: "Add account" screen, enter details, press "Next"

#### Expected result

Account should be created and connect.

#### Actual result

On the "Jabber ID" line there's a "(!)" notification: "TLS negotiation failed"

#### Debug output

logcat unavailable.

Attempts to work around: In "Expert Settings" checked "Don't trust system CAs". That did not appear to help. Also attempted to "Validate hostname with DNSSEC" in case that might help, but it did not.

As noted, one of my XMPP accounts works fine (hcoop.net) but the dismail.de one does not.

**Comment by iNPUTmice** [comment]
The cipher list offered by the server is probably too restrictive for the
outdated Android stack. Contact your provider or pick a different one.

**Comment by wiktor-k** [comment]
hcoop.net has definitely weaker security requirements: https://check.messaging.one/result.php?domain=hcoop.net&type=client
dismail.de, for comparison: https://check.messaging.one/result.php?domain=dismail.de&type=client#tls
And here you can roughly estimate the capabilities of your phone: https://www.ssllabs.com/ssltest/viewMyClient.html

**Comment by keverets** [comment]
@wiktor-k the SSL Labs test comes back all green in the on-device browser ("Your user agent has good protocol support", it's not vulnerable to Logjam, FREAK, POODLE, etc, TLS 1.2).

I'll look at how I can improve the experience for the user in the client (thinking something to click to give a better indication of what failed in the TLS negotiation... if there was an exception, etc). Right now the user is left blind as to what went wrong and what steps to take to correct it.

**Comment by wiktor-k** [comment]
What API level are you on? Before level 20 (Lollipop) Android had support for TLS1.1+ but it was not enabled by default, and need to be explicitly set. For more info see this entire page: https://developer.android.com/reference/javax/net/ssl/SSLSocket.html#setEnabledProtocols(java.lang.String[])

**Comment by unbranched** [comment]
Could please anybody help me with this? I'm going crazy:
my friend needs to connect to my server, but he has Android 4.4 on Samsung S4 mini. Every time he tries to connect he gets "TLS negotiation failed". I then opened up ALL the ciphers on Prosody but he still gets the same error. Any idea where the problem is?

**Comment by wiktor-k** [comment]
@unbranched did you try setting `curve` to `secp256r1`?

The parameter is described here: https://prosody.im/doc/advanced_ssl_config.html

**Comment by wiktor-k** [comment]
Well note that this may negatively impact connectivity with other Prosody instances (that use 384 by default) but not with ejabberd that uses both curves.

Prosody also has support for both curves but that is included only in trunk (not in tagged releases).
