### ISSUE TITLE
Quotation and copy to clipboard possible of an uploading file

### ISSUE THREAD

**Issue by steffanson** [siacs/Conversations#2892]
#### General information

* **Version:** 2.0.0-beta2
* **Device:** Samsung S4
* **Android Version:** LineageOs 14.1
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Send a file
2. While it is still uploading, long press on the file / message
3. Option to quote is available

#### Expected result

Apparently there seems to be no meaning to "quote an uploading file". 

#### Actual result when quoting (eg)

> |233990|1920|1440

**Comment by iNPUTmice** [comment]
I think this has been fixed in this commit: 2e8cc12ada164643624ad79ef7a65d91b65a0318
