### ISSUE TITLE
same emoji like gajim?

### ISSUE THREAD

**Issue by hubgitbb** [siacs/Conversations#2898]
Version: 1.23.8
Device: different devices

Hi
it is possible to use the same emoji like the on gajim uses?
if i send emojis from conversations, the gajim emojis do not look the same or they doesn't display at all.

regards

**Comment by licaon-kter** [comment]
The Conversations emojis are newer, update them for Gajim I guess.

/Close as invalid

**Comment by iNPUTmice** [comment]
Emoji are like font. They look different on every plattform.
