### ISSUE TITLE
Don't enable OMEMO by default as it breaks chatting

### ISSUE THREAD

**Issue by Hund** [siacs/Conversations#2905]
I understand that E2EE has it's obvious usecases. But I don't see any reasons as to why a fairly unsupported encryption option should be forced enabled by default in a client as it breaks chatting.

When OMEMO is enabled any other client (that doesn't support OMEMO?) will not get the message sent from the client and unlike OTR you won't get notified about any encrypted message either, which means you will never know if someone sent you a message, unless you have a client supporting it which far from all of us have.

Now I need to check with all of my friends if they use Conversations and tell them to disable OMEMO, which is going to be a bit annoying.

Please disable it by default, it's a terrible design choice.

**Comment by licaon-kter** [comment]
What clients do you use? 

There's at least one client on every platform that supports OMEMO.

**Comment by Hund** [comment]
Bitlbee like everyone else. :)

**Comment by iNPUTmice** [comment]
If you don’t like the changes use Conversations Legacy which is currently on it’s way to the Play Store and will probably be available on F-Droid as well.

**Comment by pfak** [comment]
OMEMO should at very least not be enabled by default in group chats.
