### ISSUE TITLE
Error on sending images with httpupload on 2.0.0-beta2

### ISSUE THREAD

**Issue by danieldianes-cocktail** [siacs/Conversations#2906]
#### General information

* **Version:** 2.0.0-beta2
* **Device:** Bq aquaris e4.5
* **Android Version:** Android 4.4.2 stock with kernel 3.4.67
* **Server name:** self hosted
* **Server software:** Prosody 0.10.0 debian 7
* **Installed server modules:**
               "offline", "roster", "saslauth",  "tls",
                "dialback", "disco", "posix";
                "private",  "vcard";                                                                     
            "smacks",  "csi",  "throttle_presence", "filter_chatstates",
            "mam",   "carbons", "http",   "blocking", "version"
                "uptime",  "time",  "ping", "pep"
                "register",  "admin_adhoc"
                "groups"

* **Conversations source:** f-droid

#### Steps to reproduce

1. Try to send an image to other user on the same server using conversations as well

#### Expected result

The image is sent with httpupload and the other user can download it

* This was working until I upgraded to 2.0.0
* From gajim with httpupload I can send files to conversations or to other gajim, so I presume the server remains well configured.
* From Conversations 1.23.1 the other user CAN send images to my gajim or my conversations, but I can not switch back to this version to check because the apk is missing 
* Besides, I got no error on the server when the file transfer fails.

#### Actual result

"Error on sending" ("Error al enviar")

#### Debug output
D/conversations( 6471): app switched into background
D/conversations( 6471): reInit(hasExtras=false)
D/conversations( 6471): scrolledToBottomAndNoPending=true
D/conversations( 6471): jump to first unread message
D/conversations( 6471): ignoring read callback. mActivityPaused=true
D/conversations( 6471): _(account deleted)_ send ping (action=ui,lowTimeout=false)
D/conversations( 6471): app switched into foreground
D/conversations( 6471): ConversationFragment.onBackendConnected()
D/conversations( 6471): app switched into background
D/conversations( 6471): copy image (file:///storage/emulated/0/DCIM/Camera/IMG_20180327_094511.jpg) to private storage /storage/emulated/0/Conversations/Media/Conversations Images/d8d73c4f-e07f-42cb-81af-ceadd292df06.jpg
D/conversations( 6471): reading bitmap with sample size 1
D/conversations( 6471): reInit(hasExtras=false)
D/conversations( 6471): scrolledToBottomAndNoPending=true
D/conversations( 6471): jump to first unread message
D/conversations( 6471): ignoring read callback. mActivityPaused=true
D/conversations( 6471): received uri permission for file:///storage/emulated/0/DCIM/Camera/IMG_20180327_094511.jpg
D/conversations( 6471): app switched into foreground
D/conversations( 6471): ConversationFragment.onBackendConnected()
D/conversations( 6471): send file message
**D/conversations( 6471): _(deleted user)_Conversations.L5d1: invalid response to slot request <iq to="_(Account deleted)_/Conversations.L5d1" from="_(server deleted)_" xmlns="jabber:client" type="result" id="8KXeQoQUfZPX"><slot xmlns="urn:xmpp:http:upload:0"><get xmlns="urn:xmpp:http:upload:0">_(server deleted)_:5281/upload/-DmgPZAxZPWEsFw0/2Nc8T-B_QsuBr86t0pLfBg.jpg</get><put xmlns="urn:xmpp:http:upload:0">_(server deleted)_:5281/upload/-DmgPZAxZPWEsFw0/2Nc8T-B_QsuBr86t0pLfBg.jpg</put></slot></iq>**

Thanks for the great work!

**Comment by licaon-kter** [comment]
update your http_upload module

/duplicate of other issues

**Comment by danieldianes-cocktail** [comment]
worked like a charm, thanks.

**Comment by rohitgarg29** [comment]
Hi, I am very new to this stuff, sorry to ask this stupid question but how can i update the http_upload module? Thanks!

**Comment by licaon-kter** [comment]
@rohitgarg29 The server admin has to do that. Are you the administrator? If not, do contact them.
If you are, just download the new modules from the website.
