### ISSUE TITLE
Add custom resources

### ISSUE THREAD

**Issue by Ralfor** [siacs/Conversations#2915]
#### General information

* **Version:** 2.0.0
* **Device:** Google Pixel XL
* **Android Version:** Android 8.1
* **Conversations source:** PlayStore

#### Steps to reproduce

Maybe I was just blind then please close this one, but after 2h searching in the settings and recreating accounts I think I can exclude that :)

1. Switched to conversations because of some recommendations of my friends
2. Want to set my resource name as usual (not this cryptic one)
3. Can't find a setting for this after searching all settings

#### Expected result

Possibility to set my resource ID

#### Actual result

What do you see instead? Nothing

EDIT: Oh sorry, just found that it was removed just in 2.0. And there is now a legacy version for this. Will check this out. Thanks for Conversations it's great!! (with this exception :P)

EDIT2: I tried the legacy version, but I like the feeling of v2 more, so I keep this open. Meanwhile I'll use the legacy version.

**Comment by iNPUTmice** [comment]
Customizable resource have been removed deliberately.
