### ISSUE TITLE
Conversations 2.0 unusable due to OMEMO default

### ISSUE THREAD

**Issue by Natureshadow** [siacs/Conversations#2917]
The new default setting activiating OMEMO makes Conversations unusable for me and most of my contacts. We are using a central server and clients that do not support OMEMO. Our priority is synchronisation and compatibility, not encryption. Conversation is thus unusable in that scenario.

Please at least add a preference that sets the default for new chats - it can be turned on by default, but it absolutely needs to be there!

**Comment by iNPUTmice** [comment]
fixed in a6539be52bf08c0f0c22a884510c43714a9a37cb
