### ISSUE TITLE
Allow to specify birthday and show birthdays of contacts

### ISSUE THREAD

**Issue by allo-** [siacs/Conversations#2919]
A nice feature of many social networks and some messengers is that they remind you of the birthday of your contacts. 

As xmpp contacts have a vcard anyway, there just needs to be some ui to add the birthday there and some ui to list the next birthdays of your contacs and to display the birthday of a contact in his profile.

**Comment by tdemin** [comment]
Integration with the address book of the device would be much nicer. You would be able to find out the birthday by simply opening the contact details if this was implemented. And the calendar app would do the job of notifying you about birthdays.

**Comment by allo-** [comment]
I think there is integration with the address book, if you allow Conversations to use it.
But jabber-vcards may contain much information which you do not have in the address book and you may want to put information there, which can be read by people with PC clients.

**Comment by iNPUTmice** [comment]
I don’t think this is a direction i want Conversations to move to.
