### ISSUE TITLE
Conversations fails after update to 2.0 with: Can't downgrade database from version 40 to 39

### ISSUE THREAD

**Issue by anyc** [siacs/Conversations#2925]
I upgraded conversations over F-droid and noticed that it won't start anymore. Afterwards, I saw that 2.0 won't work on the Jolla 1 due to a too old Android environment. I downgraded to several older versions but all failed to start now due to a SQLite issue. Is there a way to (manually) downgrade the database so I can use conversations with an older version?

Thank you!

#### General information

* **Device:** Jolla 1

#### Steps to reproduce

1. Start conversations

#### Expected result

Conversation starts

#### Actual result

Conversations stopped

#### Debug output

Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime: FATAL EXCEPTION: main
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime: java.lang.RuntimeException: Unable to create service eu.siacs.conversations.services.XmppConnectionService: android.database.sqlite.SQLiteException: Can't downgrade database from version 40 to 39
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at android.app.ActivityThread.handleCreateService(ActivityThread.java:2380)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at android.app.ActivityThread.access$1600(ActivityThread.java:137)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at android.os.Handler.dispatchMessage(Handler.java:99)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at android.os.Looper.loop(Looper.java:137)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at android.app.ActivityThread.main(ActivityThread.java:4781)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at java.lang.reflect.Method.invokeNative(Native Method)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at java.lang.reflect.Method.invoke(Method.java:511)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:568)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at dalvik.system.NativeStart.main(Native Method)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 40 to 39
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:361)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:255)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at eu.siacs.conversations.persistance.DatabaseBackend.getAccounts(DatabaseBackend.java:778)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at eu.siacs.conversations.services.XmppConnectionService.onCreate(XmppConnectionService.java:989)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         at android.app.ActivityThread.handleCreateService(ActivityThread.java:2370)
Mar 31 18:32:31 Sailfish start_alien.sh[12790]: 03-31 18:32:31.574  9825  9825 E AndroidRuntime:         ... 10 more

**Comment by iNPUTmice** [comment]
Downgrades are usually not supported and are rather complicated. Don’t get your hopes up on this getting fixed.

**Comment by anyc** [comment]
Oh, so this means I will loose my OMEMO key and chat history as I have to start with a new "profile"?

**Comment by therob84** [comment]
I have exactly the same problem! 

My hope is to manually edit the database-history-file of a new C1.23.8-profile an paste sections about keys and history from the nad updated C2b2 history file with my settings on Amdroid4.2 with a text editor.

Could this work, @iNPUTmice ?

**Comment by therob84** [comment]
I just wantet to do a manual comparisation of Conversations' database/history-file with Notepad++, but either I am doing anything completely wrong, or the file IS completely different, as you can see here:

- Conversatios 1.23.8 on Android 4.2: 
![grafik](https://user-images.githubusercontent.com/15350793/38172160-3ca6a97a-35a7-11e8-84fe-746d2231c8e0.png)
- Conversations 2.0Beta2 on Android 7: ![grafik](https://user-images.githubusercontent.com/15350793/38172120-b2980328-35a6-11e8-8189-59bd6fccd5b8.png)

As I am not familiar with looking into commits - I could not figure out how to search for the history-file-corresponing position in th code.

Any help?

**Comment by licaon-kter** [comment]
http://sqlitebrowser.org/ ?

**Comment by therob84** [comment]
@licaon-kter 
yep, I found the same and tried.
I could open the C2b2 (sql version 40), but did not find a way to simply re-save it in version 39. Ideas?
The 1.23.8-file I cannot open at all, as it asks me for a passphrase - I don't know, what it meas.

**Comment by iNPUTmice** [comment]
If you have root.
* stop the app
* copy `/data/data/eu.siacs.conversations/database/history` to your computer
* open file with sqlite. execute statement `pragma user_version=39`
* copy file back to the phone.
* start the app.

**Comment by anyc** [comment]
Works for me, thank you!

**Comment by therob84** [comment]
- Conversations 1.23.8 needs pragma_user_version = 39
- Conversations 2.0Beta2  uses pragma_user_version = 40

My comments to the successful tested instruction:
> 1. stop the app
- If you are using C2.0Beta2 under Android 4.2 and the app does crash directly after splashscreen this is equal to "stop app". But to be safe, check it in Android/Settings/Apps/Conversations->Kill
> 2. copy /data/data/eu.siacs.conversations/database/history to your computer    
> 1. open file with sqlite. execute statement pragma user_version=39

- For 3) I used [SQLiteDatabaseBrowserPortable](https://portableapps.com/apps/development/sqlite_database_browser_portable). 
Open the db (file: history), change in tab “Edit Pragmas” the user Version to desired version (40 -> 39) and "write changes".
![grafik](https://user-images.githubusercontent.com/15350793/38211001-589f7eb4-36b9-11e8-8065-d491dd42abbc.png)
   
> 4. copy file back to the phone.
> 5. start the app.

if you have problems later with updating Conversations (if available for legacy 1.x-branch) consider to make the same procedure and change version from 39 to needed value.

Additional note: If any OMEMO-message with this device/identity is sent between making a backup/copy and restoring the backup/copy – the OMEMO-identiy is out of sync and wont work anymore. 
last option then would be to reset your OMEMO-identity (under Advanced Settings)!

**Comment by ddiss** [comment]
> If you have root.
> 
> - stop the app
> - copy /data/data/eu.siacs.conversations/database/history to your computer
> - open file with sqlite. execute statement pragma user_version=39
> - copy file back to the phone.
> - start the app.

I had the (non-starting) 2.0-beta installed on Android 4.3 and have been trying to get back to a working 1.23.8 setup without losing OMEMO keys / history, via:

- download history and history-journal databases
- open with sqlite3 and execute "pragma user_version=39"
  - history-journal is missing on .quit -  sqlite3 flushes journal into main db?
- remove conversatons 2.0-beta
- install conversatons 1.23.8
- upload history file to device and restore uid/gid
- delete history-journal on device
- start conversations
  - conversations crashes

**Comment by ddiss** [comment]
@therob84 outcome was that I was not able to get 1.23.8 working with my downgraded user_version=40->39 database. Conversations was killed during db download and upload.
I ended up starting again with 1.23.8 from scratch.

it'd be great if the app natively supported key (and perhaps history) file export / import.
