### ISSUE TITLE
MUC chat doesn't show share photo button anymore

### ISSUE THREAD

**Issue by Matthias84** [siacs/Conversations#2927]
#### General information

* **Version:** 2.0.0b2
* **Device:** Samsung S3 i9300
* **Android Version:** Android 7.1.2 Lineage 14.1 Guava
* **Server name:** jabber.plattform32.de
* **Conversations source:** f-droid

#### Steps to reproduce

1. Switch to a groupchat
2. Share picture, sound, video, ...

#### Expected result

You have a share button, like at a 1:1 chat on the topbar.

#### Actual result

Share button is missing (also at ... folded menu) and the lower send button is just the ordinary one.
![screenshot_20180401-120237](https://user-images.githubusercontent.com/217511/38172125-d199b636-35a6-11e8-90ea-e200dcf637ba.png)

**Comment by licaon-kter** [comment]
This this work before on 1.23.x?

**Comment by Matthias84** [comment]
I can't confirm for my platform, but my peers on Google Android and 1.23.8 doesn't seem to have this problem.

**Comment by iNPUTmice** [comment]
The HTTP upload plugin is probably out of date on that server.

**Comment by Matthias84** [comment]
@iNPUTmice Thank you for pointing me to the outdated plugin. I updated to the current prosody community modules and everything works fine.

Indeed the Conversations Server infos pointed an corrupted image upload feature, but at 1:1 chats it still worked fine :thinking: 

P.S: Happy eastern! :rabbit:
