### ISSUE TITLE
No way to open first conversation with stranger

### ISSUE THREAD

**Issue by af8a524db1** [siacs/Conversations#2928]
#### General information

* **Android Version:** Android 6.1 Stock
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Clean Conversations installation without converations / Clear all conversations (no back button / no way to open ConversationsActivity)
2. Stranger sends a message to me. Since there is no notification from strangers and there is no back button there is no way to open the conversation with the stranger.

#### Expected result

Back button to open the ConversationsActivity appears when a new messages is received.

#### Actual result

No back button even though there is a "hidden" conversation with a stranger.

**Comment by licaon-kter** [comment]
First: Enable "notification from strangers" in Settings.

Also, depends on server too, as now the default is OMEMO encrypted, if server does not support, you might not get anything.

Second: Stranger should switch to unencrypted and send again.

**Comment by licaon-kter** [comment]
Ok, I just repro this.

Indeed, you don't see anything by default or you see a notification if that's enabled, you can even quickreply.

But...a chat view with this conversation is not opened.

**Comment by iNPUTmice** [comment]
I *think* this should be fixed in 2.1.0 - however I'm still traveling without one of my dev phones and can’t actually test this.
