### ISSUE TITLE
Wrong command "Send location" remains in the menu despite uninstalling opensharelocationplugin

### ISSUE THREAD

**Issue by Buntbart** [siacs/Conversations#2931]
#### General information

* **Version:** 2.0.0-b2
* **Devices:** klte, flo, maguro
* **Android Version:** 7.1.2 (LineageOS 14.1)
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Install [opensharelocationplugin](https://bitbucket.org/SamWhited/opensharelocationplugin)
2. use new menu entry "Send location" in chat
3. uninstall plugin

#### Expected result

Menu entry "Send location" disappears

#### Actual result

The menu item "Send location" remains unchanged, sends the last location saved before uninstallation

Please read also [this issue](https://bitbucket.org/SamWhited/opensharelocationplugin/issues/20/menu-entry-location-remains-after-removing).
Maybe a command in the expert settings would be possible to delete plug-in data.

**Comment by iNPUTmice** [comment]
Does the problem persist after restart Conversations?

**Comment by Buntbart** [comment]
Yes

**Comment by licaon-kter** [comment]
Where did you install the plugin from? The Bitbucket site? What version?

**Comment by Buntbart** [comment]
v2.4.1 From F-Droid/Archive

**Comment by licaon-kter** [comment]
Can you install it from the dev provided APK: https://bitbucket.org/SamWhited/opensharelocationplugin/downloads/

And retry the steps?

**Comment by Buntbart** [comment]
That would only be meaningful, if I would also reinstall Conversations before, because the wrong menu entry is already there. I want to avoid that so I don't lose my OMEMO keys.

**Comment by licaon-kter** [comment]
Two ideas:
1. try this, so we can see that after this UNinstall it will go away.
2. also try to install Conversations Legacy and see if it appears/disappears from there too, so we can exclude a ROM issue

Also, did you restart your device in the mean time? The app queries the system if the plugin is installed.

**Comment by Buntbart** [comment]
Okay, so what did now on my tablet (Nexus 7/2013, LineageOS 14.1):

1. Backuped existing Conversations 2.0.0-b2 via oandbackup
2. Uninstalled Conversations **and** plug-in via F-Droid App
3. Rebooted tablet
4. Installed Conversations Legacy from F-Droid, set up dummy-account, login, 
Then the button "Send location" was already there again, although I haven't installed the plug-in yet!

So I moved on:

5. Same procedure, but in Step 3 I booted to twrp and deleted the Dalvik cache
And again, the button "Send location" was already there again, without the the plug-in installed!

Therefore, I suspect that remnants of the plug-in will remain in the Android system after uninstallation. Conversations probably doesn't check if the plug-in is really installed or how old the last saved location is.
Since the wrong menu entry is also present in the restored Conversations 2.0.0-b2, I suspect that the problem is independent of the conversation version.

**Comment by Buntbart** [comment]
My preferred solution would be that Conversations could request the location itself from Android. This is best done in the form of an option that is deactivated by default. I don't need a map function or a button in the chat, but would prefer a simple output as url like geo:lat,lon. This offers the most possibilities to continue using the location information.
Conversations could then check if a plug-in with map function is actually installed and then use this.

**Comment by licaon-kter** [comment]
It's late now, but FYI Conversation Legacy has a different ID, you can install it side by side to the main Conversations app.

**Comment by licaon-kter** [comment]
@Buntbart Still an issue on 2.2.0?

**Comment by Buntbart** [comment]
No. Now that the function has become an integral part of the app, my original complaining is over. I'd still prefer a url like geo:lat,lon instead of the button, but that's another topic.
