### ISSUE TITLE
[UI] Create and join a MUC is not consistent

### ISSUE THREAD

**Issue by esu23** [siacs/Conversations#2950]
Since Floating Action Buttons (FAB) appeared in Conversations joining into a group chat (MUC) it's not as intuitive as creating a new group at present.

The current way to create a new group chat is via FAB. Otherwise, to join into existing rooms is via menu (AdapterView.OnItemClickListener).

Following this flow, I doubt the main action is to create a new group and not to join
join an one. So for that reason I think that the FAB should be join into a group in any case.

But to continue to consistency and standards, I feel both options must be accessed on the same way.

**Comment by esu23** [comment]
My approach to the solution is to show two FABs, one for joining and another one for creating a group chat.

Something like this:

![twofabs](https://user-images.githubusercontent.com/20012803/38454238-a5051d74-3a63-11e8-9cde-e8bd9d2447e7.jpg)

**Comment by esu23** [comment]
Another solution could be to press the FAB and collapse another two FABs: One to join a MUC an another to create a MUC. I give the Nextcloud Android app as an example:

![ezgif-2-9e4f4f6311](https://user-images.githubusercontent.com/20012803/39676028-991bc348-5163-11e8-9bc4-558bf3aa5ff4.gif)

**Comment by STPKITT** [comment]
Why in the world was this issue closed?

**Comment by licaon-kter** [comment]
@STPKITT It's not closed. What do you mean?

**Comment by iNPUTmice** [comment]
By the way PRs welcome for the collapse / expand solution as shown in the screenshot @esu23 posted. There is no standard library for this so it is a bit of a pain to create this with all the animations and stuff. The prexising libraries (that I were able to find) don’t use the FAB from the standard library though. So a nice PR with nice animations that uses the standard FABs will very likely get merged.

**Comment by ashjas** [comment]
How about, leavingbthe existing flow as is. And showing the join group chat dialog on long pressing the existing unmodified FAB?

**Comment by esu23** [comment]
Good job! But basically the join group chat (MUC) option has disappear (now it is only possible to join via invitation or by clicking in a xmpp URI previously shared).

I am not against this idea but the following feature is now missing: create a muc with a custom URI (which was possible before using the join MUC instead of creating a MUC).

Maybe it is a good idea to allow the user to custom the URI when the MUC is created.
