### ISSUE TITLE
XMPP RESOURCES NOT PROPERLY DISPLAYED 

### ISSUE THREAD

**Issue by beckysophie** [siacs/Conversations#2952]
***Expected Behavior***

It should be able to display all XMPP resources properly, regardless of the screen's orientation 

***Actual Behavior***

When the screen is on landscape mode, the first item on the list of the XMPP Resources, is cut out and disallowing users from selecting it as their choice 

***How to produce the bug***

* Open the app 
* Log in with your details 
* After logging in, click on more options, select settings 
* Under general, you should see the XMPP Resources, select it.
* When it is clicked, you would see a list of options, that is, types of devices of which one's device falls into.(The first on the list is the name of my device, and it would be cut out when rotated) 

* Now rotate screen : You would see that the first on the list is no more available and can't be selected on landscape mode 
 

***TEST TOOLS***

* Operating system : Android 6.0
* Phone : Infinix hot s
* Conversation Legacy v1.23.9

***Recording of the bug is showned below......***

https://youtu.be/4SVdQ4goLUo

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@beckysophie/xmpp-not-properly-displayed">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by licaon-kter** [comment]
/offtopic What coin do you hope to get?
