### ISSUE TITLE
Button "Check file size on server" appears in muc, also for file smaller setup size

### ISSUE THREAD

**Issue by Zibc** [siacs/Conversations#2954]
Hello,

I noticed that when uploading a picture or file to a conference, some users get a button "Check file size on server" for each file sent. I am the owner of the chat room and for me all files are downloaded following my preference.

I am not sure whether or not it is a bug, but I would like to know this behavior happens. and if there a way to fix it.

Thanks in advance!

**Comment by licaon-kter** [comment]
What type of MUC? Private? Public?

**Comment by Zibc** [comment]
After your comment, I hecked that and the muc was public. So I changed that to private, and still have that button showing up for some people ... the server is prosody 0.10 is that is relevant.

**Comment by licaon-kter** [comment]
All the people have a large "accept file size" setup?

**Comment by Zibc** [comment]
Yes, I checked that too.

**Comment by iNPUTmice** [comment]
After changing the muc settings other users might have to rejoin. (=Restarting Conversations)
Questions of this kind are better handled in our community group chat.
