### ISSUE TITLE
Conversations won't send messages to some contacts for unknown reason

### ISSUE THREAD

**Issue by aladar42** [siacs/Conversations#2961]
#### General information

* **Version:** 2.0.0
* **Device:** Xiaomi Mi4c
* **Android Version:** LineageOS 14.1
* **Server name:** wiuwiu.de
* **Server software:** unknown
* **Installed server modules:** list at https://wiuwiu.de/
* **Conversations source:** F-Droid

When I'm trying to send a message to certain friends in my contact list, Conversations won't send anything. Right away I get "delivery failed" and the only error message Conversation offers is "service unavailable". Tried Conversation Legacy as well. Messages sent as plain text. I have tried to capture logcat, but I couldn't find anything really

Sorry if the info doesn't help, I have no idea what info I should look for.

#### Steps to reproduce

1. Message a certain contact
2. Error occurs

#### Expected result

Message gets sent

#### Actual result

Message fails to deliver straight away

#### Debug output

````
https://pastebin.com/6SHDSqv2
````

It doesn't even seem to log anything once I start typing and send the message.

**Comment by licaon-kter** [comment]
Other servers work?

**Comment by aladar42** [comment]
Yes. In at lea

**Comment by aladar42** [comment]
God, I'm sorry, my broswer froze and Android thought I clicked close issue. Good stuff. :/

Anyway, yes, other servers work. This case seems to be related to not being able to send anything until approved by the recipient. Which I guess it by design, but Conversations should reflect this with a message that's helpful in some way, I feel?

**Comment by iNPUTmice** [comment]
Conversations doesn’t have any other information other than 'service-unavailable'. This is the error message from the server and is basically the same error message as you would see if the account doesn’t exist. IMHO this is a design flaw of the method of spam blocking.
