### ISSUE TITLE
Flags are not displayed correctly

### ISSUE THREAD

**Issue by heipa0** [siacs/Conversations#2963]
Hello,

Flags from my Samsung keyboard are not show correctly in Conversations. Only question marks appear.

Thanks

![flags](https://user-images.githubusercontent.com/35292661/38728266-fd2d29aa-3f41-11e8-906d-ef0ee6a68610.png)

**Comment by SoyaLeaf** [comment]
What is your android version?

**Comment by licaon-kter** [comment]
What Conversations version?

**Comment by SoyaLeaf** [comment]
@licaon-kter   It is mentioned in another issue.

>  We both using the newest version of Conversation (2.1.0) from the Play Store but it also happened with previous versions.

**Comment by heipa0** [comment]
After the last update it works. Flags are now displayed correctly.
