### ISSUE TITLE
when bluetooth paired, route notification sound to handset

### ISSUE THREAD

**Issue by TntDestroyer** [siacs/Conversations#2966]
Is this more a job for Tasker?  I have jangly loud sounds so i can detect messages in LOUD environments. My car is not such a place. 

Disabling notification sound globally is easy enough but i would prefer hearing it from the phone, not amplified by my stereo

Any tasker experts know how to route sound path?  

Will this require deep knowledge of conversations?  (this is why i ask here)

conversations 2
fdroid build
android 444, 6, and 7.0
various samsung flagship devices

**Comment by iNPUTmice** [comment]
Notification sounds are entirely handled by the OS. Conversations has no influence. If you are looking for Tasker experts the Conversations bug tracker is probably not the right place. You might try our conference.
