### ISSUE TITLE
Notifications Reply should imply Mark as Read

### ISSUE THREAD

**Issue by tyler71** [siacs/Conversations#2971]
#### General information

* **Version:** 2.1.1
* **Device:** Samgsung J3
* **Android Version:** Android 7.0 Stock
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** [Dpaste of installed modules](http://dpaste.com/3W5Y9E4)
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. Be sent a message
2. View message in notifications
![Demo Notification](https://i.imgur.com/lapPCwk.jpg)

#### Expected result

After replying to a message through the notification, the notification should be considered "Read" and remove the notification

#### Actual result

The notification lingers after replying and you need to mark it as read as well.
![lingering notification](https://i.imgur.com/pgdhzNt.jpg)

**Comment by licaon-kter** [comment]
That's what I would like too, but not what Google wants...

https://github.com/siacs/Conversations/pull/2880

/close as wontfix
