### ISSUE TITLE
Conversations 2.1.0 does not seem to respect /system/etc/hosts file

### ISSUE THREAD

**Issue by duantocy** [siacs/Conversations#2972]
#### General information

* **Version:** 2.1.0
* **Device:** samsung galaxy s4 mini
* **Android Version:** lineageos 14.1
* **Server name:** self hosted
* **Server software:** metronome 3.7.9
* **Installed server modules:** ?
* **Conversations source:**  F-Droid,

#### Steps to reproduce

1. Edit /system/etc/hosts on Android OS, e.g. echo "x.x.x.x yourserverdomain" > /system/etc/hosts
(Note: This step requires root access)

2. Try to connect with conversations to "yournick@yourserverdomain" with correct credentials

#### Expected result

Conversations succeeds to connect to your xmpp server as it uses the IP address specified in the "hosts" file.

#### Actual result

Conversations seems to ignore entry in "hosts" file instead uses another IP obtained by other means.

To proof the point that my setup is with high certainty not broken: when I use yaxim xmpp client (version 0.9.2 obtained via f-droid) the correct IP address is resolved resulting in a successful server connection.

#### Some Questions

How does Conversations retrieve IP address for a given server domain?
Does it actually look at /system/etc/hosts?
Does it cache DNS settings?
If so, how can one reset DNS cache?
Or is the caching a Java environment feature?
Is there a way to use raw IP instead of server domain?

Thank you kindly.

**Comment by iNPUTmice** [comment]
> Is there a way to use raw IP instead of server domain?

I think you can just enable the extended connection options and enter an IP in the hostname field.

> Does it actually look at /system/etc/hosts?

No.

**Comment by duantocy** [comment]
With the extended connection settings I could enter the raw IP. 

That worked, thank you!

Just for my understanding, how come the hosts file is seeminly ignored?

**Comment by cwildfoerster** [comment]
I think its because minidns to resolve all dns stuff needed for xmpp to work neetly (txt records etc)
