### ISSUE TITLE
Unable to join conference room

### ISSUE THREAD

**Issue by CaMyPau** [siacs/Conversations#2974]
#### General information

* **Version:** eg 2.1.1
* **Device:** eg Samsung Galaxy S9+
* **Android Version:** eg Android 8.0 Stock 
* **Server name:** eg conversations.im, jabber.at or self hosted
* **Conversations source:** eg PlayStore 

Unable to join conversations@conference.siacs.eu

#### Steps to reproduce

1. Create contact conversations@conference.siacs.eu
2. Try to send message to conversations@conference.siacs.eu

#### Expected result

Message is sent.

#### Actual result

"Delivery failed"

P.S.
Actually, I have problem with paying for accounts hosted on conversations.im but I can't neither reach anybody via support@conversations.im nor send message to conference room so raising issue here.

**Comment by iNPUTmice** [comment]
`support@conversations.im` is an email address not an xmpp address. (Assuming that you tried that because I haven't received in email from you.)

You can login to https://account.conversations.im/login to pay for your account. Feel free to send us an email if that doesn’t work for you though.

**Comment by CaMyPau** [comment]
Thank you for the fast reply!
Yes, of course I e-mailed you on `support@conversations.im`. That's really strange that you haven't received my e-mail. Though may be this is GMail issue.

I'd rather made link to an account management much more visible. Wasn't able to spot small "Login" hyperlink at the very bottom while inspecting page multiple times. I was able to pay for the account. Thank you one more time.

Still I'm wondering can I join conference room using conversations.im client?

**Comment by JuniorJPDJ** [comment]
You should not create contact for this, just switch tab in contacts menu, at right you have groups ;D

**Comment by CaMyPau** [comment]
Got it! Closing the issue.
