### ISSUE TITLE
no batch with unread messages

### ISSUE THREAD

**Issue by whitetornado** [siacs/Conversations#2978]
#### General information

* **Version:** eg 1.21.8
* **Device:** eg moto 4g
* **Android Version:**  Android 7. lineageos 14.1
* **Server  self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. missed or unread message no badge with counting

#### Expected result

What is the expected output? 

see near the app a badge with unreaded messages.

**Comment by licaon-kter** [comment]
This is a launcher thing, as far as I know.

Eg. Working fine in Xperia Home

**Comment by whitetornado** [comment]
i mean a badge where the counter shows..

2018-04-21 20:50 GMT+02:00 Licaon_Kter <notifications@github.com>:

**Comment by licaon-kter** [comment]
Yes...Xperia Home has that...it's a launcher thing.

**Comment by iNPUTmice** [comment]
A launcher feature indeed.

**Comment by whitetornado** [comment]
why it shows on android 7.0 and not under 7.1

Op zo 22 apr. 2018 11:57 schreef Daniel Gultsch <notifications@github.com>:
