### ISSUE TITLE
Put the voice recordings into a folder not read by music players

### ISSUE THREAD

**Issue by tdemin** [siacs/Conversations#2979]
Conversations saves the recordings into `/sdcard/Voice Recordings` after they're sent.

Unfortunately, this way they get listed by music players like Google Play Music (since `.nomedia` isn't in the voice recordings folder by default). Why don't we use an internal folder like `/sdcard/Conversations/Media/Conversations Files` for this?

**Comment by iNPUTmice** [comment]
Closing as invalid. The repository for the voice recorder is here: https://github.com/siacs/VoiceRecorder

**Comment by tdemin** [comment]
@iNPUTmice, it's now here: https://github.com/siacs/VoiceRecorder/issues/21
