### ISSUE TITLE
/me should be displayed outside of speech bubbles

### ISSUE THREAD

**Issue by allo-** [siacs/Conversations#2980]
#### General information

The command "/me does something" represents an action which can be seen, but isn't said. Conversations renders it in a speech bubble as if the user would talk to his self "User does something" instead of using some other way to display it.

I suggest to use space between speech bubbles and maybe some italic text to display "/me" actions.

#### Steps to reproduce

1. Write "bla bla"
2. Write "/me does something"

I use this ascii art for the speech bubbles used in Conversations:

    <( Hello )

#### Expected result

    <( Bla bla [User] )
    * User does something

#### Actual result

    <( Bla bla [User] )
    <( *User* does something [User] )

**Comment by iNPUTmice** [comment]
I don’t think it is worth breaking the bubble design for that.

**Comment by allo-** [comment]
The whole point is, that a bubble suggests speech, while a traditional IRC like ``/me`` does not. It's kind of talking to yourself when you display it inside a bubble, while it should convey something which can be observed (but not heard).

It's your choice if you want to support it that way, but the point is that supporting ``/me`` does not make much sense with bubbles. Not supporting it at all is an obvious option for sticking with speech bubbles only, but converting actions to spoken words seems wrong.

**Comment by badrihippo** [comment]
@iNPUTmice would you be open to merging a request if someone else implements it?

**Comment by licaon-kter** [comment]
@badrihippo Mockup?

**Comment by badrihippo** [comment]
@licaon-kter one option is to remove the bubble border completely; that will immediately make the `/me` commands stand out.

![me-command-mockup](https://user-images.githubusercontent.com/7288084/70529011-8c77b380-1b75-11ea-855d-ed900589e370.png)

Of course, this would eliminate extra info like "sent at" time and whether it's encrypted or not. Given the use-case this may not be such a big issue, but if required perhaps we could modify the design further (for example by adding the "lock" icon to the beginning or end of the message.

Another less-invasive option is to simply remove the arrow next to the speech-bubble in `/me` commands.

![me-command-mockup-2](https://user-images.githubusercontent.com/7288084/70529764-59362400-1b77-11ea-8f15-ffbd54648919.png)

To emphasise the difference, I'd suggest some other stylistic tweak, such as perhaps displaying the whole message in italic (either with or without the asterisk).

![me-command-mockup-3](https://user-images.githubusercontent.com/7288084/70529826-79fe7980-1b77-11ea-86cf-d71eb0888c1f.png)

@licaon-kter  @allo- what do you think? Do you have any further suggestions?

**Comment by licaon-kter** [comment]
> displaying the whole message in italic (either with or without the asterisk).

Interesting yes

> remove the arrow next to the speech-bubble
> displaying the whole message in italic (either with or without the asterisk)

Not changed enough

**Comment by subpub** [comment]
If it was like the "date bubble"? Still the question of 🔒 remains. WhatsApp has "events" like this:
![Image]()

**Comment by badrihippo** [comment]
> If it was like the "date bubble"? Still the question of lock remains. WhatsApp has "events" like this:
@subpub something like this?

![me-command-mockup-4](https://user-images.githubusercontent.com/7288084/70604403-aa4d2300-1c1e-11ea-81ed-af4de8c8d8f9.png)

We could add the lock icon to the beginning of the notification, or to the bottom-right corner. Multiline comments will still be distinct because they'll show in the middle of the screen rather than the side.

But I'm wondering if there are any security issues? People may confuse these with system-generated events (imagine `/me leaves the room` when they're actually still there). It might also be a good idea to include the person's profile-picture, so they can be identified more easily (eg. if multiple people have the same "name" or one person decides to change their nickname in the middle). Or is it not necessary to worry about it in this case?

Another option I was thinking of was making them similar to the "[person] has read up to this point" markers. Of course, this will have the same issue of being potentially confused with system messages.

**Comment by subpub** [comment]
> something like this? 

Yeah

> We could add the lock icon to the beginning of the notification, or to the bottom-right corner.

+1

> But I'm wondering if there are any security issues? People may confuse these with system-generated events 

Conversations does not have any "system events" (atleast not till MIX)

> It might also be a good idea to include the person's profile-picture, so they can be identified more easily

+100

> Another option I was thinking of was making them similar to the "[person] has read up to this point" markers

I think it looks weird if some messages were inside bubbles and some were not. Also I remember the developer saying something about removing the bubbles completely in the future. So, I think the developer should make the final decision

**Comment by badrihippo** [comment]
@subpub

> Conversations does not have any "system events" (atleast not till MIX)

This should be fine then. But what's MIX?

> I think it looks weird if some messages were inside bubbles and some were not. Also I remember the developer saying something about removing the bubbles completely in the future. So, I think the developer should make the final decision

Okay, in that case I guess "small centred bubbles, with the profile-picture included" would be good enough. But would you suggest putting the profile-pics inside or outside the bubble? Inside looks good for short messages but it'll look messy on multiline. On the other hand, outside looks messy in both unless we find a creative way of placing them. Maybe inside, but inline with the text (so wrapped text goes under the pic without leaving a margin? :thinking:

**Comment by subpub** [comment]
Like this?
![](https://picat.drycat.fr/5TWD7Q9E.webp)
Pic from Fasthub

**Comment by badrihippo** [comment]
Wow, looks like even Hangouts supports the `/me` command now :open_mouth:
Here's their implementation:

![me-command-on-hangouts](https://user-images.githubusercontent.com/7288084/72236145-a3d61080-35fb-11ea-928d-229e42d12e16.png)

This seems to show a smaller bubble, and no border or background for the speech-bubbles, but text still leaves a space under the profile-picture while wrapping.

@subpub in our case, I think the screenshot you sent works better though. I'll send in another mockup when I get the time and we can comment on it.

**Comment by allo-** [comment]
Is there any progress? Some of the mockups looked really good, but the issue is still closed.
