### ISSUE TITLE
OMEMO bug 2.1.1

### ISSUE THREAD

**Issue by lagosazules** [siacs/Conversations#2981]
Version 2.1.1  has issues with servers I use jabber.calyxinstitute.org and Trashserver.net

1 error 2.1.1 doesn't let my send OMEMO messages on jabber.calyxinstitute.org anymore, gettinXMPP Server doesn't allow OMEMO anymore  Only OTR allowed 

2 error: 2.1.1 My Trashserver contacts using IPhone Chatsecure do receive OMEMO messages but recieve directly a OTR error message 

Downgraded to 2.1.0 and all problems solved 

Best regards 

#### General information

* **Version:** eg 1.21.0
* **Device:** eg Google Nexus 7
* **Android Version:** eg Android 6.0 Stock or Android 5.1 Cyanogenmod
* **Server name:** eg conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
Read this https://github.com/siacs/Conversations/issues/2976#issuecomment-383275009
