### ISSUE TITLE
Directly add people to roster in deanonymized MUC

### ISSUE THREAD

**Issue by clavinet** [siacs/Conversations#2984]
Conversations 2.1.1

In a MUC, OMEMO keys can sometimes only be exchanged when you have the peope in it on your roster. Getting people's JID is cumbersome at the moment, steps as it is now:

1) join MUC
2) go to "group details" in top-right menu
3) long-press contact
4) select "start conversation"
5) go to "contact details" in top-right menu
6) hit the "add contact" button

This could be simplified to:

1) join MUC
2) go to "group details" in top-right menu
3) long-press contact
4) select "add contact"

Adding the option to directly add people from the long-press menu would let them have OMEMO-encrypted chats faster after joining a MUC.

**Comment by nekoswag** [comment]
I'm not sure what you meant by that post. The contact would see the same thing as before - a question about allowing presence subscription.

>most of the time, you might want to introduce yourself before you get added
The purpose is to save users unnecessary taps and navigation through menus.

By far not all servers have implemented this yet
https://xmpp.org/extensions/xep-0379.html
and adding an option to add contacts directly would make it easier to join a group chat with people whose server doesn't support this XEP.

**Comment by licaon-kter** [comment]
Read my post again and answer the questions, spell out the workflow on both sides.

**Comment by iNPUTmice** [comment]
I don’t think the UI should provide shortcuts for every single action a user might want to take. that will only lead to clutter. The context menu is already pretty full.
