### ISSUE TITLE
alternative for orbot consuming eating battery drain

### ISSUE THREAD

**Issue by whitetornado** [siacs/Conversations#2985]
is there a alternative for orbot? when i run it, i can not have 1 day with a battery while i just have a few chats.

for privacy tor is a must but orbot is a pain in the !@#$

**Comment by licaon-kter** [comment]
Can't repro here, Orbot has minimal impact.

Device? Android version? Orbot version?

**Comment by whitetornado** [comment]
device: motog4
android 7.1 Lineageos
Orbot latest version

2018-04-25 8:24 GMT+02:00 Licaon_Kter <notifications@github.com>:

**Comment by licaon-kter** [comment]
Orbot version pls!

Did you change any settings in Orbot?

**Comment by whitetornado** [comment]
ver 16.0.0. rc.

No i just run it as default..

2018-04-25 9:29 GMT+02:00 Licaon_Kter <notifications@github.com>:

**Comment by licaon-kter** [comment]
Try to use the .onion server address and see if it helps.
Also, disable any *optimisations* (eg. Battery) for Orbot, else reconnecting all the time will use more battery.

**Comment by whitetornado** [comment]
ok, where under the settings in Orbot? thanks for the support

2018-04-25 9:54 GMT+02:00 Licaon_Kter <notifications@github.com>:

**Comment by licaon-kter** [comment]
Conversations...account... "host name" put the right `.onion` address (see your server site for the correct address)

**Comment by whitetornado** [comment]
yes we have that, so the only thing what we can do is not optimize the orbot

2018-04-25 10:32 GMT+02:00 Licaon_Kter <notifications@github.com>:

**Comment by iNPUTmice** [comment]
Please ask general questions that are only semi related to Conversations (and are neither bugs nor feature requests) in our community group chat.
