### ISSUE TITLE
Carbons from Conversations to lurch OMEMO clients (Pidgin, Adium) broken

### ISSUE THREAD

**Issue by sfjes** [siacs/Conversations#2986]
#### General information

* **Version:** Conversations 2.1.2
* **Device:** LG V20
* **Android Version:** 7.0
* **Server name:** self hosted
* **Server software:**  prosody 0.10
* **Installed server modules:** full set of recommended (incl pep, carbons, mam, smacks, csi, etc.)
* **Conversations source:** PlayStore

Since Conversations 2.1.1, libpurple based clients using the lurch plugin are no longer able to receive carbons from Conversation clients when OMEMO is enabled. Instead they receive:

I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo

The issue appears to be introduced by this patch from 10 days ago which changed messages to always includes that message in the <body> tags, instead of only for partners for which it doesn't have keys. 
https://github.com/siacs/Conversations/commit/91a061f480565cf02252079dc769fe07277a2b71#diff-52d690b0863b6f586600025bdcfc98fa

Direct messages still work, only carbons elicit this message.

Downgrading from 2.1.2/2.1.1 to 2.1.0 or below resolves the issue.

I'm not sure if there's an official way a client receiving a carbon with both \<body\> and \<encrypted\> content is supposed to behave, but given that lurch4Adium doesn't get frequent updates (it's several versions behind the lurch source), it would be great if the change could be reverted or otherwise resolved.

Thanks!

#### Steps to reproduce

1. Install Conversations 2.1.1 or 2.1.2 from the PlayStore or F-Droid.
2. Login to an account/server with carbons enabled with Conversations.
3. Login to the same account with Pidgin or Adium using the lurch plugin, with carbons and OMEMO enabled.
4. Send a message to an OMEMO-enabled chat partner.

#### Expected result

Expected output is a carbon display in Pidgin/Adium of the message originally sent from Conversations, as occurred in all the versions I've used in the last 6 months prior to 2.1.1.

#### Actual result

"I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo" appears on Pidgin/Adium. The actual message typed into Conversations is not shown at all.

#### Debug output

The problems no longer occurs if the client is downgraded to Conversations 2.1.0 or earlier and test steps 2-4 repeated. Instead, the expected output (the original message as entered in Conversations) appears as a carbon in Pidgin/Adium.

**Comment by iNPUTmice** [comment]
This should be a fairly simple fix for the carbons plugin (which is still somewhat developed). And since Lurch4Adium is just a build script I don't think it matters that this is no longer being developed.

https://github.com/gkdr/carbons/pull/19

**Comment by iNPUTmice** [comment]
Has been fixed in lurch.
