### ISSUE TITLE
Clearing MUC history does not remove messages from the DB

### ISSUE THREAD

**Issue by mimi89999** [siacs/Conversations#2990]
#### General information

* **Version:** 2.1.2
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Add a MUC to bookmarks (tested with Conversations MUC)
2. Join the MUC
3. Select Clear history form the drop down menu. Also select the quit option

#### Expected result

The messages should not be present in the database.

#### Actual result

Messages were in the `messages` table of `history`.

**Comment by iNPUTmice** [comment]
Is 'selecting quit' a necessary part to reproduce this? What happens if you rejoin the muc?
