### ISSUE TITLE
Messages to self are treated as from  stranger

### ISSUE THREAD

**Issue by participante0** [siacs/Conversations#2993]
#### General information

* **Version:** 2.1.2
* **Device:** Google Nexus 5X
* **Android Version:** Android 8.1.0 Stock
* **Server name:** simplewire.de
* **Server software:** prosody 0.10 stable
* **Installed server modules:** All of Compliance Test
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Send a messege to yourself from another device to Conversations.

#### Expected result

Receive the message as from a known sender.

#### Actual result

I see the Block message "Received message from stranger".

**Comment by iNPUTmice** [comment]
fixed in 5e1bbea5f023513c142f92de2ac33eafd264dd98
