### ISSUE TITLE
topic cannot be empty

### ISSUE THREAD

**Issue by s72785** [siacs/Conversations#2994]
#### General information

* **Version:** eg 2.1.2
* **Device:** OnePlus One

#### Steps to reproduce

alternatively
* confirm empty string for topic (no text entered)
* enter an invisible character such as char code 160
* enter a nonbreaking space

#### Expected result

according to example 88 in XEP 45 the topic should be unset or at least seem empty to the eye

#### Actual result

instead it seems this is prevented on purpose, the topic does not change

**Comment by iNPUTmice** [comment]
Fixed in `master`
