### ISSUE TITLE
File sending fails randomly

### ISSUE THREAD

**Issue by sbrl** [siacs/Conversations#2995]
#### General information

* **Version:** eg 2.1.2
* **Device:** Samsung Galaxy S5 mini
* **Android Version:** 6.0.1
* **Server name:** self hosted - starbeamrainbowlabs.com (test account available upon request)
* **Server software:** prosody 0.9.10-1
* **Installed server modules:** [list available here](https://hastebin.com/kipanodege)
* **Conversations source:** Official paid Google Play Store build

#### Steps to reproduce

1. Attempt to send an audio file, for example, to a client.
2. Note that it stays on "offering" indefinitely

#### Expected result
The file transfers successfully and quickly. 

#### Actual result
It says "offering...." or "waiting...." indefinitely.

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

 - `adb logcat -s conversations` output: [conversations.adb.log](https://github.com/siacs/Conversations/files/1954889/conversations.adb.log)

#### Comments

My server has support for both SOCKS5 and HTTP File Upload. It seems that Conversations is preferring SOCKS5 over File Upload, but  don't see any options in the settings to control this.

Furthermore, it appears to _still_ prefer SOCKS5 over File Upload if the other user is not online. This is not a good choice, as I might never be online at the same time as the person I want to transmit to. In addition, SOCKS5 might be blocked on my network, so Conversations should at the very least retry via File Upload.

In the provided log file it ended up working eventually, but for the reasons discussed above it ought to retry via http file upload when it fails. An option to choose which method I'd prefer would be welcome too.

**Comment by licaon-kter** [comment]
Do attach a report of https://github.com/iNPUTmice/ComplianceTester

**Comment by iNPUTmice** [comment]
Go to account details / server info to see if http upload is available. My guess is it isn't. In that case you probably need to update your http upload module.

**Comment by sbrl** [comment]
@licaon-kter: I get this when I try to run that compliance tester:

```
Error: Invalid or corrupt jarfile ComplianceTester-0.2.3.jar
```

Java version:

```
$ java -version
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
```

@iNPUTmice Oh awesome! I didn't know about that server state thing. That's really useful! Thanks :D

You were right - it was showing as unavailable. That _seems_ to have resolved the issue for now. How does _Conversations_ determine which method it's going to utilise to send a file, out of curiosity? It'd be nice if the UI indicated somehow (e.g. via an icon or something) which method a file was sent by.
