### ISSUE TITLE
Can't confirm that users belon to a MUC -> Can't send to the MUC

### ISSUE THREAD

**Issue by KrimaRula** [siacs/Conversations#2997]
#### General information

* **Version:** 2.1.2
* **Device:** Wileyfox Swift + Glaxy Tab S
* **Android Version:** Lineage OS 14.1
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** carbons, mam, mam_muc, smacks, smacks_offline, roster, muc, ...
* **Conversations source:** F-Droid

#### Problem 

I am using version 2.1.2 (F-Droid) on a tablet and a smartphone. Additionally I use Gajim 1.0.1.

I have problems sending messages to encrypted MUCs. Under Gajim I confirmed the fingerprints and can send to the MUC.

I can also send under Conversations (Tablet). Here I blindly trusted the fingerprints. Confirming this worked without any problems.

Under Conversations (Smartphone) I cannot send to the MUC. I'm shown two contacts that the system says I already trust the fingerprints. The system asks me to confirm that the contacts belong to the MUC. However the "Done" button is disabled. So I cannot send from this device to the MUC.

#### Steps to reproduce

1. Send message to MUC from Gajim/Tablet (works)
2. Send message to MUC from Smartphone (doesen't work)

#### Expected result

I expect an enabled "Done" button to confirm, that the contacts belong to the MUC.

#### Actual result

The "Done" button is disabled. I can't confirm -> I cant' send messages to the MUC.

**Comment by licaon-kter** [comment]
Can you take a picture of that message? Censor IDs

It behaves like this when it can't get the keys.

**Comment by KrimaRula** [comment]
![muc-conversations](https://user-images.githubusercontent.com/38381749/39398559-b71c6e10-4b0f-11e8-9d71-6a2eac996612.jpg)

**Comment by licaon-kter** [comment]
Do you have other contacts (not shown here!) in the MUC that you (SMARTPHONE) don't have the keys of?

**Comment by KrimaRula** [comment]
I'm not quite sure. I think I have all the keys. 1:1 chats also work without problems.

I'm not sure if it matters, maybe it's another problem, but I don't always get all the messages on my smartphone. On the tablet and in Gajim I get more messages.

**Comment by licaon-kter** [comment]
Is Archive on `Always` in your account setup on SMARTPHONE?

**Comment by KrimaRula** [comment]
Yes it is set on "Always".

**Comment by KrimaRula** [comment]
Version 2.1.4 fixes the problem.
