### ISSUE TITLE
On large displays with side-by-side view, the title/topic of group chats isn't shown

### ISSUE THREAD

**Issue by pgeorgi** [siacs/Conversations#3001]
#### General information

* **Version:** 2.1.2
* **Device:** Chromebook with Play Store
* **Android Version:** Android 7.1.1 stock (as shipped on Chromebooks)
* **Server name:** N/A
* **Server software:** N/A
* **Installed server modules:** N/A
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Join MUC (in my case: a IRC channel via biboumi bridge)
2. Notice on a phone that entering the group shows its topic in the title bar
3. Notice on Chromebook that the title bar remains at "Conversations", the title of the conversations list on the left side

That probably also happens on tablets with sufficiently large screens

#### Expected result

Seeing the current channel's topic somewhere.

#### Actual result

"Conversations", which isn't too informative.

**Comment by licaon-kter** [comment]
@Echolon 2.1.4 is just a bugfix, I can confirm the issue.
Use `adb shell wm density 180` then look at a MUC.
Use `adb shell wm density reset` to go back.

**Comment by pgeorgi** [comment]
Indeed. updated to 2.1.4, same situation

**Comment by iNPUTmice** [comment]
It is still shown in the overview on the left hand side and the current conversation is selected.

**Comment by pgeorgi** [comment]
It's shown in the overview, but it's the same black-on-white as the other open conversations. What should the current conversation look like there?

**Comment by pgeorgi** [comment]
![screenshot 2018-05-01 at 20 09 39](https://user-images.githubusercontent.com/47232/39486214-a7ffa848-4d7b-11e8-8a0e-6727aeeb7bdc.png)
