### ISSUE TITLE
openchatscreen as mainscreen?

### ISSUE THREAD

**Issue by whitetornado** [siacs/Conversations#3002]
is it possbile to have the "open chatscreen", you can see the chats with unreaded messages, as start screen as soon as their are unread messages?

**Comment by licaon-kter** [comment]
Define the workflow? What's a _start screen_ ?

**Comment by whitetornado** [comment]
default screen is the screen with contact. When you got messages from different contact you, you can select the contact and start to chat. One step back you see the list with other unread messages. I would like that as the main screen as long the chats unread.

**Comment by licaon-kter** [comment]
I can't repro this, when I (force) close the app it always starts with *open chats* view. Where, *if* you have unread messages, you will see them.

**Comment by iNPUTmice** [comment]
Maybe join our conference and discuss/explain this feature request? with other users. That probably a more suitable place then the issue tracker
