### ISSUE TITLE
Message search: Search result for something like string[%$...]

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#3007]
#### General information

* **Version:** 1.22.0-beta
* **Android Version:** LinOS 14.1
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. Search for example,

- a$
- a$$$$
- a%
- a&
- a-
- ...

 where "a" can be any string

#### Expected result

Only messages, which exactly contain the string in the body.

#### Actual result

Messages are displayed that don't contain the exact string but those where the in this example the letter "a" is followed by a whitespace or other any grammatical character (!@-). Nothing becomes highlighted though.

**Comment by licaon-kter** [comment]
Or write "word", find something... add "word@#$_" and the highlight is gone...but the results are kept.
