### ISSUE TITLE
"Attach file" paperclip absent in MUC

### ISSUE THREAD

**Issue by crosser** [siacs/Conversations#3010]
#### General information

* **Version:** 2.1.4
* **Device:** Sony Z3
* **Android Version:** 6.0.1 stock
* **Server name:** self hosted
* **Server software:** jabberd2 2.6.1
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Join a chatroom
2. Observe that paperclip icon is absent

#### Expected result

Media attachments should work for chatrooms and for individual chats alike, as they do in earlier versions of Conversations (1.16.xx ?). Sending pictures and other attachments in MUC got broken in some versions of Conversations during 1.x.y cycle, but worked in most versions until a few months back. Some time before release 2.0 paperclip disappeared and does not work since then. I can still see attachments that others make, when they use old version of Conversations.

**Comment by licaon-kter** [comment]
Your server software is at fault, http_upload namespace support.

**Comment by crosser** [comment]
1. I use https://github.com/siacs/HttpUploadComponent for http_upload
2. Media upload works for non-MUC (one-to-one) chats
3. Media upload worked from older versions of conversations to the same MUC rooms

@licaon-kter , if you think it's http_upload fault, would you care to provide more details? Thanks!

**Comment by licaon-kter** [comment]
See the other issues, search for upload.

**Comment by crosser** [comment]
This is indeed duplicate of #2927, but I believe that this is still an error to report httpupload as "unavailable" but still have it working in one-to-one chats. It confuses the user, because he *knows* that httpupload actually works (in one-to-one chats) and has no any hint that he needs to check server capabilities.

Not to say, the same server software works fine with older versions.

**Comment by iNPUTmice** [comment]
The component has been EOL for quite some time now. The XEP has been updated in the meantime. It shouldn’t be too difficult to make the component support the new XEP though if you want to give it a try.
