### ISSUE TITLE
after updating to 2.x beta it always crash a few moments after starting

### ISSUE THREAD

**Issue by FOSS-Fan** [siacs/Conversations#3014]
#### General information

* **Version:** eg 1.23.x to 2.0 beta to 1.23.x to 1.21.0 to 1.23.8
* **Device:** Samsung Stratosphere II
* **Android Version:** Android 4.1.2 Stock

* **Conversations source:** F-Droid

After updating  conversations with an in F-Droid offered beta version it always crashs at the start. For a moment there is the conversations gui and than the message: Unfortunately, Conversations has stopped. I updated from 1.23.x to the 2.x beta. From this time i could not start it anymore. I installed version 1.23.x → crash at the start, install 1.21.0 → crash at the start. I believe it has somethimg to that i only have Android 4.1.2 an every Conversations up from 1.23.8 needs Android 4.4. I don‘t know how i can get converstions working again and hope you can help me.
#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````
--------- beginning of /dev/log/system
--------- beginning of /dev/log/main
D/conversations( 1890): initializing database...
D/conversations( 1890): restoring accounts...
D/conversations( 2683): initializing database...
D/conversations( 2683): restoring accounts...

**Comment by licaon-kter** [comment]
Do you care about chat history? If so, with root and patience you can transfer it.

You need to switch to `Conversations Legacy` from F-Droid.

**Comment by FOSS-Fan** [comment]
Yes I do licaon. With root and patience, so so. How can I get root rights for the phone and what do I have to do than with patience?

I don‘t really need to switch to Conversations Legacy, do I? Why? Conversations worked until the update with the XMPP Servers. So why should it be necessary to switch now?

**Comment by licaon-kter** [comment]
There was an issue on F-Droid and 2.0.0-beta was released as stable for a while to all devices albeit it was not compatible with Android 4.3 and lower. But that was more than a month age, when did you update to 2.0.0-beta? Why did you wait so long to report it?

Legacy version is still compatible but in a frozen state, it won't get updates unless there's some grand issue.(eg. It got a small fixup update yesterday)

If you want to take your history to Conversations 1.23.8 or Conversations Legacy 1.23.10 you'll need root access, if you don't have it you can't keep it, just login in Legacy and start anew.

**Comment by iNPUTmice** [comment]
If you have root [here](https://github.com/siacs/Conversations/issues/2925#issuecomment-377813154) is a quick summary on how to downgrade from 2.0.0-beta back to 1.23.8

Otherwise you should install Conversations Legacy.
