### ISSUE TITLE
Connecting status "Connecting..." stays forever

### ISSUE THREAD

**Issue by schwindp** [siacs/Conversations#3015]
#### General information

* **Version:** 2.2.0 beta
* **Device:** Oneplus X (ONE E1003)
* **Android Version:** Android 6.0.1
* **Server name:**  self hosted
* **Server software:** prosody 1nightly882-1~stretch
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:**  PlayStore Beta Channel

#### Steps to reproduce

1. Use Conversations
2. After some time, connection status is "Connecting..."

#### Expected result

Flawlessly working Conversations.

#### Actual result

"Connecting..." connection status

This seems to be a new problem invented with 2.2.0 beta, haven't seen this before often enough. It even tends to happen when going mobile only, without switching inbetween Wifi and 3G.

'Run in Foreground' is disabled.

To successfully reconnect, I have to disable the account and reenable it again.

**Comment by licaon-kter** [comment]
Enable foreground service
Disable battery optimisations

**Comment by iNPUTmice** [comment]
Please provide the output of `adb logcat -s conversations` during one of those connection attempts.

**Comment by schwindp** [comment]
> Enable foreground service
> Disable battery optimisations

Why should I disable b) if this hasn't been needed before v2.2.0? Any suspicious changes in code?

**Comment by iNPUTmice** [comment]
There haven’t been any changes recently that would lead to such a behaviour.

**Comment by iNPUTmice** [comment]
I tried to reproduce this with two separate Prosody servers and didn’t experience any issues. However I had another user report similar problems (with Prosody). If you get me a test account on your server I can look into it. (You can PM the credentials to my JID which is on my website)

**Comment by iNPUTmice** [comment]
I think there might be something wrong with your prosody server.
* It works on two other Prosody servers (trashserver.net, jabber.de)
* I can’t resume on your server using Conversations Legacy either so it doesn’t seem to be a 2.2.0 regression

Diving a bit deeper into the log it seems that Conversations is sending out the resume stanza which we never get a response to from the server.
