### ISSUE TITLE
Improving on data saving on metered networks

### ISSUE THREAD

**Issue by tyler71** [siacs/Conversations#3017]
#### General information

* **Version:** 2.2.0
* **Android Version:** Android 7.0 Stock
* **Conversations source:** PlayStore Beta Channel

It would be great if conversations would have some kind of option for restricting data usage on metered networks, and removing restrictions on unmetered networks (like most connections with wifi)

As far as I'm aware, there's two methods of saving data:
* Accept files
* Compress Pictures

I have no issue with receiving and sending large file sizes on my wifi, but on mobile would want to limit it.

For example, should there be a data saving option, it could combine the roles of Accept files and Compress Pictures options with something like

All settings Wifi: No compression, auto accept files < 100MiB
* None (Mobile: No compression, auto accept files < 100MiB)
* Min    (Mobile: No compression, auto accept files < 10MiB)
* Med   (Mobile: Automatically Compress, auto accept files < 1MiB)
* Max   (Mobile: Automatically Compress, auto accept files < 256KiB)

**Comment by iNPUTmice** [comment]
Enable the data saver of your OS and make an exception for Conversations. This will make Conversations do more or less the right thing.
