### ISSUE TITLE
Feature: Long tap on link inside message

### ISSUE THREAD

**Issue by b09dan** [siacs/Conversations#3019]
It will be fine to have an ability to do various things with URL inside a message bubble on a long tap.
![image](https://user-images.githubusercontent.com/17816777/39678587-11e744f8-5198-11e8-8e1c-d291a85f3e7c.png)

**Comment by licaon-kter** [comment]
You can "Copy address" now, what more do you want?

**Comment by iNPUTmice** [comment]
There is copy address. Long pressing the url itself is a bit too fiddly for my taste.
