### ISSUE TITLE
Compatibility for Android Oreo Go edition

### ISSUE THREAD

**Issue by sah-anshu** [siacs/Conversations#3020]
Hi
Is this app compatible for Android Oreo Go edition.

Rdgs,
Anshu

**Comment by licaon-kter** [comment]
It should, why?

**Comment by licaon-kter** [comment]
It should, why?

**Comment by sah-anshu** [comment]
No, Let me re-define my question. How can we Optimize this app for Android Oreo Go edition.
It is not working on Nokia1 (Android Oreo Go).

pl advise.

**Comment by licaon-kter** [comment]
Edit the issue title then.

Use ADB to capture a logcat of the start of the app so the devs can see any errors.
