### ISSUE TITLE
[Feature request] swipe/slider for switching between chats

### ISSUE THREAD

**Issue by Xohoo** [siacs/Conversations#3022]
I miss the functionality to switch between different chats without using the back button (like in conversations legacy). It would be great if conversations had a slider like this one https://github.com/r0adkll/Slidr

**Comment by JuniorJPDJ** [comment]
Hell yeah..
You found good example and library.

**Comment by SoyaLeaf** [comment]
switching between chats?
Or something like 1.0？

**Comment by iNPUTmice** [comment]
I’m currently not interested in adding such functionality.
