### ISSUE TITLE
MAM messages lost if server's clock is later than client's clock

### ISSUE THREAD

**Issue by willempx** [siacs/Conversations#3024]
#### General information

* **Version:** 2.2.0
* **Device:** BQ Aquaris X5
* **Android Version:** LineageOS 14.1
* **Server name & software:** reproducible with multiple servers including trashserver.net (prosody 0.10 stable), suchat.org (ejabberd 18.4)
* **Installed server modules:** PEP, blocking command, stream management, roster versioning, message carbons, MAM, CSI, HTTP File Upload, (maybe others as well)
* **Conversations source:** F-Droid
* **Reproducibility:** Always

#### Steps to reproduce

1. Register two accounts, let's call them AccountPhone and AccountPC, and make them appear in each other's contact list.
2. For always-reproducibility, let the server's clock be later than the phone's clock. You can do this by changing the server clock, but it's usually easier to change the client clock. To do so:
2.1. Go to Android Settings (pull down the top bar with the time, tap the gear icon).
2.2. Tap the `Date & Time` menu item
2.3. Uncheck `Automatic date & time`
2.3. Tap `Set time`
2.4. Set a time 5 minutes *in the past*. For example, if the actual time is 11:20, set time to 11:15
3. Let Conversations go online with AccountPhone (but not with AccountPC).
4. Let your PC go online with *both* AccountPhone and AccountPC. I used pidgin.
5. Send a message "Message1" on the PC from AccountPC to AccountPhone.
6. Let Conversations go offline with AccountPhone: in `Manage Accounts` uncheck the AccountPhone's account.
7. Send a message "Message2" on the PC from AccountPC to AccountPhone. Do not wait between step 6 and step 7.
8. Let Conversations go online with AccountPhone. Do not wait between step 7 and step 8.
9. Send a message "Message3" on the PC from AccountPC to AccountPhone

#### Expected result
"Message1", "Message2" and "Message3" should be visible in Conversations.

#### Actual result
Only "Message1" and "Message3" are visible in Conversations. "Message2" is lost.

#### Debug output

no logcat provided because always reproducible.

#### Notes
Clocks are never perfectly synchronized, so better clock synchronization is not a solution. I found the issue by digging why sometimes MAM messages are lost and initially did not know time was a factor, i.e. it is a real-world problem and not just something theoretical.

**Comment by licaon-kter** [comment]
Not synced for a couple of seconds yes, but what's the usecase here to disable auto time sync?

**Comment by willempx** [comment]
> Not synced for a couple of seconds yes

Can you be more precise what you mean? Do you think "Message2" is shown in Conversations a couple of seconds after step 8 or step 9?

> but what's the usecase here to disable auto time sync?

As I wrote, "For always-reproducibility, let the server's clock be later than the phone's clock". So it's not a use case, it's for making it easier to reproduce.

**Comment by licaon-kter** [comment]
Device time not synced for a couple of seconds is understandable, at a point as you go astray even TLS will break.

What "real problem" is shown here? Why would anyone disable time sync?

**Comment by iNPUTmice** [comment]
I’m working on a fix

**Comment by willempx** [comment]
@licaon-kter:
> What "real problem" is shown here?

Sometimes MAM messages are lost, also without disabling time sync.

> Why would anyone disable time sync?

For debugging.

It's a lot easier to debug a problem if the steps-to-reproduce always (instead of sometimes) reproduce the problem. 

@iNPUTmice
> I’m working on a fix

Awesome!

**Comment by CappyT** [comment]
Same issue here, waiting for a fix

**Comment by licaon-kter** [comment]
@CappyT Turning "automatic time & date" fixes it?

**Comment by iNPUTmice** [comment]
The fix made it into 2.2.1

**Comment by DMSalesman** [comment]
@iNPUTmice I can see a similar issue happening on 2.2.2: when an Android device is offline and messages are sent to it, Conversations doesn't display these messages when connection is restored.

I'll check if this behavior is consistent and make you know. For now, I can say that messages coming from jabber.at are affected.
