### ISSUE TITLE
[Feature request] MUC vCard

### ISSUE THREAD

**Issue by svenuthe** [siacs/Conversations#3025]
It would be nice to have a function to set group chat avatars.
The function would rely on [xep-54]. (http://xmpp.org/extensions/xep-0054.html) and therefore would reuse most of the code used for user avatars.

If we could evaluate a concept and enlist most the pitfalls, I would code it myself and publish a PR.

A protocol example can be found at [ejabberd](https://docs.ejabberd.im/tutorials/muc-vcard/)

**Comment by iNPUTmice** [comment]
We can already *display* avatars. The only thing we need is to a method to *set* avatars. Which will probably require a redesign of the Conference Details screen to have a fitting place to set the avatar. While redesigning the conference details screen we should also account for a place to display the muc subject.
And the user list should go in it’s own screen as well for performance reasons.

So it's all a bit more complicate UI wise or else this would have happened already. If you want to take a go with this we should probably discuss some UI mockups first.

**Comment by jimmy51997** [comment]
Hello @svenuthe ....is there any documentation on how to set up the development environment if i want to contribute ??

**Comment by licaon-kter** [comment]
@jimmy51997  get Android Studio...

**Comment by jimmy51997** [comment]
@licaon-kter  I have that already....do i only need to clone the repo and start it using Android studio or are there any additional processes?

**Comment by jimmy51997** [comment]
additional processes?

**Comment by licaon-kter** [comment]
Nope:
Here on Github fork this repo
git clone your-repo
git checkout -B newbranchname
Android Studio
git push origin
On your Github branch, make pull request

Kinda like that...with testing builds on your devices in between.

**Comment by svenuthe** [comment]
How can I set the muc avatar with gajims xml console like in conversations@conference.siacs.eu?
> The avatar is "just" a vCard for the room.
The mentioned ejabberd explanation does not work.
(Need it for testing)

**Comment by licaon-kter** [comment]
You need Gajim fro  development iirc, not the one released, try to use a snapshot.

**Comment by iNPUTmice** [comment]
Current `master` has been redesigned to allow users to set the avatar.
