### ISSUE TITLE
Heads-up Notification New incoming messages only display first notification unless cleared.

### ISSUE THREAD

**Issue by xekon** [siacs/Conversations#3028]
Heads-up Notification New incoming messages only display first notification unless cleared.

#### General information

* **Version:** 2.2.0
* **Device:** Moto X Pure (XT1575 - Android 5.1.1), LG G Pad X 8.3 (VK815 - Android 5.0.2)
* **Server name:** self hosted example.com
* **Server software:** ejabberd 18.04 running on Ubuntu 18.04
* **Installed server modules:** Omemo enabled
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Have Conversations installed on two devices, and log them both in. (to make this simple we will call them romeo and juliet)

2. Have Juliet go to android Home screen, All apps minimized.

3. Romeo opens Conversations and send Juliet a message, "Hello"

4. Juliet Glances at her home screen or Lock screen, and sees that Romeo has sent the message Hello, but shes to busy to respond just yet, so she does nothing, not even clearing the notification.

5. Romeo send another message to Juliet "I love you".

6. Juliets phone receives another notification, the phone vibrates and chimes, unfortunately its still just showing "Hello" on the heads-up notification as well as on the lock screen.

7. Romeo then says, "I just got in a CAR CRASH, Im bleeding ALL OVER!"

8. Juliet glances at her home screen, it still just says "Hello"

9. Juliet later has time to do more than just glance at her phone, unfortunately Romeo is now dead in a ditch somewhere, Had the heads up notification displayed Romeos message, maybe she could have gotten to him sooner, such a tragedy.

#### Expected result

The expected result is that every time a message is sent, the Heads-up notification displays correctly.
Even if that means sending a new Notification instead of altering the old one.
If some people prefer an altered notification instead of a new notification maybe, this could be a toggle option.

#### Actual result

The heads-up notification only shows the first notification, unless you clear/swipe them as they arrive.

#### Debug output

I think this is actually just an oversight on the heads-up notification, and is simply not implemented the way I expect it to work.
Many other chat programs such as hangouts or xabber display each heads-up notification as they arrive regardless if i clear them or not.

However if this is working properly for other people, or possibly in later version of android, then please let me know and I can provide any debug requested. Thank you, and I love this application, and am excited to be using it.

**Comment by licaon-kter** [comment]
Then split the watch issue on a different issue, close this one if duplicate.

**Comment by xekon** [comment]
Sure, and I see you made a reference to it, looks like that report was made back in 2015 so I will just have to see what I can do to work around the problem for now, doesn't seem there was much demand for this since it was 2-3 years ago.

**Comment by licaon-kter** [comment]
Yeah, Juliet should be concerned that Romeo keeps sending her repeated Hello's 😉
