### ISSUE TITLE
messages do not arrive

### ISSUE THREAD

**Issue by whitetornado** [siacs/Conversations#3029]
#### General information

* **Version:**  1.23.8
* **Device:**  Moto g4
* **Android Version:**  Android 7.1 Lineageos / rooted 
* **Server name:**  self hosted
* **Server software:** ii  prosody  0.9.7-2+deb8u3  amd64    Lightweight Jabber/XMPP server
* **Installed server modules:**  all modules what is default by the repo
* **Conversations source:**  self build 

#### Steps to reproduce

1. … user sends message but does not arrive
2. … after a reboot sometimes it works. Its not on all devices but this happend often
3.  connection is over mobile network only!!

#### Expected result

get the message of sender !!!

#### Actual result

nothing, user looks online but still he dont get message, only after a reboot it goes good for a few minutes..

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````
05-16 10:06:42.865 D/conversations(  469): test004@xxxxxx.org send ping (action=ui,lowTimeout=false)
05-16 10:06:42.887 D/conversations(  469): app switched into foreground
05-16 10:06:51.900 D/conversations(  469): AxolotlService (test004@xxxxx.org): Finding devices without session for 53179293@xxxxxxxxxxx.org
05-16 10:06:51.901 D/conversations(  469): AxolotlService (test004@xxxxxxx.org): Cache miss: 6a430858-605e-4eb8-a8ac-716b07763f26
05-16 10:06:51.964 D/conversations(  469): AxolotlService (test004@xxxxxxx.org): Generated message, caching: 6a430858-605e-4eb8-a8ac-716b07763f26
05-16 10:06:51.964 D/conversations(  469): AxolotlService (test004@xxxxxxx.org): Cache hit: 6a430858-605e-4eb8-a8ac-716b07763f26

69 D conversations: AxolotlService (test004@xxxxxxxx.org): Finding devices without session for 53179293@xxxxxxxx.org
05-16 09:57:43.760   469   469 D conversations: AxolotlService (test004@xxxxxxxx.org): Cache miss: f65885ef-3976-4411-a322-15746ac8bb49
05-16 09:57:43.896   469   731 D conversations: AxolotlService (test004@xxxxxxxx.org): Generated message, caching: f65885ef-3976-4411-a322-15746ac8bb49
05-16 09:57:43.897   469   731 D conversations: AxolotlService (test004@xxxxxxxx.org): Cache hit: f65885ef-3976-4411-a322-15746ac8bb49

05-16 09:59:07.016   469   469 D conversations: deleting presence template with uuid 82fdc07f-c098-4b41-bc63-64290e6e98bb
05-16 09:59:09.123   469   469 D conversations: AxolotlService (test004@xxxxxxxx.org): Finding devices without session for 53179293@xxxxxxxx.org
05-16 09:59:09.124   469   469 D conversations: AxolotlService (test004@xxxxxxxx.org): Cache miss: cf40ac20-919f-474a-8254-5fb23848eea8
05-16 09:59:09.199   469   731 D conversations: AxolotlService (test004@xxxxxxxx.org): Generated message, caching: cf40ac20-919f-474a-8254-5fb23848eea8
05-16 09:59:09.199   469   731 D conversations: AxolotlService (test004@xxxxxxxx.org): Cache hit: cf40ac20-919f-474a-8254-5fb23848eea8
05-16 09:59:39.526   469   469 D conversations: app switched into background
05-16 09:59:47.054   469   469 D conversations: test004@xxxxxxxx.org send ping (action=ui,lowTimeout=false)
05-16 09:59:47.067   469   469 D conversations: app switched into foreground

**Comment by licaon-kter** [comment]
Please edit the text, remove the template examples and add your version, your device, your, your, your...

**Comment by whitetornado** [comment]
done

**Comment by licaon-kter** [comment]
So you self build the app but you are at version 1.23.8?

**Comment by whitetornado** [comment]
yes because that build contains some cosmetics changes...

2018-05-16 10:50 GMT+02:00 Licaon_Kter <notifications@github.com>:

**Comment by licaon-kter** [comment]
Ok, you've disabled battery optimizations?

You added the app to the protected apps or whatever LOS has?

**Comment by whitetornado** [comment]
1) yes its not optimized
2) no i not did that

2018-05-16 11:52 GMT+02:00 Licaon_Kter <notifications@github.com>:

**Comment by whitetornado** [comment]
build the latest version and also the first messages are not arrive. This
is the logcat:

05-16 12:12:03.631 I/conversations(25512): AxolotlService (
test004@xxxxxxxx.org): Adding 1 new preKeys to PEP.
05-16 12:12:03.640 D/conversations(25512): AxolotlService (
test004@xxxxxxxx.org): : Bundle 957203907 in PEP not current. Publishing...
05-16 12:12:04.097 D/conversations(25512): AxolotlService (
test004@xxxxxxxx.org): Successfully published bundle.
05-16 12:12:15.053 D/conversations(25512): AxolotlService (
test004@xxxxxxxx.org): Finding devices without session for
59347105@xxxxxxxx.org
05-16 12:12:15.054 D/conversations(25512): AxolotlService (
test004@xxxxxxxx.org): Cache miss: fabfab4b-faf1-4474-b3e3-608bc0daf312
05-16 12:12:15.094 D/conversations(25512): AxolotlService (
test004@xxxxxxxx.org): Generated message, caching:
fabfab4b-faf1-4474-b3e3-608bc0daf312
05-16 12:12:15.094 D/conversations(25512): AxolotlService (
test004@xxxxxxxx.org): Cache hit: fabfab4b-faf1-4474-b3e3-608bc0daf312
05-16 12:12:32.315 D/conversations(  469): found auth tag as part of omemo
key
05-16 12:12:32.317 D/conversations(  469): AxolotlService (
test004@xxxxxxxx.org):  Received Message with session fingerprint:
05074036124ae1d907ac840dc20d579f43945abd0aeab3e8fad9e835e6809fe335
05-16 12:12:32.330 D/conversations(  469): update unread count to 2
05-16 12:12:32.333 D/conversations(25512): found auth tag as part of omemo
key
05-16 12:12:32.335 D/conversations(25512): AxolotlService (
test004@xxxxxxxx.org):  Received Message with session fingerprint:
05074036124ae1d907ac840dc20d579f43945abd0aeab3e8fad9e835e6809fe335
05-16 12:12:32.353 D/conversations(25512): update unread count to 1
05-16 12:12:32.361 D/conversations(25512): test004@xxxxxxxx.org:
suppressing notification because conversation is open
05-16 12:12:32.405 D/conversations(25512): update unread count to 0
05-16 12:12:32.436 D/conversations(25512): test004@xxxxxxxx.org: sending
read marker to 59347105@xxxxxxxx.org/phone
05-16 12:12:48.450 D/conversations(25512):
ConversationsOverviewFragment.onStart()
05-16 12:12:48.450 D/conversations(25512):
ConversationsOverviewFragment.onResume()
05-16 12:12:49.664 D/conversations(25512):
ConversationsOverviewFragment.onPause()

2018-05-16 12:07 GMT+02:00 Henk Nienhuis <whitetornado.nl@gmail.com>:

**Comment by whitetornado** [comment]
ok testing only with wifi and all messages are arrived. So the pain in the !@#$ is mobile internet. How is it possible that with mobile internet exhibited this behavior and how to get this reliable without WiFi ??

**Comment by licaon-kter** [comment]
Do you have network controls, efsg. Mobile data background restrictions ?

**Comment by licaon-kter** [comment]
Do you have network controls, efsg. Mobile data background restrictions ?

**Comment by pmaier1** [comment]
Afaik you need to install from Google Play to be able to use push notifications which should help (needs to be supported by the server as well).

**Comment by CappyT** [comment]
Disable battery optimizations on android, data restrictions and background activity should be enabled on android 8+

Had the same problem, on ejabberd i set the resend_on_timeout: always on mod_stream_management and default: true on mod_mam (to ensure messages are not lost)

**Comment by iNPUTmice** [comment]
Conversations 2.3.9 will display 'unable to decrypt' warnings and will also attempt to self heal broken sessions. Both features require your server to support `mam:2`.
