### ISSUE TITLE
new logo design

### ISSUE THREAD

**Issue by harunbadilli** [siacs/Conversations#3030]
Hi, I have a logo that I want to gift to you. It is a more understandable logo with its design and new appearance. I can send in any size and format.just specify what you need. I hope you like it

![1](https://user-images.githubusercontent.com/34319922/40109444-0b224dd2-5906-11e8-87c4-55521a5d456b.png)

**Comment by ArchangeGabriel** [comment]
This utopian.io things is becoming annoying…
