### ISSUE TITLE
OMEMO: Doesn't seem to refetch new device IDs

### ISSUE THREAD

**Issue by aszlig** [siacs/Conversations#3032]
Unfortunately I don't have the XML logs for this anymore, but let my try to describe it:

This has happened between me (`Y`) using Gajim only and another contact (`X`) with Gajim and Conversations.

`Y` recently cleared the device list and started with a new device ID. While the Gajim client of `X` refreshed the device IDs upon connect and sent messages only with the `rid`s that really existed, Conversations on the other hand still sent messages with `rid` attributes containing old device IDs.

After digging a bit through the source code of Conversations it seems that the *full* device list of other contacts are only fetched if they're empty ([createSessionsIfNeeded](https://github.com/siacs/Conversations/blob/be579332be40d147e581230853834572840dc32f/src/main/java/eu/siacs/conversations/crypto/axolotl/AxolotlService.java#L1190)), but I'm not familiar enough with the code base so maybe I'm forgetting about something.

Wouldn't it make sense to re-fetch the new device ID list whenever a new device ID pops up in a new message? Or maybe have a button where someone can trigger this?

**Comment by aszlig** [comment]
@iNPUTmice: This occured with mutual presence subscription. So this indicates that somehow the PEP event didn't get pushed to Conversations of `X`, but shouldn't that be sent several times if the event didn't reach the client? This happened over the course of two weeks or so, so if my assumption is correct the event must have been sent, right?

**Comment by iNPUTmice** [comment]
Your contacts device list will get send in the moment they change it and then again every time you log in.

**Comment by aszlig** [comment]
Okay, so in theory this means that Conversations shouldn't be at fault here. I'll close this for now until I can fully replicate this and it's indeed a bug in Conversations, thanks for your input.
