### ISSUE TITLE
Unable to download locally deleted files that I sent

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#3033]
#### General information
* **Version:** 2.2.0
* **Android Version:** Oreo
* **Conversations source:** F-Droid

#### Steps to reproduce
1. Send a file (eg. video/image file, something with preview)
2. After a (short) while delete original from device

#### Expected result
* The preview disappears.
* A text appears instead saying `File deleted`
* Long press on message you have the option `Download`

#### Actual result
* Preview is a black rectangle
* Trying to play the file you get the toast with `File deleted`
* There is no option to download on long press

#### Workaround
* disconnect account
* swipe app
* ForceClose app
* re-open app-> black previews are gone, message bubbles say `File deleted`, long press `Download` option reappears.

#### Debug output
Not yet

**Comment by iNPUTmice** [comment]
Where was the file stored originally?

**Comment by licaon-kter** [comment]
It does not matter, eg. default Movies folder, but I'll have to check in adb if there's a mention exactly

Also, on another device on Marshmallow I saw a received file that was deleted from Conversations/Media/Conversations Images/ that stayed as preview in Conversations, same behaviour.@

**Comment by licaon-kter** [comment]
This improved in the mean time.
