### ISSUE TITLE
Transfer Conversations to a new phone...

### ISSUE THREAD

**Issue by dennisguse** [siacs/Conversations#3034]
I would like to migrate a Conversations installation to a new phone without the cloud (I think Google provides a backup functionality that allows that).

I could not find an end-user capable option to export all data and import it on the new phone.
So, what is the best option to achieve a data transfer?

Running Conversations 2.2.1 on both phones.

PS: It is an upgrade from Android 6.0 to Android 8.1.

**Comment by licaon-kter** [comment]
`adb backup`, see the README info too.

**Comment by alexara** [comment]
It would indeed be desirable to have a simple feature to export and import an account + settings + chat history and files password protected (encrypted) -- especially since OMEMO is default now. :-)

I guess the average user does not have `adb` installed or wants to deal with it.

**Comment by hermann-san** [comment]
I think the disclaimer of Holo-Backup (which is using ADB-Backup) underlines the need for a export/backup solution that works without root.
![dd-6](https://user-images.githubusercontent.com/7679654/40862692-976c939e-65ed-11e8-841e-78c076d4f473.png)
"ADB Backup is an undocumented, hacky and untested part of the Android SDK. There are various phones and tables it has trouble with....."

**Comment by iNPUTmice** [comment]
2.4.0 will and current master does support backup/restore.
