### ISSUE TITLE
Disable Google Analytics introduced by FCM

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#3041]
Since you have introduced Firebase, you might need to explicitly disable Google Analytics:

Source: https://firebase.google.com/docs/analytics/

> **Permanently deactivate collection**
> 
> If you need to deactivate Analytics collection permanently in a version of your app, set firebase_analytics_collection_deactivated to true in your app's AndroidManifest.xml in the application tag. For example:
> 
> `<meta-data android:name="firebase_analytics_collection_deactivated" android:value="true" />`
> 
> **Disable Advertising ID collection**
> 
> If you wish to disable collection of the Advertising ID in your Android app, you can set the value of google_analytics_adid_collection_enabled to false in your app's AndroidManifest.xml in the application tag. For example:
> 
>` <meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />`
> 

Source: https://firebase.google.com/support/guides/disable-analytics

See also https://stackoverflow.com/questions/39327141/disable-the-analytics-service-for-firebase-cloud-messaging

**Comment by iNPUTmice** [comment]
Oh *thats* why they are forcing people to migrate to fcm :-(

**Comment by alexara** [comment]
I am not sure if I did not panic too early actually :-)

If you look at these instructions: https://firebase.google.com/docs/analytics/android/start/
It says 
> Getting started with Analytics is easy. Just add the Firebase SDK to your new or existing app, and data collection begins automatically
(...)
Add Analytics to your app
Add the dependency for Google Analytics for Firebase to your app-level `build.gradle` file:
`implementation 'com.google.firebase:firebase-core:15.0.0'`

>FCM | Analytics automatically logs events that correspond to notification messages sent via the Notifications composer and supports reporting on the impact of each campaign.

If you have a look at https://firebase.google.com/docs/android/setup#available_libraries
it says that the `firebase-core` library corresponds to the Analytics part of FireBase.

So, will Analytics only be used if  the `firebase-core` library is explicitly compiled with the app?
Or do you need to exclude it in the `build.gradle` file to prevent FireBase from tracking?

`configurations.all {
exclude group: 'com.google.firebase', module: 'firebase-core'
}`

**Comment by iNPUTmice** [comment]
By looking at the merged manifest excluding it seems to work...
But it was pulled in as a dependency. Will do some more testing.

**Comment by iNPUTmice** [comment]
I’m closing this issue. I think current master successfully disables analytics. Thanks for bringing this to my attention.
