### ISSUE TITLE
Image download via http_upload does not work

### ISSUE THREAD

**Issue by mase76** [siacs/Conversations#3042]
#### General information

* **Version:** 2.2.0
* **Device:** Sony Xperia X
* **Android Version:** Omnirom 8.1.0
* **Server name:** self hosted
* **Server software:** Prosody 0.10.0
* **Installed server modules:** csi, mam, http_upload, carbons smacks
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Receive an image (omemo enabled)
2. Click check image size (works)
3. Click download (fails with not found)

#### Expected result
Image is downloaded and shown

#### Actual result
Check of image size correct, also the link address of the image is correct. Error Message file not found.

What do you see instead?
Download failed, file not found.
The same in gajim works.

#### Debug output
No error messages in logcat.
connection: com.android.okhttp.internal.huc.HttpURLConnectionImpl:https://<correct_link>

**Comment by licaon-kter** [comment]
Update server and modules, retry?

**Comment by mase76** [comment]
Already did so. No changes.

**Comment by licaon-kter** [comment]
More logs...

**Comment by mase76** [comment]
Solved by deleting the Conversations folder on the device.
