### ISSUE TITLE
Push notifications not working on prosody 0.10.1

### ISSUE THREAD

**Issue by beatstick** [siacs/Conversations#3043]
I get the following error report by prosody when trying to send a message to my phone:
my_domain.org:cloud_notify        info Got error of type 'cancel' (item-not-found) for identifier 'push.siacs.eu<64uuqnltro0dj': error count for this identifier is now at 1

Microg reported the last push message was send to conversations last December (I think around the time I updated prosody to 0.10). So maybe something changed with prosody and not conversations, but I am not sure.

* **Version:**  2.2.1
* **Device:** Moto G Falcon 2013
* **Android Version:** crdroid 7.1 
* **Server name:** self hosted prosody
* **Server software:** prosody 0.10.1
* **Installed server modules:** Stream Managment, CSI, MAM, 
* **Conversations source:** play store

**Comment by Failure404** [comment]
Hi, I experience the same in pretty much the same environment.

**Comment by iNPUTmice** [comment]
Since 2.2.1 Conversations is using p2.siacs.eu as an app server. References to push.siacs.eu can just be removed on the server.
