### ISSUE TITLE
Feature Request: send predefined message to predefined contact

### ISSUE THREAD

**Issue by aslmx** [siacs/Conversations#3046]
#### General information

_I hope this wasn't discussed (and rejected) before, but i could only find slightly relating tickets._

Since we have Contact Shortcuts as a widget now, it would make my life - and maybe/hopefully others as well - easier if we could have a widget that not only opens the contacts thread, but also puts a predefined message into the text box. Whether the text is send automatically or not can be discussed. 

It could (i'm not entirely sure yet) be a workaround to implement to implement this rejected feature request
https://github.com/siacs/Conversations/issues/1808
and then simply use some kind of generic link / shortcut widget.

#### UX Proposal

1. User has contact
2. User goes to home screen and adds a widget, within the conversations category of widgets he can now see the 1x1 contact shortcut that is already implemented, but also these additional two widgets

- message draft
- direct message

3. user adds "message draft" first. He is shown the roster to choose a contact or a Group
4. after choosing the contact he can write a message and save it.

5. after that he adds a "direct message". Also here he is shown the roster to select a contact or a group
6. after choosing contact or group, also here he can save a message.

The difference of the two created shortcuts/widgets would be
**message draft**: if the user clicks the widget, the contacts thread is openend and the predefined message is put into the text box. The user can simply add or change predefined text and then decide to send it
**direct message**: the user clicks on the shortcut and is shown the message thread. The predefined message is directly sent without any further action necessary.

#### Use Cases

i would have or could imagine the following use cases:

- I could send a message "coffee is ready" or "Coffee is WIP" to our teams group chat when the coffee is ready or when i have prepared it
- i could send a message to loved ones that i have arrived safely
- I could send a message to my car pool that i'm leaving work and i am about to pick them up
- ... or i could let them know that i am now " 5 minutes" from their place and they should get ready (which would make me press only one button while driving, yes i know it is also too much alrady ;) )

... and i guess people  have millions of other messages that they send regularly to the same contacts...

**Comment by martinsauter** [comment]
+1

**Comment by tdemin** [comment]
This is called "message templates".

**Comment by seanlilmateus** [comment]
+1
I like the idea of having "messages templates" as well, special as shortcuts

**Comment by adiaholic** [comment]
+1

**Comment by tdemin** [comment]
@martinsauter @seanlilmateus @adiaholic you should use the reactions instead of commenting with "+1", those flood the discussion.

**Comment by brighterness** [comment]
> his is called "message templates".

This is one step away from  an "autoresponder".  In xmpp lingo this is "pounce".

**Comment by wiktor-k** [comment]
By the way one can use URI shortcuts, for example, a shortcut for the following URI: `xmpp:contact@example.com?message;body=testing%20test` will open Conversations will pre-filled message body.

One way to do that is to download [AnyCut](https://play.google.com/store/apps/details?id=com.spring.bird.anycut&hl=en) (I've got no affiliation with them), creating a new AnyCut widget on screen, choose "Make my own" enter `android.intent.action.VIEW` as action and `xmpp:contact@example.com?message;body=testing%20test` as data.

Not as straightforward as a built-in method but certainly do-able.

**Comment by iNPUTmice** [comment]
I suggest you use @wiktor-k suggestion.

**Comment by aslmx** [comment]
Thanks for the suggestion.
But no thanks.

i'm not going to install some chinese non-open source app from the play store. 
Rather i'd live with this "feature gap".

**Comment by aslmx** [comment]
Well. Thanks for the clarification. My knowledge of such Android specifics is limited.

You don't happen to know an app that does the same and is abailable on fdroid?
