### ISSUE TITLE
FR: Parse image urls as inline images

### ISSUE THREAD

**Issue by gerroon** [siacs/Conversations#3049]
#### General information

* **Version:** 
2.2.1
* **Device:** eg Google Nexus 5
Samsung
* **Android Version:** eg Android 6.0 Stock or Android 5.1 Cyanogenmod
Lollipop
* **Server name:** eg conversations.im, jabber.at or self hosted
Self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
ejabberd 18.04
* **Module:** 
mod_http_upload

* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)
Fdroid

Hi

I use Psi+ on Linux. When I upload an image in a message in Psi+, it sends the image as a url (based on my http_upload settings) to Conversations, at least that is what I see in Conversations. But Psi+ inlines the upload image properly. The url etc are all correct and the upload image is downloadable from in a web browser.

I think that it would be very nice if Conversations treats these kinds of image urls like parseable images and downloads and inlines the images. This way most of these xmpp clients can be abit more compatible with Conversations. I do not have this issue from Conversations to Conversations,the uploads/downlloads feels transparent.

thanks

**Comment by iNPUTmice** [comment]
Psi+ should add an [x-obb](https://xmpp.org/extensions/xep-0066.html#x-oob) tag to the message to signal that the URL is in fact an attachment and not just a pasted URL.

```
<message to="someone" from="someoneelse">
  <body>https://domain.tld/file.jpg</body>
  <x xmlns='jabber:x:oob'>
    <url>https://domain.tld/file.jpg</url>
  </x>
</message>

**Comment by gerroon** [comment]
Hi

Sure it would be nice if everyobe out there respects all this stuff, but it does not happoen. My FR is for making the experience much smoother for the Conversations users. 

We can`t control what others use.

**Comment by iNPUTmice** [comment]
No we can not. But you can ask the Psi+ to implement this feature. Thats why I described what needs to be done in that amount of detail.
