### ISSUE TITLE
Detect all valid geo urls

### ISSUE THREAD

**Issue by sualko** [siacs/Conversations#3050]
[RFC 5870](https://tools.ietf.org/html/rfc5870) allows to add extra parameters zu an geo url. Therefore it would be nice if Conversations would also detect urls like `geo:46.6912331,8.136409;u=29.3570325`.

I think the change would be easy at this position:

https://github.com/siacs/Conversations/blob/8d5a7c79da566336230a1d59919f7ba769e08d9d/src/main/java/eu/siacs/conversations/utils/GeoHelper.java#L29

Are you interested in a pr?

**Comment by iNPUTmice** [comment]
> Are you interested in a pr?

yes
