### ISSUE TITLE
Use IPv6

### ISSUE THREAD

**Issue by genofire** [siacs/Conversations#3060]
#### General information

* **Version:** 2.2.2
* **Device:** FP2
* **Android Version:** Android 7.1
* **Server name:** eg conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce
Connect to a dual-stack xmpp hoster.

#### Expected result
Connection with IPv6

#### Actual result

Connected with IPv4

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
I’m not sure I agree with the premise of the expected result.
IPv6 is broken on a surprising numbers of wifis and servers and that’s why IPv4 gets tried first. Can you explain why you want it to prefer IPv6?

**Comment by ValdikSS** [comment]
@iNPUTmice, IPv6 is preferred over IPv4 on all modern operation systems. In fact, there's a standard of a priority of various IP address types: https://tools.ietf.org/html/rfc3484
A proper way to handle IPv6 and IPv4 without any delays is [Happy Eyeballs](https://en.wikipedia.org/wiki/Happy_Eyeballs) algorithm.

**Comment by iNPUTmice** [comment]
> A proper way to handle IPv6 and IPv4 without any delays is Happy Eyeballs algorithm.

And you are very welcome to implement this or pay me to implement this. Until it has and given the situation described above i think it is in the interest of the users to have a working solution across all networks.

**Comment by ValdikSS** [comment]
@iNPUTmice why did you close the bug? This is a valid issue.

**Comment by iNPUTmice** [comment]
@genofire This is a very wasteful implementation. What one needs to do is establish the sockets that will actually be used for XMPP simultaneously and use the one that establishes a stream first.

**Comment by genofire** [comment]
1. It is better than to force the use of IPv4, only because there is an IPv4 DNS entry.
That does not work in IPv6-only networks. I do not get any working connection. (Your Application does not work there).
So we need really a solution.

2. On this way, it works for everyone and use there the best connection.
So nobody could say that it not work on his broken IPv4 or IPv6 network.

**Comment by iNPUTmice** [comment]
> It is better than to force the use of IPv4, only because there is an IPv4 DNS entry.
That does not work in IPv6-only networks. I do not get any working connection. (Your Application does not work there).

The current code is supposed to try both. Just with a preference of IPv4 over IPv6. If that doesn’t work please provide the output of adb logcat during the connection attempt.

**Comment by laclaro** [comment]
Hi guys,

please negotiate again about ipv6 support. Better do it privately, but I'm really sure it does not help to split forces and develop this flagship of secure mobile xmpp in parallel!

Behind the scenes, ipv6 is here since years now and it is indeed faster.

And as a plus for the hackers utopia of distributed xmpp servers as backbone of world-wide secure communication:
Many large ISPs leave private customers with no choice but host an ipv6 server or pay for ipv4. Enable them to host their own server (no problem at all) and still use Conversations!

Best,

Henning

**Comment by iNPUTmice** [comment]
> Many large ISPs leave private customers with no choice but host an ipv6 server or pay for ipv4. Enable them to host their own server (no problem at all) and still use Conversations!

Conversations connects absolutely fine to IPv6 only servers.

**Comment by jpds** [comment]
The linked PR should now be merged. IPv4 is now the minority protocol version in various countries: https://www.google.com/intl/en/ipv6/statistics.html#tab=per-country-ipv6-adoption

Amazon/Apple/Facebook/Google/Microsoft/Netflix/Wikimedia all natively support IPv6 for client facing traffic, including mobiles. One cannot objectively state that an app isn't going to properly support it on an OS when the YouTube app on it works just fine.

**Comment by licaon-kter** [comment]
IPv6 works fine already, it does not work for you?

**Comment by jpds** [comment]
@licaon-kter No, it does not because Conversations is hard coded to prefer IPv4.

I came across this issue whilst trying to figure out why all my users use v6 just fine on all the other clients but Conversations.

**Comment by licaon-kter** [comment]
Where's *your* issue with logs?

**Comment by iNPUTmice** [comment]
Conversations 3.0 will probably be a good point to remove the IPv4 preference.

**Comment by sijanec** [comment]
Sorry for hijacking this issue, but Conversations 2.12.3+free (and it's fork, monocles) does not connect when on an IPv6-only data connection (my ISP does not offer dual stack).

I'm connecting to a dual stack server (JID: anton@sijanec.eu)
