### ISSUE TITLE
Unread messages count badge is missing on android 8.

### ISSUE THREAD

**Issue by rohij** [siacs/Conversations#3067]
#### General information

* **Version:** 2.2.2
* **Device:** Galaxy S7
* **Android Version:** Android 8.0 Stock
* **Server name:** conversations.im, 
* **Conversations source: F-Droid

I have updated my phone from android 7 to android 8, and now it does not show unread count bagde. For other apps it seems to work fine.

**Comment by licaon-kter** [comment]
Other launchers work?

This badge is a launcher function, not an app one.

FYI, works fine on Xperia Home.

/close as invalid

**Comment by guerda** [comment]
I'm also missing the unread badge on Android 7.
* Version: 2.3.2 from FDroid
* Device: honor 5C

Other applications use the badges successfully (Signal, Threema, WhatsApp, LinkedIn)

**Comment by licaon-kter** [comment]
What launcher?

**Comment by guerda** [comment]
I'm using the default launcher of my honor 5C. The interface is called EMUI, I think this is also the launcher's name. I'm using EMUI version 5.0.3

**Comment by iNPUTmice** [comment]
The unread badge depends on your launcher.
