### ISSUE TITLE
TCP connection active even when push is registered on the server

### ISSUE THREAD

**Issue by dhiru1602** [siacs/Conversations#3072]
#### General information

* **Version:** 2.2.2
* **Device:** Samsung Galaxy S8+
* **Android Version:** Android 8.0
* **Server name:** Self Hosted
* **Server software:** Ejabberd 18.04-1
* **Installed server modules:** MAM (ODBC), Stream Management, mod_push, p2, mod_ping
* **Conversations source:** Self Build (Tag 2.2.2)

#### Steps to reproduce

1. Enabled FCM push support on ejabberd using Conversations Push Proxy. 
2. Build the playstore release favor of Conversations.

#### Expected result
When push is registered on the server, Conversation should make a direct TCP connection only when the application is active and close the connection when the app is in the background. The stream management on the server would detect a connection loss and initiate a push message to inform newer messages which would subsequently wake up Conversations and initiate a direct TCP connection again. 

#### Actual result
A direct TCP connection is maintained to the server regardless of push registration on the server which renders the push service completely useless.

**Comment by licaon-kter** [comment]
So you are a registered developer on the Play store, got a push key from Google, put that in code, hosted your own instance of the push server, modified the code to point that instead of p2.siacs.eu, built the playstore flavor.....and it does not work?

**Comment by dhiru1602** [comment]
Yes. Push works perfectly fine as intended, however the issue is that when push is registered on the server, I was expecting the direct server TCP connection to be killed when the application is inactive which is not happening. The direct connection is still being maintained, which would render push support useless.

I have come across earlier patches which implemented PUSH_MODE, which have been eventually reverted with no commit description.
**optional mode to close tcp connection when going into background**
https://github.com/siacs/Conversations/commit/251f2479c2df4510690a8ef4be9d4b7d2b9e04f7

**close tcp connection after 30s of inactivity when in push_mode**
https://github.com/siacs/Conversations/commit/9bfdbc708eeb83219d9f1eb711b167b92df93805

**Comment by iNPUTmice** [comment]
This is working as intended. Conversations uses push only as a fallback. The config settings you mentioned were only being used for testing purposes.
