### ISSUE TITLE
OMEMO messages silently fail to be decrypted with "InvalidMessageException: No valid sessions." in logcat

### ISSUE THREAD

**Issue by ashimokawa** [siacs/Conversations#3076]
#### General information

* **Version:** 2.2.2
* **Device:** Galaxy S4 Mini
* **Android Version:** 8.1.0 (LineageOS self compiled)
* **Server name:** jaber.ccc.de
* **Server software:** I don't know
* **Installed server modules:** PEP, Blocking Command, Stream Management, Roster Versioning, Message Carbons, MAM, CSI
* **Conversations source:** F-Droid

#### Steps to reproduce

Impossible to reliably reproduce, either it always works with a contact, or it never does

#### Expected result

All OMEMO messages arrive.

#### Actual result

OMEMO messages never arrive from and to some contacts. Fingerprints are accepted on both sides. They are received by Conversations, but not displayed. I can sucessfully communicate with some on the same remote server with the same Conversations version, but with others it always fails. Also using Gajim I can send OMEMO messages to the non-working contacts and my own messages sent from Conversations and Gajim get replicated in the other client.

#### Debug output

06-12 21:13:21.283  8281 15872 W System.err:    at eu.siacs.conversations.crypto.axolotl.XmppAxolotlSession.processReceiving(XmppAxolotlSession.java:102)
06-12 21:13:21.284  8281 15872 W System.err:    at eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage.unpackKey(XmppAxolotlMessage.java:275)
06-12 21:13:21.284  8281 15872 W System.err:    at eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage.decrypt(XmppAxolotlMessage.java:284)
06-12 21:13:21.284  8281 15872 W System.err:    at eu.siacs.conversations.crypto.axolotl.AxolotlService.processReceivingPayloadMessage(AxolotlService.java:1404)
06-12 21:13:21.284  8281 15872 W System.err:    at eu.siacs.conversations.parser.MessageParser.parseAxolotlChat(MessageParser.java:123)
06-12 21:13:21.284  8281 15872 W System.err:    at eu.siacs.conversations.parser.MessageParser.onMessagePacketReceived(MessageParser.java:399)
06-12 21:13:21.284  8281 15872 W System.err:    at eu.siacs.conversations.xmpp.XmppConnection.processMessage(XmppConnection.java:790)
06-12 21:13:21.284  8281 15872 W System.err:    at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:653)
06-12 21:13:21.284  8281 15872 W System.err:    at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:512)
06-12 21:13:21.284  8281 15872 W System.err:    at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:837)
06-12 21:13:21.284  8281 15872 W System.err:    at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:496)
06-12 21:13:21.284  8281 15872 W System.err:    at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:410)
06-12 21:13:21.284  8281 15872 W System.err:    at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:483)
06-12 21:13:21.290  8281 15872 W conversations: AxolotlService (XXX@XXX.XX): Failed to decrypt message from XXX@XXX.XX: Error decrypting WhisperMessage InvalidMessageException: No valid sessions.
.

**Comment by ashimokawa** [comment]
I fixed this problem the following way:

1. Disable account
2. Force close Conversations
3. Do the following:

adb root && adb shell
cd /data/data/eu.siacs.conversations/databases/
sqlite history
delete from sessions where name='XXX@XXX.XX';

4. Other contact removed me from the contact list and readded me
5. I could accept the OMEMO keys
6. success

**Comment by iNPUTmice** [comment]
Conversations 2.3.9 will display 'unable to decrypt' warnings and will also attempt to self heal broken sessions. Both features require your server to support `mam:2`.
