### ISSUE TITLE
Feature: changing behaviour of quick share

### ISSUE THREAD

**Issue by Etua** [siacs/Conversations#3077]
Currently when I use share button in an external app like Gallery, I'm presented with last 4 MUCs or users from whom I received a message recently. I participate in a few public chats that tend to be very active and that results in them taking all 4 slots, despite I rarely want to share something there.

Instead, I suggest showing last 4 RECIPIENTS of our messages. If you are during conversation with friend or someone from MUC and switch to another app just to send him something, he should be visible both now and after such change, but a MUC that you only read for most of the time would not replace any contact just because the latter sends you a message every few hours not a few minutes.

**Comment by licaon-kter** [comment]
Isn't that a ROM feature? Share "to Conversations"

**Comment by Etua** [comment]
@licaon-kter I use LineageOS, this feature.looks like:
![](https://i.imgur.com/7xDR3VB.png)

**Comment by licaon-kter** [comment]
Right, Sony has those too, not sure Conversations can control what appears there.

**Comment by tdemin** [comment]
@licaon-kter nah, I add a thumb-down emoji in cases when I disagree with a person or know he/she's not right.

**Comment by licaon-kter** [comment]
@tdemin and in my case? I mean if you add that, make it clear why...
