### ISSUE TITLE
Contacts search ignores offline toggle

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#3079]
F-Droid 2.2.2

Steps:
* Open roster
* Check "hide offline"
* Search for contacts

Expected result:
* Only online contacts are shown

Actual result
* All contacts are shown, both online and offline

**Comment by iNPUTmice** [comment]
This is a feature.

**Comment by thereyougo** [comment]
enable Dynamic Tags to see which contacts are online 😄

**Comment by licaon-kter** [comment]
@thereyougo Not what I've asked.
