### ISSUE TITLE
Account registration with Captcha

### ISSUE THREAD

**Issue by kruks23** [siacs/Conversations#308]
Hi,

I don't know if would be possible to register a new account on server where captha is required.
The problem is most servers requires captcha for registrarion and if it is so difficult to persuade people to join xmpp, when I tell them they have to go to the computer to create an account, they ignore me...

For example the server I used (suchat.org), captcha is required. 
Is there a XEP to deal with captcha? Maybe XEP-0158?

Thank you.

**Comment by 1nsan3** [comment]
For me, this also is one of the last problems stopping me from recommending the use of Conversations and Jabber. As stated in #724, jabber.ccc.de is using this, probably the biggest and most trustful open jabber server in Germany.

**Comment by akallabeth** [comment]
I'd be willing to create a patch for that, just need some hint in how to properly show an ```AlertDialog``` from ```XmppConnection``` and propagate the response back.

**Comment by iNPUTmice** [comment]
implemented in 1.6.x
