### ISSUE TITLE
Sharing files does not trigger the Trust Keys Activity

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#3083]
#### General information

* **Version:** 2.2.3
* **Server name:** self hosted
* **Server software:** ejabberd 18.04.79
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Be in an OMEMO enabled MUC
2. Some new users where added
3. Try to send a picture

#### Expected result

You see the _"these are the keys press Finish"_ screen (since there are new keys for the new users), then the picture is sent.

#### Actual result

Picture fails to send, there is no long press menu entry to see the error, hence it's not clear what's wrong.

#### Fix

Write a text message, see _"these are the keys press Finish"_ screen, then try to send the picture, now it will work.

**Comment by iNPUTmice** [comment]
How are you trying to send a picture

**Comment by licaon-kter** [comment]
Right, I've tested:
* _Share from Gallery to MUC_
* _Share from Gallery to SendReduce to MUC_

**Comment by iNPUTmice** [comment]
'Fixed' by the introduction of media preview.
