### ISSUE TITLE
some notify

### ISSUE THREAD

**Issue by thereyougo** [siacs/Conversations#3084]
#### General information

* **Version:** eg 2.2.3 b274
* **Device:** eg note 6
* **Server name:** conversations.im
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** , F-Droid, 

#### Steps to reproduce

Can I fire no notification icon for anyone other than specified roster members?

Or how can I use Tasker to dismiss notification icons other than people I white list? That way I can have it if it's not a feature.

1. …
2. …

#### Expected result

not have to disable notifications for annoying people

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by licaon-kter** [comment]
You can disable notifications for each one. That's not enough?
