### ISSUE TITLE
least effort lowest competencies to install fully compliant prosody in cloud hosting

### ISSUE THREAD

**Issue by thereyougo** [siacs/Conversations#3089]
I am not savvy enough to figure out the missing bits from online setup journals.  I want to buy a domain to use the same address for email, xmpp, and someday sip & matrix. For myself and up to 5 other people.

Can you recommend some low cost functional options?  I am located in Sunset Beach, California, USA

DreamHost DreamCompute cloud is $4.75/month for minimal stuff.  Amazon AWS seems like it would be low cost. Arvixe.com is GROSSLY inept. Digital Ocean?

**Comment by licaon-kter** [comment]
/close this

Not the place, maybe use the conference for questions

**Comment by iNPUTmice** [comment]
Please use the community group chat for these kind of questions.
