### ISSUE TITLE
"stream error" with servers that require TLS 1.2

### ISSUE THREAD

**Issue by hotaru2k3** [siacs/Conversations#3090]
#### General information

* **Version:** 2.2.4
* **Device:** Google Pixel XL
* **Android Version:** 9 beta
* **Server name:** self hosted
* **Server software:** prosody
* **Conversations source:** Play store

#### Steps to reproduce

1. attempt to connect to a server that requires TLS 1.2

#### Expected result

What is the expected output?
Online

#### Actual result

What do you see instead?
Stream error

**Comment by licaon-kter** [comment]
You can repro this with another server (not your own)?

**Comment by hotaru2k3** [comment]
I don't know of any other servers that require TLS 1.2. all of the public servers I've found support TLS 1.0.

**Comment by licaon-kter** [comment]
Look around the observatory, eg. https://check.messaging.one/result.php?domain=creep.im&type=client is what you want?

**Comment by hotaru2k3** [comment]
after registering an account on creep.im, it connected successfully to both creep.im and to my server with TLS 1.2. I'm no longer able to reproduce the issue with my server.

**Comment by licaon-kter** [comment]
So close this?
