### ISSUE TITLE
Cant dectrypt after reinstall

### ISSUE THREAD

**Issue by hubgitbb** [siacs/Conversations#3096]
#### General information

* **Version:** 2.2.3
* **Device:** Xperia Z
* **Android Version:** Android 6.0 
* **Server name:** self hosted
* **Server software:** prosody 
**Installed server modules:** MAM
* **Conversations source:** F-Droid,

#### Steps to reproduce

1. remove/deinstall app from my xperia z
2. install app again

#### Expected result

all omemo encrypted messages that have been send/receive should be decrypted and readable . 

#### Actual result
messages that were send/receive cant be read. placeholder messsage is: "the message was not encrypted for this device"

what can i do the get al messages decrypted.

**Comment by licaon-kter** [comment]
You can't, those were encrypted for that installation, when you've uninstalled (why?) you've destroyed that key.

It's how OMEMO works...

/Close as invalid

**Comment by hubgitbb** [comment]
i am also using gajim with the same user. can i export from gajim to get the messages back on the phone?

**Comment by licaon-kter** [comment]
No

**Comment by hubgitbb** [comment]
"those were encrypted for that installation" what exactly does that mean? do i need the fingerprint? what if i have the fingerprint? can i reuse it the decryt the messages ?

**Comment by licaon-kter** [comment]
No, that installation had the keys.

Messages are decrypted only once (you did that in the past already).
