### ISSUE TITLE
[Location] manual correcting of the location at Android<5

### ISSUE THREAD

**Issue by ildar** [siacs/Conversations#3097]
Location determined by system is not always correct. The one obvious example is a user in a building where GPS doesn't work. Then sent location is misleading. I suggest to allow user correct the location as it is done in Telegram and Hangouts.

**Comment by licaon-kter** [comment]
Touch the circle with the cross in the lower right side of the screen, *the dot inside will disappear*... Now move the map as you wish, send whatever location you want (location under the green sign)...

/close as invalid

**Comment by ildar** [comment]
emm, ?
![screenshot_2018-06-26-12-11-29](https://user-images.githubusercontent.com/517752/41892508-269821be-793a-11e8-9a39-c8727fc8196c.png)

**Comment by ildar** [comment]
version 2.2.3 (F-Droid)
Android 4.4 LA11 + GApps

**Comment by licaon-kter** [comment]
With the included maps or OpenSharePlugin? See app Settings...

**Comment by ildar** [comment]
I don't have any Conversation plugins and can't find anything related in
Settings. Further ideas?

**Comment by licaon-kter** [comment]
No idea then, maybe it's different on Android 4.4 🤷🤔

**Comment by ildar** [comment]
@iNPUTmice , devs, any advise then?

**Comment by zz-ha-dum** [comment]
Why not use GPS location spoofing in buildings with poor GNSS reception?

**Comment by ildar** [comment]
The issue appeared on 4.4 Android unable to change the location manually.
