### ISSUE TITLE
Conversation 2.2.4-pcr image delivery fail at 0% on Android 8.0.0 up

### ISSUE THREAD

**Issue by pommm** [siacs/Conversations#3099]
Hi,

We have noticed a problem sending images from Conversations that occurs only on users using Android 8.0.0 or higher. We are using a Prosody server (prosody-0.10-1nightly489-1~xenial) with XEP-0363 HTTP file upload module enabled, and the Conversations clients that have this problem allow the user to choose an image file to send but freezes at "0% uploaded", before failing with "delivery failed" a few minutes later. Checking the server logs suggests that the HTTP PUT does not occur for Android 8.0.0 and up.

We have also tested on Android 7.1.1 and 6.0.1 and image upload works fine.

Both the group of phones that can send images successfully and the ones that fail are using Conversations 2.2.4-pcr, so we are fairly confident the determining factor is actually how Conversations is interacting with the Android 8.0.0 and up.

Please let us know if we can help diagnose the issue in any other way.

Sincerely,

pommm

**Comment by iNPUTmice** [comment]
I’m not experiencing any issues on Android 8.0+ using a couple of the prosody servers I have access to. `adb logcat` might be a good start.

**Comment by pommm** [comment]
Thanks for the quick reply iNPUTmice. Sorry it took me a few days to set up the logcat session.


We set up Android Studio to emulate a Pixel XL with Android 8.0.0 and Android 7.1 in order to replicate the problem we are seeing on our phones. We were able to successfully replicate it on the emulated Android. We've gone ahead and produced a logcat of one session each to compare.

(Both sessions connect to the same Prosody server, but I've changed username to “myuser” and DNS domain name to “mydomain”, and IP address to XX.XX.XX.XX.)


Here is the logcat while trying to send image to a multi user chat from Emulator version 27.2.9-4773671 (KVM 12.0.0) running Android version 8.0.0 (Oreo) API 26 on Pixel XL API 26. This version fails to upload and times out, same as our phones on Android 8.0 and up.


The difference appears to be that Android 7.1 resolves the URL for the upload to the correct hostname https://proxy.mydomain.com:5281, while the Android 8.0 logcat shows it trying to upload to the wrong URL at  https://mydomain.com:5281. After trying to connect to the wrong hostname, it times out.


Since the difference is only the Android version, I'd be quite curious if anyone can offer any suggestions why Conversations attempts the image upload to a different server hostname. Since this issue only occurs for us on Conversations, and only on Android 8.0 and up, I'm starting out posting here. (Image uploads even work fine on ChatSecure on iOS.) But it also wouldn't surprise me if we've configured something wrong somewhere. So any suggestions where we might look next would be much appreciated.


`07-03 01:42:07.549 5803-5825/eu.siacs.conversations D/EGL_emulation: eglMakeCurrent: 0xa5094c20: ver 2 0 (tinfo 0xb1112270)
07-03 01:42:08.200 5803-5803/eu.siacs.conversations D/conversations: app switched into background
07-03 01:42:09.543 5803-5803/eu.siacs.conversations D/conversations: ConversationsActivity.onActivityResult() - attaching image to conversations. CHOOSE_IMAGE
07-03 01:42:09.570 5803-5803/eu.siacs.conversations D/conversations: myuser@mydomain.com: not compressing picture. sending as file
07-03 01:42:09.579 5803-5803/eu.siacs.conversations D/conversations: reInit(hasExtras=false)
07-03 01:42:09.585 5803-5852/eu.siacs.conversations D/conversations: send file message
07-03 01:42:09.595 5803-5803/eu.siacs.conversations D/conversations: scrolledToBottomAndNoPending=true
    jump to first unread message
07-03 01:42:09.602 5803-5803/eu.siacs.conversations D/conversations: received uri permission for content://com.android.providers.media.documents/document/image%3A45
07-03 01:42:09.625 5803-5894/eu.siacs.conversations D/conversations: uploading to https://mydomain.com:5281/upload/DBkpZNeA7Jj7sjV7/xlVJBF4HRd-Kuwbw_XgA4g.jpeg w/ read timeout of 115s
07-03 01:42:09.916 5803-5803/eu.siacs.conversations D/conversations: app switched into foreground
    ConversationFragment.onBackendConnected()
07-03 01:42:09.936 5803-5825/eu.siacs.conversations D/EGL_emulation: eglMakeCurrent: 0xa5094c20: ver 2 0 (tinfo 0xb1112270)
07-03 01:42:10.060 5803-5825/eu.siacs.conversations D/EGL_emulation: eglMakeCurrent: 0xa5094c20: ver 2 0 (tinfo 0xb1112270)
07-03 01:42:10.125 5803-5825/eu.siacs.conversations D/EGL_emulation: eglMakeCurrent: 0xa5094c20: ver 2 0 (tinfo 0xb1112270)
07-03 01:42:10.162 5803-5825/eu.siacs.conversations D/EGL_emulation: eglMakeCurrent: 0xa5094c20: ver 2 0 (tinfo 0xb1112270)
07-03 01:43:09.690 5803-5894/eu.siacs.conversations W/System.err: java.net.SocketTimeoutException: failed to connect to mydomain.com/XX.XX.XX.XX (port 5281) from /192.168.232.2 (port 54668) after 15000ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
        at libcore.io.IoBridge.connect(IoBridge.java:130)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
07-03 01:43:09.691 5803-5894/eu.siacs.conversations W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
        at java.net.Socket.connect(Socket.java:616)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
07-03 01:43:09.692 5803-5894/eu.siacs.conversations W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
07-03 01:43:09.693 5803-5894/eu.siacs.conversations W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
        at eu.siacs.conversations.http.HttpUploadConnection.upload(HttpUploadConnection.java:191)
        at eu.siacs.conversations.http.HttpUploadConnection.access$300(HttpUploadConnection.java:32)
        at eu.siacs.conversations.http.HttpUploadConnection$1.lambda$success$0$HttpUploadConnection$1(HttpUploadConnection.java:148)
        at eu.siacs.conversations.http.HttpUploadConnection$1$$Lambda$0.run(Unknown Source:18)
        at java.lang.Thread.run(Thread.java:764)
07-03 01:43:09.693 5803-5894/eu.siacs.conversations D/conversations: http upload failed failed to connect to mydomain.com/XX.XX.XX.XX (port 5281) from /192.168.232.2 (port 54668) after 15000ms
`

Here is a logcat from Emulator version 27.2.9-4773671 running Android version 7.1 (Nougat) API 25 on Pixel 2 XL API 25. This version uploads successfully, same as our phones running 7.1.

`07-03 01:57:19.186 2632-2632/eu.siacs.conversations W/IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
07-03 01:57:19.283 2632-2960/eu.siacs.conversations D/EGL_emulation: eglMakeCurrent: 0x9f5051e0: ver 2 0 (tinfo 0x9f5036f0)
07-03 01:57:19.342 2632-2632/eu.siacs.conversations W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
07-03 01:57:19.693 2632-2632/eu.siacs.conversations D/conversations: app switched into background
07-03 01:57:22.475 2632-2632/eu.siacs.conversations D/conversations: ConversationsActivity.onActivityResult() - attaching image to conversations. CHOOSE_IMAGE
07-03 01:57:22.526 2632-2632/eu.siacs.conversations D/conversations: myuser@mydomain.com: not compressing picture. sending as file
07-03 01:57:22.533 2632-2632/eu.siacs.conversations D/conversations: reInit(hasExtras=false)
07-03 01:57:22.540 2632-3923/eu.siacs.conversations D/conversations: send file message
07-03 01:57:22.576 2632-3967/eu.siacs.conversations D/conversations: uploading to https://proxy.mydomain.com:5281/upload/5wwubmPIL1BKvdQE/hx6gWSuPSf2Rfx7-Z9Mc3w.jpeg w/ read timeout of 115s
07-03 01:57:22.873 2632-2632/eu.siacs.conversations D/conversations: scrolledToBottomAndNoPending=true
    jump to first unread message
07-03 01:57:22.905 2632-2632/eu.siacs.conversations D/conversations: received uri permission for content://com.android.providers.media.documents/document/image%3A85
07-03 01:57:23.456 2632-2632/eu.siacs.conversations D/conversations: app switched into foreground
    ConversationFragment.onBackendConnected()
07-03 01:57:23.458 2632-2632/eu.siacs.conversations I/Choreographer: Skipped 32 frames!  The application may be doing too much work on its main thread.
07-03 01:57:23.468 2632-2960/eu.siacs.conversations D/EGL_emulation: eglMakeCurrent: 0x9f5051e0: ver 2 0 (tinfo 0x9f5036f0)
07-03 01:57:23.636 2632-2960/eu.siacs.conversations D/EGL_emulation: eglMakeCurrent: 0x9f5051e0: ver 2 0 (tinfo 0x9f5036f0)
07-03 01:57:23.792 2632-2960/eu.siacs.conversations D/EGL_emulation: eglMakeCurrent: 0x9f5051e0: ver 2 0 (tinfo 0x9f5036f0)
07-03 01:57:23.814 2632-3967/eu.siacs.conversations D/conversations: finished uploading file
07-03 01:57:23.848 2632-2960/eu.siacs.conversations D/EGL_emulation: eglMakeCurrent: 0x9f5051e0: ver 2 0 (tinfo 0x9f5036f0)
`

Sincerely, 

Pommm

**Comment by pommm** [comment]
fixed by add http_upload module to conference section

```
Component "conference.mydomain.com" "muc"
        modules_enabled = {
                "muc_log";
                "muc_config_restrict";
                "http_upload";
                }
```

I'm confusing that this just works because the global modules already have "http_upload" enabled and it works fine on Android 7 and lower with out enabled it in conference section.
