### ISSUE TITLE
long reconnection delay (upto one minute) or even no reconnection when using ETHERNET (with USB-LAN-adapter)

### ISSUE THREAD

**Issue by toxtox** [siacs/Conversations#3102]
#### General information

* **Version:** 2.2.3
* **Device:** 1.) Motorola XT894 | 2. Huawei honor BND-AL10
* **Android Version:** 1.) LineageOS14.1 | 2.) stock ROM Android 7.0
* **Server name:** self hosted
* **Server software:** ejabberd 18.03-2
* **Installed server modules:** all modules listed in conversation's "_Account details_" except XEP-0313 MAM
* **Conversations source:** F-Droid

Both devices: 
Conversations->Settings->Expert->Foreground service is **ON**
Android->Settings->Battery->Conversations is "**not optimize**"
_Background data_ is enabled
_unrestricted data usage_ is enabled

#### Steps to reproduce

When using mobile data (cellular data) or wifi the reconnection delay is very short after enabling mobile data or wifi  (maybe 1 or 2 seconds for turning from "_Network is unreachable_" to "_Online_"). 

BUT when you use ETHERNET (USB-LAN-adapter with "_Asix_" chipset "_AX88772B_") the reconnection delay is long or fails completely
1. Motorola XT894
**without** https://github.com/lemonsqueeze/fakewificonnection you get **_"No connectivity"_**
**with** https://github.com/lemonsqueeze/fakewificonnection it shows "_**Connecting...**_" up to 1 Minute before it shows "**_Online_**" [this works even in background but **_Fake Wifi Connection_** requires root :-( ]
My experience is that round about 50% of all apps need **_Fake Wifi Connection_** for getting internet access via ethernet. (for example: **_fennec_** and _**K-9-Mail**_ do not need **_Fake Wifi Connection_** but "**_Forecastie_**" and the "**_F-Droid_**" app need **_Fake Wifi Connection_**.
=> Better ETHERNET (LAN) compatibility should be possible for **_Conversations_**.

2. Huawei honor BND-AL10
This device does not need **_Fake Wifi Connection_**. All apps including _conversations_ can access internet via ethernet BUT it **never reconnects** in background even if you enable _conversation's_ "_Foreground service_". Only if you really open conversations, conversations reconnects after a delay of up to 1 Minute.

#### Expected result

_Conversations_ should have the same reconnection behavior independent on the kind of internet connection (ethernet should run as good as mobile data or wifi [short reconnection delays and reliable reconnection])

#### Actual result

Long reconnection delays on both devices and failing reconnection on Huawei honor BND-AL10

**Comment by licaon-kter** [comment]
The Huawei situation is kinda normal, unfortunately, don't swipe the app, in task manager press the titlebar lock.

For the other, Conversations depends on what Android says...connected or not....grab some logs via adb.

**Comment by toxtox** [comment]
Thanks for your fast reply.
### 2. Huawei honor BND-AL10 + ethernet:
But I am not sure what you mean with "_task manager_" and "_**titlebar lock**_" ? Maybe you could post a screenshot of this setting?
I looked around for a similar named setting and played around with notification settings. Maybe this had an effect. Now I see in ejabberd Web Admin that conversations is online after some minutes. But this test was made with screen on and conversation app not displayed on screen (but with "_Foreground service_"). I have not seen that conversation connects when screen is off yet.

### 1. Motorola XT894 + ethernet:
> For the other, Conversations depends on what Android says...connected or not....

But I guess _Conversation_ only checks if wifi or mobile data is available and then the connection process is triggered. Obviously conversation does not check if ethernet is available or Android does not say that it is available without a request because there are some apps that run with ethernet out of the box (**_fennec_** and _**K9-Mail**_ and some more).

**Comment by licaon-kter** [comment]
> played around with notification settings
Hope you did not disable anything...

> But I am not sure what you mean with "task manager" and "titlebar lock" ? 
Eg. https://club.hihonor.com/data/images/2017/2/17/f677fb4de2fccc518b820f941c028d52.png

> But this test was made with screen on and conversation app not displayed on screen 
Use ADB to see the logcat going, turn off the screen, wait 2 minutes, send message to the device....look at the log...app from F-Droid means it will auto-check  every 300seconds (at worse)

> But I guess Conversation only checks...
No, it waits for Android to say that it is connected...
Again, adb, logcat, turn ethernet on and off...se what happens...

**Comment by toxtox** [comment]
### 1. Motorola XT894 + ethernet:
I made the following test without the _**"Fake Wifi Connection"**_ app (log is filtered for "_conversations_" entries):

1. starting conversations with all accounts disabled:
[logcat_07-03-2018_21-47-15_starting_conversations_with_all_accounts_disabled.txt](https://github.com/siacs/Conversations/files/2160867/logcat_07-03-2018_21-47-15_starting_conversations_with_all_accounts_disabled.txt)

2. switching on my account (it displays:_"No connectivity"_)
[logcat_07-03-2018_21-51-10_switching_on_the_account.txt](https://github.com/siacs/Conversations/files/2160921/logcat_07-03-2018_21-51-10_switching_on_the_account.txt)

3. switching off my account (it displays:_"No connectivity"_)
[logcat_07-03-2018_21-57-53_switching_off_the_account_b.txt](https://github.com/siacs/Conversations/files/2160935/logcat_07-03-2018_21-57-53_switching_off_the_account_b.txt)

I cannot see any errors but nevertheless _Conversations_ does not work without the _**"Fake Wifi Connection"**_-app.

**Comment by iNPUTmice** [comment]
I think using 'fake wifi connection' is an appropriate work around for a bug in the operating system. I don’t think it is desirable for Conversations to attempt to connect if the operating system reports that there is no internet connectivity.
