### ISSUE TITLE
[Feature Request] Refuse Avatar Pictures

### ISSUE THREAD

**Issue by SimonMaenaut** [siacs/Conversations#3103]
In order to reduce network traffic and for general esthetics it would be nice to have an option to refuse all Avatar Pictures and revert to the default letters in Conversations.

**Comment by iNPUTmice** [comment]
If you enable the data saver an make an exception for Conversations it won’t download avatars. However for the general user I think it is desirable to keep avatars.

**Comment by SimonMaenaut** [comment]
Thanks!
