### ISSUE TITLE
Adding New Feature in Conversation- Self Destructable Message

### ISSUE THREAD

**Issue by johnnyAnd** [siacs/Conversations#3104]
I am in process of adding a new feature for conversation tgat is ability for self destructable message
I was going through old issues posted here @inputMice doesn’t seem to incorporate it

Anyways coming back to my question
As a starting point i want to send an additional parameter with a message. How can I do that in code, exactly which file.
Any help in this regard us appreciated

**Comment by johnnyAnd** [comment]
Also, once I complete this. Can I add this feature here?
Thanks

**Comment by johnnyAnd** [comment]
@licaon-kter yes I believe.

But I want to add it to repository as an add-on.
Need your assistance in this regard to find the code.

**Comment by licaon-kter** [comment]
Yes what? Which one? 

And again, how do you protect yourself if I run my own build that was programmed to **not** destroy any message?

**Comment by johnnyAnd** [comment]
@licaon-kter I would like to send an additional parameter with my message. For example if I am sending Hello message , it must have additional attributes with it like encryption type, language code etc etc

I would like to send an additional parameter with my message

And again, how do you protect yourself if I run my own build that was programmed to not destroy any message?

Regarding this, this may only work if both clients are using conversation.In case user tries to send message to a user who is not using conversation, it will notify him that recipient is using a different variant.

**Comment by myluckyapps** [comment]
I have earlier passed new variable "Gift" using below files, you explore these files for more.

```
1) Message.java - pass new flag in constructor( also IndividualMessage.java to pass same flag)
2) MessageGenerator.java  - set this flag, i.e if(message.isGift()) packet.setAsGift();
3) MessagePacket.java - to have new method

+    public void setAsGift(){
+        addChild(MessageWrapper.GIFT);
+    }
3) MessageParser.java - extract field final Element gift = packet.findChild(MessageWrapper.GIFT); (around onMessagePacketReceived)
4) DatabaseBackend.java - for persistence: 

+        if (oldVersion < 44 && newVersion >= 44) {
+            db.execSQL("ALTER TABLE " + Message.TABLENAME + " ADD COLUMN " + Message.IS_GIFT + " BOOLEAN DEFAULT 0");
+            db.execSQL("ALTER TABLE " + Message.TABLENAME + " ADD COLUMN " + Message.GIFT_READ + " BOOLEAN DEFAULT 0");
+        }

5) ConversationFragment.java - main conversations layout for UI
```

**Comment by licaon-kter** [comment]
@myluckyapps https://conversations.im/j/conversations@conference.siacs.eu

**Comment by johnnyAnd** [comment]
@myluckyapps Can i get your email address please

**Comment by iNPUTmice** [comment]
There are currently no plans to implement this

**Comment by myluckyapps** [comment]
@johnnyAnd, sorry I missed your message, my email is ramesh.jangama@gmail.com. If you really serious to implement self destruct messages, I can help you to provide demo code changes which passes special flag in XML to other users and how other user app read this flag to permform any action.  If you really want it then I will create PR which demonstrate this for education purpose. Let me try over this weekend.

**Comment by licaon-kter** [comment]
I heard WA has them, maybe: https://github.com/4nubhav/WhatsDeleted
