### ISSUE TITLE
Reminder

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [siacs/Conversations#3106]
Did you see MattJ's answer here: https://issues.prosody.im/1129#comment-12

**Comment by licaon-kter** [comment]
Did you see this commit: https://github.com/siacs/Conversations/commit/48e366e4108cf509631f753dc3d16ab0ab483276 ?

**Comment by tmolitor-stud-tu** [comment]
@licaon-kter oh nice, thank you!
I'll close this one then
