### ISSUE TITLE
Make read markers in public MUC

### ISSUE THREAD

**Issue by meaz** [siacs/Conversations#3107]
#### General information

* **Version:** 2.2.5
* **Server name:** self hosted
* **Server software:** prosody trunk
* **Installed server modules:** Many... not relevant here I guess
* **Conversations source:**  F-Droid

#### Steps to reproduce
1- Have a conference (MUC) with more than 5 users in a public MUC
2- Send a message

#### Expected result
See who read the message

#### Actual result
It is not possible to know who read my message in a public MUC, only in a private one.

#### Objective of this enhancement?
This could be useful on public rooms too. For example I have a public room, where we discuss a project. I would like to see who read the messages (for example when having a meeting) but dont want to necessary have the room private as I dont mind people joining in.

**Comment by iNPUTmice** [comment]
This would be way too noisy for large public groups. The only option would be to limit this to a maximum number of participants but that seems even more intransparent then the way it current is.
