### ISSUE TITLE
MUC Subject from server is dropped when language does not match

### ISSUE THREAD

**Issue by g0ldstrike** [siacs/Conversations#3108]
#### General information

* **Version:** 2.2.5
* **Device:** Google Nexus 5
* **Android Version:** Android 8.0
* **Server name:** ejabberd
* **Server software:** ejabberd 17.04
* **Installed server modules:** MAM
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Create a MUC and set its subject on a device on which Android is set to language X.
2. Another user in the same MUC with Android set to language Y will not see the subject.

#### Expected result

If the subject is not available in language Y, the subject should still be shown.

#### Actual result

No subject is shown.

#### Reason

MessageParser.onMessagePacketReceived() calls Element.findInternationalizedChildContent("subject"). This method ONLY returns the received subject if language equals client's device setting, and otherwise null.

**Comment by licaon-kter** [comment]
Are you sure the other contact has Conversations 2.2.5?

**Comment by iNPUTmice** [comment]
The stream language is set to en. So the subject you are posting always
gets published in en not your device language. When receiving the subject
it will fall back to the one without language attribute meaning the one in
en.

Please provide the subject stanza on the receiving end and what server you
use
