### ISSUE TITLE
[Suggest for an update] Xep 0045 : destroying room

### ISSUE THREAD

**Issue by electro575** [siacs/Conversations#3112]
#### General information

* **Version:** trunk
* **Server software:** prosody
* **Installed server modules:** MAM, MAM-MUC
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Destroy a room of a muc since conversations app
2. Sync this with prosody server 

#### Expected result

Send information about destroying room

#### Actual result

All customers again have the room in spite of destroying by admin.

Thanks a lot.

Have a nice Day

**Comment by iNPUTmice** [comment]
This is implemented in 2.3.11

**Comment by electro575** [comment]
Nice.

Thank's a lot
