### ISSUE TITLE
request: disable grace period

### ISSUE THREAD

**Issue by jacob019** [siacs/Conversations#3114]
I want to hear the notification sound every time I receive a message, regardless of what I am doing on other clients.  Currently the options for grace period are short, medium, long.  Can an option be added to disable this feature?

**Comment by licaon-kter** [comment]
How long is short?

**Comment by jacob019** [comment]
short = 144 seconds
medium = 610 seconds
long = 2584 seconds

**Comment by iNPUTmice** [comment]
fixed in master
