### ISSUE TITLE
Daily prompt on confirming that server admin is a member of OMEMO MUC

### ISSUE THREAD

**Issue by Mikaela** [siacs/Conversations#3118]
#### General information

* **Version:** 2.27+pcr
* **Device:** OnePlus 3
* **Android Version:** 8.0.0 (1 June 2018, OP3_O2_BETA_39)
* **Server name:** blesmrt.net
* **Server software:** Prosody
* **Installed server modules:** everything available according to Conversations
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. Create a MUC (on Prosody).
2. Invite server admin.
3. Send a OMEMO encrypted message.
4. Verify keys or confirm that the server admin is a member of the room.

#### Expected result

I won't see 4. again.

#### Actual result

I am prompted to confirm that the server admin is a room member at least once a day if not more often when I send a message to the MUC.

In the Conversations MUC I understood that this is possibly a Conversations bug caused by a Prosody bug.

#### Debug output

N/A, unavailable (broken port allowing charging, but not adb?)

**Comment by iNPUTmice** [comment]
I guess at this point the only good answer to that is don’t use your admin account as your regular xmpp account.

**Comment by Mikaela** [comment]
And when the Conversations users isn't an admin?
