### ISSUE TITLE
Update "account details > server info" screen to match conversations.im/compliance

### ISSUE THREAD

**Issue by axelsimon** [siacs/Conversations#3119]
The list of XEP supported by a server (shown by going into account details, overflow menu, server info)
isn't as complete as the one on https://conversations.im/compliance/.
It would be nice to have it check for the same things :)

#### Relevant information
* **Version:** 2.2.5+fcr
* **Server software:** prosody 0.10.2-1
* **Conversations source:** F-Droid

#### Steps to reproduce
1. Go into account details, overflow menu, server info
2. The account details expand, showing you what XEPs the server supports

#### Expected result
The list of supported XEP is complete and matches https://conversations.im/compliance/

**Comment by iNPUTmice** [comment]
The server info is not trying to replace the compliance tester. The server info will only show the most important information.
