### ISSUE TITLE
Feature Request: TLS 1.3 Support

### ISSUE THREAD

**Issue by max421** [siacs/Conversations#3120]
Hi,

i have a simple question. I don't whether you heard from it but a few months ago the new TLS 1.3 standard is ready. And for example Chrome, Firefox have already support for it. 

I switched the XMPP server and the new server which i use now supports TLS 1.3, too.
So my question is the following: Does Conversations support it? And if not can you add this feature? It would be ok for me to take this in the expert section in the settings but i would be happy see this because TLS 1.3 seems to bring a lot of improvements in comparision to TLS 1.2. 
And in generell i think it would a nice feature for experienced user when he could choose which TLS version the app uses.

Thx in advance for a reply/replies

**Comment by iNPUTmice** [comment]
Conversations uses the TLS implementation by the operating system. It will be supported if your operating system does support it. Which is no Android version for now. Not sure if P will support it. Probbaly not.
