### ISSUE TITLE
Message preview: styling using code blocks

### ISSUE THREAD

**Issue by msantos** [siacs/Conversations#3124]
#### General information

* **Version:** 2.2.7+pcr
* **Device:** Google Pixel
* **Android Version:** Android 8.1.0
* **Conversations source:** PlayStore

#### Steps to reproduce

Similar to https://github.com/siacs/Conversations/issues/2705:

1. Send a message fenced with code blocks:

~~~
```
Line one
Line two
```
~~~

#### Expected result

Display the first line of the message:

~~~
Line one
~~~

#### Actual result

Only the code block delimiter is displayed in message previews and notifications:
~~~
```
~~~

**Comment by licaon-kter** [comment]
That's technically the first line....not sure if this is a bug really. Yes, in this case it would be useful to see the first line of text in the block.
