### ISSUE TITLE
Duplicate incoming messages on desktop side if contact is not in roster

### ISSUE THREAD

**Issue by dartraiden** [siacs/Conversations#3126]
Test case:
- smartphone with Conversations
- PC with Gajim or Miranda NG (both support Message Carbons)

Incoming messages are doubled on desktop side _if contact not in roster_. For example, someone trying to send message to me from MUC private. If smartphone is off, all OK.

Attached logs from Miranda (network log and XML console dump). In this case, I just write "test" to bot and receive 2x answer "passed"

[xml-miranda.txt](https://github.com/siacs/Conversations/files/2223252/xml-miranda.txt)

[netlog-miranda.txt](https://github.com/siacs/Conversations/files/2223253/netlog-miranda.txt)

**Comment by iNPUTmice** [comment]
Not a Conversations bug. One client can influence what carbon copies are received on another client.
