### ISSUE TITLE
Autocyrp?

### ISSUE THREAD

**Issue by thomaspeterthiede** [siacs/Conversations#3131]
Hello,

its a little be complicated to use omemo in muc.
it ist possible to implement autocrypt?

greetings

**Comment by licaon-kter** [comment]
Is Autocrypt easier for a MUC?

What issue do you have with OMEMO in a MUC?

Please correct title.

**Comment by thomaspeterthiede** [comment]
Omemo doenst work so easy in muc, because of the keys.
in delta chat autocrypt is working so easy in muc

**Comment by licaon-kter** [comment]
"because of the keys" mean what? The fact you need to have that contact online when you add them?

**Comment by thomaspeterthiede** [comment]
problems to get the keys. every contact in the group hast to scan the qr code from everybody< otherwise omemo is not working in muc

**Comment by licaon-kter** [comment]
Umm no, you scan to verify (shield in fingerprint), but you don't need that.

You start a MUC and start to invite people, a good server (ejabberd 18.03+ or prosody 0.10+omemo_access) will just allow you to add contacts without them needing to scan or even add eachother.

What server did you use?

/PS: please edit typo in title

**Comment by thomaspeterthiede** [comment]
hello, i use prosody in the newest version.
the contacts are from different servers. perhaps this is the problem?

**Comment by licaon-kter** [comment]
With "omemo_all_access" enabled it should work.

**Comment by thomaspeterthiede** [comment]
thank you, but it is on

**Comment by licaon-kter** [comment]
They all use OMEMO enabled clients, right?

**Comment by thomaspeterthiede** [comment]
yes, but on diffetent servets, so that can be the problem when on the other server omemo_all_access isnt enabled. i dont know

**Comment by licaon-kter** [comment]
Not as far as I know, the server where the MUC is created matters.

**Comment by zz-ha-dum** [comment]
autocrypt might be an interesting plugin to bridge email for those servers where one URI functions as both email and JID (and even SIP)
