### ISSUE TITLE
allow to select multiple files/videos for sending (like pictures)

### ISSUE THREAD

**Issue by toxtox** [siacs/Conversations#3132]
#### General information

* **Version:** 2.2.8+fcr
* **Device:** XT894 (independend on device)
* **Android Version:** LOS14.1
* **Server name:** self hosted
* **Server software:** ejabberd 18.03-2
* **Installed server modules:** all modules listed in conversation's "Account details" except XEP-0313 MAM
* **Conversations source:** F-Droid

#### Steps to reproduce

I can select a (video)-file but when I want to select a second (video)-file for sending the first selected (video)-file is deselected

#### Expected result

Multiple (video)-files should be selectable the same way like picture-files.

#### Actual result

You can select and send video files only one by one.

#### Debug output
not needed

````
adb logcat -s conversations
````

**Comment by licaon-kter** [comment]
See #1047 as an included gallery will do that

In the meantime use your device gallery or a file manager to "Share to..." Conversations

/Close this

**Comment by toxtox** [comment]
> See #1047 as an included gallery will do that

Good to know that this is being in development.

> In the meantime use your device gallery or a file manager to "Share to..." Conversations

I tested the standard file manager, "Amaze" file manager and the gallery but "Share to..." Conversations is only possible if I select only **one** video file.
