### ISSUE TITLE
Pictures taken by Conversations are stored on internal storage, camera is configured for SD card

### ISSUE THREAD

**Issue by Edcrfv248** [siacs/Conversations#3135]
#### General information

* **Version:** 2.2.28+fcr
* **Device:** Samsung Galaxy S5 Neo (SM-G903F)
* **Android Version:** Android 6.0.1 Stock
* **Server name:** jabber.ccc.de
* **Server software:** unkown
* **Installed server modules:** unknown
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Take picture directly from Conversations
2. Picture is stored in [InternalStorage]\DCIM\Camera
3. Picture taken by normal camera app is stored in [extsdcard]\DCIM\Camera

#### Expected result

Pictures taken from Conversations should be stored in same folder as camera app

#### Actual result

Pictures are stored on internal storage, camera is configured for extsdcard

---

Thank you very much for this great piece of software :)

Kind regards
Steve

**Comment by licaon-kter** [comment]
> Picture is stored in \DCIM\Camera
> Picture taken by normal camera app is stored in \DCIM\Camera

Umm, edit this ^^^^^^^^^

**Comment by Edcrfv248** [comment]
square brackets are better than greater/less signs ;)

**Comment by licaon-kter** [comment]
eh Markdown flavour of the month...

**Comment by eku** [comment]
> Pictures taken from Conversations should be stored in same folder as camera app

Well, it depends. I would expect that pictures are not stored in public but app private folder.

**Comment by licaon-kter** [comment]
@eku Media is not stored stored in the app private folder but in `/sdcard/Conversations/` anyway. You want Conversations to delete the picture from `<>/Camera/` ? I'm not sure that's what the user expects.

**Comment by eku** [comment]
@licaon-kter I don't want other Apps to access pictures only taken for/within Conversations. That's my understanding of privacy. Conversations should implement privacy by default (GDPR).

**Comment by licaon-kter** [comment]
I understand, but why do you use apps that you don't trust, apps that scan and access your sdcard?

**Comment by licaon-kter** [comment]
I understand.

How de I share a file from Conversations then?

**Comment by ChaosKid42** [comment]
@licaon-kter Long press on image, share with?

**Comment by licaon-kter** [comment]
Wait....see, I got an image on my old account about a year ago, it was in a MUC that we closed, that account was disabled for a while and now deleted.

Ok, long press where exactly?

**Comment by iNPUTmice** [comment]
The camera app can not be told to use its default storage location.
