### ISSUE TITLE
Does the F-Droid version support XEP-0357 Push Notifications via GCM or Firebase?

### ISSUE THREAD

**Issue by devurandom** [siacs/Conversations#3141]
Does the F-Droid version support XEP-0357 Push Notifications via GCM or Firebase? I am unsure, because in the description it says "Do not require a Google Account or specifically Google Cloud Messaging (GCM)". Does it not require a Google account, but can optionally use one if available, or does it not support GCM / Firebase at all?

**Comment by iNPUTmice** [comment]
The F-Droid version does not support pushing over FCM

**Comment by baimafeima** [comment]
@iNPUTmice Seems like it's not updated here: https://f-droid.org/en/packages/eu.siacs.conversations/
Just to be sure, is there any push notification for Conversation users who have installed via F-Droid? What about the solution via SSE as Tutanota has done? See: https://f-droid.org/en/2018/09/03/replacing-gcm-in-tutanota.html

**Comment by licaon-kter** [comment]
@baimafeima there's no mention of PUSH on F-Droid, not sure what you mean.

No alternatives (as Tutanota) implemented either.

Also, did you use it? Did you have issues with the F-Droid version? What device? What Android version?

**Comment by iNPUTmice** [comment]
> No alternatives (as Tutanota) implemented either.

Well XMPP is the alternative. XMPP is a push protocol. You don’t need another push protocol to wake up what’s already a push protocol.

@baimafeima read https://gultsch.de/xmpp_2016.html

**Comment by baimafeima** [comment]
@licaon-kter @iNPUTmice Thanks for the updates and the link! That's what I wanted to know.
