### ISSUE TITLE
"Grace Period": None

### ISSUE THREAD

**Issue by luke-jr** [siacs/Conversations#3143]
My desktop XMPP client doesn't tell me at all when I get messages, so I like to use Conversations for notifications even for conversations I am actively responding to at my PC. Can a "None" option be added to the "Grace Period" settings?

**Comment by luke-jr** [comment]
Psi, running on hardware without any audio output. Why add audio output, when my phone is right there?

**Comment by vanitasvitae** [comment]
There is #3116, which does exactly this.

**Comment by iNPUTmice** [comment]
fixed in master
