### ISSUE TITLE
Unhelpful error message when attempting to highlight offline member of MUC

### ISSUE THREAD

**Issue by contrapunctus-1** [siacs/Conversations#3144]
If a user is offline and one tries to highlight them by tapping their avatar or tapping on their entry in the member list, Conversations says `"<user> has left the group chat"`, which is inaccurate and unhelpful.

A message like `"<user> is offline"` would be better, but going by Conversations' philosophy of "you don't need to know if someone is offline, and if what you actually want to know is whether your message is being read, we have chat states for that", perhaps doing away with the error entirely would be even better.

**Comment by licaon-kter** [comment]
Maybe the user really left the group for good...what then? 

I find the message ok, you get notified that the user that was previously here....is not here anymore...

**Comment by contrapunctus-1** [comment]
It's okay, but only for that case. Far, far more often I run into the opposite situation - user is simply offline, but the error makes you think they've left the group for good.

**Comment by meaz** [comment]
I agree with contrapunctus-1 that `"<user> has left the group chat"` can be misunderstood as someone that will not be able to read the message anymore. I find `"<user> is offline"` clearer too.
