### ISSUE TITLE
Video file shared more than once with a contact

### ISSUE THREAD

**Issue by srgcdev** [siacs/Conversations#3145]
#### General information

* **Version:** 2.2.8-fcr
* **Device:** Nexus 5X
* **Android Version:** Android 8 LineageOS
* **Server name:** self hosted ejabberd
* **Server software:** ejabberd 18.06
* **Installed server modules:** Stream Managment, CSI, MAM, httpUpload...
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Select a video file and share it
2. Select the contact yout wnat to share the video file
3. A notification appears on the screen saying that the video is being compressed
4. Select the contact again a few times while the file is being compressed

#### Expected result

What is the expected output? 
I expect the video file is shared only once

#### Actual result

What do you see instead?
The video file is shared two o three times with the contact

**Comment by iNPUTmice** [comment]
This issue has been fixed in 2.3.0
