### ISSUE TITLE
Show Crypto button with Lock icon

### ISSUE THREAD

**Issue by genofire** [siacs/Conversations#3146]
#### General information

* **Version:** 2.2.8+fcr
* **Android Version:** Android 8.1 (LinageOS 15.1)
* **Conversations source:**  F-Droid

#### Steps to reproduce

1. Go Android Settings
2. Set Display Size to 'Small' or 'Smallest'

#### Expected result

Lock/Crypto button always visible

#### Actual result

Button disappear (is only visible for less than a second):

![conversations-bug](https://user-images.githubusercontent.com/6905586/44255260-b92bed00-a205-11e8-9b7a-660655ff1ee6.jpg)

https://chat.sum7.eu/upload/4b2ab8b47d9551a701a91aa9e52f815cb7ff4a7b/d77DMHkIbvIE53hj0usSVnfoV6uRfh1R07iP90qy/2018_08_17_09_43_02.mp4

**Comment by SoyaLeaf** [comment]
Hi, is the upload file button always there?
I haven't seen this button for a long time, but I thought it was closed by the owner... =_=

![qq 20180817162143](https://user-images.githubusercontent.com/20620071/44255882-0c1f9780-a23a-11e8-8553-dd878c2c0274.png)

**Comment by iNPUTmice** [comment]
Whats your Privacy / OMEMO setting?

**Comment by genofire** [comment]
Oh it switch to always on - i have set it to 'On by Default' and it was overwritten on a update

**Comment by licaon-kter** [comment]
@genofire Didn't I tell you the same thing in the MUC?

Afaik, no update changed that to Always, it was user action,

**Comment by genofire** [comment]
@licaon-kter sry, i have not take it serious at muc - becouse i have send to a irc transport already not crypted messages.

Why it change to `Always` again - no idea.
