### ISSUE TITLE
allow message correction in group chat

### ISSUE THREAD

**Issue by luweitest** [siacs/Conversations#3150]
#### General information

* **Version:** Conversations 2.2.8+fcr
* **Device:** Xiaomi 5
* **Android Version:** Android 8
* **Server name:** conversations.im
* **Server software:** (unknown)
* **Installed server modules:** (unknown)
* **Conversations source:** F-Droid

#### Steps to reproduce

1. …Join a group chat like xmpp:conversations@conference.siacs.eu
2. …Make a message contains a typo
3. Long press the message.

#### Expected result

"correct message" option should be shown as in private chat.

#### Actual result

No "correct message" option.

**Comment by iNPUTmice** [comment]
This has been implemented in 2.3.0
