### ISSUE TITLE
gradlew compile error: /gradlew assembleDebug  > Task :compilePlaystoreCompatDebugJavaWithJavac  /root/Conversations-master/src/playstore/java/eu/siacs/conversations/services/PushManagementService.java:32: error: cannot find symbol                         final Jid appServer = Jid.of(mXmppConnectionService.getString(R.string.app_server));                         

### ISSUE THREAD

**Issue by compevo** [siacs/Conversations#3153]
#### General information

* **Version:** eg 1.21.0
* **Device:** eg Google Nexus 5
* **Android Version:** eg Android 6.0 Stock or Android 5.1 Cyanogenmod
* **Server name:** eg conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce
./gradlew

/gradlew assembleDebug

> Task :compilePlaystoreCompatDebugJavaWithJavac 
/root/Conversations-master/src/playstore/java/eu/siacs/conversations/services/PushManagementService.java:32: error: cannot find symbol
                        final Jid appServer = Jid.of(mXmppConnectionService.getString(R.string.app_server));
                                                                                              ^

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
The readme has instructions on how to compile the free flavor

**Comment by tbaro** [comment]
I have the same issue as compevo. The readme says:

git clone https://github.com/siacs/Conversations.git
cd Conversations
./gradlew assembleFreeSystemDebug

But using Android Studio IDE I want to debug the application running on the device. To do that I need to debug Conversations in thye IDE and select Conversations as the build. When I try to debug from the IDE, the build fails:

(*) - details omitted (listed previously)

Circular dependency between the following tasks:
:checkManifestChangesFreeCompatDebug
\--- :instantRunMainApkResourcesFreeCompatDebug
     \--- :transformClassesAndDexWithShrinkResForFreeCompatDebug
          \--- :transformDexArchiveWithDexMergerForFreeCompatDebug
               +--- :preColdswapFreeCompatDebug
               |    \--- :incrementalFreeCompatDebugTasks
               |         +--- :transformClassesAndClassesEnhancedWithInstantReloadDexForFreeCompatDebug
               |         |    \--- :transformClassesWithInstantRunForFreeCompatDebug
               |         |         \--- :checkManifestChangesFreeCompatDebug (*)
               |         \--- :transformClassesWithInstantRunForFreeCompatDebug (*)
               \--- :transformClassesWithDexBuilderForFreeCompatDebug
                    +--- :preColdswapFreeCompatDebug (*)
                    \--- :transformClassesWithInstantRunForFreeCompatDebug (*)

(*) - details omitted (listed previously)

So how to debug from the IDE? The README has very little information.
