### ISSUE TITLE
Feature request: option to ask before sending/compressing

### ISSUE THREAD

**Issue by Mikaela** [siacs/Conversations#3156]
#### General information

* **Version:** 2.2.9+pcr
* **Device:** OnePlus 3
* **Android Version:** Android 8.0.0 / OP3_O2_BETA_39
* **Server name:** blesmrt.net
* **Server software:** Prosody unknown
* **Installed server modules:** everything "available"
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. Send a image
2. The image gets compressed without me being tomd original size or asked about it and I can only select in settings to either compress always/never/automatically.

#### Expected result

What is the expected output? 

I have option to always ask me whether I want to compress or not and get told the file size, so I could easily send expanded screenshots uncompressed and compress photos not requiring quality. This is how Riot.im app handles this.

#### Actual result

What do you see instead?

When I send extended screenshot, the image gets compressed unreadable (assuming it contains text) or when I send a not that important photo, it's 5 MB in size and the recepient won't download it over limited data.

#### Debug output

N/A + broken port preventing adb.

**Comment by Mikaela** [comment]
Sorry for not filling most of the defaults now, I will do it later on PC, it just didn't seem that important.

**Comment by iNPUTmice** [comment]
If you select 'attach file' the image will be send uncompressed. Prompting on every single image will slow down the process and most users don’t care.
