### ISSUE TITLE
Feature: Display contacts that have jabber info from phonebook in Start Conversations screen

### ISSUE THREAD

**Issue by wiktor-k** [siacs/Conversations#3158]
Currently Conversations allows integration of Roster contacts with Phone contacts by setting `PROTOCOL_JABBER` field on a phone contact.

It would be nice if the reverse was also true - if a phone contact that *is not* in the Roster have `PROTOCOL_JABBER` field set (either via manual vCard import or manual entry via Phone book) then it would appear on Start Conversation screen (either below all contacts, or with a special dynamic tag).

That would have the same effect as starting the conversations via `xmpp:jid@example.com?message` URI and it would **not** modify roster in any way.

Most of the code is already in Conversations (from my casual skimming), phone contacts with `PROTOCOL_JABBER` are already stored in memory but are filtered out by [this condition](https://github.com/siacs/Conversations/blob/af724a66977aec8e5886fc1e3b9faedc11f99eb4/src/main/java/eu/siacs/conversations/ui/StartConversationActivity.java#L865) that ultimately [checks if the contact is in the roster](https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/entities/Contact.java#L334).

If this issue sounds good I can work on a PR.

**Comment by wiktor-k** [comment]
Looks and works great Daniel! (Play Store beta version), two small things:

- phonebook-only contacts still have "remove contact" menu option when long clicking, this is a no-op, maybe remove the menu options altogether for phone-only contacts?
- in Start Conversation the phone-only contact is properly displayed with Display Name from phone book but when clicking such a contact its name is replaced by their JID. This is probably due to the fact that it's not in Roster. Adding contact adds the name from Phone book (that's good).

**Comment by wiktor-k** [comment]
Very cool, thanks again for the fixes Daniel!

**Comment by licaon-kter** [comment]
These were not yet commited but in a beta?

**Comment by wiktor-k** [comment]
Not published on Github but I guess committed on Daniel's laptop. Or not committed if he's thinking about perfect wording of the commit message :)

It works, believe me.

**Comment by iNPUTmice** [comment]
fixed in 2.2.8

**Comment by iNPUTmice** [comment]
Yes it was removed on purpose. I didn’t like it.

**Comment by wiktor-k** [comment]
Ok, thanks for taking the time to explain.
