### ISSUE TITLE
Coversations gets logout, when moved to background. Logins when move to foreground

### ISSUE THREAD

**Issue by mmaahmed** [siacs/Conversations#3159]
#### General information

* **Version:** eg 2.2.8.
* **Device:** eg Vivo 1610
* **Android Version:** eg Android 6.0.1
* **Server name:** self-hosted
* **Server software:** Openfire 4.2.3
* **Installed server modules:** eg Achieve, REST API. Monitoring Service, Presence, HTTP File Upload, User Status, Content Filter, Jingle Nodes Plugin
* **Conversations source:** eg Github (Master Branch)

#### Steps to reproduce

1. User Logs in successfully, able to send message to any other entity.
2. Moving the app to background, removing from recent apps.
3. User gets log out automatically somehow, and doesnot get any messages from other entity, with which the chat was initiated moments ago.
4. Open the app, and it logs you in again, then only you are able to chat again.

#### Issue

The app logs out the conversation user as soon as it is cleared from recent apps, even with enabling "Keep service in foreground" option in Expert Settings.

The app logs the user again and again, when you close and open it every single time.

#### Attached logs
[log.txt](https://github.com/siacs/Conversations/files/2336485/log.txt)

#### Expected Result

We want to keep the user logged in even the app is cleared from recent apps and receiving messages on time.

**Comment by licaon-kter** [comment]
Blame your ROM, did you whitelisted the app in Android >Settings> Apps ?

**Comment by iNPUTmice** [comment]
The log doesn’t actually show the swipe / logoff. In general the app will log off when swipped away but should relogin a few moments later unless your OS prevents that. Enabling the foreground service in the expert settings can help. For further questions please use the group chat.
