### ISSUE TITLE
How to setup xep-264 or xep-363

### ISSUE THREAD

**Issue by conectasmart** [siacs/Conversations#3161]
Hi all,
How can I chosse/setup file transfer file features to use xep-363 ?

Thanks,

#3155 ### General information

* **Version:** eg 1.21.0
* **Device:** eg Google Nexus 5
* **Android Version:** eg Android 6.0 Stock or Android 5.1 Cyanogenmod
* **Server name:** eg conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by licaon-kter** [comment]
Why do you mention 264 too?

Setup a server that provides 363.


/Close this

**Comment by iNPUTmice** [comment]
If you have further questions the group chat (see our README) is a more appropriate place to ask those. But in general @licaon-kter is right. Just enable 0363 on your server.
