### ISSUE TITLE
Conversations does not recognize Samsungs "Do not disturb"-Mode

### ISSUE THREAD

**Issue by kromonos** [siacs/Conversations#3165]
#### General information

* **Version:** 8.0.0
* **Device:** Galaxy A3 (2017)
* **Android Version:** Android 8.0 Stock
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce
1. Conversations: Settings -> Expert Settings
2. Deactivated: Manage availability manually, Away when screen is off
3. Activated: "Do not disturb" in silent mode, Treat vibrate as silent mode
4. Stock Android of Galaxy A3: Settings -> Sounds and vibrations
5. Activate "Do not disturb"

#### Expected result
Conversations went to "DnD"

#### Actual result
Conversations does not recognize Samsungs "Do not disturb"-Mode. But it worked with vanilla Android.

**Comment by unicorntaco** [comment]
> Activated: "Do not disturb" in s

You misunderstand this feature.  You have activated an Availability state.  This is information about yourself you are volunteering to subscribers in your roster.  This is not silencing the app notifications.

**Comment by kromonos** [comment]
> You misunderstand this feature. 
You misunderstand, what I wrote. Conversations does not set my status to away, when I silence my phone! Please read everything, before writing something!

**Comment by iNPUTmice** [comment]
This has been fixed in 2.2 or 2.3
