### ISSUE TITLE
Avatar isn't square in chat

### ISSUE THREAD

**Issue by weeman1337** [siacs/Conversations#3166]
#### General information
* **Version:** 2.2.9+pcr
* **Device:** Galaxy Nexus
* **Android Version:** Android 5.1.1
* **Server name:** self hosted
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** PlayStore

#### Steps to reproduce
1. Use a square avatar
2. Open a chat

#### Expected result
The avatar is displayed square

#### Actual result
The avatar isn't square
![image](https://user-images.githubusercontent.com/6216686/44999694-8e8cb300-afbf-11e8-93ff-2d319131b7a5.png)

It is square in the settings.

**Comment by weeman1337** [comment]
Since I want to contribute some things to Conversations I'll try solving this as a starter... :)

**Comment by licaon-kter** [comment]
What's the deviation?

**Comment by weeman1337** [comment]
@licaon-kter see my screenshot posted above. The avatar isn't square. But I uploaded a square one and it's also displayed square in the Conversations account settings.

**Comment by iNPUTmice** [comment]
Huh; never noticed that that must be in there for three years or so - I know what’s causing it - fixing it is somehow a bit more problematic;

**Comment by licaon-kter** [comment]
Oh, the little rounded corners...good catch.

**Comment by alexara** [comment]
> Oh, the little rounded corners...good catch.

I always thought that this was a feature and suits the rest of the app as many other corners, like those of a chat bubble or a hint, are actually round too. :-)

**Comment by iNPUTmice** [comment]
The rounded corners are not the issue. The issue was that the avatar wasnt
square. (not the same width and height)

**Comment by iNPUTmice** [comment]
Fixed in 11f67ac1ae8888cdac927a09275f8b757d98af45
