### ISSUE TITLE
Feature Request: Set default options

### ISSUE THREAD

**Issue by thomas-mc-work** [siacs/Conversations#3168]
#### General information

* **Version:** latest
* **Device:** independent
* **Android Version:** independent
* **Server name:** independent
* **Server software:** independent
* **Installed server modules:** independent
* **Conversations source:** F-Droid

#### Actual result

The options `Send button indicate status` and `Expert Settings/Request message receipts` are not enabled by default.

#### Expected result

Is there anything that prevents from having these options enabled per default? I think they are very useful and hard to find – especially for beginners.

**Comment by licaon-kter** [comment]
https://github.com/siacs/Conversations/issues/2516
&
did you read https://gultsch.de/xmpp_2016.html yet?
```
 Some users might like to see the presences and status messages of their contacts. Some other users are confused by that flood of information. Proprietary instant messaging solutions do not give you that choice. You are stuck with whatever some designer thought was right for most people. 
```

**Comment by thomas-mc-work** [comment]
> #2516

It's only proposing to move the option out of expert settings. A bit different, but also a good point.

> did you read gultsch.de/xmpp_2016.html yet?

Yes, but long time ago. I'll review that later.

But …

> Some other users are confused by that flood of information.

I think this doesn't hold true for this feature because the indication is in both situations very very subtle. I think even Whatsapp is showing whether the message has arrived. If Whatsapp users aren't confused then it should be perfectly fine for XMPP users. Finally it'l still be configurable, so you're free to disable it.

> Proprietary instant messaging solutions do not give you that choice.

This claim isn't about choice but only about the default setting.

**Comment by thomas-mc-work** [comment]
@iNPUTmice Why did you close this ticket without any reason?

**Comment by zz-ha-dum** [comment]
i agree with the proposed better Informatics defaults

also default status screen off and silent indications enabled.  i would not treat vibration as silent
