### ISSUE TITLE
app should create .noindex files 

### ISSUE THREAD

**Issue by unicorntaco** [siacs/Conversations#3169]
I don't want the images I receive in Conversations to be aggregated in android gallery.  Less savvy users are not able to touch this file into being.  An app option to not-index images/videos this way or otherwise would be grand.

**Comment by licaon-kter** [comment]
You mean `.nomedia` maybe?

Also, users should use their Gallery app preferences to EXCLUDE what the don't want, given that you know that #1047 is not fixed, this request makes no sense.
