### ISSUE TITLE
request: break out options for Address Book integration:  photo vs avatar

### ISSUE THREAD

**Issue by brighterness** [siacs/Conversations#3173]
I would want the ability globally (but preferably per contact)

* show JID's uploaded avatar as priority
* show photo from contact that includes JID in 'IM' 'Jabber' as the priority
* show the avatar I have assigned her JID myself via Conversations as the priority

**Comment by iNPUTmice** [comment]
I suggest you don’t add the jid to the contact book then. Having the contact avatar from the phone book is pretty much the only reason to add it in the first place.
