### ISSUE TITLE
request: option to stop suggesting servers as I add JID to roster

### ISSUE THREAD

**Issue by brighterness** [siacs/Conversations#3174]
On my older devices this is a huge lag factor in the UI.  I know the JID.  I am, after all, already adding it;  I don't need hinting.

**Comment by licaon-kter** [comment]
How old is the device? Or how many entries of servers do you have?

**Comment by zz-ha-dum** [comment]
> I know the JID. I am, after all, already adding it; I don't need hinting.

👍
