### ISSUE TITLE
Avatars in muc disappear when users are offline

### ISSUE THREAD

**Issue by meaz** [siacs/Conversations#3176]
#### General information

* **Version:** 2.2.9+fcr
* **Device:** Galaxy S4 mini
* **Android Version:** Lineageos 14
* **Server name:** selfhosted
* **Server software:**  last prosody trunk
* **Installed server modules:** mod_profile and a lot of others :)
* **Conversations source:** F-Droid

#### Steps to reproduce

1. User1 talks in a muc with user2 that has an avatar.
2. User1 sees all user2 messages along with user2's avatar.
3. User2 goes offline, not user1

#### Expected result

User1 still sees user2 messages along with his avatar.

#### Actual result

What do you see instead?
User1 still sees user2 messages, but with no his avatar anymore (instead he sees a generic avatar with a letter)

**Comment by iNPUTmice** [comment]
This has been fixed in 2.3 or 2.2
