### ISSUE TITLE
[tiny feature request] Answering from within notification 

### ISSUE THREAD

**Issue by moppman** [siacs/Conversations#3177]
I think it's safe to assume that the user has read a message if they  quick-reply from within a notification. Currently, the user has to tap "mark as read" after hitting send. This extra tap is redundant imho.
Thanks for your consideration and a great app, @iNPUTmice  :)

**Comment by moppman** [comment]
Too bad, I didn't know this was against the Android design guidelines because WhatsApp does it, too :)
I'll close this then.

**Comment by iNPUTmice** [comment]
After replying you can also swipe the notification away for the same effect. I don’t think this will be too much work and also keeps the option of reading the response again and checking for typos etc.
