### ISSUE TITLE
Screen not disabled during voice message playback when earpiece is true

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#3184]
#### General information

* **Version:** 2.3.0-beta2
* **Device:** Samsung Galaxy S4 Mini i9195
* **Android Version:** LineageOS 14.1
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Playback a voice message
2. Cover proximity sensor (switch to earpiece)

#### Expected result

Screen turns off.

#### Actual result

Screen stays on.

**Comment by iNPUTmice** [comment]
Conversations uses standard android APIs to disable the screen. If it doesn’t work on your ROM its a fault of the ROM.

**Comment by alexara** [comment]
> Conversations uses standard android APIs to disable the screen. If it doesn’t work on your ROM its a fault of the ROM.

Indeed, I built and installed the latest version of LineageOS 14.1 and now it works as expected. :-)



Indee
