### ISSUE TITLE
Remove specific Message from DB ?

### ISSUE THREAD

**Issue by teymoori** [siacs/Conversations#3186]
Hi
How to remove a message from db? i cant find this method in MessageArchiveService or Message Class.
thanks

**Comment by licaon-kter** [comment]
See how pixart is doing it

/Close as invalid

**Comment by teymoori** [comment]
do you have any link or document?
i cant find any thing

**Comment by iNPUTmice** [comment]
There is no method to delete messages from the database. You need to write one yourself.

**Comment by licaon-kter** [comment]
@teymoori Oh c'mon
https://github.com/kriztan/Pix-Art-Messenger/commit/4f612fc9bc50e8665c11cab59f502ace854a4a9f

**Comment by kriztan** [comment]
This methode doesn't work if you use message archive management. All deleted messages will be added in a later mam retrieval.

**Comment by licaon-kter** [comment]
@kriztan OMEMO messages even?
