### ISSUE TITLE
Conversations caches obsolete certs and doesn't revalidate TLS with the current valid cert

### ISSUE THREAD

**Issue by shh0** [siacs/Conversations#3187]
#### General information

* **Version:** 2.2.8+fcr
* **Device:** Xiaomi Mi A1
* **Android Version:** Android 8.1 Stock
* **Server name:** self hosted
* **Server software:** prosody 0.10.2-1~stretch1
* **Installed server modules:** all stuff to be fully compatible like conversations.im
* **Conversations source:** F-Droid

#### Steps to reproduce
1. Use google keyboard and send a GIF to your contact. This GIF get's into your "recently used" list.
2. Before letsencrypt's cert get's obsolete, create a new cert, install it, restart servers: prosody, ngynx...
2. Wait until the old(!) cert from 1.) get's obsolete.
4. Try to send this GIF to some contact again.

#### Expected result

Conversations should just send the GIF to the recipient without any TLS error msg.
Conversations should use the new cert of the site, and revalidate that TLS connection.

#### Actual result

Conversations uses the old obsolete letsencrypt cert. A message pops up, telling "Unbekanntes Zertifikat akzeptieren?", "timestamp check failed", "Möchtest du trotzdem eine Verbindung herstellen". It also shows my old cert of the server.
Maybe this is a caching issue, but Conversations should not cache old certs, rather revalidate connections on reusage. Or cached items should get an expire timestamp...

#### Debug output

```
adb logcat -s conversations
09-22 11:26:10.494 12969 12969 D conversations: app switched into foreground
09-22 11:26:10.494 12969 12969 D conversations: ConversationFragment.onBackendConnected()
09-22 11:26:10.495 12969 12969 D conversations: reInit(hasExtras=false)
09-22 11:26:10.501 12969 12969 D conversations: scrolledToBottomAndNoPending=false
09-22 11:26:10.522 12969 12969 D conversations: load more messages for My Friend prior to 2017-12-19T20:10:21.269Z
09-22 11:26:22.718 12969 12969 D conversations: received uri permission for content://com.google.android.inputmethod.latin.inputcontent/inputContent?fileName=%2Fdata%2Fuser_de%2F0%2Fcom.google.android.inputmethod.latin%2Ffiles%2Fgif2364989397429859850&packageName=eu.siacs.conversations&mimeType=image%2Fgif
09-22 11:26:22.727 12969 13408 D conversations: copy content://com.google.android.inputmethod.latin.inputcontent/inputContent?fileName=%2Fdata%2Fuser_de%2F0%2Fcom.google.android.inputmethod.latin%2Ffiles%2Fgif2364989397429859850&packageName=eu.siacs.conversations&mimeType=image%2Fgif to private storage (mime=image/gif)
09-22 11:26:22.733 12969 13408 D conversations: copy file (content://com.google.android.inputmethod.latin.inputcontent/inputContent?fileName=%2Fdata%2Fuser_de%2F0%2Fcom.google.android.inputmethod.latin%2Ffiles%2Fgif2364989397429859850&packageName=eu.siacs.conversations&mimeType=image%2Fgif) to private storage /storage/emulated/0/Conversations/Media/Conversations Images/23777515-46b0-43f0-a05f-8dcf2f5b531b.gif
09-22 11:26:22.775 12969 13408 D conversations: send file message
09-22 11:26:22.839 12969 13409 D conversations: uploading to https://upload.domain.xyz:5281/upload/LghX8PSO7Gg5RyLj/I3d1FUawQ_CgX43PL1tTGw.gif w/ read timeout of 262s
09-22 11:26:23.534 12969 12969 D conversations: app switched into background

```
^-- now the TLS-error msg is showing. I can now accept it once, cancel, or always accept the old cert.
The following comes when I accept the old cert one:

```
09-22 11:31:32.124 12969 12969 D conversations: ConversationFragment.onAttach()
09-22 11:31:32.172 12969 12969 D conversations: me@domain.xyz send ping (action=ui,lowTimeout=false)
09-22 11:31:32.174 12969 12969 D conversations: app switched into foreground
09-22 11:31:32.175 12969 12969 D conversations: ConversationFragment.onBackendConnected()
09-22 11:31:32.175 12969 12969 D conversations: reInit(hasExtras=false)
09-22 11:31:32.183 12969 12969 D conversations: scrolledToBottomAndNoPending=false
09-22 11:31:32.233 12969 12969 D conversations: load more messages for My Friend prior to 2017-12-19T20:10:21.269Z
09-22 11:31:32.548 12969 13409 D conversations: finished uploading file
09-22 11:31:32.558 12969 13409 D conversations: AxolotlService (me@domain.xyz): Cache miss: 23777515-46b0-43f0-a05f-8dcf2f5b531b
09-22 11:31:32.594 12969 13677 D conversations: AxolotlService (me@domain.xyz): Generated message, caching: 23777515-46b0-43f0-a05f-8dcf2f5b531b
09-22 11:31:32.594 12969 13677 D conversations: AxolotlService (me@domain.xyz): Cache hit: 23777515-46b0-43f0-a05f-8dcf2f5b531b
09-22 11:31:43.986 12969 12969 D conversations: app switched into background
09-22 11:31:44.007 12969 12969 D conversations: ConversationFragment.onAttach()
09-22 11:31:44.072 12969 12969 D conversations: app switched into foreground
09-22 11:31:44.072 12969 12969 D conversations: ConversationFragment.onBackendConnected()
09-22 11:31:44.072 12969 12969 D conversations: reInit(hasExtras=false)
09-22 11:31:44.079 12969 12969 D conversations: scrolledToBottomAndNoPending=false
09-22 11:31:44.100 12969 12969 D conversations: load more messages for My Friend prior to 2017-12-19T20:10:21.269Z
09-22 11:32:32.395 12969 12969 D conversations: app switched into background

```
The GIF (496KiB) then is sent and offered for download at the other phone (we both automatically accept 512KiB files due to Conversations settings)
However, the recipient Conversations (2.2.9+fcr) also get's this TLS error message about the old cert and if he/she want's to accept it once/cancel/always.

**Comment by iNPUTmice** [comment]
I don’t think it caches certs. It may reuse connections though.

**Comment by shh0** [comment]
I'm not sure if I understand that correctly.
Do you mean, Conversations tries to reuse old connections that prosody (still) provides? I used "prosody reload" to activate the new letsencrypt certs.

**Comment by shh0** [comment]
Solved, thanks for pointing me to the server! :)
Restarting prosody solved the issue and I was able to send this old GIF without TLS errors.

I think prosody doesn't clear the cache on "prosodyctl reload" after installing fresh certs.
Filed another issue: https://github.com/bjc/prosody/issues/23
