### ISSUE TITLE
message was not encrypted for this device

### ISSUE THREAD

**Issue by boroli** [siacs/Conversations#3189]
#### General information

* **Version:** 2.2.9+fcr
* **Device:** multiple 
* **Android Version:** Android 7 and others
* **Server name:** home.zom.im
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Using multiple devices with the same account and omemo encryption 
2. It seems that the first device which receives the message can decrypt it, while the second got the following error message:

message was not encrypted for this device

The same also applies for sent messages. 

#### Expected result

The message should be decrypted at all devices. 

Is it a bug or a feature?

Is it a server or client problem?

**Comment by licaon-kter** [comment]
Does your contact have the keys for ALL your devices? What client does your contact use?

**Comment by mrDoctorWho** [comment]
Me and my contacts on different servers experience the same issue. We all use Gajim and Conversations.

Everything worked perfectly not a long time ago. I didn't add any new devices, all of them trust each other.

The issue is seem to be applying only for Conversations. For instance, Gajim can decrypt all messages just fine.

**Comment by iNPUTmice** [comment]
On the sending client you have to make sure that all keys are activated

**Comment by mrDoctorWho** [comment]
Just like I said, everything was working perfectly until some point in time.

After you send a message from the party that was unable to decrypt the message, everything works perfectly. Until you try another device. 

May it be a message carbons issue?

**Comment by iNPUTmice** [comment]
@mrDoctorWho please provide more detailed steps to reproduce the issue using 'Device A (Conversations)' and 'Device B (Gajim) or 'User 1 Device C (Conversations)' or whatever.

Sending a message from a device will reactivate it on all other devices. Question is why it got deactivated in the first place.

**Comment by mrDoctorWho** [comment]
User 1, device A (conversations), sends a message to user 2, device A (conversations). User 2 had previously used device B (Gajim) and now is unable to decrypt the message sent from user 1, no matter the device.

I'm not yet sure if that's the correct way of reproducing the problem, I'm not around my PC.

What I can tell for sure that user 1, device A can't decrypt the message from their own device B.

**Comment by mrDoctorWho** [comment]
So I built Conversations d8c13276 myself and I'm unable to reproduce this bug anymore.

@boroli is this issue still there for you?

**Comment by alkorgun** [comment]
- Version: 2.2.9+pcr, 2.3.1+pcr
- Device: Nokia 7 plus
- Android Version: 8.1, 9.0
- Server name: helldev.net
- Conversations source: Google Play Store

I have the same issue. Gajim+Conversations=fail. Older versions (1.23.0, 1.23.4) on other devices work fine.

**Comment by wiktor-k** [comment]
I've recently sent a message from Gajim to a *new* contact (meaning I just added them to roster) that uses Conversations 2.3.1+pcr. When they replied I got a message that could be decrypted only on Gajim, not on Conversations (that showed `message could not be decrypted on this device`).

Could it be possible that for new contacts/conversations not all keys are fetched and used?

**Comment by mrDoctorWho** [comment]
@wiktor-k did your contact confirm all of your fingerprints?

**Comment by iNPUTmice** [comment]
Not a bug report. Please use the group chat for help

**Comment by markuskramerIgitt** [comment]
@iNPUTmice,  I have the same issue. 
"Other devices" session is accepted in both devices.
Which group chat do you mean, please?

**Comment by licaon-kter** [comment]
@markuskramerIgitt 

xmpp:conversations@conference.siacs.eu?join

**Comment by markuskramerIgitt** [comment]
@licaon-kter thanks!

**Comment by markuskramerIgitt** [comment]
You advised me to double-check the sending device: my keys were disabled.
After enabling them, everything fine.

Than you for your advise!!
