### ISSUE TITLE
Messages read aloud

### ISSUE THREAD

**Issue by hermann-san** [siacs/Conversations#3190]
has somebody managed to get new Conversations messages to read aloud (Text to Speech)?

I can see that there are apps to read notifications messages. Has someone tried it?
[https://play.google.com/store/apps/details?id=com.pelix.notify]()

Specifically supports chat apps (like WhatsApp, Telegram), but not Conversations  [https://play.google.com/store/apps/details?id=com.pacosal.vfnp&hl=de](https://play.google.com/store/apps/details?id=com.pacosal.vfnp&hl=de)

Thanks

**Comment by iNPUTmice** [comment]
Maybe ask in the group chat if someone has experience was that tool.
