### ISSUE TITLE
Messages lost when switching networks

### ISSUE THREAD

**Issue by dnut** [siacs/Conversations#3191]
#### General information

* **Version:** 2.2.8
* **Device:** Sony Xperia Z3, LG G3, LG V20
* **Android Version:** Android 5.0.2 Sony stock, Android 6.0 Resurrection Remix, Android 7.0 LG stock
* **Server name:** self-hosted
* **Server software:** prosody 0.10
* **Installed server modules:** PEP, Carbons, MAM, HTTP upload
* **Conversations source:** F-Droid

#### Steps to reproduce

Send a message when switching networks or temporarily being without any network service. For example, walk outside the range of a wifi network and send a message while waiting for LTE connection. I notice this most often when I go into the parking garage under my building where I lose a signal for about 30 seconds.

#### Expected result

The message doesn't send without network access, but eventually either sends successfully or notifies the user of failure.

#### Actual result

The message does not send while I have no network access. It says "waiting". Then when I connect to the other network it says "just now", indicating success, but the message did not send. Sometimes the message will actually send, but sometimes it does not.

#### Debug output

This only happens at inopportune times. I can't reproduce it by manually disconnecting wifi.

**Comment by iNPUTmice** [comment]
It’s very likely that your server is not setup correctly. You can use the [compliance tester](https://compliance.conversations.im) to verify. Also

> but the message did not send.

How do you know? Maybe it didn’t arrive.

Due to the nature of your problem (not actually a bug in Conversations) I recommend you ask in the group chat for help this also allows for a better back and forth than the issue tracker.

**Comment by dnut** [comment]
To me this looks a problem with Conversations since it is determined by conditions in the client. I don't see how the server could be at fault here. I've been using this server for a long time without any messages going missing with other clients.

Also, I'm not getting any results from your compliance tester. I enter in some credentials and all it does is tell me they were submitted.

**Comment by licaon-kter** [comment]
@dnut so your server is not on the tested list now?

**Comment by dnut** [comment]
Right, and I'd like to keep it that way. It was foolish of me to enter test credentials in there without understanding what it does. I'll run the test locally when I have time.

**Comment by iNPUTmice** [comment]
@dnut Conversations will also show a limited version of that if you select 'Server Info' from the overflow menu in the account details.
