### ISSUE TITLE
Delete Media File on Http upload Server 

### ISSUE THREAD

**Issue by mulles** [siacs/Conversations#3193]
#### General information
* **Version:** 2.2.9+fcr 
* **Device:**  Google Nexus 4* **Android Version:** eg Android 8.0 Lineage Os 
* **Server name:** movim.eu 
* **Server software:** ejabberd (version  to be completed)
* **Installed server modules:** to be completed
* **Conversations source:**  F-Droid

#### Steps to reproduce

1. Long Press Media file (e.g Image) in Chat window. 
2. Select Delete image/audio/etc.
3. New placeholder for the mediafile:  "The file has been deleted"

#### Expected result

The file will be removed from my phone and Server it is stored on. Should the media file not been uploaded by yourself, conversation should inform you that it can only delete the file locally. 

Another option, might be to make clear to the user that the file will only be delete locally. The current behavior, could led the user to believe that the file does not reside any longer on the server. This would still not allow the user to delete files from his used Server, thus he would need to contact the System Administrator in order to get his files removed. 

This might be related to the following issue: #2367

#### Actual result

The file is only deleted from my phone but not from the server.

**Comment by mulles** [comment]
#2368

**Comment by licaon-kter** [comment]
That's not how XMPP works.

/Close as wontfix

**Comment by wiktor-k** [comment]
Unfortunately this is a limitation of the underlying HTTP Upload XEP that [defines only GET and PUT methods](https://xmpp.org/extensions/xep-0363.html#request). So to properly support removing files one would have to extend XEP-0363 by introducing `DELETE` slot, then the server implementations should add support for that and clients (like Conversations) would have to remember DELETE slots for uploaded images.

The feature is not unreasonable but would require quite a lot of work. Fortunately with media confirmation dialogs deleting uploaded media is not a big concern (IMHO).

**Comment by mulles** [comment]
@Wiktor

thx for elaborating. I knew it is a limitation of the Http Upload XEP, but I am not into the XEP's to much, thus preferred not to share my incomplete knowledge. 
What do you mean by Media confirmation dialogs? 

Furthermore, I think  conversations should still be adjusted to more specifically indicate what happens exactly with the media file on "deletion"

I will try to do a pull request enhancing this.  

On September 27, 2018 2:47:30 PM GMT+02:00, Wiktor <notifications@github.com> wrote:
>Unfortunately this is a limitation of the underlying HTTP Upload XEP
>that [defines only GET and PUT
>methods](https://xmpp.org/extensions/xep-0363.html#request). So to
>properly support removing files one would have to extend XEP-0363 by
>introducing `DELETE` slot, then the server implementations should add
>support for that and clients (like Conversations) would have to
>remember DELETE slots for uploaded images.
>
>The feature is not unreasonable but would require quite a lot of work.
>Fortunately with media confirmation dialogs deleting uploaded media is
>not a big concern (IMHO).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/siacs/Conversations/issues/3193#issuecomment-425077367

Emile Schons

**Comment by wiktor-k** [comment]
> What do you mean by Media confirmation dialogs?

In Conversations 2.3.0 you have to confirm that you want to send the picture to a contact. This avoids many accidental media messages to random people. Previously it was too easy to send media to wrong people or channel by using Android's Quick Share.

**Comment by mulles** [comment]
thx for clarifying. 

In resume you mean: The requirement to delete media files from server is not so important as chances are low that you shared them with the wrong person. 

Please note that still the server administrator has access to media files you choose to share unencrypted, for whatever reason. 

When encryption becomes mandatory, the issue might be consider obsolete. Still one need to keep in mind that your information resides encrypted on a server you don't have much control over. 

On September 27, 2018 4:39:48 PM GMT+02:00, Wiktor <notifications@github.com> wrote:
>> What do you mean by Media confirmation dialogs?
>
>In Conversations 2.3.0 you have to confirm that you want to send the
>picture to a contact. This avoids many accidental media messages to
>random people. Previously it was too easy to send media to wrong people
>or channel by using Android's Quick Share. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/siacs/Conversations/issues/3193#issuecomment-425118171

Emile Schons

**Comment by wiktor-k** [comment]
> Please note that still the server administrator has access to media files you choose to share unencrypted, for whatever reason. 

If you think your server administrator is evil you better run your own as if they were truly evil they could still make a copy and fake deletion.

By the way you may like to discuss the XEP changes in this room: xsf@muc.xmpp.org

**Comment by zz-ha-dum** [comment]
Is the omemo encrypted file housed by MAM or carbons?  When erase history is actuated are not also those files erased?

**Comment by zz-ha-dum** [comment]
I would extend deletion to Self Destruct (in N units of time)

**Comment by mulles** [comment]
I got it wrong. The files themselfs are not OMEMO encrypted just the link pointing to the file.  

The file itself is encrypted using the aesgcm:// scheme.
See:https://github.com/iNPUTmice/ImageDownloader 


@Wiktor You are right concerning the trust of the administrator ( thx for specifing) . The idea is that one can delete the files without requesting the admin to do so manually, but as you sugguested the xep chat is the right place to enhance that.
In resume one must trust the server/admin to behave as expected, on manual or automated delete.

**Comment by MalevolentGrin** [comment]
> I would extend deletion to Self Destruct (in N units of time)

Awesome!
