### ISSUE TITLE
Audio Recorder doesn't work when ONLY_INTERNAL_STORAGE = true

### ISSUE THREAD

**Issue by ChaosKid42** [siacs/Conversations#3205]
#### General information

* **Version:** 2.3.0
* **Device:** Moto G4
* **Android Version:** LineageOS 14.1 (Android 7.1.2)
* **Server name:** self-hosted
* **Server software:** ejabberd 18.09 
* **Installed server modules:** compliant to 2018 Compliant Suite
* **Conversations source:** self-built with ONLY_INTERNAL_STORAGE = true

#### Steps to reproduce

1. compile Conversations with ONLY_INTERNAL_STORAGE = true
2. try to record, attach and send audio recording

#### Expected result

Audio is recorded and sent

#### Actual result

Audio is recorded but not sent. Error-Toast:
Security error: Invalid file access

#### Debug output

````
adb -d logcat -v time -s conversation
10-01 09:54:06.438 D/conversations( 6401): ConversationsActivity.commitAttachments() - attaching file to conversations. CHOOSE_FILE/RECORD_VOICE/RECORD_VIDEO
10-01 09:54:06.457 D/conversations( 6401): trying to attach file that belonged to us
10-01 09:54:06.492 D/conversations( 6401): received uri permission for file:///data/user/0/eu.siacs.conversations/files/Recordings/RECORDING_20181001_095401644.m4a
````

**Comment by iNPUTmice** [comment]
04ac2264e83f01e8b201579d05bbbe136a35a7d7 should fix this. (Or more specifically this and the commit before it.)

**Comment by ChaosKid42** [comment]
Can confirm that the fix works. Thanks!
Nevertheless I suggest, that the recordings directory is added to file_paths.xml. Otherwise you can't share a recording:
https://github.com/siacs/Conversations/pull/3216
