### ISSUE TITLE
Video compression thoughts

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#3206]
Since https://github.com/siacs/Conversations/commit/bb6b647af8988fea006c123bdff68d1f97eac966 video compression has gotten better (size wise) yet worse (quality wise). 

I did a quick comparison, source 200Mb MP4, 4K, 53sec of hand stabilised random phone camera video:
 * 2.2.9/2,3,0 - 37.6Mb, 960x540 -> current situation
 * 2.3.0+ bb6b647af8988fea006c123bdff68d1f97eac966 - 7.3Mb, 640x480
 * 2.3.0+ bb6b647af8988fea006c123bdff68d1f97eac966 but _resolution raised to 1280x720 and bitrate to 2048kbps_ - 14.5Mb, 1280x720

_(click to open full size)_
![comparison](https://user-images.githubusercontent.com/2282799/46280386-4bd8df00-c55b-11e8-863c-84634d9568d0.png)

Now, while I like a small file as anyone else, I like the faces of the people to be recognizable and not a mash of 8x8 pixels.

The current (HEAD) transcoding library is better ( 1280x720 file is 2.5x smaller than the 960x540 one!!!) so it's already **good**, I'd like to keep the good part and not lower resolution to VGA just because the file is smaller.

Hence, I'd propose a selector ( yes yes like Pix-Art has go away :P ) that's not video length linked:
* VGA (640x480@1024kbits) - as current HEAD
* HD (1280x720@2048kbits) - I use this setting with https://github.com/brarcher/video-transcoder and, except high-motion scenes, it yields good enough video files. I'd like this to be default. (remember it's already miles better than 2.3.0 and older both size and quality wise)
* Full HD (1920x1080@4096kbits) - using the transcoder linked above (based on ffmpeg) I see resolution not having such a big impact (size-wise), this setting is already 4-5x reduced bitrate wise compared to the original video produced by Android cameras

/PS: Pix-Art has:
* 144px @ 100kbits
* 360px @ 500kbits - default
* 720px @ 2000kbits

/PS2: Ping me in the MUC if you want prebuild APKs to test HEAD and HEAD@1280 yourself.

**Comment by contrapunctus-1** [comment]
Riot has a selector too. In fact, for all media. I honestly find it preferable, otherwise I'm frequently fiddling with (or _forgetting_ to fiddle with) the compression settings.

**Comment by licaon-kter** [comment]
[Nooooooo](https://github.com/siacs/Conversations/commit/b27fa6d206e7995a5431bdccacb809ba68c0c0e8) :( :(
