### ISSUE TITLE
F-Droid or .apk download

### ISSUE THREAD

**Issue by baimafeima** [siacs/Conversations#3215]
I don't use any Google services (neither Amazon) but would like to use `Conversations` as my main communication platform on a mobile device. Could you make it available via F-Droid or as a separate .apk download? If not, could you post a reliable and secure way of getting to the .apk by other means for those who do not use Google or Amazon. For me, this is the biggest blocker towards adopting it as my main communication tool.

**Comment by licaon-kter** [comment]
It's already on F-Droid. Feel free to donate some $$ for the dev effort: https://github.com/siacs/Conversations#i-dont-have-a-google-account-but-i-would-still-like-to-make-a-contribution

**Comment by baimafeima** [comment]
@licaon-kter Only the legacy version is on F-Droid but not the latest.

**Comment by licaon-kter** [comment]
@baimafeima If you can't find it it means you don't have Android 4.4 or later, so you can only use Legacy.

**Comment by baimafeima** [comment]
@licaon-kter I'm on the latest LineageOS. It appears that generally only the legacy version is made available on F-Droid.

**Comment by iNPUTmice** [comment]
@baimafeima Conversations is available on fdroid https://f-droid.org/en/packages/eu.siacs.conversations/ - maybe you didn’t sync the repo or something.
