### ISSUE TITLE
Latest version cannot connect to prosody behind SNI/SSL shared port

### ISSUE THREAD

**Issue by terracotta-org** [siacs/Conversations#3218]
#### General information

* **Version:** 2.3.1+pcr
* **Device:** LG G4
* **Android Version:** Android 6.0 Stock 
* **Server name:**  self hosted SSL/SNI with port shared between nginx and prosody
* **Server software:** prosody 0.10
* **Installed server modules:** unchanged from when it worked
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Since I don't want to disclose the hostname of our server, I'm not sure what to enter here.

#### Expected result

Conversations should connect (and did up until this update, even yesterday).  All other XMPP clients still connect fine (eg psi+)

#### Actual result

![capture _2018-10-07-11-52-14](https://user-images.githubusercontent.com/4680353/46583636-09664500-ca28-11e8-940d-1b268c2f451c.png)

Local test via JuiceSSH:
![capture _2018-10-07-11-53-51](https://user-images.githubusercontent.com/4680353/46583698-c9ec2880-ca28-11e8-9041-a7fdd3cae900.png)

#### Debug output

> 
> 10-07 11:58:05.862  4849  4849 D conversations: USER@PRIVATE.HOST: error connecting account. reconnecting now. lowPingTimeout=false
> 10-07 11:58:05.865  4849 20433 D conversations: USER@PRIVATE.HOST: connecting
> 10-07 11:58:05.865  4849 20433 D conversations: verified hostname PRIVATE.HOST
> 10-07 11:58:05.878  4849  4849 D conversations: ForegroundService: off
> 10-07 11:58:05.878  4849 20436 D conversations: USER@PRIVATE.HOST: connecting
> 10-07 11:58:05.879  4849 20436 D conversations: verified hostname PRIVATE.HOST
> 10-07 11:58:05.898  4849 20436 D conversations: USER@PRIVATE.HOST: using values from resolver PRIVATE.HOST:443 tls: true
> 10-07 11:58:05.900  4849 20433 D conversations: USER@PRIVATE.HOST: using values from resolver PRIVATE.HOST:443 tls: true
> 10-07 11:58:06.027  4849 20433 D conversations: USER@PRIVATE.HOST: thread was interrupted before beginning stream
> 10-07 11:58:06.027  4849 20433 D conversations: USER@PRIVATE.HOST: not force closing socket because thread was interrupted
> 10-07 11:58:06.054  4849 20436 D conversations: USER@PRIVATE.HOST: xml parser mishandled XmlPullParserException(Unexpected token (position:TEXT HTTP/1.1 400 Bad...@8:1 in java.io.InputStreamReader@d339f05) )(java.io.IOException)
> 10-07 11:58:06.054  4849 20436 D conversations: USER@PRIVATE.HOST: error connecting account. try again in 42s for the 3 time. lowPingTimeout=false
> 10-07 11:58:06.402  1218  3316 D InputTransport: channel '6f0fc3e eu.siacs.conversations/eu.siacs.conversations.ui.ManageAccountActivity (server)' : action=ACTION_DOWN(0), id=0, tooltype=1, deviceId=4, source=0x1002, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, downTime=1871498297000, eventTime=1871498297000, pointerCount=1
> 10-07 11:58:06.431  1218  3316 D InputTransport: channel '6f0fc3e eu.siacs.conversations/eu.siacs.conversations.ui.ManageAccountActivity (server)' : action=ACTION_UP(0), id=0, tooltype=1, deviceId=4, source=0x1002, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, downTime=1871498297000, eventTime=1871530632000, pointerCount=1
> 10-07 11:58:06.458  4849 20440 D conversations: USER@PRIVATE.HOST: disconnecting force=true
> 10-07 11:58:06.459  4849  4849 D conversations: ForegroundService: off
> 10-07 11:58:16.452  4849  4849 D conversations: EventReceiver ignored action ping

**Comment by iNPUTmice** [comment]
What does it except in the SNI name? The domain name or the host name?

**Comment by terracotta-org** [comment]
I'm actually not sure, I set this up ages ago, but my haproxy config looks like this:

>     use_backend www-ssl        if  { req.ssl_sni -i XXXXXXX }
>     default_backend xmpp

Which means that the config is relying on the fact that XMPP clients do not usually pass SNI information, but web browsers do ...

**Comment by wiktor-k** [comment]
Could you try routing based on ALPN value? Conversations should use `xmpp-client` browsers will use something different (e.g. `h2`).

**Comment by iNPUTmice** [comment]
Conversations will add the domain name as SNI. If it is the same domain as
the webserver you can try alpn

**Comment by terracotta-org** [comment]
Thanks, will look into it.  nginx and prosody are indeed using the same domain name in my setup.

**Comment by akomakom** [comment]
This turned out to be a really bad plan...

After a lot of hours that included upgrading haproxy and reconfiguring everything, I've discovered that:

- If you want to use the ALPN value, you need to configure your haproxy with an SSL cert, so that haproxy handles SSL instead of your backends. 
- If you do this, you need to reconfigure your backends without SSL (nginx and prosody, in my case)
- If you do this, you need to reconfigure every single XMPP client (except Conversations) to use "Legacy SSL": https://stackoverflow.com/a/46667870/1735931 (confirmed).

I'm honestly not sure that this is a good idea.  
Maybe we could just have a checkbox to disable SNI? :)

**Comment by tapete** [comment]
The same problem for me. Since the last update, me and my friends are offline. Unfortunately I can not find enough information about SNI to fix this problem on the server side. And unfortunately downgrading conversations with fdroid leads to an unknown error. Quit severe issue I think.

**Comment by licaon-kter** [comment]
@tapete you can't downgrade an Android (security feature) unless you build you ROM and disable that.

**Comment by tapete** [comment]
I am using apache on port 443 and prosody on ports 5xxx at the same IP. They do not share the same port or the same hostname. Is there any special config detail for prosody to make it work with SNI? It is the first time I heard of SNI so I am really clueless. This issue is affecting me hard since most of my digital communication is broken.

**Comment by akomakom** [comment]
@tapete what makes you think that your issue has anything to do with this?  This issue is about shared port installations where haproxy can't determine whether to serve web or xmpp traffic.  You are not sharing a port.

**Comment by tapete** [comment]
@akomakom I thought it is mostly related to prosody and SNI.

**Comment by akomakom** [comment]
@iNPUTmice in desperation, I gave up on port sharing and have haproxy always go straight to prosody (always), but Conversations still doesn't connect, while all other XMPP clients work fine:

> 10-10 10:43:36.977 29453 27256 D conversations: verified hostname PRIVATE
> 10-10 10:43:36.977 29453 27256 D conversations: USER@PRIVATE: using values from resolver PRIVATE:443 tls: true
> 10-10 10:43:37.032 29453 27254 D conversations: USER@PRIVATE: TLS certificate verification failed
> 10-10 10:43:37.032 29453 27254 D conversations: USER@PRIVATE: not changing status to TLS_ERROR because thread was interrupted
> 10-10 10:43:37.032 29453 27254 D conversations: USER@PRIVATE: not force closing socket because thread was interrupted
> 10-10 10:43:37.042 29453 27256 D conversations: USER@PRIVATE: TLS certificate verification failed
> 10-10 10:43:37.042 29453 27256 D conversations: USER@PRIVATE: error connecting account. try again in 42s for the 3 time. lowPingTimeout=false

haproxy logs confirm that it's routing to prosody.  
The certificate is valid (LetsEncrypt), and this shows a valid cert:
openssl s_client -connect PRIVATE:443 </dev/null -starttls xmpp

**Comment by wiktor-k** [comment]
@akomakom, "legacy ssl" is now "modern ssl" and a preferred method of connection.
Conversations will try it first but regular STARTTLS-like connections should work as before.
If you don't need prosody running on 443 just add this to Prosody config: `legacy_ssl_ports = { 5223 }` and SRV record like this `_xmpps-client._tcp.your-domain.com. 3600 IN SRV	4 0 5223 your-domain.com.` It will work.
Note that only Conversations, Gajim and a few others will use that, the rest will connect to standard XMPP port (using SRV of course).

`TLS certificate verification failed` are you using expired Let's Encrypt cert maybe? (just a guess)

If you want you can contact me with your server's address and I can try debugging it.

**Comment by akomakom** [comment]
Thanks, @wiktor-k for the suggestions.  I don't control DNS (and if I could control DNS, I would probably have the ability to expose more ports, making this whole issue moot).  Likewise, I cannot expose port 5223 (I only have one port - 443).  It's possible that using a more robust sslh config would work to share the port among three destinations (nginx, 5222 and 5223), but my naive experiments did not arrive at a satisfactory configuration, and experimenting further would require a lot of downtime that I also can't get away with.  (I have set up a local docker environment to mimic this, but it's not quite like the real thing).  It seems that there is much dancing around to be done to satisfy every possible client.

Quite frankly, I've exceeded my time budget with this issue, and we're looking at replacing XMPP altogether (with some self-hosted slack equivalent like zulip).

**Comment by iNPUTmice** [comment]
Saying this here again even though not all of you might be effected by this.
If you manually enter port 443 or 5223 in Conversations (please try not to and use SRV records instead) it will expect a direct TLS connection. So your port 443 needs to redirect to 5223 (direct tls) and not port 5222 (starttls). This does not apply to SRV records. With SRV records you can tell Conversations to do what ever you want. If you are now using a SSL multiplexer on port 443 you need to be aware that Conversations will set the domain name as the SNI name. That’s the same behaviour you would have if you were using SRV records.

**Comment by akomakom** [comment]
For the record, I got it working by switching to **sslh** and following https://wiki.xmpp.org/web/Tech_pages/XEP-0368 and enabling **legacy_ssl_ports = {5223};** in prosody.  Thanks for your patience @wiktor-k and @iNPUTmice 

On a side note, I still can't get prosody to use the correct SSL certificate on this new port, no matter what I've tried (it uses some self-signed cert)... but at least it works.

**Comment by iNPUTmice** [comment]
@akomakom maybe you have specified the old cert as a virtual host cert; the legacy_ssl_port option will use the global cert. Just set the global cert to be the cert you used for the vhost. But this is getting very prosody specific now. The prodoy doc or the prosody muc channel will be the better place for questions about Prosody.
