### ISSUE TITLE
Better contacts screen + contact sharing

### ISSUE THREAD

**Issue by contrapunctus-1** [siacs/Conversations#3219]
I intended for this to be a suggestion for easier contact sharing, but it has also become a suggestion for a better contacts screen.

# Current long-press behavior in the contacts screen
A menu is displayed, where you can see a single contact's details or barcode, or block or delete them.

# Proposed long-press behavior in the contacts screen
Long-press selects a contact and hides the search bar, barcode scanner button, and the overflow menu.

If only a single contact is selected, the following buttons are displayed where the search was -
1. contact details (ℹ️)
2. share
3. barcode button
4. block (🚫)
5. delete (trash can).

If more than one contacts are selected, the following buttons are displayed where the search was - 
1. share
2. block (🚫)
3. delete (trash can).

This makes it easier to block and delete > 1 contacts. This is also the sanest place I can think of for placing the contact sharing functionality.

Contacts should be shared as a vCard (so that the receiving user can defer the decision to add the contacts, or share those contacts with someone else) containing only the JID.

When contacts are shared, the receiving user should be able to select which contacts to add to their roster.

**Comment by iNPUTmice** [comment]
I don’t think this is a direction I want to go.

**Comment by contrapunctus-1** [comment]
@iNPUTmice okay. What would you suggest instead for the case of adding mutual contacts for a newly onboarded contact?

**Comment by Echolon** [comment]
I like the idea basically!
