### ISSUE TITLE
Typo french translation

### ISSUE THREAD

**Issue by Botigli** [siacs/Conversations#3222]
There is a small typo in the french sentences.

https://github.com/siacs/Conversations/blob/d02b1237f72e576afa4c1bc09aeefb8db824ad28/src/main/res/values-fr/strings.xml#L537

This should be `utilisez` instead of `utitlisez`.

**Comment by wiktor-k** [comment]
Translations are handled through https://www.transifex.com/siacs/conversations/

**Comment by Botigli** [comment]
Oh I didn't know, sorry.
I will correct it then.

**Comment by wiktor-k** [comment]
No problem, it's quite nice and you can also translate the other missing French strings!

You need to join the team and that requires approval from project owner. If you wouldn't get it for a day or two you can ask in this room: https://conversations.im/j/conversations@conference.siacs.eu (I had to do this once).
