### ISSUE TITLE
"TLS negotiation failed" when connecting on port 443 (regression since 2.3.1)

### ISSUE THREAD

**Issue by md-work** [siacs/Conversations#3224]
#### General information

* **Version:** 2.3.1
* **Device:** Fairphone 2
* **Android Version:** Android 7.1 / LineageOS 14.1 (20180808-NIGHTLY)
* **Server name:** self hosted
Company server. SSL cert is signed by the company's root CA, which isn't imported on my private Android device.

* **Server software:** prosody 0.9.14 (openSUSE-42.3)
* **Conversations source:** F-Droid

Worked fine until version 2.3.0 and Conversations Legacy 1.23.12 is also fine.
Bug only appears when I specify to connect to port 443. Everything's fine if I use port 5222.

_

Also tested with version 2.3.0 on a different device right now with exactly the same settings and everything works. (Samsung S4 Mini i9195 / Android 7.1 / LineageOS-14.1)
I just gut this message on first login, which I confirmed with "always accept" (German).
```
Unbekannted Zertifikat akzeptieren?

Das Serverzertifikat stammt nicht von einer bekannten Ausstellungsstelle (CA).

Zertifikat-Details:
CN=workgroup.example.org,
[...]
Signed by: [...] CN=Server CA[...]

[...]
CN=Server CA[...]
[...]
Signed by: [...] CN=Root CA[...]

[...]
CN=Root CA[...]
```
Replaced the companies top level domain with "exmaple.org" and "username+mobile" with "user+mobile". (mobile indicates accounts for use on private phones in the company i'm working for)

Afterwards there was a second message, which I also confirmed with "always accept".
```
Abweichende Servernamen akzeptieren?

Der Server konnte sich nicht als "example.org" ausweisen. Das Zertifikat gilt nur für:

CN=workgroup.example.org, [...]

Verbindung trotzdem aufbauen?

Zertifikat-Details:
CN=workgroup.exmaple.org, [...]
```

_

Then also updated that device to version 2.3.1 and the bug appeared.

So I'm pretty sure, that this is some kind of regression. Although it only appears under very special circumstances.

_

#### Steps to reproduce

1. Start conversations.

2. Go to settings->expert and enable detailed connection settings (so you can specify hostname and port)

3. Add existing account.
my scenario
username: user+mobile@example.org
hostname: workgroup.example.org
port: 443

#### Expected result

Login works.

#### Actual result

```TLS negotiation failed```

#### Debug output

````
10-10 10:32:39.098 16911   581 D conversations: user+mobile@exmaple.org: connecting
10-10 10:32:39.099 16911   581 D conversations: verified hostname workgroup.exmaple.org
10-10 10:32:39.104 16911   581 D conversations: user+mobile@exmaple.org: using values from resolver workgroup.example.org:443 tls: true
10-10 10:32:39.196 16911   581 V NativeCrypto: SSL handshake aborted: ssl=0x976066b8: Failure in SSL library, usually a protocol error
10-10 10:32:39.196 16911   581 V NativeCrypto: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (/usr/local/google/home/flooey/code/boringssl/ssl/tls_record.cc:242 0xacf90f2f:0x00000000)
10-10 10:32:39.198 16911   581 W System.err: javax.net.ssl.SSLPeerUnverifiedException: No peer certificates
10-10 10:32:39.205 16911   581 W System.err:    at org.conscrypt.SessionSnapshot.getPeerCertificates(SessionSnapshot.java:133)
10-10 10:32:39.205 16911   581 W System.err:    at org.conscrypt.ExternalSession.getPeerCertificates(ExternalSession.java:111)
10-10 10:32:39.205 16911   581 W System.err:    at org.conscrypt.Java7ExtendedSSLSession.getPeerCertificates(Java7ExtendedSSLSession.java:133)
10-10 10:32:39.205 16911   581 W System.err:    at org.conscrypt.Java7ExtendedSSLSession.getPeerCertificates(Java7ExtendedSSLSession.java:30)
10-10 10:32:39.205 16911   581 W System.err:    at eu.siacs.conversations.services.MemorizingTrustManager$MemorizingHostnameVerifier.verify(MemorizingTrustManager.java:808)
10-10 10:32:39.205 16911   581 W System.err:    at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:348)
10-10 10:32:39.205 16911   581 W System.err:    at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:458)
10-10 10:32:39.205 16911   581 W System.err:    at java.lang.Thread.run(Thread.java:761)
10-10 10:32:39.205 16911   581 D conversations: user+mobil@example.org: TLS certificate verification failed
````

**Comment by iNPUTmice** [comment]
Looks like what ever you are using to multiplex or terminate ssl isn't
working. Conversations now puts the domain name as SNI. (just like it would
when connecting via SRV records)

**Comment by md-work** [comment]
> Looks like what ever you are using to multiplex or terminate ssl isn't working. Conversations now puts the domain name as SNI.

I'm not sure what multiplex or terminate ssl is. But as far as I know, the Prosody server is a pretty simple openSUSE-Linux system without any fancy network stuff.


> (just like it would when connecting via SRV records)
For the server there's a SRV record which looks like this:
```
_xmpp-client._tcp.example.org has SRV record 0 5 5222 workgroup.example.org
```

Everything is fine when I don't use the hostname and port fields. So in case I don't put in a hostname and port, I guess Conversations is connecting via the SRV record and there's no problem.

But I need to put in the port, because some wireless networks I'm frequently in only allow port 443 and 80.

**Comment by iNPUTmice** [comment]
Are you using direct tls on port 443? if so what does the related prosody config look like?

**Comment by md-work** [comment]
> Are you using direct tls on port 443? if so what does the related prosody config look like?
Sadly I don't have a login on that server, so I don't know. But I'll try to get that information from the server's administrator.

Can I provide any more helpful information from my Android device?

**Comment by md-work** [comment]
The server's admin gave me the iptables rules.

```
# iptables -t filter -nvL | grep 443 
    X     X ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443

# iptables -t mangle -nvL | grep 443       
    X     X MARK       tcp  --  *      *       0.0.0.0/0            1.2.3.4              tcp dpt:443 MARK set 0x1

# iptables -t nat -nvL | grep 443       
    X     X REDIRECT   tcp  --  *      *       0.0.0.0/0            1.2.3.4              tcp dpt:443 redir ports 5222
```
(server ip has been replaced with 1.2.3.4)

**Comment by Flunkyball** [comment]
I got exactly the same problem over here. 
In my setup I am using HAProxy to forward traffic for a certain domain im.domain.com incoming on port 443 to the correct ejabberd server on port 5222. Forwarding is done on TCP basis so no breaking of the SSL encryption is done.
The ejabberd server is setup with a vaild and correct letsencrypt certificate.

All clients work fine with that server and Conversations including 2.3.1 did as well.

Connecting directly to ejabberd on port 5222 works with 2.3.1.

Any ideas ?

**Comment by iNPUTmice** [comment]
@md-work if you manually enter port 443 or port 5223 in the extended connection settings Conversations will attempt to use TLS. Redirecting port 443 to 5222 means it is a STARTTLS port.

I recommend that your server admin setups proper SRV records instead. You can have a SRV record that points to 443 with a lower priority and Conversations will automatically attempt to use that if the regular port doesn’t work.

@Flunkyball same thing; I recommend you set up SRV records.

**Comment by md-work** [comment]
@iNPUTmice 

At first thanks very much for the help!

So would this DNS entry tell Conversations to use STARTTLS, if I clear the hostname and port fields in Conversations?

_xmpp-client._tcp.pre-sense.de has SRV record 10 5 443 workgroup.example.org

I think theoretically this should make clear, that it is STARTTLS (explicit SSL) on port 443. Because for implicit SSL (non-STARTTLS) the record would start with `_xmpps-client` (mind the `s`). But I don't know if Conversations honors this.

The alternative would be, to add another port forwarding to port 5222 from something else than 443 on the server. Maybe from port 80. But I actually like port 443, because I think it's the one which is at least disturbed by stupid firewalls on public wifis.

**Comment by Flunkyball** [comment]
@iNPUTmice 
Thank you for the input.

There is only one srv record which is correctly set to port 443. Port 5222 is not accessable from outside the network. 

According to the specification of ejabberd ([https://docs.ejabberd.im/admin/configuration/#examples](url)) using port 5223 is depreciated and the usage of StartTLS on port 5222 is recommended as standard.

So the question remains:
Why does Conversations from v2.3.1 following the correct srv record for the domain via port 443 with StartTLS not successfully connect anymore ?

**Comment by kolAflash** [comment]
@Flunkyball
Can you post the current srv record for your server?

**Comment by iNPUTmice** [comment]
> So would this DNS entry tell Conversations to use STARTTLS, if I clear the hostname and port fields in Conversations?
> 
> `_xmpp-client._tcp.pre-sense.de has SRV record 10 5 443 workgroup.example.org`

Yes.

> I think theoretically this should make clear, that it is STARTTLS (explicit SSL) on port 443. Because for implicit SSL (non-STARTTLS) the record would start with _xmpps-client (mind the s). But I don't know if Conversations honors this.

Yes Conversations will honor xmpps records.

@Flunkyball This issue is about problems that occur when you manually enter ports with the extended connection options. If you create an SRV records like the one above (from your statement that is already the case) and then **do not** use the extended connection options it should work.  If it doesn’t it is a separate issue. In that case please open a new issue and be specific about the domain and so on so I can test it myself.

**Comment by licaon-kter** [comment]
@Flunkyball 
For ejabberd I have 443->5223 and:

```
_xmpps-client._tcp.example.org. 86400 IN SRV 10 0 443 xmpp.example.org.
_xmpp-client._tcp.example.org. 86400 IN SRV 10 0 443 xmpp.example.org.
_xmpp-client._tcp.example.org. 86400 IN SRV 5 0 5222 xmpp.example.org.
```

**Comment by Flunkyball** [comment]
@licaon-kter 
Thank you for the input !

the "_xmpps-client" record does do the trick. After adding it additional Conversations is connecting again.

Thank you everyone for the help.

**Comment by licaon-kter** [comment]
This is the config from the wiki: https://wiki.xmpp.org/web/Tech_pages/XEP-0368 isn't everyone reading that?
