### ISSUE TITLE
[UI improvement] Colour text bubbles according to XEP-0392

### ISSUE THREAD

**Issue by sicherha** [siacs/Conversations#3225]
Conversations colours the text bubbles of received messages in either green or white, depending on the user's choice. The default setting, green, makes it easy to distinguish between sent messages and received messages.

However, it is still relatively difficult in MUCs to differentiate between messages received from different participants as they all have the same background colour, and one has to look at the left edge of the screen to see the sender's avatar. This is not optimal. I believe that a lot of clarity could be gained by colouring not only avatars according to XEP-0392 but also the bubbles of received messages. Applying this to both MUCs and 1:1 chats may also be beneficial because it would constitute an additional visual aid to distinguish between different chats.

Hence, I would like to put the following suggestion up for discussion: introduce a tri-state option to colour the text bubbles of all received messages
a) statically green,
b) statically white,
c) dynamically according to XEP-0392.

(This ticket touches on aspects of #2065.)

**Comment by licaon-kter** [comment]
/duplicate #2065

Also https://github.com/siacs/Conversations/pull/2960

**Comment by iNPUTmice** [comment]
I don’t think those colors are design to provide a large enough contrast for the use as a background color.
