### ISSUE TITLE
OMEMO broken (on Android 5.1 and older?)

### ISSUE THREAD

**Issue by STPKITT** [siacs/Conversations#3226]
* **Version:** 2.3.1+fcr
* **Device:** Samsung Galaxy SIII mini
* **Android Version:** Lollipop 5.1.1 (CyanogenMod 12.1) 20150706
* **Server name:** tested on jabber.at, jabber-germany.de, trashserver.net
* **Conversations source:** F-Droid

Since updating to Conversations 2.3.1+fcr OMEMO on the device listed above encrypted messages are not received at all and sending a message with OMEMO enabled immediately results in "Delivery failed" / "Zustellung fehlgeschlagen" while unencrypted messaging works fine.
I personally don't have that problem on a Galaxy S5 running LineageOS 15.1 (Android 8.1.0).
Members of conversations@conference.siacs.eu tried the same Conversations version on multiple Android 6 & 8 devices and on one Android 7 device and also had no problem using OMEMO.
So until now it looks like a problem on devices running Android 5.1 and maybe older.

#### Debug output

2018-10-10 10:00:41,INFORMATION,Timeline,Android-System,Timeline: Activity_windows_visible id: ActivityRecord{33eef5b6 u0 eu.siacs.conversations/.ui.ConversationsActivity t27968} time:27703418
2018-10-10 10:00:44,DEBUG,conversations,Conversations,AxolotlService (stp@jabber.at): Finding devices without session for someone@jabber.at
2018-10-10 10:00:44,WARNING,conversations,Conversations,AxolotlService (stp@jabber.at): Have no target devices in PEP!
2018-10-10 10:00:44,DEBUG,conversations,Conversations,AxolotlService (stp@jabber.at): Cache miss: 40f4b65b-e124-4372-8e5f-e778096e5e8a
2018-10-10 10:00:44,WARNING,conversations,Conversations,AxolotlService (stp@jabber.at): Failed to encrypt message: java.security.InvalidAlgorithmParameterException: Expected IV length of 12 but was 16

**Comment by ghc2018** [comment]
Can confirm this bug on Android 5.1 on a Wiko Rainbow Jam Smartphone.

This bug isn't present on my Samsung Tab 10.1 running Android 7.0.

**Comment by tapete** [comment]
I also can confirm this bug on android 5.1.1. I erroneously thought this problem was related to ISN. After 5 hours of troubleshooting in prosody I found out that unencrypted messages work fine. I tried to reset all omemo keys but it did not help. I deinstalled conversations and installed the older 2.3.0 version but this also did not help. Then I installed conversations legacy and this worked fine.

**Comment by iNPUTmice** [comment]
Possibly fixed in 409bf3c0cbf0a33e08819bb858cfcb6489f6fb5b

**Comment by AxeemHaider** [comment]
yes, it's the problem due to the length of IV in different devices. I solved it myself and send a change request. Hope it will available soon. You can check it here https://github.com/siacs/Conversations/pull/3227
This is working fine in my device

**Comment by zuglufttier** [comment]
Can confirm this problem with a client on Android 5.1.1. Will there be a new version soon?

**Comment by STPKITT** [comment]
I certainly hope so, I'm currently bound to Gajim.

**Comment by licaon-kter** [comment]
Already released on F-Droid too.

**Comment by STPKITT** [comment]
Thanks for that information, it's indeed available now and I tried sending and receiving OMEMO messages and it all seems to work fine again. I'd say this issue can be closed then but I'll leave that decision to the bosses :-)

**Comment by licaon-kter** [comment]
@STPKITT close it if fixed

**Comment by STPKITT** [comment]
Well I can only test on Android 5.1, but the issue also affected Android 6 AFAIK.
