### ISSUE TITLE
XmppConnectionService.java line 1675 is type error

### ISSUE THREAD

**Issue by geniewin** [siacs/Conversations#3229]
XmppConnectionService.java line 1675 is type error ,one of "c" is "contact"

	public List<Conversation> findAllConferencesWith(Contact contact) {
		ArrayList<Conversation> results = new ArrayList<>();
		for (final Conversation c : conversations) {
			if (c.getMode() == Conversation.MODE_MULTI
					&& (c.getJid().asBareJid().equals(c.getJid().asBareJid()) || c.getMucOptions().isContactInRoom(contact))) {
				results.add(c);
			}
		}
		return results;
	}

**Comment by wiktor-k** [comment]
Wow, nice catch! Why didn't you submit a PR though?

**Comment by wiktor-k** [comment]
Well `c.getJid().asBareJid().equals(c.getJid().asBareJid()` should always return `true` so in the best case it should be removed, in worst this is a bug.
