### ISSUE TITLE
MUC LIGHT

### ISSUE THREAD

**Issue by DemonH** [siacs/Conversations#3231]
How can I use MOD_MUC_LIGHT in Conversation?

**Comment by licaon-kter** [comment]
This is the [Mongoose IM thing](https://mongooseim.readthedocs.io/en/latest/open-extensions/muc_light/)? If so, like [ejabberd MUC/Sub](https://docs.ejabberd.im/developer/xmpp-clients-bots/proposed-extensions/muc-sub/), it is not supported.

I guess they need to be proper XEPs and bring really nice things too. :)

**Comment by iNPUTmice** [comment]
You can’t.
