### ISSUE TITLE
TLS Negotiation Failed

### ISSUE THREAD

**Issue by Sanyy** [siacs/Conversations#3238]
* **Version:** 2.3.2+fcr
* **Device:** LG K8
* **Android Version:** Android 8.1.0 Stock
* **Server name:** self hosted
* **Server software:** prosody 0.10.2, Valid "Let's Encrypt" cert, TLS 1.2+, CHACHA20 & AESGCM cipher suites only
* **Server Openssl version: OpenSSL 1.1.0h  27 Mar 2018**
* **Installed server modules:** many
* **Conversations source:** F-Droid

After upgrading Conversations from F-droid client can not connect to the server anymore.
Nothing was changed on the server side.
Desktop clients still work. (No server side problem?)

Did not try to downgrade TLS version or change cipher suites. Worked great before with these.

**Comment by licaon-kter** [comment]
Logcat?

**Comment by iNPUTmice** [comment]
Are you using the extended connection settings? Read [my comments here](https://github.com/siacs/Conversations/issues/3224#issuecomment-428780087).

**Comment by Sanyy** [comment]
It was not the SRV record (Did not solve it). Just as i thought it seems Conversations does not support the chosen (or any) DHE suites anymore. Must use EC (prime256v1) on it. 

At least it works again.

This would be a nice feature to see in the future though:
 - Setting the desired ciphers in Conversation from a list like Pidgin does.

Thanks for your help,
Gruß

**Comment by licaon-kter** [comment]
Isn't the whole web moving away from DHE?

You should use these anyway (see ssl-ciphers line): https://mozilla.github.io/server-side-tls/ssl-config-generator/
