### ISSUE TITLE
User is not asked for SD memory access permission when sharing a file in a certain way

### ISSUE THREAD

**Issue by STPKITT** [siacs/Conversations#3248]
#### General information

* **Version:** tested on 2.3.1+fcr & 2.3.4+fcr
* **Device:** Samsung Galaxy S5
* **Android Version:** LineageOS 15.1 (Android 8.1.0)
* **Conversations source:** F-Droid

#### Steps to reproduce

When using a freshly installed Conversations at some point when needed Conversations will trigger the Android confirmation screen where the user is asked if he wants to grant access to the SD memory.
Now I ran into a situation where Conversations does not trigger that confirmation screen when in fact it should do.
I'll explain what I did to experience that situation.
I had setup my account in Conversations, so I had contacts in my roster and I had already chatted with contacts on that Conversations installation.
I then wanted to send a picture to a contact. I did open the gallery app, which in this case was "Simple Gallery", opened a picture and pressed the share icon. Android brought up the sharing screen where it asks the user with which app he wants to share the file. On more recent Android versions like in this case version 8.1.0 Android, in addition to installed apps, also lists contacts from several apps to directly select, so there will also appear contacts from Conversations. When I clicked on such a contact Conversations opened the corresponding 1:1 chat and showed the picture inserted into the message input field. When I clicked to send the picture Conversations *did not* trigger the confirmation screen to grant access to SD memory. Instead it showed the following error message: "Allgemeiner Fehler. Vielleicht hast Du keinen Speicherplatz mehr?"
I then tried sharing the picture via selecting Conversations on the Android sharing screen. That brought up the roster and when I clicked on the desired contact the confirmation screen to grant access to SD memory was correctly brought up.

**Comment by licaon-kter** [comment]
Update to 2.3.4 and retry?

**Comment by STPKITT** [comment]
Forgot that 2.3.4 is the latest. Same result on 2.3.4 though.
