### ISSUE TITLE
Notifcations doesnt come in and missing

### ISSUE THREAD

**Issue by ryanjoejames** [siacs/Conversations#3250]
After the update on 18 October, the notifications does not come in until user open the app.
It took a while for the the texts to appear ( about 6 to 8 lines of short messages) and few lines were not presented.

**Comment by licaon-kter** [comment]
Android version? Device? Disabled battery optimizations for Conversations? Enabled expert-foreground service?

**Comment by ryanjoejames** [comment]
So sorry
here are the details

Android 7.0
Huawei Y7
Battery Optimizations Disabled
Expert-foreground - Disabled

**Comment by ryanjoejames** [comment]
i see.
I will enabled it. 
By the way, do you suggest to install the Google or Frdroid version?

**Comment by licaon-kter** [comment]
> Google or Frdroid version

That's for you to decide... If you use Google services then maybe that's better, since you have Push.

**Comment by ryanjoejames** [comment]
Thank for your help. cheers
