### ISSUE TITLE
Confusing mix of private and direct messages for MUC moderators

### ISSUE THREAD

**Issue by ritzmann** [siacs/Conversations#3257]
#### General information

* **Version:** 2.3.5
* **Device:** Sony Xperia XZ1 Compact
* **Android Version:** Android 8.0 stock
* **Server name:** trashserver.net
* **Server software:** prosody
* **Installed server modules:** 
* **Conversations source:** 

#### Steps to reproduce

1. Log into MUC as moderator
2. Receive private message from an occupant
3. Long press occupant icon in order to reply

#### Expected result

What is the expected output? 

Option to send private message to occupant.

#### Actual result

What do you see instead?

Option to start conversation, i.e. send a direct message to the real JID and not the occupant JID.

As a result, an occupant who sent a private message in a MUC gets a reply to his real JID. That is rather confusing for both parties. I would prefer to stay in the same message channel, i.e. either private message or direct message but not arbitrarily switch from private to direct. I am aware of the issues with private messages and more than once accidentally sent to the MUC instead of private and vice versa but removing the option entirely depending on the role of the occupant is even more confusing.

#### Debug output

n/a

**Comment by licaon-kter** [comment]
Saw this too, +1 on a fix (aka add the whisper option for moderators too)

**Comment by zuglufttier** [comment]
Or if the proposed solution is not feasible, make it very clear that you will directly communicate with the user and expose your real JID.
