### ISSUE TITLE
HTTP Upload max-file-size should be shown in the UI

### ISSUE THREAD

**Issue by marmistrz** [siacs/Conversations#3258]
#### General information

* **Version:** 2.3.5+fcr
* **Conversations source:** F-Droid

Today I came across a situation when the `max-file-size` advertised by a Prosody instance (wiuwiu.de) doesn't match with what the server expect, which results in a mysterious 502 bad gateway error. It'd have spent much less time wondering what it is, if the server info UI displayed the actual max-file-size.

**Comment by licaon-kter** [comment]
Long press -> show error said 502?

**Comment by iNPUTmice** [comment]
I fundamentally reject the idea that Conversations should be a debugging tool for shitty servers. If anything the Compliance Tester at some point could maybe pick up on that.

**Comment by marmistrz** [comment]
@iNPUTmice I agree that Conversations shouldn't be a debugging tool for shitty servers, but there's a difference about debugging shitty servers and finding out that my server is shitty.

Such an information has an additional added benefit that it makes it possible to predict in advance, which files will require simultaneous presence of both contacts. `max-file-size` is a useful information.

Then what's the point of the server info at all?

Should the compliance tester upload a 50MB file (some servers advertise 50MB max slot) on every test? I think it's unnecessary strain on public servers.

**Comment by SamWhited** [comment]
> I agree that Conversations shouldn't be a debugging tool for shitty servers, but there's a difference about debugging shitty servers and finding out that my server is shitty.

This seems like splitting hairs.

**Comment by sebastiansterk** [comment]
@iNPUTmice Thank you for being so polite and respectful.

**Comment by marmistrz** [comment]
@SamWhited First of all, I somehow ended up using Daniel's "terminology" all the way round, which altered the intended meaning. It was more meant as

> I agree that Conversations shouldn't be a debugging tool for shitty servers, but there's a difference about debugging shitty servers and finding out that the server I'm using has some issues to be fixed. 

There's no software without bugs.
If I know that it's a server's issue, then I'll just contact the admin. If I don't know it, I'll end up posting an issue to the Conversations tracker, without knowing that I'm talking to the wrong person, wasting everybody's time. 

If I see that the issue is fixed by the admin, then I have some evidence that the server is well-maintained. If the server issues stay unresolved for months, then it may be a good sign that I should change the server.
If I were the admin, then this would give me an easy way to check if the changes in HTTP Upload configuration are properly propagated.
