### ISSUE TITLE
[FR] Allow manually using Jingle FT / suggest using Jingle if HTTP Upload fails

### ISSUE THREAD

**Issue by marmistrz** [siacs/Conversations#3259]
#### General information

* **Version:** 2.3.5+fcr

#### Steps to reproduce
If HTTP Upload fails, e.g. due to the reason described in #3258, the user is left completely without the possibility of sending files to the contact. If HTTP Upload fails, the user should be able to either manually initiate a Jingle FT instead of a HTTP Upload (the latter still remaining the default) or, alternatively, the app should offer retrying using Jingle.

**Comment by iNPUTmice** [comment]
Closing because I consider #3258 as invalid. Conversations already falls back to jingle if the server is configured correctly.
