### ISSUE TITLE
Feature Request: Warn contact if device is change or sender

### ISSUE THREAD

**Issue by whitetornado** [siacs/Conversations#3261]
currently omemo accept blind a contact what already is verified when he moved to a other device.
This situation can be that the contact is not moved to a other device, but his account is take over by someone else and he can send messages in the name of the contact.
I want a popup if my contact has changed his device and then i can decide to accept it or not.

**Comment by iNPUTmice** [comment]
Disable Blind Trust Before Verification (BTBV) in the expert settings.
