### ISSUE TITLE
Error Message when no xmpp server found

### ISSUE THREAD

**Issue by mat321** [siacs/Conversations#3272]
#### General information

* **Version:** 2.3.5
* **Device:** all
* **Android Version:** all
* **Server name:** wrong one
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Try to login to a non-existant Server. e.g. fkdujfkduf.ff

#### Expected result

Error Message like "Server not found" or "Server not reachable".

#### Actual result

Nothing

**Comment by licaon-kter** [comment]
I can see (after a while) "Server not found", then (rather quickly) it retries.

/close as invalid

**Comment by mat321** [comment]
No message here

**Comment by licaon-kter** [comment]
But? Stays on connected forever?

The message appears but if you're not paying attention it will start trying to connect again...

**Comment by mat321** [comment]
When i click on "weiter" it says "Verbinde..." for about 1 or 2 seconds. Then i can click "Weiter" again, with the same result.

**Comment by mat321** [comment]
Bug just occurs if "über tor verbinden" is active.

**Comment by mat321** [comment]
Not really makes sense.

**Comment by mat321** [comment]
Please reopen.

**Comment by licaon-kter** [comment]
Please attach a logcat.
