### ISSUE TITLE
Add "quicksy" flavoir of Conversations to f-droid app store?

### ISSUE THREAD

**Issue by k3b** [siacs/Conversations#3273]
The main app-flavoir of this app is already available on [f-droid app store](https://f-droid.org/de/packages/eu.siacs.conversations).

Is it possible to add the [quicksy](https://quicksy.im/) app-flavoir that adds support to xmpp partner discovery via telephonenumber as a seperate app to f-droid app store ?

If You as the authors of the quicksy flavoir like to be added you can apply for inclusion at 

* https://gitlab.com/fdroid/rfp/

**Comment by genofire** [comment]
@licaon-kter is already working on it: https://gitlab.com/fdroid/fdroiddata/merge_requests/3935

**Comment by iNPUTmice** [comment]
Unrelated but if 'fdroid people' are reading this; Conversations 2.3.6 an Quicksy were the first release that bumped the targetSdk version to 28 - you should be able to `sed` that back to 25 and not have that annoying notification. Conversations should behave normal with targetSdk=25.

**Comment by licaon-kter** [comment]
Read the commits ;)

**Comment by tuxayo** [comment]
> Unrelated but if 'fdroid people' are reading this; Conversations 2.3.6 an Quicksy were the first release that bumped the targetSdk version to 28 - you should be able to sed that back to 25 and not have that annoying notification. Conversations should behave normal with targetSdk=25.

Will that "annoying notification" affect only the F-Droid build?

it's something about background services that require to display a notification?

**Comment by licaon-kter** [comment]
@tuxayo yes. It's a bit better, but depends on your Android version.
