### ISSUE TITLE
Conversations shows user published avatar instead of internal contact picture

### ISSUE THREAD

**Issue by ghtux** [siacs/Conversations#3278]
#### General information

* **Version:** 2.3.6+fcr
* **Device:** Samsung Galaxy S5
* **Android Version:** Android 8.1 @ LineageOS 15.1
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Open contact details within conversations. 
2. Click on the picture. Contact avatar in conversations doesn´t use Androids internal one and can´t be changed.

#### Expected result

If there is no picture for the contact, the published avatar should be displayed. Otherwise show internal picture.

#### Actual result

Can´t change contact picture shown within conversations.

**Comment by iNPUTmice** [comment]
Yes this has changed in 2.3.6 and was a deliberate change.

**Comment by imolein** [comment]
I agree with @klemens. Most of my contacts don't have an avatar set, so it was nice that the pictures from my phone book were shown, where I have set up picture at least for my personal friends.

Why don't add an option where the user can choose whether or not use the avatar from the phone book.

**Comment by iNPUTmice** [comment]
@imolein the change should not remove phone avatars entirely but just preference server over phone. So if your contacts don’t set an avatar on the server the phone avatar should be shown.

**Comment by imolein** [comment]
@iNPUTmice Ah yes, you're right. Sorry, I've seen this wrong...

But still it would be nice to choose between the avatars, so I can use the one from my phone book. The benefit (at least for me) is to have the same face in different apps where I have contact with this person (for example Email, other messaging programs).

**Comment by zimbelstern** [comment]
I would appreciate a choice, too.
Not everyone has an avatar set. The link with the address book can provide an fallback option. Currently, this means that you can't see the XMPP avatars anymore or you have to link only a subset of contacts – who can change their minds about adding an avatar later and you'll never know.
In my opinion, avatars are a key feature of a chat protocol. Users set their avatars to share the image with their contacts. Avatars should be respected and not be overwritten by a client.
