### ISSUE TITLE
UI: "End this conversation" vs "Clear history" is unclear

### ISSUE THREAD

**Issue by kousu** [siacs/Conversations#3281]
I always confuse "End this Conversation" and "Clear History". Every single time I go to use them I need to think and remember which is which.

Usually I find myself wanting "Clear History" + "End this conversation afterwards": that is analogous to the Delete button in most messengers; call this the "janitorial" case.  Sometimes but very very rarely do I want to "Clear History" + "~End this conversation afterwards~"; call this the "sensitive data" case. I **never** want "~Clear History~" + "End this conversation" because that keeps hidden state that I will forget about. (and the "~Clear History~" + "~End this conversation~" case is just not pressing any button).

But, though it's the worst one, I almost always accidentally trigger the third case. Conversations is programmed to pop a modal dialog on "Clear History" that makes "End this Conversation" an optional subtask of it, but my intution always tells me that "Clear History" is a subtask of "End this Conversation" so I tap the latter and then swear at myself.

Plus "End this Conversation" doesn't prompt for confirmation so it's quick to make the mistake, and then it's hard to undo because that requires remembering the JID I just wiped restarting/reopening a new conversation with it, finding the menu item again, and re-remembering which of the two options is the one I want.

I am training myself to ignore "End converation" and always use "Clear history", but I keep stumbling and I doubt I'm the only one with this confusion.

#### General information

* **Version:** 2.3.6+fcr
* **Device:** condor
* **Android Version:** LineageOS 14.1.
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Tap on a conversation/chat
2. Tap the menu
3. See "End This Converation" and "Clear History"
4. Either:
    a. Tap "Clear History" -> prompted with a modal that includes the "End this conversation afterwards" option conversation is wiped but still active _**or**_
    b. Tap "End This Conversation" item -> coversation is wiped without confirmation

#### Suggestion

Unify these operations into a single "Delete" button, to make the "janitor" case easy.

For the rare times I want to do the "sensitive data" case, I can press "Delete" and then restart a conversation with a person.

The XMPP protocol doesn't even transmit when a conversation window is open or not, so why bother making the the distinction in the UI?

Groupchats throw a wrench in my suggestion: they tend to be busier and I might want to do a sensitive data wipe in them without leaving. But having to rejoin or recreate in order to wipe data isn't the end of the world.

##### Addendum

I see that this was suggested in #2402 before and didn't get any traction there. To respond to the issue raised there: almost every Android messenger behaves like this, with a single Delete button. WhatsApp, Facebook Messenger, Signal, the default SMS apps that ship with ROMs, they all have a single deletion option.

**Comment by rozzin** [comment]
>  I never want !"Clear History" + "End this conversation" because that keeps hidden state that I will forget about.

I do fine the "end" terminology confusing: "close" seems more appropriate; "end" sounds much more `fatal' (like "delete this conversation") and makes me afraid that it will also "clear history", which (unlike @kousu ) is actually something that _I never want to do_....

In fact that's exactly the reason that I _do_ want to keep the history: so that I can "forget about" it when I don't care about it, but still have the logs available when I do remember them (either when I specifically remember a conversation that I want to look up, or when I remember some fragment of something that was said and want to search through the logs to recall specifically what was said, when it was said or in what context).

Maybe the terminology makes more sense in other language, and it's just a translation issue.

> Conversations is programmed to pop a modal dialog on "Clear History" that makes "End this Conversation" an optional subtask of it, but my intution always tells me that "Clear History" is a subtask of "End this Conversation" so I tap the latter and then swear at myself.

That does sound very much inline with my tendency of "end this conversation" as "delete this conversation" that I described above. Just the slight change in terminology from "end" to "close" or "hide" would fix it for me....

**Comment by licaon-kter** [comment]
Are you stuck on 2.2.5? 2.3.6 is out, refresh your F-Droid repos ;)

**Comment by kousu** [comment]
@rozzin It isn't "clear history" that destroys the conversation, it's "end conversation". It's just that the first triggers the second (usually, maybe).

This is exactly the sort of confusion I hope to see addressed in this issue.

**Comment by licaon-kter** [comment]
@kousu yes, the timing is strange, it's a bug I guess https://gitlab.com/fdroid/fdroidclient/issues/1623


@rozzin Didn't say it's different ;)

@kousu "Clear History" deletes your messages from the device, with OMEMO encryption there is no turning back.

"End conversation" just closes the view, go in your roster and find the id, open  the chat and there it is, all your chat history.

Don't mix them up. Don't put the destructive option first, actually as rozzin above I would like the delete option to be even more hidden.
