### ISSUE TITLE
The Bigg Fingerprint Problem 

### ISSUE THREAD

**Issue by black8x** [siacs/Conversations#3282]
Hi All,

I was reading this blog http://blogs.fsfe.org/vanitasvitae/2018/09/07/future-of-omemo/, and I agreed with the writer on many points.

> OMEMOs trust management (still) sucks. One architectural key feature of OMEMO is, that every device does have its own identity key. If a user wants to send a message to one of their contacts, they’re presented with a list of all of their identity keys. Now they have to decide, which keys to trust and which not by comparing fingerprints (seamingly arbitrary strings of 64 characters). This is not a very comfortable thing to do. Some clients encourage the user to verify your contacts devices by scanning QR-Codes, which is way more comfortable, users do however have to meet up in person or share the QR code on another channel.
> But what if you get a new device or just reinstall your chat application? Suddenly all your contacts have to decide whether to trust your new fingerprint or not. In the long run this will lead to the user just being annoyed and blindly accepting new fingerprints, ruining the concept of end-to-end encryption.
> 
> Daniel Gultsch introduced the concept of BTBV (Blind Trust Before Verification) which can be summed up as “do not bother the user with encryption and hope everything goes well until the user explicitly states that they are interested in having good security”. The principle is, that clients blindly trust any OMEMO identity keys until the user commits to verifying them manually. This makes OMEMO easy to use for those who don’t really care about it, while offering serious users who depend on it the needed security.
> 
> But what do you do, if suddenly a rogue fingerprint appears? Do you panic and message all your contacts not to trust the stranger key? In theory any device which has access to the users account (the users server too) can just add another OMEMO identity key to the users list of devices and there is not really anything the user can do about it. OMEMO does not have a “blacklist”-feature or a signed list of trusted keys. It would however be possible to implement such thing in the future by combining OMEMO with OpenPGP for example. Of course, if some stranger has access to your account, it is time to change the password/server anyways.
> 
> Another weakness of OMEMO is, that it is currently only usable for encrypting the messages body. Since XMPP is an extensible protocol with other use cases than messaging, it would be nice to have support for arbitrary extension element encryption. There is however the extension protocol “OX” (XEP-0373: OpenPGP for XMPP), which has such capabilities. This feature can be extracted from OX and reused in OMEMO relatively easy. 

---------------------------------
I agreed with the fingerprint part, there must be another way to verify a fingerprint, with qr code it is difficult to verify someone who is on the other side of the world.

Why not a code that must match together for verification, you have a part of the code and the other side has a part of the code.

For example, by sending a voice memo to each other, you verify this code. 

-------------------------------
Also whether or the user removes his or her own previously used key, instead of turning it off, it is actually removed everywhere. And is never usable again.

All contacts in his roster must receive a message that the fingerprint has been changed. And this contact must be re-verified.
---------------------------------

And I like to see a module written in lua for prosody, omemo_only. Users of the server can only use omemo, no otr, if no enryption is applied the chat should not work.

-----------------------------------------

I wonder what people think of my ideas, this problem should in my opinion be resolved quickly.

**Comment by iNPUTmice** [comment]
Hi,

thank you for your feedback. I have read all of it and I agree for the most part. Let me ensure you that the OMEMO are constantly working on improving OMEMO.

If you actually want to **work** on OMEMO as well i encourage you to join our group chats and get to know the other OMEMO developers.

However this issue is too vague and also not directly specific to Conversations to act as an issue

**Comment by black8x** [comment]
Oke thank you, I hope to see some changes soon
