### ISSUE TITLE
Feature request: Account info in send field?

### ISSUE THREAD

**Issue by r4dh4l** [siacs/Conversations#3284]
Hi,

using multiple accounts it is sometimes a little bit confusing which account is in use. Would it be possible to indicate the account in use by exchanging

```
Send OMEMO encrypted/unencrypted message
```

with

```
Send OMEMO encrypted/unencrypted with user@example.com
```

?

**Comment by licaon-kter** [comment]
/duplicate https://github.com/siacs/Conversations/issues/3074
