### ISSUE TITLE
Conversations does not show server error messages

### ISSUE THREAD

**Issue by allo-** [siacs/Conversations#3285]
Conversations does not show server error messages. When I tried to send a message to a user on a server with some trouble, I got no feedback about it, except for the missing checkmark.

Gajim shows me the error message:

    Error sending the message ( Server-to-server connection failed: connection-timeout )

which explains, why the message does not arrive.
#### General information

* **Version:** 2.3.6+pcr
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Send a message to a user, when their server is not reachable.
2. Look into your server log and see the error.
3. Look into the gajim window and see the error.
4. Look at conversations, which does not show the error.

#### Expected result

Either parsing the error and showing some useful information about it, or showing the raw error text.

#### Actual result

Nothing

**Comment by iNPUTmice** [comment]
Did you send the message using Gajim? The error message is only routed to the client that sends it.

**Comment by allo-** [comment]
I sent it with gajim. Later I sent a message in Conversations to test, but I think it got through.
Does the server try again for a while?

**Comment by iNPUTmice** [comment]
> Does the server try again for a while?

No once a message is bounced back that way your own server wont try again.

For messages send via Conversations you can trigger a resend.

> I sent it with gajim.

That explains why the error didn’t show up in Conversations.
