### ISSUE TITLE
Question about photo transfer with omemo and proxy65

### ISSUE THREAD

**Issue by black8x** [siacs/Conversations#3286]
Hi,

I have question about the file transfer with OMEMO, is this also fully encrypted when it goes trough proxy65 with prosody ?

https://prosody.im/doc/modules/mod_proxy65

Thank you for a good answer.

**Comment by licaon-kter** [comment]
They're encrypted before they leave de device, yes.

**Comment by iNPUTmice** [comment]
Yes it is. For future questions please use our chat room. This is not a forum but a bug tracker.
