### ISSUE TITLE
Avatar availabilty

### ISSUE THREAD

**Issue by meaz** [siacs/Conversations#3290]
#### General information

* **Version:** 2.3.7
* **Device:** Galaxy s4 mini
* **Android Version:** Lineageos 15.1
* **Server name:** self hosted
* **Server software:** prosody trunk
* **Installed server modules:** mod_vcard4 mod_vcard_legacy
* **Conversations source:** F-Droid

#### Actual result

Avatars uploaded with Conversations are not accessible to people not in the contact list, so if people are not in your contact list, you can't see their avatar in a MUC and there is nothing you can do about it.

#### Expected result

It would be nice to:
- either Conversations makes avatar explicitly available to everyone by default, which would be the best option for usability.
- or Create an option in Conversations so that the user can set his/her avatar available to everyone, would be better for privacy.

**Comment by iNPUTmice** [comment]
Fixed in 1de385dcb9e29164d91977423259ca985f4c042a
