### ISSUE TITLE
Group not Found

### ISSUE THREAD

**Issue by black8x** [siacs/Conversations#3292]
Hi,

With the latest versions and also with the previous versions from conversations.

I can not make Group chat.

When creating in the app a new group chat, and invite people then i get the error group not found.

Using prosody  0.11

**Comment by iNPUTmice** [comment]
I suggest you use the compliance tester to configure your server correctly.

**Comment by black8x** [comment]
How to ?

**Comment by iNPUTmice** [comment]
https://compliance.conversations.im/add/

**Comment by black8x** [comment]
Also possible with .onion ? Tor?

**Comment by iNPUTmice** [comment]
No. By the way I told you in your last issue that this is not a support forum. Please use our group chat if you have questions.

**Comment by black8x** [comment]
oke wtf?

**Comment by black8x** [comment]
nevermind
