### ISSUE TITLE
No notifications since update to 2.3.7

### ISSUE THREAD

**Issue by jaromanda** [siacs/Conversations#3293]
#### General information

* **Version:** 2.3.7+pcr
* **Device:** Samsung Galaxy A5 (2017)
* **Android Version:** Android 8.0.0 Stock
* **Server name:** self hosted
* **Server software:** prosody 0.11.0
* **Installed server modules:** csi_simple, mam
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Receive message when Conversations is not in foreground

#### Expected result

Notification sound, and a (1) on the conversations icon, maybe something in the notification bar

#### Actual result

Nothing, no sound, no indicator, nothing in the notification bar

This worked up until the update 3 days ago

**Comment by licaon-kter** [comment]
Picture with Notification settings for Conversations?

**Comment by jaromanda** [comment]
Nevermind

Reverted to 2.3.6, problem persists

Sorry for wasting your time

**Comment by jaromanda** [comment]
Just as an FYI - the issue is with the CSI_SIMPLE module in Prosody - I happened to enable that at the same time as Conversations was updated - removing the module fixed my issue

**Comment by caffeinejolt** [comment]
Btw - csi_simple does cause problems with conversations notifications - just ran across this - however... the csi module works fine - there may still be some battery savings with running just csi.  I am not really familiar with what the simple version does - but it loads csi and then evidently makes things simple :-)
