### ISSUE TITLE
Messages not sent/receiced to/from *all* devices

### ISSUE THREAD

**Issue by sledz** [siacs/Conversations#3295]
#### General information

* **Version:** 2.3.7
* **Device:** Fairphone FP2
* **Android Version:** Fairphone Open 18.10.0 (Android 7.1.2)
* **Server name:** jabber.in-berlin.de
* **Server software:** unknown
* **Installed server modules:** unknown
* **Conversations source:** F-Droid

#### Steps to reproduce

Account A has two devices A.1 and A.2

OMEMO enabled

- Case a: Account B sends message to A
- Case b: Account A sends message to B from A.1
- Case c: Account A sends message to B from A.2

#### Expected result (probable till 2.3.6)

- Case a: A receives message at A.1 and A.2
- Case b: B receives message
- Case c: B receives message

#### Actual result (probable since 2.3.7)

- Case a: A receives message at A.1 but not at A.2
- Case b: B receives message
- Case c: B does not receive message

No error messages or warnings.

**Comment by licaon-kter** [comment]
Do they all have all the keys ok?

**Comment by sledz** [comment]
Yes.

Until a few days before (I assume the day the update from 2.3.6 to 2.3.7 was made) everything worked well. 

And another interesting information: without OMEMO encryption the messages were transferred without problems to/from all devices.

BTW: Upon request, the server operator has stated that there were no configuration changes in the period in question.

**Comment by iNPUTmice** [comment]
This has nothing to do with the update from 2.3.6 to 2.3.7 - this update didn’t contain any changes relevant to OMEMO. It sounds like a2 is the problematic device here. Maybe the omemo sessions on that device have gotten out of sync. (Possibly for example due to restoring a backup incorrectly). You can go to the expert settings on device a2 and reset your omemo identity.

**Comment by sledz** [comment]
The update from 2.3.6 to 2.3.7 was just an assumption.

I'll try resetting the OMEMO identity and will report the result later.

**Comment by iNPUTmice** [comment]
Current `master` has an experimental self healing feature that should fix the situation.

**Comment by sledz** [comment]
Just for your information: Resetting the OMEMO identities has fixed the problem. But I do not have any ideas what has caused it.
