### ISSUE TITLE
Group chat join (automatically join bug?)

### ISSUE THREAD

**Issue by evilblackeye** [siacs/Conversations#3297]
#### General information

* **Version:** 2.3.7
* **Device:** PIxel 2
* **Server software:** prosody 0.11-14

------------------------------------------------
When option "Automatically join group chats" has been disabled,  you still automatically join the group chat even when disabled. 

Fix Pls : Maybe good idea to add a button accept or reject group chat, to prevent possible spam

**Comment by iNPUTmice** [comment]
The expert option refers to bookmarks. And it also doesn’t influence chats that are already open.
