### ISSUE TITLE
Group chat notification not hidden

### ISSUE THREAD

**Issue by evilblackeye** [siacs/Conversations#3298]
#### General information

* **Version:** eg 2.3.7
* **Device:** Pixel 2
* **Server software:** Prosody 0.11-14
--------------------------------------------------------

The pop-up notification when a message come's in is not hidden(content), as is the case with normal messages.

Content of incoming messages can be read immediately, please also make them hidden, as normal messages.

**Comment by iNPUTmice** [comment]
I think there is no difference between group chat and 1:1 in regards to notifications. Hiding the text is not supported. But there is a feature request for this already.
