### ISSUE TITLE
Is it still safe to use older versions of Conversations via f-droid archive on Android 4.4 KitKat?

### ISSUE THREAD

**Issue by github-userx** [siacs/Conversations#3299]
The newer versions of Conversations apparently aren't compatible with my KitKat devices anymore. 

Or should KitKat users use ConversationsLegacy? (I don't need OTR but just OMEMO)

https://f-droid.org/app/eu.siacs.conversations.legacy

**Comment by licaon-kter** [comment]
Safe in what way? Yes, in theory you might be more in danger using that old Android version (so many unfixed CVEs) than from Conversations per se.

**Comment by iNPUTmice** [comment]
There are currently no known security issues with Conversations Legacy. Conversations Legacy will _probably_ receive security updates if there is ever something significantly wrong with it. (And when it is not really really complicated to fix.)
You might want to follow me on twitter (@iNPUTmice) to stay up to date with security update information.
