### ISSUE TITLE
Different Server than in Jabber ID Domain?

### ISSUE THREAD

**Issue by BuddyButterfly** [siacs/Conversations#3300]
Hi,

where to configure a different xmpp server than the domain part of the jabber id?
hostname!=domain?

**Comment by iNPUTmice** [comment]
Exepert settings; Enable advanced connection options.

**Comment by BuddyButterfly** [comment]
Ah cool, will try. Was really searching for this setting. Do not know, why I did not find it!
Thanks a lot! Issue solved!
