### ISSUE TITLE
Get landline phone numbers listed quicksy.im

### ISSUE THREAD

**Issue by nieselregencom** [siacs/Conversations#3301]
You can also register landline numbers with WhatsApp (see [1][2]). I would love it if Quicksy copied this feature from WhatsApp as well. Since Twilio's Verify API supports both SMS and automated voice calls to verify phone numbers[3], the effort should be limited.

---
[1] Whatsapp jetzt auch mit simquadrat moeglich
    https://www.sipgate.de/blog/whatsapp-jetzt-auch-mit-simquadrat-moglich

[2] "Choose the Call me option to request the call. When you answer the call, an automated voice should tell you the 6-digit code."
    https://faq.whatsapp.com/en/android/20970873/?category=5245245

[3] Verify Phone Verification API
    https://www.twilio.com/docs/verify/api/verification

**Comment by iNPUTmice** [comment]
Are you primarily talking about the directory or the app itself?

**Comment by nieselregencom** [comment]
I meant the directory.

I just didn't know how else to submit an feature request for the directory.

**Comment by iNPUTmice** [comment]
Call verification has been implemented into the Quicksy directory.
