### ISSUE TITLE
http upload gives error and fails

### ISSUE THREAD

**Issue by c0t0d0s2** [siacs/Conversations#3302]
#### General information

* **Version:** 2.3.8+pcr
* **Device:**  Google Pixel 2XL
* **Android Version:** Android 9.0 stock
* **Server name:** Self-hosted
* **Server software:** Prosody 0.10.2
* **Installed server modules:** http_upload
* **Conversations source:** PlayStore

#### Steps to reproduce

1. try and send an image via http upload

#### Expected result

What is the expected output? 
Expected that image gets sent

#### Actual result

What do you see instead?
"Delivery failed"
when you click to see error message, you get:
"Cleartext HTTP traffic to (http_upload server) not permitted."

Other users with the same version of conversation on android 7.x do not get the message.

Unfortunately I cannot post debug output at the moment, but apparently the following is now required if this is going to be used:

```

 <network-security-config>
    <base-config cleartextTrafficPermitted="true" />
 </network-security-config>
```

**Comment by iNPUTmice** [comment]
I can highly recommend that you enable HTTPS on your HTTP-Upload. There will come a point where Conversations will disable support for HTTP independently of OS configuration.
