### ISSUE TITLE
[Feature request] XEP-0201 - Threads

### ISSUE THREAD

**Issue by cmrd-senya** [siacs/Conversations#3303]
I propose to implement support for replying to specific threads in Conversations as defined in [XEP-0201](https://xmpp.org/extensions/xep-0201.html).

According to XEP-0201 it is possible that a remote XMPP entity that you communicate with sends a message with a thread identifier. For usual one-to-one chats supporting threads would normally mean inclusion of the same thread ID as in the message you're replying to (normally, the last received message).

In order to support this, we should save the thread ID which we receive as a part of a message as a current thread ID.

However what makes threads useful is the ability to reply to an arbitrary message with a different thread ID than the current one.

In terms of UI I can see this as following basic change.

When there is a message in our chat log which has a different thread ID from the current thread ID we show an action in the context menu of this message which offers to reply to this thread.

Example (sorry for a lousy mock up): 

![-nez9bp4rhygsgcctqovzw_9b3e417e37](https://user-images.githubusercontent.com/10187586/49596813-db4ba580-f983-11e8-9ae2-641752947d24.jpg)

When user selects "Reply to this thread" the current thread ID is set to the thread ID of the selected message. If there is no thread ID available or thread ID is the same, Conversations should not display this context menu option.

Other useful things may be achieved with threads. For instance we can show "in reply to" hint in message when message contains a different thread ID from the current one. Or we can add "Show the thread" feature which would open the chatlog for the specific thread. But as for now (for a specific project I have in mind) having a "reply to the thread" menu action would be valuable on its own.

Is it possible that Conversations would want to have this feature?

**Comment by cmrd-senya** [comment]
I originally posted a comment at #3125, but these are quite different IMO, so I thought it deserves a separate request

**Comment by licaon-kter** [comment]
Indeed... Carry on.... ;)

**Comment by iNPUTmice** [comment]
I don’t think we want to go down the thread rabbit hole; especially with the constraints of a mobile UI. However some people are currently work on message references.

**Comment by cmrd-senya** [comment]
> However some people are currently work on message references.

What exactly are the message references? Is it something specified?

How about at least supporting of sending back the received `<thread>` identifiers in reply? This wouldn't require any additional UI.

**Comment by lifranc** [comment]
@iNPUTmice  What about the non-threaded conversations rabbit hole, especially on a mobile device.
Went around the block for the past few days looking for a way to collaborate openly; xmpp is the only viable route. But there are no threaded clients. I mean, look at us, fucking retards still using github! Where is our dignity!?

**Comment by Octothorn** [comment]
I understand Movim has announced XEP-0201 as of today.

https://nl.movim.eu/?node/pubsub.movim.eu/Movim/reply-to-chat-messages-a-new-movim-feature-coming-soon-dB0P1v
