### ISSUE TITLE
Hide dynamic tags if account not connected

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#3307]
2.3.8 F-Droid

Steps:
* enable "show dynamic tags"
* connect
* look at contact details/roster see "online", "busy", etc
* turn off Wi-Fi & mobile data

Expected result:
* don't see any tags

Actual result:
* everyone has "online", "busy", etc tags

**Comment by iNPUTmice** [comment]
I do not agree with the assumption that this is expected behaviour.
