### ISSUE TITLE
[Android 9] Notifications don't show avatar

### ISSUE THREAD

**Issue by moppman** [siacs/Conversations#3310]
#### General information

* **Version:** 2.3.10 +pcr
* **Android Version:** stock Android 9 on a Xiaomi Mi A2 (Android One)
* **Server name:** self hosted
* **Server software:** prosody trunk
* **Conversations source:** Play Store

#### Steps to reproduce

1. Get notification from a contact with an avatar

#### Expected result

Sender's avatar is in the notification

#### Actual result

What do you see instead?

Instead of the sender's profile pic, a placeholder pic with the initial of the sender's nick is shown

**Comment by licaon-kter** [comment]
I'm seeing the avatar just fine here on AOSP Pie.

**Comment by licaon-kter** [comment]
Funny, what makes it official?

How did you add the contact? Through Conversations or from phone address book?

**Comment by moppman** [comment]
By "official" (notice notice the quotes) I just meant that it's the unmodified rom the phone comes with. The issue is the same for all my contacts, no matter if they've been linked via phone book or added from within Conversations. Sat Dec 15 21:39:33 GMT+01:00 2018 Licaon_Kter <notifications@github.com>: Funny, what makes it official? How did you add the contact? Through Conversations or from phone address book? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by iNPUTmice** [comment]
Haven’t received the Android 9 update for my Mi A1 yet. In the meantime maybe a screenshot would be nice.

**Comment by moppman** [comment]
>In the meantime maybe a screenshot would be nice.

Thanks for replying, Daniel!
Screenshot:
[![Bild screenshot_20181216-1wxchu.jpg auf abload.de](https://abload.de/img/screenshot_20181216-1wxchu.jpg)](https://abload.de/image.php?img=screenshot_20181216-1wxchu.jpg)

**Comment by licaon-kter** [comment]
Right...so it worked fine on 2.3.9 seeingmthis "error" on 2.3.10+fcr.... #makenotificationiconsgreatagain

**Comment by licaon-kter** [comment]
Of note, the letter is lower case while the generated avatars (XEP-0392) are (normally?) upper case.

**Comment by iNPUTmice** [comment]
I still don’t have Android 9 to test this properly. But 835c89328d44e81525b1d402090bfe48987cd26f is an attempt that you @moppman can check out.

**Comment by moppman** [comment]
Thanks Daniel. I don't have a build environment atm, though, but I will report back as soon as the next beta hits the store.

**Comment by licaon-kter** [comment]
And another note, it only happens in MUCs, 1:1 still shows them ok.

@iNPUTmice I'd build like I always do, but these days [changing Id](https://github.com/siacs/Conversations/blob/master/build.gradle#L83) does not do anything anymore :(

**Comment by moppman** [comment]
> And another note, it only happens in MUCs, 1:1 still shows them ok.

Can't confirm, they don't show at all for me.

**Comment by licaon-kter** [comment]
Looks like straight gradle build generates the app ok, with the changed ID.

@moppman Try this APK (app name and ID is different, so it won't mess your Conversations): 
[testapk.zip](https://github.com/siacs/Conversations/files/2734880/testapk.zip)

**Comment by licaon-kter** [comment]
Some tests with users with avatars:

* 2.3.10 -> HEAD 1:1: no avatar, no icon, blank space

* 2.3.10 -> HEAD MUC: no avatar, no icon, blank space

* HEAD -> 2.3.10 1:1: avatar shown

* HEAD -> 2.3.10 MUC: lowercase letter in generated icon

* HEAD -> HEAD 1:1 & MUC: no avatar, no icon, blank space

**Comment by moppman** [comment]
Thanks for your effort, @licaon-kter !
I, too, was able to compile from current git head:

> HEAD -> 2.3.10 1:1: avatar shown

This is different for me: it's lowercase letter in generated icon, so no difference to how it looked before https://github.com/siacs/Conversations/commit/835c89328d44e81525b1d402090bfe48987cd26f

**Comment by licaon-kter** [comment]
Looks fixed in HEAD :+1:
