### ISSUE TITLE
Policy Violation

### ISSUE THREAD

**Issue by Taekus** [siacs/Conversations#3313]
#### General information

* **Version:** 2.3.9+fcr
* **Device:** LG-G7 Thinq (LM-G710TM)
* **Android Version:** 8.0.0 (Kernel 4.9.65
* **Server name:** kode.im
* **Server software:** Prosody (Unknown Version)
* **Installed server modules:** unknown ( https://kode.im/ )
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Put JID
2. Put Password
3. Press Connect

#### Expected result

What is the expected output?
Successful Connection

#### Actual result

What do you see instead?
"Policy Violation"

#### Debug output

`12-17 23:52:01.445 D/conversations(22276): taek@kode.im: connecting
12-17 23:52:01.684 D/conversations(22276): Resolver: [Result{ip='66.175.221.41', hostame='venus.kode.im', port=5222, directTls=false, authenticated=false, priority=10}, Result{ip='173.255.245.243', hostame='io.kode.im', port=5222, directTls=false, authenticated=false, priority=10}, Result{ip='2600:3c01::f03c:91ff:fea1:fff8', hostame='io.kode.im', port=5222, directTls=false, authenticated=false, priority=10}, Result{ip='2600:3c01::f03c:91ff:feae:2ed8', hostame='venus.kode.im', port=5222, directTls=false, authenticated=false, priority=10}, Result{ip='173.255.245.243', hostame='io.kode.im', port=443, directTls=true, authenticated=false, priority=15}, Result{ip='66.175.221.41', hostame='venus.kode.im', port=443, directTls=true, authenticated=false, priority=15}, Result{ip='2600:3c01::f03c:91ff:fea1:fff8', hostame='io.kode.im', port=443, directTls=true, authenticated=false, priority=15}, Result{ip='2600:3c01::f03c:91ff:feae:2ed8', hostame='venus.kode.im', port=443, directTls=true, authenticated=false, priority=15}, Result{ip='173.255.245.243', hostame='io.kode.im', port=5223, directTls=true, authenticated=false, priority=20}, Result{ip='66.175.221.41', hostame='venus.kode.im', port=5223, directTls=true, authenticated=false, priority=20}, Result{ip='2600:3c01::f03c:91ff:feae:2ed8', hostame='venus.kode.im', port=5223, directTls=true, authenticated=false, priority=20}, Result{ip='2600:3c01::f03c:91ff:fea1:fff8', hostame='io.kode.im', port=5223, directTls=true, authenticated=false, priority=20}]
12-17 23:52:01.686 D/conversations(22276): verified hostname null
12-17 23:52:01.686 D/conversations(22276): taek@kode.im: using values from resolver venus.kode.im/66.175.221.41:5222 tls: false
12-17 23:52:01.976 D/conversations(22276): taek@kode.im: TLS connection established
12-17 23:52:02.062 D/conversations(22276): taek@kode.im: protocol=TLSv1.3 cipher=TLS_AES_256_GCM_SHA384
12-17 23:52:02.063 D/conversations(22276): taek@kode.im: error connecting account. try again in 156s for the 8 time. lowPingTimeout=false`

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by licaon-kter** [comment]
Do search the log for "policy" or "violation", wasn't the full stanza written?

**Comment by iNPUTmice** [comment]
The error message is:
```
test@kode.im: policy violation. TLS cipher 'TLS_AES_256_GCM_SHA384' not acceptable
```
You should report this to your server operator.

**Comment by Taekus** [comment]
Perhaps you should re-read my error log, the error message you say is in my log does not exist.

**Comment by iNPUTmice** [comment]
@Taekus I added logging in this commit 9659f46136aab868fe185181912ebd227c03670b and connected to your server with a non existing account to grab the error message for you.
