### ISSUE TITLE
Not building with OpenJDK 11

### ISSUE THREAD

**Issue by pupper68k** [siacs/Conversations#3316]
#### General information

* **Version:** Latest Master, 2.3.10, or 2.3.9

* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. install and configure latest openjdk
2. clone source from this repo
3. `$ ./gradlew assembleConversationsFreeSystemDebug`
4. build fails

#### Debug output
The following link leads to the output of ./gradlew assembleConversationsFreeSystemDebug --stacktrace
https://pastebin.com/1nBTrt4V

**Comment by iNPUTmice** [comment]
Yes I know. Just build it with Java 8.
