### ISSUE TITLE
Problem sending GPX 

### ISSUE THREAD

**Issue by Ji-eF** [siacs/Conversations#3317]
#### General information
* **Version:** 2.3.9+fcr
* **Device:** Motorola G4Plus (athene), Huawei Nexus 6P (angler)
* **Android Version:** LineageOS 14.1 (athene) , LineageOS 15.1 (angler)
* **Server name:** self hosted
* **Server software:** prosody 0.10.2
* **Installed server modules:** standard install + "register"; "watchregistrations"; "limits"; "carbons"; "mam"; "http_upload_external"; "smacks"; "csi"; "pubsub" ; "cloud_notify"; "omemo_all_access";

* **Conversations source:** F-Droid

#### Steps to reproduce
1. Long-click some gpx files (GPS traces from openstreetmap, Favorites points from OSMAnd~, ... which are basically XML files)
2. Click the "Share with..." button, select "Conversation" then a friend or a group
3. The file is ready to be sent via Conversation, click the arrow to actually send it

#### Expected result
The file should be sent.

#### Actual result
I get a red message "Delivery failed"

#### Debug output
````
12-23 14:02:22.126 20731 20731 D conversations: app switched into foreground
12-23 14:02:25.590 20731 20731 D conversations: action: android.intent.action.SEND_MULTIPLE
12-23 14:02:25.591 20731 20731 D conversations: ConversationFragment.saveMessageDraftStopAudioPlayer()
12-23 14:02:25.593 20731 20731 D conversations: reInit(hasExtras=true)
12-23 14:02:25.593 20731 20731 D conversations: trimming conversation
12-23 14:02:25.601 20731 20731 D conversations: scrolledToBottomAndNoPending=true
12-23 14:02:25.601 20731 20731 D conversations: jump to first unread message
12-23 14:02:25.689 20731 20731 D conversations: ConversationFragment.onBackendConnected()
12-23 14:02:31.479 20731 20731 D conversations: AxolotlService (athene_plus@n***.***): Finding devices without session for ji-ef@n***.***
12-23 14:02:31.488 20731 20731 D conversations: ConversationsActivity.commitAttachments() - attaching file to conversations. CHOOSE_FILE/RECORD_VOICE/RECORD_VIDEO
12-23 14:02:31.505 20731 20731 D conversations: received uri permission for content://net.osmand.plus.fileprovider/share/favourites.gpx
12-23 14:02:31.506 20731 20821 D conversations: copy content://net.osmand.plus.fileprovider/share/favourites.gpx to private storage (mime=application/octet-stream)
12-23 14:02:31.506 20731 20821 D conversations: extension from mime type was null
12-23 14:02:31.513 20731 20821 D conversations: copy file (content://net.osmand.plus.fileprovider/share/favourites.gpx) to private storage /storage/emulated/0/Conversations/Media/Conversations Files/abc232fb-5af3-4f21-b9ce-f6ac2031c466.gpx
12-23 14:02:31.522 20731 20821 D conversations: send file message
12-23 14:02:31.645 20731 20830 D conversations: uploading to https://upload.n***.***/share_v2.php/342cb313-1f0e-4283-8dc3-de06121e9c2e/q8Iy-1rzTyG5zvasIDHEZg.gpx?v2=e*** w/ read timeout of 15s
12-23 14:02:32.128 20731 20830 D conversations: http upload failed null
````

I should add that **renaming** favorites.gpx to favorites.txt (for the sake of it) fixes the problem ; the file is sent successfully.
Also, sending the same file from Gajim works fine too, which is why I think there is no problem with my jabber instance.

**Comment by iNPUTmice** [comment]
Looks like a server issue to me.

**Comment by Ji-eF** [comment]
I'll check it some more today. Coincidence, prosody went to 0.11.1 with this night's updates. Thanks for your input, iNPUTmice.
