### ISSUE TITLE
video compression fails / crashes

### ISSUE THREAD

**Issue by toxtox** [siacs/Conversations#3325]
#### General information

* **Version:** 2.3.10+fcr
* **Device:** XT894
* **Android Version:** LOS14.1
* **Server name:** self hosted
* **Server software:** ejabberd 18.03-2
* **Installed server modules:** all modules listed in conversation's "Account details" except XEP-0313 MAM
* **Conversations source:** F-Droid

#### Steps to reproduce

1. choose **1080p** video file, 
2. press send button, 
3. progress bar for video compression appears but it stops at 90 to 99% (depending on file size) with a logcat message (see below)

#### Expected result

compression to the selected "_Video Quality_" "_Medium (**360p**)_" or "_High (**720p**)_"

#### Actual result

video compression fails / crashes (see  logcat message)
The only possibility to send video files is to avoid the video compression by recording only 720p and lower videos and choosing  "_Video Quality_" "_High (**720p**)_"

#### Debug output

> [01-01 14:44:25.466 1839:8456 D/conversations]
> ignoring execution exception. Should get handled by onTranscodeFiled() instead
> java.util.concurrent.ExecutionException: java.lang.Error: Could not shutdown extractor, codecs and muxer pipeline.
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
> 	at eu.siacs.conversations.services.AttachFileToConversationRunnable.processAsVideo(AttachFileToConversationRunnable.java:107)
> 	at eu.siacs.conversations.services.AttachFileToConversationRunnable.run(AttachFileToConversationRunnable.java:165)
> 	at eu.siacs.conversations.utils.SerialSingleThreadExecutor$Runner.run(SerialSingleThreadExecutor.java:58)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
> 	at java.lang.Thread.run(Thread.java:761)
> Caused by: java.lang.Error: Could not shutdown extractor, codecs and muxer pipeline.
> 	at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.transcodeVideo(MediaTranscoderEngine.java:116)
> 	at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:184)
> 	at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:166)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> 	... 3 more
> Caused by: java.lang.IllegalStateException
> 	at android.media.MediaCodec.native_stop(Native Method)
> 	at android.media.MediaCodec.stop(MediaCodec.java:2007)
> 	at net.ypresto.androidtranscoder.engine.VideoTrackTranscoder.release(VideoTrackTranscoder.java:138)
> 	at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.transcodeVideo(MediaTranscoderEngine.java:102)
> 	... 6 more

**Comment by iNPUTmice** [comment]
Yes the video compression is known not to work on some Androids. As long as it falls back to sending the video uncompressed this is a wont fix.

**Comment by toxtox** [comment]
> `Any file size will do this?`

Yes, for version **2.3.10**+fcr, I tried video file sizes of **2MB** and **9.5MB** and **40MB** with same failure
No, for version 2.**2**.8+fcr, because this old version has obviously a **hardcoded filesize-threshold of 10MB** => videos smaller 10MB will be send immediately and will not be compressed. But the compression of video files bigger then 10MB fails the same way.

> `Any resolution?`

It always fails if the video resolution is higher then the chosen "**_Video Quality_**".
examples (version **2.3.10**+fcr):
**1080p**-videos always lead to compression failure, because highest selectable "_Video Quality_" is "_High (**720p**)_"
  **720p** videos always lead to compression failure if you set "_Video Quality_" to "_Medium (**360p**)_"

**Comment by iNPUTmice** [comment]
Can you check if cfab0dbe1b7dcb7b979058ca29d2352ea940ed74 successfully falls back to sending the file in an uncompressed state?

**Comment by toxtox** [comment]
@iNPUTmice 
Yes, the fall-back to uncompressed state is working for me. 
Now with "**_720p_/_360p_**" the progress bar appears, runs along and disappears at 100%, but the result is an uncompressed video file (fall-back).

The difference of the "_**uncompressed**_" option is that the uncompressed video file is send immediately.

But **video compression would be a very useful feature** to save data volume and 360p is just fine for watching on mobile phones ;-)

**Comment by iNPUTmice** [comment]
Seems like video compression doesn’t work on your device. (It’s known that it doesn’t work on all devices) But the important thing is that fall back is working.
