### ISSUE TITLE
Use medium font size by default

### ISSUE THREAD

**Issue by av2k** [siacs/Conversations#3328]
#### General information

* **Version:** 2.3.10
* **Device:** all
* **Android Version:** all
* **Conversations source:** latest HEAD

#### Expected result

Conversations uses the medium font size by default, which is much more friendly to the eye than the small font size.

#### Actual result

Conversations uses the small font size by default.

**Comment by iNPUTmice** [comment]
The so called 'small' font size is the recommended font size when you follow Android design guidelines.
