### ISSUE TITLE
Redesign chat window to make it more screen-space efficient

### ISSUE THREAD

**Issue by av2k** [siacs/Conversations#3330]
#### General information

see #3329

#### Steps to reproduce

Run a group chat in conversations.

#### Expected result

The chat screen should make maximum use of the available screen space to make reading and writing messages as appealing as possible.

#### Actual result

Screen space is wasted by

- redundant display of the avatars of the users in each message
- the display of the username of each user in each message
- the timestamp of each message is displayed in a separate row above the message within the frame for each user's message

#### Possible solutions

see #3329 and additionally:

- show the avatar and username of each user only if the message before his wasn't written by him, meaning that if user A writes a message and then user B writes n messages, the message of user A and only the first message of user B will show his avatar and username, while the other coherent n-1 messages of user B won't show his avatar or username. This also makes the chat more readable, since the Conversations user will see at first glance that the coherent n-1 messages were written by user B, instead of having to re-check for each message

**Comment by iNPUTmice** [comment]
This is a somewhat valid issue but I don’t think we need two separate issues for group chats and 1:1. Since the view should be coherent any redesign needs to happen in both type of views.

**Comment by licaon-kter** [comment]
@av2k Any mock-ups of your thoughts?

**Comment by iNPUTmice** [comment]
I’m closing here for now. Conversations is currently focused on stability rather than new features or redesigns. But your feedback will be Incorporated in some form or another (together with all the other feedback I get) in a possible redesign in 2020.
