### ISSUE TITLE
Contact shortcuts not working

### ISSUE THREAD

**Issue by caffeinejolt** [siacs/Conversations#3331]
#### General information

* **Version: 2.3.10+pcr
* **Device: S9
* **Android Version: 8.0.0
* **Server name: self hosted
* **Server software: prosody latest stable
* **Installed server modules: CSI
* **Conversations source: PlayStore

#### Steps to reproduce

1. Assign a direct shortcut to a Conversations target (i.e. in Nova Launcher)
2. Converstations open prompt to select contact for shortcut
3. I choose the contact
2. Shortcut fails to be created, but works in all other apps I tried (i.e. whatapp, direct sms to contact, etc.)

#### Expected result

What is the expected output? 
I expected that the shortcut to directly chat with Conversatiom's contact would be returned - i.e. works with actions in Nova, like a gesture, or other.

#### Actual result

What do you see instead?
It returns nothing and I cannot utilize the shortcut
This is the screen from which I can open the prompt to select the Conversations shortcut: https://drive.google.com/open?id=1hLT88q_Vk4Mv9LiYy6Z83Cth0kjydiTt

**Comment by licaon-kter** [comment]
Any other launcher works?

**Comment by iNPUTmice** [comment]
I’m unable to even find the 'Choose Action' screen in nova launcher. Creating a widget works fine. In nova and every other launcher i tested.

**Comment by caffeinejolt** [comment]
In Nova, two ways you can get to that menu (possibly others as well):

1) Nova Settings > Gestures & Inputs > Choose any gesture > Shortcuts Tab
2) Long hold any app icon on home screen > Edit icon (pencil) > Swipe action > Shortcuts tab
