### ISSUE TITLE
Media browser preview - show only available files

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#3332]
2.3.10+fcr

Steps:
* open a chat
* look at details -> see last 6 (or whatever, it depends on DPI) files
* enter media browser -> see them all
* send 5 pics from a folder, wait for them to be delivered
* delete the files in the original folder
* disconnect accounts
* close app
* reboot device (so cache gets cleaned)
* restart C, reconnect
* see bubbles with "file was deleted"

What we see:
* open chat details -> see 1 file and 5 empty spaces
* open media browser -> see the rest of the files from the chat (except those deleted from their original location ofcourse)

What was expected:
* open chat details -> see the last 6 files that are available locally

**Comment by klonfish** [comment]
Additionally, if *all* recent files are deleted (all six in your example), the media preview box is hidden completely, including the button to get to the media browser.

I created a PR to fix this issue.

**Comment by iNPUTmice** [comment]
Latest version does that.
