### ISSUE TITLE
XMPP presence priority

### ISSUE THREAD

**Issue by Neustradamus** [siacs/Conversations#3334]
Can you add the XMPP presence priority?
from -127 to +127.

**Comment by iNPUTmice** [comment]
Priority is not needed in a modern XMPP environment.

**Comment by stcktrce** [comment]
How so? I've had issues with messages only showing up on my mobile device, and not on other clients because priorities are messed up.

**Comment by licaon-kter** [comment]
@stcktrce No carbons? No mam?
