### ISSUE TITLE
SCRAM-SHA-1-PLUS is missing (same for SCRAM-SHA-256-PLUS)

### ISSUE THREAD

**Issue by Neustradamus** [siacs/Conversations#3335]
SCRAM-SHA-1-PLUS is missing (from RFC6120)

**Comment by Neustradamus** [comment]
+ From RFC7677: https://tools.ietf.org/html/rfc7677

**Comment by iNPUTmice** [comment]
Please search the issue tracker for existing issues before creating new ones.

**Comment by Neustradamus** [comment]
In the code, there is only:
- SCRAM-SHA-1
- SCRAM-SHA-256

There is not:
- SCRAM-SHA-1-PLUS
- SCRAM-SHA-256-PLUS

Can you add PLUS part?

**Comment by Neustradamus** [comment]
Linked to https://github.com/siacs/Conversations/issues/42
