### ISSUE TITLE
Delay in sending OMEMO encrypted messages

### ISSUE THREAD

**Issue by skumarm** [siacs/Conversations#3338]
#### General information

* **Version:** 
* **Device:** All
* **Android Version:** All
* **Server name:** self hosted
* **Server software:** ejabberd-18.09
* **Installed server modules:** 
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Run a 1-to-1 OMEMO conversation between two users ( Blindly trusted keys ). Send the messages frequently. 

#### Expected result
The OMEMO encrypted chat should be sent immediately from the sender side, as same as in an unencrypted 1-to-1 conversation.

#### Actual result

I am getting a consistent delay in sending these OMEMO encrypted messages.

**Comment by licaon-kter** [comment]
What server hardware?

**Comment by skumarm** [comment]
> What server hardware? Server config (use gist)?

I am a mobile developer. 
What kind of details you want from chat server ?
We are using **ejabberd-18.09** as chat server.

**Comment by licaon-kter** [comment]
Are you modifying Conversations?

**Comment by skumarm** [comment]
> Are you modifying Conversations?
> 
> Since you have issues in [other](https://github.com/ChatSecure/ChatSecure-iOS/issues/1086) clients as well, it would be useful to share on https://gist.github.com the server config

Yes. I have modified Conversations. Also tried to build an app on iphone using ChatSecure-iOS.

Are you talking on the **ejabberd.yml** configuration file ? Please find the configuration file [here](https://gist.github.com/skumarm/e6308006c388b7cc9983acdbdbe98a57)

**Comment by licaon-kter** [comment]
Oh, for app modifications please use the conference.

This is for app issues

/close this

**Comment by licaon-kter** [comment]
@skumarm Please see the updated config template, and please read the info about OMEMO first: https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example

**Comment by licaon-kter** [comment]
READ THE OMEMO NOTE ffs, your setup is wrong

Yes, that conference.

**Comment by skumarm** [comment]
> READ THE OMEMO NOTE ffs, your setup is wrong
> 
> Yes, that conference.

Can you specify the OMEMO Note link ? Is that ejabberd configuration file ?

**Comment by licaon-kter** [comment]
You've said:
> I cross checked with the ejabberd config file with the config template you given

But your config has:
```
"eu.siacs.conversations.axolotl.*":
  access_model: whitelist
```

Didn't you read these 2 lines: https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example#L215

**Comment by skumarm** [comment]
> You've said:
> 
> > I cross checked with the ejabberd config file with the config template you given
> 
> But your config has:
> 
> ```
> "eu.siacs.conversations.axolotl.*":
>   access_model: whitelist
> ```
> Didn't you read these 2 lines: https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example#L215 ???

I canged the configuration as follows already... But still its not working...

    force_node_config:
      ## Avoid using OMEMO by default because it
      ## introduces a lot of hard-to-track problems
      "eu.siacs.conversations.axolotl.*":
        access_model: open
      ## Avoid buggy clients to make their bookmarks public
      "storage:bookmarks":
        access_model: whitelist

**Comment by iNPUTmice** [comment]
I’m closing here. For commercial support please use the email address mentioned in the README on on the website.
