### ISSUE TITLE
Conversations contact shortcuts still not working

### ISSUE THREAD

**Issue by caffeinejolt** [siacs/Conversations#3346]
This is a followup report on #3331 

The shortcut support added resulting from Issue #3331 *does* work as expected if Conversations is/was closed prior calling the shortcut.

However, if Conversations is already open on a different chat contact (any contact other than the one the shortcut references), and you initiate the shortcut, the Conversations app will get pulled into focus on Android, but it will remain on whatever contact previously had focus.  In other words, it does not shift focus to the shortcut target in this scenario.

I believe the expectation in this case is that Conversations would pull up the contact whom was defined in the shortcut.

**Comment by iNPUTmice** [comment]
Please provide the output of `adb logcat -s conversations` during the two scenarios you described and mark in the log which is which.

**Comment by wiktor-k** [comment]
Seems to be working now with the latest flags.

**Comment by iNPUTmice** [comment]
Remember you need to recreate the shortcut to make this work
