### ISSUE TITLE
Permanent notifications still exists in F-Droid 2.3.10+fcr

### ISSUE THREAD

**Issue by 4carlos** [siacs/Conversations#3347]
#### General information

* **Version:** 2.3.10+fcr
* **Device:** Jolla 1
* **Android Version:** Dalvik Android 4.1.2 (API 16)
* **Server name:** self hosted
* **Server software:** ejabberd 
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** F-Droid

#### Steps to reproduce

**You wrote in FAQ's**

_I’m getting this annoying permanent notification
Starting with Conversations 2.3.6 Conversations releases distributed over the Google Play Store will display a permanent notification if you are running it on Android 8 and above. This is a rule that it is essentially enforced by the Google Play Store **(you won’t have the problem if you are getting your app from F-Droid)**.

**However you can disable the notification via settings of the operating system.** (Not settings in Conversations.)_

#### Expected result

No permanent notification.

#### Actual result

I get these notifications periodically.

#### Hint

In Alien Dalvik of SailFish OS it's not possible to turn off notifications.

**Comment by licaon-kter** [comment]
So in Settings - Expert - you can't disable Foreground service?

**Comment by 4carlos** [comment]
No. Disabling as foreground service make Conversations completely silent if I close the App.

In SailFish, Conversations has permission to run in the background, but I only receives notifications when "foreground service" is enabled. As a side effect this annoying and permanent notification appears.

Other Apps like Threema or Deltchat don't show these notifications.

**Comment by licaon-kter** [comment]
Well, how do you expect to get messages when the app is off and you don't have Google Services getting push notification to wake/start the app?

You force close Threema/DeltaChat and they still get messages?

**Comment by 4carlos** [comment]
When Threema and DeltaChat are closed, they continue in the background as service. This can be allowed or forbidden for every single app in SFOS.

Yes, they continue to receive and notify. Google Services does not exist with Sailfish. Presumably, a connection continues via a Websocket.

Conversations also works quite well, only this multiple message is completely unnecessary.

Does this have to be programmed? What is it for?

**Comment by licaon-kter** [comment]
> they continue in the background as service.

This is the point of the notification too, actually not the notification but the foreground service, the notification is just a required thing by Android.

The other option, see other apps, is the split service, I don't have the details why it was not choosen, @iNPUTmice ?

**Comment by 4carlos** [comment]
Why closed?

**Comment by iNPUTmice** [comment]
@4carlos see the commit message of the commit that closed this. e1fe969bcaa7e4927783f202fc16551f26333799 or the updated text in the readme

**Comment by teasus-spiced** [comment]
You have to go to the full notification setting in Android prefs (not the app settings) by swiping the notification sideways to press the cog, then press the cog again - then you can turn it off. It's the option called Foreground service. HTH
