### ISSUE TITLE
F-Droid foreground notification, does not show connected accounts

### ISSUE THREAD

**Issue by genofire** [siacs/Conversations#3352]
#### General information

* **Version:** 2.3.11-fcr
* **Device:** FB2
* **Android Version:** Android 8.1
* **Server name:* self hosted
* **Server software:** -
* **Installed server modules:** -
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Install from F-Droid
2. Enable Foreground Service / Notification
3. Open Androids Notificationbar

#### Expected result

Notification Message should contain `x of y accounts are connected `  like in PlayStore Version

#### Actual result

`Touch to open Conversations`

**Comment by licaon-kter** [comment]
/close as invalid?

There is no 2.3.12 on F-Droid (yet)

And versions are different, ref. https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/eu.siacs.conversations.yml#L1644
