### ISSUE TITLE
Support application/x-www-form-urlencoded message payload (html formatted)

### ISSUE THREAD

**Issue by aslmx** [siacs/Conversations#3353]
Hey,

i was wondering whether conversations would be able to support sending inline images. Gajim does this just fine. 

I'm using Prosody 0.10 with mod_post_msg to be able to use cURL to send a http POST and trigger a message to a recipient.

https://modules.prosody.im/mod_post_msg.html

I'm trying to send photos of my surveillance cam via XMPP. Currently i'm only sending a notification that movement was detected, which is kind of annoying when the neighbours cat visited the garden for the tenth time a day. 
So i have to sftp to my storage, download the mp4 or the autogenerated thumbnail and check out what happened. 

Right now i have a script running that detects new thumbnail files, copies it to www-root and generates a link. That is already some convenience.

I followed this https://cweiske.de/tagebuch/prosody-send-http.htm tutorial and https://stackoverflow.com/a/4198747/4427958 to find out how to send HTML and could succesfully send inline images to Gajim.

My curl call is: 
  curl -v https://myjabberserver.tld:5281/msg/user@myjabberserver.tld -u "bot@myjabberserver.tld:botpassword" \
        -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode "body=Surveillance Notification" \
         --data-urlencode "html=<img src=\"data:image/png;base64,$image_base64\" />"

$image_base64 being the base64 encoded image. 

Also i'm trying to send 

   curl -v https://myjabberserver.tld:5281/msg/user@myjabberserver.tld -u "bot@myjabberserver.tld:botpassword" \
        -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode "body=Surveillance Notification https://web.myserver.tld:10000/surveillance/"$filename".jpg" \
         --data-urlencode "html=<b>Surveillance Notification:</b> <a href=\"https://web.myserver.tld:10000/surveillance/"$filename".jpg\">https://web.myserver.tld:10000/surveillance/"$filename".jpg</a>"
        
Which also works fine with Gajim and produces a clickable link.

Conversation however only shows the body part, so at least the link is parsed into a clickable one.
But the image is apparently not shown.

Is that supported and i'm just doing it wrong (and it works in Gajim by accident..) or is it something which can be easily added to be supported in conversations.

I can think of other generic usecases that might become possible...

Thanks
br
sebastian

**Comment by iNPUTmice** [comment]
Conversations doesn’t support HTML-IM and won’t for the foreseeable future.
I’m not fully aware of what you are trying to do but if you have a thumbnail on `https://host/example.jpg` try sending this:
```
<message to="you">
<body>https://host/example.jpg</body>
<x xmlns='jabber:x:oob'>
    <url>https://host/example.jpg</url>
  </x>
</message>
