### ISSUE TITLE
Messages received while user inactive are out of order (correspondents are on different timezones)

### ISSUE THREAD

**Issue by 9662** [siacs/Conversations#3358]
#### General information

* **Version:** Unknown (problem manifests on remote device, user not aware of version in use)
* **Device:** Samsung, model unknown.
* **Android Version:** Android 7
* **Server name:** Self-hosted
* **Server software:** ejabberd 
* **Installed server modules:** stream management, MAM, others
* **Conversations source:** PlayStore (I presume)

#### Steps to reproduce

* Let user `romeo@example.net` be in Venice, Italy, timezone UTC+0100
* Let user `juliet@example.net` be in Venice, Florida, timezone UTC-0500
* Let the server `example.net` operate in UTC. MAM is enabled on the server.
* Romeo chats with Juliet while both are online. Messages are received and displayed as expected.
* Juliet goes about her business and leaves her phone in her bedchamber. The phone may lose and regain connection to the server intermittently due to network coverage issues.
* In the meanwhile, Romeo continues sending messages to Juliet.
* When Juliet latter takes a look at her phone, she sees in her lockscreen that she has messages from Romeo …
* … but upon unlocking the phone, the messages are not visible in the chat window.
* Eventually, Juliet scrolls back in history in the chat window, and the messages appear out of order, perhaps in the middle of a previous conversation.

#### Expected result

Messages received while the user is online and active, and messages received while the user is away (perhaps via MAM or offline messages?) should be shown in correct chronological order in the chat window.

#### Actual result

Message ordering is messed up when the correspondent's phones are in different timezones.

#### Possibly related (or not)

* #2745 
* https://stackoverflow.com/questions/28037244/iphone-xmpp-offline-message-timestamp-lead-the-chat-list-disorder

*No electrons were harmed in the making of this message*

**Comment by iNPUTmice** [comment]
Messages received from MAM get sorted into the message list according to their time stamp as presented by the server. If this time stamp is wrong your clock on the server is out of sync.
Please provide screenshots sowing the received and sent time (screenshots from sender and recipient showing the same message)

**Comment by 9662** [comment]
The server's clock is NTP-synchronised and running fine. Both hardware and OS are set to UTC.

I'll get some screenshots.
