### ISSUE TITLE
 Feature Request: Exit button

### ISSUE THREAD

**Issue by yoy232** [siacs/Conversations#3359]
Please add a option to exit the application. 
It would be very usefull to exit the application and release the resources for other applications.

**Comment by iNPUTmice** [comment]
Android does a *very* good job at doing this by itself.

**Comment by yoy232** [comment]
Yes, it does good job at doing this by itself, but many developers append this feature to their apps. 
When user don't need the app for longer time, he have the opportunity to end it and he don't need to install any other special apps, which are designed for killing aps, which don't have this feature.
