### ISSUE TITLE
Unable to join a chatroom using IDN in its address

### ISSUE THREAD

**Issue by Sylvhem** [siacs/Conversations#3367]
#### General information

* **Version:** 2.3.12+fcr
* **Device:** Wileyfox Spark +
* **Android Version:** Android 7.0
* **Server name:** self hosted
* **Server software:** prosody 0.9.12 (Debian Stretch's package prosody 0.9.12-2+deb9u2)
* **Installed server modules:** core modules (admin_adhoc, posix…)
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Open Conversations.
2. Click on the green speech bubble icon at the bottom of the screen.
3. Click on "Group conversations".
4. Click on the three dot at the top of the screen.
5. In the menu, click on "Join the group conversation".
6. In the dialog, add a Punycode encoded JID containing an IDN as the conversation's address. For example, `chat@xn--caf-dma.example`.
7. A conversation dialog will open. The error message "Remote server not found" is displayed.

#### Expected result

Connecting to a MUC using an IDN in its JID should work. Once connected, you should be able to send messages to the chatroom.

#### Actual result

When opening the chatroom, an error message saying "Remote server not found" is displayed to the user. If you try to send a message, it'll fail.

#### Debug output

**Comment by Sylvhem** [comment]
> Please provide an actual example.

You can try with `chat@conférence.lepubdelobservateur.fr`.

> Also what happens if you enter the not punycoded jid

Just tried it, and the exact same thing happens.

**Comment by licaon-kter** [comment]
Android log says:
```
unknown error in conference: <presence type="error" xmlns="jabber:client" to="user@domain.tld/Conversations.14m7" from="chat@confￃﾩrence.lepubdelobservateur.fr/Test"><error type="cancel" by="domain.tld" xmlns="jabber:client"><remote-server-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Server-to-server connection failed: host-unknown (This host does not serve confￃﾩrence.lepubdelobservateur.fr)</text></error></presence>
```

And server log says:
```
warning] <0.7255.0>@ejabberd_s2s_out:process_closed:160 Failed to
 establish outbound s2s connection domain.tld -> confÃ©rence.lepubdelobservateur.fr: Strea
m closed by peer: This host does not serve confÃ©rence.lepubdelobservateur.fr (host-unknow
n); bouncing for 230 seconds
```

**Comment by iNPUTmice** [comment]
Looks to me like that host isn’t set up correctly.

**Comment by Sylvhem** [comment]
I can access this chatroom using Dino though. And other people were able to do so.

**Comment by iNPUTmice** [comment]
I’m unable to join `chat@conférence.lepubdelobservateur.fr` with Dino.

**Comment by Sylvhem** [comment]
Sorry, bad timing on my part. My TLS certificate got renewed early this morning and I didn't realized it. So my server was broken.
It is now fixed and you should be able to perform tests.

**Comment by iNPUTmice** [comment]
The error message @licaon-kter posted indicates a miss configured and/or buggy server.

**Comment by licaon-kter** [comment]
@iNPUTmice I wonder why is the `é` mangled?

Logcat does not support it?

Linux log does not support it?

Or Conversations sends it mangled?

**Comment by Sylvhem** [comment]
> The error message @licaon-kter posted indicates a miss configured and/or buggy server.

It may be a server side error, yes. But if it is, I wonder why I still manage to log on to it through Dino.

**Comment by iNPUTmice** [comment]
@Sylvhem what version did you type into Dino?

**Comment by Sylvhem** [comment]
I'm using Dino from Ubuntu packages. It's an old version apparently (0.0.git20180921-1).

**Comment by iNPUTmice** [comment]
> @iNPUTmice I wonder why is the é mangled?

It breaks somewhere in the logging process. But Conversations sends it alright. Note that you can *reach* the server (DNS resolution on your ejabberd works) but then the remote prosody? says the server is not responsible for that domain.

**Comment by iNPUTmice** [comment]
@Sylvhem did you enter the encoded or decoded variant of the domain in Dino?

I assume you entered the punycode variant in the prosody config while it has to be the one containing the special chars.

**Comment by Sylvhem** [comment]
I entered the Punycode version in both Dino and prosody. Didn't seem to work otherwise.
