### ISSUE TITLE
Unable to restore MUC history

### ISSUE THREAD

**Issue by zauli83** [siacs/Conversations#3368]
#### General information

* **Version:** 2.3.12 
* **Device:** Xiaomi MIA1, nokia plus 7
* **Android Version:** Android Pie stock
* **Server name:** self hosted
* **Server software:**  Openfire 4.3.0
* **Installed server modules:** MAM, HttpFileUpload
* **Conversations source:**  self build (latest HEAD)

#### Steps to reproduce

1. Join in a MUC 
2. Write messages
3. Log in in another account in another phone
4. Enter in the previously mentioned MUC

#### Expected result

All the history, or at least some messages, was restored.

#### Actual result

No previously messages was restored

I've also bought the app in the Play Store and it gives me the same results.

#### Debug output

I've force to load messages from server by clearing history on the MUC and tapping on "LOAD MORE MESSAGES" button.

There's my logcat:

D/conversations: myname@server: running mam query to=xitah@conference.server, end=2019-02-06T16:10:42.118Z, order=REVERSE, catchup=false, ns=urn:xmpp:mam:1
D/conversations: toggle forced foreground service after receiving event (action=ping)
D/conversations: ForegroundService: on

... and nothing else.

**Comment by licaon-kter** [comment]
What type of MUC? Encrypted or not?

**Comment by zauli83** [comment]
I've also tried to debug it, where  (i think )the  call was done, inside the `execute` method in the `MessageArchive` class. It seems that after the call on the method `this.mXmppConnectionService.sendIqPacket` with a body
`<iq type="set" to="qegitiwesol@servername"><query queryid="7qnau6aju7" xmlns="urn:xmpp:mam:1"><x type="submit" xmlns="jabber:x:data"><field var="FORM_TYPE" type="hidden"><value>urn:xmpp:mam:1</value></field><field var="end"><value>2019-02-06T16:59:18.178Z</value></field></x><set xmlns="http://jabber.org/protocol/rsm"><before/><max>50</max></set></query></iq>`

the client didn't receive the response. At least, in the next 2 mins.

In fact i received a xmpp message `<iq type="timeout"/>` message afterwards.

**Comment by iNPUTmice** [comment]
> It's not the server's fault, as another client restore correctly the MUC.

Other clients might use MUC history or different MAM versions. So this is not necessarily an indication.

**Comment by zauli83** [comment]
> > It's not the server's fault, as another client restore correctly the MUC.
> 
> Other clients might use MUC history or different MAM versions. So this is not necessarily an indication.

As a server i use a self-hosted version of Openfire 4.3.0. Can you tell me the one you use for testing client functionality?
