### ISSUE TITLE
2.4.0 beta minor issues

### ISSUE THREAD

**Issue by SkewedZeppelin** [siacs/Conversations#3369]
#### General information

* **Version:** 2.4.0 beta
* **Android Version:** Android 8.1
* **Conversations source:** freeCompatRelease from 4c8b1eb4bc1c82b0f777726cbe57f176c67b4cb3

#### Issues
- In a public channel the extra menu has "Destroy group chat" instead of "Destroy channel"
![channel-destroy-mismatch](https://user-images.githubusercontent.com/8296104/52450250-2a53b980-2b32-11e9-9471-75ee860ac395.png)

- In the start chat fab long actions can get cut off
![fab-cutoff](https://user-images.githubusercontent.com/8296104/52450256-2d4eaa00-2b32-11e9-87b2-01e7f1c38736.png)

**Comment by iNPUTmice** [comment]
Should be fixed in master.
