### ISSUE TITLE
File sent in a pivate message within a MUC becomes actually a public message

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#3372]
#### General information

* **Version:** 2.24.0-beta
* **Device:** Samsung S4
* **Android Version:** LineageOS 14.1
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Join a public, anonymous MUC
2. Long press on an avatar to start a private message
3. Insert a image you'd like to share in private

#### Expected result

The image is shared as a private message.

#### Actual result

The image is shared in public with the whole MUC.

#### Idea

Also consider https://github.com/siacs/Conversations/issues/2449

**Comment by licaon-kter** [comment]
Saw this too in 2.3.12, luckily it started a nice conversations, but caught me by surprise.

**Comment by rojoweko** [comment]
Somehow with version 2.4.2 it doesn't work for me to start a private message in a group chat by long pressing an avatar in the first place. A context menu shows up instead, but without an menu entry to switch to PM mode. Do I need to enable this feature somehow before I can use it?

**Comment by licaon-kter** [comment]
@rojoweko only in public anonymous chats

In private ones you know each others ID so you can just 1:1

**Comment by rojoweko** [comment]
@licaon-kter Ah, OK, thanks for the info! 😉

**Comment by marmistrz** [comment]
Yup, there seems to be no way to send a file privately in a MUC.
