### ISSUE TITLE
Image not loading when using JWT Bearer token

### ISSUE THREAD

**Issue by NePheus** [siacs/Conversations#3376]
#### General information

* **Version:** 2.3.12
* **Device:** Samsug Galaxy S7 edge
* **Android Version:** Android 8.0
* **Server name:** jabber.de
* **Conversations source:** PlayStore

#### Steps to reproduce

I am running a .NET server with this action:
```
[Route("image.jpg")]
public IActionResult Image()
{
    var data = new WebClient().DownloadData("...");
    return File(data, "image/jpeg");
}
```
and the [Matrix vNext](https://www.ag-software.net/matrix-vnext/) library to send this image:
```
public static async Task SendChatImageAsync(this XmppClient client, Jid to, string url)
{
    var msg = new Message()
    {
        Type = MessageType.Chat,
        To = to,
        Body = ".../image.jpg"
    };
    msg.Add(new XOob()
    {
        Url = msg.Body
    });
    await client.SendAsync(msg);
}
```
So basically **Conversations** shows the image without problems, but when I activate the bearer token validation in .Net:
```
...
    .AddJwtBearer(x =>
    {
        ...TokenValidationParameters
        x.Events = new JwtBearerEvents
        {
            OnMessageReceived = ctx =>
            {
                if (ctx.Request.Method.Equals("GET") &&
                    ctx.Request.Query.ContainsKey("accessToken"))
                    ctx.Token = ctx.Request.Query["accessToken"];
                return Task.CompletedTask;
            }
        };
    });
```
In the OnMessageReceived, I take out the accessToken parameter and set the context token, to get a valid authorization.
Then I add the authorization to my action:
```
[Route("image.jpg")]
[Authorize] // <-- new
public IActionResult Image()
{
    var data = new WebClient().DownloadData("...");
    return File(data, "image/jpeg");
}
```
When running this, I can open the image without any problem with:
".../image.jpg?accessToken=12345" inside the browser (Without the accessToken parameter I get a 401, so its working).
But when I send this path to conversations, it says "Bild auf HTTP-Host wird überprüft" (Image on HTTP-Host is checked) and then shows me "Bild-Größe auf ... prüfen" (Check size of ...).
When I remove the [Authorize] attribute and send the same link again (with accessToken parameter), conversations shows the image again without problems. I didn't see any differences when comparing the request/response headers in the browser when opening the url (with or without authorization activated). Can someone help me with solving this problem?

**Comment by iNPUTmice** [comment]
Conversations does a HEAD request to figure out the size before doing a GET request for the actual download.

**Comment by NePheus** [comment]
Thank you very much for this information!
I removed the:
```
ctx.Request.Method.Equals("GET")
```
inside my "OnMessageReceived" event listener, now its working perfect!
