### ISSUE TITLE
can not generate playstore apk version

### ISSUE THREAD

**Issue by noobinandroid** [siacs/Conversations#3377]
Hello

I can not generate playstore version. i get this error:

error: cannot find symbol variable app_server
			final Jid appServer = Jid.of(mXmppConnectionService.getString(R.string.app_server));

Ive got this issue with multiple version of conversations.

**Comment by ChaosKid42** [comment]
See here:
https://github.com/iNPUTmice/p2/blob/master/README.md#building-conversations
