### ISSUE TITLE
[UX] Fully show error message in the failed message 

### ISSUE THREAD

**Issue by Echolon** [siacs/Conversations#3379]
Hi,

I would like to suggest to put the actual error message below in the failed message.

XMPP is decentral, so I think it is important to do some extra efforts in consistency for the users. Especially users who even don't know that there is a possible error message. Yes, it would be great to know the error and improve about this, but not all errors are app related and its 'ultra' hard to get some valid information out of non-savy users.... so this could be a good step to get some information and dont let the user alone with the problem, which is no solution at all in my opinion. I think this would be good thing about experience wihtin the app and the network in general.

Here, a crappy visualised suggestion:

<img src="https://user-images.githubusercontent.com/29168011/52878840-eed27400-315d-11e9-8d49-8621201b1aad.png" width="250">

Kind regards & thanks for the app development

**Comment by licaon-kter** [comment]
Most users don't and should not care. I don't find the _extra step_ to long press such a hassle as they'll also long press to resend anywayp

**Comment by Echolon** [comment]
I am sure this is a big difference. Because the app starts actually giving feedback. Every service or instance somehow tries to give feedback. And if there is no feedback, the apps gets uninstalled with a bad rate in the end. I convinced 30-40 people to xmpp, from this 'experience' it tells me leaving the user not stucked is very important.

**Comment by licaon-kter** [comment]
Take your example, what would the user do next? Make a new account on a better server, re-add all their contacts, convince them its really them? Or think that _"Conversations can't send more than 10Mb"_ and uninstall? What's easier?

**Comment by Echolon** [comment]
Sometime they can solve the problems by themselves, using compression or somehow at least directly me what the problem is. I think, directly telling them what not working is a general better approach than passively waiting for the user to look for the problem. This is easier of course and at least it is consistent.

Why do you think I bring this up? Because everything is working so well or they reported perfectly about the issue? Of course not....

**Comment by iNPUTmice** [comment]
d95b904b5b5fd68765e81a10c70edd34049d94c6 solves this specifically for file too large. Displaying the *entire* error messages takes up too much space. But I agree that displaying something more meaningful than a generic delivery failed is the way too go.

**Comment by Echolon** [comment]
This was not about file size, but errors in general.

I further think, as this not a thing which will be there all the time, it is absolutely okay to show a message. Still, there could be a hint to expand this extra info beneath the chat bubble. So, user knows he can get information, then decides to look at it or not. In the current state, most don't even know about an error output.

**Comment by iNPUTmice** [comment]
What other errors besides file too large to you frequently run in?

**Comment by Echolon** [comment]
It's actually mostly not me, but it's my contacts with tell me about problems (also not related to me). Network errors, probably the same stuff about file size or something with the servers.

This is another reason I ask for. If they would see something like this, they would/could tell me directly. Or tell someone else.

I think, it is often not the apps' fault that something is not working. Yes, I know C is not a debug tool. But we should consider that it is a hard thing about messages in XMPP as decentral network and do help the user to understand at least.

If I have an expemplary situation I will post it here.

**Comment by iNPUTmice** [comment]
Yes I’m happy to add more specific error messages to the list of error messages that are shown in place of 'delivery failed'

**Comment by Echolon** [comment]
service unavailable


Additionally, every failed message should create a push notification. People otherwise expect that a message has been send.

**Comment by Echolon** [comment]
Another one is network timeout

**Comment by licaon-kter** [comment]
"Push notification" means Android notification?

**Comment by Echolon** [comment]
Yes, I just meant that the user should somehow be informed that something (not) happended.  Thought push notification would be good and mostly intutive

**Comment by Echolon** [comment]
New error message:

Connection failed: connection refused

I had no evidence of that my network was broken, other could receive my messages. However, you asked for the errors I get

**Comment by licaon-kter** [comment]
@Echolon this was an s2s issue? Was rare?

**Comment by Echolon** [comment]
No idea ¯\_(ツ)_/¯ 

Yes it was the first time. Now is fine. But my point in this thread is another one

**Comment by Echolon** [comment]
And another one:

Recipient not in room
