### ISSUE TITLE
Recorded audio files are huge compared to other IMs like Telegram

### ISSUE THREAD

**Issue by av2k** [siacs/Conversations#3380]
#### General information

* **Version:** 2.3 (most recent one)
* **Device:** any
* **Android Version:** any
* **Server name:** any
* **Server software:** any
* **Installed server modules:** any
* **Conversations source:** any

#### Steps to reproduce

1. Record an audio message within Conversations
2. Send the audio message

#### Expected result

The audio file is efficiently compressed to produce a voice recording of the smallest possible size where the audio still sounds reasonably good.

#### Actual result

A huge audio file is produced. The file is much larger than e.g. Telegram audio messages.

#### Debug output

Not neccessary.

#### Possible solution

Use Opus or another free, high compression codec with a reasonably low bandwith/quality setting that is just good for voice messages.

See here for reasonable Opus quality settings: 

https://wiki.xiph.org/index.php?title=Opus_Recommended_Settings

VoIP | 1 | 10 - 24 | 10 Kb/s will deliver narrowband most of the time, 24 Kb/s should give fullband.
-- | -- | -- | --

**Comment by iNPUTmice** [comment]
Android does not ship with an opus encoder. In fact even aac he is broken on some ROMs. We are not going to ship a opus library just to reduce  the file size slightly.

**Comment by av2k** [comment]
Hello,

the minimum API Level for Conversations is 16.

Maybe instead of Opus, HE-AAC could be used? It is integrated in Android since API Level 16. So there should be no requirements for additional libraries.

I think there should also be an enforcement of mono recording and with HE-AAC, 32kbit/s should be more than satisfying for voice.

https://developer.android.com/reference/android/media/MediaRecorder.AudioEncoder.html#HE_AAC

https://developer.android.com/reference/android/media/MediaRecorder#setAudioChannels(int)

- HE-AAC for audio encoding, which requires the same API Level like Conversations itself (16) and is well-integrated in Android
- 32kbit/s encoding rate or 24kbit/s which is sufficient for voice audio with HE-AAC and just fine for the low sampling rate of 22kHz used by Conversations currently
- enforce mono channel to avoid stereo recording for voice, which is almost always intended to be recorded as a mono channel

I look forward to learn your opinion.

**Comment by iNPUTmice** [comment]
> HE-AAC for audio encoding, which requires the same API Level like Conversations itself (16) and is well-integrated in Android

It is not: https://github.com/siacs/Conversations/issues/3021

**Comment by av2k** [comment]
Ok...I still think the two other points (enforcing mono channel and lower bitrate) stay valid.

Regarding the HE-AAC issue: is it possible to probe for HE-AAC availability and fall back to normal AAC if HE-AAC is not possible?

In the issue you have linked, it is suggested to "Force to use the Google encoder" which *should* work on all devices with API Level 16 or higher.

It appears to me that this is only a change of a few lines of code, and it would make the audio recording feature (which is probably widely used, because it is easier to record voice than to type text on a very small on-screen keyboard) much more useful for people with restricted bandwith and/or data volume plans.
