### ISSUE TITLE
A MUC is not removed from bookmarks when destroyed

### ISSUE THREAD

**Issue by marmistrz** [siacs/Conversations#3385]
#### General information

* **Version:** 2.3.12+fcr
* **Conversations source:** f-droid

#### Steps to reproduce

1. Create a MUC in Conversations
2. (presumably not needed) write something in the MUC
3. Destroy the MUC and remove it from the conversation list
4. Launch gajim on desktop

#### Expected result
Nothing happens in gajim (i.e. the groupchat is properly removed from bookmarks)

#### Actual result
Gajim fails to connect to the MUC with the message `gone`, this is due to the fact that the bookmark was not removed by Conversations

#### Debug output

This one should be easily reproducible and I'm currently quite busy. Please let me know if you really need it.

**Comment by iNPUTmice** [comment]
Does it remove the autojoin flag? Because i think it does and that would be expected behaviour

**Comment by licaon-kter** [comment]
I can see this in 2.4.1 w/ ejabberd HEAD

Steps:
* account A makes a private group with account B
(which is offline)
* A writes something 
* A destroys the group
* A goes offline
* B comes online
* Destroyed group pops-up
* B closes it
* B goes offline (change from Wi-Fi to mobile)
* Destroyed group comes back
* B closes/destroys it
* B disconnects
* B reconnects
* Destroyed group comes back

**Comment by marmistrz** [comment]
Yes, the autojoin flag is not removed. C is my Conversations device, G is my Gajim device.

1. Create a private groupchat on C
2. Quit G, Launch G: a group-chat is auto-joined
3. Quit G.
4. Destroy the groupchat on C
5. Launch G

**Comment by iNPUTmice** [comment]
You have to leave the chat for autojoin to be removed.
