### ISSUE TITLE
Messages from another account (but same user part) are shown as own messages for public room

### ISSUE THREAD

**Issue by doak** [siacs/Conversations#3390]
#### General information

* **Version:** 2.4.0+fcr (F-Droid build)
* **Device:** Samsung S3 i9300
* **Android Version:** Replicant 6.0 (based on CM/Lineage 14.1)
* **Server name:** *conversations.im* and *jabber.ccc.de*
* **Server software:** <unknown>
* **Installed server modules (for jabber.ccc.de):** all but *HTTP File Upload*
* **Conversations source:** F-Droid

#### Steps to reproduce

`<user>` is the very same name for both accounts.

1. Join any **public** room as `<user>@<server1>`.
2. Send  message `This was sent by <user>@<server1>.`.
3. Join the very same public room as `<user>@<server2>`.
4. Send message `This was sent by <user>@<server2>.`.

#### Expected result

Conversations should show only own messages on the right side (i.e. as own messages). In other words, the message `This was sent by <user>@<server1>.` should be shown as sent by `<user>@<server1>` if viewed by `<user>@<server2>`.

#### Actual result

In fact Conversations "merges" both JIDs and shows both messages are shown **as own messages**.

#### Debug output

Will provide if needed.

**Comment by doak** [comment]
It is the some for *Gajim* by the way, you cannot distinguish between same username on different servers. I hope it is not XMMP related.

**Comment by licaon-kter** [comment]
in public anonymous room your client doesn't have ways to distinguish the users, it only sees nicks.

This doesn't happen in a (private) non-anonymous room, right?

**Comment by doak** [comment]
@licaon-kter, I see.
This is because the member list is configured to not beeing broadcasted for privacy reasons, isn't it?

Here is the the public room as an example: `test.same-username.different-server@conference.conversations.im`

**Comment by doak** [comment]
> This is because the member list is configured to not being broadcasted for privacy reasons, isn't it?

Although configuration (examined with Gajim) seems not to strip anything. Does that mean it is caused by the protocol?

**Comment by licaon-kter** [comment]
> This is because the member list is configured to not beeing broadcasted for privacy reasons, isn't it?

Yes, albeit iirc the second user that logs in should be rejected as _"nick already exists"_ or something.

**Comment by doak** [comment]
> Yes, albeit iirc the second user that logs in should be rejected as "nick already exists" or something.

Yes, but only if other user is currently connected. Furthermore that does **not** happen if room has been created right now.

**Comment by doak** [comment]
> This doesn't happen in a (private) non-anonymous room, right?

Yes, does not happen. Indeed I am requested to change nick.

Is the behaviour protocol or implementation related? I am asking, because this could be an issue for public channels.

**Comment by iNPUTmice** [comment]
You need to join with the same nick for any xmpp client to realize that the messages are coming from the same account.

**Comment by doak** [comment]
@iNPUTmice, just to clarify: it is intended by XMPP that `username@conversations.im` is the *very same user* as `username@jabber.ccc.de` on public channels, as long as the same nick is configured?

I am wondering why XMPP do not consider the full JID, though it is a federated protocol?
