### ISSUE TITLE
feature request: Configuration for read-only public channels

### ISSUE THREAD

**Issue by doak** [siacs/Conversations#3391]
#### General information

* **Version:** 2.4.0+fcr (F-Droid build)
* **Device:** Samsung S3 i9300
* **Android Version:** Replicant 6.0 (based on CM/Lineage 14.1)
* **Server name:** *conversations.im*
* **Server software:** <unknown>
* **Conversations source:** F-Droid

#### Description

Conversations already support "read-only" public channels, though does not support to configure respectively create one. (In case you are not allowed to send messages, Conversations displays `You are not participating` within input field.)

Not sure if that has already been discussed. I quickly scanned https://wiki.xmpp.org/web/Sprints/2019_January_Brussels/Pad (linked by [this comment](../issues/3387#issuecomment-466166441)), but it seems not be covered.

Not sure if it wanted anyway, but imho it would be nice to add this configuration option for public channels.
Naturally, granting specific members voice would be requested very likely as follow-up, though that infrastructure is imho already in place (roles can be assigned).

Another follow-up would be probably support to request voice, which is imho not supported by Conversations right now.

#### Expected result

Public channels can be made *read-only for guests* in *channel details* dialogue.

Probably UI needs to stress the fact "you are guest and you are not allowed to send messages" a little bit more. Currently there is a just string within the input field. At least that string needs to be adapted to be more clear.

#### Actual result

There is not way to configure "read-only" behaviour right now.

**Comment by iNPUTmice** [comment]
You can do that if you turn on advanced mode

**Comment by doak** [comment]
@iNPUTmice, sorry for creating an unnecessary issue then.

Which option needs to be activated/deactivated?
I only see *'Make XMPP addresses visible to anyone'*, *'Allow anyone to edit the topic'* and *'Make channel moderated'* which imho does not configure requested behaviour.

What do I miss?
