### ISSUE TITLE
Don't force-open MUCs if user does not have it bookmarked and already opened

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#3392]
#### General information
* **Version:** 2.4.1+fcr
* **Server name:** self hosted ejabberd HEAD
* **Installed server modules:** 100% compliance
* **Conversations source:** F-Droid

#### Steps to reproduce
1. join a bridged room from Matrix.org 
2. `xmpp:#matrix#matrix.org@bridge.xmpp.matrix.org?join`
3. see that bridges are not our lord and saviour from silos
4. delete room bookmark
5. end the conversation

#### Expected result
Be happy to only talk to XMPP users

#### Actual result
When users post in those rooms, that you don't care about any more since you've deleted their bookmarks and closed it, the room opens all by itself, like any 1:1 would do.

#### Debug output
There is no error... I only do the "leaving" part
```
02-26 17:28:05.815  5045  5045 D conversations: myuser@mydomain.tld: leaving muc #matrix#matrix.org@bridge.xmpp.matrix.org
02-26 17:28:53.188  5045  5045 D conversations: myuser@mydomain.tld: leaving muc #matrix#matrix.org@bridge.xmpp.matrix.org
02-26 18:05:16.025  5045  9223 D conversations: myuser@mydomain.tld: leaving muc matrix-appservice-purple@conf.xmpp.matrix.org/MyNick
02-26 18:07:50.485  9447  9500 D conversations: myuser@mydomain.tld: joining conversation matrix-appservice-purple@conf.xmpp.matrix.org/MyNick
02-26 18:08:03.722  9447  9500 D conversations: skipping duplicate message with matrix-appservice-purple@conf.xmpp.matrix.org/Github [@Half-Shot:half-shot.uk].serverMsgIdUpdated=false
02-26 18:09:56.325  9447  9561 D conversations: myuser@mydomain.tld: leaving muc matrix-appservice-purple@conf.xmpp.matrix.org/MyNick
02-26 18:10:17.514  9447  9572 D conversations: myuser@mydomain.tld: leaving muc matrix-appservice-purple@conf.xmpp.matrix.org/MyNick
02-26 18:10:36.018  9447  9573 D conversations: myuser@mydomain.tld: joining conversation matrix-appservice-purple@conf.xmpp.matrix.org/MyNick
02-26 18:10:52.983  9447  9573 D conversations: skipping duplicate message with matrix-appservice-purple@conf.xmpp.matrix.org/Github [@Half-Shot:half-shot.uk].serverMsgIdUpdated=false
02-26 18:13:00.578  9447  9823 D conversations: myuser@mydomain.tld: leaving muc matrix-appservice-purple@conf.xmpp.matrix.org/MyNick
02-26 18:13:02.100  9447  9824 D conversations: myuser@mydomain.tld: leaving muc matrix-appservice-purple@conf.xmpp.matrix.org/MyNick
02-26 18:13:13.430  9447  9825 D conversations: myuser@mydomain.tld: joining conversation matrix-appservice-purple@conf.xmpp.matrix.org/MyNick
02-26 18:13:24.142  9447  9825 D conversations: skipping duplicate message with matrix-appservice-purple@conf.xmpp.matrix.org/Github [@Half-Shot:half-shot.uk].serverMsgIdUpdated=false
```

**Comment by iNPUTmice** [comment]
If the room is still sending us messages they should be shown

**Comment by licaon-kter** [comment]
I disagree that it should be shown, this is basically SPIM now...

Yes, block s2s to that server would *fix it*, but what if I **want** to join another room there?

**Comment by licaon-kter** [comment]
Logcat from ejabberd: https://gist.github.com/9d2601e0acefe836582aa73528f1d785

**Comment by iNPUTmice** [comment]
The gateway keeps sending you messages even though you've left. This is clearly a bug in the gateway. If Conversations would stop showing them they'd still cause traffic and processing resources on Conversations. This is something that needs to be fixed in the gateway anyway. So i don’t see a point of creating a work around on the client side.
