### ISSUE TITLE
Incorrect regex for matching nicknames in mentions

### ISSUE THREAD

**Issue by groug** [siacs/Conversations#3395]
#### General information

* **Version:** 2.3.12+pcr
* **Device:** OnePlus 5
* **Android Version:** OxygenOS 9.0.3 (Android 9)
* **Server name:** self hosted
* **Server software:** prosody
* **Conversations source:** Play Store

#### Steps to reproduce

Since issue #3249 has been resolved with commit 03cd176c2773b6951bd496b46658570f2fe62eea, the regex for finding nick highlights matches in some scenarios where it shouldn't, because \p{Punct} matches `!"#$%&'()*+,-./:;<=>?@[\]^_``{|}~`. 
I don't know which characters are valid characters to use in a nickname, but I know for sure _ is one of them.

1. Enable notifications on a MUC only for mentions
2. Ask for someone else to type your nickname concatenated to _

#### Expected result
No notification, no highlighted (bold) nick in the conversation

#### Actual result
A notification appears and your nick is in bold in the conversation

**Comment by iNPUTmice** [comment]
Yes. Basically all characters are valid that could potentially act as word boundaries. Including `.`. A regex based approach to mentions will always have limitations.

**Comment by groug** [comment]
It always will, indeed, but is closing the issue and not changing anything the way to go?

I think a simple approach would be to change regex from
`
Pattern.compile("(?<=(^|\\s))" + Pattern.quote(nick) + "(?=\\s|$|\\p{Punct})");
`
To
`
Pattern.compile("(?<=(^|\\s))" + Pattern.quote(nick) + "(?=\\s|$|\\p{Punct}\\s)");
`

As: "nick followed by either a whitespace, or the end, or a punctuation followed by a whitespace".

Because that's really not normal to highlight "foo" in the word "foo-bar"

**Comment by iNPUTmice** [comment]
Feel free to create a PR with a better solution. Probably has to be any number of punct followed by white space or end.
