### ISSUE TITLE
ver 2.4 on android 4.4 

### ISSUE THREAD

**Issue by fenix-soft** [siacs/Conversations#3396]
good morning, I am writing to make a report. In android 4.4 kitcat (samsung j1) the version of conversation Version 2.3.12 + fcr available in the repo of f-droid works perfectly, but in the repo f-droid there is an update to the branch 2.4 (Version 2.4.1 + fcr (321) - Added on 2019-02 -25). This version 2.4.1 + fcr on android 4.4 kitcat has problems does not display images in the chat, you see a black box, if you touch that frame the image is opened and displayed without problems in the gallery program, but it is impossible to view it in conversation as a preview ..., for this reason I have to return to the branch 2.3
tips?

**Comment by licaon-kter** [comment]
Try to disconnect (NOT delete) your accounts, close the app, force close the app in Android settings and clear app CACHE (not data!) .


Then reopen...reconnect...

**Comment by conversationsuser** [comment]
I see exactly the same symtoms with versions 2.4.0 and 2.4.1 from F-Droid on Android 4.4.2. Following licaon-kters instructions did not fix the problem. I could not see any lines in logcat output that I would consider as possibly related to this problem.

Same problem can bee seen for video preview images, the media files in the contact/conference details screens and in the media browser. The icons for audio files are shown there however.
