### ISSUE TITLE
Add an icon for disconnected MUCs

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#3397]
....since the banner is seen only if I open the chat.

Eg. It happens fairly often, after a disconnect/reconnect, like in the morning when I connect or even on network change, that rooms don't get connected, and I need to press that banner button to get it going.

Today after testing something else by killing the app and reconnecting, I got a dozen messages in rooms that I thought were connected ok, but cleary they weren't.

I did chat 1:1 ok during the day. 

By an icon I mean sort of the cut cloud one that you use for disconnected accounts, but put it near the notification bell in the chat view. Or better yet, maybe overlay it on the room avatar with some alpha.

Thanks 

/LE: also this is the first time I got _"not encrypted for this device"_ errors in normal usage.

**Comment by iNPUTmice** [comment]
We will attempt to make muc connections more reliable.

**Comment by licaon-kter** [comment]
Any work on this front?

Today I've looked and they were ok (Conversations, Dino, Monal, CS), some hours passed without any network switch or  device change, and now checking them I see a grey arrow and no users. After leaving and rejoining they're back ok.

No error in the logs (client, server).
