### ISSUE TITLE
Synchronize with contacts not optional

### ISSUE THREAD

**Issue by Yky** [siacs/Conversations#3399]
#### General information

* **Version:** 2.3.12+fcr
* **Device:** Google Nexus 5
* **Android Version:** LineageOS 14.1
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Open Conversations
2. Click on the floating action button with the message symbol
3. "Synchronize with contacts" dialog appears

#### Expected result

Ability to add a MUC without synchronizing contacts. 

This is possible, but the workflow could be more user friendly. 
At the moment you need to click next, and then deny, when the Android permission request pops up, instead of asking the user, whether he would like to synchronize contacts or not. 

#### Actual result

Dialog appears. The only option for navigating is clicking next. There is no cancel button, nor does the dialog close when clicking somewhere else on the screen.

**Comment by licaon-kter** [comment]
You can deny it, and then the second time it happens you can check to never ask and rejecw forever.

/close as invalid?

**Comment by Yky** [comment]
Why not give the user the option of syncing or not syncing in the first place?

**Comment by licaon-kter** [comment]
You have that option, either accept the permission to sync or not.

Not sure what you mean.

Also, latest version is 2.4.1.

**Comment by Yky** [comment]
2.4.1 does not change the behavior. 

Yes, I understand it needs that permission. 

Still, from a UX perspective, I think it would be better to give the user the option to sync contacts, but also have an option such as "not now", and still be able to navigate to the screen containing the "contacts" and "bookmarks" tabs. 

The way the dialog is currently designed, it gives me the false impression that I _must_ grant permission to contacts in order to get to the next screen, which is not true.

**Comment by iNPUTmice** [comment]
These Android Dialogs are specifically designed to work like that. all of them are.

**Comment by licaon-kter** [comment]
@iNPUTmice you are showing the info dialogue **after** the first reject...why not **before** the first permission dialogue?
