### ISSUE TITLE
beautify UI

### ISSUE THREAD

**Issue by gitlerat** [siacs/Conversations#3403]
Hi, I want to make some suggestion to the UI.

In private chat there is always the avatar visible - why? I think there is no need for that information for every post. I see the benefit in large groups, but even there this should be optional. Many major instant messaging client like Signal and WhatsApp don't work that way. In Riot the Avatar is present but much smaller and in Monal (iOS) there is also no avater in the chat (like you see in the picture)

For non-tech people like my friends, the UI is much more important than the things in the background - so my experience is that if the UI would be a bit more fancy the change from WhatsApp would be easier :) 

![300x0w](https://user-images.githubusercontent.com/46427021/53941765-40b14e80-40b9-11e9-8708-ec868d984f77.jpg)

I highly suggest to orient an the UI from Signal, WhatsApp or Monal. Also the smartphone displays get smaller in the width so there would be also a benefit...

kind greetings

**Comment by licaon-kter** [comment]
Users still complain they don't know to which chat they answer, so there's the contra-argument, this will make it worse, if you have contacts with almost the same nick it's easy to confuse them.

Also this: https://mobile.twitter.com/iNPUTmice/status/1086970528114634752

And: https://mobile.twitter.com/iNPUTmice/status/1088178949962850307

**Comment by gitlerat** [comment]
To not mix up different things: I am talking about the avatars inside a chat. 
The avatars outside for all my chats should stay because if there is only the name I would also have problems to select the right chat.

**Comment by licaon-kter** [comment]
Once you open a chat, eg. Via a notification, it doesn't matter that you can see the avatar elsewhere.

Also, it will look inconsistent, no avatars in 1:1 but shown in MUCs.

**Comment by gitlerat** [comment]
it would be really nice to have this as an optional feature that I can control from the settings. For me I dont have the need to see in a 1:1 always my profile picture, but I understand your opinion.

**Comment by iNPUTmice** [comment]
@gitlerat your feedback has been read and acknowledged. I partially agree. Currently Conversations is focused on stability rather than new features and/or redesigns. Being more space efficient in one form or another will be part of a possible redesign in 2020.

**Comment by licaon-kter** [comment]
@gitlerat looking at your Monal screenshot, I wouldn't mind not having the per message avatar if say it'd have an avatar up on the title bar near the nick/ID.

**Comment by gitlerat** [comment]
@licaon-kter yeah that would be nice :)
