### ISSUE TITLE
Conversations ignores DNS over TLS

### ISSUE THREAD

**Issue by jamesbond55** [siacs/Conversations#3404]
#### General information

* **Version:2.4.2+fcr
* **Device: Xperia XZ2
* **Android Version: Android 9; OmniROM

* **Conversations source: F-Droid

Hi dear developers,

i've been since a while on Android 9 and since then i'm using the Private DNS feature (so my DNS Requests goes over TLS).
As expected i can't see the dns requests from my apps anymore because they use my secured dns channel. The only exception is Conversations so i can see the dns requests whether they run via TLS.
So it seems for me that Conversations ignores my setting. Can you please fix it?

**Comment by licaon-kter** [comment]
Android must force all the requests, it's nothing that Conversations can control.

How do you see the DNS requests (Netguard)?

How do you know that it bypasses your DNS and gets the IP from elsewhere?

**Comment by iNPUTmice** [comment]
Yes Conversations currently does not support DNS over TLS. There are no
immediate plans to support it. I don't think our dns library supports it
yet.

**Comment by jamesbond55** [comment]
@licaon-kter 

I use AdAway to record the dns traffics via TCPDump.

@iNPUTmice 
ok thx for the info. That explains my obversation. So i hope the dns library you use will support DNS over TLS soon. Can you please implement it when the library support it?

**Comment by iNPUTmice** [comment]
closing in favor of #3405
