### ISSUE TITLE
Members-Only Rooms address

### ISSUE THREAD

**Issue by meaz** [siacs/Conversations#3407]
#### General information

* **Version:** 2.4.2+fcr
* **Device:** Galaxy S4 mini
* **Android Version:** Lineageos 14.1
* **Server name:** self hosted
* **Server software:**  prosody trunk
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Choose "Create private group chat"
2. Choose a name for the conversation group, for example "myroom"
3. Choose the participants

#### Expected result

Create a MUC with the provided name, for example **myroom@muc.server.com**

#### Actual result

Create a MUC with a random name, for example **erizgzeropcpoz@muc.server.com**

**Comment by iNPUTmice** [comment]
I do not agree that this is expected result. For private group chats the XMPP address should not matter.

**Comment by licaon-kter** [comment]
@meaz isn't the pivate room invitation only? Hence you can't just yell the room name (the need to be customisable) and they can join....

**Comment by meaz** [comment]
But will those members join automatically this private muc? I mean when they lauch COnversations, do the app fetches this room? Or will they still have to add the muc address manually the first time they want to join it in? In this latest case, I find it relevant to have a custom muc name.

**Comment by licaon-kter** [comment]
@meaz the MUC will open for them yes
