### ISSUE TITLE
Conversations deletes files cached by NewPipe

### ISSUE THREAD

**Issue by Mat406** [siacs/Conversations#3409]
#### General information

* **Version:** 2.4.2+fcr
* **Device:** Samsung Galaxy S4
* **Android Version:** 7.1.2 - Lineage OS
* **Server name:** Self hosted
* **Server software:** Prosody 0.11.1
* **Installed server modules:** Conversations lists all as available, including: Stream Management, Carbons, MAM, Client State Indication
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Start Conversations
2. Open NewPipe (Mine is v0.16.0 from F-Droid)
3. Check logcat logs

#### Expected result

Conversations only deletes cached files created by Conversations

#### Actual result

Conversations deletes files cached by NewPipe

#### Debug output

When opening NewPipe a few of these pop-up:
03-13 08:42:45.753  2140  2163 D conversations: deleted file /storage/emulated/0/Android/data/org.schabi.newpipe/cache/state_cache/606539438035526.31f8b95c-e5f1-42e0-a070-b610d9bd2d20.player internal=false, database hits=0

And when playing a video there's a fast stream of these:
03-13 08:38:31.288  2140  2163 D conversations: deleted file /storage/emulated/0/Android/data/org.schabi.newpipe/cache/exoplayer/95.17825792.1552466175099.v3.exo internal=false, database hits=0

**Comment by iNPUTmice** [comment]
No it doesn’t.This is just a notification about the fact that the file was deleted.

**Comment by licaon-kter** [comment]
/close as invalid

Conversations is subscribed to media events so it gets notified whenever files are created/deleted.
