### ISSUE TITLE
error when recording an audio message

### ISSUE THREAD

**Issue by gudbes** [siacs/Conversations#3411]
#### General information

* **Version:** 2.4.2+pcr
* **Device:** ONEPLUS 5T (A5010)
* **Android Version:** Android 9 (lineageos 16.0-20190315
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. click on the microphone icon to send an audio message 

#### Actual result

I have an error "Unable to start recording"
![Screenshot_20190317-150004_Conversations](https://user-images.githubusercontent.com/20442433/54492296-82b26f80-48c5-11e9-9e22-f2ca200b6493.png)

Does anyone have this problem?

Thx

**Comment by licaon-kter** [comment]
Try to install "voice recorder plugin" from F-Droid

**Comment by gudbes** [comment]
I tried but it's the same thing 😭

**Comment by gudbes** [comment]
It's okay, I made the last update of lineageos
