### ISSUE TITLE
Conversations doesn't link to use pgp encryption with a compiled version of openkeychain

### ISSUE THREAD

**Issue by HackM3nt3** [siacs/Conversations#3412]
I did compile my own debug version of openkeychain but i wasn't able to link it with conversations.
What changes do i need to make in this repository to make it work?

**Comment by licaon-kter** [comment]
@HackM3nt3 app id like this https://github.com/siacs/Conversations/blob/ec0b9b9a72977aa67bbb19314752973ff2a7d1c5/src/main/java/eu/siacs/conversations/ui/XmppActivity.java#L265 ?

**Comment by iNPUTmice** [comment]
the debug is build with a `.debug` appended to the application id. you have build the release version; or change the application id of open key chain. or also build conversations and change what id it is looking for.
