### ISSUE TITLE
Feature request: Restore export as a plain text file

### ISSUE THREAD

**Issue by multimob** [siacs/Conversations#3415]
Version 2.4.0 introduced a nice new backup/restore feature.

Yet, exporting chat history as plain text file (up to 2.3.12) can be useful for some people too.  I archive past chats as text files and store them securely on an encrypted drive.  This is no longer possible with CEB files generated by the new export feature (Expert settings > Create backup).

Suggestion: keep backup/restore feature AND add an option to export as a text file.

#### General information

* **Version:** eg 2.4.2+fcr
* **Conversations source:** F-Droid

**Comment by iNPUTmice** [comment]
I don’t think it makes sense to implement this into Conversations. Maybe someone from the community wants to develop a tool that extracts plain text logs from the backups. But cluttering the app itself with that niche functionality is not a good move.

**Comment by ippaket** [comment]
### I really miss this feature too.

I do not need an encrypted backup. Some conversations I have archived on my PC, which has an encrypted mass storage. It would be very nice, if  the old plain text file comes back.
I do not know, how it is possible to extract the plain files from the backup. What kind of format is it ?  What is CEB ? Where and how can i restore the backup ? It makes no sense for me to restore it on the phone.

I have an android phone from bq (version 8.1.0) and get the conversations from google store.

**Comment by iNPUTmice** [comment]
There is https://github.com/iNPUTmice/ceb2txt

The current export format is pretty basic. Feel free to modify that to what ever you want. I frankly don’t know what people expect from a plain text backup format.

**Comment by markus-gellrich** [comment]
i expect to copy several messages at once. E.g. we log blood sugar level of our cat in a chat room. i would go nuts copying line by line for the vet. thx for ceb2txt, h8ing to have to install jre though. could there be a feature to plainly export a specific chat, so one could do this with less than two devices?

**Comment by fm444fm** [comment]
I completely agree: the users should have the control over their message history and be able to easily export it to txt files like it used to be. Please reinstate that functionality

**Comment by agrajagg42** [comment]
I'd like to see this feature coming back myself. I used it in the past frequently and since the update am a bit lost.
Unfortunately my ability to compile ceb2text for Anroid does not allow me to produce something that I could use.

**Comment by licaon-kter** [comment]
@agrajagg42 it's not for Android, it's a Java app for PC

**Comment by github-userx** [comment]
Any update on this? It honestly boggles my mind that you would remove such a crucial backup feature. I’ve done this with signal, WhatsApp and many others. Backing up straight to a plain textfile is so important and handy.
It also gives you the option to read your chat log on any device without Conversations, Java or anything else installed

**Comment by alping** [comment]
For anyone who is interested, I've made a simple Python tool for extracting the data in CEB files into a database:
https://gitlab.com/alping/ceb-extract

It's inspired by https://github.com/iNPUTmice/ceb2txt mentioned above, but doesn't require Java.

**Comment by github-userx** [comment]
Amazing! Thank you!
