### ISSUE TITLE
OMEMO: cross-signing device keys

### ISSUE THREAD

**Issue by kousu** [siacs/Conversations#3417]
[Blind-Trust-Before-Verification](https://gultsch.de/trust.html) was the UX improvement in response to #1626 (and, I assume, related issues, though I didn't find them in the tracker).

[Keybase just posted an explanation](https://keybase.io/blog/chat-apps-softer-than-tofu) of their tactic for the same problem. They have a very similar setup to OMEMO: per-device keys that should never get extracted. Their solution, hard won after many UX cycles, is:

1. The first key seen by a peer is accepted by TOFU
2. Future keys appended to the account prompt the original device to cross-sign. If the owner accepts and signs, the new key is appended to the account.
3. Future keys seen by a peer device either accept the new key if they see it cross-signed, or, if they receive a message from the new device without have not been accepted yet, reject it or throw up a big warning.
3. Any trusted device can revoke and disable a key across *all* devices, both user and peer, automatically.
3. An account's keyserver can be wiped and replaced by a new, fresh key, and in this case it prompts on the peer device with a big, very obvious, warning, that the account has been reset and you should reverify manually.

I've been using OMEMO for a couple years now and my phone has 12 device keys remembered, of which only 2 are actually active. And the "active" state is stored per-device, so to disable or revoke a key I need to go to Gajim, Conversations, now [dino](https://dino.im) (hi dino!) and manually figure out which keys are good and which are gone.

When I add a new device, I don't need to re-meet all my contacts to trade new keys: I can copy the QR code or fingerprint and send it to them in a message from a device they already trust. This is effectively a manual implementation of the protocol above, and it's what I've done for the few people who I have on jabber that care about verifying keys. Why can't we automate this?

It should also be possible to sync the list of accepted/revoked keys between my own clients. There's no reason why Gajim and Conversations should be in disagreement about that: if they trust each others' keys they can tell each other what is valid and what's not.

Integrating automatic cross-signing into OMEMO would be a big boon to it, UX-wise. And I don't want to get dragged to keybase which, while open source and doing lots of good work, is a centralized service; the big selling point of OMEMO is that it is the only mobile-friendly e2e encryption protocol that works without vendor lock-in.

I haven't thought through whether this _replaces_ or _complements_ blind-trust-before-verification. What do you all think?

**Comment by kousu** [comment]
This is important context that I was also missing on the current OMEMO design: https://github.com/siacs/Conversations/issues/2076#issuecomment-255576608
> 
> there is nothing you can choose, clear devices means that the list of devices/keys on your server (not your device) is set to zero.
> this is published to all of your contacts and yourself + your other devices.
> 
> if a device receives a device/key list of zero, it sets all keys to inactive.
> if an active device of yourself becomes a device/key list of zero, it knows this is wrong, and adds itself to the server list again, everyone of your active devices does this.
> 
> so you end up with an up to date server list of only devices that are active, devices that are not in use cant add themself to the server list.
> this all happens of course in seconds.

Adding cross-signing into this mix would still be a powerful addition.

**Comment by iNPUTmice** [comment]
Cross signing can probably replace BTBV. It's not that cross signing is an unwanted feature. It is just very hard to get right. We can probably learn something from what keybase is doing on that front. But think of it as a multi year process and not something that we can 'just do' tomorrow.

**Comment by kousu** [comment]
Oh that's great to hear! I am glad that I was able to bring their research to your attention then. They've probably figured out some of the nasty corner cases and we can learn from them. Happy day :) :)

---


> However the centralized trust anchor plays a not insignificant role in getting revocations to work. Doing this in a federated manner will further complicate [the] problem

Which trust anchor are you thinking of? The XMPP server? That isn't where I anchor trust; it's the device key(s) that I trust to sign off on things (and before I manually verify a key I assume it's suspect and would adjust myself accordingly); the servers should just be a transport. What they *can* do is lie about what account- or pre- keys are available, either by silently adding new ones or censoring a recovation of an old one, but that should be at least detectable after the fact.

I am personally more concerned about the ghost-device attack than losing control of a device's keys; I think it's much easier and sneakier for someone to corrupt a server than to steal a device and extract its keys. Both are legitimate attacks worth countering, though.

[Keybase's approach](https://keybase.io/blog/chat-apps-softer-than-tofu#can-you-talk-more-about-this-claim-by-ncc-however-the-attacker-is-capable-of-refusing-to-update-a-sigchain-or-rolling-back-a-user-s-sigchain-to-a-previous-state-by-truncating-later-chain-links-) to this issue involves an auditable public ledger:

> To be clear Keybase cannot invent signatures for someone; like any server, it could withhold data. But our transparent merkle tree is designed to keep this to a very a short period, and permanently discoverable.

---

If I was doing this in my manual protocol I would send a message to my friends *encapsulated in OMEMO* saying "hey my iPhone died please revoke it"; that itself would be safe (i.e. authenticated), and if I have read-receipts enabled I'll know it got to my peers' devices. Could automated revocations be wrapped inside OMEMO? We have a list of all of our own devices that support OMEMO -- because we have their keys! -- so we could periodically send revocations as custom XMPP stanzas inside OMEMO until we recieve an ACK for them.

Shouldn't new keys and revocations sent over OMEMO be safe?

**Comment by iNPUTmice** [comment]
I’m closing here since there is no immediate action that could be taken.

**Comment by muppeth** [comment]
Looks like Riot just did release cross signing. Perhaps something to look into as its also federated and what not. 
Just pointing out. I have no clue how they do it and if its even relevant, but thought maybe worth mentioning it here.

**Comment by licaon-kter** [comment]
@muppeth Like this https://blog.riot.im/e2e-encryption-by-default-cross-signing-is-here/ ?

**Comment by kousu** [comment]
To whoever downvoted this: closing was reasonable. This is a hard problem to get right and there wasn't anything to do about it until someone makes a well designed spec and thinks through all the consequences. But it sounds like doing that would get this implemented. I'm obviously interested but I know I don't have the time to get the security right by myself.

Thanks for bringing Riot's work to attention @muppeth!

**Comment by jf99** [comment]
Cross-signing is a really important issue.

@iNPUTmice How much would it cost to design an XEP and implement it? I trust you and I am willing to spend 250 €. Maybe others as well.
