### ISSUE TITLE
Do not require OOB message body to be equal to the link

### ISSUE THREAD

**Issue by himselfv** [siacs/Conversations#3419]
Currently Conversations requires OOB message body to be equal to the `x:oob` link, or empty:

```
<message ...>
<x xmlns='jabber:x:oob'><url>http://my/url</url></x><active xmlns="http://jabber.org/protocol/chatstates"/>
<body>http://my/url</body>
</message>
```

There's no such requirement in [XEP-0066](https://xmpp.org/extensions/xep-0066.html) and it doesn't seem to be how it's meant to be used.

It should be okay to include additional text in the body:
```
<body>Here's a picture: http://my/url</body>
```

This is handled [here](https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/parser/MessageParser.java#L488).
```
if (body != null && body.equals(oobUrl)) {
  message.setOob(true);
  ...
}
```
Maybe this can be replaced with "body.contains(oobUrl)"?

Though the client seems to rely on this in other places [such as this](https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/utils/MessageUtils.java#L66).

Maybe there could be a separate message field listing all the URIs to be treated as OOBs in this message.

Related: Issue 3378.

**Comment by iNPUTmice** [comment]
Conversations can currently only show text or an image in a message bubble but not both.
I don’t think oob is a good fit for sending images with descriptions. If you want to send a link to a picture and not embed it as in your example Conversations will correctly just show the body with the link.

**Comment by bqv** [comment]
😠
