### ISSUE TITLE
feature request: open "share location" in map app, e.g. osmand

### ISSUE THREAD

**Issue by TjrGithub** [siacs/Conversations#3421]
I would appreciate if the "share location" feature gives the receiver the choice what app to use to view the shared location. For example, I have Osmand installed with offline maps. Showing it in Osmand would be advantageous in case of slow a data reception, a depeleted data plan, or the wish to navigate to the shared location or bookmark it.

#### General information

* **Version:** 2.4.3+fcr FDroid
* **Device:** Xiaomi Redmi Note 4
* **Android Version:** LineageOS 15.1 with MicroG, Xposed+XPrivacyLua
* **Server name:** trashserver.net
* **Server software:** no idea
* **Installed server modules:** no idea
* **Conversations source:** F-Droid

#### Steps to reproduce

1. press "share location" menu on another device
2. wait for shared location to pop up on my device
3. tap on the shared location

#### Expected result

I'd expect for some kind of Android Intent to open up, or something that gives me the choice what app to view the location with. I have Osmand installed, which can handle such things without relying on data plan.

#### Actual result

After some waiting for it to load, a bespoke map viewer opens up with tiled map data.

#### Debug output

n/a (no crash)

**Comment by licaon-kter** [comment]
Copy the location and paste it in your favourite app?

I feel this would just leak the location to Google every time I share one, since it would pop-up in Maps and not in the local view.

**Comment by iNPUTmice** [comment]
Long press for 'Open with'

**Comment by TjrGithub** [comment]
Hmm. If I long-press share, it proposes a lot of completely unrelated apps, but doesn't propose Osmand. If I long-press open, it does fire up Osmand.

I wish this were more intuitive.
