### ISSUE TITLE
Information about what kind of muc

### ISSUE THREAD

**Issue by meaz** [siacs/Conversations#3422]
It would be nice to be able in what type of muc we're in: public one or private one. Perhaps in the muc details.

**Comment by licaon-kter** [comment]
@meaz When you look at details, if it says "channel" is public.

**Comment by meaz** [comment]
Thanks @licaon-kter 
@iNPUTmice if I may, i think the sementic difference between "Chat groups" and "Channel" is not that obvious. Why not changing it by "Private chat" and "Public chat"? It seems more clear, no?

**Comment by licaon-kter** [comment]
@meaz Look at "New" button labels.

**Comment by meaz** [comment]
@licaon-kter in French, I have "Create a private chat conversation" and "Create a public canal". I still think if would be more comprehensible for everyone to just have "Create a private chat" and "Create a public chat".

To me, in those "New" buttons, the only important words are "private" and "public", there are the one people would directly see and understand, whereas "Chat groups" or "Channel" are not as clear. What really is a channel? a group chat? I mean in common language. For example, if you change "Create public group chat" by "Create public channel", people with just understand that what they're creating is public. The same with "Create private group chat" replaced by "Create private channel": they would understand that what they're creating is private.

I hope I make my point. I'm just trying to suggest something easier for everyone to understand, but I may be wrong.

**Comment by licaon-kter** [comment]
You can join the translation team on Transifex and fix that....or word it better.

**Comment by meaz** [comment]
I did create an account on Transifex but can  not join the French team because French is not available in the list of language and so I can not click on "Join team".
![transiflex](https://user-images.githubusercontent.com/13604424/55416056-6cb3d880-556e-11e9-93c2-dc0d07842b46.png)

**Comment by licaon-kter** [comment]
@meaz ask to be included and @iNPUTmice will accept and then you can
