### ISSUE TITLE
Http_upload not working with prosody in conversation

### ISSUE THREAD

**Issue by SpadeAces** [siacs/Conversations#3425]
#### General information

* **Version:** eg 2.4.2+fcd
* **Device:** Samsung J3 Pro
* **Android Version:** Android 6.0 Stock 
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** all community and basic modules to be specific "http_upload" 
* **Conversations source:** github

#### Steps to reproduce

1. Sending Image across clients doing well with text messages

#### Expected result

What is the expected output? 
it sends the image to the receiver 

#### Actual result
delivery failed, 

What do you see instead?
Error Message 
failed to connect domain.com/xxxx,xx,xxx,xxx (port 5281) after 15000ms:
isConnection failed: ECONNREFUSED 

#### Debug output

04-04 12:23:39.975 7518-6714/eu.siacs.conversations I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
04-04 12:23:41.345 7518-6714/eu.siacs.conversations I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-04 12:23:41.345 7518-6714/eu.siacs.conversations I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
04-04 12:23:41.935 7518-6714/eu.siacs.conversations I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-04 12:23:41.935 7518-6714/eu.siacs.conversations I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
04-04 12:23:42.245 7518-6714/eu.siacs.conversations I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-04 12:23:42.245 7518-6714/eu.siacs.conversations I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
04-04 12:23:42.855 7518-6714/eu.siacs.conversations I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-04 12:23:42.855 7518-6714/eu.siacs.conversations I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
04-04 12:23:43.185 7518-6714/eu.siacs.conversations I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-04 12:23:43.185 7518-6714/eu.siacs.conversations I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
04-04 12:23:43.775 7518-6714/eu.siacs.conversations I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-04 12:23:43.775 7518-6714/eu.siacs.conversations I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err: java.net.ConnectException: failed to connect to www.instabuzz.tech/198.54.117.210 (port 5281) after 15000ms: isConnected failed: ECONNREFUSED (Connection refused)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:238)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at java.net.Socket.connect(Socket.java:882)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:1222)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:416)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:319)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:399)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:110)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at eu.siacs.conversations.http.HttpUploadConnection.upload(HttpUploadConnection.java:183)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at eu.siacs.conversations.http.HttpUploadConnection.access$300(HttpUploadConnection.java:30)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at eu.siacs.conversations.http.HttpUploadConnection$1.lambda$success$0(HttpUploadConnection.java:138)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at eu.siacs.conversations.http.-$$Lambda$HttpUploadConnection$1$xe9LFzy6COS1JMdivVN6RPSpYq4.run(lambda)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at java.lang.Thread.run(Thread.java:818)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err: Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:223)
04-04 12:23:44.105 7518-6714/eu.siacs.conversations W/System.err: 	... 18 more
04-04 12:23:44.105 7518-6714/eu.siacs.conversations D/conversations: http upload failed failed to connect to www.instabuzz.tech/198.54.117.210 (port 5281) after 15000ms: isConnected failed: ECONNREFUSED (Connection refused)
04-04 12:23:44.135 7518-7518/eu.siacs.conversations I/InjectionManager: dispatchCreateOptionsMenu :eu.siacs.conversations.ui.ConversationsActivity
04-04 12:23:44.135 7518-7518/eu.siacs.conversations I/InjectionManager: dispatchCreateOptionsMenu :eu.siacs.conversations.ui.ConversationFragment
04-04 12:23:44.135 7518-7518/eu.siacs.conversations I/InjectionManager: dispatchPrepareOptionsMenu :eu.siacs.conversations.ui.ConversationsActivity
04-04 12:23:44.135 7518-7518/eu.siacs.conversations I/InjectionManager: dispatchPrepareOptionsMenu :eu.siacs.conversations.ui.ConversationFragment

**Comment by licaon-kter** [comment]
So your server refuses the connection... fix it.
