### ISSUE TITLE
(Encrypted) image shared with WhatsApp is considered a file, not an image

### ISSUE THREAD

**Issue by stevenroose** [siacs/Conversations#3426]
If I receive an (encrypted) image from a contact and press the Share button in the image view screen, and select WhatsApp, it shares the file as a file instead of as an image.

**Comment by licaon-kter** [comment]
Any other app?

**Comment by stevenroose** [comment]
Hmm, confirmed that it works if I long press the image and press `Share with...`. So it must be the galary app that is providing that view. Standard Android gallery...
