### ISSUE TITLE
Delivery Error messages unreadable in dark color theme

### ISSUE THREAD

**Issue by cfra** [siacs/Conversations#3428]
#### General information

* **Version:** 2.3.6+pcr
* **Device:** eg Google Pixel 2 XL
* **Android Version:** 9 Stock
* **Server name:** conversations.im
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Send message which can't be delivered

#### Expected result

What is the expected output? 

The error message should be clearly readable. A color which could be used here would be yellow.

#### Actual result

What do you see instead?

The error message is very low contrast. To me, it is almost invisible as the red appears similarly dark as the background of the message itself.

![conversations](https://user-images.githubusercontent.com/1347051/55725894-eb958f00-5a0e-11e9-9ee6-5a84b650b072.jpg)

**Comment by licaon-kter** [comment]
Why so old version?

It's readable to me...

**Comment by iNPUTmice** [comment]
@cfra can you read this? https://gultsch.de/files/contrast.png

**Comment by trwnh** [comment]
@iNPUTmice that screenshot is better, and is at least "readable"

**Comment by cfra** [comment]
@iNPUTmice that looks a lot better. Thank you very much for the quick resolution. :+1:

@licaon-kter no idea. I installed it via playstore and assumed it would autoupdate. Apparently, it did not. Will look into it.
