### ISSUE TITLE
F-Droid version now requires location permission?

### ISSUE THREAD

**Issue by TRSx80** [siacs/Conversations#3429]
#### General information
* **Version:** 2.1.4
* **Device:** Samsung Galaxy s5
* **Android Version:** LineageOS 12.1 (Android 5.1.1)
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** I don't remember now and shouldn't be relevant to issue
* **Conversations source:** F-Droid

Version listed above is what I am on, because somewhere after that it was going to require location permissions, and I said no. What for, in a messaging app? And on F-Droid version, no less? So I am now stuck on several versions old.

I don't want to come across as ungrateful, in fact quite the contrary. You are making a great product: polished, functional, and rock-solid reliable. My hat is off to you. I have read your reasoning for creating a good, modern messaging app based on open protocols and I strongly agree. I have been sick of siloed messaging applications ever since the days of AOL IM, etc. I run my own server, help others to do the same, as well as trying to promote XMPP messaging (and F/LOSS in general) whenever the topic comes up. So I was just very disappointed and puzzled to see this permission requirement change.

I realize this happened a while ago, however until now I haven't had the time to come and ~~REEEEEEEE~~ register my objection.

**Comment by licaon-kter** [comment]
Why the old version? Latest is 2.4.3.

Yes...if you want to share your location, else not, it will ask for it on Android 6 or later, as expected, but on 5.1.1 it will just get it, can't you disable it?
