### ISSUE TITLE
Add a block button when someone wants to add you to their buddylist

### ISSUE THREAD

**Issue by allo-** [siacs/Conversations#3430]
When someone you do not know sends you a message that is spam, you have an instant "block" button for the user or the whole server.

When the same spammer wants you to allow them to add you to their buddylist before sending his first message, there is only a "Accept" button, but no easy "block" button.

It would be nice to have buttons like "accept", "do not accept", and "block" instead of only an accept button.

**Comment by licaon-kter** [comment]
Long press on ALLOW?

**Comment by allo-** [comment]
This works. 
But it is REALLY counter-intuitive.
I would not have known that this button as secondary options at all, but even then I would not suspect that behind "allow" there is a menu with a "block" item.

**Comment by licaon-kter** [comment]
I agree...long press actions are not intuitive.

**Comment by allo-** [comment]
When someone just asks you to allow them to add you, the screen is empty anyway. So there should be enough room to place an additional button.
(I need to wait for the next spam message to see if it could fit in the message itself)

When you're already chatting back and forth, the block button does not need to be that prominent when they eventually try to add you. But facing quite a bit of spam currently, I would like to have a quick block button for anything coming from unknown users.

**Comment by licaon-kter** [comment]
I'm not sure that banner can be bigger

**Comment by iNPUTmice** [comment]
We only have so much space. At the current state I’m considering spam blocking a bit of an expert option which is ok to be hidden.

**Comment by allo-** [comment]
On my old jabber.org account I get 10 Spam messages per day. I do not think that Spam blocking is an expert option in this case.
In general, the flow for dismissing the message could be improved, but an obvious block button would be a good start.

Another smaller issue: when the sender jid is abbreviated in the header, it is unclear what domain will be blocked with block domain.

I would imagine two buttons
(Block "spammer@spam")(block domain "spam")

(in my case domain blocking is useless anyway as the spammers use hundreds of random domains)

**Comment by iNPUTmice** [comment]
If you have 'an old jabber.org account' you are by definition an expert. Don’t extrapolate your experiences with jabber.org and other accounts that have been around for a long time to the average user.

If we ever do a redesign we might get rid of the snackbars and do something like whatsapp does with the top bar (that Conversations ironically had ~5 years ago as well)

**Comment by allo-** [comment]
I am probably kind of an expert. But I think jabber.org will not be the only server with spam (Their server is a mess nowadays, but others may be as well) and I am annoyed about two different and one less intuitive ways of blocking even as an expert.

Your redesign suggestion sounds good, but probably takes more time and discussions about design before it will be implemented?
