### ISSUE TITLE
UI: Private message - improved appearance

### ISSUE THREAD

**Issue by Echolon** [siacs/Conversations#3432]
Hello,

I would like to suggest an interface improvement to make it more clear to the user whether the user is in the private message mode or not. I only could found this related issue: #3142 

So, here is my simple sketch. Once started a private conversation, there is appears a green bold border along the text field as well as a little flag/register telling the user which recipient will receive the message - not only by the empty text field before typing.

<img src="https://user-images.githubusercontent.com/29168011/55996285-3c2f1580-5cb7-11e9-8c5a-8856835b1815.jpg" width="350">

So, finally during the whole conversation the user always knows that he or she is in the private mode. This can help prevent very unpleasant misunderstanding :)

Kind regards

**Comment by licaon-kter** [comment]
Is that border an Android lib thing?

**Comment by Echolon** [comment]
Hm, I draw that thing myself. No idea :neutral_face:
