### ISSUE TITLE
Upcoming changes in XEP-0308: Last Message Correction

### ISSUE THREAD

**Issue by lnjX** [siacs/Conversations#3437]
There are upcoming changes in the expected behaviour regarding last message correction:
https://github.com/xsf/xeps/pull/781

#### Steps to reproduce
Correct a message multiple times.

#### Expected result
The id of the original message should always be used as replacement id.

#### Actual result
If you correct a message twice (or more) the id of the last correction is used.

**Comment by iNPUTmice** [comment]
be4953b1e477c693df58e58e7e03ad467239ced4 adds read (receive) support for LMC version 1.1 - In half a year or so we will switch over write (send) support.

**Comment by iNPUTmice** [comment]
2.6.1 switched to write (send) support.
