### ISSUE TITLE
Suggestion: Allow users to sign up for a FREE conversations.im account

### ISSUE THREAD

**Issue by Zig-03** [siacs/Conversations#3443]
Hi and thank you everyone who contributes to this great project! (_my first post here_ :smiley: )

Right now, if a user downloads Conversations from F-droid, he has to choose from going with the trial period (6 months) or paying 8 euros/year or to sign up on another server and come back and sign in into Conversations - all this I think is a big entry barrier, especially for someone who doesn't wanna pay at that moment _(I know, you'd say that they can choose the trial period, but this would mean that IF they'd later decide they don't wanna continue using conversations.im account, they'll have to announce all their contacts about his new account, and then make them add him/her  to their contacts list, etc..)_.

And let's not forget that most popular IMs, including those that are privacy and security centered are FREE and so I was thinking why not adopt this strategy as well and come up with another way to monetize the service? A few ideas I have:
- limit the functionalities of free accounts, thus reducing the load on your servers. For example, no MAM and Video Chat support for free accounts.
- once a week, make a pop-up window appear that would ask for an account upgrade, and that would remind the user that he is using a free account and that hosting a server isn't cheap.

Maybe someone else has some better ideas?

**Comment by alexara** [comment]
> limit the functionalities of free accounts (...) no MAM and Video Chat support for free accounts.

> once a week, make a pop-up window appear that would ask for an account upgrade

I don't think reducing the UX or using annoying popups is any helpful for onboarding new users.

Have you seen https://github.com/siacs/Conversations/issues/3440 ?

**Comment by iNPUTmice** [comment]
We are currently very happy with the way conversations.im is operating and have no plans of changing that.
