### ISSUE TITLE
HTTP File upload failed 

### ISSUE THREAD

**Issue by golangbu** [siacs/Conversations#3449]
Http upload was working fine . From yesterday it was not working 
When I am trying to upload image on the server. I am getting handshake failed

avax.net.ssl.SSLHandshakeException: Handshake failed
 W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:302)
 W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1480)
 W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1424)
     at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1368)
 W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:219)
W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:142)
 W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:104)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:325)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:470)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
 W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
 W/System.err:     at http.HttpUploadConnection$FileUploader.upload(HttpUploadConnection.java:180)
 W/System.err:     at http.HttpUploadConnection$FileUploader.run(HttpUploadConnection.java:153)
    at java.lang.Thread.run(Thread.java:764)
W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7b90c4a708: Failure in SSL library, usually a protocol error
W/System.err: error:1000043e:SSL routines:OPENSSL_internal:TLSV1_ALERT_INAPPROPRIATE_FALLBACK (external/boringssl/src/ssl/tls_record.cc:592 0x7b7a711908:0x00000001)
 W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err:     at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:383)
W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
 W/System.err:

**Comment by iNPUTmice** [comment]
Please fill in the issue template including app version and what server you are using. Since nothing has changed on Conversations since yesterday I would suggest there is something wrong with your server.
