### ISSUE TITLE
Make more use of contact NAMES.

### ISSUE THREAD

**Issue by stevenroose** [siacs/Conversations#3453]
People are not e-mail addresses. I always link my Jabber contacts with the contacts in my contact book, so I never see XMPP addresses.

I only recently noticed that Conversations just shows XMPP addresses if you don't do that. I didn't do thorough research, but I think that using **names** is very important for UX.

1. Ask a users name when he first opens the app, along with the avatar. I think name is more important than avatar so I'm surprised it is not asked.
2. Use this name (or first name based on it) by default in MUCs as nickname instead of username.
3. Show contact by the name they set themselves (vCard fetch or something). Unless you have a nickname specified in the roster, but fall back to their own name.

**Comment by paskalito** [comment]
You send your messages to xmpp adresses not to people. (you just hope that the people actually own these accounts and then read and respond etc.)

apart from that i don't know if theres a space for names in the xmpp protocol. the very nice thing about xmpp dough imho IS that it is only an adress. Supersimple and metadatacautios.

Also one person can have as many xmpp accounts as they want. 
And also if you care about names then you also can just rename people however you like.

**Comment by stevenroose** [comment]
@paskalito vCards are already a thing in XMPP and they are actively used for avatars. So I'm not trying to change any protocol here or add any extra information to people's records. I'm just saying that the field exists and if a user decides to fill it, it should be used by clients because it's far more informative than a JID.

**Comment by Echolon** [comment]
If no information is provided I think its always nicer to show the name of the ID without the domain:

jondoe@domain.com --> jondoe

**Comment by Wonko7** [comment]
If you rename a contact with another client (pidgin in my case), conversations uses it instead of the address. What's missing is a way to edit the name/alias within conversations? 

Or did I miss something in the UI?

**Comment by licaon-kter** [comment]
@Wonko7 menu, contact details, use pen icon to edit ?

**Comment by Wonko7** [comment]
@licaon-kter I missed the pen icon, thanks :)

**Comment by iNPUTmice** [comment]
I think point 2 & 3 have been implemented for a very long time (even before you posted this). Point 1 has been implemented with 2.6.2
