### ISSUE TITLE
Seperate conversation-lists for accounts

### ISSUE THREAD

**Issue by BaumGuard** [siacs/Conversations#3461]
It would be nice, if Conversations had the ability to create a conversation-list for each account, because sometimes it's confusing when you don't know, from which account you are writing.
Gajim has that feature, so why not integrate it into Conversations?

**Comment by licaon-kter** [comment]
The usecase is multiple accounts connected to the same MUC?

**Comment by BaumGuard** [comment]
@licaon-kter Yes, but in my opinion that could also be solved by making an own list for the MUCs.

**Comment by iNPUTmice** [comment]
There are other clients that make it easier to distinguish what account is being used. Conversations deliberately does not do that to not clutter the UI with useless garbage.
It generally follows the idea of 'use your work account to talk to your colleagues and your personal account to talk to your friends. and based on the contact you know what account you are using.'
