### ISSUE TITLE
[Feature request]: enable by default notifications by unknown

### ISSUE THREAD

**Issue by danjde** [siacs/Conversations#3463]
Hi Devs!
We are an [Italian association](https://www.3x1t.org/), and would like to inform you that for our (newbies) users, the option "notifications by unknown" should be enabled by default.
Otherwise it creates problems for inexperienced users.

Thanks!

Davide

**Comment by licaon-kter** [comment]
/close as invalid

https://github.com/siacs/Conversations/blob/master/src/main/res/values/defaults.xml#L6

**Comment by danjde** [comment]
Ah, this mean that on the current release:
 
`<bool name="notifications_from_strangers">true</bool>`

notification from strangers is enabled.

Could you confirm please?

Thanks!

**Comment by licaon-kter** [comment]
Been like that since 2.3.11

But, if it was off in a prior version in won't turn on on update.
