### ISSUE TITLE
Feature request: options to reduce iddle traffic

### ISSUE THREAD

**Issue by sergey-feo** [siacs/Conversations#3464]
Hello! Excuse me for my poor English please :-) 

#### General information

* **Version:** 2.5.1+pcr
* **Device:** redmi 5
* **Android Version:** 7.1.2
* **Server name:** conversations.im
* **Conversations source:** Google Play

#### Steps to reproduce

1. Start app
2. Do nothing

#### Actual result
When I do nothing, Conversations creates traffic about several kylobytes per hour in my case.
Feature request: add some options that can significantly reduce this iddle traffic (just guesses: rare server pings, do not transmit and receive presence states, etc).

With best regards, Sergey

**Comment by iNPUTmice** [comment]
These features have already been implemented.
