### ISSUE TITLE
Instant rejoin after kick

### ISSUE THREAD

**Issue by ritzmann** [siacs/Conversations#3466]
#### General information

* **Version:** 2.5.1
* **Device:** Sony XZ1C
* **Android Version:** Android 8.1
* **Server name:** rooms.dismail.de
* **Server software:** ejabberd
* **Installed server modules:** unknown
* **Conversations source:** F-Droid

#### Steps to reproduce

1. As moderator in a public MUC, with a XMPP client that supports kicks like Gajim, select a MUC member that uses Conversations and choose to kick member.

#### Expected result

Member is not in the MUC anymore, should be informed that she was kicked and needs to rejoin manually.

#### Actual result

Conversations seems to immediately and automatically rejoin the MUC.

**Comment by licaon-kter** [comment]
And that's a bug because a user rejoining manually makes that user less ban-worthy?

**Comment by ritzmann** [comment]
Rephrasing expected and actual result. Sorry, should have tested that first. As moderator, I simply see quite a few users rejoin immediately without realizing that this is frowned upon.

*Expected result*

Member is informed that she was kicked as result of a moderator action.

*Actual result*

User gets message "you were kicked out of this group chat" together with a join button. Inexperienced users may mistake this message for a network level problem. The convenient join button makes it too easy to immediately rejoin.

**Comment by fuesschen** [comment]
Also it would be important to display the reason of beeing kicked.

**Comment by iNPUTmice** [comment]
> As moderator, I simply see quite a few users rejoin immediately without realizing that this is frowned upon.

Is this frowned upon?

I’m not very onboard with using kicks as a way to punish users.
