### ISSUE TITLE
geo: links in messages

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#3469]
...would be nice to be treated as expected, with a show location button.

Looking back: https://github.com/siacs/Conversations/issues/1881 this was a feature at some point?

**Comment by contrapunctus-1** [comment]
Ah, I was making an issue about this, too -

~~# When sharing a location - register for geo: links
Currently, it is a total pain to share a location from a map application like OsmAnd or Maps.me to Conversations. Most such applications support sending a geo: link - Conversations should offer to handle them.~~ Argh, this is not true. Only OsmAnd does that (as does Vespucci, but that's a map editor, not something DUAs use.) Even MAPS.ME has a textual message. It would still be nice if Conversations registered for geo: links, though.

# Opening a geo: link - be consistent
Currently, a geo: link by itself is rendered as a button and _is opened only by Conversations_ (I tried clearing defaults for Conversations, but this behavior persisted). A geo: link sent as part of a message (e.g. "here I am geo:lat,lon") is handled better - all applications registered for geo: links are offered.

Buttons should also behave the way the links currently do.

**Comment by iNPUTmice** [comment]
This was the case in Conversations 1.x. However people really wanted Conversations to include it's own map viewer because they couldn’t be bothered to install their own. You can long press a 'Show location' button to get a 'open with' context menu item.
