### ISSUE TITLE
Conversations crashes after retrieving MAM-message for certain contact in conference room

### ISSUE THREAD

**Issue by IUnderstandLetsChangeMyUsername** [siacs/Conversations#3470]
#### General information

* **Version:** 2.5.2+pcr
* **Device:** Google Pixel 2 XL
* **Android Version:** Android 9 
* **Server name:** creep.im
* **Server software:** ejabberd 18.12.1-1~afa90 
* **Installed server modules:** MAM
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Open Conversations.
2. Have a chat room in bookmarks with MAM enabled.

#### Expected result

Conversations is able to parse retrieved messages without crashing, or degrade gracefully. For unsuccessfully decrypted messages it's better to mark them as unsuccessfully decrypted rather than crashing. Or something.

#### Actual result

Conversations tries to reconnect, but some inner module crashes and the whole process stuck in the loop.

#### Debug output

````
05-28 19:24:53.823 W/conversations(16410): AxolotlService (ME@SERVER.IM): Failed to decrypt message from FRIEND@SERVER.IM
05-28 19:24:53.823 W/conversations(16410): eu.siacs.conversations.crypto.axolotl.CryptoFailedException: Error decrypting SignalMessage
05-28 19:24:53.823 W/conversations(16410):      at eu.siacs.conversations.crypto.axolotl.XmppAxolotlSession.processReceiving(XmppAxolotlSession.java:132)
05-28 19:24:53.823 W/conversations(16410):      at eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage.unpackKey(XmppAxolotlMessage.java:279)
05-28 19:24:53.823 W/conversations(16410):      at eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage.decrypt(XmppAxolotlMessage.java:288)
05-28 19:24:53.823 W/conversations(16410):      at eu.siacs.conversations.crypto.axolotl.AxolotlService.processReceivingPayloadMessage(AxolotlService.java:1410)
05-28 19:24:53.823 W/conversations(16410):      at eu.siacs.conversations.parser.MessageParser.parseAxolotlChat(MessageParser.java:123)
05-28 19:24:53.823 W/conversations(16410):      at eu.siacs.conversations.parser.MessageParser.onMessagePacketReceived(MessageParser.java:443)
05-28 19:24:53.823 W/conversations(16410):      at eu.siacs.conversations.xmpp.XmppConnection.processMessage(XmppConnection.java:779)
05-28 19:24:53.823 W/conversations(16410):      at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:640)
05-28 19:24:53.823 W/conversations(16410):      at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:486)
05-28 19:24:53.823 W/conversations(16410):      at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:380)
05-28 19:24:53.823 W/conversations(16410):      at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:457)
05-28 19:24:53.823 W/conversations(16410):      at java.lang.Thread.run(Thread.java:764)
05-28 19:24:53.823 W/conversations(16410): Caused by: org.whispersystems.libsignal.DuplicateMessageException: Received message with old counter: 1 , 0
05-28 19:24:53.823 W/conversations(16410):      at org.whispersystems.libsignal.SessionCipher.getOrCreateMessageKeys(SessionCipher.java:377)
05-28 19:24:53.823 W/conversations(16410):      at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:310)
05-28 19:24:53.823 W/conversations(16410):      at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:268)
05-28 19:24:53.823 W/conversations(16410):      at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:243)
05-28 19:24:53.823 W/conversations(16410):      at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:211)
05-28 19:24:53.823 W/conversations(16410):      at eu.siacs.conversations.crypto.axolotl.XmppAxolotlSession.processReceiving(XmppAxolotlSession.java:117)
05-28 19:24:53.823 W/conversations(16410):      ... 11 more
05-28 19:24:53.829 D/conversations(16410): ME@SERVER.IM: finished mam after 3(0) messages. messages left=false count=3
05-28 19:24:53.829 D/conversations(16410): ME@SERVER.IM: found 0 pending receipt requests
05-28 19:24:53.830 D/conversations(16410): ME@SERVER.IM: finished mam after 0(0) messages. messages left=true count=0
05-28 19:24:53.830 D/conversations(16410): ME@SERVER.IM: found 0 pending receipt requests
05-28 19:24:53.835 D/conversations(16410): ME@SERVER.IM: finished mam after 1(0) messages. messages left=false count=1
05-28 19:24:53.835 D/conversations(16410): ME@SERVER.IM: found 0 pending receipt requests
05-28 19:24:53.836 D/conversations(16410): ME@SERVER.IM: finished mam after 0(0) messages. messages left=true count=0
05-28 19:24:53.836 D/conversations(16410): ME@SERVER.IM: found 0 pending receipt requests
05-28 19:24:53.837 D/conversations(16410): ME@SERVER.IM: xml parser mishandled XmlPullParserException(expected: '>' actual: '/' (position:START_TAG (empty) <http:>@105:33691 in java.io.InputStreamReader@6fd8866) )
````

Hi Daniel! I found a bug which haunts me for a better part of the month, and finally I'm submitting a bug report.

So I have a conference room bookmarked, which I join at the app's startup. But the very strange thing occurs every now and then: when a friend of mine shares **some photo** taken with his phone (he also uses freshest Conversations from the Play Store), my Conversations crashes immediately.

To make things worse, since the "malformed" message is stored on the server and retrieved from it during the app's startup, I just can't hold to the connection. It connects, retrieves the message and crashes.

The interesting part is that **no one else** in this conference is experiencing the same problem. It fails **just for me**.

It happened to me multiple times. Once he is sharing a pic, my messenger goes fubar.

I tried different Conversations versions from Play Store and F-Droid. The issue persists.

The "fix" is to go to the conference room in question and pick "Clear history" from the overflow menu. This way you'll be able to connect next time, but, well, the history is gone.

**Comment by IUnderstandLetsChangeMyUsername** [comment]
If you need any additional debug, please don't hesitate to request.

**Comment by iNPUTmice** [comment]
I’m fairly certain that this happens because the server sends invalid XML. Since the entire connection is basically just one giant XML document there is basically no way for the client to recover from that even if it 'only' happens mid message. It might even be a security issue to attempt to recover from that.
I have seen something similar before and on that occasion I suspected ejabberds mam/xml compression to be the cause for that issue. However the user back then just deleted their server side archive and we were unable to investigate. I suggest you either bring this to the attention of the ejabberd developers or attempt to update the server software first.

**Comment by licaon-kter** [comment]
@iNPUTmice This? https://github.com/processone/ejabberd/issues/2744

@IUnderstandLetsChangeMyUsername If that's the issue an updated ejabberd (to 19.2 or 19.5) should fix it. As ejabberd 19.05 just got released, iirc the creep.im server uses the jabber.at Debian repo but they're still on 18.12 for some reason.

**Comment by iNPUTmice** [comment]
This one looks slightly different. But yes the issue you are referring to is the issue I had in mind. So this could be a different bug in the compression - if creep.im has that enabled. In any case I would probably update ejabberd and take it from there.

**Comment by SamWhited** [comment]
Surely if Conversations crashes this is also a bug in Conversations? I'd expect it to disconnect and tell me there was an error if invalid XML is received, not crash.

**Comment by IUnderstandLetsChangeMyUsername** [comment]
creep.im uses jabber.at repo and this is the reason the ejabberd is still at 18.12. jabber.at itself is at  18.09-1~afa90, so that means they didn't update the repo for some time.

If you are saying this is an ejabberd's issue then I'm going to close this ticket. However, I encourage anyone interested to look into it in Conversations, since I strongly believe that login loops, no matter the reason it caused them, should be avoided.

At the very least, user should be given an option to mitigate this. Like "We detected some malformed messages coming from the server which may crash Conversations. Would you like to NOT to retrieve these?"

**Comment by licaon-kter** [comment]
@IUnderstandLetsChangeMyUsername server got updated, this is fixed?

https://compliance.conversations.im/server/creep.im/

**Comment by IUnderstandLetsChangeMyUsername** [comment]
@licaon-kter yes, this totally fixed that.
