### ISSUE TITLE
Default to storing images in private /data directory 

### ISSUE THREAD

**Issue by RobertCochran** [siacs/Conversations#3471]
#### General information

* **Version:** 2.4.3+fcr
* **Device:** Samsung Galaxy S10+
* **Android Version:** Samsung-flavor Android 9
* **Server name:** Self-hosted
* **Server software:** ejabberd 18.12.1
* **Installed server modules:** All listed under 'server info', though it doesn't matter for this report AFAIK
* **Conversations source:** F-Droid

#### Steps to reproduce
1. Have someone send you an image
2. Download it, if you have to

#### Expected result
The image gets saved to a private directory by default, then provides an option for saving to a public directory.

#### Actual result
The image gets saved to a public directory in all cases.

#### Debug output
< Unnecessary in this case>

I have a friend, @Virepri , who does not like the behaviour of how images are saved by default. They cite two primary reasons:
* Gallery/photo viewer apps will pick them up and display them, causing clutter in the image list.
* Sensitive images, such as those that are NSFW, end up being easily findable by photo viewers and other apps. This presents a possible privacy issue.

Saving the image to private `/data` storage by default, and then allowing for copying into public directories, ala Signal Private Messenger, would to me be the most optimal solution.

**Comment by Virepri** [comment]
Thanks for pinging me, @RobertCochran.

Yeah, I dislike the current behavior of image saving as it not only clutters my camera roll, but there is the afformentioned privacy issue.

NSFW items aren't the only real issue here. Let's say we have a legal document that has an NDA on it. If it were distributed via conversations at the moment, every single app on my phone could read it the second I receive it. IMO, I should have control over where images and files I receive go and when they go there.

**Comment by licaon-kter** [comment]
> The image gets saved to a public directory in all cases.

The device is private and encrypted...right?

> Gallery/photo viewer apps will pick them up and display them, causing clutter in the image list.

Exclude that folder in the Gallery, either in that app or add a plain `.nomedia` file to the folder.

> This presents a possible privacy issue.

Don't run apps that you don't trust...don't grant storage permission to apps that you don't trust...use a firewall (eg. NetGuard) to block apps from leaking you data.

> Version: 2.4.3+fcr

Why not use the F-Droid client to get notified of app updates? Latest version is 2.5.1 or 2.5.2.

@Virepri Build your own, make it true: https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/Config.java#L113

I'll repeat my self from another issue:
_How do I share a file from Conversations then?_
You'd say long press on image, share with?
_Wait....see, I got an image on my old account about a year ago, it was in a MUC that we closed, that account was disabled for a while and now deleted._
_Ok, long press where exactly?_
Oh...export...where would the export function for a deleted bookmark live exactly? Oh, you'd delete my files? Mmmmmnope

/duplicate https://github.com/siacs/Conversations/issues/1948 https://github.com/siacs/Conversations/issues/3135 ...

**Comment by RobertCochran** [comment]
> @Virepri Build your own, make it true: https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/Config.java#L113

If making this particular change is literally just flipping a single config flag, why is it not the default? Or, even if it's not the default, reworking the code slightly so that it is a runtime configurable setting instead of a setting set in stone at compile time? I honestly don't think it's reasonable to essentially force someone to have to track upstream and manually rebuild and install for every release just because they want a *more secure* setting. :/

**Comment by licaon-kter** [comment]
@RobertCochran Did you read my last block of text?

**Comment by RobertCochran** [comment]
I did read the last block, but evidently I'm having trouble understanding it what it's supposed to mean. Could you please go into more detail about what exactly the problem is? That block of text is sparse and lacks context all by itself.

**Comment by licaon-kter** [comment]
How do you treat files exactly? Per chat? What happens when you close and delete a bookmark? Is an internal filemanager needed?

When you pop a thought here, please follow it through all the operations involving the files, share, delete, edit....and operations regarding the actual chats where these files appear.

**Comment by RobertCochran** [comment]
>How do you treat files exactly? Per chat?

If you're asking about where to store them, then probably just store them in `$data_dir/$remote_jid/images/` (just in case something else needs to be stored with the remote JID on the fs in the future).

>What happens when you close and delete a bookmark?

While I'm not exactly up-to-speed on all of the Jabber terminology (sorry), my general approach is garbage-collector-style: if it's accessible through a chat/bookmark, then it'll it stay in the appropriate images directory, and if the chat/bookmark goes away, then so does the images directory. Deciding to reopen a chat/bookmark means that, if you have MAM - great, it'll create the directory and pull the images in and it'll basically be as if you'd never closed it in the first place. Otherwise you'll just get the new images.

>Is an internal filemanager needed?

I don't think so; Signal gets along fine without one. I've never felt the need for one.

> When you pop a thought here, please follow it through all the operations involving the files, share, delete, edit....and operations regarding the actual chats where these files appear.

I mean... a menu item when you long-press on the image that is 'copy to public storage' and maybe a 'delete' button are about all I think are necessary. Conversations shouldn't have to grow it's own image editor. It doesn't make much sense to me personally to delete images from conversations - either the conversation is still going and I want the images I've downloaded to remain or I delete the chat and I want the images to go away, so I don't have anything regarding file manipulation in mind at the chat-level.

@Virepri does all of this sound sane so far?

**Comment by iNPUTmice** [comment]
We might include a more complete file browser some time in the future. However this has absolutely no priority. Until this exist it won’t be feasible to store files in private storage.

The vast majority of people want/need the convenience of being able to manage their files with the file manager / galleries provided by the operating system.

Besides if you are receiving important data on your phone it is good advice to lock down (and encrypt) your phone properly.

**Comment by Virepri** [comment]
>How do you treat files exactly? Per chat?

Simple. For the application as a whole. All that has to be stored per-chat is a image name.

>What happens when you close and delete a bookmark?

Clean up the images associated with the chat.

>Is an internal filemanager needed?

I don't personally need one, but I can see the use of it.

Literally all I see as necessary here is just a set of context menu actions on an image in a chat. Save to internal storage, clear cache, delete message.

If that's asking for too much, then sue me.

**Comment by licaon-kter** [comment]
> Clean up the images associated with the chat.

I don't want to lose the files...

> I see as necessary here is just...

PR's welcomed I guess, as said above keep in mind what Q brings: https://www.xda-developers.com/android-q-storage-access-framework-scoped-storage/

**Comment by RobertCochran** [comment]
> I don't want to lose the files...

I'm still having trouble trying to what the problem is here... if you want to save a picture or file from a chat, then you should carefully save them to external media. Otherwise, it doesn't make sense to me to keep images when the chat is closed. Maybe then, there should be a "Save the files in this chat to external media?" checkbox on the delete confirmation dialog?
