### ISSUE TITLE
Notifications arrive with a delay

### ISSUE THREAD

**Issue by BaumGuard** [siacs/Conversations#3474]
Often notifications arrive some minutes after the message was received. I don't have that problem in Gajim, there the notifications arrive as soon as the message is received.
In the expert settings I have enabled the option that Conversations is being executed in the foreground and I have also disabled the accu-optimizing.
Why does this problem happen and how can I solve it?

**Comment by licaon-kter** [comment]
Device? Android version? F-Droid version? Server score on https://compliance.conversations.im ?

**Comment by BaumGuard** [comment]
Device: BQ Aquaris X (I had that problem also on another smartphone)
Android Version: 8.1.0
Conversations-version: 2.5.2+fcr
Installed from F-Droid

You can have a look on the compliance-site. I use the XMPP-Server wiuwiu.de

**Comment by licaon-kter** [comment]
Do you get messages instantly when the app is on screen?

Do you get messages instantly when the app is is the background but the screen is on?

If you answer YES, then the device Android version is too aggressively killing apps and/or network connections. Try to find more settings where to whitelist Conversations in, like "unrestricted network access" and whatever you can find.

**Comment by philfry** [comment]
fwiw another solution is to "lock" conversations. Go to the recent-apps-window while conversations is running and press the lock symbol or the three settings dots (depending on your Android version) to keep conversations alive.

**Comment by BaumGuard** [comment]
@philfry I can't find a lock symbol. When I go to the settings, then to "apps and notifications", I can see the recently opened apps. But there is no lock symbol like you mentioned it.

**Comment by philfry** [comment]
The "recent apps" should open when pressing the left or right button (depending on where your back button is: it's the other one).

![Screenshot_20190617-122505](https://user-images.githubusercontent.com/1649785/59597898-301e6480-90fb-11e9-8965-f966163ba9fe.jpg)

**Comment by BaumGuard** [comment]
@philfry Okay, now I know what you mean. I'm sorry! But on my phone there's no lock button and no menu for that.

**Comment by iNPUTmice** [comment]
This is a general support question and not a particular bug in Conversations. I suggest you ask around in the Conversations group chat if you still have issues.
