### ISSUE TITLE
Feature request: Make self-messaging easier

### ISSUE THREAD

**Issue by Mikaela** [siacs/Conversations#3477]
#### General information

* **Version:** 2.5.2+pcr
* **Device:** Nokia 1
* **Android Version:** Android 8.1 Go Stock
* **Server name:** blesmrt.net
* **Server software:** Prosody?
* **Installed server modules:** all supported in server info
* **Conversations source:** Play Store Beta

#### Steps to reproduce

1. Open a new chat
2. Look for yourself in contacts

#### Expected result

I wish I saw all my accounts on top as something like "Note to self (mikaela@blesmrt.net)", "Note to self (mikaela@disroot.org") etc.

This is similar to what Telegram ("saved messages") and Signal ("note to self") offer and I think it would be practical in transferring private content, as I have scanned the QR codes of individual accounts. The difference is that Telegram is unencrypted and Signal is tied to mobile + desktops, so copying data between two Androids would be easier.

#### Actual result

I see a long list of contacts beginning with IRC and Matrix users due to their transported XMPP IDs and if I search for myself, I find myself with multiple accounts and am not sure if I have scanned their fingerprints and how to start verifying them.

**Comment by licaon-kter** [comment]
You are already verified.

**Comment by Mikaela** [comment]
> You are already verified.

What do you mean?

mikaela@blesmrt -> mikaela@blesmrt is verified by scanning my own QR codes everywhere
mikaela@disroot -> mikaela@disroot is verified by sacnning my own QR code everywhere
mikaela@blesmrt <-> mikaela@disroot is not verified unless I start separately scanning my QR codes again

And when I search for myself, I get multiple results which are unverified or I have to be very lucky to pick the verified one.

All other accounts also verify only themselves when scanned, so if there is a MUC with multiple accounts (ref: https://github.com/siacs/Conversations/issues/3074), those accounts need to scan accounts on the same phone separately in order to be verified.

**Comment by licaon-kter** [comment]
When you speak to yourself on the same account. (iirc, can't find the exact commit though)

**Comment by Mikaela** [comment]
Yes, however I am havibg difficulties finding that account and thus opened a feature request to find it more easily

**Comment by iNPUTmice** [comment]
You can use the 'Add contact' dialog to create a conversation with yourself.
