### ISSUE TITLE
Android App can not connect to server

### ISSUE THREAD

**Issue by Thomas301263** [siacs/Conversations#3479]
#### General information

* **Version:** eg 1.21.0
* **Device:** Samsung SM-T580
* **Android Version:** Android 8.1
* **Server name:** self hosted
* **Server software:** ejabberd 18.12.1.1
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** PlayStore 

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

Hi,
I upgraded my linux server to the latest version and now am using TLS1.3.
Before all works great but after the upgrade the APP Conversations which I got from
playstore can not connect to the server anymore.
Other clients like gajim pidgin are working.
As a test I installed the APP conversations-legacy and there the connection can be established.
So where is the difference between those two APPS?
BR
Thomas

**Comment by Thomas301263** [comment]
Sorry but I haven't seen that I should add  adb logcat -s conversations.
How can I get that informations from my tablet? I am not used to working with android so therefore I need help

**Comment by iNPUTmice** [comment]
https://github.com/siacs/Conversations/#i-get-stream-opening-error-what-does-that-mean
