### ISSUE TITLE
hide messages on lock screen

### ISSUE THREAD

**Issue by philfry** [siacs/Conversations#3481]
With Android 9 I'm unable to classify conversation's messages for the lock screen: Android 9 doesn't show any settings regarding what to display on the lock screen. Other apps offer such classification, see attached screenshots. Did I miss something?

#### General information

* **Version:** 2.5.2
* **Device:** OnePlus 3T
* **Android Version:** OOS 9.0.3 / Android 9
* **Server name:** self hosted
* **Server software:** prosody 0.11.2
* **Installed server modules:** …
* **Conversations source:** self build (from tag)

#### Steps to reproduce

1. lock screen
2. receive a message

#### Expected result

Some kind of anonymous notification that Conversation has received a message

#### Actual result

The complete message on the lock screen

#### Screenshots
![Screenshot_20190617-115952](https://user-images.githubusercontent.com/1649785/59596314-c2bd0480-90f7-11e9-96bb-3792eabfc2fc.jpg)
![Screenshot_20190617-120003](https://user-images.githubusercontent.com/1649785/59596315-c2bd0480-90f7-11e9-9f9e-a8167899f04e.jpg)

**Comment by iNPUTmice** [comment]
This is not the right screen. You need to press 'Nachrichten' to specically configure DND settings for notifcations of type 'Nachrichten'. Alternatively the setting 'Notfication Settings' from the Conversations Settings screen should get you right into the proper screen.
If this doesn’t work you need to report this problem to the vendor of your ROM.
