### ISSUE TITLE
Feature request: allow forcing single notification on N and above

### ISSUE THREAD

**Issue by cthu1hoo** [siacs/Conversations#3484]
Using latest source from git, behavior not related to server/platform.

I'd like to ask for being able to force a single notification on all platform versions if there's only one unread event pending.

The reason is, while this combined notification displays properly on my phone, it becomes useless while being synced to mi band 3 by Mi Fit. Mi Fit for some reason only forwards "1 unread notification(s)" part of the notification and it's impossible to see actual message text, so I have to dig for my phone all the time.

Stock behavior produces a notification which looks like this:

![stock](https://user-images.githubusercontent.com/47687909/59844849-893d0100-9364-11e9-94c0-c61af7a164cc.png)

I understand the point of group notifications if there's multiple events pending, but for a single event I'd prefer to be able to read actual message text:

![modified](https://user-images.githubusercontent.com/47687909/59844858-8d691e80-9364-11e9-9c77-11df85dec12b.png)

A tiny modification made notifications display properly on a band for me (NotificationService.java:400, commented out check for N):

```
if (notifications.size() == 1 /*&& Build.VERSION.SDK_INT < Build.VERSION_CODES.N*/) {
```

I understand that this is an esoteric request and I'm happy to just maintain the fork for myself but I'm sure other people use Mi Fit and would prefer this behavior to stock, which is why I'm posting this ticket. Maybe an advanced option? Thanks in advance for considering.

**Comment by iNPUTmice** [comment]
Are you using the MiFit app? A buddy of mine uses Notify and Fitness for Miband and reports no such issues.

**Comment by cthu1hoo** [comment]
Yes, latest Mi Fit from play store. I haven't tried the notify and fitness app but notifications also work properly with Gadgetbridge. It is a Mi Fit-specific problem, but in my opinion interacting properly with an official app might be a good idea. It's not like I could report anything to Xiaomi and get meaningful results.

**Comment by iNPUTmice** [comment]
I just got a Mi Band 3 the other day as well and from limited experience the notification handling of the Mi Fit app is completely broken. For example (and that's even worse than the issue you are describing) it shows connectivity error notifications which are clearly marked as local only. I think it's hopeless and I've personally switched to Gadgetbridge.
Creating an extra setting just for a limited (It will still break if you have more than one unread conversation) fix for a broken app for one device is probably not a good idea in terms of cluttering the settings screen when unnecessary options.

If you have problems with Gadgetbridge let's just fix those instead.
