### ISSUE TITLE
[Translation] Add bengali to the list of supported languages on Transifex

### ISSUE THREAD

**Issue by biswasab** [siacs/Conversations#3485]
I will help in translating conversations in Bengali (India).

**Comment by licaon-kter** [comment]
Sign in via Github, join a team, translate: https://www.transifex.com/siacs/conversations/

/close this

**Comment by biswasab** [comment]
@licaon-kter That language doesn't exist in transifex
`Can't find the language you want? Please perform a request language action before joining project translation.`
