### ISSUE TITLE
Message_deletion_values 

### ISSUE THREAD

**Issue by willemkuijpers** [siacs/Conversations#3486]
#### General information

* **Version:** eg 1.21.0
* **Device:** eg GooglePixel 3 / Android 8)

#### Steps to reproduce

Change values in arrays.xml > automatic_messages_deletion_values

#### Expected result

1 day changed to 60 seconds , message should be deleted in 1 minute

#### Actual result

Message are not deleted, after i have selected automatic_message_deletions 60 seconds.

How to fix this ?

**Comment by willemkuijpers** [comment]
Checked with logcat, 

deleted 0 expired messages 

After 30 minutes / 1800 seconds

I can not find where this is set

**Comment by iNPUTmice** [comment]
This is a bug tracker for Conversations not a replacement for the consulting and development service I'm offering.
