### ISSUE TITLE
How can i stop the updates from google play in the code?

### ISSUE THREAD

**Issue by HackM3nt3** [siacs/Conversations#3487]
I want to build my own conversations app and i don't want to receive the updates from google play in the cellphone where i will install it.

What lines in the code do i have to change to stop the updates? or what should i do?

**Comment by licaon-kter** [comment]
If you build it, and sign it, it will not be updated by other stores or other versions signed by others.

/close this

**Comment by HackM3nt3** [comment]
to sign it, i need to pay in google play and i´m not going to do that, i just want to stop the updates in the original code, that´s it, can you help me?

**Comment by HackM3nt3** [comment]
Thanks
