### ISSUE TITLE
I sent you an OMEMO encrypted message but your client doesn’t seem to support that.

### ISSUE THREAD

**Issue by Avispa** [siacs/Conversations#3488]
#### General information
* **Version:** I'm just the receiver (_Gajim_)
* **Device:** I'm just the receiver
* **Android Version:** I'm just the receiver
* **Server Software:** Prosody 0.10
* **Conversations source:** F-Droid

#### Steps to reproduce
* Receive an advertisement message from a regular, non tech affine, _Conversatons_ user.
(or)
*  Let something else get wrong randomly.

#### Actual result
`I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo`
`I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo`
`I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo`
_[sic: to illustrate my frustration]_
Useless, wrongly informed <sup>[1]</sup> 20 words long advertisement for _Conversations_ including a link to `conversations.im` for which ironically the certificate just expired yesterday: **NET::ERR_CERT_DATE_INVALID**.

#### Expected result
* Inform the user, that there are devices for which he doesn't encrypt the message. Which doesn't seem to be the case all the time.
* At least put some useful information about the device into the message, instead of putting a 20 words long ad which just clutters my chat.

PS: Sorry if you still read a lot of frustration between the lines. It is not the first time that this annoys me deeply with about roughly 10-15 clients.
______
_[1] I support OMEMO, you just didn't encrypt it._

**Comment by animeshkgupta** [comment]
Hi @iNPUTmice @Avispa ,

We are experiencing the same error for quite sometime while sending messages to some of the iOS and android clients.

Below is the error which is observed -

I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on
[https://conversations.im/omemo</body><markable](https://conversations.im/omemo%3C/body%3E%3Cmarkable)
xmlns="urn:xmpp:chat-markers:0"></markable><message_type xmlns="jabber:message:type">0</message_type><Caption></Caption><request xmlns="urn:xmpp:receipts"></request><error code="406" type="cancel"><blocked xmlns="urn:xmpp:blocking:errors"></blocked><not-acceptable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"></not-acceptable></error></message>

Could you help us with the information on how we should get this working?

Thanks

**Comment by kamalkumar13** [comment]
Hi @iNPUTmice  @Avispa,

We are getting similar issue for one client(iOS to iOS), While on other it's working

Message sent on server and its return to sender itself along with error :

<errortype="cancel" code="406" >
<blockedxmlns="urn:xmpp:blocking:errors" >
</blocked>
<not-acceptablexmlns="urn:ietf:params:xml:ns:xmpp-stanzas" >
</not-acceptable>
</error>

Is this blocked by receiver or something else?
Could you help us?

Thanks
