### ISSUE TITLE
Conversations does not fully adhere to XEP-0393: Message Styling

### ISSUE THREAD

**Issue by Olf0** [siacs/Conversations#3489]
#### General information

* **Version:** 2.5.2-fcr
* **Device:** Jolla 1
* **Android Version:** AOSP 4.1.2 based Android runtime environment (AlienDalvik with API level 16)
* **Server name:** multiple
* **Server software:** ejabberd and prosody
* **Installed server modules:** All XEPs the [XMPP Compliance Tester tests for](https://compliance.conversations.im/tests/) are supported
* **Conversations source:** F-Droid

Conversations does not fully adhere to [XEP-0393: Message Styling](https://xmpp.org/extensions/xep-0393.html)

Of the examples in [section 5.2 *Spans*](https://xmpp.org/extensions/xep-0393.html#span), the fourth one of the first bullet list (`*strong*plain*`) does not work as advertised in XEP-0393.
So do `_italic_plain_` and `~strikeout~plain~`, which are not mentioned as examples but should also work differently (according to XEP-0393) as currently implemented in Conversations.
Consequently composed sequences as e.g. `_italic_~strikeout~plain_` or 
`~strikeout~_italic_plain~` also do not work as advertised.

Side note: Trying to escape the offending, closing (last) meta-character does not work, e.g. `_italic_~strikeout~plain\_` or `~strikeout~_italic_plain\~`
This is the expected result, as XEP-0393 does not propose any escape characters.  Actually I think it would be a bad idea to introduce one.

Note that e.g. `_italic_plain_italic_plain` or `_italic_~strikeout~_italic_plain` show a visually different failure mode.

#### Steps to reproduce

Input to a message in Conversations:
 `*strong*plain*`
`_italic_plain_`
`~strikeout~plain~`

#### Expected result

\***strong**\*plain\*
\_*italic*\_plain\_
\~~~strikeout~~\~plain\~

#### Actual result

\***strong\*plain**\*
\_*italic\_plain*\_
\~~~strikeout\~plain~~\~

#### Impact

I stumbled across this a couple of times, when writing `*strong*plain*strong*` resulted in \***strong\*plain\*strong**\* being displayed in Conversations, instead of \***strong**\*plain\***strong**\*
This combination (ABA) of character attributes is actually common and useful in contrast to the rather academic examples above.

Extensions of this sequence as ABCA logically also fail in the same way.
As denoted above, the extensions ABAB (e.g. `_italic_plain_italic_plain`) or ABAC (e.g. `_italic_~strikeout~_italic_plain`) show a visually different failure mode (the technical reason may still be the same).

This is annoying and prohibits writing any words composed of plain, **strong**, ~~struck out~~ and *italic* characters in Conversations for long.

#### P.S.

**All** other aspects of XEP-0393 seem to be working fine in Conversations.
I tested nested attributes extensively.
Thanks!

**Comment by iNPUTmice** [comment]
* Conversations is a testing ground for XEP-0393. So not adhering to the XEP is not a problem by itself. If we consider something to be working in Conversations it might as well make it back into the XEP
* Please talk about concrete rule changes (to the parser) and not examples.
* I believe the behaviour you are referring to was changed in this commit 6a06bcfd58fd773742f722f956a021a2345db90a for the reason explained in the commit message.
* FWIW the `*strong*plain*` examples renders the same in WhatsApp and Conversations.

**Comment by Olf0** [comment]
a. I am aware of that, but IMO this example (and the idea of a rule behind it) in the current XEP-0393 draft is perfectly valid.
I hoped to have this properly denoted in the **Impact** section of the original issue report above.

b. That is beyond my capabilities (especially in Java).
Side note: Sorry, this request sounds a bit like "provide at least code or your report is worth nothing". 😉  Hey, I took the effort to test most aspects of XEP-0393 in a organised manner, after having discovered it and seeing that the single deviating behaviour of Conversations explains an annoying issue I observed for long.

c. I tried to track, if this commit (#6a06bcf) was already in a release, but failed (it carries the tag 2.5.3, but I cannot find it in the commit diff of the 2.5.2 to the 2.5.3 release).
Is there a released version containing this commit, so I can at least retest?

d. What's WhatsApp? 😉
Is this really a proper reference point?

**Comment by licaon-kter** [comment]
@Olf0 that was released with 2.3.10 in Dec 2018

**Comment by iNPUTmice** [comment]
The commit I referenced is the one that deliberately deviates from the XEP after being compatible with it. It has been in Conversations for a while now. See the reasoning in the XEP. In short I do see a good reason why ```_Programmier_innen_``` should render like it currently does. You haven`t explained why ```*strong*plain``` should render the way you want it.
Besides your ```*strong*plain*strong*``` wouldn’t render that way according to the XEP either. The second strong would be plain because it doesn’t have a leading white space.
