### ISSUE TITLE
Feature request: presence 'invisible option'

### ISSUE THREAD

**Issue by magicbrothers** [siacs/Conversations#3491]
With 'Manage availability manually' in expert settings enabled, you can change your presence by hand to: online, away, not available, busy. 
Feature request: add the option 'invisible', which allows to seem to be offline. 
Because Conversations is a privacy focused client, it should be up to myself to show to all of my contacts if I am online or not.

See also Issue #880 'Invisibility'

**Comment by iNPUTmice** [comment]
If you already found #880 why open a new one?
