### ISSUE TITLE
Share intent ignores attachment

### ISSUE THREAD

**Issue by stevenroose** [siacs/Conversations#3492]
My favorite calendar app ([Business Calendar](https://play.google.com/store/apps/details?id=com.appgenix.bizcal)) has an option to share an event and it has a checkbox to "Include .ics file". When used, it opens the share intent layover menu to select an app to share with. When I select either ProtonMail of Gmail, an e-mail opens with the event summary line and the .ics file as attachment.
When I open Conversations, however, it just has the summary line, but no file attached.

I'm not an Android dev, but I assume this is because the intent has some extra field for a file somehow and Conversations is ignoring it. It would be nice if Conversations would accept that file and share it as well. (Of course preferably not without explicit user confirmation first.)

**Comment by iNPUTmice** [comment]
fixed in 719b35e4315a34d29767919bf8d5fc43f6a7b96c

**Comment by stevenroose** [comment]
Awesome!
