### ISSUE TITLE
Share the backup

### ISSUE THREAD

**Issue by contrapunctus-1** [siacs/Conversations#3493]
When creating a backup, it would be nice if Conversations either
* automatically started a share action for the backup file when the backup is complete

or
* had a "Share" button in the "Your backup has been created" notification.

Personal use case - ~~I'd like to share the backup to a Syncthing folder.~~ Ah, it's unnecessary for Syncthing users who backup the whole Conversations folder,  as I do.

Other advantages -
1. this is how most Android applications I've seen handle backups (e.g. Contacts app)
2. don't need to navigate to the file in the file manager

**Comment by iNPUTmice** [comment]
fixed in b68851b719d89f2f6b7746189d34ccf5d2f295a6
