### ISSUE TITLE
Implement XEP-0201: Best Practices for Message Threads

### ISSUE THREAD

**Issue by andypl** [siacs/Conversations#3494]
I have made a smiliar feature request for ConverseJS - https://github.com/conversejs/converse.js/issues/1646.

The whole idea is to simplyfing discussion by adding support of threads/subjects in group chats.

>**Is your feature request related to a problem? Please describe.**
Sometimes when we speak with other people in 1:1 conversations or in MUCs, we speak about different topics/threads. Now its hard to detect witch message belongs to a specific conversations subject and/or its really difficult to relate our message to any of active thread.
Implementing this XEP will use power of `<subject>` and `<thread>` element in conversations especially in MUC. This feature will be something smiliar to SLACK threads https://get.slack.help/hc/en-us/articles/115000769927-Use-threads-to-organize-discussions-.

>Threads are often used in a company when group of people (developers, buissness guys) discuss about different topic in the same channel/room.

>**Describe the solution you'd like**
I think that people starting implementing this should see what SLACK, Mattermost or other IM use it in a GUI.
Message window should be able to show active threads in a room and allow user to reply to any of this active threads.

>Converese also should display all messages by grouping them by threads just like e-mail clients do.

**Comment by iNPUTmice** [comment]
I don’t think this is a good fit for Conversations right now. Also I'm pretty sure this is duplicate.
