### ISSUE TITLE
Show raw text

### ISSUE THREAD

**Issue by gabrielmoura** [siacs/Conversations#3497]
I consider it important to display raw text, to see without the text before it is deciphered or formatted.

Or you can see the XML of the chosen message. 

Translated by Google.

Eu considero importante ver o texto cru, ou seja antes de ser decifrado ou até mesmo formatado.
Ou a opção de ver o XML da mensagem escolhida.

**Comment by iNPUTmice** [comment]
I don’t consider that to be an important feature.
