### ISSUE TITLE
Messages are deleted when they have not been read yet 

### ISSUE THREAD

**Issue by willemkuijpers** [siacs/Conversations#3498]
General information

    Version: Last Version

Steps to reproduce

if I receive a message and my deletion time is 1 day, the messages will be deleted when they have not been read. So the received messages are also deleted when they have not been read after passed the delete time from 1 day.

Fix :?

Have messages deleted only when they have been read by the recipient

**Comment by iNPUTmice** [comment]
Yes this is how this feature is supposed to work. Can’t say I'm a huge fan of that 'feature' but that's how it is.

**Comment by willemkuijpers** [comment]
but imagine that you get an important message and you are traveling, you have received the message but you have not read it yet, then you really have to be on time to read the message, this is awkward ...

**Comment by iNPUTmice** [comment]
Yes I fully agree that this feature is useless.
