### ISSUE TITLE
[Feature] filter/block participant in MUC

### ISSUE THREAD

**Issue by azrdev** [siacs/Conversations#3501]
#### General information

(only partly relevant to the matter)

* **Version:** 2.5.4+fcr
* **Device:** OnePlus One
* **Android Version:**  Android 9 [LineageOS for microG](https://lineage.microg.org/)
* **Server name:** irc.hackint.org
* **Server software:** [Biboumi](https://biboumi.louiz.org/)
* **Installed server modules:** (ATM unknown)
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Join a MUC
2. Identify another participant whose messages you don't want to see
  - E.g. the bridge to the hackint IRC network sends IRC mode changes as messages
  - Note you don't need to know the JID of that participant, AFAIK, since MUCs are anonymous. (correct me if I'm wrong)

#### Expected result

3. be able to filter messages from that participant, so they don't appear in the MUC

#### Actual result

3. have not found a way to do so.

#### Debug output

not relevant to the problem, AIUI

**Comment by iNPUTmice** [comment]
You can add the full jid (room@server.tld/nick) in the block dialog. That is supported since 2.5.4 - but use at your own risk (some servers might not like you bouncing messages). That's also why there is no dedicated UI for that (plus unreliable on principle because people can just change nicks)
