### ISSUE TITLE
Allow Notification Options for direct chats

### ISSUE THREAD

**Issue by paskalito** [siacs/Conversations#3502]
There are this very nice notification options in MUC (Alway notify / Only when im "tagged"/ not at all)

I would like to be able to have this options in normal p2p chats as well.

This way i could manage a little bit from whom / which notifications i want to have on my lockscreen / vibrations / notifications about and with which i'd rather just see them when i actually have time to care / communicate about them.

**Comment by licaon-kter** [comment]
Someone is calling you on your alias in an 1:1?

**Comment by paskalito** [comment]
> Someone is calling you on your alias in an 1:1?

Not at the moment, but if this feature would be implemented, i would tell people to do so.

(it then also would be good to get a "call" on tapping on the icon in the 1:1 chat as well)

**Comment by iNPUTmice** [comment]
I don’t think this makes sense and/or is good ux for what you are trying to achieve.
