### ISSUE TITLE
Cannot send file with http upload with "connect via tor" proxy setting to onion server with self signed cert

### ISSUE THREAD

**Issue by onion-user** [siacs/Conversations#3511]
#### General information

* **Version:** 2.5.4+fcr
* **Device:** samsung galaxy s3
* **Android Version:**  lineage os 14.1
* **Server name:** self hosted, hidden service, self signed cert, no clearnet access
* **Server software:** Prosody 0.11.2 xubuntu 18.04
* **Installed server modules:** my config here: https://pastebin.com/raw/upmYKFgt
prosody logs here: https://pastebin.com/raw/RefbZcic
* **Conversations source:** F-Droid

I can send files when using vpn-mod in orbot (and also can do it with firejailed gajim)

but I get the following error when I try to send a file using the "connect via tor" setting in conversations:
Unable to resolve host "upload.kfhixmcrdf3h6tgxnczvlugdliwyl7tpfalnxhrmlaj2hzexygoi5jqd.onion": No address associated with hostname

#### Steps to reproduce

1. open orbot and connect to tor (dont use vpn mode)
2. open conversation and enable "connect via tor" in settings
3. connect to onion server with self signed cert and try to send or download file

````
adb logcat -s conversations
````
https://pastebin.com/raw/vGQJDvYn

**Comment by iNPUTmice** [comment]
I've just recently tested HTTP Upload to onion domains and it worked fine. I haven’t tested sub domains though. I didn’t know they were even a things. I'd suggest you simply don’t use them. Otherwise you might want to inquire with Orbot.

**Comment by onion-user** [comment]
Thanks for the quick response bro

I tried with subdomains (tor ignores them and omits) , and without them (using http upload external mod for prosody), with http and https, and with onion v2 and onion v3 - it does not work

conversations cannot resolve onion domain, there were no logs of incoming connections in nginx and prosody at all

i tested firefox and it can resolve the onion domain via socks and orbot

i also installed conversations on android 8.1 x86 (in virtualbox) and it works fine.
i get the problem only in my phone, i reinstalled conversations but it didnt help

it is not so important, i can use vpn mode in orbot. it was just very interesting why i get error
