### ISSUE TITLE
Unexpected behaviours after a screen orientation change (reported by activity)

### ISSUE THREAD

**Issue by dlicse1** [siacs/Conversations#3513]
I developed an automatic test case generation tool and it detected these problems in your app.
I would like to know if you consider them as failures and, if not, why. Thanks for your collaboration.

1) When I change the orientation of the device screen, a Dialog appears in UriHandlerActivity
![2019-08-02 18-06-31_before](https://user-images.githubusercontent.com/53469180/62412809-ba694c00-b607-11e9-9305-3d85d8c473f8.png)
![2019-08-02 18-06-31_after](https://user-images.githubusercontent.com/53469180/62412810-bb01e280-b607-11e9-8199-2330bdbfc89e.png)

2) When I change the orientation of the device screen, StartConversationActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
"Cut, Copy, Paste" options appear
![2019-08-02 18-21-56_before](https://user-images.githubusercontent.com/53469180/62412794-855cf980-b607-11e9-8e24-fcdc69255454.png)
![2019-08-02 18-21-56_after](https://user-images.githubusercontent.com/53469180/62412795-855cf980-b607-11e9-8c09-c309ecf2b7fb.png)

-- second case --
The TextView disappears
![2019-08-02 13-41-40_before](https://user-images.githubusercontent.com/53469180/62412796-855cf980-b607-11e9-92d9-166bfae727c4.png)
![2019-08-02 13-41-40_after](https://user-images.githubusercontent.com/53469180/62412797-85f59000-b607-11e9-8335-b2c78f58740e.png)

3) When I change the orientation of the device screen, the Dialog shrinks itself in SettingsActivity
![2019-08-02 16-27-28_before](https://user-images.githubusercontent.com/53469180/62412782-547cc480-b607-11e9-8117-98f5757a9562.png)
![2019-08-02 16-27-28_after](https://user-images.githubusercontent.com/53469180/62412783-547cc480-b607-11e9-8b56-fa479bcfe7f5.png)

4) When I change the orientation of the device screen, the Dialog disappears in ManageAccountActivity
![2019-08-02 13-40-04_before](https://user-images.githubusercontent.com/53469180/62412771-2ac39d80-b607-11e9-8fd9-9b18a0b9ee35.png)
![2019-08-02 13-40-04_after](https://user-images.githubusercontent.com/53469180/62412772-2ac39d80-b607-11e9-89f3-e29f5406266a.png)

5) When I change the orientation of the device screen, EditAccountActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
The Dialog disappears
![2019-08-02 14-52-08_before](https://user-images.githubusercontent.com/53469180/62412745-ef28d380-b606-11e9-8f87-b956143b49aa.png)
![2019-08-02 14-52-08_after](https://user-images.githubusercontent.com/53469180/62412746-efc16a00-b606-11e9-9d7c-85f534ff30e5.png)

-- second case --
It doesn't keep the scroll position
![2019-08-02 12-55-00_before](https://user-images.githubusercontent.com/53469180/62412747-efc16a00-b606-11e9-90d4-9b986ad0e46e.png)
![2019-08-02 12-55-00_after](https://user-images.githubusercontent.com/53469180/62412748-efc16a00-b606-11e9-85df-416d5eac27d5.png)

6) When I change the orientation of the device screen, the "Paste, Select All" options disappear  in ConversationActivity
![2019-08-02 15-38-03_before](https://user-images.githubusercontent.com/53469180/62412728-c9033380-b606-11e9-859b-f0607c4b3002.png)
![2019-08-02 15-38-03_after](https://user-images.githubusercontent.com/53469180/62412729-c9033380-b606-11e9-9872-1e9ecc0602c7.png)

7) When I change the orientation of the device screen, the Dialog disappears in ContactDetailsActivity
![2019-08-02 13-54-58_before](https://user-images.githubusercontent.com/53469180/62412704-9f4a0c80-b606-11e9-9a8b-e2b9fb145c8b.png)
![2019-08-02 13-54-58_after](https://user-images.githubusercontent.com/53469180/62412705-9f4a0c80-b606-11e9-9707-75b279883b76.png)

8) When I change the orientation of the device screen, the Dialog disappears in BlocklistActivity
![2019-08-02 13-02-36_before](https://user-images.githubusercontent.com/53469180/62412622-a1f83200-b605-11e9-9364-809817714d62.png)
![2019-08-02 13-02-36_after](https://user-images.githubusercontent.com/53469180/62412623-a1f83200-b605-11e9-872d-7db78f07c1f9.png)

**Comment by licaon-kter** [comment]
And the same with version 2.5.5?

**Comment by dlicse1** [comment]
The version was v1.23.12, isn't it the latest version? Anyway, could you tell me if you consider them or some of them as failures? Even if they are not present in the latest version anymore. Thank you

**Comment by iNPUTmice** [comment]
> Anyway, could you tell me if you consider them or some of them as failures?

I would probably consider them failures; however as you probably know dealing with screen rotation on Android is super annoying as you manually have to save state for almost everything. So a lot of those are too minor to be worth going through the immense effort to fix them.

You are testing a version of Conversations that is no longer supported (1.x) - The more problematic of these have been addressed in 2.x
