### ISSUE TITLE
SOCKS5 to IBB fallback as initiator: doesn't send `transport-replace` after failed SOCKS5

### ISSUE THREAD

**Issue by hrxi** [siacs/Conversations#3515]
After the SOCKS5 transport failed via mutual `<candidate-error>`s, Conversations does not send a `transport-replace` with IBB info.

#### General information

* **Version:** 2.5.5+fcr
* **Device:** Nexus 5X
* **Android Version:** Android 8.1 (LineageOS 15.1)
* **Server name:** from jabber.ccc.de to 5222.de
* **Server software:** not known
* **Installed server modules:** not known
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Offer a file using Conversations to your client.
2. Make sure that all SOCKS5 candidates fail. Send a `<candidate-error />` and wait for Conversations' `<candidate-error />`.

Client → Conversations
```
<iq id='5c12aa9e-28f9-44ad-97dd-f65fd20f6318' type='set' to='initiator@jabber.ccc.de/Conversations.aSP7'>
  <jingle xmlns='urn:xmpp:jingle:1' action='transport-info' sid='d95vef1kk7'>
    <content creator='initiator' name='9us90rm793'>
      <transport xmlns='urn:xmpp:jingle:transports:s5b:1' sid='kdgusrnaqv'>
        <candidate-error />
      </transport>
    </content>
  </jingle>
</iq>
```

Conversations → Client
```
<iq type='set' to='responder@5222.de/dino.ffd8e29b' from='initiator@jabber.ccc.de/Conversations.aSP7' id='tDCNeHRyFaux' lang='en'>
  <jingle xmlns='urn:xmpp:jingle:1' initiator='initiator@jabber.ccc.de/Conversations.aSP7' action='transport-info' sid='d95vef1kk7'>
    <content creator='initiator' senders='initiator' name='9us90rm793'>
      <transport xmlns='urn:xmpp:jingle:transports:s5b:1' sid='kdgusrnaqv'>
        <candidate-error />
      </transport>
    </content>
  </jingle>
</iq>
```

Client → Conversations
```
<iq id='tDCNeHRyFaux' to='initiator@jabber.ccc.de/Conversations.aSP7' type='result' />
```

Conversations → Client
```
<iq type='result' to='responder@5222.de/dino.ffd8e29b' from='responder@jabber.ccc.de/Conversations.aSP7' id='5c12aa9e-28f9-44ad-97dd-f65fd20f6318' lang='en' />
```

#### Expected result

Conversations sends a `transport-replace` with IBB info.

#### Actual result

Conversations does not send anything after acknowledging the `<candidate-error />`.

#### Debug output

Not provided.

**Comment by iNPUTmice** [comment]
Can you provide the logcat output for. I’m unable to reproduce this.

**Comment by hrxi** [comment]
Seems to be my mistake, I can't reproduce it anymore (my local version hasn't changed). Sorry. :/
