### ISSUE TITLE
Diffrents between Conversations and Zom

### ISSUE THREAD

**Issue by githubboy1** [siacs/Conversations#3518]
Hallo 
Can someone tell me whats the diffrents are between Conversations and Zom for security?
i think both are the same? using omemo and xmpp, or i missing something?

**Comment by iNPUTmice** [comment]
These sort of questions are better dealt with at our group chat.

**Comment by licaon-kter** [comment]
@githubboy1 Zom is no longer developed, right? They jumped to Matrix: https://gitlab.com/keanuapp
