### ISSUE TITLE
Can't restore backups with Quicksy

### ISSUE THREAD

**Issue by samantohermes** [siacs/Conversations#3522]
#### General information

* **Version:** 2.5.5
* **Device:** Motorola Moto G 2015
* **Android Version:**  Android 9 (LineageOS)
* **Server name:** quicksy.im
* **Server software:**  
* **Installed server modules:** Stream Managment, CSI, MAM
* **Quicksy source:** F-Droid

#### Steps to reproduce

Install Quicksy and open for the first time

#### Expected result

It should appear an option to restore a backup at the first startup, or on "manage account" screen. 

#### Actual result

Quicksy just doesn't have any option to restore a backup, unlike Conversations

**Comment by licaon-kter** [comment]
/close as invalid

It's by design to encourage switching to Conversations.

;)

**Comment by samantohermes** [comment]
I won't be able to convince all my friends to register on a server and to add contacts manually using Jabber IDs

**Comment by samantohermes** [comment]
:(
