### ISSUE TITLE
Bad quality of uploaded avatar

### ISSUE THREAD

**Issue by zimbelstern** [siacs/Conversations#3524]
#### General information

* **Version:** 2.5.5
* **Device:** Moto G5
* **Android Version:**  Android 9 – Omnirom
* **Server name:** self hosted
* **Server software:** prosody 0.11
* **Installed server modules:** pep, profile, and others
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Crop and set an image as avatar (original size 3120x4160 pixels)
2. View user avatar with Pix-Art Messenger or Gajim

#### Expected result

Reasonable quality

#### Actual result

Really bad image quality:
Many compression artifacts and a small size (192x192 pixels)

By the way, avatars uploaded with Pix-Art Messenger are fine (480x480 pixels)

**Comment by iNPUTmice** [comment]
There is a server side limit of ~9KB. Uploading larger avatars with Pix-Art will break in funny ways on some servers. Conversations attempts to provide a stable user experience no matter what server you use.

**Comment by zimbelstern** [comment]
Thank you for the explanation. However, I think it's time to revise the XMPP specifications then. 9 kB are not much.
