### ISSUE TITLE
how to stop the installation of openkeychain from google play?

### ISSUE THREAD

**Issue by HackM3nt3** [siacs/Conversations#3528]
Hi mates;

I have my own modified version of openkeychain, but sometimes when i reinstall a new version of converstions, the pgp keys are not recognized and the program tries to install the original openkeychain from google play, how can i stop this?

some help please

**Comment by licaon-kter** [comment]
Your version has a changed appID ?

**Comment by iNPUTmice** [comment]
You don’t have to hit the install button; just hit the restart button.
