### ISSUE TITLE
Ejabberd and Conversations - Chat History And Offline Messages Retrieval

### ISSUE THREAD

**Issue by ArunMuthu-NS** [siacs/Conversations#3530]
Hi all,

I'm trying to create a chat service. I'm using ejabberd as a xmpp server and tried to create a java console program using smack. I managed to send and receive messages. But when i tried to get chat history and offline messages i couldn't find enough tutorials or documents. So i tried to look into the code of open source xmpp clients like spark and conversations.

**Spark**
In spark they are maintaining it like logs in their application itself and they are not retrieving it from the ejabberd server. 

**Conversations**
In Conversations android app, i saw the sqlite db used to add and recover chat history.  

Do we have to keep track of the messages in our client or separate server that is being sent to and received  from ejabberd. Or is there any way to do this ? I tried to find but ended up with some Smack API like OfflineMessageManager, MAMArchive etc.,. But didn't get any concrete one.

Need help in this context ? Thanks in advance

And is there any better alternate for ejabberd like open fire or mongoose ?

**Comment by iNPUTmice** [comment]
The XSF publishes the so called Compliance Suite which acts as sort of an index or table of contents on what extensions you need to implement for a certain feature set. You can find the current one on [XEP-0412](https://xmpp.org/extensions/xep-0412.html).

Also the developer chat room of the XSF is probably a better place to ask those questions then a bug tracker of one particular app.
https://xmpp.org/community/chat.html

But my recommendation is read XEP 412 and then the relevant XEPs listed in there.
