### ISSUE TITLE
Channels: default notification parameter wrongly set to "when mentioned"

### ISSUE THREAD

**Issue by blacoste** [siacs/Conversations#3533]
#### General information

* **Version:** 2.5.6

#### Steps to reproduce

1. Join a channel
2. Wait for someone to write a message

#### Expected result

Default notification parameter should be set to "notified on every message".

#### Actual result

Default notification parameter is set to "only when mentioned".

Actually, my correspondents and I believed it was an issue on server or client side. This choice is really not conventional. 
If channel is too noisy, this is really natural to jump on this setting and set the parameter to "only when mentioned", not the opposite. We actually missed information messages.

Thanks.

**Comment by licaon-kter** [comment]
Only when mentioned on public.

Always on private.

**Comment by blacoste** [comment]
Yeah I confirm this is what is implemented.
I am just saying this is really not human friendly.

**Comment by licaon-kter** [comment]
@blacoste Do join the support room xmpp:conversations@conference.siacs.eu/?join and enable notifications for all messages, how long would you last?

It's friendly to have it on for your private family room of 10, but not for a public 200 members random room.

**Comment by blacoste** [comment]
I agree with you. But for a chan with 3 people this is the complete opposite as you say.

So what to choose by default ? I would always have chosen the option that make the user aware of it: so notif by default.

So you seemed to be aware of it. It's up to your choice.

**Comment by licaon-kter** [comment]
Yes, it's up to your choice, hence not a bug.

How about the app is NOT annoying by default?

**Comment by blacoste** [comment]
So you would agree that Facebook, Whatsapp (not FB choice before bought) made really bad marketing choice when enabling notification by default when creating a group discussion ? For sure those platform users would have report this as a bug.

**Comment by licaon-kter** [comment]
@blacoste yeah, where's the WA Github issues site?

**Comment by blacoste** [comment]
Ohhh... this is being sarcastic. I do not order or mandate a change. There are other ways to disagree.

I won't bother you with my issues/suggestions anymore as I stop using and funding.

**Comment by licaon-kter** [comment]
@blacoste I'm not the dev, not sure what you mean, I'm just an user with an opinion, and big MUCs with this default would be annoying.
