### ISSUE TITLE
[Feature Request]: add support for github or wordpress style avatar generation

### ISSUE THREAD

**Issue by stevenleeS0ht** [siacs/Conversations#3536]
Sometimes, the contact in same group with same init letters of name. We get identical avatar. It is impossible to distinguish.

If hash-based avatar is supported, it would be awesome.

**Comment by subpub** [comment]
[Openfire has a random avatar plugin](https://discourse.igniterealtime.org/t/new-openfire-plugin-random-avatars/) but they seem to be in .SVG

**Comment by iNPUTmice** [comment]
I’m currently fine with the implementation of XEP-0392
