### ISSUE TITLE
[Feature request] Automatically categorize received files by contact folder

### ISSUE THREAD

**Issue by Hund** [siacs/Conversations#3539]
I (and I guess a lot of other users) receive a lot of files, especially pictures. I keep most of them on my computer and I sort them in folder by the person who sent them to me.

I do this every few months and I then have hundreds of images. it's sometimes hard to remember who sent what and it would therefor be nice if there was an optional setting to automatically sort the files in per contact folders. So if my contact named "john@doe.tld" sends me a file, it gets stored in a new folder called "john@doe.tld" in the current folder, if the folder "john@doe.tld" doesn't already exist.

I hope it's something you would consider!

**Comment by licaon-kter** [comment]
Please us the search function.

/close as duplicate https://github.com/siacs/Conversations/issues/1540

**Comment by Hund** [comment]
I did use the search feature. Thanks!
