### ISSUE TITLE
Conversations.im IPv6 support

### ISSUE THREAD

**Issue by oksjd** [siacs/Conversations#3543]
This issue is concerned about the IPv6 support status of Conversations.im Jabber service, not the app itself.
Since in the latter half of #3542 I've messed up the issue description quite a bit, I will try to summarize it here.
## Background
The problem is discovered when I was trying to join conversations@conference.siacs.eu using my private account on my home server, which only supports IPv6 connection.
#### Mobile connection
China Mobile cellular network, which supports native IPv6 connection and carrier grade NAT IPv4 connection (address begin with 10.xx.xx.xx)
#### Server connection
100 Mbps/20 Mbps fiber (!) connection provided by China Mobile, supports native IPv6 connection and carrier grade NAT IPv4 connection (address begin with 10.xx.xx.xx). Using PPPoE
#### Server configuration
Home server is running Proxmox, running ejabberd in a LXC container. Home router is an EA6350v3 with OpenWrt snapshot.
#### DNS
The DNS service is provided by Cloudflare. I wrote a script to update the records periodically (DDNS) and update the firewall configuration in the router accordingly.
#### Important notes
**All internet connection to servers outside China is really slow and with unacceptable packet loss rate via IPv4. IPv6 connection isn't exhibiting this problem as of now.**
#### IPv6 in VR China
In December 2018 the all 3 major ISPs in China massively deployed native IPv6 under government request. The main purpose is to solve the lack of IPv4 address and prepare for IoT applications. All phones supporting VoLTE support IPv6. Even WiFi hot-spot function can delegate IPv6 address to the client.
#### Firewall
![pve](https://user-images.githubusercontent.com/54463160/65422044-efd82c00-de37-11e9-999d-3a59c2229619.JPG)
![ow](https://user-images.githubusercontent.com/54463160/65422047-f2d31c80-de37-11e9-8521-082accf3c7b9.JPG)

## Account registration
Client | Conversations.im | 404.city
------------ | ------------- | -------------
Conversations | Succeeded | Failed
Conversations with IPv6 | didn't test | succeeded
## Test results
All conducted with the same Android 9 phone

Client | Account | Send message to gyc@jr.alpenveilchen.xyz
------------ | ------------- | -------------
Pix-Art | gyc@jr.alpenveilchen.xyz | \ 
Conversations | w4tpo@conversations.im | failed, with DNS lookup error 
Conversations with IPv6 | w4tpo@404.city | succeeded, with OMEMO blind trust 
## Join public channels from gyc@jr.alpenveilchen.xyz

1. prosody@conference.prosody.im Succeeded
2. news@chat.404.city Succeeded
3. conversations@conference.siacs.eu Failed (remote server timed out)
## Port "filtered"
> nmap -6 -p 5269 jr.alpenveilchen.xyz -Pn
> Starting Nmap 7.70 ( https://nmap.org ) at 2019-09-22 15:43 CEST
> Nmap scan report for jr.alpenveilchen.xyz (2409:8a14:a012:4320::16d)
> Host is up.
> 
> PORT     STATE    SERVICE
> 5269/tcp filtered xmpp-server
> 
> Nmap done: 1 IP address (1 host up) scanned in 2.26 seconds
According to Nmap docs

> filtered
> Nmap cannot determine whether the port is open because packet filtering prevents its probes from reaching the port. The filtering could be from a dedicated firewall device, router rules, or host-based firewall software. These ports frustrate attackers because they provide so little information.

In my understanding this status is more or less an alias for "unknown".

**Comment by oksjd** [comment]
A test account on my server can be obtained at gyc@jr.alpenveilchen.xyz

**Comment by iNPUTmice** [comment]
We’ve fixed the DNS issue and are now getting 'Connection timeout' as expected. Because again we can’t reach your server from any of our servers. And we tried at least 5. Maybe someone or something is blocking the entire German IP range or something.

FWIW it doesn’t matter what client you use for this.

**Comment by oksjd** [comment]
> We’ve fixed the DNS issue and are now getting 'Connection timeout' as expected. Because again we can’t reach your server from any of our servers. And we tried at least 5. Maybe someone or something is blocking the entire German IP range or something.
> 
> FWIW it doesn’t matter what client you use for this.

The choice of client does matter as the IPv4 connection is bad here, and the original Conversations is hard coded to prefer IPv4 over IPv6, as demostrated by the failure of 404.city registration.
As showed in the traceroute result in the previous issue, my server is not able to reach your server as well
> 17 be2846.rcr22.fra06.atlas.cogentco.com (2001:550:0:1000::9a36:251e) 299.557 ms * *
> 18 * * *
> 30 * * *

The connection ended in France.

**Comment by iNPUTmice** [comment]
> The choice of client does matter as the IPv4 connection is bad here

It doesn’t matter when we are talking about S2S connections.

> As showed in the traceroute result in the previous issue, my server is not able to reach your server as well

Yes. That’s what I'm saying.

Further servers that I tested that are not able to connect to yours:
* trashserver.net
* xmpp.zone / jabber.at

I’m done here. There is nothing I can do about that.

**Comment by oksjd** [comment]
I found some online website test tools and sure enough, my blog https://blog.alpenveilchen.xyz , hosted on the same server, is not accessable from Frankfurt. But it is accessable from London or Singapore.
So something blocked the connection. But I still wonder the reason.

**Comment by oksjd** [comment]
This is definitely a recent problem. I still remember that when I tested with the very same tool (keycdn Web Performance Test) my webserver was accessable from Germany.
Maybe time will fix the problem.

**Comment by oksjd** [comment]
I connected to the conversations@conference.siacs.eu group chat finally.

**Comment by oksjd** [comment]
$ traceroute 2a00:1828:2000:215::44 1?: [LOCALHOST]                        0.151ms pmtu 1500
 1:  no reply
 2:  2409:8014:2803:304::4                                50.124ms
 3:  2409:8014:2803:38::4                                 43.925ms
 4:  2409:8014:2803:20e::5                                35.372ms
 5:  no reply
 6:  no reply
 7:  2409:8080:0:1:105:6b1::                             223.633ms asymm  8
 8:  2409:8080:0:1:105:201:0:1                            73.913ms asymm  9
 9:  2409:8080:0:1:201:2c1:0:1                            81.568ms asymm 10
10:  no reply
11:  no reply
12:  2402:4f00:2000:100::18d                             360.268ms
13:  2402:4f00:2000:100::f2                              479.771ms
14:  2001:978:2:21::bb:1                                 353.112ms
15:  be12500.ccr22.lon01.atlas.cogentco.com              320.256ms
16:  be2871.ccr42.lon13.atlas.cogentco.com               391.019ms
17:  no reply
18:  no reply
19:  be2845.rcr22.fra06.atlas.cogentco.com               388.476ms
20:  2001:978:2:42::63:2                                 317.800ms asymm 15

21:  inexio2.cr1.network.manitu.net                      349.797ms asymm 16
22:  xmpp.conversations.im                               482.833ms reached
     Resume: pmtu 1500 hops 22 back 17

**Comment by oksjd** [comment]
![Screenshot_2019-09-25-10-35-34-140_de pixart messenger](https://user-images.githubusercontent.com/54463160/65564716-5bc5ac00-df80-11e9-8d69-90202dfcb0b3.png)
![Screenshot_2019-09-25-10-35-30-351_de pixart messenger](https://user-images.githubusercontent.com/54463160/65564719-62ecba00-df80-11e9-8ba4-9ebce507e37e.png)

**Comment by oksjd** [comment]
Now you can test the server connections again if you want.

**Comment by oksjd** [comment]
Didn't last long. The connection is lost, again.
18:  be2813.ccr41.fra03.atlas.cogentco.com               572.750ms
19:  be2846.rcr22.fra06.atlas.cogentco.com               421.143ms
20:  no reply
21:  no reply
22:  no reply
23:  no reply
24:  no reply
25:  no reply
26:  no reply
27:  no reply
28:  no reply
29:  no reply
30:  no reply
     Too many hops: pmtu 1500
     Resume: pmtu 1500

**Comment by unriccio** [comment]
The hops via Cogent ring a bell...
https://www.theregister.co.uk/2018/08/28/ipv6_peering_squabbles/
https://en.wikipedia.org/wiki/Tier_1_network#Other_major_networks
