### ISSUE TITLE
Socks5 file transfer stalls/slow

### ISSUE THREAD

**Issue by Black-Nr1** [siacs/Conversations#3545]
#### General information

* **Version:** 2.5.8
* **Device:** Five different Android devices (Xiaomi Redmi 7, Samsung..)
* **Android Version:**  Android 9 (stock)
* **Server name:** x1.gleeze.com
* **Server software:** Latest prosody, S2S: latest ejabberd
* **Installed server modules:** Stream Managment, Socks5, proxy65
* **Conversations source:** PlayStore & F-Droid

#### Steps to reproduce

1. …Install Conversations 2.5.8
2. …Send a file/picture to another Conversations user

#### Expected result
Up to 2.5.6, the file transfer via SOCKS5 is lightning fast. File is transferred immediatly.

#### Actual result

What do you see instead?
File transfer is delayed showing "0%", and is either transferred after a delay, or not at all.
Downgrading Conversations on both sides solves the problem immediately. Upgrading reintroduces the problem. It is enough that just one side runs Conversations 2.5.8 to get the undesired behaviour.

#### Debug output
Sorry, I'm not capable of carrying out such a debug log.

**Comment by licaon-kter** [comment]
You tested in the same LAN?

**Comment by Black-Nr1** [comment]
Yes, with the same result. Three different users connected to the same local network and server. I don't think it has something to do with the network or server. Some of my connections are connected to ejabberd, some to both my own and external prosody servers. The problem appears when at least one uses Conversations 2.5.8 and vanishes when downgraded.

**Comment by iNPUTmice** [comment]
Without a debug output / log file there is nothing I can do on that matter.
