### ISSUE TITLE
Feature-Request: Message-Forwarding via XEP-0297

### ISSUE THREAD

**Issue by worlword** [siacs/Conversations#3550]
Hello,

in Conversations you are able to use citation or re-send a message in another chat. But the standardized way would be to forward a message via XEP-0297 (https://xmpp.org/extensions/xep-0297.html). This XEP defines a standard to forward stanzas to other chats. 
Right now Conversations only displays the additional message and not the forwarded message. So forwarded messages from other XMPP-Clients are not displayed correctly in Conversations. 
Since we are using converse.js as desktop-client and Conversations as mobile client, it is preferable if both clients understand XEP-0297. For converse.js we already implemented the XEP (https://github.com/conversejs/converse.js/pull/1732).

If you implement XEP-0297 you could replace your custom functionality with the standard. This way your Application is more open to communication with other XMPP-Clinets, not only converse.js.

**Comment by worlword** [comment]
> 
> 
> /duplicate #1565 ?

Yes and no. #1565 only wants to display these messages correct. A full implementation would also require to send such a message.

**Comment by iNPUTmice** [comment]
I’m not a fan of using forwarding as a means of quoting as this would require you to use a different mechanism for partial quotes.
