### ISSUE TITLE
Incoming messages not displayed until app is force-quit and restarted

### ISSUE THREAD

**Issue by benoliver999** [siacs/Conversations#3553]
#### General information

* **Version:** 2.5.11+fcr
* **Device:** Google Pixel 3a XL
* **Android Version:**  Android 10 (GrapheneOS)
* **Server name:** conversations.im - custom domain
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Message sent to me.

#### Expected result

I see the message in the app, and get notified.

#### Actual result

Nothing shows in the app.

---

On desktop (gajim) the messages show up as normal, which is how I know I am missing out on mobile.

This can be fixed by force-closing the app and restarting it (all messages flood in at once), so I don't think it's an encryption issue (otherwise 'missed' messages would not show).

I have battery optimisation disabled for the app.

**Comment by licaon-kter** [comment]
Did you enable Foreground Service in Expert settings?

**Comment by benoliver999** [comment]
Agh of course. I didn't go near them this time but I must have done that on my last device. Thanks!
