### ISSUE TITLE
Paperclip (Attachment) button is not loaded in Group chat

### ISSUE THREAD

**Issue by stevenleeS0ht** [siacs/Conversations#3560]
#### General information

* **Version:** 2.5.11
* **Device:** Honor 7
* **Android Version:**  Android 8 (stock)
* **Server name:** jab.im
* **Server software:**Not known
* **Installed server modules:**Not known
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

In personal chat, everything is fine. But when entering group chat (Not the owner of group), PaperClip button will be not loaded.

Is that a bug? or there is some setting on the group should be set?

#### Expected result

What is the expected output? 

Load paperclip button.

#### Actual result

What do you see instead?

No paperclip button in group chat. Only triple dot button.

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

Don't know where to start, because paperclip is not loaded, I cannot push this button.

**Comment by licaon-kter** [comment]
This is a server issue...in Accounts....this account...menu...server features...what features are available? Is 0363  ok?

**Comment by iNPUTmice** [comment]
Your server [does not support HTTP Upload](https://compliance.conversations.im/server/jab.im/) which is needed to share files in group chats.
