### ISSUE TITLE
Export/import history to new account possible?

### ISSUE THREAD

**Issue by mw80** [siacs/Conversations#3562]
#### General information
I switched to a new XMPP account. Is it possible to transfer existing conversations to the new account? As soon as I deleted the old account all converstations will be lost.

* **Version:** 2.5.3
* **Device:** Xiaomi Mi A1
* **Android Version:**  Android 9 (stock)
* **Server name:** conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
No this is not possible.
