### ISSUE TITLE
In mobile client side original message getting duplicate when editing that message from web conversation client side 

### ISSUE THREAD

**Issue by raviteja74** [siacs/Conversations#3567]
#### General information

* **Version:** 2.5.3
* **Device:** Xiaomi Mi A1
* **Android Version:**  Android 9 (stock)
* **Server name:** conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by licaon-kter** [comment]
What web client? Maybe that web client didn't properly edit the correct ID or that message? Did you report that to that client devs?

**Comment by iNPUTmice** [comment]
Unable to even fill out an issue template…

**Comment by raviteja74** [comment]
thank you @licaon-kter

**Comment by Sarun515s** [comment]
> #### ข้อมูลทั่วไป
> * **รุ่น:** 2.5.3
> * **อุปกรณ์:** Xiaomi Mi A1
> * **รุ่น Android:**   Android 9 (หุ้น)
> * **ชื่อเซิร์ฟเวอร์:** Conversations.im, jabber.at หรือโฮสต์ด้วยตนเอง
> * **ซอฟต์แวร์เซิร์ฟเวอร์:** ejabberd 16.04 หรือฉันทลักษณ์ 0.10 (ถ้าทราบ)
> * **โมดูลเซิร์ฟเวอร์ที่ติดตั้ง: การ**จัดการสตรีม, CSI, MAM
> * **แหล่งที่มาของการสนทนา:** PlayStore, PlayStore Beta Channel, F-Droid, สร้างตัวเอง (HEAD ล่าสุด)
> 
> #### ขั้นตอนในการทำซ้ำ
> 1. ...
> 2. ...
> 
> #### ผลลัพธ์ที่คาดหวัง
> ผลลัพธ์ที่คาดหวังคืออะไร
> 
> #### ผลลัพธ์ที่แท้จริง
> คุณเห็นอะไรแทน
> 
> #### ดีบักเอาต์พุต
> กรุณาโพสต์ผลลัพธ์ของ adb logcat บันทึกควรเริ่มต้นด้วยการเริ่มต้นของการสนทนาและรวมถึง
> ขั้นตอนทั้งหมดที่ใช้ในการทำให้เกิดปัญหาอีกครั้ง
> 
> ```
> adb logcat -s conversations
> ```

**Comment by licaon-kter** [comment]
@Sarun515s Try in English
