### ISSUE TITLE
[Feature request] Prevent the merging of messages after they are sent in sequence

### ISSUE THREAD

**Issue by nancxjo** [siacs/Conversations#3568]
Conversations has the feature to merge messages when they are sent quickly one after the other.
I would like to disable this feature, as it is making me dizzy.
If you could either implement a button to disable this that would be greatly appreciated.
Also, if you could point me to where in the source code I would have to go to change it so that merging does not happen that would also be appreciated.

**Comment by iNPUTmice** [comment]
I’m currently not interested in a setting for that. Unmerged messages will consume too much vertical space with the current design. A future design in 2020 or 2021 will get rid of merging entirely.
