### ISSUE TITLE
The edited message in web coming as a new message in mobile instead of showing the selected edited message itself.

### ISSUE THREAD

**Issue by Vjaych** [siacs/Conversations#3569]
#### General information

* **Version:** 2.5.3
* **Device:** Xiaomi Mi A1
* **Android Version:**  Android 9 (stock)
* **Server name:** conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? 

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
Same person? Please fill out the issue template. A fairly recent version of Conversations fixed an inter op issue with converse.js
