### ISSUE TITLE
Ability to search for messages

### ISSUE THREAD

**Issue by cubedeeev** [siacs/Conversations#3572]
A common feature for messengers which I consider to be fundamental is the ability to search for messages, highlight them and have a next/previous button. I'd appreciate this feature

**Comment by licaon-kter** [comment]
/close as duplicate of https://github.com/siacs/Conversations/issues/3101 and/or https://github.com/siacs/Conversations/issues/3243

FYI you can search now too, but only globally, when you see all the open chats go to menu, search.
