### ISSUE TITLE
Remember (keyboard) language for each conversation

### ISSUE THREAD

**Issue by ericschdt** [siacs/Conversations#3576]
Conversing with different people in different languages it would be very convenient if Conversations could remember the the language for each conversation.

**Comment by iNPUTmice** [comment]
I don't even know if that's possible. But if it is feel free to create a PR
for that. I personally don't have a keyboard where I can or need to switch
the language.

**Comment by ericschdt** [comment]
> I don't even know if that's possible. 

Me neither, but maybe I or someone else will find it out later.

> But if it is feel free to create a PR for that. 
When it's possible and I find the time for it, sure.

> I personally don't have a keyboard where I can or need to switch the language.
I mainly require it for word suggestions and corrections.

**Comment by iNPUTmice** [comment]
I’m closing here since there is no actionable item on my part. Feel free to create a PR.
