### ISSUE TITLE
Port not removable

### ISSUE THREAD

**Issue by jugendhacker** [siacs/Conversations#3578]
#### General information

* **Version:** 2.5.12+fcr
* **Device:** Samsung J5 (j5nlte)
* **Android Version:**  Android 9 (LineageOS)
* **Server name:** self hosted
* **Server software:** ejabberd 19.09.1
* **Conversations source:** F-Droid

#### Steps to reproduce

1. set a port in the account settings
2. save it
3. remove the port
4. try to save it

#### Expected result

Conversations should take it and select the port automatically again.

#### Actual result

It shows an error about invalid port number.

#### Debug output

There is no output in logcat....

**Comment by jugendhacker** [comment]
Also another user told me that he has the same issue, but I don't know his setup....

**Comment by iNPUTmice** [comment]
What does automatically mean in this context? If you want Conversations to use SRV record you can empty the hostname. Just emptying the port doesn’t make a lot of sense?

**Comment by jugendhacker** [comment]
Yeah I mean by SRV records.... but even if I remove I can't remove the port and that is at least bad UX in my eyes because intuitive is to remove both...

**Comment by jugendhacker** [comment]
And also the port number is just greyed out if you remove the hostname.... this doesn't really look like conversations does not use it anymore.... it looks more like it's now unchangeable
