### ISSUE TITLE
dont show pictures send from monal as link

### ISSUE THREAD

**Issue by nanderer** [siacs/Conversations#3583]
#### General information
The iphone app monal dose not send pictures over omemo correct jet so it is displayed as a link not as a picture, but could you still display them correctly even if it is send as plain https and not ascmwhatrverhttps
* **Version:** 2.5.11+fcr (fdroid)
* **Device:** bb keyone
* **Android Version:**  stock android 
* **Server name:** jabber.at
* **Server software:** see for yourself
* **Installed server modules:**
* **Conversations source:** F-Droid,

#### Steps to reproduce

1. get one person with android conversations one with monal on ios an omemo conversations (lock symbol activated)
2. see the result if one sends image to anotherone

#### Expected result

What is the expected output? 

The image

#### Actual result

What do you see instead?

A link to the image

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by licaon-kter** [comment]
Both users on jabber.at ?

**Comment by nanderer** [comment]
Me on jabber.at he on jabber-germany.de ; but its  very unlikely that this is a server thing because you can reproduce the same behavior when you select copy original link in an unencrypted chat and paste it into an omemo one

Am 14. November 2019 12:32:18 MEZ schrieb Licaon_Kter <notifications@github.com>:
>Both users on jabber.at ?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/siacs/Conversations/issues/3583#issuecomment-553848060

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by iNPUTmice** [comment]
Have a look here: https://github.com/siacs/Conversations/issues/2641#issuecomment-332457050
