### ISSUE TITLE
Proper Open Street Map attribution

### ISSUE THREAD

**Issue by Etua** [siacs/Conversations#3588]
Currently the only place I could find the Open Street Map attribution was the "About" section which is not really visible nor tight to the actual work. In my opinion Conversations should follow the common rule of including the attribution text in the bottom corner of the map (compare to the attached image).
![Screenshot_20191123-063456_StreetComplete](https://user-images.githubusercontent.com/13040148/69474094-aca92380-0dbc-11ea-81c4-439e55f99ed2.png)
Such requirement stems directly from the license 

> You must include a notice associated with
the Produced Work reasonably calculated to make any Person that uses,
views, accesses, interacts with, or is otherwise exposed to the Produced
Work aware that Content was obtained from the Database, Derivative
Database, or the Database as part of a Collective Database, and that it
is available under this License.

Moreover I suggest referring to the OSM contributors in the appropriate places as it's their work that the database is made upon and most of the copyright notices I have seen recognise that and don't solely use the name of the project which is alike us having "Daniel Gultsch" in the "About" rather than "Conversations, copyright 2014-2019 Conversations".

**Comment by iNPUTmice** [comment]
Yes, I agree. Pull requests welcome.
