### ISSUE TITLE
App shows no notification on Chinese phones

### ISSUE THREAD

**Issue by vendiloy** [siacs/Conversations#3590]
conversations and quicksy dont show any notifications on Chinese phones such as xiaomi, oppo, huawei, realme, asus, ZTE etc. On my phone Oppo, i have tried everything from autostart allowed, and all battery optimizations disabled. Simply not working. The only way to make it work is by simply not closing the app via Task Manager, as on chinese phones it will completely kill the whole application including background service. Any workaround for Chinese phones ?

**Comment by licaon-kter** [comment]
Works fine on Huawei and Xiaomi here.

Did you do all the dance steps: https://dontkillmyapp.com ?

**Comment by vendiloy** [comment]
hi, thanks for the prompt reply. As explained on the https://dontkillmyapp.com ?
-------
Oppo F1S
Background services are being killed (including accessibility services, which then need re-enabling) every time you turn the screen off. So far, a workaround for this is:

pin your app to the recent apps screen
enable your app in the app list inside the security app’s “startup manager” and “floating app list” (com.coloros.safecenter / com.coloros.safecenter.permission.Permission)
turn off battery optimizations
give the service a persistent notification to remain in the foreground
All four of those need to be done before the app would function. Here are links to some other resources verifying that some of the above steps work on other Oppo devices:
-----------

"pin your app to the recent apps screen" means lock the application on the recent apps screen which unfortunately won't work if power saving mode is on, sure, it 'd work if i turn it off. That's exactly what i meant with "The only way to make it work is by simply not closing the app via Task Manager...", i think many of us runs our phone on power saving mode, so i can't lock / pin the app, so i just let it run there, and make sure i dont accidentally press the "Close All" button.

Any other workaround to let the app run on power saving mode on Oppo A71  'd be highly appreciated. Thanks.

**Comment by vendiloy** [comment]
The app from Google Play store or F-Droid?
> from google play
In taskmanager can you "lock" it, to protect it?
>can't if it's on power saving mode
Is the permanent notification killed too?
>everything

**Comment by iNPUTmice** [comment]
I’m not aware of work arounds other than those described on dontkillmyapp.com

**Comment by iNPUTmice** [comment]
And enabling the foreground service obviously.
