### ISSUE TITLE
Duplicate messages with Carbons enabled/option to disable Carbons

### ISSUE THREAD

**Issue by matslarson** [siacs/Conversations#3595]
I have a server I connect to that uses a bot to automatically generate messages to users on certain events. Due to poor user education on the behavior of XMPP regarding resource priority and multiple devices, a decision was made (well above my head) to configure the bot to send the messages explicitly to all connected resources for a user to prevent "lost" or "undelivered" messages (from the users' point of view) rather than follow the standard XMPP behavior. This worked fine while Carbons were not widely supported by many clients, but now each client receives the message directly to its resource, as well as a carbon-copied duplicate from all other resources.

I understand this is due to a non-standard server configuration, but I came across many other closed requests for such a feature, mostly related to issues with OTR. It seems like a relatively simple power user feature to add an option to disable Carbons (obviously the default should still be enabled on a mobile client like Conversations) and would go a long way to resolving issues users face when dealing with outdated clients (lookin' at you Pidgin, although even Pidgin has an optional Carbons plugin at this point) or strange server behavior beyond their control. 

I've been using Xabber as a workaround, as it still offers an option to disable Carbons, but I much prefer Conversations and would like to return to using it without getting 3-4 copies of each message.

#### General information

* **Version:** 2.6.1
* **Device:** Pixel 4XL
* **Android Version:**  Android 10 (stock)
* **Server name:** self/organization hosted
* **Server software:** Openfire unknown version
* **Installed server modules:** MUC, Stream Managment, Carbons
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Connect to server, wait for messages sent to each JID/resource to arrive from the bot

#### Expected result

A single copy of the message is delivered to each device

#### Actual result

Each client receives as many duplicates of the message as the JID has resources logged in with Carbons enabled

**Comment by iNPUTmice** [comment]
Add `<private xmlns='urn:xmpp:carbons:2'/><no-copy xmlns='urn:xmpp:hints'/>` to the bot’s outgoing messages.

**Comment by matslarson** [comment]
> Add `<private xmlns='urn:xmpp:carbons:2'/><no-copy xmlns='urn:xmpp:hints'/>` to the bot’s outgoing messages.

I thought I was pretty clear I can't make changes to the server itself and was looking for a client-side workaround. 

Oh well, thanks for the tip, guess I'll just stick with Xabber.
