### ISSUE TITLE
Received images disappear !?

### ISSUE THREAD

**Issue by Maastodonte** [siacs/Conversations#3597]
Hi,

#### General information

* **Version:** 2.6.0
* **Device:** Crosscall Action-X3
* **Android Version:**  Android 7.1.2 (stock)
* **Server name:** self hosted
* **Server software:** prosody 0.10.0
* **Installed server modules:** Various
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Receive some images from a contact
2. Come back some time later (one or two days) to the chat
3. Images are not available anymore and conversation shows the message "Failed file transfer" (translated from french "Echec de l'envoi du fichier")

If I go to my gallery disapperead images are replaced by white squares in the middle of other images still visible in Conversations.
This strange behavior begins few weeks ago, one image from time to time was impacted. But now it is several images at the same time and it's becoming really annoying.

On my wife's phone with the same version of Conversations, images she sent to me are still there in the chat, with success trasfer on them.

I could bare if the images were still avalaible in the Conversation folder but they are literally blanked out!
We use Conversations since years with no problem at all and are really loving it... despite this sudden bug.

Anyone has this problem ?
I didn't change anything on my phone or my server, all was working well and then all of a sudden... this strange and annoying behavior!

#### Expected result

Images should not be deleted from the Conversations folder without notification or user action after successfully being received!

#### Actual result

Images disappear at some unknown will !?

#### Debug output

I can't produce any since I am not able to identify when or why this appened and can't let my phone connected to a computer all day to get debug output.

Thanks for your help, advice, etc...

**Comment by licaon-kter** [comment]
Is Conversations moved to the SD card?

**Comment by iNPUTmice** [comment]
> Installed server modules: Various

please elaborate on that one.

**Comment by Maastodonte** [comment]
No.
I just checked and it is on internal storage.

As I said it just happenned all of a sudden and got worse the past few weeks. 

If it can be of any help : we exchange with my wife a lot of pictures lately of our now 4 months baby :)
She takes more pictures than me so the problem is most visible on my receiving phone but she lost a few images I sent to her too. Behavior is the same.

**Comment by Maastodonte** [comment]
> 
> 
> > Installed server modules: Various
> 
> please elaborate on that one.

A copy of my prosody conf file regarding modules enabled :

`modules_enabled = {
    -- Generally required
		"roster"; -- Allow users to have a roster. Recommended ;)
		"saslauth"; -- Authentication for clients and servers. Recommended if you want to log in.
		"tls"; -- Add support for secure TLS on c2s/s2s connections
		"dialback"; -- s2s dialback support
		"disco"; -- Service discovery

	-- Not essential, but recommended
		"carbons"; -- Keep multiple clients in sync
		"pep"; -- Enables users to publish their mood, activity, playing music and more
		"private"; -- Private XML storage (for room bookmarks, etc.)
		"blocklist"; -- Allow users to block communications with other users
		"vcard"; -- Allow users to set vCards

	-- Nice to have
		"version"; -- Replies to server version requests
		"uptime"; -- Report how long server has been running
		"time"; -- Let others know the time here on this server
		"ping"; -- Replies to XMPP pings with pongs
		"register"; -- Allow users to register on this server using a client and change passwords
		"mam"; -- Store messages in an archive and allow users to access it

	-- Admin interfaces
		"admin_adhoc"; -- Allows administration via an XMPP client thatsupports ad-hoc commands

	-- HTTP modules
		"bosh"; -- Enable BOSH clients, aka "Jabber over HTTP"
		"websocket"; -- XMPP over WebSockets

	-- Other specific functionality
		"posix"; -- POSIX functionality, sends server to background, enables syslog, etc.
		"groups"; -- Shared roster support
		"server_contact_info"; -- Publish contact information for this service
		"announce"; -- Send announcement to all online users
		"offline";
}`

I checkes my logs and my error.log is empty on log level "error".
I don't see anything on the logs at the time of my last disappeared images (the 11th at 20h14) and after.
I can activate debug log server side if it can help.

**Comment by g33xt4h** [comment]
I can verify this behaviour, my wife and me have the same error.

General information

    Version: 2.6.1+pcr
    Device: Huawei Mate 20 Lite
    Android Version: Android 9 (stock)
    Server name: self hosted
    Server software: prosody 0.10.0
    Conversations source: Google Playstore (Bought it)

I'm upgrading to prosody 0.11 at the moment but i doubt it is a bug of prosody (couldn't find any information regarding it "https://issues.prosody.im/")

**Comment by iNPUTmice** [comment]
@g33xt4h are you sure you are seeing this 2.6.1 as well? Please post your modules.

**Comment by g33xt4h** [comment]
Hi,
sorry i've just noticed there was an update to 2.6.1+pcr - the Bug was in 2.6.0.
I'm gonna wait a few days and post feedback here.

My modules with prosody 0.11 are (except from standard):
smacks, mam, carbons, csi csi_battery_saver, bosh

**Comment by Maastodonte** [comment]
No disapperance either on my part since upgrading to 2.6.1 a few days ago.

Looking at the changelogs I noticed this :
2.5.6 => fixes for Jingle file transfer
2.5.8 => Support XEP-0396: Jingle Encrypted Transports - OMEMO
2.5.12 => Jingle file transfer fixes
2.6.1 => fixes for Jingle IBB file transfer

Maybe a bug was introduced for our use case somewhere in the near past and corrected with 2.6.1.

I am not closing this issue right now. I prefer to wait a bit but I think we are good now !
Thanks guys :)

**Comment by iNPUTmice** [comment]
I’m fairly confident the issue has been resolved.

**Comment by Maastodonte** [comment]
Absolutely right :)
You did it!
