### ISSUE TITLE
Orbot and Conversations — Automatic Connection to TOR Network

### ISSUE THREAD

**Issue by solus-hq** [siacs/Conversations#3599]
#### Steps to reproduce

1. Connect XMPP account through TOR socks with Orbot active and running 
2. Switch WIFI to mobile network OR vice versa OR restart phone which stops Orbot
3. Permanently loose connection to XMPP account  

#### Expected result

Check for TOR network availability and restart/make Orbot reconnect to reinstate XMPP connection

#### Actual result

Conversations simply states: Tor network is not available

**Comment by licaon-kter** [comment]
In C 2.6.1? Did you enable "autostart" in Orbot settings?

**Comment by solus-hq** [comment]
@licaon-kter Here's an update including screenshots

![photo_2019-12-16 17 30 48](https://user-images.githubusercontent.com/26515805/70914917-fa1a5880-2029-11ea-9953-1c6e5899fa9f.jpeg)
![photo_2019-12-16 17 30 44](https://user-images.githubusercontent.com/26515805/70914919-fab2ef00-2029-11ea-980f-8c93f6603cb0.jpeg)
![photo_2019-12-16 17 30 41](https://user-images.githubusercontent.com/26515805/70914921-fab2ef00-2029-11ea-9b7d-5ccf902f2af1.jpeg)
![photo_2019-12-16 17 30 38](https://user-images.githubusercontent.com/26515805/70914922-fb4b8580-2029-11ea-8cd3-23850a00b9b6.jpeg)
![photo_2019-12-16 17 30 33](https://user-images.githubusercontent.com/26515805/70914923-fb4b8580-2029-11ea-8367-d54f5f0c3a4d.jpeg)

**Comment by iNPUTmice** [comment]
If Orbot doesn’t reconnect after a network switch (or a phone reboot) that seems to be an issue with Orbot (or your phone); please report this to Orbot.
It works fine on my phone.

**Comment by licaon-kter** [comment]
@solus-hq whitelist Orbot in all the energy saving sections that you can find. 

You didn't mention what device, so do read https://dontkillmyapp.com too

**Comment by solus-hq** [comment]
@licaon-kter Orbot was "optimized" by Samsung's battery optimization... Hope turning everything off will improve app behaviour. 

Thanks!
