### ISSUE TITLE
Display already receivd and full file size of the partially downloaded file

### ISSUE THREAD

**Issue by ericschdt** [siacs/Conversations#3602]
When a download was interrupted, it can be resumed. 

Currently there's only a button which says "download". It would be convenient if it said "resume download" and additionally display the already downloaded size vs the full size.

**Comment by iNPUTmice** [comment]
We wouldn’t be able to predict if the server has that capability.

**Comment by ericschdt** [comment]
That means you don't know if you can resume a partially downloaded file until you try it? Where and for how long is the already downloaded part stored if the file won't be downloaded completely?

**Comment by ericschdt** [comment]
> We wouldn’t be able to predict if the server has that capability.

In the future the HTTP Upload XEP could probably be expanded by an optional advertisement of a `resume-capability`, which then could be used by the clients to enhance the UX.
