### ISSUE TITLE
While downloading a received file from HttpUpload it's possible to press "download" again

### ISSUE THREAD

**Issue by ericschdt** [siacs/Conversations#3604]
#### General information

* **Version:** 2.6.1
* **Device:**  S4
* **Android Version:** Android 7.1 (LO)
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Download a large file
2. While downloading, long press on the downloading file

#### Expected result

The context menu offers to "cancel" or "pause" the download.

#### Actual result

The context menu has an option to "download" the file again.

**Comment by iNPUTmice** [comment]
I’m unable to reproduce this.
