### ISSUE TITLE
Message styling: Parse from out to in

### ISSUE THREAD

**Issue by ericschdt** [siacs/Conversations#3605]
#### General information

* **Version:** 2.6.1

#### Steps to reproduce

```_*_this is italic and *and bold and ~crossed out~* plus `mono space`_*_```

#### Expected result

The outer asterisk * are used to make the complete sentence bold.

#### Actual result

The first and the third out of four asterisks are used.

![Screenshot_20200102-230900](https://user-images.githubusercontent.com/43318127/71696398-c884e980-2dac-11ea-8dc6-d70ef662e268.png)

**Comment by ericschdt** [comment]
The situation seems to more complicated:

`*strong*plain*` renders as follows:
![strong_plain1](https://user-images.githubusercontent.com/43318127/71697101-d8053200-2dae-11ea-8837-d56c7093e64e.png)
which seems fine,

while

`*strong**plain* renders as
![strong_plain2](https://user-images.githubusercontent.com/43318127/71697128-ece1c580-2dae-11ea-90f0-0984b66e5f97.png)

where I'd expect either all to be bold between the outer asterisks or the `plain` to be bold too.

**Comment by SamWhited** [comment]
This follows [the spec](https://xmpp.org/extensions/xep-0393.html) which says:

> the opening styling directive MUST be located at the beginning of the line, or after a whitespace character.

However, this prevents any span from having multiple styling directives applied (despite examples of multiple styling directives later in the document) so this is actually a bug in the spec.

**Comment by iNPUTmice** [comment]
> However, this prevents any span from having multiple styling directives applied (despite examples of multiple

It only prevents wrapping multiple of the same styling in each other. That’s why the example form op doesn’t work.

However:
```
*_italic_ ~strike~ `mono`*
```
renders as you would expect.

I’m not entirely sure what op was even trying to achive by making the entire text bold and then again bold in the middle.

Imho both the parser and the spec are fine. It's a trade off between easy to use and also avoiding false positives. Therefor it's ok not to cover "ops usecase" - even though i don’t really know what the usecase is. If you disagree please raise it on the standards mailing list.

**Comment by SamWhited** [comment]
Ah yes, I misunderstood what the op was saying was wrong. The spec was wrong, but that isn't actually a problem here. The second marker wasn't used because it had a space before it, and therefore wasn't a closing styling directive (which is correct). The third marker is used because it *is* a closing styling directive and the spec says that directives are greedily matched.
