### ISSUE TITLE
[Feature Request] Let theme depend on system setting

### ISSUE THREAD

**Issue by weiss** [siacs/Conversations#3611]
On Android 10, it would be nice if the light/dark theme was auto-selected depending on the system-wide setting (by default), as [suggested by Google][1] these days.  This way, OS mechanisms such as auto-switching to dark mode when the battery is low would also take effect on Conversations.

[1]: https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#changing_themes_in-app

**Comment by iNPUTmice** [comment]
I’m adding a `pr-welcome` label. If anyone wants to do this I suggest that the theme select dialog in the settings should have a third option called 'Automatic' if - and only if - running on Android 10.
