### ISSUE TITLE
push enabled at our server side successfully by using playstore version of conversations app but not getting service awaking push notification(our server is::prosody)?

### ISSUE THREAD

**Issue by VEEPURI** [siacs/Conversations#3614]
#### General information

* **Version:** 2.4.0
* **Device:** Samsung M10
* **Android Version:**  Android 9 
* **Server name:** conversations.im
* **Server software:**  prosody 0.11.3 (if known)
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** PlayStore

#### Steps to reproduce

1. By using play store version of conversations app i enabled push notifications in our prosody server successfully but not getting background service awaking notification for messages please let me know I did any mistake here is my serverside log
Thanks in advance

#### Expected result

What is the expected output? 
service awaking push notification expected

#### Actual result

What do you see instead?
push notifications enabled successfully at the server side but not getting in mobile

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
Jan 10 13:07:25 c2sebed4b0      info    Authenticated as ravitejak@xxxxxxx-im.net
Jan 10 13:07:29 s2soutf382320   info    Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
Jan 10 13:07:29 xxxxxxx-im.net:saslauth        info    SASL EXTERNAL with p2.siacs.eu failed: not-authorized: unable to verify the first certificate
Jan 10 13:07:30 s2sincef35b0    info    Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
Jan 10 13:07:30 xxxxxxx-im.net:saslauth        info    Accepting SASL EXTERNAL identity from p2.siacs.eu
Jan 10 13:07:30 s2sincef35b0    info    Incoming s2s connection p2.siacs.eu->xxxxxxx-im.net complete
Jan 10 13:07:30 s2soutf382320   info    Outgoing s2s connection xxxxxxx-im.net->p2.siacs.eu complete
Jan 10 13:07:30 s2sin61f8b60    info    Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
Jan 10 13:07:30 xxxxxxx-im.net:saslauth        info    Accepting SASL EXTERNAL identity from p2.siacs.eu
Jan 10 13:07:30 s2sin61f8b60    info    Incoming s2s connection p2.siacs.eu->xxxxxxx-im.net complete
Jan 10 13:07:30 c2sebed4b0      info    Push notifications enabled for ravitejak@xxxxxxx-im.net/xxxxxxxBusiness.Mg9h (p2.siacs.eu<ALkbj3B4hNlJ)
Jan 10 13:07:37 c2sebed4b0      info    Client disconnected: closed
````

**Comment by iNPUTmice** [comment]
> not getting background service awaking notification for messages

How do you tell?

**Comment by VEEPURI** [comment]
sir i didn't trigger any service awaking notification in push message receiver class when my app was in kill state to getting new message notifications

**Comment by iNPUTmice** [comment]
"your app?" - You can just recompile the app and reuse the `p2.siacs.eu` server. That wont work. You need to setup your own app server.

**Comment by VEEPURI** [comment]
Could you please tell me  the procedure for how to create my own Appserver in my app source code... Please help me sir

**Comment by licaon-kter** [comment]
@VEEPURI this is not the place for your own app support

**Comment by iNPUTmice** [comment]
@VEEPURI if you are building your own app for fun or as a side project I suggest you build the `free` flavor as the README recommends you do. If you are using this commercially I’m available for hire. Find more information on my [website](https://gultsch.de).
