### ISSUE TITLE
discover which servers have web-interface MUC/channel

### ISSUE THREAD

**Issue by ToEatFreshBabies** [siacs/Conversations#3615]
Perhaps on new JID account creation indicate which server has this capability?

example gleaned from https://search.jabber.network/

https://chat.jabberfr.org/

**Comment by iNPUTmice** [comment]
To do what and why?

**Comment by ToEatFreshBabies** [comment]
To facilitate conversation with recalcitrant family or those people on ios with lackluster xmpp app options
