### ISSUE TITLE
Quicksy, Phone Number Verification Dialog: Back and Next buttons at same place

### ISSUE THREAD

**Issue by jhdohrmann** [siacs/Conversations#3625]
#### General information

* **Version:** 2.6.3+fcr
* **Device:** Samsung Galaxy S III Mini (GT-I8190)
* **Android Version:**  Android 4.1.2 (stock)
* **Server name:** quicksy.im
* **Server software:** ? (if known)
* **Installed server modules:** ?
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Start Quicksy
2. Enter valid mobile number
3. Next
--> The "We have sent you an SMS to ..."-Screen appears

#### Expected result

Screen with usable control elements -- in this case: Usable "Next" and "Back" buttons, in particular.

#### Actual result

Screen whose "Next" and "Back" buttons are at exactly the same position, so that it's actually impossible to go on from that screen. That renders the application completely unusable, effectively. 

#### Debug output

Forgive me, if I did not create that yet. Should it actually be necessary to reproduce the error, please give me a note; I'll of course hand it in, then.

**Comment by jhdohrmann** [comment]
IMHO, the issue still exists in Quicksy 2.6.4+fcr (at Samsung Galaxy S III Mini (GT-I8190) with Android 4.1.2). Would you reopen this issue, or should I open a new one and refer to the one at hand?

**Comment by iNPUTmice** [comment]
This is not supposed to be fixed in 2.6.4 - master has the fix.
