### ISSUE TITLE
[future] when calling then OSTN

### ISSUE THREAD

**Issue by eveofdestruction** [siacs/Conversations#3627]
For your consideration in future use of jingle et all please consider also OSTN

https://dev.guardianproject.info/projects/ostn/wiki/

> OSTN is a de-facto standard by which a voice over internet protocol service can be considered end-to-end secured, with verifiable encryption, minimal logging, and a decentralized model of deployment and use. From this standard, we will work to deploy a network of compliant server/service instances and client software, mobile and desktop, that are federated, audited and interoperable.

**Comment by licaon-kter** [comment]
So not XMPP? We'd have to host another server too?

**Comment by iNPUTmice** [comment]
Thank you for your suggestion. It will be taken into consideration.
