### ISSUE TITLE
It should change the name

### ISSUE THREAD

**Issue by rmotao** [siacs/Conversations#3628]
#### General information

* **Version:** 2.6.2
* **Device:** Mororola One Macro
* **Android Version:**  ANDROID
* **Server name:** xmpp.re
* **Server software:** PROSODY
* **Conversations source:** F-Droid

Problem:

Every smartphone, with Android, that I install Conversations I see that the OS split the name. Conversations don't show your entire name, every time Android split the name... like Conversa..ions or Conversa-tions. The name is too long for Android.

Suggestion:

Change the name... Conversation to new a short one.

**Comment by licaon-kter** [comment]
Get a larger screen device?

Change your screen density? 

Change your UI/font size in Android settings?

**Comment by iNPUTmice** [comment]
I agree that the name is too long. But it is too late to change it. My next project has learned from that mistake and is simply called: [Ltt.rs](https://ltt.rs).

**Comment by rmotao** [comment]
@licaon-kter  and @iNPUTmice  I am having problems to estimulate regular people to use this App. They don't want to change nothing else for a single Application and I still suggest change the name for a short one.

**Comment by rmotao** [comment]
@iNPUTmice Whare can I get the source code of Conversation Legacy?

**Comment by licaon-kter** [comment]
@rmotao https://github.com/siacs/Conversations/tree/legacy

>  I am having problems to estimulate regular people to use this App.

Really the length of the name is the issue? Why? Try Quicksy then...
