### ISSUE TITLE
[Feature Request] Provide different emoji fonts 

### ISSUE THREAD

**Issue by spacekookie** [siacs/Conversations#3629]
The Android emoji are rather polarising whether or not people like them or not. Some apps (such as tusky) end up shipping several emoji fonts to choose from. Specifically I think the twitter emoji are quite popular and easy enough to include: https://github.com/twitter/twemoji

Is this something you would be interested in adding?

**Comment by iNPUTmice** [comment]
I’m afraid that would be more complicated than it sounds and I don’t want the maintenance burden associated with that.

If I’m wrong and it's really just two lines of code or something feel free to provide make a PR and I’ll reconsider.

**Comment by spacekookie** [comment]
There's other free software apps that bundle the twitter emoji set, such as tusky: https://github.com/tuskyapp/Tusky/blob/b79e86cacd7b21f1a14d601e7f5a9a51d239202d/app/src/main/java/com/keylesspalace/tusky/util/EmojiCompatFont.java#L69

Does that help?
