### ISSUE TITLE
[Feature Request] Notification on user log-on

### ISSUE THREAD

**Issue by drcross** [siacs/Conversations#3630]
Hi, Applications doesn't seem to allow you to have a notification when a user logs in. Could you please add it? Great App by the way.

**Comment by iNPUTmice** [comment]
No. That would be really annoying.

**Comment by drcross** [comment]
I wasn't saying that it should be enable by default and obviously there should be a toggle to disable the feature but it's a quite important feature for communication of a very sensitive nature. For example Snowden used xmpp to discuss matters with journalists. It's important for them to know when he was online. It's plain to see that this feature, which is enabled on most desktop clients (gajim and pidgin) is needed.

**Comment by licaon-kter** [comment]
@drcross Snowden did it with OTR, no multi device, no messages if contact is offline.

If he would do it now (he'd use Signal lol) with OMEMO he would not need to wait for Poitras or Greenwald to come online, he writes in HK timezone and the others see it when they wake up in NY or Rio.

**Comment by drcross** [comment]
I simply suggested a feature that all major xmpp clients have. I have a need for it and I guess a lot of others do too, otherwise all the other major clients wouldn't have added it. I'm not asking for a complete rewrite of the codebase in machine code, I'm simply asking to add a checkbox based notification option that fires when a specific user logs in.

**Comment by licaon-kter** [comment]
Which major **mobile** xmpp client has this?

**Comment by drcross** [comment]
Conversations is the only major mobile xmpp client so there is no comparison and you're not really making a strong point against adding the feature with your last comment.
