### ISSUE TITLE
【BUG】can not receive the add friend/invite request

### ISSUE THREAD

**Issue by iminto** [siacs/Conversations#3634]
#### General information

* **Version:** 2.6.0
* **Device:** Smartisan 3 坚果3
* **Android Version:**  Android7
* **Server name:** creep.im
* **Server software:** ejabberd 19.09.1 or prosody 0.11.3 (if known)
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1.Login with a XMPP account A(XXX@dismail.de or any other account)  by Gajim or any other XMPP client，then send message to B(xxx@creep.im) 
2. because creep.im has this rule **"In order to be able to communicate, you have to add the contact to your contact list first."** ，so Gajim will send an invite request to add B(xxx@creep.im)
3.open Conversations App,Login with B(xxx@creep.im) 

#### Expected result

receive the invite request from A,and add A to contacts.

#### Actual result

has nothing received.

But if use other Android  app client or desktop client (For example,Gajim or eyeCU),B will receive a request message from A .

**Comment by iNPUTmice** [comment]
I’m sorry but I can’t reproduce that. A subscription request will open a new empty conversation and display a snack bar in it.
