### ISSUE TITLE
Privacy: Conversations leaks all accounts and group chats via logcat

### ISSUE THREAD

**Issue by gsantner** [siacs/Conversations#3637]
#### General information

* **Version:** 2.6.4+pcr
* **Device:** Poco F1
* **Android Version:**  Android 9 (stock)
* **Server name:** any
* **Server software:** any
* **Installed server modules:** ka
* **Conversations source:** F-Droid

#### Steps to reproduce
1. Have developer stuff enabled
2. Connect on device or via usb/network to adb
3. See that Conversations logs relevant information via logcat continued. Including full id and associated name

#### Expected result
That Conversations does not expose my accounts and all chats associated with that account via logcat by default.  Add an option to enable it if really needed

#### Actual result
![grafik](https://user-images.githubusercontent.com/6735650/74100938-17e8d300-4b2c-11ea-8faf-87c677eb3a1b.png)

account name
![grafik](https://user-images.githubusercontent.com/6735650/74100976-9776a200-4b2c-11ea-9503-1a9601cabeef.png)

A associated channel name ![grafik](https://user-images.githubusercontent.com/6735650/74100979-a198a080-4b2c-11ea-9ad4-385e56106981.png)

A channel ID
![grafik](https://user-images.githubusercontent.com/6735650/74100982-af4e2600-4b2c-11ea-8d59-359e746c8087.png)

#### Debug output
See above.

**Comment by gsantner** [comment]
sidenote: I also have lots of other apps installed that require login, among that Riot, DavX5 for example. I had logcat now running for a while and no other app than Conversations logcat's account info "gregor" or "gsantner".

**Comment by licaon-kter** [comment]
/close as duplicate of https://github.com/siacs/Conversations/issues/1588 ?

I'm thinking of adding some if-then for "error reporting" and if it's disabled it should not log anything or at least not anything related to accounts.

**Comment by gsantner** [comment]
Oh yeah seems like same, thanks.

Sadly seems nobody cares about it, this is open since ~4 years ..

 @iNPUTmice any input on any of both issues?

**Comment by iNPUTmice** [comment]
@gsantner I've added a `pr-welcome` label to the original issue.
