### ISSUE TITLE
"Error installing Conversations. The privileged permissions have not been granted to the extension! Please create a bug report!"

### ISSUE THREAD

**Issue by kenrestivo** [siacs/Conversations#3641]
#### General information

* **Version:** 2.6.4+FCR
* **Device:** NextBit Robin
* **Android Version:**  9 lineageos 16.0 20200217 nightly ether
* **Server name:** n/a
* **Server software:** ejabberd 19.09.1 or prosody 0.11.3 (if known)
* **Installed server modules:** n/a
* **Conversations source:** F-Droid,

#### Steps to reproduce

1. Try to install from F-droid
2. Get the attached obnoxious and perplexing error message.
3. Create a bug report like the message says.
4. Repeat recursively.

#### Expected result

What is the expected output? 
App installs

#### Actual result

What do you see instead?

This error message

#### Debug output
none, it didn't install

![0c9b8dc9d392d9409d5cd8c7e2abfb5af554e294386e36d98dd7058fd160537c](https://user-images.githubusercontent.com/108085/74705583-3c4a4c80-51c9-11ea-92d0-e65191603a95.png)

**Comment by licaon-kter** [comment]
This is a F-Droid setup error, close this.

(Uninstall the priviledged extension and retry)
