### ISSUE TITLE
vCard does not work

### ISSUE THREAD

**Issue by OmlineEditor** [siacs/Conversations#3642]
#### General information

* **Version:** 2.6.4+fcr (362) f-droid
* **Device:** Xiaomi Redmi Note 7 and Xiaomi Redmi Note 8 Pro
* **Android Version:**  Android 9 (stock) MIUI 11
* **Server name:** self hosted
* **Server software:** prosody 0.11.3 
 * **Installed server modules:** "profile"; -- new vervion "vcard" XEP-0398: User Avatar to vCard-Based Avatars Conversion.

When communicating there are no avatars of contacts in the main menu.
I opened the program and see only names and standard avatars in the form of multi-colored backgrounds and a single letter.
Other programs see and support the avatars of the contacts in the vCard. you don't have that.
Please fix the problem.

**Comment by iNPUTmice** [comment]
I’m not aware of any problems in that regard.

**Comment by OmlineEditor** [comment]
> I’m not aware of any problems in that regard.
if you have no problems, this is not a reason to close the ticket. maybe you don't have problems others do. tell me how to solve the problem?

**Comment by meaz** [comment]
I think you should set mod_vcard_legacy and mod_vcard4 instead of mod_profile.

**Comment by wepanx** [comment]
I encounter the same problem, but only after having re-installed conversations and restored its internal backup. All avatars are gone except for those from one restored account with only few contacts. Newly created avatars (after restoring) are shown fine, however.
The server did not run mod_bookmarks before, just now after the problematic restoring. Might this be the cause?
