### ISSUE TITLE
Group encryption OMEMO

### ISSUE THREAD

**Issue by noobday77** [siacs/Conversations#3644]
So if got an issue here, I’m using omemo on private xmpp server
All working well groupchats with omemo encryption as well

Except when I make a group with users that don’t know eachother so don’t have eachother encryption key. 

Ive made the groupchat anonymous 
But the encryption doesnt work

What can we do about it?

**Comment by licaon-kter** [comment]
What server?

For OMEMO they need to be able to grab the keys from each other, so they need to see the real address.

Even if they don't have each others as contacts, the server will do the stuff needed, but the chat needs to be non-anon.

**Comment by iNPUTmice** [comment]
OMEMO in anonymous group chats is not supported and not something we plan to support.
