### ISSUE TITLE
Ask users when they want to receive notifications about new MUCs

### ISSUE THREAD

**Issue by blind-coder** [siacs/Conversations#3656]
#### General information

* **Version:** 2.7.0
* **Device:** any
* **Android Version:**  any
* **Server name:** self hosted
* **Server software:** prosody 0.11.3
* **Installed server modules:** any
* **Conversations source:** any

#### Steps to reproduce

Get invited to MUC.

#### Expected result

Get asked when you want to be notified about messages in this group.

#### Actual result

No prompt. Messages are not getting notifications until person gets tagged.
We use conversations in a non-tech-savvy environment (ie: family chat) where people regularly open/close MUCs with select other people. People then often complain that they don't get any messages (when in fact they only don't get notifications).

Kind regards,
Benjamin

**Comment by licaon-kter** [comment]
In Private groups you get notified by default.

In Public channels only on mentions.

Which ones are you talking about and why don't you use Private ones?

**Comment by blind-coder** [comment]
@licaon-kter 
Thank you for your quick answer!
How do you check if group chats are public or private? I need to ask my users which kind of channel they use.

**Comment by licaon-kter** [comment]
How where they created?

**Comment by blind-coder** [comment]
Using conversations in our prosody Server.

**Comment by licaon-kter** [comment]
Ok. So instruct them to create only Private then.

/close as duplicate https://github.com/siacs/Conversations/issues/3533

**Comment by iNPUTmice** [comment]
Conversations makes a distinction between private group chats and public channel. They behave in different ways. For example you can not use encryption in public channels.
I think for family and friends chats private group chats are more suited and will have 'proper' notification settings.
