### ISSUE TITLE
USE MY OWN PROVIDER, return cannot find server error

### ISSUE THREAD

**Issue by plutonem-mobile** [siacs/Conversations#3660]
Hi, guys.

I am just setting up my personal XMPP server through ejabberd. and i can create new user in ejabberd admin dashboard, for example: user1@ip-172-26-14-16.us-east-2.compute.internal ("ip-172-26-14-16.us-east-2.compute.internal" is my aws instance hostname)

but when i use conversation to create new account with my own provider option, everytime i enter a new user for example user3@ip-172-26-14-16.us-east-2.compute.internal, i just got cannot find server error.

is it that i left some critical configuration to be set on my aws instance server?

ps: i could use xxx@conversation.im to set up a new account when means that my network connection may be good.

**Comment by plutonem-mobile** [comment]
this is my error page

![762120A7193D732B25B68A92AAB88F21](https://user-images.githubusercontent.com/8728579/76949132-11c3ee80-6943-11ea-9dd0-1b1e6dd36f63.jpg)

**Comment by licaon-kter** [comment]
You need an actual demain accesible from outside.


/close as not an issue

**Comment by plutonem-mobile** [comment]
i will try it later.

thanks.
