### ISSUE TITLE
XEP-0384: OMEMO Encryption 0.4.0

### ISSUE THREAD

**Issue by Neustradamus** [siacs/Conversations#3663]
Can you update the XEP-0384: OMEMO Encryption support to 0.4.0?

- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.3.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html

**Comment by iNPUTmice** [comment]
Please stop spamming my issue tracker.
