### ISSUE TITLE
Encryption keys transferred in system backup

### ISSUE THREAD

**Issue by benoliver999** [siacs/Conversations#3666]
There was some chat about this in the group, but I am filing an issue to formalise it.

When Android system backup is used, Conversations includes OMEMO keys.

This means that when restoring from a backup to a new device, the same keys are used as on the old device.

For many users, this also means that their encryption keys have gone to Google Drive. I do not think this is intended behaviour, since most other apps do not behave this way. I tested with Whatsapp and a few others: passwords and keys are not included in the backup.

Android [has the ability to exclude keys](https://developer.android.com/guide/topics/data/autobackup) from the system backup.

**Comment by benoliver999** [comment]
Is this a non-issue? Did I just misunderstand what is happening?

**Comment by licaon-kter** [comment]
Look at the commit, now the app autoexcludes itself from Google backup.
