### ISSUE TITLE
Android 10 issue: send failed, long latency receiving

### ISSUE THREAD

**Issue by stevenleeS0ht** [siacs/Conversations#3668]
#### General information

* **Version:** 2.7.1+fcr
* **Device:** Huawei Mate 20
* **Android Version:**  Android 10
* **Server name:** chat.sum7.eu
* **Server software:** Not known
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** F-Droid

frequently send failed, and cannot receiving in background. Take long time to receiving new message after open this app.

**Comment by licaon-kter** [comment]
Foreground service enabled?

Battery optimizations disabled?

**Comment by iNPUTmice** [comment]
The issue tracker is not a good place to debug individual problems. I invite you to join our community group chat though.
