### ISSUE TITLE
Open settings menu on current android? to add new account not obvious

### ISSUE THREAD

**Issue by TrickTrackNO** [siacs/Conversations#3670]
It took a long while to convince a friend to use xmpp via this app. After his trial of JID expired he was too cheap to pay an extension.  He could not figure out how to get into settings to operate the add account / account manager.  Not having a current version of android I could not advise him.  He has not been able to resume communication via xmpp & this app.

Perhaps this should be more obvious?

**Comment by licaon-kter** [comment]
If no menu icon pres menu button? If Android 4.x

**Comment by iNPUTmice** [comment]
I think the overflow menu is a pretty common design feature on Android; If you have trouble finding that you will have trouble with a lot of apps.
