### ISSUE TITLE
omemo key ratchet to 'force' messages be unusuable by any party

### ISSUE THREAD

**Issue by TrickTrackNO** [siacs/Conversations#3671]
I can set my client to autodelete messages.  Perhaps others are not.  Could the ratchet be used to this effect making aged thread messages unavailable to any party?

**Comment by licaon-kter** [comment]
The encrypted messages are decrypted only once, so when yesou set in Conversations settings to "delete messages older than X" those messages that reappear via MAM.... were not encrypted.
