### ISSUE TITLE
Outbound s2s connection to p2.siacs.eu after user signs in via Conversations

### ISSUE THREAD

**Issue by jan0sch** [siacs/Conversations#3676]
#### General information

* **Version:** 2.7.1
* **Server name:** self hosted
* **Server software:** ejabberd 20.03
* **Installed server modules:** Everything default except disabled s2s

Hi, I'm not sure if this is the right place to ask, but here we go:

I run an instance of ejabberd for a closed group of family and friends and disabled the s2s_in and s2s_dialback module. However if a user signs in via Conversations I see s2s connection messages in the log:

```
[info] <0.705.0>@ejabberd_c2s:bind:434 (tls|<0.705.0>) Opened c2s session for ID@SERVER/Conversations.bLL4
[info] <0.704.0>@ejabberd_c2s:process_auth_result:271 (tls|<0.704.0>) Accepted c2s SCRAM-SHA-1 authentication for ID@SERVER ...
[info] <0.706.0>@ejabberd_s2s_out:init:273 Outbound s2s connection started: SERVER -> p2.siacs.eu
[info] <0.706.0>@ejabberd_s2s_out:handle_auth_success:209 (tls|<0.706.0>) Accepted outbound s2s EXTERNAL authentication SERVER -> p2.siacs.eu (78.47.177.120)
```
It made me wonder why there is an outbound connection after all? The user account was created on the server and nothing except the usage of Conversations is linked to `p2.siacs.eu`.

If a user signs in with another client then no s2s connection is triggered:

```
[info] <0.725.0>@ejabberd_c2s:process_auth_result:271 (tls|<0.725.0>) Accepted c2s SCRAM-SHA-1 authentication for ID@SERVER ...
[info] <0.725.0>@ejabberd_c2s:bind:434 (tls|<0.725.0>) Opened c2s session for ID@SERVER/profanity.jKZx
```

Any ideas what might be going on here?

Kind regards,

Jens

P.S.: Thank you very much for writing this application, it rocks! :heart:

**Comment by iNPUTmice** [comment]
Push. See the FAQ on push notifications.
