### ISSUE TITLE
Thank you for making the audio/video calls feature

### ISSUE THREAD

**Issue by immanuelfodor** [siacs/Conversations#3679]
Hi Everyone, I just wanted to thank you for making the audio/video calls feature happen! Works fantastic with Prosody + Coturn with the turncredentials community module (https://prosody.im/doc/coturn). Jitsi is also great for conferencing but so great for on-demand 1-on-1 calls, however, this is easy to use, works like other messengers, and wife-compatible! :grinning: Thank you, again, it was worth waiting for it.

**Comment by iNPUTmice** [comment]
Thank you. I’m glad people like it.
