### ISSUE TITLE
Use of self contact photo when server does not support publication of avatars

### ISSUE THREAD

**Issue by wassname** [siacs/Conversations#457]
Prior to 0.6 a self-contact photo was used as a self-avatar all accounts, but with 0.6 this was replaced with avatar publication. However some servers (facebook, gtalk, etc) do not support so it would be great to bring back self contact photos as fall-back option.

It seems like a minor thing but avatars in a conversation can add a lot of context  and this feature distinguished Conversations from other apps like Xabber. Maybe I am being whimsical but it's a large part of the reason I started using conversations after trying all other OSS xmmp apps. Keep up the great work, in making a pretty and streamlined tool!

**Comment by licaon-kter** [comment]
Any news on this? I don't want to change my avatar, but Xabber downloads my avatar from Gtalk, any problem for Conversations to do this too?

**Comment by licaon-kter** [comment]
Yes the materialized letter is nice, but I'd like a way to be allowed to change it locally with a picture of choice, and I can do it, I can choose it (I can't publish it anywere but I don't care), but it gets deleted on back arrow. :(

**Comment by iNPUTmice** [comment]
I don't see a point in supporting those kind of servers.
