### ISSUE TITLE
Support non-pubsub headline messages

### ISSUE THREAD

**Issue by singpolyma** [siacs/Conversations#492]
For now I've just changed the message handling to treat headline messages the same as chat or normal, but I'm not sure if that's quite right, I just want them to not get ignored :)

**Comment by BrianBlade** [comment]
+1
In compliance with http://tools.ietf.org/html/rfc6121#page-70 a popup notification would be appropriate. But anything is better than simply ignoring headline messages.

**Comment by iNPUTmice** [comment]
should be fixed in 1.5.0-alpha
