### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by jkufner** [siacs/Conversations#512]
To display current status of Conversations and/or unread messages or some other stuff.

It is a nice alternative to permanent notifications or other terrifying beasts.

Small version (1x1) should be a simple replacement of home screen icon. Large version may show list of active conversations.

**Comment by SamWhited** [comment]
@jkufner I started playing around with a simple 1x1 widget which shows the number of unread conversations (the number of notifications, even if they're merged into one summary notification) in [this branch](https://github.com/SamWhited/Conversations/tree/widget). Right now the intent that fetches the number isn't being sent properly.

I probably won't continue with this, I was just trying to figure out how widgets worked, but if someone else wants to use this as a base for something feel free

**Comment by hermann-san** [comment]
1x1 shortcuts on the homescreen to specific conversations contacts would be nice.
eventually with a unread counter on the symbol

**Comment by iNPUTmice** [comment]
We show unread badges on supported platforms. The widget concept seems dead to me.
