### ISSUE TITLE
Mark conversations as read in notification

### ISSUE THREAD

**Issue by maufl** [siacs/Conversations#515]
I often receive messages in Conversation as well as in Pidgin or the Facebook web chat and then answer them in Pidgin for example.
It would be nice if I could just mark all unread messages as read in the notification. Especially when there are multiple unread messages from multiple conversations I have to open Conversation and go into each conversation the mark them as read.

**Comment by iNPUTmice** [comment]
bbce690d4fad7047e529ed384e656da6d7ee1dd9 adds a 'Mark as Read' button to the notification.

**Comment by maufl** [comment]
Awesome, I totally forgot about this issue :D I'll buy you a beer if you want.
