### ISSUE TITLE
Feature: nearly people

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#596]
There are a few apps which use Bluetooth to connect each others to talk (like FireChat) but we have an alternative in XMPP since a while: a [link-local XMPP messaging](http://xmpp.org/protocols/linklocal/). If this app it's famous because of that, why not Conversations?

I think that it would be a nice feature for all of us and it could be one of the [XEP](http://www.xmpp.org/extensions/xep-0174.html) which difference Conversations from the rest.

**Comment by ao2** [comment]
Hi, I too am interested in link-local XMPP on Android, but I see that this issue has been closed.
What is the reason for closing the issue?

Thanks,
   Antonio

**Comment by iNPUTmice** [comment]
> I too am interested in link-local XMPP on Android

pull requests welcome
