### ISSUE TITLE
idea: distinctly show if encryption was lost/ended

### ISSUE THREAD

**Issue by tbeitter** [siacs/Conversations#607]
A few times now I just did not realize that a contact ended the pgp/otr encryption, as I just did not see that the little lock icon was gone. It would be really nice if there could be a dinstinct notification if an active and encrypted chat was ended. Maybe by a popup similar to the "verify fingerprint" messages that could be acknowledged.

Best,
Til

**Comment by dicer** [comment]
I second this. Constantly happens to me that I accidentally send unencrypted messages. I would go as far as to propose a new setting to force end-to-end encryption on certain avatars. I know there is a global option for this, but some of my contacts don't support encryption. It would be great to enable it for the ones where I am sure they support it.

**Comment by iNPUTmice** [comment]
77920c7aa608bd92391ade653eb8971b977eb7d5 paints message bubbles in red if you receive an unexpected plain text message

**Comment by alexara** [comment]
@iNPUTmice Conversations offers several kind of encryptions. When within an conversation the encryption changes (eg from OTR to OMEMO) all OTR encrypted messages become red.

Is that intended? From your definition above they should be green. Maby it's possible to write a small text (OTR/OMEMO/PGP) right to the lock symbol or to introduce symbols for the type of encryptions.

But as it is now I find it very confusing.

**Comment by SamWhited** [comment]
Somewhat related to this issue: The current red message bubble solution works great for me, but I can imagine that if you're red/green color blind it wouldn't be much use. No idea what to do about that though.

**Comment by iNPUTmice** [comment]
@SamWhited I think that depends on your type of red-green blindness.
android can simulate both. and if I remember correctly the bubbles are
distinguishable for one of them. everybody else can probably enable the
always use white background for incoming messages mode.
