### ISSUE TITLE
simplify resource option

### ISSUE THREAD

**Issue by Sohalt** [siacs/Conversations#682]
The current way to set the resource is undesirable in my opinion. The drop down menu unnecessarily limits advanced users and may confuse users not familiar with xmpp's concept of a resource. Therefore I would suggest to eliminate the dropdown entirely, using a sane default (like "conversations") and adding a text input in the experts options to allow arbitrary resource names.

**Comment by tehabe** [comment]
I had the same idea when I tried to set my resource, especially because I want one, which is not based on what my device is.

**Comment by Sohalt** [comment]
@iNPUTmice Any views/opinions/updates on this?

**Comment by hillbicks** [comment]
Although this issue is quite old, since it is still open, I'm replying here and voicing my interest in a custom resource field for conversations.

**Comment by d9h02f** [comment]
With a properly set up server, i.e. one which supports the XEPs listed in the README, the whole idea behind (custom) resources doesn't even need to exist in the first place, so I'm not sure whether it's worth spending any attention on this rather than slowly phasing it out.

**Comment by Sohalt** [comment]
I agree that the concept of a resource is not the most user friendly  and intuitive (which is why I think it belongs to the expert options), but with the current state of the xmpp ecosystem and the way certain things are implemented it sadly is still necessary (for example for file transfer you need to select where a file should be sent).

**Comment by SamWhited** [comment]
> or example for file transfer you need to select where a file should be sent

If user-readable resources were phased out (yes please) we can just use client identity for this (which is generally a much better solution than using the resource anyways).

**Comment by jkufner** [comment]
Current implementation does not work well when user has two phones of same type. If current list of available resource names is extended with [user defined device name](http://inside-galaxy.blogspot.cz/2014/08/samsung-galaxy-s4-how-to-change.html) we can close this issue for ever.

**Comment by towo** [comment]
Plus one on this; Nexus 6P is not unique for me, but the device's name is.

**Comment by iNPUTmice** [comment]
Resources are gone now
