### ISSUE TITLE
Expose certain functionality (disable accounts) via Intents

### ISSUE THREAD

**Issue by bgschaid** [siacs/Conversations#700]
It would be nice if there was intent (didn't see it in the manifest) with which accounts could be enabled/disabled.

Let me explain: I use Tasker to under certain conditions switch off non-essential communications. Tasker can send intents with parameters to applications. So if Conversations had an intent a Tasker-task could disable certain accounts and later enable them again

If implemented I'd suggest a preference entry that "guards" this functionality (the user has to opt-in to allow the control through the intent)

Of course the concept could be extended to other functionality (sending of messages). But I'm not sure about the security implications of that

**Comment by SamWhited** [comment]
If something like this were to be implemnted, I think the proper way would be to create a custom permission that other apps would have to request (eg. a "control conversations" permission or a more fine grained "modify account status" permission).

This provides more security (theoretically anyways; I doubt most users actually read the permissions their apps are requesting), and means we wouldn't have to clutter up the preferences every time we wanted to add a new intent (eg. if we wanted a "send messages" intent later)

**Comment by flocke** [comment]
If you use specifically Tasker one other solution could be to implement a Tasker-Plugin (see http://tasker.dinglisch.net/plugins.html) for Conversations.

**Comment by bgschaid** [comment]
Right. But from what I understand the Tasker-Plugin can not do anything if there is no legal way to access functionality (which as I understand it is an "intent" in Android)

**Comment by iNPUTmice** [comment]
This is not on our todo list
