### ISSUE TITLE
Closing Conversations is always returning to desktop

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#704]
If I'm surfing in the Internet with chrome or having another app open and a Conversations notification arrived, I'm pulling down the notification bar and tipping the notification. Conversations is starting. After reading the message I'm tipping the back button multiple times until Conversations is closed. So I should come back to chrome or the other open app, but I'll come to the desktop.

**Comment by allo-** [comment]
Its about how the Intent for the activity is created.

Have a look, if this can help you:

https://github.com/allo-/SharedUrlList/commit/5b20e43f27527e2562c2be71310cf1226c835f64
