### ISSUE TITLE
Styles in Contact Details

### ISSUE THREAD

**Issue by ghost** [siacs/Conversations#719]
Hello,

With the new tags in contact details, when the name of the group you have chosen for one contact is too long, status tag should be in a new line.

Another thing is when the jid of a contact is too long, it is shown in two line and is little ugly.

Shouldn't be translated status tag too?

Atached images.

Thank you.
![screenshot_2014-11-27-19-01-48](https://cloud.githubusercontent.com/assets/5982769/5220713/9ed5b9ac-7669-11e4-9066-4972ef4640a6.png)
![screenshot_2014-11-27-19-05-58](https://cloud.githubusercontent.com/assets/5982769/5220712/9ed32606-7669-11e4-9d7f-fc8b86533763.png)

**Comment by iNPUTmice** [comment]
This has been fixed a couple of versions ago.
