### ISSUE TITLE
Conference with: name and selection of users

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#722]
**Name**
I think it's more intuitive to use "Invite friends" than "Conference with...". People don't relate the word "conference" with "chat group" usually. 

**Selection of users:** 
IMO the users selection must be done checking the occupants from a list with all our contacts, not one by one.

**Comment by iNPUTmice** [comment]
21ebb35e44ee2e6a6cffaffee737d537ab1b8d6b

**Comment by iNPUTmice** [comment]
It should be noted that for this to work properly your server needs to implement some niche features from the XEP.
For prosody there are two feature requests:
https://prosody.im/issues/issue/682
https://prosody.im/issues/issue/445

Our very own [conversations.im](https://account.conversations.im) of course already has support for that.
