### ISSUE TITLE
Choose file. Adding "Record audio", "Choose audio" and "Choose video"

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#723]
**Introduction and Record audio**
Right now, we can send audio files by pressing the attachments icon → Choose file → Audio recorder→use de app and the file is sent. I propose to add an option to send audio files, that way, if we only have one app for audio recording, this is the app which is going to be opened automatically (as pictures app does (the gallery)):
attachments icon → Record audio →use de app and the file is sent.

**Choose audio/video**
The same as "Choose picture" does but selecting audio files and videos opening the music player and video player respectively.

**Comment by github-k8n** [comment]
@SamWhited , in general I would agree with having a separate app for recording.
However my concern is that the current process is prohibitively complicated.
Currently even IF the soundrecorder would show up in the Choose File menu it still does not allow for a useful feature. The point of having short audio messages instead of text is that you don't have to type a lot. You just press a button then say something, then you let go of the button. then it either gets sent aufomatically or you just press send.

The current feature is focused around the occasional file or picture that is sent in addition to the normal text, not as a true communication option.

See the following screenshot to see what I mean (example in WeChat):
http://3.bp.blogspot.com/-BIe-Tm1T7C0/UV2WyOeUGNI/AAAAAAAAFLw/lPWaYnaKnh0/s1600/Screenshot_2013-04-03-11-26-27.png

**Comment by strb** [comment]
Not to sound too snarky or anything, but you do realize that you're literally holding a phone in your hand, right?

**Comment by github-k8n** [comment]
@strb Not to sound too snarky or anything, but you realize that you can already send SMS without a need for an application like Conversations?

The point is NOT a VoIP-like conversation, but an asynchronous messaging, short audio snippets that you can listen to when you have the time, just like with text messages.

This is in contrast to the synchronous communication (phone or voip) which requires the receiving party to listen in real time.

**Comment by moshpirit** [comment]
Well, I totally agree with @github-k8n, it's a quite comfortable feature and really basic, IMO it's really easy to implement and use and it doesn't change Conversations into a VOIP app at all!! It's just an excellent feature to use when we are hurry or we can't type at this moment.

**Comment by wiseoldman95** [comment]
@SamWhited 
>IMO that seems like needless complication for something that can be done better in a modular fashion (by loading up an external audio recorder that properly registers its intents). Conversations is a messaging app, not a camera or an audio recorder..do one thing and do it well.

I completely disagree with this. Doing one thing and doing it well is all fine and dandy unless it severely harms the end-user experience. You really wouldn't want Conversations to open up a notepad app for each message being composed, because it makes it impractical -or at least very hard- to use Conversations for message exchange. Likewise, currently Conversations is impractical for "audio chats" , and having a built in audio recorder resolves this.

This deserves its own issue though, so I opened one here: #1070

In my humble opinion, build-in audio is the last missing major feature, with that in place, Conversations can function as a complete Whatsapp replacement.

**Comment by SamWhited** [comment]
> Likewise, currently Conversations is impractical for "audio chats" , and having a built in audio recorder resolves this.

That's because Conversations is a text chat app, not an audio chat app.

**Comment by moshpirit** [comment]
But all of the text apps allows this option, they have evolved into that. If we want Conversations to be a Whatsucks replacement, it has to satisfy all the needs that Whatsucks does, including what you both call "audio chats".

Btw, including the ability to send some audios easily doesn't make Conversations an "audio chat", just a more friendly/easier to use app.

**Comment by wiseoldman95** [comment]
@SamWhited Those who originally said "Do one thing and do it well" did not intend it be interpreted as "Have a separate app for chats, an app for voice chats, an app for sending images, and an app for arbitrary file transfer. Heck, have a seperate app for Emojis!".

it's perfectly fine to intertwine very closely related tasks into one app.

**Comment by SamWhited** [comment]
I'm not suggesting that it shouldn't have audio chats, just that the recorder is something that's already well supported by Android. The android way to do this sort of thing is to use a separate app, and send intents between the two (as inputmice did with the location plugin).

**Comment by github-k8n** [comment]
@SamWhited in my opinion the best way would be to have this feature as a plugin (just like the location sharing), if it is possible to integrate so tightly into the UI using a plugin and maybe have an optional "record" icon on the left side of the text entry (enabled by a preference)
The big issue here is not to make it possible at all but to have it integrated in the UI in such a way that you don't have to dig into big menus (try to explain how to use that to my wife "and then another program opens, then you record something then you attach it...", she'd just use something else), just a button and just potentially a recording indicator while you keep the button pressed.
I'd gladly buy such a plugin.

**Comment by wiseoldman95** [comment]
@SamWhited , Outsourcing is fine as long as it does not harm usability. In this case, it does.

**Comment by TameOfGroans** [comment]
@strb 

OSTN? 

https://ostel.co 

"can be done better in a modular fashion (by loading up an external audio recorder that properly registers its intents)."

Greatly preferred; else plug-ins akin to ChatSecure. 

"Conversations is a text chat app"

Strictly speaking is it not an Xmpp client?  Which is primarily used for Xmpp Texting? 

"intertwine very closely related tasks"

Yes, via intents. 



OT thought for food 

https://waze.uservoice.com/forums/59223-client-how-can-we-improve-waze-on-your-phone/suggestions/2997613-use-jingle-to-send-short-audio-blurbs-to-others

**Comment by wiseoldman95** [comment]
Intents can never achieve that "Hold, talk, release, sent" magic.

**Comment by wiseoldman95** [comment]
If intents *can* somehow do that, I actually don't mind it. But currently sending a voice message requires a dozen clicks.

**Comment by SamWhited** [comment]
> Outsourcing is fine as long as it does not harm usability. In this case, it does.

I disagree. The current situation is very usable.

> If intents can somehow do that, I actually don't mind it.

Sure, why not. This could be done, but it doesn't strike me as being in the spirit of Conversations. Sending an audio file (and maybe even previewing it) is the extent of what Conversations should do. It's not a voice app, and we shouldn't treat it like one.

> But currently sending a voice message requires a dozen clicks.

Click the menu (1), click share audio (2), click record (3), click done (4), click send (5).

I'm not saying that this process couldn't be improved, but it's certainly not onerous. The plugin for ChatSecure should work with Conversations if you want a simple, light-weight UI for this.

**Comment by wiseoldman95** [comment]
>I disagree. The current situation is very usable...Click the menu (1), click share audio (2), click record (3), click done (4), click send (5).

Yep, very convenient. Compare that to "Hold and talk, now release".
Have you ever had a "voice conversation" in Whatsapp before? It's literally Hold and talk, then release, and people shoot those messages one after another, making it a walkie-talkie-style talk. The current process is annoying enough to make a walkie-talkie style conversation not feasible. Currently Conversations is not "very usable" for walkie-talkie chats and there's no arguing here. I have to click exactly 5 times on my screen for each message. Compare that to *just one* click in Whatsapp. I would never buy such a walkie-talkie in real life.

>it doesn't strike me as being in the spirit of Conversations....It's not a voice app, and we shouldn't treat it like one.

Like other chat apps, Conversations has the capability to send arbitrary files. The most commonly shared files are images and audio, therefore these receive special treatment in almost all chat apps: They show up inline and sending them is just a click away. Conversation has achieved that with images, but not with voice messages. Making voice messages convenient does not convert it into a "voice app", it's just making the most commonly shared files easier to share.

**Comment by wiseoldman95** [comment]
iNPUTmice rejected the idea of a builtin voice recorder, because "this goes against the design principle of requiring as little permissions as possible".
I think that the best option left is going the plugin route.

I am currently on the hunt for a voice recorder app which begins recording instantly when opened, and stops when closed. It would make sharing audio in conversations much easier without actually modifying conversations (3 clicks instead of 5). If I don't find one, I intend to write one my own, this is an easy task. 
This is a good temporarily fix, but I'd prefer a single click in the future.

@iNPUTmice: Suppose I write/find a GPLed thing like that, would you be willing to re-brand it as a Conversations voice plugin?

@github-k8n 
>in my opinion the best way would be to have this feature as a plugin (just like the location sharing), if it is possible to integrate so tightly into the UI using a plugin and maybe have an optional "record" icon on the left side of the text entry (enabled by a preference)

Whatsapp and Telegram do it by having a "record" button instead of the "Send message" button when the message textbox is blank, when the user begins writing text, the "record" button is transformed into a "send" button.

Conversations could do that. (Holding the record button would open the record plugin intent, and the intent would close when the user releases touch).

**Comment by moshpirit** [comment]
>I'm not saying that this process couldn't be improved, but it's certainly not onerous. The plugin for ChatSecure should work with Conversations if you want a simple, light-weight UI for this. 

The plugin only show another different ui for the audio recorder, we'd like to have something like what Whatsucks and Telegram have but I think that some kind of shortcut like this could work too: if we hold the send button, Conversations could shows the audio recorder. It's not exactly what we want, but it's a middle term for both of us.

**Comment by iNPUTmice** [comment]
I've [just published](https://play.google.com/store/apps/details?id=eu.siacs.conversations.voicerecorder) a voice recorder plugin for Conversations that in conjunction with the newly introduced quick actions should give you pretty much what you are asking for. One click to start recording. One click to stop recording. (You can set the quick actions to always show the record button if you like)

Quick Actions require Conversations 1.4.0 which has just been tagged and pushed to [beta](http://conversations.im/#beta).

Please note the voice recorder plugin is still beta and might receive some further optimizations regarding recording quality and user interface.

**Comment by SafwatHalaby** [comment]
You rock.

**Comment by SafwatHalaby** [comment]
Is it open source?

**Comment by github-k8n** [comment]
While I already bought it in PlayStore and also recommend everyone to either buy it there or donate directly to support Conversations, I really do hope that the source code is available as well :-)

**Comment by moshpirit** [comment]
I prefer not to use Google at all and donate the money directly to them (me, for example I donated $5)

**Comment by Natureshadow** [comment]
Yep, Google Play is a potential malware service, not a crowdfunding platform.

**Comment by github-k8n** [comment]
Well, for me it is either using PlayStore in a VM to buy the app (I don't use google services on my phone of course...) or use PayPal. I prefer to not use PayPal :-)
If there is another easy way to donate I might do that instead.

**Comment by SamWhited** [comment]
This is not the place for this discussion.

**Comment by github-k8n** [comment]
Don't know where else to comment on the voice plugin so I'll do it here:
It's great, however a few suggestions:

1. The recording view would look nicer if it did not cover the whole screen, you could use
android:theme="@style/CommonTheme.Dialog"
for the activity itself to get a dialog like window something similar to this:
https://lh6.ggpht.com/0ySkHic9oNokS2h06acuv9NLJI2LgwTQqoHEFZ8ILCEYbP1nNPZoSg_MQFLMd5mXZLA=h900
(as example, that is another app intent that was called from the contact app)

2. Maybe the plugin could also offer to do the playback (again, with a dialog-like interface, not covering the whole screen)

3. The icing on the cake would of course be something like SafwatHalaby mentioned:
"Holding the record button would open the record plugin intent, and the intent would close when the user releases touch."

**Comment by SafwatHalaby** [comment]
I wonder if 3 is even possible with a Conversations plugin.
Anyways, I suggest you open a new issue for these, they'll get more attention there.

**Comment by github-k8n** [comment]
Oh, and

4. The bitrate is too high. 24kB for 3 seconds.. I would suggest to either downsample to 16 or 8 kHz and encode with less bitrate if you want to use AAC for compatibility reasons, or just use a better codec (opus? speex? latency doesn't matter as the recording is asynchronous) and also do the playback (see point 2)

**Comment by github-k8n** [comment]
I forgot, regarding (1)
android:theme="@style/CommonTheme.Dialog"
 doesn't make much sense without the following:
I had the following in styles.xml in res/values:
<style name="CommonTheme.Dialog" parent="android:Theme.Dialog"></style>
this one in styles.xml in res/values-v11
<style name="CommonTheme.Dialog" parent="android:Theme.Holo.Dialog"></style>
this one in styles.xml in res/values-v14:
<style name="CommonTheme.Dialog" parent="android:Theme.DeviceDefault.Dialog"></style>

That way, you get the "native" old UI on old devices and the native new UI on new devices and don't have to use a compatibility library on old devices.
