### ISSUE TITLE
XEP-0080: User Location support

### ISSUE THREAD

**Issue by Elmi77** [siacs/Conversations#73]
SecuXabber has a nice feature to inform other user about own position:
- select menu item "send own position"
- this evaluates own geolocation using GPS and libwlocate
- position is sent to other end encrpted
- there Nominatim is used to convert geolocation to an address
- address is shown as current position of other user

Code for Nominatim access and address decoding can be found in https://sourceforge.net/p/secuxabber/code/ci/master/tree/src/com/secuxabber/android/encryption/

libwlocate for fast and easy position evaluation can be found at https://sourceforge.net/p/libwlocate/code/ci/master/tree/master/android/LocDemo/src/com/vwp/libwlocate/

**Comment by jkufner** [comment]
Relevant article describing some tricky parts of this feature: https://guardianproject.info/2015/01/23/sharing-your-location-privately/

**Comment by allo-** [comment]
I guess there are two sides of the problem:
  - adding direct support needs another permission. Many users do not like, when an app requires stuff like location
  - sharing location from google maps app (or openstreetmap, etc.) is not known by many users. they will really need a "share location" button to find the option.

**Comment by knoy** [comment]
I believe the Guardian Project approach is the best in this case, using a geo:// URL which will trigger an intent can be used by various map applicatoins

**Comment by neufeind** [comment]
The integration with osmand sounds like a nice idea to me, in case they agree. Sharing a location once, sharing a location automatically for a certain time or so  ... that would be awesome. And being able to click in osmand on an icon to message that person directly from there (going through conversions internally) that sounds like a nice solution imho.

**Comment by iNPUTmice** [comment]
This has been implement in 1.2.0 with geo-uris. Sending geo-uris has a few benefits compared to using some sort of XML/stanza mark up. Mainly that it is working with end-to-end encryption because the URI is embedded in the body of a message. On the sending end you will need a [plugin](https://play.google.com/store/apps/details?id=eu.siacs.conversations.sharelocation). On the receiving end it will just work out of the box.
