### ISSUE TITLE
MUC disabled notifications UI

### ISSUE THREAD

**Issue by SamWhited** [siacs/Conversations#735]
I have two MUC rooms for which I like to receive all notifications (highlighted or no) and several others that I idle in and read occasionally, but don't want to be notified unless I'm mentioned.

This means that I have to have all notifications enabled, and disable notifications for individual rooms. This is fine, but means that most of the rooms I idle in have the "Notifications are disabled" bar at the bottom of the room at all times.

I'd like to discuss modifying the UI / UX so that it's not always there. Maybe a check box in the drop down menu would work better (that could be individually checked / unchecked, and the preference would just control the default value of this check box)?

Thoughts? Good idea? Bad idea?

**Comment by Natanji** [comment]
I have fixed this bug more than three months ago, see https://github.com/siacs/Conversations/pull/1023 -> it would be great if my pull request could be incorporated into Conversations somewhen soon.

**Comment by iNPUTmice** [comment]
> This means that I have to have all notifications enabled, and disable notifications for individual rooms.

I think this is the more pressing point here. So I'm closing this for now and direct you to #629 for a more general discussion on how to handle notifications in MUC.
