### ISSUE TITLE
Single contact visible in conversation start screen

### ISSUE THREAD

**Issue by ivucica** [siacs/Conversations#755]
Cheers,

I am having trouble with seeing only one contact on my contact list.

- It's not the first nor the last contact; 
- it's not unique in not having custom name; 
- it's not unique in having `subscription="none"`. 

It seems unique only in having `ask="subscribe"`. 

As I fiddled on other clients, causing presences to go to Conversations, more contacts appeared. Could it be that Conversations is not requesting `jabber:iq:roster` properly? 

Sadly, lack of time to investigate the XMPP stream prevents me from reporting this properly.

This is on Prosody revision `ea60d0441df7`. Server that I've experienced this with also serves the `badc0de.net` domain. You can use JIDs `conversationstest@badc0de.net` and `conversationstest2@badc0de.net`, both with password `conversationstest`. I'll delete the accounts in about a month, or sooner if you're done with them. If you need me to keep them longer, please let me know when you need the extension.

**Comment by iNPUTmice** [comment]
The actual issue has been resolved in 0.10.
We can deal with crazy unicode stuff in a seperate issue.
