### ISSUE TITLE
Sometimes don't arrive notifications and read marker is sent without unlock the phone

### ISSUE THREAD

**Issue by kruks23** [siacs/Conversations#758]
Hello,

Sometimes, when I lock the phone with a conversation open with contact A, when I receive a message from A, the notification doesn't arrive and the read marker is sent to A.

Here are the logs:

This log is when I lock the phone with the Conversation with A open and I receive a message from A:
12-07 08:49:53.815    2485-2485/eu.siacs.conversations D/conversations﹕ xxxx@suchat.org: sending read marker to A@suchat.org/mobile

I unlocked the phone and locked the phone again and i got this log:
12-07 08:50:09.728    2485-2485/eu.siacs.conversations I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@4209bd68 time:13903640

I repeted the process a few times:
12-07 08:50:23.923    2485-2485/eu.siacs.conversations D/conversations﹕ xxxxx@suchat.org: sending read marker to A@suchat.org/mobile
12-07 08:50:33.488    2485-2485/eu.siacs.conversations I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@4209bd68 time:13927400
12-07 08:50:44.081    2485-2485/eu.siacs.conversations D/conversations﹕ xxxx@suchat.org: sending read marker to A@suchat.org/mobile
12-07 08:50:52.372    2485-2485/eu.siacs.conversations I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@4209bd68 time:13946285

Then, I opened Conversations, and I put Conversations in the background with return Android bottom 2 times:
12-07 08:50:53.873    2485-2485/eu.siacs.conversations W/IInputConnectionWrapper﹕ showStatusIcon on inactive InputConnection

Then, when I recieve a message, send marker is not sent and the notification was there when I unlock the phone.

I'm using cyanogenmod 4.4.4 and my phone is Motorola Moto g, with Conversations 0.9.2 from fdroid.

Anyone else having the same problem?

Thank you

**Comment by iNPUTmice** [comment]
bcd3be59ce78609e608f4a8f7a868be977fdb4bb tries to address that. This has been released with 0.10 but since I never actually could verify the bug myself this is untested.
Could someone verify whether or not this worked?

**Comment by SamWhited** [comment]
I just ran into this (or something very similar) post-0.10 (d7ac9b88cf608e9a1dd66af8149264f89ba9678d). I'm unsure if it was sending the read marker or not, so it may not be related. I'll keep logcat running for a bit and see if I can reproduce the problem.

At the time, I had Gajim open and in the foreground on my desktop, and Conversations running in the background (screen was off) on my phone; I got a new message on Gajim, and heard my notification tone start on my phone, then cut off abruptly. I turned the phone screen on, and there was no new notification.

I didn't look to verify that Conversations even handles it this way, but my guess would be that Conversations is creating the notification, and then getting the read marker from Gajim and terminating the notification (but the sound or vibration has already started playing).

**Comment by iNPUTmice** [comment]
> I didn't look to verify that Conversations even handles it this way, but my guess would be that Conversations is creating the notification, and then getting the read marker from Gajim and terminating the notification (but the sound or vibration has already started playing).

That would be the case but to my knowledge gajim doesn't send out read markers does it?

**Comment by SamWhited** [comment]
@iNPUTmice Yah, it does. I'm not sure when it was added, so it may not be released yet (I'm building from a slightly customized branch off of the latest source).

**Comment by iNPUTmice** [comment]
Oh ok. Fair enough. Then yes the gajim read marker could be the source of what you are describing. But I think it is unrelated to this issue. Because I definitely saw this happening with people who weren't using another client at the time. We could open another issue for that 'received read marker from another instance a very short time after we received a message' to discus how Conversations should behave in this situation.

**Comment by kruks23** [comment]
In my case, I was only using Conversations and the read marker was sent and I didn't unlock the phone. I will test if with 0.10 is still happening.

**Comment by iNPUTmice** [comment]
> I will test if with 0.10 is still happening.

any results yet?

**Comment by kruks23** [comment]
Sorry, I couldn't notice if it is solved becuase my contacts haven't updated to 0.10 and I didn't test my self with my other phone. I tell them to update.

One thing it happens now is that sometimes the notification doesn't dissapear althougth you have read the message. I supposed this is another issue.

**Comment by kruks23** [comment]
I can't reproduce the problem in 0.10, If someone can reproduce it, I'll reopen the issue.

Thank you!
