### ISSUE TITLE
RFE: Option to enable custom vibrate pattern

### ISSUE THREAD

**Issue by deoren** [siacs/Conversations#761]
I use 8sms as my text messaging app and really appreciate being able to set a custom vibration pattern. Even if I miss the ringtone of a new text message, the custom vibrate pattern helps to get my attention.

Values for the `Vibrate pattern` setting:

* Normal
* Medium Vibrate
* Long Vibrate
* Multiple Short
* Multiple Long
* Custom vibrate pattern

**Comment by DefyMiners** [comment]
Have you tried LightFlow? I licensed it to manage such things.  It supports every Xmpp Texting app I know.

**Comment by iNPUTmice** [comment]
This level of customization is not within the scope of the project. sorry.
