### ISSUE TITLE
Register a new account

### ISSUE THREAD

**Issue by Lucki** [siacs/Conversations#769]
The registration is allowed and works with Pidgin and Kopete.
Conversations tells me that registration is unsupportet. @SamWhited thinks the available registration isn't advertised. However, Conversations should register a new account, even when the service isn't advertised. Some server can't advertise or admins don't want to advertise in special use cases like private networks.

**Comment by cultixate** [comment]
Some in-line registration pushes a URL with a captcha.  Is that the case for Pidgin and Kopete use of concerned server?
