### ISSUE TITLE
Reconnection after failure

### ISSUE THREAD

**Issue by knoy** [siacs/Conversations#770]
Recently I've been getting reports of after having been logged in, Conversations loses connectivity and reports "server not found" in accounts. Perhaps this is a bug in the reconnection code? What exactly is the logic after a connection is lost?

**Comment by iNPUTmice** [comment]
Conversations will try to reconnect again and again with an exponential back off.
There have been some DNS fixes in 50410dad334643945e4978117d81dc3cbf4c3157 and 5cbae258084a5f77857c5f535451fe3b459ce0d1 which might have been the cause for that error in the first place.
