### ISSUE TITLE
QR Code Verification Failed

### ISSUE THREAD

**Issue by knoy** [siacs/Conversations#771]
I've noticed a problem sometimes pops up when trying to verify via QR code. This seems to be caused by mismatching fingerprints which I confirmed by manually comparing the remote fingerprint while having each phone side by side. Both of us are only signed in from our phones and have the conversation open with each other, and are able to send and receive OTR messages normally

**Comment by iNPUTmice** [comment]
if you click on verify the VerifyOTRActivity is called with a parameter for the account (as jid) and a parameter for the Conversations (as Jid as well) is the any possibility that in this particular scenario the mapping failed somehow? Multiple accounts with the same Jid? Multiple Conversations with one contact?
In that case we could use the Conversations UUID as parameter instead which should be more bullet proofed
