### ISSUE TITLE
Cannot select between links

### ISSUE THREAD

**Issue by mokkin** [siacs/Conversations#777]
If somebody sends me links, no matter if in a single or by multiple messages, I cannot choose between them but get always the first one. Even the typical copy funktion doesn't work because it allows you only to copy the whole text instead to select some parts.

Motorola Moto G
Cyanongenmod 11 (Android 4.4.4)
Conversations 0.9.3

![screenshot_2014-12-13-10-42-02](https://cloud.githubusercontent.com/assets/2938748/5425439/72660380-8317-11e4-818f-d6989a4a726e.png)

**Comment by DefyMiners** [comment]
One link per message is required.

**Comment by DefyMiners** [comment]
I notice a different problem when link amidst other text. Sometimes following text appended to URL in interweb browser.

**Comment by iNPUTmice** [comment]
This seems to be fixed in Android 5.0
