### ISSUE TITLE
Discussion: Conference Options / MUC options

### ISSUE THREAD

**Issue by iNPUTmice** [siacs/Conversations#788]
XMPP gives us a lot of control over conference rooms (MUCs). The access control is far more complex than what for example IRC has to offer. (Some might say it is over engineered)
Obviously it wouldn't be the Conversations way to expose all of that functionality to the end-user. However more advanced users might miss certain functionalities MUC has to offer and maybe even some regular users will end up liking some of the features if we implement them well enough (Make them easy enough to use.)
However for this to work we need to pick a subset of the MUC spec and pack that into a good user experience.

Now my question to the 'more advanced users' of Conversations. Which muc functionality do you need very often and would like to see in Conversations?

And if there are any 'regular users' reading this issue tracker? What are some conference features / options / controls you would like to have? You can use plain English to describe. You don't have to use IRC or MUC vocabulary.

To become a bit more specific my thoughts on that would be to provide a simple Private / Public switch which in the background would set membersonly=1, whois=anyone, public=0 or their reverse respectively.
On top of that it might be a good idea to ditch the entire role stuff in favor of only using affiliations. The background here is that roles are temporary and affiliations are not. (Thus in after a reconnect roles will be gone which might be very hard to explain to the average user. And I honestly can't imagine a real use case here.)
@betheg has already laid some ground work in his #725 pull request which at least from the technical side of things will allow us to implement a nice UX on top.

**Comment by iNPUTmice** [comment]
HEAD has now some basic muc controls (change affiliation, modify certain options)
It's not yet completely tested and there is still some work today (participants aren't being promoted to members when making a room private)

It took me a while to figure out how the UX should be like for this but I think the result is light enough but still allows for future extension if we ever want to provide the user with more control over conferences.

**Comment by flasheater** [comment]
Do I need to build from source to test this ,or is there a beta channel?

-- Oliver Krylow

**Comment by egproo** [comment]
all option here

https://github.com/solkin/mandarin-j2me-legacy/blob/master/note/conference_settings.txt

**Comment by iNPUTmice** [comment]
@egproo the point isn't to link to every available option but to explain why Conversation should include a particular option.

**Comment by egproo** [comment]
@iNPUTmice  :: Importance stems from the Owner's need to manage muc room and eliminate the need to use another XMPP/Jabber client And sufficiency conversation.
