### ISSUE TITLE
Allow canceling of transmissions with status "waiting"

### ISSUE THREAD

**Issue by SamWhited** [siacs/Conversations#808]
When a file or image transmission has status "waiting" (eg. send a file to a contact who is offline), the transfer can't be canceled via the long-press context menu.

I threw a quick patch together [here](https://github.com/SamWhited/Conversations/tree/sendfixes), but I don't really understand the file transfer code well enough yet and suspect this is the wrong way to go about it. May not be able to get back to this today, so I made the issue in case anyone else has time to fix it or wants to take a look.

**Comment by iNPUTmice** [comment]
fixed in 3df23a4f75263d17a4db95a9a4f8c26c0246962c
