### ISSUE TITLE
Add Conversations to Amazon App Store

### ISSUE THREAD

**Issue by maufl** [siacs/Conversations#815]
I would really like to gift Conversions to some of my friends. Unfortunately this is not possible in Google Play Store. On Amazon you can do this.

**Comment by DefyMiners** [comment]
It is a double gift on F-droid.org.   You help a friend experience repo FREEDOM. You also provide liberation from false-free apps [malware (adware)].

**Comment by singpolyma** [comment]
Now that Amazon store is on all blackberry devices, I want this even more

**Comment by iNPUTmice** [comment]
OK I need your help.
Amazon requires me to publish screenshots in Full HD resolution. (Portrait) I currently don't have a device capable of this. Can someone create some Screenshots for me? (You probably have to create some fake conversations to not violate the privacy of your contacts.)
This, admittedly, is some work but will be vastly appreciated and is a great way for to contribute to the projrct if you don't have any coding skill.

**Comment by maufl** [comment]
I have a OnePlus One, which should have the required resolution. I made to screenshots of chats where I asked my partner for permission to use it in the Amazon App Store.
Let me know if you want more/different images.
![screenshot_2015-04-07-17-03-22](https://cloud.githubusercontent.com/assets/423964/7026400/c3aa9d28-dd49-11e4-8d9a-15ebbcdf4b2e.png)
![screenshot_2015-04-07-15-50-13](https://cloud.githubusercontent.com/assets/423964/7026399/c3a823ae-dd49-11e4-8bbb-352b41cf24d4.png)

**Comment by iNPUTmice** [comment]
Added http://www.amazon.com/dp/B00WD35AAC/

will see if and how I can add a button to the readme later

@maufl I will gladly take those. Thank you
