### ISSUE TITLE
First message not delivered

### ISSUE THREAD

**Issue by sniperle** [siacs/Conversations#820]
When I open a chat or reopen an existing chat after a while, the first message sent in that chat is not delivered. Starting with the second message all messages arrive as expected.

**Comment by iNPUTmice** [comment]
I'm guessing this is for OTR messages? If so please use a server that has stream management enabled (you should do that anyway) 
duplicate of #635

**Comment by iNPUTmice** [comment]
No reaction from OP? closed

**Comment by sniperle** [comment]
I'm using jabber.org
