### ISSUE TITLE
CSI on server info menu not available

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#828]
With the PlayStore Verison 0.10 on the server info menu the XEP-0352: Client State Indication is not available, but it seems to work. The android logging shows the indications "foregroud" and "background" and in prosody trunk it is activated without any errors.

**Comment by iNPUTmice** [comment]
mod_csi for prosody doesn't announce a csi version but `urn:xmpp:csi`. which is pre-xep i believe. Conversations triggers only on the XEP version which is `urn:xmpp:csi:0`
I guess I could make Conversations trigger on  `urn:xmpp:csi` but the right thing to do would be to update the mod. (I guess you could even to that yourself very quickly)

However the last think I heard is that CSI in prosody still has some bugs with stream management.... Thats why I haven't tested this myself yet. @Zash ?

**Comment by Zash** [comment]
> CSI in prosody still has some bugs with stream management

Last I heard is that I thought I fixed those.

**Comment by kriztan** [comment]
With the current mod_csi and prosody trunk 541, I've noticed a lot of reconnects round about every 5 to 10 minutes. Although some of the clients are inside the same network like the server is.

**Comment by RalfJung** [comment]
> Last I heard is that I thought I fixed those.

Which prosody version(s) contain the fix? Debian stable has 0.9.7. I'm currently wondering whether it would be better for me to enable `mod_csi` from prosody-modules (which seems to add the extension name that Conversations expects) to save battery, or whether I should not do this because it breaks things?

**Comment by Zash** [comment]
There's no fix in Prosody, it was fixed in mod_smacks.
