### ISSUE TITLE
indicate received files with a tick

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#842]
Is it possible to add a tick for successfully received files and images like in #460 for messages?

**Comment by iNPUTmice** [comment]
Images are send P2P so if the image is transferred (changes from sending to sent) the image is also received

**Comment by jkufner** [comment]
Then it should be easy to add the tick, just for the sake of consistency.

**Comment by kriztan** [comment]
Yes, @jkufner talks out of my mind.
