### ISSUE TITLE
[Req] display every Resource for logged in contact

### ISSUE THREAD

**Issue by DefyMiners** [siacs/Conversations#844]
Should each full JID have a different OTR fingerprint

Base JID: savory@ra.tld 

Full JIDs

Savory@ra.tld/mobile
Savory@ra.tld/tablet 
Savory@ra.tld/mbp 

I would like to select the resource for Xmpp Texting when I know which device friend will be carrying.

**Comment by iNPUTmice** [comment]
Conversations will prompt you with dialog to select the resource if needed. Eg when starting an otr session or when sending a file.
All other messages will go to the bare jid and arrive on every resource
