### ISSUE TITLE
Use Transifex for translations

### ISSUE THREAD

**Issue by plsng** [siacs/Conversations#853]
I think it would be useful if the translations for this project could be put on Transifex (or something similar). That way it's easier for people to contribute, as instead of manually editing files they can just enter translations for their favourite language on Transifex. (Unless manually editing isn't what I should be doing.)

**Comment by iNPUTmice** [comment]
Project on transifex has been created.

https://www.transifex.com/projects/p/conversations/

will add missing resources and other stuff later
