### ISSUE TITLE
Conversations doesn't ignore "carbon"ed OTR messages

### ISSUE THREAD

**Issue by tasn** [siacs/Conversations#855]
Hey,

I have the following setup:
Prosody with "carbon" enabled.
Gajim on the desktop
Conversations on the phone
When I initiate an OTR session from the phone and message a friend, I don't get any messages in Gajim, as expected.
When I initiate an OTR session from Gajim and message a friend, I get in CC all mine (but not my friend's) messages in encrypted form (?otr...). This obviously shouldn't be happening.

**Comment by timosl** [comment]
Duplicate of #674 and #214

**Comment by tasn** [comment]
Oh sorry, I only looked for open tickets, not closed ones. My bad.
