### ISSUE TITLE
Conversations does not work properly with Bitmask (VPN)

### ISSUE THREAD

**Issue by icaroperseo** [siacs/Conversations#856]
I've used Conversations with [Bitmask](https://bitmask.net/) for a while but unfortunately I have been unable to use it properly with some Jabber/XMPP-servers. For example, it works well with **riseup.net** but with **jabber.at** it is unable to perform the connection while bitmask is active. I tried with another Jabber/XMPP-client (Xabber) and I have not had this problem.

If you need more information about it, just let me know...

Thanks in advance!

**Comment by RiftDraft** [comment]
> https://bitmask.net/en/features

"We take extra security measures to prevent problems common to other personal VPNs"

Would you be able to elaborate? 

Why trust such a service promoting itself as convenient gatekeeper and keymaster for OpenPGP:

"Automatic Key Management. The user never needs to know or worry about generating keys, discovering keys, or validating keys."


Would you be willing to rise up and invite me to create a new user account for additional exploration in this scope?  [in-band registration was not surprisingly unsuccessful].

**Comment by the-solipsist** [comment]
@RiftDraft Bitmask currently doesn't work with legacy Riseup account credentials, and in-band registration is the way to create a new account.  In-band registration doesn't require invites the way the legacy Riseup accounts do.

**Comment by iNPUTmice** [comment]
@icaroperseo is this still a problem? Since you originally posted this Conversations received some updates on its DNS code. Any chance that this solved your problem?

**Comment by icaroperseo** [comment]
@iNPUTmice sorry, no luck here! Same issue.

**Comment by iNPUTmice** [comment]
@icaroperseo current HEAD has again received some updates. Can you check again?

**Comment by iNPUTmice** [comment]
probably fixed by 3db70876588ca43687b69a3305a2547270aa0850
