### ISSUE TITLE
Long string interferes with advanced mode settings icon

### ISSUE THREAD

**Issue by SamWhited** [siacs/Conversations#860]
In the MUC options, the public conference string in the default locale is a bit long and interferes with the advanced options icon:

![screenshot](https://cloud.githubusercontent.com/assets/512573/5693154/b4866c82-98de-11e4-8b3c-3265985056d9.png)

**Comment by iNPUTmice** [comment]
This string has now proper line breaks. Question is whether we should still change the default string to something shorter. Like leaving the 'This is a'?

**Comment by SamWhited** [comment]
That seems reasonable to me; just as readable, and less verbose.

**Comment by plsng** [comment]
I think "This is a public conference" or something like that could also work.
