### ISSUE TITLE
Support for XMPP servers with internal domain.

### ISSUE THREAD

**Issue by mfriedenhagen** [siacs/Conversations#861]
In our company we use an internal XMPP server where usernames are USER@COMPANY.domain. These names are obviously not resolvable from the internet, so the standard lookup mechanism via a SRV entry does not work. So it would be great if you could add the possibility to add a custom server entry in a configuration dialog.

**Comment by jkufner** [comment]
You can setup private DNS server which will resolve these private domains.

**Comment by mfriedenhagen** [comment]
Is the server cached/stored once it is resolved? I have no real influence on DNS resolution when on the road (where I want to use Conversations obviously ;-)).

**Comment by jkufner** [comment]
It is cached, but not for long. Best option here is VPN.

**Comment by mfriedenhagen** [comment]
Unfortunately VPN is not an option :cry:

**Comment by jkufner** [comment]
Then the last option is to edit /system/etc/hosts and add missing
hostnames there. But your phone needs to be rooted for this to work and
changes will be lost after system upgrade (probably).

If even this fails, I have some bad news for you. This feature was
declined many times, so your company should fix your Jabber server.

**Comment by mfriedenhagen** [comment]
That's a pity, when you try to host your own XMPP server you are not always able to influence DNS either.

**Comment by iNPUTmice** [comment]
> That's a pity, when you try to host your own XMPP server you are not always able to influence DNS either.

you will need control over DNS for server to server communication anyway
