### ISSUE TITLE
Server not found WLAN issues

### ISSUE THREAD

**Issue by tokudan** [siacs/Conversations#862]
Hello,

this might or might not be related to #811. I just saw Conversations being unable to connect again, while my laptop using Psi+ had no trouble connecting (and reconnecting when I forced the connection to close from the server) to my Prosody server. I saw it happen twice since upgrading to 0.10 now.

I restarted Prosody to ensure that the server had no issue with any cached data. Psi+ happily reconnected after a couple of seconds.
Watching the server log I did not see any connection attemps from Conversations, which just kept repeating the "Server nicht gefunden" (~ server not found) message

Both my laptop and the android device are connected through the same WLAN, so the routing should be exactly the same.
Not sure if Psi+ uses the SRV records to determine the actual server name, but this shouldn't really matter as my domain name and the SRV record point to the same IP both in IPv4 and IPv6:
example.com IN A 1.2.3.4
example.com IN AAAA 1:2:3:4:5::6
xmpp.example.com IN A 1.2.3.4
xmpp.example.com IN AAAA 1:2:3:4:5::6
_xmpp-client._tcp.example.com  18000 IN SRV     0 5 5222 xmpp.example.com

After disconnecting from the WLAN, Conversations was able to connect at once. Reenabling WLAN resulted in Conversations being able to connect through the WLAN as well.

I did not see any way to enabling logging somewhere or to get a better error message what exactly failed. Can you provide more detailed errors in Conversations?

**Comment by iNPUTmice** [comment]
> I did not see any way to enabling logging somewhere or to get a better error message what exactly failed. Can you provide more detailed errors in Conversations?

Not in Conversations itself but on your computer via the android debug bridge. See [README.md](https://github.com/siacs/Conversations#how-do-i-debug-conversations)

**Comment by tokudan** [comment]
thanks, that works. Next time I see the issue I'll try to capture the logs.

Not related to this issue: Is it normal that conversations falls back to the google DNS server 8.8.8.8? I saw that happen in the log while wlan was just connecting.

**Comment by tokudan** [comment]
Ok, I think I have a clear picture what causes this issue.
The problem only occours in IPv6 WLANs where android gets an IPv6 address when connecting, but for some reason IPv6 does not work. From the terminal I was unable to ping the IPv6 address of the router or any other IPv6 address, but android claimed to have a valid and routable IPv6 address in the output of "ip a".

The reason that Conversations is unable to connect is rather simple: It does not fall back to IPv4 if IPv6 fails. I can watch it failing to connect to the IPv6 address, while IPv4 would work instantly.

While IPv6 is still rather unstable, could you please implement a fallback, if IPv6 fails, try IPv4?

**Comment by iNPUTmice** [comment]
> While IPv6 is still rather unstable, could you please implement a fallback, if IPv6 fails, try IPv4?

Conversations will try to connect to every IP address (v4 and v6) that it finds in DNS. How do your DNS records look like? Maybe your DNS server only reports ipv6 addresses?

**Comment by iNPUTmice** [comment]
would you be able to build / test Conversations yourself if I gave you a special branch to test with?

**Comment by tokudan** [comment]
my DNS records should be ok:
_xmpp-client._tcp  18000 IN SRV     0 5 5222 xmpp.besaid.de.
_xmpp-server._tcp  18000 IN SRV     0 5 5269 xmpp.besaid.de.
xmpp                     IN A       148.251.6.51
xmpp                     IN AAAA    2a01:4f8:201:6032::2

And querying the same DNS server that my android device uses:
# host xmpp.besaid.de 192.168.253.1
Using domain server:
Name: 192.168.253.1
Address: 192.168.253.1#53
Aliases: 

xmpp.besaid.de has address 148.251.6.51
xmpp.besaid.de has IPv6 address 2a01:4f8:201:6032::2

I should be able to build it. Though I don't have much experience with building android apps yet.

**Comment by SamWhited** [comment]
If it's trying to connect to v6 first (and not falling back to v4), it wouldn't even get the SRV records if v6 isn't working.

**Comment by tokudan** [comment]
It does seem to get the SRV values, as it resolves the domain to the correct xmpp server.
From what I can see below all Conversations does is try the IPv6 address. Considering that nslookup returns both IPv4 and IPv6 addresses I think the fallback does not work.
Note that the first connection (using IPv6, according to the server log) seems to be fine and all later connections fail.
I've traced the IPv6 issue back to AFWall+...  as soon as I disable the firewall, IPv6 works. But still Conversations should fall back to IPv4 in my opinion.

Here's a full log after an android reboot:
--------- beginning of /dev/log/system
02-08 17:22:49.908 D/conversations( 4058): start merging phone contacts with roster
02-08 17:22:49.928 D/conversations( 4058): df@besaid.de: connecting
02-08 17:22:49.938 D/conversations( 4058): finished merging phone contacts
02-08 17:22:49.938 D/conversations( 4058): using dns server: 192.168.253.1 to look up besaid.de
02-08 17:22:49.948 D/conversations( 4058): using dns server: 8.8.8.8 to look up besaid.de
02-08 17:22:49.958 D/conversations( 4058): df@besaid.de: timeout in dns
02-08 17:22:51.648 D/conversations( 4058): start merging phone contacts with roster
02-08 17:22:51.648 D/conversations( 4058): finished merging phone contacts
02-08 17:22:51.928 D/conversations( 4058): start merging phone contacts with roster
02-08 17:22:51.938 D/conversations( 4058): finished merging phone contacts
02-08 17:22:59.408 D/conversations( 4058): df@besaid.de: connecting
02-08 17:22:59.408 D/conversations( 4058): using dns server: 192.168.253.1 to look up besaid.de
02-08 17:22:59.478 D/conversations( 4058): df@besaid.de: using values from dns xmpp.besaid.de:5222
02-08 17:22:59.828 D/conversations( 4058): df@besaid.de: TLS connection established
02-08 17:22:59.888 D/conversations( 4058): df@besaid.de/mobile: Authenticating with SCRAM-SHA-1
02-08 17:23:00.388 D/conversations( 4058): df@besaid.de: logged in
02-08 17:23:00.498 D/conversations( 4058): df@besaid.de: sending deprecated session
02-08 17:23:00.538 D/conversations( 4058): df@besaid.de: fetching roster
02-08 17:23:00.548 D/conversations( 4058): df@besaid.de: sending intial ping
02-08 17:23:00.808 D/conversations( 4058): df@besaid.de: online with resource mobile
02-08 17:23:00.818 D/conversations( 4058): df@besaid.de: successfully enabled carbons
02-08 17:28:05.358 D/conversations( 4058): df@besaid.de send ping
02-08 17:28:17.388 D/conversations( 4058): df@besaid.de: ping timeout
02-08 17:28:17.458 D/conversations( 4058): df@besaid.de: disconnecting
02-08 17:28:17.498 D/conversations( 4058): df@besaid.de: Socket closed
02-08 17:28:17.498 D/conversations( 4058): df@besaid.de: connecting
02-08 17:28:17.508 D/conversations( 4058): using dns server: 192.168.253.1 to look up besaid.de
02-08 17:28:17.568 D/conversations( 4058): df@besaid.de: using values from dns xmpp.besaid.de:5222
02-08 17:28:37.648 D/conversations( 4058): df@besaid.de: failed to connect to xmpp.besaid.de/2a01:4f8:201:6032::2 (port 5222) after 20000ms
02-08 17:28:37.648 D/conversations( 4058): df@besaid.de: error connecting account. try again in 5s for the 1 time
02-08 17:28:43.698 D/conversations( 4058): df@besaid.de: connecting
02-08 17:28:43.698 D/conversations( 4058): using dns server: 192.168.253.1 to look up besaid.de
02-08 17:28:43.768 D/conversations( 4058): df@besaid.de: using values from dns xmpp.besaid.de:5222
02-08 17:29:03.788 D/conversations( 4058): df@besaid.de: failed to connect to xmpp.besaid.de/2a01:4f8:201:6032::2 (port 5222) after 20000ms
02-08 17:29:03.798 D/conversations( 4058): df@besaid.de: error connecting account. try again in 17s for the 2 time
02-08 17:29:21.968 D/conversations( 4058): df@besaid.de: connecting
02-08 17:29:21.968 D/conversations( 4058): using dns server: 192.168.253.1 to look up besaid.de
02-08 17:29:22.038 D/conversations( 4058): df@besaid.de: using values from dns xmpp.besaid.de:5222
02-08 17:29:40.048 D/conversations( 4058): df@besaid.de: failed to connect to xmpp.besaid.de/2a01:4f8:201:6032::2 (port 5222) after 20000ms: isConnected failed: EHOSTUNREACH (No route to host)
02-08 17:29:40.058 D/conversations( 4058): df@besaid.de: error connecting account. try again in 38s for the 3 time

Conversations keeps trying, so if's just removed the failed retries at the end.

some adb shell commands:
root@hlte:/ # nslookup xmpp.besaid.de 192.168.253.1                            
Server:    192.168.253.1
Address 1: 192.168.253.1 fritz.box

Name:      xmpp.besaid.de
Address 1: 2a01:4f8:201:6032::2 ashe.besaid.de
Address 2: 148.251.6.51 ashe.besaid.de
root@hlte:/ # ping 148.251.6.51
PING 148.251.6.51 (148.251.6.51) 56(84) bytes of data.
64 bytes from 148.251.6.51: icmp_seq=1 ttl=54 time=39.1 ms
64 bytes from 148.251.6.51: icmp_seq=2 ttl=54 time=35.6 ms
64 bytes from 148.251.6.51: icmp_seq=3 ttl=54 time=35.7 ms
^C
--- 148.251.6.51 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 35.618/36.828/39.100/1.607 ms
root@hlte:/ # ping6 2a01:4f8:201:6032::2
PING 2a01:4f8:201:6032::2(2a01:4f8:201:6032::2) 56 data bytes
From 2a02:2028:154:c781:28ca:b715:6145:5fe icmp_seq=1 Destination unreachable: Address unreachable
From 2a02:2028:154:c781:28ca:b715:6145:5fe icmp_seq=2 Destination unreachable: Address unreachable
From 2a02:2028:154:c781:28ca:b715:6145:5fe icmp_seq=3 Destination unreachable: Address unreachable
From 2a02:2028:154:c781:28ca:b715:6145:5fe icmp_seq=4 Destination unreachable: Address unreachable
From 2a02:2028:154:c781:28ca:b715:6145:5fe icmp_seq=5 Destination unreachable: Address unreachable
From 2a02:2028:154:c781:28ca:b715:6145:5fe icmp_seq=6 Destination unreachable: Address unreachable
^C
--- 2a01:4f8:201:6032::2 ping statistics ---
7 packets transmitted, 0 received, +6 errors, 100% packet loss, time 6004ms

1|root@hlte:/ #

**Comment by iNPUTmice** [comment]
16dc13e4dfd2995da3213f7197de63ac97d74d56 tries to address this issue. Bare in mind though that this just prevents Conversations from resolving the domain and lets the operating system do it's magic.  If your IPv6 setup is broken or blocked by a firewall this might or might not work.
If you are a member of the beta testing team http://conversations.im/#beta you will receive that patch within the next hours. otherwise you can try and build this yourself.

**Comment by Bogdan-D** [comment]
I have same issue sometimes! But not related to ipv6. I just wish Conversations keep trying to reconnect event if server not found, because minute ago server was awailable

**Comment by h4711** [comment]
This issue seems to be related to WLAN access (via fritz box), server gets found imedeatly using mobile data. Tested with 1.0.1.

**Comment by AndreasKrause** [comment]
In my case I see the following: Conversations works as expected in my home WiFi network but after some time in standby it loses the connection and can't reconnect due to EHOSTUNREACH. My guess is, this is somehow related to expiring ipv6 addresses which aren't refreshed properly (in fact, I found my interface with a link local ipv6 address only). Android user experience this in various ways:

http://developer.samsung.com/forum/board/thread/view.do?boardName=General&messageId=239890
https://jira.cyanogenmod.org/browse/CYAN-5990

So one solution could be: When Conversations notices a lost connection it might try to reconnect to the last used IP address just as it does now. But if that fails, don't retry over and over again to this address, instead try other resolved IP addresses of the server, especially ipv4.

**Comment by AndreasKrause** [comment]
Finally I found this:

Samsung phones ignore ICMP/IPv6 as soon as they're switched in standby mode. This can be proved by pinging them with ICMP/IPv6 and ICMP/IPv4 at the same time. While the IPv4 packets continue to be answered, IPv6 ping answers stop in the moment the phone is switched to standby. This behavior is the same for stock firmware and for e.g. Cyanogenmod, so the problem sits in the wifi driver (see http://developer.samsung.com/forum/board/thread/view.do?boardName=General&messageId=239890).

This _breaks_ IPv6 in the moment the IPv6 address reaches its end of lifetime, as no router advertisements are received to accept a new one. In my case the IPv6 changes quite often (Deutsche Telekom dual stack, less than half an hour or so). So within max 30 min in standby Conversations will lose its connection due to the lost IPv6 address. Other Apps including Google Push Services are affected as well. It's all Samsung's fail.

So my options are to switch off IPv6 in my entire local network (c'mon, Samsung, it's 2015!) or to disable AAAA records for C2S in my DNS (since I run my own DNS, not everyone is able to do this).

Since this problem affects everyone running Conversations on a Samsung phone in a dual stack network with short lease times, I suggest a workaround for this: When Conversation fails to reconnect with "EHOSTUNREACH (No route to host)" due to no valid global IPv6 address on the local interface it should not retry the same destination address over and over again (which is an IPv6 address and IPv6 connectivity is broken at this moment of time), instead re-resolve DNS and try other (IPv4) addresses. Currently this can be triggered manually by disabling and re-enabling all accounts. So after EHOSTUNREACH it really should trigger the same process as the initial connect.

**Comment by iNPUTmice** [comment]
@AndreasKrause can you post the log output of when this happens? Because since 1.0.3 Conversations should always try to resolve this again and not use the cache IPv6 address.

**Comment by AndreasKrause** [comment]
@iNPUTmice Timeline was as follows: 10:39:48 device set into standby mode, 10:50:00 device switched on, found Conversation in not connected state. Shortly after that: disabled account and re-enabled it. I do hope it's the relevant part of the log and anonymization of domains and IPs did not eradicate any useful information

02-27 10:39:48.275 D/conversations(3972): app switched into background
02-27 10:44:38.380 D/conversations(3972): me@mydomain.tld send ping
02-27 10:44:49.395 D/conversations(3972): me@mydomain.tld: ping timeout
02-27 10:44:49.405 D/conversations(3972): me@mydomain.tld: disconnecting
02-27 10:44:49.410 D/conversations(3972): me@mydomain.tld: Socket closed
02-27 10:44:49.430 D/conversations(3972): me@mydomain.tld: connecting
02-27 10:44:49.435 D/conversations(3972): using dns server: 192.168.178.1 to look up mydomain.tld
02-27 10:44:49.590 D/conversations(3972): me@mydomain.tld: using values from dns xmpp.mydomain.tld:5222
02-27 10:44:50.190 D/conversations(3972): me@mydomain.tld: failed to connect to xmpp.mydomain.tld/1111:2222:3333:4444:5555:6666:7777:8888 (port 5222) after 20000ms: isConnected failed: EHOSTUNREACH (No route to host)
02-27 10:44:50.200 D/conversations(3972): me@mydomain.tld: error connecting account. try again in 25s for the 1 time
02-27 10:45:24.610 D/conversations(3972): me@mydomain.tld: connecting
02-27 10:45:24.620 D/conversations(3972): using dns server: 192.168.178.1 to look up mydomain.tld
02-27 10:45:24.785 D/conversations(3972): me@mydomain.tld: using values from dns xmpp.mydomain.tld:5222
02-27 10:45:25.115 D/conversations(3972): me@mydomain.tld: failed to connect to xmpp.mydomain.tld/1111:2222:3333:4444:5555:6666:7777:8888 (port 5222) after 20000ms: isConnected failed: EHOSTUNREACH (No route to host)
02-27 10:45:25.125 D/conversations(3972): me@mydomain.tld: error connecting account. try again in 37s for the 2 time
02-27 10:46:03.190 D/conversations(3972): me@mydomain.tld: connecting
02-27 10:46:03.190 D/conversations(3972): using dns server: 192.168.178.1 to look up mydomain.tld
02-27 10:46:03.350 D/conversations(3972): me@mydomain.tld: using values from dns xmpp.mydomain.tld:5222
02-27 10:46:25.465 D/conversations(3972): me@mydomain.tld: failed to connect to xmpp.mydomain.tld/1111:2222:3333:4444:5555:6666:7777:8888 (port 5222) after 20000ms: isConnected failed: EHOSTUNREACH (No route to host)
02-27 10:46:25.475 D/conversations(3972): me@mydomain.tld: error connecting account. try again in 34s for the 3 time
02-27 10:47:18.555 D/conversations(3972): me@mydomain.tld: connecting
02-27 10:47:18.575 D/conversations(3972): using dns server: 192.168.178.1 to look up mydomain.tld
02-27 10:47:18.720 D/conversations(3972): me@mydomain.tld: using values from dns xmpp.mydomain.tld:5222
02-27 10:47:21.705 D/conversations(3972): me@mydomain.tld: failed to connect to xmpp.mydomain.tld/1111:2222:3333:4444:5555:6666:7777:8888 (port 5222) after 20000ms: isConnected failed: EHOSTUNREACH (No route to host)
02-27 10:47:21.730 D/conversations(3972): me@mydomain.tld: error connecting account. try again in 81s for the 4 time
02-27 10:49:03.440 D/conversations(3972): me@mydomain.tld: connecting
02-27 10:49:03.560 D/conversations(3972): using dns server: 192.168.178.1 to look up mydomain.tld
02-27 10:49:03.710 D/conversations(3972): me@mydomain.tld: using values from dns xmpp.mydomain.tld:5222
02-27 10:49:06.695 D/conversations(3972): me@mydomain.tld: failed to connect to xmpp.mydomain.tld/1111:2222:3333:4444:5555:6666:7777:8888 (port 5222) after 20000ms: isConnected failed: EHOSTUNREACH (No route to host)
02-27 10:49:06.710 D/conversations(3972): me@mydomain.tld: error connecting account. try again in 123s for the 5 time
02-27 10:50:15.690 I/Timeline(2665): Timeline: Activity_launch_request id:eu.siacs.conversations time:573537
02-27 10:50:15.695 I/ActivityManager(2219): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=eu.siacs.conversations/.ui.ConversationActivity bnds=[152,465][251,578]} from pid 2665
02-27 10:50:16.010 D/conversations(3972): app switched into foreground
02-27 10:50:16.500 I/Timeline(2219): Timeline: Activity_windows_visible id: ActivityRecord{426dfb40 u0 eu.siacs.conversations/.ui.ConversationActivity t2} time:574346
02-27 10:50:18.635 I/Timeline(3972): Timeline: Activity_launch_request id:eu.siacs.conversations time:576482
02-27 10:50:18.635 I/ActivityManager(2219): START u0 {cmp=eu.siacs.conversations/.ui.ManageAccountActivity} from pid 3972
02-27 10:50:18.900 I/ActivityManager(2219): Displayed eu.siacs.conversations/.ui.ManageAccountActivity: +229ms
02-27 10:50:19.225 I/Timeline(2219): Timeline: Activity_windows_visible id: ActivityRecord{42511140 u0 eu.siacs.conversations/.ui.ManageAccountActivity t2} time:577074
02-27 10:50:27.870 D/conversations(3972): me@mydomain.tld: error connecting account. try again in 42s for the 5 time
02-27 10:50:27.980 D/conversations(3972): me@mydomain.tld: disconnecting
02-27 10:50:30.495 D/conversations(3972): me@mydomain.tld: connecting
02-27 10:50:30.500 D/conversations(3972): using dns server: 192.168.178.1 to look up mydomain.tld
02-27 10:50:30.610 D/conversations(3972): me@mydomain.tld: using values from dns xmpp.mydomain.tld:5222
02-27 10:50:31.190 D/conversations(3972): me@mydomain.tld: TLS connection established
02-27 10:50:31.235 D/conversations(3972): me@mydomain.tld/mobile: Authenticating with SCRAM-SHA-1
02-27 10:50:31.315 D/conversations(3972): me@mydomain.tld: logged in
02-27 10:50:31.395 D/conversations(3972): me@mydomain.tld: sending deprecated session
02-27 10:50:31.440 D/conversations(3972): me@mydomain.tld: sm catchup: <iq xmlns="jabber:client" type="result" id="a4b7ibsubc"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid xmlns="urn:ietf:params:xml:ns:xmpp-bind">me@mydomain.tld/mobile</jid></bind></iq>
02-27 10:50:31.455 D/conversations(3972): me@mydomain.tld: fetching roster
02-27 10:50:31.460 D/conversations(3972): me@mydomain.tld: sending intial ping
02-27 10:50:31.470 D/conversations(3972): me@mydomain.tld: sm catchup: <iq xmlns="jabber:client" to="me@mydomain.tld/mobile" type="result" id="sf8o6b8o8p"/>
02-27 10:50:31.490 D/conversations(3972): me@mydomain.tld: stream managment(3) enabled (resumable)

**Comment by iNPUTmice** [comment]
Oh thats not the Conversation DNS cache here that we are running into thats the DNS cache of the underlying C functions of the operating system. I quickly googled that and I have no idea on how to reset those.
I mean what Conversations does is basically tell the OS please resolve xmpp.mydomain.tld for me.
I also don't know why re-enabling an account would cause the the DNS library to flush. Maybe because this will create a new object?! However as a work around this is not really feasible because this will loose all state information. (like session and so forth)

> Other Apps including Google Push Services are affected as well.

Stop buying Samsung phones?! If your phone is younger than 6 month just return it...

I know I'm not really helping here and I'm sorry about that. But everything Conversations could do it this point would be some ugly, ugly workarounds. (Maybe do DNS completly by itself?)
The problem here is that I neither have a Samsung device nor an IPv6 network (ok the latter could maybe arranged somehow.)
If someone who owns a Samsung device would come up with a solution that is not too dirty I'm willing to merge it

**Comment by AndreasKrause** [comment]
Yes, as I've written before: It's all Samsung's fail. In my case it's a Samsung Galaxy S2 with CM11 and a Samsung Galaxy S4 with stock KK. Returning either of them is not an option, so as you can't do anything to work around the problem, I will remove the AAAA records from my DNS.

Whenever I'll find another solution or workaround, I will post it here.

THX anyway

**Comment by moneytoo** [comment]
Now I understand why other clients use bundled resolvers - like Jitsi uses ``org.xbill.DNS``.

**Comment by iNPUTmice** [comment]
latest HEAD explicitly requests both ipv4 and ipv6 addresses now. this should solve most of the ipv6 related problems

**Comment by gerroon** [comment]
@AndreasKrause 

Have you found a solution/work around for this issue because I still get server not found when the device is in standby on my Samsung phone.

**Comment by iNPUTmice** [comment]
@gerroon do you have a logcat for when this happens? Recent Conversations should explicitly prefer IPv4 and I'm curious on why this doesn't seem to be happening.

**Comment by gerroon** [comment]
@iNPUTmice

Sorry I did not have a log to report here. It always catches me when I am on the go so I did not have a setup to get the logs. I was wondering if @AndreasKrause had some progress since I have a similar phone to his.

**Comment by AndreasKrause** [comment]
Meanwhile I was forced to switch to another phone, Samsung Galaxy S5, that currently runs CM13 (nightly). These nightlies have issues with WiFi disconnecting in standby in general. So I can't contribute anything helpful here. All I can tell is that @iNPUTmice 's solution helped a lot back then.

**Comment by gerroon** [comment]
Could this be also related to "manual status" mode?
