### ISSUE TITLE
Add support for the /me command (XEP-0245)

### ISSUE THREAD

**Issue by SamWhited** [siacs/Conversations#865]
It should be trivial to implement [XEP-0245][xep0245], the IRC-style `/me` command (since it's just formatting).

Displaying the username in italics (similar to private markers, but without the text color change to prevent confusion) in place of the `/me` would probably look fine.

[xep0245]: http://xmpp.org/extensions/xep-0245.html

**Comment by SamWhited** [comment]
/me messages should probably not be merged as well (like private messages).

**Comment by iNPUTmice** [comment]
you should use Message.mergable(Message) to prevent messages starting with /me from being merged.

otherwise using
````
final String formattedBody = message.getBody().replaceAll("^/me ", nick + " ");
````
instead of message.getMergedBody().replaceAll(.... will lead to message loss.

or merge /me messages and just do the ***nick*** says thing in every line

**Comment by SamWhited** [comment]
@iNPUTmice Is this stil the case since `getMergedBody` is never being called? The way it works right now is it checks if the current message starts with \me and if it does it sets the message text. Otherwise, it calls `getMergedBody` and uses that as the message text.

**Comment by iNPUTmice** [comment]
unfortunately not...

the way the adapter works is each Message checks whether it has been merged into the previous message Message.wasMergedIntoPrevious() and randers a NULL message.( 0xp high dummy.) but wasMergedIntoPrevious doesn't access a variable but checks with mergable again. meaning neither wasMergedIntoPrevious nor mergable are infuenced by getMergedBody()

**Comment by SamWhited** [comment]
@iNPUTmice Ah, I haven't seen `wasMergedIntoPrevious`; I'll have to go take a look at that. Thanks.

**Comment by SamWhited** [comment]
@iNPUTmice Added it to the list of stuff that shouldn't be mergable. Also retabbed it for readability (that was a long line...).

**Comment by SamWhited** [comment]
Discussion moved to pull request.
