### ISSUE TITLE
Option to disable (or preferrably opt-in) auto-download of HTTP/HTTPS images

### ISSUE THREAD

**Issue by mmn** [siacs/Conversations#867]
I'd like it if Conversations did not automatically download images linked in a chat. When fetching images remotely, not only do I access a third party webserver giving away IP address and such to the remote party as well as my ISP, but there have also been many cases of security holes in image libraries. Such vulnerabilities could quickly and easily be abused when discovered if peoples' XMPP clients gladly download anything anyone sends them.

I'd prefer that this was an opt-in preference, since the security and privacy implications of auto-downloading and parsing data from random sources can be pretty severe.

**Comment by iNPUTmice** [comment]
Oh sorry. That should have been the case since from the beginning. fixed in ef6e4c5dd5e601f6a3c9e4e755fb31537a8cd56e
