### ISSUE TITLE
every facebook / xmpp login seen as a new browser that needs to be approved / saved

### ISSUE THREAD

**Issue by heupink** [siacs/Conversations#875]
Recently discovered conversations, and absolutely love it. Works fantastic! Thanks!

I also use it with my facebook account, to avoid having to install the facebook messenger app. There is one issue with it: every xmpp login using conversations is detected as a 'new browser', that needs to be approved, and saved in the facebook website site. I'm not sure why.

I have configured conversations with xmpp resource 'conversations', so that should remain the same.

Anyone else seeing this? Is this some config issue on my side, or something that can be changed in conversations? Conversations could be a great replacement for the much dreaded facebook chat app if we can sort this out.

**Comment by plsng** [comment]
Accessing Facebook Chat through XMPP will no longer be possible at the end of april this year, so I'm not sure if this is even worth looking into.

**Comment by heupink** [comment]
Oh? I did not know that... That is extremely disappointing...

**Comment by jkufner** [comment]
In that case it is time to write a new XMPP transport for Facebook using
their Graph API. Any volunteers?

Btw, I have the same "problem" with Facebook, but I use jabber2jabber
transport to connect to it. Just disable that confirmation in settings,
you will still see a lot of sessions, but it won't be anoying anymore.
As long as you have strong password, you will be fine. Facebook is not
private anyway.

**Comment by heupink** [comment]
Thanks for the jabber2jabber tip, did not know that.

I have just read through the facebook page about the new api (https://developers.facebook.com/docs/apps/changelog?locale=nl_NL) and I don't see any mention of an alternative to chat.facebook.com. They only mention that chat.facebook.com/xmpp will no longer be available once v1.0 is phased out.

What a sad news.

**Comment by heupink** [comment]
Perhaps this is interesting: http://spectrum.im/

**Comment by jkufner** [comment]
Yes, Spectrum is good set of transports. I use it for a few years now.

**Comment by iNPUTmice** [comment]
Good opportunity to migrate you and your friends to proper XMPP servers and Conversations.
