### ISSUE TITLE
Compression?

### ISSUE THREAD

**Issue by singpolyma** [siacs/Conversations#878]
The current prosody mod_smacks does not work well with their mod_compression.  Obviously, this isn't anything to do with Conversations, but it alerted me to the fact that Conversations seems to be using XMPP stream compression even when doing TLS.  Why not just use TLS compression?

**Comment by iNPUTmice** [comment]
conversations doesn't use stream compression anymore (since 0.10)

**Comment by singpolyma** [comment]
Oh, ok.  I'm on an older version.  Thanks for the info!
