### ISSUE TITLE
Colored letter avatar not showing up

### ISSUE THREAD

**Issue by SamWhited** [siacs/Conversations#884]
Some odd behavior I noticed a moment ago (but haven't been able to reproduce since):

![screenshot](https://cloud.githubusercontent.com/assets/512573/5744495/418ab5c6-9bef-11e4-9bb5-e7063949d47d.png)

This behavior persists if I sign out of all accounts, make sure the foreground service is off, close Conversations and restart. Running Android 5.0 on a CyanogenMod nightly from a few days ago.

All my other conversatoins / MUC's seem to be working fine (and other Avatars in the ejabberd room). Just those few messages... I didn't have conversations open when they were received, so I wasn't doing anything special at the time.

**Comment by iNPUTmice** [comment]
I might be seeing ghosts but look at the distance between the dot and the H of Holger and the distance between the dot and the d of dragon. It looks like dragon is either using some sort of white space character in his nick or some other unrenderable character. And it looks like he changed his nick between the 12 mins ago message and the 4 mins ago message. (Thus the background color which is a hashsum over the entire nick) changes.
Not entirly sure how to proceed here. But this might be the cause of the bug.

Maybe you can find out by looking in the db what kind of character is being used here. Maybe we should trim the nick string before selecting the first char.

**Comment by SamWhited** [comment]
@iNPUTmice Good eye! The actual nick is `\ndragon`.

**Comment by SamWhited** [comment]
Quick fix (left the hash using the full name so two people with the same name but different numbers of spaces will still have a visual indication that they're not the same person):

```
diff --git a/src/main/java/eu/siacs/conversations/services/AvatarService.java b/src/main/java/eu/siacs/conversations/services/AvatarService.java
index 3ac4462..ccb3b3f 100644
--- a/src/main/java/eu/siacs/conversations/services/AvatarService.java
+++ b/src/main/java/eu/siacs/conversations/services/AvatarService.java
@@ -205,14 +205,15 @@ public class AvatarService {
        }
 
        public Bitmap get(final String name, final int size) {
-               final String KEY = key(name, size);
+               final String KEY = key(name.trim(), size);
                Bitmap bitmap = mXmppConnectionService.getBitmapCache().get(KEY);
                if (bitmap != null) {
                        return bitmap;
                }
                bitmap = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
                Canvas canvas = new Canvas(bitmap);
-               final String letter = name.isEmpty() ? "X" : name.substring(0,1);
+        final String trimmedName = name.trim();
+               final String letter = trimmedName.isEmpty() ? "X" : trimmedName.substring(0,1);
                final int color = UIHelper.getColorForName(name);
                drawTile(canvas, letter, color, 0, 0, size, size);
                mXmppConnectionService.getBitmapCache().put(KEY, bitmap);
```

**Comment by SamWhited** [comment]
Oops, pasted the wrong patch. Fixed.
