### ISSUE TITLE
Scan QR code to join a MUC opens 'new contact' dialog

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#887]
I wanted to join a muc with scanning a QR code and after scanning the code, the 'new contact' dialog opens. 
You can reproduce it as follows:
- touch the + on top right to start a new conversation
- touch conferences to start or join a conference
- the press menu button or the three vertical dots on top right and then scan QR code

**Comment by iNPUTmice** [comment]
did you generate that QR code yourself or did you scan one from the app?
conference uris need a ?join at the end for example `xmpp:conversations@conference.siacs.eu?join`

**Comment by kriztan** [comment]
I scaned a QR Code which contains only the address, without  `xmpp:` and `?join`.

**Comment by iNPUTmice** [comment]
the scanning of the bare jid is instead of the uri is merly a compatibilty way. If you want to create qr codes yourself please use correct uris.
