### ISSUE TITLE
OTR messages from contact using Adium have <FONT> tags

### ISSUE THREAD

**Issue by plsng** [siacs/Conversations#894]
For some reason, when I use OTR to chat with a contact using Adium (on OSX), their messages have `<FONT>` tags, like `<FONT>`message goes here`</FONT>`. These don't appear when chatting without OTR (I haven't tried with PGP yet). Is this a problem with Conversations or with Adium?

**Comment by SamWhited** [comment]
Related #23

**Comment by plsng** [comment]
I see, thanks!
