### ISSUE TITLE
invite contact improvement suggestion

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#903]
The way to invite a contact is a little bit puzzling I think, this should be simplified.
* Currently you have to open a contact, touch the options menu and chose 'invite contact', then a new dialog appears where I have to chose a contact. 
* Haven't I chosen somebody yet? Shall I chose a second contact or what's this dialog for?

I think this should work this way: you have to open a contact, touch the options menu and chose 'invite contact', then a new dialog appears where I have to chose an existing conference or the option to create a new conference. Currently I'm unsure if it's better to create a private conference with a random name or another options menu where I can chose between random name or with custom name.

**Comment by iNPUTmice** [comment]
Well the way this is meant to work is:
You are in a Conversation with Alice. You want to invite Bob into this Conversation. You open the Conversation with Alice. You select 'Invite Contact'. You choose Bob from the list.
The workflow doesn't change whether your original Conversations is a one-on-one Conversation or a group chat. 'Invite Contact' always invites a new contact to the currently open Conversation.

Maybe we can clear up the wording on this. But 'Invite new contact to this conversation' is a bit to long.

**Comment by kriztan** [comment]
OK, but nevertheless it should not be possible to choose the already chosen contact.
E.g. I'm in a conversation with Alice and select 'Invite Contact', Alice should not be in this list, because Alice is already chosen. Currently you can start a conference with only two members; you and the double chosen contact.

**Comment by iNPUTmice** [comment]
> OK, but nevertheless it should not be possible to choose the already chosen contact again.

this is fixed now
