### ISSUE TITLE
Personal account nickname issue！

### ISSUE THREAD

**Issue by chyk1991** [siacs/Conversations#907]
Why personal account can not be modified nickname it? Contacts for easy identification!

**Comment by chyk1991** [comment]
Yes!Allowed to change my account nickname,Contacts for easy identification

**Comment by akgprcom** [comment]
how ?

**Comment by Orhideous** [comment]
When adding a contact is possible to specify not only the name/surname, but a nickname. Google Contacts definitely has this feature (vCard version 3.0 and later, «NICKNAME» field).

I want to have an option that allow to switch displayed contact's name between "Name + Last Name" (as now) and «Nickname» (if it is available in vCard).

> I need a feature and I need it now!

How much does it cost to the realization of this feature?

**Comment by iNPUTmice** [comment]
merged into #1477
