### ISSUE TITLE
One side cannot verify in OTR, with SMP

### ISSUE THREAD

**Issue by viric** [siacs/Conversations#910]
A friend started an OTR verification with me, while I wasn't online. He used the SMP.

When I got online, at my side I was asked for the SMP, and I asnwered correctly. His side got verified, but at my side, it keeps on saying that he is not verified. This worked fine before in other cases, when SMP was requested while I was online. So I imagine being offline at request time breaks something.

If now I start SMP, he doesn't get the proposal, so it is never answered. I think SMP should work if restarted at any time by any side.

Using the latest F-Droid version as of today, 0.10.

**Comment by knoy** [comment]
This is not really how SMP was designed to be used, both parties should be online
