### ISSUE TITLE
Custom server:port, sticky notification&exit button, separate lists for different accounts

### ISSUE THREAD

**Issue by FullXD** [siacs/Conversations#911]
1. I'm not able to log into my account when connected to WiFi due to the fact that my ISP is blocking 5222/5223 ports and there is no ability to change the default port and server in the program.

2. Please add the exit button which will kill the process, and a constant notification with the status when the program runs with "keep service in foreground" option enabled.

3. Separate contact, chat, and conference lists for different accounts are really needed since I have some similar contacts in two accounts, same goes for conferences.

4. The program keeps reconnecting when the option "keep service in foreground" is enabled = status spamming in conferences.

Also, will the program support '/me' sentences someday in the future?

**Comment by SamWhited** [comment]
> I'm not able to log into my account when connected to WiFi due to the fact that my ISP is blocking 5222/5223 ports and there is no ability to change the default port and server in the program.

See #689, #583, and [the readme](https://github.com/siacs/Conversations#where-can-i-set-up-a-custom-hostname--port) (TL;DR — get the server administrator to add a DNS SRV record with whatever ports they support).

> Please add the exit button which will kill the process

See #458, #74, and #62 (TL;DR — it's not going to happen as this is against the android design principles; log out of all accounts and swipe the app away to kill the program).

**Comment by jkufner** [comment]
When ISP is blocking some ports, ask for refund for not providing
Internet service.

If it is some wierd free wifi, use VPN. You will have the same problem
with other services anyway.

**Comment by FullXD** [comment]
I don't get the point of sending everyone to the server administration instead of just implementing this function as, for example, jTalk developers do. In jTalk I can easily set the allports.jabber.ru server with port 80 and it will connect without any problems
And, anyway, it seems like the administration of jabber.ru never shows up online.

**Comment by SamWhited** [comment]
They've got registration disabled temporarily: https://jabber.at/en/node/119

**Comment by cultixate** [comment]
Does jabber.at support in-band registration?  I don't have handy access to Discovery Service at the time of post.

Can you register here?
https://account.jabber.at/

**Comment by SamWhited** [comment]
@FullXD Jabber.at has apparently added a captcha to their registration (which Conversations doesn't support). You'll have to register an account on the website, or with another client then you should be able to use it with Conversations.

**Comment by iNPUTmice** [comment]
> I don't get the point of sending everyone to the server administration instead of just implementing this function as, for example, jTalk developers do.

because Conversations has a different scope. If Conversations would simply be implementing every feature that Xabber or jTalk has it wouldn't be Conversations any more.
