### ISSUE TITLE
Show whether the account will use TLS with the server

### ISSUE THREAD

**Issue by viric** [siacs/Conversations#915]
One thing that surprised me is that I had no option to enable/disable TLS, neither anything shows if it is using it or not.

I imagine it uses TLS always and it is a requirement, but I don't see any statement about that, specially on screen.

It's common among "legacy xmpp clients" to expect non-tls by default, so I think that a clear statement on the account screen would be nice to have.

**Comment by iNPUTmice** [comment]
Conversations just won't connect to a server without encryption.
Some things should be taken for granted in the year 2015 thus I don't think an indication would be necessary because that indication would always say encrypted.

**Comment by viric** [comment]
By indication I mean a text line in the account creation screen, which says: "Conversations will only use a TLS connection" or similar. It's mainly for new users who don't know about this.

I also looked at the FAQ about it and I couldn't find an answer.

**Comment by jkufner** [comment]
I agree with @viric. Even if encryption is always enforced, it should be
stated on "Add account" screen. It is half empyt anyway, so friendly
note with securely-looking lock will not obstruct anything.
The only purpose of it is to make user feel better, nothing more.
