### ISSUE TITLE
How to connect to servers, port 443?

### ISSUE THREAD

**Issue by viric** [siacs/Conversations#917]
Under certain networks I cannot use the usual jabber port.

Then I want to use my profile (@jabber.ru) using the host ssl.jabber.ru:443, but I cannot tell Conversations to use it.

Using 0.10, from F-Droid.

**Comment by DrAzraelTod** [comment]
that's what keeps me from using conversations for my work-account
i can't change what port those admins at work use, so it would be nice to specify it here

i get why you kept the interface as simple as possible, but a checkbox/button for additional connection-settings wouldn't hurt that bad (i.e. connection host, auth, port, proxy, ...)

**Comment by iNPUTmice** [comment]
> Then I want to use my profile (@jabber.ru) using the host ssl.jabber.ru:443, but I cannot tell Conversations to use it.

proper jabber servers like jabber.at for example just annouce the 443 port in their SRV records as well. jabber.ccc.de for example announces port 80.

Same for your work problem @DrAzraelTod you can not convince them to use a different port. But maybe you can convince them to set up a proper SRV record.

**Comment by DrAzraelTod** [comment]
i know of SRV, doesn't help for servers where i have no influence to the config (like the one at work)

so i guess that's a "won't fix"-close then?
