### ISSUE TITLE
Photos get lost when smartphone isn't online

### ISSUE THREAD

**Issue by JannisHeinen** [siacs/Conversations#920]
Conversations is working fine ... when the smartphones are online. I don't use encryption. Text, photos and soundfiles can be send and correct received ...  hurrey

But when I
1. switch off one of the smartphones A
2. send text and Photos to it from an other smartphone B
3. and then switch on A again
then I only get the textmessages ... the photos get lost. I've tried this several times with various smartphones.

I am using:
- Prosody
- Samsung Galaxy S3mini and S4
- this App: Conversations :-)

Do I understand something wrong? Has every smartphone to be online all the time? This wouldn't be very userfriendly. Please help ... I want to convice my chief to use conversations x prosody for the whole company and I am shure such a restriction wouldn't be accepted.

Regards Jannis

**Comment by iNPUTmice** [comment]
Both clients will have to be online at the same time because file transfer for now is peer to peer. If one client is offline Conversations will automatically wait for the other device to come online and then send the image. (This is why you might the the status 'waiting...' underneath an image.

**Comment by JannisHeinen** [comment]
No,
Conversations don't wait and sends the photo when the other client gets online. The photo never arrives :-( .... a bug?
And No, 
there ist no status "waiting" under the image.

**Comment by JannisHeinen** [comment]
Does i make sense to write answers into closed issues? Or do they get lost and it's better to start a new issue?

**Comment by iNPUTmice** [comment]
what you are describing has probably been fixed with: 82a74fabc978d554384351aae13996059c827550

**Comment by JannisHeinen** [comment]
Thanx for the quick answer. 
I am using the version from Google Playstore. Is the version there very old or do you update conversations there quite often?
I couldn't find a changelog ... do you push patches every week or month into playstore? Or does it take much longer?

**Comment by iNPUTmice** [comment]
A new release is coming on on every first of a month. (Plus minus a few days)
We do hava a [Changelog](https://github.com/siacs/Conversations/blob/development/CHANGELOG.md) and a [release history](https://github.com/siacs/Conversations/releases)
