### ISSUE TITLE
Notifications in notification bar does not disappear

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#921]
In the latest beta, I've recognized, that the notifications in the notification bar sometimes doesn't disappear. 
It happens like this on my two devices:
Conversations is in the background, a message received. I pull down the notification area, click on the notification, conversations opens, but the notification icon doesn't disappear. I manually have to delete the notification. 
But this doesn't happen very often and currently I can't repuduce it. It happens round about once, perhaps twice a day.

**Comment by kruks23** [comment]
This problem happens in 0.10 too, only a few times I have reproduced it.

**Comment by iNPUTmice** [comment]
I might have a fix which is completely untested because I can not reproduce this.
Would you be able to test a branch with a proposed fix or can I send you a build with that fix. (beta2 + that fix)

Because I really wouldn't like to have that in mainline unless it has been confirmed working

**Comment by iNPUTmice** [comment]
there is a branch now that tries to fix that. https://github.com/siacs/Conversations/tree/issue921

**Comment by kriztan** [comment]
I think it solves the issue. I didn't have persistent notifications with this patch anymore.
