### ISSUE TITLE
avatar not publishid

### ISSUE THREAD

**Issue by babak3548** [siacs/Conversations#925]
I get this error when published other users a avatar
'fetching avatar for babakm@xxxx.xx failed (parsing error)'
class: XmppConnectionService => line 1721

**Comment by iNPUTmice** [comment]
What server software are you using?

**Comment by babak3548** [comment]
Openfire 3.9.3

**Comment by iNPUTmice** [comment]
This is in fact a bug in OpenFire that seems to be fixed (according to them) in 3.10
https://igniterealtime.org/issues/browse/OF-837

**Comment by babak3548** [comment]
best compatible server software with conversations?

**Comment by andersruneson** [comment]
I moved from openfire to prosody and can really recommend prosody. Another
good server is ejabberd, I think it depends on your requirements.

/Anders
