### ISSUE TITLE
Can i create a new chat app using your code?

### ISSUE THREAD

**Issue by sirajabbas** [siacs/Conversations#926]
Can i create a new chat app using your published code.I would like to know the procedure of setting xmpp connection and how app communicates through xmpp connection?

**Comment by Draghtnod** [comment]
Google the XMPP protocol, grab an XML Library you like and start coding. :grin:
If you really like to reuse this code, read the LICENSE file in the root folder.

**Comment by iNPUTmice** [comment]
spam #922
