### ISSUE TITLE
muc " xmpp conference " configuration

### ISSUE THREAD

**Issue by egproo** [siacs/Conversations#928]
when i join room on any jabber/xmpp server  whith affilate owner i can't show or edit room configuration

**Comment by iNPUTmice** [comment]
Is the a bug report towards version 1.0? or a feature request? I will assume the later. This has been implemented in 1.0

**Comment by egproo** [comment]
yes on version 1.0 only cany change  2 option ( make member only and make none-anonymous)

on other client find many options such as :: on iq code ::
""
<iq from="room@conference.example.org" to="egproo@example.org/QIP" id="qip_17" type="result">
<query xmlns="http://jabber.org/protocol/muc#owner">
<instructions>You need an x:data capable client to configure room</instructions>
<x xmlns="jabber:x:data" type="form">
<title>Configuration of room bot@conference.syriamoon.org</title>
<field type="hidden" var="FORM_TYPE">
<value>http://jabber.org/protocol/muc#roomconfig</value>
</field>
<field type="text-single" label="Room title" var="muc#roomconfig_roomname">
<value />
</field>
<field type="text-single" label="Room description" var="muc#roomconfig_roomdesc">
<value />
</field>
<field type="boolean" label="Make room persistent" var="muc#roomconfig_persistentroom">
<value>1</value>
</field>
<field type="boolean" label="Make room public searchable" var="muc#roomconfig_publicroom">
<value>1</value>
</field>
<field type="boolean" label="Make participants list public" var="public_list">
<value>1</value>
</field>
<field type="boolean" label="Make room password protected" var="muc#roomconfig_passwordprotectedroom">
<value>0</value>
</field>
<field type="text-private" label="Password" var="muc#roomconfig_roomsecret">
<value />
</field>
<field type="list-single" label="Maximum Number of Occupants" var="muc#roomconfig_maxusers">
<value>200</value>
<option label="5">
<value>5</value>
</option>
<option label="10">
<value>10</value>
</option>
<option label="20">
<value>20</value>
</option>
<option label="30">
<value>30</value>
</option>
<option label="50">
<value>50</value>
</option>
<option label="100">
<value>100</value>
</option>
<option label="200">
<value>200</value>
</option>
</field>
<field type="list-single" label="Present real Jabber IDs to" var="muc#roomconfig_whois">
<value>anyone</value>
<option label="moderators only">
<value>moderators</value>
</option>
<option label="anyone">
<value>anyone</value>
</option>
</field>
<field type="text-single" label="enter isida bot jid to protect room from flood or spam" var="muc#roomconfig_filter_jid">
<value>n-booot@syriamoon.org/MelOdyBoT</value>
</field>
<field type="boolean" label="Make room members-only" var="muc#roomconfig_membersonly">
<value>1</value>
</field>
<field type="boolean" label="Make room moderated" var="muc#roomconfig_moderatedroom">
<value>1</value>
</field>
<field type="boolean" label="Default users as participants" var="members_by_default">
<value>1</value>
</field>
<field type="boolean" label="Allow users to change the subject" var="muc#roomconfig_changesubject">
<value>0</value>
</field>
<field type="boolean" label="Allow users to send private messages" var="allow_private_messages">
<value>1</value>
</field>
<field type="list-single" label="Allow visitors to send private messages to" var="allow_private_messages_from_visitors">
<value>anyone</value>
<option label="nobody">
<value>nobody</value>
</option>
<option label="moderators only">
<value>moderators</value>
</option>
<option label="anyone">
<value>anyone</value>
</option>
</field>
<field type="boolean" label="Allow users to query other users" var="allow_query_users">
<value>0</value>
</field>
<field type="boolean" label="Allow users to send invites" var="muc#roomconfig_allowinvites">
<value>0</value>
</field>
<field type="boolean" label="Allow visitors to send status text in presence updates" var="muc#roomconfig_allowvisitorstatus">
<value>0</value>
</field>
<field type="boolean" label="Allow visitors to change nickname" var="muc#roomconfig_allowvisitornickchange">
<value>0</value>
</field>
<field type="boolean" label="Allow visitors to send voice requests" var="muc#roomconfig_allowvoicerequests">
<value>1</value>
</field>
<field type="text-single" label="Minimum interval between voice requests (in seconds)" var="muc#roomconfig_voicerequestmininterval">
<value>1800</value>
</field>
<field type="boolean" label="Make room CAPTCHA protected" var="captcha_protected">
<value>0</value>
</field>
<field type="jid-multi" label="Exclude Jabber IDs from CAPTCHA challenge" var="muc#roomconfig_captcha_whitelist" />
</x>
</query>
</iq>
""

**Comment by iNPUTmice** [comment]
that's for simplicity reasons. we had a [discussion](https://github.com/siacs/Conversations/issues/788) a while back on what conference options are really needed and should be exposed by Conversations.
If you thing you need more options feel free to make your point for a specific option in that thread.

**Comment by egproo** [comment]
@iNPUTmice 

muc#roomconfig_roomname
muc#roomconfig_roomdesc
muc#roomconfig_persistentroom
muc#roomconfig_publicroom
muc#roomconfig_passwordprotectedroom
muc#roomconfig_roomsecret
muc#roomconfig_maxusers
muc#roomconfig_whois
muc#roomconfig_filter_jid
muc#roomconfig_membersonly
muc#roomconfig_moderatedroom
members_by_default
muc#roomconfig_changesubject
allow_private_messages
allow_query_users
muc#roomconfig_allowinvites
muc#roomconfig_allowvisitorstatus
muc#roomconfig_allowvisitornickchange
muc#roomconfig_allowvoicerequests
muc#roomconfig_voicerequestmininterval
muc#roomconfig_captcha_whitelist
