### ISSUE TITLE
support smiles

### ISSUE THREAD

**Issue by egproo** [siacs/Conversations#929]
when write message can't send smile.

**Comment by SamWhited** [comment]
@egproo Conversations should handle emoticons fine. Are you getting an error? What is being displayed instead? Are you using a custom keyboard without an emoticon button (in which case there's nothing we can do about it)?

We're going to need more information to solve this if it's a bug.

**Comment by egproo** [comment]
I have Mobile Samsung :: keyboard  Basic :: I can choose from symbols, for example, D-: as it is written D-: without any significant impact .. well what I aspire to exist smiles .GIF Animations :: impact strongest and best
