### ISSUE TITLE
Resend friend request

### ISSUE THREAD

**Issue by viric** [siacs/Conversations#934]
Adding a new contact asks for sending friendship request, but there isn't a possibility to send it again, if the other side somehow unnoticed it.

I'm not sure the friend request is noticed in the other side either...

**Comment by iNPUTmice** [comment]
xmpp will store the request on the server side until it is either rejected or accepted. if it has been rejected you can go into contact details and request it again by checking the checkbox. but just resending it while it is pending won't change anything. afaik servers won't even deliver the request.
