### ISSUE TITLE
make new conferences non-anonymous as default

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#936]
I think it's better to make new conferences non-anonymous as default. I'm often asked, why we can not see any avatars in the conferences. So I have to explain, that the conference has to be set as non-anonymous in the conference details.
I think non-anonymous conferences are the more common way and it's a step forward to simplify the usability of Conversations. 
Expert users can make a conference anonymous in the conference settings if it's necessary.

**Comment by jkufner** [comment]
I agree. Usually people know each other anyway, so there is no reason to not tell them who is who. And if a  public chat room is required, it needs to be configured anyway.

**Comment by iNPUTmice** [comment]
Fixed in 841e718d6aaf335d5750170da181a6443c7c8048
