### ISSUE TITLE
conference muted info overlapped any other infos

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#939]
I'm a participant in some conferences which I have muted sometimes. The 'conference muted' info at the bottom overlapped any other info messages at the bottom e.g. 'conference not found' or 'Nickname already in use'.
I think this should be ordered by importance. For me, the mute info is the last important one, so this info should not stay in foreground.

**Comment by ChristianWendt** [comment]
I would prefer that particular information be be less visible as well, i *know* that i mute those conversations, i don't need a full line of screen for it all the time...

**Comment by kriztan** [comment]
Perhaps it is possible to show an icon instead of a text. This icon could be placed next to the contact/muc name under the time info in the chat list and in front of the contact/muc name in the chat window.
