### ISSUE TITLE
Add the possibility to send multiple files at once

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#943]
In Conversations there should be the possibility to send multiple files at once.
Depending on the connection quality it could be useful to create a kind of queue to prevent network overload.

**Comment by philipflohr** [comment]
The android file chooser intent does only support the selection of a single file.

It would be possible to use a library implementing this feature (like https://github.com/paulasiimwe/Android-Multiple-file-Selector-Dialog) but this would completely break the user experience and create a lot new problems (like folder handling)

I think the solution for multiple file sending is a classic zip or tar tool.

**Comment by kriztan** [comment]
implemented for images in 37d0827

**Comment by silberzwiebel** [comment]
I got the complaint from a Conversations user that this feature doesn't exist. I tried it on my own with two devices (Samsung tablet and Motorola smartphone) and indeed, I could not send more than one image choosing "menu > send image".
Then I found this issue. Either the mentioned fix is broken or I don't understand the workflow.
