### ISSUE TITLE
Missing KeySync functionnality

### ISSUE THREAD

**Issue by alphazo** [siacs/Conversations#946]
The KeySync functionnality found in ChatSecure is a clever idea for using the same secret key among multiple platform (desktop and mobile for example) so you can start an OTR discsussion on your phone and then switch to the desktop. Source code seems to be available so this would make a nice addition to Conversations.

**Comment by timosl** [comment]
This would only work for PGP and not OTR.

Also: Duplicate of #78

**Comment by alphazo** [comment]
Can you elaborate on why this won't work with OTR?  
keysync is used on ChatSecure exclusively for OTR https://guardianproject.info/apps/keysync/ and to allow transfer of OTR secret key between a desktop and a mobile device. I understand the limitation of PFS but not having to re-certify an new key between multiple appliances is a huge benefit.

**Comment by the-solipsist** [comment]
It won't work because you can't start an OTR discussion on your phone and switch to desktop.  However, KeySync allows you to start an OTR discussion on your phone, end it, kill your mobile app, and then switch to desktop and start a new OTR conversation there.

**Comment by alphazo** [comment]
@the-solipsist I fully agree with your analysis and it perfectly makes sense. Limitation looks fine to me. There is still some value to sync the OTR secret across a number of devices to simplify fingerprint verification and key exchange.

**Comment by the-solipsist** [comment]
@alphazo: Yes, I agree, there'd be a benefit and a very valid use case.  However, unless you can provide a pull request, the point seems moot since — as @timosl pointed out — the devs don't seem interested in it right now.

**Comment by SamWhited** [comment]
> There is still some value to sync the OTR secret across a number of devices to simplify fingerprint verification and key exchange.

Perhapse; there's also some value in just using a different key on every device (if it gets stolen, you can tell your contacts to stop using that specific key, instead of all of them, whereas if you use a single key, they can no longer safely communicate with any of your devices).

**Comment by the-solipsist** [comment]
@SamWhited That doesn't work with OTR. Given that many clients encrypt on the basis of partial JID (name@server.ltd) instead of full JID (name@server.ltd/resource), many times the server ends up delivering to the wrong device.  That means that you can't decrypt the messages on your phone, but your laptop isn't receiving the messages.  

Thus it's helpful to have the same key on multiple devices if you want to chat with the same person from multiple devices while using OTR.  If you don't do so, you might not be able to chat with them at all.

**Comment by eighthave** [comment]
The idea with keysync is to make it easy to use one key on every device, so even if the key gets compromised, it is easy to generate a new one and sync it to all of your devices.  Building up a whole list of verified keys takes time, so if someone uses the same key across devices, that means less time verifying keys, and more sessions that are fully verified.  That's the theory at least.

**Comment by iNPUTmice** [comment]
> Perhaps; there's also some value in just using a different key on every device (if it gets stolen, you can tell your contacts to stop using that specific key, instead of all of them, whereas if you use a single key, they can no longer safely communicate with any of your devices until you find a way to verify a new key out of band).

> Generally, syncing OTR keys is a security risk, and not worth the percieved "convenience" in my  opinion.

full ack. closing
