### ISSUE TITLE
MUC image sharing suggestion

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#947]
I've written a small app to share images to other apps. This app uploads an image to PHP webspace and shares a link to e.g. Conversations.
Yesterday, I tried to add a share image intent from other apps e.g. the galery but I didn't get it working (I'm not a programmer ;) )
I also want to improve the resampling, the current version is working, but I'm not satisfied, espacially for small files...

[Android App](https://github.com/kriztan/ImageHost-Android)
[PHP Server Side](https://github.com/kriztan/ImageHost-PHP)

Perhaps it is a dirty soloution to share images on an easy way in MUCs until it's working directly from Conversations.

**Comment by somebody873425** [comment]
I find this is very bad practice because this kills security and is not decentralised, which is what xmpp is all about.

**Comment by kriztan** [comment]
This should not be an invitation to use MY webspace. You could it on your own webspace... or you use dropbox or owncloud or whatever you want... This should only be a simple soloution to share images in MUCs on a relatively fast and easy way.
