### ISSUE TITLE
File transfer proxy configuration

### ISSUE THREAD

**Issue by Lateralus2** [siacs/Conversations#948]
Hello all,

First of all, to the dev team, thanks for the app Conversations, it is the best XMPP app I tried so far. 

I have registered a virtual server and I'm running Openfire xmpp server on it on CentOS. Basicly, Conversations is working really well. File transfer works great, but if a client goes offline, I can't get the file to go to the proxy server.

I think I put all the basic settings right in Openfire about the file transfer proxy. In my domains DNS records I have proxy.domain.com pointing with an A record to my servers IP. I have no SRV records pointing to 5222 or 5223 port.

In Openfire I added a rule:

xmpp.proxy.externalip to my servers IP.

Openfire is supporting XEP-0065. 

This is all I know about it, does anybody have any advise on how to get it to work? 

Thank you very much,

/Johan

**Comment by iNPUTmice** [comment]
That not what the file transfer proxy is for. Thats still only for peer to peer communication. it just solves firewall / NAT issues.
there are other open issues here that discuss how we can implement offline file transfer and muc file transfer in the future.

**Comment by Lateralus2** [comment]
ah, I understand, thanks for your clarification
