### ISSUE TITLE
Just wanted to say thanks!

### ISSUE THREAD

**Issue by Lateralus2** [siacs/Conversations#950]
Hey, maybe this is not the right section, but I don't no where else to post it, anyway, Thank you very much for this great great XMPP client! I'm working with Openfire, and since version 1.0 even starting group chats and inviting people is working. That did not work in the previous version, but now in 1.0 when I check " not anonymous" after it is checked I can add users.

Thanks and good luck developing!

Bye,
Johan

**Comment by Lateralus2** [comment]
by the way, what XMPP server software fits best for Conversations?

**Comment by SamWhited** [comment]
@Lateralus2 Try asking on the conference (`conversations@conference.siacs.eu`). This is an issue tracker, not a discussion forum, and you're likely to get a better answer there.

**Comment by Lateralus2** [comment]
oh sorry, how do I get on that conference? Where should I register? Is it a jabber chat?

**Comment by SamWhited** [comment]
Yes, you don't need to register; just join it from your client of choice (in Conversations you can click the new conversation button, go over to the "conferences" tab, and click the add button in the action bar).
