### ISSUE TITLE
Connection to Server:

### ISSUE THREAD

**Issue by BenJule** [siacs/Conversations#952]
I miss the Setting for adding Server. Its only possible to connect the Server with ID@Server.
Ex: My ID is nick@jabber.ff3l But Server is: jabber.myserver.de
Please fix :/

**Comment by andersruneson** [comment]
Please read
https://github.com/siacs/Conversations/#where-can-i-set-up-a-custom-hostname--port

**Comment by BenJule** [comment]
andersruneson; my Jabber iD is different as the Server Connection URL. In Conversations its only possible to connect the server via JabberID. I need a seperat Settings für Server URL!
