### ISSUE TITLE
No GPG after recovery

### ISSUE THREAD

**Issue by mase76** [siacs/Conversations#958]
Hi!
I use Titanium Backup to backup my apps. But after recovering Conversations, it seems not
to recognize Openkeychain. I am told, that the receipient did not offer his private key.
I have to clear the app data and readd my account. The everything works again. Very
annoying, because I lose my history.

**Comment by conrad-heimbold** [comment]
I always do my backup the manual way and **never** had problems. Titanium Backup is **not open-source**, so I can't give you **any** help concerning this app. 
## Creating the backup: 
```
adb root
adb shell
$ cd /data/data/eu.siacs.conversations/
$ tar -czf data.tar.gz databases  files shared_prefs app_KeyStore
$ exit
adb pull /data/data/eu.siacs.conversations/data.tar.gz $HOME/conversations-backup.tar.gz
```

## Applying the backup: 
```
adb root
adb shell -c mkdir -p /data/data/eu.siacs.conversations
adb push $HOME/conversations-backup.tar.gz /data/data/eu.siacs.conversations/
adb shell
$ cd /data/data/eu.siacs.conversations
$ tar -xzf data.tar.gz
$ exit
```

If your phone does not have root access for adb; you should also be able to do the mentioned steps from the recovery menu or during fastboot.  

If you are on Windows, replace $HOME/conversations-backup.tar.gz with a more suitable path.

**Comment by mase76** [comment]
I am without gservices for a very long time. I don't know, if this issue is still present. I am doing my backups with oandbackup. No problems so far.
Should this issue be closed?

**Comment by conrad-heimbold** [comment]
> Should this issue be closed? 

Yes, because the issue is not present anymore and even doesn't seem to be Conversations' fault.
