### ISSUE TITLE
Carbon copies with OTR and another client

### ISSUE THREAD

**Issue by abbradar** [siacs/Conversations#961]
In this scenario:

1. Server supports carbon copies
2. Pidgin, which does not support them, with OTR enabled and ongoing conversation
3. `Conversations` enabled

`Conversations` would receive undecipherable OTR messages for every message sent or received via Pidgin.

If I understand correctly, CCs are disabled by default unless one of the clients requests them. So, I suppose this can be workarounded by adding an option to disable carbon copies in `Conversations`.

**Comment by Natureshadow** [comment]
Another solution would obviously be using a decent client instead of Pidgin.

However, issues like that cannot be solved with the exsiting OTR standard.

**Comment by iNPUTmice** [comment]
search the issue tracker for pidgin and otr. that's a bug in pidgin. if you are logged in with another instance of conversations for example this doesn't happen

**Comment by abbradar** [comment]
If I understand correctly, that's not a bug in Pidgin but rather an unsupported feature; hence, this is not a matter of "fixing" Pidgin (it does nothing wrong), but of Conversations client maintaining compatibility. For example, in Gajim you can disable Message Carbons in the Advanced Configuration Editor. I don't have a good expertise on XMPP, though, please correct me if I'm wrong.

The ideal solution, of course, would be clients with OTR (and servers in general) supporting http://xmpp.org/extensions/inbox/message-processing-hints.html .

**Comment by SamWhited** [comment]
@abbradar The carbon's patch for Pidgin isn't even in the repo; it's not even alpha code yet. Why should we try to be backwards compatible with something that's not even finished yet (and should just add message hints before it's released, if it ever is which isn't that likely knowing the Pidgin devs).

This is *not* something we should be "backwards compatible" on (that would require some ridiculous hackery that's likely to just break other things), this is something that should be fixed in Pidgin if and when the carbons patch is ever merged. You using unfinished code isn't something we need to work around.

**Comment by abbradar** [comment]
If this feature would require hackery, then we better to wait till
support in other clients -- sorry for bugging, then! I haven't meant
that you should implement Message Hints, too (that was just me dreaming
about ideal state of things, and for that to become true first the
standard needs to be approved, major servers get support etc. etc.) --
sorry for misunderstanding.

**Comment by abbradar** [comment]
P.S. Strangely, I don't see your reply on Github, only on mail. Do you
have any issues?

**Comment by SamWhited** [comment]
@abbradar huh, weird, I must have deleted it somehow... oh well, it's documented in your reply. Sorry about that.

**Comment by abbradar** [comment]
That's true, too. Thanks for the conversation! (And for `Conversations`, too -- a breath of fresh air for XMPP on Android ^_^)

**Comment by iNPUTmice** [comment]
Messages hints are set by the sending client. Conversations does that. For this reason OTR messages sent by Conversations wont show up in your other clients.
