### ISSUE TITLE
Intermittent "Incompatible Server"

### ISSUE THREAD

**Issue by knoy** [siacs/Conversations#963]
Sometimes, after having been connected for a long period of time the application randomly refuses to communicate with our server it otherwise has no problem with. This seems to be after long periods of inactivity and late at night. 

Temporarily disabling and re-enabling the account fixes the issue. Perhaps an automatic attempt to re-connect (similar to a timeout) would be able to fix this?

**Comment by iNPUTmice** [comment]
Is this for Conversations 1.0 or for your fork (which is based on 0.9 or 0.10?)
If this is not against 1.0 try applying: 3a52f318248134a49dda7d6704ba43bc91784318

**Comment by knoy** [comment]
Awesome, will implement this and report back

**Comment by knoy** [comment]
This fixed it thanks
