### ISSUE TITLE
send image via http link --> error 404 file not found issue

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#964]
In MUCs I often share images with my contacts. If an image was deleted, conversations should display an error "file not found" or "file deleted" on status code 404. But the context menu should offer the option to retry downloading the image again.
Currently Conversations says "checking file" and returns to the link, but nothing happens. The user doesn't know, why no image was downloaded.

**Comment by iNPUTmice** [comment]
Fixed in 0f5c87ca1f3dc25e0f76ff1fa4308326d1d287f0
