### ISSUE TITLE
Allow audio playback like a phone call

### ISSUE THREAD

**Issue by amo13** [siacs/Conversations#965]
A nice feature even whatsapp does not have would be to allow the playback of audio messages as if it was a normal phone call. Else you always have the problem that people around you can hear it and you don't always carry around earplugs.

**Comment by jkufner** [comment]
Osmand (maps & navigation) has an option for choosing how to play
navigation commands. Whether like music or like a phone call. It also
allows you to send sound to handsfree which does not support music
playback (hi quality A2DP profile).

**Comment by amo13** [comment]
Well yes this sounds like a nice feature. Maybe the same can be done for recording audio?

**Comment by iNPUTmice** [comment]
Conversations doesn't play the audio itself but relies on third party audio players. So this is something the audio player should do.
