### ISSUE TITLE
Friend status on contact screen

### ISSUE THREAD

**Issue by dionnejkelly** [siacs/Conversations#966]
Hi, Is it possible to have the status of each user on the contact tab ?
The status could be anything ("Am on top of the world !") and then an icon to show if the user is offline or online.

**Comment by jkufner** [comment]
I really like how Xabber and Skype show status in contact details. Not
in the app itself, but in the phone's address book.

**Comment by mistersixt** [comment]
I am missing the online status, too, one always needs to actually start a conversation to see whether the counterpart is online or not (this colored arrow thing at the bottom right).

That is really the only part I am missing with conversations, the rest is nearly perfect in the meantime (so thanks for this nice XMPP client!!!).

**Comment by iNPUTmice** [comment]
@mistersixt I believe this issue is about the status message. If you want to see the availibitly beforhand you might want to turn on 'dynamic tags' in the settings.

**Comment by mistersixt** [comment]
Dude, you are damn right ... sorry for that, I somewhat missed that feature ;-) ... thanks a lot for the speedy response!

**Comment by TameOfGroans** [comment]
If status I would like to see presence indicated in android contacts. Is Xabber acting as a Contacts Provider?  I would prefer Conversations take this to the next level of integration

**Comment by sniperle** [comment]
It would be great to have the status (on/off) of each person directly shown in the conversations list not just "only" in the contacts list (when dynamics tags is enabled).  +1 from me

**Comment by Natureshadow** [comment]
Additionally, I'd like to have an optional filter for only online contacts in the new conversation view.

**Comment by iNPUTmice** [comment]
Showing the status message has been implemented some time ago.
