### ISSUE TITLE
Sending of files (New Features)

### ISSUE THREAD

**Issue by dionnejkelly** [siacs/Conversations#967]
Conversations going to support sending of other file format anytime soon ?
What about typing status ? A notification when a user is typing.
I like these lil features - make the app feel up to date and feature rich.

**Comment by iNPUTmice** [comment]
> Conversations going to support sending of other file format anytime soon ?

what do you mean by that? Conversations can send any type of file already.

**Comment by dionnejkelly** [comment]
Oh, sorry for that question. Havent use the new version yet. I compile it last year and use it, am having problem building it again so i havent seen all that it can do as yet.
Is it possible to post a .apk in the dev folder ?

**Comment by iNPUTmice** [comment]
There is a build version available via the playstore
