### ISSUE TITLE
provide an xmpp intent (new feature)

### ISSUE THREAD

**Issue by hgruber** [siacs/Conversations#969]
it would be nice to have an xmpp intent. This would allow sending xmpp messages with tasker or llama.

**Comment by SamWhited** [comment]
This is partially done by #895, but it would have to be exposed in some way to outside apps (eg. a permission). Generally speaking, while I can think of a few uses for this, I don't really see this as being a "good fit" for Conversations.

Personally, I think this would create a lot of problems for very little benefit.

**Comment by jkufner** [comment]
IPC via XMPP can be very powerful. I can imagine two people sharing
their location in real-time using Osmand, which could send user's
location and visualize received location from other users.

Another use can be playing chess or similar games. In combination with
MUC results it can be very interesting (done that, it works nicely).

Simple API could open very wide area of oportunities. And such
interaction is very Android-way. Lets provide communication channel for
other apps and see what happens.

**Comment by TameOfGroans** [comment]
Is such not offered via the MAXS Project? 

http://projectmaxs.org

https://f-droid.org/repository/browse/?fdid=org.projectmaxs.main

**Comment by iNPUTmice** [comment]
Conversations might not be the right place to do this. Conversations is a Chat App and not an XMPP App.
I agree XMPP can be or is very powerfull. But this is out of scope for Conversations. If you want your App to communicate with a Server its pretty easy to just use smack or something.
