### ISSUE TITLE
Images or files don't show 'read up to this point' image

### ISSUE THREAD

**Issue by knoy** [siacs/Conversations#974]
If you send an image, afterwards it won't show the avatar on the left indicating the recipient has viewed it

**Comment by iNPUTmice** [comment]
This is not supported by the XEP. The XEP only works on messages.

**Comment by iNPUTmice** [comment]
For the record if someone else is interested in this: https://github.com/knoy/Chat/commit/74958f5700c9f3892a965f33975121ccb8e90095

(Just a hack though that only works if both sides use the same client)
