### ISSUE TITLE
Conversations consume a lot to get started 

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#977]
With these last versions, it needs more and more time to get started, it even get crashed (without apparently giving me the option to send you the chrash report) but if I'd select "Close" instead of "wait" I'd couldn't use it.
In my phone it consumes circa 30mb (2 accounts).
I know my phone it very bad handling RAM memory, but if you could do anything I would be very appreciated.

**Comment by iNPUTmice** [comment]
The start up time should be little faster now with 1.0.3

**Comment by moshpirit** [comment]
Perfect, thank you!!! :-)

**Comment by iNPUTmice** [comment]
I just made a second commit that loads the avatars async as well. In combination this should get rid of all lag.
