### ISSUE TITLE
Server Not Found

### ISSUE THREAD

**Issue by MohitAnand786** [siacs/Conversations#982]
i am facing a problem with siacs conversation i.e Server Not Found while i try to connect with certain email like "manreet@jabber.com".

Please revert please.

**Comment by iNPUTmice** [comment]
Looks like the Server is down. I can't even ping it. Neither the actual jabber server at denjab2.jabber.com nor jabber.com

**Comment by MohitAnand786** [comment]
So Brother is this server related issues?

**Comment by iNPUTmice** [comment]
Yes

**Comment by MohitAnand786** [comment]
so can you please tell when it will get fine?

**Comment by iNPUTmice** [comment]
Conversations is an XMPP client capable of connection to XMPP servers. The XMPP server you choose (jabber.com) doesn't seem to exist (at the moment?)
I can not tell you if and when jabber.com will be reachable again. If you were trying to create a new account though you can try others servers like jabber.at for example.

**Comment by MohitAnand786** [comment]
But i am not getting an exact url of jabber site.

**Comment by jkufner** [comment]
Sorry, nothing to do at this end of line.
