### ISSUE TITLE
User status not managed

### ISSUE THREAD

**Issue by tukoman** [siacs/Conversations#984]
Hi, 

First of all congratulations for your great job. I like it.

I noticed that Conversations does not set the status to 'away' when I lock the phone. In my opinion no sense show the contact status if the status is always 'online'. That's why I think that the user status should be set to 'away' when we lock the phone and set to 'online' again when we unlock the phone.

Thanks a lot and great job.

**Comment by SamWhited** [comment]
For more information, see [the readme](https://github.com/siacs/Conversations#where-can-i-see-the-status-of-my-contacts-how-can-i-set-a-status-or-priority), or search through [the issues](https://github.com/siacs/Conversations/issues?q=is%3Aissue+presence).
