### ISSUE TITLE
Avatars: transparent pixels displayed as black

### ISSUE THREAD

**Issue by JKingweb** [siacs/Conversations#987]
I am using this image as my avatar:

![](http://jkingweb.ca/me.png)

However, Conversations displays the background as black rather than transparent, which makes it awfully hard to see.  I realize this is both minor and fairly unusual as a requirement (not to mention often wrong in all kinds of software), but it annoys me every time I see it, which is often.  :-/

**Comment by iNPUTmice** [comment]
What Android version are you on? because this seems to be working for me. And I quick google search revealed that Android has support for transparent webp images since 4.2

**Comment by JKingweb** [comment]
I'm running 4.4.1 on a Galaxy S5.  I suppose it's possible Samsung broke something.  When I first select the evatar for publishing it's shown on a grey background; once it's actually published it's black, though.  Could the server be manipulating it incorrectly (is it allowed/supposed to manipulate it?)?  I'm running Prosody 0.9.7.

**Comment by iNPUTmice** [comment]
does c283fec0d1af6d4dc8c6b794a065fa1029b6d178 fixes this for you?

**Comment by JKingweb** [comment]
I don't have any experience building software for Android, so I'm afraid I can't tell you.  :(

**Comment by moshpirit** [comment]
Same problem here. Android 4.3.

**Comment by JKingweb** [comment]
Conversations 1.3.1 does fix this for me, however.  I've upgraded to Android 5.0 since reporting the bug, and I did have to re-publish my avatar for it to display properly.

**Comment by moshpirit** [comment]
I changed my avatar using Conversations 1.3.1 and it shows a black background

**Comment by moshpirit** [comment]
At least, it could use the same colour than the background :\

**Comment by Natureshadow** [comment]
I have seen some proprietary ROMs convert images to image/jpeg soewhere in between intents wehen passign them to an application requesting them. JPEG does not have transparency.

**Comment by moshpirit** [comment]
Please, don't close it, it's still not fixed in android 4.x

**Comment by OlafLostViking** [comment]
Still valid on Android 5.1.1 (CyanogenOS 12.1.1) with Conversations 1.9.4 when uploading PNG based avatars.

**Comment by JKingweb** [comment]
Also occurs for me once again on CyanogenMod 13 (Android 6) on the same Galaxy S5 using Conversations 1.9.4.the cropper shows a checkered background, but the resulting image has a black background.
