### ISSUE TITLE
Expose additional ressources for theming

### ISSUE THREAD

**Issue by flocke** [siacs/Conversations#990]
I'm currently working on theming Conversations using [RRO](https://github.com/deadman96385/RRO-WIKI/wiki/About-RRO), which basically overwrites files from Conversations res/ folder on runtime.
I managed to change most of the colors by adapting colors.xml to my needs as shown here:

![screenshot_2015-02-17-10-45-56](https://cloud.githubusercontent.com/assets/76665/6226141/a363b05a-b692-11e4-9dae-c7e4c5ad088a.png)

The only problems I had so far are that some colors are not affected by those changes, like e.g. the whole settings:

![screenshot_2015-02-17-10-46-19](https://cloud.githubusercontent.com/assets/76665/6226236/5efd6d92-b693-11e4-9056-8a59f9588b3b.png)

Would it be possible to make the settings page use the colors from the colors.xml file, like the other parts of the application?

There are some other parts that are not themable with the current ressources, but those are minor and I just wanted to ask for now if improving the ability to theme Conversations is something the developers would be interested in.
If yes I could look into this a little deeper and maybe even try to write a patch myself, but I have no experience in Android coding whatsoever.

**Comment by iNPUTmice** [comment]
> Would it be possible to make the settings page use the colors from the colors.xml file, like the other parts of the application?

I'm not sure but I don't think so. You would have to switch to a dark theme to do this.

> if improving the ability to theme Conversations is something the developers would be interested in

yes. I don't have the time right now to do this myself. But I'd be happy to merge this.
